### ISSUE TITLE
Build Error in validate_noiseprofiles_json

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7312] opened 2020-12-14 01:53 UTC
Current master WSL Ubuntu build errors (clean builds by removing contents of build folder). Probably related to noise profiles added recently.

```
...
..
.

0.000367349297779409, 0.000142437567744199, 0.000285612821654188], 'b': [3.91931856021865e-07, 6.40422964348142e-07, 3.19798274358322e-07]}, {'name': 'M1 iso 12800', 'iso': 12800, 'a': [0.000646091953940536, 0.000249611704546539, 0.000503382676952126], 'b': [3.21639519553332e-07, 4.12083597021623e-07, 2.47763269471236e-07]}, {'name': 'M1 iso 25600', 'iso': 25600, 'a': [0.0015156519054789, 0.000574054729750559, 0.00117894088012683], 'b': [8.15014471836272e-07, 6.89013051723195e-07, 6.80076388708215e-07]}]}]}] is too long
[  7%] Test-compiling OpenCL program colorspace.cl
Merging translations into /home/mchhil/darktable/build/share/darktable/darktable.desktop.
Merging translations into /home/mchhil/darktable/build/bin/../share/appdata/darktable.appdata.xml.
[  7%] Built target opencl-program-rgbcurve.cl
[  7%] Built target opencl-program-nlmeans.cl
[  7%] Built target opencl-program-common.h
[  7%] Built target generate_authors_h
make[2]: *** [share/darktable/CMakeFiles/validate_noiseprofiles_json.dir/build.make:59: share/darktable/CMakeFiles/validate_noiseprofiles_json] Error 1
make[1]: *** [CMakeFiles/Makefile2:7005: share/darktable/CMakeFiles/validate_noiseprofiles_json.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  7%] Checking validity of darktable.desktop
CREATED /home/mchhil/darktable/build/bin/../share/appdata/darktable.appdata.xml
Scanning dependencies of target opencl-program-rgblevels.cl
Scanning dependencies of target opencl-program-bloom.cl
Scanning dependencies of target opencl-program-colorreconstruction.cl
Scanning dependencies of target opencl-program-dwt.cl
[  7%] Built target darktable.appdata_file
[  7%] Built target validate_darktable_desktop
[  7%] Test-compiling OpenCL program bloom.cl
[  7%] Test-compiling OpenCL program rgblevels.cl
[  7%] Test-compiling OpenCL program colorreconstruction.cl
[  7%] Test-compiling OpenCL program dwt.cl
[  7%] Built target opencl-program-colorspace.cl
[  7%] Built target opencl-program-rgblevels.cl
[  7%] Built target opencl-program-bloom.cl
[  7%] Built target opencl-program-colorreconstruction.cl
[  7%] Built target opencl-program-dwt.cl
make: *** [Makefile:152: all] Error 2
```

**Comment by johnny-bit** [comment] 2020-12-14 06:53
Interesting... I thought CI caught json validation. can you share whole build output as well as jsonschema version?

**Comment by chhil** [comment] 2020-12-14 07:24
when I run **`.\build.sh &> build_out.txt`** I get the following output. I did not do a clean build (did not remove build directory contents as it does not matter).


[build_out.txt](https://github.com/darktable-org/darktable/files/5687087/build_out.txt)


The schema file....
[noiseprofiles.schema.txt](https://github.com/darktable-org/darktable/files/5687095/noiseprofiles.schema.txt)

**Comment by jade-nl** [comment] 2020-12-14 07:25
Came here to report this one, so: Confirmed.

Here's my full build log.
[dt.build.2020.12.14.0814.log](https://github.com/darktable-org/darktable/files/5687092/dt.build.2020.12.14.0814.log)

python-jsonschema -> 2.6.0-4 (Python 2.7)

**Platform**
* darktable        : 3.3.0+2085 gab91bf320
* OpenCL installed : Yes (nvidia-opencl-common 450.80.02-1)
* OpenCL activated : Yes
* Graphics card    : GeForce RTX 2060 SUPER 7979 MiB
* Graphics driver  : nvidia (450.80.02)
* OS               : Linux (kernel 5.8.10-1)
* Distro           : Debian Buster (rel. 10.7)
* Xorg             : 7.7+19

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by johnny-bit** [comment] 2020-12-14 07:34
You are correct - I haven't noticed that CI does catch this. This is caused by #7310 being merged. Working on simple fix.

**Closed** 2020-12-14 07:46 UTC

**Comment by jade-nl** [comment] 2020-12-14 07:53
#7313 was just merged, but this issue isn't fixed.

**Comment by chhil** [comment] 2020-12-14 07:55
I just ran the json against a schema on an online validator


```Array item count 14 exceeds maximum count of 13.```

So the maxlength probably need to change somewhere.

**Comment by johnny-bit** [comment] 2020-12-14 07:58
Yeah, sorry about forgetting that one...

pon., 14 gru 2020, 08:55 użytkownik Murtuza Chhil <notifications@github.com>
napisał:

**Comment by chhil** [comment] 2020-12-14 08:03
Schema change max and min item to 14.
![image](https://user-images.githubusercontent.com/1119439/102055455-e78b5880-3e10-11eb-9fbd-dd14ea347ace.png)
