### ISSUE TITLE
Demosaic/Conversion -> Messages in GUI + Teminal errors (development)

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#7080] opened 2020-11-26 16:57 UTC
**Describe the bug**

After discarding the histories of all my test files and while it was reassessing all the files the following message showed up in the GUI (lighttable, multiple times):

> history problem detected
> please report via the issue tracker
> include the xmp file

The following was seen on the terminal:

> blockdenom vanishes 
> [dt_dev_pixelpipe_synch] found enabled demosaic in history for non-raw `grainy.II.negative.11.dng`, id: 426
> [dt_ioppr_transform_image_colorspace_cl] invalid conversion from 0 to 2
> [_transform_matrix] invalid conversion from 0 to 2
> [dt_ioppr_transform_image_colorspace] invalid conversion from 0 to 2
> [dt_dev_pixelpipe_synch] found enabled demosaic in history for non-raw `grainy.reflections.dng`, id: 1173
> [_transform_matrix] invalid conversion from 0 to 2
> [dt_ioppr_transform_image_colorspace] invalid conversion from 0 to 2
> blockdenom vanishes 
> [dt_dev_pixelpipe_synch] found enabled demosaic in history for non-raw `villa.bluthner.canon.exr`, id: 1199
> numblox = 0

**To Reproduce**
1. Start darktable from a terminal
2. Select a fim roll/folder that contains exr and/or dng files
3. Select these dng/exr files and discard history
4. See GUI message while darktable is reassessing
5. See errors in terminal

**Expected behavior**
No errors and conversion/demosaicing is done correctly for all file types.

These are clean xmp's to start with, nothing was added/changed by the me. I made sure by removing all the xmps in that specific directory.

**Platform**
* darktable        : 3.3.0+1809 g0415cd920
* OpenCL installed : Yes (nvidia-opencl-common 450.80.02-1)
* OpenCL activated : Yes
* Graphics card    : GeForce RTX 2060 SUPER 7979 MiB
* Graphics driver  : nvidia (450.80.02)
* OS               : Linux (kernel 5.8.10-1)
* Distro           : Debian Buster (rel. 10.6)

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Asked for info**

[grainy.II.negative.11.dng.xmp.txt](https://github.com/darktable-org/darktable/files/5604222/grainy.II.negative.11.dng.xmp.txt)

[grainy.reflections.dng.xmp.txt](https://github.com/darktable-org/darktable/files/5604219/grainy.reflections.dng.xmp.txt)

[villa.bluthner.canon.exr.xmp.txt](https://github.com/darktable-org/darktable/files/5604215/villa.bluthner.canon.exr.xmp.txt)

I'm going to refrain from uploading the RAWs for the moment (26+26+55 Mb ). I'm willing to upload if needed, though.

**Comment by aurelienpierre** [comment] 2020-11-28 21:08
I just merged a PR adding debug strings. Could you compile master now, start `darktable -d params` and give the output here ?

**Comment by jade-nl** [comment] 2020-11-28 21:25
Pulled, recompiled and run.

Here's the info you asked for: [dt.params.out.txt](https://github.com/darktable-org/darktable/files/5611258/dt.params.out.txt)

Ran and discard history on 3 dng files (first part 16.yxyz/17.xyz) and one exr file (31.xyz).

**Comment by aurelienpierre** [comment] 2020-11-28 22:15
So, 
```17.013503 [history] successfully loaded module rawprepare from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 1:	version ok	params ok
17.013511 [history] successfully loaded module colorin from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 6:	version ok	params ok
17.013516 [history] successfully loaded module colorout from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 5:	version ok	params ok
17.013522 [history] successfully loaded module gamma from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 1:	version ok	params ok
17.013525 [history] successfully loaded module temperature from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 3:	version ok	params ok
17.013529 [history] successfully loaded module highlights from history
			blendop v. 0:	version WRONG	params WRONG
			params v. 2:	version ok	params ok
```
shows that your mask parameters are wrong, therefore your history is corrupted. It can be because of your presets or because bad defaults.

Can you please share the files ?

**Comment by aurelienpierre** [comment] 2020-11-28 23:39
Ok, I have been able to reproduce some of the errors you have.

It seems film scans produced with Viewscan DNG are detected by darktable as RAW files, supporting standard input matrices and needing demosaicing. This is wrong. Other DNG files I have tested (for example, produced by cameras or by Adobe DNG Converter) have proper embedded matrices and work as expected. But because Viewscan DNG don't embed their profiles, they pass through the ICC checks of darktable.

Still not sure what a good solution would be. Viewscan makes stupid things in the first place, here. Not sure why their output poses as RAW since it comes out of a non-mosaiced scanner.

**Comment by parafin** [comment] 2020-11-29 07:01
DNG could be non-mosaiced, but in any case some color profile is required by specification. Where can I find an example of such file?

**Comment by jade-nl** [comment] 2020-11-29 07:45
@aurelienpierre : 

I know that darktable isn't able to handle dng files all that well, but this issue isn't dng specific, I also see this when discarding exr history stacks.

This specific one was created from [this \[pixls\]](https://discuss.pixls.us/t/villa-bluthner-built-in-1858/19521) cr2 file via:  cr2 -> darktable -> exr -> GIMP -> exr -> darktable

[villa.bluthner.canon.exr](https://www.fromsmash.com/opu5eglG8t-dt) (55Mb)
[villa.bluthner.canon.exr.xmp.txt](https://github.com/darktable-org/darktable/files/5611814/villa.bluthner.canon.exr.xmp.txt)

The issue isn't limited to this one exr, all exr files I tested show the *[...] found enabled demosaic in history for non-raw [...]* message.

PS: the *... invalid conversion from ...* part is fixed.

**Comment by jdneumeyer77** [comment] 2020-11-29 16:48
I'm experiencing the same issue even with the most recent build. Except instead of DNGs I'm working with linear tifs produced with Sequator (stacking program for astrophotography). It's generally worked well up until a couple days ago. Not sure which input color space to choose (usually lin Rec2020), but that's a different issue.

The following happens regardless if I discard history or not. The UI still insists I have a corrupted XMP history and the console reports:

`[_transform_matrix] invalid conversion from 2 to 0
[dt_ioppr_transform_image_colorspace] invalid conversion from 2 to 0
`
and this:
`[dt_dev_pixelpipe_synch] found enabled demosaic in history for non-raw `independence_pass_16mm_linear_autobrightness_filtered.tif`, id: 1374
`

**Comment by aurelienpierre** [comment] 2020-11-29 16:56
@jade-nl well, your XMP file shows demosaic in history, while the file is non-mosaiced, so the message is consistent. The question is why does dt treat any exr, dng or tiff as raw ?

**Comment by aurelienpierre** [comment] 2020-11-29 17:00
@jdneumeyer77 I suppose the faulty TIFF are 32 bits float ?

**Comment by parafin** [comment] 2020-11-29 17:06
Raw is ambiguous term. Just because data is not mosaiced doesn't mean it's not "raw". Raw means unprocessed, and if acquisition device doesn't have bayer filter (monochrome camera, scanner) then raw won't be mosaiced, but still be raw (e.g. linear, with black level and so on).
I'm not sure what is the current logic in dt, but just checking for raw flag isn't enough to decide that demosaicing is needed it seems. But I guess it can just default to pass-through mode for these types of files.

**Comment by jdneumeyer77** [comment] 2020-11-29 17:08
@aurelienpierre: sadly my faulty TIFFs are only 16 bits. Wish Sequator would produce 32 bit float TIFF files and would run on Linux natively.

**Comment by jade-nl** [comment] 2020-11-29 17:28
> The question is why does dt treat any exr, dng or tiff as raw ?

Yeah, that is the issue at hand.

It does not matter if these are unedited or previously edited files.

I can only add to all the above that these messages did not show up before. I run my development version always from a terminal and I haven't seen them. Can't pin it down, but I'm all but sure that this is something that started in the last month (if that long) or so.

I'm excluding tiff files from all this btw, those are rather strange and have been creating messages in the terminal for as long as I have been using darktable (there are multiple open/closed issues about that).

So the exp and dng are the ones that started showing error/warning/informational(?) messages.

**Comment by aurelienpierre** [comment] 2020-11-29 17:59
> Raw is ambiguous term. Just because data is not mosaiced doesn't mean it's not "raw". Raw means unprocessed, and if acquisition device doesn't have bayer filter (monochrome camera, scanner) then raw won't be mosaiced, but still be raw (e.g. linear, with black level and so on).
> I'm not sure what is the current logic in dt, but just checking for raw flag isn't enough to decide that demosaicing is needed it seems. But I guess it can just default to pass-through mode for these types of files.

It seems that Viewscan produces DNG when user asks for "raw" output (that's the label in their UI). So far, all DNG seem to be detected as RAW, and default parameters are initialised with that. Later on, the demosaicing module realizes there is no CFA and bypasses the demosaicing.

> I can only add to all the above that these messages did not show up before. I run my development version always from a terminal and I haven't seen them. Can't pin it down, but I'm all but sure that this is something that started in the last month (if that long) or so.

The messages have been added in ea7c4d7 4 days ago. But still, they are only log messages, not the real culprit.

**Closed** 2020-11-29 18:15 UTC

**Comment by jade-nl** [comment] 2020-11-29 18:40
Messages are gone.

Did you fix it or just mute the messages?

**Comment by aurelienpierre** [comment] 2020-11-29 19:32
> Did you fix it or just mute the messages? :-)

No, it's a real fix. The EXR and AVIF files were loaded without explicitely unflagging them as RAW. It's really just a coding mistake in the I/O lib.
