### ISSUE TITLE
Leica M10 Monochrom DNG files have some color.

### ISSUE THREAD

**Issue by Jedek-Selera** [darktable-org/darktable#14034] opened 2023-03-26 21:43 UTC
Hi Developers,

I uploaded two RAW DNG files from Leica M10 Monochrom to https://raw.pixls.us/. I'm using Darktable 4.2.1 compiled from source on Slackware 15. Imported raw files have some color cast.  Also I was able to reproduce this with fresh install of Darktable 4.2.1 on Windows 10. Here is screenshot of the dng file opened in Darktable. 
https://github.com/Jedek-Selera/screenshoots/blob/main/Screenshot_2023-03-26_12-25-48.jpg
I also notice that input profile for dng file is linear Rec709 RGB, I'm not sure if that matters or not ? 
Next I installed RawTherapee 5.9 and it does not have the same problem.

**Comment by jenshannoschwalm** [comment] 2023-03-27 05:30
That is very likely caused by an active "color calibration" module, it's on by default. You probably want to define a preset for monochromes that disables it.

**Comment by jenshannoschwalm** [comment] 2023-03-27 11:10
> I thought we had mono detection and dedicated workflow?

For some modules, yes. We might want "color calibration" for some tinting so i didn't disable it, For true monochromes at least the default should be "off".

**Comment by jenshannoschwalm** [comment] 2023-03-27 15:39
> I also uploaded DNG files to [google drive](https://drive.google.com/drive/folders/1FrC7_AWsXTgm0r2dieKLUiqBfayWGn8u?usp=sharing)

Could you also share an xmp?

**Comment by Jedek-Selera** [comment] 2023-03-27 16:13
yes,  [L1004979.DNG.xmp](https://github.com/Jedek-Selera/screenshoots/blob/main/L1004979.DNG.xmp) and [L1004984.DNG.xmp](https://github.com/Jedek-Selera/screenshoots/blob/main/L1004984.DNG.xmp)

**Comment by Jedek-Selera** [comment] 2023-03-27 18:29
Here something interesting, I downloaded [DNG ](https://raw.pixls.us/getfile.php/1087/nice/Leica%20-%20LEICA%20M%20MONOCHROM%20(Typ%20246)%20-%2012bit%20(3:2).DNG) LEICA M MONOCHROM (Typ 246) from raw.pixls.us repository and it does same thing with color cast. Here is  [Leica - LEICA M MONOCHROM (Typ 246) - 12bit (3_2).DNG.xmp](https://github.com/Jedek-Selera/screenshoots/blob/main/Leica%20-%20LEICA%20M%20MONOCHROM%20(Typ%20246)%20-%2012bit%20(3_2).DNG.xmp) file.  
Here is the [screenshot ](https://github.com/Jedek-Selera/screenshoots/blob/main/DT.JPG)with zoom in image and visible histogram. Am I doing something wrong here ?

**Comment by jenshannoschwalm** [comment] 2023-03-27 18:29
Thanks for the files and again an even bigger Thanks for pinpointing to this issue.

Unfortunately too many of us don't own a monochrome camera so we messed that.

> I also notice that input profile for dng file is linear Rec709 RGB, I'm not sure if that matters or not ?

Indeed it does! Select another input profile and results will be even worse. I will think about how we can solve this problem. Or - i see you haven't yet been involved in darktable github so far - in case you can program C and would like to get involved in this project, what about going into this yourself?

**Comment by Jedek-Selera** [comment] 2023-03-27 19:17
This is very encouraging, but I'm not very good in programming, had programing classes in collage, but you got me excited now. Let me improve my programing skills and I will take you up on your offer.

**Comment by jenshannoschwalm** [comment] 2023-03-27 20:01
I just had a quick look into the intermediate steps in the processing, it's not easy at all :-) 

Anyway
1. i could reproduce and the effect is indeed pretty strange especially if you zoom in with reddish and bluish taints at dark-ro-bright transitions and vice versa.
2. There is a "fix" for you until this gets properly fixed in dt code; you could define an auto-applied preset for monochrome raws setting to B&W luminance based.
![grafik](https://user-images.githubusercontent.com/50982232/228053146-e3d880a5-991d-4503-aeef-29a910eaebf6.png)

**Comment by jenshannoschwalm** [comment] 2023-03-29 17:42
Indeed a very old bug :-) BTW another one detected via `--dump-pipe rawprepare`, the cast at dark <-> bright transitions is clearly visible already there.

**Closed** 2023-03-29 20:04 UTC
Labels: reproduce: confirmed, bug: pending
