### ISSUE TITLE
Additional instance of retouch module doesn't show in darkroom

### ISSUE THREAD

**Issue by Scorpion078** [darktable-org/darktable#15018] opened 2023-08-06 13:24 UTC
### Describe the bug

When creating an additional instance of the retouch module the new instance doesn't show in the module panel.
The history shows that the new instance was created.
In order to actually see the new instance I have to go back to the lighttable and open it up in the darkroom again.
I haven't notice this behavior in any other module.

Looks like it was introduced after 4.5.0+195~g66d4bf2888
Currently on build: 4.5.0+288~gdd4cc99163

### Steps to reproduce

Create additional instance of the retouch module 
History stack reports the new instance
the new instance doesn't show in the module panel
close the photo and return to the light table
reopen the photo and the new instance is now visible

### Expected behavior

create a new visible instance

### Commit

I assume it happened with this commit: 0ccd3b3

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+288~gdd4cc99163

### What OS are you using?

Windows

### What is the version of your OS?

Windows11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia RTX 3060, Nvidia Driver 536.67

**Comment by jenshannoschwalm** [comment] 2023-08-06 14:38
Reproduced but so far without a clue why this is happening.

**Comment by wpferguson** [comment] 2023-08-06 15:49
bisect says 0ccd3b31c4b30b43c184e9005633ab227fd9eb73

**Comment by TurboGit** [comment] 2023-08-06 16:12
@wpferguson : Thanks a lot for the bisect, it will help fixing.

@jenshannoschwalm : Note that the same issue applies to the Liquify module.

**Comment by jenshannoschwalm** [comment] 2023-08-06 18:12
Yes, so far i seem to understand where this is happening. By defining a `operation_tags_filter()` in the module we have checks = TRUE in `imageop.c` Lines 2171 & 2199 and thus call `dt_dev_invalidate_from_gui()` which does ` dt_dev_pop_history_items()`.

ATM i don't understand the reason for the check at all, it i comment those lines the new module instance appears as it should but **why** is the check there at all.? Could someone enlighten me?

**Comment by TurboGit** [comment] 2023-08-06 20:45
You're speaking of:

```
    if(out_focus_module->operation_tags_filter())
      dt_dev_invalidate_from_gui(darktable.develop);
```

This code dates from 2011 (see cd24715ef91d0223130cb0342ac6cc9141117b2b). Not sure about it too. I read it as, since we have some module's specific tags we invalidate the dev to ensure a full recomputing of the pipe when leaving the focus for this module.

**Comment by jenshannoschwalm** [comment] 2023-08-07 07:28
But why is the new instance not shown in the module tabs?

**Comment by TurboGit** [comment] 2023-08-07 07:41
> But why is the new instance not shown in the module tabs?

That's weird, don't know.

I have commented out:

```
    if(out_focus_module->operation_tags_filter())
      dt_dev_invalidate_from_gui(darktable.develop);
```

But I still don't have the new instance displayed.

**Comment by TurboGit** [comment] 2023-08-07 07:44
> But why is the new instance not shown in the module tabs?

A reload of the module list maybe? The instance is in the history so probably in `dev->history` but maybe not in `dev->iop`?

**Comment by TurboGit** [comment] 2023-08-07 12:09
Some thoughts...
1. This code is dating from a long time
2. The call to `dt_dev_invalidate_from_gui` is only done for module having `operation_tags_filter` defined
3. Those modules are: `ashift`, `clippig`, `crop`, `liquify`, `retouch`
4. All other modules have the duplicate & new instance working fine  without this call
5. Why for `ashift`, `clippig`, `crop`, `liquify`, `retouch` are we calling `dt_dev_invalidate_from_gui` which reload history?
6. Why reloading history in a routine handling the focus in / out of a module?
7. And why doing this only for modules with `operation_tags_filter` defined?
8. The issue is only GUI as if you exit dt and restart it the history is properly displayed and all instances are properly listed into the module group.

At this stage this seems to be some kind of old stuff not needed anymore.

Indeed the following patch fixes the issue:

```
diff --git a/src/develop/imageop.c b/src/develop/imageop.c
index fa60b6f2a4..0f76e627d5 100644
--- a/src/develop/imageop.c
+++ b/src/develop/imageop.c
@@ -2170,9 +2170,6 @@ void dt_iop_request_focus(dt_iop_module_t *module)
     gtk_widget_set_state_flags(dt_iop_gui_get_pluginui(out_focus_module),
                                GTK_STATE_FLAG_NORMAL, TRUE);
 
-    if(out_focus_module->operation_tags_filter())
-      dt_dev_invalidate_from_gui(darktable.develop);
-
     dt_iop_connect_accels_multi(out_focus_module->so);
 
     /* reset mask view */
@@ -2198,9 +2195,6 @@ void dt_iop_request_focus(dt_iop_module_t *module)
     gtk_widget_set_state_flags(dt_iop_gui_get_pluginui(module),
                                GTK_STATE_FLAG_SELECTED, TRUE);
 
-    if(module->operation_tags_filter())
-      dt_dev_invalidate_from_gui(darktable.develop);
-
     dt_iop_connect_accels_multi(module->so);
 
     if(module->gui_focus)
```

And doesn't seem to introduce regressions.

@dterrahe : Your insight is also welcome here. Do you think for example that this could have bad effects in the shortcuts systems? My thinking is that shortcuts in multi-instance may need this?

**Comment by jenshannoschwalm** [comment] 2023-08-07 12:12
I tried commenting that also but ran into trouble in crop module immediately.

**Comment by TurboGit** [comment] 2023-08-07 12:16
Yes, exactly... just found this out :( Removing those lines breaks crop.

**Comment by TurboGit** [comment] 2023-08-07 12:19
@jenshannoschwalm : What about:

```
diff --git a/src/develop/imageop.c b/src/develop/imageop.c
index fa60b6f2a4..e8ab078a22 100644
--- a/src/develop/imageop.c
+++ b/src/develop/imageop.c
@@ -2171,7 +2171,7 @@ void dt_iop_request_focus(dt_iop_module_t *module)
                                GTK_STATE_FLAG_NORMAL, TRUE);
 
     if(out_focus_module->operation_tags_filter())
-      dt_dev_invalidate_from_gui(darktable.develop);
+      dt_dev_invalidate_all(darktable.develop);
 
     dt_iop_connect_accels_multi(out_focus_module->so);
 
@@ -2199,7 +2199,7 @@ void dt_iop_request_focus(dt_iop_module_t *module)
                                GTK_STATE_FLAG_SELECTED, TRUE);
 
     if(module->operation_tags_filter())
-      dt_dev_invalidate_from_gui(darktable.develop);
+      dt_dev_invalidate_all(darktable.develop);
 
     dt_iop_connect_accels_multi(module->so);
```

**Comment by jenshannoschwalm** [comment] 2023-08-07 12:37
I added an additional flag In iop_flags telling to ignore the check. That "works" but don't oversee further implications.

**Comment by jenshannoschwalm** [comment] 2023-08-07 12:40
Ah, yes that could work. Probably even a disable later variant recently introduced would be even better...

Can't test now as at ⚒️

**Comment by dterrahe** [comment] 2023-08-07 14:29
> My thinking is that shortcuts in multi-instance may need this?

I'm not immediately worried about that; `dt_iop_connect_accels_multi` is the call that (depending on settings) reassigns default-instance shortcuts to the currently focused instance (which is probably the new one). So that should still work.

> -      dt_dev_invalidate_from_gui(darktable.develop);
> +      dt_dev_invalidate_all(darktable.develop);

On the face of it, that seems to make much more sense.

**Closed** 2023-08-08 13:58 UTC
Labels: reproduce: confirmed, bug: pending
