### ISSUE TITLE
UI issue: new retouch & liquify with cropping visibile

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#15286] opened 2023-09-20 21:07 UTC
A PR has been merged to display the full image with cropping area when enabling  retouch and liquify. This is good, no question about that. But after the commit 290e18ccd7cdc41a7e6e68e1798c53ce92ba29df we have introduced a bad UI behavior. Even for images without crop, expanding & collapsing the module retouch or liquify does make the image flicker a little bit. This is very annoying. It is even more visible (and annoying) when working at zoom level 100% or 150%.

I have bisected this to:

```
commit 290e18ccd7cdc41a7e6e68e1798c53ce92ba29df
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Sat Sep 9 10:58:35 2023 -0400

    avoid  double image when focusing crop

 src/develop/imageop.c | 31 +++++++++++++++----------------
 1 file changed, 15 insertions(+), 16 deletions(-)
```

@dterrahe : Can you have a look please?

**Comment by dterrahe** [comment] 2023-09-20 21:26
This was already mentioned in the PR you refer to (https://github.com/darktable-org/darktable/pull/15222#issuecomment-1718576319). I don't know if @jenshannoschwalm has looked at it any further or has suggestions for further research.

**Comment by jenshannoschwalm** [comment] 2023-09-20 22:10
I didn't yet, could do so ... 
1. check if we really have to invalidate full cache or can do better
2. I don't understand the "dirty" trick 
```
 if(dev->pipe) dev->pipe->backbuf_zoom_x = 1000;
 if(dev->preview2_pipe) dev->preview2_pipe->backbuf_zoom_x = 1000;
```

**Comment by TurboGit** [comment] 2023-09-21 05:17
> This was already mentioned in the PR you refer to ([#15222 (comment)](https://github.com/darktable-org/darktable/pull/15222#issuecomment-1718576319)). I don't know if @jenshannoschwalm has looked at it any further or has suggestions for further research.

I was pretty sure I saw a comment about this but was not able to find it. Anyway, better to have an issue assigned to milestone 4.6 to not forget about this.

**Comment by TurboGit** [comment] 2023-09-21 07:27
> 2\. I don't understand the "dirty" trick

Let's remove this and see how we could rework this part properly. This is the trick that breaks retouch & liquify and is quite annoying.

**Comment by dterrahe** [comment] 2023-09-21 12:56
Let's just revert my whole attempt to fix smooth panning without doing a full refactor and cleanup of the zooming code. It creates too many side effects that can't be fixed without writing vktd. See #15290

**Comment by TurboGit** [comment] 2023-09-21 13:25
Yep, would be nice to know about all the side effects. I've been using dt quite a lot with it and the only side effect is the flicker when expanding retouch & liquify. And this can be fixed just by removing the trick (2 lines with "= 1000" discussed above).

**Comment by dterrahe** [comment] 2023-09-21 15:10
> this can be fixed just by removing the trick

Which will just reintroduce the issue #15222 fixes. I know you didn't see that in tests on a fast machine (with few modules?), but on a slow machine that is annoying too.

**Comment by TurboGit** [comment] 2023-09-21 15:52
> Which will just reintroduce the issue #15222 fixes. I know you didn't see that in tests on a fast machine (with few modules?), but on a slow machine that is annoying too.

Maybe we can force the recompute (what the trick is trying to do) but only when the out_focus_module is "crop"?

**Comment by TurboGit** [comment] 2023-09-21 15:54
Anyway, let's wait for @jenshannoschwalm idea on this as our pixelpipe expert.

**Comment by dterrahe** [comment] 2023-09-21 16:36
> force the recompute (what the trick is trying to do)

No, the recompute (or rather, the refresh of the center and preview which, because the cache has been invalidated triggers a recompute) happens anyway. This is determined somewhere else.

What the trick does is not use the _old_ images, because we don't know where to place them or by how much to scale them. In _theory_ that could be calculated at a focus change, but because of the complexities of the focus variables and calculation (and because that is in such dire need of redesign or at least refactor) and because we don't know _when_ the new focus settings come into effect (because that depends on when and in which order the new center and preview images come available) in _practice_ there's little hope to get this right (without requiring yet more _fixes_ elsewhere).

@jenshannoschwalm I don't know where all of this happens, but would it be somehow possible to treat focused and unfocused crop as identical in the cache (generate same hash?) if the crop margins are all zero? Both for (un)focusing the crop module and for any of the other modules that temporarily toggle crop. And similar for r&p and maybe others? Maybe just looking at the resulting dimensions might give a satisfactory result for our purposes here (i.e. to determine if the "trick" should be used when switching focus) but of course not for cache correctness.

**Comment by dterrahe** [comment] 2023-09-21 17:59
> And this can be fixed just by removing the trick (2 lines with "= 1000" discussed above).

BTW I may not have mentioned this so may have left the wrong impression. The "trick" I eventually came up with is not just a dirty hack after 5 minutes of throwing mud at the wall. In fact I spent 4 or 5 days (may have been longer) analysing the problem from all angles and trying to figure out a clean way to determine if the previous image is still valid and can be reasonably positioned without completely doing away with the panning/scaling of #15084. I concluded it either required a complete reworking of the zooming and positioning (and white border etc) framework, and I can't/won't commit to a year of tedious&frustrating work, or an elaborate workaround (that would make it even harder to later on implement a correct approach).

So then I put the "trick" in place to solve at least my problem quite well. I did not introduce new variables to determine the positioning, because that would mean figuring out all the places where they need to be (un)set to not introduce new regressions. These are the hard choices one has to make when a codebase becomes unmaintainable.

Yes, due to similar difficulties on the caching side (where we have a hero working away at those issues...) this has a different set of drawbacks, so it looks we can have two, but not three, of:
- smooth zooming/panning
- no artifacts when switching on/off a significant crop
- smooth switching on/off retouch/liquify when there is no crop
- ...

Just to say that if you simply remove those two lines I won't suddenly come up with a much better approach. I'm not even going to try again. But @jenshannoschwalm might.

**Comment by dterrahe** [comment] 2023-09-21 18:18
> sound/proper

I wouldn't claim this. I hate workarounds as much as anybody. But I can't rip everything up.

**Comment by jenshannoschwalm** [comment] 2023-09-21 18:45
> No, the recompute (or rather, the refresh of the center and preview which, because the cache has been invalidated triggers a recompute) happens anyway. This is determined somewhere else.

The short section in question here is
```
  dt_dev_invalidate_all(dev);
  dt_dev_pixelpipe_rebuild(dev);
```
1. The invalidate_all() could be replaced by `dt_dev_pixelpipe_cache_invalidate_later(const struct dt_dev_pixelpipe_t *pipe, const int32_t order)` with order being the position in the pipe of the focus_out_module). This would certainly help as only cache data of following modules in those pipes would be made unvalid. (unvalid means here, won't be found by pixelpipe_hb.c checking for modules data from last to first) This would certainly help for responsiveness as only modules after crop would have to be recalculated. 
2. The rebuild is necessary because of these lines 

```
  if(modules)
  {
    module = (dt_iop_module_t *)modules->data;
    piece = (dt_dev_pixelpipe_iop_t *)pieces->data;
    // skip this module?
    if(!piece->enabled
       || (dev->gui_module && dev->gui_module != module
           && dev->gui_module->operation_tags_filter() & module->operation_tags()))
      return _dev_pixelpipe_process_rec(pipe, dev, output, cl_mem_output, out_format,
                                        &roi_in,
                                        g_list_previous(modules),
                                        g_list_previous(pieces), pos - 1);
  }

```

That code is pretty hard but in fact it means the `module->operation_tags()` having modules won't be processed and the roi modifications that situation. Something similar is done in pixelpipe_cache
```
    if(!(dev->gui_module && dev->gui_module != piece->module
         && (dev->gui_module->operation_tags_filter() & piece->module->operation_tags())))
    {
      hash = ((hash << 5) + hash) ^ piece->hash;
``` 
This is done to give following modules different hashes to avoid "early-fallbacks" to cachelines instead of reprocessing.

Unfortunately i don't have a proper solution for the whole story right now. I will think about it the next days. The big problem as @dterrahe already mentioned is "how to draw correctly and in a smooth way" as processed data are coming in later. We might be able to diminish this by
a) using the "invalidate later idea"
b) we can increase the cacheline weight of the crop module before expanding - that would still mean the rest of data has to be processed


> Even for images without crop, expanding & collapsing the module retouch or liquify does make the image flicker a little bit.

A second idea here on this. If we could test for a no-crop situation in crop module while checking the module->operation_tags stuff - so no flags given back - we would avoid the reprocessing ... that __would__ work

**Comment by jenshannoschwalm** [comment] 2023-09-21 22:36
I took some time for a first deeper look, the code in question - we know it was existing basically as is before - seems to be plain wrong. In case of a module like retouch that means we do full reprocessing in all cases due to the ` existing module->operation_tags_filter()` flags.

```
  if((out_focus_module && out_focus_module->operation_tags_filter())
     // || (module && module->operation_tags_filter())
     )
  {
    dt_dev_invalidate_all(dev);
    dt_dev_pixelpipe_rebuild(dev);
    // don't use previous image as overlay
    if(dev->pipe) dev->pipe->backbuf_zoom_x = 1000;
    if(dev->preview2_pipe) dev->preview2_pipe->backbuf_zoom_x = 1000;
  }

```

I think this is a worthwhile problem for me and i think we can find a proper fix :-) So @dterrahe and @TurboGit - don't revert as in #15290, there is so much good in that work to me.

**Comment by dterrahe** [comment] 2023-09-22 00:00
Thank you for looking into this! (what timezone are you in again?)

I'm afraid I won't understand the pipe and cache processing enough until (and if ever) I really dive into it and start breaking stuff. There's so much "oh of course you'd have to do that!" in there that only makes sense if you've ever had to fight it. My naive and simplistic reasoning always wants to say "but you never want to throw away cache because what if you toggle an option on and you immediately want to toggle it off again; you'd want to reuse the previously cached value, like any other module" but to make that possible probably means unbreaking all kinds of long since settled assumptions and nobody would want to shorten their live like that.

But checking if a non-zero crop actually exists in `operation_tags_filter` sounds like a doable and sensible thing. `retouch` and `liquify` don't do the actual cropping themselves and I skipped looking at how that piece of magic works, but you wrote it so I guess you'll know where to ask :-)

_In theory_ you'd want to check that in-focus and out-focus modules have _different_ crops (in case you switch from liquify to retouch or to crop itself, but presumably that would require (much) more restructuring....

**Closed** 2023-10-08 19:07 UTC
Labels: priority: medium, scope: UI, bug: pending
