### ISSUE TITLE
Unexpected export size after cropping

### ISSUE THREAD

**Issue by oxpa** [darktable-org/darktable#3106] opened 2019-10-09 18:35 UTC
**The problem and steps to reproduce**
The problem is somehow related to #2849 yet I'm using vanilla darktable from ubuntu repos.

- I have a picture with WxH of 6011x4022 (or whatever).
- I want to exported image it to be exactly 6000 by 4000.
- I crop to exact size I need: 6000 by 4000 (I have to zoom in in a strange manner to see the center and a side I'm moving).
- Then I export the image limiting width and height with 6000.
- The resulting image is 5999 by 4000.
  Other results I get are 6001 by 3999 or 6000 by 3999 depending on crop size.
  So I have to use exactly 6006 by 4004 crop to get a 6000x4000 exported image.

**Expected behavior**
I expect that a cropped to 6000x4000 image would be exported as 6000x4000

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Version :
```:~$ darktable --version
this is darktable 2.6.2
copyright (c) 2009-2019 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 5.0.1
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  OpenEXR support enabled
```

**Comment by junkyardsparkle** [comment] 2019-10-09 21:34
Does setting "allow upscaling" to "yes" in the export module help? Otherwise, if you're absolutely sure you have a pixel-precise cropping, you could just set the output dimensions to zero, for no scaling. The problem is that darktable's cropping module isn't really designed for pixel-precise adjustment; that type of thing is better handled in a paint-type program like GIMP after exporting.

**Comment by jorsn** [comment] 2020-08-20 11:56
I have the same problem with uncropped pictures in darktable 3.0.1 on NixOS 20.03.
This is independent of whether OpenCL is switched on or off and whether upscaling or HQ resampling is activated.

According to the image information in darktable, each picture has dimensions 3724x2754, while some appear as 3724x2753 in the output. The pictures are RAW (RW2) images from a Lumix DMC-FZ28 with only mandatory filters applied.

**Comment by johnny-bit** [comment] 2020-08-20 13:02
@jorsn :

> The problem is that darktable's cropping module isn't really designed for pixel-precise adjustment; that type of thing is better handled in a paint-type program like GIMP after exporting.

same whith exporting raw - it's basically a "rounding" problem and if you want exact pixel dimensions it's not darktalbe's job. Additionally you actually get MORE pixels from darktable than form your camera's JPEG (which is max 3648 x 2736 compared to dt's 3724x2754) :)
If you need exact pixel dimmensions, crop in gimp/imagemagick etc.

**Comment by jenshannoschwalm** [comment] 2020-08-20 16:10
Should be fixed already in 3.2

**Comment by johnny-bit** [comment] 2020-08-20 16:52
Apologies to @jenshannoschwalm  and I need to correct myself from earlier: in dt 3.2.1 both exact crop and export with exact dimmensions work pixel perfect!

**Closed** 2020-08-20 16:58 UTC
Labels: no-issue-activity

**Comment by Arecsu** [comment] 2024-09-06 15:35
I'm experimenting this with the latest version of Darktable. The image is 6048x8064. Have plenty of room to crop it. I crop it in 4x5 aspect ratio vertically by taking off just the top and bottom parts of the image. In the export module, I choose 1080x1350 and end up with a JPG that is 1079x1350
