### ISSUE TITLE
Image information datetime fail

### ISSUE THREAD

**Issue by gitdarktable** [darktable-org/darktable#3306] opened 2019-11-06 06:52 UTC
The date field is shown empty

1. Go to 'module image information'
2. Click on 'module image information'
3. Scroll down to 'datetime'
4. See error field 'empty'

**Expected behavior**
View exif date create
![datetime](https://user-images.githubusercontent.com/57431523/68274570-d0a10100-0069-11ea-8e56-0771c30f1620.png)

**Platform (please complete the following information):**
 - OS: Windows 7 Pro x64
 - Version updated

**Additional context**

It also happens with TIFF imported to darktable  from developed program that accompanies the camera Pentax K-50.

**Comment by sams96** [comment] 2019-11-07 08:08
Can you provide a sample file please.

**Comment by gitdarktable** [comment] 2019-11-07 18:20
I've seen that in the generated .xmp the creation date is correct but darktable doesn't represent it.

.dng compressed ZIP:
[IMGP0017.zip](https://github.com/darktable-org/darktable/files/3821116/IMGP0017.zip)

.tif LZW compressed ZIP:
[IMGP0017.zip](https://github.com/darktable-org/darktable/files/3821120/IMGP0017.zip)

**Comment by jenshannoschwalm** [comment] 2019-11-07 21:13
On current master and linux can't reproduce. When inspecting via exiv2 correct metadata are present.

**Comment by gitdarktable** [comment] 2019-11-14 06:49
I test stable v2.6.2 and .dng and .tif datetime is good.

In [v2.7 for Windows](https://discuss.pixls.us/t/darktable-2-7-dev-windows-builds/12579/140) and currently v3.0.0rc0 fail.

**Comment by gitdarktable** [comment] 2019-11-23 08:44
I tests currently v3.0.0rc1 fail

**Comment by gitdarktable** [comment] 2019-11-29 11:13
I tests currently v3.0.0rc2 fail

**Comment by gitdarktable** [comment] 2019-12-12 17:07
Solved:

both in Win10 and Win7 Datetime fail if regional settings language in OS is different to English (UK).

https://discuss.pixls.us/t/datetime-information/15150/32 

It is not a complete solution but it works, will have an easy solution (I guess).

**Comment by gitdarktable** [comment] 2019-12-26 15:40
Hi, partial days are correct, but not all, in latest v3.0.0.

**Comment by Nilvus** [comment] 2021-01-22 20:37
This issue seems to have been fixed since. So I close it. @gitdarktable: feel free to reopen with new information if it's still there on darktable 3.4. Note too that 3.4.1 will be out really soon (2 or maybe 3 weeks probably).

**Closed by Nilvus** 2021-01-22 20:37 UTC
Labels: no-issue-activity
