### ISSUE TITLE
Unexpected behavior in the white balance module

### ISSUE THREAD

**Issue by gi-man** [darktable-org/darktable#11377] opened 2022-03-21 20:04 UTC
**Describe the bug/issue**
I use the Camera Reference selection in white balance module. Since switching to 3.9.0+798~g8152dd9d6, the selection shows as User Modified and I get the red warning of White Balance Applied Twice. The temperature and tint values remain the same. If I select Camera Reference or reset, the warning goes away without changes to the image.  

**To Reproduce**
Just open a previously edited image in darkroom.

**Expected behavior**
The Camera Reference selection remains instead of going with User Modified.

**Screenshots**
![image](https://user-images.githubusercontent.com/97920861/159352121-f8c9b442-5bf0-4ffc-9c7f-ec346a56f4ce.png)

**Which commit introduced the error**
I noticed it in 3.9.0+798~ g8152dd9d6. I was using 3.9.0+219~ g06ad12bae before.  I read thru the merged PRs and this one had changes to this module. https://github.com/darktable-org/darktable/pull/11291

**Platform**

* darktable version : 3.9.0+798~ g8152dd9d6
* OS                : Yes Win11
* Memory            :  16Gb
* Graphics card     :  NVidia 3060 12Gb
* Graphics driver   :  511
* OpenCL installed  : yes
* OpenCL activated  : yes

**Additional context**
 - Can you reproduce with another darktable version(s)? Not in 3.9.0+219~ g06ad12bae or priors 
 - Can you reproduce with a RAW or Jpeg or both? N/A
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? No. If I remove from database and delete the xmp, it works correctly.

**Comment by MStraeten** [comment] 2022-03-21 20:39
if you have colorcalibration enabled and whitebalance (not camera reference) then this warning occurs (also if you have two colorcalibration instances). If you are doing this intentionally then you can disable the warning in preferences.

**Comment by Nilvus** [comment] 2022-03-21 20:50
This is not an issue as @MStraeten and not related to #11291 (this PR was just about moving buttons on top of the module, so nothing had been changed by #11291 about behavior you pointed).
Seems that you didn't notice but it's there since arrival of color calibration module and absolute normal behavior. Think about closing this issue after seeing and following @MStraeten advice. Thanks.

**Comment by Nilvus** [comment] 2022-03-21 20:50
This is not an issue as @MStraeten and not related to #11291 (this PR was just about moving buttons on top of the module, so nothing had been changed by #11291 about behavior you pointed).
Seems that you didn't notice but it's there since arrival of color calibration module and absolute normal behavior. Think about closing this issue after seeing and following @MStraeten advice. Thanks.

**Comment by gi-man** [comment] 2022-03-21 21:03
Maybe i was not clear. It is happening automatically. 

As i stated, i use Camera Reference. It is automatically being changed to User Modified. I don't want it changed.

**Comment by MStraeten** [comment] 2022-03-21 22:15
maybe your old edit was made before adobe-coeff stuff was changed. So to prevent old edits from being broken the old setting for camera white balance are kept an as a user modified setting.
So works as designed …

**Comment by gi-man** [comment] 2022-03-22 13:54
> So works as designed …

How can I test it is the adobe-coeff? The edits are not that old, 2-3days old in 3.9.0+219. The actual white balance settings remained the same (6205K/1.000). 

I'm ready to go ahead and create a style or Selective Copy/Paste to change all the images in my collection to use the white balance Camera Ref setting instead of the User setting. (aka workaround)

**Comment by MStraeten** [comment] 2022-03-22 16:44
the pr was merged 25 days ago. 3.9.0+219 seems to be a build in the first week of February, so without the adobe-coeff change.
The values didn't change in most cases but the values were taken over as manual settings to avoid breaking older edits where in case of changes.

**Comment by Nilvus** [comment] 2022-03-31 17:58
I reopen this issue as I finally think there's an issue. I have seen it on my side and on start was thinking I missed something (wrong copy/paste preset). But as I have modern setting set in processing tab for chromatic adapation, on main preferences, I so should have white balance with camera reference point and color calibration.

AS @gi-man pointed here, I indeed now always had user modified setting (instead of camera reference one) by default on all newly imported images (and all previous one). That's really annoying.

I of course check if I had or not presets that could override that but no. No presets, nor on import nor on white balance module.

**So expected behavior should remain, as it was since it's implementation:**
When setting modern option in auto-apply chromatic adaptation, white balance module should set camera reference point and not user modified one. That was the case quite recently.

**Comment by MStraeten** [comment] 2022-03-31 19:18
> I reopen this issue as I finally think there's an issue. I have seen it on my side and on start was thinking I missed something (wrong copy/paste preset). But as I have modern setting set in processing tab for chromatic adapation, on main preferences, I so should have white balance with camera reference point and color calibration.

yes, this behaviour was introduced again between two builds i made after a git pull at 25.03. and 26.03. - so definitely a different case.
the original behaviour is a consequence of changing the adobe_coeff stuff and now it's something that was introduced later.
So it's worth to differenciate between both cases. maybe at weekend i have a bit time to bisect ...

**Comment by MStraeten** [comment] 2022-03-31 19:23
it seems https://github.com/darktable-org/darktable/pull/11329 did some changes with side effects on whitebalance

**Comment by phweyland** [comment] 2022-03-31 19:30
> it seems #11329 did some changes with side effects on whitebalance

I'll have a look at it...

**Comment by Nilvus** [comment] 2022-03-31 21:04
> btw. the original issue is a result of the adobe_coeff change. The reopening was made because the latest build has similar symptoms but a different reason.

No, I have seen many images since a month with that issue but I was thinking it was just an error I made (some copy/paste error or something like that), I thought that @gi-man issue was not one. I think his and mine are the same.

IF it's a side effect of Adobe coeff change, it's should not affect white balance default setting. I've searched more and found that all my images where affected, really all (old ones and newly imported ones. All have white balance added on top of the history stack with 6239K setting (so user modified one). When I so select previous step on history stack, white balance revert back to camera reference setting.

I don't know how it's possible but this seems like if white balance with 6239K were applied on top of all image edits!

**Comment by TurboGit** [comment] 2022-03-31 21:08
> > When setting modern option in auto-apply chromatic adaptation, white balance module should set camera reference point and not user modified one.
> 
> I cannot reproduce the corresponding issue (3.9.0+880~g2b96c9917). With a fresh config, `setting processing / auto-apply chromatic adaptation` defaults to `modern`, then importing (`add to library`) raw files I have white balance set to `camera reference`. EDIT importing files without xmp. Do I look at the right issue ? If not, somebody could rephrase it ? Any tip to reproduce the issue ?

Likewise cannot reproduce at the moment. @MStraeten if you can reproduce easily and can bisect the issue it would be very helpful indeed.

**Comment by TurboGit** [comment] 2022-03-31 21:11
BTW, @MStraeten is that on some specific RAW files format?

**Comment by TurboGit** [comment] 2022-03-31 21:34
If that's the issue we are on a dead-end! The change was made a rawspeed maintainer don't want to update the adobe_coeff.c that was on the darktable repository and it was asked that dt use the rawspeed data instead. If there is some discrepancies between the old adobe_coeff.c and new rawspeed values that's unfortunate. And note that this move is a good one as it will avoid those discrepancies on the future. So what can we do... nothing I can think of at the moment :(

**Comment by Nilvus** [comment] 2022-03-31 21:38
> If that's the issue we are on a dead-end! The change was made a rawspeed maintainer don't want to update the adobe_coeff.c that was on the darktable repository and it was asked that dt use the rawspeed data instead. If there is some discrepancies between the old adobe_coeff.c and new rawspeed values that's unfortunate. And note that this move is a good one as it will avoid those discrepancies on the future. So what can we do... nothing I can think of at the moment :(

I understand. What's annoying is that it changed old edits and do not completely respect something auto-applied. When darktable 4.0 will be landed, we have the risk to have quite some complaints. I can deal with that easily, for me, even if it's annoying, copy/paste white balance to all images to fix that as already began.

Just a question/thought to try to avoid limits: Would not been at least possible to add some conditions on code, to avoid applied/change that on old edits (for example edits made before darktable 4.0 and/or if modern chromatic adaptation is set in preferences?

**Comment by TurboGit** [comment] 2022-03-31 21:41
> Just a question/thought to try to avoid limits: Would not been at least possible to add some conditions on code, to avoid applied/change that on old edits (for example edits made before darktable 4.0 and/or if modern chromatic adaptation is set in preferences?

Maybe, yes but it should already be the case. I mean an old edit having already the adobe coeff should not load some other values. What kind of RAW is that BTW, we really need to fully understand the issue before trying to find a way to fix whatever the issue is.

**Comment by TurboGit** [comment] 2022-03-31 21:42
Also, what is confusing is that it has been said that this was reproducible with new edits. And in this case the adobe coeff envisioned issue cannot be in play. So there must be something else. Again at this stage the issue is not understood enough.

**Comment by jenshannoschwalm** [comment] 2022-04-08 13:13
@TurboGit hasn't this been fixed by #11465 ?

**Closed** 2022-06-07 19:25 UTC
Labels: priority: high, reproduce: confirmed, bug: pending

**Comment by bilddateien** [comment] 2022-07-03 19:53
Sorry to come in on this again.
Just switched from 3.8.1 to 4.0 and see this with **all** of my images (hundreds of them) I edited with 3.8.1
Is this to be expected ... and ... do I have to hand-reedit all of those? :(

I started using Color Calibration and Camera Reference in modern workflow as soon as this was introduced (3.8?, maybe earlier).

**Comment by Nilvus** [comment] 2022-07-03 20:35
@bilddateien: please read comments here carefully. All is explain. Nothing can be done and this doesn't broke edits. The only thing you can do is to set an image with neutral D65 (bulb icon), then copy/paste this on other images. Opening an issue will just be a duplicate of this one and so will be closed.

**Comment by bilddateien** [comment] 2022-07-03 20:43
maybe I overread something in this long discussion, but:
> The only thing you can do is to set an image with neutral D65 (bulb icon), then copy/paste this on other images.

is the kind of help I can deal with.

Thanks for this advice!!
