### ISSUE TITLE
Retouch: Source copied ~10 pixels above target

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#5131] opened 2020-05-19 20:12 UTC
**Describe the bug**
When retouching a large panorama (20.000×5.000) the source is copied roughly 10 pixels above the marked target area. The panorama is 16bit TIFF generated by Hugin.

**To Reproduce**
1. Activate Retouch
2. Mark an area
3. See error, error happens both when using _Healing_ or _Clone_

**Expected behavior**
Source is copied to target area.

**Screenshots**
Here is a cut from the darkroom image.
![image](https://user-images.githubusercontent.com/18402158/82370244-ed5ac000-9a20-11ea-83d1-68761cf8e47b.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Win10
 - OpenCL active
 - NVIDIA GeForce 940MX

**Additional context**
 - The same issue is also on Linux darktable 3.1.0

**Comment by elstoc** [comment] 2020-05-19 20:23
Could be related to #3904. What other modules do you have active? If you deactivate all other modules, does the issue go away?

**Comment by paperdigits** [comment] 2020-05-20 01:16
Can you try with openCL disabled and see if the result is the same?

**Comment by juhavlintula** [comment] 2020-05-20 05:15
I think it is related to #3904. I had cropped the image and when I disabled hi crop and rotate the areas are aligned. A workaround I found is to do the retouch first and crop it after. The drawn target area will move, but the actual target remains the same.

**Comment by johnny-bit** [comment] 2021-06-13 07:15
I've re-tested with `3.5.0+2512~g6751588ef` and couldn't reproduce moving of retouch points. Also - thanks to adding `crop` module wchic comes after retouch in pipe I think the issue is solvable similarly to your workaround - by using that module ;)

I think that thanks to recent c&r + crop changes + fixes in masks code, the issue is essentially "fixed". Therefore I'd like to close the issue if you don't mind.

If the problem remains in current master it'd be great to have reproducible case.

**Closed by johnny-bit** 2021-06-13 07:15 UTC
Labels: no-issue-activity

**Comment by TurboGit** [comment] 2021-06-13 17:21
Yep, I fixed this issue which was some kind of rounding issues IIRC.
