### ISSUE TITLE
[Tone Equalizer 3.3.0-xxx] Circular cursor shows +nan EV

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6572] opened 2020-10-19 02:35 UTC
A lot of areas show +nan EV while using the tone equalizer module.
This image the lower part of the image 

![image](https://user-images.githubusercontent.com/1119439/96394830-9ed46c00-11e0-11eb-8760-9fc3cf5184f5.png)

![image](https://user-images.githubusercontent.com/1119439/96394955-f5da4100-11e0-11eb-81f4-cb62a527ff43.png)

**Comment by matt-maguire** [comment] 2020-10-19 02:44
Did you adjust the black point on the raw black/white point module or on the exposure module? If it is set too high, it can result in negative values that can cause NaN values. Black point adjustments for creative purposes are better left to filmic (or by putting a toe in base curve etc.).

**Comment by chhil** [comment] 2020-10-19 03:21
This image was a jpeg so raw black/white point was not available

Pixelpipe
![image](https://user-images.githubusercontent.com/1119439/96397689-a77c7080-11e7-11eb-9f2e-7fd9155312f7.png)

History
![image](https://user-images.githubusercontent.com/1119439/96397714-b82ce680-11e7-11eb-9e15-d7d39b1e73f4.png)

Tone equalizer was just turned on with no changes in its sliders.

I did change levels, but it's after the toneequalizer in the pipe.
![image](https://user-images.githubusercontent.com/1119439/96397930-3b4e3c80-11e8-11eb-86c9-9c1748633722.png)

**Comment by aurelienpierre** [comment] 2020-10-19 13:21
Try changing the black level in exposure module. The most probable reason is you have negative RGB values.

**Comment by chhil** [comment] 2020-10-19 14:19
1. I turned  exposure off. 
2. Used color picker in RGB mode, values never turn negative but tone equalizer cursor shows nan at the same location.

![image](https://user-images.githubusercontent.com/1119439/96463258-23a4a180-1244-11eb-8d4f-0cd6819f13c2.png)

**Comment by aurelienpierre** [comment] 2020-10-19 15:23
The color picker shows the output of the pipe while we care about the input. There is the raw black/white levels module that fiddles with black point compensation, so it can still create negatives there. Just brighten the black in exposure and see if that fixes it.

**Comment by chhil** [comment] 2020-10-21 06:18
Set the exposure black level correction to -0.9999 and I still get NAN. Though some areas on the ladies dress that were NAN  are no longer NAN. But the road at the bottom of the frame still shows NAN.

![image](https://user-images.githubusercontent.com/1119439/96680525-4e514000-1393-11eb-97b1-3604e9f56e79.png)


![image](https://user-images.githubusercontent.com/1119439/96680384-07fbe100-1393-11eb-8c7d-c14a0aae89e8.png)

**Comment by aurelienpierre** [comment] 2020-11-21 14:04
Could you show the output of the mask ?

**Comment by chhil** [comment] 2020-11-22 03:32
I assume this is the info you are requesting...

![image](https://user-images.githubusercontent.com/1119439/99892993-3b3ad400-2ca1-11eb-99f7-3a8101fe61a6.png)

This is with the current master, and I must add that the toneequalizer spreads the mask much better now and I feel it works better now.

**Comment by johnny-bit** [comment] 2020-12-15 18:50
I can't replicate that too...

Can you share file & xmp with us so we can debug issue, more in line with what's to be expected?

**Comment by Nilvus** [comment] 2021-06-20 21:25
@chhil as you don't provide more infos since 6 months on this one, I close this one. I can't also not reproduce it in actual master. Of course, if you can reproduce, feel free to reopen (or ask for it) by providing more infos and especially file & xmp with the issue to help.

**Closed by Nilvus** 2021-06-20 21:25 UTC
Labels: no-issue-activity
