### ISSUE TITLE
darktable segfault in tone equalizer

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#15662] opened 2023-11-15 03:20 UTC
### Describe the bug

Backtrace

```
Thread 1 (Thread 0x7fb485b4b0c0 (LWP 242327) "darktable"):
#0  0x00007fb48e0ea42f in __GI___wait4 (pid=pid@entry=243971, stat_loc=stat_loc@entry=0x0, options=options@entry=0, usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
        sc_ret = -512
        sc_cancel_oldtype = 0
#1  0x00007fb48e0ea3ab in __GI___waitpid (pid=pid@entry=243971, stat_loc=stat_loc@entry=0x0, options=options@entry=0) at ./posix/waitpid.c:38
#2  0x00007fb48e584e30 in _dt_sigsegv_handler (param=11) at /home/bill/src/darktable/darktable/src/common/system_signal_handling.c:101
        pid = 243971
        name_used = 0x55f14ee248d0 "/tmp/darktable_bt_F6CNE2.txt"
        fout = <optimized out>
        delete_file = 0
        datadir = "/opt/darktable45/share/darktable", '\000' <repeats 4063 times>
        pid_arg = 0x55f1511b9290 "242327"
        comm_arg = 0x55f14f444cb0 "/opt/darktable45/share/darktable/gdb_commands"
        logenable = 0x55f1517cb080 "set logging enabled on"
        setlogfile = 0x55f15130d8d0 "set logging file /tmp/darktable_bt_F6CNE2.txt"
#3  0x00007fb48e042520 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007fb4581bce94 in _unset_distort_signal (self=<optimized out>) at /home/bill/src/darktable/darktable/src/iop/toneequal.c:2595
        g = <optimized out>
        __FUNCTION__ = "_unset_distort_signal"
        self = 0x55f14e55d960
        g = 0x7ffe
#5  _develop_distort_callback (instance=0x55f14a5007a0, user_data=0x55f14e55d960) at /home/bill/src/darktable/darktable/src/iop/toneequal.c:2571
        self = 0x55f14e55d960
        g = 0x7ffe
#6  0x00007fb48e266d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007fb48e282c36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007fb48e5a37ce in _signal_raise (user_data=0x55f15172f7a0) at /home/bill/src/darktable/darktable/src/control/signal.c:256
        params = 0x55f15172f7a0
#9  0x00007fb48df1b435 in g_main_context_invoke_full () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007fb48e5a3e3c in dt_control_signal_raise (ctlsig=<optimized out>, signal=signal@entry=DT_SIGNAL_DEVELOP_DISTORT) at /home/bill/src/darktable/darktable/src/control/signal.c:367
        signal_description = 0x7fb48e9519f0 <_signal_description+2160>
        params = 0x55f15172f7a0
        instance_and_params = 0x55f151569ad0
        extra_args = {{gp_offset = 16, fp_offset = 0, overflow_arg_area = 0x7ffed64401e0, reg_save_area = 0x7ffed6440170}}
#11 0x00007fb48e614f89 in dt_iop_gui_update (module=<optimized out>) at /home/bill/src/darktable/darktable/src/develop/imageop.c:2135
        __FUNCTION__ = "dt_iop_gui_update"
#12 0x00007fb48e60b520 in dt_dev_pop_history_items (dev=dev@entry=0x55f14caff400, cnt=<optimized out>) at /home/bill/src/darktable/darktable/src/develop/develop.c:1283
        module = <optimized out>
        dev_iop = 0x55f1505e2b80 = {0x55f14f0b8b70, 0x55f14f23f730, 0x55f150bd5a80, 0x55f14f449350, 0x55f14fb0b760, 0x55f14efed200, 0x55f14e8ddb60, 0x55f150dfd920, 0x55f151130400, 0x55f1508f6b70, 0x55f14e69fb50, 0x55f14e5cc9b0, 0x55f150bec490, 0x55f14f903a50, 0x55f150136370, 0x55f14fa89b70, 0x55f150a04370, 0x55f14fd66b80, 0x55f15035fc00, 0x55f1508f8400, 0x55f150df7260, 0x55f14e68eb30, 0x55f14f40f400, 0x55f14ee04770, 0x55f14f25d710, 0x55f14f345400, 0x55f14f38eb40, 0x55f14e94c490, 0x55f1505b3740, 0x55f14ed1b610, 0x55f150898000, 0x55f14f2a0370, 0x55f14e5c2400, 0x55f14e9c3000, 0x55f14e547800, 0x55f1504a6b70, 0x55f150bd1760, 0x55f14fa2a800, 0x55f14e5af380, 0x55f14f0a6e00, 0x55f151481d60, 0x55f150cbe270, 0x55f14ff8d800, 0x55f15038f890, 0x55f14e0b6090, 0x55f14ed1f560, 0x55f14fccf380, 0x55f150e52b60, 0x55f14ebe1800, 0x55f14e131800, 0x55f14f656b70, 0x55f14f5d5750, 0x55f14f42d780, 0x55f14f9c3800, 0x55f15102e360, 0x55f14f395370, 0x55f14e9f31c0, 0x55f1510253b0, 0x55f14e9e4f00, 0x55f14eaff120, 0x55f14ff24b70, 0x55f14ed52980, 0x55f150db1380, 0x55f150906970, 0x55f14dfcd970, 0x55f14fe3d800, 0x55f150a391c0, 0x55f14fd5f890, 0x55f1504ed980, 0x55f15078f000, 0x55f15046c4e0, 0x55f14f90bb00, 0x55f150ba5200, 0x55f14f757890, 0x55f14e616370, 0x55f14e392a40, 0x55f1503619c0, 0x55f14ea5d990, 0x55f15002b120, 0x55f1510de400, 0x55f14f00eb80, 0x55f14f4cf800, 0x55f150b9a570, 0x55f14e480800, 0x55f150988400, 0x55f1508f6150, 0x55f14f999b50, 0x55f150dd6b80, 0x55f14e5a1b50, 0x55f14f15e470, 0x55f14e65f360, 0x55f14eb0cb50, 0x55f14f8f5800, 0x55f150e5b830, 0x55f14ffcab50}
        modules = 0x55f14cad0940 = {0x55f14f0b8b70, 0x55f14f23f730, 0x55f150bd5a80, 0x55f14f449350, 0x55f14fb0b760, 0x55f14efed200, 0x55f14e8ddb60, 0x55f150dfd920, 0x55f151130400, 0x55f1508f6b70, 0x55f14e69fb50, 0x55f14e5cc9b0, 0x55f150bec490, 0x55f14f903a50, 0x55f150136370, 0x55f14fa89b70, 0x55f150a04370, 0x55f14fd66b80, 0x55f15035fc00, 0x55f1508f8400, 0x55f150df7260, 0x55f14e68eb30, 0x55f14f40f400, 0x55f14ee04770, 0x55f14f25d710, 0x55f14f345400, 0x55f14f38eb40, 0x55f14e94c490, 0x55f1505b3740, 0x55f14ed1b610, 0x55f150898000, 0x55f14f2a0370, 0x55f14e5c2400, 0x55f14e9c3000, 0x55f14e547800, 0x55f1504a6b70, 0x55f150bd1760, 0x55f14fa2a800, 0x55f14e5af380, 0x55f14f0a6e00, 0x55f151481d60, 0x55f150cbe270, 0x55f14ff8d800, 0x55f15038f890, 0x55f14e0b6090, 0x55f14ed1f560, 0x55f14fccf380, 0x55f150e52b60, 0x55f14ebe1800, 0x55f14e131800, 0x55f14f656b70, 0x55f14f5d5750, 0x55f14f42d780, 0x55f14f9c3800, 0x55f15102e360, 0x55f14f395370, 0x55f14e9f31c0, 0x55f1510253b0, 0x55f14e9e4f00, 0x55f14eaff120, 0x55f14ff24b70, 0x55f14ed52980, 0x55f150db1380, 0x55f150906970, 0x55f14dfcd970, 0x55f14fe3d800, 0x55f150a391c0, 0x55f14fd5f890, 0x55f1504ed980, 0x55f15078f000, 0x55f15046c4e0, 0x55f14f90bb00, 0x55f150ba5200, 0x55f14f757890, 0x55f14e616370, 0x55f14e392a40, 0x55f1503619c0, 0x55f14ea5d990, 0x55f15002b120, 0x55f1510de400, 0x55f14f00eb80, 0x55f14f4cf800, 0x55f150b9a570, 0x55f14e480800, 0x55f150988400, 0x55f1508f6150, 0x55f14f999b50, 0x55f150dd6b80, 0x55f14e5a1b50, 0x55f14f15e470, 0x55f14e65f360, 0x55f14eb0cb50, 0x55f14f8f5800, 0x55f150e5b830, 0x55f14ffcab50}
        dev_iop_changed = <optimized out>
#13 0x00007fb47ea801c2 in enter (self=0x55f14c9775f0) at /home/bill/src/darktable/darktable/src/views/darkroom.c:2976
        __FUNCTION__ = "enter"
        dev = 0x55f14caff400
        box = <optimized out>
        sw = <optimized out>
        option = "plugins/darkroom/rawprepare/expanded\000\000ed\000\000\000M\361U\000\000`\nx\215\264\177\000\000@\004D\326\376\177\000\000\060\004D\326\376\177\000\000\200u9J\361U\000\000C\000\000\000\000\000\000\000\020\021+\216\264\177\000\000C\000\000\000\000\000\000\000\326\065(\216\264\177\000\000\000\000\000\000\000\000\000\000\260H\000N\361U\000\000@\004D\326\376\177\000\000\200u9J\361U\000\000\001", '\000' <repeats 15 times>, "\001\000\000\000\000\000\000\000\001\000\000\000\264\177\000\000\367\003\000\000\000\000\000\000У\034N\361U\000\000\300\215gM\361U\000\000\200"...
        active_plugin = <optimized out>
#14 0x00007fb48e706915 in dt_view_manager_switch_by_view (vm=0x55f14c8eaaa0, nv=0x55f14c9775f0) at /home/bill/src/darktable/darktable/src/views/view.c:413
        old_view = <optimized out>
        new_view = 0x55f14c9775f0
        __FUNCTION__ = "dt_view_manager_switch_by_view"
#15 0x00007fb48e706d11 in dt_view_manager_switch (vm=<optimized out>, view_name=view_name@entry=0x7fb48e8403f0 "darkroom") at /home/bill/src/darktable/darktable/src/views/view.c:250
        switching_to_none = <optimized out>
        new_view = <optimized out>
#16 0x00007fb48e698351 in _event_button_press (widget=<optimized out>, event=0x55f151052f10, user_data=0x55f14a44fdd0) at /home/bill/src/darktable/darktable/src/dtgtk/thumbtable.c:1272
        table = 0x55f14a44fdd0
        view = 0x55f14c8e2f20
        id = 66050
        __FUNCTION__ = "_event_button_press"
#17 0x00007fb48d9e5b77 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007fb48e266d2f in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007fb48e282c36 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007fb48e284026 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007fb48e284863 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007fb48d9ae724 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007fb48d851680 in  () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007fb48d85252a in gtk_main_do_event () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007fb48d532743 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#26 0x00007fb48d569f56 in  () at /lib/x86_64-linux-gnu/libgdk-3.so.0
#27 0x00007fb48df1bd3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007fb48df71258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fb48df1b2b3 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007fb48d848cfd in gtk_main () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007fb48e6b2f3d in dt_gui_gtk_run (gui=<optimized out>) at /home/bill/src/darktable/darktable/src/gui/gtk.c:1365
        widget = <optimized out>
        allocation = {x = 0, y = 0, width = 1057, height = 467}
#32 0x000055f14a1510d6 in main (argc=<optimized out>, argv=<optimized out>) at /home/bill/src/darktable/darktable/src/main.c:94
[Inferior 1 (process 242327) detached]
backtrace written to /tmp/darktable_bt_F6CNE2.txt
/home/bill/bin/darktable45: line 1: 242327 Segmentation fault      (core dumped) /opt/darktable45/bin/darktable -d lua --cachedir $HOME/.cache/darktable45 --configdir $HOME/.config/darktable45 $@
```

### Steps to reproduce

1. Use tone equalizer on an image
2. Add another instance of exposure with a drawn mask and make an exposure change.
3. Return to lighttable
4. Double click to reopen the image in darkroom
5. See the backtrace...

Here's the xmp from the image I was editing...

[101EOSR7_1E1A6483.CR3.xmp.txt](https://github.com/darktable-org/darktable/files/13359657/101EOSR7_1E1A6483.CR3.xmp.txt)

### Expected behavior

No crashes please

### Commit

633336efbeafaf812701653060247e4f955d3a22

### Where did you install darktable from?

darktable.org

### darktable version

darktable 4.5.0+1188~g9516d9b10b

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

i7-12800HX
32 GB
4K Monitor
NVIDIA GeForce RTX 3070 8MB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia 535

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Bisect

```
633336efbeafaf812701653060247e4f955d3a22 is the first bad commit
commit 633336efbeafaf812701653060247e4f955d3a22
Author: Pascal Obry <pascal@obry.net>
Date:   Tue Nov 14 07:51:52 2023 +0100

```

@TurboGit

**Comment by TurboGit** [comment] 2023-11-15 09:45
Yep, on my side...

**Comment by TurboGit** [comment] 2023-11-15 11:14
@wpferguson : I have pushed a possible fix. Let me know if all is good on your side. I was not able to reproduce the issue, so I cannot be sure about the fix.

**Comment by apostel338** [comment] 2023-11-15 13:37
With 4.5.0~git1212.0cb2ac6e-10893.1 (as far as I can see, it should contain the fix?) I get crashes when going from darkroom to lightroom to a new photo, or double click to close darkroom.

[bt.txt](https://github.com/darktable-org/darktable/files/13365322/bt.txt)

**Comment by s7habo** [comment] 2023-11-15 15:15
> I get crashes when going from darkroom to lightroom to a new photo, or double click to close darkroom.
> 
> [](https://github.com/darktable-org/darktable/files/13365322/bt.txt)


I can also confirm this and Ubuntu 22.04

https://github.com/darktable-org/darktable/pull/15644#issuecomment-1812721345

**Comment by TurboGit** [comment] 2023-11-15 16:07
@apostel338 : Sadly the backtrace is not usable.

**Comment by wpferguson** [comment] 2023-11-15 16:08
@TurboGit fix works for me

**Comment by TurboGit** [comment] 2023-11-15 16:12
I have been able to reproduce the other issue, different from the one I have already fixed. Stay tuned...

And thanks for checking this delicate stuff, if it start to be too hard to fix we'll revert anyway.

**Comment by TurboGit** [comment] 2023-11-15 16:16
@apostel338 @s7habo @wpferguson : New fix pushed, do not hesitate to test and report. Thanks!

**Comment by jenshannoschwalm** [comment] 2023-11-15 16:25
Tested right now and no issues any more for now.

**Comment by s7habo** [comment] 2023-11-15 16:38
It has just happened again: :/

[darktable_bt_HNUIE2.txt](https://github.com/darktable-org/darktable/files/13367144/darktable_bt_HNUIE2.txt)

**Comment by TurboGit** [comment] 2023-11-15 16:44
@s7habo : Is that with latest version? I have pushed a fix minutes ago.

**Comment by TurboGit** [comment] 2023-11-15 16:45
@s7habo : Also is that with the same scenario as previously? That is, entering darkroom from lighttable?

**Comment by s7habo** [comment] 2023-11-15 16:46
> @s7habo : Is that with latest version? I have pushed a fix minutes ago.

4.5.0+1214~g98adb4ebd




> @s7habo : Also is that with the same scenario as previously? That is, entering darkroom from lighttable?

Yes.

**Comment by apostel338** [comment] 2023-11-15 16:46
I just got a crash when turning lens correction off with 4.5.0+1214~g98adb4ebd4. But so far not when switching photos.

If I did something wrong with my BT, please let me know how to provide valiable information.

**Comment by TurboGit** [comment] 2023-11-15 16:56
> If I did something wrong with my BT, please let me know how to provide valueable information.

No you did not, the OBS version is not compiled with debug, if you compile yourself you need to use RelWithDebInfo

**Comment by TurboGit** [comment] 2023-11-15 16:56
> Get crashes too when switching lens corretion with 4.5.0+1214~g98adb4ebd4.

Reproduced, seems to happen only with "embedded metadata" method. I'm on it...

**Comment by apostel338** [comment] 2023-11-15 16:56
Open DT
from LT, open a photo
toggle lens correction: seems to work
back to LT
open next photo
toggle lens corretion: mostly crash

if no crash so far, it will at the latest on the third one.

**Comment by apostel338** [comment] 2023-11-15 16:58
> Reproduced, seems to happen only with "embedded metadata" method. I'm on it...

This is not available for my Z 50 raws I'm testing with.

**Comment by wpferguson** [comment] 2023-11-15 17:02
@TurboGit tried latest push and still works for me

**Comment by apostel338** [comment] 2023-11-15 17:24
Just built 65ea777. No improvement here.

Hopefully more usable logs.

[darktable_bt_A78UE2.txt](https://github.com/darktable-org/darktable/files/13367496/darktable_bt_A78UE2.txt)
[gdb.txt](https://github.com/darktable-org/darktable/files/13367499/gdb.txt)

**Comment by apostel338** [comment] 2023-11-15 17:43
Here is one when switching from darkroom to lightroom using the top panel button.

[darktable_bt_8GBRE2.txt](https://github.com/darktable-org/darktable/files/13367656/darktable_bt_8GBRE2.txt)

**Comment by TurboGit** [comment] 2023-11-15 17:58
Ok, should be fixed now... And this time I'm very confident about the fix. Please test again, TIA.

**Closed** 2023-11-15 17:57 UTC
Labels: priority: high, bug: pending

**Comment by apostel338** [comment] 2023-11-15 18:13
Tested on a few tens of photos, no crash so far.

**Comment by s7habo** [comment] 2023-11-15 18:23
Yes, it seems to be good now.

**Comment by TurboGit** [comment] 2023-11-15 18:33
Good to hear, the issue was terrible, I had forgotten to unregister the signal when cleaning up the GUI (leaving darkroom) and so the signal was still applied to de-allocated GUI data :( For this to happen you add to first enter a picture having tone-equalizer enabled and move to some other images from lighttable.
