### ISSUE TITLE
[3.3.0.xxx Duplicate Manager] Main Image in duplicate view not in synch with image in darkroom.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6087] opened 2020-08-25 00:30 UTC
Have an edited image with framing.
Expand duplicate manager.
See image has a frame in there.
Disable framing module.
Frame disappears from main image in darkroom.
Duplicate manager frame is still present. [problem]
Then create a duplicate with history.
Duplicate created  has frame but the original now does not have a frame. [problem]

Double clicking the images in duplicate manager eventually makes the frame disappear. Its a refresh issue on the thumbnails in the history manager.

this is darktable 3.3.0+307~gb360212f1
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by Nilvus** [comment] 2021-06-20 13:01
@chhil: could you reproduce that one in actual master? If no, consider closing this one. Thanks.

**Comment by johnny-bit** [comment] 2021-06-25 20:10
Cannot reproduce on 3.4.1.1 and on ` 3.7.0+1~g05bdc45ac`

Closing. Please comment if you still can reproduce the issue and we'll re-open the issue.

**Closed by johnny-bit** 2021-06-25 20:10 UTC
Labels: no-issue-activity
