### ISSUE TITLE
Styles and copy/paste don't save modules order

### ISSUE THREAD

**Issue by bastibe** [darktable-org/darktable#9813] opened 2021-08-15 10:22 UTC
I create a new style, with the LUT module after filmic, but the module order is not saved. 

I create the style with the "create" button in the Lighttable view, I select the modules "modules order (custom)", "lut 3D (on)", and "filmic rgb (on)", enter a name, and click "save". If I immediately click "edit" on the new style, "modules order (custom)" is not included, and when I apply the style "lut 3D" comes before "filmic rgb", i.e. in the old modules order.

I would expect the style to include the modules order, since I clicked its check mark.

I tried creating a new modules order, but that did not change the behavior.

If I go to the Darkroom and copy (CTRL-C on a thumbnail) and paste (CTRL-V on a thumbnail), the module order is not transferred, either.

I'm using Darktable 3.6.0.1 on Windows 10.

**Comment by elstoc** [comment] 2021-08-15 13:13
This looks like a duplicate of https://github.com/darktable-org/darktable/issues/9523

**Comment by johnny-bit** [comment] 2021-08-15 17:35
Indeed it looks like a duplicate and it was fixed. I don't seem to be able to reproduce on current master.

Since you're using windows can you dare to try either @wpferguson's Windows Insider builds (https://discuss.pixls.us/t/darktable-windows-insider-program-8-8/26355?u=johnny-bit - probably next one will be today) or current nightly (https://github.com/darktable-org/darktable/suites/3501444988/artifacts/83446907)

**Comment by bastibe** [comment] 2021-08-15 18:22
It seems to be fixed in the latest Windows Insider Build. Thank you!

On a second thought, it seems to be fixed in my main install, too. Apparently it happened only intermittently for some strange reason.

**Closed** 2021-08-15 18:30 UTC
Labels: duplicate, bug: fixed
