### ISSUE TITLE
When zooming in culling mode, image is not centered

### ISSUE THREAD

**Issue by dguertin** [darktable-org/darktable#12469] opened 2022-09-11 16:12 UTC
**Is your feature request related to a problem? Please describe.**

I'm a wildlife photographer that makes heavy use of culling mode. I typically take bursts of many shots, and then use culling mode to pick the sharpest/best of the burst. This means I'm constantly toggling between full view and 100% zoom while in culling mode. The issue is that when I toggle 100% zoom, the view zooms to the top left corner of the image instead of to the center. Since most of the time my subject is somewhere near the center, this is an annoyance since I then have to re-center the zoomed images on my subject.

**Describe the solution you'd like**

Is there a way to make darktable default to zooming to the center in this situation? If not, could there be one?

**Comment by ptilopteri** [comment] 2022-09-11 16:46
odd, when I hold <ctrl> and roll the mouse wheel, the image 
remains centered on the mouse pointer
as the OII is seldom in the exact center of image, I prefer the 
current method.

ps: if this satisfies, please close this issue.

**Comment by Nilvus** [comment] 2022-09-11 17:01
Zooming depending on cursor position. You could also distinctly zooming and panning on image with Maj+click or Ctrl+click depending on what you what. See culling part of manual (quick access by clicking ? icon on top bar then on culling view. With 'h' shortcut, you could also see available shortcuts of current view.

Think about closing the issue as what you ask for is possible and more.

**Comment by dguertin** [comment] 2022-09-12 00:47
Yes, Ctrl-mouse wheel keeps the image centered, but I prefer to use keyboard shortcuts, especially when dealing with hundreds of images. I have the "z" key mapped as a shortcut to lighttable/preview zoom 100%, as it is more efficient than scrolling the mouse wheel. But in culling mode, preview zoom 100% zooms to the top left corner of the image, not to the center.

I have looked at the manual on culling view, and those are the shortcuts that I am using. Interestingly, the "preview zoom 100%" shortcut zooms to the center of the image while in sticky preview mode, as it should. It is only in culling mode that "preview zoom 100%" jumps to the top left corner. Ideally, the behavior would be the same regardless of the mode, preferably zooming to the center.

**Comment by dguertin** [comment] 2022-09-12 01:01
Here are some screenshots to illustrate what I mean.
Culling mode with "preview zoom fit" shortcut:
![full2](https://user-images.githubusercontent.com/17552015/189557163-07cf580e-b463-4164-985e-2ae90df28562.png)
I want to look at the birds more closely, so I select "preview zoom 100%", and it zooms to the top left corner:
![zoom2](https://user-images.githubusercontent.com/17552015/189557175-e9e76afa-e518-4761-ba51-3335f4864856.png)
What I would like is to zoom to the center of the image, like this, which I currently need to use the mouse wheel to do (or what I usually do, which is zoom to the top left corner, and then drag the images up and to left to center them):
![center2](https://user-images.githubusercontent.com/17552015/189557181-784199f1-70e6-4aea-9237-2450829fcc7f.png)

Again, this only happens in culling mode. Sticky preview mode zooms to the center.

**Comment by pcanning** [comment] 2022-09-12 02:39
FWIW, when culling I would prefer if it zoomed to the same position as it was last zoomed to.  That way if I have to move the zoomed image away from the center to see the subject it will zoom to the same place in the next image which is likely to still be close the subject when I shot a sequence of images of the same subject, and if not I can zoom out to find the subject and then zoom into that subject using the mouse.

**Comment by dguertin** [comment] 2022-11-14 23:29
Any updates on this? If this is "won't fix" issue, any recommended workarounds while using preview zoom 100% in culling mode?

**Comment by Nilvus** [comment] 2023-01-15 10:35
@AlicVB: what's your view on that?

**Comment by AlicVB** [comment] 2023-01-15 20:30
yes, that would be a great enhancement for sure.
The problem is that when we react to a shortcut, we don't have the cursor position. I think there should be some solution to retrieve it, but that's not straightforward...

**Comment by Nilvus** [comment] 2023-01-16 20:56
I would suggest to consider differently how user interact with culling/preview modes:

1. if keyboard shortcuts are used:
- center by default (by using images sizes).
- but if the user pan on the image (when zoom had been done, for current shown images, keep position on image when zooming
- and so only keep position for current culling view. If the user quit culling, next time reset position to the center of the image

2. if mouse is used to zoom, center depending on cursor position, as it is actually.

**Closed** 2024-01-13 00:17 UTC
Labels: feature: enhancement, scope: DAM, no-issue-activity
