### ISSUE TITLE
Panasonic DC-S5M2

### ISSUE THREAD

**Issue by JLD33** [darktable-org/darktable#16164] opened 2024-01-21 21:11 UTC
Hello, 

Would it be possible that new version of Panasonic DC-S5 that to say the DC-S5M2 be supported. 
I use DARKTABLE for more than 6 years now and would not change for another software.
Thank you
Best regards 
Jean Louis DAGRON

PS : I have contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

I can provide other samples if needed.

**Comment by kmilos** [comment] 2024-01-21 22:51
Duplicate of https://github.com/darktable-org/darktable/issues/13511

Please search before opening new issues.

**Closed by kmilos** 2024-01-21 22:51 UTC
Labels: scope: camera support
