### ISSUE TITLE
Double click no longer resets a setting

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#11427] opened 2022-03-29 13:13 UTC
Ubuntu 20.04 dt 3.9.0+846~gab4f9caaf built today
Previously a double click would restore a setting to a default value, e.g. global brilliance in color balance rgb.
This is no longer happening.  This seems a useful feature, is there a reason for removing it?

**Comment by phweyland** [comment] 2022-03-29 15:00
On debian sid and dt 3.9.0+840~gb2f2158ce this still work for me.

**Comment by elstoc** [comment] 2022-03-29 20:11
I'm also unable to reproduce this on Arch Linux and current master 3.9.0+866~g91de3c063

**Comment by Nilvus** [comment] 2022-03-29 20:15
Can't reproduce too. Double-click works great too on my side, as usual and same master than @elstoc. On Debian Sid

**Comment by RawConvert** [comment] 2022-03-29 21:29
Well I've gone back to check this out further, and I'd say we're all partly right and partly wrong.
I think mouse behaviour must have changed recently.

(A) 3.9.0+226 and earlier
This is the behaviour I'm used to, as follows -
click - alters the setting of a slider
dbl click on the "triangle" or the digits making up the value - resets the value
right click - invokes the wagging tail widget for fine adjustment.

(B) 3.9.0+846
dbl click on the triangle - resets the value
dbl click on the digits - treated as two ordinary clicks
click on the slider "line" - alters value
click on the digits - same as right click above
right click on triangle or digits - same as right click above

So what's happened for me is that I used to reset by double clicking in the area of the current value and it was fine.  But now you have to be quite particular and target the triangle.  Similarly before, you could click in a decent sized band above the slider "line" to change value.  Now it is fussy and you have to be on or close to the line.

I can't see the value of this change - if indeed it's deliberate.

**Comment by elstoc** [comment] 2022-03-29 22:49
This was done on purpose in #10499 and was made a bit less bad in #11257 but I also preferred it when the whole slider was clickable.

**Comment by RawConvert** [comment] 2022-03-30 11:21
I think restricting the clickable areas is a bad move and have commented in #10499

**Comment by elstoc** [comment] 2022-04-05 21:36
@RawConvert hope you don't mind but I've raised a separate issue #11462 with a more complete description of the request so that it's a bit more visible, and I'm going to close this one in favour of that one. Feel free to add a comment to the new issue.

**Closed by elstoc** 2022-04-05 21:36 UTC
Labels: feature: redesign, scope: UI

**Comment by RawConvert** [comment] 2022-04-07 09:04
Ok
