### ISSUE TITLE
Reset preset does not work for tagging module (and others?)

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9615] opened 2021-07-24 12:31 UTC
**Describe the bug/issue**
The "reset" button of the tagging module does not work. In my understanding it should revert all changes made to the currently active preset.

**To Reproduce**
1. Select some tags 
2. Create a new preset from those tags
4. add some more tags
5. reset to preset
Nothing changes

**Expected behavior**
Only tags present in the preset should remain.
To return to the tags of the preset, reapply the preset by selecting it from the list of presets.

**Side Note**
I think I experienced a similar behavior in the export module. But when I tried again I could not reproduce it anymore...

**Platform**
* darktable version : list+305~gc1925dcc6
* OS                : Manjaro Linux

**Comment by johnny-bit** [comment] 2021-07-24 13:02
Tags are in db and attached to images. Tag module presets have no point in existing at all. the "reset" button simply clears up entry and resets view.

IMO. Works as intended.

Closing since this is NOT an issue. You might want to fill a feature request but I have no idea what are you trying to accomplish with tag presets.
Also: version `list+305`... what branch are you on and why?

**Closed by johnny-bit** 2021-07-24 13:02 UTC

**Comment by Solarer** [comment] 2021-07-24 14:04
@johnny-bit
I just recompiled from master commit c1925dcc6dee06fd0acd5a504f6817d7f3413425 and have no idea why it is displayed that way. It was not like this a few weeks ago.

I could think of some use cases for tagging presets but the question is rather: since you CAN create tag module presets shouldn't the reset button do the same thing as in all other modules?

Could you please explain once more what the reset button should do in your opinion? I played a little bit with it and it seems to me like it is not doing anything.

**Comment by johnny-bit** [comment] 2021-07-24 14:38
You can create presets to any module I think. Doesn't mean it's useful. Reset clears text entry.

**Comment by johnny-bit** [comment] 2021-07-24 20:40
@phweyland - tagging you If you want to take a look...

**Comment by phweyland** [comment] 2021-07-25 21:37
The @johnny-bit answers are correct.
"reset" has nothing to do without "preset".
In lighttable "reset" just sets the module back to its default state (may be a bit different in darkroom). Clear the entry field, completion, etc ...
It does not make any change on the selected images. 

> I just recompiled from master commit [c1925dc](https://github.com/darktable-org/darktable/commit/c1925dcc6dee06fd0acd5a504f6817d7f3413425) and have no idea why it is displayed that way. It was not like this a few weeks ago.

**Comment by Solarer** [comment] 2021-07-26 21:35
Thanks for the clarification. I saw that the reset button did reset something in the export module but you are right - it is only resetting it to the defaults - not to any presets. My fault. Can stay closed!
