### ISSUE TITLE
File descriptor exhaustion with dangling references to /dev/bus/usb/XX/YY?

### ISSUE THREAD

**Issue by bjornedstrom** [darktable-org/darktable#8974] opened 2021-05-15 13:46 UTC
**The bug/issue**
Hi Darktable developers - thank you so much for spending time building and improving this fantastic software! I really appreciate your hard work! Apologize in advance if this is a gphoto and not a darktable issue, I'm not familiar with darktable internals.

I'm running Ubuntu 18.04 and the latest Darktable 3.4.1 package provided by the OpenSuse repository (which provides packages for OpenSuse, Ubuntu, Debian and Fedora).

Leaving Darktable running for a week or two of active photography eventually exhausts the max file descriptor limit, as I insert and remove the USB cable and import from the PTP camera. This manifests itself as warning/error messages in the darktable UI, like "can't write temporary file, max limit reached" or similar. The culprit:

    $ ulimit -n
    1024
    $ lsof -p 17887 # darktable pid
    ...
    darktable 17887 bjorn   39u      CHR            189,265      0t0       676 /dev/bus/usb/003/010 (deleted)
    darktable 17887 bjorn   40u      CHR            189,265      0t0       676 /dev/bus/usb/003/010 (deleted)
    <snip>
    darktable 17887 bjorn 1022u      CHR            189,277      0t0       694 /dev/bus/usb/003/022 (deleted)
    darktable 17887 bjorn 1023u      CHR            189,277      0t0       694 /dev/bus/usb/003/022 (deleted)

Note "(deleted)": when the camera is connected, a few file descriptors are active (not "(deleted)") until the camera is disconnected from USB. The resources are however not cleaned up afterwards.

Restarting darktable solves the issue for a while.

**To Reproduce**
1. Attach your camera to USB and import photos
2. Repeat the first step many times, depending on ulimits
3. Eventually file descriptors are exhaused as above

**Platform**
* darktable version : 3.4.1.1~git0.3641764ed-1
* OS                : Ubuntu 18.04 / 4.15.0-140-generic
* Linux - Distro    : buntu 18.04
* Desktop           : Gnome 3.28.2
* GTK+              : 2.24.32-1ubuntu1 and 3.22.30-1ubuntu4

**Comment by johnny-bit** [comment] 2021-05-15 14:42
@jenshannoschwalm could this be caused by constant probing or more of gphoto2 not closing resource properly?

**Comment by jenshannoschwalm** [comment] 2021-05-15 16:19
It's not the constant probing.
It seems to be true that the device is not closed correctly after plugging out the cable. Don't know what the reason is, maybe it's gphoto not handling this ... will try to find out.

**Closed** 2021-05-24 19:18 UTC
Labels: scope: hardware support, scope: software support
