### ISSUE TITLE
Removing a folder does not reliably remove the images

### ISSUE THREAD

**Issue by pfheatwole** [darktable-org/darktable#8433] opened 2021-03-07 22:03 UTC
**Describe the bug/issue**

Creating a rule in the "collect images" with a "folders" criteria will provide a folder tree of all the folders that contain images in the darktable library. Right-clicking a folder and choosing "remove" should remove all the images in that folder (and its subfolders) from the darktable library. The problem is that sometimes the folder is (temporarily) removed from the folder tree, but the images are not removed.

Because the images are still in the library, the folder will reappear. For example, if you change the "collect images" rule from "folders" to some other criteria, like "film roll" then back to "folders" then the recently removed folder will reappear. The folder will also reappear if you restart darktable.

**To Reproduce**

1. Create a folder hierarchy:

  ```
  Test
  ├── Subdir 1
  │   ├── file1.dng
  │   ├── file2.dng
  │   └── file3.dng
  └── Subdir 2
      ├── file4.dng
      ├── file5.dng
      └── file6.dng
  ```

2. Import the top-level folder `Test` with "import folders recursively" enabled.
3. In the collect images pane, double click `Subdir 1` to open `file[123].dng` in lighttable.
4. In the collect images pane, right-click `Subdir 2` and select `remove`.

**Expected behavior**

A popup asking "do you really want to remove 3 images from the collection?". Clicking "yes" would remove `file[456].dng` from the darktable library, and `Subdir 2` would be removed from the folder tree.

**Actual behavior**

The folder `Subdir 2` is removed from "collect images", but the images are not removed. Double clicking the folder `Test` shows `file[456].dng` in lighttable even though the folder is missing in the tree. If the "collect images" rule is changed from "folders" to some other criteria (eg, "film roll") and back again, then `Subdir 2` will reappear.

**Platform**

* darktable version : 3.4.1
* OS                : Linux - kernel 5.10.20
* Linux - Distro    : Fedora 33
* Memory            : 24GB
* Graphics card     : Intel HD 530

**Extra information**

This test is what I can reproduce, but I think the actual bug is a little more complicated. In this test setup, double clicking the `Test` folder and clicking "remove" is reliably removing all six images, but in my actual library I had some folders that would not remove the images even if I opened the folder first. For now I'm simply double clicking the folder I want to remove, pressing `Ctrl-a` to select all the images in lighttable, then clicking "remove" in the "selected images" pane; those steps have been reliably removing the images from the library, and the folder naturally disappears once the images have been removed.

**Comment by ptilopteri** [comment] 2021-03-07 22:24
"remove" merely removes the selected directory/image from the "collection".
DELETE is the term you want which is a file system operation rather than a
data-base/collection operation

**Comment by pfheatwole** [comment] 2021-03-07 22:27
@ptilopteri I'm not trying to delete the images from the filesystem. I am "removing" entire folders of images from the darktable library.

**Comment by pfheatwole** [comment] 2021-03-07 22:46
I forgot to mention: is it possible that this is related to the fix suggested in https://github.com/darktable-org/darktable/issues/4635#issuecomment-610388226 ?

@elstoc wrote:

> This is because `view_popup_menu_onRemove` (`collect.c`) populates main.selected_images with all of the images in the folder but then calls `dt_control_remove_images` (`control.c`) which ignores this and instead calls `dt_view_get_image_to_act_on`. Probably need some way to force this function to use selected_images.

That might explain why I have to open the folder in lighttable before calling "remove" on the folder.

**Comment by AlicVB** [comment] 2021-03-08 18:30
hmm... I can't reproduce, but I think there have been changes in this area recently, as in master, as soon as I right-click on a folder, the folder content is shown (same effect as double-click). Also double-click on a folder doesn't show the images of its subdirs...

By any change, can you test with current master ?

**Comment by pfheatwole** [comment] 2021-03-08 18:45
Nice, can confirm your experience on Fedora 33 Using `darktable-3.5.0~git1377.893e45a13-5511.1.x86_64.rpm`. Right-clicking has the effect of double clicking, and removing `Test` in this case removes all pictures in `Test` and all subdirs. (I did have to tweak the test case since it looks like newer builds change how sub-directories are handled, but overall this behavior is working as expected. Not to mention the development build is FAST, wow!)

I'll leave this issue open in case anybody with the current release searches for this bug, but feel free to close it if that's more in-line with how darktable issues are handled. Thanks!

**Comment by Nilvus** [comment] 2021-03-08 19:12
> I'll leave this issue open in case anybody with the current release searches for this bug, but feel free to close it if issues are supposed to track development. Thanks!

As issues are for track development, I close this. Thanks for testing and reporting. Issues closed can be found by searching if needed.

**Closed by Nilvus** 2021-03-08 19:12 UTC
