### ISSUE TITLE
[darkroom] filmstrip jumps to first pic when changing rating-view

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5735] opened 2020-07-11 12:24 UTC
**Describe the bug**

When changing the rating view e.g. between 3* back to 1*, the filmstrip jumps to first pic in collection.

**To Reproduce**
1. Go to 'darkroom' with a collection having approx. 50 pics in 3* and many more in 1*. place your fokus somewhere in the middle of 3* selection
2. Change from 3* down to 1*
3. See error

**Expected behavior**
Same than lighttable, the focus shall stay centred from where the user left one rating to another (if in the new collection is no such pic, stay very near to that position in the collection)

**Platform (please complete the following information):**
* darktable version : 3.1.0+2448~g4b77a5410
* OS                : Linux - kernel 5.7.7-gentoo
* Distro            : Gentoo Base System release 2.6
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.100-r1
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.20
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by AxelG-DE** [comment] 2020-07-12 10:27
@AlicVB may I ping you here? :slightly_smiling_face:

**Comment by AlicVB** [comment] 2020-07-13 17:16
@AxelG-DE : this is more a feature request than an issue, as it's not implemented now (in filemanager too) currently, when you refilter the collection, the offset is keep only if the image is still in the new collection, otherwise, it's reseted to beginning.

Implementing the case you want would require quite a lot of work and I'm not even sure there's good way to do it as the collection may very well have changed completely... Need more thought !

I've just fixed a small glitch in filmstrip where in this case, the filmstrip is moved to the right with no centered image.

**Comment by Nilvus** [comment] 2020-07-14 15:25
I would add that filmstrip display is also related to filters settings on top bar, so this will work differently regardless of filters settings and that's quite normal. I'm not really sure to understand what you describe so If I'm not on, please excuse me. But on what I understand, you change filter so filmstrip display is updated to that filter change, so just what is wanted. So, as @AlicVB says: if the image selected before filter change is always visible, that's normal to see that image always selected but if not, so that seems normal for me that darktable, as he has no selected image displayed, go back to first picture.

**Comment by AxelG-DE** [comment] 2020-07-16 15:11
> @AxelG-DE : this is more a feature request than an issue, as it's not implemented now (in filemanager too) currently, when you refilter the collection, the offset is keep only if the image is still in the new collection, otherwise, it's reseted to beginning.

Which is very annoying in big collections :-)

My workflow is (each vacation trip I come back with way above 1.000 pics): 
- I import with 0 stars,  (for time being we merely consider "=")
- select in two rounds up to 2*. 
- Those 2* pics I will edit. 
- After editing they will be changed to 3*. 
- Later two more rounds of selection 4* and 5* acc. to foto-quality. 

From time to time I switch either from =3* to =2* or from =3* to >=2* or <=3* to find another pic (maybe a sharper one). 
That is the moment it gets annoying, when you have to find back, where did you come from....
If I am at pic-ID e.g. 3500 and I change from =3* to =2*, indeed there is no pic-ID 3500 but MAYBE a pic-ID  3487 and maybe a a pic-ID  3698. Then I would appreciate to be located close to those....

From my perspective I think my workflow is not that special and I am surprised, nobody else speak that out...

> Implementing the case you want would require quite a lot of work and I'm not even sure there's good way to do it as the collection may very well have changed completely... Need more thought !

I see....
Maybe also my description here is still not good enough, I am 40% with my mind still in my job, sorry for that...

> I've just fixed a small glitch in filmstrip where in this case, the filmstrip is moved to the right with no centered image.

Actually I also faced once, filmstrip moved totally to the left and no pic centred or highlighted...

@Nilvus Did my explanation make it a little more clear and a little sense? I hope so otherwise I need to spend more energy for proper explanation :)

**Comment by Nilvus** [comment] 2020-07-16 16:08
@AxelG-DE: your explanation si clear now. I found your workflow quite complicated and it's probably not used that way by a lot of people (but I could be wrong) and maybe that why nobody else speak about that.

I never change ratings on darkroom. I always set them on lighttable and often with culling mode by comparing images. But I'm someone not conservative so I always remove lot of photos (and sometimes come back to old photos and delete some). So, even if I have 2000 pics, I rarely keep a lot more than a hundred ones, sometimes less. I then rate them and after edit them. And I never use ratings filters on darkroom.

**Comment by AxelG-DE** [comment] 2020-07-16 17:42
My explanation is **not** good enough, LOL

Mainly I do the rating in lighttable too just in between the edit I do it sometimes in darkroom and sometimes in lighttable. Both with same annoying result :-)

**Comment by Nilvus** [comment] 2020-07-16 17:47
> My explanation is **not** good enough, LOL
> 
> Mainly I do the rating in lighttable too. Just in between the edit I do it sometimes in darkroom and sometimes in lighttable. Both with same annoying result :-)

Your explanation is good enough, be sure for that. Just different view of workflow. Just to be sure, in lighttable, you have only filmstrip on culling and preview view and of course, filmstrip works the same way on all views. To be more precise, I personally rarely use filmstrip, and when using it, it's only on darkroom.

**Comment by AxelG-DE** [comment] 2020-07-16 18:18
IIRC the issue is the same with the shown pics in lighttable view's main window...

**Comment by EC1000** [comment] 2020-07-28 20:57
It would be a nice addition to be able to keep the "nearest" image selected, when changing rating and even collection. 

> I found your workflow quite complicated and it's probably not used that way by a lot of people (but I could be wrong) and maybe that why nobody else speak about that

I use kind of a similar workflow. Not exactly the same, but I also do several rounds of rating to add stars or sometimes remove one/reject (with more or less a target proportion bewteen the number of each ratings). Thus when changing between rating (>= or =, number of stars), I also sometimes "lost my position". For example just when changing between 2* and 3* ; my "workaround" is to go on a 3-star picture before changing the filter, but being able to not mind about that would indeed be a nice improvement. 

In can also happen with collection (example with color label, which may have a signification like rating to define a "sub-collection"), even if that is less often for me.

**Comment by pahl34** [comment] 2020-09-27 12:34
To be honest, I actually have the same issue quite regularly. Consider this situation, which I often run into: 
I have imported a bunch of images and rated them already in lighttable, e.g. everything > 2* I would like to consider for editing in darkroom. Before starting to edit, I want to be sure I did not miss any "good picture", so I set the lighttable filter to 'all photos < 2*". Now I only get the pictures I had eliminated before. Whenever I decide that there is a picture I actually want to consider for editing, I'll give it a 2* rating. The picture will get removed from my current selection and the focus jumps back to the first picture matching the still active 'below 2*' filter.

I understand that this may be hard to change/fix, so is there maybe a better/more common lighttable workflow for picking the pictures worth editing?

**Comment by pahl34** [comment] 2020-10-02 14:37
I now was able to reproduce the problem again:
- Culling mode with 2 pictures shown next to each other
- Filter "all except rejected" is active
- If I reject the right picture of the two shown pictures, everything behaves as expected (the next picture is shown instead)
- If I reject the left picture, however, the view "jumps back" to the very first picture in the selection.

To me, this seems to be a bug rather than a missing feature, as it works in one way but does not work the other way.

**Comment by Nilvus** [comment] 2020-10-02 14:58
@pahl34: what you describe about rejecting left picture goes to the very first picture seems more a bug than a feature. I always use culling same way as yours (but not this week) and I don't remember having such issue.

Could you precise which culling mode you use: dynamic or fixed one? And if possible, could you reproduce that on both dynamic and fixed mode or only one?

**Comment by pahl34** [comment] 2020-10-03 17:33
@Nilvus: Thanks for your quick reply. I use fixed zoom to reproduce the described issue.

I just tried to reproduce it as well in dynamic zoom mode, however I think I do not understand how this mode works at all, or I cannot get it to work. Whenever I enter that mode, there is a message "no image selected". However, I do not find a way to select any image from the filmstrip on the bottom, except "Ctrl+A" which selects all images in the current selection and displays them in the main pane (in small size, so all of them fit in). Then, if I try to zoom using "Ctrl + Mouse Wheel", nothing happens, but I get a message "zooming is limited to 4 images".
Thus, I was not able to try to reproduce the problem described above (the one I have in fixed zoom mode), because I never reach the situation in which it would occur in dynamic zoom mode.

**Comment by Nilvus** [comment] 2020-10-03 19:02
@pahl34: so first I suggest you to read 3.0 and 3.2 articles in darktable.org/blog. That will help you understand those modes and some shortcuts for filmstrip.
That will also, probably, learn you some great things about darktable and how to better use it.

**Comment by pahl34** [comment] 2020-10-04 11:39
@Nilvus: Thanks for the hint and sorry for having wasted your time. I read the articles you mentioned and I now understand much better how culling mode works (it's actually great!). I think my main problem was to not know about the Alt+Click in order to start a new selection on the film strip, but there was surely much more for me to learn from the articles.
Before, I had only checked the [section about culling](https://darktable.gitlab.io/doc/en/lighttable_chapter.html#lighttable_culling) in the 3.0 manual but in future I'll make sure to read all available documentation and blog entries more carefully before posting here!

I have to admit that now I cannot reproduce the problematic behavior anymore, neither in file manager, nor in fixed or dynamic zoom modes of culling. While I am very sure that I actually reproducibly had this behavior earlier, I now have to assume that the reported error was caused by another operating error on my part. Probably the software was actually behaving as designed but I just misinterpreted its behavior because of my lack of understanding.
In case I'll ever find out what steps exactly caused the behavior, I'll post again here - then we could still see whether there might be a bug, but for now (at least until I can prove otherwise) I will consider my report a "false alarm".

Thanks for your help and sorry again for posting before fulling understanding how the interface works.

**Comment by AxelG-DE** [comment] 2020-10-04 13:44
@parafin 
why my issue got closed? The discussions between Nilvus and pahl34 do not actually solve my problem

**Comment by parafin** [comment] 2020-10-04 14:19
sorry

**Comment by AxelG-DE** [comment] 2020-10-04 14:59
No problem 🙂
Thanks for reopening.

**Comment by pahl34** [comment] 2020-10-04 16:34
Sorry for having caused confusion here. 

I just now realized after reading again AxelG-DE's initial post, that the original issue/feature request is something different than the "maybe-bug" I described. So I should not have posted in this discussion in the first place, but, if at all, opened a new one.

So for any further discussion about the original topic please do not get confused by my postings, they were actually off-topic in this context.

**Comment by pahl34** [comment] 2020-10-18 15:26
I think I found out what my problem posted in my comment from 02. of october was and documented it in issue #6566.

**Comment by Nilvus** [comment] 2020-10-18 17:40
@pahl34: so maybe closing this issue would be good. Issue #6566 is clear (title is just hard to read!) and @AlicVB already assign it to him. That means he will check that.

**Comment by pahl34** [comment] 2020-10-18 17:53
I believe that issue 5735 describes another problem. I think it is about the behavior when changing the view filter, not when changing the rating of an image. It was my mistake to think it was describing the same problem I was facing.It even had been closed already some weeks ago after my postings  but the original author of that issue complained that it was indeed something else and then it was reopened.So I think 5735 should stay open - at least it should not be closed because of my findings. 
-------- Ursprüngliche Nachricht --------Von: Nicolas Auffray <notifications@github.com> Datum: 18.10.20  19:40  (GMT+01:00) An: darktable-org/darktable <darktable@noreply.github.com> Cc: pahl34 <michael.schimpf@gmx.de>, Mention <mention@noreply.github.com> Betreff: Re: [darktable-org/darktable] [darkroom] filmstrip jumps to first pic when changing rating-view (#5735) 
@pahl34: so maybe closing this issue would be good. Issue #6566 is clear (title is just hard to read!) and @AlicVB already assign it to him. That means he will check that.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/darktable-org/darktable/issues/5735#issuecomment-711323960",
"url": "https://github.com/darktable-org/darktable/issues/5735#issuecomment-711323960",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Closed** 2020-12-31 17:47 UTC
Labels: feature: enhancement, no-issue-activity
