### ISSUE TITLE
FR: Generate previews from GUI for current  directory / film roll

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#9472] opened 2021-07-09 11:04 UTC
**Is your feature request related to a problem? Please describe.**
Problem:
I import 100-200 photo's.  Before culling I need to generate the previews or the culling is painfully slow.  
I scroll back and forth, back and forth, back and forth... untill all previews are generated. This is tedious and it feels like a waste of time.

**Describe the solution you'd like**
I would like a menu option or button: "Generate previews of the current directory"  with an indication of which sizes I need generated.
It should not block the GUI so I can start culling while the previews are being generated.

**Alternatives**
I have tried the commandline preview generator. It works.  But it is an all-or-nothing tool.  
When you have used DT for a while, you may have thousands of pictures.
You can only generate previews for *everything*  and it blocks the database while it's working.
I don't want to generate all possible sizes for all these images - just the most recent directory.  And I want to start culling while the process runs.

**Additional context**

**Comment by johnny-bit** [comment] 2021-07-09 12:15
Duplicate of #5171

**Closed by johnny-bit** 2021-07-09 12:15 UTC
Labels: duplicate
