### ISSUE TITLE
Negadoctor - lightroom - selective copy/paste bug (Darktable 4.4.2)

### ISSUE THREAD

**Issue by scrste** [darktable-org/darktable#15857] opened 2023-12-11 17:04 UTC
### Describe the bug

Used darkroom-negadoctor to edit a color image of a black-and-white negative, selecting b&w film setting in negadoctor (image is converted to b&w).
Went to lightroom to selectively copy/paste the negadoctor setting to more color images which are actually b&w negatives.
The BUG is that the b&w film setting does not paste -- the other images remain as color images even after the negadoctor settings are applied.

### Steps to reproduce

Start with a color image of a b&w negative.
Use negadoctor to edit the image (select B&W film, crop, etc)
Return to lightroom, selectively copy the negadoctor settings from the edited image
Selectively paste the negadoctor settings to other images (color images of b&w negative.
Notice that the pasted images remain color images.

### Expected behavior

Pasted images should match donor image and become b&w.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Version	10.0.22621 Build 22621

### Describe your system?

Ryzen 7 5700x
32GB RAM
Gigabyte B450 AORUS M  
NVIDIA GeForce GT 1030

### Are you using OpenCL GPU in darktable?

None

**Comment by TurboGit** [comment] 2023-12-11 17:35
Cannot reproduce in master.

**Comment by pehar1** [comment] 2023-12-14 08:22
Same here with 4.5.0+1447~g6f7d326972 on Linux / Ubuntu 22.04
Selective copy of _negadoctor_ settings works correctly for me in lighttable and darkroom.

**Comment by scrste** [comment] 2023-12-18 01:25
When I selected "black and white film" in negadoctor on one image and 
then did a selective copy of negadoctor settings and selective paste on 
other images, I expected the film type selection of "black and white 
film" to be copied during the selective paste and it did not work that 
way. It may well be that my expectation of how that should work is wrong 
and my identifying this as a problem was a mistake and perhaps the issue 
should be closed out, I'd be fine with that. There are other ways to do 
what I want to do.




------ Original Message ------
From "pehar1" ***@***.***>
To "darktable-org/darktable" ***@***.***>
Cc "scrste" ***@***.***>; "Author" ***@***.***>
Date 12/15/2023 4:02:19 AM
Subject Re: [darktable-org/darktable] Negadoctor - lightroom - selective 
copy/paste bug (Darktable 4.4.2) (Issue #15857)

**Comment by pehar1** [comment] 2023-12-18 08:16
> I expected the film type selection of "black and white film" to be copied during the selective paste

This is exactly how it works for me (now on 4.7.0+5-gd2a72895c3). It can be done via module _"history stack"_ in lighttable or by using the shortcuts _CTRL-SHIFT-C_ (selective copy) and _CTRL-SHIFT-V_ (selective paste) in lighttable and darkroom.
See also https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/lighttable/history-stack/ for the description of the module _"history stack"_ in lighttable.

**Comment by ralfbrown** [comment] 2024-06-25 09:29
Can't reproduce with 4.8.0 either.

Closing because nobody has been able to reproduce and the OP hasn't responded in over six months.

**Closed by ralfbrown** 2024-06-25 09:29 UTC
Labels: scope: UI, scope: image processing, no-issue-activity
