### ISSUE TITLE
Filmic preset/style overwrites ALL values, not just the changed ones

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#12145] opened 2022-07-07 08:54 UTC
**Describe the bug/issue**
Latest Darktable V4.0.
I take a clean image in the new workflow. Filmic is automatically applied.
I want to create a style with a changed 'Lattitude' value. 
I change the Lattitude.
I create a style or preset.

** behaviour:**
When I apply this style/preset to another image, it applies (copy-paste) all values including the black/white point values. 
This overwrites the auto-calculated settings for those values with those of the first image - which make no sense on the 2nd image.

**Expected behaviour:**
I want the style to copy/paste/overwrite only the settings which are changed from the default.
If I changed parameter X to create the style, I want the style to alter only that parameter.

**Additional context**
Suggested fix which would improve everything:
I noticed this when I export the setting:  <op_params>gz02eJybNXOyo7Hx5wMPq6Y4MDA4QPEJJwiGgFlANfrLKmxAYvY/kxz+/5/qdPZMjz1M/uwZHztGIM0MxIxQMUYoZoJiBigNAPmEF0E=</op_params>
This seems like a binary blob which is imported in a module. 
It makes more sense to use XML here. Spell out the parameters.  That way you can include ONLY parameters that were actually changed from the default.
Optionally, add an attribute per parameter to indicate if it should be overwritten, or possibly only overwritten if it was not changed from the original.
Example:
<op_params>
    <whitePoint update='no'>4.60</WhitePoint>
    <Lattitude update='yes'>75</Lattitude>
</op_params>

**Comment by elstoc** [comment] 2022-07-07 11:37
This is not necessarily easy to do and has been requested before. The auto-calculation in filmic only happens when the module is first added to the pipe and it's not easy to redo it within a preset.

I think this should probably be closed as a duplicate of https://github.com/darktable-org/darktable/issues/8861

**Comment by rekcodocker** [comment] 2022-07-07 12:14
How about the other way around? There is no need to re-calculate the parameters, if they are simply not overwritten. 
I think this applies to all parameters which values are calculated based on the Exif or image.

A similar bugfix was done for Lens Correction and Denoise - those had the profiles overwritten when a preset was applied (for examply, it would apply a noise-profile which did not match the Exif), but that has been fixed.  They now only apply the parameters that the user sets, not those that are based on the Exif or the image.

(see "additional context" above where I suggest a solution).

**Closed** 2022-07-07 12:43 UTC
