### ISSUE TITLE
Add white balance for Panasonic Lumix DC-G9M2

### ISSUE THREAD

**Issue by twjacobs** [darktable-org/darktable#16000] opened 2023-12-31 22:14 UTC
[darktable-whitebalance-20231231.tar.gz](https://github.com/darktable-org/darktable/files/13802299/darktable-whitebalance-20231231.tar.gz)

**Comment by kmilos** [comment] 2024-01-01 01:35
Duplicate of https://github.com/darktable-org/darktable/issues/15703

Please search before opening new issues.

**Closed by kmilos** 2024-01-01 01:35 UTC
