### ISSUE TITLE
Lighttable image not in synch with darkroom image when an older edit's deprecated channelmixer is turned off.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7159] opened 2020-12-02 07:24 UTC
On current master.

File that was edited with channel mixer prior to the current channel calibration.

Image has a border and is black and white.
Double click image in lighttable.
In darkroom, turn off framing and deprecated channel mixer.
Now image is without border and is in color in darkroom.
Go to lighttable, the image is still black and white with border.
Go back to darkroom.
Compress history.
Do **note** that there is no indicator for channel mixer being turned off, just the "x" indicating its deprecated)
Go back to lighttable, the image is now without a frame and is in color.

For some reason, maybe the deprecated module turning off is not triggering the update for the cached images and not triggering the modules following it in the pipeline( e.g. framing).

![History](https://user-images.githubusercontent.com/1119439/100841360-31814f80-349d-11eb-86fc-92ba221439e8.gif)

**Comment by chhil** [comment] 2020-12-02 07:34
Also once channel mixer is turned off.
You go to lighttable and still see b/w image, then go to darkroom and do a ctrl+z to re-enable channel mixer, it does nothing.

However, when channel mixer is turned off and then immediately ctrl+z is done, the channel mixer gets re enabled.

**Comment by chhil** [comment] 2020-12-11 03:30
Bump.

**Comment by johnny-bit** [comment] 2020-12-28 19:27
Indeed i can confirm - It's enough to enable channel mixer (eg via deprecated modules group) and visibly change something + something non-deprecated on top -> you'll see updated in lighttable. Go then to darkroom and disable channelmixer, then return to lighttable -> the thumbnail is not updated...

**Comment by TurboGit** [comment] 2020-12-28 20:44
@johnny-bit : cannot reproduce, any more precise step by step ?

**Comment by johnny-bit** [comment] 2020-12-28 20:57
OK, here's how I made it reappear:

1. make virgin dupliacate of image (from lighttable)
2. enter darkroom and add deprecated module -> channel mixer and make visible adjustment (i for example made sky pink)
3. crop image to apply visible non-deprecated module change.
4. go back to lighttable and see that thumbnail shows image is modified
5. go back to darkroom
6. disable channel mixer
7. go back to lighttable and see that the thumbnail is not modified (looks exactly like on step 4)

creating duplicate from produced image creates proper thumbnail
compressing history on produced image changes nothing.

dunno what's going on.

**Comment by TurboGit** [comment] 2020-12-28 22:53
Ok, reproduce and also with a non deprecated module. So this is more general and match the code I've been reading....

**Comment by TurboGit** [comment] 2020-12-29 09:15
Should be fixed in  #7532. In fact this is not related at all to deprecated module but a wrong code to compute a hash of the actual dev for an image. A similar bug was present when using multiple instances.

**Closed** 2020-12-29 14:13 UTC
Labels: bug: pending, priority: medium, reproduce: confirmed, scope: UI
