### ISSUE TITLE
GIMP no longer will open raw files

### ISSUE THREAD

**Issue by FoutsSA** [darktable-org/darktable#16186] opened 2024-01-26 00:03 UTC
### Describe the bug

I installed darktable 4.6 from 4.4.2 and now after I edit a picture in darktable and close it gimp ver 2.10.36 complains there is now program to open raw file. I am running windows 10 ver.22H2 build 19045.3930

### Steps to reproduce

1 update darktable from 4.* to 4.6
2 Open and edit raw file in updated darktable 
3 Close the file and gimp will open but complains no program is installed to open raw files.

### Expected behavior

darktable should open the raw file in my case NEF files and when closed gimp should open.

### Logfile | Screenshot | Screencast

Opening 'C:\Users\SAFouts\Pictures\Nikon Transfer 2\124\_DSC6405.NEF' failed: There is no RAW loader installed to open 'Raw Nikon' files.

GIMP currently supports these RAW loaders:
- darktable (http://www.darktable.org/), at least 1.7
- RawTherapee (http://rawtherapee.com/), at least 5.2

Please install one of them in order to load RAW files.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

windows 10 ver.22H2 build 19045.3930

### Describe your system?

32 gigs of RAM 

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

4095MB NVIDIA GeForce GTX 1070 (MSI) ver 31.0.15.4633

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This only started with darktable 4.6

**Comment by gi-man** [comment] 2024-01-26 00:51
Duplicate of https://github.com/darktable-org/darktable/issues/15968

Will be fixed when we merge PR https://github.com/darktable-org/darktable/pull/15973

**Comment by victoryforce** [comment] 2024-01-27 06:51
@FoutsSA Since this is a duplicate, I'm closing it. If you are interested in tracking the resolution process, you can subscribe to the issue mentioned above. One way or another, this problem should be fixed in release 4.6.1.

**Closed by victoryforce** 2024-01-27 06:51 UTC
Labels: duplicate

**Comment by FoutsSA** [comment] 2024-01-27 20:11
Thanks much for letting me know, appreciate you guys.

Steve
