### ISSUE TITLE
Darktable 4.4.2 fails to execute on Ventura 15.5.1

### ISSUE THREAD

**Issue by i3oc9i** [darktable-org/darktable#15087] opened 2023-08-20 08:09 UTC
### Describe the bug

After installing darktable with brew, the application does not not start. MacOs reports a damaged image.

![Screen Shot 2023-08-20 at 10 00 48 AM](https://github.com/darktable-org/darktable/assets/4766500/7f6112ba-4588-4e23-8b9e-4e07e57cc651)

### Steps to reproduce

> brew install darktable
```
==> Downloading https://github.com/darktable-org/darktable/releases/download/release-4.4.2/darktable-4.4.2-arm64.dmg
==> Installing Cask darktable
==> Moving App 'darktable.app' to '/Applications/darktable.app'
🍺  darktable was successfully installed!
```

### Expected behavior

darktable start.

### Where did you install darktable from?

distro packaging

### darktable version

4.2.2

### What OS are you using?

Mac

### What is the version of your OS?

Ventura 13.5.1

### Describe your system?

Mac studio M1

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment] 2023-08-20 08:24
Duplicate of #14746 

Please search before opening new issues

**Closed by zisoft** 2023-08-20 08:24 UTC
