### ISSUE TITLE
[3.2.1] culling view dangerous behaviour while trashing photos

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#6625] opened 2020-10-24 11:19 UTC
darktable 3.2.1. In culling view, if you click on one photo and you click trash button, darktable will trash the entire group of images. It is not possible to select one single image.

**Comment by AxelG-DE** [comment] 2020-10-24 12:24
Similar thing applies to star rating. I'm not sure is bug or feature. But I suggest you press "r" for reject and after culling go to filemanager mode and set to rejected once and delte all at once

**Comment by quovadit** [comment] 2020-10-27 09:43
I stumbled upon a quite similar strange behaviour:
- I open culling view by pressing 'x' and see 2 images at once
- I apply a rating (e.g. 1 star or reject) to the first image
- I quit culling view by pressing 'x' again
- the two images are now shown grouped with a white flashing border and two grey arrows on the top of the two thumbnails (see screenshot)
- as long as I don't click but only mouseover one of the two images, every time I apply a rating now in file manager view, it gets applied to both images automatically
- only if I click on one image, the strange grouping-behaviour stops and the rating gets applied only to the selected image
![darktable-bug](https://user-images.githubusercontent.com/5677563/97284308-2ead9200-1841-11eb-943b-2904dc265b2f.png)

**Comment by j-schneid** [comment] 2020-10-27 20:26
> I suggest you press "r" for reject and after culling go to filemanager mode and set to rejected once and delte all at once

This is what I do - but I think it is more of a workaround. The whole point of culling is to sort out images you don't want. There is no point in needing two steps for that.

**Comment by quovadit** [comment] 2020-11-05 21:26
I just retested with the latest master version and both issues seem to be fixed (deleting within culling and applying rating after exiting culling)

**Comment by Germano0** [comment] 2020-12-06 00:36
> This issue did not get any activity in the past 30 days and will be closed in 365 days if no update occurs. Please check if the master branch has fixed it and report again or close the issue.

Right now I don't have time to test it on master

**Comment by quovadit** [comment] 2020-12-06 09:43
the problem still exists on master.

If the mouse is not hovered over one of the images, all actions (rating, color label, trash, rotate, ...) in culling mode get applied on all visible images (instead of the selected ones).
So when pressing the 'trash' button in the sidebar, of course the mouse is not hovered over the image.
If you hover over one image and press 'Del' on the keyboard, it only affects this one image.

The problem only occurs in culling mode, not in file-manager mode or zoomable light table

**Comment by AlicVB** [comment] 2020-12-06 11:14
yes, this is how culling works...
we can't have "select by click on the image" in culling as selection is already used here to determine which image to show. Not to speak that everything is done in lighttable to preserve the selection when changing views/modes...

That doesn't mean that you can't achieve what you want : use 'r' shortcut (or 'del' if you want a remove in 1 step) you can also press the cross icon (there's no remove icon currently)...

And for the "dangerous" part, I don't agree with you : you always have a confirmation dialog that indicate the number of image to remove (and the image is just remove from dt, so you can always reimport it if needed). I know that not every people doesn't read dialogs (some even disable them) but imho, that's a completely different (educational) issue, out of the scope of dt.

I'll close this for now as it's the wanted behavior. Don't hesitate to reopen if I've misunderstood the issue...

**Closed by AlicVB** 2020-12-06 11:14 UTC
Labels: no-issue-activity

**Comment by quovadit** [comment] 2020-12-06 11:24
@AlicVB : ok, I understand, that makes sense for dynamic zoom, but not for the fixed zoom.
There the number stays the same independent of the selected images, the header says '1 image of 3 (#1) in current selection is selected', but the 'trash' button affects all 3 images.
I agree that it's not 'dangerous' because of the popup, but it's definitely not intuitive or expected by the user.

**Comment by AlicVB** [comment] 2020-12-06 12:51
for fixed zoom, selection is used to define the list of image inside which you'll navigate. You can even restrict the culling navigation to non-continuous selection. This esp. useful when you have unrelated images inside a serie (some landscapes in the middle of birds, for example)

**Comment by quovadit** [comment] 2020-12-06 12:59
@AlicVB : thanks, that's great - I didn't know that.
So I'll update the dtdocs to highlight that feature and mention this impact on modifying images

**Comment by quovadit** [comment] 2020-12-06 21:01
@AlicVB :
I still have a problem with the current situation, because the behavior is not consistent:
- I select the first image in file-manager view and press 'x'
- I move the mouse to the top so that it doesn't hover over an image 
- the header says '1 image ... is selected'
- pressing 'r' rejects only one image
- pressing 'del' removes all visible images

The goal of culling is to compare images, so I don't see a usecase where I want to apply actions to all visible images!

When navigating with arrow-keys the first visible image automatically gets highlighted with the white border, and rating is applied to this image (if not hovered on another image).

So in my opinion it would be consistent to apply all actions (including 'del') only to the highlighted image.
Therefor it has to be ensured, that there is always one image highlighted (even if the mouse leaves the main area)
- if the mouse is hovered over an image in center area / filmstrip this image is highlighted
- else the first visible image is highlighted

**Comment by AlicVB** [comment] 2020-12-07 18:05
> * pressing 'r' rejects only one image
> 
> * pressing 'del' removes all visible images

That's a bug clearly ! I'll have a look. 'r' and 'del' should be applied to all visible images...

>     * else the first visible image is highlighted

that would be even more surprising because when you go with the mouse to the right panel, the highlighting will sort of "jump".
but we can't do the reverse, as we have to imagine that we can have more than 2 images in culling and disposition can change...


> The goal of culling is to compare images, so I don't see a usecase where I want to apply actions to all visible images

I tend to agree, but the only other consistent solution I see is to not apply anything if no image is highlighted, but that would means disabling all action via the right panel libs, and this wouldn't be good either.

**Comment by AlicVB** [comment] 2020-12-07 18:10
@quovadit : I don't reproduce your bug with 'r' and 'del'... Can you try and see if you reproduce ? and looking in the code, both action call the same function to get the images to act on, so I don't understand what happen !

**Comment by quovadit** [comment] 2020-12-07 22:03
@AlicVB : sorry, you are absolutely right, 'r' and 'del' behave exactly in the same way, my fault :-( 

So it seems, there are two different states, in which the culling view can be:
a) no image is highlighted --> all actions apply to all visible images
b) one image is highlighted --> all actions apply to the highlighted image only

The problem is, that it's not always clear in which state you are...


Of course as long as the mouse is hovered over one image, this image is highlighted (state a) 

If you actively move the mouse outside of the center-area, no image is highlighted (state b)

If the mouse is outside of the center-area and you press the right arrow key to move forward to the next images, the first image gets highlighted and we are in state a) again

BUT:
When starting culling without moving the mouse, it's not predictable for me, in which state you are, and which image is highlighted.

It seems to depend on where the mouse cursor is, but it's not only important if the mouse is inside or outside the center-area, but also if it is in the top left or bottom right corner of the screen.

Maybe it also depends on which image was highlighted the last time culling was opened...

There even are situations where one image is highlighted (so actions only get applied to this image) but no image has a white border.

AND:
There is no chance to explicitly highlight a specific image and then move the mouse out of center-area (e.g. to press a button).

.

So here is an idea how all described problems could be fixed:
- when starting culling mode, the first visible image gets highlighted and saved as highlighted
- when moving (!) the mouse over an image (in center-area or filmstrip) this image gets highlighted but not saved as highlighted
- when clicking on an image (in center-area or filmstrip), this image gets highlighted and saved as highlighted
- as soon as the mouse leaves an image (in center-area or filmstrip), the image which is saved as highlighted gets highlighted 
- when changing the visible images (by scrolling or pressing an arrow-key) the first visible image gets highlighted and saved as highlighted


Would this still be a bugfix (for 3.4) or a new feature (for 3.4.1)?

**Comment by AlicVB** [comment] 2020-12-09 10:31
> When starting culling without moving the mouse, it's not predictable for me, in which state you are, and which image is highlighted.
> 
> It seems to depend on where the mouse cursor is, but it's not only important if the mouse is inside or outside the center-area, but also if it is in the top left or bottom right corner of the screen.
> 
> Maybe it also depends on which image was highlighted the last time culling was opened...
> 
> There even are situations where one image is highlighted (so actions only get applied to this image) but no image has a white border.

Let's start to focus on this first. Some seems to be bugs and need to be understand and eventually fixed.

For the rest of your proposal, I'm really not convinced by your "saved highlight" feature. That won't really solve the base issue, and will pose lot of other problems...


> Would this still be a bugfix (for 3.4) or a new feature (for 3.4.1)?

I would say 3.4.1 : 3.4 is too close now and imho this isn't a critical issue.

To keep things clean, can you please open a new issue with an abstract of the content here ? that would avoid to debate on a closed issue with a wrong title... Thanks in advance
