### ISSUE TITLE
Clip & rotate - Not exactly clipping correctly

### ISSUE THREAD

**Issue by UsefGeorge** [darktable-org/darktable#9123] opened 2021-05-31 19:10 UTC
1) import a .jpg image ( no associated .xmp file )
2) using the clip/rotate module, on the picture draw a clip rectangle. I cropped image of the portraits of
	3 children, just so that the 3 heads showed
3)	Rotate some arbitrary amount. ( waif for it to finish its gyrations )
4)	place back to 0 ( or as much as u can ) 0 (zero) degrees

results:
		image clipped has moved, OR the box has moved. Either case, its unwanted clipping.
		do 3 & 4 a few times, and the clipped area gets smaller & smaller.

Note:	How do u enter a number for the amount of degrees?
	How do u enter A  number for the % right/left/top/bottom?
	dimensions for the image is 3264 x x2448 ( as per left button mouse. documented? )
	i dont think the type of file matters.

1) IMPORT a .jpg file ( no associated .xmp file )
2) using the clip/rotate module, on the picture draw a clip rectangle. I cropped image of the portraits of
        3 children, just so that the 3 heads showed
3) rotate some arbitray amount ( say 20 degrees )

results
		Image that was clipped by a human, now has moved, and is clipping a differnt area of the picture. Clipping box is still veritcle/horizontal lines
		at 0, 90 degrees.

Note:
		Before this electronic stuff, rotating a picture ment rotating an easel, and not the negative carrier, or ( heaven forbid ) the 
		enlarger head.
		Before this electronic stuff, clipping ment altering the dimensions of the blades on and easel. Cheap easels had only 2 moveable
		blades. The $$$ easels had 4 moveable blades.
		SO WHEN THE EASEL IS ROTATED SO DOES THE CLIPPING BOX GET ROTATED.  Not in darktable.

1) IMPORT a .jpg file ( no associated .xmp file )
2) using the clip/rotate module, on the picture draw a clip rectangle. I cropped image of the portraits of
        3 children, just so that the 3 heads showed
3) double click on the image ( image history saved? )
4) thumbnail appears correct, area to be clipped appears
5) Main viewers appear to be  correct, just the portrait of the heads of children.
6) "quit" close with the 'x' in the upper right corner
7) restart/rerun darktable
8) Thumbnail appears incorrect - looks like FULL unclipped image
9) image in main viewer, has the full darkened image, and the part to be clipped ( step 2), as if the double click never happened at all.

results

	I expected just the image that was clipped to "ONLY" show up. I expected angle/rotation to be set back to 0 ( zero ) degrees,
	 as this is a new, unmolested  picture.

note
	any further rotation should rotate just the image that was just clipped , using its center of gravity.

Fedora linux 32, Darkroom 3.4.1

**Comment by johnny-bit** [comment] 2021-06-01 15:49
The issue is fixed in current master thanks to all the lovely people that worked on this. Also in 3.6 we'll have 2 modules: `crop & rotate` + `crop` which in combination should alleviate any problems with cropping and rotating :)

**Closed by johnny-bit** 2021-06-01 15:49 UTC
