### ISSUE TITLE
Is darktable-chart broken again or just me...08/09/23 Nightly not working -- Solved

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#15058] opened 2023-08-12 02:33 UTC
### Describe the bug

I believe I am not doing anything wrong exporting to the PFM files with Lab output profile and Lab is set to enabled but when I try to open it in darktable-chart the initial red x on the screen is replaced by a black screen. There is no crashing as was the case previously starting in that window after 3.6 or so. I don't think I am doing anything wrong...can someone confirm... Running latest nightly build for windows...I am going to do my own build and see if maybe that fixes it??

### Steps to reproduce

Go to source image tab
Load source image.
Get a black screen in the preview ie no image...

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+300~g04fce12a72

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

3060Ti

**Comment by todd-prior** [comment] 2023-08-12 20:47
Seems like the export dialogue has to have resize set to no.... mine was set to yes... Things are working now... Sorry for the noise

**Comment by ptilopteri** [comment] 2023-08-13 02:33
then you might close the issue?

**Closed** 2023-08-13 09:21 UTC

**Comment by geni1105** [comment] 2023-09-16 13:45
There seems to be something wrong with the export function for PFMs: I have the same issue, that they show just as black in darktable-chart, and in macOS Finder they are designated as sRGB instead of Lab. Exiftool throws a "file format error".

I got it working shortly, when I exported with various rendering intent options - with relative, saturation and absolute all of a sudden the images displayed correctly in darktable-chart. But I can't reproduce this anymore, no matter which options I select ...

BTW, the file format option now displays just as "PFM" in the dialog, not as "PFM (float)" as described in the darktable-chart section of the manual.

**Comment by 0xdc** [comment] 2024-01-27 10:27
I ran into this issue today.

I'm running 4.4.2 and PFMs exported from this version are not appearing in chart-4.4.2. Lab values are NaN.

"allow upscaling" was always set to no. I have tried changing intent with none showing up in chart.

Previously exported PFMs from 4.2.1 are working and show up in chart from 4.4.2.

**Comment by eathtespagheti** [comment] 2024-04-15 15:49
This issue still happens on chart-4.6.1, but the PFM files created from 4.2.1 are fine
