### ISSUE TITLE
Styles with more than one instance of a module do not get created correctly

### ISSUE THREAD

**Issue by swsounds** [darktable-org/darktable#7581] opened 2020-12-31 16:28 UTC
**Describe the bug**

I have created a style that includes 3 instances of the exposure module having named instance 2 and 3 "exposure dodge" and "exposure burn". When applying that style to a new image the new image does not take on these modules. 

**To Reproduce**

In darkroom turn on modules and set parameters. Then in history stack create a new style selecting the items I want to include in the style, then name and create it. 
In lightable go to a new image and from the right hand side style sections add this style to the image with Styles mode = overwrite . 
On opening the new image in Darkroom there are no modules for dodge and burn. 

**Expected behavior**

I expect these modules to appear in the module list (this had worked in 3.2). When I had created similar instances.

**Screenshots**

I have added 3 screen shots which are of the module list for the original where the modules have been added. one for the new image where the modules are not listed and one of the create styles box where I created the style and the 2 modules are shown.
**Platform (please complete the following information):**
 - Darktable Version:  3.4.0
 - OS:  Mac OS 10.13.6
 -  No
 -  Intel HD Graphics 4000 1536 MB graphics

**Additional context**

This was working in 3.2
It is starting with newly loaded images. 
I have installed DT using the DT Mac installer

Also attached 2 xmp files saved as text files with no further changes made. I looked through and as far as I can tell the additional modules do not appear to be in there.

Thanks very much

![34 module list of style](https://user-images.githubusercontent.com/75428372/103418099-25b0a800-4b85-11eb-8293-283e7fea5f68.jpeg)
![34 module list style applied](https://user-images.githubusercontent.com/75428372/103418105-28ab9880-4b85-11eb-919e-6adef6a7aa11.jpeg)
![34 style create](https://user-images.githubusercontent.com/75428372/103418107-2b0df280-4b85-11eb-91c9-7dc46f951f61.jpeg)
[original.CR2xmp.txt](https://github.com/darktable-org/darktable/files/5757725/original.CR2xmp.txt)

[styleapplied.CR2xmp.txt](https://github.com/darktable-org/darktable/files/5757728/styleapplied.CR2xmp.txt)

**Comment by swsounds** [comment] 2020-12-31 16:33
Please note that when I apply the style to the image from the DR it does add these modules but it appends the style items rather than overwriting as it does from the LT view. I was using the LT view in 3.2 because it did replace the existing rather than adding.

**Comment by swsounds** [comment] 2020-12-31 16:49
Also they are listed in the History stack but not in the module list.

**Comment by Nilvus** [comment] 2021-01-22 13:49
Maybe related to new way to manage module and module group manager? @AlicVB?

@swsounds: could you share your style with those multi-instances? You just select it in styles module and then export it (should be in dtstyle extension.

**Comment by swsounds** [comment] 2021-01-29 15:46
Hi Nilvus,
Thanks for the reply. Sorry for being so slow to reply. Please find attached the .dtsyle file as requested, zipped.
Steve
[Steve 3,4.dtstyle.zip](https://github.com/darktable-org/darktable/files/5894755/Steve.3.4.dtstyle.zip)

**Comment by AlicVB** [comment] 2021-01-29 17:56
hmm... I've test and I can't reproduce... maybe it's already fixed in master...
What I've done : 
- import your style
- import a new "fresh" image (no xmp)
- go in darkroom
- apply the style linked in your post
- => get the right instances of exposure, in the module list (right) and in the history (left)

**Comment by swsounds** [comment] 2021-01-29 20:34
Hi Alic

I just saw your edit.... after I nearly finished typing a reply to the email notification. I'm not sure, because as I hope you can see from my examples above, if I apply the style in the Lighttable it doesn't put it in the modules list even though the modules do appear as being applied in the History Stack. 
My 2 module lists shown in the pics above are from style firstly having been applied in DR and secondly in LT. 
Any further thoughts or is there an update coming? 
Thanks
Steve

**Comment by AlicVB** [comment] 2021-01-30 12:00
No, I've tried again on new pics, by applying your style inside LT and then opening it in darkroom : I always see the 3 exposure instances in the module list...
I've also done some try with other styles including multi-instances and it's the same : everything seems to works well...

Note that it doesn't means the bug doesn't exists, it's just that if I can't reproduce, it will be more difficult to fix... By any chance, are you able to test current master ?

**Comment by swsounds** [comment] 2021-01-30 12:20
It's odd I know, I don't know if you are using OS 10.13.6 but this OS had given me different issues with the previous version of DT so I suppose it could be OS version specific. 
How do I test the current master? I am quite happy to give it a try if you can make the latest available to me and you have installation instructions to keep it separate from the mainly working version.

**Comment by AlicVB** [comment] 2021-01-30 14:56
sorry, I've absolutely no idea how to test/build/... on OSX... We'll have to wait for some other people here :(

**Comment by swsounds** [comment] 2021-01-30 16:06
Ok no worries. Thanks for trying to help.

**Comment by ianpasmith** [comment] 2021-03-22 20:26
I am using Windows 10, and reviewing 3.4.1.1 before migrating from 3.2
Some of my styles under 3.2 use multiple instances of modules, some do not.
I exported my styles from 3.2
After importing all styles into 3.4.1.1, after applying styles with multiple instances, to an image, the
image appears 'corrupt' - multiple color squares. Applying a style without multiple modules seems
to give the correct results.
On from this point, the issue can be created by simply creating a new style in 3.4.1.1, with multiple
instances of a module, saving the new style and then applying the style to another image.
This seems a basic issue, and I am wondering if it is because I am using Windows and not Linux.
Please let me know of the information I can supply to resolve this issue,

**Comment by johnny-bit** [comment] 2021-06-20 08:56
Tested, re-tested etc :) It looks like on current master ALL issues regarding multi-instance stuff are fixed :)

Closing :)

@ianpansmith - if you can't check current master, plz wait till 3.6 release (due in less than 2 weeks!) and it should fix the issue completely for you :)

**Closed by johnny-bit** 2021-06-20 08:56 UTC
Labels: no-issue-activity
