### ISSUE TITLE
Darktable 3.8.0 crashes at startup on Windows 10

### ISSUE THREAD

**Issue by KongasKongstew** [darktable-org/darktable#11056] opened 2022-02-04 09:19 UTC
Hi, after not working for a few weeks with darktable 3.8.0 I wanted to develop a few raws I shoot yesterday and tried to start darktable.
A dos box appeared and dissapeared and after a few seconds the Error pop-up pops up, suggesting I should share a backtrace file with the developers when reporting an issue. So I do this. 

As a first resort I deleted ALL files in \AppData\Local\darktable , except for the directories for styles etc., but this did not fix the issue.
Next step was a reinstallation of the programm, but the issue persisted. 

Attached the backtrace file.
[darktable_bt_K51VG1.txt](https://github.com/darktable-org/darktable/files/8001536/darktable_bt_K51VG1.txt)
.

**Comment by MStraeten** [comment] 2022-02-04 10:19
seems to be a duplicate of https://github.com/darktable-org/darktable/issues/10767
and there's a workaround mentioned

hint: use search before filing new issues ...

**Closed** 2022-02-04 11:34 UTC

**Comment by KongasKongstew** [comment] 2022-02-04 11:35
Ok, seems to be a duplicate. Sry for not finding the original bug with the search, didn't use windows11 or the exception in search.
