### ISSUE TITLE
Unhandled exception when editing a mask name

### ISSUE THREAD

**Issue by cdyson37** [darktable-org/darktable#9803] opened 2021-08-13 17:51 UTC
Trying to change the name of a mask results in an unhandled exception.

**To Reproduce**
- Open a photo in darkroom
- Go to mask manager
- Click "add gradient"
- Draw the gradient
- Click to place the gradient
- Slow click on `gradient #1` to make the name editable (you do not need to type anything), then click outside

**Expected behavior**
Mask's name edit is confirmed.

**Platform**
* darktable version : 3.6.0
* OS                : Win10 20H2
* Memory            :  16GB
* Graphics card     :  GeForce RTX 2070 Super
* Graphics driver   : 252.06
* OpenCL installed  : unknown
* OpenCL activated  : unknown

**Typical backtrace**
```
Error occurred on Friday, August 13, 2021 at 18:31:25.

darktable.exe caused an Access Violation at location 00007FFAFCD26EB4 in module libgobject-2.0-0.dll Reading from location FFFFFFFFFFFFFFFF.

AddrPC           Params
00007FFAFCD26EB4 000000000000000C 0000000000000004 0000000000000001  libgobject-2.0-0.dll!g_type_check_instance_cast
00007FFAE3105AD7 0000000000000037 0000000000000028 000001E75CE90000  libmasks.dll!0x7ffa00005ad7
00007FFAEDE6AA51 000001E75D05E030 00007FFAF84467D6 000001E75CF111E0  libgtk-3-0.dll!0x7ffa0000aa51
00007FFAFCD070E3 0000003AB79FDF60 00007FFAFCD2A01B 0000003AB79FDF60  libgobject-2.0-0.dll!g_closure_invoke
00007FFAFCD1EE9B 000001E7766380F0 00007FFAFCD0B993 000001E700000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFAFCD1EFE8 000001E7728E3700 00007FFAEE1183A8 0000003AB79FE09C  libgobject-2.0-0.dll!g_signal_emit
00007FFAEDEC6A5B 4093A40000000000 00007FFB20425930 00000000000000CB  libgtk-3-0.dll!gtk_cell_renderer_spinner_new
00007FFAFCD06ECE 000001E75CE902AC 0000000000000000 0000000000000030  libgobject-2.0-0.dll!g_closure_invoke
00007FFAFCD18EF9 000001E772C9AA20 0000000000000000 000001E774F43E10  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFAFCD1EB84 000001E774F43E10 000001E776171300 0000003A00000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFAFCD1F159 0000000000000000 0000000000000001 000001E772A02078  libgobject-2.0-0.dll!g_signal_emit_by_name
00007FFAEDEB5F78 000001E75B052D60 0000000000000000 000001E7727EC850  libgtk-3-0.dll!gtk_cell_area_stop_editing
00007FFAEE102770 0000000000000020 00007FFA00000000 000001E75CF111E0  libgtk-3-0.dll!gtk_tree_view_convert_widget_to_bin_window_coords
00007FFAFCD070E3 000001E75CFAEAE0 000001E75CF7B100 0000000000016912  libgobject-2.0-0.dll!g_closure_invoke
00007FFAFCD1EE9B 000001E7763B8A80 000001E7745BBC90 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFAFCD1EFE8 0000000000000000 00007FFB4383B90B 0000003AB79FE8C8  libgobject-2.0-0.dll!g_signal_emit
00007FFAEDF764AF 000001E75FE5AFE0 0000000000000008 0000000000000000  libgtk-3-0.dll!gtk_gesture_long_press_new
00007FFAFCD099DA 0000000000000030 00007FFB438607B0 0000000001DE0341  libgobject-2.0-0.dll!g_cclosure_marshal_VOID__BOXEDv
00007FFAFCD070E3 000001E75F02E140 00007FFB438607B0 0000003AB79FEBA0  libgobject-2.0-0.dll!g_closure_invoke
00007FFAFCD1EE9B 000001E7763B8A80 4069200000000011 4031000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFAFCD1EFE8 0000000000000180 000001E700000008 0000000000000005  libgobject-2.0-0.dll!g_signal_emit
00007FFAEDF7302D 0000000000000001 0000000000000000 000001E7763B8A80  libgtk-3-0.dll!gtk_glade_catalog_init
00007FFAEDF74547 0000000000000002 000001E776185DC0 000001E7763B8A80  libgtk-3-0.dll!gtk_gesture_handles_sequence
00007FFAEDF777B4 4069200000000000 4031000000000000 4069200000000000  libgtk-3-0.dll!gtk_gesture_rotate_get_angle_delta
00007FFAEDF3C61D 0000003AB79FEFF8 0000003AB79FEFF8 000001E75F02F790  libgtk-3-0.dll!gtk_event_controller_handle_event
00007FFAEE111B0C 0000000000000001 00007FFAFCD070E3 0000000000000030  libgtk-3-0.dll!gtk_requisition_free
00007FFAEDE62D16 0000003A00000002 00007FFAFCD0B7AC 00007FFAFCD48268  libgtk-3-0.dll!0x7ffa00002d16
00007FFAFCD06ECE 000001E7727EDC00 0000000000000002 0000000000000004  libgobject-2.0-0.dll!g_closure_invoke
00007FFAFCD18933 000001E75F02FA30 0000000000000000 000001E776185EB0  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFAFCD1E854 000001E776185EB0 0000000000000000 000001E700000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFAFCD1EFE8 000001E776185EB0 00007FFAFCD26936 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
00007FFAEE113425 000001E700000000 00007FFAEE13BC7A 000001E783F84D10  libgtk-3-0.dll!gtk_requisition_copy
00007FFAEDFC12DF FFFFFFFF00000000 00007FFB422BE703 00007FFB422BEB96  libgtk-3-0.dll!gtk_lock_button_set_permission
00007FFAEDFC3308 0000000000000000 00007FFAF2E06680 0000000000000000  libgtk-3-0.dll!gtk_main_do_event
00007FFAF2DCF56A 0000003AB79FF370 000001E75F00F1C0 00007FFB422BE040  libgdk-3-0.dll!gdk_event_free
00007FFAF2E066BF 000001E75CF7B100 00007FFAF83EB62D 0000000000000000  libgdk-3-0.dll!gdk_win32_drag_context_get_type
00007FFAF83E88F4 0000000000000002 000001E776A52630 000001E776A52630  libglib-2.0-0.dll!g_clear_list
00007FFAF83EBA46 0000000000000001 000001E75CF4F480 000001E75CF75F70  libglib-2.0-0.dll!g_main_context_check
00007FFAF83EBF6C 0000000000000000 0000000000000000 00007FFAEEBB70C0  libglib-2.0-0.dll!g_main_loop_run
00007FFAEDFC21ED 0000000000000000 00007FF612F126E0 000001E75CF76BD0  libgtk-3-0.dll!gtk_main
00007FFAEE95B27C 00007FFB00000001 000001E75CF4F480 00007FFB00000001  libdarktable.dll!dt_gui_gtk_run
00007FF612F12A6C 00007FF612F11660 0000000000000010 0000000000000000  darktable.exe!0x7ff600002a6c
00007FF612F115B5 000000000000005A 0000000000000000 00007FF612F17090  darktable.exe!0x7ff6000015b5
00007FF612F113D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff6000013d4
00007FF612F11506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff600001506
00007FFB42467034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFB43862651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart
```

**Comment by phweyland** [comment] 2021-08-13 22:51
Duplicate of #9504 & #9790

**Comment by johnny-bit** [comment] 2021-08-28 10:07
duplicate of #9504 
Fixed in https://github.com/darktable-org/darktable/pull/9514
will be part of 3.6.1 release

**Closed by johnny-bit** 2021-08-28 10:07 UTC
Labels: duplicate
