### ISSUE TITLE
Black Square in lighttable

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#8753] opened 2021-04-22 19:30 UTC
**Describe the bug/issue**
When disabling _color calibration_, but having _exposure_ and _filmic rgb_ modules active there is a black square, size of half of the window height. I have seen the square both in bottom left corner and top right corner.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open an image with modern workflow and color management enabled
2. disable color calibration
3. See the square

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18402158/115774078-cd164c80-a3b9-11eb-827e-0b39b45cac27.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+1796
* OS                : Win10/64
* OpenCL activated  : no impact
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
The bug disappears, if I also disable exposure and/or filmic rgb.

**Comment by Mark-64** [comment] 2021-04-22 19:47
Can't reproduce, can you provide a raw file and the relative .xmp where you have the issue?

**Comment by Nilvus** [comment] 2021-04-22 21:49
Duplicate of #8645

**Comment by paolodepetrillo** [comment] 2021-04-23 05:16
I was just looking at #8645, found that it's possible for color calibration to produce an output pixel that has the floating point value NaN. If a single NaN value gets into filmic rgb's highlight reconstruction, it will produce a black square exactly like this.

**Comment by juhavlintula** [comment] 2021-04-23 05:39
I have the issue, when color calibration is disabled, enabling it, makes the issue disappear. But the outcome looks the same as in #8645.

[2021_04_20.zip](https://github.com/darktable-org/darktable/files/6362998/2021_04_20.zip)

**Comment by paolodepetrillo** [comment] 2021-04-23 06:11
This might be an optimization related thing. if I remove the finite-math-only and fast-math optimization flags from channelmixerrgb.c, that seems to fix the problem by making it output zeros where it would otherwise output NaNs if those flags were present. Not sure exactly what is going on..

**Comment by Nilvus** [comment] 2021-04-23 06:20
@aurelienpierre: maybe for you this one? Seems quite specific bug related to color calibration and probably on Windows only (both issues, this one and #8645 are from Windows users).

**Comment by aurelienpierre** [comment] 2021-04-23 08:09
Does it happen even with gamut clipping enabled in color calibration ? Things like this happen when negative RGB values get input in logs and powers, but the code is supposed to check for them. I have never seen that on Linux.

**Comment by Nilvus** [comment] 2021-04-23 09:18
> Things like this happen when negative RGB values get input in logs and powers, but the code is supposed to check for them. I have never seen that on Linux. Can you post the picture + XMP ?

You have them in above comment: https://github.com/darktable-org/darktable/issues/8753#issuecomment-825401051

**Comment by jenshannoschwalm** [comment] 2021-04-23 09:55
There also might be the demosaicer output involved. In rawprepare there is no check for negative values after correction for white/black levels. The demosaicer might get negatives for input, comparable issues like the one here had been described and solved for green equal. For RCD we correct for negative input/output, for PPG, VNG and the fuji demosaicers i am not sure.

**Comment by juhavlintula** [comment] 2021-04-23 11:41
I tested with different demosaicer algorithms and the black areas changed. Turning the exposure down from 2.10EV to 0.70 ballpark, removes the black area. But I felt some randomness on there.

**Comment by Mark-64** [comment] 2021-04-23 12:04
I experienced the same random issue with DT git master on Windows, but only recently (few days)

**Comment by paolodepetrillo** [comment] 2021-04-23 12:45
I think the problem may be originating in overshoot from the lanczos3 interpolation creating negative pixels. I'm looking at an example now where the problem sometimes goes away if I switch to bilinear interpolation. This would explain why the issue is hard to reproduce, everyone has a different screen size / UI config so the scaling factor for the preview at fit to screen zoom level is different. If it can be reproduced at 50% zoom level with the image panned to a certain location containing the offending pixel, that should be more consistent than trying to reproduce at fit to screen zoom level.

With the image from #8645, a few pixels with small negative G and B values are input to the first color calibration instance (with lanczos3 interpolation on) and if gamut clipping is off, they are output as very large values. For example (0.042890,-0.011823,-0.016639) becomes (-178859.156250,65839.820312,119374.476562). The second color calibration instance then outputs NaNs for these pixels causing filmic rgb to output the black areas.

I am testing on Arch Linux, building master with gcc 10.2.0, so it isn't Windows-specific.

**Comment by jenshannoschwalm** [comment] 2021-04-23 12:52
> With the image from #8645, a few pixels with small negative G and B values are input to the first color calibration instance (with lanczos3 interpolation on) and if gamut clipping is off, they are output as very large values

This would be very easy to test via changing blackpoint in rawprepare.

**Comment by paolodepetrillo** [comment] 2021-04-23 14:52
Might have found something, in channelmixerrgb.c gamut_mapping().

```
static inline void gamut_mapping(const float input[4], const float compression, const int clip, float output[4])
{
  // Get the sum XYZ
  float sum = 0.f;
  for(size_t c = 0; c < 3; c++) sum += input[c];
  sum = fmaxf(sum, NORM_MIN);

  // Convert to xyY
  float Y = fmaxf(input[1], 0.f);
  float xyY[4] DT_ALIGNED_PIXEL = { input[0] / sum, input[1] / sum , Y, 0.0f };
```
If the input X Y and Z sum to a negative number, then sum is set to NORM_MIN, and x and y in xyY end up with very large values on the order of 100 or 1000 when they should be in the range 0-1. After that point everything blows up and the module outputs an RGB pixel with very large values on the order of +/- 100000. When this happens twice in a row with two color calibration modules, the second one overflows and outputs a NaN.
I think there does need to be a sanity check for this case - even though X+Y+Z should never be < 0, as long as there is interpolation with ringing and overshoot happening in the pipeline, there is always the possibility of having single pixels with completely invalid values.

**Comment by aurelienpierre** [comment] 2021-04-23 15:30
I think the true question here is how do we end up with pixels where X + Y + Z < 0, because that's really invalid on every possible space. It's nothing to do with this particular module, any color space using opponent colors (Yxy, Yuv, Yrg, etc.) will face the same issue. Clipping will hide the problem, not fix it.

**Comment by jenshannoschwalm** [comment] 2021-04-23 15:50
> Rather than blaming the interpolation, I would first check towards the raw black point.

Do you think of: checking in rawprepare about such a situation and maybe do some auto correction?

**Comment by paolodepetrillo** [comment] 2021-04-23 16:05
I do think that in some cases the interpolation that happens immediately after demosaicing is introducing the negative values. I'm testing with the image from #8645, in demosaic.c process() counting the number of negative RGB pixels of each color before and after the interpolation.
For this case, for a zoom level where it resizes from 6032x4009 to 1151x765, there are only 5 pixels with a negative blue value in the full resolution image after demosaic. After the resize using bilinear interpolation, there are no negative pixels left. But after the resize using lanczos3, there are 602 R, 2382 G, 3670 B negative values, and a few of these eventually end up getting into color calibration with X+Y+Z < 0.

**Comment by aurelienpierre** [comment] 2021-04-23 16:49
> Do you think of: checking in rawprepare about such a situation and maybe do some auto correction?

That's an option yes.

> For this case, for a zoom level where it resizes from 6032x4009 to 1151x765, there are only 5 pixels with a negative blue value in the full resolution image after demosaic. After the resize using bilinear interpolation, there are no negative pixels left. But after the resize using lanczos3, there are 602 R, 2382 G, 3670 B negative values, and a few of these eventually end up getting into color calibration with X+Y+Z < 0.

What happens if you clip negatives at the output of rawprepare ?

**Comment by paolodepetrillo** [comment] 2021-04-23 17:05
Clipping the negative values at 0.0 in rawprepare does not get rid of the negative values at the demosaic output. The negative values at the output of the interpolation aren't caused by negative values at the input, it's because of values close to 0 adjacent to large values being pushed negative by lanczos3's ringing and overshoot. I think it's the same issue as the visual artifacts seen in #8016 and described on p35 of [Cinematic Color](http://github.com/jeremyselan/cinematiccolor/raw/master/ves/Cinematic_Color_VES.pdf).

**Comment by juhavlintula** [comment] 2021-04-23 19:23
I can confirm that changing lighttable window size changes the black areas. Also increasing the raw black points, decreases the black areas.

**Comment by aurelienpierre** [comment] 2021-04-23 20:47
So that's clipping after interpolation then.

**Comment by aurelienpierre** [comment] 2021-04-24 22:55
I will add negative clipping in interpolation methods.

**Closed** 2021-04-25 15:37 UTC
Labels: bug: pending, priority: high, scope: image processing, understood: incomplete
