### ISSUE TITLE
 Can't copy history when image grouping is enabled

### ISSUE THREAD

**Issue by ianhattendorf** [darktable-org/darktable#10592] opened 2021-12-09 02:17 UTC
**Describe the bug/issue**

Copy history is greyed out when image grouping is enabled.

**To Reproduce**
1. enable image grouping
2. make edit to RAW file with JPEG pair
3. try to copy history but button is greyed out
4. disable image grouping
5. note that raw + jpeg are selected
6. select just raw
7. copy history is no longer greyed out

**Expected behavior**
Able to copy history of RAW file while image grouping is enabled. Similar to how double-clicking a grouped image opens the RAW file or mousing over a grouped image shows the RAW info, I would expect history copy to copy the history of that RAW file.

**Screenshots**
Grouping enabled:
![image](https://user-images.githubusercontent.com/2917725/145111582-79bf3bea-06ec-4462-86e6-00ac3efa7976.png)

Grouping disabled, both images selected:
![image](https://user-images.githubusercontent.com/2917725/145111613-8edeb922-4f17-4794-8057-c38fe858af46.png)

Grouping disabled, one image selected:
![image](https://user-images.githubusercontent.com/2917725/145111637-3206f741-90bf-487f-aa53-564b41dffb39.png)

**Platform**

* darktable version : 3.6.1-1.fc35.1 and master
* OS                :  Linux - kernel 5.15.6-200.fc35.x86_64
* Linux - Distro    : Fedora 35
* Memory            :  8GB
* Graphics card     :  GTX 970 4GB
* Graphics driver   : NVidia Proprietary
* OpenCL installed  :  yes
* OpenCL activated  :  yes
* Xorg              :  Wayland
* Desktop           :  Gnome
* gcc               :  11.2.1-7.fc35

**Additional context**
See #5931, specifically https://github.com/darktable-org/darktable/issues/5931#issuecomment-988288778 and newer

**Comment by paolodepetrillo** [comment] 2021-12-09 05:25
I am seeing something that might be related, testing with 3.7.0+1646~gc76d3c3de. With grouping enabled, when I return from the darkroom to lighttable, the selective copy and copy buttons are initially disabled. But as soon as I bring the mouse cursor from the lighttable button into the central lighttable area, the buttons immediately enable.

**Comment by ianhattendorf** [comment] 2021-12-09 05:30
Thanks for commenting! I forgot to mention that I briefly noticed that as well, however the behavior wasn't very consistent for me and I was having a hard time reproducing it. After my cursor left the window the buttons greyed out again, on return they remained grey.

**Comment by Nilvus** [comment] 2021-12-09 18:49
Thanks for your comment both. So, if I understand your last comments, this is more how to act on images is actually configured in darktable than an issue (and so how to change that). And we have had some discussions on that and we are not all agree on the way to deal with that. See this issue: #6025 (we expect to find a better way that is good for all or at least most of us for 4.0).

**Comment by ianhattendorf** [comment] 2021-12-09 19:31
> Thanks for your comment both. So, if I understand your last comments, this is more how to act on images is actually configured in darktable than an issue (and so how to change that). And we have had some discussions on that and we are not all agree on the way to deal with that. See this issue: #6025 (we expect to find a better way that is good for all or at least most of us for 4.0).

Yes, I originally thought it was a bug but it seems like the issue is really the image selection/lighttable design. Thanks for linking that issue, it didn't come up in my search earlier.

**Comment by Nilvus** [comment] 2021-12-09 20:07
> Yes, I originally thought it was a bug but it seems like the issue is really the image selection/lighttable design. Thanks for linking that issue, it didn't come up in my search earlier.

So it is better to continue on #6025 the discussion and try to have a better way to act on images for 4.0. I so close this issue as it is easier to follow just one and this one is linked to #6025 and so complete it.

**Comment by paolodepetrillo** [comment] 2021-12-10 03:30
Maybe this really is a bug that only occurs in some cases, rather than working as designed? I am always able to select a grouped raw/jpeg and copy the history successfully, in 3.6.1 and latest master. The only issue is that sometimes when returning from darkroom to lighttable I have to move the mouse over the lighttable, but after that the copy button always stays active.

**Comment by ianhattendorf** [comment] 2021-12-10 03:47
> Maybe this really is a bug that only occurs in some cases, rather than working as designed? I am always able to select a grouped raw/jpeg and copy the history successfully, in 3.6.1 and latest master. The only issue is that sometimes when returning from darkroom to lighttable I have to move the mouse over the lighttable, but after that the copy button always stays active.

Interesting, I think you might be right. My understanding from https://github.com/darktable-org/darktable/issues/5931#issuecomment-673158002 was that > 1 image selected would always disable history copy, but it looks like `dt_view_get_images_to_act_on` might be expected to handle grouped images and only return one image to act on...

I wonder if it has to do with image types? I'm shooting Olympus (ORF+JPEG), I wonder if that has something to do with it? In the previous issue it was mentioned that CR2+JPEG worked.

 https://github.com/darktable-org/darktable/blob/bbd387ccd3d77eb67cfbbf8506fc55f6f2b97eaa/src/views/view.c#L696

**Comment by ianhattendorf** [comment] 2021-12-10 03:52
OK there's definitely a bug here @Nilvus, can this be re-opened?

On my other machine (same OS + darktable version) I'm able to copy history of grouped images. Tested both on my images, and by downloading an ORF+JPEG (I grabbed some sample images from https://www.dpreview.com/sample-galleries/8542947609/olympus-om-d-e-m1-mark-ii-real-world-samples-gallery/5001574539), renaming the JPEG to match the raw name, opening both in darktable.

![image](https://user-images.githubusercontent.com/2917725/145514082-51211b3d-7ad3-446e-bb71-118909f96a8a.png)

And yes, the history copy + pastes correctly (it doesn't no-op).

**Comment by paolodepetrillo** [comment] 2021-12-10 04:39
The "-d act_on" command line parameter may be useful for getting debug messages that might show what the problem is.

On my system, the copy buttons being grayed out until I move the mouse into the lighttable doesn't always happen but it does happen consistently for a certain directory of images.

**Comment by ianhattendorf** [comment] 2021-12-10 04:44
> The "-d act_on" command line parameter may be useful for getting debug messages that might show what the problem is.

Interesting, gave that a shot and it appears that mousing over selects both but clicking (supposedly) selects one, although copy is still greyed out... (as soon as a pressed the screenshot hotkeys it switched back to mousing over, however the button is definitely greyed out when the terminal is saying `6` is selected).

![image](https://user-images.githubusercontent.com/2917725/145518497-923d5264-68f9-4adb-8547-651ecd29b6db.png)

**Comment by Nilvus** [comment] 2021-12-10 07:44
@AlicVB: could you check that?

**Comment by AlicVB** [comment] 2021-12-10 17:31
I've just tested and I'm not been able to reproduce de issue...
Normally, whatever how you "select" the grouped images (hover or click), you should only have the group leader id in the [image to act on] image list...
Can you confirm (to be sure I correctly understand) that in your case, the image list always contain the id of the group leader and the id of the corresponding "hidden" image ?

If that's the case, that's quite strange, and I'll have to investigate further what can cause the problem...
Thanks !

**Comment by ianhattendorf** [comment] 2021-12-10 20:58
> Can you confirm (to be sure I correctly understand) that in your case, the image list always contain the id of the group leader **and** the id of the corresponding "hidden" image ?

@AlicVB here's me mousing over + clicking, using arrow keys, using space to multi-select, and enter to select. Also toggling between grouping and non-grouping. This is on a fresh darktable config running darktable from git master. Let me know if there's anything else that would help.

https://user-images.githubusercontent.com/2917725/145640040-b374e00b-51d9-4f54-b035-1c261486f98d.mp4

**Comment by AlicVB** [comment] 2021-12-12 17:57
@ianhattendorf : thanks for your video. Sadly, I'm not able to reproduce on my system...
I've rechecked the code and the only cause I'm thinking of would be that for some reason some part of the code request the list with the hidden image and then this list is cached and return whatever the flag only_visible...

PR #10607 should fix that. Can you test it and report if that fix the issue on your side ? Thanks a lot !

**Comment by elstoc** [comment] 2021-12-14 19:56
Reopening as the fix has been reverted due to unanticipated side-effects.

**Comment by AlicVB** [comment] 2021-12-14 20:38
@ianhattendorf : I'll need you for some test, later, in order to propose another fix for 3.8.1... sorry for not fixing this in 3.8, but as @elstoc has said, the previous commit as unwanted side-effect and it's now too late in the release cycle to propose something more complete (and more intrusive)
I'll ping you when it's ready !

**Closed** 2021-12-28 08:28 UTC
Labels: scope: UI
