### ISSUE TITLE
unexpected message - Size of XMP JPEG segment is larger than 65535 bytes

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#7455] opened 2020-12-25 20:28 UTC
dt 3.4.0+dirty   Ubuntu 18.04

`[dt_exif_xmp_attach_export] /mnt/b3fa3123-84fd-4cfc-97a8-567e75014d9a/Data/CR2 Store/2020_12_16-6D-low-sun-Pembroke-Road/_6D_00721-xxxx-V1-S-sRGB.jpg: caught exiv2 exception 'Size of XMP JPEG segment is larger than 65535 bytes'`

I noticed this in the Terminal window running dt.  It's with a very simple history stack, just a few basic modules active, no masks.  It is not produced if I switch off "develop history" in "edit metadata" export settings.

[_6D_00721.CR2 (copy).txt](https://github.com/darktable-org/darktable/files/5742366/_6D_00721.CR2.copy.txt)

**Comment by ralfbrown** [comment] 2020-12-26 05:48
The JPEG file format has a limit of 64KiB for any metadata type.  Your sidecar file is bigger than that as a result of lots of editing, changes to masks, etc.

One thing that has happened is that you have a lot of shapes from drawn masks which got orphaned -- they are still stored in the sidecar, but don't show up in the interface as available.  In the darkroom, go to Masks Manager, right-click on the center pane where shapes would be listed, and select "clean up unused shapes".  You will now have a 19K sidecar file.  If you additionally click on "Compress History Stack" to eliminate superceded editing steps, you'll be down to 11K.

There was a bug where dt wouldn't clean up discarded shapes because it thought they were still in use.  I saw a fix for that put in a couple of months ago, but it might only affect new shapes, not the accumulated orphans from older versions.

**Comment by johnny-bit** [comment] 2020-12-26 11:15
I've seen couple of issues where large-ish history can cause problems but I can't seem to be able to find it.

The workaround/fix would be IMO to skip adding dev history if sidecar file is larger than allowed by destination format (but still try to add any other tag)... This is a bit problematic since afaik there's no "how big can segment be" api in exiv2 and the error happens on write, not on attach in exiv2. Obviously the exception does have error code which can tell what's happening (in this case - `kerTooLargeJpegSegment`) but `dt_exif_xmp_attach_export` looks like one big `try{}catch{}` block... So that would need a reconsideration/rewrite with step-by-step writes and segmented tries... eg: try to write xmp with full history -> that failed? well, slice history off then. -> that failed? well... shit.

Aditional downside is that some people use export + history as a "backup" for dev history instead of sidecar files but since jpeg is limited AF that gets problematic really quick...

// sidenote: I'm not touching `dt_exif_xmp_attach_export` - waaay too fragile/important code for my clumsy hands.

**Comment by RawConvert** [comment] 2020-12-26 14:45
Thanks @ralfbrown for the info.  I've done what you say and the XMP is smaller, but not 11k, it's gone from 68.2 down to 35.9kb.  That's the cleanup plus compress history.
[_6D_00721.CR2 (copy).txt](https://github.com/darktable-org/darktable/files/5743215/_6D_00721.CR2.copy.txt)

I also noticed a strange thing, perhaps this s/be a separate issue?, when I do the right-click and cleanup, the Watermark module gets switched on!  I did this twice to make sure I wasn't seeing things.  Here are screen grabs before and after, the only change is the clean-up (and possibly compress history).  See "photo" in image centre.
![Screenshot from 2020-12-26 14-25-52](https://user-images.githubusercontent.com/16868433/103153344-d551d880-4787-11eb-9ed2-a1067a86ad2d.png)
![Screenshot from 2020-12-26 14-26-21](https://user-images.githubusercontent.com/16868433/103153360-e8fd3f00-4787-11eb-8de1-5aa47099bc88.png)

-------------------------------------
I don't recall the jpeg error before, I got it yesterday with the new 3.4.  I'm guessing the new build has "develop history" on as default.  I don't think that's a great default, I mean if you sent someone a box of chocolates, would you enclose a map showing your route to the shop where you bought them?  :)

**Comment by ralfbrown** [comment] 2020-12-26 15:36
> Thanks @ralfbrown for the info. I've done what you say and the XMP is smaller, but not 11k, it's gone from 68.2 down to 35.9kb. That's the cleanup plus compress history.

I bet you have "store xmp tags in compressed format" set to "never" in Preferences under "storage".  I have it at the default "only large entries".  I tried changing it to "never" and got a 37k sidecar.

**Comment by johnny-bit** [comment] 2020-12-26 15:42
> I'm guessing the new build has "develop history" on as default. 

No it isn't default (AFAIK)

> I also noticed a strange thing, perhaps this s/be a separate issue?, when I do the right-click and cleanup, the Watermark module gets switched on! I did this twice to make sure I wasn't seeing things. Here are screen grabs before and after, the only change is the clean-up (and possibly compress history). See "photo" in image centre.

If you think it's a legitimate issue - you should open a new issue. One topic - one issue :)

**Comment by johnny-bit** [comment] 2021-01-26 06:28
Good news everyone! this should've been fixed by https://github.com/darktable-org/darktable/pull/7967 :)

**Closed by johnny-bit** 2021-01-26 06:28 UTC
Labels: bug: pending, no-issue-activity, scope: software support

**Comment by RawConvert** [comment] 2021-01-26 13:57
Yes good, though I didn't spot any ref to this issue in #7967 [although ctrl+F doesn't work on these pages (Firefox) ?]  7967 seems to be more about managing the tags etc in the Jpeg?

ALSO: @ralfbrown said above "...shapes from drawn masks which got orphaned -- they are still stored in the sidecar, but don't show up in the interface as available"
Isn't part of this fix to stop unwanted orphans getting stored and propagated e.g. in a Style (if I understand correctly) ?

**Comment by johnny-bit** [comment] 2021-01-26 14:06
No, the #7967 didn't refer this issue at all, but refered earlier one that this issue is basically a duplicate of.
