### ISSUE TITLE
DT 4.3.0 Hierarchically higher modules ignore/disable rastermask if created with detail treshold mask.

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#14271] opened 2023-04-20 12:53 UTC
### Describe the bug

If you have created _detail threshold mask_ in one module (let's say for example exposure module) and reuse it in _hierarchically higher module as raster mask_ (for example in contrast equalizer) in next hierarchically higher module (for example color balance rgb) _it will be ignored/disabled._

If you then _switch off the raster mask_ in the module where the raster mask was used (in this case contrast equalizer) and _switch it on again_, it will _also be taken into account_ by the higher module (color balance rgb). 

### Steps to reproduce

1. Create a mask with the help of _detail threshold_ slider and apply it (exposure module here):

![grafik](https://user-images.githubusercontent.com/38165484/233351213-5fd87a54-fc64-4207-bf6b-1484a956e6ce.png)
![grafik](https://user-images.githubusercontent.com/38165484/233351768-9a83d7ce-7897-4744-a3c8-110b8babd8de.png)

2. Make a change in hierarchically higher module (contrast equalizer) and apply the _raster mask_ based on detail threshold mask made by exposure module :

![grafik](https://user-images.githubusercontent.com/38165484/233352562-b1765016-ecfa-42a2-ac8b-db5cc72cabaa.png)
![grafik](https://user-images.githubusercontent.com/38165484/233352734-4525ff12-352a-4873-b5f2-03623070e367.png)

3. Go to a hierarchically higher module (color balance rgb) and make a change there. The raster mask applied to the hierarchically lower module is _ignored/disabled_. 

![grafik](https://user-images.githubusercontent.com/38165484/233357315-67830229-cdfe-4049-a3c1-8a7511386e78.png)

4. Go back to the module that used the raster mask (contrast equalizer) . Although it is _shown as applied_ in the menu, _it is not active_:

![grafik](https://user-images.githubusercontent.com/38165484/233359219-635c4ce2-7252-4b75-9732-bc6df8929f20.png)

5. Deactivate it and activate it again. Now it is applied again. 

![grafik](https://user-images.githubusercontent.com/38165484/233359592-fcf7bc0e-e0f0-469a-91fb-e313bde51635.png)

6.  This time it will be active also in hierarchically higher module:

![grafik](https://user-images.githubusercontent.com/38165484/233360191-6bc7b760-9ffd-4c08-a4c8-e3005930c2a4.png)

7. It can be - but this is not always the case - if you then make another change in this module (color balance rgb), that again the raster mask is switched off. Then you have to repeat steps 4 to 6. In the following video that was the case:

https://user-images.githubusercontent.com/38165484/233368904-3291e672-eece-4739-a722-3b53e6c9c505.mp4

Here is also the output of the terminal with "darktable -d all" when this video was made:

[darktable_raster_mask.txt](https://github.com/darktable-org/darktable/files/11286278/darktable_raster_mask.txt)

Important note:

This behavior _does not always happen_. However, I could not determine under what circumstances this happened. 

Raw file I used for the demonstration is from this post
https://discuss.pixls.us/t/gamut-issues-should-i-be-worried/36719/1

### Expected behavior

When raster mask is used by one module, it should not be affected by other modules that are used after it.

### Where did you install darktable from?

darktable.org

### darktable version

4.3.0+1872~gd2c7145fd

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu Studio 22.04

### Describe your system?

Operating System: Ubuntu Studio 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-70-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1070/PCIe/SSE2

**Comment by s7habo** [comment] 2023-04-20 13:03
Here is also sidecar file:

[ER6_2855.CR3.xmp.zip](https://github.com/darktable-org/darktable/files/11286460/ER6_2855.CR3.xmp.zip)

**Comment by jenshannoschwalm** [comment] 2023-04-20 13:43
Thanks :-) Before getting into this:
1. Are you sure this worked correctly with 4.0 / 4.2?
2. Can you reproduce with --disable-pipecache ?
3. BTW, in most cases -d common will be far enough :-)

**Comment by s7habo** [comment] 2023-04-20 15:19
> Are you sure this worked correctly with 4.0 / 4.2?`

I think I experienced this at times with 4.0 / 4.2

> Can you reproduce with --disable-pipecache ?

No. I just tried 4-5 times and the problem does not seem to appear.

Here is the terminal output:
[darktable_raster_mask_d_common_disable_pipecache.txt](https://github.com/darktable-org/darktable/files/11287705/darktable_raster_mask_d_common_disable_pipecache.txt)

After that I tried it again without "--disable-pipecache" and had the problem again:
Output:

[darktable_raster_mask_d_common.txt](https://github.com/darktable-org/darktable/files/11287725/darktable_raster_mask_d_common.txt)

What I also noticed - but this is not necessarily related to this problem - is that the results are not always displayed in the thumbnails in ligttable when the thumbnails have a certain size. With smaller thumbnails you don't see the results (from size 5 and above):

![grafik](https://user-images.githubusercontent.com/38165484/233409826-fc83c40c-cbf3-4379-a758-f36d682799a4.png)

From size 4 it looks then like in the darkroom:


![grafik](https://user-images.githubusercontent.com/38165484/233411269-422151e3-69c3-4ece-9781-0f6e1e3be27b.png)

In this case it does not matter if with or without -disable pipecache.

**Comment by jenshannoschwalm** [comment] 2023-04-21 07:04
> What I also noticed - but this is not necessarily related to this problem

Not related but - an issue :-)

**Comment by s7habo** [comment] 2023-04-22 09:24
Thank you! The second issue is solved, but the first is still there.
I have now tested it with  4.3.0+1917~gba44a8d60
The same raw file as above

[darktable_raster_mask_d_common2.txt](https://github.com/darktable-org/darktable/files/11300928/darktable_raster_mask_d_common2.txt)

**Comment by jenshannoschwalm** [comment] 2023-04-22 13:30
@s7habo i think i simply don't get the issue **exactly**. Have not used raster masks much so likely i don't look at it "the right way". Maybe you could explain again in more detail?

**Comment by s7habo** [comment] 2023-04-22 15:43
First of all, thank you @jenshannoschwalm  for your effort!  

To better explain what the problem is, I made a short video :

https://youtu.be/wEChTZ9HAKc

**Comment by jenshannoschwalm** [comment] 2023-04-22 16:57
Whow. Understood what you mean, not understood what happens. The rastermask code is something I haven't worked on, so it might take a bit more time.

**Comment by s7habo** [comment] 2023-04-22 17:14
What I have just noticed is that this problem only affects the display of the result on the screen, not the internal processing.

When this phenomenon occurs and I zoom out and zoom in, the display is "corrected". See the end of the video:



https://user-images.githubusercontent.com/38165484/233797743-fdae363a-3382-4621-b054-45329571d37b.mp4

**Comment by jenshannoschwalm** [comment] 2023-04-24 16:45
Can you reproduce: After going to lighttable and back again to darkroom, here the issue is also **not** persisting, seems to be the same as "is ok" in your late video ???

**Comment by s7habo** [comment] 2023-04-24 17:03
>  After going to lighttable and back again to darkroom, here the issue is also not persisting, seems to be the same as "is ok" in your late video ???

Yes, the effect is the same as when I zoom in and out.

So in summary, effect is gone when I _either go into lighttable and then back into darkroom_, or when I _zoom in and out in darkroom_ - when I practically "**refresh**" the display on the canvas in darkroom after the problem appeared.

But if I go back into color balance module and move any slider, the problem reappears (raster mask is turned off again).  Then you have to repeat the steps above to get the correct display again.

**Comment by s7habo** [comment] 2023-04-24 17:45
I just realized, it gets weirder. :laughing:

In this video below, I zoom in and out to see if the problem reappears. And indeed, it does: 

https://user-images.githubusercontent.com/38165484/234074734-8008198f-2bc6-4a02-b099-96eefd4a46ba.mp4

**Comment by jenshannoschwalm** [comment] 2023-04-24 17:52
@s7habo i will track this down - promised! It will likely need some more days, this part of the pixelpipe is not trivial :-) Plus - there are no debugging tools for this (yet) - But: fixing other issues while checking this :-)

**Comment by s7habo** [comment] 2023-04-24 17:54
Thanks! I'll keep experimenting and let you know if I find anything.

**Comment by s7habo** [comment] 2023-04-28 18:09
I have just installed master and the problem I still there :confused:

**Comment by s7habo** [comment] 2023-04-28 18:12
DT 4.3.0+2027~g2b3d5ec05:


lighttable:

![grafik](https://user-images.githubusercontent.com/38165484/235222256-604445bc-8d5a-483a-bc4d-f78095997b5b.png)


darkroom:

![grafik](https://user-images.githubusercontent.com/38165484/235222512-19428f23-2988-4461-950d-714bb5dc5845.png)

**Comment by jenshannoschwalm** [comment] 2023-04-28 20:48
I see :-( Good thing here is: we see that on some reason the raster mask is lost. I think i did a slightly different test setting, i didn't duplicate the exposure module and for me that made the difference.

**Comment by s7habo** [comment] 2023-04-28 21:11
>  i didn't duplicate the exposure module and for me that made the difference.

I tried that too, using only the first instance for mask. Unfortunately it does not matter. I also tried to use different modules both for creating the mask and then for raster mask later in the pixelpipe. The problem appears again and again. This is a very tricky bug.

In any case, one thing is for sure - it is not bound to a specific module. 

The scheme is always the same - create the mask, use it later as a raster mask and higher in the pixelpipe it is ignored. But also not always. I have not noticed any regularity under which circumstances it is ignored/switched off. :confused:

**Comment by s7habo** [comment] 2023-04-28 21:29
By the way, it is also not tied to detail treshold. No matter on which way the mask is created (detail/parametric/drawn), if it is later used as a raster mask these problems appear. 

The rats from the pixelpipe seem to prefer it.

**Comment by jenshannoschwalm** [comment] 2023-04-28 23:15
> I tried that too, using only the first instance for mask.

1. So just one exposure module ?
For me this seems to make the difference. Couldn't reproduce if the mask was generated in that single module.
2. the -d pipe logs show the raster mask is lost in the reproducer

**Comment by s7habo** [comment] 2023-04-29 05:00
> So just one exposure module ?

yes

> the -d pipe logs show the raster mask is lost in the reproducer

I have started darktable with this option (-d pipe) and there seems to be dropouts regarding rastermask. I made a short video about this...

https://youtu.be/2VX2QJmx820

...and here is also the log file that was created during the processing that can be seen in the video:

[darktable_raster_mask_minus_d_pipe.txt](https://github.com/darktable-org/darktable/files/11358412/darktable_raster_mask_minus_d_pipe.txt)

I emphasize again, this does not always happen. I had to make one or two attempts before the problem appeared.

**Comment by jenshannoschwalm** [comment] 2023-05-06 15:23
@s7habo There has been another PR #14432 that should fix all remaining (not easy to trigger) issue related to detail, raster masks and history selecting.

I would appreciate it a lot, if you could test in depth after that got merged.

**Comment by s7habo** [comment] 2023-05-07 15:50
@jenshannoschwalm , I  was able to reproduce the bugs that were mentioned in https://github.com/darktable-org/darktable/issues/14393 and https://github.com/darktable-org/darktable/pull/14432. 

The issues only affect the raster mask regardless of which mask was used as the basis for creating the raster mask. Please see the details in the video: 

https://youtu.be/ijHPIvluXws

Here is the output of the terminal with -d common option accompanying the video:

[darktable_raster_mask_two_issues.txt](https://github.com/darktable-org/darktable/files/11415419/darktable_raster_mask_two_issues.txt)

**Comment by jenshannoschwalm** [comment] 2023-05-07 16:29
Yes. I also spent some time on this, at least some issues due to incorrectly calculated masks should be gone. One question, how are opencl settings? "Very fast or default"?

**Comment by s7habo** [comment] 2023-05-07 16:32
> One question, how are opencl settings? "Very fast or default"?


Very fast GPU

**Comment by jenshannoschwalm** [comment] 2023-05-07 17:02
Ok some issues fixed in the latest pr. But i have found an extremely easy to reproduce situation showing something really wrong with blending and raster masks. BTW this is not related to pixelpipe cache or opencl on/off, can be reproduced whatever you are using here.

Is a simple shape mask to control the first exposure module, fine.

Second exposure uses raster mask from first exposure, fine as long as no polarity is in use. If you toggle raster mask polarity-> whow. Log file shows raster mask is taken in both cases but only applied if not inversed.





[DSCF2164.RAF.xmp.txt](https://github.com/darktable-org/darktable/files/11415558/DSCF2164.RAF.xmp.txt)

It seems to be even more simple, have you tried a simple shape mask on exposure and invert it?

**Comment by s7habo** [comment] 2023-05-07 17:11
> have you tried a simple shape mask on exposure and invert  it?

I forgot to demonstrate this in video but yes, I tried it and no problems. Everything works as expected.

**Comment by jenshannoschwalm** [comment] 2023-05-07 17:21
Hmm. I'm absolutely not the video guy ...



[Bildschirmaufzeichnung vom 2023-05-07, 19-20-22.webm](https://user-images.githubusercontent.com/50982232/236692745-d03007f7-bf1a-435b-bd8b-e3fb998ae571.webm)

**Comment by s7habo** [comment] 2023-05-07 17:25
Just so that we don't misunderstand each other - if I use simple (drawn) mask and for second instance of the module I use *inverted version of the same mask* - **not** rastermark!-  there are no problems. 

Problems arise when in the second instance you do not use the inverted drawn mask itself, but the **inverted raster mask**, which is based on this drawn mask. Exactly as you have shown in your example.

**Comment by jenshannoschwalm** [comment] 2023-05-07 17:31
Yes i understand what you say. But what i am really surprised about is what happens if you simply just have a shape mask and invert it. I would expect to only have any effect on pixels-not-inside-the-shape...

**Comment by s7habo** [comment] 2023-05-07 17:46
> I would expect to only have any effect on pixels-not-inside-the-shape.


This is indeed the case. 

The problem with the mask - the circle - that you used in your example is the transparency of the mask. It has only 44% opacity:

![image](https://user-images.githubusercontent.com/38165484/236693662-49cc8752-73b3-4b84-8480-ed1743be1bac.png)

 If you invert it, then the part inside the shape will be affected accordingly (it has only 56% opacity there):

![image](https://user-images.githubusercontent.com/38165484/236693843-630dc1ed-29e6-4456-890a-bc010721f27d.png)

**Comment by s7habo** [comment] 2023-05-07 17:53
If opacity is 100%, then the inner area will be completely transparent when the mask is inverted:

![image](https://user-images.githubusercontent.com/38165484/236694211-6e0509fd-828b-4ce0-9b9b-920e37f6805e.png)

**Comment by jenshannoschwalm** [comment] 2023-05-07 18:01
Arrrrgh!

Btw i think i have found the inverted raster mask issue. Pascal will have a look but it seems to be a very old one ...

**Comment by jenshannoschwalm** [comment] 2023-05-10 19:37
May i ask you again to check current master? (You have much more use for any mask than me so i would likely not run into issues but we want all remaining issues getting fixed in 4.4 :-)

**Comment by s7habo** [comment] 2023-05-10 20:15
Have done just now. 

With darktable 4.3.0+2236~g46414573f. 

Nothing new. The same issues as described in the video above:

![grafik](https://github.com/darktable-org/darktable/assets/38165484/caf5e958-44b6-4ea0-9035-a7d41d1e5196)

**Comment by s7habo** [comment] 2023-05-10 20:16
-d common

[darktable_raster_mask_issues_continued.txt](https://github.com/darktable-org/darktable/files/11445645/darktable_raster_mask_issues_continued.txt)

**Comment by s7habo** [comment] 2023-05-10 20:19
![grafik](https://github.com/darktable-org/darktable/assets/38165484/3d23df9c-603e-44e0-975a-36de3ffb09a2)

**Comment by TurboGit** [comment] 2023-05-10 20:20
@s7habo : Can you check if you are using down-sampling? 

`preferences` -> `darkroom` -> `reduce resolution of preview image`

If so, try again with "original" (no down-sampling).

**Comment by s7habo** [comment] 2023-05-10 20:24
> If so, try again with "original" (no down-sampling).

I use that option. I don't use down-sampling.

**Comment by s7habo** [comment] 2023-05-10 20:56
Raw file with Bird. 

@jenshannoschwalm , @TurboGit Have you tried to reproduce it?

 It is enough to go to the lighttable and back to the darkroom. 

The raw file is from:

https://discuss.pixls.us/t/gamut-issues-should-i-be-worried/36719

The sidecar file:

[ER6_2855.CR3.xmp.txt](https://github.com/darktable-org/darktable/files/11445840/ER6_2855.CR3.xmp.txt)

**Comment by jenshannoschwalm** [comment] 2023-05-10 20:59
I will check tomorrow. You comment about go to Lightroom and back to dr might be a hint as we keep cachelines ...

**Comment by jenshannoschwalm** [comment] 2023-05-12 09:05
I am not quite sure what the exact status of "remaining issues" is.

I can reproduce issue related to color picker for sure and would concentrate on that first. Unfortunately i have never looked & touched color_picker code yet. @TurboGit  @dtorop @dterrahe what would be the place to look here? (Where is color_picker data taken and where is is written? )

**Comment by dterrahe** [comment] 2023-05-12 12:19
Haven't in depth read this whole issue so not sure what color picker you are referring to. The parametric masks ones? So first a very high level overview (which you probably figured out already).

Colorpicker data gets calculated, if requested for a module, in the pipe in `pixelpipe_process_on_CPU` or `dt_dev_pixelpipe_process_rec` and when available a signal `DT_SIGNAL_CONTROL_PICKERDATA_READY` is sent to the UI thread. This gets picked up in `_iop_color_picker_pickerdata_ready_callback` which sets
```
  piece->pipe->changed |= DT_DEV_PIPE_REMOVE;
  piece->pipe->cache_obsolete = 1;
```
and propagates the signal to the blending code first (`blend_color_picker_apply`) and then to the per module method `color_picker_apply`. If a module has multiple pickers, it needs to check there first which one is active.

Last time I looked at this, without much _understanding_; I was just refactoring :-) was a while back. Please let me know if I can help figuring it out.

**Comment by dtorop** [comment] 2023-05-12 14:14
And this comment

https://github.com/darktable-org/darktable/blob/09d99ce81f139ee9c7dd60f8c73ad6f35503861d/src/gui/color_picker_proxy.c#L28-L57

gives a rundown of some of how the pixelpipe picker interacts with the GUI. Likewise, I've done some refactoring in the last couple years, but don't understand this ongoing debugging work enough to know how the colorpicker interacts. But happy to try to elucidate anything I know about colorpicker code.

**Comment by jenshannoschwalm** [comment] 2023-05-18 05:33
@s7habo may i ask you again? I can **not** reproduce the demonstrated issues any more with #14533 applied.

If there are still issues for you `-d pipe` logs would be perfect.

**Comment by s7habo** [comment] 2023-05-21 06:56
I have just tested it and the first issue 
https://github.com/darktable-org/darktable/issues/14393
is solved.  I can't reproduce it anymore.

Problem in this bug report still exists in part. The _navigator, color picker and histogram_ still **lose the data** when you switch to the lighttable and then come back to the darkroom:

![rastermask_Issue](https://github.com/darktable-org/darktable/assets/38165484/5c7ee7ff-55f2-4593-a449-1252174e1138)



 Watch the short video:

https://youtu.be/UYDPrYCOMT4
 
Here is the output of the terminal with -d pipe option:

[darktable_raster_mask_issues_after_14533.txt](https://github.com/darktable-org/darktable/files/11523848/darktable_raster_mask_issues_after_14533.txt)

**Comment by jenshannoschwalm** [comment] 2023-05-21 07:57
1. Thanks for testing
2. Strange i did  not observe this, do you have any presets for the involved modules by chance?

Will keep on tracks!

**Comment by s7habo** [comment] 2023-05-21 08:00
>     do you have any presets for the involved modules by chance?

No, I do not use presets. Everything is default.

**Comment by s7habo** [comment] 2023-05-21 08:06
By the way, the data loss in the navigator, color picker and histogram is the only problem now. On the canvas in darkroom and as thumbnail in ligthtable the raster mask is displayed correctly. There are no more problems.

**Comment by jenshannoschwalm** [comment] 2023-05-21 14:30
> the data loss in the navigator, color picker and histogram is the only problem now.

Sounds as that can still be fixed for 4.4 :-)

**Comment by s7habo** [comment] 2023-05-21 16:15
Another couple of things I have just noticed:

1. when I restart darktable and go into drakroom the _problem does not_ appear. But when I then go into _lighttable_ and then _back into darkroom_, the issue _is there again_.
2. When issue is there (when navigator, color picker and histogram have no data) and when you _zoom in or out in canvas_, you can see that the _intermediate steps also turn black_ when zooming. These _black intermediate steps_ are _not present_ in the canvas when zooming, if you use other mask types where the problem does not appear.
3. Despite these black intermediate steps, unlike the navigator, color picker and histogram, the image in the canvas gets _updated when the zoom operation is over_.

This can be seen very well in the short video:


https://github.com/darktable-org/darktable/assets/38165484/c33dec46-df91-4fab-af35-05addb6009a9

**Comment by s7habo** [comment] 2023-05-21 16:36
What I meant above under _intermediate zooming steps_ is this: 

![grafik](https://github.com/darktable-org/darktable/assets/38165484/4ce44444-6e8f-4054-82d1-984d72748d4d)

When zooming process is finished, the image appears, but only on the canvas. Navigator and color picker remain black and Histogram shows only black.

![grafik](https://github.com/darktable-org/darktable/assets/38165484/ec928dda-463c-43ea-ae34-ee1bda33bbf1)

**Comment by jenshannoschwalm** [comment] 2023-05-21 16:43
Yes. That sounds a lot like preview pixelpipe(s) don't always a) get correct blend parameters or b) some cache issue. As usual i would ask; do you see this with pipe cache disabled (i will find out :-)

**Comment by s7habo** [comment] 2023-05-21 16:48
> s usual i would ask; do you see this with pipe cache disabled (i will find out :-)

No. When pipe cache is disabled ( --disable-pipecache ) everything runs as expected. No issues at all.

**Comment by jenshannoschwalm** [comment] 2023-05-21 16:54
> No. When pipe cache is disabled ( --disable-pipecache ) everything runs as expected. No issues at all

ok. Same here. BTW i just could reproduce. And very strange: the log looks like "it should be ok in preview too".

**Comment by s7habo** [comment] 2023-05-22 06:25
No change unfortunately.

**Comment by s7habo** [comment] 2023-05-22 06:46
Maybe the hint is, that the problem occurs **only** when you go into lighttable and then back into darkroom. 

If you process the photo without going into lighttable, everything works without problems.

That is, when going **into lighttable and/or going back from lighttable into darkroom**, something happens that **causes the Navigator, Color Picker and Histogram data to be lost**.

**Comment by jenshannoschwalm** [comment] 2023-05-22 10:27
Could you check the log while switching from light table to darkroom? Just that part would be fine. -d pipe -d opencl please in this case...

**Comment by s7habo** [comment] 2023-05-22 12:08
One more remark what I just discovered:

When the problem occurs, and then when I switch in **scopes window** from **vectorscope** to **waveform** or **histogram** and vice versa, **the problem disappears.** The rendering is correct again.

If I switch from **waveform** to **RGB parade**, nothing changes.

**Comment by jenshannoschwalm** [comment] 2023-05-22 18:30
Ok.
1. I can reproduce here so far **only** if a color picker was active before adding the raster mask as source.
2. I also see the "interesting" conversion debug output line.

**Comment by s7habo** [comment] 2023-05-22 18:38
> I can reproduce here so far only if a color picker was active before adding the raster mask as source.

Strangely, I can **always** reproduce it. 

I have also discovered something concerning the color picker. Video coming in a moment...

**Comment by jenshannoschwalm** [comment] 2023-05-22 19:01
I am thinking about two things now, maybe @TurboGit or @dterrahe have an idea about either, i might be a bit blind on this ...

2. In pixelpipe cache code 
```
    if(!(dev->gui_module && dev->gui_module != piece->module
         && (dev->gui_module->operation_tags_filter() & piece->module->operation_tags())))
    {
      hash = ((hash << 5) + hash) ^ piece->hash;
      if(piece->module->request_color_pick != DT_REQUEST_COLORPICK_OFF)
      {
        if(darktable.lib->proxy.colorpicker.primary_sample->size == DT_LIB_COLORPICKER_SIZE_BOX)
        {
          const char *str = (const char *)darktable.lib->proxy.colorpicker.primary_sample->box;
          for(size_t i = 0; i < sizeof(float) * 4; i++)
            hash = ((hash << 5) + hash) ^ str[i];
        }
        else if(darktable.lib->proxy.colorpicker.primary_sample->size == DT_LIB_COLORPICKER_SIZE_POINT)
        {
          const char *str = (const char *)darktable.lib->proxy.colorpicker.primary_sample->point;
          for(size_t i = 0; i < sizeof(float) * 2; i++)
            hash = ((hash << 5) + hash) ^ str[i];
        }
      }
    }
``` we only check for **one** picker per module. How does that correlate with the left side "color picker lib"?

2. We don't include the module's `dsc` in the hash. I thinks that's correct as it's changed in process()
3. `dt_dev_pixelpipe_cache_get()` doesn't update the dsc if there was a hit. Would that be necessary?

**Comment by s7habo** [comment] 2023-05-22 19:01
https://youtu.be/l05Q9rotW5c

Terminal output:

[darktable_setps_with_d_pipe_d_opencl_V2.txt](https://github.com/darktable-org/darktable/files/11535987/darktable_setps_with_d_pipe_d_opencl_V2.txt)

**Comment by s7habo** [comment] 2023-05-22 19:41
> And i would want to say: you have fully earned yourself a drink or two for this in-deepest-depth testing :-)

Indeed. But I don't mind the testing. On the contrary. 

The frustrating thing for me is that I'm too stupid to look at the code and you (and of course others) have to do this most difficult part.  

So I'm the one who invites for the round when the time comes. :beers:

**Comment by dterrahe** [comment] 2023-05-22 19:47
I'm sorry I'm away from my development machine until end of the month so can't help (even if I did understand any of the caching stuff, which i don't).

**Comment by jenshannoschwalm** [comment] 2023-05-22 22:46
@s7habo just to make sure, can you confirm:
1. If you are using a second (default) instance of exposure module to generate the raster mask later used by color contrast, there is no issue?
2.  If you watch out in the log for the "extra color conversion" line, it's a) always **absent** if there is **no issue** and b) always **there** if there **is** an issue?

**Comment by s7habo** [comment] 2023-05-23 01:41
> If you are using a second (default) instance of exposure module to generate the raster mask later used by color contrast, there is no issue?

Indeed. When raster mask is made with second instance, problem does not appear.

> If you watch out in the log for the "extra color conversion" line, it's a) always absent if there is no issue and b) always there if there is an issue?


Here I have made two tests.  

In the first one, I made the raster mask with the first instance of the exposure module, as usual. 
In this example it is indeed the case that there is **one line too much** in the preview when the **issue is there**, or - as you put it - is always **absent** if there is **no issue**.

Here is terminal output:

[darktable_setps_with_d_pipe_d_opencl_RM_E_1_Instance.txt](https://github.com/darktable-org/darktable/files/11538264/darktable_setps_with_d_pipe_d_opencl_RM_E_1_Instance.txt)

Here is the same output, but commented by me (with description of the steps and marking the line in question):

[darktable_setps_with_d_pipe_d_opencl_RM_E_1_Instance_with_comment.txt](https://github.com/darktable-org/darktable/files/11538278/darktable_setps_with_d_pipe_d_opencl_RM_E_1_Instance_with_comment.txt)


In the second test I used the first instance of the color calibration module for creating the raster mask which was then  used in the contrast equalizer. 
And there it is the other way round - there is **one line missing** when **issue appears**!   :laughing:

Terminal output:

[darktable_setps_with_d_pipe_d_opencl_RM_CC_1_Instance.txt](https://github.com/darktable-org/darktable/files/11538325/darktable_setps_with_d_pipe_d_opencl_RM_CC_1_Instance.txt)

Commented version:

[darktable_setps_with_d_pipe_d_opencl_RM_CC_1_Instance_with_comment.txt](https://github.com/darktable-org/darktable/files/11538330/darktable_setps_with_d_pipe_d_opencl_RM_CC_1_Instance_with_comment.txt)

**Comment by jenshannoschwalm** [comment] 2023-05-23 05:34
Whow. So we're somehow on the right track. It's not something special with exposure module but seems to correlate with colorspace of raster-writing-module??

**Comment by s7habo** [comment] 2023-05-23 07:40
>  It's not something special with exposure module but seems to correlate with colorspace of raster-writing-module??


Interestingly, this does not affect **all** modules

I have used several modules to generate the raster mask to see what happens. 

The modules where the **problem occurs** are:

exposure
tone equalizer
color calibration

In these modules, the issue indeed **correlates** with the **color space**. 

With the **exposure** module and **tone equalizer** the line in [preview] output:

_colorin IOP_CS_LAB -> IOP_CS_RGB_

is one line **too many** compared to lines listed in [full]. This can be corrected by changing scope in the scope window.

When the **color calibration** module is used to generate the raster mask, in the [preview] output **a line is missing** that is present in [full]:

_atrous  IOP_CS_RGB -> IOP_CS_LAB_

This also an be corrected by changing scope in the scope window.

In both examples, this unwanted change always happens just before the other module gets its raster mask.

In some other modules that I have also tested for generating the raster mask, the problem **does not appear**. These are:

liquify
retouch
difuse and sharpen
contrast equalizer
color balance rgb

With these modules the output in [preview] **corresponds** to the output in [full].

**Comment by jenshannoschwalm** [comment] 2023-05-29 15:15
@s7habo may i ask you again?

**Comment by s7habo** [comment] 2023-05-29 16:23
Yes @jenshannoschwalm ! You did it! :tada: :rocket: :cake:

**Comment by jenshannoschwalm** [comment] 2023-05-29 16:43
Great to close this :-)))

**Closed by jenshannoschwalm** 2023-05-29 16:43 UTC
Labels: reproduce: confirmed, bug: pending
