### ISSUE TITLE
Lens correction is not applied when copying history stack to another photo

### ISSUE THREAD

**Issue by s7habo** [darktable-org/darktable#12293] opened 2022-08-09 08:56 UTC
**To Reproduce**

1. In lighttable, copy history stack from one edited photo (with lens correction turned on) and paste it to another. 
2. Open that another photo in darkroom. History stack is applied but without lens correction (lens correction module is turned off)

Interestingly, lens correction _is_ applied when you copy the history stack in lighttable with "copy" function and apply it with _"selective paste"_:

**To Reproduce**

1. In lighttable, copy history stack from one edited photo (with lens correction turned on).
2. Choose "selective paste" option. Popup window opens with list of modules used in the photo. Among other things, Lens Correction module is also active. 
3. Click "OK" without any further changes. In darkroom, open this photo to which you applied history stack. Lens Correction module is also active this time.

**Expected behavior**

If you copy history stack from one photo where Lens Correction was applied to the other, Lens Correction should be applied to the other photo as well.

If another photo has a different lens, for example, the lens correction should either be adjusted automatically or you can use the "selective paste" option when copying and deactivate lens correction there. After that you can switch on the correction manually in darkroom.

**Platform**

* darktable version : 4.1.0~git122.196131db-1
* OS                :Kubuntu 20.04
* Graphics card     : NVIDIA GeForce GTX 1070
* Graphics driver   : 470.141.03
* OpenCL installed  : yes
* OpenCL activated  : yes

**Comment by Nilvus** [comment] 2022-08-09 10:17
Duplicate of #9585 (I suggest you to read it and links posted. It's not an issue so I close.

**Closed by Nilvus** 2022-08-09 10:17 UTC
