### ISSUE TITLE
Grid disappears in "rotate and perspective" module

### ISSUE THREAD

**Issue by CubicrootXYZ** [darktable-org/darktable#12890] opened 2022-11-13 20:25 UTC
**Did you buy darktable from an application store ?** Nope

**Describe the bug/issue**

When in the "rotate and perspective" module the grid disappears and enabling/disabling it will not bring it back. As soon as I switch into another module and change sth there the grid is back. 

**To Reproduce**

1. Open image in darkroom 
2. Enable grid
3. Rotate image in "rotate and perspective"
4. Grid disappears
5. Press "g" or the grid button - nothing happens
6. Change sth in another module - grid is back

**Expected behavior**

The grid should be visible in rotate module.

**Screenshots**

![image](https://user-images.githubusercontent.com/24812442/201542732-2ec45919-3fce-4565-84aa-c88796c1caf0.png)

**Which commit introduced the error** idk

**Platform**

* darktable version : 4.0.1
* OS                : e.g. Linux - 5.15.0-52-generic
* Linux - Distro    : Ubuntu 22.4
* Memory            : unknown
* Graphics card     : unknown
* Graphics driver   : unknown
* OpenCL installed  : unknown
* OpenCL activated  : unknown
* Xorg              : unknown
* Desktop           : Gnome
* GTK+              : unknown
* gcc               : unknown
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Additional context**
none

**Comment by pehar1** [comment] 2022-11-14 07:09
Not able to reproduce with current master

darktable 4.1.0+991-g0a5f6d199
OS : Linux 5.15.0-46-generic / Ubuntu 22.04.1 LTS
Memory : MemTotal:       65773056 kB
Graphics Card :     Product Name                          : NVIDIA GeForce RTX 2060
Graphics Card : Driver Version                            : 470.141.03
OpenCL installed :   Device OpenCL C Version                         OpenCL C 1.2 
OpenCL activated : yes
Xorg : Version: 1:7.7+23ubuntu2
Desktop : LXQt
GTK+ : 3.24.33
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
CMAKE_BUILD_TYPE : release

**Comment by Nilvus** [comment] 2022-11-14 19:10
So this means this is already fixed. Actual master is future 4.2 release. Release is planned around 21th december. Note that Ubuntu apt repos are updated quite later (depends on Ubuntu maintainers). To have up-to-date release earlier, best way is to add OBS repository. See there: [https://software.opensuse.org/download.h...=darktable](https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable) (better to follow "Add repository and install manually" instructions. That will include that repository to your Ubuntu updates).

To have a fix for your issue, you will so have to wait 4.2 release. There will not be another release before. I so close this issue by now.

**Closed by Nilvus** 2022-11-14 19:10 UTC
