### ISSUE TITLE
When accented character are in the path darktable in windows fails to process the photos correctly

### ISSUE THREAD

**Issue by vsanchez** [darktable-org/darktable#15863] opened 2023-12-13 02:15 UTC
### Describe the bug

In a very recent version of windows, 4.5.0+1435~g6d4cfccf32, i am having a very serious problem. When I import a set of photos that are contained in a folder that has an accented character or ñ it will import the photos but will not read the metadata (or perhaps is unable to store it in the database). When one starts it again and it recognizes that the XMP files are newer that the database registry it will say that it cannot write it in the database, giving the following error:

![imagen](https://github.com/darktable-org/darktable/assets/74031/6ff403ef-a768-4e57-9d6d-c48f4afddce4)

This problem was not present before and it is not present in Linux (in a slightly older release 4.5.0+1412)

### Steps to reproduce

Create a directory that contains in its name an accented character. Try to import the contents of that directory. The photos will not have information about shutter speed, etc. Will not be automatically rotated, etc. 

### Where did you obtain darktable from?

self compiled

### darktable version

4.5.0+1435~g6d4cfccf32

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA Ge Force RTX 4070Ti

**Comment by kmilos** [comment] 2023-12-13 08:26
Duplicate of https://github.com/darktable-org/darktable/issues/15478

Please search before opening new issues.

**Closed** 2023-12-13 10:51 UTC
Labels: duplicate
