### ISSUE TITLE
[New ModuleGroups] ...cause GUI refresh performance loss {bisected}

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#6522] opened 2020-10-13 21:32 UTC
**Describe the bug**

Recently something caused me a GUI-refresh or redraw sluggishness.

I "feel" it in darkroom, e.g. when popup windows appear (e.g. duplicate manager's question, whether I really want to delete).

But also when I "draw" a new window on top of dt. 
_With the following I describe something, one may easily (and too fast) say, "oh this is not a dt issue..."_ I clearly bisected it... 

So (not only) for testing purposes, I refer to my bash-tool I use, which is _yakuake_ That one opens up like a curtain from the top of your screen.

When dt: 
- has the focus (click on it) 
- is in darkroom 
- and you press F12 (or FN-F12 for some laptops), recently that roll down is very slow.
- go back to lighttable and repeat that test, it is normal
- bring the focus to another Window on your system and the behaviour is normal too (dt in darkroom mode but no focus)

**To Reproduce**
see above please

**Expected behavior**

GUI update speed prior commit  2058f80

**BiSect**

Bisect gave me:
```
2058f803637f53f7de3093ec3b7e2a57b2285fc7 is the first bad commit
commit 2058f803637f53f7de3093ec3b7e2a57b2285fc7
Author: AlicVB <dev@lnaa.fr>
Date:   Sat Sep 19 20:13:01 2020 +0200

    iop_layout: @aurelienpierre new icons for groups

 src/dtgtk/paint.c       | 89 ++++++++++++++++++++++++++++++++++++++++++++-----
 src/dtgtk/paint.h       | 10 ++++--
 src/libs/modulegroups.c | 28 ++++++++++++++--
 3 files changed, 114 insertions(+), 13 deletions(-)
```
@AlicVB I am quite afraid, yet again I give you something, you cannot reproduce :-/ as @matt-maguire was kindly testing thru discussions on IRC and could not, either.

**Platform and Additional context**
* darktable version : 3.3.0+948~g1b164d2c7
* OS                : Linux - kernel 5.7.15-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.100-r2
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by junkyardsparkle** [comment] 2020-10-13 22:48
The version of the build you give is a random commit in the middle of the work on the new layout, there were many related ones after that. Maybe try a more recent build?

Also, understand that your instruction to "press F12" doesn't tell anything about what you're actually doing, that key could be bound to anything... it sounds like you use it as a global desktop environment shortcut? (Using unmodified Fn keys this way isn't a great idea, since many applications use them) In any case, it sounds like an issue of a window manager competing with darktable for gpu resources.

**Comment by dterrahe** [comment] 2020-10-14 08:56
@AxelG-DE would you mind testing if 8c31abfd716b8dc6a0c7a07be6d6f195298d679c had an impact on this?

That commit was needed to fix a glitch with some newly-resizeable lib modules (mostly left-hand side in darkroom) that didn't always update immediately after they were resized. After this commit, they check their size every time they are painted. The performance impact was a concern, but seemed negligible with the testing I (and @TurboGit) did before the PR was merged. It would be helpful if you could confirm that this is indeed not related to the slowdown you are now seeing.

**Comment by matt-maguire** [comment] 2020-10-14 09:05
> Also, understand that your instruction to "press F12" doesn't tell anything about what you're actually doing, that key could be bound to anything...

In this case, F12 is bound to a pop-up shell window called yakuake. On my system, it pops up normally, but on @AxelG-DE 's system it is very slow to pop up when darkroom is active. I checked with @AxelG-DE whether his system might have been heavily paging/swapping, but this was not the case.

**Comment by AlicVB** [comment] 2020-10-14 09:26
I'll have a look and try to reproduce (not this week), but I'm *very* doubtful that the mentioned commit https://github.com/darktable-org/darktable/commit/2058f803637f53f7de3093ec3b7e2a57b2285fc7 can have anything to do with this issue : All parts of it's content are called on darkroom enter only or when showing the modulegroups dialog...

To exclude (or not) the only possibility I can think of, can you test this : 
- create a new layout and be sure to *not* use `grading` or `technical` icons for the group you choose (you can even set up an empty layout)

thanks

**Comment by AxelG-DE** [comment] 2020-10-14 11:20
I will test tonight, when I am back home from office...

**Comment by AxelG-DE** [comment] 2020-10-14 18:17
@AlicVB 

> To exclude (or not) the only possibility I can think of, can you test this :
> 
>     * create a new layout and be sure to _not_ use `grading` or `technical` icons 

**BINGO**
I created a totally empty set and then the sluggish is gone
Switch back to my own module set, which looks like below, the sluggish is back!

![Screenshot_20201014_201522](https://user-images.githubusercontent.com/49004103/96028792-11002600-0e5a-11eb-9e33-ebed2f0cc818.png)

**Comment by AxelG-DE** [comment] 2020-10-14 18:29
> @AxelG-DE would you mind testing if [8c31abf](https://github.com/darktable-org/darktable/commit/8c31abfd716b8dc6a0c7a07be6d6f195298d679c) had an impact on this?

@dterrahe 
tested, is not the one (also it is older than what I found thru bisect)

**Comment by AlicVB** [comment] 2020-10-14 20:15
@AxelG-DE : great ! So it seems that one of the 2 new icons introduced in the commit is the culprit... Can I abuse your time with another test ?
can you test if you reproduce this issue with a duplicated "default" preset and : 
- all the group icons set to "basic"
- all the group icons set to "grading"
- all the group icons set to "technical"

thanks again for your help

**Comment by junkyardsparkle** [comment] 2020-10-14 20:48
> In this case, F12 is bound to a pop-up shell window called yakuake. On my system, it pops up normally, but on @AxelG-DE 's system it is very slow to pop up when darkroom is active.

Thanks for the explanation, reading the issue again I guess that information was *kind of* included... anyway @AxelG-DE, sorry for my initial response... I can't wait to find out how an icon is causing this one... :popcorn:

**Comment by AxelG-DE** [comment] 2020-10-14 22:24
I will do the required tests indeed.
As Thursday is gym time, it might have to wait by the weekend though :-)

**Comment by AxelG-DE** [comment] 2020-10-15 18:55
@AlicVB test accomplished

**BINGO^2**

-    all the group icons set to "basic"           --> _fast_
-    all the group icons set to "grading"       --> **super SLOW**
-    all the group icons set to "technical"    --> _fast_

**Comment by AlicVB** [comment] 2020-10-15 19:20
ok thanks for your tests.
so it seems that on your system, for some reason, the drawing of the grading icon is slow...
Sadly I've no idea why, the cairo code doesn't looks too complex... @aurelienpierre : any idea ? this is your code at the beginning :P 

in the meantime, a quick workaround could be to avoid the use of the grading icon ;)

**Comment by AxelG-DE** [comment] 2020-10-15 19:34
> in the meantime, a quick workaround could be to avoid the use of the grading icon ;)

Yes, I switched to _colour_ icon and it helps.
One keep in mind, the above test is for illustration only. Really the GUI refreshes faster w/o grading icon (e.g. when you duplicate an image, teh redrawing of that part of the GUI is noticeably affected)

**Comment by AxelG-DE** [comment] 2020-10-15 20:07
I just figured, filmstrip in darkroom scrolls way faster again with this workaround

**Comment by matt-maguire** [comment] 2020-10-15 20:43
This dtgtk_cairo_paint_modulegroup_grading() function seems to get called quite often, and each time you are creating and destroying two patterns and doing three fill operations. Would it be better to cache the icons in a surface, rather than redrawing them from scratch every time?

**Comment by AxelG-DE** [comment] 2020-11-17 11:10
I just tested n current master 3.3.0+1680~g838418e38 
issue is still there

**Comment by AlicVB** [comment] 2020-11-18 11:15
@aurelienpierre : this icon is your work, in fact. I'm not sure we can do anything to simplify the drawing, though...
@matt-maguire : this would have to be done on dtgtk_*button level... and it would be a huge task... to be honest, for most case, I wonder if using external svg images wouldn't be simpler... (I have absolutely no idea if that would enhance or degrade perfs...)

The only "simple" point maybe to improve is trying to reduce the number of redraw, I'll have a look, but no promise...

**Comment by AxelG-DE** [comment] 2020-11-18 12:36
> EDIT : here, all redraw seems only usual system ones, so we can't reduce them... => no idea how to solve this... better use another icon until we find a solution !

That is, what I do. Just don't wanna close this, just as is. 
Funfact: on my lenovo-laptop with i7 and onCPU opencl (UHD5500 IIRC) you cannot feel this speed-loss. Hard to understand, why my core i9 9900k shows this hard impact

**Comment by johnny-bit** [comment] 2020-12-15 19:26
Cairo magic....

Interesting idea could be caching icons to virtual surface and then drawing icons from cache.

**Comment by Nilvus** [comment] 2021-07-02 15:00
@AxelG-DE: could you test again with last master and check if you can reproduce this issue or not? And close it, if not of course. Thanks.

**Comment by johnny-bit** [comment] 2021-07-02 15:20
@Nilvus - the issue is sstill present as evidenced by #9148 and it's a mix of problems: pixman/nvidia/gpu. IMO in this case the icons instead of painted on every refresh, should be painted to pixmap (as a cache) and placed on tabs as such since there's no need for per-flag changes for them.

**Comment by AxelG-DE** [comment] 2021-08-02 06:04
I am still (and will be for quite some time) without PC hence cannot test if issue still persists.

Please no auto-close

**Comment by AxelG-DE** [comment] 2021-10-02 06:59
Unfortunately I still cannot test, whether this issue is still persistent

**Comment by AxelG-DE** [comment] 2021-12-02 13:41
Ping

**Comment by jenshannoschwalm** [comment] 2023-05-23 18:47
There has been a lot of work spent on "redrawing performance" in 4.4. Closing for now until re-opened with fresh data.

**Closed by jenshannoschwalm** 2023-05-23 18:47 UTC
Labels: scope: UI, scope: performance, bug: pending, no-issue-activity
