### ISSUE TITLE
Culling mode view has vertical scrollbar which is useless.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#8054] opened 2021-02-01 00:53 UTC
Master debug with release.
darktable 3.5.0+891~gc672080f5

WSL Ubuntu 20.04

Culling mode view has scrollbar which is useless.

We have had this discussion before when it was there and not there and was told its not supposed to be there.

![image](https://user-images.githubusercontent.com/1119439/106403697-f2985780-6455-11eb-951e-afd9b57ca5d5.png)

**Comment by Nilvus** [comment] 2021-02-01 20:52
Can't reproduce on 3.5.0+897~g88067a4e8. You will need to be more precise and/or find how to reproduce exactly and how you can't reproduce. If I set same view as yours (black theme, eight images displayed, all panels visible), no scrollbars.

**Comment by johnny-bit** [comment] 2021-06-08 15:41
can't replicate on `3.5.0+2484~g3fb45f9a4` either. Closing due to non-reproducability. If we could replicate then sure, we'll reopen.

**Closed by johnny-bit** 2021-06-08 15:41 UTC
Labels: no-issue-activity, understood: unclear
