### ISSUE TITLE
Crop is incorrect when cropping a portrait image to landscape

### ISSUE THREAD

**Issue by yellowsink** [darktable-org/darktable#17206] opened 2024-07-26 18:45 UTC
### Describe the bug

When setting a crop on a portrait image that should produce a landscape crop, the set area does not match the output.
It appears to me as if the "bottom" setting of the crop is completely ignored and all others are applied.

this issue appears to be consistent across darkroom, lighttable, and export.

### Steps to reproduce

1. Open a portrait image in darktable
2. Enable crop, and set a landscape crop area
3. Apply the crop
4. The bottom edge of the crop is ignored and extends entirely down

### Expected behavior

The crop area shown in the preview should match the actual output.

### Logfile | Screenshot | Screencast

[dt.log](https://github.com/user-attachments/files/16395520/dt.log)
![image](https://github.com/user-attachments/assets/a167c8e1-5aba-4625-a4df-5cbf405cf967)
![image](https://github.com/user-attachments/assets/b0252157-4af7-41f1-ba58-81b93bb75654)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.8.0

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Describe your system?

OpenCL is not in use on my system (not supported), running on Wayland, x86-64

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Steps are reproductible with a fresh edit.
I do not use lua scripts.
Only tested with JPEG, I don't have raws on hand.

**Comment by jenshannoschwalm** [comment] 2024-07-26 18:56
Unfortunately a known problem "by design" ATM, will be fixed in 5.0. sorry ...

**Comment by yellowsink** [comment] 2024-07-26 19:06
Hmm okay, I'll wait for 5.0 and reprocess that photo. No worries.
Out of interest, I'd love to know why exactly that's by design!

**Comment by jenshannoschwalm** [comment] 2024-07-26 20:18
Just a suboptimal way how to assume what is a landscape photo.

**Comment by pehar1** [comment] 2024-07-27 06:07
Has been fixed with #17052 for 4.8.1. Checked with current master (4.9.0+76~g832fd4f39d) which should be very close to 4.8.1. Crop works correctly, both with rotated aspect of "_original image_" and with "_freehand_".

**Closed** 2024-07-27 09:08 UTC
Labels: scope: image processing, Fixed in master
