### ISSUE TITLE
Alert message when opening Darktable 3.2.1 and then in crashes

### ISSUE THREAD

**Issue by photomn** [darktable-org/darktable#7407] opened 2020-12-23 00:05 UTC
When I open darktable, it appears a dialogue stating where to find a report, and then, when I click Ok the program crashes.

I use a HP 250 G7 notebook
OS: Windows 10
Ram: 8 GB
Processor: Intel Celeron N4100
OpenCL: I tried with both on and off but nothing happens

I enclose the report from darktable

Thank you all for any response 

[darktable_bt_LS63V0.txt](https://github.com/darktable-org/darktable/files/5732551/darktable_bt_LS63V0.txt)

**Comment by ralfbrown** [comment] 2020-12-23 04:48
The backtrace indicates that the Lua (script) interpreter was trying to close a file with a nonexistent name (NULL pointer).  This is most likely due to some kind of misconfiguration, though it will take someone better versed in Lua to diagnose things in more depth.

In the mean time, please try running with an empty configuration (as if this were the first-ever run on this machine) to rule out a bad setting in your darktable config file.  You can do this by creating an empty directory somewhere and pointing darktable at it.  I haven't used Windows in a very long time, but from a terminal / commandline window, type
   "{path-to}\darktable.exe" --configdir "{path-to-empty-dir}"
replacing {path-to} and {path-to-empty-dir} with the full path to the darktable executable (something like C:\Program Files\x86\....) and the full path to your empty directory.  You can find the path to the executable by right-clicking on the desktop shortcut and looking in Properties.

If darktable starts up successfully, it means that your darktablerc file has a bad setting.

**Comment by wpferguson** [comment] 2020-12-23 19:51
You could also try starting darktable from the command line with the `-d lua` switch which should tell you what lua was doing when it crashed.  You can save the output by add the `>log.txt` to the end of the command.

**Comment by photomn** [comment] 2020-12-23 22:12
@ralfbrown  thanks a lot. Your solution is working. The program is not crashing anymore

**Comment by johnny-bit** [comment] 2020-12-23 23:12
> thanks a lot. Your solution is working. The program is not crashing anymore

so! the issue is solved ;) I'll close the issue now ;)

@photomn - if you want to further help, after reconfiguring your darktable you could send us failing and not failing configs, so we could check where the original problem was. Running darktable with debugging info enabled (`-d lua` in this case) would also give us more information so that users face fewer of such errors in the future...

**Closed by johnny-bit** 2020-12-23 23:12 UTC
