### ISSUE TITLE
Lumix G85/G85 isn't available on the linux version

### ISSUE THREAD

**Issue by darkpumpkins** [darktable-org/darktable#9897] opened 2021-08-28 22:08 UTC
**Describe the bug/issue**
My camera G80 is missing into camera list inside the objective correction module on my linux version. On my Windows version of darktable I do have the Lumix G80. 

* darktable version : 3.6.0-1.1
* OS                : Linux - kernel 5.11.0-31
* Linux - Distro    :  Ubuntu 21.04
* Memory            :  16Go DDR4
* Graphics card     : Nvidia GTX 1070Ti
* Graphics driver   : 470.57.02
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 11.0
* Desktop           : Gnome 3.38.5
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

 - Can you reproduce with another darktable version(s)? **yes with linux version 3.4**

**Comment by pitbuster** [comment] 2021-08-29 04:15
You should run `lensfun‑update-data` in the command line to get updates for the correction database.

**Comment by johnny-bit** [comment] 2021-08-29 08:13
The reason windows package has and linux hasn't is beause when building binary package, maintainer bundles newest lens db at the time of package build. On linux however we depend on the system to provide up to date db. Since lensfun doesn't do frequent releases and distros don't set up cron for updating lens db (some are even dum enough to put lensfun-update-data into separate package!) it's very likely that your lens db is out of date.

for quick & easy solution follow @pitbuster's advice.

for medium term solution follow https://github.com/darktable-org/darktable/issues/4180

for long term solution - see lensfun efforts to have new release.

Closing since the problem is outside of darktable's sphere of influence and the FR for having in-app lensfun update is (very slowly) being worked on.

**Closed by johnny-bit** 2021-08-29 08:13 UTC
Labels: duplicate, bug: won't fix, bug: upstream

**Comment by darkpumpkins** [comment] 2021-08-29 08:35
Okay, in my case i had to do :

`sudo apt install liblensfun-bin`

and then 

`/usr/bin/g-lensfun-update-data`

Thanks !
