### ISSUE TITLE
commit cfa1abfdb or 53603424b  might have broken current master

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#6767] opened 2020-11-06 19:27 UTC
**Describe the bug**

formerly successfully opened / edited picture is shown fully black

**To Reproduce**

1. Go to lighttable
2. double click to open a photo which you have opened and edited prior commit cfa1abfdb
3. find your self in darkroom
4. See error (screenshots below)

**Expected behavior**

pic should open and being editable as normal

**Screenshots**

*o.k.-Version*
![Screenshot_20201106_200112](https://user-images.githubusercontent.com/49004103/98405686-fbeb7100-206c-11eb-963e-0e1c6eecf6c5.png)

*bad version*
![Screenshot_20201106_200506](https://user-images.githubusercontent.com/49004103/98405765-22111100-206d-11eb-80c2-65edd1abdd55.png)

*fresh config-dir*
![Screenshot_20201106_202426](https://user-images.githubusercontent.com/49004103/98406400-2db10780-206e-11eb-9894-437a30be0cdf.png)

@aurelienpierre may I ping you here, as both commits are yours. Prior to cfa1abfdb the error is not there. As cfa1abfdb cannot build, I could not provide a proper bisect result

dt throws the following on the command line:
`[dt_ioppr_set_pipe_work_profile_info] unsupported working profile 12 , it will be replaced with linear rec2020`

**Platform (please complete the following information):**
* darktable version : 3.3.0+1379~g53603424b
* OS                : Linux - kernel 5.7.15-gentoo
* Distro            : Gentoo Base System release 2.7
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.100-r2
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.8-r1
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.22
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Additional context**
 - Are the steps above reproduce with a fresh edit (removing history)? **YES**
 - with or w/o **opencl** does **not matter**
 - Is the issue still present using an empty/new config-dir **result is different, see screenshots**

**Comment by ptilopteri** [comment] 2020-11-06 19:35
perhaps related to #6766, but I can build g53603424b

**Comment by aurelienpierre** [comment] 2020-11-06 20:46
Duplicate of https://github.com/darktable-org/darktable/issues/6766

**Closed by aurelienpierre** 2020-11-06 20:46 UTC
