### ISSUE TITLE
darktable crashing when opening pixel 3a dng files

### ISSUE THREAD

**Issue by Alfred74New** [darktable-org/darktable#8584] opened 2021-03-30 01:06 UTC
**Describe the bug/issue**
Darktable crashes when trying to open .dng files from my Pixel 3a

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open darktable
2. go to lightable view
3. double click dng file
4. See error "an unhandled exception occurred. 

**Expected behavior**
file to open for editing

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

Darktable 3.4.0
Windows 10
Systems and OS details in attached file
Backtrace in attached file
[WICKEDFAST.txt](https://github.com/darktable-org/darktable/files/6225436/WICKEDFAST.txt)
[darktable_bt_Z2QZ00.txt](https://github.com/darktable-org/darktable/files/6225444/darktable_bt_Z2QZ00.txt)

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**

**Comment by jade-nl** [comment] 2021-03-30 09:52
I'm not able to reproduce this one on Linux using this [pixel 3a RAW file on pixls.us](https://discuss.pixls.us/t/play-raw-door-9/13444)

Tried using dt 3.4.0, dt 3.4.1 and latest master (3.5.0+1562~g074d2dd21)


**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.9)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : Unknown
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 0.27.3
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by Alfred74New** [comment] 2021-03-30 11:40
Problem occurred on W 10 platform 

⁣Alfred New
Red Newt Productions
802-999-1672 

Get TypeApp for Android ​

**Comment by johnny-bit** [comment] 2021-06-17 11:21
Checked using [This actual Google Pixel 3a](https://raw.pixls.us/getfile.php/3496/nice/Google%20-%20Pixel%203a%20-%2016bit%20(4:3).dng) from raw.pixls.us

on darktable 3.4.1.1
on windows 10 (update 21H1)

no crash experienced.

The backtrace attached to the issue contains no information what so ever...

Closing since it should work (also - plz update your darktable from 3.4.0 to 3.4.1.1)

**Closed by johnny-bit** 2021-06-17 11:21 UTC
Labels: no-issue-activity
