### ISSUE TITLE
darktable.org → Website is offline

### ISSUE THREAD

**Issue by rdmasio** [darktable-org/darktable#14898] opened 2023-07-18 16:51 UTC
### Describe the bug

The website listed in the repository, darktable.org, is offline.

### Steps to reproduce

1. Browse to [darktable.org](**https://www.darktable.org/**) 

### Where did you install darktable from?

darktable.org

### darktable version

n/a

### What OS are you using?

Mac

### What is the version of your OS?

14.0 Beta (23A5286i)

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment] 2023-07-18 17:16
duplicate of #14893

**Closed by zisoft** 2023-07-18 17:16 UTC
