### ISSUE TITLE
Lighttable: history only shown for top left image - lua-problem

### ISSUE THREAD

**Issue by bilddateien** [darktable-org/darktable#3952] opened 2019-12-30 13:43 UTC
**Describe the bug**
https://darktable.gitlab.io/doc/en/lighttable_chapter.html#lighttable_overview
In the top right corner of every image frame in lighttable there is a +/- icon. This should show a popup with editing history of that image.
In 3.1.0~git227.4585dba8d this is only the case for the first image of a collection, the top left image in lighttable in file manager view.

**To Reproduce**
1. lighttable view: file manager
2. open a collection
3. hover mouse over first image top left: history is shown
4. hover mouse over icon in second and following images: history __not__ shown

**Expected behavior**
Behavior before 3.x was: each image shows history when hovering over +/- icon top right

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0~git227.4585dba8d
 - OS: debian sid

**Additional context**

search done for "hover", "icon", "frame" and found nothing similar

**Comment by chhil** [comment] 2019-12-30 13:53
Cannot reproduce on version: darktable 3.1.0+244~g4757cc876

**Comment by ptilopteri** [comment] 2019-12-30 14:46
I can on darktable 3.1.0~git245.a96a1aac8

openSUSE Tumbleweed 20191228
NVIDIA GF106 [GeForce GTS 450]
NVidia 390.129
OpenCL on

the difference may be your operating system which you do not mention

**Comment by bilddateien** [comment] 2019-12-30 16:13
There were also two confirmations on the mailing list before I filed the report:
https://www.mail-archive.com/darktable-user@lists.darktable.org/msg08338.html

**Comment by Nilvus** [comment] 2019-12-30 18:09
Can't reproduce it on 3.1.0+233~g1c69da70d-dirty nor on 3.1.0+254~g2a20248e1-dirty (just compiled). It works on all images. I'm on Ubuntu 19.10.

**Comment by bilddateien** [comment] 2019-12-30 18:45
had to go back to 3.1.0~git136.2a252d0b6 because of some ugly CPU-load-issues.
For this I purged the previous version and deleted the `/.config/darktable` folder.
After reimporting some filmstrips into the now empty darktable it seems to work as expected although sometimes it takes some time.
At least for this version it seems to be some sort of configuration issue since it also didn't work a few days ago when I upgraded to this very version from V2.6.3 from the repository but kept all configuration as it was at that time.

**Comment by bilddateien** [comment] 2019-12-30 18:47
had to go back to 3.1.0~git136.2a252d0b6 because of some ugly CPU-load-issues.
For this I purged the previous version 3.1.0~git227.4585dba8d and deleted the `/.config/darktable` folder.
After reimporting some filmstrips into the now empty darktable it seems to work as expected although sometimes it takes some time.
At least for this version it seems to be some sort of configuration issue since it also didn't work a few days ago when I upgraded to this very version from V2.6.3 from the repository but kept all configuration as it was at that time.

**Comment by bilddateien** [comment] 2019-12-30 18:48
had to go back to 3.1.0~git136.2a252d0b6 because of some ugly CPU-load-issues.
For this I purged the previous version 3.1.0~git227.4585dba8d and deleted the `/.config/darktable` folder.
After reimporting some filmstrips into the now empty darktable it seems to work as expected although sometimes it takes some time.
At least for this version it seems to be some sort of configuration issue since it also didn't work a few days ago when I upgraded to this very version from V2.6.3 from the repository but kept all configuration as it was at that time.

**Comment by bilddateien** [comment] 2020-01-03 19:08
I use darktable 3.0.0 now with a clean profile.
Everything worked. Then I installed lua-scripts - script manager by William Fergusson.
I reproduced three times the described behavior in #1 by activating `image_path_in_ui` and restarting darktable. Disable the lua-script will bring back full funktionality to the mouse-hover displaying history.

**Comment by bilddateien** [comment] 2020-01-05 14:53
>  by activating `image_path_in_ui` and restarting darktable. Disable the lua-script will bring back full funktionality to the mouse-hover displaying history.

Meanwhile confirmed by thokster in the mailing list

**Comment by ptilopteri** [comment] 2020-01-05 15:01
confirm disabling lua-script brings back the "mouse-hover" image history list

**Comment by wpferguson** [comment] 2020-05-16 20:45
Just tested with darktable git 3.1.0+1660~gd5e9e177e and was unable to reproduce. @bilddateien, @ptilopteri can you verify this is still a problem?

**Comment by ptilopteri** [comment] 2020-05-17 01:47
@wpferguson I see the history now, tks

**Comment by wpferguson** [comment] 2020-05-17 06:38
I didn't change anything.  I think it was something in all of the lighttable changes and it got cleaned up when the code settled.

@TurboGit I think this is no longer an issue.

**Comment by bilddateien** [comment] 2020-05-17 07:13
@wpferguson On darktable 3.0.1 I still see above mentioned behaviour.
Image history only on top left image in lighttable.

**Comment by TurboGit** [comment] 2020-05-17 10:53
Yes, 3.0.1 this is expected.

Closing.

**Closed by TurboGit** 2020-05-17 10:53 UTC
Labels: no-issue-activity
