### ISSUE TITLE
I am unable to open Darktable after a clean install - "An Unhandled exception occurred..."

### ISSUE THREAD

**Issue by DrStern** [darktable-org/darktable#11014] opened 2022-01-28 01:54 UTC
**Describe the bug/issue**
I downloaded Darktable 3.8 last week, it worked great the first time I used it.  I tried to open the program again today but it does not open; instead I get an error message stating "An unhandled exception occurred."  I have the backtrace log; the error appears to be in reference to a Clon12Compiler.dll module.  For what it's worth, my PC is 3 weeks old with a Ryzen 7 Series 5800x and a 3080 video card.  I tried uninstalling and reinstalling multiple times but that does not seem to solve the issue.  My graphics card driver is up to date as well.

**To Reproduce**
The program does not open
In attempting to open the program, I get an error regarding an unhandled exception occurring (Screen shot attached)
This occurs even after uninstalling and reinstalling. 

**Expected behavior**
I would like the program to open.

**Screenshots**
- Attached a screenshot of 
![Error Message](https://user-images.githubusercontent.com/4109255/151473160-a5748f9e-5ab0-45a1-a3c7-13c762f09db8.jpg)

** Backtrace **

this is darktable 3.8.0 reporting an exception:

-------------------

Error occurred on Thursday, January 27, 2022 at 20:35:38.

darktable.exe caused a Breakpoint at location 00007FF9F1BD5A34 in module CLOn12Compiler.dll.

AddrPC           Params
00007FF9F1BD5A34 000001CB1EC85DA0 000001CB1EC85DA0 00000030F49FBCA0  CLOn12Compiler.dll!clc_specialize_spirv
00007FF9F1BD2002 000001CB03869420 000001CB108CA160 00000030F49FC670  CLOn12Compiler.dll!clc_specialize_spirv
00007FF9F1BD50F5 00000030F49FC4D0 0000000000000000 000001CB108C9AD0  CLOn12Compiler.dll!clc_specialize_spirv
00007FF9F1B15857 00000030F49FD9D0 00000030F49FDED0 000001CB7063D130  CLOn12Compiler.dll!clc_spirv_to_dxil
00007FF9FADAC6CC 0000000000000000 00007FF9FADAC930 000001CB17DA8920  OpenCLOn12.dll!0x7ff90000c6cc
00007FF9FADC9F20 0000000000000000 000001CB00000000 000001CB1907FFB0  OpenCLOn12.dll!clUnloadPlatformCompiler
00007FF9FADC8B4C 000001CB6A521458 000001CB20824A18 000001CB126446C0  OpenCLOn12.dll!clUnloadPlatformCompiler
00007FF9FADC8471 000001CB6A525880 00000030F49FE6D8 000001CB69F17760  OpenCLOn12.dll!clUnloadPlatformCompiler
00007FF9FADCC5B8 000001CB6A521400 00000000000024B0 0000000000000000  OpenCLOn12.dll!clBuildProgram
00007FFA084FCC30 00000030F49FEE50 0000000000000103 000001CB69CE2190  libdarktable.dll!dt_opencl_build_program
00007FFA0850236C 000001CB69DA4160 0000000000000001 000001CB00000000  libdarktable.dll!dt_opencl_init
00007FFA08460A1B 00007FFA00000001 000001CB6860AAF0 00007FFA00000001  libdarktable.dll!dt_init
00007FF68F4A2B15 00007FF68F4A1660 0000000000000010 0000000000000000  darktable.exe!0x7ff600002b15
00007FF68F4A15B5 000000000000005A 0000000000000000 0000000000000000  darktable.exe!0x7ff6000015b5
00007FF68F4A13D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff6000013d4
00007FF68F4A1506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff600001506
00007FFA63D454E0 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFA6544485B 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.8.0.0
ntdll.dll   	10.0.22000.469
KERNEL32.DLL	10.0.22000.434
KERNELBASE.dll	10.0.22000.434
apphelp.dll 	10.0.22000.282
AcLayers.DLL	10.0.22000.1
msvcrt.dll  	7.0.22000.1
SHLWAPI.dll 	10.0.22000.1
SortWindows61.dll	10.0.22000.1
libintl-8.dll	0.19.8.0
libglib-2.0-0.dll	2.70.2.0
ADVAPI32.dll	10.0.22000.434
sechost.dll 	10.0.22000.434
ole32.dll   	10.0.22000.120
msvcp_win.dll	10.0.22000.1
RPCRT4.dll  	10.0.22000.434
ucrtbase.dll	10.0.22000.1
libdarktable.dll
GDI32.dll   	10.0.22000.1
libiconv-2.dll	1.16.0.0
PSAPI.DLL   	10.0.22000.1
win32u.dll  	10.0.22000.434
SHELL32.dll 	10.0.22000.469
gdi32full.dll	10.0.22000.469
libwinpthread-1.dll	1.0.0.0
USER32.dll  	10.0.22000.282
WS2_32.dll  	10.0.22000.1
combase.dll 	10.0.22000.282
libgcc_s_seh-1.dll
libstdc++-6.dll
exchndl.dll 	0.9.3.0
libcairo-2.dll
libgdk_pixbuf-2.0-0.dll	2.42.6.0
libgio-2.0-0.dll	2.70.2.0
libgobject-2.0-0.dll	2.70.2.0
libgdk-3-0.dll	3.24.30.0
IMM32.dll   	10.0.22000.1
lua54.dll
SETUPAPI.dll	10.0.22000.469
libpango-1.0-0.dll	1.50.0.0
zlib1.dll
libpangocairo-1.0-0.dll	1.50.0.0
libgomp-1.dll
libavif.dll
libcurl-4.dll
CRYPT32.dll 	10.0.22000.348
WLDAP32.dll 	10.0.22000.1
libgmodule-2.0-0.dll	2.70.2.0
libexiv2.dll
libgtk-3-0.dll	3.24.30.0
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libheif.dll
comdlg32.dll	10.0.22000.120
shcore.dll  	10.0.22000.71
libicuin69.dll
libicuuc69.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
libIlmImf-2_5.dll
libopenjp2-7.dll
libpng16-16.dll
liblcms2-2.dll
libpugixml.dll	1.11.0.0
libsecret-1-0.dll
librsvg-2-2.dll
libsoup-2.4-1.dll
libsqlite3-0.dll
libtiff-5.dll
libxml2-2.dll
libpcre-1.dll
VERSION.dll 	10.0.22000.1
MSIMG32.dll 	10.0.22000.1
mgwhelp.dll 	0.9.3.0
libfontconfig-1.dll
libfreetype-6.dll	2.11.1.0
libpixman-1-0.dll
gdiplus.dll 	10.0.22000.434
DNSAPI.dll  	10.0.22000.282
IPHLPAPI.DLL	10.0.22000.282
libffi-7.dll
dwmapi.dll  	10.0.22000.41
HID.DLL     	10.0.22000.1
libcairo-gobject-2.dll
WINMM.dll   	10.0.22000.1
libepoxy-0.dll
libfribidi-0.dll
libpangowin32-1.0-0.dll	1.50.0.0
libthai-0.dll
libharfbuzz-0.dll
libpangoft2-1.0-0.dll	1.50.0.0
libdav1d.dll	5.1.1.0
libaom.dll
rav1e.dll
libbrotlidec.dll
libidn2-0.dll
libcrypto-1_1-x64.dll	1.1.1.12
libpsl-5.dll
libnghttp2-14.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.12
libzstd.dll
libexpat-1.dll
libexif-12.dll
libltdl-7.dll
libsystre-0.dll
COMCTL32.dll	6.10.22000.120
libbz2-1.dll
libde265-0.dll
WINSPOOL.DRV	10.0.22000.348
libx265.dll 	3.4.0.31
libicudt69.dll
libatk-1.0-0.dll	2.36.0.0
libHalf-2_5.dll
libIex-2_5.dll
libIlmThread-2_5.dll
libImath-2_5.dll
libgcrypt-20.dll	1.9.4.0
bcrypt.dll  	10.0.22000.1
USERENV.dll 	10.0.22000.1
libdeflate.dll
libjbig-0.dll
libLerc.dll
liblzma-5.dll	5.2.5.0
libwebp-7.dll
dbghelp.dll 	10.0.22000.1
libdatrie-1.dll
libgraphite2.dll
libbrotlicommon.dll
libunistring-2.dll	0.9.10.0
libtre-5.dll
libgpg-error-0.dll	1.43.0.0
dbgcore.DLL 	10.0.22000.1
CRYPTBASE.DLL	10.0.22000.1
USP10.dll   	10.0.22000.1
CRYPTSP.dll 	10.0.22000.1
rsaenh.dll  	10.0.22000.282
bcryptPrimitives.dll	10.0.22000.376
NSI.dll     	10.0.22000.1
windows.storage.dll	10.0.22000.469
wintypes.dll	10.0.22000.41
mswsock.dll 	10.0.22000.1
winhttp.dll 	10.0.22000.1
uxtheme.dll 	10.0.22000.120
MSCTF.dll   	10.0.22000.434
DEVOBJ.dll  	10.0.22000.1
cfgmgr32.dll	10.0.22000.1
WINTRUST.dll	10.0.22000.469
MSASN1.dll  	10.0.22000.1
kernel.appcore.dll	10.0.22000.71
clbcatq.dll 	2001.12.10941.16384
OpenCL.dll  	3.0.1.0
dxcore.dll  	10.0.22000.1
AppXDeploymentClient.dll	10.0.22000.469
urlmon.dll  	11.0.22000.282
iertutil.dll	11.0.22000.348
srvcli.dll  	10.0.22000.434
netutils.dll	10.0.22000.434
Windows.ApplicationModel.dll	10.0.22000.37
OLEAUT32.dll	10.0.22000.1
propsys.dll 	7.0.22000.37
profapi.dll 	10.0.22000.1
mssprxy.dll 	7.0.22000.348
nvopencl64.dll	30.0.15.1123
cryptnet.dll	10.0.22000.1
drvstore.dll	10.0.22000.120
wldp.dll    	10.0.22000.120
nvapi64.dll 	30.0.15.1123
OpenCLOn12.dll
dxgi.dll    	10.0.22000.469
d3d12.dll   	10.0.22000.120
nvcompiler64.dll	30.0.15.1123
D3D12Core.dll	10.0.22000.120
imagehlp.dll	10.0.22000.1
nvspcap64.dll	3.24.0.126
ntmarta.dll 	10.0.22000.1
D3DSCache.dll	10.0.22000.65
twinapi.appcore.dll	10.0.22000.469
nvldumdx.dll	30.0.15.1123
nvwgf2umx.dll	30.0.15.1123
CLOn12Compiler.dll
DXIL.dll    	10.0.19592.1000
mrmcorer.dll	10.0.22000.120
windows.staterepositorycore.dll	10.0.22000.65
windows.staterepositoryclient.dll	10.0.22000.65
bcp47mrm.dll	10.0.22000.65
Windows.UI.dll	10.0.22000.1
TextShaping.dll
textinputframework.dll	10.0.22000.282
CoreMessaging.dll	10.0.22000.71
CoreUIComponents.dll	10.0.22000.132

Windows 6.2.9200
DrMingw 0.9.3

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 32 gigs ddr4
* Graphics card     : RTX 3080
* Graphics driver   : 511.23
* OpenCL installed  : unknown
* OpenCL activated  : unknown
* Xorg              : unknown
* Desktop           : unknown
* GTK+              : unknown
* gcc               : unknown
* cflags            : unknown
* CMAKE_BUILD_TYPE  : unknown

**Comment by parafin** [comment] 2022-01-28 08:23
duplicate of #10767

**Closed by parafin** 2022-01-28 08:23 UTC
