### ISSUE TITLE
r shortcut not working

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#6171] opened 2020-09-01 17:56 UTC
in 3.2.1, darktable mode, the "r" shortcut which should activate the crop and rotate module, doesn't work

**Comment by johnny-bit** [comment] 2020-09-01 21:09
the "r" keyboard shortcut by default is mapped to "REJECT" operation of images view. I tried to re-assign "r" to "enable module" action of crop & rotate module and it works.

If that solves your issue please close this report :+1:

**Comment by paolobenve** [comment] 2020-09-02 04:34
> the "r" keyboard shortcut by default is mapped to "REJECT" operation of images view.

In my settings I see  R shortcut in `views - thumbtable - rate reject`, but I'm in darkroom view. I have a R shortcut in `image operations - crop and rotate - show module` too, but is not respected.

Resetting the shortcuts makes the second desapperar. Setting again to `image operations - crop and rotate - show module` alerts me that there was a previous shortcut which is going to be replaced: **OK**

Is my supposition correct that R = `image operations - crop and rotate - show module` was a previous default and it was changed at some time? I think that I found that default shortcut some version ago.

Anyway the bug could be that a version change hasn't detected the `image operations - crop and rotate - show module` shortcut and has added the `views - thumbtable - rate reject` one?

**Comment by paolobenve** [comment] 2020-09-02 04:35
But I'm wondering: isn't the crop and rotate module a frequently used one, worth a shortcut?

**Comment by johnny-bit** [comment] 2020-09-02 05:25
If all it takes is simple reassignment to fix trouble then it's not a bug 😉
Perhaps at some point you added r as a shortcut to crop and rotate, but it
got overridden by one about rejecting image?

As for default shortcuts... I don't think any image operation deserves one
because it's highly dependent on your workflow. However things like rating
and rejecting images are usually quite universal.

śr., 2 wrz 2020, 06:35 użytkownik Paolo Benvenuto <notifications@github.com>
napisał:

**Closed** 2020-09-04 17:43 UTC
