### ISSUE TITLE
Crop module behaving weird in darktable git

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#15036] opened 2023-08-08 19:26 UTC
### Describe the bug

I opened an image which was cropped, then I opened the crop module to see how much of the image is being croped. The area shown in the crop preview is different to how the image looked before and when closing the image, another crop area has been chosen.

### Steps to reproduce

1. Open an image that has been cropped and select crop module
2. See different area highlighted than what was shown before
3. Close crop module and have the image croped completely different than before

### Expected behavior

darktable should show the crop module area correctly

### Logfile | Screenshot | Screencast

before:
![original image](https://github.com/darktable-org/darktable/assets/920721/a85e97f9-6ef2-4f67-9647-d1b91ed328bd)

crop actived:
![crop actived](https://github.com/darktable-org/darktable/assets/920721/3d82cb4e-b3c3-4d24-9bf6-2ccc2a1d6d01)

crop closed:
![after crop module](https://github.com/darktable-org/darktable/assets/920721/ef0678bd-d5f6-4c66-9d77-51593c43b933)

XMP: [_51A0937.CR3.zip](https://github.com/darktable-org/darktable/files/12295160/_51A0937.CR3.zip)

### Where did you install darktable from?

darktable.org

### darktable version

4.5.0+296~gf7de85ec7e

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Describe your system?

Kernel 6.4.8, 64 GB Ram, Wayland, latest GTK3

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD Polaris RX 580 (all time favorite)

**Comment by piratenpanda** [comment] 2023-08-08 19:27
It seems like the crop preview does not render the complete image that's why the preview and the result is wrong

**Comment by piratenpanda** [comment] 2023-08-08 19:36
Yeah the crop preview is rendered on the already cropped image. This should obviously not be the case.

**Comment by jenshannoschwalm** [comment] 2023-08-08 20:25
Confirmed and indeed related to something we all oversaw while testing #15025 . @TurbGit In fact reverting
`dt_dev_invalidate_all(darktable.develop)` to `dt_dev_pop_history_items(darktable.develop, darktable.develop->history_end)` fixes this.

**Comment by jenshannoschwalm** [comment] 2023-08-09 05:35
Sorry about closing, hit the wrong button.

The runtime while using `dt_dev_invalidate_all(darktable.develop)` shows a 
```
    12.6847 modify roi IN              [full]         crop                   (   0/  60)  845x 564 scale=0.1699 --> (   0/   0)  845x 564 scale=0.1699 
    12.6852 modify roi IN              [full]         lens                   (   0/  59)  841x 564 scale=0.1699 --> (   0/  60)  845x 564 scale=0.1699 
    12.6852 modify roi IN              [full]         demosaic               (   0/ 346) 4949x3319 scale=1.0000 --> (   0/  59)  841x 564 scale=0.1699 
    12.6852 modify roi IN              [full]         highlights             (   0/   0) 6032x4032 scale=1.0000 --> (   0/ 346) 4949x3319 scale=1.0000 

``` 
RoI modify for the crop module, **that** seems to be the culprit. The related code for _runtime disabling_ modules via the `operation_tags_filter()` is handled in pixelpipe_hb and pipe cache code, there we test for the gui status of modules "all over" and i am not sure we can do those tests otherwise in a safe way.

**Comment by TurboGit** [comment] 2023-08-09 07:04
@jenshannoschwalm : See #15040.

**Closed** 2023-08-09 08:46 UTC
Labels: priority: high, reproduce: confirmed, bug: pending
