### ISSUE TITLE
After upgrade to 5.0.0, the lighttable lost ability to filter collection by module

### ISSUE THREAD

**Issue by leclercj** [darktable-org/darktable#18121] opened 2024-12-31 14:13 UTC
### Describe the bug

In darktable 5.0.0 lighttable, the collection filtering by module does not work any more
No module list displayed, preventing any selection
Directly writing a module name in the text box does not work neither
Was working fine up to darktable 4.8.1

### Steps to reproduce

In lighttable, try to filter collection by darktable module and see empty module list
Also, hoovering over the ![Capture d’écran du 2024-12-31 15-09-16](https://github.com/user-attachments/assets/a737d30c-8785-4986-99cb-c4f8c9a779b9) icon on any image does not display the list of applied modules anymore

### Expected behavior

collection filtering by module should present a list of used modules

### Logfile | Screenshot | Screencast

![Capture d’écran du 2024-12-31 14-54-51](https://github.com/user-attachments/assets/87164f58-ca8b-4d80-a89f-9ffa87e96c55)

### Where did you obtain darktable from?

self compiled

### darktable version

5.0.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 24.10

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Not relevant here

**Comment by zisoft** [comment] 2024-12-31 14:38
Duplicate of #18093

**Closed** 2024-12-31 14:39 UTC
Labels: duplicate, Fixed in master
