### ISSUE TITLE
dt 3.6.01 Windows Quick Access Panel 

### ISSUE THREAD

**Issue by 520kaymann** [darktable-org/darktable#9432] opened 2021-07-06 15:56 UTC
Using in Quick Access Panel: local contrast, color balance rgb, color calibration, lens correction, and denoise will cause an unhandled exception.  Clicking on use full version and making adjustments there causes zero issues.

![Screenshot 2021-07-06 083931](https://user-images.githubusercontent.com/57155093/124629768-97b8c100-de36-11eb-8830-bc951464cf92.png)
 
[darktable_bt_Y0O550.txt](https://github.com/darktable-org/darktable/files/6771244/darktable_bt_Y0O550.txt)

Using Quick Access Panel: exposure, crop and rotate works perfectly

**Comment by johnny-bit** [comment] 2021-07-06 16:26
The bug is already fixed on master... although...

@TurboGit & @wpferguson - I wonder if windows package should receive a patch in form of #9410 otherwise we'll be getting reports like this till 3.8 release :/

**Comment by Nilvus** [comment] 2021-07-06 16:49
> The bug is already fixed on master... although...
> 
> @TurboGit & @wpferguson - I wonder if windows package should receive a patch in form of #9410 otherwise we'll be getting reports like this till 3.8 release :/

As we also have #9433 related to Windows package, maybe plan a 3.6.0.2 for the end of this month or august with such fixes (qap and dependencies related on #9433). And maybe some other minor fixes that we could have in following days/weeks?

Or plan a whole 3.6.1 if we have some minor fixes for all OS.

**Comment by Dave22152** [comment] 2021-07-07 14:26
FWIW it looks like you can prevent the crash in Settings>darkroom>modules and turning off "expand the module when it is activated, and collapse it when disabled"

**Comment by Nilvus** [comment] 2021-07-11 10:35
I close this one as it is fixed. A probable 3.6.1 should be released (not confirmed though actually but fixed in actual master).

**Closed by Nilvus** 2021-07-11 10:35 UTC
Labels: bug: fixed, scope: windows support

**Comment by Dave22152** [comment] 2021-07-11 17:06
I checked in 3.7.0+279 and was able to verify that the problem was corrected.  Thanks!
