### ISSUE TITLE
Panning the visible area in darkroom using keyboard

### ISSUE THREAD

**Issue by esq4** [darktable-org/darktable#10349] opened 2021-11-07 11:47 UTC
Hello.

Zoom an image in darkroom in any way.
Try panning visible area using Up/Down/Left/Right keys.

Both Up/Down keys move the area up.
Both Left/Right keys move the area right.

Is this bug or feature?

darktable version: master
OS: Linux / Win

**Comment by MStraeten** [comment] 2021-11-07 12:04
cannot reproduce - seems to be an issue with local defines shortcuts.
Try to delete (or rename) the ./config/shortcutsrc* files to run darktable with defaults

**Comment by Nilvus** [comment] 2021-11-07 12:19
I can reproduce too. On what I just check in new input ng system, I see same lines reproduced twice regarding those shortcuts. So maybe something on that side. See screenshot below:

![image](https://user-images.githubusercontent.com/45535283/140644468-da9e28e4-7723-4bb6-a657-01516ea6049b.png)

Removing files as suggested by @MStraeten fix this issue. After that, settings above became:

![image](https://user-images.githubusercontent.com/45535283/140644558-c4ffcb94-e309-4f80-ba25-e561ead3b4f0.png)

So updated those for settings in that last screenshot should fix too. Anyway, I think something need to be updated, lines are redundant (horizontal/vertical) and do not allow clearly to understand way they go (up/down, left/right), expect with shortcut on left column (but they could be changed. Other thing, I never update those lines, so is there something wrong by default?

@dterrahe: as you work on that part, what's your view on that?

**Comment by Nilvus** [comment] 2021-11-07 12:26
In effects column, for horizontal lines, maybe just update text to move right/move left? Actually, we just have up/down and top/bottom in dropdown.

**Comment by esq4** [comment] 2021-11-07 14:14
> Anyway, I think something need to be updated, lines are redundant (horizontal/vertical) and do not allow clearly to understand way they go (up/down, left/right), expect with shortcut on left column (but they could be changed. Other thing, I never update those lines, so is there something wrong by default?

Indeed, some concreteness would not hurt. I changed some of the shortcuts and  your and @MStraeten help saved me time and frustration.

The value _edit_ in the _effects_ column is not very informative. And the lack of _left_/_right_ values also makes it difficult to understand this setting. A small explanation directly in the program would not be superfluous.

**Comment by dterrahe** [comment] 2021-11-26 15:41
I believe from the above discussion that this particular issue resulted from an incorrect configuration.

It is true that the new input system is powerful and provides many ways to shoot oneself in the foot. There are ways provided to restore the default configuration (apart from just completely deleting shortcutsrc), which might have been able to fix this issue. But that still leaves a general lack of handholding. Building full documentation of all actions and their elements and effects into the configuration dialog itself would require an extension of the framework and significant effort and maintenance to fill in enough detail to be useful. Alternatively, there could be a warning (a la microsoft regedit) that there are dragons here and a pointer to the manual.

Other "solutions" could be proposed in separate FRs, but this particular bug should probably be closed at this point.

**Comment by TurboGit** [comment] 2021-11-26 17:27
@dterrahe : Thanks, closing.

**Closed by TurboGit** 2021-11-26 17:27 UTC
Labels: feature: enhancement, priority: medium, understood: clear, reproduce: confirmed, scope: UI
