### ISSUE TITLE
Count in "Collect images > folders" incorrect

### ISSUE THREAD

**Issue by Werzi2001** [darktable-org/darktable#8781] opened 2021-04-25 08:45 UTC
Darktable only shows the sum of the sub folders as image count for a folder that has sub folders. This leads to an incorrect image count if the folder (that has sub folders) also contains images.

Steps to reproduce:

- Create the following directories main/ main/sub1/ main/sub2/
- Put images in all 3 directories (also directly in main/)
- Import the main/ directory into Darktable
- Check the image counts shown in "Collect images > folders"

Result:

- The image count of main/ is simply the sum of main/sub1/ and main/sub2/ and does not contain the images in main/ itself

Expected result:

- The image count of main/ should also contain the images that are directly in main/

Edit:
I am using Darktable 3.4.1 on Arch Linux.

**Comment by Nilvus** [comment] 2021-04-25 10:39
As asked when you write an issue, please provide all infos:

- darktable version used,
- Which OS?

Said that, we have others users that prefer what darktable show actually. How we deal with that? 

I'm personally convinced that having images such way is not really good. Having images only in subfolder and use parents ones to organize seems better. Apart of that, don't forget that you have other ways to organize your photos, with tags for example or by using filmrolls, depending on how your set (import) them.

**Comment by Werzi2001** [comment] 2021-04-25 10:47
I added the required information to the original post (sorry have missed that).

I agree with you on that and am not doing it anymore. Nonetheless I did it in the past. Back then I had the original images in the main folder and e.g. edits (not darktable edits but Gimp edits) or panoramas in sub folders.

Nonetheless I think that this shouldn't matter. The image count shown for the parent directory is just incorrect. Don't get me wrong. It's not critical for me in any way. I just noticed it and though it would be work a bug report.

**Comment by Nilvus** [comment] 2021-04-25 10:55
> Nonetheless I think that this shouldn't matter. The image count shown for the parent directory is just incorrect. Don't get me wrong. It's not critical for me in any way. I just noticed it and thought it would be worth a bug report.

The image count is recursive and it's good on what I see/know (even if I don't use folders views on darktable, I just check that). On what way is incorrect for you, considering the count is recursive, so it's an add of actual folder and eventual children folders?

**Comment by Werzi2001** [comment] 2021-04-25 11:04
Did you follow the "Steps to reproduce" I wrote in the initial post? If so did it lead to a different result as it does for me? For example if I have the following folders (with the given number of images in them):

- main: 25
- - sub1: 25
- - sub2: 25

Darktable shows this:

- main: 50
- - sub1: 25
- - sub2: 25

instead of this:

- main: 75
- - sub1: 25
- - sub2: 25

I just tried it with a fresh library and could reproduce it on Darktable 3.4.1.

Nonetheless if I double click on "main" Darktable shows me all 75 images correctly. So personally I consider this a bug as the image count shown in "Collect images" does not match the number of images actually shown.

**Comment by phweyland** [comment] 2021-04-26 23:51
You are right but me this bug has been fixed.

The current master shows this and shows in lighttable what it says when click on one of the folders, unless you shift-click on main to see all the 75 in lighttable:

> * main: 25
> 
> * * sub1: 25
> 
> * * sub2: 25

**Comment by phweyland** [comment] 2021-04-27 11:36
duplicate of #8524

**Comment by Werzi2001** [comment] 2021-04-27 20:58
Great to hear that. Solution with Ctrl+Click and Shift+Click is something I'll have to get used to but will definitely work.

**Comment by johnny-bit** [comment] 2021-05-28 05:54
duplicate of #8524

**Closed by johnny-bit** 2021-05-28 05:54 UTC
Labels: no-issue-activity
