### ISSUE TITLE
Fujifilm GFX 16bits lossless support

### ISSUE THREAD

**Issue by jas01** [darktable-org/darktable#8903] opened 2021-05-09 10:45 UTC
The FujiFilm GFX100S got 2 formats of RAW  : 16 bits and 14 bits.
Each format come with 3 mode : uncompress, lossless, compress.

The 14 bits works well with uncompress and lossless. 
The 16 bits files work only in uncompress mode. 

It's would be super nice to have the support for 16bits lossless format.

Currently when we try to open a 16bits lossless file, darktable say the file are maybe corrupted. 

The advantage of lossless file are the size are half the size and because each 16 bits weight 200Mo...it's huge saving ;-)

**Comment by SteveLamont** [comment] 2021-05-26 15:33
I'm experiencing the same issue as above.

If sample images are needed, I'll be happy to provide them.

**Comment by johnny-bit** [comment] 2021-05-27 06:07
I think all the necessary files are present on https://raw.pixls.us/ but you can check :)

**Comment by kmilos** [comment] 2021-06-02 14:53
Sounds like this is duplicate of https://github.com/darktable-org/rawspeed/issues/228 and https://github.com/darktable-org/darktable/issues/4323

**Comment by johnny-bit** [comment] 2021-06-02 14:57
Closing in favour of those 2 then :)

**Closed by johnny-bit** 2021-06-02 14:57 UTC
Labels: scope: camera support, scope: hardware support
