### ISSUE TITLE
Nikon Z6II

### ISSUE THREAD

**Issue by Dupradeau** [darktable-org/darktable#8135] opened 2021-02-07 15:47 UTC
I submitted 8 raw files under that CC0 license at https://raw.pixls.us/ !
NiKon_Z6II_12bits_compressed_DSC_0797.NEF
NiKon_Z6II_12bits_lossless-compressed_DSC_0796.NEF
NiKon_Z6II_12bits_uncompressed_DSC_0798.NEF
NiKon_Z6II_14bits_compressed_DSC_0800.NEF
NiKon_Z6II_14bits_lossless-compressed_DSC_0799.NEF
NiKon_Z6II_14bits_uncompressed_DSC_0801.NEF
NiKon_Z6II_medium_DSC_0802.NEF
NiKon_Z6II_small_DSC_0803.NEF
It looks like darktable 3.4.1 does not recognize RAW files from Nikon Z6II. I am aware Z6II is a quite new camera... 
-> New Camera Support
-> Noise profile / White balance presets
thanks, regards, Fy
PS this is the first I come here, so please be patient if I did mistakes during the submissions...

**Comment by johnny-bit** [comment] 2021-02-07 18:07
Duplicate of #6898

the support will come in either 3.4.2 or 3.6 :)

**Closed by johnny-bit** 2021-02-07 18:07 UTC
Labels: scope: camera support
