### ISSUE TITLE
Noise profiler generating wrong maker and model items in presets.json

### ISSUE THREAD

**Issue by grattus** [darktable-org/darktable#9100] opened 2021-05-29 08:04 UTC
**Bug description**
The `maker` and `model` items in `presets.json` generated by `darktable-gen-noiseprofile` do not match the items present in RAW files, which means the "denoise (profiled)" module does not show the generated camera profile even though the pictures are  the same as that used for profile generation.

More specifically, for my Ricoh GR III, `presets.json` showed `"maker": "Ricoh"` instead of `"maker": "RICOH IMAGING COMPANY, LTD."` and `"model": "GR III"` instead of `"model": "RICOH GR III"`. Editing the file manually solved the problem.

Note: probably related to #2499.

**Platform**
* OS: Fedora 34
* Darktable version : 3.4.1

**Comment by johnny-bit** [comment] 2021-05-29 08:23
duplicate of #8992

**Closed by johnny-bit** 2021-05-29 08:23 UTC
