### ISSUE TITLE
When "look for new XMP on startup" is enabled and RAWs + XMP are on a CIFS share darktable launch can take more than 10 minutes to launch

### ISSUE THREAD

**Issue by leanderhutton** [darktable-org/darktable#17215] opened 2024-07-27 23:22 UTC
### Describe the bug

Hello, I have my files stored on a Debian based file server over a 10GBe network.  As I use multiple machines to edit I enabled the "check for newer XMP files on startup" on my Fedora 40 desktop and MacBook Pro running Sonoma. Even though there is plenty of network bandwidth available Darktable takes an exceedingly long time (up to 10-15+ minutes on the Mac over 2.5GBe) for the XMP crawler to run. Files stored on a local drive on both machines do not have this issue. Using the the -d flag I can see the crawler moving very slowly through the file structure.

I've not tried this over NFS yet so it may be something with the way CIFS handles files and not darktable itself. Wired or Wifi makes no difference and I'm running all these machines through a single 10GBe switch. If the CIFS is unmounted darktable launches promptly as it should. If the option is unchecked darktable also launches normally. 

Thanks! I can provide additional input if needed. I'm comfortable with git, self-compiling, etc. 

### Steps to reproduce

1. Store photos on SMB share
2. Check option "look for new XMP files on startup" under Preferences -> Storage
3. Close and re-launch darktable. 
4. Grab a coffee and wait :) 

### Expected behavior

Darktable should launch in a reasonable amount of time (0-30 seconds)

### Logfile | Screenshot | Screencast

     0.0002 application_directory: /opt/darktable/bin
     0.0002 darktable.datadir: /opt/darktable/share/darktable
     0.0002 darktable.plugindir: /opt/darktable/lib64/darktable
     0.0003 darktable.localedir: /opt/darktable/share/locale
     0.0003 darktable.configdir: /home/leander/.config/darktable
     0.0003 darktable.cachedir: /home/leander/.cache/darktable
     0.0003 darktable.sharedir: /opt/darktable/share
     0.0004 darktable.tmpdir: /tmp
     0.0004 [memory] at startup
     0.0004 [memory] max address space (vmpeak):      151876 kB
            [memory] cur address space (vmsize):      151876 kB
            [memory] max used memory   (vmhwm ):       31488 kB
            [memory] cur used memory   (vmrss ):       31488 kB
     0.0004 new_xdg_data_dirs: /opt/darktable/share:/home/leander/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
     0.0573 [init sql] library: /home/leander/.config/darktable/library.db, data: /home/leander/.config/darktable/data.db
     0.3039 [sql] /home/leander/src/darktable/src/common/tags.c:644, function dt_set_darktable_tags(): exec "DELETE FROM memory.darktable_tags"
     0.3040 [sql] /home/leander/src/darktable/src/common/tags.c:649, function dt_set_darktable_tags(): prepare "INSERT INTO memory.darktable_tags (tagid) SELECT DISTINCT id FROM data.tags WHERE name LIKE 'darktable|%%'"
     0.3042 [sql] /home/leander/src/darktable/src/common/database.c:5579, function dt_database_start_transaction(): exec "BEGIN TRANSACTION"

    45.6578 [crawler] `xmp file stored on CIFS share' (id: 14260) is a newer XMP file.
    
    .... 

### Where did you obtain darktable from?

self compiled

### darktable version

4.8.0

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 40

### Describe your system?

Desktop:
Fedora 40 GNOME
64GB RAM
AMD Threadripper 2950X
10GB Ethernet
Radeon RX 6900 XT

Laptop:
2023 MacBook Pro
macOS Sonoma
M2 Max
USB-C 2.5GBE connection

Fileserver:
A bunch of disks in Z2 ZFS
Debian 12 Bookworm
10GBe networking

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

6900 XT, RoCM

**Comment by ralfbrown** [comment] 2024-07-28 03:09
Not a bug as such, just a consequence of having a large collection on (relatively) very slow storage.  The fix for this situation would be to perform the crawling in the background, but that raises issues of what to do if the user accesses an image which hasn't yet been crawled (and even if it has been crawled, safely getting that information and dealing with handling a sidecar mismatch found in the crawl).

**Comment by leanderhutton** [comment] 2024-07-28 04:11
Yeah I figured as much. I can't be the only one with a lot of photos over a network share though. 

I did some more debugging with tcpdump on my file server and I think this might be a protocol tuning issue. Even with the RTT over a network I think it should still be out-performing an old 4200RPM hard drive in a USB 3 enclosure.  Samba is notoriously iffy on lots of small file read/write operations by default IIRC. NFS being a volume share instead of a file share might help so I'm going to do an export and try that. Samba/CIFS is universal with client operating systems though and macOS (despite allegedly being BSD) doesn't really support NFS all that well. I'll do some more benching and testing and report back!

**Comment by victoryforce** [comment] 2024-07-28 09:05
> I did some more debugging with tcpdump on my file server and I think this might be a protocol tuning issue. 

CIFS is known to perform directory browsing in an extremely inefficient way, requiring a huge number of round trips to open a remote folder. 

In any case, this problem cannot be solved by tuning darktable itself, so I see no need to keep this issue open.

**Comment by leanderhutton** [comment] 2024-07-28 19:34
I did some more testing and I can make CIFS slightly faster for a Linux client, but Apple's CIFS client seems hopeless. 

NFS mounted for Linux is slightly faster but it's till on the order of minutes to launch with the option enabled. There might be some further ZFS adjustments I can make however I'm probably chasing minimal gains.

I was wondering if the DB and the XMP file differed which would get precedence and found this in the user manual:

> Once an image has been imported into darktable, the database entries take precedence over the XMP file. Subsequent changes to the XMP file by any other software are not visible to darktable – such changes will be overwritten the next time darktable synchronizes the file. On request, darktable can be configured to search for updated XMP files at startup, offering a choice to update the database or overwrite the XMP file where changes are identified. This configuration can be changed in [preferences > storage > XMP sidecar files](https://docs.darktable.org/usermanual/4.8/en/preferences-settings/storage/#xmp-sidecar-files).

So it seems like an edit on one machine will get overwritten by a DB on another machine unless that option is checked.

The good news is the XMP crawling is reasonably fast, even on slow disks, when locally mounted. So my old way of just using the file server as an rsync point between machines would still work. I just have to remember which machine synced what when or I'll lose edits. 

> In any case, this problem cannot be solved by tuning darktable itself, so I see no need to keep this issue open.

As currently written I agree,  _but_ I think there might be other ways to implement this feature. Unfortunately most of my C programming knowledge has evaporated over the last 16 years. I wonder what something like a maridadb back end that can be hosted on a server like what digiKam can use might help with this. 

But the short of it is: there's not a reasonable way to edit on multiple clients and centralize your files without doing some kind rsync/cloning to local storage. Edits will get lost or you'll be waiting on the program to launch for a long while. The "copy to local" feature kind of helps but doesn't deal with changes that might have happened on another machine.

**Closed** 2024-07-28 19:34 UTC
Labels: feature: enhancement, difficulty: hard

**Comment by leanderhutton** [comment] 2024-07-28 19:43
Post close thought: I'm guessing the DB stores the time stamp of the edit? If so an easier approach might be to have an option for the XMP files to have precedence if the edits are newer? At least then if one were to open a file in the darkroom module on another machine it wouldn't nuke the edit. That would probably be easier than re-figuring the database back end.

**Comment by ralfbrown** [comment] 2024-07-28 19:50
That's a definite possibility, but would require checking the sidecar every time a new image is accessed for its edit or metadata.  Could potentially slow lighttable to a crawl....

**Comment by wpferguson** [comment] 2024-07-28 20:06
I keep the images I'm currently working on local.  Once they are done, I move them to a NAS.  I still keep the xmp files local, but I replace the image with a link to the NFS mounted image.  I then backup the xmp files separately (currently 728804 xmps).  I don't check for updated xmp files on startup, so I can't speak to how long it would take.  I don't notice any lag on startup or use unless I open an NFS mounted image which takes a little longer than a local one.

**Comment by leanderhutton** [comment] 2024-07-28 21:55
> That's a definite possibility, but would require checking the sidecar every time a new image is accessed for its edit or metadata. Could potentially slow lighttable to a crawl....

So, if I understand this correctly the XMPs are only checked on import or if the "look for new changes" option is enabled? Otherwise darktable just overwrites them with whatever is in the database once an image is accessed in darkroom or some metadata is changed in lighttable? So it's better to think of the XMPs as a "back up" of whats in the SQLite database instead of the primary source of information if I'm following. That is, if there's a conflict or some corruption on the XMP side darktable is just going to wipe out the XMP most of the time? 

> I keep the images I'm currently working on local. Once they are done, I move them to a NAS. I still keep the xmp files local, but I replace the image with a link to the NFS mounted image. I then backup the xmp files separately (currently 728804 xmps). I don't check for updated xmp files on startup, so I can't speak to how long it would take. I don't notice any lag on startup or use unless I open an NFS mounted image which takes a little longer than a local one.

It seems keeping the XMP files locally is the trick. Generating previews of remotely stored images and applying edits is pretty smooth over a fast enough (1Gbps or more) network connection in my experience. It's just that initial start up delay (my Mac is going on 30 minutes now, Apple's CIFS implementation is pretty bad and that's saying something) that's the kicker.
