### ISSUE TITLE
The program crushed.

### ISSUE THREAD

**Issue by harianwang** [darktable-org/darktable#9870] opened 2021-08-24 05:39 UTC
When I modified the name of a mask item in Mask Manaer, the program crushed.

<img width="432" alt="1" src="https://user-images.githubusercontent.com/89441626/130561927-7e2cdbe3-5764-450b-a99c-2e81d43df557.png">
<img width="645" alt="2" src="https://user-images.githubusercontent.com/89441626/130561937-fa846fef-bebd-45da-8a2e-4989e850044b.png">
<img width="380" alt="3" src="https://user-images.githubusercontent.com/89441626/130561941-ed2c910b-8e66-462e-ade6-f8ae14f2d0bd.png">

**Comment by johnny-bit** [comment] 2021-08-28 10:07
duplicate of #9504 
Fixed in https://github.com/darktable-org/darktable/pull/9514
will be part of 3.6.1 release

**Closed by johnny-bit** 2021-08-28 10:07 UTC
Labels: duplicate, scope: UI, bug: fixed
