### ISSUE TITLE
Panasonic DC-S1R

### ISSUE THREAD

**Issue by charliemb2** [darktable-org/darktable#4305] opened 2020-02-16 16:05 UTC
I have uploaded a raw file to pixls.us.  I may add another.

Note: Aspect ratios selected in this camera don't affect the raw file dimensions.  This is unlike other Panasonic cameras.

Thanks,

Charlie

Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment] 2020-03-18 09:06
Was added in https://github.com/darktable-org/rawspeed/commit/f8ad19a692f91e4bc7016cad3587379a78bafac8, not yet propagated into darktable.

**Comment by LebedevRI** [comment] 2020-03-18 09:07
Duplicate of https://github.com/darktable-org/darktable/issues/2649

**Closed by LebedevRI** 2020-03-18 09:07 UTC
Labels: scope: camera support
