### ISSUE TITLE
crash using "date-time taken" rule on Windows

### ISSUE THREAD

**Issue by jpulmann** [darktable-org/darktable#7949] opened 2021-01-21 13:37 UTC
**Description**
When using the "date-time taken" rule, which I chose by selecting a range on the bottom time-axis, darktable 3.4.0 on Windows 10 crashes. If used together with a "folder" rule, darktable does not crash, until the folder rule is cleared. I tried with the "camera" rule and that one does not prevent the crash.

**Platform:**
 - Darktable Version: 3.4.0
 - OS: Windows 10

I am attaching the file darktable produces at the crash

[darktable_bt_M4XOX0.txt](https://github.com/darktable-org/darktable/files/5849621/darktable_bt_M4XOX0.txt)

Thank you for maintaining the windows port as well!

**Comment by Nilvus** [comment] 2021-01-21 18:05
@jpverrue: I don't know if you use Windows but if I'm not wrong you work on this part. Maybe you will have some ideas? backtrace doesn't seems to bring infos.

**Comment by jpverrue** [comment] 2021-01-21 18:26
I'm sorry, I don't use Windows, only Linux (opensuse tumbleweed)
Moreover I did not work on this timestamp. "date-time taken" is extracted directly from the exif data. It has been available since the early days of darktable.
However, while working on the other timestamps I saw in the code the lines allowing to filter the pictures according to "date-time taken". I even used them as inspiration to write the filters for the 4 new timestamps.
Indeed the trace doesn't give any information except the name of the function where the crash occurs: strlen().

So to debug. It would be necessary to put traces in the code before and after all the strlen() applied to the timestamp "date-time taken" to try to identify the place of the crash in darktable. But without windows...

**Comment by Mark-64** [comment] 2021-01-21 20:08
I could debug on Windows, problem is I don't get the crash, neither with 3.4.0 nor with git master

**Comment by Mark-64** [comment] 2021-01-21 20:13
@jpulmann can you try to narrow down the issue, for example trying to start with a cleat test configuration, import some pictures and see if you still have the crash ?

**Comment by TurboGit** [comment] 2021-01-21 20:29
I think this has been fixed in master. It was due to a NULL datet/tme in the db.

**Comment by TurboGit** [comment] 2021-01-21 20:44
Probably a duplicate of #7502.

**Closed** 2021-01-21 20:44 UTC
Labels: bugfix, duplicate, scope: OS support

**Comment by jpulmann** [comment] 2021-01-21 20:51
Thank you, I will try with the new version.

In the meantime, I discovered how to reproduce this crash: one needs to use the date-time taken rule while a folder is being imported.
