### ISSUE TITLE
Rejecting - loses position in film roll

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#4679] opened 2020-04-11 08:36 UTC
**Describe the bug**
When I press "R" to reject an image, I lose the position in my filmroll. 

**To Reproduce**
1. Choose a folder with multiple photos
2. Pick a photo in the filmroll but not the first (e. G. Pick the 2nd or 3rd or higher positioned photo)
3. Press the keystroke for reject (should be "R" button by default) 
4. Dt keeps selected the rejected photo  and loses its position in the filmroll

**Expected behavior**

Whenever I reject a photo in the filmroll, dt should advance to the next photo, ideally photo 3 (if we rejected photo 2 in the filmroll) and not, lose its position and continue to show a rejected photo, as it is pointless and breaks the workflow

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Mac
 - no OpenCL 
 - AMD Radeon HD 3 gb

**Additional context**
Nobody did ever address this problem, this bug is present in older versions of dt as well

**Comment by Nilvus** [comment] 2020-04-11 09:07
First, update to last release: actually 3.0.1 (the 3.0.2 should come quite soon) as many bugs have been fixed on 3.0.1 UI (maybe that one). Then, all lighttable is rework to improve performances and fix lot things and will be for the next major release for Christmas.

Last thing you didn't precise and quite important here: which filter do you use in this behavior (top left of lighttable filemanager view (do you use all image, all except rejected, etc.).

**Comment by AlicVB** [comment] 2020-04-11 10:36
Confirmed, this has been fixed in master by my filemanager/filmstrip rewrite. This will go in next major release (not in minor ones, due to the amount of change)
I'm closing to tidy up github issues list

**Closed by AlicVB** 2020-04-11 10:36 UTC

**Comment by johans3** [comment] 2020-04-11 14:02
> Confirmed, this has been fixed in master by my filemanager/filmstrip rewrite. This will go in next major release (not in minor ones, due to the amount of change)
> I'm closing to tidy up github issues list

Awesome, what version do you mean 3.o.1 or 3.o.2?
Currently Mac users can't download a version higher than 3.o.o
Anyways good to know you've solved the issue, thanks!

**Comment by ptilopteri** [comment] 2020-04-11 14:13
@johans3 master is the development version, currently 3.1.0+1152~g4cf35ef40

**Comment by Nilvus** [comment] 2020-04-11 14:20
> Awesome, what version do you mean 3.o.1 or 3.o.2?
> Currently Mac users can't download a version higher than 3.o.o
> Anyways good to know you've solved the issue, thanks!

A major release mean that 2nd number increase. So the next major one will be 3.2 (probably) which be released in Christmas (because all lighttable is deeply rewrited (performance increase and bug fixes same time, so you will have to wait).

And where did you see the 3.0.0 is the last release you can download on Mac? Just check the install page on darktable.org and see that 3.0.1 is here. You could also download this release since a month here: https://github.com/darktable-org/darktable/releases

All new releases a first available on last link.

**Comment by johans3** [comment] 2020-04-11 14:26
> Last thing you didn't precise and quite important here: which filter do you use in this behavior (top left of lighttable filemanager view (do you use all image, all except rejected, etc.).

I reject pictures twice, one time in lighttable (bad shot) and also in darkroom (picture isn't special enough) . 
For my report, I was talking about rejecting photos in darkroom module.

I understand you've addressed the issue in both modules, be it in lighttable and darkroom
