### ISSUE TITLE
Multiple module instances lost when copy history stack to other photos and results in pixel-trash

### ISSUE THREAD

**Issue by cytrinox** [darktable-org/darktable#7297] opened 2020-12-13 09:26 UTC
**Describe the bug**

Version master 3.3.0~git2079.19b17c9cc. When copy and paste a history stack from a photo that has more than one CC module instance (or other modules like *Exposure*), only the first instance is visible in the enabled modules panel and the preview results in pixel-trash.

**To Reproduce**
1.Open a new raw file in darkroom
2. Add two CC modules
3. Go back to Lighttable and copy and paste the history stack to another photo
4. See the error (screenshots)

You see that in the history stack, the second CC instance is applied. But it is not shown on the right side module list.

**Expected behavior**

All CC instances should be transferred to the new photo.

**Screenshots**

![Screenshot from 2020-12-13 10-23-15](https://user-images.githubusercontent.com/509535/102007919-44154780-3d2d-11eb-94c5-324db5bf8d04.png)
![Screenshot from 2020-12-13 10-23-31](https://user-images.githubusercontent.com/509535/102007924-4aa3bf00-3d2d-11eb-88da-ba413bfffe0f.png)

**Platform (please complete the following information):**
Darktable Version: 3.3.0~git2079.19b17c9cc.
OS: Debian Bullseye
OpenCL: yes
PNY Nvidia Quadro 450.80.02-1

Binary package was obtained from https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

**Comment by MStraeten** [comment] 2020-12-13 16:14
I found similar behavior when copying a history stack to an unprocessed image. What happens if the target image was opened in darkroom before pasting the history stack?

**Comment by cytrinox** [comment] 2020-12-13 16:29
@MStraeten good hint. Then it works. I've tested it again with **chromatic adaptions default* set back to lagacy, but this option has no effect on this bug report.

**Comment by aurelienpierre** [comment] 2020-12-14 16:30
And multiple instances of other modules work ?

**Comment by cytrinox** [comment] 2020-12-14 17:08
@aurelienpierre Good question. It happens with other modules, too!
I rarely use multiple modules but I've followed your youtube tutorial for CC module and tried to copy a style with two CC modules, thats why I hit the problem. But it's a general bug, not related to to CC module.

I've created 3 instances of *Exposure* and only one is applied when copy the stack to another image. The preview gets scrambled/pixel-trash, too.

**Comment by cytrinox** [comment] 2020-12-15 08:30
@TurboGit afaik you want to release/freeze 3.4 today. If this bug corrupts history stacks and styles created with 3.4 and can not be recovered with 3.4.1 (not sure if it is such a big thing), I just want to make sure you are aware of the issue.

**Comment by TurboGit** [comment] 2020-12-15 14:54
I cannot reproduce, so we need better information about the way to reproduce. I have even tried in overwrite or append mode.

**Comment by cytrinox** [comment] 2020-12-15 15:12
I've created a Debian Test-VM and fresh install of darktable d35f30083b652a431461620c4db7975b775d0567 from https://software.opensuse.org/download.html?project=graphics:darktable:master&package=darktable

I've used this CR2: http://www.rawsamples.ch/raws/canon/RAW_CANON_EOS_5DMARK3.CR2
Make sure no existing XMP file is in the same folder.

1. Import CR2 file
2. Open file in darkroom
3. Apply two Exposure modules, one with +1EV, another with -1EV
4. Create an original duplicate
5. Go back to lighttable
6. Select edited file and choose *History stack* / *copy*
7. Select duplicate and choose *History stack* / *discard*, then *paste*

The second *Exposure* module is missing now and the image preview is garbage.

I've not changed any defaults, started with a empty ~/.config/darktable. No OpenCL on this VM available.

**Comment by chhil** [comment] 2020-12-15 15:28
This is not new...

https://github.com/darktable-org/darktable/issues/6868

**Comment by TurboGit** [comment] 2020-12-15 15:51
Still no luck with this procedure. How do you set the exposure value ?

**Comment by cytrinox** [comment] 2020-12-15 16:04
This is strange, as I can reproduce it on all my machines, with new config and configs migrated from 3.0 -> 3.2 😃 

I change the value by mouse+slider. Then I choose *New instance* and move the slider to -1EV.
After that, I collapse the *exposure 1* module and click lighttable.

![grafik](https://user-images.githubusercontent.com/509535/102239822-88ecda00-3ef7-11eb-86c9-3db15b15134a.png)

**Comment by cytrinox** [comment] 2020-12-15 16:15
Discovered on thing: if I write the sidecar file and import it on the duplicate, it works. The problem seems to be the copy/paste action. After that, I can copy/paste from the original to duplicate in any mode (append/override) without problems.

Only if I discard the history of the duplicate and paste again, the problem is back,

Copy/paste also works when you open the destination image one single time in darkroom, so an initial set of modules is applied.

**Comment by TurboGit** [comment] 2020-12-15 17:35
Tried copy/paste, tried copy parts only exposure selected and paste. Did the same thing after discarding the history of the duplicate just before pasting and tested also by discarding the history and removing the .XMP before pasting.... In all case all is ok on my side. This issue was fixed some time ago, so this looks quite suspicious especially since I seems to not be able to reproduce.

Sorry, nothing more I can do before the 3.4 release, but the good news is that even if there is an issue it is certainly in a very specific context/setup !

**Comment by cytrinox** [comment] 2020-12-15 18:17
Thats okay, there is a workaround, just open the destination image once before pasting such a stack.
And it seems not to irreversible corrupt anything, otherwise loading the xmp should fail, too.

But it's interesting why I even can reproduce it on a fresh machine, seems not so specific context :smile: 

Looking forward to 3.4 :gift:

**Comment by johnny-bit** [comment] 2020-12-28 20:26
This should be fixed on master with recent #7511 being merged. Please test and report back! If the issue is fixed, please close :)

**Closed** 2021-01-01 15:25 UTC
