### ISSUE TITLE
Crop isn't being saved and other crop bugs

### ISSUE THREAD

**Issue by Hieke81** [darktable-org/darktable#6448] opened 2020-10-04 16:42 UTC
OS: Windows 10 on a 2 year old gaming laptop with special graphic cards and processor for movie making.
darktable: latest version (downloaded last week).

So... I just got darktable after reading a lot of positive reviews and comparisons. I started yesterday and I was happy with it (rating, view only X stars in the viewport etc.), until my first real editing started. My first step is always the cropping.

When cropping an image, several problems occur:

1. no cropping grid/handles are being shown
2. automatic crop yes/no doesn't accept no as an answer
3. the chosen grid (in my case: rule of thirds) doesn't show

The software isn't stable. When I retry, it's always different: sometimes the rule of thirds shows up, sometimes it doesn't. Sometimes I can crop and it's being saved (after waiting several minutes) but most of the time the crop isn't applied. It shows in the history stack though...

Most of the time I get the grid and handles to be shown when I go to Lighttable > back to Darkroom > select square > select freehand. Then I can finally do what I want, but nothing is being saved.

I tried several times on the same photo. And on others too.

If this doesn't work, I might as well just not use darktable at all. Like I said: it's the first step I do before touching other things like adjusting the lighting etc.

Any suggestions on how to get this working?!

**Comment by ptilopteri** [comment] 2020-10-04 17:29
> OS: Windows 10 on a 2 year old gaming laptop with special graphic cards and processor for movie making.
> darktable: latest version (downloaded last week).

frequently changes and there are two paths, master and 3.2.1.  No one know what you are using.
 
> So... I just got darktable after reading a lot of positive reviews and comparisons. I started yesterday and I was happy with it (rating, view only X stars in the viewport etc.), until my first real editing started. My first step is always the cropping.
> 
> When cropping an image, several problems occur:
> 
>     1. no cropping grid/handles are being shown

Configurable, use the "gear-wheel/hamburger" at the upper right.
 
>     2. automatic crop yes/no doesn't accept no as an answer

there is a reset/cancel button upper right side of each module, it's the center one

>     3. the chosen grid (in my case: rule of thirds) doesn't show

move your configuration directory to a different location and try with a clean environment.

> The software isn't stable. When I retry, it's always different: sometimes the rule of thirds shows up, sometimes it doesn't. Sometimes I can crop and it's being saved (after waiting several minutes) but most of the time the crop isn't applied. It shows in the history stack though...

sounds like your configuration is somehow borked or the install

> Most of the time I get the grid and handles to be shown when I go to Lighttable > back to Darkroom > select square > select freehand. Then I can finally do what I want, but nothing is being saved.
> 
> I tried several times on the same photo. And on others too.
> 
> If this doesn't work, I might as well just not use darktable at all. Like I said: it's the first step I do before touching other things like adjusting the lighting etc.
> 
> Any suggestions on how to get this working?!

more nice words :)

**Comment by Hieke81** [comment] 2020-10-04 18:27
Tnx for your superquick reply. I checked, it's version 3.2.1.

I don't fully understand what there is to configure, when the software shows grids/handles sometimes and sometimes not...?

**Comment by ptilopteri** [comment] 2020-10-04 18:32
maybe it is time to read the fine manual

there are many options available such as grid lines ...

**Comment by Hieke81** [comment] 2020-10-04 18:36
Of course I read the manual, but the Crop section doesn't say anything about what to do when it behaves strangely (can't predict what happens and can't replicate the clicks and results) and when nothing is being saved.

So... I'm still curious about how to fix these issues.

**Comment by kofa73** [comment] 2020-10-04 20:30
Can you perhaps post a screenshot that shows what happens when you activate the crop/rotate module?
@ptilopteri: @Hieke81 mentioned that there are no crop handles; those, as far as I know, cannot be modified using options, right? Only the grid/guidelines, ratio etc.

**Comment by ptilopteri** [comment] 2020-10-04 22:00
@kofa73 
to my recollection there has never been "handles" but margins that you drag.

I suggested some small time with the documentation.  Since the  OP considers crop
such a basic requirement, seems he would spend a few moments reading about 
that capability and operation.

Have you ever tried another editor?  Don't you have to learn the key-combinations
to operate it?

**Comment by Hieke81** [comment] 2020-10-05 07:52
Hi all,

Who are you referring to with 'he'? I'm a woman, so it can't be me ;-)

I have 2 decades of experience with several photo and film editors (photoshop elements, irfanview and the like & powerdirector plus others), so the basic functions including changing light/contrast/colors/hue/saturation aren't new to me. It's just learning the new software.

I don't know the exact terms of everything in DT, but the main thing is... Every time I try and use it, it behaves differently. Sometimes the grid/overlay of the rule of thirds shows up, sometimes it doesn't. Same for the handles/grid/sliders of the crop function.

So please focus on that, not on the terminology :-)

**Comment by maboleth** [comment] 2020-10-05 10:27
While I cannot help you with your problem, it's a bit unfortunate there wasn't any bugfix-release planned until December and 3.4 version.

Because Darktable has so many bugs fixed in the current Git version and if you cannot compile your own, you are stuck with official 3.2.1 release. I know at least one bug in Crop that was fixed (aspect).

I'm using git version and Crop is working normally for me, all the time. No issues.

**Comment by Hieke81** [comment] 2020-10-05 10:32
Tnx, that helps managing my expectations of new releases and so on.

Maybe a very stupid question, but eh... What is a Git Version? I thought GitHub is a platform for sharing open source software and a kind of user forum. This is much quicker than the help channels of DT itself. 

I'm not a programmer and not able to compile my own version, unfortunately.

**Comment by maboleth** [comment] 2020-10-05 10:34
And oh, you are using windows version. It's a known fact that DT isn't working flawlessly in Win environment as it is in Linux.

Consider the win Darktable port as a fork, more than a fully fleshed release. This is mainly a linux program that dipped its toes in the Win waters.

**Comment by Hieke81** [comment] 2020-10-05 10:38
Yes I read about the Windows problems, but I hoped that DT was also working flawless on Windows by now...

What is a port as a fork? Kind of stripped version? That's fine with me, as long as the given functions work properly.

**Comment by Hieke81** [comment] 2020-10-05 10:39
If possible, I could make a Linux partition for DT on my laptop, but I don't know if that works and secondly it's not the optimal solution of course.

**Comment by maboleth** [comment] 2020-10-05 10:42
> Tnx, that helps managing my expectations of new releases and so on.
> 
> Maybe a very stupid question, but eh... What is a Git Version? I thought GitHub is a platform for sharing open source software and a kind of user forum. This is much quicker than the help channels of DT itself.

There's no stupid questions like those. People maintain the program all the time with commits and changes every single day. Darktable has VERY active developers. Those changes go to the Master git release. During compiling, you pull all those updated source files and build your own - git version. It's the latest release with the most current features and bug fixes.

And IMO, git version is as stable as the official release (if not even more as crucial bug fixes are implemented as well). There was so many bugs fixed, there should be 3.2.2 planned, but that's just my opinion and probably not gonna happen.

**Comment by Hieke81** [comment] 2020-10-05 10:45
Thanks for your explanation. I LOVE the activity of all those developers. But how can I (layman) get git versions too? That makes bug fixes and feature updates available much faster.

But eh... Is it correct that git versions are not official and DT versions are? Although they're made by the same people?

**Comment by kofa73** [comment] 2020-10-05 10:52
@Hieke81 : Can you perhaps post a screenshot that shows what happens when you activate the crop/rotate module?

Please note that when you create a new issue of type 'bug', you're prompted to fill in the following template for a reason -- helping the developers reproduce and fix it.
```
<!-- IMPORTANT
Bug reports that do not make an effort to help the developers will be closed without notice.
Make sure that this bug has not already been opened and/or closed by searching the issues on GitHub, as duplicate bug reports will be closed.
A bug report simply stating that Darktable crashes is unhelpful, so please fill in most of the items below and provide detailed information.
-->

**Describe the bug**
<!-- A clear and concise description of what the bug is. -->


**To Reproduce**
<!-- Provide detailed steps that can reproduce the behavior, such as:
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error
-->


**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->


**Screenshots**
<!-- If applicable, add screenshots to help explain your problem. -->


**Platform (please complete the following information):**
 - Darktable Version: <!-- [e.g. 2.6.0] -->
 - OS: <!-- [e.g. Windows 8.1, Gentoo Linux] -->
 - <!-- OpenCL activated or no? -->
 - <!-- Which graphics card and driver version -->


**Additional context**
<!-- Add any other context about the problem here, for example:
 - Can you reproduce with another Darktable version?
 - Can you reproduce with a RAW or Jpeg or both?
 - Are the steps above reproduce with a fresh edit (removing history)?
 - Attach an XMP if this is necessary
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
 - Is the issue still present using an empty/new config-dir
-->
```

**Comment by maboleth** [comment] 2020-10-05 10:52
> Yes I read about the Windows problems, but I hoped that DT was also working flawless on Windows by now...
> 
> What is a port as a fork? Kind of stripped version? That's fine with me, as long as the given functions work properly.

No, it's a full release, but known to have hiccups, as it uses different environment/libraries to work. I cannot tell you if that's because of Win environment or Crop module really had so many problems in 3.2.1. All I know, in the latest git version, on linux, it's working flawlessly.

> But how can I (layman) get git versions too? That makes bug fixes and feature updates available much faster. But eh... Is it correct that git versions are not official and DT versions are? Although they're made by the same people?

Git versions are working versions, official releases are, well, official and kind of set in stone. Git vers are fluid and change all the time, depending how fast devs work. I really don't know how to build your own on Windows, if it's even possible. Maybe someone else can offer a clue? Or try google to see what do you need. Good luck!

**Comment by Hieke81** [comment] 2020-10-05 11:20
Thanks, maboleth.

@kofa73 I didn't receive all this info when creating this 'ticket' or thread. Otherwise I would've filled that in. Will look at it later.

**Comment by kofa73** [comment] 2020-10-05 11:35
@Hieke81 : no problem. It's provided automatically if you click Issue -> Bug. You c an of course add the info later, it's just useful to have it right from the start.
![image](https://user-images.githubusercontent.com/3177739/95074967-af301580-070f-11eb-8e09-563e78fcc73c.png)

**Comment by ptilopteri** [comment] 2020-10-05 12:46
@Hieke81 
I posted the "he" reference but with no disrespect.  In English usually
the male gender is referenced when using generalities or not knowing the 
gender referred.  And I had no idea you were a Lady.

And your background has no bearing as every application marches to
a different drummer.  One cannot expect to automagically know how 
something is done, only what result to expect.

**Comment by Hieke81** [comment] 2020-10-06 17:40
I know; I was just poking a bit ;-)

**Comment by Hieke81** [comment] 2020-10-06 17:42
> @Hieke81 : no problem. It's provided automatically if you click Issue -> Bug. You c an of course add the info later, it's just useful to have it right from the start.
> ![image](https://user-images.githubusercontent.com/3177739/95074967-af301580-070f-11eb-8e09-563e78fcc73c.png)

Exactly - that's what I did. But there was NO extra text with already given subtitles/subjects. Nor is it in your screenshot.

**Comment by kofa73** [comment] 2020-10-07 07:26
@Hieke81 I don't understand your comment. When I scroll down (note the scrollbar in the very last screenshot), there are plenty of detailed steps provided to guide one through a bug report.

**Comment by MStraeten** [comment] 2020-10-07 08:55
> When cropping an image, several problems occur:
> 
> 1. no cropping grid/handles are being shown

that's works as designed: you can see a rectangle an then can drag the sides or corners. When crop&rotate is applied first, you can't see the frame, because it's identical to the image (100%).
But if you move the mousepointer near to a side or corner, the pointer changes and you can resize the frame by drag&drop

> 2. automatic crop yes/no doesn't accept no as an answer
not reproduceable (win10, dt 3.2.1)

> 3. the chosen grid (in my case: rule of thirds) doesn't show
not reproducible (win10, dt 3.2.1)
btw: the grid is only shown while setting crop&rotate - it's intentionally not present after applying crop&rotate

> The software isn't stable. When I retry, it's always different: sometimes the rule of thirds shows up, sometimes it doesn't. Sometimes I can crop and it's being saved (after waiting several minutes) but most of the time the crop isn't applied. It shows in the history stack though...

please describe each step you’re doing. Cropping is applied by double click or closing the module or switching to a different module.

--> seems to be not a bug

**Comment by Hieke81** [comment] 2020-10-07 10:08
Great, this was helpfull! I always start with the tool in the middle. I tried double clicking with left and that’s what I needed. Thnx!

 

Hartelijke groet,

Hieke

 



 

Van: Martin Straeten [mailto:notifications@github.com] 
Verzonden: woensdag 7 oktober 2020 10:56
Aan: darktable-org/darktable <darktable@noreply.github.com>
CC: Hieke81 <hieke.vanhoogdalem@gmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [darktable-org/darktable] Crop isn't being saved and other crop bugs (#6448)

 

When cropping an image, several problems occur:

1.	no cropping grid/handles are being shown

that's works as designed: you can see a rectangle an then can drag the sides or corners. When crop&rotate is applied first, you can't see the frame, because it's identical to the image (100%).
But if you move the mousepointer near to a side or corner, the pointer changes and you can resize the frame by drag&drop

2.	automatic crop yes/no doesn't accept no as an answer
not reproduceable (win10, dt 3.2.1)

3.	the chosen grid (in my case: rule of thirds) doesn't show
not reproducible (win10, dt 3.2.1)
btw: the grid is only shown while setting crop&rotate - it's intentionally not present after applying crop&rotate

The software isn't stable. When I retry, it's always different: sometimes the rule of thirds shows up, sometimes it doesn't. Sometimes I can crop and it's being saved (after waiting several minutes) but most of the time the crop isn't applied. It shows in the history stack though...

please describe each step you’re doing. Cropping is applied by double click or closing the module or switching to a different module.

--> seems to be not a bug

**Comment by Hieke81** [comment] 2020-10-07 10:15
I'm closing the ticket, my questions have been answered. Tnx again y'all! I'm super happy :-)

**Closed** 2020-10-07 10:15 UTC
