### ISSUE TITLE
The storage option "on conflict: overwrite if changed" doesn't work as described.

### ISSUE THREAD

**Issue by steph72** [darktable-org/darktable#17185] opened 2024-07-22 05:53 UTC
### Describe the bug

In the export panel, there is a "on conflict:" drop down box where one can choose the action to be performed when the exported file is in conflict (i.e. the file is already present at the export location).

However, when the "overwrite if changed" option is selected, an existing file that has changed in the meantime is not overwritten if it has been written at a different location and/or with different settings prior to that. In fact, the file is never being written if it has been exported before.

So, the "overwrite if changed" option leads to files only being written if they have changed since the last export, regardless of where the last export was.

This behavior would be right if there was only one location to export files to. However, if you have multiple export presets and export your files to different location, it severely limits the option's usefulness, because once you have exported a picture with one export preset (say, for web / social media use) you can't export it again with a different preset (say, storage or archival).

In essence, the "on conflict:" qualifier is not considered in two ways:

There's no check if there is a conflict at all (a non-changed file simply doesn't get written), and
there is no check if the file has been changed since the already existing file. There is only a check if the file was modified since it has been last exported anywhere.

### Steps to reproduce (variation 1)

1. Create a export preset that uses the "overwrite if changed" option.
3. Export one picture using this preset
4. Delete the exported picture
5. Export it again
6. The picture is not being exported

### Expected behavior

The picture should be exported.

### Steps to reproduce (variation 2)

1. Create two different export presets. Have one preset write the file to one location, the other to another location.
2. Have both export presets use the "overwrite if changed" option.
3. Export one picture using the first preset
4. Try to export the same picture using the second preset
5. The picture is not being exported a second time, although it is not yet present at the chosen location

### Expected behavior

Darktable should export the picture a second time.

### Commit

unknown

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.0

### What OS are you using?

Mac

### What is the version of your OS?

Sonoma 14.5

### Describe your system?

Macbook pro 14"

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

M2

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This bug was already reported 9 months ago but it seems no one cared (or cared enough), see: https://github.com/darktable-org/darktable/issues/15404

Other people have reported it too, see https://github.com/darktable-org/darktable/issues/16632

**Comment by zisoft** [comment] 2024-07-22 06:02
Duplicate of #15404 

Please don't open multiple issues for the same topic.

**Closed by zisoft** 2024-07-22 06:02 UTC
