### ISSUE TITLE
CANON EOS R7

### ISSUE THREAD

**Issue by jackbauer66** [darktable-org/darktable#12157] opened 2022-07-10 11:54 UTC
Hi Darktable-Team,

I recognized that it's not possible to work right with .CR3-files shooted with the new EOS R7.
Therefore I uploaded a reference file to pixls.us.
Thank you in forward to support my camera.

best regards

**Comment by Nilvus** [comment] 2022-07-10 12:19
Thanks for adding raw but please search before opening issues. Duplicate of of #12127, with exact same title.

**Closed by Nilvus** 2022-07-10 12:19 UTC
Labels: scope: camera support
