### ISSUE TITLE
filmicrgb saturation: tooltip does not follow colour science; strange behaviour at -50%

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#8210] opened 2021-02-13 15:11 UTC
**Describe the bug**
- The tooltip of the middle tones saturation slider reads: 'desaturates the output of the module specifically at extreme luminances. increase if shadows and/or highlights are under-saturated.' https://github.com/darktable-org/darktable/blob/ca5f2520f442c330d0137ebe7c48b615c3d3172d/src/iop/filmicrgb.c#L3758-L3760; however, with the default v4 colour science, the slider controls the mid-tones. Maybe the tooltip should be set based on the colour science, just like how labels are adjusted (https://github.com/darktable-org/darktable/blob/ca5f2520f442c330d0137ebe7c48b615c3d3172d/src/iop/filmicrgb.c#L3904-L3907).
- dragging the slider to the minimum value, -50%, desaturates the image completely: 
![image](https://user-images.githubusercontent.com/3177739/107852840-22ab0780-6e13-11eb-88d7-86d4d90de4a8.png)
  - at this point, the saturation curve, instead of merging into the x axis, runs almost diagonally across the chart; the setting may produce artefacts, like the completely black pixels here: 
![image](https://user-images.githubusercontent.com/3177739/107853283-440cf300-6e15-11eb-953a-d5a7f1d9fa13.png) vs
![image](https://user-images.githubusercontent.com/3177739/107853227-07d99280-6e15-11eb-8a39-8761061cf71b.png)

**To Reproduce**
Open an image; adjust filmicrgb saturation
I used https://tech.kovacs-telekes.org/files/2021-02-13-darktable-issue-8210-filmic/

**Expected behavior**
- Tooltip reflects colour science (v3: extreme luminance; v4: mid-tones)
- Scale either goes to 0%, or 50% does not cause complete desaturation
- If effective saturation is 0, the saturation curve merges into the x axis
- No artefacts in image

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+1068~g688c91aa2
 - OS: Ubuntu 20.10
 - OpenCL: active; Nvidia 1060/6GB, 450.102.04-0ubuntu0.20.10.1

**Comment by Mark-64** [comment] 2021-02-13 16:59
Saturation curve smoothely merges into X axis for me and I have no artifacts.
![immagine](https://user-images.githubusercontent.com/43290988/107855834-116af680-6e25-11eb-9ba0-d907c7c93922.png)

I agree that -50% causing complete desaturation could be confusing

**Comment by kofa73** [comment] 2021-02-13 17:37
I've added a sample NEF + xmp, but I tried other images, with default settings and the -50% saturation, and the saturation line was diagonal.

**Comment by Mark-64** [comment] 2021-02-13 17:55
I can't reproduce with the files provided, maybe it has something to do that I am on windows?
I will check with Ubuntu later

**Comment by kofa73** [comment] 2021-03-04 18:16
Reproduced with 3.5.0+1283~gcb5008425 by:
- importing a pristine Nikon D7000 image
- in filmic, dragging the saturation to -50%.
![image](https://user-images.githubusercontent.com/3177739/110010024-1af9c700-7d1e-11eb-9a81-509eca6624f3.png)

**Comment by kofa73** [comment] 2021-04-04 21:53
With a clean config directory and 3.5.0+1560~g1eb08:
- I can no longer reproduce the top-left -> bottom-right diagonal;
- however, the desaturation issue (complete desaturation at -50%) is still present
- and the tooltip is still out-of-sync with the behaviour

**Comment by johnny-bit** [comment] 2021-06-20 09:29
Well - on `3.5.0+2574` I can still see:

 - top left -> bottom right diagonal with saturation set to -50
 - tooltip being out of sync

However I think the desaturation is correct - at -50% it removes all saturation from middletones, therefore bringing total saturation to none and line in the graph shows that the saturation gets merged to 0. Fortunately I don't see any artefacts comming from -50% saturation.

**Comment by kofa73** [comment] 2021-06-20 09:34
> the desaturation is correct - at -50% it removes all saturation from middletones, therefore bringing total saturation to none

Well, if you get 50% discount at the shop, you don't get the product for free. While I understand that perhaps internally some variable having the value of 0.5 causes complete desaturation and is the minimum allowed value, I still think that on the UI it's confusing.

**Comment by kofa73** [comment] 2021-06-20 11:14
I tested now with 3.5.0+2559~g4f5ece1ae, and could not reproduce the diagonal line. This is with RelWithDebugInfo, I'll try a release build.

**Comment by aurelienpierre** [comment] 2021-06-20 12:56
Won't fix the value without breaking compatibility. Tooltip is trivial to change.

**Comment by aurelienpierre** [comment] 2021-06-20 12:58
Also, why on earth would you fully desaturate using filmic ?

**Comment by kofa73** [comment] 2021-06-20 13:25
By dragging the slider, it was not my intention to completely desaturate the image. I was simply dragging the slider and saw something that did not match my expectations. For users, who maybe want to reduce the saturation while editing filmic settings (remember, when I did this, we didn't have _color balance rgb_ and _filmic_ came with a default 10% boost), 100% desaturation at a setting of -50% is surprising.

When I went to university, one of my teachers told me that they had an assignment to design a phone switch (think the 70s, 80s). They did it, tested it, it worked: then they pushed buttons, the device behaved as expected. They set up a meeting with the client, who came, watched their demo and asked if they could also try. Confident, they said yes. The client went to the box and lay both arms on the rows of switches, pressing many buttons at once. The device crashed. The client explained that the operator may fall asleep in front of the device during the night shift, so in their eyes, this was a valid usage situation.

The moral of the story is that users will try things that you never thought about, because those things do not make sense to you.

On the up side, since no one had complained about this before, it's probably not that important, and will become even less so in the future, as filmic won't apply a boost by default. I understand that making the displayed value human-compatible is not trivial now (I guess you could find a way, but it' not worth the time and code complexity). However, in the future, exposing human-oriented numbers on the UI (in this example: -100%) instead of code-oriented ones (-50%) would be a good approach.

**Comment by aurelienpierre** [comment] 2021-06-20 13:41
> By dragging the slider, it was not my intention to completely desaturate the image. I was simply dragging the slider and saw something that did not match my expectations. For users, who maybe want to reduce the saturation while editing filmic settings (remember, when I did this, we didn't have color balance rgb and filmic came with a default 10% boost), 100% desaturation at a setting of -50% is surprising.

The saturation thingy drives the gaussian fall-off smoothly to 0, plus, when < 0, the amplitude value of the wedge. So, it's not easy to design a parametric equation for the GUI setting that will both have an understandable feedback and produce numerically valid (aka don't divide by 0) pixel ops setting. There is no way to fix now, you need to change the whole thing.

Anyway, I plan on doing a real gamut-mapping in colorout at some point, so once this happens, the hacky saturation mapping in filmic will simply disappear.

> The moral of the story is that users will try things that you never thought about, because those things do not make sense to you.

The problem of adding safety jackets everywhere to handle all users mistakes gracefully is it is going to:
1. make the code slower (pixel-wise branching on `if` statements is not always vectorizable and may end up super slow)
2. introduce a lot of heuristics and special cases that nobody will entirely test, making the reliability of the whole thing questionable.

Debating whether a 180° rotation of the stirring wheel should produce a 180° rotation of the car is kind of not the point (is it even desired ?), you eventually get used to the available range and gain, and then adjust your driving. The point is for the car to not second-guess your decision, which could lead to unpredictable behaviour, even though honoring user decision 1:1 might involve falling off a cliff.

But I like systems that fall off the cliff when instructed to.

**Closed** 2023-03-26 00:19 UTC
Labels: scope: UI, bug: pending, no-issue-activity
