### ISSUE TITLE
Filmroll filter gets populated with current filmroll and hides all other filmrolls on darktable restart

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#11237] opened 2022-02-27 13:53 UTC
Latest darktable git populates the filmroll filter when you doubleclick on one to open it. When you close the software and restart it, no other filmrolls appear as the filter only shows you the last one which was open. Is this intended behaviour?

**Comment by Jiyone** [comment] 2022-02-27 22:09
It does the same for me (macos 10.15)
Also when lightable is loaded (going to darkroom and comming back to lightable) or reloaded (removing a picture for example).

**Comment by jade-nl** [comment] 2022-02-28 08:09
This seems to be development specific (do not see this in 3.8.0 and 3.8.1).

https://user-images.githubusercontent.com/56407344/155946660-fcd20e02-6a14-47c2-af59-f9e330e5c1c2.mp4

As shown, the previous selected folder doesn't stick and depending on the method chosen you either end up with a general film-roll view or a general folder view.

Some info:

this is darktable 3.9.0+560~g2c660a5d8

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support disabled
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

OS                : Linux (kernel 5.9.15-1)
Distro            : Debian Buster (rel. 10.11)
Graphics driver   : nvidia (460.39)
OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)


Reproducible with other version(s)       : No
Reproducible with clean config directory : Yes
Reproducible after removing xmp file     : Yes
Reproducible with both RAWs and JPEGs    : Yes

**Comment by MStraeten** [comment] 2022-02-28 09:12
see #11186
it seems to be a side effect of commit [271a4c1a44da63189a3c8dfcc23f88f5f1cf4872](https://github.com/darktable-org/darktable/pull/11157/commits/86445d57865d0494dc5bb9aaeaab32447c7cebd2) in https://github.com/darktable-org/darktable/pull/11157

**Comment by Nilvus** [comment] 2022-02-28 11:41
It's so a duplicate of #11186. I so close and let you continue on #11186

**Closed by Nilvus** 2022-02-28 11:41 UTC
Labels: duplicate
