### ISSUE TITLE
Phase One iXM-RS150F

### ISSUE THREAD

**Issue by ffilipponi** [darktable-org/darktable#11166] opened 2022-02-17 14:27 UTC
A RAW reference image taken with Phase One 'iXM-RS150F' has been uploaded to https://raw.pixls.us/. I hope this is helpful in the process of adding support for that camera.

**Comment by kmilos** [comment] 2022-02-25 14:00
Duplicate of https://github.com/darktable-org/darktable/issues/10337

**Closed** 2023-09-18 13:03 UTC
Labels: duplicate, scope: camera support
