### ISSUE TITLE
[Feature] Enable independent shortcuts across views (Lighttable/Darktable/Map/...)

### ISSUE THREAD

**Issue by GLLM** [darktable-org/darktable#3636] opened 2019-11-30 12:12 UTC
Hi !

[Context + Problem]

I use LT view without the filmstrip (redundant) but I use DR with the filmstrip to be able to quickly view surrounding pics and select the one I want without having to go to LT.

As of today, whenever you try to setup a shortcut which is already define in another view (i.e. Lightroom/Dartkable/Map/Print/Lightshow/Tethering), you (cleverly) get a warning advising that this new shortcut (say in Lighttable) will replace the one already defined in another view (say Lightroom).

I would like to be able to use F1-F5 to define color tags in LT & DR, 0-5 to defines stars in LT & DR, use left & right arrows to browse to the previous/next image in LT & DR.

The part of the issue is that to be able to define starts/colors in DR, we need to use the filmstrip ... whose shortcuts collide with that of the LT because one can use the LT with filmstrip.

Currently, I cannot, for example, I can use left/right arrows for prev/next picture in LT, but need to resort using Ctrl+Left/Ctrl+Right to go to the prev/next image in DR !!

[Solution/What I want]
I would like to be able to define the same shortcuts in 2 different view (yet I think we should not force the user to be stuck with it ... i.e. not having a general shortcut), without the new one to replace the old one.

[Side note]
I'm not sure why a user would want to use the filmstrip & lighttable, which are mostly used for the same feature, at the same time ... this may be where the issue comes from.
Interestingly, the 0-1 stars default shortcurts are the same in lighttable & filmstrip ... unless you customize them. You then cannot set them back to the same value

Unless I missed something ... at least, trials on my side were unsuccessful !

Thanks
GLLM

**Comment by AlicVB** [comment] 2019-11-30 14:30
duplicate of #3562 
This will be fixed in 3.01 by PR #3594 ...

**Closed by AlicVB** 2019-11-30 14:30 UTC

**Comment by GLLM** [comment] 2019-11-30 15:30
> duplicate of #3562
> This will be fixed in 3.01 by PR #3594 ...

Fair enough, sorry for the hassle @AlicVB 
My usecase was more related to the filmstrip used in darkroom ... 
The PR you listed seem to indeed be a solution for this.
Thanks
