### ISSUE TITLE
Minor text shift when moving mouse over module tabs

### ISSUE THREAD

**Issue by millocz** [darktable-org/darktable#12769] opened 2022-11-04 15:23 UTC
**Describe the bug/issue**
There is a small glitch when interacting with any module with tabs. When moving mouse over a tab, the text may “jump” (be shifted up) a little. 

**Screenshots**
![darktable](https://user-images.githubusercontent.com/3328913/200004548-c0e55c5d-5911-4a5a-98db-1143ceb16c02.gif)

**To Reproduce**
On most platforms it is only visible when using large text (settings>general>font size in points) or using some custom CSS tweaks.

**Expected behavior**
Mouse movement should not cause potential shifts in layout. A border that is added only on hover is causing the issue. To solve this add (invisible) border to all tabs., On hover only change the color of that border. Here is my suggested solution https://github.com/millocz/darktable/commit/2fb0133efc54c5cd2f38c8df9e24371af5a00ca1

**Platform**
tested on:
* darktable version : 4.0.1
* OS                : Win10 / Linux (Manjaro+KDE)

**Comment by TurboGit** [comment] 2022-11-04 16:47
@Nilvus : Probably for you... there is a proposal for fixing that, might help as I know you are quite busy those days.

**Comment by TurboGit** [comment] 2022-11-04 16:48
Yet, I cannot reproduce.

**Comment by millocz** [comment] 2022-11-04 18:33
To clarify things: in darktable.css the border is set to be 0.1em. If 0.1em = 1px the effect wouldn't be visible. It is visible only if the font size is increased so that the border is 2px (or more - maybe on high DPI monitors?).

Just to show what is going on, we could use the same CSS, just make the border much thicker (1em). Before/after:

![darktable2](https://user-images.githubusercontent.com/3328913/200046464-d83eb886-8742-433a-96e4-f93f39a73cab.gif)

The labels before are clearly not aligned.

**Comment by Nilvus** [comment] 2022-11-04 18:36
@millocz: I never reproduce that but I do not use large fonts. Your fix is a way but not sure if it's the optimal one. Will check tonight and make some tests to be sure of the better fix. All your infos are really great and useful. Thanks for all your feedback.

**Comment by Nilvus** [comment] 2022-11-05 17:00
@millocz: just check better your issue and fix. Your fix is just the best and good way of course. As it's yours, could you propose the PR with the fix? I could do it if you prefer.

**Comment by Nilvus** [comment] 2022-11-06 10:32
Thanks @millocz for the fix. Just if one day, you propose another PR, think about adding "fixes #issue-number" to comment of the PR. That will link the issue and close it automatically when the PR is merged. I close this one.

**Closed by Nilvus** 2022-11-06 10:32 UTC
Labels: bug: wip, understood: clear, reproduce: confirmed, scope: UI
