### ISSUE TITLE
darktable 4.0 won't launch

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#12114] opened 2022-07-03 11:12 UTC
I downloaded darktable 4.0 from the recommended opensuse link (using xubuntu 20.04 add repository and install manually):
https://software.opensuse.org/download.html?project=graphics:darktable:stable&package=darktable

On Mint 20.3 (Ubuntu 20.04)

After running sudo apt update I get:

W: GPG error: http://download.opensuse.org/repositories/graphics:/darktable:/stable/xUbuntu_20.04  InRelease: The following signatures were invalid: EXPKEYSIG 040524A84C70D8B5 graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/graphics:/darktable:/stable/xUbuntu_20.04  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

After continuing with the install, darktable won't launch.

Is there a bug in that package? If not, how to solve?

**Comment by kmilos** [comment] 2022-07-03 12:52
Duplicate of https://github.com/darktable-org/darktable/issues/11851

Please contact the packager.

Please search before opening new Issues.

**Closed** 2022-07-03 15:28 UTC
