### ISSUE TITLE
Multiple module instances reversed on import from 2.6.x

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#3477] opened 2019-11-18 16:07 UTC
**Describe the bug**
Import an edit from 2.6.x that uses multiple instances of a module.  Open the image in darkroom and the history stack is correct.  Open the active module list and the instances are in reverse order.  I've shared an image and the edit at https://drive.google.com/drive/folders/1Iq_J_a4xmNEHc9CWs3z6Ze77LcS5oDfm?usp=sharing.  It uses 5 tone curves, the last of which is a contrast curve. 

**To Reproduce**
1. Load the shared image and xmp file in a folder
2. Import the folder
3. Open the image in darkroom
4. Take a snapshot
5. Open the active module list and reverse the order of the tone curves
6. Compare the image to the snapshot and notice the difference 

**Expected behavior**
Instances of a module should be applied in the original order.  The history stack reflects the correct order.  The active module list is reversed.

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 3.0.0rc1+29~g006f5384a

**Comment by parafin** [comment] 2019-11-18 16:58
I've only looked at the XMP, but here are some notes:
multi_name and multi_priority are inversed in there - multi_name "4" (which comes last in history) has multi_priority "0", so it comes first in pipe order (this wasn't changed between 2.6 and 3.0 I think) and should be displayed lower than other instances in active modules list. We should consider if this is maybe just a bug in how instances are displayed, not how they are processed. This bug may as well be in 2.6, not in 3.0. So we should check if output matches and whether order is displayed correctly.

**Comment by wpferguson** [comment] 2019-11-18 17:45
The instances are displayed correctly in the history stack.  They are displayed inverted in the active module stack and processed in that order, therefore the contrast curve in tone curve 4 has a different effect when applied as the first module than as the last and the image has a different appearance.

**Comment by parafin** [comment] 2019-11-18 18:45
Did you compare the output of 2.6 and 3.0? Because it's possible that 2.6 just displays the modules in different order, but processes them the same. Could you make screenshots of 2.6 and 3.0 with this XMP? With history and active modules visible.

**Comment by jenshannoschwalm** [comment] 2019-11-18 19:12
> multi_name and multi_priority are inversed in there - multi_name "4" ...

Right, this can also be seen in the database.
![Bildschirmfoto von 2019-11-18 19-57-02](https://user-images.githubusercontent.com/50982232/69081956-66139c00-0a3f-11ea-9cc7-013b1c9ac0e8.png)

In `_ioppr_migrate_iop_order` (iop_order.c) we take multi_priority and calculate the iop_order of that module.

**Comment by wpferguson** [comment] 2019-11-18 21:41
I uploaded 4 screenshots to the same directory as the image and xmp.

**Comment by junkyardsparkle** [comment] 2019-11-19 02:22
I just checked this with two instances of the border module, one black and one white, and confirm that the processing order is reversed, not just the GUI.

**Comment by TurboGit** [comment] 2019-11-19 08:41
So if I understand correctly #3486 should fix this issue.

Can you test and review? Thanks.

**Comment by wpferguson** [comment] 2019-11-19 16:59
Tested po//fux-order-multi-inst  branch.  Order in active modules is still inverted.  Order in the tone modules is also inverted compared to the order that would occur when you manually created the styles.  It reflects the order in active modules.

**Comment by TurboGit** [comment] 2019-11-19 17:32
@wpferguson : what did you test? it won't fix the issue for images already migrated, there is no hope for this !

**Comment by wpferguson** [comment] 2019-11-19 19:10
I built your branch and did a clean install.  I set up a new config directory that was empty.  I set up an empty picture directory, then copied in the image and xmp that I edited in 2.6.2.  I started the executable from your branch, then imported the directory containing the image from 2.6.2.  The tone curve order is still inverted in the active modules.

I'm going to try another test and create a 2.6.2 library.db with the image and do an upgrade using your branch and see if the results differ when importing from the db versus the xmp.

**Comment by TurboGit** [comment] 2019-11-19 19:18
> inverted in the active modules.

Do you mean in the history?

**Comment by wpferguson** [comment] 2019-11-19 19:22
It shows

tone curve 4
tone curve 3
tone curve 2
tone curve 1
tone curve 

in history and

tone curve
tone curve 1
tone curve 2
tone curve 3
tone curve 4

in active modules.  

I just did the 2.6.2 database migrate to 3.0+29 and it also had the same results.

**Comment by TurboGit** [comment] 2019-11-19 19:28
Well in history it is not important it is only a GUI thing. This is because the module are read in a reverse order. I would say no big deal, the important part is that on the module list it is in the right place and order.

**Comment by wpferguson** [comment] 2019-11-19 19:35
History is correct and active modules is not.  Active modules should be

tone curve 4 
tone curve 3 
tone curve 2
tone curve 1
tone curve

and that way the contrast curve in tone curve 4 affects the whole image and all the previous tone curves.  The way it is now, the contrast curve is applied before the rest of the tone curves resulting in a different edit.

**Comment by TurboGit** [comment] 2019-11-19 19:40
> active modules is not. Active modules should be
> 
> tone curve 4
> tone curve 3
> tone curve 2
> tone curve 1
> tone curve

That's what you wrote in previous message 'it shows..." so I'm lost :)

**Comment by wpferguson** [comment] 2019-11-19 19:53
They say a picture is worth a 1000 words, so let's try this..

2.6.2 edit

![2 6 3](https://user-images.githubusercontent.com/1634891/69180913-22bb3b00-0adc-11ea-99fd-86f6ccdaa281.jpg)

after import into 3.0rc1

![3 0rc1](https://user-images.githubusercontent.com/1634891/69180937-31a1ed80-0adc-11ea-8d75-03f62df202ae.jpg)

**Comment by TurboGit** [comment] 2019-11-19 19:54
Ok, when doing an import from RAW + xmp ?

**Comment by wpferguson** [comment] 2019-11-19 19:55
I tested both ways, RAW + xmp and database upgrade and it showed up in both cases exactly the same.

**Comment by TurboGit** [comment] 2019-11-19 19:58
I cannot reproduce with the RAW + XMP posted by the OP.

**Comment by TurboGit** [comment] 2019-11-19 20:00
And you are the OP :) So I cannot reproduce with the RAW + xmp you posted. I have the 4 tonecurve in the same order as in 2.6.2.

**Comment by wpferguson** [comment] 2019-11-19 20:01
Okay, then let's table this and I'll do further testing and see if I can narrow it down...  I've been reading your and @parafin's discussions of IOP order until my head hurts :), but I'll see if I can wrap my head around it.

**Comment by TurboGit** [comment] 2019-11-19 20:01
![image](https://user-images.githubusercontent.com/467069/69181660-c7a33b80-0b0f-11ea-9270-df833cbca662.png)

**Comment by TurboGit** [comment] 2019-11-19 20:02
![image](https://user-images.githubusercontent.com/467069/69181695-dd186580-0b0f-11ea-83ba-12410998ee5e.png)

**Comment by TurboGit** [comment] 2019-11-19 20:02
That is with your image. Maybe you don't have the latest branch?

**Comment by wpferguson** [comment] 2019-11-19 20:05
Could be.  I'm not confident when I try pulling branches and working from them since I don't do it a lot.  I have confidence in you, so if it's working correctly for you, then let's close it.  Thanks.

**Comment by junkyardsparkle** [comment] 2019-11-20 02:40
I tried some tests with https://github.com/TurboGit/darktable/commit/dbc8a7ef8048a8f9940cc7b30e0ce006ba86ad8e and had mixed results.

Original multiple module is 'framing', 'framing 1', 'framing 2' in that processing order in 2.6.3, producing a clear pattern of black, gray, and white for visual checking. Created a duplicate and disabled disabled the modules. Created a style from the active modules and exported it, it contains the expected "inverted" multi-priority.

First test: ingested the entire 2.6.3 profile directory with the test build. Result: both active and non-active versions imported correctly. Created a duplicate and discarded the history, then applied the style in darkroom. Ordering is incorrect: 'framing 2', 'framing', 'framing 1' both in GUI and actual processing observed in image.

Second test: Same as above, but starting with clean profile and importing image with sidecars and also the dtstyle file. Same results as above. Exported the style, both versions are attached 

[multitest_2.6.dtstyle.txt](https://github.com/darktable-org/darktable/files/3867047/multitest_2.6.dtstyle.txt)
[multitest_3.0.dtstyle.txt](https://github.com/darktable-org/darktable/files/3867048/multitest_3.0.dtstyle.txt)

**Comment by TurboGit** [comment] 2019-11-20 08:28
> Created a duplicate and disabled the modules.

Cab you clarify? Where this is used?

Have you tested @parafin tests here: https://github.com/darktable-org/darktable/pull/3486#issuecomment-555537309

It seems to be somewhat equivalent and is working on my side.

**Comment by junkyardsparkle** [comment] 2019-11-20 08:42
> > Created a duplicate and disabled the modules.
> 
> Cab you clarify? Where this is used?

The duplicate with modules disabled was only because it was mentioned earlier as being possibly significant, but I didn't find any difference there, only with applying the style.

> Have you tested @parafin tests here: [#3486 (comment)](https://github.com/darktable-org/darktable/pull/3486#issuecomment-555537309)

It's after midnight here, so if I don't manage tonight I'll look at that tomorrow.

**Comment by junkyardsparkle** [comment] 2019-11-20 09:01
> Have you tested @parafin tests here: #3486 (comment)

So, looking again at that, we didn't take exactly the same approach, but in both cases there seems to be trouble with the style. One thing I found interesting in my results with three multi-instances is that the incorrect results were not a simple inversion of correct order, but using only two modules might alias it as being that.

**Comment by TurboGit** [comment] 2019-11-20 09:15
@junkyardsparkle : so please describe a simple step by step the way to reproduce and I'll look at it. thanks.

**Comment by TurboGit** [comment] 2019-11-20 09:26
I can reproduce and this is a stupid mistake in the computation of max multi-priority!!!

**Comment by TurboGit** [comment] 2019-11-20 09:29
It was working by change up to two multi-instance!

**Comment by TurboGit** [comment] 2019-11-20 09:59
New version pushed and working with 3 multi-instances.

**Comment by wpferguson** [comment] 2019-11-20 19:50
@TurboGit , I cloned your repository, then checked out the branch and built from that.  The image imported correctly, with all the tone curves in the right place.  Thanks again.

**Comment by junkyardsparkle** [comment] 2019-11-20 22:20
After the latest commits the issues I reported above are fixed. I'll try to do some random torture testing with strange multi-ordering and styles within this branch itself later on, and report anything weird at the PR.

**Closed** 2019-11-21 06:09 UTC
Labels: bug
