### ISSUE TITLE
segfault when creating a style from history

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#16140] opened 2024-01-18 06:59 UTC
### Describe the bug

I was setting which history elements to add to a new style when darktable crashed.
[darktable_bt_65EUH2.txt](https://github.com/darktable-org/darktable/files/13973004/darktable_bt_65EUH2.txt)

### Steps to reproduce

Probably not reproducible (and may have been the result of some background processing). Anyway:
- Click on the 'new style from history elements' widget in the darkroom
- Fill in the name
- Select elements to include

### Expected behavior

should not crash

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+290~gdbd7298b89

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

X11, KDE, GTK 3.24.38

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060/6 GB, nvidia driver v525.147.05

**Comment by TurboGit** [comment] 2024-01-18 07:37
I can reproduce, I just click "select none" and select one in the list, it crashes!

**Comment by ralfbrown** [comment] 2024-01-18 15:49
Same here using Pascal's steps.  Looks like `gtk_tree_view_get_model` doesn't like being passed an empty list...  (src/gui/styles_dialog.c line 348)

**Comment by TurboGit** [comment] 2024-01-18 15:51
I have the fix, will be pushed in a moment.

**Comment by TurboGit** [comment] 2024-01-18 16:13
@kofa73 : Should be fixed, thanks for reporting. This is an issue introduced recently by me while working on another PR :)

**Closed** 2024-01-18 16:12 UTC
Labels: priority: high, reproduce: confirmed, bug: pending

**Comment by kofa73** [comment] 2024-01-18 19:52
Fix confirmed, thank you.
