### ISSUE TITLE
darktable 3.6.1 - JPG export bug: output becomes broken, depending on image size

### ISSUE THREAD

**Issue by mzannoni** [darktable-org/darktable#10283] opened 2021-10-27 22:44 UTC
**Describe the bug/issue**
I've found out that the export module has extremely inconsistent performance when exporting JPGs.
As you can see in the attached pictures below, simply changing the "set size in pixel" values in export module generates very erratic (and unusable) results.
What makes it bad is that the output at full resolution is also bad.

Thus far, I could obtain (apparently) decent JPG image only setting the pixel size to 3840x3840.
Full resolution and HD (1920x1920) settings give very bad results.

Disabling OpenCL (in "preferences -> gpu/cpu/memory) doesn't solve the issue, but produces differently looking damaged results.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Set different values in the "set size in pixel" fields in the export module in the light table
2. The result has a chance to come out "broken"

**Expected behavior**
Only the resolution should be different (resized image), but the output should be still consistently looking.

**Screenshots**
This one looks reasonable (size set to 3840x3840)
![Trentino_estate_2021_0459_dt_4K](https://user-images.githubusercontent.com/29273478/139156686-f177f541-9dd9-4e89-870c-8d7c941a5ddb.jpg)

But at full resolution it looks terrible:
(adding link, file too big) [Trentino_estate_2021_0459_dt.jpg](https://mega.nz/file/Rhl2nCgT#PUc5waQRGozkaZS4GKhrOx7vlED5lFVh9qY4IWuX7A0)

Setting to 1920x1920 also looks terrible:
![Trentino_estate_2021_0459_dt_HD_web](https://user-images.githubusercontent.com/29273478/139156800-e05e7645-1e92-4376-bc2d-e8c4aed9e896.jpg)

Same as previous, but with OpenCL disabled:
![Trentino_estate_2021_0459_dt_HD_web_01](https://user-images.githubusercontent.com/29273478/139156837-45b1adec-b18e-43cc-a8cc-98cd27720840.jpg)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.1-1.1
* OS                : Linux - kernel 5.4.0-89-generic
* Linux - Distro    : e.g. Ubuntu 20.04.3
* Memory            : 32 GB
* Graphics card     : NVIDIA GeForce GTX 1050 Ti
* Graphics driver   : nvidia-driver-460 (proprietary)
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 
* Desktop           : Gnome 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
The raw file is [this](https://mega.nz/file/Uk82zYwS#xCRlZj6lmkyY6oPH4R5poR_ks9biqNSbgRJxDyx6x7E).
The [XML file](https://mega.nz/file/wp9AgayT#w7nCeDZgwsqqcD7i8JPmzxrL3ZVswaRsoyAcogabWhw) (identical development settings for all the jog above, only difference in the export module, pixel size, and OpenCL disabled in the last).

EDIT: forgot to mention, discussion also going on [here](https://discuss.pixls.us/t/darktable-export-bug-photo-changes-depending-on-pixel-size/27610?u=billznn) (apparently I'm not the only one affected; one reported also for ver 3.7).

**Comment by Almijisti** [comment] 2021-11-08 17:15
I'm having a related issue with exporting to jpg.  Eventually, after about 5 or six exports, any additional exports are totally black and only about 220 kb in size.  This seems to be a resource issue as closing and reopening darktable resolves it, at least for the next 5 or 6 exports.

**Comment by mzannoni** [comment] 2022-01-09 14:30
I've just verified this issue is still present and with the same symptoms in darktable 3.8.0.

To summarize: the exported jpg appears broken when:
- full resolution, haze removal module enabled, doesn't matter if high quality resample is enabled or not
- HD resolution, haze removal enabled, high quality resampling enabled

It seems that it is not broken when haze removal is not used.
In 4K exports, it does not appear broken, independently of the above mentioned settings.

**Comment by peter-joo** [comment] 2022-02-05 18:44
Hi there, this is the first time I use Darktable :)
Haze removal is fantastic, thanks for the huge effort @rabauke !

However I also faced exactly the same problem mentioned in this ticket with version 3.8.0:
The exported version is totally different then the one in darkroom tab, if and only if 'Haze removal' is active.

After playing a while I can confirm -and emphasize- that **a simple workaround already pointed out by @mzannoni works!**  

What you have to do is to **set 'by scale' to '0.999999' for 'set size' in 'export' module**.
That's it :)

Setting '1.0' there does not work.
Also setting 0.999999 acts as if it was 1.0, since my exported image's with and height are the same as the input.

I am wondering whether this Haze removal module needs a non-1.0 fraction definition? 
Or maybe the whole problem is inside the export module itself, around how the scale is defined?
I don't know, but definitely the code around scale should be the culprit or at least suspicious.

Once again: the problem is **NOT** that the 'The sky in the provided image is completely blown out' pointed out by @rabauke in 
(https://github.com/darktable-org/darktable/issues/4092)
_The bright parts of an image are crucial for estimating the global hazy background light and the local amount of haze. The sky in the provided image is completely blown out. The haze removal module requires a properly exposed image. The haze removal module is able to deal with clipping highlights in some small portions of the image but a completely blown out sky causes problems._

**Comment by peter-joo** [comment] 2022-02-05 19:14
Well, this trick works for some of my images and does not work for others.

I don't know why :(

Still, based on the above 0.999999 vs 1.0 difference darktable developers can start their investigation, I suppose.

Thanks for their work, in advance.

**Comment by kofa73** [comment] 2022-02-06 19:45
Note that with the supplied image, the preview changes significantly if gamut clipping is turned on. Maybe we have out-of-gamut colours that dehaze cannot handle. 
![image](https://user-images.githubusercontent.com/3177739/152698390-3c385505-3383-416a-9755-696c5b10a371.png)
![image](https://user-images.githubusercontent.com/3177739/152698401-725fec8c-f4cd-4fef-9f79-634af4d0643f.png)

Switching to the 'modern chromatic adaptation' (WB = _camera reference_ + enabling _color calibration_) and moving the dehaze module above color calibration produces the following preview:
![image](https://user-images.githubusercontent.com/3177739/152698548-bc1a410f-1844-495e-b0ab-7c6ada7cf911.png)
And the following full-size output (well, it's scaled; but it's scaled in the viewer):
![image](https://user-images.githubusercontent.com/3177739/152698568-70225f3f-2f76-4964-88de-551b16608217.png)

**Comment by rabauke** [comment] 2022-02-08 22:13
@mzannoni: The haze removal module is expected not to work if the sky is blown out. This example, however, has no blown out sky. A few pixels are over exposed but I do not expect that these cause severe problems. Thanks for this example, which may help me to debug this issue.

**Comment by peter-joo** [comment] 2022-02-08 22:20
I hope I helped a bit too :)

Also, one question pls: what is your opinion on the 1.0 vs 0.999999 sensitivity I described above?
How come that for a certain image in practice such a minuscule difference in the scale alters the haze removal algorithm that much?
Do you plan to further investigate that one too?

**Comment by mzannoni** [comment] 2022-02-09 06:42
@rabauke you're welcome, and thanks for considering this.
I know about the applicability of haze removal, however I think here the issue is a bit different, since the output, given some specific export parameters, differs so much. Especially, for me exporting without scale, should yield something extremely similar to the preview in darktable.

**Comment by kofa73** [comment] 2022-02-09 07:31
@mzannoni The preview is **scaled**, and it is scaled by the same algorithms as used when you export with scaling **and** set *high quality resampling = no*. So the difference between 1.0 and 0.9999 is that the 2nd setting triggers scaling.

**Comment by peter-joo** [comment] 2022-02-09 10:33
@kofa73
"So the difference between 1.0 and 0.9999 is that the 2nd setting triggers scaling."

Still, between the 1.0 and 0.9999 scale the Haze removal's output shows major difference.
Why? Did you check my post above?
https://github.com/darktable-org/darktable/issues/10283#issuecomment-1030678344

I suppose that the the haze removal algorithm is (should be) robust enough, meaning that it is not sensitive for such small difference between 1.0 and 0.9999.

@kofa73 pls comment :)

**Comment by kofa73** [comment] 2022-02-09 10:53
When darktable generates the non-zoomed (-> downscaled) preview, which you see in the editor, it applies the same algorithmic trade-offs (to speed up editing), as when you do a downscaled export with _high quality resampling = no_. Therefore, when you do an export not at 100% scale, but with 99.9999%, you also get the same, lower-quality algorithms in your output. Therefore, the exported file matches the preview.
Due to a bug, scaled exports were done with low-quality mode even if you set _high quality resampling = yes_.

It's not the scaling _factor_ that counts; it's the application of the low-quality (= faster) algos. At least this is how I understand it.

**Comment by peter-joo** [comment] 2022-02-09 10:59
thank you for the explanation @kofa73, then I'll wait for https://github.com/darktable-org/darktable/pull/11079 to be fixed.

**Comment by kofa73** [comment] 2022-02-09 11:20
That won't affect this issue. The only effect will be that with you'll have to set low-quality export explicitly to match the preview.
Your image stack has some no-longer recommended modules like shadows-highlights. _rgb curves_ seems to be OK, but I don't know how that handles luminance levels > 1 (which can occur with the scene-referred workflow).
See https://pixls.us/articles/darktable-3-rgb-or-lab-which-modules-help/

**Comment by kofa73** [comment] 2022-02-09 12:06
However, the strange thing is that in your case the 100% zoomed-in preview is fine; but the exported image is not:
![image](https://user-images.githubusercontent.com/3177739/153197032-79cd0626-9158-4d55-aeca-46bfb1c8313e.png)

Maybe _dehaze_ always uses the fast algorithms for the preview?

Plus, the HQ output (6011x4008 pixels) also looks fine (a bit different from the preview, but that might be due to colour management?):
![image](https://user-images.githubusercontent.com/3177739/153197342-37e25f47-771d-41b7-988e-8d6afe1a43b9.png)

And finally, the LQ export at 6011x4008 pixels:
![image](https://user-images.githubusercontent.com/3177739/153197523-2f0eeb87-8ec2-47d0-bec9-c589b4d212a3.png)

**Comment by peter-joo** [comment] 2022-02-09 12:08
"the strange thing is that in your case the 100% zoomed-in preview is fine; but the exported image is not:"
this is exactly what's happened with me too.

Do you want to see the sample image?

**Comment by kofa73** [comment] 2022-02-09 12:30
@rabauke Heiko, there are some comments in the code:
```
  // hazeremoval module needs the color and the haziness (which yields
  // distance_max) of the most hazy region of the image.  In pixelpipe
  // FULL we can not reliably get this value as the pixelpipe might
  // only see part of the image (region of interest).  Therefore, we
  // try to get A0 and distance_max from the PREVIEW pixelpipe which
  // luckily stores it for us.
```
Might that have something to do with this difference of the 100% preview vs 100% export?

**Comment by mzannoni** [comment] 2022-04-27 13:18
This is not yet fixed in the latest release.
I've just tried with v3.8.1 and it's still look identical (with haze removal the exported jpg is broken).

**Closed** 2023-04-24 00:16 UTC
Labels: no-issue-activity
