### ISSUE TITLE
Error message while trying to install darkatable on Ubuntu (20.04) -  GPG key seems to be expired

### ISSUE THREAD

**Issue by jftregor** [darktable-org/darktable#6574] opened 2020-10-19 08:49 UTC
**Description**
Cannot "manually" install darkatble on ubuntu 20.04 because of *possibly* expired GPG key

**To Reproduce**
I follow the steps described here: [https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable#manualUbuntu](https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable#manualUbuntu)
All works fine until I reach the `sudo apt update` step:
```
Err :19 http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_20.04  InRelease
  Les signatures suivantes ne sont pas valables : EXPKEYSIG 040524A84C70D8B5 graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>
...
W: Erreur de GPG : http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_20.04  InRelease : Les signatures suivantes ne sont pas valables : EXPKEYSIG 040524A84C70D8B5 graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>
E: Le dépôt http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_20.04  InRelease n'est pas signé.
N: Les mises à jour depuis un tel dépôt ne peuvent s'effectuer de manière sécurisée, et sont donc désactivées par défaut.
```

Sorry, error messages are written in french, but basically it says that:

* `the following signatures are not valid  : EXPKEYSIG 040524A84C70D8B5 graphics:darktable OBS Project <graphics:darktable@build.opensuse.org>`
* `the repository http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_20.04  InRelease is not signed`
* `updates from such a repository cannot be done in a secure manner and therefore are deactivated by default`

After googling a little, I understand that `EXPKEYSIG` means "expired key"...

So, is the key really expired or am I missing something ?

Regards

**Platform:**
 - Darktable Version: 3.0.1 but I'm trying to install 3.2.1
 - OS:  Kubuntu 20.04

**Comment by parafin** [comment] 2020-10-19 09:27
Duplicate of #5918.
Issues with external repositories should be reported to corresponding bug trackers, e.g. https://bugzilla.opensuse.org/ in this case, not here.

**Closed by parafin** 2020-10-19 09:27 UTC

**Comment by jftregor** [comment] 2020-10-19 12:30
Well, as it is not that easy to find the solution inside [https://bugzilla.opensuse.org](https://bugzilla.opensuse.org), here is **the** step I missed: before trying to download the new key, I had to remove the older one, using the following:
```
sudo apt-key del 4C70D8B5
```
where "4C70D8B5" comes from the 8 last characters of the key...

Also, I downloaded the new key from the "master" branch of the repository (notice the *graphics:darktable:**master*** name of the repository in the following command)
```
curl -fsSL https://download.opensuse.org/repositories/graphics:darktable:master/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/graphics:darktable.gpg > /dev/null
```

And finally, `sudo apt update` gave me no more error and I was finally able to install darktable 3.2.1 :-)

Hope this helps...
