### ISSUE TITLE
dark edges around light when editing sony raw photographs

### ISSUE THREAD

**Issue by axiomgraph** [darktable-org/darktable#7618] opened 2021-01-02 03:57 UTC
**Describe the bug**
 I was editing a raw photograph of car shoot taken from sony camera. but suddenly found this dark edges around light tried to export to see if it is display related issue but it is not. tried using modules like defringe but is not working.

**To Reproduce**

just start editing 
https://drive.google.com/file/d/1IyAwXfPsRdxIR-DsMfepYaPiL2gV0rr7/view?usp=sharing

**Expected behavior**

**Screenshots**

![Screenshot from 2021-01-01 10-56-24](https://user-images.githubusercontent.com/68183694/103450435-63741480-4cdc-11eb-87f9-1c9b644454c5.jpg)

**Platform (please complete the following information):**
 - Darktable Version:  3.4
 - OS:  Ubuntu 20.04
 - 
 -  Intel HD graphics

**Additional context**

**Comment by ralfbrown** [comment] 2021-01-02 16:20
Unable to reproduce on current master.  Please provide a .xmp sidecar that shows the problem, as I see you have a bunch of modules active.

Are you applying heavy sharpening?  That tends to produce what looks like a dark outline on the dark side of a high-contrast transition.

**Comment by johnny-bit** [comment] 2021-01-02 16:43
Cant replicate. On neither 3.2.1, 3.4.0 and current master...

TBH - It's more likely that you are actually introducing problems rather than fixing them. The raw itself is OK (btw - is that your picture or CC0 licenced one?), the highlights in car lights can be made "nice" and I don't even need to use lens corrections nor defringe nor any other fun stuff. Just exposure + filmic is enough. If I add to that color calibration I can get VERY nice looking shot.

Here's what I recommend:
1. Read through https://www.darktable.org/usermanual/en/ - It's VERY up to date stuff
2. Watch https://www.youtube.com/c/AurélienPIERREPhoto and https://www.youtube.com/user/audio2u
3. Try https://discuss.pixls.us/ and "Play RAW" section to help with edits

I'm gonna close this now, but If you attach xmp file with reproducible results and it isn't due to "overbaking" settings then I reopen ASAP and we'll investigate the root of the issue.

**Closed by johnny-bit** 2021-01-02 16:43 UTC

**Comment by axiomgraph** [comment] 2021-01-03 04:42
my xml with default modules scene refered just adjusted settings
<?xml version="1.0" encoding="UTF-8"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:darktable="http://darktable.sf.net/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
   exif:DateTimeOriginal="2020:07:28 20:00:00"
   xmp:Rating="1"
   xmpMM:DerivedFrom="signature edits free raws DSC0492.ARW"
   darktable:import_timestamp="1609344154"
   darktable:change_timestamp="1609648733"
   darktable:export_timestamp="1609332732"
   darktable:print_timestamp="-1"
   darktable:xmp_version="4"
   darktable:raw_params="0"
   darktable:auto_presets_applied="1"
   darktable:history_end="19"
   darktable:iop_order_version="1"
   darktable:history_auto_hash="27d49e13cd648a9e3a7d9669aa8a9d39"
   darktable:history_current_hash="1f0a3bc8b2d5996cb8f720d7bb7a3ae7">
   <darktable:masks_history>
    <rdf:Seq/>
   </darktable:masks_history>
   <darktable:history>
    <rdf:Seq>
     <rdf:li
      darktable:num="0"
      darktable:operation="rawprepare"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="000000000000000020000000000000000002000200020002ac3f0000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAYY0QVwggZ7CB6pfNoAAEkgGQQ="/>
     <rdf:li
      darktable:num="1"
      darktable:operation="demosaic"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="0000000000000000000000000000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAYY0QVwggZ7CB6pfNoAAEkgGQQ="/>
     <rdf:li
      darktable:num="2"
      darktable:operation="colorin"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="gz19eJzjZgCCegYGgUUbbN4A6YbsOImiUARNbTBBBUILsEAFoLRGAW3sGwWkARbCSkbBMAcAFN4KiQ=="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAYY0QVwggZ7CB6pfNoAAEkgGQQ="/>
     <rdf:li
      darktable:num="3"
      darktable:operation="colorout"
      darktable:enabled="1"
      darktable:modversion="5"
      darktable:params="gz08eJxjZACCUAY4KGguEitC4lMKBC5ySVDTPErBgbuxKO5puB9LU/cJ3IwHmx9gmEhVezakx2A1z+Ahcf4J8ELVDwCSgRQz"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAYY0QVwggZ7CB6pfNoAAEkgGQQ="/>
     <rdf:li
      darktable:num="4"
      darktable:operation="gamma"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="0000000000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAYY0QVwggZ7CB6pfNoAAEkgGQQ="/>
     <rdf:li
      darktable:num="5"
      darktable:operation="temperature"
      darktable:enabled="1"
      darktable:modversion="3"
      darktable:params="008038400000803f0000b53f0000c07f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAYY0QVwggZ7CB6pfNoAAEkgGQQ="/>
     <rdf:li
      darktable:num="6"
      darktable:operation="highlights"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="000000000000803f00000000000000000000803f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYARiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAErAGQU="/>
     <rdf:li
      darktable:num="7"
      darktable:operation="sharpen"
      darktable:enabled="1"
      darktable:modversion="1"
      darktable:params="000000400000003f0000003f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYAJiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAExgGQY="/>
     <rdf:li
      darktable:num="8"
      darktable:operation="flip"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="ffffffff"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAYY0QVwggZ7CB6pfNoAAEkgGQQ="/>
     <rdf:li
      darktable:num="9"
      darktable:operation="basecurve"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="gz09eJxjYICAL3eYbKcsErU1fXPdVmRLpl1B+T07pyon+6WC0fb9R6rtGRgaoHgUDCXAhsRmwpCFxCkjkAUAufkQ3g=="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYAZiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAE4AGQc="/>
     <rdf:li
      darktable:num="10"
      darktable:operation="filmicrgb"
      darktable:enabled="1"
      darktable:modversion="4"
      darktable:params="gz02eJybNXOyIwMDw0EGhgYHBgYHKD7hBMEQMAuoRn9ZhQ1I7EpSK0je8eyZNfYMDAogvQxnz/jYMQNpRihmQGPDwBN2BgYAkDAUNQ=="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYAZiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAE4AGQc="/>
     <rdf:li
      darktable:num="11"
      darktable:operation="exposure"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="00000000000000000000000000004842000080c000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYAZiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAE4AGQc="/>
     <rdf:li
      darktable:num="12"
      darktable:operation="basecurve"
      darktable:enabled="0"
      darktable:modversion="6"
      darktable:params="gz09eJxjYICAL3eYbKcsErU1fXPdVmRLpl1B+T07pyon+6WC0fb9R6rtGRgaoHgUDCXAhsRmwpCFxCkjkAUAufkQ3g=="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYAZiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAE4AGQc="/>
     <rdf:li
      darktable:num="13"
      darktable:operation="exposure"
      darktable:enabled="1"
      darktable:modversion="6"
      darktable:params="0000000000000000b072e83f00004842000080c000000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYAZiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAE4AGQc="/>
     <rdf:li
      darktable:num="14"
      darktable:operation="filmicrgb"
      darktable:enabled="1"
      darktable:modversion="4"
      darktable:params="gz02eJybNXOyIwMDw8HW1wcdGBgcoPiEEwRDwCygGv1lFTYgsahL9iB5x7Nn1tgzMCiA9DKcPeNjxwykGaGYAY0NA0/YGRgAKtYVlg=="
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYAZiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAE4AGQc="/>
     <rdf:li
      darktable:num="15"
      darktable:operation="defringe"
      darktable:enabled="0"
      darktable:modversion="1"
      darktable:params="000080400000a04100000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYAJiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAExgGQY="/>
     <rdf:li
      darktable:num="16"
      darktable:operation="cacorrect"
      darktable:enabled="0"
      darktable:modversion="1"
      darktable:params="32000000"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz14eJxjYIAACQYYOOHEgAYY0QVwggZ7CB6pfNoAAEkgGQQ="/>
     <rdf:li
      darktable:num="17"
      darktable:operation="highlights"
      darktable:enabled="1"
      darktable:modversion="2"
      darktable:params="000000000000803f00000000000000000000803f"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYARiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAErAGQU="/>
     <rdf:li
      darktable:num="18"
      darktable:operation="highlights"
      darktable:enabled="0"
      darktable:modversion="2"
      darktable:params="000000000000803f00000000000000009643cb3e"
      darktable:multi_name=""
      darktable:multi_priority="0"
      darktable:blendop_version="10"
      darktable:blendop_params="gz13eJxjYGBgYARiCQYYOOHEgAYY0QVwggZ7CB6pfNoAAErAGQU="/>
    </rdf:Seq>
   </darktable:history>
   <dc:description>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">binary comment</rdf:li>
    </rdf:Alt>
   </dc:description>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
![Screenshot from 2021-01-03 10-07-27](https://user-images.githubusercontent.com/68183694/103471889-16f80a00-4dac-11eb-9e7f-a5afdf524c16.png)

**Comment by axiomgraph** [comment] 2021-01-03 04:45
problem still exist even i exporting image 
![signature edits free raws DSC0492_02](https://user-images.githubusercontent.com/68183694/103471915-8bcb4400-4dac-11eb-9f54-57788082ba8b.jpg)

**Comment by ralfbrown** [comment] 2021-01-03 05:13
Something went wrong when you pasted the sidecar, probably as a result of special characters being interpreted as Markdown formatting.  Please **attach** the file, don't paste it.

The only thing I see around the "angel eyes" lights in the image you posted is JPEG compression artifacts probably exaggerating a sharpening halo.

**Comment by axiomgraph** [comment] 2021-01-03 15:32
https://drive.google.com/file/d/10P1wsUWB3CVQKNFr9R26ZqoE2nGmmGd6/view?usp=sharing

**Comment by johnny-bit** [comment] 2021-01-03 15:41
IMO unnecessary oversharpening. In exported image the "angel eyes" have sharp steps even.

**Comment by axiomgraph** [comment] 2021-01-04 06:14
https://user-images.githubusercontent.com/68183694/103506165-0f0a9980-4e82-11eb-886a-f37f92c7e7ea.mp4
