### ISSUE TITLE
darktable "unknown-version"

### ISSUE THREAD

**Issue by plougastel** [darktable-org/darktable#13892] opened 2023-03-11 10:30 UTC
### description

Compiling dt leads to an "unknown-version".

### reproducing

`git clone https://github.com/darktable-org/darktable.git`
`cd darktable`
`git submodule init && git submodule update`
`./build.sh`
(become root)
`/usr/bin/cmake --build /path/to/darktable/build --target install`

Then running
`/path/to/dt/bin/darktable --version`
gives
`this is darktable unknown-version`

### others

cmake 3.25.1

**Comment by zisoft** [comment] 2023-03-11 10:56
Fetch the tags first:

`$ git fetch --all --tags`

then recompile.

**Comment by plougastel** [comment] 2023-03-11 12:35
Thanks. So [building instructions](https://github.com/darktable-org/darktable/wiki/Building-darktable#general-build-instructions) should be updated.

But fetching tags don't resolve the problem…

**Comment by kmilos** [comment] 2023-03-11 13:04
Please search before opening new issues as this was already covered, and close this one.

Please feel free to submit any documentation changes directly, thanks.

**Comment by parafin** [comment] 2023-03-11 15:41
My guess your install command is wrong. Do ‘cmake --install’ instead of build target install.

**Comment by kmilos** [comment] 2023-03-11 15:48
Possible duplicate of https://github.com/darktable-org/darktable/issues/11542

**Comment by Nilvus** [comment] 2023-03-11 15:56
I'm sure it's a duplicate of #11542. It's not a darktable issue but just a Git security. See on the on the end, one of the last commit (before mine and when I close it) to find how to fix that with a Git command.

I close this one. If needed, you could comment here even if it's closed.

**Closed by Nilvus** 2023-03-11 15:56 UTC

**Comment by plougastel** [comment] 2023-03-11 16:17
> Please search before opening new issues as this was already covered, and close this one.
@kmilos you are right…

@Nilvus @kmilos
yes it was a duplicate of [#11542](https://github.com/darktable-org/darktable/issues/11542)
