### ISSUE TITLE
Filmic and sigmoid both enabled with import

### ISSUE THREAD

**Issue by ctouz** [darktable-org/darktable#14817] opened 2023-07-01 13:40 UTC
### Describe the bug

if workflow set to scene-referred(filmic) or scene-referred(sigmoid) or none and a filmic preset and a sigmoid preset for the same camera. when importing raw for this camera, sigmoid and filmic are both automatically activated.if workflo

### Steps to reproduce

1 create a filmic preset for a body
2 create a sigmoid preset for de same body
3 set worflow on scene-referred(filmic) or scene-referred(sigmoid) or none.
4 import a raw from this body
5 filmic and sigmoid both enabled

### Where did you install darktable from?

self compiled

### darktable version

4.4.0

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro linux

### Describe your system?

16 g ranm

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

rtx3050

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

*

**Comment by MStraeten** [comment] 2023-07-01 14:22
works as designed - the workflow default doesn’t override custom preset rules

**Comment by ctouz** [comment] 2023-07-01 17:34
I don't agree, in darktable 4.2, if I have created a preset for a camera and I set the workflow to none when I import a raw from this film camera, it is not activated (which is logical).
why should it be any different in 4.4?
with 4.4 in the same scenario, filmic and sigmoide are both automatically activated, which is contrary to the manual

**Comment by Nilvus** [comment] 2023-07-01 18:33
@ctouz: your issue is not clear. First, on step 3, you precise that this appear on nearly all workflows. Thus, you do not precise how you set your presets. What is applied on import depend on what is automatically applied. So depending on how you set your presets and workflow, result could be different.

Plus, would be good if you can test again on 4.4.1 which had been released today with some fixes about auto-preset.

**Comment by ctouz** [comment] 2023-07-01 21:32
Version 4.4.1 solves the "https://github.com/darktable-org/darktable/issues/14799" problem I mentioned. but not the fact that if I create, for example, a preset on the film module for a nikon Z6 and a preset on the sigmoid module for z6.
the workflow is set to "none" if I import raw images taken with the Z6 in the history filmic and sigmoid are activated when I think they shouldn't be.if the workflow is set to scene-referred (filmic) or scene-referred(sigmoid) the 2 are activated when there should only be the module that corresponds to the workflow activated.
![Screenshot_20230701_231329](https://github.com/darktable-org/darktable/assets/28384260/1b22b9f5-bd4b-4ff0-9267-d75104f4b0a1)
![Screenshot_20230701_231251](https://github.com/darktable-org/darktable/assets/28384260/a1569ba2-4b0b-43cb-a55c-5d25874d6ed2)
![Screenshot_20230701_231214](https://github.com/darktable-org/darktable/assets/28384260/5082c9fc-f074-4d0f-ac23-a45090478575)
![Screenshot_20230701_231129](https://github.com/darktable-org/darktable/assets/28384260/84dbd554-2f6e-43b4-9b84-619474fcf643)
![Screenshot_20230701_231030](https://github.com/darktable-org/darktable/assets/28384260/50787984-cbe3-4b4c-82c0-993a8ffe6d31)

**Comment by TurboGit** [comment] 2023-07-02 05:47
> Version 4.4.1 solves the "https://github.com/darktable-org/darktable/issues/14799" problem I mentioned.

Would have been nice to answer this on the issue.

> a preset on the film module for a nikon Z6 and a preset on the sigmoid module for z6.
the workflow is set to "none" if I import raw images taken with the Z6 in the history filmic and sigmoid are activated

Yes, because the actual workflow is not part of the preset's filters. I'm not saying that it should not be, but we cannot do better at the moment.

**Comment by Nilvus** [comment] 2023-07-02 07:07
@ctouz: so that's not an issue. If you tick the auto-apply checkbox on both, you will have both auto-applied on import. That's so works as designed. Relation with workflow could maybe enabled but so more a feature enhancement as stated by @TurboGit but not an issue. If that was different on 4.2.1, that so means that was a bug on 4.2.1. If you want just one of those modules auto-applied, just deactivate auto-apply checkbox on the other preset.

**Comment by ctouz** [comment] 2023-07-02 07:42
OK

**Comment by victoryforce** [comment] 2023-09-11 20:02
@ctouz Please let us know if you're good to close this issue or just close it yourself.

**Closed** 2023-09-16 07:39 UTC
Labels: priority: low, understood: clear, difficulty: hard
