### ISSUE TITLE
White preset balance not saved correctly

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#13746] opened 2023-02-25 19:30 UTC
**Describe the bug/issue**

I do not use any workflow and prefer personal auto presets ones. Since this month (probably since some updates on presets in darktable), I see my white balance preset not applied as it should.

As I use presets with scene referred, I have saved a preset to auto-apply white balance to D65, bulb. But now, preset is applied to manual, not D65 (bulb icon).

I tested 2 times to delete preset and create it again. Each time, same thing. Anyway, this preset works as expected until I restart darktable.

@TurboGit: probably for you.

**Expected behavior**

Keep preset on white balance as it was saved.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : master

**Comment by TurboGit** [comment] 2023-02-25 20:10
> Anyway, this preset works as expected until I restart darktable.

You mean after creating it is works fine. You quit darktable and restart it and then the preset does not work anymore?

Given the description it seems to be a preset that that is auto-applied, right?

**Comment by TurboGit** [comment] 2023-02-25 20:15
Is the issue on the same image (or same camera) or when applied to a different camera?

**Comment by TurboGit** [comment] 2023-02-25 20:17
I'm asking as on my side it works when applied on the same camera. Have you tested with 4.2.1?

**Comment by TurboGit** [comment] 2023-02-25 20:20
My thinking is that this was already the case in 4.2.1 as IIRC (I need to check) we don't store the state of the icon on top (as-shot, user, bulb) but only the parameters. I may be wrong given your report (failing since a month or so) or I'm not fully understanding how you create your preset or use it.

**Comment by Nilvus** [comment] 2023-02-25 20:23
I didn't test on 4.2.1. I use master and this happens on master, since this month. Yes, It works fine after creating it. But when using darktable after restart, if, for example, I import images, then white balance is applied with manual setting instead of D65 one (bulb).

I use only one camera, so all my images are with same camera.

I check another thing to understand the issue but in fine, seems that my preset is not really applied on importing images, even if I have auto-apply checkbox ticked.

So instead of having:

![image](https://user-images.githubusercontent.com/45535283/221377988-f7e32f35-bd71-4add-9277-192d7904094c.png)

I have:

![image](https://user-images.githubusercontent.com/45535283/221377980-d0aecd50-f74a-4314-a934-3337a95a99da.png)

When having just above screenshot (so error and not what I want), I see on hamburger menu that my preset is not applied. If I select it, then it is applied as wanted.

Doing another test:
- click on original in history
- then compress

And with that, I have:

![image](https://user-images.githubusercontent.com/45535283/221378042-20a6badd-725f-46ef-9410-fe33ef9b6e1d.png)

**Comment by Nilvus** [comment] 2023-02-25 20:26
Oh, what is strange, is that if I compress history on original step, on an old image, already processed, white balance restore correctly on D65 (bulb) icon. But not on a newly imported image with only my auto-presets applied (like explained on previous comment).

Seems quite a tricky and strange issue.

**Comment by Nilvus** [comment] 2023-02-25 20:36
Of course, this white balance issue only apply when not having any workflow set on darktable preferences. When having that, we simply want to apply a auto white balance preset as it was set, on importing images, or reset existing image by compress history on original step.

I tested with scene-referred filmic preset and white balance works as expected. As I see that my presets remains auto-applied above it, I will use it until this is fixed. Hope it will be.

**Comment by TurboGit** [comment] 2023-02-25 21:04
I have set workflow to None.

I have created:
![image](https://user-images.githubusercontent.com/467069/221379395-33ad4693-552e-4a1f-890e-16037be510d2.png)

With:
![image](https://user-images.githubusercontent.com/467069/221379409-c86657a1-8b93-4c38-ae5b-a3385b2b8255.png)

- When I delete XMP and reimport image I have the same UI for White balance.
- When I click original and compress I have the same UI for White balance.
- When I got to lighttable and reset history and double-click on the image I have the same UI.

So on my side the auto-preset is properly applied and always with the bulb selected. 

Maybe a bad integration with some other auto-presets?

**Comment by Nilvus** [comment] 2023-02-25 21:38
> With: ![image](https://user-images.githubusercontent.com/467069/221379409-c86657a1-8b93-4c38-ae5b-a3385b2b8255.png)
> 
>     * When I delete XMP and reimport image I have the same UI for White balance.
> 
>     * When I click original and compress I have the same UI for White balance.
> 
>     * When I got to lighttable and reset history and double-click on the image I have the same UI.
> 
> 
> So on my side the auto-preset is properly applied and always with the bulb selected.
> 
> Maybe a bad integration with some other auto-presets?

Did test it after restarting darktable?

And what do you mean by "Maybe a bad integration with some other auto-presets?"?

**Comment by Nilvus** [comment] 2023-02-25 21:43
I have found another way to reproduce (seems related at least):

1. have an auto-preset on white balance (here of course D65 (bulb icon))
2. on an image with white balance as D65 (bulb), change setting by clicking on another icon (anyone, I have made my first test with pencil (manual))
3. click on original step on history
4. compress
5. see that auto-preset is not applied

**Comment by TurboGit** [comment] 2023-02-26 18:19
@Nilvus : This is getting worrisome, on my side the last scenario works:

1. auto preset
![image](https://user-images.githubusercontent.com/467069/221428835-be232cd5-1ef3-45ba-87bc-3c1cd59dec25.png)

![image](https://user-images.githubusercontent.com/467069/221428846-7c46d9aa-779e-448f-9197-2669f47b5b17.png)

2. I change the preset value

![image](https://user-images.githubusercontent.com/467069/221428878-e47f7271-7741-401e-b746-9f59c7e97914.png)

3. Original just before a compress:

![image](https://user-images.githubusercontent.com/467069/221428919-ae815b84-afc2-450f-8991-96dec1b2c44e.png)

4. After compress

![image](https://user-images.githubusercontent.com/467069/221428938-5adca794-0df2-4b46-bc84-b9b4fdb96d69.png)


My preset is called "def" as seen on the screenshot.

**Comment by Nilvus** [comment] 2023-02-26 20:32
@TurboGit: with workflow to none on darktable preferences?

Could you share a screenshot of your def preset settings?

**Comment by Nilvus** [comment] 2023-02-26 20:36
I always reproduce with last steps. And even if I remove and recreate (or update) my preset. This only happens on white balance module and it's really annoying. Note that I also regularly red warning appear when updating some things on different modules for color calibration and white balance module. This is always just a refresh issue as this red warning disappear if I open/close related module (settings are of course good and that warning should not appear.

I understand that this is worrisome but all this appears too often.

**Comment by jenshannoschwalm** [comment] 2023-02-26 20:39
The integration check for this seems to fail. Could this be related?

**Comment by TurboGit** [comment] 2023-02-26 20:39
Yes with workflow set to None.

**Comment by TurboGit** [comment] 2023-02-26 20:40
My preset dialog has been put here already: https://github.com/darktable-org/darktable/issues/13746#issuecomment-1445206125

**Comment by Nilvus** [comment] 2023-02-26 20:41
A video:

[Capture vidéo du 2023-02-26 21-36-51.webm](https://user-images.githubusercontent.com/45535283/221435821-c9c78980-b5cb-43e1-a0a5-d0d9e9b65015.webm)

**Comment by TurboGit** [comment] 2023-02-26 20:41
@jenshannoschwalm 
> The integration check for this seems to fail. Could this be related?

I have no integration check failing on the nightly run testsuite. Can you clarify?

**Comment by jenshannoschwalm** [comment] 2023-02-26 20:48
You should run with -d params

**Comment by TurboGit** [comment] 2023-02-26 20:59
@Nilvus : I see that you have also the color calibration auto activated, right? Can you double check without this G9 auto-preset on this module.

**Comment by Nilvus** [comment] 2023-02-26 21:02
I tested with -d params. When applying my white balance preset (was saved to D65 (bulb icon)), it is applied again to manual setting (pencil icon). I have those lines on Terminal:

```
34,4958 [pixelpipe] [full] pipeline state changing, flag 1
    34,4958 [pixelpipe] [full] synch top history module `temperature'
    34,4958 [iop_validate_params] `temperature' failed for type "float", field: g2
    34,4958 [iop_validate_params] `temperature' failed for type "dt_iop_temperature_params_t"
    34,4959 [dt_iop_commit_params] [full] committed for temperature with hash 1536704551328759607
    34,4959 [pixelpipe] [preview] pipeline state changing, flag 1
    34,4959 [pixelpipe] [preview] synch top history module `temperature'
    34,4959 [iop_validate_params] `temperature' failed for type "float", field: g2
    34,4959 [iop_validate_params] `temperature' failed for type "dt_iop_temperature_params_t"
    34,4959 [dt_iop_commit_params] [preview] committed for temperature with hash 1536704551328759607
    34,5109 Trouble: [Calibration des couleurs] white balance error (2021-10-16-Chasse Barbier-0001.RW2 30423)
    34,5110 Trouble: [Balance des blancs] double application of white balance (2021-10-16-Chasse Barbier-0001.RW2 30423)
```

If I click on bulb icon, I have that:

```
158,0340 [pixelpipe] [full] pipeline state changing, flag 1
   158,0340 [pixelpipe] [full] synch top history module `temperature'
   158,0341 [iop_validate_params] `temperature' failed for type "float", field: g2
   158,0341 [iop_validate_params] `temperature' failed for type "dt_iop_temperature_params_t"
   158,0341 [dt_iop_commit_params] [full] committed for temperature with hash 10147683874247836710
   158,0341 [pixelpipe] [preview] pipeline state changing, flag 1
   158,0341 [pixelpipe] [preview] synch top history module `temperature'
   158,0341 [iop_validate_params] `temperature' failed for type "float", field: g2
   158,0341 [iop_validate_params] `temperature' failed for type "dt_iop_temperature_params_t"
   158,0341 [dt_iop_commit_params] [preview] committed for temperature with hash 10147683874247836710
   158,5992 [pixelpipe] [full] pipeline state changing, flag 1
   158,5992 [pixelpipe] [full] synch top history module `temperature'
   158,5992 [iop_validate_params] `temperature' failed for type "float", field: g2
   158,5992 [iop_validate_params] `temperature' failed for type "dt_iop_temperature_params_t"
   158,5992 [dt_iop_commit_params] [full] committed for temperature with hash 10147683874247836710
   158,5992 [pixelpipe] [preview] pipeline state changing, flag 1
   158,5992 [pixelpipe] [preview] synch top history module `temperature'
   158,5992 [iop_validate_params] `temperature' failed for type "float", field: g2
   158,5993 [iop_validate_params] `temperature' failed for type "dt_iop_temperature_params_t"
   158,5993 [dt_iop_commit_params] [preview] committed for temperature with hash 10147683874247836710
```

@TurboGit: will test without my auto-preset. Possible that it is related.

**Comment by Nilvus** [comment] 2023-02-26 21:04
@TurboGit: confirmed, without auto-preset on color calibration module, white balance auto-preset works as expected. If I restore auto-preset on color calibration module, issue reappears. We have something.

**Comment by TurboGit** [comment] 2023-02-26 21:20
Great! Too late for me tonight, I'll have a look at this tomorrow. If I can finally reproduce I'll work on a fix.

**Comment by TurboGit** [comment] 2023-02-27 10:10
@Nilvus : I was able to reproduce and now I understand the issue. Fact is that you are trying to do a modern color adaptation. You want white-balance to be applied and also color-calibration. This is currently checked in the code by looking at the workflow being "modern" (either with filmic or sigmoid). But here you are using `None`.

The fix is not yet clear to me. My current thinking is that we must check the history and if color-calibration is enabled we ensure that reload-default in while-balance module behave as in modern CAT.

**Comment by Nilvus** [comment] 2023-02-27 10:21
Yes, that's exactly that. I could use modern (filmic) workflow, but I have my own (different) settings for color calibration and filmic modules especially.

Code should look if white balance is enabled (when color calibration is enabled) and if it is AND with D65 (bulb icon), do not reload it and keep it as it is (with no red warning and no change on white balance. If setting on white balance is different, then behavior should remains as it is actually. Without regarding workflow enabled. Because if it's legacy workflow, there's no color calibration and white balance is not set to D65 (bulb icon).

**Comment by TurboGit** [comment] 2023-02-27 22:18
@Nilvus : Please test  #13771. TIA.

**Closed** 2023-03-01 21:23 UTC
Labels: priority: high, scope: image processing, bug: pending
