### ISSUE TITLE
Unable resize crop window after last update

### ISSUE THREAD

**Issue by MauDarktable** [darktable-org/darktable#7713] opened 2021-01-06 14:38 UTC
**Describe the bug**

After the last update I'm randomly (but often) unable to resize the crop window. Before the last update this tool was working properly.

**To Reproduce**

1. Go to crop and rotate
2. Click on any margin or corner of the crop window and drag... the window does not resize...
3. Tried about 22 times in a row... the 23rd try make the window resizable withous reasons... the number of triyng is absolute random time per time...

**Expected behavior**

The crop window is resizable by using mouse.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10 Pro 10.0.19042 build 19042

**Additional context**

I've tried to re-install the software but the problem still persist.

**Comment by ralfbrown** [comment] 2021-01-06 14:53
Are you really using 3.2.1?  3.4 has been out for about two weeks now, and has lots of fixes.

**Comment by chhil** [comment] 2021-01-06 14:53
I have experienced this during the dev versions I was using before the 3.4 release. I don't see it in current master.

**Comment by MauDarktable** [comment] 2021-01-06 14:57
Sorry Ralf, I've updated to 3.4 but the problem still persist. Thanks for your help!

Inviato da smartphone Android
________________________________

**Comment by MauDarktable** [comment] 2021-01-06 14:58
HI Murtuza, just updated to 3.4 but the problem still persist. Thanks for your help!

Inviato da smartphone Android
________________________________

**Comment by TurboGit** [comment] 2021-01-06 15:22
For the record I have also been experiencing this from time to time but was never able to reproduce reliably so impossible to fix at the moment. Looks like some issue (non synchronized) between module having focus & enabled. Recently I had no control lines and by disabling the module they get displayed.

**Comment by MauDarktable** [comment] 2021-01-06 15:48
Guys... it's horrible... this is the most used tool for me... I have to try about 20 times before I can crop any file... please help me to fix this because this make Darktable really unusable... thanks!

**Comment by MauDarktable** [comment] 2021-01-06 15:53
If I use the cursors in the "margins" tab I'm able to resize... the same thing using margins of the crop window doesn't work...

**Comment by TurboGit** [comment] 2021-01-06 16:42
> Guys... it's horrible...

Sure we all agree about this, but we need a reproducer to be able to understand and fix this.

**Comment by MauDarktable** [comment] 2021-01-06 17:44
Ok, I can provide any information that you need or, if you want, I can provide a remote access to my pc to examine the problem. Say me what I have to do. Thanks.

Inviato da smartphone Android
________________________________

**Comment by chhil** [comment] 2021-01-06 17:59
I used to get around it by resetting the crop module or changing the croo ratios in the drop down.

**Comment by MauDarktable** [comment] 2021-01-06 18:28
> I used to get around it by resetting the crop module or changing the croo ratios in the drop down.

Hi Chhil, I've tried to reset, but the problem still persist. Tried with every single option available in this module too but still persist... Tried to disable/enable the module... the only workaround that allow me to resize is by using cursors in the margins tab, but it's very unconfortable to use...

**Comment by TurboGit** [comment] 2021-01-06 18:31
Please give as much information as possible. Is that on each image ? Some ? Depends on orientation ? RAW ? Jpeg ? Everything that could help tracking this done... some patterns...

Today I have developed around 200 images, a single issue with crop when the line did not appears. I have collapsed and reopened the module and that was ok. So it is very rare on my side.

**Comment by TurboGit** [comment] 2021-01-06 18:41
Also do you see the active area to resize being highlighted when moving the cursor close to them ?

**Comment by MauDarktable** [comment] 2021-01-06 19:07
> Please give as much information as possible. Is that on each image ? Some ? Depends on orientation ? RAW ? Jpeg ? Everything that could help tracking this done... some patterns...
> 
> Today I have developed around 200 images, a single issue with crop when the line did not appears. I have collapsed and reopened the module and that was ok. So it is very rare on my side.

Hi TurboGit,
- on each image
- Don't depend on orientation
- RAW, I'm working on NEF files
I'll make an share with you on this forum a video to show the problem, gime me some times to record it. Thanks a lot.

**Comment by MauDarktable** [comment] 2021-01-06 19:11
> Also do you see the active area to resize being highlighted when moving the cursor close to them ?

I activate the crom and rotate module
Move the cursor on a crom margin, I can see them
Click on one of them, now I can see the size of the crop in pixels in the center of the image
If I drag to reduce the size of the crop windows nothing appear... but the cursor is in "crop modality"
If I release the mouse button the cursor return to normal, no modification tho the crop
I've tried to repeat in a row on each margin... randomly some margine allow me to resize the crop window correctly... but it'a absolutely random... on 30 triying only 2 or 3 try works...

**Comment by TurboGit** [comment] 2021-01-06 22:07
I don't like Windows, but it would be too easy to incriminate Windows here as this is the first report of so bad working crop&rotate module. So maybe a problem with something installed on your Windows ? Have you tried on another machine ? Maybe deactivate some anti-virus or whatever as we had report about issues with those. I won't be able to help a lot as I'm not using Windows at all, but having more information will help to understand what could be going wrong.

**Comment by chhil** [comment] 2021-01-07 01:25
Just tried it on the windows install and this is how get around it.
I think I read it in one of the issues related to cropping here in github how a user got around it (its from memory but its listed).

When you press a corner to drag, don't drag immediately. Keep the mouse pressed for 2 seconds and then drag.

**Comment by chhil** [comment] 2021-01-07 01:31
Reproducer on windows. Note the mouse yellow dots.



![ImageCropNotWorking](https://user-images.githubusercontent.com/1119439/103839656-e7037c00-50b5-11eb-8d03-b38f6adf3e40.gif)

**Comment by MauDarktable** [comment] 2021-01-07 07:46
> I don't like Windows, but it would be too easy to incriminate Windows here as this is the first report of so bad working crop&rotate module. So maybe a problem with something installed on your Windows ? Have you tried on another machine ? Maybe deactivate some anti-virus or whatever as we had report about issues with those. I won't be able to help a lot as I'm not using Windows at all, but having more information will help to understand what could be going wrong.

I'm System Engineer Senior on Microsoft environment. I found the same problem on three different PCs. I haven't make significant modification to the system from Darktable with crop and rotate tool works perfectly to now.

**Comment by MauDarktable** [comment] 2021-01-07 07:50
> Just tried it on the windows install and this is how get around it. Using 3.5.0+147~gc50d2af91.
> I think I read it in one of the issues related to cropping here in github how a user got around it (its from memory but its listed).
> 
> When you press a corner to drag, don't drag immediately. Keep the mouse pressed for 2 seconds and then drag or wait for the dimensions to appear on the screen in a grey box.

Hi Chhil, you're a genius!!! I confirm that the workaround works perfectly! It's the same fo me...

**Comment by MStraeten** [comment] 2021-01-07 07:53
please check if the behaviour just happens if you’re using histogram in waveform mode. If so it might be similar to https://github.com/darktable-org/darktable/issues/7307

**Comment by MauDarktable** [comment] 2021-01-07 08:07
> please check if the behaviour just happens if you’re using histogram in waveform mode. If so it might be similar to #7307

No, I'm using the regular histogram, thanks.

**Comment by TurboGit** [comment] 2021-01-07 08:09
> I found the same problem on three different PCs.

Ok. About the 2s delay to grad the active corners, could be a Gtk issue or because the computer is slow ? What is the processor ? Have your tried without OpenCL ? Maybe related to an issue with Intel OpenCL slowing down the process....

**Comment by MStraeten** [comment] 2021-01-07 08:11
Than please run `darktable -d perf ` to get hints where the delay results from.

**Comment by MauDarktable** [comment] 2021-01-07 08:44
> > I found the same problem on three different PCs.
> 
> Ok. About the 2s delay to grad the active corners, could be a Gtk issue or because the computer is slow ? What is the processor ? Have your tried without OpenCL ? Maybe related to an issue with Intel OpenCL slowing down the process....

Intel Core i5-4210M CPU @ 2.60GHz, 16GB RAM, HD SSD. Just tried without OpenCL... it seems to work fine!

**Comment by TurboGit** [comment] 2021-01-07 08:53
> Intel Core i5-4210M CPU @ 2.60GHz, 16GB RAM, HD SSD.

Should be ok.

> Just tried without OpenCL... it seems to work fine!

Again an Intel OpenCL issue on Windows :( Sometime I'm really tempted to again blacklist all Intel GPU, this is draining our resources, we have really too many issued with those!

**Comment by chhil** [comment] 2021-01-07 09:20
I don't have opencl on my windows box.

**Comment by MStraeten** [comment] 2021-01-07 09:34
then please check also if you can reproduce this with standard histogram- your screenshot shows the waveform histogram

**Comment by chhil** [comment] 2021-01-07 10:29
Waveform or histogram, doesn't matter.

**Comment by chhil** [comment] 2021-01-07 10:36
Hardware i7 2.8Ghz 32 GB RAM.

**Comment by paolodepetrillo** [comment] 2021-01-29 06:24
I just noticed this issue today. I am running 3.5.0+854~gd1f0242fa on Arch Linux.
Core i7 5820K 3.3GHz, 16GB RAM, SSD, GTX 1080 opencl. Also happens with opencl disabled.
Clicking the border and immediately dragging doesn't always work, but clicking, holding for a second, and then dragging does work every time. It is intermittent, sometimes clicking and immediately dragging is successful.

**Comment by hyphone** [comment] 2021-02-20 22:52
I also have a similar but it seems different problem.
Sometimes I can't resize at all.

https://user-images.githubusercontent.com/6410852/108610546-a5fdc780-73d6-11eb-9ec7-86053a6f575c.mp4

**Comment by catlee** [comment] 2021-08-12 16:40
Also hitting this with darktable 3.6.0.3 from homebrew on macOS.

**Comment by Nilvus** [comment] 2021-11-21 10:46
As crop and rotate is now deprecated for 3.8 and a new rotation and perspective is added to replace it, I close this issue. @MauDarktable : I think the best would be that you test that new module when 3.8 will be out (for Christmas) and if the issue is still there, it will be better to post a new issue. Of course, if you could already test actual master (future 3.8), it will be better as this could provide better feedback for 3.8 release.

**Closed by Nilvus** 2021-11-21 10:46 UTC
Labels: no-issue-activity
