### ISSUE TITLE
Exported jpg with sRGB (web-safe), 3.0.0rc1 embedded color profile differs from 2.6.3

### ISSUE THREAD

**Issue by hpmickey** [darktable-org/darktable#3501] opened 2019-11-20 21:44 UTC
**Description**
Jpegs exported from DT2.6.3 with the the output color profile _sRGB (web-safe)_ used to be displayed the same way in the viewer/editor (Geeqie/GIMP) independently on the _View, Color Management_ settings. Not true anymore, after upgrade to 3.0.0rc1. The re-exported image view depends on the _View, Color Management_ settings (i.e. whether the embedded profile is used or not). All this, while the _export selected_ plugin settings have the same (the default) values: _profile: image settings, intent: image settings, style: none_.

**To Reproduce**

1. backup the ~/.config/darktable and delete it
2. build and install 2.6.3
3. open darktable
4. import raw photo XYZ
5. export it (you will get darktable_exported/XYZ.jpg)
6. exit darktable
7. build and install 3.0.0rc1
8. open darktable
9. re-export the XYZ (you will get darktable_exported/XYZ_01.jpg)
10. open XYZ.jpg in Geeqie 1.4
11. switch the _View, Color Management, Use color profile_ on, then off - colors stay the same
12. open XYZ_01.jpg in Geeqie, switch the _Use color profile_ option - colors alter accordingly

Instead of Geeqie, the GIMP 2.10.x can be used, option View, _Color Management, Color-Manage this View_ (and ensure that you keep the original embedded profile while opening image).

**Expected behavior**
- DT3.0.0rc1 should be consistent with 2.6.3
- displaying the jpg exported with the _sRGB (web-safe)_ color profile option should not depend on whether the used viewer is color managed or not

**Platform**
 - OS: Fedora 30 Thirty (x86-64), kernel 5.3.11-200.fc30.x86_64

**Additional context**

Please, see also attached icc info exported by the command
`exiftool  -a -S -G0 -ColorSpace -InteropIndex -WhitePoint -PrimaryChromaticities -Gamma -ICC_Profile:all ./DSC04496.jpg > ./DSC04496.jpg.exiftool.txt` (resp. `DSC04496_01.jpg`)
- [DSC04496.jpg.exiftool.txt](https://github.com/darktable-org/darktable/files/3871392/DSC04496.jpg.exiftool.txt) - color profile data of the jpg exported from 2.6.3 (point 5. above)
- [DSC04496_01.jpg.exiftool.txt](https://github.com/darktable-org/darktable/files/3871394/DSC04496_01.jpg.exiftool.txt) - ditto, but exported from 3.0.0rc1 (point 9. above)

Well, I am not really sure whether this is a bug. However, assuming that various web browsers still have iffy color management support now in 2019, I would prefer the original behavior of DT2.6.3

**Comment by TurboGit** [comment] 2019-11-21 07:55
Could be related to a4af6b603.

**Comment by TurboGit** [comment] 2019-11-21 13:00
In fact no, it is not due to the commit above. So if you can bisect the wrong commit it would be nice.

**Comment by TurboGit** [comment] 2019-11-21 13:22
This is probably because the profile is embedded in 3.0. I did the wrong testing before.

So all in all, it seems better to me to have embedded profile, no?

**Comment by TurboGit** [comment] 2019-11-21 13:28
Can you test the following jpeg with Geeqie?

![Raw_partie3_pap2_07](https://user-images.githubusercontent.com/467069/69342079-14e7f000-0c6b-11ea-831a-c3409a1e8c84.jpg)

**Comment by hpmickey** [comment] 2019-11-21 19:43
Hello, this looks good to me. Geeqie displays it all the same, regardless of the _View, Color Management, Use color_ profile setting. Moreover, in the
[69342079-14e7f000-0c6b-11ea-831a-c3409a1e8c84.jpg.exiftool.txt](https://github.com/darktable-org/darktable/files/3876406/69342079-14e7f000-0c6b-11ea-831a-c3409a1e8c84.jpg.exiftool.txt) dump is a line:
`[ICC_Profile] CMMFlags: Not Embedded, Independent`
like in the "good" one exported from DT2.6.3.
Note well, that the "wrong" one in OP contained:
`[ICC_Profile] CMMFlags: Embedded, Independent`

I would say: solved.
(unfortunately I am no expert in color management so please take my comments with a grain of salt...)

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2019-11-21 20:14
I can confirm that a DT3 exported jpg looks different in **xnview** (Win10) if it's option "use embedded icc" is on.

![Bild1](https://user-images.githubusercontent.com/57685590/69373272-be4ad800-0ca3-11ea-9bbb-2a7696b79ea5.jpg)

**Comment by junkyardsparkle** [comment] 2019-11-21 23:54
@TurboGit Even after that commit, the difference is still visible. Attached are the exiftool ICC info for old and new versions.
[srgb_2.6.3.txt](https://github.com/darktable-org/darktable/files/3877286/srgb_2.6.3.txt)
[srgb_current.txt](https://github.com/darktable-org/darktable/files/3877287/srgb_current.txt)

**Comment by TurboGit** [comment] 2019-11-22 08:00
@junkyardsparkle : Indeed! Just installed geeqie and an old 2.6.2 and I also have the color shift when enabling/disabling the color management in geeqie.

@hpmickey : Any more info? I'm tempted to reintroduce the embedded color profile.

**Comment by TurboGit** [comment] 2019-11-22 13:47
Reading some articles on the Web it seems that embedded color profile is important. So I'm really tempted to add back this.

**Comment by parafin** [comment] 2019-11-22 15:27
The effect of turning color management on/off in the viewer is affected by 2 things: color profile of the image (bundled or assumed) and display profile. I think the second one isn't taken into consideration in this bug report.
Some viewers (or rather browsers) may not do color management if picture has no ICC profile, so results indeed may differ, but the correct one is obviously when color profile is attached. So before removing it from export it would made sense to understand what is actually happening here...
One final note - I think several sRGB profiles exist out there with slight differences.

**Comment by junkyardsparkle** [comment] 2019-11-22 15:53
> One final note - I think several sRGB profiles exist out there with slight differences.

[Yes, yes there are...](https://ninedegreesbelow.com/photography/srgb-profile-comparison.html) and if you diff the two versions of the JPEG ICC info I posted above, you'll see differences.

Toggling the use of embedded profiles in geeqie is independent of toggling display color management, so we can leave that out of the picture (so to speak) for now. If I'm understanding correctly, the issue here is that there's an expectation that exporting in "web safe" sRGB means the color space used is the same one that "dumb" software will assume. I don't know how important/possible that is anymore. AFAIK major browsers, at least, respect embedded profiles.

**Comment by parafin** [comment] 2019-11-22 16:05
Original report switched on/off all color management, not just reading the profile from the file. So test cases should be constructed carefully here.

**Comment by junkyardsparkle** [comment] 2019-11-22 16:14
Indeed. Well, I was seeing the difference by toggling the *Use profile from image* setting, for whatever that's worth.

**Comment by TurboGit** [comment] 2019-11-22 16:46
> So before removing it from export it would made sense to understand what is actually happening here...

I agree with you. I have reverted to non embedded profile to be compatible with 2.6.x as I'm no expert here. I'm not sure what is happening but indeed having the profile embedded seems something wanted.

**Comment by TurboGit** [comment] 2019-11-22 17:05
@hpmickey : do you have a calibrated screen and a profile attached?

When I disable color management on GNOME I don't have color shift when activating/disabling the color management in geeqie. So I'm wondering if you are not messing the test !

**Comment by parafin** [comment] 2019-11-22 17:10
I see it the following way: if using embedded image color profile yields different results from default assumed sRGB profile, then removing the profile is definitely wrong - I assume the profile we embed is the one we're using for output color conversion, so the correct result is the one using the embedded profile. After removing the profile there's no chance the image will be rendered correctly by particular software. Therefore we need to answer 2 questions:
1). What sRGB profile do we use for output color conversion and does it match to sRGB profile other software assumes when no profile is attached to the image? This questions is complicated by the fact, that different software may have different default sRGB profiles.
2). Do we embed the same ICC profile we use for output conversion? I hope so.

**Comment by junkyardsparkle** [comment] 2019-11-22 17:24
> 1). What sRGB profile do we use for output color conversion and does it match to sRGB profile other software assumes when no profile is attached to the image? This questions is complicated by the fact, that different software may have different default sRGB profiles.

If you look at the very end of the page I linked above ("The real sRGB"), and compare the XYZ values given there with the ones in the two extracted ICC sections from 2.6.3 and current master JPEGS, you'll notice that the 2.6.3 values match closely, the new ones don't... one is a V2 profile and one is a V4. I'm not an expert on this subject either, but it certainly seems like whether embedded or not, the actual output profile *used* for "sRGB (web safe)" should probably conform to the spec. This might mean using something other than what's being used as the sRGB *working* profile.

**Comment by TurboGit** [comment] 2019-11-22 17:29
> If you look at the very end of the page I linked above ("The real sRGB"), and compare the XYZ values given there with the ones in the two extracted ICC sections from 2.6.3 and current master JPEGS, you'll notice that the 2.6.3 values match closely, the new ones don't...

@junkyardsparkle : not sure to follow, the values seems identical on master and 2.6.3:

> master

> static const cmsCIEXYZTRIPLE rec709_primaries_prequantized = {
>   {0.43603516, 0.22248840, 0.01391602},
>   {0.38511658, 0.71690369, 0.09706116},
>   {0.14305115, 0.06060791, 0.71392822}
> };

> 2.6.3

> static const cmsCIEXYZTRIPLE rec709_primaries_pre_quantized = {
>   {0.43603516, 0.22248840, 0.01391602},
>   {0.38511658, 0.71690369, 0.09706116},
>   {0.14305115, 0.06060791, 0.71392822}
> };

Or maybe you're speaking of something else?

**Comment by TurboGit** [comment] 2019-11-22 17:30
You're talking about the extracted ICC ?

**Comment by junkyardsparkle** [comment] 2019-11-22 17:33
Yes, attached again here for convenience:
[srgb_2.6.3.txt](https://github.com/darktable-org/darktable/files/3880709/srgb_2.6.3.txt)
[srgb_current.txt](https://github.com/darktable-org/darktable/files/3880710/srgb_current.txt)

**Comment by TurboGit** [comment] 2019-11-22 18:03
I see, not sure it matters, the white point is also different. The routine used not cmsCreateRGBProfile() instead of the hand crafted creation is probably creating differently the profile. Again I'm no expert, but the output of the image (I have tested sRGB, AdobeRGB, Rec709, Rec2020) are looking the same in master and 2.6.3.

**Comment by TurboGit** [comment] 2019-11-22 18:04
@parafin:
> 2). Do we embed the same ICC profile we use for output conversion? I hope so.

Yes, sure!

**Comment by TurboGit** [comment] 2019-11-22 18:05
> 1). What sRGB profile do we use for output color conversion and does it match to sRGB profile other software assumes when no profile is attached to the image? This questions is complicated by the fact, that different software may have different default sRGB profiles.

Probably not as there is many different sRGB profiles indeed. The one we use is constructed from a Rec709 primaries.

**Comment by TurboGit** [comment] 2019-11-22 19:06
The RawTherapee output is also different:

```
[MakerNotes] ColorSpace: sRGB
[ICC_Profile] ProfileCMMType: Little CMS
[ICC_Profile] ProfileVersion: 4.3.0
[ICC_Profile] ProfileClass: Display Device Profile
[ICC_Profile] ColorSpaceData: RGB
[ICC_Profile] ProfileConnectionSpace: XYZ
[ICC_Profile] ProfileDateTime: 2018:11:13 11:18:51
[ICC_Profile] ProfileFileSignature: acsp
[ICC_Profile] PrimaryPlatform: Microsoft Corporation
[ICC_Profile] CMMFlags: Not Embedded, Independent
[ICC_Profile] DeviceManufacturer: 
[ICC_Profile] DeviceModel: 
[ICC_Profile] DeviceAttributes: Reflective, Glossy, Positive, Color
[ICC_Profile] RenderingIntent: Perceptual
[ICC_Profile] ConnectionSpaceIlluminant: 0.9642 1 0.82491
[ICC_Profile] ProfileCreator: Little CMS
[ICC_Profile] ProfileID: 0
[ICC_Profile] ProfileDescription: RTv4_sRGB
[ICC_Profile] ProfileCopyright: Copyright RawTherapee 2018, CC0
[ICC_Profile] MediaWhitePoint: 0.9642 1 0.82491
[ICC_Profile] ChromaticAdaptation: 1.04788 0.02292 -0.05022 0.02959 0.99048 -0.01707 -0.00925 0.01508 0.75168
[ICC_Profile] RedMatrixColumn: 0.43604 0.22249 0.01392
[ICC_Profile] BlueMatrixColumn: 0.14305 0.06061 0.71391
[ICC_Profile] GreenMatrixColumn: 0.38512 0.7169 0.09706
[ICC_Profile] RedTRC: (Binary data 40 bytes, use -b option to extract)
[ICC_Profile] GreenTRC: (Binary data 40 bytes, use -b option to extract)
[ICC_Profile] BlueTRC: (Binary data 40 bytes, use -b option to extract)
[ICC_Profile] ChromaticityChannels: 3
[ICC_Profile] ChromaticityColorant: Unknown (0)
[ICC_Profile] ChromaticityChannel1: 0.64 0.33
[ICC_Profile] ChromaticityChannel2: 0.3 0.60001
[ICC_Profile] ChromaticityChannel3: 0.14999 0.06
[ICC_Profile] DeviceMfgDesc: RawTherapee
```
Note that in master I have the exact same MediaWhitePoint.

**Comment by hpmickey** [comment] 2019-11-22 21:25
Arghhh, I knew I should not have touched the color management ;)

First of all, thank you all for the effort, and sorry, gentlemen, I am quite busy recently, so it took me some time to reach the bug I had assumed it was already closed.

First, I'd like to repeat and emphasize some personal findings:
1. I am no expert in color management (and after reading some discussions about the topic, I have no intention to become to be one ever)
2. DT3.0.0rc1 behavior differs from DT2.6.3 behavior
3. the 2.6.3 _sRGB (web-safe)_ output was more "me, all soccer moms, and my father in law" friendly - we all did not need to care about fiddling with jpeg view options to display picture exported from DT (actually, I do care a bit, for the others mentioned. Hence I found the discrepancy, and opened the issue)
4. the image viewer color management support is not all that common yet, especially at mobile devices (source: [Web Browsers and Colour Management](https://imagescience.com.au/knowledge/web-browsers-and-colour-management))

Now for the questions:
> @hpmickey : Any more info? I'm tempted to reintroduce the embedded color profile.

 well, I might overlook some subtle color differences when examining the giraffes photo. The histogram is always the same (as it displays the "input" image, in Geeqie), so I had to rely on my eyes. In OP, I used the DSC04496.ARW with a saturated blue sky (attached in other issue: [DT-2.6.3-to-3.0.0rc1-different-color-response.7z](https://www.dropbox.com/s/p8yb1b8s7fo9k4d/DT-2.6.3-to-3.0.0rc1-different-color-response.7z?dl=0), but processed as described in OP here)

> @hpmickey : do you have a calibrated screen and a profile attached?
 
currently not, and intentionally, because: I view the two exported jpegs in the same viewer, same user account, same OS, same everything, except the jpegs. The 2.6.3 version does not change, while the 3.0.0rc1 do. I think (unfortunatelly do not know for 100% sure) the screen profile has nothing to do with the test.

I see it the same way as @junkyardsparkle better summarized in [here](https://github.com/darktable-org/darktable/issues/3501#issuecomment-557586632):
> Toggling the use of embedded profiles in geeqie is independent of toggling display color management, so we can leave that out of the picture (so to speak) for now. If I'm understanding correctly, the issue here is that there's an expectation that exporting in "web safe" sRGB means the profile used is the same one that "dumb" software will assume

but my opinion differs about this:
> AFAIK major browsers, at least, respect embedded profiles

imo the vast majority of browsers is installed at mobile phones and tablets and they are not managed at all (see the link at point 4. above, pls). Not to mention all the soccer moms again, who think that color management is an insult, but clearly notice that the images I posted them suddenly look weird

Well, I would really like to help better, but with my lack of knowledge of CM it is quite difficult. Maybe this could help - the exiftool output line:
DT2.6.3 and RawTherapee 5.7 (correct behavior, imo)
`[ICC_Profile] CMMFlags: Not Embedded, Independent`
DT3.0.0rc1 (incorect behavior, imo)
`ICC_Profile] CMMFlags: Embedded, Independent`
If you give me an option to get output with the `Not Embedded`, I believe I am fine (hopefully ;) ). And it does not have to be called _sRGB (web-safe)_ if the name is reserved for other purposes.

**Comment by junkyardsparkle** [comment] 2019-11-22 21:59
> If you give me an option to get output with the Not Embedded, I believe I am fine (hopefully ;) ). And it does not have to be called sRGB (web-safe) if the name is reserved for other purposes.

Well, maybe... but again only if the actual profile applied closely matches the "official" sRGB spec (note that the RawTherapee version posted by @TurboGit seems saner in this regard, at least for the primaries, which resemble the dt 2.6.3 ones and others).

>I see, not sure it matters, the white point is also different. The routine used not cmsCreateRGBProfile() instead of the hand crafted creation is probably creating differently the profile. Again I'm no expert, but the output of the image (I have tested sRGB, AdobeRGB, Rec709, Rec2020) are looking the same in master and 2.6.3.

Yes, the output will always be ok when the software involved can correctly make use of correctly assigned profiles... but the whole point of "web safe" is that it's supposed to be ok even when that isn't the case, and you can't tell the application anything about the *applied* profile. That's the reason for continuing to *apply* a "web safe" profile that matches the legacy assumptions, *whether you embed it or not*. So it's not really a question of embedding or not, but being strict about the profile itself.

FWIW, I found the weirdness in the current version to be most easily visible in images with large bright areas in the red-magenta range... some of the differences there were not subtle. :-)

**Comment by junkyardsparkle** [comment] 2019-11-22 22:57
Here's an example of the effect of on saturated reds, first is with the profile being assigned, second is what a "dumb" application (apparently there still are some out there!) will render.

![screenshot-1574462802](https://user-images.githubusercontent.com/4522189/69466198-36fb7400-0d38-11ea-9698-d8a2bac9f4e4.png)

![screenshot-1574462844](https://user-images.githubusercontent.com/4522189/69466199-37940a80-0d38-11ea-9f6a-89d7a6ddb5df.png)

**Comment by TurboGit** [comment] 2019-11-22 23:01
I don't see a difference :( Maybe we need a screenshot of both image at the same time.

**Comment by junkyardsparkle** [comment] 2019-11-22 23:03
Can you open each in its own browser tab and A/B them? That's the quick'n'dirty visual diff method.

**Comment by junkyardsparkle** [comment] 2019-11-23 02:27
Here are the respective correct, incorrect, and unenhanced diff from a color target shot.

![colorchart_good](https://user-images.githubusercontent.com/4522189/69471547-5fde3200-0d55-11ea-8824-93f79692c9fd.png)
![colorchart_bad](https://user-images.githubusercontent.com/4522189/69471552-6a003080-0d55-11ea-8223-c4801f67f3a6.png)
![colorchart_diff](https://user-images.githubusercontent.com/4522189/69471557-71273e80-0d55-11ea-9856-5240ca1ab359.png)

**Comment by TurboGit** [comment] 2019-11-23 09:19
@junkyardsparkle : thanks but I'm wondering if we are not shifting the issue. The OP had a diff with geeqie whit and without using the profile info. Here the diff in the output between 2.6 and 3.0 could well be due to the new pipe engine which color managed (not using Lab all the time).

**Comment by TurboGit** [comment] 2019-11-23 09:29
@junkyardsparkle : can you tests the branch "colorspaces-263" and check if you see the diff too?

This is 3.0.0 with the color-spaces as created in 2.6.3 (with broken ProPhoto RGB).

**Comment by junkyardsparkle** [comment] 2019-11-23 09:31
The issue isn't really between 2.6 and 3.0, it just happened to become apparent because something that was working in 2.6 isn't working anymore in 3.0. The issue is that the profile being applied as "web safe" sRGB doesn't actually conform to that specification, therefore it doesn't do what that specification was created to do: match the default assumptions so that the results are the same if the profile information in the image is used or if it isn't. That's the whole reason for using that profile instead of a wider-gamut one. In recent years, this situation applies in fewer places, but as the OP pointed out, it's still an issue.

**Comment by junkyardsparkle** [comment] 2019-11-23 09:37
> can you tests the branch "colorspaces-263" and check if you see the diff too?

I will, but it might not be in the next 12 hours or so. A quick sanity check would be to look at the primaries in an exported JPEG and see if they are ~= the "official" ones, like everybody else does.

**Comment by TurboGit** [comment] 2019-11-23 09:53
Yes the primaries in the JPEG are equal to official.

**Comment by junkyardsparkle** [comment] 2019-11-23 09:54
>  Here the diff in the output between 2.6 and 3.0 could well be due to the new pipe engine which color managed (not using Lab all the time).

I'm sorry, I'm tired and should have responded to this first: those diffs are not from different darktable versions, they are the difference between the "smart" and "dumb" mode in geeqie as the OP used, which simulates what happens in "dumb" web browsers, etc.

**Comment by junkyardsparkle** [comment] 2019-11-23 10:02
> Yes the primaries in the JPEG are equal to official.

Well, I would guess they'll work as expected, but again, I'm no expert here, and I'm not sure about the importance of things like the white point (which RawTherapee version has the same as 3.0... this may be related to V4 instead of V2, but again, I don't really know). Somebody who *is* an expert on this could probably clear this up very easily. :-)

**Comment by TurboGit** [comment] 2019-11-23 10:55
Ok, I have just pushed a fix in master using pure primaries and in this case I do get the exact same RGB matrix in the exported jpeg than in RawTherapee or in 2.6.3. I think this is the proper fix, the prequantized primaries we add in colorspaces.c where probably not ok to be used with the new high level LittleCMS API.

**Comment by junkyardsparkle** [comment] 2019-11-23 16:22
Only had time for a quick check, but the exported results look good now visually, anyway... thanks for enduring all the discussion. :-)

> I think this is the proper fix, the prequantized primaries we had in colorspaces.c where probably not ok to be used with the new high level LittleCMS API.

I'm curious about that. If I can, I'll try to spend some time in the next days updating my understanding of this stuff.

**Comment by TurboGit** [comment] 2019-11-27 09:31
This is now fixed, closing.

**Closed by TurboGit** 2019-11-27 09:31 UTC
Labels: bug
