### ISSUE TITLE
Crash when trying to use crop and rotate from quick access panel

### ISSUE THREAD

**Issue by Odud** [darktable-org/darktable#9812] opened 2021-08-15 09:09 UTC
**Describe the bug/issue**

Crash when trying to use crop and rotate from quick access panel

**To Reproduce**
Select an image
Go into darkroom
Select quick access panel
Turn on crop and rotate

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : Win10 (21H1 with latest recommended quality updates)
* Memory            :  16GB
* Graphics card     :  Nvidia GeForce GTX 1660
* Graphics driver   :  Latest
* OpenCL installed  :  Yes
* OpenCL activated  :  Yes

[darktable_bt_CK0B80.txt](https://github.com/darktable-org/darktable/files/6987833/darktable_bt_CK0B80.txt)

**Comment by jenshannoschwalm** [comment] 2021-08-15 10:04
Please use and try latest dt 3.6

**Comment by johnny-bit** [comment] 2021-08-15 18:43
@Odud - when filling up issue template please correctly state used darktable version.

your backtrace shows that you're using 3.6.0. The issue you're facing is a duplicate of https://github.com/darktable-org/darktable/issues/9432 and is already fixed with https://github.com/darktable-org/darktable/pull/9410 

the fix will be a part of 3.6.1 release

in the mean time there's a workaround described here: https://github.com/darktable-org/darktable/issues/9432#issuecomment-875650898

**Comment by Odud** [comment] 2021-08-16 08:14
Thanks for this workaround. Apologies for raising a duplicate and missing
out the version I was using.

*Pete Barlow*

**Comment by johnny-bit** [comment] 2021-08-16 08:22
OK, no problem! Closing then and I hope 3.6.1 fixes all the issues for you.

**Closed by johnny-bit** 2021-08-16 08:22 UTC
Labels: duplicate, bug: fixed
