### ISSUE TITLE
Crop module (3.6) does not remove crop handles when deactivated in not expanded state

### ISSUE THREAD

**Issue by Konzertheld** [darktable-org/darktable#9565] opened 2021-07-19 01:07 UTC
**Introduction**
Follow-up to #7978 

**Did you buy darktable from an application store ?**
no

**Describe the bug/issue**
Crop handles to not disappear when crop module is deactivated (the new one, not crop & rotate) when the module is not expanded (shown). Crop is not applied when I chose another photo but need to expand and un-expand to reset the view to normal without changing the photo.

**To Reproduce**
1. Activate Crop module via click or shortcut
2. Deactivate Crop module via click or shortcut

**Expected behavior**
Crop handles disappeared, no crop applied

**Screenshots**
![Bildschirmfoto vom 2021-07-19 03-03-35](https://user-images.githubusercontent.com/505380/126088592-44a38caf-81e2-4be8-afe4-ed67f34eb0b9.png)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.0
* OS                : Linux on Kernel 5.13.1
* Linux - Distro    : Manjaro
* Memory            : 16 GB
* Graphics card     : AMD Radeon RX 570
* Graphics driver   : open
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : no
* Desktop           : Gnome 40

**Additional context**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - Do you use lua scripts? no

**Comment by elstoc** [comment] 2021-07-19 08:59
The crop module is supposed to show its guides when the module has focus - it doesn't matter whether it is enabled or not. In this case, your screenshot indicates that the module does have focus (you can tell by the slight shading behind the on/off toggle) so this is working as intended. 

The question is: how does the module still have focus after you've collapsed it? Could you clarify how you are activating/deactivating the module because I cannot reproduce this issue in current master.

**Comment by Konzertheld** [comment] 2021-07-19 14:24
@elstoc Thanks for your answer. You are right about the focus. The module does not keep focus when I expand and collapse it. It does get and keep focus though when I activate and deactivate it in collapsed state. I looked closer and noticed that this only happens when using a hotkey, not when clicking the on/off toggle. Also, activating / deactivating another module using the on/off toggle does not move the focus but using a hotkey does. Expanding any other module also moves focus (collapsing another module does not). Note that I use "activate" hotkeys, not "move focus" hotkeys (though I understand those better now).

I guess moving focus to the activated module when activating a module makes sense. It is confusing though that a) the on/off toggle does not behave the same as the hotkey, b) the hotkey does draw focus to the module when activating but not give focus away when deactivating while c) the "move focus" hotkey does move focus in both directions. Also d) the hotkey is named "activate", not "activate and focus", which is probably why I did not understand that focus is the relevant thing here.

**Comment by elstoc** [comment] 2021-07-19 14:35
Ok I do reproduce this using a keyboard shortcut. Focus should not normally change when enabling/disabling modules so the fix would be to amend the keyboard shortcut to not do this any more. Usually you want focus in order to interact with a module and you'd normally need to expand it and/or click on a module control (either of which should give the module focus).

However, since all of the keyboard shortcut functionality is being rewritten in darktable 3.8, it might not be worth looking at this issue now (I'm not sure it warrants inclusion in a 3.6.x release). We'll leave it open in case somebody wants to tackle it but right now it could _only_ be fixed in the 3.6.x branch (not in master).

**Comment by Konzertheld** [comment] 2021-07-19 14:38
Alright, thanks for the clarification. I'll use the "move focus" keyboard shortcut until changes are made. As the crop module activates itself automatically once I select a crop area, that's perfectly fine for me.

**Closed** 2022-02-01 17:53 UTC
Labels: no-issue-activity
