### ISSUE TITLE
FR: Quick Access panel: order of widget according to iop instead of alphabetical order

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9739] opened 2021-08-05 20:04 UTC
if i add some sliders of colorbalance rgb to the quick access panel these are ordered alphabetically. 
In my opinion it makes more sense to keep the order of the original module since this order makes sense ;)

**Alternatives**
make the order of widgets customizable (more effort to allow users to get the same result)

**Comment by AlicVB** [comment] 2021-09-22 18:24
Sorry the delay... I can confirm the issue... it was working in 3.6.x thought...

@dterrahe : I fear I have again to ask for your help as it may be another side effect of your work on shortcuts... (sorry, I fell I'm offloading the work on you each time...)
iirc, before, the shortcuts (and so the QAP widgets) where stored in the order they have been defined in module `gui_init` but something may have changed here...

**Comment by dterrahe** [comment] 2021-09-22 19:22
If it worked in 3.6.x, it is most likely that I did break this, yes. I have to go back and remember what I did...

**Comment by AlicVB** [comment] 2021-09-22 19:35
I know the problem :) Thanks !

**Comment by AlicVB** [comment] 2021-11-04 21:12
@dterrahe : little up to be sure you don't forget this one ;)

I've tried to find the root cause, and I would say that it comes from : https://github.com/darktable-org/darktable/blob/669ed6b889afe0527da4b1839bbea7d32f38904b/src/gui/accelerators.c#L3642
iiuc this automatically store the widgets list in alphabetic order, right ? That would mean that the "real" widget order set in `gui_init` is not store anymore...
From there, I'm not sure how to solve the issue... should we add a new param to `dt_action_t` in order to keep a trace of this order ? but then I'm not sure how we can keep the track of this position...

**Comment by dterrahe** [comment] 2021-11-05 12:49
@AlicVB I'm sorry I misinterpreted your last message from Sep 22 and thought you had a fix for this. I also misread the bug itself (thinking that the order of the modules in QAP was wrong rather than the widgets within the module). All of this because I have very little time to spend on dt these days.

You are right; the order of the widgets is lost by the automatic alphabetic ordering in the action list creation. But especially in the case of complex modules with multiple notebook pages, the order in which the widgets are created is sometimes somewhat arbitrary anyway (and can happen in a different sequence than how widgets are shown). So it would probably be best to follow @MStraeten's alternative suggestion to make the order of the widgets customizable.

That means reparenting them in the order of the QAP stored list, rather than the order of the module's action list (which I think is what happens now, but I haven't checked). Would you be able to look at this and see if that would fix it for existing QAPs?

Eventually making widget order customizable by dragging them around would be nice, but initially they could just be kept in the order they were added. It is very easy to rebuild the QAP list for a module by ctrl-clicking on them in shortcut mapping mode and this is not something that most people do all the time, so I'd say for 3.8 that would be "good enough"?

I'm writing this without access to a dev environment, so please forgive me if I'm getting all of this wrong...

**Comment by AlicVB** [comment] 2021-11-05 18:11
thanks for your answer (and sorry for my bad english). I'll try to solve this issue then, no problem !

I'm not a great fan of the customizable order : usually, modules widgets order is done on purpose, so I would prefer to keep that. Eventually user defined order can happen *after* that...
That said, I agree that sometimes widget initialization order is not the right one either...

I have some ideas how to do that... let's try and find an "as unintrusive as possible" solution !

**Comment by AlicVB** [comment] 2021-11-05 22:31
@dterrahe @MStraeten : PR #10340 should fix it by retrieving the "real" widgets order as shown in the ui (not as defined in gui_init)

**Closed** 2021-11-08 06:54 UTC
Labels: feature: enhancement, scope: UI
