### ISSUE TITLE
Drag and drop image onto lighttable stopped working on nightly build

### ISSUE THREAD

**Issue by pejax** [darktable-org/darktable#17793] opened 2024-11-08 09:57 UTC
### Describe the bug

See title

### Steps to reproduce

Drag and drop an image file onto Lighttable. There is no plus-sign in the ghost image and dropping does nothing.

### Expected behavior

darktable should accept the image file.

### Commit

Not sure

### Where did you obtain darktable from?

GitHub nightly

### darktable version

4.9.0+1040~gd27e50b7d6

### What OS are you using?

Mac

### What is the version of your OS?

macOS Sequoia 15.1

### Describe your system?

Mac Studio M1 Ultra 64Gb

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

M1

**Comment by pehar1** [comment] 2024-11-08 14:26
Cannot reproduce with self build 4.9.0+1040~gd27e50b7d6 on Ubuntu 24.04 (fresh `.config`)

**Comment by victoryforce** [comment] 2024-11-08 14:44
I can't reproduce it in Windows either. The problem seems to be specific to macOS.

**Comment by zisoft** [comment] 2024-11-08 16:19
Just tried and cannot reproduce either with current master on macOS 15.1

**Comment by pejax** [comment] 2024-12-11 09:23
I just checked again with the latest nightly build (4.9.0+1271~g0acaaab617) - it is back working.

**Comment by victoryforce** [comment] 2024-12-11 09:39
Good to hear! So I'm closing the issue.

**Closed by victoryforce** 2024-12-11 09:39 UTC
Labels: reproduce: peculiar, scope: macos support
