### ISSUE TITLE
crop tool: edge drag doesn't work if mouse moves too fast

### ISSUE THREAD

**Issue by hqhoang** [darktable-org/darktable#11124] opened 2022-02-13 04:33 UTC
**Describe the bug/issue**
Not sure if it's designed intentionally, but in the "crop" module, dragging from an edge to resize the photo only works if I leave a small delay after pressing the mouse, then I can drag the mouse as fast as I want. But if I started dragging the edge too quickly, the cursor changes to the drag arrow but doesn't do anything, or moves the cropbox instead.

**To Reproduce**
1. select the "crop" tool
2. hold down the mouse at an edge area, move the mouse cursor immediately and quickly 
3. the edge of the photo doesn't move with the mouse cursor

**Expected behavior**
The edge of the photo moves with the mouse, regardless of how fast the mouse moves initially

**Platform**
* darktable version : 3.9.0+378~ge053d5ff2-dirty
* OS                : Linux - kernel 5.13.0-28-generic
* Linux - Distro    : Ubuntu 21.10
* Memory            : 16GB
* Graphics card     : RTX 3060 6GB
* Graphics driver   : 470.103.01
* OpenCL installed  : OpenCL 3.0 CUDA 
* OpenCL activated  : yes
* CMAKE_BUILD_TYPE  : Release

**Additional context**
I think I've encountered this weird behavior for a while, but didn't try to reproduce it until now. Sorry I don't know since when it's introduced, but at least it didn't happen with the old "crop and rotate" module. It seems to me that the mouse-down event triggers some calculations, and thus, I need to delay a bit for it to initiate the resize mode before I can start dragging.

**Comment by hqhoang** [comment] 2022-02-14 15:15
> @hqhoang : Can you test with latest master to see if my last change fix this on your side? TIA.

Tested 3.9.0+410~g47ee206a7-dirty, still have the same problem. If I mousedown on the edge without moving, wait for half a second, then I can jerk/move the mouse how fast I want and it will still work correctly. But if I don't wait, or if the mouse is still moving on mousedown, then it either moves the cropbox instead or doesn't do anything (although the cursor changes).

**Comment by TurboGit** [comment] 2022-02-14 15:18
I cannot reproduce, so I'm a bit in the dark, and I have almost the same config GNU/Linux, Nvidia 470.103.01-2, OpenCL. I'm on kernel 5.16 and GNU/Debian sid. But I don't think this can change anything. Maybe you Window Manager? I'm using GNOME Shell.

**Comment by hqhoang** [comment] 2022-02-14 17:58
I have gnome-shell 40.5 on Ubuntu 21.10. I pulled out my old Dell 7567 laptop with Ubuntu 20.04 (gnome-shell 3.36.9) and still have the same problem. My mouse is a Logitech G300s. Tested with another cheap non-gaming mouse and still have problem. Turning OpenCL on/off doesn't make any difference. I'll keep testing to see if I can isolate the cause, but let me know if you can think of anything else. Thanks much!

**Comment by TurboGit** [comment] 2022-02-16 08:59
Maybe I do not try to reproduce exactly as you. Can you describe precisely and step-by-step how to reproduce systematically? TIA.

**Comment by hqhoang** [comment] 2022-02-16 15:56
I'm sorry I still haven't found a way to consistently reproduce it. I found that if I make darktable busy by adding intense modules to the stack, then it seems to happen more often. I have a Ryzen 7 5800H + RTX 3060, not sure how much it was slowed down.

Here's a screen-recording just so you have an idea of what it is. About 40-70% of the times? I tested with an almost empty history, then enabled "diffuse or sharpen" with medium deblur and cranked iterations to 68.

https://youtu.be/fFqLrbJO-XU

**Comment by TurboGit** [comment] 2022-02-16 18:46
@hqhoang : I see, but I don't see the time between the click and the move. Anyway... looks like some Gtk+ events not being properly handled.

**Comment by hqhoang** [comment] 2022-02-17 19:22
Let me know how I can help with further troubleshooting, I'm not experienced with debugging desktop software :-(

**Comment by geni1105** [comment] 2022-02-20 13:01
I have the same issue like described by @hqhoang. I need to wait for several seconds with the mouse button clicked, until I can start to move it reliably. Often I just get the drag cursor, but moving it around does nothing.

May be related or not 
- according to OpenCL debug output, the pixelpipe is rerun when just the mouse button is clicked inside the crop rectangle, at least I get debug out like 
464,748847 [pixelpipe_process] [preview/fast] using device -1
464,748876 [pixelpipe_process] [full] using device 0
- There's a noticeable lag after clicking the mouse button until the crop rectangle dimensions are displayed (close to a second). 
- In general moving / adjusting the crop window is very laggy and jerky, same in all modules where some kind of overlayed pattern can be moved around - gradient filter bar, tone equalizer EV picker, color calibration pattern, ... 

I'm on Mac Retina 5k, Quad-Core i5, 16 GB, AMD R9 M290X / 2GB and MacOS 11.6.4, and usual image adjusting operations are aceptably fast, about a second even with a lot of modules like diffuse/sharpen (demosaic sharpen non-AA), local contrast, tone equalizer, lens correction, denoise, ... activated. OpenCL is enabled and active.

**Comment by geni1105** [comment] 2022-02-20 13:31
More observations: 
- if a crop has been already applied, grabbing and moving the corner "too fast" actually moves the rectangle instead of resizing it, although the corner drag cursor is displayed, not the crossed move cursor
- moving the rectangle immediately after the mouse button click works all the time (although jerky)

**Comment by jec993** [comment] 2022-02-20 14:42
This issue ("crop tool: edge drag doesn't work if mouse moves too fast") also shows itself on my win11 fresh install of 3.8.1 
for me, the issue is not affected by having openCL on or off - happens regardless of openCL state.

**Comment by TurboGit** [comment] 2022-02-21 16:50
@hqhoang @jec993 @geni1105 : See #11196. If one of you can test it would be good. TIA.

**Comment by hqhoang** [comment] 2022-02-21 17:56
tested TurboGit:po/fix-crop-handles, problem fixed. Even tried flick-shotting with the mouse cursor moving while being clicked, still works. Thanks much!

**Comment by geni1105** [comment] 2022-02-21 19:06
Strange, on my side I can only crop via the sides, not via the corners anymore (see comment in the PR). Grabbing a corner always ends up with just one of the sides changed - maybe something went wrong with me pulling the PR.

**Comment by hqhoang** [comment] 2022-02-21 19:10
> Strange, on my side I can only crop via the sides, not via the corners anymore (see comment in the PR). Grabbing a corner always ends up with just one of the sides changed - maybe something went wrong with me pulling the PR.

Crap, I've never grabbed the corner, thus my test was incomplete. Can confirm that grabbing each corner only moves one edge. Sorry!

**Comment by TurboGit** [comment] 2022-02-21 22:55
> Can confirm that grabbing each corner only moves one edge. Sorry!

A step by step reproducer please. I cannot reproduce this. Since you are two having this bad issue I certainly do something different. I have tested with a portrait and landscape picture.

**Comment by hqhoang** [comment] 2022-02-21 23:22
Not sure what could be the difference :-( I did delete /opt/darktable completely before recompiling/reinstalling your branch. Here's a video of the corner issue:

https://youtu.be/shLjNCudIeQ

**Comment by TurboGit** [comment] 2022-02-22 06:47
There is huge mystery there... How is that possible that I do not see that??? Will try on another computer.

**Comment by geni1105** [comment] 2022-02-22 06:55
I put in some printouts of the "grab" variable in mouse_moved() and button(pressed) - here's the result of grabbing and trying to move the top left corner:
grab-pressed: 3
grab-moved: 3
grab-moved: 0
grab-moved: 0
grab-pressed: 3
grab-moved: 3
grab-moved: 1
grab-moved: 1
grab-moved: 1

As you can see, initially the variable takes on the correct corner value, but (while the button is being kept pressed) changes to one of the edges.

**Comment by geni1105** [comment] 2022-02-22 09:11
There's else-if conditions in mouse_moved() after line #1470 - removing the else's corrects the issue on my side.
Wondering how it could ever do a corner move, given that code?

------

else
      {
        if(g->cropping & GRAB_LEFT)
        {
          ...
        }
        else if(g->cropping & GRAB_TOP)
        {
         ...
        }
        .. ..

**Comment by TurboGit** [comment] 2022-02-22 10:32
@geni1105 : Thanks, indeed the code looks wrong. I have now fixed that. The mystery is still there, why I didn't reproduce the issue!!!! Anyway, can you test latest version? TIA.

**Comment by geni1105** [comment] 2022-02-22 11:32
Tried to test, but something weird is going on here - I can‘t get rid of the else‘s, they always show up when I switch to your branch or the PR (vs. the master is clean). 
However on the web interface, the code on your branch is also good now - why can‘t I get it to replicate locally … somewhat confusing!??

**Comment by TurboGit** [comment] 2022-02-22 11:49
I suppose you have a local branch named after my remote branch po/fix-crop-handles. So when on this branch, just do:

```
$ git fetch <myremote>
$ git reset --hard <myremote>/po/fix-crop-handles
```

But it actually depends on how you have integrated my changes locally.

**Comment by geni1105** [comment] 2022-02-22 13:32
Had some local changes (for debugging) that I needed to stash first, ...

Anyway, tested and works, thanks! :-)

**Comment by hqhoang** [comment] 2022-02-22 14:14
github had a timeout for half an hour on me, also had to delete the local branch before being able to pull again without conflict. 

Anyway, tested the corners and edges with flick-shottings, all work. Thanks!

**Closed** 2022-02-22 19:52 UTC
Labels: priority: high, understood: clear, reproduce: confirmed, difficulty: average, scope: UI, scope: codebase, bug: pending, release notes: pending

**Comment by geni1105** [comment] 2022-02-22 20:28
@TurboGit BTW, I noticed that whenever the mouse button is released (after either changing or moving the crop window), the pixelpipe is rerun, although the change is not yet committed by closing the crop module and therefore the preview is unchanged. Is this intentional?

**Comment by TurboGit** [comment] 2022-02-22 20:53
@geni1105 : The preview on top-left of the UI? Yes, it is expected as it corresponds to the whole image not yet cropped.

**Comment by TurboGit** [comment] 2022-02-22 20:54
But in another scenario we are still missing a refresh see #11197.

**Comment by jec993** [comment] 2022-02-23 00:23
Thank you.
When I learn how to compile for win, I can be of more help.

**Comment by geni1105** [comment] 2022-02-23 11:30
> @geni1105 : The preview on top-left of the UI? Yes, it is expected as it corresponds to the whole image not yet cropped.

If I interpret the debug output correctly, it is not just the navigation preview, but the full pipe. See https://github.com/darktable-org/darktable/issues/11124#issuecomment-1046232959 above. 
I am puzzled about the jerky behavior of crop (and other iops with overlaid structures, like gradient), as I cannot imagine that simply pulling the rectangle around can cause a lot of computation.

**Comment by geni1105** [comment] 2022-02-28 18:29
Found out through various hints, that the jerkiness on MacOS is due to issues of gtk3 and/or Cairo with custom monitor profiles. Switching the iMac monitor to sRGB drastically improves the responsiveness for actions like moving/changing the crop rectangle, moving the EV picker in tone equalizer etc.  

Luckily, my monitor seems to be pretty close to sRGB, as I see only small changes between sRGB and my custom profile - barely perceptible, and only in highly saturated magenta. 
Still wondering why a different monitor profile makes such a performance difference. There must be numerous translations back and forth already for simple operations like moving the crop rectangle ...?

**Comment by parafin** [comment] 2022-03-01 10:21
As far as I remember, color correction for display is handled in macOS by OS and operates in terms of surfaces. Displayed image is one such surface, so I guess whenever darktable updates its content (e.g. caused by pipeline re-run when enabling crop) some processing is taking place, slowing things down. BTW, do you use OpenCL? Color correction being done by OS might be running on GPU, and the way GPUs work it may introduce more latency than expected when multiple processing pipelines are running on it.

**Comment by geni1105** [comment] 2022-03-02 09:54
Yes, OpenCL is active. However, the slowing down simply occurs when when I resize the crop rectangle or move it around (or similar overlaid structures, like tone equalizer‘s EV picker). Pixelpipe is not re-run in this case, at least I do not see re-runs in the output of -d opencl.

I understand from cairo_quartz_surface.c (if that‘s what is being used) that the surface is created under DeviceRGB color space, meaning essentially no color management. Then color space translation must happen somewhere else - maybe DeviceRGB is assumed to be sRGB there, and it is skipped if the calibrated color space is set to sRGB? This would explain the speed-up in this case.

**Comment by parafin** [comment] 2022-03-02 13:52
it is sRGB, not monitor colorspace

**Comment by geni1105** [comment] 2022-03-05 17:25
I found that replacing the four instances of  
_...  = CGColorSpaceCreateDeviceRGB ();_
by
_... = CGDisplayCopyColorSpace(CGMainDisplayID());_
in cairo-quartz-surface.c resolves the issue. This should create the surface in the monitor's set color space, not in a generic  "device RGB" that is fixed to sRGB apparently. 
(I did not bother how to correctly set the color space for dual-monitor setup, as I use just one monitor).

I rebuilt cairo locally by (after cloning from github and patching cairo-quartz-surface.c as indicated above)
_./autogen.sh --prefix=/opt/local
make
sudo make install_
which is a bit dirty, as it copies the locally built libraries over the macports ones. But it serves the purpose ...

**Comment by parafin** [comment] 2022-03-07 09:20
Note that this way you broke color management. You need to export display's profile, put it where dt can find it and select it explicitly as monitor profile in dt.

**Comment by geni1105** [comment] 2022-03-07 14:33
Thanks for the hint - but I am not sure why I would break color management: first, I assumed (maybe wrong?) that cairo would only be used for drawing overlays like the crop rectangle, but not for the image itself. Second, in today‘s implementation cairo is always using sRBG, independent of the monitor calibration - wouldn’t that break color management even more?

**Comment by parafin** [comment] 2022-03-07 14:49
> Thanks for the hint - but I am not sure why I would break color management: first, I assumed (maybe wrong?) that cairo would only be used for drawing overlays like the crop rectangle, but not for the image itself.

As far as I know everything is rendered using cairo. Maybe I'm wrong, but I guess you could just check if image changes visually when you switch between patched and un-patched cairo.

> Second, in today‘s implementation cairo is always using sRBG, independent of the monitor calibration - wouldn’t that break color management even more?

No. macOS is using what's called full-screen color management. GTK/cairo renders everything in sRGB, which is then converted by OS to monitor's profile. Since you've changed sRGB to monitor profile, you now have to tell DT to do the conversion to this profile instead of sRGB. Of course your patched approach would give better results, since you're no longer limited to sRGB gamut.

**Comment by geni1105** [comment] 2022-03-09 21:22
I compared the patched and un-patched cairo, and I guess you are right - the patched version does not work correctly. In particular and strangely, the rendering of the patched version does not change if I switch the monitor in the system settings to a different profile - the rendered image always looks according to the output profile selected in darktable, even if I switch the monitor to completely weird color space like ACES Linear. Or is this to be expected?

The unpatched version's rendering changes with the selected system monitor profile, and always looks identical to MacOS quicklook or preview (tried out with a profile/printer evaluation image in TIF format).

I simply do not understand the logic behind the color management: the pixelpipe is mostly running in its working profile (linear Rec2020 RGB by default), then GTK/Cairo renders in sRGB (or in monitor profile, with my patch), and finally the OS transforms into the monitor profile selected in the system settings (or skips it, if it's already there). Where does the output profile come into play, that can be selected in the soft proof list?

I'm confused and think I will simply revert the patch, switch everything to sRGB and live happily ever after ... ;-)

**Comment by parafin** [comment] 2022-03-10 07:51
Soft-proof and output profile doesn't matter for this discussion - only display profile setting in darktable and monitor profile in macOS settings.

For unpatched cairo it goes like this: dt outputs image in display profile (sRGB by default and shouldn't be changed) -> cairo renders it to Quartz surface with sRGB colorspace -> macOS transforms sRGB into monitor profile selected in OS settings

For your patched cairo: dt outputs image in display profile (sRGB by default, should be changed by you to real monitor profile instead) -> cairo renders it to Quartz surface with monitor colorspace -> macOS does nothing and displays image as is on display

For unpatched cairo changing dt display profile or OS monitor profile affects how image looks (not that you should change any of those). For patched cairo changing dt display profile affects the image look the same (and should be changed to monitor profile), changing OS monitor profile doesn't affect the described conversions, but it still affects gamma correction LUTs, so still can have visible difference.

**Comment by geni1105** [comment] 2022-03-12 11:48
Thanks for the explanation, that clarifies it for me:-) 
What confused me was the behavior of the "system display profile" option that I used in the soft proof popup: it seems to always lead to sRGB, not to the display profile selected in the MacOS system settings. So I was relying on darktable automatically switching to the correct profile, if I select that option - instead I need to do it manually, like you described.

Now regarding the jerky / laggy behavior, when a profile other than sRGB is selected in the system settings: the last step "macOS transforms sRGB into monitor profile selected in OS settings" seems to be exceptionally CPU consuming for some reason, and apparently is skipped if the monitor profile == sRGB (or permanently in my patched version), hence the speedup.

BTW a big thanks to you for bringing darktable to MacOS!

**Comment by parafin** [comment] 2022-03-12 12:32
> Thanks for the explanation, that clarifies it for me:-) What confused me was the behavior of the "system display profile" option that I used in the soft proof popup: it seems to always lead to sRGB, not to the display profile selected in the MacOS system settings. So I was relying on darktable automatically switching to the correct profile, if I select that option - instead I need to do it manually, like you described.

Because it’s default value for that setting and effectively it is display profile, since OS takes care of that. Obviously dt can’t know you patched cairo.
