### ISSUE TITLE
Compress History in darkroom view does weird things

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3009] opened 2019-09-26 05:36 UTC
**Describe the bug**
Compress history in darkroom gives unpredictable results.

**To Reproduce**
See images.

**Expected behavior**
Compress should compress history to the point selected in history.

**Screenshots**
Original history
![image](https://user-images.githubusercontent.com/1119439/65660607-d5c36700-e04c-11e9-8838-d4e3822555cd.png)

Selecting Original
![image](https://user-images.githubusercontent.com/1119439/65660627-eb389100-e04c-11e9-9af5-358031dd8459.png)

Hitting compress
![image](https://user-images.githubusercontent.com/1119439/65660659-fd1a3400-e04c-11e9-9ac3-e93f49ed4c9b.png)

Selecting step 14 and then hitting compress
![image](https://user-images.githubusercontent.com/1119439/65660732-38b4fe00-e04d-11e9-8bd9-2dc5cc25ea15.png)

Now selecting 5 in history and hitting compress.
![image](https://user-images.githubusercontent.com/1119439/65660775-626e2500-e04d-11e9-85f9-4aee7c9bf0f8.png)

**Platform (please complete the following information):**
 - OS:Win 10
 - Version darktable-2.7.0+1862~g879f1e5f9-win64

Only way to reset is to discard history in lightable view.

**Comment by TurboGit** [comment] 2019-09-26 09:54
Really strange! I cannot reproduce.

**Comment by jenshannoschwalm** [comment] 2019-09-26 16:10
Might be related to #3016

**Comment by jenshannoschwalm** [comment] 2019-09-29 06:59
Could you try again with current master after removing file from database and removing xmp file?

**Comment by chhil** [comment] 2019-09-29 07:04
Couldnt reproduce on a cleandarktable-2.7.0+1898~ge37281ae4-win64.

Though an ideal test would be to upgrade from 2.6.2 to current.

**Comment by jenshannoschwalm** [comment] 2019-09-29 11:25
maybe you can close this issue for now. testing the 2.62 -> current master is ok, the problem was the iop_ordering and now that seems to be fixed.

**Comment by chhil** [comment] 2019-09-30 01:44
@jenshannoschwalm 

When you import the pic and the default history is present, you can't compress it to the original step 1 in history.
Compressing to any other point in the existing default history also shows.

Default history.
![image](https://user-images.githubusercontent.com/1119439/65843858-76699d80-e351-11e9-821b-d83e651b8ba7.png)

Selecting original
![image](https://user-images.githubusercontent.com/1119439/65843880-8bdec780-e351-11e9-93c7-99fbb980c9c0.png)

Clicking compress history
![image](https://user-images.githubusercontent.com/1119439/65843907-a4e77880-e351-11e9-931f-8966ba86b82d.png)


Then when I click step 4 
![image](https://user-images.githubusercontent.com/1119439/65843932-b9c40c00-e351-11e9-9796-e5770eebe399.png)

Click compress history
![image](https://user-images.githubusercontent.com/1119439/65843947-c9dbeb80-e351-11e9-99f0-f8210a89443e.png)

The order changes, step 4 goes to the top and some sort of rotation of the order happens.

**Comment by jenshannoschwalm** [comment] 2019-09-30 11:19
I think this is completely ok. You try to remove history items but these modules are **always** activated so they all appear again. Just the history looks _reordered_  and nothing has been removed.

This related to a number of PR's that make "always active" also "always on display"

**Comment by chhil** [comment] 2019-09-30 12:33
Even if the first case can be excused, the second one reorders, it too should do nothing .

**Comment by jenshannoschwalm** [comment] 2019-09-30 13:35
When selecting demosaic before compression all modules above that are forgotten. BUT after that the rest is forced to be inserted below. it just means possibly done changes in the modules above/later than demosaic are lost.

**Comment by chhil** [comment] 2019-10-03 04:12
The entry called Gamma, there is no module associated with it, feels odd to have a history of a non-existent module.

**Comment by jenshannoschwalm** [comment] 2019-10-21 12:45
I think this is fixed. Please concider to close issue :-)

**Closed** 2019-10-21 14:49 UTC
