### ISSUE TITLE
OSX: Liquify: liquified area is displayed as solid black

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#7349] opened 2020-12-18 09:23 UTC
the liquified area is displayed as solid black - nut just the spot or line, the whole area
![liquifyerror](https://user-images.githubusercontent.com/39386816/102597240-a483fa80-411a-11eb-8a87-30240d726541.jpg)

**To Reproduce**
1. Apply spot or line in module liquify
2. See error

**Platform (please complete the following information):**
 - Darktable Version: darktable 3.3.0+2144~gb3e73b014-dirty
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
 - OS: OSX Big Sur
 - with/without OpenCL activated

**Comment by TurboGit** [comment] 2020-12-18 09:55
Looks like a MacOS issue only, at least I cannot reproduce on GNU/Linux.

**Comment by parafin** [comment] 2020-12-18 14:06
I confirm this issue on macOS 10.14. Basically liquify is broken on macOS.

**Comment by ralfbrown** [comment] 2020-12-18 14:58
Is this on screen only or does it affect exports?

On-screen in darkroom, the areas affected by liquify are shown with a yellow overlay of very low opacity.   Your screenshot looks like the overlay is being drawn fully opaque.  What version of GTK is installed on your system?

(I can't reproduce on Linux with GTK 3.24.)

**Comment by parafin** [comment] 2020-12-18 15:12
In the preview image in darkroom these areas are rendered pure black, so I think it affects export too.

**Comment by parafin** [comment] 2020-12-18 15:14
It's black in export too (and when you close liquify tool). It's tinted in the above screenshot because of yellow overlay, as you said.
GTK version is 3.24.23 with quartz backend.

**Comment by parafin** [comment] 2020-12-18 15:15
But given it affects export, I don't see why GTK would play a role here. Processing itself is affected.

**Comment by parafin** [comment] 2020-12-18 15:16
Does anyone use clang builds on Linux? Maybe it's clang-specific bug. Do we have an integration test for liquify?

**Comment by jenshannoschwalm** [comment] 2020-12-18 15:27
Gtk includes Cairo stuff. I have seen such issues when colors for drawing were NaN.

**Comment by TurboGit** [comment] 2020-12-18 15:40
@parafin : Just tested with clang-9 on Linux and it works correctly. And yes we have two integration test for liquify.

**Comment by TurboGit** [comment] 2020-12-18 15:47
I have rebuilt everything on GNU/Linux from scratch with clang-11 now, and still no issue:

```
$ DARKTABLE_CLI=/opt/darktable/bin/darktable-cli ./run.sh --op=liquify
Test 0035-multiple-modules
      Image mire1.cr2
      CPU & GPU version differ by 1.47299e+06 pixels
      Max  dE         0.9854
  OK

Test 0036-liquify
      Image mire1.cr2
      CPU & GPU version differ by 33990 pixels
      Max  dE         0.0000
  OK


Total test 2
Errors     0
```

**Comment by TurboGit** [comment] 2020-12-18 15:53
@MStraeten : was this working on 3.0 ? on the same OS version ?

**Comment by TurboGit** [comment] 2020-12-18 15:56
BTW, this shows again that there is not enough maintainers on MacOS, at the moment I think we have a single maintainer (@parafin) committing stuff to fix MacOS issues. This can also be said for Windows. So **if some devs are reading that and are using MacOS or Windows, please help maintaining those platforms.**

**Comment by MStraeten** [comment] 2020-12-18 19:31
i checked with an older builds,  darktable 3.3.0+1993~ga5829cf6c (05.12.2020) was fine, 
next build darktable 3.3.0+2038~g0ba18ac8b (08.12.2020) shows the issue.

**Comment by johnny-bit** [comment] 2020-12-18 19:49
This gives a narrow range for bisecting the issue ;)

**Comment by MStraeten** [comment] 2020-12-18 21:10
in just need to get my macports environment working again - after an Xcode update darktable just produces segfaults ;)

**Comment by MStraeten** [comment] 2020-12-18 21:35
just rebuild darktable on windows: it's fine there

**Comment by parafin** [comment] 2020-12-18 21:37
@MStraeten, which XCode version are you using BTW?

**Comment by MStraeten** [comment] 2020-12-18 22:15
i was using 12.3 now i'm back to initial 12 and segfaults are gone - now bisecting can start

**Comment by MStraeten** [comment] 2020-12-18 22:41
```
03dd4187511351d27c061611e72f2591f0cc9f47 is the first bad commit
commit 03dd4187511351d27c061611e72f2591f0cc9f47
Author: Ralf Brown <ralfbrown@users.noreply.github.com>
Date:   Mon Dec 7 07:20:22 2020 -0500

    [performance] adjust OpenMP directives for better scaling (#7226)

    * adjust OpenMP directives for better scaling

    build_round_stamp performance is critical not just to liquify itself,
    but also any other iop following it in the pipeline using shapes, as
    distort_transform calls that function.

    On darktable-bench-3.4.xmp with 32 threads, average of two runs:
    before  after   iop
    0.071   0.064   liquify
    0.163   0.137   spot healing
    0.211   0.191   retouch (heal)
    0.470   0.443   retouch (wavelets with brush)

    Single-threaded performance is within measurement error in all cases:
    0.259  liquify
    0.328  spot
    0.383  retouch (heal)
    0.825  retouch (wavelet)

    * fix OpenMP for GCC9, inline hypotf

    Since we know we won't have overflows or denormals, using
    sqrtf(x*x+y*y) instead of hypotf(x,y) shaves off a few
    more milliseconds.

    * fill circle in quadrants instead of octants to avoid false sharing

    Performance is a dead heat single-threaded, but shows a nice speedup
    at 4 and 8 threads:

    4 threads
    master   PR   iop
    0.181  0.122  liquify
    0.412  0.183  spot removal
    0.453  0.225  retouch (heal)
    0.744  0.512  retouch (wavelets)

    8 threads
    master   PR   iop
    0.121  0.087  liquify
    0.290  0.149  spot removal
    0.325  0.183  retouch (heal)
    0.591  0.455  retouch (wavelets)

    32 threads
    master   PR   iop
    0.071  0.060  liquify
    0.160  0.111  spot removal
    0.228  0.167  retouch (heal)
    0.473  0.426  retouch (wavelets)

 src/iop/liquify.c | 105 ++++++++++++++++++++++++------------------------------
 1 file changed, 46 insertions(+), 59 deletions(-)
```

**Comment by johnny-bit** [comment] 2020-12-18 23:18
Wow... so @ralfbrown optimization speed up stuff everywhere except mac ;)

**Comment by ralfbrown** [comment] 2020-12-19 00:52
The weird thing is that the function build_round_stamp() which got changed doesn't directly modify anything in the image -- it computes offsets for shifting pixels around.  Since the code works just fine on non-Macs, we'll have to try some long-distance debugging....

First try: check whether compiler optimization is involved by making a debug build.

Second try: check whether parallelization is involved by commenting out the second _OPENMP directive in build_round_stamp() [you can just change _OPENMP to _OPENMPx for example] and see whether that changes the behavior.

**Comment by chhil** [comment] 2020-12-19 03:48
> So **if some devs are reading that and are using MacOS or Windows, please help maintaining those platforms.**

What does maintaining mean? I can help assisting with Windows from a testing perspective. Not comfortable with coding as the math seems beyond my current skillset and haven't coded in C for atleast 2 decades now ;) .  
I am trying to setup the build environment on a M1 Mac but am struggling and using pixl to interact and filing bugs at macports.  Once setup I can of course help test there too.

**Comment by TurboGit** [comment] 2020-12-19 06:43
@chhil: Maintaining means that you have a full development environment, that you can build, test, and debug darktable to find issues and propose PR. You can do that for a specific platform (Windows in your case) or tackle issues that are for all platforms as reported here. My point is that most devs around are currently on GNU/Linux and having more regular devs on MacOS and Windows will certainly help a lot having those two platforms in better shape.

**Comment by MStraeten** [comment] 2020-12-19 08:18
> First try: check whether compiler optimization is involved by making a debug build.
issue occurs using
 -DCMAKE_BUILD_TYPE=RelWithDebInfo
as well as
 -DCMAKE_BUILD_TYPE=Release
 the build with -DCMAKE_BUILD_TYPE=Debug fails very early since a long time ago :
```
/Users/martinstraeten/src/darktable_debug/src/common/darktable.h:346:49: fatal error: 'acquire_capability' attribute requires
      arguments whose type is annotated with 'capability' attribute; type here is 'dt_pthread_mutex_t'
      (aka 'struct dt_pthread_mutex_t') [-Wthread-safety-attributes]
static inline void dt_lock_image(int32_t imgid) ACQUIRE(darktable.db_image[imgid & (DT_IMAGE_DBLOCKS-1)])
                                                ^
/Users/martinstraeten/src/darktable_debug/src/external/ThreadSafetyAnalysis.h:37:33: note: expanded from macro 'ACQUIRE'
  THREAD_ANNOTATION_ATTRIBUTE__(acquire_capability(__VA_ARGS__))
                                ^
1 error generated.
make[2]: *** [bin/CMakeFiles/lib_darktable.dir/bauhaus/bauhaus.c.o] Error 1
```
is there another way to override the optimization? I build according to https://github.com/darktable-org/darktable/blob/master/packaging/macosx/BUILD.txt (but with a different deployment target)

**Comment by ralfbrown** [comment] 2020-12-19 08:51
The compile error is something a clang expert would need to look at; a quick check indicates that a workaround would be to modify src/external/ThreadSafetyAnalysis to define "THREAD_ANNOTATION_ATTRIBUTE__" as a no-op, as it is for compilers other than clang.

You can also brute-force turning off optimization by replacing the instances of "-O2" and "-O3" in src/CMakeLists.txt with "-O0" (that's a zero, for no optimizations).

**Comment by chhil** [comment] 2020-12-19 09:11
@TurboGit I will spend some time setting up a build/debug environment for windows. I had set it up long time ago with the netbeans ide had some success with it. When I got wsl working , I have primarily moved to it and run DT under linux and debug using vscode. Without further muddying this issue thread, I will progress with the windows setup and use pixl for questions/concerns/direction. Funny enough I have been trying to build DT on an M1 mac and working with macports to get it going as the existing instructions don't work as the arch is arm64 now and just one month old. ;)

Sorry for the noise.

**Comment by MStraeten** [comment] 2020-12-19 09:52
with forced -O0 it's fine

**Comment by MStraeten** [comment] 2020-12-19 10:02
this also fixes a segfault when combining liquify with a gradient mask ...

**Comment by MStraeten** [comment] 2020-12-19 10:11
second try (commenting out the second _OPENMP directive in build_round_stamp() ) is also fine (even for combination with gradient mask)

**Comment by johnny-bit** [comment] 2020-12-19 10:32
I wonder - XCode C/C++ compiling is based on Clang (so LLVM) and now i wonder wheter similar problem would exhibit on linux using LLVM11 as compiler

**Comment by TurboGit** [comment] 2020-12-19 11:51
@johnny-bit : I have tested with llvm 10 & 11 on Linux. See my message above. No problem defected.

**Comment by Mark-64** [comment] 2020-12-19 13:43
> BTW, this shows again that there is not enough maintainers on MacOS, at the moment I think we have a single maintainer (@parafin) committing stuff to fix MacOS issues. This can also be said for Windows. So **if some devs are reading that and are using MacOS or Windows, please help maintaining those platforms.**

I have a fully configured Eclipse IDE for DT on both Windows and Linux, I can help testing and debugging. I am already doing It, in the limits of my spare time 😉

**Comment by MStraeten** [comment] 2020-12-19 14:21
this issue is not reproducible on windows - at least not with my recent build

**Comment by ralfbrown** [comment] 2020-12-19 14:46
@MStraeten Odd that _both_ of the things I asked you to try fix the problem.  Optimization on/off should never change the behavior of a program unless there's a compiler bug or the programmer has violated a language rule (such as aliasing 'restrict'  pointers).  And parallelization shouldn't change results either unless there's a race condition  or a compiler bug.

What happens if instead of disabling the loop parallelization, you add "I" (the imaginary number basis) to the dt_omp_firstprivate?  That's an identifier which is defined by <complex.h>, and while neither GCC8 nor clang-8 are complaining about it not being declared in the pragma, if it has some weird value inside the loop due to optimization interacting with parallelization, that could cause the bad image data when the generated displacement values are used to select pixels..

**Comment by MStraeten** [comment] 2020-12-19 16:34
> What happens if instead of disabling the loop parallelization, you add "I" (the imaginary number basis) to the dt_omp_firstprivate?
i don’t get what you’re talking about. my programming skills are moretheless search for similar reported stuff, copy & paste ...

**Comment by ralfbrown** [comment] 2020-12-19 16:49
Just add ", I" (capital letter "eye") to the end of the dt_omp_firstprivate arglist:
```
  #ifdef _OPENMP
  #pragma omp parallel for schedule(static) default(none) \                                           
    dt_omp_firstprivate(iradius, strength, abs_strength, table_size, I)   \
    dt_omp_sharedconst(center, warp, stamp_extent, lookup_table, LOOKUP_OVERSAMPLE)
  #endif
```

**Comment by MStraeten** [comment] 2020-12-19 17:02
```
[ 88%] Building C object lib/darktable/plugins/CMakeFiles/liquify.dir/introspection_liquify.c.o
In file included from /Users/martinstraeten/src/darktable/build/lib/darktable/plugins/introspection_liquify.c:156:
/Users/martinstraeten/src/darktable/src/iop/liquify.c:926:70: fatal error: expected variable name
    dt_omp_firstprivate(iradius, strength, abs_strength, table_size, I)   \
                                                                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/complex.h:42:11: note: expanded from macro 'I'
#define I _Complex_I
          ^~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/complex.h:40:35: note: expanded from macro '_Complex_I'
#define _Complex_I (__extension__ 1.0iF)
                                  ^~~~~
/Users/martinstraeten/src/darktable/src/common/darktable.h:89:49: note: expanded from macro 'dt_omp_firstprivate'
#  define dt_omp_firstprivate(...) firstprivate(__VA_ARGS__)
                                                ^~~~~~~~~~~
1 error generated.
make[2]: *** [lib/darktable/plugins/CMakeFiles/liquify.dir/introspection_liquify.c.o] Error 1
make[1]: *** [lib/darktable/plugins/CMakeFiles/liquify.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ralfbrown** [comment] 2020-12-19 17:11
Well, that officially leaves me out of ideas right now for fixing the error without eliminating parallelization on MacOS.

Looks like #7361 is the way forward until someone comes up with something better.

**Comment by TurboGit** [comment] 2020-12-20 16:04
BTW, can't this be due to alpha channel being reset. I kind of remember some similar issue long time a ago... Not sure if it applies here, just a note.

**Comment by ralfbrown** [comment] 2020-12-20 16:29
But isn't the alpha channel only used to pass masks down the pipe for display by the gamma iop?

**Comment by TurboGit** [comment] 2020-12-20 16:42
> Besides, turning parallelization on/off should not change the contents of the alpha channel.

My idea is that it was buggy today and by chance the value was correct. With optimization on we have another order of instructions making this visible. But that's only willde guess as I find it hard to believe that such a compiler bug may exists.

**Comment by TurboGit** [comment] 2020-12-23 11:43
As a fix has been put in place now I suppose you want to close this issue?

**Comment by MStraeten** [comment] 2020-12-23 12:09
this can be closed - the quick&dirty patch is no longer required in current master (in darktable-3.4.x it’s further required)

**Comment by TurboGit** [comment] 2020-12-23 12:14
@MStraeten : Can you tell me more ? I may have missed something, why the quick&dirty fix is not needed on master anymore ?

**Comment by johnny-bit** [comment] 2020-12-23 12:14
You mean that on macos with current master you can remove `&& !defined(__APPLE__)` and have working liquify with OpenMP? but 3.4 has to have it?

**Comment by MStraeten** [comment] 2020-12-23 12:52
yes, i removed it in my current master build enviroment and it's fine (./bin/darktable --disable-opencl) 
my  `git clone -b darktable-3.4.x --single-branch https://github.com/darktable-org/darktable.git` environment need the patch.
i'm going to bisect which commit made it in current master ...

**Comment by MStraeten** [comment] 2020-12-23 13:12
it seems to be not that simple:
`-DCMAKE_BUILD_TYPE=Debug` is fine without the quick an dirty patch
`-DCMAKE_BUILD_TYPE=RelWithDebInfo' is not fine and needs the patch
(my darktable-3.4.x i built with `-DCMAKE_BUILD_TYPE=Release'

**Comment by johnny-bit** [comment] 2020-12-23 13:22
I think debug build also disables optimizations which can optimize out stuff and cause the liquify problem.

I'd say that while the openmp dirty patch "fixes" issue it might introduce performance penalty... So IMO either keep this issue open to track progress of removing dirty patch or close this issue and create new for tracking?

**Comment by MStraeten** [comment] 2020-12-23 13:49
in my opinion it’s worth to keep the quick and dirty patch for 3.4 since a lousy performance is more acceptable than black strokes. But in fact comparing Debug without path and Release with patch doesn’t indicate penalty yet.
`took 0,041 secs (0,411 CPU)` (Debug without patch)
`took 0,014 secs (0,041 CPU)` (3.4 Release with patch)
 
Maybe it makes sense to create a new issue for the different behaviour of Debug and Release Builds and disable the fix just for current master to be able to see i.

**Comment by johnny-bit** [comment] 2020-12-23 13:52
well, the penalty is 10x slowdown...

**Comment by TurboGit** [comment] 2020-12-23 14:55
Yes please open a new issue. You may want to add the reference to this one for all discussions. Please also reference the commit in master which is 3e0e655ab1996f801644db58b9cdede9929370e4.

The issue at this stage is on Apple only so probably a CLang issue when using full optimization. Worth noting all that in the new issue. TIA.

I'm closing this one.

**Closed by TurboGit** 2020-12-23 14:55 UTC

**Comment by TurboGit** [comment] 2020-12-23 14:59
Last, I'm not sure we want to remove the fix on master as it will annoy people using the dev build and reporting issues as this one is really blocking. That being said I encourage you to try from time to time to see if it got fixed or not.

What could be interesting is to try different version of CLang and see of one of them is OK. Anyway thing you can find to have a better idea about this issue will be very appreciated.

What I still don't understand is why CLang on GNU/Linux does not exhibit the issue. So there is maybe something else in the equation.

**Comment by parafin** [comment] 2020-12-23 15:03
Apple clang is modified compared to vanilla clang, so who knows what they added.

**Comment by dtorop** [comment] 2020-12-27 02:30
> What I still don't understand is why CLang on GNU/Linux does not exhibit the issue. So there is maybe something else in the equation.

The continuing mystery in all this for me: There's been OpenMP code in darktable for a while, compiled successfully with Clang for OS X. Why is it suddenly breaking in v3.4? The only pattern seems to be that newly added OpenMP code is breaking. Compiler error seems so unlikely. I'd be much more inclined to think that there's a subtle error in dt's use of OpenMP which only a certain compiler/OS combination is revealing... Or maybe I'm missing something (e.g. https://mac.r-project.org/openmp/). Did v3.4 just so happen to coincide with new build tools from Apple??

**Comment by parafin** [comment] 2020-12-27 08:42
Build tools hasn't changed, except maybe for openmp library. But since old code continues to work, that's unlikely to be the cause. I wouldn't rule out compiler bug on the other hand.

**Comment by dtorop** [comment] 2020-12-27 21:23
> Build tools hasn't changed, except maybe for openmp library. But since old code continues to work, that's unlikely to be the cause. I wouldn't rule out compiler bug on the other hand.

Is this a case for git bisect? Questions to resolve:

- Can v3.2.x compile and work with current build tools?
- Was there a commit between v.3.2.x and v3.4 which first broke things?

From the compile logs which @MStraeten sent in https://github.com/darktable-org/darktable/issues/7307#issuecomment-751449050 there are a lot of warnings such as:

```
/Users/martinstraeten/src/darktable_debug/src/libs/histogram.c:221:1: warning: loop not vectorized: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation
      ordering [-Wpass-failed=transform-warning]
#pragma omp parallel for simd default(none) \
^
```

FWIW, all of the errors in that log appear to relate to either `#pragma omp parallel for simd` or `#pragma omp simd` directives. See https://github.com/darktable-org/darktable/issues/7307#issuecomment-751513337 for a non-SIMD variant to test.
