### ISSUE TITLE
Darktable crashes when Wavelet scales slider in retouch module is adjusted above a certain value

### ISSUE THREAD

**Issue by rexbron** [darktable-org/darktable#7929] opened 2021-01-19 13:40 UTC
**Describe the bug**

When adjusting the wavelet scale above a certain value (8 for me) in the retouch module, Darktable crashes and produces a back trace. 

**To Reproduce**

1. Enable the retouch module
2. Adjust the lower slider for wavelet scales
3. Raise by one until crashing value is encountered. 

**Expected behavior**

That Darktable not crash and inform the user if there is an upper bound to wavelet scales.

**Screenshots**

![image](https://user-images.githubusercontent.com/587341/105042120-db0ea700-5a31-11eb-9323-1e7ff56e3932.png)
![image](https://user-images.githubusercontent.com/587341/105042203-f4afee80-5a31-11eb-85c6-41151c5e3067.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10
 - OpenCL activated
 -  Nvidia 1080Ti / 441.87

**Additional context**

Backtraces attachedL
[darktable_bt_5DQEX0.txt](https://github.com/darktable-org/darktable/files/5836169/darktable_bt_5DQEX0.txt)
[darktable_bt_9LLGX0.txt](https://github.com/darktable-org/darktable/files/5836175/darktable_bt_9LLGX0.txt)
[darktable_bt_AMLGX0.txt](https://github.com/darktable-org/darktable/files/5836176/darktable_bt_AMLGX0.txt)
[darktable_bt_HS0BX0.txt](https://github.com/darktable-org/darktable/files/5836177/darktable_bt_HS0BX0.txt)

**Comment by jade-nl** [comment] 2021-01-19 16:58
I'm not able to replicate this behaviour.

I've tried using darktable 3.4 (and also, just  to be sure, the latest development version).

I get a nice message saying *max scale is XX for this image size*, but I can push the slider beyond that. Tried this on a larger format image (9200x6200 - max scale 12), normal sized one (6000x4000 - max scale 11) and a smaller one (2500x1700 - max scale 10).

Could you post a RAW and the accompanying sidecar of one that shows this issue?

Here's my software/hardware info:

**Platform**
* darktable        : 3.4.0 +  5.8-2727-gc5f669249
* OpenCL installed : Yes (nvidia-opencl-common 450.80.02-1)
* OpenCL activated : Yes
* Graphics card    : GeForce RTX 2060 SUPER 7979 MiB
* Graphics driver  : nvidia (450.80.02)
* OS               : Linux (kernel 5.8.10-1)
* Distro           : Debian Buster (rel. 10.7)

**Additional context**
* Self compiled : Yes.
* Compilers     : gcc 8.3.0
* Cmake         : 3.13.4
* Gtk           : 3.24.5-1
* Glib          : 2.58.3-2
* Sqlite        : 3.27.2
* Optimization  : None

**Comment by rexbron** [comment] 2021-01-19 19:55
The files are not raw, they are 16bit tiff scans from an Imacon 949 scanner. 
The sample file is also very large fyi, ~1.1Gb. 
https://cloud.hunter.camera/s/zMJd4NeBF3PXzzL

I have also noticed that the same behavior with Fuji Jpegs but with a different max number. 

Also of note, when I select the preview option for the various wavelet decompositions, I am presented with a pure white image.
I left darktable open with one of the files, it it appears that the various preview levels for wavelet decomposition were rendered.

**Comment by ralfbrown** [comment] 2021-01-19 21:00
Sounds like you have either run out of memory or hit an `int` versus `size_t` issue, a number of which have been fixed in recent weeks.

Are those tiffs compressed?  (I haven't tried downloading due to size.)  Even uncompressed, a 48-bpp TIFF of 1.1 GB means that **each** image buffer is ~1.5 GB.  Every processing module needs at least two buffers (input and output), and the wavelet decompose needs four or five buffers in addition, depending on what is being done.  So retouch would need over 10GB of RAM....  Given that it takes a really long time to render a wavelet scale, it sounds like you have less physical RAM than that and are heavily swapping.

If your tiffs are compressed, the in-memory buffer size could easily exceed 2GB, at which point the `int` versus `size_t` issue comes into play and the code may erroneously try to access data at negative offsets.

**Comment by jade-nl** [comment] 2021-01-19 21:17
I just DL-ed your file and give it a whirl: I cannot reproduce this. 

I tried it using the image + sidecar first, and then the original 23748x7992 double negative scan.

About what @ralfbrown said: My machine has this to work with: 32 Gb + 15 Gb Swap.

**Comment by rexbron** [comment] 2021-01-19 21:20
Could it be something windows specific, as the screenshots below show, I don't max out the RAM and hit swap. 

![image](https://user-images.githubusercontent.com/587341/105093474-d0273700-5a70-11eb-8afa-fbb0b091c408.png)
![image](https://user-images.githubusercontent.com/587341/105093549-e8975180-5a70-11eb-94ed-7327baa70b68.png)

From the AsTiffTagExplorer:
![image](https://user-images.githubusercontent.com/587341/105094160-d9fd6a00-5a71-11eb-96f9-141522c0c433.png)


SubFileType (1 Long): Zero
ImageWidth (1 Short): 7992
ImageLength (1 Long): 23748
BitsPerSample (3 Short): 16, 16, 16
Compression (1 Short): Uncompressed
Photometric (1 Short): RGB
StripOffsets (1 Long): 600356
SamplesPerPixel (1 Short): 3
RowsPerStrip (1 Long): 23748
StripByteCounts (1 Long): 1138764096
XResolution (1 Rational): 72
YResolution (1 Rational): 72
ResolutionUnit (1 Short): None
RichTiffIPTC (16 Long): 469893120, 33554972, 41156608, 469913600,...
34152 (16 Long): 469893120, 33554972, 41156608, 469913600,...
Photoshop (76 Byte): 56, 66, 73, 77, 4, 4, 0, 0, 0, 0, 0, 64, 28,...
46277 (200000 Byte): 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 1, 229, 1, 82,...
46279 (56 Byte): 0, 0, 0, 52, 4, 0, 0, 0, 0, 12, 65, 117, 81,...
50457 (400000 Byte): 0, 0, 174, 93, 60, 63, 120, 109, 108, 32,...
50458 (90006 Byte): 0, 3, 0, 100, 1, 44, 254, 254, 254, 254,...

**Comment by rexbron** [comment] 2021-01-19 21:57
The Wavelets do eventually render; perhaps a progress indicator of some kind would be helpful.

**Comment by ralfbrown** [comment] 2021-01-19 22:25
Silly me, I was off by a factor of two in memory size (thinking 4/3 of the TIFF size when it's actually 8/3).  A 7992x23748 image requires ~2900 MB in memory for each buffer, so 20 GB when using retouch....  Also, your memory report mentions compressed memory.  If you are using compressed pages, that is a form of swapping (using reserved RAM as the backing storage) - faster than disk or SSD, but still _much_ slower than having everything in plain RAM.

IMHO, modern machines should be run with little (relative to RAM size) or no swap space due to the enormous performance hit and the fact that we are no longer dealing with mere megabytes of memory.  A few hundred megabytes at most to hold things like program startup code and other stuff that will "never" be used.  Think of how long it takes just to copy 15GB from your SSD/HD -- that's the **minimum** amount of time the system could be non-responsive if some program chews up all the swap space in Jade's case.  And probably much longer, since swap space is rarely accessed sequentially.  (For the record, I've been running my personal Linux systems completely without swap ever since getting up to 16GB RAM about a decade ago.)

**Comment by rexbron** [comment] 2021-01-19 22:55
With all that in mind, is there anything else anyone can advise me to do with regards to debugging the crash?

**Comment by Mark-64** [comment] 2021-01-20 06:53
I indeed get the crash in Windows 10 with latest git master and normal size images. So probably there is something more than low memory here.

[darktable_bt_BS39W0.txt](https://github.com/darktable-org/darktable/files/5840582/darktable_bt_BS39W0.txt)
My backtrace says the following:
```
Error occurred on Wednesday, January 20, 2021 at 07:45:21.

darktable.exe caused an Access Violation at location 000000006E905190 in module libdarktable.dll Reading from location 000000007FFEC7C0.

AddrPC           Params
000000006E905190 0000000000000000 00007FFC99C02EF8 0000000000000000  libdarktable.dll!dwt_decompose_vert._omp_fn.0  [C:/msys64/home/marco/develop/darktable/build/Release_test/../../src/common/dwt.c @ 167]
   165:       for (int c = 0; c < 4; c++)
   166:       {
>  167:         temprow[4*col + c] = 2.f * center[4*col+c] + above[4*col+c] + below[4*col+c];
   168:       }
   169:     }
```

**Comment by Mark-64** [comment] 2021-01-20 06:58
...but this log says something different
[darktable_bt_T5FQX0.txt](https://github.com/darktable-org/darktable/files/5840613/darktable_bt_T5FQX0.txt)

It seems another Windows only weird issue related to parallelization, we are having too many recently

**Closed** 2021-01-20 18:22 UTC

**Comment by rexbron** [comment] 2021-01-21 13:24
Given that this affects the 3.4.0 release, would it be possible to have the fix backported to the next point release?

**Comment by TurboGit** [comment] 2021-01-21 14:35
I understand but given the number of changes in this file and all the code refactoring done in dt this won't apply in 3.4.x branch. Maybe for 3.4.2 if we merge most of things from master. I'm considering different options, nothing easy !

**Comment by rexbron** [comment] 2021-01-21 14:36
Ah I see, well best to wait for the next stable release then :)
