### ISSUE TITLE
"Add to Library" pictures do not show up in collection when "recursive directory" is enabled

### ISSUE THREAD

**Issue by alexstaeding** [darktable-org/darktable#16038] opened 2024-01-05 16:00 UTC
### Describe the bug

If the "recursive directory" is enabled, I am unable to import pictures using the "Add to Library" feature. The message "Imported x images" shows up, but there are no pictures in the collections tab.

Changing nothing else, other than selecting a subdirectory, I was able to import the pictures after disabling "recursive directory".

Attached is a clip showing the process on an Apple Silicon MacBook Pro, including resetting the config at the beginning. After the clip ends, I select one of the subdirectories with pictures in it and disable the "recursive directory" option which then works as expected.

### Steps to reproduce

1. Click "Add to Library"
2. Select the desired folder to include
3. Select "recursive directory"
4. Click "Add to LIbrary"
5. Don't see pictures in collection

### Expected behavior

Show the pictures in the collection

### Logfile | Screenshot | Screencast

https://github.com/darktable-org/darktable/assets/24614463/4208dace-5f21-40a6-b519-d8494aa46859

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 14.2.1

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by kmilos** [comment] 2024-01-05 16:12
Duplicate of https://github.com/darktable-org/darktable/pull/15894

Please search before opening new issues.

**Closed** 2024-01-05 16:12 UTC

**Comment by alexstaeding** [comment] 2024-01-05 16:14
Sorry, I did search but it did not show up with the search terms I tried.
