### ISSUE TITLE
darktable 4.2.0 misses support for Sony A7RM5 (ILCE-7RM5) RAW files although it says it would support them

### ISSUE THREAD

**Issue by AchimDittrich** [darktable-org/darktable#13183] opened 2022-12-22 15:48 UTC
<img width="1724" alt="Bildschirm­foto 2022-12-22 um 16 47 28" src="https://user-images.githubusercontent.com/121246256/209171423-783940cc-8621-4d12-9d4b-01b4dfd38a7c.png">

**Comment by kmilos** [comment] 2022-12-22 15:57
Lossless compressed Sony files are currently not supported, as the 4.2 release notes clearly state.

@Nilvus Please close this as duplicate of https://github.com/darktable-org/darktable/issues/8523

**Closed** 2022-12-22 16:32 UTC
Labels: duplicate

**Comment by Nilvus** [comment] 2022-12-22 16:37
To complete, darktable 4.2.0 release notes says that a base support is added for that camera but not compression mode is missing. Actually, such camera support is not complete and we have already issues about that.

**Comment by AchimDittrich** [comment] 2022-12-24 10:57
Hi Nicolas,

 

the darktable release note just say "Base Support" without specifying what exactly that means but thanks for the info.

I hope the support for uncompressed Sony A7R V RAW files will soon be added.

 

 

Merry Christmas resp. happy holidays,

 

Achim
 

Homepage: achimdittrich.de / achimdittrich.com
Instagram: achimdittrich_photography

 
 

Gesendet: Donnerstag, 22. Dezember 2022 um 17:37 Uhr
Von: "Nicolas Auffray" ***@***.***>
An: "darktable-org/darktable" ***@***.***>
Cc: "AchimDittrich" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [darktable-org/darktable] darktable 4.2.0 misses support for Sony A7RM5 (ILCE-7RM5) RAW files although it says it would support them (Issue #13183)


 

To complete, darktable 4.2.0 release notes says that a base support is added for that camera but not compression mode is missing. Actually, such camera support is not complete and we have already issues about that.

**Comment by kmilos** [comment] 2022-12-24 19:29
No problem w/ the raw.pixls.us samples (both lossy or uncompressed):

![image](https://user-images.githubusercontent.com/4973094/209448947-79e91792-a6aa-4e47-af25-db6caf9d142d.png)
