### ISSUE TITLE
Group indicator "G" is not reset when current group is diminished to a single image

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#4840] opened 2020-04-28 13:28 UTC
openSUSE Tumbleweed 20200425
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable 3.1.0~git1346.532efbf17-2885.1.x86_64
OpenCL on 
i7 12-core 36GB

Select an image in lightroom
duplicate the image, now a group exists and the original image is marked "G"
delete the original image in light table, the "G" indicator moves to the duplicate image, only remaining image, but there is no longer a group.

The "G" indicator should disappear.

**Comment by Nilvus** [comment] 2020-04-28 17:34
@phweyland: as your work on group part with your #4802 PR, maybe this could be related.

**Comment by phweyland** [comment] 2020-04-30 15:51
Now #4802 is merged is this issue still alive ?

**Comment by ptilopteri** [comment] 2020-04-30 16:32
now, if I duplicate a single image, the dup shows the new symbol replacing the "G" and the original image does not.  If I dup a single image and delete the original the dup looses the symbol.

**Comment by Nilvus** [comment] 2020-04-30 16:55
> now, if I duplicate a single image, the dup shows the new symbol replacing the "G" and the original image does not. If I dup a single image and delete the original the dup looses the symbol.

Maybe it's not related but I fix an issue on last CSS PR merged where the group icon (old and new one) was not visible on main image of the group in grey theme. Be sure, if you use grey theme, you have the latest master (CSS PR was merged yesterday). On my side, I don't have what you described. the icon is visible on main image and on dup ones.

**Comment by Nilvus** [comment] 2020-04-30 16:56
> > now, if I duplicate a single image, the dup shows the new symbol replacing the "G" and the original image does not. If I dup a single image and delete the original the dup looses the symbol.
> 
> Maybe it's not related but I fix an issue on last CSS PR (#4856) merged where the group icon (old and new one) was not visible on main image of the group in grey theme. Be sure, if you use grey theme, you have the latest master (CSS PR was merged yesterday). On my side, I don't have what you described. the icon is visible on main image and on dup ones.

**Comment by Nilvus** [comment] 2020-04-30 17:12
Edit: I just see that your PR, @phweyland, was merged after my CSS fix and I confirm that the main icon on not visible now, even with my fix. And after checking just now why with Gtk inspector tool, it's not about CSS: the icon is not activate (on Gtk Inspector tool, the line is in grey, so it's for elements not rendered by Gtk, like for example audio icon as it's a rarely used one). Before and when I test my CSS fix, the line was not grey but black and indeed visible. Other thing, the icon was always visible on hover effect but no more now. So something broken on the code.

**Closed** 2020-05-01 15:15 UTC

**Comment by ptilopteri** [comment] 2020-05-01 15:37
If this has been published, it is not a solution.
still fails in darktable 3.1.0+1389~g0487939fc

**Comment by ptilopteri** [comment] 2020-05-01 16:11
nor on darktable 3.1.0+1390~gcc18fbf01

**Comment by phweyland** [comment] 2020-05-01 18:00
I've just rebuilt 3.1.0+1390~gcc18fbf01. I cannot reproduce the issue.
Whatever the image I remove, the remaining hasn't the group symbol anymore.

**Comment by ptilopteri** [comment] 2020-05-01 19:25
now works for me, tks
