### ISSUE TITLE
Crash with astrophoto denoise when adjusting image

### ISSUE THREAD

**Issue by hitausmomentti** [darktable-org/darktable#13371] opened 2023-01-18 18:06 UTC
With astrophoto denoise enabled, Darktable crashes when making other adjustments. Not immediately, but the problem usually reproduces within 30 seconds of actively moving the exposure back and forth. 

Happens with prepackaged as well as self-built binaries. Below the backtraces from self-built release and debug versions.

Environment:
 - Ubuntu 22.10
 - Intel E5 2695 v2
 - Nvidia 1060 with proprietary drivers
 - OpenCL checkbox checked

```
Thread 832 "worker res 1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe4c68d6c0 (LWP 63695)]
nlmeans_denoise_sse2._omp_fn.0 () at /home/lauri/paketoimattomat/darktable/src/common/nlmeans_core.c:710
710                   out[col] += (pixel * wt);
(gdb) bt
#0  nlmeans_denoise_sse2._omp_fn.0 () at /home/lauri/paketoimattomat/darktable/src/common/nlmeans_core.c:710
#1  0x00007ffff76d9b9e in  () at /lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff7490402 in start_thread (arg=<optimised out>) at ./nptl/pthread_create.c:442
#3  0x00007ffff751f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) p col
$1 = 1296
(gdb) p pixel
$2 = <optimised out>
(gdb) p wt
$3 = {0.00236019865, 0.00236019865, 0.00236019865, 0.00236019865}
```

debug build:
```
Thread 576 "worker res 1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffe3b1df6c0 (LWP 46261)]
0x00007ffff784b6e8 in _mm_load_ps (__P=0x7ffd558660c4) at /usr/lib/gcc/x86_64-linux-gnu/12/include/xmmintrin.h:927
927       return *(__m128 *)__P;
(gdb) bt
#0  0x00007ffff784b6e8 in _mm_load_ps (__P=0x7ffd558660c4) at /usr/lib/gcc/x86_64-linux-gnu/12/include/xmmintrin.h:927
#1  pixel_difference_sse2 (pix1=0x7ffd558660c0, pix2=0x7ffd558660c4, norm=0x7fffe4fd6a30) at /home/lauri/paketoimattomat/darktable/src/common/nlmeans_core.c:192
#2  0x00007ffff784bb05 in init_column_sums_sse2
    (col_sums=0x7fffc4065208, patch=0x7fffc4028220, in=0x7ffd55100080, row=360, chunk_left=1296, chunk_right=1347, height=900, width=1347, stride=5388, radius=1, norm=0x7fffe4fd6a30)
    at /home/lauri/paketoimattomat/darktable/src/common/nlmeans_core.c:317
#3  0x00007ffff784f0c2 in nlmeans_denoise_sse2._omp_fn.0 () at /home/lauri/paketoimattomat/darktable/src/common/nlmeans_core.c:686
#4  0x00007ffff7f6eb9e in  () at /lib/x86_64-linux-gnu/libgomp.so.1
#5  0x00007ffff7290402 in start_thread (arg=<optimised out>) at ./nptl/pthread_create.c:442
#6  0x00007ffff731f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

Raw file and XMP available at `https://www.dropbox.com/s/58cqcczcy8o5i7w/repro.zip?dl=0`

**Comment by jenshannoschwalm** [comment] 2023-01-31 13:29
Duplicate of #12662 :-) Maybe close this one ... instead keeping discussions there :-)

**Comment by hitausmomentti** [comment] 2023-01-31 16:06
Dupe of #12662

**Closed** 2023-02-09 10:18 UTC
