### ISSUE TITLE
OSX: cmake settings:  -DCMAKE_BUILD_TYPE=RELEASE is mandatory?

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#4402] opened 2020-02-29 16:33 UTC
**Describe the bug**
after updating macports, deleting the darktable build directory and using 
```
cmake .. \
 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13\
 -DCMAKE_CXX_FLAGS=-stdlib=libc++ \
 -DOpenMP_C_INCLUDE_DIR=/opt/local/include/libomp \
 -DOpenMP_CXX_INCLUDE_DIR=/opt/local/include/libomp \
 -DCMAKE_LIBRARY_PATH=/opt/local/lib/libomp \
 -DBINARY_PACKAGE_BUILD=ON \
 -DRAWSPEED_ENABLE_LTO=ON \
 -DBUILD_CURVE_TOOLS=ON \
 -DBUILD_NOISE_TOOLS=ON
```
to recreate my build environment i got compilation errors on osx 
```
/Users/martinstraeten/src/darktable/src/common/camera_control.c:1032:21: error:
      incompatible pointer types passing 'size_t *' (aka 'unsigned long *') to
      parameter of type 'uint64_t *' (aka 'unsigned long long *')
      [-Werror,-Wincompatible-pointer-types]
                    &chunksize, c->gpcontext) == GP_OK)
                    ^~~~~~~~~~
/opt/local/include/gphoto2/gphoto2-camera.h:451:48: note: passing argument to
      parameter 'size' here
                                 uint64_t offset, char *buf, uint64_t *size,
                                                                       ^
/Users/martinstraeten/src/darktable/src/common/camera_control.c:1048:21: error:
      incompatible pointer types passing 'size_t *' (aka 'unsigned long *') to
      parameter of type 'uint64_t *' (aka 'unsigned long long *')
      [-Werror,-Wincompatible-pointer-types]
                    &chunksize, c->gpcontext) == GP_OK)
                    ^~~~~~~~~~
/opt/local/include/gphoto2/gphoto2-camera.h:451:48: note: passing argument to
      parameter 'size' here
                                 uint64_t offset, char *buf, uint64_t *size,
                                                                       ^
/Users/martinstraeten/src/darktable/src/common/camera_control.c:1092:19: error:
      incompatible pointer types passing 'size_t *' (aka 'unsigned long *') to
      parameter of type 'uint64_t *' (aka 'unsigned long long *')
      [-Werror,-Wincompatible-pointer-types]
                  &chunksize, c->gpcontext) == GP_OK)
                  ^~~~~~~~~~
/opt/local/include/gphoto2/gphoto2-camera.h:451:48: note: passing argument to
      parameter 'size' here
                                 uint64_t offset, char *buf, uint64_t *size,
                                                                       ^
3 errors generated.

```
adding `-DCMAKE_BUILD_TYPE=RELWITHDEBINFO` explicitly to the cmake command results in the same error.
adding  `-DCMAKE_BUILD_TYPE=RELEASE` : the build was successful

**Comment by parafin** [comment] 2020-02-29 16:37
Which darktable version?

**Comment by MStraeten** [comment] 2020-02-29 16:37
current master just 30 min old ;

**Comment by parafin** [comment] 2020-02-29 16:38
I think this is duplicate of #4391 which is marked as fixed.

**Comment by MStraeten** [comment] 2020-02-29 16:49
ok seems so

**Closed** 2020-02-29 17:01 UTC
