### ISSUE TITLE
deleted default shortcuts don't stay deleted

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#10452] opened 2021-11-22 13:38 UTC
1. Open the shortcut tab of the preferences window and select global > panels in the top pane. 
2. Select global/panels/right (ctrl+shift+r) in the bottom pane and press the delete key. Dialog appears asking for confirmation. 
3. Click yes and the shortcut is removed.
4. Close and re-open darktable and repeat. Shortcut has been reinstated.

User created shortcuts are correctly removed.

**Comment by dterrahe** [comment] 2021-11-22 17:53
I don't mind if you tag me in inputng related bug reports; I don't currently have much time to spend on dt, but am generally happy to help with bugfixing or clarification and it would save me the trouble of checking the issue list.

You raise a very valid point that I was honestly a little surprised did not come up earlier, but then maybe that's an indication of how much of a problem it really is for people.

The reason default shortcuts come back is that the personalised shortcutsrc is loaded _after_ the defaults have been initialised and _only_ override default shortcuts when the particular key combination is used for something else. This was done so that if a new default shortcut is added, it will automatically appear also for existing users. The "simple" solution, to throw away all defaults if a shortcutsrc file is found, would break that.

Currently no distinction is made between a default shortcut that isn't in shortcutsrc because it was introduced by a new version and a default shortcut that was intentionally deleted by the user. To make that distinction, we could introduce a new fake (internal only) action "intentionally deleted" and map a default shortcut to that, whenever a user deletes it. It would then be saved and reloaded at next start and overwrite the default shortcut with something that does nothing. And then we could also make that not appear in H and the shortcuts configuration dialog. To reinstate the default shortcut it would have to be explicitly mapped again (which would overwrite, skipping the normal confirmation question, the mapping to "intentionaly deleted").

To make this scheme work, we would have to keep track of which shortcuts are defaults (when deleted, they are mapped to "intentionally deleted") and those that were created by the user (delete just deletes). But then, when the user recreates an "intentionally deleted" shortcut, we'd have to mark it as "default" again, so that if they delete it _again_ it doesn't just get deleted and recreated at next start. But that is not trivial, because currently the default shortcuts are not stored in memory after being overwritten, so we can't directly compare if the new and default are the same. My worry would be that we'd end up implementing something that in first instance behaves more logically, but that sometimes falls apart in confounding ways.

And it would sacrifice the current "feature" that if you accidentally overwrite a default shortcut, you can just delete the wrong one and you'll have the default back after restart. You could use the "restore" button in the configuration dialog for that, but that would restore _all_ default shortcuts.

The "benefit" would be that the shortcut list could be pruned, without reusing the freed up keys for something else. I suspect the audience that requires this is rather small (but a poll/responses to this issue could prove me wrong). Please also let me know if there are other aspects to this issue that would make it worthwhile implementing (and debugging) a solution. Or if I'm overlooking much simpler solutions.

**Comment by elstoc** [comment] 2021-11-22 18:09
> I don't mind if you tag me in inputng related bug reports; I don't currently have much time to spend on dt, but am generally happy to help with bugfixing or clarification and it would save me the trouble of checking the issue list.

Noted. I didn't know how involved you wanted to be at the moment.

> I was honestly a little surprised did not come up earlier, but then maybe that's an indication of how much of a problem it really is for people.

I'm raising stuff like this now because I've only just upgraded my working version to master for testing/playing and am actively using it for real image processing. I suspect you've overestimated the number of users on master who are actively using anything more than very basic shortcuts.

I personally prefer to remove every shortcut I'm not intending to use (which is how I worked with the old system) so that stuff doesn't happen without my intending it when I press the wrong key. For example I use Ctrl+S to activate module search but sometimes I don't hit Ctrl and the slideshow starts, which is annoying.

Perhaps deleting could strikethrough removed defaults and they could be restored by pressing delete a second time.

**Comment by dterrahe** [comment] 2021-11-22 19:07
> I suspect you've overestimated the number of users on master who are actively using anything more than very basic shortcuts.

My estimate of that number is pretty close to zero...

> Perhaps deleting could strikethrough removed defaults and they could be restored by pressing delete a second time.

Sure, that's the UI representation part. Internally, it means keeping track of defaults as special cases and at several points do something different with them. For example suppose you delete Ctrl-Q (quit). It will now appear struck through. Now you assign Ctrl-Q to something else (say, contrast equalizer). Do both the struck through default and the new, active, shortcut appear? That would mean the shortcut is not unique in the internal list anymore and every test and every search will need to be amended to deal with duplicates; bugs galore. Or maybe only the new shortcut appears. Now, if I delete _that_ one, does the original default appear again? Struck through? That means I needed to have kept it somewhere in a separate list. Lots of bookkeeping fun. What if I didn't explicitly delete "quit", but I _did_ overwrite it with "contrast equalizer". Now if I delete _that_ one, should "quit" reappear? Struck through?

A solution to your specific problem could be to have a dummy global action that you could use just to overwrite/disable defaults but that doesn't _do_ anything. You could just use global/modifiers, but it would be nicer to have something with a descriptive name and give it special treatement in H by filtering it out. Now you have full control, but there is no need for magic behind the scenes that complicates a lot of codepaths and _still_ leads to unexpected behavior.

Don't get me wrong; if someone implements your suggestion in a clean way I'd be very supportive!

**Comment by elstoc** [comment] 2021-11-22 19:16
> A solution to your specific problem could be to have a dummy global action that you could use just to overwrite/disable defaults but that doesn't do anything.

The delete action could explicitly do that - assign any deleted shortcut to a (potentially hidden) global shortcut as well as physically deleting it. That way the system doesn't need to care if it's a default shortcut or not (it can do the same thing for deletion of user shortcuts).

If the user subsequently creates another identical shortcut darktable can just remove it from that dummy global action without prompting the user.

**Comment by dterrahe** [comment] 2021-11-22 19:35
Yes.

And any dummy placeholders for deleted user shortcuts could be discarded during the loading process when they are not actually overwriting (disabling) any (presumably default) shortcuts. So we wouldn't end up with an endless proliferation of deleted user shortcuts.

From experience, I would expect that implementing this kind of thing and hunting down all the resulting bugs would take me a few days. Maybe someone else could do it quicker.

It would also throw out the easy way of getting back an accidentally overwritten default shortcut (easy for someone who doesn't really understand what they are doing, but we could tell them "if you want the original meaning of Ctrl-Q back, go find all the Ctrl-Qs in you current list of shortcuts and delete them and restart; done".)

But it would make you happy (or at least happier than using the mentioned global/modifiers workaround). Maybe some others who would definitely use this could chime in to help motivate me to put it on my todo list.

**Comment by elstoc** [comment] 2021-11-22 19:45
> It would also throw out the easy way of getting back an accidentally overwritten default shortcut 

Or we could make the "global/deleted" action visible and allow the user to really delete shortcuts from it. "restore..." would revert all deletions.

> But it would make you happy (or at least happier than using the mentioned global/modifiers workaround). Maybe some others who would definitely use this could chime in to help motivate me to put it on my todo list.

As it is, it looks like you can delete stuff but you can't so it feels like at least a UI bug (for which one solution might be to disable deletion - still hard to do). The workaround is a good idea waaay too much effort (I'd have to search through the shortcuts, make a list of the ones I want to delete and then recreate them all individually)

I'm happy to look into doing the dev on this (I've started looking at the code) but I might need some pointers.

**Comment by dterrahe** [comment] 2021-11-22 20:17
> Edit: We might need to have one-per-view, so that the "view/deleted" shortcut has the same scope as the one the user has removed. Or to only add to the global shortcut if there are no other conflicts

I just realised this as well.

> "restore..." would revert all deletions.

You'd have to remember _which_ shortcut was deleted to be able to do this.

> it feels like at least a UI bug

This could be "fixed" in the tooltip by adding "default shortcuts will reappear after restart". This will also make clear that this is a way to recover accidentally deleted ones.

> waaay too much effort

In that case I'd suggest editing shortcutsrc by hand and take the one time pain, rather than 

> doing the dev on this

Great! Please keep in mind that a large part of the cost of features like this is the time spent in future by some other dev chasing down bugs caused by corner cases, so it pays to keep changes as localised as possible.

Thank you!

**Comment by elstoc** [comment] 2021-11-22 20:26
How about for now we just create a `global/null` action to give a truly no-op bucket and then I can list this as a recommended way to remove defaults (by editing shortcutsrc) in the manual. This would be sufficiently safe for 3.8 and allow further consideration for a better solution later.

**Comment by elstoc** [comment] 2022-03-04 20:56
Here's an idea -- how about a new option "reload default shortcuts on startup", which is enabled by default. If a user disables the option, the defaults remain (because they've already been saved in shortcutsrc) but are never loaded again (darktable just loads shortcutsrc). If the user wants the defaults back they untick the option and restart.

**Comment by dterrahe** [comment] 2022-03-04 21:28
You mean ticking the option gets you _just_ the default shortcuts? Any you created yourself (or speed adjustments) are lost? Or do you mean what happens now, i.e. first defaults but customisations overwrite (but don't delete)?

> If the user wants the defaults back they untick the option and restart.

You mean _tick_ the option, right?

If the "clear defaults at startup and just use shortcutsrc" is implemented, the easier way to get defaults back as a one-of (and possibly overwrite any customisations you made, which may be needed in case a new default shortcut was created using a key you already assigned to something else) would be to _restore_ them in the shortcuts dialog. Because the complete up-to-date _shortcutsrc.defaults_ would still have been created. That would overwrite customisations (or delete all of those if you tick that box).

Your suggestion is a very good one (and I think it might be trivial to implement) if you can make the description more accurately explain what it does...

**Comment by elstoc** [comment] 2022-03-04 21:35
> You mean tick the option, right?

That's what I meant, yes.

> You mean ticking the option gets you just the default shortcuts? Any you created yourself (or speed adjustments) are lost?

My understanding of the current system is that it's a two step process that loads the defaults and then loads the user's cusomisations on top (which may then override one or more of the defaults). My thought was that deselecting the option would just cancel the first (load defaults) step and then re-selecting it would reinstate it again. So neither option would ever override any user-added shortcuts (there are already options to do that). Perhaps there's a better name/description we could give it to be clearer.

> and I think it might be trivial to implement

That's what I was hoping :). We could get rid of the global/no-op action at the same time.

**Closed** 2022-03-16 09:20 UTC
Labels: scope: UI, bug: pending
