### ISSUE TITLE
lighttable image display changes on reload

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#4957] opened 2020-05-08 20:34 UTC
I have a collection containing 4 images and I have the lighttable (file manager) set to display 4 images per row. When I initially open darktable all of the four images in my collection are displayed together on the top row.

![Screenshot_2020-05-08_21-29-41](https://user-images.githubusercontent.com/9555491/81446554-0e92f500-9173-11ea-84a9-f4c0bb2b0b09.png)

If I double-click, say, the second image to go into the darkroom and then exit back to the lighttable the layout changes (presumably with the aim to put the selected image to the top-left of the screen):

![Screenshot_2020-05-08_21-30-46](https://user-images.githubusercontent.com/9555491/81446619-31250e00-9173-11ea-956e-4fb20dee3477.png)

If I scroll up, I now have empty space in the first three slots of the lighttable view:

![Screenshot_2020-05-08_21-32-16](https://user-images.githubusercontent.com/9555491/81446809-6893ba80-9173-11ea-8a68-a0781f2ac6b0.png)

If I scroll up again, the layout changes back to the starting point (all four images on a line together).

Rather than try to place the selected image in the top-left, perhaps the lighttable should merely attempt to place the selected image on the top _row_, thus keeping the overall layout intact.

**Comment by AlicVB** [comment] 2020-05-08 20:42
All I can say is that's the intended behavior, so that's more a feature request than an issue.
Now for the question if that should change, I admit that I have no clear opinion here...

**Comment by elstoc** [comment] 2020-05-08 20:51
> that's more a feature request than an issue

Ok fair enough. Given that it'll reflow when you scroll to the top imo it would be better to not have a different layout when re-entering than before going to the darkroom. And it does feel like a glitch when it reflows to fill the gaps.

**Comment by thisnamewasnottaken** [comment] 2020-07-18 23:57
This seems fixed in https://github.com/darktable-org/darktable/pull/5605

**Comment by elstoc** [comment] 2020-07-19 08:57
Issue still occurs in 3.1.0+2475~g08eba104b

**Comment by pmjdebruijn** [comment] 2020-07-31 17:37
If this is intended behavior, I find this nothing short of bizarre to have as a default behavior...

I would consider this severe enough, that it should be considered a release blocker for 3.2.0

**Comment by TurboGit** [comment] 2020-07-31 18:37
> I would consider this severe enough, that it should be considered a release blocker for 3.2.0

Blocker ? No certainly not. Something to fix probably.

**Comment by pmjdebruijn** [comment] 2020-07-31 18:46
> Blocker ? No certainly not. Something to fix probably.

It's your call ofcourse, but it's a significant behavioral regression in a extremely common used part of the application, in the simplest of usecases.

**Comment by johnny-bit** [comment] 2020-07-31 19:15
Issue happens on 3.2 branch as well as on master (and is a bit iffy)

**Comment by cornergraf** [comment] 2020-08-01 15:21
I can confirm that this issue is quite annoying - I am editing my pictures from my summer vacation, and the pictures constantly change position... I am on the current git branch, at it is definitely still an issue.

**Comment by pmjdebruijn** [comment] 2020-08-03 16:55
I briefly tested elstoc patch, and that makes it much better, though it's not a full fix. So even with that patch being a huge improvement over what 3.2 currently is, the remaining behavior is still a significant usability regression over previous versions of darktable.

**Comment by elstoc** [comment] 2020-08-03 17:20
It's difficult to argue that the scroll-up glitch isn't a bug.

But the rest feels to me like just a change in functionality that you can either agree or disagree with. I think it seems fairly reasonable to have the last-edited image appear in the top row, especially given that you could have changed image while in the darkroom.

**Closed** 2020-08-04 08:09 UTC
Labels: bug: pending, difficulty: trivial, no-issue-activity, priority: high, scope: UI
