### ISSUE TITLE
Lua script does not work properly (dt 4.8.0)

### ISSUE THREAD

**Issue by robyquin** [darktable-org/darktable#17108] opened 2024-07-08 10:04 UTC
### Describe the bug

In the version 4.8.0 of darktable, not all scripts lua work correctly.

In this example, I used "OpenInExplorer" (repo contrib).

This script does not open folder, but it should do it like in the old version.

### Steps to reproduce

1. Select an image
2. click on button "Show in file explorer" (script lua "OpenInExplorer")

### Expected behavior

darktable should open folder of selected image

### Logfile | Screenshot | Screencast

darktable 4.8.0
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.3.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

    19,3480 LUA [script installer] dont show not set
    19,3480 LUA [script installer] checking for lua directory
    19,3480 LUA [script installer] checking for scripts
    19,3649 LUA [script installer] line is color
    19,3650 LUA [script installer] line is darktablerc
    19,3651 LUA [script installer] line is darktablerc_20240101
    19,3651 LUA [script installer] line is data.db
    19,3652 LUA [script installer] line is data.db-pre-4.4.2
    19,3653 LUA [script installer] line is data.db-pre-4.5.0
    19,3654 LUA [script installer] line is data.db-pre-4.6.0
    19,3654 LUA [script installer] line is data.db-pre-4.6.1
    19,3655 LUA [script installer] line is data.db-pre-4.7.0
    19,3656 LUA [script installer] line is data.db-pre-4.8.0
    19,3656 LUA [script installer] line is data.db-snp-20240526155629
    19,3657 LUA [script installer] line is data.db-snp-20240602161430
    19,3658 LUA [script installer] line is data.db-snp-20240609192445
    19,3658 LUA [script installer] line is data.db-snp-20240624090049
    19,3659 LUA [script installer] line is data.db-snp-20240701212953
    19,3660 LUA [script installer] line is data.db.lock
    19,3660 LUA [script installer] line is library.db
    19,3661 LUA [script installer] line is library.db-pre-4.4.2
    19,3661 LUA [script installer] line is library.db-pre-4.5.0
    19,3662 LUA [script installer] line is library.db-pre-4.6.0
    19,3663 LUA [script installer] line is library.db-pre-4.6.1
    19,3663 LUA [script installer] line is library.db-pre-4.7.0
    19,3664 LUA [script installer] line is library.db-pre-4.8.0
    19,3665 LUA [script installer] line is library.db-snp-20240526155629
    19,3665 LUA [script installer] line is library.db-snp-20240602161430
    19,3666 LUA [script installer] line is library.db-snp-20240609192445
    19,3667 LUA [script installer] line is library.db-snp-20240624090049
    19,3667 LUA [script installer] line is library.db-snp-20240701212953
    19,3668 LUA [script installer] line is library.db.lock
    19,3668 LUA [script installer] line is lua
    19,3669 LUA [script installer] scripts found
    19,3669 LUA [script installer] line is luarc
    19,3670 LUA [script installer] line is shortcutsrc
    19,3670 LUA [script installer] line is shortcutsrc.backup
    19,3671 LUA [script installer] line is shortcutsrc.defaults
    19,3672 LUA [script installer] line is shortcutsrc.edit
    19,3672 LUA [script installer] line is styles
    19,3673 LUA [script installer] line is user.css
    19,3673 LUA [script installer] line is watermarks
    32,3444 LUA OpenInExplorer run_cmd = explorer.exe /select, "D:\[path file here]\filename.NEF"
    32,3445 LUA ERROR Windows command failed: unable to create batch file
  2058,5445 LUA OpenInExplorer run_cmd = explorer.exe /select, "D:\\[path file here]\filename.NEF"
  2058,5446 LUA ERROR Windows command failed: unable to create batch file

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.0

### What OS are you using?

Windows

### What is the version of your OS?

10

### Are you using OpenCL GPU in darktable?

None

**Comment by wpferguson** [comment] 2024-07-08 14:11
The solution to this is either
* open a command prompt and go into the scripts directory (`C:\users\<username>\%LOCALAPPDATA%\darktable\lua`) then run the command `git pull`, or
* remove the scripts directory and let darktable reinstall the scripts.

**Comment by wpferguson** [comment] 2024-07-08 14:58
> `2058,5445 LUA OpenInExplorer run_cmd = explorer.exe /select, "D:\[path file here]\filename.NEF"`

The `D:\[path file here]` and `filename` are extracted from the image entry in the database.  What directory and filename were you trying to open?

**Comment by robyquin** [comment] 2024-07-08 15:21
Any image in any path.

Of course the image is in the database, the path can be of this type: D:\Picture_Win\InsertMedia-pre\20240615\Podio_wp\20240615_0141_podio_wm0.jpg

I updated the repository (git pull), I tried to reinstall all the scripts, but nothing!

**Comment by wpferguson** [comment] 2024-07-08 15:41
I found it.  There is a typo (quote_windows-command should be quote_windows_command) in the system library.  Give me a few minutes and I'll push a fix.  The next time you start darktable it should automatically pull it down.

**Comment by wpferguson** [comment] 2024-07-08 15:47
Done

**Comment by wpferguson** [comment] 2024-07-08 17:19
Fixed one issue, but windows still won't allow the script to create a batch file.

**Comment by robyquin** [comment] 2024-07-08 17:42
> Fixed one issue, but windows still won't allow the script to create a batch file.

Yes, correct!
I think that "io" library isn't loaded, or It doesn't work fine!

**Comment by wpferguson** [comment] 2024-07-09 01:28
I managed to figure out what is going on.  The issue is sanitizing strings that are presented to the operating system.  The file wasn't being created because the file name was "over" sanitized.  When I worked past that, the command that went into the file was over sanitized too, so it still wouldn't work.

I'm going to close this since it's really a scripts issue and not a darktable issue.  You can track the progress in the above linked issue.

**Closed by wpferguson** 2024-07-09 01:28 UTC
Labels: lua
