### ISSUE TITLE
Gimp cannot find darktable plugin for DT 4.8.1

### ISSUE THREAD

**Issue by beew** [darktable-org/darktable#17410] opened 2024-09-01 04:08 UTC
### Describe the bug

This is the same as https://github.com/darktable-org/darktable/issues/17039 

which has been closed because fix was supposed to be released in next sub version release, but DT 4.8.1 still has the same problem.

### Steps to reproduce

Try to open a raw file with gimp.

Gimp complains that it cannot find a raw plugin

### Expected behavior

Gimp should open the file in Darktable.

### Where did you obtain darktable from?

distro packaging

### darktable version

4.8.1 Darktable installed from the ppa https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/darktable

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04 

### Describe your system?

Ubuntu 22.04, Gimp 2.10.38 compiled from source, it was able to open raw files with DT 4.6.1

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment] 2024-09-01 04:52
> which has been closed because fix was supposed to be released in next sub version release, but DT 4.8.1 still has the same problem.

Yes, the fix is already pending in GIMP and should make it into the next release of GIMP. The fix was added to the GIMP codebase on May 25. The problem is that there hasn't been a single GIMP release since then.

The only thing you can do is ask in GIMP issue tracker to speed up their new release, as the current situation is causing you inconvenience.

Since we can't help from the side of darktable, I am closing this issue.

**Closed by victoryforce** 2024-09-01 04:52 UTC
