### ISSUE TITLE
Canon M50 camera is missing in file cameras.xml

### ISSUE THREAD

**Issue by mmhh76** [darktable-org/darktable#9429] opened 2021-07-05 22:41 UTC
Hi again!

I saw there were denoise profile as well added to the Canon M50 camera. Didn't work either.
What I saw was that the Canon M50 is not in the cameras.xml at all.

What I did was copy the Canon M10 code and then changed the text to Canon M50, like this:
\<Camera make="Canon" model="Canon EOS M50">
		\<ID make="Canon" model="EOS M50">Canon EOS M50\</ID>
		\<CFA width="2" height="2">
			\<Color x="0" y="0">RED\</Color>
			\<Color x="1" y="0">GREEN\</Color>
			\<Color x="0" y="1">GREEN\</Color>
			\<Color x="1" y="1">BLUE\</Color>
		\</CFA>
		\<Crop x="72" y="52" width="0" height="-2"/>
		\<Sensor black="2048" white="16000"/>
		\<BlackAreas>
			\<Vertical x="2" width="68"/>
			\<Horizontal y="2" height="40"/>
		\</BlackAreas>
		\<Hints>
			\<Hint name="wb_offset" value="142"/>
		\</Hints>
	\</Camera>

I don't know if it's the correct values for the M50, but after I added the code to cameras.xml, Denoise profile and White Balance profiles works without any changes to the White balance profiles which I did before to get it to work.

I compiled the latest development version of Darktable with the changes to cameras.xml. I followed the instructions on the github page.

I am using Ubuntu 21.04. Running the default graphic desktop GNOME.

I didn't add any patches to Darktable.

**Comment by johnny-bit** [comment] 2021-07-06 07:20
This issue is duplicate of your #9391 which should be closed IMO
This issue is duplicate of #2827

If you want to "ride" experimental CR3 support then the correct values are in https://github.com/darktable-org/rawspeed/pull/271
(or just copy cameras.xml from there)

**Closed by johnny-bit** 2021-07-06 07:20 UTC
Labels: duplicate
