### ISSUE TITLE
Importing multiple dirs to a filmroll - crash

### ISSUE THREAD

**Issue by progo** [darktable-org/darktable#9338] opened 2021-06-26 09:18 UTC
**Describe the bug/issue**

Under my storage I have files in directories based on shooting day/session.

```
(~/pics/digikuvat) for d in 2018-12-*; do echo -n "$d -- file count: " ; ls "$d" |wc -l ; done
2018-12-04(Tue)-sekalaista -- file count: 21
2018-12-06(Thu)-kuorinka -- file count: 16
2018-12-11(Tue)-wb-presets -- file count: 11
2018-12-22(Sat)-koneistamo-oku -- file count: 49
2018-12-26(Wed)-joulu -- file count: 77
2018-12-28(Fri)-m240-init -- file count: 112
2018-12-29(Sat)-satos-talvi -- file count: 150
2018-12-31(Mon)-testeja--talviaurinko -- file count: 412
```

I processed these in darktable back in 2018 and I probably have revisited these directories (each as a film roll) since. 

What never worked but now I want to raise it as a bug report, is importing all these to one film roll for speed and convenience.

But it crashes in the import process whenever I try to import more than one directory at once. 

Important to stress: Each directory will import fine if as sole argument.

**To Reproduce**

Selecting more than one directory to import. "Import recursively" is on. There are some jpegs but mostly raws, with XMP sidecars.

Starting with an empty `library.db` has no effect.

**Expected behavior**

The filmroll should be populated with all the files under all selected directories.

**Platform**

* darktable version : 3.4.1
* OS                : gentoo amd64
* Linux - Distro    : gentoo amd64
* Memory            : 24 G
* Graphics card     :  Nvidia GTX1060
* Graphics driver   : proprietary blob 
* OpenCL installed  : y
* OpenCL activated  : y

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **I have a strong feeling I have never got this to work properly. I've used darktable 2.2 and upwards.**

**Comment by johnny-bit** [comment] 2021-06-26 10:32
Huh 0.o Recursive imports have ALWAYS worked for me...

Can you attach crash log? and/or console output?

**Comment by progo** [comment] 2021-06-26 11:04
Most recent traceback as reported by darktable.

[darktable_bt_QVAR50.txt](https://github.com/darktable-org/darktable/files/6719963/darktable_bt_QVAR50.txt)


As I was reproducing this, I noticed something probably important.

- When I have "Ignore JPEG files" **disabled** ie. unticked, the crash occurs with the traceback above.
- When I have the same option **enabled** ie ticked, the process does not crash but only the first directory is imported, the rest seemingly ignored. There should be hundreds of files but there's only four (4). This is probably no help but here is some of the captured log (`-d all`) occured during the import [darktable-import.log.gz](https://github.com/darktable-org/darktable/files/6719969/darktable-import.log.gz)

And sure enough because this option switch seems to be involved in things somehow, I also tried to import several directories that will have no jpegs in them. Does not crash either way, but also will only import files from the first argument, ignoring the rest. Could be I don't know how to operate the film roll filters but anyway.

**Comment by johnny-bit** [comment] 2021-06-26 12:48
This is weird. According to backtrace the last point of contact in darktable before crash is https://github.com/darktable-org/darktable/blob/3641764ed2a2443a495d6769355d644bf9cb7710/src/libs/collect.c#L1780 and then crash "happens in the db".

However sigserv handler gets called in lua processing context and one of last sensible points that have some reference is _image_import_internal with xmp file for `/home/progo/pics/digikuvat/2018-12-28(Fri)-m240-init/MP004197.JPG.xmp`

This points me to 2 things - either DB or lua scripts are the problem.

I know you tried with empty db - but have you tried with empty db AND lua disabled?

additionally - we have similar os setup (gentoo, 24g ram, 1060...) so I wouldn't say that it might have "old" sqlite that's causting problems. And I don't see how `SELECT folder, film_rolls_id, COUNT(*) AS count FROM main.images AS mi JOIN (SELECT id AS film_rolls_id, folder       FROM main.film_rolls)   ON film_id = film_rolls_id  WHERE (1=1) GROUP BY folder ORDER BY film_rolls_id DESC` could cause problems for sqlite...

And lastly - the 3.6 release is comming in just ~7 days so if you can test current master (or 3.6 branch) and if it has the same problem i'd be appreciated.

**Comment by progo** [comment] 2021-06-26 13:24
Yes, thank you for help.

1. Couldn't repro the crash anymore. Something got written in `library.db`, my guess.
2. New library and disable lua. Doesn't crash.
3. New library and enable lua. Crash.

I have a lua script hooked to "post-import-image" event.

Gentoo-related, LUA_SINGLE_TARGET for darktable is lua5-3 and USE=lua is active.


PS. Please ignore my problem description about importing (when it doesn't crash, that is) not respecting several directories at once. This was a RTFM related issue.

**Comment by progo** [comment] 2021-06-26 13:56
When I was troubleshooting this, mainly moving library.db around, importing photos to filmrolls, and commenting/uncommenting lua lines, ...

... darktable was again able to somehow lose my edits. The sidecars were overwritten with "virgin histories". The last time darktable fucked up my data I set up a daily backup but apparently I need to set up something that runs every 10 mins.

**Comment by johnny-bit** [comment] 2021-06-26 14:06
nothing should get written to xmp, maybe with exception of import timestamp. And since I don't have lua enabled at all I wouldn't be able to reproduce your problem anyway.

can you share the lua script you're using? It's most likely the source of crash (but shouldn't be).

And since it's more than likely that it's a lua issue i'd need to call @wpferguson for assistance on this one :)

**Comment by wpferguson** [comment] 2021-06-26 14:57
Could you please attach the lua script, or if it's one from the lua scripts repository identify it?

**Comment by progo** [comment] 2021-06-26 15:30
https://github.com/progo/leica-q-autocrop/blob/master/autocrop.lua

Spoiler alert: `pcall`, external processes, lots of obvious suspects here.

I didn't remember the existence of this script as it has been years since I had the gear I need the script for.

**Comment by wpferguson** [comment] 2021-06-26 16:44
can you give me an image that I can test with, please?

**Comment by wpferguson** [comment] 2021-06-26 16:53
> And lastly - the 3.6 release is comming in just ~7 days so if you can test current master (or 3.6 branch) and if it has the same problem i'd be appreciated.

The register_event call changed in 3.6, so if you check against master the arguments are name, event, callback, where name is just a string

**Comment by wpferguson** [comment] 2021-06-26 17:34
@progo can you try wrapping the darktable.styles.apply call with darktable.print_log() to see if it's a specific image or specific style.  You can run darktable from the console with -d lua to see the print_log messages in the console.

**Comment by wpferguson** [comment] 2021-06-27 03:12
I'll also need the styles

**Comment by progo** [comment] 2021-06-27 08:20
This is about the corruption problem. I did precisely nothing else but to try import the files (while reproducing the crash) and one xmp has had some changes that look suspicious. Now in this case those modules are all automatically applied ones so bear that in mind.

Because this deals with data loss I think this is urgent, even though necessarily related to this crash.

[xmp-corr.patch.gz](https://github.com/darktable-org/darktable/files/6721235/xmp-corr.patch.gz)


I will now continue with the original lua crash, build a mvp

**Comment by progo** [comment] 2021-06-27 08:53
It can be reliably reproduced and it has something to do with concurrency. A single directory always imports fine, multiple dirs always fail (with the offending file) and they are being imported concurrently. I assume it has to do with concurrency. 

The lua script doesn't ever get to the point of applying styles. The crash happens during the pcall. I can probably reduce the lua script a great bit.

Here's also a piece of log outpt  that maybe, MAYBE exhibits a crash that happens simply because of a simple lua coding mistake: [possibly-crash-from-lua-error.log.gz](https://github.com/darktable-org/darktable/files/6721281/possibly-crash-from-lua-error.log.gz)

**Comment by progo** [comment] 2021-06-27 09:29
Sadly with a very minimal sample input the problem is not reproducible, at least it will not happen often.

I have taken the autocrop.lua and taken it to parts. No longer will it search styles or apply one. It won't even call `exiftool` anymore -- I replaced it with a dummy `/bin/echo` call. It is enough to trigger the condition and crash.

The problem is with the process invocation and reading its stdout. If I comment `get_stdout(...)` out, no crash.

Attached is a `-d lua` log using the latest version of the lua file, also attached.

[echo.log.gz](https://github.com/darktable-org/darktable/files/6721329/echo.log.gz)

[autocrop.lua.txt](https://github.com/darktable-org/darktable/files/6721331/autocrop.lua.txt)

**Comment by progo** [comment] 2021-06-27 09:36
To confirm, it's not apparently about any particular file, raw or JPEG. It is about using `io.popen` and reading stdout of an outside process when doing multiple directories in parallel. This is my finding and understanding  of this problem, at this moment.

**Comment by progo** [comment] 2021-06-27 09:59
And now testing MASTER 79067124e0701, built fresh.

The new import dialog looks fancy but I see usability concerns right off the bat because in my photo storage of hundreds if not thousands of directories I can't now search for "2018-12" to get to my files from Dec 2018. 

But I digress. Let's see about that lua problem.


The new selector interface doesn't allow me to select multiple directories anymore. Perhaps this little UI change fixes the race conditions? heh

Since the behavior has changed between 3.4.1 and master I can't test the same exact thing anymore.

**Comment by progo** [comment] 2021-06-27 10:06
Let me attach the log from my master test above.

The log is cleanly written in chronological order. Implies that a directory is being imported in one thread without any danger to get usual problems from concurrency.

[darktable-master-lua.log.gz](https://github.com/darktable-org/darktable/files/6721369/darktable-master-lua.log.gz)

**Comment by wpferguson** [comment] 2021-06-27 15:06
If I understand correctly there is no problem while using master and everything works correctly?

**Comment by progo** [comment] 2021-06-27 15:15
If it's fixed, it's a win by technicality perhaps. The new UI won't allow concurrent imports so any race conditions are not likely to occur. My educated guess.

**Comment by wpferguson** [comment] 2021-06-27 15:34
There were a lot of changes to import for 3.6, so it could have gotten fixed just in the course of things.  Or as you say, by not doing concurrent imports.

You could change your script to trigger on post-import-film, and then process a complete directory at one time instead of running on each image.  Lua is single threaded and running an external executable takes time, so hammering it with concurrent events is probably a recipe for problems.

I noticed in one of the log outputs an error about concatenating a boolean.  You have to wrap a boolean with a tostring() call to print the value.

**Comment by progo** [comment] 2021-06-27 16:05
Regarding the lua error about concatenating a boolean, it was me chasing a wrong lead. 

Regarding lua having concurrency problems is probably something that should be mentioned in the documentation. Perhaps it is, it's been a while I last dabbled with lua with darktable. It's probably difficult making lua run in good isolation, the price of easy embeddability of a scripting engine.

Perhaps the key takeaway is that the problem is not solved and if concurrent imports are making a comeback in a later version this thing could resurface to someone.

**Comment by wpferguson** [comment] 2021-06-28 00:03
> Perhaps the key takeaway is that the problem is not solved

We can't reproduce the problem in 3.6.  The import code was reworked, so we don't know if the problem was solved in the rework or just doesn't appear because the imports aren't concurrent.

So do we leave this open because at some time in the future it might appear again, or do we close it and open a new problem if it reappears?

**Closed** 2021-06-28 06:31 UTC
Labels: lua, scope: DAM
