### ISSUE TITLE
MacOs - Replace unhandy Modifier key CTRL with CMD

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#4384] opened 2020-02-27 18:18 UTC
**Describe the bug**

Shortcuts - Modifier key on Mac is CMD (ex-Apple) not CTRL
Using the Control (Ctrl) key is unnatural and cumbersome on Apple Keyboards.  
CTRL is on the extreme left / extreme right on the last line of my keyboard and not side by side to the spacebar button.
I tried to add CMD to as Modifier key to the shortcuts i use, but Darktable is unable to detect CMD. If i press CMD+F, then DT registers only F. 

**Expected behavior**

Please re-place the modifier Key CTRL with CMD for Apple Users. 

**Platform:**
 - Darktable Version: 3.0.0
 - OS: MacOs: 10.14.6
 - OpenCL activated :  no
 - AMD Radeon HD 7970 3 GB

**Comment by Nilvus** [comment] 2020-02-27 19:53
It's more a feature request than a bug. First reason about that behavior is that darktable is at first a Linux software and is now a cross-platform one. For that, you should point some MacOS developer (like @parafin) to just see if a condition could be added (or the possibility to correctly detect CMD to let user modify shortcuts).

For other OS, actual behavior to need to be keep as it is.

**Comment by johans3** [comment] 2020-02-27 20:20
Yeah, first i wanted to send it as a feature req, but seeing that Darktable ignores a modifier key completely made me change idea. I hope this problem can be solved. As said before, keyboards are not all the same. I installed also Linux on my (Mac) machine, but that cannot solve the problem ;)

**Comment by parafin** [comment] 2020-02-27 21:29
First of all this a duplicate of #2322.
Secondly GTK has a concept of "<Primary>" key that can be used in accelerator strings, which resolves to GDK_CONTROL_MASK on Linux and GDK_META_MASK on macOS, as we need. The problem though is that darktable code uses GDK_CONTROL_MASK directly, so <Primary> doesn't really help. One need to change every occurrence of GDK_CONTROL_MASK with some other special platform-dependent define, or re-write key-bindings code to use strings instead.
Whatever you call it, bug or feature request, I have no interest in implementing it. I personally find it more consistent that Ctrl is used on every platform.

**Comment by johans3** [comment] 2020-02-27 22:19
sounds like a lot of work that you alone would have to carry, as there is not much people providing ports for Mac. 
Would you consider to talk with the whole team, about this topic, to alleviate the problem?

**Comment by johans3** [comment] 2020-03-04 13:41
![Gnome-Settings-Change keyboard layout](https://user-images.githubusercontent.com/48620536/75884408-08a42f00-5e25-11ea-8ee6-f4fd03e3d59b.png)

This are my keyboard settings for the ctrl key on Linux, using the gnome settings
I just switched the windows - keys with the ctrl key to get cmd as my default key instead, of ctrl

**Comment by johans3** [comment] 2020-04-11 07:39
> First of all this a duplicate of #2322.
The first report was ignored but the problem persists nevertheless. 

> Secondly GTK has a concept of "Primary" key that can be used in accelerator strings, which resolves to GDK_CONTROL_MASK on Linux and GDK_META_MASK on macOS, as we need. The problem though is that darktable code uses GDK_CONTROL_MASK directly, so Primary doesn't really help. One need to change every occurrence of GDK_CONTROL_MASK with some other special platform-dependent define, or re-write key-bindings code to use strings instead.

I fully subscribe what you said. This sounds troublesome, so the best would be to talk a bit with relevant developers of dt to seek some viable solution 

> Whatever you call it, bug or feature request, I have no interest in implementing it. I personally find it more consistent that Ctrl is used on every platform.

If the keystroke can't be changed directly then why not implementing a keystroke swap like, :
If the system is Mac OS, swap Ctrl with cmd / super / windows or whatever the main key is called

**Comment by AlfHou** [comment] 2020-11-02 11:14
I would like this "feature" as well

**Comment by rmens** [comment] 2020-12-24 23:12
I would like this feature as well. Darktable is great but this breaks my brain every time on macOS.

**Comment by rmens** [comment] 2021-01-24 09:33
> Please check if the master branch has fixed it and report again or close the issue.

The master branch has not fixed this in my latest test.

**Comment by dterrahe** [comment] 2021-03-12 19:31
Maybe some of the people on this thread would be willing to test if #8078 solves this issue?

If it does, please opine on whether this should be the only option on Macs or whether it should be the default but with an option to keep the current behavior for those who have gotten used to it.

**Comment by johnny-bit** [comment] 2021-06-29 09:40
Reminder: if you are able to - please test PR #8078 and does it fix your problems. It's a big PR so needs big testing :)

**Closed** 2021-07-02 13:09 UTC
Labels: bug: wip, scope: OS support
