### ISSUE TITLE
huge UX regression: very strange button ordering in darktable development

### ISSUE THREAD

**Issue by garrett** [darktable-org/darktable#14372] opened 2023-04-30 13:57 UTC
### Describe the bug

Hi! Firstly: Thanks for darktable! I use it a lot.

I'm a UX/UI designer working in FOSS for the past couple decades (since 1997) and have contributed to countless Free Software / Open Source projects and started several important FOSS initiatives over the years. I'm also a photographer and have been using darktable for a few years, and use GNOME on Fedora Linux.

Not only has the button order changed on dialogs in the last version or so of darktable to be more inconsistent that before, it's been altered for the worse in the development version of darktable.

This button order makes _absolutely no sense_. I discovered it when I kept clicking on "help" instead of "OK". It's super frustrating.

![image](https://user-images.githubusercontent.com/10246/235353049-79a0a8ce-e341-4ae3-80aa-5be0407062e6.png)

The order should be more like this quick screenshot modification:

![buttons-fix](https://user-images.githubusercontent.com/10246/235354757-f1f0bab3-51a9-4666-93f7-ae8031d0d458.png)

Explanation of the changes:
- This is right-aligned for the default action, which is the default on both many Linux desktops and macOS, and darktable _mostly_ tries to do right-aligned actions.
- Secondary actions are on the far side.
- The button spacing is 6px between sets of buttons (as it currently is in darktable) and there's 12px (2x the space) between select all and select none and the help button. In other words, button groups, when not at opposite ends, should be separated by 2x the normal space.
- Action verbs should be used for dialog buttons. Similar to how "Yes"/"No" should _always_ be avoided. "OK", should _usually_ be avoided if there's a better descriptive word. (In this case, the action is "Paste".)

The import dialog uses a similar convention, but also has a similar problem:

![image](https://user-images.githubusercontent.com/10246/235353518-36b91fa7-e698-4634-b2e4-63441b0a6de4.png)

It would look something like this instead:

![image](https://user-images.githubusercontent.com/10246/235355528-549f0141-a8f2-4e40-a3db-ae7ef6bef79e.png)

Additionally, resetting an image has a yes/no (which is a bad anti-pattern and should have actions such as cancel/reset instead). This used to be the other order the release before last, but was flipped and is inconsistent with most other dialogs in darktable (and I've been hitting the wrong action half the time since the last release):

![image](https://user-images.githubusercontent.com/10246/235353544-42000ca4-b10f-4463-a620-408d757cf1da.png)

It should be more like this:

![history reset](https://user-images.githubusercontent.com/10246/235356656-d0b58bfb-6861-4d77-b174-994e43971408.png)

Saving and editing profiles has similar issues:

![image](https://user-images.githubusercontent.com/10246/235353583-9e020e87-11d7-44c5-beea-2f778764af6e.png)

It should probably be:

- Left side:
   - Export...
   - Delete
   - _space_
   - Help
- Right side:
   - Cancel
   - Save

Which would look like this:

![image](https://user-images.githubusercontent.com/10246/235355826-fad22ce5-4cf6-420e-a3f1-3a85cd056245.png)

Additionally, it would be nice to have the default expected action highlighted. GNOME, macOS, and Windows all do this. It's usually a different shade/color on a button, but could also be bolding the button as well.

- GNOME HIG on suggested buttons (and destructive buttons): https://developer.gnome.org/hig/patterns/controls/buttons.html#button-styles
- Apple's HIG is similar, with suggested buttons also styled differently: https://developer.apple.com/design/human-interface-guidelines/components/menus-and-actions/buttons
- Windows design guidelines on buttons: https://learn.microsoft.com/en-us/windows/apps/design/controls/buttons#examples

In a few places, darktable does seem to use suggested buttons, such as the history reset. (It's odd that the reset action is not the default though, as that was what was asked for.)

...but adopting default buttons everywhere would probably need to be another issue. A sensible and consistent button order is more important.

### Steps to reproduce

1. Open any dialog in darktable. Many are now super-inconsistent with any OS and desktop.

### Expected behavior

darktable should use dialogs that follow common expected conventions; at a minimum, darktable should at least be consistent with itself

### Where did you install darktable from?

OSB

### darktable version

4.3.0~git2027.2b3d5ec0-9882.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38 Silverblue

### Describe your system?

AMD Ryzen 5 5600X
AMD RX 6700XT GPU
32 GiB RAM
X11 (for color management support)
GNOME 44.1
GTK 3.24.37

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD RX 6700XT GPU /

**Comment by garrett** [comment] 2023-04-30 14:00
Oh! I just saw a PR that was merged over the past day (and isn't in my build of darktable):

- https://github.com/darktable-org/darktable/pull/14363

Excellent! This might resolve some of the issues I pointed out above.

However, even after the change, darktable is probably inconsistent with itself across dialogs, which _is_ still covered in this issue.

**Comment by MStraeten** [comment] 2023-04-30 16:52
not really:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/39386816/235360152-15ec04f8-c4c6-495e-bb1c-47bf538d56a2.png">

it make sense to define some rules for placing the buttons - according to your (and e.g. apple) suggestion:

Primary - the button most likely to choose is default if not destructive --> rightmost
Cancel - left of primary on the right side and default if destructive to prevent loss of stuff by just hitting enter

already usual in ok / cancel dialogs 
toDo: 
- history dialog
- styles dialog
- accelerators > restore shortcuts (since there's no ok but just destructive functional buttons cancel should be rightmost
- presets

suggestion: #14379

Secondary buttons - on the left side in a functional order
most likely function leftmost
help rightmost on the left side. --> I'm not convinced with the leftmost help button (also the size needs to be tweaked)

**Comment by Nilvus** [comment] 2023-04-30 18:38
@garett: I've put just yesterday an issue about that (and fix was merged yesterday), a day before so yours. See: #14359. So this one is a duplicate. And now, that main issue had been fixed, this issue may be closed.

I read your last comments where you say: "This might resolve some of the issues I pointed out above.
However, even after the change, darktable is probably inconsistent with itself across dialogs, which is still covered in this issue."

As issue is so different, even if it's related, I suggest to close that issue and that you create a new one for inconsistencies you see, with fixes you suggested. I'm sure there's some, I have less time to spent on UX/UI.

**Closed by Nilvus** 2023-04-30 18:38 UTC

**Comment by MStraeten** [comment] 2023-04-30 19:05
the help button is just one part of the ux related issue here - so why closing this if the topic isn’t even discussed.
I haven’t seen a further issue addressing those button order or naming stuff, so not sure why ‚duplicate‘

**Comment by Nilvus** [comment] 2023-04-30 19:29
I explain this on my comment. I could reopen it but I fear discussing ordering would be better on a new issue than this one. Order, except help bitton added, is there since a time.
So title and main comment about UX regression is fixed.

**Comment by Nilvus** [comment] 2023-04-30 19:31
I edit my last comment made on phone and posted with errors. So think about reading it on github. Thanks

**Comment by Nilvus** [comment] 2023-04-30 19:38
And what remains is more feature request (enhancement) than a bug, as it was designed as is and need to be improved.

**Comment by garrett** [comment] 2023-05-01 15:49
Hey, thanks for the update (even before I filed it :wink:)! It's a lot better now.

It could be improved further, but that's probably a bikeshedding discussion. Meanwhile, it's all un-broken now, so that's the most important thing. Thanks again!
