### ISSUE TITLE
Performance degradation on old edits

### ISSUE THREAD

**Issue by jakubfi** [darktable-org/darktable#6708] opened 2020-11-01 14:33 UTC
**Description**

When I was trying to modify one of my older edits I've noticed that the performance is _heavily_ degraded. And it's not the image processing, rather the UI is sluggish due to some background task using one CPU core. Basically any operation on any module (enabling or disabling it, changing parameters) hangs the software for about two seconds. Problem goes away when I duplicate the image and reapply the edit history.

**To Reproduce**
1. Download the test image+xmp: http://spin.ict.pwr.wroc.pl/amo/test.zip
1. Import the test image
1. Go to darkroom and enable highpass filter (I've used this particular one as its effects are clearly visible) - note the time to apply the module, also observe the CPU usage pattern.
1. Go back to lighttable
1. Duplicate the image
1. Discard history for the duplicate
1. Select the original image, copy the whole history stack and paste it onto the duplicated image
1. Open the duplicate in darkroom and once again enable highpass filter - now everything works as expected.

**Platform**
 - Version: darktable-master
 - OS: Gentoo
 - tested with both OpenCL enabled and disabled
 - Intel Corporation UHD Graphics 630 (Desktop 9 Series)

**Comment by jakubfi** [comment] 2020-11-01 15:17
Sone more info:
- starting dt with a fresh config doesn't help
- dt compiled "by hand" - same behavior
- I wen't back to ccb6d04fb - same behavior

**Comment by MStraeten** [comment] 2020-11-01 19:33
There are a couple of performance improvements just merged into master so wait for Christmas ;)

**Comment by jakubfi** [comment] 2020-11-01 20:50
> There are a couple of performance improvements just merged into master so wait for Christmas ;)

This was tested on master and it looks either like a regression or a weird corner case.

**Comment by ralfbrown** [comment] 2020-11-01 21:18
MStraeten did mean "just now", as in since you opened this issue :-).  One of the improvements merged today is for the highpass module, doubling its speed when running on a single core, and letting it actually take advantage of multiple cores (it now runs 19 times as fast on a 32-core system as it did yesterday).

**Comment by jakubfi** [comment] 2020-11-01 21:33
I've used highpass as an example here. As stated in the issue description, this has probably nothing to do with image processing performance. My best guess ATM is that it is related to the number of shapes stored in the XMP.

**Comment by ralfbrown** [comment] 2020-11-01 21:51
I just looked at your example, and can confirm that it spends a lot of time without a lot of CPU activity.   Running with -d all reveals a huge number of database calls for masks before doing anything with the image, and looking at mask manager reveals an enormous number of masks (which also explains the enormous size of the .xmp).  After copying the history, you're left with just a single mask, and the sidecar file shrinks to a more normal size (16k instead of 445k).

So it's more a case of a pathological sidecar file than a darktable problem, but it should still be addressed if there's a relatively simple fix.
(Much as the devs have recently added parameter validation and sanitization.)

**Comment by elstoc** [comment] 2020-11-01 23:17
If you've historically used a lot of shapes on an image it's basically up to you to clean them up - darktable will retain them in case you want to reuse them later. There is an option in the right-click menu in the mask manager to 'clean up unused shapes' but I'm not sure it works correctly (or if it does then I don't understand exactly what it's intended to do). You can delete them manually though - I believe unused shapes are at the bottom of the list in the mask manager and don't have a group icon to the right of them. Just select them all, right-click and choose "delete this shape"

**Comment by jenshannoschwalm** [comment] 2020-11-02 06:54
If history is compressed the masks loose the ownership of a module, are assigned to the mask-manager as owner and can *not* be deleted any more. Very tricky stuff.

**Comment by elstoc** [comment] 2020-11-02 08:04
> are assigned to the mask-manager as owner

Even if they are still used by a module's mask? I cannot reproduce this - if I reset parameters on a module the shapes remain but they no longer show as part of the mask group. Presumably the reset function can ignore the mask manager when it iterates through the history - if a shape is used by the mask manager and another module it won't be deleted? Unless I'm misunderstanding (I've only briefly glanced at the code).

**Comment by elstoc** [comment] 2020-11-02 08:49
I think I've fixed the broken "cleanup unused shapes" functionality in #6719.

**Comment by jenshannoschwalm** [comment] 2020-11-02 09:07
I am not sure about your pr so far, can't test.

I was speaking about history compression.

**Comment by elstoc** [comment] 2020-11-02 09:13
As far as I can tell, the shapes are retained (by "clean up unused shapes") if they belong to any module in the history stack. If you use a module in a mask and then later reset that module's parameters, the shapes are still owned by the mask from the earlier edit so are retained. If you compress history then ownership reverts to the mask manager module (because the earlier edit no longer exists). The above PR basically says that if the only owner of the shape is the module manager, then it is no longer used and should be removed.

**Comment by jenshannoschwalm** [comment] 2020-11-02 09:46
You are right except it's not belonging to a module but history step. As these are reordered while compressing history it was too difficult to re-reference to the module and the masks was assigned to 0 being the mask manager.

**Comment by HansBull** [comment] 2020-11-02 11:16
DB queries on masks_history table in dt_history_compress_on_image involve both imgid and num columns, maybe the corresponding masks_history_imgid_index should cover both of them?

**Comment by jenshannoschwalm** [comment] 2020-11-02 12:01
The compression of history is really tricky, I worked on that quite a lot a while ago and was not able to find a better solution. At least it's correct and safe now with just one minor issue.

You can forget masks as you like while developing but can't do that after compression of history any more. But you can re-use those masks later if you want to do so.

**Comment by jakubfi** [comment] 2020-11-02 16:32
This sidecar is definitely a pathological case and I can't remember how it got to that state. This wasn't intentional, that's for sure. But I don't remember it being a performance problem back when I was editing the image (on a ~2x slower system, btw).
In the meantime I've tried to "cleanup unused shapes" and it solves the problem for me. It also does one weird thing: it enables recently disabled module... But that's another issue, I guess.
Thanks guys!

**Closed** 2021-11-21 10:24 UTC
Labels: no-issue-activity
