### ISSUE TITLE
images won't open, program freezes

### ISSUE THREAD

**Issue by petercfischer** [darktable-org/darktable#7492] opened 2020-12-27 12:19 UTC
>when we go from lighttable to darktable with a pre selected image it will open
>if we are in lighttable and select a second image the program freezes
>if we select a neh image in GIMP the program works as it should and opens the image in DT where we can edit to our heart's content...when image is closed it return as it should to GIMP where it is display in the workspace with the DT edits intact

 
>!-- IMPORTANT
Bug reports that do not make an effort to help the developers will be closed without notice.
Make sure that this bug has not already been opened and/or closed by searching the issues on GitHub, as duplicate bug reports will be closed.
A bug report simply stating that Darktable crashes is unhelpful, so please fill in most of the items below and provide detailed information.
-->

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

**Additional context**

**Comment by johnny-bit** [comment] 2020-12-27 14:04
> if we are in lighttable and select a second image the program freezes

Cannot replicate on neither 3.4.0 nor current master 3.5.0+208

> if we select a neh image in GIMP the program works as it should and opens the image in DT where we can edit to our heart's content...when image is closed it return as it should to GIMP where it is display in the workspace with the DT edits intact

What's a "neh image"? you mean "NEF" as in the Nikon's RAW format? I actually don't understand this bit: "when image is closed it return as it should to GIMP where it is display in the workspace with the DT edits intact" - you mean that darktable <=> gimp integration is working correctly or not?

Also: You haven't specified your darktable version, OS (and it's version), whether you have OpenCL enabled or not... Please edit your report and include all the required info.

**Comment by AxelG-DE** [comment] 2020-12-27 14:07
I recommend to close this as it is a duplicate of #7491

**Comment by johnny-bit** [comment] 2020-12-27 14:19
Duplicate of #7491

**Closed by johnny-bit** 2020-12-27 14:19 UTC
Labels: understood: unclear
