### ISSUE TITLE
Cannot load the maps

### ISSUE THREAD

**Issue by atriantas** [darktable-org/darktable#17703] opened 2024-10-22 09:06 UTC
### Describe the bug

When I am clicking to go at the Maps workspace the program freezes. After some time, it shows me the Map workspace but the maps never load and the area is plain white. 
![Darktable Maps](https://github.com/user-attachments/assets/3263d061-cb86-4322-afe1-4485bb3227a4)

### Steps to reproduce

The issue is always happening at my primary PC but not at my secondary.

### Expected behavior

darktable should show the maps at Map Workspace

### Logfile | Screenshot | Screencast

(darktable.exe:18496): OsmGpsMap-WARNING **: 01:27:59.234: Error getting missing tile
'C:\Program Files\darktable\lib\gio\modules\libgiolibproxy.dll': The specified module could not be found.
Failed to load module: C:\Program Files\darktable\lib\gio\modules\libgiolibproxy.dll

(darktable.exe:18496): OsmGpsMap-WARNING **: 01:32:32.062: Error getting missing tile

(darktable.exe:18496): OsmGpsMap-WARNING **: 01:32:32.063: Error getting missing tile

(darktable.exe:18496): OsmGpsMap-WARNING **: 01:32:32.064: Error getting missing tile

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10 Pro Version 22H2

### Describe your system?

Intel(R) Core(TM) i7 CPU 920  @ 2.67GHz
NVIDIA GeForce GTX 660
RAM 6,00 GB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 660, 2048 MB GDDR 5, Driver Version 475.06

**Comment by victoryforce** [comment] 2024-10-24 09:42
> 'C:\Program Files\darktable\lib\gio\modules\libgiolibproxy.dll': The specified module could not be found.

@atriantas Please check whether this DLL file exists in the specified path. It is very possible that some inadequate antivirus deleted (or quarantined) it.

**Comment by wpferguson** [comment] 2024-10-24 16:27
I can reproduce on my weekly builds.  I checked and the module is there and in the correct place.

**Comment by pehar1** [comment] 2024-10-25 07:23
4.9.0+918~g9cc90ba804, Ubuntu 24.04
I do **not** get an empty (white) map, the map is correctly shown, but I get a large number of `OsmGpsMap-WARNING`, `GLib-GObject-CRITICAL` and `GdkPixbuf-CRITICAL` messages :

```
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.055: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.105: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.105: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.105: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.105: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.105: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.105: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.105: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.105: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile                               
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.106: Error getting missing tile
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.107: Error getting missing tile
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.107: Error getting missing tile
(darktable:7403): GdkPixbuf-CRITICAL **: 09:09:45.351: gdk_pixbuf_new_from_data: assertion 'width > 0' failed
(darktable:7403): GLib-GObject-CRITICAL **: 09:09:45.352: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed
(darktable:7403): GdkPixbuf-CRITICAL **: 09:09:45.352: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed
(darktable:7403): GLib-GObject-CRITICAL **: 09:09:45.352: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
(darktable:7403): OsmGpsMap-WARNING **: 09:09:45.352: Error getting missing tile
(darktable:7403): GdkPixbuf-CRITICAL **: 09:09:45.352: gdk_pixbuf_new_from_data: assertion 'width > 0' failed
(darktable:7403): GLib-GObject-CRITICAL **: 09:09:45.352: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed
(darktable:7403): GdkPixbuf-CRITICAL **: 09:09:45.352: gdk_pixbuf_scale_simple: assertion 'GDK_IS_PIXBUF (src)' failed
(darktable:7403): GLib-GObject-CRITICAL **: 09:09:45.352: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

and much more ...
```

**Comment by victoryforce** [comment] 2024-11-12 09:30
My observations:

- On the day when this issue was raised, I tried to open the map and, likewise, I saw a white field instead of the map for a very long time. A very long time, tens of seconds. Then, very slowly, the tiles began to be loaded. The app didn't really freeze though, I could switch between modes (although the response when switching from map mode felt a little slow).

- I did not see in the log notifications about the problem with finding and loading libgiolibproxy.dll. I don't know if this problem is somehow related to the problem of getting tiles from the map service.

- I see a lot (hundreds!) of "Error getting missing tile" messages even now when the map is loading at an acceptable speed.

- To me it looks like a problem with the map service that we can't fix on the darktable side.

- We haven't received any further comments from @atriantas in three weeks, so we can't draw any further conclusions or test any assumptions.

- In such a situation, I think it would be best to close this issue. If the originator of the issue wants to say something (or someone else reproduces all the same symptoms), we can always reopen.

**Comment by atriantas** [comment] 2024-11-12 11:49
Sorry for the late reply. I think it is something wrong with my PC.
I tried copying the .dll from the PC that Darktable works.
I disable firewall and cleared hosts file but nothing worked.
I gave up on the issue because it is a feature that I rarely use.

**Comment by victoryforce** [comment] 2024-11-13 09:45
Have you tried selecting a different map source? If no other map service is working, this indicates that the problem is not in the map service, but in the unavailability of the network for darktable.

In addition to the hosts file and the system firewall, an antivirus kit can also block the Internet connection. By the way, the freezing of the program, which you write about, indicates that it is possible that the outgoing packets are simply dropped along the way. This is very similar to the effect of a firewall (if not a system one, then in an antivirus kit) that is configured to DROP outgoing packets instead of REJECT.

**Closed** 2024-11-14 20:08 UTC
Labels: reproduce: confirmed, scope: windows support
