### ISSUE TITLE
it terminated and the interface setting appears to be lost

### ISSUE THREAD

**Issue by Lorenzoeffe** [darktable-org/darktable#7467] opened 2020-12-26 15:07 UTC
Describe the bug
After a few minutes of work, when using the "tone mapping" tool, the application closed.
This was the screen when I restarted the application.
The interface setting appears to be lost and the application also no longer responds correctly to commands.
From further tests made, the behavior is repeated at each modification of the application settings.
The application also no longer responds correctly to commands.

To Reproduce
I don't understand how to reproduce the behavior as it occurs every time the application settings are changed.

Expected behavior
The interface setting appears to be lost and the application also no longer responds correctly to commands.
From further tests made, the behavior is repeated at each modification of the application settings.
The application also no longer responds correctly to commands.

Screenshots
Attached

Platform:
 - Darktable Version: 3.4
 - OS: Windows 10 Pro 20H2 Build 19042.685
AMD Ryzen 7 1800X
32GB RAM
Radeon RX560 4GB Driver 20.11.3
Windows 10 Pro 20H2 Build 19042.685
 OpenCL activated or no? --> NO, the same behavior also occurs after activation

Additional context:
Going to the path "C:\Users\xxx\AppData\Local\darktable" and deleting all the configuration files in the folder, DarkTable returns to work correctly, a reset is performed.
![006](https://user-images.githubusercontent.com/50571973/103153876-3b445d00-4794-11eb-9e47-303894998c3b.jpg)

**Comment by johnny-bit** [comment] 2020-12-26 15:15
What do you mean by "the behavior is repeated at each modification of the application settings."? You mean you can replicate the behaviour every time you modify preferences?

IMO the issue is caused by antivir software blocking darktable from accessing proper files. Try to make sure your antivir knows that darktable isn't a malware. Many antivirs seem to think GTK apps are evil.

**Comment by Lorenzoeffe** [comment] 2020-12-26 15:26
_What do you mean by "the behavior is repeated at each modification of the application settings."? You mean you can replicate the behaviour every time you modify preferences?_ YES

_IMO the issue is caused by antivir software blocking darktable from accessing proper files. Try to make sure your antivir knows that darktable isn't a malware. Many antivirs seem to think GTK apps are evil._ NO

I just disabled Karspersky and tried to change the application settings, enabling OpenCL support.
I got the same result.

**Comment by johnny-bit** [comment] 2020-12-26 15:38
If you open up darktable with no configs, close it changing nothing and re-open - does the interface still look ok or is it mangled?

**Comment by cerlienkus** [comment] 2020-12-26 17:03
Hello,
If you check issue #7469 it describes my symptoms for a problem wich seems very similar to the above one.
I've Norton 360 wich found the installer secure.
Thanks

Maurizio

**Comment by johnny-bit** [comment] 2020-12-26 17:12
Can you both make sure that darktable is "known good" to antivirus? Antivirs/antimalware/antiransomware stuff often lurks in the background blocking legitimate writes in hopes of preventing attack.

**Comment by Lorenzoeffe** [comment] 2020-12-26 17:30
I have set 2 specific rules in the antivirus, so that they exclude folders:
"C: \ Program Files \ darktable"
"C: \ Users \ xxx \ AppData \ Local \ darktable"
The problem persists.
If I open / close DarkTable and use the software I have no problems.
If, on the other hand, in any work session, I access the settings, the problem occurs at the next restart of the application.

**Comment by cerlienkus** [comment] 2020-12-26 17:45
> Can you both make sure that darktable is "known good" to antivirus? Antivirs/antimalware/antiransomware stuff often lurks in the background blocking legitimate writes in hopes of preventing attack.

I use Norton 360 and when I downloaded and installed, it raised no alarms.
Scanned darktable in directories "C: \ Program Files \ darktable" and "C: \ Users \ xxx \ AppData \ Local \ darktable" with no issues or warning whatsoever.
Now I've excluded dt from scanning. Let's see what happens.
Thanks

Maurizio

**Comment by cerlienkus** [comment] 2020-12-26 18:47
> > Can you both make sure that darktable is "known good" to antivirus? Antivirs/antimalware/antiransomware stuff often lurks in the background blocking legitimate writes in hopes of preventing attack.
> 
> I use Norton 360 and when I downloaded and installed, it raised no alarms.
> Scanned darktable in directories "C: \ Program Files \ darktable" and "C: \ Users \ xxx \ AppData \ Local \ darktable" with no issues or warning whatsoever.
> Now I've excluded dt from scanning by Norton. Let's see what happens.
> Thanks
> 
> Maurizio

Sorry but no result. Closed dt and reopened with the same issue.

Maurizio

**Comment by cerlienkus** [comment] 2020-12-26 19:56
Hi,
I've reinstalled dt for the nth time!
Can this issue be caused by this?

![image](https://user-images.githubusercontent.com/69572937/103158276-2d0a3700-47bc-11eb-8075-7a3e9320a644.png)

I'll try to set the answer to "remind me later" every time before closing the program to see if the next time settings remain unchanged.

I'll keep you updated.

Thanks for your help.

Maurizio

**Comment by cerlienkus** [comment] 2020-12-27 11:04
Hello,
I unistalled and reinstalled back from scratch.
GUI appeared normal.
Accessed the preferences panel without making any change.
The GUI appeared like this:

![image](https://user-images.githubusercontent.com/69572937/103169368-3a1a3b00-483b-11eb-90a4-1dcc7275294c.png)

Imported a folder. This is the result of selecting an image:

![image](https://user-images.githubusercontent.com/69572937/103169396-849bb780-483b-11eb-9009-9ec14eb3f0e9.png)

with no histogram

Now I'm going to revert to the older version.

Maurizio Cerlienco

**Comment by TurboGit** [comment] 2020-12-27 11:16
> with no histogram

Read the doc, this can be collapsed.

> The GUI appeared like this:

Broken, removing any CSS installed or clean-up **install dir**.

> Now I'm going to revert to the older version.

Which will not solve the issue...

**Comment by cerlienkus** [comment] 2020-12-27 13:57
@Lorenzoeffe ,
If you have the css modify theme flagged on in the general panel in preferences, switch it off like below

![image](https://user-images.githubusercontent.com/69572937/103172431-abfe7e80-4853-11eb-9214-dc52d522f933.png)

It solves this issue!

Maurizio

**Comment by johnny-bit** [comment] 2020-12-27 14:13
Interestingly disabling css tweaks is a workaround. Probably this means that the way custom css works is a bit incompatible with your windows setup...

I wonder - does your username in windows and therefore your user dir contains special diacritic characters/accent marks? Perhaps the issue is due to the fact that on linux/mac pathnames are utf8 while on windows pathnames are utf16

**Comment by cerlienkus** [comment] 2020-12-27 14:48
> Interestingly disabling css tweaks is a workaround. Probably this means that the way custom css works is a bit incompatible with your windows setup...
> 
> I wonder - does your username in windows and therefore your user dir contains special diacritic characters/accent marks? Perhaps the issue is due to the fact that on linux/mac pathnames are utf8 while on windows pathnames are utf16

Hi,
No, this is not my case. The name in the user directory doesn't have any special character.

Maurizio

**Comment by Lorenzoeffe** [comment] 2020-12-27 16:09
Actually the quick method works, disabling the change to the css, the problem is solved.
Also in my case, the username or the path in general, have no particular characters and have no symbols, except the /

**Comment by johnny-bit** [comment] 2020-12-27 16:16
So... This might be how CSS is loaded in windows :/ Pinging @elstoc for custom css insights... however afaik nothing in CSS loading changed since 3.2.1

**Comment by elstoc** [comment] 2020-12-27 18:09
Probably need a Windows dev to look at this.

**Comment by elstoc** [comment] 2020-12-27 18:38
@Lorenzoeffe out of curiosity what happens if you instead click the "save and apply" button on the CSS edit screen?

**Comment by Lorenzoeffe** [comment] 2020-12-27 21:56
I ran some tests:
if the css theme change is active, on the next restart, the described problem occurs
if the theme change is not active or is disabled when the problem occurs after restart, the problem is resolved
clicking on the "save and apply" button seems to have no effect

**Comment by johnny-bit** [comment] 2020-12-27 22:16
"no effect" means... well... we would need to give you visible change... Hmmm... failure to setup css leads to output being writen to log. need a way on windows to tell you what to look for. darktable should spew quite a lot of those actually...

**Comment by Lorenzoeffe** [comment] 2020-12-27 22:33
Ok, if you tell me how, I can try and let you have feedback

**Comment by johnny-bit** [comment] 2020-12-28 12:58
Please look for any files in `C:\Users\username\AppData\Local\Microsoft\Windows\Temporary Internet Files\darktable\` and/or in `C:\Users\username\AppData\Local\Temp\darktable*`

**Comment by Lorenzoeffe** [comment] 2020-12-28 15:56
Hello, I checked and at the first path there are some files that I can attach if I want I tried to "recreate" the problem concerning the CSS; and none of the files in those folders are written or modified.
The "darktable-log.txt" file is empty.

Instead I noticed that by "deactivating" the CSS theme change and clicking on "apply and save" the summary sign is automatically resected, if instead, once deselected I close the settings window, it remains in that mode

**Comment by johnny-bit** [comment] 2020-12-28 16:30
Yeah, please attach files. Just make sure to remove old files, start darktable, reproduce problem and attach all newly created log files.

Thanks!

**Comment by Lorenzoeffe** [comment] 2021-01-02 11:09
.ZIP Interface error
.txt various error 
[darktable.zip](https://github.com/darktable-org/darktable/files/5760142/darktable.zip)
[darktable_bt_GCL0V0.txt](https://github.com/darktable-org/darktable/files/5760143/darktable_bt_GCL0V0.txt)

**Comment by johnny-bit** [comment] 2021-01-02 18:32
OK, in `darktable_bt_GCL0V0.txt` it shows DEP violation error which can ONLY mean 3 (well, actually 4, but darktable isn't malware and the package itself isn't malware) things: crappy antivir, crappy windows kernel stuff or overheating/faulty CPU.

the issue is in `g_malloc` which we use to allocate memory in many ways across whole darktable and SOMETHING is messing with it...

On the ohter hand in zip there's nothin in darktable-log which is weird since interface problem or problems with css are NOISY in logs. The only thing I see is that you have Baffin architecture AMD GPU, so you might want to try and upgrade drivers, those might mess with OpenCL processing...

I think in order to better debug the issue I'd need you to try and run debug version of darktable (however it's not really available right now, you'd have to self-compile it using https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.txt instructions but instead of "Release" build "RelWithDebInfo" package)

**Comment by elstoc** [comment] 2021-02-21 17:31
This has also been reported on the mailing list, this time on Linux ([here](https://www.mail-archive.com/darktable-dev@lists.darktable.org/msg06154.html)), so I think we have to consider that this might not be an OS support issue. I still can't reproduce though, which makes it hard to suggest a resolution.

**Comment by elstoc** [comment] 2021-06-24 09:46
This could be a translation issue. See https://discuss.pixls.us/t/solved-image-stuck-on-background-in-lighttable-and-no-selection-showing-user-css-issue/

**Closed** 2021-07-03 09:43 UTC
Labels: bug: pending, scope: UI, scope: translation
