### ISSUE TITLE
Sony ILCE-6700

### ISSUE THREAD

**Issue by robertgalambos** [darktable-org/darktable#15089] opened 2023-08-20 10:10 UTC
New camera from Sony.
Already contributed the whole raw sample to https://raw.pixls.us/
Seems to be similar to 6600 file format...maybe fully the same.

**Comment by kmilos** [comment] 2023-08-20 11:13
Duplicate of https://github.com/darktable-org/rawspeed/issues/507 and https://github.com/darktable-org/darktable/issues/15014

Please search before opening new issues.

**Closed** 2023-08-20 11:14 UTC
Labels: duplicate, scope: camera support
