### ISSUE TITLE
Enabling profiled denoise results in corrupted image display

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#6320] opened 2020-09-18 04:01 UTC
**Describe the bug**
When opening any photo that has profiled denoise applied, the thumbnail in the filmstrip, the navigator display, and the histogram all become corrupted. Additionally, this can be reproduced when enabling profiled denoise on any image.
Disabling OpenCL leads to the main image window also being corrupted.

**To Reproduce**
1. Pick a photo.
2. Enable profiled denoise
3. Observe the effect seen in the screen shot.

**Expected behavior**
I expect there to be a correctly rendered image in thumbnail, histogram, and navigator display.

**Screenshots**
[![No-Denoise.png](https://i.postimg.cc/yNbrjY0t/No-Denoise.png)](https://postimg.cc/cKfm4W9B)
[![With-Denoise.png](https://i.postimg.cc/d3MNMHH9/With-Denoise.png)](https://postimg.cc/ZBcxpch9)

**Platform (please complete the following information):**
```
this is darktable 3.3.0+771~g1d309c9db
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support disabled
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```
 - Darktable Version: 
 - OS: archlinux
 - Yes/No
 - OpenCL: Intel NEO on skylake

**Comment by groutr** [comment] 2020-09-20 17:57
Further testing reveals that the only affected modes seems to be the non-local means modes. Wavelets work as expected.

**Comment by johnny-bit** [comment] 2020-09-22 10:03
Cannot replicate on 3.3.0+792~g435335440 with your settings on nvidia-based system. regardless if opencl is enabled or not.
if main window is corrupted after disabling opencl I'd recommend you try to either removing intel's opencl drivers totally or compile darktable without opencl enabled and see if you still have problem.

**Comment by groutr** [comment] 2020-09-23 06:31
When trying to disable opencl at compile-time, darktable fails to compile on my machine
```
[ 35%] Building C object src/CMakeFiles/lib_darktable.dir/develop/tiling.c.o
In file included from /home/xxxxxx/tmp/dt2/src/develop/pixelpipe.c:22:
/home/xxxxxx/tmp/dt2/src/develop/pixelpipe_hb.c: In function ‘dt_dev_pixelpipe_process_rec’:
/home/xxxxxx/tmp/dt2/src/develop/pixelpipe_hb.c:1875:52: error: passing argument 4 of ‘pixelpipe_process_on_CPU’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1875 |     if (pixelpipe_process_on_CPU(pipe, dev, input, &roi_in, input_format, output, out_format, roi_out,
      |                                                    ^~~~~~~
      |                                                    |
      |                                                    dt_iop_roi_t *
/home/xxxxxx/tmp/dt2/src/develop/pixelpipe_hb.c:980:72: note: expected ‘dt_iop_buffer_dsc_t *’ but argument is of type ‘dt_iop_roi_t *’
  980 |                                     float *input, dt_iop_buffer_dsc_t *input_format, const dt_iop_roi_t *roi_in,
      |                                                   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/home/xxxxxx/tmp/dt2/src/develop/pixelpipe_hb.c:1875:61: error: passing argument 5 of ‘pixelpipe_process_on_CPU’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1875 |     if (pixelpipe_process_on_CPU(pipe, dev, input, &roi_in, input_format, output, out_format, roi_out,
      |                                                             ^~~~~~~~~~~~
      |                                                             |
      |                                                             dt_iop_buffer_dsc_t *
/home/xxxxxx/tmp/dt2/src/develop/pixelpipe_hb.c:980:106: note: expected ‘const dt_iop_roi_t *’ but argument is of type ‘dt_iop_buffer_dsc_t *’
  980 |                                     float *input, dt_iop_buffer_dsc_t *input_format, const dt_iop_roi_t *roi_in,
      |                                                                                      ~~~~~~~~~~~~~~~~~~~~^~~~~~
[ 35%] Building C object src/CMakeFiles/lib_darktable.dir/dtgtk/button.c.o
cc1: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/lib_darktable.dir/build.make:1323: src/CMakeFiles/lib_darktable.dir/develop/pixelpipe.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2236: src/CMakeFiles/lib_darktable.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```
I doubt OpenCL is a major factor here. My drivers have been version pinned for some time and worked fine with my previous compiled version of darktable.

Bisecting recent commits in darktable isolated this commit (from PR #5974).
```
3aaa08367b1be0300290173ec7e896798a1ae16b is the first bad commit
commit 3aaa08367b1be0300290173ec7e896798a1ae16b
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Fri Aug 21 23:14:04 2020 -0400

    switch denoise(profiled) to use new nlmeans code

 src/iop/denoiseprofile.c | 928 ++++++++++++++++-------------------------------
 1 file changed, 313 insertions(+), 615 deletions(-)
```

**Comment by johnny-bit** [comment] 2020-09-23 07:34
Interesting...

Pinging @ralfbrown :) If you have time, can you look at this?

**Comment by ralfbrown** [comment] 2020-09-23 17:07
Won't be able to get to it for a while.  Since I've used the non-CL nlmeans in both denoise(profiled) and denoise(nlmeans) on a bunch of photos myself, obviously I wasn't having any issue.  So it's likely I won't be able to replicate.

@groutr I recall mention of a compiler bug in GCC 10.x.0 (was it 10.2?), so can you try compiling with a different version of GCC?

**Comment by groutr** [comment] 2020-09-23 18:15
I downgraded my gcc to 10.1, but it does not resolve the issue.

Oddly, only the denoise(profiled) seems to be affected. When I tried the denoise(nlmeans) no issues are noticed.

**Comment by groutr** [comment] 2020-09-26 05:19
Another update: I can pretty regularly crash darktable by manipulating the sliders in denoise(profile). While I can't pin it down to a specific setting, if I adjust the sliders long enough, darktable will segfault.

**Comment by groutr** [comment] 2020-09-29 01:17
@TurboGit, thanks for fixing this: https://github.com/darktable-org/darktable/commit/a4c38b807b6098d3ca6f50192b3a086a00d62d36

I recompiled dt (3.3.0+869~gc5d05c948) without opencl support. I can still reproduce the both the artifact and the crash that I reported above.

**Comment by TurboGit** [comment] 2020-09-29 05:49
I have not fixed anything, the code I changed was not used except if darktable **compiled** with OpenCL and in this case the compiler was complaining about wrong code.

**Comment by ralfbrown** [comment] 2020-10-01 02:54
Unable to reproduce using the posted .xmp with either my distro's official 3.2.1 build or a late-August git-master build.

**Comment by groutr** [comment] 2020-10-01 03:40
@ralfbrown, may I ask what version of gcc your dt was compiled with? Perhaps I could try with that version.
I tried with an config directory and I can still reproduce the crash on my machine. I was able to obtain a coredump of darktable at the time of crash. I can try to upload the file if that is needed.
Output from coredumpctl
```
Stack trace of thread 664203:
                #0  0x00007f68d3603615 raise (libc.so.6 + 0x3d615)
                #1  0x00007f68d35ec862 abort (libc.so.6 + 0x26862)
                #2  0x00007f68d36455e8 __libc_message (libc.so.6 + 0x7f5e8)
                #3  0x00007f68d364d27a malloc_printerr (libc.so.6 + 0x8727a)
                #4  0x00007f68d364eb0c _int_free (libc.so.6 + 0x88b0c)
                #5  0x00007f68d38bf7ef nlmeans_denoise_sse2 (libdarktable.so + 0xf07ef)
                #6  0x00007f68a8dc9576 process_nlmeans_cpu (libdenoiseprofile.so + 0xb576)
                #7  0x00007f68d3952bde pixelpipe_process_on_CPU (libdarktable.so + 0x183bde)
                #8  0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #9  0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #10 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #11 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #12 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #13 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #14 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #15 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #16 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #17 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #18 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #19 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #20 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #21 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #22 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #23 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #24 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #25 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #26 0x00007f68d395274f dt_dev_pixelpipe_process_rec (libdarktable.so + 0x18374f)
                #27 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #28 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #29 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #30 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #31 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #32 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #33 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #34 0x00007f68d395274f dt_dev_pixelpipe_process_rec (libdarktable.so + 0x18374f)
                #35 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #36 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #37 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #38 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #39 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #40 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #41 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #42 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #43 0x00007f68d395274f dt_dev_pixelpipe_process_rec (libdarktable.so + 0x18374f)
                #44 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #45 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #46 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #47 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #48 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #49 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #50 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #51 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #52 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #53 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #54 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #55 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #56 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #57 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #58 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #59 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #60 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #61 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #62 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
                #63 0x00007f68d3953039 dt_dev_pixelpipe_process_rec (libdarktable.so + 0x184039)
```

When starting with a fresh configdir, I could not replicate the artifacts in the screenshots in the first post.

**Comment by ralfbrown** [comment] 2020-10-01 19:30
I'm currently on gcc 8.4.0, and presumably that's the version used for the distro's official 3.2.1 build.

**Comment by MikeFJohnson** [comment] 2020-10-04 19:29
groutr is not the only one with this bug. :)

![image](https://user-images.githubusercontent.com/72357391/95024966-893d3f00-0643-11eb-8a49-4306c80015f7.png)

Definitely only happens with me when using Denoise (profiled) with non-local means. If I switch to Denoise (profiled) and use wavelets, the problem goes away.

I'm running darktable 3.2.1 on Windows 10 with an Intel Core i7-9750H processor and an NVIDIA GeForce GTX 1660Ti graphics card. I never had this problem until upgrading from the prior version of darktable

Not sure what other info you might need from me.

**Comment by ralfbrown** [comment] 2020-10-05 02:40
I came across cases where the list of modules in the .xmp had been corrupted with multiple copies of the same instance of a multi-instance module, which confused the 3.1.0 (i.e. what becamse 3.2) pixelpipe code and caused problems including modules disappearing from the history stack.  Wasn't able to reproduce that at the time, so assumed that it was a bug that had been fixed since the time the XMPs were generated.

If what you're seeing only occurs where there are multiple instances of denoise(profiled) active and only in old history stacks, it may be something other than what @groutr is experiencing, but I'll keep it in mind when I finally have a chance at a full debugging session.

**Comment by MStraeten** [comment] 2020-10-07 15:29
@MikeFJohnson
thats a different case. in your example the pixel pipe is corrupted - maybe you used a development build 3.1 to edit the picture. you might fix it by cloning the image and copying (ctrl+shift+c / ctrl+v) the module instance which are visible in the right list of active modules. Sometimes this helps

**Comment by ralfbrown** [comment] 2020-12-13 15:20
@groutr If you're still having the corrupted-image issue with nlmeans denoise, can you check whether #7300 fixes it?

**Comment by groutr** [comment] 2020-12-13 15:57
@ralfbrown, yes I was still having issues with a corrupted image display.
#7300 seems to fix issue. After some quick testing, I have been unable to reproduce the issue with that PR. I can test more thoroughly within the next couple of days. Thank you!

**Comment by rawfiner** [comment] 2020-12-13 16:24
@groutr could you check if you have the bug with #7300 and with codepaths/sse2=false in your darktablerc?

**Comment by groutr** [comment] 2020-12-13 17:33
@rawfiner this bug manifests itself with codepaths/sse2=false. :disappointed: 
I get both the segfault with search radius/scattering and the corrupted display.

**Comment by rawfiner** [comment] 2020-12-14 08:27
Fixed by #7309 :-)

**Comment by groutr** [comment] 2020-12-14 15:27
Thank you @ralfbrown and @rawfiner for fixing this :)

**Comment by ptilopteri** [comment] 2020-12-14 15:38
If it is considered fixed, shouldn't it be closed?

**Comment by johnny-bit** [comment] 2020-12-14 15:42
Well if it's fixed then let's close it!

**Closed by johnny-bit** 2020-12-14 15:42 UTC
Labels: no-issue-activity
