### ISSUE TITLE
Crash on Mac Ventura when settings opened

### ISSUE THREAD

**Issue by ericlief** [darktable-org/darktable#15961] opened 2023-12-26 03:01 UTC
### Describe the bug

I build using the script on M1 Mac (13.6.1)

The app works better than the homebrew one I tried, which does not display the options correctly in windows, one if the issues reported in Issue #15895.

However, scrolling with the mouse/trackpad in Lightroom does not work properly and opening the settings crashes the app.
 

### Steps to reproduce

1 Build with script on M1 mac (Ventura)
2. Open app and import photos
3. Try scrolling with mouse in LIghtroom (only works when clicking on scroll bar)
4. Open settings (will crash)

### Expected behavior

Not crash...

### Logfile | Screenshot | Screencast

too long to post (see attachement)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

Master

### What OS are you using?

Linux

### What is the version of your OS?

13.6.1

### Describe your system?

Model: MacBookAir10,1, BootROM 10151.41.12, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: spdisplays_display, 1920 x 1080 (1080p FHD - Full High Definition), Main, MirrorOff, Online
Display: Color LCD, 2560 x 1600 Retina, MirrorOff, Online
Memory Module: LPDDR4, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: May 13 2023 07:20:48 version 18.20.383.15.7.8.150 FWID 01-b37727a5
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: USB2.1 Hub
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

![Screenshot 2023-12-25 at 8 49 51 PM](https://github.com/darktable-org/darktable/assets/16747511/02e6f86a-1f7e-40d8-ae48-f745a0a778c8)
[crash-darktable-test.txt](https://github.com/darktable-org/darktable/files/13768203/crash-darktable-test.txt)

**Comment by MStraeten** [comment] 2023-12-26 05:45
you might check f all prerequisites are properly installed - it seems it doesn't find GSettings schemas
maybe set it explicitly vis GSETTINGS_SCHEMA_DIR=... in the start command

**Comment by ericlief** [comment] 2023-12-26 16:23
OK, but where should this directory point to? I can't figure this out

**Comment by MStraeten** [comment] 2023-12-26 16:38
how did you build the app? dis you follow one of the BUILD... scripts in https://github.com/darktable-org/darktable/tree/master/packaging/macosx?

**Comment by ericlief** [comment] 2023-12-26 18:22
./build.sh --prefix /opt/darktable --build-type Release --install --sudo

**Comment by ericlief** [comment] 2023-12-26 18:28
I will try the homebrew instr. I thought that script in build was also for macos?

**Comment by ericlief** [comment] 2023-12-26 20:19
OK, building with steps 1-4 for homebrew worked with master (4.7.0+70~g18c7ddbf83)
I confirm that the window issue I reported (https://github.com/darktable-org/darktable/issues/15895) works as expected in settings.
In the Readme, I feel it would be helpful to label those instructions as only for Linux and add these steps for mac there.

**Comment by ericlief** [comment] 2023-12-27 01:01
Update: There is stilla a scrolling issue with this build in Lightroom. Put cursor in the area of previews and scroll with trackpad and nothing happens, whereas the scrollbar works.

**Comment by victoryforce** [comment] 2024-01-13 13:31
> I confirm that the window issue I reported (#15895) works as expected in settings.

So you can close the issue if the problem is solved. Also, if I understand correctly, there is no problem with the crash anymore, if you build according to the instructions.

**Comment by victoryforce** [comment] 2024-02-03 20:07
> Also, if I understand correctly, there is no problem with the crash anymore, if you build according to the instructions.

@ericlief I still don't see your answer and I assume that if the problem was still there you would have answered. Therefore, I close this issue. Feel free to comment further if the problem still exists.

**Closed by victoryforce** 2024-02-03 20:07 UTC
Labels: scope: macos support
