### ISSUE TITLE
Darktable keeps crashing openig .tif

### ISSUE THREAD

**Issue by Technohell** [darktable-org/darktable#8389] opened 2021-03-03 18:35 UTC
I have a problem!
When i try to open a Picure Darktable crashes.
I tried everything I know. the Bugreport is like  this:
[darktable_bt_59LHZ0.txt](https://github.com/darktable-org/darktable/files/6078303/darktable_bt_59LHZ0.txt)
[darktable_bt_ABKMZ0.txt](https://github.com/darktable-org/darktable/files/6078304/darktable_bt_ABKMZ0.txt)
[darktable_bt_BR3IZ0.txt](https://github.com/darktable-org/darktable/files/6078305/darktable_bt_BR3IZ0.txt)
[darktable_bt_CT5AZ0.txt](https://github.com/darktable-org/darktable/files/6078306/darktable_bt_CT5AZ0.txt)
[darktable_bt_EDMNZ0.txt](https://github.com/darktable-org/darktable/files/6078307/darktable_bt_EDMNZ0.txt)
[darktable_bt_JLC9Y0.txt](https://github.com/darktable-org/darktable/files/6078308/darktable_bt_JLC9Y0.txt)
[darktable_bt_8FTFZ0.txt](https://github.com/darktable-org/darktable/files/6078309/darktable_bt_8FTFZ0.txt)
[darktable_bt_8PJCZ0.txt](https://github.com/darktable-org/darktable/files/6078310/darktable_bt_8PJCZ0.txt)
[darktable_bt_9KAIZ0.txt](https://github.com/darktable-org/darktable/files/6078311/darktable_bt_9KAIZ0.txt)

I'm stupid, sad and need help.

Thanks for Darktable and hopfully help, you're great, Sven

**Comment by Nilvus** [comment] 2021-03-03 18:57
Hi,

We ask for some infos to share when posting the issue, you don't answer to most of them, so it will be hard to help (OS?. Graphic card? OpenCL or not? Tested with antivirus deactivated? and more things were asked when creating the issue). We ask for those infos for reason and it will be hard to help with so few informations.

You could also consider that a crash of darktable could also not be related to darktable. Just a quick search with "ntdll.dll" 'module cited in the beginning of bugreport) in Google will let you see many links with other softwares crash due to that, so maybe some infos to find that way...

**Comment by Nilvus** [comment] 2021-03-03 18:58
Oh, and you say when openin an image, with .tif in title. I suppose you talk about tiff (and not tif) images. Do you have that with only tiff images or also RAW, JPG...?

**Comment by Technohell** [comment] 2021-03-03 19:46
[EverestReport.txt](https://github.com/darktable-org/darktable/files/6078700/EverestReport.txt)

Sorry I'm a bit "pissed" causes of this.
I'll wirte more tomorrow.
Just for the questions: yes not only .tif also .png and .jpg but in the same folder. 
I deletes alle Darktable .xmp data but still the same ind THIS FOLDEr only this and the same frame set copied to other folders.

Thanks for the fast replay

**Comment by johnny-bit** [comment] 2021-03-03 20:35
All crashes happen with nvopencl64.dll library which means the problem is with nvidia's opencl (CUDA) drivers.

**Comment by Mark-64** [comment] 2021-03-04 15:42
@Technohell  
We have the same graphics card so it must work.
I suggest the following:

- open a command prompt
- go to` C:\Program Files\darkatble\bin`
- launch darktalle with OpenCL disabled: `darktable --disable-opencl`
- try to open the tiff file

if it works, then is definitely your nVidia / OpenCL driver. In that case I suggest you reinstall / update it.
Better if you do a clean install (google for it).

**Comment by johnny-bit** [comment] 2021-06-08 15:46
I've checked on windows by intentionally breaking mentioned librrary. The solution: reinstall nvidia drivers. 

Closing due to `Not a fault of darktable` :)

**Closed by johnny-bit** 2021-06-08 15:46 UTC
Labels: no-issue-activity, understood: unclear
