### ISSUE TITLE
Image becomes black and/or histogram disappears when using denoise (profiled) in wavelets mode and viewed at 100% (Mac OS)

### ISSUE THREAD

**Issue by jrguerreiro** [darktable-org/darktable#8852] opened 2021-05-03 12:51 UTC
Sometimes, when I use the "denoise (profiled)" module in wavelets mode and zoom in to 100%, the image turns black. The issue may manifest itself differently: sometimes the image turns black completely; sometimes only the preview and histogram disappear; sometimes just the histogram goes away; and thumbnails usually become black, both in lighttable and darkroom. It happens randomly, but with a high frequency. There are no issues when using the "non-local means" mode.

dt version used: 3.5.0+1877g666bdde167-dirty

System: OS X 10.15.7
Processor: 2,6Ghz Intel Core i5
Graphics card: Intel Iris 1536
OpenCL: No

Please let me know if there is more information I could provide.

**Comment by jrguerreiro** [comment] 2021-06-03 00:51
Was anyone able to reproduce this issue?

**Comment by jillesvangurp** [comment] 2021-09-29 06:31
I've seen this issue once or twice. Switching to lightroom and back to darkroom seems to fix things. I have no way to reproduce it though as it does not happen consistently. But I was editing some night time photos a week ago and saw this happen on one of my photos.

**Comment by jrguerreiro** [comment] 2021-09-29 11:58
I will try and make a video demonstrating the issue, it happens here very frequently, even with dt 3.7 dev version.

**Comment by jrguerreiro** [comment] 2021-10-31 19:11
Sorry I took so long, but here is a video showing how, when I turn denoise (profiled) on, the histogram and the preview go black. I hope it help

https://user-images.githubusercontent.com/66041590/139597977-24501a60-647a-4ba7-9ec0-31162e4d4eb6.mp4

s.

**Comment by parafin** [comment] 2021-10-31 19:18
It may be a duplicate of #10221, please check that it didn’t fix your issue.

**Comment by jrguerreiro** [comment] 2021-11-05 16:25
Unfortunately not, I’m still getting the black thumbnails when denoise (profiled) is on wavelets mode (it doesn’t happen if I use non-local means).

**Comment by swsounds** [comment] 2021-11-12 15:51
On Mac OS10.15.7 Approximately half of my image thumbnails in Lighttable appear as black squares. The start point style that I use has Denoise Profiled in Wavelets mode. Sometimes changing other modules will bring them back but it is hit and miss. Having read this thread I tried two things, firstly disable Denoise, result was thumbnail appears. Then change from wavelets to wavelets auto and this worked in all but one case out of 7. In that one case turning off denoise sorted the issue. The only other thing is that all the ones that were converted to black and white  in Colour Calibration were ok the one that didn't work was a colour image.  
I don't know but does this help anyone? I know it's a very small sample and not very scientific ....

**Closed** 2023-03-25 00:19 UTC
Labels: no-issue-activity
