### ISSUE TITLE
[FR] 3 suggestions to improve the film strip in culling layout

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#8847] opened 2021-05-02 17:55 UTC
**Describe the bug/issue**
This is less of a bug but more of a suggestion to improve the way the filmstrip behaves in culling layout modes.

I am on latest master, Manjaro Linux.

1. 
The picture that is currently in focus is highlighted in the film strip by a very small and black triangle which is very hard to spot.
<img src="https://user-images.githubusercontent.com/2805109/116821507-668fec00-ab7a-11eb-8a99-d38fe511debc.png" width="100%" height="100%">

only when the mouse hovers over the picture in central view, the picture is highlighted by a white border:
<img src="https://user-images.githubusercontent.com/2805109/116821560-a7880080-ab7a-11eb-85d1-b273f6d94f6b.png" width="70%" height="70%">

This looks almost identical to selecting a picture with Ctrl+left-mouse-click (here: the bamboo picture is not-selected but in central view, the bird picture has been selected but is not central view). The only difference is the black triangle.
<img src="https://user-images.githubusercontent.com/2805109/116821663-11a0a580-ab7b-11eb-9107-f1a08af2ae53.png" width="70%" height="70%">

I propose using a border around the picture in focus (yellow or some other color) instead of the black triangle indicator. The white border should only be used for selected pictures:
<img src="https://user-images.githubusercontent.com/2805109/116822050-15352c00-ab7d-11eb-9a94-a8e2c2a3db3c.png" width="70%" height="70%">

2.
When clicking on a picture from the filmstrip, the whole filmstrip automatically centers on the new picture. In combination with the  hard to spot black triangle from (1) it is very easy to loose track of where you are and where you came from.
Picture of bird in focus before clicking on bamboo
<img src="https://user-images.githubusercontent.com/2805109/116821994-c38ca180-ab7c-11eb-9bff-7666fd5ac786.png" width="70%" height="70%">

after clicking on bamboo:
<img src="https://user-images.githubusercontent.com/2805109/116822295-65f95480-ab7e-11eb-86bc-2abd3349e5ed.png" width="70%" height="70%">
This is especially annoying when you want to switch back and forth between two pictures using your mouse.

I propose not moving the filmstrip at all when selecting a picture with a mouse click but only when scrolling the mouse wheel while hovering the cursor on the film strip or on the central view.

3.
I would love a scrollbar at the bottom to fast scroll through the film strip and also to get an idea where I am in a collection. Since this has already been done for the file manager layout, is there any reason not to implement this in the film strip as well?

I hope these ideas resonate with you

**Comment by Nilvus** [comment] 2021-05-02 18:59
Please precise darktable version you use?

About your 1st suggestion, this had already been discussed a lot and borders had been removing because of others critics. The focus is not only the top triangle but also color.And you don't have it here. Do you have any CSS tweak that could break that? Or maybe an old version with an issue here. See what I have on my side (I suspect that you use darker or darktable default one):

![2021-05-02_20-55](https://user-images.githubusercontent.com/45535283/116824109-ee282b80-ab77-11eb-873c-17c01ae335f1.png)

For 2nd one, as it's related to 1st one, with different background and top triangle, it's clearly visible.

About 3rd one, why not but I find that ok to not have one in such part

**Comment by Solarer** [comment] 2021-05-02 19:15
@Nilvus thanks for your reply. I am on latest master branch using Manjaro Linux (I added that information above).

1. I did not apply any CSS tweaks, it is plain dt out of the box. I do see the same white color as you do, but it is only visible when I hover my mouse over the big picture in the central view. If I move the mouse elsewhere, only the top triangle remains which is hard to spot. Please check my screenshots above: in screenshot No.2 you can see the white color and also the cursor right on the bamboo picture - in screenshot No.1 I moved the mouse and the color is gone.

2. This is not only really about the bad visibility but more about the shift in general. Even if the picture was highlighted good, the automatic shift of the film strip makes it hard to navigate with the mouse. It is easiest to understand if you try for yourself to switch back and forth between 2 pictures that are not right next to each other using the mouse.

3. Yes, I saw a setting to disable the vertical scrollbar for other modes. This could be implemented here as well for those that do not like it.

**Comment by Nilvus** [comment] 2021-05-02 20:57
> @Nilvus thanks for your reply. I am on latest master branch using Manjaro Linux (I added that information above).
> 
>     1. I did not apply any CSS tweaks, it is plain dt out of the box. I do see the same white color as you do, but it is only visible when I hover my mouse over the big picture in the central view. If I move the mouse elsewhere, only the top triangle remains which is hard to spot. Please check my screenshots above: in screenshot No.2 you can see the white color and also the cursor right on the bamboo picture - in screenshot No.1 I moved the mouse and the color is gone.

And I talk about your first screenshot. My screenshot is without mouse hover and on last master too (I compile and made CSS used for that). So I see an issue on your side, and darktable have different color for selected image (and it's the exact same one as on lighttable thumbnails) without no doubt. I can't understand why you don't have the color if you have no CSS tweak applied. Just to be sure: could you check (and remove it if you have one) if you have a user.css file in ~/.config/darktable folder?

>     2. This is not only really about the bad visibility but more about the shift in general. Even if the picture was highlighted good, the automatic shift of the film strip makes it hard to navigate with the mouse. It is easiest to understand if you try for yourself to switch back and forth between 2 pictures that are not right next to each other using the mouse.

@AlicVB: what's your view about that? I rarely use filmstrip so no more idea here.

>     3. Yes, I saw a setting to disable the vertical scrollbar for other modes. This could be implemented here as well for those that do not like it.

The issue here is that we all recently talk about the fact that darktable has too many settings and that overload it.

**Comment by Solarer** [comment] 2021-05-03 20:33
The CSS file was there. I removed it but it still looks the same. I also tried to change the config dir with:
   > /opt/darktable-test/bin/darktable --configdir /tmp

same result. I am on 3.5.0+2050~g2741ac4db and I build it with
   > rm -rf build
   > rm -rf /opt/darktable-test
   > ./build.sh --prefix /opt/darktable-test --build-type Release --install --sudo --enable-opencl

I did not execute any other commands and did nothing to any CSS files. The only way for me to get the same white color as in your screenshot is by either selecting the picture with Ctrl-left-mouse or hovering with the mouse on the film strip / central picture.

**Comment by Nilvus** [comment] 2021-05-04 18:40
> The CSS file was there. I removed it but it still looks the same. I also tried to change the config dir with:
> 
> > /opt/darktable-test/bin/darktable --configdir /tmp
> 
> same result. I am on 3.5.0+2050~g2741ac4db and I build it with
> 
> > rm -rf build
> > rm -rf /opt/darktable-test
> > ./build.sh --prefix /opt/darktable-test --build-type Release --install --sudo --enable-opencl
> 
> I did not execute any other commands and did nothing to any CSS files. The only way for me to get the same white color as in your screenshot is by either selecting the picture with Ctrl-left-mouse or hovering with the mouse on the film strip / central picture.

Thanks for your precision. By now, I so really don't understand how you can't have this color on your side. Ctrl+left mouse is to select an image in filmstrip. If you have the top triangle means that the image is selected AND has the focus, so you should have it. I suggest you to post a precise step by step to always have this (starting from lighttable and with most steps as possible to... maybe... understand. By now, I find your issue quite strange and not reproducible on my side. So hard to help more.

The only thing that your screenshot means is that the image is no more selected but remains to have the focus (and it's a normal behavior but not normal if you started on a selected image. It would be good to precise with your step by step which filter you use too (especially ones in top left of main view).

For example, if I select an image in lighttable and then press 'd' to go to darkroom, I see my image with the white color to show that the image is selected and the triangle to show that the image has the focus. If I ctrl+left mouse on it, I unselect it so only triangle remains (that's a normal behavior). If I select this image and other with ctrl+left mouse, I let the "white color" comes back.

**Comment by Solarer** [comment] 2021-05-04 19:29
Ok, now we are not coming to a consent:
In my workflow I have no images selected before I open culling layout. That allows me to scroll through all images without being limited by a file selection. 
If I select pictures prior to entering culling mode, all selected pictures are white AND I have the triangle for those in focus. In that case I can not scroll to pictures that have not been selected. Is that the same behavior as yours?

Still this does not really change anything for me. If I select all picture, they will all be white and I still cannot spot which one I have in focus without having to search for the tiny triangle. (Well at least it is now a black triangle on a white foreground, so it is a little easier, but not a lot.)

I agree that it is important for the layout to be consistent throughout darktable. Check out what I just found:

Go to filemanager mode, don't select any picture and go to culling mode. Now, focus one picture and select another one and return to filemanager mode. You can see that the selected picture has the white background but the image that was in focus (and is not selected) has a white border that flashes 3 times before it disappears. That white boarder is exactly what I want for the culling mode! (maybe without the flashing) That should be consistent, since it is already implemented on master, right?

I took a screenshot. Here, the elefant is in focus and the mountain has been selected:
![image](https://user-images.githubusercontent.com/2805109/117058646-2fa70b00-ad1f-11eb-99a9-9e045f3dbb52.png)

**Comment by AlicVB** [comment] 2021-05-04 20:08
>     2\. This is not only really about the bad visibility but more about the shift in general. Even if the picture was highlighted good, the automatic shift of the film strip makes it hard to navigate with the mouse. It is easiest to understand if you try for yourself to switch back and forth between 2 pictures that are not right next to each other using the mouse.

I tend to agree with you. Even if I don't use filmstrip that much... I'll see what I can do. and if I get some result will do a PR... another line on my TODO :)

**Comment by Nilvus** [comment] 2021-05-04 20:15
> Ok, now we are not coming to a consent:

I don't see that. Your first issue was just not clear as you never explain how you come on your behavior. You just explain what you had but not how. But your last comment is the precise step by step I asked and indeed that a way to do not correctly applied and so something to improve.

Your last comment explain way better the real issue: a way to enter darkroom without any image selected and I suspect many user (like me) mostly enter darkroom with image selected. That's so explain why we don't have same thing. I let now @AlicVB works on that when he will have time to do that. @AlcVB as it will be more than only CSS code here (and I only have skills for CSS code here!)

**Comment by Solarer** [comment] 2021-05-04 20:55
Oh, you were talking about darkroom! I was talking about lighttable! Seems like the problem is in both!

You can break the highlighting in the following ways:

1. Enter lighttable (culling mode) from file manager mode with no selection: no white color here
2. With no selection in lighttable (culling mode) now enter darkroom: no white color here. (You cannot get here from filemanager without selecting a file directly because darktable complains that you have no selection).
3. Select a file in filemanager and enter darkroom. The picture is highlighted in white color AND via triangle. If you click on another picture, white color and triangle will move together (all ok until here). Now either a) select an addition picture with Ctrl-click or b) remove current selection with Ctrl-Shift-A. If you now click on other pictures, they will not get the white color anymore. You can fix this by removing all selected pictures with Ctrl-Shift-A, then selecting 1 picture with Ctrl-Click and then focus the selected picture with a normal mouse click. This realigns selection and focus and both will move together again.
4. Go to lighttable filemanager layout, don't select a picture and enter culling mode. Now select 1 picture but focus another one. If you now enter darkroom mode, you will still see the image that was in focus and the selection on the other picture remains. So again - you successfully splitted selection and focus.

:)

**Comment by Nilvus** [comment] 2021-05-04 21:34
> Oh, you were talking about darkroom! I was talking about lighttable! Seems like the problem is in both!

No, I means both and starting especially from lighttable to enter to darkroom. I just mean that I never go, like you, in darkroom with a non selected image. So I never had the focused image without "white color". And that many users probably go in darkroom by beginning with a selected image.

> You can break the highlighting in the following ways:

Thanks but no more necessary as all is understood now. 

Could you try to just add to darktable preferences and CSS tweak part (editor text in first tab) those lines:

#thumb_main:active #thumb_back,
#thumb_main:selected #thumb_back
{
  background-color: shade(@thumbnail_selected_bg_color, 1.05);
}

And then just save and apply. That should add selected color on non thumbnail that has the focus (the one with border top and triangle) even if not selected. Is it better and ok for you with that?

**Comment by Solarer** [comment] 2021-05-05 07:36
Thanks, the CSS tweak makes it a lot better!

Is there also CSS code to get the white border as in my previous screenshot around the elefant?

**Comment by Nilvus** [comment] 2021-05-05 16:12
> Thanks, the CSS tweak makes it a lot better!
> 
> Is there also CSS code to get the white border as in my previous screenshot around the elefant?

With something like that (a white border is too much, but something between white and background set should be good). See what I can propose below (so add border line in previous code):

```
#thumb_main:selected #thumb_back
{
  background-color: shade(@thumbnail_selected_bg_color, 1.05);
  border: 1px solid shade(@thumbnail_selected_bg_color, 1.15);
}
```

I'm waiting for your feedback!

**Comment by Solarer** [comment] 2021-05-05 20:06
Thanks for your support!

    #thumb_main:active #thumb_back
    {
      border: 3px solid shade(@thumbnail_selected_bg_color, 1.25);
    }

Works better for me because it allows me to differentiate between a selected picture and a picture in focus. In lighttable view, those are not necessarily the same. It also looks more similar to what the filemanager looks like.

**Comment by Nilvus** [comment] 2021-05-06 16:25
> Thanks for your support!
> 
> ```
> #thumb_main:active #thumb_back
> {
>   border: 3px solid shade(@thumbnail_selected_bg_color, 1.25);
> }
> ```
> 
> Works better for me because it allows me to differentiate between a selected picture and a picture in focus. In lighttable view, those are not necessarily the same. It also looks more similar to what the filemanager looks like.

The way to differentiate is the top triangle, so this will not be integrated. And I find 3px way too large, and 1.25 way too bright. But that why darktable have a place to put CSS tweaks. We have all different ways to work/view things.

Anyway? I will integrate my last code proposal here to be included in next darktable release, 3.6, as it's much better than what we have actually in darktable. Thanks for your feedback that had allow this improvement.

I let @AlicVB continue for point 2 of your issue!

**Comment by AlicVB** [comment] 2021-05-06 17:28
yep, I'll have a look asap... But I'm not sure it'll be in 3.6, depends of the complexity and when I'll have the time to do this ;)

**Comment by Solarer** [comment] 2021-05-06 18:22
All right, no problem. I am fine with applying that custom CSS tweak manually. 
Glad I could help improve darktable!

**Comment by Solarer** [comment] 2021-06-28 07:13
Keep open.
2. Don't move filmstrip when clicking on a picture
and 
3. Implement a scrollbar for filmstrip
have not been done yet

**Comment by johnny-bit** [comment] 2021-06-29 10:19
Personally I don't agree with point 2. IMO image active should be centered as is. And I don't know if we have "switch back to previously opened file" or just move +/- in the collection but "previously opened file" would solve your issue here.

as for having scrollbar in filmstrip - i guess it's OK to have...

**Comment by Nilvus** [comment] 2021-06-29 17:44
> Personally I don't agree with point 2. IMO image active should be centered as is. And I don't know if we have "switch back to previously opened file" or just move +/- in the collection but "previously opened file" would solve your issue here.
> 
> as for having scrollbar in filmstrip - i guess it's OK to have...

I agree, active image should be centered as is. It's wanted behavior.

About scrollbar, why not, even if for a filmstrip I don't find that useful!

**Comment by Solarer** [comment] 2021-06-29 22:13
> I agree, active image should be centered as is.

Do you think so even when clicking with the mouse into the filmstrip? I agree that it should be centered when scrolling through the images using mouse wheel or arrow keys but when clicking the movement is just too much. 
It might still be acceptable when you only have like 3 images selected but if you select the whole filmstrip and start clicking, it is not a nice experience for mouse users.

**Comment by johnny-bit** [comment] 2021-06-30 05:19
I do use mouse on filmstrip with not too small collections and find "centering" of the current image very intuitive and jump very acceptable.

from my standpoint - only scrollbar is actionable.

**Comment by Solarer** [comment] 2021-06-30 08:04
OK, then let's stick with the scroll bar for now. 
I guess that will also indirectly help with the centering because the scroll bar visualizes the current position in the collection

**Comment by Spidermarc** [comment] 2021-07-04 12:59
I would love to have a scrollbar !
(in fact I am hardly using darktable at the moment because i can't find a workflow that works for me without a scrollbar)

**Comment by Solarer** [comment] 2021-08-15 08:48
Can we tell the github bot to keep this open for more than 30 days? 

It looks like no one is working on a scrollbar yet and I don't want to bump this thread every month

**Comment by johnny-bit** [comment] 2021-08-15 08:56
This will only be closed after 365 days so maybe somebody will pick it up? :P Don't worry, if somebody will pick it up it's great and if not - yell and either me or @Nilvus or others will re-open it.

**Comment by johnny-bit** [comment] 2021-09-02 09:25
issue #9919 has IMO more straightforward description of what's needed regarding scrollbar. If you don't mind let's close this in favour of continuing work on #9919.

**Closed by johnny-bit** 2021-09-02 09:25 UTC
Labels: feature: enhancement, priority: medium, understood: clear, reproduce: confirmed, scope: UI, no-issue-activity
