### ISSUE TITLE
DNG file has strange default wb values, wrong colors and error message

### ISSUE THREAD

**Issue by gadolf66** [darktable-org/darktable#3555] opened 2019-11-25 02:35 UTC
**Describe the bug**
DNG files from a CHDK point-and-shoot Canon show strange default values in white balance module and very pale colors.
Besides, everytime the file is opened or a module is activated, it shows a warning/error message stating that

`Canon Canon Powershot A3100 IS color matrix not found
`
Rawtherapee and Photoflow show "normal" values. By "normal" I mean a color temperature around 6, 7K, not 25K as show by darktable.

**To Reproduce**
1. Open attached dng file
2. See default white balance values
3. Open the same file in Rawtherapee and/or Photoflow and compare.

**Expected behavior**
1) Color temperature is way too high (25K)
2) Colors are very faint

**Screenshots**
After opening file in dt:
![Screenshot from 2019-11-24 23-59-45](https://user-images.githubusercontent.com/46730249/69509126-944d1c00-0f16-11ea-969d-d377366db862.png)

After opening file in rt:
![Screenshot from 2019-11-24 23-27-12](https://user-images.githubusercontent.com/46730249/69507628-f6efe900-0f11-11ea-91a6-2697a95495c2.png)

After opening file in PhF:
![Screenshot from 2019-11-24 23-28-00](https://user-images.githubusercontent.com/46730249/69507671-138c2100-0f12-11ea-841c-59457a1ae413.png)

**Platform (please complete the following information):**
 - OS: ubuntu 18.04
 - Version 3.0.0rc1-git82.cde1d

**Additional context**
raw file:

[IMG_5861.zip](https://github.com/darktable-org/darktable/files/3884577/IMG_5861.zip)

**Comment by jenshannoschwalm** [comment] 2019-11-25 06:43
dng file has a CalibrationIlluminant1=1 and dt has no conversion matrix for this atm. I will fix this and there will be a proper temperature.

About the image being dull --> you will have to use some module like base curve or filmic ...

**Comment by gadolf66** [comment] 2019-11-25 10:10
Thanks,
As for the dullness, I was referring to the fact that it is much more dull than Rawtherapee or Photoflow. Please note that both rt and phf are showing the unedited raw and show more color.

**Comment by gadolf66** [comment] 2019-11-25 10:19
Sorry, I forgot to mention, dt also show black borders around the image (if you turn on the over/under exposed indicator, it becomes clear).
Again, rt and phf don't.

**Comment by jenshannoschwalm** [comment] 2019-11-25 11:58
1. "Right color" will be fixed
2. "Dullness" is not a bug but intended in dt as you should apply base curve or preferred rgb-filmic.
3. I also saw the borders, another point that should be fixed. The cropping exif data in your image is somewhat strange.

**Comment by jenshannoschwalm** [comment] 2019-11-25 18:19
The colour matrix problem has been fixed via #3565 so your colours will look much better!

About the black border; in fact this is by "intention". dt takes the size as suggested by "Default Crop Size" (which is normally smaller than "Active Area", in your image it's the same size, you can see these data by using exiftool. This behaviour is suggested by DNG standard. rt automatically crops borders in this case. If you want to get rid of these borders you could use the crop module and activate that automatically (the manual tells you how to do it) or define a style. Keep going!

**Comment by jenshannoschwalm** [comment] 2019-11-25 18:20
Think of closing this issue please

**Comment by gadolf66** [comment] 2019-11-25 18:26
Thanks! I'm unable to test it now.
Will I have to build it myself,or will this be merged to master, so that I can grab it via opensuse package?

**Comment by jenshannoschwalm** [comment] 2019-11-25 20:26
You can watch the pr to find out when it's available in master.

**Closed** 2019-11-27 12:08 UTC
