### ISSUE TITLE
Built-in color chart tool

### ISSUE THREAD

**Issue by seadra** [darktable-org/darktable#5093] opened 2020-05-17 02:15 UTC
**Is your feature request related to a problem? Please describe.**

Making use of a color checker with darktable is not straightforward. There is an external tool (darktable-chart) that covers a special case, but having a built-in tool that we can use as a part of usual editing process would be nice.

**Describe the solution you'd like**

A module that allows us to fit a part of the image to a known color chart data. DaVinci Resolve has such a tool that is very easy and straightforward to use: https://youtu.be/lzMe50L-Md0?t=170

It works really simple: the color checker is a part of the photo, and the user just selects that region, and tells the program which color chart is being used. The program then generates the LUT.

**Alternatives**

There is the "Color look up table" module, but is extremely tedious because one needs to fine-tune each color, one by one. The knobs in this module are also hard to map to the table of color values for the color chart that is being used.

**Additional context**

**Comment by johnny-bit** [comment] 2020-12-17 13:49
Duplicate of #5618 (and will be fixed by #7293) :)

**Closed by johnny-bit** 2020-12-17 13:49 UTC
Labels: duplicate, no-issue-activity
