### ISSUE TITLE
Avif - Real RGB Color Profile support

### ISSUE THREAD

**Issue by Shanti099** [darktable-org/darktable#7824] opened 2021-01-13 01:51 UTC
Hello,

Thank you for all your great work, 

Would you please add the ability for Avif to have real RGB colors. Why AVIF changed the color of the photos to YUV?
Even when i convert jpeg (sRGB) or NEF (RAW) in darktable to AVIF with sRGB profile - the colors are not like in the original photos. i know, that it's not bug of your software, but AVIF issue, but perhaps you can fix it.

So far, only [https://github.com/kornelski/cavif-rs](url) and GIMP with AVIF support can convert to AVIF with the almost original color. but **cavif-rs** - is the command line exe and **GIMP** - can convert in batch mode only with command line. 

So i hope that you can fix AVIF color to match color of the original photos.

Thank you

**Comment by Nilvus** [comment] 2021-01-22 13:30
Seems to be a duplicate of #7661. But maybe not completely. As I don't use and know Avif, maybe @cryptomilk who work on Avif support could complete before choose to close or not this issue.

**Comment by cryptomilk** [comment] 2021-01-22 14:00
YUV is the internal format of AVIF. By default if you export as sRGB this is stored in a NCLX box. The software you use for viewing AVIF files needs to support this.

So far I can't identify a bug here at all.

**Comment by Nilvus** [comment] 2021-01-22 14:32
Thanks @cryptomilk for your reply. So as this can't be fixed on darktable side, I close this issue. @Shanti099: so check on the side of software you use to display images to add that support on it.

**Closed by Nilvus** 2021-01-22 14:32 UTC
Labels: bug: won't fix
