### ISSUE TITLE
Unable to open program

### ISSUE THREAD

**Issue by sororravn** [darktable-org/darktable#2655] opened 2019-06-02 13:52 UTC
**Describe the bug**
darktable will not open. Anytime that I attempt to open the program, it crashes instead.

**To Reproduce**
1. Click Start
2. Click the darktable folder
3. Click darktable
4. Error! An unhandled exception occurred.

This same issue occurs no matter if I open it this way or if I run it as admin.

**Expected behavior**
For the program to open so that I can actually attempt to use it

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10 Home edition, 8 GB of RAM, 632 GB free HD space
 - Version 2.6.2
[darktable_bt_5LAP2Z.txt](https://github.com/darktable-org/darktable/files/3244863/darktable_bt_5LAP2Z.txt)

**Additional context**
I am including the backtrace file. I have rebooted the machine, uninstalled and reinstalled the program with the same results.

**Comment by sororravn** [comment] 2019-06-02 15:02
Here are the results from the CL test described here:
https://www.darktable.org/about/faq/#faq-windows-opencl

[CL Test.txt](https://github.com/darktable-org/darktable/files/3244919/CL.Test.txt)

I am not sure how to disable it from the instructions located here:

https://www.darktable.org/usermanual/en/darktable_and_opencl_still_fubar.html

**Comment by peterbud** [comment] 2019-06-03 11:43
Hi @sororravn this is very similar to #2599, and based on the trace an AMD driver issue.

In order to disable openCL, either you start darktable from the cmd with the described command line:
`darktable --disable-opencl`

or _alternatively_, on Windows you can right click on darkable menu item in the start menu, then select "More/Open file location". In the new window you will see the darktable launch icon, right click on that, select "Properties" and in the dialog box enter  --disable-opencl as you see below:

![image](https://user-images.githubusercontent.com/7863452/58799387-7eb10680-8605-11e9-9ef8-ebbba7145bae.png)

**Comment by johnny-bit** [comment] 2020-12-22 13:31
I've checked around and the problem is (or rather was) caused by buggy AMD drivers. The problem affected not only darktable, but other opencl apps, such as luminar or some adobe stuff.

Duplicate of #2562

**Closed** 2020-12-22 13:31 UTC
Labels: no-issue-activity
