### ISSUE TITLE
Feathered mask glitchy for color balance rgb with heavy edits

### ISSUE THREAD

**Issue by geraldgattringer** [darktable-org/darktable#16004] opened 2024-01-02 08:50 UTC
### Describe the bug

When using the color balance rgb module with high brilliance settings in combination with a feathered mask (drawn or parametric) the effect bleeds outside of the masked region in a glitchy way. The bug is invariant to the module order.

The effect also shows up sporadically when changing the mask opacity. E.g. for a mask opacity of +79% and +81% the image looks as expected, for an opacity of +80% it does not. Similar for mask constrast: +9% and +11% look fine but +10% does not.

The glitches show up in an exported image.

When a instance of the exposure module+mask is used in a analogous way to increase brightness the effect does appear.

### Steps to reproduce

1. Open bright image.
2. Strongly incrase brightness with color balance rgb module (e.g. global brilliance + highlights)
3. Add drawn mask.
4. Feather mask.

### Logfile | Screenshot | Screencast

<video src="https://github.com/darktable-org/darktable/assets/151759884/0d75a2e4-aeea-4ff9-90a5-dd73714a0515" width="200"></video>
<img src="https://github.com/darktable-org/darktable/assets/151759884/206e1336-fa8c-4cf8-b9da-212744f531a8" width="200"/>
<img src="https://github.com/darktable-org/darktable/assets/151759884/d7aa16ea-4da7-4559-a37c-e7c3a21f512f" width="200"/>

### Commit

fcbe7dd5b10d86cd20e7a56afe7ec6357814d350

### Where did you obtain darktable from?

self compiled

### darktable version

4.7.0+97~gfcbe7dd5b1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Nvidia GTX 970

**Comment by ralfbrown** [comment] 2024-01-02 14:10
High brilliance values can produce extremely large pixel values (e.g. in the billions, where 1.0 is pure white) -- see #12442.  If you have highlight reconstruction turned on in FilmicRGB, this results in artifacts as the reconstruction blends those extreme highlights with the surrounding.

Does the glitch appear with filmic's reconstruction completely disabled?  (check-box unticked)

**Comment by geraldgattringer** [comment] 2024-01-02 15:26
Filmic's highlight reconstruction was disabled. The anomaly also appears with a disabled filmic rgb module. Module order does not seem to play a role, besides the effect's strength.

**Comment by gi-man** [comment] 2024-01-02 16:06
You should provide the image and xmp for us to recreate the issue.

**Comment by geraldgattringer** [comment] 2024-01-02 18:25
Minimal example from the first post: gradient.png & gradient.png.xmp (zipped as .xmp uploads are not allowed)
[gradient.zip](https://github.com/darktable-org/darktable/files/13812914/example.zip)

**Comment by gi-man** [comment] 2024-01-02 19:27
I can reproduce, Fedora 39 KDE, 4.7.0~git98.bce83d51

Set the Color RGB Global Brilliance and highlights to 100%. Place a round circle drawn mask, increase feathering to 1px. snd it bleeds over horizontal or vertical or both. 

If I rotate the image, the lines remain horizontal/vertical from the display screen and not to the image.

**Comment by ralfbrown** [comment] 2024-01-02 20:33
It's the same underlying issue as in filmic's reconstruction - both that and the guided filter work by blurring the input, which means the supernova-bright pixels generated by overuse of the brilliance slider get spread around and cause artifacts.

Don't push the highlights brilliance past +20% or so (sum of global and highlights sliders), as the math breaks down.

**Comment by victoryforce** [comment] 2024-01-11 20:15
> Don't push the highlights brilliance past +20% or so (sum of global and highlights sliders), as the math breaks down.

Complaints about this appear so often that it is worth somehow making it difficult for users to shoot themselves in the foot. I'll make a PR that adds soft limit of ±20% for all brilliance sliders.

**Comment by geraldgattringer** [comment] 2024-01-11 21:02
I expected the image to break for high values. I found it strange how it effects the masked out areas and doing so in a seemingly unpredictable way.

**Comment by victoryforce** [comment] 2024-01-11 21:41
> I expected the image to break for high values.

At least darktable works as expected :)

> I found it strange how it effects the masked out areas and doing so in a seemingly unpredictable way.

So you're essentially pushing dt algos to  where they could not operate meaningfully and want them to produce broken images in predictable ways? I'd say that failure to do so should not be considered as darktable bug.

**Comment by ralfbrown** [comment] 2024-01-11 22:20
>  I'll make a PR that adds soft limit of ±20% for all brilliance sliders.

Really only of use for the global and highlights sliders, as the pixel must be pretty bright to begin with.  OTOH, consistency is also desireable.

Worth adding a note to the tooltips that (global+highlights>20%) can cause artifacts with any subsequent wavelets, guided filter, or blurring operations?

**Comment by geraldgattringer** [comment] 2024-01-12 09:52
A note would indeed be useful. As of now I did not find a hint in the doc or tooltip that too high values can lead to problems.

As a sidenote the same phenomenon also occurs when using an instance of the exposure module with a ludicrous setting (like +18 EV) and the same mask+feathering setting. Admittedly, this scenario is even more far fetched.

**Comment by jenshannoschwalm** [comment] 2024-03-03 14:38
Seems to be fixed via #16093

**Closed by jenshannoschwalm** 2024-03-03 14:38 UTC
Labels: scope: image processing
