### ISSUE TITLE
applying a style then ctrl+z  to remove it cause styles to remain in some parts

### ISSUE THREAD

**Issue by emko** [darktable-org/darktable#11725] opened 2022-05-05 01:20 UTC
To Reproduce
apply a style then ctrl+z to remove it 

if you apply a style then ctrl+z to remove the style, it will still show, the thumbnail at the bottom will reset and when you zoom to a certain level it will show reset image, you have to go to darkroom to get it to fully reset.

Screencast
https://streamable.com/kqv55u

    darktable version : 3.8.1
    OS : Fedora 36
    Memory : 32gb
    Graphics card : 970
    Graphics driver : Nvidia

    Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes

**Comment by TurboGit** [comment] 2022-05-09 15:59
I cannot reproduce so I think this is fixed in master.

**Comment by emko** [comment] 2022-05-10 21:18
https://streamable.com/qj5zon 

are you sure its fixed? for me it happens on master

**Comment by AlicVB** [comment] 2022-05-10 21:29
no, we are not sure, that was a deduction done by the fact that there has been some fix on filmstrip update recently, and that we were not able to reproduce... Let's reopen then ;)

**Comment by emko** [comment] 2022-05-10 21:48
oh okay thanks, i tested on latest changes from today ae5b7bd.

**Comment by dterrahe** [comment] 2022-10-29 13:41
@emko I don't know if you are able to compile from master or if a snapshot is available for your distribution, but if so, would you be able to test if the recently merged #12671 solves this problem as well? If it does, please close this issue and otherwise please report back here. Many thanks!

**Closed** 2023-10-27 00:16 UTC
Labels: no-issue-activity
