### ISSUE TITLE
Panasonic TZ90 wb/colors

### ISSUE THREAD

**Issue by tpapp** [darktable-org/darktable#10111] opened 2021-09-28 07:22 UTC
Compared to OOC JPEGs, raw images in DarkTable (3.6.1) have a reddish cast. I just [uploaded](https://raw.pixls.us/?missing#repo) samples (JPEG+RAW), can also attach here but files are large.

(x-ref: [discussion](https://discuss.pixls.us/t/panasonic-tz90-reddish-cast-in-raw-how-to-remove/27138))

**Comment by kofa73** [comment] 2021-09-28 08:11
Might be related to https://github.com/darktable-org/darktable/issues/10008.
If you raise exposure, does the chart lift off from the bottom, as shown there? In that case, see the comments for a temporary fix if you can build darktable yourself; otherwise, override the black levels manually for now.

**Comment by tpapp** [comment] 2021-09-28 08:40
Sorry, I don't understand what the chart means in this context.

Can you please download the files from the discussion (now linked above) and check that it is the same issue?

**Comment by tpapp** [comment] 2021-09-28 09:07
Colors are correct in Darktable 3.4.1, with black levels = 139 on all channels (as opposed to 128 in Darktable 3.6). But merely chancing that back to 128 in 3.6 does not reproduce the issue.

**Comment by kofa73** [comment] 2021-09-28 09:29
> Sorry, I don't understand what the chart means in this context.

The histogram in 'RGB parade' mode, as shown on the screenshots of #10008. https://docs.darktable.org/usermanual/3.6/module-reference/utility-modules/shared/histogram/#rgb-parade

**Comment by tpapp** [comment] 2021-09-28 12:16
Thanks, I get it now. With the original setting (all 128), I have
![before](https://user-images.githubusercontent.com/84122/135084510-b664276e-3dab-4560-aaa6-90751bc47ecc.png)
but with 139 (and no other change) I get
![after](https://user-images.githubusercontent.com/84122/135084542-150c7b1d-e8ea-4f68-aeec-ead381725993.png)

This actually fixes the reddish cast. (The above is all in 3.6.1.)

I appreciate your patience in guiding me through a solution. Hopefully this will be fixed as a default setting in the future, but putting it in the default style I use for this camera is a convenient workaround.

**Comment by kofa73** [comment] 2021-09-28 12:33
For my LX7, unfortunately the black points vary from photo to photo, even at the same ISO. See https://github.com/darktable-org/darktable/issues/10008#issuecomment-922359733

**Comment by tpapp** [comment] 2021-09-28 12:47
That appears to be already reverted in `master` (cf https://github.com/darktable-org/rawspeed/pull/292#issuecomment-920315042), so can I just compile master?

**Comment by Nilvus** [comment] 2021-09-28 18:16
As this is related to already known issue in rawspeed, I close this issue. If needed, you could of course continue to discuss on this here.

**Closed by Nilvus** 2021-09-28 18:16 UTC

**Comment by Nilvus** [comment] 2021-09-28 18:19
@tpapp: you could also create an automatic preset on black/raw module with 139 value instead of 128. I have a Panasonic G9 and had create a preset as a workaround of this annoying issue from rawspeed, automatically applied to all new images (for other, a simple copy/paste of development with only this module will also help. As @kofa73 said, I also see on some images that the values could change but most of the time default good value (139 here for you) is good for most of the images. So just need to adjust on images remaining that keep a red shift.

**Comment by tpapp** [comment] 2021-09-29 07:13
@Nilvus: if this is a known open issue in rawspeed, can you please link it so I could subscribe to it?

**Comment by tpapp** [comment] 2021-09-29 14:24
In case there is no open issue, I am not sure I understand why this one was closed. This is currently an issue in darktable (incl `master`), and resolving this may be as simple as using a particular version of rawspeed, but nevertheless this is still an issue.

Can you please reopen?

**Comment by Nilvus** [comment] 2021-09-29 17:13
I don't understand what's not clear in what we precise here about this issue? THIS IS NOT darktable issue but rawspeed one. Rawspeed is a library used by darktable to read RAW. AND issue is fixed in rawspeed library (link posted by @kofa73 above) AND included in a develop branch of rawspeed that is a first step before update rawspeed used by darktable. That's why I ping here @LebedevRI which is main rawspeed developer about why this is not included in rawspeed for darktable by now as rawspeed used by darktable seems actually be stuck in septembre 11th. I don't know how this is updated but so the issue is not the same and could be why rawspeed in actual darktable master is stuck quite 15 days ago.

**Comment by tpapp** [comment] 2021-09-30 07:33
I understand that it is *assumed* that the develop branch in rawspeed would fix this, but at the moment this is *not* fixed in darktable, which is why I think it would be reasonable to have an open issue about it.

When things are updated, I can just test this in darktable and then close the issue. Closing at the moment seems premature to me.

**Comment by Nilvus** [comment] 2021-11-07 16:19
Now fixed in darktable master by update of rawspeed submodule. Should be so ok for 3.8.
