### ISSUE TITLE
Descending collection sorting not working

### ISSUE THREAD

**Issue by FalCT60** [darktable-org/darktable#15988] opened 2023-12-29 17:11 UTC
### Describe the bug

Either checking or unchecking the "Descending collection sort" has no effect.

### Steps to reproduce

1- uncheck the button so as the collections be sorted from most recent to oldest
2- save
3- check the button
4- save
5- notice there is no change in the displayed list

### Expected behavior

dt should change the order according to the button state.

### Logfile | Screenshot | Screencast

![Ascending](https://github.com/darktable-org/darktable/assets/49912948/c5d955a9-7b58-4a31-8148-57158db320a0)
![Descending](https://github.com/darktable-org/darktable/assets/49912948/7c419b67-403e-49a1-9d6e-4628600c1363)

### Where did you obtain darktable from?

self compiled

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04.3 LTS 64 bits

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment] 2023-12-29 18:17
Duplicate of #15669

**Closed** 2023-12-29 18:17 UTC
