### ISSUE TITLE
Module focus when applying/pasting style

### ISSUE THREAD

**Issue by mvrvelous** [darktable-org/darktable#8101] opened 2021-02-05 03:17 UTC
**Describe the bug**
I'm not sure if this is a bug, maybe it's expected behavior but can't find anything on it. Whenever I apply or paste a style, it changes the focused module. Let's say I'm working on exposure and I apply/paste the style in a new photo, it will jump to another module and I need to go back to go back to "show only active modules", scroll down again (while some other modules have opened up also. It's quite a hassle. 

**Expected behavior**
I would like it to stay at the module I was at last time.

**Screenshots**
- Might upload video to show

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: Windows 10

**Additional context**
Also had this with the previous version(s). So again, maybe this is expected behavior but I would not see why. It makes working on a picture maybe 3-5 times longer.

**Comment by ralfbrown** [comment] 2021-02-05 15:23
Unable to reproduce on current master, so you'll need to supply more details such as a step-by-step listing of what you do, starting from Lighttable view.

Here's what I tried out, with an image in darkroom on the active modules tab.  In all cases, the active modules tab remains current, with the same module open and focused:

- apply style via shortcut key
- apply style via the quick-select menu on the button at lower left of the center view
- jump back to lighttable, apply style from the Styles module, then return to darkroom
- reset the edit history by selecting step 0 and clicking Compress (if the open module is auto-applied)

Obviously, the open module disappears on selecting a step in the edit history where it is not active, but it comes right back, still open, on selecting another step where it _is_ active.

**Comment by johnny-bit** [comment] 2021-06-20 08:32
Tested in darktable 3.4.1.1 on windows 10 21h1 - Cannot reproduce. same procedure as ralfbrow's and the results stay the same. Only the module I selected is fucused/active.

Closing :)

> Might upload video to show

If you do upload the video and/or steps that show the issue and we'll be able to reproduce the issue then we'll reopen :)

**Closed by johnny-bit** 2021-06-20 08:32 UTC
Labels: no-issue-activity
