### ISSUE TITLE
Zooming in to 800% or 1600% when "denoise (profiled)" module is on with mode "wavelets" cause darktable to crash

### ISSUE THREAD

**Issue by lukkepcz** [darktable-org/darktable#4087] opened 2020-01-11 14:28 UTC
**Describe the bug**

Zooming in to 800% or 1600% when "denoise (profiled)" module is on with mode set to "wavelets" cause darktable to crash with "An unhandled exception occured" box showing up. The same behaviour observed when zoom is set to 1600% or 800% and "denoise (profiled)" module with the same mode is activated.

**To Reproduce**

1. Go to 'Correction group'
2. Click on 'Denoise (profiled)'
3. Set 'mode' to 'wavelets'
5. Change zoom to 1600% either by clicking 1600% or scrolling mouse wheel with Ctr

Alternatively:
1. Go to 'Correction group'
2. Click on 'Denoise (profiled)'
3. Set 'mode' to 'wavelets'
4. Deactivate 'Denoise (profiled)' module
5. Change zoon to 1600%
6. Activate 'Denoise (profiled)' module
7. See error

**Expected behavior**

Should not crash

**Screenshots**

![Error](https://user-images.githubusercontent.com/59767780/72205556-be39ae00-3484-11ea-883c-f4948360642f.png)

**Platform (please complete the following information):**
 - Darktable Version:  darktable 3.0.0
 - OS:  Windows 10
 - CPU: Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz

**Additional context**

This is observable either with previously edited and with new raws. Backtrace file is usually almost empty, I also add another bactrace file generated after the same error but with content.

[darktable_bt_68B0D0.txt](https://github.com/darktable-org/darktable/files/4049412/darktable_bt_68B0D0.txt)
[darktable_bt_6FB0D0.txt](https://github.com/darktable-org/darktable/files/4049413/darktable_bt_6FB0D0.txt)

**Comment by aurelienpierre** [comment] 2020-01-13 18:02
Does not reproduce on Linux (Intel® Xeon(R) CPU E3-1505M v6 @ 3.00GHz × 8).

**Comment by rawfiner** [comment] 2020-01-13 20:40
I can reproduce on linux
I will debug it

**Comment by lukkepcz** [comment] 2020-01-13 21:15
I reinstalled darktable - still hav

**Comment by lukkepcz** [comment] 2020-01-13 21:18
I wanted to write a "thank you" comment but I think I accidentaly closed the issue :( I'm sorry, how to undo that?

**Comment by upegelow** [comment] 2020-01-14 19:24
> I will debug it

Maybe related to the issue tackled in PR #4076

**Comment by rawfiner** [comment] 2020-01-14 19:28
@upegelow Indeed! I'll check by building, but looking at the change of your PR I am quite confident it fixed this bug :-)
Thank you!

**Comment by upegelow** [comment] 2020-01-14 19:39
Maybe a second thought on my commit is justified. 

It deals with issues like in

https://github.com/darktable-org/darktable/blob/6d897ea0eca02b7f550e6814006fb51f419c2100/src/iop/atrous.c#L518-L529

However, could there be situations where 2 * mult is below 5 and we get out of bounds due to the inner loops?

**Comment by rawfiner** [comment] 2020-01-14 20:16
I've just pulled and build, and the issue is gone.

2 * mult is below 5 for the scale 0 and the scale 1 (mult = 1 << scale), but I don't see how we can get out of bounds with the inner loop. In the inner loops, SUM_PIXEL_CONTRIBUTION_WITH_TEST is used whenever an out of bound index would be possible I think, and it tests and corrects it if needed

**Comment by upegelow** [comment] 2020-01-14 20:19
Sounds reasonable. Should be fine then.

**Comment by aurelienpierre** [comment] 2020-01-14 20:48
Closing then, feel free to reopen if needed.

**Closed by aurelienpierre** 2020-01-14 20:48 UTC
Labels: bug: wip, priority: high, reproduce: confirmed, understood: clear
