### ISSUE TITLE
Bug: Using Lua to add multiple widgets results in a crash of darktable

### ISSUE THREAD

**Issue by scheckmedia** [darktable-org/darktable#4934] opened 2020-05-07 12:34 UTC
**Describe the bug**

Hello everyone,

I'm developing an auto-tagging plugin using Lua and I encountered an error using widgets. For my plugin actually I need a list widget but I was not able to find something in the API. As a workaround, I'm using the box widget. Each tag is represented as a `check_button` and a child of the box. This works well for a small number of tags but at some point, I get an error and darktable crashes with ` PANIC: unprotected error in call to Lua API (error in __gc metamethod (Destroying a widget which is still parented, this should never happen (check_button at 0x7fd2b80be900)
))
Aborted (core dumped)
` 

**To Reproduce**

1. Save and activate the script
2. Start darktable which should contain a widget  `gc_error_test` in the ride sidebar
3. click multiple times on `Produce Error`
4. after three or four clicks darktable should crash

```Lua
local dt = require "darktable"
local du = require "lib/dtutils"

du.check_min_api_version("3.0.0", "gc_error")
local PS = dt.configuration.running_os == "windows" and  "\\"  or  "/"

local GUI = {
    container = dt.new_widget("box")
    {
        orientation = "vertical",
        sensitive = photils_installed,        
    }    
}

local counter = 0
local function crash_method()
    local box = dt.new_widget("box")
    {
        orientation = "vertical"        
    }

    for i=1,1000,1 do                
        table.insert(box,  dt.new_widget("check_button") {
            label = "item " .. counter
        })
        counter = counter + 1
    end

    if #GUI.container > 1 then
        GUI.container[#GUI.container] = nil
    end
    
    table.insert(GUI.container, box)
end


table.insert(GUI.container, dt.new_widget("button"){
    label = "Produce Error",
    clicked_callback = crash_method
})

dt.register_lib(
    "gc_error",                                                                  -- plugin name
    "gc_error test",                                                             -- name
    true,                                                                        -- expandable
    false,                                                                       -- resetable
    {[dt.gui.views.lighttable] = {"DT_UI_CONTAINER_PANEL_RIGHT_CENTER", 100}},   -- containers
    GUI.container,
    nil,-- view_enter
    nil -- view_leave
  )
```

**Expected behavior**

I've expected that, if I nil the value of the box containing the tags/check_buttons everything will be released and I can recreate a new box with N tags. 

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Ubuntu 20.04 LTS

**Additional context**

I've also used another implementation where I iterate through each tag and nil these explicit but the error is with this implementation the same.

**Comment by wpferguson** [comment] 2020-05-08 04:38
I've seen this before.  The garbage collector gets confused when you create a large number of widgets.  @boucman, who I believe implemented the darktable LUA integration was aware of it, but we were never able to determine the root cause.  I suspect it's something to do with threading.  

In the meantime what I do to get around it is:

create your widgets and add them to a table, then uppack it in the box widget.

If you still get the error/crash then insert a collectgargage("stop") line at the start of your initialization and a collectgarbage("restart") after the initialization.  This is what I had to do with tools/script_manager.lua, which also creates a lot of widgets.

If you want to attach the script that you're writing, I'll look at it and see if I see any other issues or ways to minimize the pain.

**Comment by scheckmedia** [comment] 2020-05-08 12:03
@wpferguson Thank you for your fast answer. Meanwhile, I've selected another approach. I'm using now a fixed number of possible tag widgets and have implemented a pagination approach. I think this is better than scrolling hundred of possible tags in darktable. 

I will contribute the script to the Lua scripts repository in some days.

![photils](https://user-images.githubusercontent.com/1307133/81403578-036ca480-9134-11ea-89cc-4344fda3f7d2.gif)

I don't know whether I can close the issue because my issue is solved by a workaround :)

Thanks and greetings.

**Comment by wpferguson** [comment] 2020-05-08 16:08
@scheckmedia, I like the pagination. Nice idea, nice solution.

@TurboGit should we leave this open or close it.  The issue is that when you create a large number of widgets in a lua script the garbage collector gets confused and throws errors.  This can result in a darktable crash.  I raised the issue to @boucman several years ago, but I don't think he ever found a solution.  There is a work around, which is turning off garbage collection, creating the widgets, then turning garbage collection back on.  AFAIK @scheckmedia is only the second person to stumble across this problem in the last 4 years or so.

**Comment by TurboGit** [comment] 2020-05-08 19:10
@wpferguson : I have zero experience with Lua, I think that your proposal to close this is ok as reading your message makes it clear that the issue is rare and that we won't have a solution very soon!

**Closed by TurboGit** 2020-05-08 19:10 UTC
