### ISSUE TITLE
Debian 12 Bookworm Missing Darktable application icon X11

### ISSUE THREAD

**Issue by sanju-mathew** [darktable-org/darktable#16542] opened 2024-03-29 23:32 UTC
### Describe the bug

I just compiled Darktable from the official Git repo. It is installed well in my Debian 12 Bookworm. Once the installation was completed, I created a symlink to _/usr/share/applications/org.darktable.darktable.desktop_; the link worked, but the Darktable logo is missing. I am using X11 on Debian 12.
All the information from the Git page is carefully followed. There was a very similar issue with Wayland; here is the link to the post [https://github.com/darktable-org/darktable/issues/13946](url)
I have also checked the wmclass mentioned in that post, but I still have no luck.
It would be very helpful if someone could help with this issue.
Kind regards
![Screenshot from 2024-03-29 23-18-19](https://github.com/darktable-org/darktable/assets/151461125/5de407f3-33da-4196-b969-7fc1d3ed83fd)

### Steps to reproduce

To reproduce this issue, click
![Screenshot from 2024-03-29 23-18-19](https://github.com/darktable-org/darktable/assets/151461125/2fa47834-ffa0-41e3-97ab-dbf5c29ac2cf)
 the Darktable app image.

### Expected behavior

darktable should be displaying the app icon

### Commit

git clone --recurse-submodules --depth 1 https://github.com/darktable-org/darktable.git

### Where did you obtain darktable from?

self compiled

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Debian 12 Bookworm 

### Describe your system?

AMD Ryzen™ 7 5700X × 16
Memory 32.0 GiB
Windowing System X11

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce RTX™ 3060

**Comment by rafalkrupinski** [comment] 2024-06-30 09:33
Just for some context, the .desktop file in OBS package has the proper icon.

**Comment by victoryforce** [comment] 2024-08-01 10:48
> Just for some context, the .desktop file in OBS package has the proper icon.

So there is no problem if everything is installed correctly.

> Any chance the the desktop file is referring to the icon using a relative path?

There is no answer to this question or any other response from @sanju-mathew during the month. So I'm closing this issue due to the absence of the issue creator and because I see no chance that this is our fault and not wrong user action (and yes, the relative path to the icon seems to be the cause of the problem to me too).

**Closed by victoryforce** 2024-08-01 10:48 UTC
Labels: scope: UI, scope: OS support

**Comment by tlhunter** [comment] 2024-12-05 03:56
I had an issue with a missing darktable icon in Debian bookworm with KDE + Wayland after installing darktable via apt. Here's an easy fix:

```sh
cd /usr/share/applications/
sudo cp org.darktable.darktable.desktop darktable.desktop
```
