### ISSUE TITLE
Style shortcuts in darkroom apply the style to the wrong image

### ISSUE THREAD

**Issue by sh1llo** [darktable-org/darktable#4669] opened 2020-04-10 09:32 UTC
This issue is similar to https://github.com/darktable-org/darktable/issues/4576 but for styles. It only happens when styles are applied via a shortcut, not when using the styles menu in darkroom.

Applying a style via shortcut will affect the selection instead of the current image. Chaging the current image with SPACE, BACKSPACE or clicks to the filmstrip doesn't change the selection. Furthermore, the thumbnails will not update so the change to the images is invisible until the images are revisited in darkroom.

To reproduce:

1. Create a style if you don't have any
2. Go to settings / shortcuts / global / styles and assign a shortcut to a style
3. Select an image in lighttable
4. Switch to darkroom ('D')
5. Switch to next image ('SPACE')
6. Press the style shortcut

Seemingly nothing happens but pressing BACKSPACE shows that the previous image was stealth-changed.

Expected: the current image changes unless user somehow specifically indicates a different intent.

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0 + current master 3b7a2dd4
 - OS: Ubuntu 18.04
 - 
 -

**Comment by AlicVB** [comment] 2020-04-10 12:07
yes, I've not changed anything in styles, so it should be the same issue (and the same solution as in #4576 
I'll handle that when revisiting the `get_images_to_act_on` part... apart if someone is quicker than me ;)

**Comment by GrahamByrnes** [comment] 2020-04-10 12:39
On my machine, the issue is a more general one of the absence of a refresh after applying a style in lighttable. There are plenty of consequences, but it seems to me that not being able to see the effect of double-clicking a style leads to all sorts of confusions.

I now either apply styles via the accelerator in darkroom (where the refresh happens immediately), or very systematically in lighttable, by selecting, applying, and immediately moving to DR to see the results.

I've assumed this is all pert of the lighttable growing pains... but I'd be very happy if it was fixed :-D

**Comment by AlicVB** [comment] 2020-04-10 12:59
the refreshing problem is due to the filemanager/filmstrip rewrite too. I know that all this should be fixed (and it shouldn't be too hard) it's just that I need more free time !
I'm already quite busy with lot of personal things and the culling/preview rewrite...

**Comment by GrahamByrnes** [comment] 2020-04-10 14:30
Which is all fine... just nice to know it's in process :-)

**Closed** 2020-05-11 08:58 UTC
Labels: difficulty: average, no-issue-activity, scope: UI
