### ISSUE TITLE
white balance set to camera reference in old edits

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#7145] opened 2020-12-01 01:36 UTC
**Describe the bug**
Set auto apply chromatic adaptation defaults to modern then open a film roll of old edits (display referred from 2017).  Open an image in darkroom and check the white balance and notice it's now set to camera reference.  The color calibration module is not applied.  If you set auto apply chromatic adaptation defaults back to legacy and open another film roll of old edits the white balance is still set to the original edit.  

**To Reproduce**

1. Go to settings and set auto apply chromatic adaptation defaults to modern
2. Go to collect images and open an old film roll 
3. Open an image and check the white balance
4. See that it's set to camera reference  It should have been as shot or user defined.
-->

**Expected behavior**
Old edits should retain the white balance settings they were processed with.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1925~g5eba7b2d2
 - OS: Ubuntu 18.04
 - OpenCL activated 
 - Nvidia 970m 455.38

**Comment by aurelienpierre** [comment] 2020-12-08 15:48
I tried and couldn't reproduce.

**Comment by wpferguson** [comment] 2020-12-08 21:40
I copied and saved the xmp from an old edit, then opened the file in darkroom, then closed darktable.  Here's the 2 xmp files.
[crw_0191.crw.xmp.save.txt](https://github.com/darktable-org/darktable/files/5662101/crw_0191.crw.xmp.save.txt)
[crw_0191.crw.xmp.txt](https://github.com/darktable-org/darktable/files/5662102/crw_0191.crw.xmp.txt)

**Comment by aurelienpierre** [comment] 2020-12-13 11:16
Your saved history **does not** have a temperature module, which is wrong. So darktable adds it as it should, and with the proper defaults you chose.

The real question is how did you manage to not have white balance saved in your edit history in the first place ?

**Comment by wpferguson** [comment] 2020-12-14 05:43
The file was originally imported with dt 2.2.  I created a new library and used a batch import script to repopulate the library, depending on the xmp files to reapply the edits.

**Comment by wpferguson** [comment] 2020-12-16 18:14
@aurelienpierre, does this need closed?

**Comment by elstoc** [comment] 2020-12-27 21:09
I'm seeing this issue on old edits as well now that I've upgraded my working copy to darktable 3.4

**Comment by elstoc** [comment] 2020-12-27 21:49
I think this will probably impact any image that was last edited before darktable 3.0 (I think this is where the entire stack started to be saved to the xmp) and where the default parameters for white balance were not updated as part of the edit.

**Comment by johnny-bit** [comment] 2020-12-28 09:44
The possible "solution" would be to detect 'correctly made' old xmp under old assumptions (eg there are no auto modules, but there are other modules) and insert old auto defaults for them.

**Comment by parafin** [comment] 2020-12-28 10:11
> The possible "solution" would be to detect 'correctly made' old xmp under old assumptions (eg there are no auto modules, but there are other modules) and insert old auto defaults for them.

Yes, that's how previously such issues were handled, so it looks like the way to go.

**Comment by carobinario** [comment] 2021-03-27 17:48
I can conform this bug in Darktable 3.4.1 while editing raw files that was edited using Darktable 2.6.2.

**Comment by leclercj** [comment] 2021-04-02 16:33
I have same problem using dt 3.4.1 with many (I can't say all) raw files processed with dt 2.6

**Comment by TurboGit** [comment] 2021-04-02 16:38
Ok, I'll try to reproduce and assigned this to me. I missed this bug report, it seems very bad so we need to fix that for 3.6.

**Comment by leclercj** [comment] 2021-04-02 16:43
@TurboGit , I can reproduce at will, so let me know if you need any traces or info

**Comment by TurboGit** [comment] 2021-04-02 16:49
@leclercj : One thing I would like to confirm is that this is only when loading an XMP. In other words the question is : is the history on the database for such old edits contains a _white balance_ entry ?

**Comment by elstoc** [comment] 2021-04-02 16:58
@TurboGit I find this with any edits I did in older versions of darktable. Not just with XMP. I've been going through old edits and I'm seeing it quite a lot.

**Comment by leclercj** [comment] 2021-04-02 17:11
@TurboGit : I'm observing the issue without any white balance entry in XMP, but I don't know what is in database. Do you have any sqlite3 command I can use to check this ?

**Comment by TurboGit** [comment] 2021-04-02 17:13
@elstoc : Thanks for the feedback. So we have to work at the time we do check for the need of auto applied presets and not when dealing with XMP.

@leclercj : No at this stage it is clear that this is not only for XMP.

This will be a nice one to fix :)

**Comment by elstoc** [comment] 2021-04-02 17:26
The issue here is that, at the point the image was originally processed, white balance was left at default values. At that time, we only recorded _changes_ to the database. In the new version it detects that white balance is not set, and sets it to default, which in this case is "camera reference" due to the workflow preference. I'm not sure there's an easy way to distinguish this scenario from a normal "user compressed away the wb module" scenario.

**Comment by leclercj** [comment] 2021-04-02 17:33
Correct: if I switch back to "legacy" chromatic adaptation in the preferences, I do not observe the problem any more

**Comment by wpferguson** [comment] 2021-04-02 17:38
Can we catch that there is no white balance in the history stack, then check the time of the last edit in the history stack and see if it's before 3.0 was released?

**Comment by elstoc** [comment] 2021-04-02 17:41
not everyone upgrades on the day that a new version comes out

**Comment by TurboGit** [comment] 2021-04-02 18:10
@wpferguson : No it is easier than that. If there is no white-balance we need to add one with the default values pre-3.0. There is no need to check for the edit as all edits (for RAW) must have a white balance.

**Comment by elstoc** [comment] 2021-04-02 18:13
@TurboGit the same could be true of a new edit though. No images have white balance before you load them in the darkroom. Similarly, if I move the white balance to the top of the stack and then remove it with compress history, again, there's no white balance.

**Comment by wpferguson** [comment] 2021-04-02 18:18
The blendop_version in 2.6.x was 7.  The blendop_version in 3.0 was 9.  If there's a way to check that then that would let us know.

**Comment by elstoc** [comment] 2021-04-02 18:22
@wpferguson that might work

**Comment by TurboGit** [comment] 2021-04-02 22:03
PR proposed #8599

**Comment by TurboGit** [comment] 2021-04-02 22:03
@leclercj @elstoc @wpferguson : would be nice if you could review & test the proposed PR. TIA.

**Closed** 2021-04-05 07:14 UTC
Labels: bug: pending, priority: high, reproduce: confirmed, understood: clear

**Comment by Werzi2001** [comment] 2021-04-09 21:09
I just noticed the same problem in my library. Am I getting it right that images that I opened (and maybe will open) as long as the problem is not fixed will remain incorrect even with the fix because by opening the white balance module gets added and therefore it cannot be detected by the fix anymore?

**Comment by wpferguson** [comment] 2021-04-09 21:14
Yes, but you can fix the old edit by changing the white balance back to as
shot in camera

**Comment by Werzi2001** [comment] 2021-04-09 21:20
@wpferguson Might be hard to find these. Is it possible to change the white balance directly in the library database (I don't think that I ever used "camera reference" willingly) and then update all XMP files by the content in the library?

**Comment by wpferguson** [comment] 2021-04-09 22:01
White balance wasn't stored in the database for old edits unless it was
changed from the default, which is what led to the problem.

There isn't a way to easily distinguish between old and new edits, because
once the wrong white balance is applied, then the image has a new edit.

Your best bet is to create a style with white balance set to as shot and
apply that to the messed up images.

**Comment by elstoc** [comment] 2021-04-09 23:20
> Your best bet is to create a style with white balance set to as shot and apply that to the messed up images.

My understanding is that white balance is stored as RGB coefficients and "as shot" is a calculated value whose coefficients are different for each image. White balance therefore cannot be set to "as shot" on multiple images using a style. AFAIK the only way to apply "as shot" to multiple images is manually.

**Comment by wpferguson** [comment] 2021-04-10 03:24
@Chris Elston ***@***.***> You're right.  I forgot about
that.

**Comment by Werzi2001** [comment] 2021-04-10 15:24
I recreated all thumbnails about 1 month ago and that process set the (incorrect) whitebalance for all my old images. Therefore about 30000 images were affected and doing it manually was not an option. I found a way to solve it for me and wanted to share in case it might be useful for somebody else.

First of all I needed to know which images exactly were affected. Therefore I needed a library backup from the time before the incorrect whitebalance was added. Luckily that was easy as Darktable keeps weekly backups and the time when the modules were added was obvious as the size of the library nearly doubled (~250MB => ~450MB) at that time. Using this library and the current one and a SQLite tool I checked which (old) images have a whitebalance module now but didn't in the backup. That lead me to about 28000 images (as expected). I did some sanity checks by looking at some of the images in Darktable and do (very basic) checks of the op_params value of the module in the database but at the end I decided that these images were really the ones affected. It could be that some were not really affected and I have false positives (e.g. if I really manually added a custom whitebalance to an old image between the backup and now) but I was willing to take that risk.

In order to get the correct whitebalance back for these images I removed the whitebalance module directly in the library database, switched the chromatic adaptation to legacy in darktable and removed (deleted) the generated thumbnails for the affected images in the cache. Afterwards I recreated all now missing thumbnails. This caused darktable to readd the whitebalance module but this time (as I switched to legacy) with the correct/old settings. After that I confirmed in the library that the whitebalance module was in fact added and I was not just seeing some kind of default value that will go away when switching back to modern. Finally all looked fine again and I switched back to modern.

Just as a note:
The generation of the thumbnails just adds the module in the library but does not update the sidecar files. So that process leads to inconsistent files. Anyhow this was already the case with the initial regeneration (that messed up the whitebalance) and therefore not really a step backwards.
