### ISSUE TITLE
Corrupt images when copy multiple watermarks at the same time.

### ISSUE THREAD

**Issue by MisterDeeDee** [darktable-org/darktable#8330] opened 2021-02-25 17:30 UTC
**Describe the bug**
After creating two watermarks in one photo, (simple text, and logo watermark with transparency) I try to paste  (copiede from the  history stack)  the 2 watermarks on the rest of the collection, but the image gets corrupted with vertical lines. If I paste the watermarks one by one, ther is no problem.

**To Reproduce**
1.- Open one picture of a collectyion in lightable.
2.- create a watermark with simple text option
3.- create a new instance of watermark wit a logo with transparency
4.- back to the lighttable, and copy the new watermarks from the picture in the history stack.
5.- Select multiple pictures from the collection and try to paste the watermarks.
6.- The pictures gets corrupted with vertical black lines.

**Expected behavior**
Watermarks aplied to the selected pictures where the watermarks are pasted in.

**Platform (please complete the following information):**
 - Darktable Version: 3.4.1.1
 - OS: Windows 64
 - Nvidia GeForce GTX 1080, 
 - Nvidia Drivers 461.40

**Additional context**
The issue is not present in Darktable 3.2.1 version. Always worked fine until I upgraded to the latest version.
![2-2](https://user-images.githubusercontent.com/62974803/109192464-89c3a700-7797-11eb-8aea-ac22e0341d70.jpg)
![1-2](https://user-images.githubusercontent.com/62974803/109192467-8a5c3d80-7797-11eb-85c4-78fc46d079cc.jpg)

**Comment by ralfbrown** [comment] 2021-02-25 23:34
This looks like it may be a duplicate of #7655 (see also #8049 and #8235).  Was the source image's history stack created before your upgrade?

**Comment by MisterDeeDee** [comment] 2021-02-26 11:13
> 
> 
> This looks like it may be a duplicate of #7655 (see also #8049 and #8235). Was the source image's history stack created before your upgrade?
No it wasnt, I uninstalled Darktable, and deleted the Darktable users folder. Remake from scratch the watermarks and the issue persists.

**Comment by ptilopteri** [comment] 2021-02-26 13:35
did you delete or move the xmp file associated with subject image?

**Comment by MisterDeeDee** [comment] 2021-03-01 15:52
> 
> 
> did you delete or move the xmp file associated with subject image?

Yes, the XMPs files associated were deleted.

**Comment by DominusFulguris** [comment] 2021-03-11 12:08
I have been having the very same issue. Using 3.4.1.1 on Windows.

I use two watermark instances and these are copied/pasted via lighttable/history stack.

If I "discard history" on a target image and then paste history without the watermarks, no problem.

Film rolls were imported with the same version and I haven't done anything with sidecar files.

Both Sony and Canon raws are affected.

**Comment by Nilvus** [comment] 2021-03-25 18:51
> > did you delete or move the xmp file associated with subject image?
> 
> Yes, the XMPs files associated were deleted.

Could you share image with the issue and XMP? Did you try to duplicate corrupted image with an original clone (with duplicate manager in darkroom) with so a default history, then copy/paste corrupted history to new clone. If this fix the issue, so that same issue than closed ones cited by @ralfbrown and so a fixed one (in 3.2.1). And I see that you explain that you don't have it in 3.2.1 but in 3.4.1.1. But what's annoying with this issue it's that it could appear later, depending on how you use (or not) 2 instances of same module. It's fixed now to not appear in totally new images and history but could still appear for some past history/images.

So, it would be good to test what I suggest here. 2 issues then:
- you have a good image on duplicate one, so just delete corrupted one and close this issue. That's the same fixed issue cited in @ralfbrown comment above.
- you still have the issue, and maybe something remaining specific to watermark module (or something else).

**Comment by MisterDeeDee** [comment] 2021-03-26 20:04
> 
> 
> > > did you delete or move the xmp file associated with subject image?
> > 
> > 
> > Yes, the XMPs files associated were deleted.
> 
> Could you share image with the issue and XMP? Did you try to duplicate corrupted image with an original clone (with duplicate manager in darkroom) with so a default history, then copy/paste corrupted history to new clone. If this fix the issue, so that same issue than closed ones cited by @ralfbrown and so a fixed one (in 3.2.1). And I see that you explain that you don't have it in 3.2.1 but in 3.4.1.1. But what's annoying with this issue it's that it could appear later, depending on how you use (or not) 2 instances of same module. It's fixed now to not appear in totally new images and history but could still appear for some past history/images.
> 
> So, it would be good to test what I suggest here. 2 issues then:
> 
>     * you have a good image on duplicate one, so just delete corrupted one and close this issue. That's the same fixed issue cited in @ralfbrown comment above.
> 
>     * you still have the issue, and maybe something remaining specific to watermark module (or something else).


Hi, @Nilvus
First of all, im going to replicate error, and then following the instructions in the past post.

Replication error:
-Import a new folder with .CR2 extension pictures.
![1](https://user-images.githubusercontent.com/62974803/112680115-411e0d00-8e6d-11eb-8be4-7a313a25e369.jpg)

-Open first picture in DarkRoom , and aplly two watermarks, first a image wit the semi trasnparent logo, then I duplicate the instance of the watermark, to insert a simple text.
![2](https://user-images.githubusercontent.com/62974803/112680783-15e7ed80-8e6e-11eb-8808-50a90d5510cf.jpg)

- Copy parts ( watermarks) from the copy parts option in the history stack section
![3](https://user-images.githubusercontent.com/62974803/112681118-8bec5480-8e6e-11eb-9418-7071ede520de.jpg)

- Select all pictures and paste parts option( the two watermarks selected)
![4](https://user-images.githubusercontent.com/62974803/112681319-d1a91d00-8e6e-11eb-871f-dcc17d914057.jpg)

- The result is all pictures corrupted except the first one. If I discard the history the pictures are fine.
![5](https://user-images.githubusercontent.com/62974803/112681582-3ebcb280-8e6f-11eb-9a0f-6094988985a6.jpg)

This is one picture sample and one XMP file of one corrupted picture.
![IMG_3216](https://user-images.githubusercontent.com/62974803/112681962-b4288300-8e6f-11eb-83bb-9b21798d60e2.jpg)

This is the asociated XMP file to that pic.
 ##[IMG_3216.CR2.zip](https://github.com/darktable-org/darktable/files/6213876/IMG_3216.CR2.zip).

Now im going to try to copy the history to an uncorrupted clone.
- I aply the watermarks in the same way described before.
![6](https://user-images.githubusercontent.com/62974803/112683312-a8d65700-8e71-11eb-8f02-fab0c746e5ff.jpg)

- I duplicate the target picture
![7](https://user-images.githubusercontent.com/62974803/112683463-e2a75d80-8e71-11eb-8999-a9d4196b5a83.jpg)

- Paste the watermarks to the original picture.
![8](https://user-images.githubusercontent.com/62974803/112683718-49c51200-8e72-11eb-97f2-c324c4ce90bb.jpg)

-Removed the original and paste the history to the clone picture, the resul is the same.
![10](https://user-images.githubusercontent.com/62974803/112683875-898bf980-8e72-11eb-9b89-cae45c4bb819.jpg)

Ive found a way to make this process without error:
- First of all I copy parts ( the two watermarks) from the history stack of the original modified picture like I explained before.
- Then I paste the Simple text Watermark, and once aplied I paste the second watermark with the semi transparent logo. This way works fine. If I paste the logo before the text, the logo disapears and the image gets corrupted.

I hope this long post can help you to replicate and fix the bug. If you need more information just ask for it.

Greetings from Sopelana.

**Comment by DominusFulguris** [comment] 2021-03-27 00:43
This is pretty consistent with what I have been experiencing.One watermark with a custom graphic, other simple text with image ID.Not been using cloned images at that point and never mucked with xmp files.
-------- Original message --------From: MisterDeeDee ***@***.***> Date: 27/3/21  7:04 am  (GMT+10:00) To: darktable-org/darktable ***@***.***> Cc: DominusFulguris ***@***.***>, Comment ***@***.***> Subject: Re: [darktable-org/darktable] Corrupt images when copy multiple
  watermarks at the same time. (#8330) 



did you delete or move the xmp file associated with subject image?

Yes, the XMPs files associated were deleted.

Could you share image with the issue and XMP? Did you try to duplicate corrupted image with an original clone (with duplicate manager in darkroom) with so a default history, then copy/paste corrupted history to new clone. If this fix the issue, so that same issue than closed ones cited by @ralfbrown and so a fixed one (in 3.2.1). And I see that you explain that you don't have it in 3.2.1 but in 3.4.1.1. But what's annoying with this issue it's that it could appear later, depending on how you use (or not) 2 instances of same module. It's fixed now to not appear in totally new images and history but could still appear for some past history/images.
So, it would be good to test what I suggest here. 2 issues then:
* you have a good image on duplicate one, so just delete corrupted one and close this issue. That's the same fixed issue cited in @ralfbrown comment above.

* you still have the issue, and maybe something remaining specific to watermark module (or something else).


Hi, @Nilvus
First of all, im going to replicate error, and then following the instructions in the past post.
Replication error:
-Import a new folder with .CR2 extension pictures.

-Open first picture in DarkRoom , and aplly two watermarks, first a image wit the semi trasnparent logo, then I duplicate the instance of the watermark, to insert a simple text.



Copy parts ( watermarks) from the copy parts option in the history stack section



Select all pictures and paste parts option( the two watermarks selected)



The result is all pictures corrupted except the first one. If I discard the history the pictures are fine.



This is one picture sample and one XMP file of one corrupted picture.

This is the asociated XMP file to that pic.
##IMG_3216.CR2.zip.
Now im going to try to copy the history to an uncorrupted clone.


I aply the watermarks in the same way described before.



I duplicate the target picture



Paste the watermarks to the original picture.



-Removed the original and paste the history to the clone picture, the resul is the same.

Ive found a way to make this process without error:

First of all I copy parts ( the two watermarks) from the history stack of the original modified picture like I explained before.
Then I paste the Simple text Watermark, and once aplied I paste the second watermark with the semi transparent logo. This way works fine. If I paste the logo before the text, the logo disapears and the image gets corrupted.

I hope this long post can help you to replicate and fix the bug. If you need more information just ask for it.
Greetings from Sopelana.

**Comment by johnny-bit** [comment] 2021-06-19 10:36
I think it's duplicate of #7477 (fixed in current master)
or duplicate of  #8547 (also fixed in current master)
and similar (fixed in current master).

Unfortunately the fix didn't make it to 3.4 branch, but will be part of 3.6 release comming in just 2 weeks :)

So - while I can reproduce the issue on 3.4, i can't do it on current master which means the issue is fixed so closing :)

**Closed by johnny-bit** 2021-06-19 10:36 UTC
Labels: no-issue-activity
