### ISSUE TITLE
Darktable 4.6.0 crashes when clicking "show global preferences"

### ISSUE THREAD

**Issue by esm7** [darktable-org/darktable#16293] opened 2024-02-11 08:17 UTC
### Describe the bug

After upgrading to Darktable 4.6.0, as soon as I click "show global preferences", the application exists.

### Steps to reproduce

1. Open Darktable (shown in Lighttable mode).
2. Click "show global preferences" (the button before the "lighttable" title).

### Expected behavior

Open the preferences dialog.

### Logfile | Screenshot | Screencast

[darktable_bt_YO9TI2.txt](https://github.com/darktable-org/darktable/files/14231737/darktable_bt_YO9TI2.txt)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Manjaro

### Describe your system?

An updated Manjaro distro. X11.

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by pehar1** [comment] 2024-02-11 08:48
Cannot reproduce with 4.7.0+524~g44b346cc0f, Ubuntu 22.04

Did you try launching darktable from the commandline with a fresh configuration  ( `--configdir <dirname>` ) , `dirname` pointing to an empty or non existing directory. See https://darktable-org.github.io/dtdocs/en/special-topics/program-invocation/darktable/

Can you provide a debug log of the crash ( for example `-d common` or `-d all` ) ?

**Comment by esm7** [comment] 2024-02-11 09:42
1. Launching Darktable with a fresh configuration opens fine. Are there hints in the crash log what's part of my configuration is causing this? (it worked before upgrading just a few days ago)
2. Attached is the debug log using `-d all`.
[darktable_bt_TCQWI2.txt](https://github.com/darktable-org/darktable/files/14231888/darktable_bt_TCQWI2.txt)

**Comment by pehar1** [comment] 2024-02-11 10:09
> Darktable with a fresh configuration opens fine

Possibly a damaged `darktablerc` ? You can check this by restoring your old configuration **without** `darktablerc`, then launching darktable again. Still crashing ?

You provided a backtrace of the crash. The debug log `-d all` is the terminal output of darktable before it crashes. You can redirect it to a file, for example `darktable -d all > path/to/logfile.txt`

**Comment by esm7** [comment] 2024-02-11 10:14
I deleted `darktablerc`, it opened with what seemed to be some default configuration (e.g. not my style settings), but still crashed the same.
Here's a log with `-d all` directed to file.
[log.txt](https://github.com/darktable-org/darktable/files/14231986/log.txt)

**Comment by pehar1** [comment] 2024-02-11 10:38
From the log for me this looks like a problem with your presets. They are saved in `data.db`. Can you check again with your old configuration but now **without** `data.db` ?

**Comment by esm7** [comment] 2024-02-11 10:52
Launching without `data.db` works, I can open the global preferences.
Is there a way to narrow down the issue further?

**Comment by pehar1** [comment] 2024-02-11 11:01
Inside `data.db` there is a table `presets`. One could try to analyze the content of this table. But for this we need an expert for darktables databases...
Does anyone feel addressed ? @TurboGit ?

**Comment by pehar1** [comment] 2024-02-13 07:50
@esm7 , do you still have an older darktable version? And backups of your databases ( `...-pre-4.6.0` ) ? Can you open the preferences dialog with this version ? In this case, you can also try to narrow down the problem further by exporting your personal presets using _Preferences_ -> _Presets_ -> _Export_.
Then start darktable 4.6.0 without `data.db` and try to re-import your exported presets step by step.

**Comment by esm7** [comment] 2024-02-13 10:14
I have all the backups (great thing that Darktable saves them) but not quite sure how to install an older Darktable on Manjaro as a rolling release. I'll look into it.

**Comment by pehar1** [comment] 2024-02-13 15:17
Disclaimer: I never used Manjaro, so I can't tell you for sure if this would work...
https://wiki.manjaro.org/index.php/Downgrading_packages#Introduction

**Comment by esm7** [comment] 2024-02-25 08:33
Sorry for the holdup. I tried to give this a go but downgrading packages in Manjaro/Arch is a hit or miss, and this time it was a miss... Since the whole distro is rolled as one unit, a downgrade of a single package quickly escalates into a dependency hell.
At least that's my experience...
I tried with the `manjaro-downgrade` utility, but starting from an incompatibility with `libjxl.so.0.8` and going further, it became too much of a project :(

**Comment by esm7** [comment] 2024-02-25 08:40
Sorry for the holdup. I tried to give this a go but downgrading packages in Manjaro/Arch is a hit or miss, and this time it was a miss... Since the whole distro is rolled as one unit, a downgrade of a single package quickly escalates into a dependency hell.
At least that's my experience...
I tried with the manjaro-downgrade utility, but starting from an incompatibility with libjxl.so.0.8 and going further, it became too much of a project :(
Is there any way to export presets from the command line or without opening the settings window?

**Comment by ptilopteri** [comment] 2024-02-25 14:03
presets are contained in ~/.config/darktable/data.db
and visible using sqlite3 or sqlitebrowser or ...

**Comment by pehar1** [comment] 2024-02-26 09:22
Example to just list the content of a table as terminal output (create a backup copy of your database first) :
`sqlite3 /path/to/your/data.db "select * from presets"`
but consider: the table contains BLOBs (Binary Large Objects) which are not human readable

... or dump the content of table `presets` into a file with SQL commands
```
$ sqlite3 /path/to/your/data.db
.output /path/to/presets.sql
sqlite> .dump presets
sqlite> .quit
```
Part of these commands (`INSERT INTO`) could be used to reimport (part of) your presets into a fresh database.

... or you can use a tool with graphical user interface like `SQLiteStudio` (only one example of several tools available)

**Comment by ralfbrown** [comment] 2024-05-20 05:06
Closing as this is a file-corruption problem specific to the OP's system, who has not responded further for over two months.

**Closed by ralfbrown** 2024-05-20 05:06 UTC
Labels: no-issue-activity
