### ISSUE TITLE
Tooltips Issues in darkroom modules

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6901] opened 2020-11-14 06:00 UTC
3.3.0+1591~g0aeaa230b

git pull : 660dc23..0aeaa23 master

1. Any modules purpose in the tooltip shows a square icon, this usually happens when the character used is unavailable on the system.
I am on a ubuntu 20 system on a windows linux sub system.

![image](https://user-images.githubusercontent.com/1119439/99140971-40c66780-266c-11eb-83cd-05c111abdc06.png)

2. Surface blur module does not have a tooltip.

**Comment by parafin** [comment] 2020-11-14 08:27
1 was caused by !6858, I warned about this there, but PR was merged regardless.

**Comment by TurboGit** [comment] 2020-11-14 11:24
@parafin : yes merged to see what is happening on other environments, and here we go... let's try to see what could be done.

Here we have blocker though... It is Windows but hidden under WSL !

@chhil : What happens on Windows native ? If it is the same, then we can at least replace first icon on Windows platforms. Now we certainly won't fix the issue under WSL. Note that Aurélien tried to find a way to ask pango about available Glyph but it seems difficult has the doc is really missing some pieces. And i can confirm that as I spent about 1h yesterday trying to make sense of PangoFontContext & PangFont....

**Comment by chhil** [comment] 2020-11-14 11:28
Building it now to test. Will report back.

**Comment by parafin** [comment] 2020-11-14 11:32
I suspect WSL behaves the same as plain Linux in regard to fonts. Someone can try a fresh install of Ubuntu (e.g. in VM) and check what fonts are there - just open a text editor and paste these characters there. I'm not sure why you keep insisting that it's more a problem for Windows and macOS. IMHO on these platforms it's more likely that a lot of fonts are installed out-of-the-box, while Linux installation vary much more and you basically can rely only on English characters being rendered OK. I will repeat my suggestion from original PR - replace that first icon with something else, it will decrease the chances of this issue significantly.

**Comment by TurboGit** [comment] 2020-11-14 11:48
> I'm not sure why you keep insisting that it's more a problem for Windows and macOS.

Because at this stage such problems were only reported by Windows users. I don't remember a Linux users reporting that, no? I don't remember a MacOS user reporting this, do you have this icon parafin on your MacOS box ?

Anyway, I agree with you for replacing the first character. Let's see what @chhil reports.

**Comment by TurboGit** [comment] 2020-11-14 11:54
BTW, for purpose just a simple ? or  ↷ or ↻ may be ok, what do you think ? The two later are from the standard arrows section, should be safe.

**Comment by parafin** [comment] 2020-11-14 11:55
Erhm, I was the first to mention that this icon isn't rendered for me and explicitly stated that it happens on Linux.

**Comment by TurboGit** [comment] 2020-11-14 11:56
@parafin : sorry, I read too many things those days...

**Comment by parafin** [comment] 2020-11-14 11:57
Arrows are rendered for me fine.

**Comment by chhil** [comment] 2020-11-14 11:59
The first one shows up as a "?" in @TurboGit  [reference ](https://github.com/darktable-org/darktable/issues/6901#issuecomment-727196159) of arrows. I am on windows.

**Comment by TurboGit** [comment] 2020-11-14 12:00
@chhil : yes that a ? char.

What about others ? And this one ⟳ ?

**Comment by chhil** [comment] 2020-11-14 12:02
I thought it was easier to paste what I see

![image](https://user-images.githubusercontent.com/1119439/99146561-586b1380-269f-11eb-9389-36c5526489cc.png)

**Comment by chhil** [comment] 2020-11-14 12:22
Windows build installed...
On windows its worse.

The first and third rows show up as boxes similar to the linux one, 
The second and fourth row appear horizontal lines , I guess its not rendered well as in my linux case. But definitely linux ones are identifiable.

Unfortunately I cannot take a screenshot and the video capture too does not work when DT is run.
The op image was a screengrab from a video as the shortcut keys to grab a screen capture close the tooltips.

**Comment by TurboGit** [comment] 2020-11-14 13:03
Ok, so I'll use ⟳ for first icon and on Windows I'll default all to plain bullet (as use in the info line). And I'll let a Windows dev propose something that works there. @chhil : if you have some spare time to propose 4 icons for Windows that works well it would be really nice.

**Comment by TurboGit** [comment] 2020-11-14 13:20
Done. @chhil : as I said feel free to propose 4 icons for Windows and I'll update the standard bullets.

**Closed by TurboGit** 2020-11-14 13:20 UTC
Labels: bug: pending, priority: high

**Comment by chhil** [comment] 2020-11-14 13:21
Is the plan to have different characters for windows and unix?

Maybe pick something from wingdings-wingdings3 which is available on all windows system https://docs.microsoft.com/en-us/typography/font-list/wingdings

![image](https://user-images.githubusercontent.com/1119439/99147844-1d221200-26aa-11eb-8f4f-f63d87687fef.png)


![image](https://user-images.githubusercontent.com/1119439/99147875-50fd3780-26aa-11eb-9112-0460208ccfd4.png)

For what its worth, pick bullet points, I don't see a need the icon to be specific to the text describing it.

**Comment by TurboGit** [comment] 2020-11-14 14:00
> Is the plan to have different characters for windows and unix?

Yes.

**Comment by TurboGit** [comment] 2020-11-14 14:02
> Maybe pick something from wingdings-wingdings3 which is available on all windows system

Which I don't have. So if you could ack the last function in `src/develop/imageop.c` and replace the icons in the _WIN32 section it would be really nice.

**Comment by TurboGit** [comment] 2020-11-14 14:03
See the code:

```
#ifdef _WIN32
  // TODO: a windows dev is needed to find 4 icons properly rendered
  const char *icon_purpose = "•";
  const char *icon_input   = "•";
  const char *icon_process = "•";
  const char *icon_output  = "•";
#else
```

**Comment by chhil** [comment] 2020-11-15 03:06
I confirm on linux, the "purpose" icon is correctly displayed now.

![image](https://user-images.githubusercontent.com/1119439/99161861-92c6c600-271c-11eb-9906-33a1a344c9c0.png)

Windows is building, will share results later.

**Comment by chhil** [comment] 2020-11-15 03:53
> See the code:
> 
> ```
> #ifdef _WIN32
>   // TODO: a windows dev is needed to find 4 icons properly rendered
>   const char *icon_purpose = "•";
>   const char *icon_input   = "•";
>   const char *icon_process = "•";
>   const char *icon_output  = "•";
> #else
> ```


Windows , works as designed.
![image](https://user-images.githubusercontent.com/1119439/99162460-0e784100-2724-11eb-9e0d-3b56e7c52be3.png)

**Comment by chhil** [comment] 2020-11-15 03:55
@TurboGit 
Any scope of aligning the ":" character ?

Linux it appears correctly justified, windows it's not.

**Comment by TurboGit** [comment] 2020-11-15 15:13
It all depends on the font actually used, nothing really we can do a tab is just that depending on the current position on the line it will fo to the next tab-stop (every 8 chars I suppose).
