### ISSUE TITLE
Before and after

### ISSUE THREAD

**Issue by scapster** [darktable-org/darktable#9780] opened 2021-08-09 16:03 UTC
**Is your feature request related to a problem? Please describe.**

Difficult and slow to do a before and after review of an image. Snapshots suck since zooming is not properly available for both images

**Describe the solution you'd like**

Add a feature for image review where you can compare before an after at current zoom levels. Click and hold on the image at work would be best.

**Alternatives**

Go back to using Lightroom and give Adobe my firstborn

**Additional context**

Seriously missing from an otherwise very capable editor.

**Comment by aurelienpierre** [comment] 2021-08-09 16:13
This involves spawning 2 concurrent pipelines, multiplying RAM and/or vRAM headroom by 2 and having to synchronize them in 2 different threads. Said otherwise, it's a can of worms.

The first question to ask is why do you need snapshots at same zoom level for ? For example, if it's only to assess focusing/sharpness, there are already other options available for this purpose.

**Comment by scapster** [comment] 2021-08-09 17:00
Every other editor is able to do this. Even Google Photos on your phone can handle this happily. I am not saying that it doesn't require skill to be able to do it but it certainly is possible since others are doing it as well. Darktable is targeting a photographer user base that is for one reason or other not satisfied with how Lightroom or Capture One does things, mainly cost. For that most are willing to give up some features but overall the product needs to be pretty good or you can just use the above mentioned Google Photos Editor which has decent performance and does editing well enough for many. Darktable fills that niche for people that want more editing capability but don't want to spend the $20 a month for Lightroom or Capture One, mainly amateur enthusiasts. If you fall into that category your workflow is not perfectly defined nor is you eye or even your monitor calibrated enough to evaluate minute differences in images. When it comes to changes in white balance or even shadow/highlight changes, curve shapes or even sharpening or vignette intensity a back and forth comparison (at your current zoom level) to your original or previously edited image is a nice feature to have available as a shortcut and would suit Darktable very well.

**Comment by elstoc** [comment] 2021-08-09 17:08
This is a duplicate of #2784. Please search for existing issues before raising a new one.

**Comment by aurelienpierre** [comment] 2021-08-09 17:09
I don't care what every other editor is able to do. darktable is able to process pictures on both CPU and GPU, and switch from each other transparently, it comes at a price that most other soft don't have to pay.

> Darktable is targeting a photographer user base that is for one reason or other not satisfied with how Lightroom or Capture One does things, mainly cost.

No, definitely not. darktable is targeting Linux users who can't run either Lightroom or Capture One on their OS. We have no desire to compete with software that have huge budget and resources with only a handful of part-time devs only to get users asking us to develop the same features for 0 $. That's simply unfair and disgusting.

> When it comes to changes in white balance or even shadow/highlight changes, curve shapes or even sharpening or vignette intensity a back and forth comparison (at your current zoom level) to your original or previously edited image is a nice feature to have available as a shortcut and would suit Darktable very well.

You don't need zoom support to do that. Actually, it's even bad to compare images when zoomed-in.

**Comment by scapster** [comment] 2021-08-09 17:21
Easy boy, easy.


"darktable is an open source photography workflow application and raw developer. A virtual lighttable and darkroom for photographers. It manages your digital negatives in a database, lets you view them through a zoomable lighttable and enables you to develop raw images and enhance them."

Not a word about Linux as a target audience, not my words. It is the first thing that comes up on the Darktable website.

"If you feel like contributing to this project, here are a few suggestions.

… in terms of testing:
Just use it! And afterwards let us know how you like it. Send your bug reports, feature requests, suggestions or just your personal opinion to our mailing list. You can file a bug to our bug tracker as well – but maybe you want to discuss it first (on IRC or mailing list)."

Feature requests, that's what I sent and now some dickhead is busting my chops. 

Don't advertise what you don't want to deliver

**Comment by elstoc** [comment] 2021-08-09 17:28
Calling our developers dickheads is not ok, and this is a duplicate issue.

**Closed by elstoc** 2021-08-09 17:28 UTC
Labels: duplicate

**Comment by scapster** [comment] 2021-08-09 17:30
I would like to remind you that there are only 2 kinds of people on Earth : those looking for solutions and those looking for excuses. 

Pierre's own words.

Just because you don't charge doesn't mean you don't have customers!

**Comment by scapster** [comment] 2021-08-09 17:33
> Calling our developers dickheads is not ok, and this is a duplicate issue.

Apologies Pierre, I removed it. 


You shouldn't let him handle customer requests.

**Comment by aurelienpierre** [comment] 2021-08-09 17:49
I have made no excuse here, I have explained that :

1. darktable is not what you think it is (aka not a cheap LR for cheap users – that's your interpretation), 
2. what you are asking has technical pitfalls you may not want to deal with (you will be happy when the 2 pixelpipes overflow your limited GPU memory and both run on slow CPU),
3. the feature you are asking actually does not serve your end goal,
4. trying to reproduce some other soft's feature for the sake of it is worthless.

Last time I checked, to be a "customer" involved a commercial transaction. If that's your childish way of trying to get noticed with grown-up words and of reminding us that you matter, well, then message received and fallacy decrypted.

For the rest, go fuck yourself.

**Comment by codingdave** [comment] 2021-08-09 19:13
If you don't mind i enter this unpleasant discussion with a productive proposal: when we zoom into the image while we have the snapshot open the snapshot does not zoom but stays at the level of zoom it was taken at. It feels like a bug because it's not synchronous anymore. So we could either implement the can of worms or we could disallow to zoom when the snapshot feature is on (and zoom to fit when we have already zoomed in and the snapshot it's turned on). I believe this is very explicit and clean behavior.
