### ISSUE TITLE
Default UI language is Russian?

### ISSUE THREAD

**Issue by jaakla** [darktable-org/darktable#4038] opened 2020-01-05 22:33 UTC
After fresh install (OSX, installed using downloaded latest DMG) initial UI language is _Russian_. It is not easy to find place where to change it back to something more universally usable like English. I'm pretty sure my computer settings have nothing about Russian language; it may indicate some Estonian language or country settings through. Estonian language is about as far to Russian as English is to Chinese, even through they are not geographically far enough.

**Comment by timur-davletshin** [comment] 2020-01-06 07:40
@jaakla tried running LANG=et_EE.UTF-8 'darktable' — it loads English as substitute. What's your locale settings?

> It is not easy to find place where to change it back

Come on! Estonians perfectly understand Russian. I was in Tallin last year.

**Comment by jaakla** [comment] 2020-01-06 07:53
Some generations do understand it here for sure, the others consider even spelling Tallinn with single n (as in Russian) as a political statement and dont know Cyrillic. :)
Shell-level locale is:
```
$ locale
LANG=
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```
OsX level locale: 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/5609650/71803787-5b05e100-306a-11ea-8c48-131220628fd5.png">

**Comment by timur-davletshin** [comment] 2020-01-06 08:16
Can't confirm, works fine for me. Why do you keep Russian in preferred languages if you don't speak it?

**Comment by parafin** [comment] 2020-01-06 08:25
Some locale selection logic was removed in 3.0 compared to 2.6 due to changes required by macOS Catalina. I don't have enough knowledge on how GTK locale interacts with macOS settings to fix it.

**Comment by timur-davletshin** [comment] 2020-01-06 08:32
@parafin first, I believe, he should try to remove Russian from preferred languages list. I doubt that it will fall back to Russian.

**Comment by parafin** [comment] 2020-01-06 08:44
Yes, I agree, but Russian is last in the list, not first, so English should have been chosen automatically as a default instead.

**Comment by timur-davletshin** [comment] 2020-01-06 08:45
@parafin darktable doesn't have UK English in supported list.

**Comment by timur-davletshin** [comment] 2020-01-06 08:47
@parafin same for Estonian. If English is not en_US then (if some creepy strict logic was applied) it will fall back to Russian.

**Comment by parafin** [comment] 2020-01-06 08:59
Right, makes sense. So probably adding English (US) might help.

**Comment by timur-davletshin** [comment] 2020-01-07 15:39
> even spelling Tallinn with single n (as in Russian)

Proper Russian spelling is Revel'.

**Comment by timur-davletshin** [comment] 2020-01-07 15:42
@jaakla I think you can close this report. It's not a bug IMO. You can join translation team and make all Estonian users happy. It's not that hard and only about 2500 strings. As far as I remember.

**Comment by mkovalen** [comment] 2020-03-13 00:33
Same problem here – the interface is in Russian straight out of the DMG. Downloaded on Feb 25. First system language is English (US). While Russian is not a problem for me, the default interface on Mac OS 10.13.6 offers no clues as to how to change the language. I have no idea what "tried running LANG=et_EE.UTF-8 'darktable' — it loads English as substitute" means (see above). What am I supposed to do with it?

Looks like a bug to me. Please fix instead of looking for reasons not to. Not a good first impression for a potential new user.

Thank you!

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

![Screen Shot 2020-03-12 at 19 21 35 ](https://user-images.githubusercontent.com/9467216/76578689-68d74880-6497-11ea-8230-93c543150d4a.PNG)

**Comment by mkovalen** [comment] 2020-03-13 00:42
I finally found **preferences > GUI options > interface language** selector that was blank. Upon selection of **English** and a program restart the interface is now in English. Hope this helps to debug but still is a problem.

Just curious, what does the development team has against capital letters? There are very few of them in the interface.

**Comment by parafin** [comment] 2020-03-13 08:55
Feel free to fix this language bug and create a pull request, I've already explained what's happening here and that I won't be able to fix it (and there's no other active macOS developers in darktable project).

**Comment by aurelienpierre** [comment] 2020-03-14 00:37
> Just curious, what does the development team has against capital letters? There are very few of them in the interface.

That's for legacy reasons and to honour the founder's wishes, but I would be very happy with capitals.

**Comment by abby142** [comment] 2020-05-30 13:34
If anyone else, like me, doesn't know Russian, its ** ⚙️ (settings) > интерфейс > язык интерфейсa** There is a box to the right where you can choose the language. Then just restart the program.

**Comment by mcint** [comment] 2020-06-13 23:37
After messing with "Preferred languages" in the macOS "Language & Region" tab of System Preferences, I observe that:
- if the primary language is not English, it is used by darktable
- if the primary language is English, and other Preferred languages are present:
  - the first among non-English languages is chosen

Maybe a maintainer would know if this is darktable-specified behavior, or a default behavior from GTK.

**Closed** 2020-09-12 20:53 UTC
Labels: no-issue-activity, reproduce: peculiar, scope: OS support, scope: translation, understood: incomplete
