### ISSUE TITLE
4.2.1 nor master will build with GCC 13 - upstream GCC issue

### ISSUE THREAD

**Issue by leanderhutton** [darktable-org/darktable#14057] opened 2023-03-28 19:29 UTC
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

After checkout of release-4.2.1 from Github on Fedora 38 building fails with this error:

```
/src/darktable/src/libs/tagging.c: In function ‘_pop_menu_dictionary_edit_tag’:         
/src/darktable/src/libs/tagging.c:1935:26: error: ‘category’ may be used uninitialized [
-Werror=maybe-uninitialized]                                                                         
 1935 |       gint new_flags = ((gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(category)) ? DT_TF_CA
TEGORY : 0) |                                                                                        
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~           
compilation terminated due to -Wfatal-errors.                                                        
cc1: all warnings being treated as errors
```
Tried with the master branch as well with the same results, also cloned out a fresh copy of the repo just to be sure. 

**To Reproduce**

```
sudo dnf builddep darktable
git clone --recurse-submodules --depth 1 https://github.com/darktable-org/darktable.git
cd darktable
git fetch --tags
git checkout tags/release-4.2.1
./build.sh --prefix /opt/darktable --build-type Release --install --sudo
```

**Expected behavior**

darktable built and installed to /opt

**Which commit introduced the error**

Not sure this is applicable here, think this may be related to F38 itself, the last change tagging.c was: 

[06b06f3](https://github.com/darktable-org/darktable/commit/06b06f331a6e48c3c6fdb4b0f8952b1e2c92800a) Mar 13, 2023

I could still build it (on F37) at that time. 

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : release-4.2.1
* OS                :  6.2.8-300.fc38.x86_64
* Linux - Distro    : Fedora 38
* Memory            :  64GB
* Graphics card     :  Intel ADL GT2/nVidia RTX 3060
* Graphics driver   :  Intel i915/nVidia 530.41.03
* OpenCL installed  : yes
* OpenCL activated  :  doesn't get that far
* Xorg              :  1.20.14-18.fc38.x86_64
* Desktop           :  GNOME 44
* GTK+              :  4.10
* gcc               :  gcc-13.0.1-0.8
* cflags            :  default in build.sh 
* CMAKE_BUILD_TYPE  : release

**Additional context**
 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 Yes, master branch

**Comment by kmilos** [comment] 2023-03-28 20:38
Might as well change the title to GCC 13. There's probably more warnings that have become errors now.

**Comment by victoryforce** [comment] 2023-03-29 08:16
@leanderhutton It looks like you're not compiling the latest git master as the commit you're referring to as the latest one in tagging.c was made specifically to fix the compile error you reported. Therefore, if you wanted to report this specific error, the issue can be closed.

**Comment by leanderhutton** [comment] 2023-03-29 11:07
@victoryforce opps, for some reason I think I forgot git switch - when reporting. 

Master still fails though:

```
/src/darktable/src/iop/colorchecker.c: In function ‘commit_params’:
/src/darktable/src/iop/colorchecker.c:723:35: error: ‘__builtin_memset’ writing 32 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  723 |       for(int i=N;i<N+4;i++) b[i] = 0;
      |                              ~~~~~^~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
```

for sanity check:
```
[leander@host darktable]$ git branch
* master
```
Updated submodules with:

```
git submodule update --init
```

**Comment by leanderhutton** [comment] 2023-03-29 11:28
Build success with clang and clang++:

```
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
cmake -DCMAKE_INSTALL_PREFIX=/opt/darktable-master-test/ ..
make
```

Looks like this might be related to the gcc bug here? 

https://gcc.gnu.org/pipermail/gcc-bugs/2023-March/814763.html

**Comment by TurboGit** [comment] 2023-03-29 15:27
> 723 |       for(int i=N;i<N+4;i++) b[i] = 0;

This is GCC 13.x I bet? I had another report like this on a French forum. The code is ok, so GCC seems a bit more zealous here.

**Comment by leanderhutton** [comment] 2023-03-29 19:07
@TurboGit yes, GCC 13. I did some digging on the GCC GNU mailing lists and others have reported similar issues for other projects as a problem in GCC itself. For now I'm building on Fedora 38 with LLVM 15 and it's working fine. Should I keep this open for tracking GCC 13 problems?

**Comment by ptilopteri** [comment] 2023-04-09 17:04
same/similar problem on openSUSE Tumbleweed with gcc-13-1 building master

**Comment by atomikdg** [comment] 2023-04-19 12:36
I tried it on opensuse tumbleweed. It fails also with gcc-12 and gcc-11 on 4.2.x
I did an export CC=gcc-12 and export CXX=g++-12 (I tried also with version 11). 
With clang et clang++ it compiles without any problem. (clang-16)

My script for compiling:
rm -rf build/*
git fetch origin
git checkout darktable-4.2.x

git reset --hard origin/darktable-4.2.x
git submodule update
./build.sh --prefix /opt/darktable-42x --build-type Release --install --sudo

**Comment by ptilopteri** [comment] 2023-04-19 13:08
fwiw: gcc 12 worked fine for me on openSUSE Tumbleweed but 
upgrading to gcc 13 then failed with 4.3.0+1632~g7a3c976cff

clang works fine but with *many* warnings.

**Comment by atomikdg** [comment] 2023-04-20 19:06
To summarize my findings (on OpenSuse tumbleweed):

On branch 4.2.x: I can't compile with gcc-11 gcc-12 and gcc-13 (don't know why it worked well some weeks ago)
The error is: https://bin.infini.fr/?3b105223fba74de8#8NDjnC8CoFiKFAJYBWjsaAFfvL6Mn5Dcbp8VmJo7RfGs

Using this patch: https://github.com/darktable-org/darktable/commit/06b06f331a6e48c3c6fdb4b0f8952b1e2c92800a
It compiles with gcc-12 (I didn't try with gcc-11)
But it **doesn't** compile with gcc-13 with another error: https://bin.infini.fr/?c7f6dac902b6458a#F5D1SZbtfi8fUbpAt17wjDWEmwztjGbNSkQYkXJexCCi

Without any patching, it compiles well with clang16

Hope it can helps some devs ;-)

**Comment by TurboGit** [comment] 2023-04-20 19:59
> BTW: why not apply on the last stable branch (ex: 4.2.x) fix like [06b06f3](https://github.com/darktable-org/darktable/commit/06b06f331a6e48c3c6fdb4b0f8952b1e2c92800a) ? @TurboGit

Because we do not release any other bug fix release on the 4.2.x series.

**Comment by elstoc** [comment] 2023-04-20 20:19
> Because we do not release any other bug fix release on the 4.2.x series.

Releases aren't the only reason to do this. There is a cohort of users (myself included) who self-build the stable release. When an issue such as this occurs we're all left having to each independently investigate and solve the issue because the project doesn't publicise a list of the issues and fixes. Usually I can find an appropriate commit to cherry-pick but sometimes it takes quite a bit of effort and occasionally have to write something myself. Applying such fixes to the 4.2.x branch would help those users as well as maintainers who need to keep 4.2.1 functional in the various distributions.

I don't think it's unreasonable for us to consider at least providing information to users who want to keep releases working while waiting for the next release. Obviously we wouldn't include darktable functionality fixes in this list but issues caused by dependent libraries are pretty common -- I almost always have to patch the stable release at some point, because I use ArchLinux and dependent libraries are updated quite frequently.

**Comment by TurboGit** [comment] 2023-04-20 20:41
So please help, I don't have time to check 4.2.x... PR can be done easily especially if you already did the work to patch dt.

**Comment by elstoc** [comment] 2023-04-20 20:52
> So please help, I don't have time to check 4.2.x

https://github.com/darktable-org/darktable/pull/14277

**Comment by victoryforce** [comment] 2023-05-17 18:54
@leanderhutton if this is not an issue anymore, please consider closing it.

**Closed** 2023-05-19 14:38 UTC
Labels: bug: upstream
