### ISSUE TITLE
Canon R6 Mark ii

### ISSUE THREAD

**Issue by mduiop** [darktable-org/darktable#14252] opened 2023-04-19 01:55 UTC
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by MStraeten** [comment] 2023-04-19 05:18
please search for already closed issues related to canon R6 mII
raw files are already provided
cr3 support is based on libraw.
Grass doesn’t grow faster if you continue pulling….

**Comment by kmilos** [comment] 2023-04-19 05:43
Duplicate of #13684

Please search before opening new issues.

**Closed** 2023-04-19 18:03 UTC
Labels: duplicate, scope: camera support, depends: libraw
