### ISSUE TITLE
Click in module search has altered behavior in DT 4.1

### ISSUE THREAD

**Issue by Hpbirkeland** [darktable-org/darktable#12587] opened 2022-10-04 16:31 UTC
**Did you buy darktable from an application store ?** No

**Describe the bug/issue**
The search field is no longer activated by a simple left-click. I have to either click and drag a little bit or right-click. This has been the case since the start of the 4.1.0-series on Linux Mint. I also have 4.0.0 on Mac, this works as expected.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'darkroom'
2. Click on 'module search field'

**Expected behavior**
Up until 4.0.0, it was possible to left click in the search field. Not tested with 4.0.1.

**Platform**

* darktable version : e.g. 4.1.0-git438.80222570-1 and earlier in the 4.1 series
* OS                : Linux - kernel 5.4.0-126-generic 
* Linux - Distro    :  Linux Mint 20.3
* Memory            : 8 GB
* Graphics card     : Nvidia GTX 850M
* Graphics driver   : Nvidia driver 470
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : 
* Desktop           : Cinnamon
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by Nilvus** [comment] 2022-10-04 18:15
Could you precise which Gtk version you have installed? Which desktop environment and graphic server (X.org or Wayland) server you use?

I am on Debian Sid with latest Gtk 3 version and on Gnome 43 and can't reproduce your issue.

We have had such UI different behavior causing sometimes by some specific desktop environment or window manager... Or even, for a user on Windows same issue cause by an external software to manage keyboard. See: #12524

**Comment by Hpbirkeland** [comment] 2022-10-04 18:44
Hi, Nilvus,

DE is Cinnamon 5.2.7, graphic server is Xorg. 

Gtk seems to be both 2.24.32 and 3.24.20, according to the command 'dpkg -l libgtk2.0-0 libgtk-3-0', which I found via Google. Looking through Synaptic, there doesn't seem to be anything Gtk3-related actually installed, though. I don't know much about these things, it should be whatever is normal for an updated Linux Mint installation.

**Comment by Nilvus** [comment] 2022-10-04 19:37
2.24.32 is about Gtk2. darktable use Gtk3
Anyway, there's probably something related to your specific config as this works as expected on my side.
Could you test with another DE (Gnome for example) and check how it works on your side?

**Comment by dterrahe** [comment] 2022-10-04 19:39
> The search field is no longer activated by a simple left-click.

Thanks for reporting this.

I have reproduced that clicking in the search field doesn't activate the blinking cursor. If I start typing, text still _does_ appear in the search box (and then the blinking cursor appears as well), so it does get focus, just not visibly so. Does that correspond with your experience?

I'll look into how this can best be fixed.

**Comment by Hpbirkeland** [comment] 2022-10-04 19:45
@dterrahe yes, now that I try I see that you are right. So it's just the blinking cursor that is missing.

**Comment by dterrahe** [comment] 2022-10-04 21:53
If you are able to compile a PR, please test #12588 and report back there if it solves your problem. Thanks!

**Comment by Hpbirkeland** [comment] 2022-10-05 07:02
> If you are able to compile a PR, please test #12588 and report back there if it solves your problem. Thanks!

Not at the moment. For that I would have to find time to learn how to compile and all that. So in the weekend at the earliest. But thanks for your effort, I hope it works out!

**Comment by dterrahe** [comment] 2022-10-05 12:03
Maybe @TurboGit can reproduce the small issue and confirm the fix works for him so he might already have merged the low risk change before the weekend so you can test from the daylies...

**Comment by TurboGit** [comment] 2022-10-05 15:28
Yes I was able to reproduce and confirm the fix is working. Thanks @dterrahe for fixing this... Let me call you our Gtk+ expert :)

**Closed** 2022-10-05 15:28 UTC
Labels: bug: wip, understood: incomplete, reproduce: confirmed, scope: UI

**Comment by dterrahe** [comment] 2022-10-05 21:12
> our Gtk+ expert

A hard-earned accolade! You mean that I know more Gtk bugs than anybody, right?

@Hpbirkeland I hope you can still confirm after the weekend that the bug has been fixed in latest master (or otherwise please reopen this issue).
