### ISSUE TITLE
Rejecting multiple images resets filmroll selection to the very first image

### ISSUE THREAD

**Issue by edio** [darktable-org/darktable#7358] opened 2020-12-19 10:16 UTC
**Describe the bug**
With view filtering enabled, rating more than one image so, that they no longer pass the view filter, resets selection to the very first image in the film roll.

This is related to #5968 which is now closed. While filmroll works ok with no grouped images, rejecting grouped images or doing mulitple rejections in a row (select multiple with shift on the filmroll and then rate) resets the selection.

**To Reproduce**
While multiple rejections does reproduce the issue for me, I'm describing here a flow, that causes the most inconvenience and should be quite common in my opinion - grouped raw+jpg.

1. obtain a filmroll with multiple jpg and raw pairs
2. go to _Darkroom_ view
3. enable _Collapse grouped images_
4. set view filter to "All except rejected"
5. select an image in the middle of the roll
6. press "r" to reject the image
7. press space to advance to the next image

**Expected behavior**
Expected behavior: next image after all the rejected ones is selected. Only if no images exist in the roll, the first one should be selected
Actual behavior: selection always jumps to the beginning of the roll

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Archlinux
 - OpenCL activated
 - Driver: amdgpu

**Additional context**
 - Can you reproduce with another Darktable version? *yes*
 - Can you reproduce with a RAW or Jpeg or both? *both*
 - Are the steps above reproduce with a fresh edit (removing history)? *yes* (assuming default edits like applying color profile are considered "fresh")
 - Did you compile Darktable yourself? If so which compiler was used, with what options? *no*
 - Is the issue still present using an empty/new config-dir *yes*

**Comment by Nilvus** [comment] 2020-12-20 10:07
#5968 had been closed because it has been fixed in master, so probably in darktable 3.4 which will be released in just 4 days. I suggest you to close this issue, test that on darktable 3.4 when it will be out and if always there (I'm quite sure that had been fixed), you could reopen this issue by updating it and cite 3.4 instead of 3.2.1.

**Comment by edio** [comment] 2020-12-20 11:57
@Nilvus , thanks for the explanation. I mistakenly concluded, that the fix is already released.

I've just tried building darktable from source. Right now, I'm on 3.5.0+43~g5500e45da
![image](https://user-images.githubusercontent.com/787439/102712614-30d51f80-42cb-11eb-929c-bfd714cd84ad.png)

I still observe the behavior I've descirbed in this issue. Let me know, if you'd like a screen recording or something

**Comment by edio** [comment] 2020-12-20 12:26
Here's the screen recording (decided to give new fancy video upload feature a try)

https://user-images.githubusercontent.com/787439/102713225-346aa580-42cf-11eb-9cb1-b0b761f7f856.mp4

**Comment by Nilvus** [comment] 2020-12-20 15:39
@AlicVB: maybe for you?

**Comment by AlicVB** [comment] 2021-01-20 18:20
@edio : I can't reproduce, but there has been some fix in this aspect (grouping/ungrouping) recently, so I think it's now fixed in master. Can I ask you to try again ? Thanks a lot !

**Comment by edio** [comment] 2021-01-21 07:45
@AlicVB, I can confirm that the issue can no longer be reproduced with my reproducing scenario on the latest git version.

Thanks a lot for the fix!

**Comment by TurboGit** [comment] 2021-01-21 07:53
So closing.

**Closed by TurboGit** 2021-01-21 07:53 UTC
Labels: no-issue-activity

**Comment by edio** [comment] 2021-01-21 20:25
@AlicVB , @TurboGit 
I'm sorry but I've stumbled on this issue again.

So I have built the latest DT, tried to reject images, and it all worked great in the morning

I processed few pictures, suspended my computer

Then several hours later tried to work in the same DT process again: and suddenly rejecting >1 pictures in a row resets the film roll to the very first image.

This behavior I can now stably reproduce. I tried
* a new filmroll
* restarting darktable process
* with enabled/disabled opecl
* a fresh darktable instance with empty `.config/dartable` and `.cache/darktable`

I can only conclude that the issue has to be reopened.

Please let me know, what debug information can I provide to help with this issue.

Thanks
