### ISSUE TITLE
Matrices/vectors computations may be wrong with GCC 10

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#5737] opened 2020-07-12 15:55 UTC
There is an upstream bug with GCC 10 that leads to inconsistent matrice/vector operations: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96133
So far, no issue has been detected in darktable, but @heckflosse found issues in Rawtherapee in code that performs very basic algebraic operations used in darktable too (XYZ to RGB conversions).

I'm dropping this here for future reference, just in case. Nothing to do for now.

Thanks to @heckflosse for sending me the info.

**Comment by rabauke** [comment] 2020-07-13 20:05
Good to know. The GCC issue tracker mentions version 10.1.0 as affected version. I can reproduce this issue with version 10.0.1 on Ubuntu 20.04, too.

**Comment by heckflosse** [comment] 2020-08-13 07:37
The issue is fixed in gcc 10.2.0

**Comment by johnny-bit** [comment] 2021-05-18 18:14
I think this can be closed now. The distros that package gcc 10 package either fixed gcc 10.2 or 10.3 so we're good here (I think)

**Closed by johnny-bit** 2021-05-18 18:14 UTC
Labels: no-issue-activity
