### ISSUE TITLE
DT 4.4.2 Mac ARM DMG is damaged

### ISSUE THREAD

**Issue by jcampbell05** [darktable-org/darktable#14956] opened 2023-07-26 09:13 UTC
### Describe the bug

When downloading the ARM64 image of Darktable from the website Mac OS complains the application is damaged

### Steps to reproduce

1. Download the ARM64 build
2. Open the the darktable app
3. Mac will complain the DMG is damaged

### Expected behavior

It should be able to open

### Where did you install darktable from?

darktable.org

### darktable version

4.2.2

### What OS are you using?

Mac

### What is the version of your OS?

13.3

### Describe your system?

M1 Pro

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment] 2023-07-26 09:21
@jcampbell05 Damaged? Like [this](https://www.darktable.org/install/#macos)?

**Comment by jcampbell05** [comment] 2023-07-26 09:46
> @jcampbell05 Damaged? Like [this](https://www.darktable.org/install/#macos)?

No like this

<img width="372" alt="Screenshot 2023-07-26 at 10 45 49" src="https://github.com/darktable-org/darktable/assets/1484989/11f7e7a7-d15f-4d09-86b8-853b0b7a88d6">

**Comment by kmilos** [comment] 2023-07-26 10:10
Duplicate of #14746

Please search before opening new issues.

**Comment by victoryforce** [comment] 2023-07-26 10:17
> > @jcampbell05 Damaged? Like [this](https://www.darktable.org/install/#macos)?
> 
> No like this.

I don't quite understand why "no". On the page I linked, one of the two possible system warnings mentioned is what you describe. The page has advice on what to do in this case. Did these actions not help you?

> This always appears no matter how many times I redownload, the intel version opens fine but obviously is slower due to rosetta translation layer.
> 
> <img alt="Screenshot 2023-07-26 at 10 45 49" width="372" src="https://user-images.githubusercontent.com/1484989/256190410-11f7e7a7-d15f-4d09-86b8-853b0b7a88d6.png">

**Comment by ralfbrown** [comment] 2023-07-26 11:35
Can someone submit a bug report to Apple that there's an incorrect error message? :-)
It **should** be reporting an unsigned image and asking whether to run it anyway.

**Closed by ralfbrown** 2023-07-26 11:35 UTC
Labels: duplicate, bug: upstream, scope: macos support

**Comment by jcampbell05** [comment] 2023-07-27 08:41
> I don't quite understand why "no". On the page I linked, one of the two possible system warnings mentioned is what you describe. The page has advice on what to do in this case. Did these actions not help you?

No they did not. WIth the intel image I can easily right click and open it to bypass the quantine.  There is clearly something wrong with the ARM image.

**Comment by victoryforce** [comment] 2023-07-27 10:40
> > I don't quite understand why "no". On the page I linked, one of the two possible system warnings mentioned is what you describe. The page has advice on what to do in this case. Did these actions not help you?
> 
> No they did not.

I would like to clarify: are you saying that the actions suggested on the darktable dmg file download page (see screenshot below) do not fix the problem?

<img width="523" alt="chrome_tDRgRZey6z" src="https://github.com/darktable-org/darktable/assets/6246352/99b83798-b3bb-49bc-bf4a-7dc06a33b13f">


_If this does not solve the problem_, then it is really worth raising a separate issue and research, because it would mean that there is an error in the recipe for solving the problem.

I want to emphasize that the very existence of a macOS complaint about the alleged "damage" of darktable dmg is not a darktable bug, it is simply a consequence of the fact that the dmg __is not digitally signed because it requires an expensive Apple developer account__. Consequently, this macOS warning will not be eliminated and all raised issues that expect such a result will just be closed.

> WIth the intel image I can easily right click and open it to bypass the quantine. There is clearly something wrong with the ARM image.

You should ask Apple about this. Both images are just not signed, that's all.
