### ISSUE TITLE
"keep original filename" check box invisible if not selected

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#12099] opened 2022-06-30 20:07 UTC
Import, module `copy& import...` dialog: the checkbox for `keep original filename` isn't visible, possibly because it has the same color as the check box of `keep this window open`, but the latter has a darker background.

I think that the color of the text boxes (like `sub directory naming pattern`) should be used

**Comment by paolobenve** [comment] 2022-06-30 20:22
same thing in import module,  `parameters` section, `ignore EXIF rating` and `apply metadata` check boxes

**Comment by pehar1** [comment] 2022-07-01 05:48
Which dt version and which theme?
On 4.1.0+20~gbaa74228f and darktable-elegant-grey it is visible :
![parameters](https://user-images.githubusercontent.com/104291381/176831771-e32d6037-5320-49e0-ad04-a48254da603a.png)

**Comment by paolobenve** [comment] 2022-07-01 06:12
> Which dt version

yesterday's master

> which theme

darktable

> On 4.1.0+20~gbaa74228f and darktable-elegant-grey it is visible

yes, it's visible when checked, invisible when unchecked:

![Schermata del 2022-07-01 08-12-14](https://user-images.githubusercontent.com/1417508/176834902-c152b21c-dc16-4a54-9ba0-a70d03469c46.png)

**Comment by pehar1** [comment] 2022-07-01 06:24
I see it, even unchecked, on both screenshots. The contrast is low, but it is visible on my screen.

**Comment by Nilvus** [comment] 2022-07-01 11:22
Duplicate of #5040. I suggest you to read that. Not so easy to do and will probably never been fixed instead you should/want do that.

**Comment by Nilvus** [comment] 2022-07-01 11:25
Oups, forget my last comment. I read your issue too quickly...

**Comment by Nilvus** [comment] 2022-07-01 11:42
@paolobenve: see last commit in my #12081 PR which fixes your issue (set same background-color as text fields in those collapsible sections.

**Closed** 2022-07-11 08:40 UTC
Labels: feature: enhancement, scope: UI
