### ISSUE TITLE
JPEG Export EXIF Data missing

### ISSUE THREAD

**Issue by rfreytag1** [darktable-org/darktable#12394] opened 2022-08-28 10:52 UTC
**Introduction**

The exported JPEGs no longer have the EXIF data regarding the camera settings. The original DNG raw files include all the data.

**To Reproduce**
1. Select an image
2. Select JPEG file format in the Export Module
3. Export the image
4. Open the exported file with any other software which reads the EXIF data and notice no data

**Expected behavior**

Camera, lens, exposure and copyright information should be present in the EXIF data block.

**Platform**

* darktable version : 4.0.0
* OS                : Windows 10 Pro 19044.1889

**Comment by gi-man** [comment] 2022-08-28 11:16
Are your export metadata processing parameters on? 

Here is the section of the manual that should read.
https://github.com/darktable-org/darktable/pull/11797

**Comment by Nilvus** [comment] 2022-08-28 11:20
And good to search before posting issues. Duplicate of #12352. EXIF data are not enabled by default, for privacy security reasons.

**Closed by Nilvus** 2022-08-28 11:20 UTC

**Comment by rfreytag1** [comment] 2022-08-28 11:31
Oof... why is this option so hidden? Should be right there with the rest of the settings in that module. I never even considered the preset menu because I don't consider regular settings as presets.

@Nilvus haven't considered closed issues, sorry.

**Comment by ptilopteri** [comment] 2022-08-28 11:34
maybe should be in the main config settings

**Comment by gi-man** [comment] 2022-08-28 11:38
> maybe should be in the main config settings

Discussed here, but i don't think there was an agreement on resolution. https://github.com/darktable-org/darktable/pull/11498
