### ISSUE TITLE
Graduated mask causes chequered effect in Lighttable

### ISSUE THREAD

**Issue by mberg2007** [darktable-org/darktable#4192] opened 2020-01-27 14:48 UTC
**Describe the bug**
Working with a landscape image and applying the exposure module with a graduated mask to reduce the brightness of the sky causes a chequered pattern to leak through the lightest part of the graduated mask when viewed in the Lighttable.

**To Reproduce**
Please find attached the image and sidecar file shown in the screenshot below. It should demonstrate the problem perfectly.

[issue-4192-sample.zip](https://github.com/darktable-org/darktable/files/4121261/issue-4192-sample.zip)

**Expected behavior**
Chequered pattern should not be visible.

**Screenshots**
![dt_lighttable_checkered_skies](https://user-images.githubusercontent.com/1942974/73183932-e92a3000-411b-11ea-908c-a64b6d1ce435.png)

**Platform (please complete the following information):**
Darktable built from current master 69b79685e2f7b668bb95d860bd89407154066565
Ubuntu 19.10/XFCE-4
OpenCL not activated

Darktable Built from source in a docker container, based on dependencies and toolchain as described in .ci/Dockerfile on the current master branch.

**Comment by jenshannoschwalm** [comment] 2020-02-06 13:45
Can't see what mask parameters you are using ...

**Comment by mberg2007** [comment] 2020-02-06 14:05
> Can't see what mask parameters you are using ...

What mask parameters? The sidecar file should tell you everything you need?

**Comment by jenshannoschwalm** [comment] 2020-02-06 18:33
It does, just takes time to download and include in the lib....

Anyway, can't reproduce here on master f5c6070, Fedora 31, nvidia. Neither with/without cl activated. Tried several window sizes.

Is the problem also evident in exported images?

**Comment by mberg2007** [comment] 2020-02-06 22:25
The problem is not in the exported images. It looks to be perhaps some sort of scaling/moire issue when showing images in the lighttable view. It could also be caused by the specific set of modules and related masking. I'm not sure but it doesn't look good.

I'll give it another shot with the current master.

**Comment by johnny-bit** [comment] 2020-12-20 13:39
OK, I tried to replicate it with current master and indeed it's replicable. Here's how you can replicate it:

import the sample attached to the issue
open lighttable view in file manager mode
adjust zoom level.
for me the issue is visible @ zoom levels 3, 4 & 5. Issue disappears at zoom level < 3 or > 5. Exported image and imported back do not produce such artefacts in any zoom levels.

Here's how it looks - on the left is the RAW and on the right is exported image from raw.

![ISSUE_4192_zl3](https://user-images.githubusercontent.com/10687765/102714666-94ae1700-42d0-11eb-999e-81b00473b2cb.png)
![ISSUE_4192_zl4](https://user-images.githubusercontent.com/10687765/102714669-97107100-42d0-11eb-9b06-55f6a9e7e46a.png)
![ISSUE_4192_zl5](https://user-images.githubusercontent.com/10687765/102714670-98419e00-42d0-11eb-8708-9eab13802236.png)
![ISSUE_4192_zl6](https://user-images.githubusercontent.com/10687765/102714672-98da3480-42d0-11eb-90a4-59a301529f1e.png)

Pinging @AlicVB or @jenshannoschwalm since this issue is interesting for thumbnails...

**Comment by jenshannoschwalm** [comment] 2020-12-24 16:36
Hi @johnny-bit i just heard your ping :-) Looked into it and can confirm the issue.

It can also be reproduced on bayer images and the pattern is somewhat related to the sensor pattern. I have a look at at - likely pretty complicated stuff - and will later report.

**Comment by jenshannoschwalm** [comment] 2020-12-29 09:38
This issue is related to `demosaic_qual_flags` and aliasing effects if we don't use the full image but instead use  "merged cfa data" for faster processing. See ~L.2842 in demosaic.c. Unfortunately i don't see a solution without heavy impact on performance atm.

**Comment by johnny-bit** [comment] 2020-12-29 10:03
OK, so the issue won't show up on jpeg thumbnails of unprocessed raws nor for any non mosaiced images and "solution" would impact performance quite a bit...

I wonder if it's more for documenting the behaviour or for uber-performance setting...

**Comment by jenshannoschwalm** [comment] 2020-12-29 21:32
Maybe you misunderstood slightly, it **is** visible on thumbs, because there is wrongly interpolated input data. We can force to render hq thumbs but that would have an impact.

**Comment by jenshannoschwalm** [comment] 2021-01-04 09:22
Maybe this is related to #3022 ?

**Comment by jenshannoschwalm** [comment] 2021-03-07 16:09
Today i took another look at this as i suspected some pixel interpolator issue.

The title of this issue is somewhat misleading, if you take the original xmp, disable velvia and exposure using the mask and the issue is still there. It's also independent of the pixel interpolator selected via preferences.

The issue comes down to
1. the crop module activated **and**
2. the setting of "high quality thumbs processing from ..."
![Bildschirmfoto von 2021-03-07 16-54-34](https://user-images.githubusercontent.com/50982232/110245956-db252080-7f65-11eb-8c18-a506426b619d.png)

Currently i think, we use a fuji sensor here and as we downscale the raw sensor data we get that sort of pattern (for bayer the approximation is much simpler (and only 2x2 photosites) so this issue has not been reported for such sensors.

Also i am sure, this is **not** a cairo scaling problem at all.

Conclusion:
1. There is no processing error, it's only a side effect of the way we calculate the thumbs for low resolution.
2. Maybe we should extend the tooltip or explain in the manual ...

ping @johnny-bit

**Comment by johnny-bit** [comment] 2021-03-07 17:13
So... What's your recommendation here then? "There is no error but sideeffect" so: "won't fix" + "tooltip and usermanual changes needed"?

**Comment by jenshannoschwalm** [comment] 2021-03-07 17:54
Yeah, won't fix and tooltip/manual changes needed :-) will you or shall do the pr?

**Comment by johnny-bit** [comment] 2021-03-07 18:05
I'd rather you do the suggested changes as I have trouble understanding anything this weekend ;)

**Comment by jenshannoschwalm** [comment] 2021-03-07 18:27
>  as I have trouble understanding anything this weekend 

Too bad but sometimes happens :-)

**Closed** 2021-03-22 07:04 UTC
Labels: bug: won't fix, reproduce: confirmed, scope: UI
