### ISSUE TITLE
Intents in darkroom

### ISSUE THREAD

**Issue by pahervin** [darktable-org/darktable#10329] opened 2021-11-04 11:47 UTC
**Describe the bug/issue**
Upgraded DT display intents ('rendu' in french) in the darkroom, a new install does not.
(see joined screen copies)

The joined darktablerc file comes from DT upgrades of every version since 2.6.

**To Reproduce**
1. Set the joined darktablerc file in the DT environnement directory
2. Start DT
3. Open the darkroom with any photo
4. Open the output profile module and check with the joined screenshot (intent is displayed)
5. Open the second display options and check with the joined screenshot (intents are displayed)
6. Stop DT and remove the darktablerc file
7. Start DT, the default settings are applied
8. Check again : intents are not displayed

**Expected behavior**
Have the same options set displayed irrespective of darktablerc file origin

**Screenshots**
![Profil-sortie-rendu](https://user-images.githubusercontent.com/6032499/140306777-cbb09446-b938-494e-8fa5-9cf1d323dab8.jpg)
![Profil-ecran-rendu](https://user-images.githubusercontent.com/6032499/140307000-efb1c14b-0a0a-40a1-9283-e9ffef764543.jpg)

**Files**
[darktablerc](https://github.com/darktable-org/darktable/files/7474521/darktablerc.txt)

**Platform**
* darktable version : 3.6.1
* OS                : Win10 (21H1)
* Memory            : 8GB
* Graphics card     : Intel UHD Graphics 620 and Radeon 520
* OpenCL installed  :  no

**Additional context**
 - Can you reproduce with another darktable version(s)? no
 - Do you use lua scripts? no

**Comment by Nilvus** [comment] 2021-11-06 09:31
And what behavior do you have with a new darktablerc file? This could be because of your darktablerc file or maybe some writing permissions. Would be good to test if the update works great with a whole fresh new darktablerc. If so, this is an issue with your darktablerc file, not darktable directly. Thus, I can't reproduce on my side with my darktablerc file. Update is good.

**Comment by pahervin** [comment] 2021-11-06 14:30
My darktablerc file comes only from darktable updates and darktable settings. No direct edit of the file (with a text editor)
Some darktable updates were unstable, and some updates failed since the 2.6 version. So my darktablerc file was mis-updated sometimes by DT. 
As a software enginer, I understand that may happen during software life. Including DT.
DT must manage darktablerc file content, while it was not hand edited. Including update issues.

Unlike the db file, darktablerc is not saved before update. An ordinary user cant replay update, after un update failure.
DT should remove out of date options from the darktablerc file, and should not display them any more.
DT should save the darktablerc file before an update, as the db files.

My DT start properly with a fresh darktablerc file (but all my settings are lost). I dont now how to merge it with the former one, to retrieve my settings. I dont know which settings are available, and the out of date ones.
Are they implicit options, or all the options are in the darktablerc file with a default value (if not set) ?

I dont know if the intent options should to be displayed or not, or where they are moved (if they are).

I point out the intent options, because I noticed them. Are they other options in the same case ?

**Comment by Nilvus** [comment] 2021-11-06 17:56
@pahervin: tested again and now I understand your issue. I had just understand your issue quite the opposite. I can reproduce. @TurboGit: on what I found, last people that had worked on that part was you. What's your view on that?

To understand issue, no need to all infos provided here. Just start dt with a whole fresh new config and see no intents in any parts they usually are in darktable.

**Comment by Nilvus** [comment] 2021-11-06 17:59
They so appear with an old darktablerc files that include intents lines.

**Comment by TurboGit** [comment] 2021-11-06 19:03
@Nilvus : Thanks for looking at this. I'll see what is wrong.

**Comment by TurboGit** [comment] 2021-11-06 19:07
But when I start dt on a new config dir I do have the intent?

**Comment by TurboGit** [comment] 2021-11-06 19:09
Maybe the build is not done with LittelCMS? The intents are only displayed (supported) when LittleCMS is used.

**Comment by Nilvus** [comment] 2021-11-06 19:37
> Maybe the build is not done with LittelCMS? The intents are only displayed (supported) when LittleCMS is used.

On my side, build is done with LittleCMS. I just check again and LCMS2 is found. I install on my side all dependencies, even optional. The only package darktable build config do not found is libheif (and I don't use heif format).

Anyway, if LittleCMS was not used, intents should so not be displayed (a warning should be good to add) even if lines in darktablerc are present. On my side, as @pahervin, I see intents with my darktablerc file and I don't see them with a whole new one.

**Comment by Nilvus** [comment] 2021-11-06 19:42
@TurboGit and @pahervin: I found why and it's normal: with a whole new fresh config, so new darktablerc file, "always use LittleCMS 2 to apply output color profile" setting in processing tab in main preferences, is not checked by default. @pahervin: so just check it and intents are back. @TurboGit: is this should be by default checked instead of not checked?

**Comment by pahervin** [comment] 2021-11-12 16:59
@TurboGit and @Nilvus : Thanks for your answers.
I did not understood a single setting option several widgets on the display. I was looking for individual settings.
So I can keep my old darktablerc file without merging it with a fresh one.

**Comment by aurelienpierre** [comment] 2021-11-15 10:34
>  is this should be by default checked instead of not checked?

No. LittleCMS2 is slow and anyway, intents are not really used (the perceptual intent relies on a LUT in the ICC profile that we don't define, so it basically defaults to relative colorimetric).

**Comment by TurboGit** [comment] 2021-11-26 16:34
Nothing more to do.

**Closed by TurboGit** 2021-11-26 16:34 UTC
Labels: bug: invalid, priority: high, understood: clear, reproduce: confirmed, scope: color management
