### ISSUE TITLE
Can not open .NEF files from my camera

### ISSUE THREAD

**Issue by RononDex** [darktable-org/darktable#8119] opened 2021-02-06 17:06 UTC
**Describe the bug**
If I try to open a raw format (.NEF) from my camera (Nikon Z6 II) I get the following error displayed on screen:
![image](https://user-images.githubusercontent.com/2249071/107124684-a90c9a00-68a5-11eb-8275-478baaed2899.png)

Even though the thumbnail is displayed in lighttable

**To Reproduce**
1. Import some .NEF file from a Z6 II
2. Double click the image in the lighttable to open darkroom
3. See error

**Expected behavior**
The photo can be opened in "darkroom" for editing

**Screenshots**
![image](https://user-images.githubusercontent.com/2249071/107124716-db1dfc00-68a5-11eb-984e-5d9588035009.png)
![image](https://user-images.githubusercontent.com/2249071/107124721-e40ecd80-68a5-11eb-9e5d-c40fcb1a212c.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Arch Linux
 - 
 - NVIDIA GTX1080Ti with up to date drivers

**Additional context**

**Comment by johnny-bit** [comment] 2021-02-06 19:03
Duplicate of #6898

@TurboGit - had changes in rawspeed submodule (commit  dcd4827) made it into 3.4.1?

**Closed by johnny-bit** 2021-02-06 19:03 UTC

**Comment by RononDex** [comment] 2021-02-06 19:56
Just tried it with version 3.4.1 and the error still appears

**Comment by johnny-bit** [comment] 2021-02-06 20:01
@TurboGit - This might be a candidate for 3.4.2 then...

**Comment by TurboGit** [comment] 2021-02-06 21:09
Sure, but again rawspeed is usually updated by @LebedevRI.

**Comment by johnny-bit** [comment] 2021-02-06 21:15
Yes, however rawspeed submodule updates are done just on master AFAIK, but rawspeed is incredibly stable lib, so maybe it'd be worth porting it to release branches?

**Comment by TurboGit** [comment] 2021-02-06 21:20
Sorry I missed the fact that Z6-II was supported on master so I could have updated the branch indeed. Let's remember that for 3.4.2 if it is released otherwise it will be for 3.6.

**Comment by RononDex** [comment] 2021-02-06 23:41
Any update on when those versions will be released?

**Comment by johnny-bit** [comment] 2021-02-07 07:03
Version 3.6 is planned for summer. 3.4.2 depends on number of variables.

niedz., 7 lut 2021, 00:41 użytkownik RononDex <notifications@github.com>
napisał:

**Comment by RononDex** [comment] 2021-02-07 11:58
Just tried it with the up to date master branch and it works, however the brightness levels are wierd.
For explanation, this is the preview in lighttable:
![image](https://user-images.githubusercontent.com/2249071/107145733-d0b23f80-6943-11eb-9b75-cba73e7574e4.png)

And when I open it in the darkroom:
![2021-02-07_12-57](https://user-images.githubusercontent.com/2249071/107145777-27b81480-6944-11eb-92af-6b61bf483a52.png)

**Comment by RononDex** [comment] 2021-02-10 09:24
Is that considered normal? Or should I open a new issue for this?

**Comment by LebedevRI** [comment] 2021-02-12 12:11
> Sorry I missed the fact that Z6-II was supported on master so I could have updated the branch indeed. Let's remember that for 3.4.2 if it is released otherwise it will be for 3.6.

@johnny-bit is correct.
As i have already previously stated several times, I only touch dt master,
and whatever stable branch elsewhere can immediately cherry-pick from there.
