### ISSUE TITLE
sql errors on import

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#4162] opened 2020-01-21 23:11 UTC
openSUSE Tumbleweed 20200118
NVIDIA GF106 [GeForce GTS 450], 390.129
darktable 3.1.0~420.304f71e37
OpenCL on 
i7 12-core 36GB

when importing, I see a lot of sqlite3 errors:
   sqlite3 error: /home/abuild/rpmbuild/BUILD/darktable-3.1.0~git420.304f71e37/src/common/collection.c:1813, function dt_collection_shift_image_positions(), query "BEGIN": cannot start a transaction within a transaction

**Comment by jenshannoschwalm** [comment] 2020-02-03 18:34
@ptilopteri isn't this a duplicate of a solved issue?

**Comment by TurboGit** [comment] 2020-02-03 18:52
Yes, I have fixed that yesterday.

**Closed by TurboGit** 2020-02-03 18:52 UTC
