### ISSUE TITLE
liquify tool image moved  when moving liquify nodes when zoomed in

### ISSUE THREAD

**Issue by eyedear** [darktable-org/darktable#8109] opened 2021-02-06 08:39 UTC
the liquify tool seem to have small bug

**Describe the bug**
go to liquify and click draw points and click a node. when zoom to fit moving the node is works as per describe. but when you zoom in and try to move the node the images seem to move a little bit in the direction of your mouse movement. i have attach video to show what I mean

**Expected behavior**
the image should not move when you try to move the node

**Screenshots**
[https://youtu.be/7s0WQ8t_69g](url)

**Platform (please complete the following information):**
 - Darktable Version: 3.5.0+948~g8b296ed1b
 - OS: Windows 10 Home. bug reproducible on ubuntu 20.10 
 - OpenCL activated or NOT the issue still persists
 - nvidia gtx 1060 max-Q driver 461.40

**Additional context**

 - i have see this happen in the nightly build of darktable on ubuntu 20.10
 - so far i test it on RAW only
 - after history is clear the issue still persists
 - the windows version i compile it myself following the steps outline on github
 - i have recompile into a new directory
 - i have seen this since the master was at 3.5.0

I hope the info helps. if you would like me to test anything else do let me know

can I also request the center node point area for mouse click be enlarge a little bit. it's difficult to select and move it as it is 

thanks again. hope this information will help the developers

**Comment by TurboGit** [comment] 2021-02-06 18:28
Yes, I have seen that. I'll try to fix.

**Comment by TurboGit** [comment] 2021-02-06 18:41
Can you check with PR #8121 applied. It should fix the issue. TIA.

**Comment by ralfbrown** [comment] 2021-02-06 18:49
Confirmed.  It looks like the very first mouse-move event after clicking on the node is still being processed by the default handler and dragging the viewport.  Second and subsequent mouse-move events then move the node as desired instead of the viewport.

**Comment by eyedear** [comment] 2021-02-07 01:14
may i know how do i apply the pull request to my local git to test out the updates. whats the git command to do that. sorry for the noob question

**Comment by TurboGit** [comment] 2021-02-07 15:12
This is now merged on master, so just test current master. TIA.

**Closed** 2021-02-07 15:11 UTC
Labels: bugfix

**Comment by eyedear** [comment] 2021-02-07 23:49
Yeah just saw will test the new master
