### ISSUE TITLE
[performance] moving the mouse in the lighttable panel takes up to 50% CPU usage

### ISSUE THREAD

**Issue by JeanRemiDelteil** [darktable-org/darktable#2770] opened 2019-07-03 15:38 UTC
**Describe the bug**
Just moving the mouse cursor on the lighttable panel takes up to 50% CPU usage on a 8 core CPU, in the windows x64 version.
All actions are noticeably slow (favorite, selections...)

Tested on v2.6.2 and v2.6.0.

**To Reproduce**
1. Launch darktable on windows10
2. Open the CPU monitoring tool
3. Move mouse around in the lighttable panel
4. Listen to your fan speeding up a lot

**Expected behavior**
Moving the mouse should not be ressource consuming.
This behaviour is not observed in the other panels, it's specific to the lighttable panel

**Platform (please complete the following information):**
 - OS: Windows 10, v1903 x64
 - Version 2.6.0, 2.6.2

**Additional context**
Computer specs:
Processor Intel Core i7-8550U (base speed: 1.80GHz, turbo: 4.00GHz)
RAM: 16Go
HD: SSD

**Comment by aurelienpierre** [comment] 2019-07-03 15:55
This has been improved a bit in current master branch, however, the GTK library used for the UI is not optimized for performance, especially on 4K screens, is single-threaded, and generally sucks.

**Comment by fabienengels** [comment] 2019-07-07 09:56
Same thing under Archlinux and Darktable 2.6.2, lighttable is really slow, with a lag of few seconds before highlighing the hovered photo.

**Platform** :
Archlinux
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
NVIDIA Corporation GP104 [GeForce GTX 1080]
SSD

**Comment by AlicVB** [comment] 2019-07-07 11:08
The problem is that on each mouse move, **all** the thumbnails on screen are queried in the database and drawn. This is especially slow when you have big database and/or collect images with complex filters.

@TurboGit has done lot of work to avoid that and now only the needed thumbnails are redrawn. This is only available in master but will be part of the next major release.
There's still room for improvement as @aurelienpierre has said, thought !

**Closed by AlicVB** 2019-07-07 11:08 UTC
