### ISSUE TITLE
Updating a lot of XML sidecars freezes Darktable

### ISSUE THREAD

**Issue by elman22** [darktable-org/darktable#5722] opened 2020-07-08 16:48 UTC
**Describe the bug**
I use 2 computers to edit my photos. I use syncthing to synchronize photo folders. Each Darktable installation updates a lot of xmp files (even thou I don't edit all those files, but that is different issue I guess). So when I sync xmp to the other Darktable installation and start it, I'm prompted about updated xml (sometimes about 10000 of them). Then I select all xmp and click "update database from selected xmp files". Darktable then freezes. Not sure if after everything is processed or before, but some xmp files on disk have current timestamp. Also not sure why, since I want to update database, not xmp files. Maybe some racing condition. Or maybe it is actually something doing for so long, and progress indicator would be nice. When I kill Darktable and start it again, I'm again prompted with updated xmp files. When I repeat all steps, database is updated and I'm able to close the window.

**To Reproduce**
1. Import about 10000 images to first Darktable installation
2. Move all files including xmp to second Darktable installation (same version of Darktable)
3. Edit some files in second installation, maybe set time offset to all of them
4. Move all files to first installation and overwrite files
5. Start first Darktable
6. Select all xmp files and click update database from selected xmp files"

**Expected behavior**
Window content should be updated (with empty contents) and I should be able to close it.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Manjaro Linux
 - OpenCL activated
 - nVidia proprietary 440.xx

**Comment by Mark-64** [comment] 2020-07-10 06:00
Indeed, as wrote in #5697, in current git master this use case seems broken as DT sees all .xmp as modified.
This didn't happen in DT 3.0.2

**Comment by TurboGit** [comment] 2020-07-10 12:08
Should be good to be fixed in 3.2 indeed. Now the reproducer is not ok to me. Please can you find a simple way to reproduce without the 10000 pictures. You can't expect any dev to handle such reproducer. Can you reproduce with one or two XMP ? If so can you describe the steps to reproduce ? Thanks.

**Comment by elman22** [comment] 2020-07-10 20:29
OK, I will try to find simpler way to reproduce.

**Comment by TurboGit** [comment] 2020-07-10 20:41
Very much appreciated, thanks!

**Comment by ralfbrown** [comment] 2020-07-11 05:28
I suspect the problem is that all of the work is being done in a button callback, specifically _reload_button_clicked in src/control/crawler.c, which calls dt_history_load_and_apply for each and every selected XMP before returning control to GTK.  Similarly, _overwrite_button_clicked just below it calls dt_image_write_sidecar_file for every selected XMP before returning control to GTK.
Moving the actual work off of the GUI thread should eliminate the apparent hang, but would presumably require additional synchronization.

**Comment by Mark-64** [comment] 2020-07-11 05:43
I believe the root cause is that DT 3.1 sees all .xmp as changed if you switch between two computers, while DT 3.0.2 shows only the edited ones. 
Perhaps the 3.1 is an unwanted behaviour and, as a consequence, DT seems to hang.

**Comment by thisnamewasnottaken** [comment] 2020-07-17 08:42
> 
> 
> Very much appreciated, thanks!

@TurboGit , I also have this issue but due to working with Digikam as DAM and Darktable for workflow.
Steps to reliably reproduce with minimal files **on one computer:**

**Option 1: New collection DK>DT>DK>DT**
1. Ensure that neither DK or DT are open.
1. Open DK, import images and change something like a tag and write metadata (ensure settings have write meta to XMP enabled)
1. Close DK (reboot if you wish)
1. Open DT & import to collection, make some changes.
1. Close DT (reboot if you wish)
1. Open DK and add a rating or some flag or some other meta and write metadata (ensure settings have write meta to XMP enabled)
1. Close DK (reboot if you wish)
1. Open DT, "Updated XMP sidecar files found" shows up. 
1. Select one multiple, or all (similar result regardless).
1. Click on "update database from selected xmp files"
1. App now hangs.

**Option 2: Existing collection**
Follow above from step 6.

**Additional notes:**
- DK is set up to write xmp's like DT, i.e. <filename>.<ext>.xmp
- DK and DT should never be open at the same time as this will guarantee issues with the XMPs.
- DK is not set to write meta to files (i.e. file and xmp concurrent changes issues). 
- The XMPs are not corrupt, I checked.
- There are no other race conditions. These files are local only and are not affected by any sync / tracking issues from other apps.

Is there a workaround in the meantime?
![DT Annotation 2020-07-17](https://user-images.githubusercontent.com/8645373/87766781-98191000-c811-11ea-97d4-b0882bbe7ece.jpg)

**Comment by TurboGit** [comment] 2020-07-17 09:13
@thisnamewasnottaken : I don't use DK and won't install it.

Please can you send the diff of the XMP as written by DK when adding a tag (step 2 above) or changing start (step 6). Thanks.

**Comment by thisnamewasnottaken** [comment] 2020-07-18 22:53
[STEP_7_IMG-20190302-WA0001 - Copy.jpg.xmp.txt](https://github.com/darktable-org/darktable/files/4942842/STEP_7_IMG-20190302-WA0001.-.Copy.jpg.xmp.txt)
[STEP_5_IMG-20190302-WA0001 - Copy.jpg.xmp.txt](https://github.com/darktable-org/darktable/files/4942841/STEP_5_IMG-20190302-WA0001.-.Copy.jpg.xmp.txt)
[STEP_2_IMG-20190302-WA0001 - Copy.jpg.xmp.txt](https://github.com/darktable-org/darktable/files/4942839/STEP_2_IMG-20190302-WA0001.-.Copy.jpg.xmp.txt)

**Comment by Jognu** [comment] 2020-07-18 23:15
I reproduce this problem (the "updated xmp sidecar files found" pop-up which freeze when the button "update database" is used) on Windows 10 with the 3.0.2 and with just one file.
On the same computer, I used 2 darktable with 2 differents configdir.
Import the folder with the file on darktable-1. Do a modification. Close darktable-1.
On darktable-2, import the folder, do a modification. Close darktable-2.
Open darktable-1, the pop-up appear, check the file and click "update database" --> it works. Do a modification, close darktable-1.
Open darktable-2, the pop-up appear, check the file and click update --> freeze.
I can wait, I can try again, it won't work anymore.
Only the "overwrite" button works.

**Comment by phweyland** [comment] 2020-08-01 21:28
>  I believe the root cause is that DT 3.1 sees all .xmp as changed if you switch between two computers, while DT 3.0.2 shows only the edited ones.

May be linked to #5847 ?

**Comment by phweyland** [comment] 2020-08-04 21:41
The PR #5869 may not solve completely this issue but at least could make it less critical.
As the main issue seems to be on windows, could someone build it there and tell if the changes help ?

**Closed** 2020-10-10 20:42 UTC
Labels: bug: pending, no-issue-activity, priority: medium
