### ISSUE TITLE
Odd behaviour using masks with a jpeg

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#9608] opened 2021-07-23 19:32 UTC
3.7.0+324~g17d82bb19  Ubuntu

When masking, should you be allowed to use scene referred parametric masking, and is there a bug here?....

You drag and drop a JPEG that's never been opened in dt before into lighttable.  You now create a second Exposure instance and do a drawn+para mask, starting with the para part.  You select "hz", click the "dropper+" icon, and the mask delimiters are already positioned, instead of being "wide open".  In my case it's a very narrow selection that might be from a previous edit of a different file, but I'm not certain.  Resetting the module and starting again does not clear the setting.  You now click the mask display button expecting little of the image to be yellow but in fact the whole is full-on yellow.  You now sample various parts of the image by drawing rectangles with the sampler, but the para mask delimiters don't change.

You now change the module to (RGB) display masking, and all seems fine.

I appreciate editing Jpegs must be a minority scenario for dt, and using scene referred probably? makes little sense with a jpeg, however I think this behaviour is worth reporting not least because it might indicate bugginess/fragility that might affect more mainstream situations.

If jpeg+scene makes no sense, should dt pop up a warning?

**Comment by johnny-bit** [comment] 2021-08-06 16:10
Cannot reproduce on `3.7.0+678~ga913f10c0` with JPEG and exposure set to scene refered - perhaps it got fixed with #9723?

Please check.

**Closed** 2021-11-26 16:57 UTC
Labels: bug: fixed
