### ISSUE TITLE
Pentax K200D

### ISSUE THREAD

**Issue by waldbaer59** [darktable-org/darktable#11205] opened 2022-02-22 14:33 UTC
This is to inform You that I have provided two RAW file exemples for the Pentax K200D - one DNG and one PEF. This is one of the earlier DSLRs of Pentax, so I wonder why support is about to be dropped. At the moment there shows up a message in Darktable that new RAW files should be uploaded at "https://raw.pixls.us/" as otherwise the support for the camera would be suspended in (one of the) next version(s). So I gave You the data.

Thank You and best regards
Stephan

**Comment by kmilos** [comment] 2022-05-18 09:39
Duplicate of https://github.com/darktable-org/darktable/issues/11012

**Closed** 2022-05-20 13:24 UTC
Labels: duplicate, scope: camera support
