### ISSUE TITLE
Missing EXIF data in some JPEG images

### ISSUE THREAD

**Issue by jlvdb** [darktable-org/darktable#16883] opened 2024-05-26 17:59 UTC
### Describe the bug

On a small fraction of JPEG images, Darktable shows no EXIF data (camera, lens orientation, etc.). EXIF data looks correct when viewed in external viewer. I am shooting RAW+JPEG and the RAW file has been handled correctly by darktable (shot with Sony a6000). The image was imported through DT's copy&import function and the file was named correctly based on it's EXIF timestamp.

### Steps to reproduce

Unfortunately I do not have the original image anymore, so cannot reproduce the issue, but I included the image below. As said above, this images has already been imported and copied by DT.

### Logfile | Screenshot | Screencast

![20240505_132959_0060](https://github.com/darktable-org/darktable/assets/23313315/ff3b92ba-ce4e-4d29-bf21-76c89aa08e8b)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.1-1.1+74.1

### What OS are you using?

Linux

### What is the version of your OS?

Linux Mint 21.2 Cinnamon

### Are you using OpenCL GPU in darktable?

No

**Comment by victoryforce** [comment] 2024-05-26 18:21
> but I included the image below

I don't quite understand from your text, is this image the one for which darktable doesn't show the EXIF data?

**Comment by jlvdb** [comment] 2024-05-26 18:46
Yes, if I download the image and import it to a new filmroll, this is the image information that DT shows (none)
![DT_image_information](https://github.com/darktable-org/darktable/assets/23313315/b23f6097-bab7-4a77-b7df-276d61a19ee2)

**Comment by victoryforce** [comment] 2024-05-26 19:18
Can't reproduce:

<img width="324" alt="darktable_j0JjRUW8ZZ" src="https://github.com/darktable-org/darktable/assets/6246352/5b413ecd-5345-429c-aaa7-d9b050d60b84">

&nbsp;
The exiv2 command line utility doesn't show data either?

**Comment by jlvdb** [comment] 2024-05-26 19:56
It seems that the file is fine for `exiftool`, but `exiv2` says `corrupted image metadata`.
This issues seems to be an issue not with just one photo, but with about 70 out of a 3000 that I have tried to load into DT so far. Although I haven not confirmed with exiv2 yet.

**Comment by jlvdb** [comment] 2024-05-26 20:14
This would indicate to me that it is either an issue with the camera or exiv2. Just wondering how you get a correct reading of the EXIF data and I don't. Maybe a different exiv2 oder DT version?
My system is using `libexiv2-27:amd64 / 0.27.5-3ubuntu1` I think.

**Comment by victoryforce** [comment] 2024-05-27 05:33
> This would indicate to me that it is either an issue with the camera or exiv2.

exiv2, most likely

> Just wondering how you get a correct reading of the EXIF data and I don't. Maybe a different exiv2 oder DT version?

darktable is the same (4.6.1) but built with exiv2 0.27.7

> My system is using `libexiv2-27:amd64 / 0.27.5-3ubuntu1` I think.

@kmilos Is this smells familiar to you? Is this the same bug you fixed in exiv2 0.27.7 and 0.28.1?

**Comment by victoryforce** [comment] 2024-05-27 13:53
@jlvdb You need a newer libexiv2 on your system, so I'm closing the issue since it's not a darktable bug.

**Closed by victoryforce** 2024-05-27 13:53 UTC
Labels: bug: upstream

**Comment by jlvdb** [comment] 2024-05-27 14:51
Thanks for helping me sort this out!
