### ISSUE TITLE
Dt 3.6.0.1 Crop not working when export photos

### ISSUE THREAD

**Issue by Krakt** [darktable-org/darktable#9443] opened 2021-07-07 16:04 UTC
**Introduction**
This bug just appear after updating to the latest DT version installed from the official page. This was not the case with my old install running the DT 3.4. I try to fond a fix on the internet but I didn't find something. Sorry if it's already been reported but I didn't find it with a search on crop.
---------------------------------------------------------------

**Describe the bug/issue**
When I export a cropped image, the export do not create the cropped part but still give me the full image. I try with the old module crop & rotate and the new crop module. Also I try with the export menu from lighttable and from the darkroom one.

**To Reproduce**
Crop an image in 1:1 the image should be a square
Export the image

**Expected behavior**
The image should be a square

**Screenshots**
![Capture](https://user-images.githubusercontent.com/13851145/124791753-a09bb680-df4c-11eb-96c7-53080696df10.PNG)

![DSC01680_ig](https://user-images.githubusercontent.com/13851145/124791644-895cc900-df4c-11eb-8daa-a470b380cb3b.jpg)

**Platform**
* darktable version : 3.6.0.1
* OS                : Windows 10 professionnel 2004 19041.1052
* Memory            :  32GB DDR4 4200 MHz
* Graphics card     :  GTX 1070Ti 
* Graphics driver   :  v 471.11

**Additional context**
 - I try to install 3.6.0.1 again from a new download from your webpage (installer windows)
 - Try to crop with other logiciel and it's working.
- My file a raw file from Sony Alpha M3

**Comment by elstoc** [comment] 2021-07-07 17:43
You're applying a style as part of the export in "replace history" mode. I believe this will cause your darkroom edits to be discarded and replaced with the edits defined in the "Watermark center" style.

Perhaps try switching the "mode" to "append history" instead.

**Comment by Krakt** [comment] 2021-07-07 18:29
> You're applying a style as part of the export in "replace history" mode. I believe this will cause your darkroom edits to be discarded and replaced with the edits defined in the "Watermark center" style.
> 
> Perhaps try switching the "mode" to "append history" instead.

You totally right. I juste try to export without my watermark style and it's working as attended. I don't use any others styles and my watermark is only a watermark if I understand DT correctly. So the problems comme from that.

![Capture](https://user-images.githubusercontent.com/13851145/124810654-e151fa80-df61-11eb-9dcf-b3dde6c63011.PNG)

Workaround:
So actually for me to bypass this bug. I crop my picture and reimport the jpg cropped to put my watermark on it or simply change the export mode to "append history" as @elstoc mention above.

PS sorry I though I try to no use the watermark for a test, but it's look like it was only on my mind :)

**Comment by johnny-bit** [comment] 2021-07-07 18:33
> simply change the export mode to "append history"

exactly :)

Replace is for actually 100% replacing whole history with style content. Append is for adding things.

I think the main reason behind this kind of bug was because previously "append" did nothing and "replace" actually appended instead of replacing.

since everything works as intended - closing :)

**Closed by johnny-bit** 2021-07-07 18:33 UTC
Labels: bug: invalid
