### ISSUE TITLE
Windows 11 Error Launching Darktable (never has worked)

### ISSUE THREAD

**Issue by talklikeaduck** [darktable-org/darktable#11723] opened 2022-05-05 01:01 UTC
![darktable launch error](https://user-images.githubusercontent.com/59065204/166850054-15d12a39-7527-43cc-b024-1b061f1daecd.png)
Darktable worked on my Windows 10 machine, but I bought a Windows 11 machine and I get an error on launch. I reinstalled but same error. The error (see image upload) is an unhandled exception. The generated logfile contents are as follows:

----

this is darktable 3.8.1 reporting an exception:

-------------------

Error occurred on Wednesday, May 4, 2022 at 17:54:22.

darktable.exe caused a Breakpoint at location 00007FF9BD723754 in module CLOn12Compiler.dll.

AddrPC           Params
00007FF9BD723754 0000018DA2580A60 0000018DA2580A60 00000052B41FC930  CLOn12Compiler.dll!clc_specialize_spirv
00007FF9BD71F491 00000052B41FC701 0000000000000000 00000052B41FC930  CLOn12Compiler.dll!clc_specialize_spirv
00007FF9BD722E06 00000052B41FC770 0000000000000000 0000018DA994EE10  CLOn12Compiler.dll!clc_specialize_spirv
00007FF9BD655DD5 0000000000002147 00007FFA7E822C05 0000018DA02892B0  CLOn12Compiler.dll!clc_spirv_to_dxil
00007FF9FE9EC6CC 0000000000000000 00007FF9FE9EC930 0000018DA98A3E80  OpenCLOn12.dll!0x7ff90000c6cc
00007FF9FEA09F20 0000000000000000 0000018D00000000 0000018DAAC62500  OpenCLOn12.dll!clUnloadPlatformCompiler
00007FF9FEA08B4C 0000018DA714B848 0000018DA9A40D08 0000018DAAC8CD40  OpenCLOn12.dll!clUnloadPlatformCompiler
00007FF9FEA08471 0000018D86F227D0 00000052B41FE998 0000018D86BC20C0  OpenCLOn12.dll!clUnloadPlatformCompiler
00007FF9FEA0C5B8 0000018DA714B7F0 00000000000024B0 0000000000000000  OpenCLOn12.dll!clBuildProgram
00007FFA2E8DE8C0 00000052B41FF110 0000000000000103 0000018D87226710  libdarktable.dll!dt_opencl_build_program
00007FFA2E8E3FFC 0000018D86FEBA60 0000000000000001 0000018D00000000  libdarktable.dll!dt_opencl_init
00007FFA2E84194B 00007FFA00000001 0000018D863FD970 0000018D00000001  libdarktable.dll!dt_init
00007FF78A342B15 00007FF78A341660 0000000000000010 0000000000000000  darktable.exe!0x7ff700002b15
00007FF78A3415B5 000000000000005A 0000000000000000 0000000000000000  darktable.exe!0x7ff7000015b5
00007FF78A3413D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff7000013d4
00007FF78A341506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff700001506
00007FFA7CDB54E0 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFA7E80485B 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.8.1.0
ntdll.dll   	10.0.22000.527
KERNEL32.DLL	10.0.22000.613
KERNELBASE.dll	10.0.22000.613
msvcrt.dll  	7.0.22000.1
libintl-8.dll	0.21.0.0
ADVAPI32.dll	10.0.22000.434
libglib-2.0-0.dll	2.70.3.0
ole32.dll   	10.0.22000.120
sechost.dll 	10.0.22000.556
libiconv-2.dll	1.16.0.0
msvcp_win.dll	10.0.22000.1
libdarktable.dll
ucrtbase.dll	10.0.22000.1
RPCRT4.dll  	10.0.22000.613
GDI32.dll   	10.0.22000.1
win32u.dll  	10.0.22000.613
USER32.dll  	10.0.22000.282
gdi32full.dll	10.0.22000.527
combase.dll 	10.0.22000.527
PSAPI.DLL   	10.0.22000.1
SHELL32.dll 	10.0.22000.593
WS2_32.dll  	10.0.22000.1
libwinpthread-1.dll	1.0.0.0
libpcre-1.dll
libgcc_s_seh-1.dll
libcairo-2.dll
exchndl.dll 	0.9.3.0
libstdc++-6.dll
libgdk_pixbuf-2.0-0.dll	2.42.6.0
libgdk-3-0.dll	3.24.31.0
IMM32.dll   	10.0.22000.1
libgobject-2.0-0.dll	2.70.3.0
libgtk-3-0.dll	3.24.31.0
libgio-2.0-0.dll	2.70.3.0
SETUPAPI.dll	10.0.22000.469
SHLWAPI.dll 	10.0.22000.1
lua54.dll
libpango-1.0-0.dll	1.50.3.0
zlib1.dll
libpangocairo-1.0-0.dll	1.50.3.0
comdlg32.dll	10.0.22000.527
libavif.dll
libgomp-1.dll
shcore.dll  	10.0.22000.613
libcurl-4.dll
CRYPT32.dll 	10.0.22000.348
libgmodule-2.0-0.dll	2.70.3.0
libexiv2.dll
libgphoto2-6.dll
WLDAP32.dll 	10.0.22000.1
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libheif.dll
libicuuc69.dll
libicuin69.dll
libjpeg-8.dll
libIlmImf-2_5.dll
libjson-glib-1.0-0.dll
liblcms2-2.dll
libopenjp2-7.dll
libpng16-16.dll
libpugixml.dll	1.11.0.0
libsecret-1-0.dll
librsvg-2-2.dll
libsoup-2.4-1.dll
libtiff-5.dll
libxml2-2.dll
libsqlite3-0.dll
MSIMG32.dll 	10.0.22000.1
libfontconfig-1.dll
libfreetype-6.dll	2.11.1.0
libpixman-1-0.dll
VERSION.dll 	10.0.22000.1
mgwhelp.dll 	0.9.3.0
gdiplus.dll 	10.0.22000.434
dwmapi.dll  	10.0.22000.41
libffi-7.dll
HID.DLL     	10.0.22000.1
DNSAPI.dll  	10.0.22000.593
IPHLPAPI.DLL	10.0.22000.282
WINMM.dll   	10.0.22000.1
libcairo-gobject-2.dll
libfribidi-0.dll
libpangowin32-1.0-0.dll	1.50.3.0
libepoxy-0.dll
libthai-0.dll
COMCTL32.dll	6.10.22000.120
libharfbuzz-0.dll
libpangoft2-1.0-0.dll	1.50.3.0
libaom.dll
libdav1d.dll	5.1.1.0
rav1e.dll
WINSPOOL.DRV	10.0.22000.348
libatk-1.0-0.dll	2.36.0.0
libltdl-7.dll
libexpat-1.dll
libexif-12.dll
libsystre-0.dll
libbrotlidec.dll
libidn2-0.dll
libnghttp2-14.dll
libcrypto-1_1-x64.dll	1.1.1.13
libpsl-5.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.13
libzstd.dll
libbz2-1.dll
libde265-0.dll
libHalf-2_5.dll
libx265.dll 	3.4.0.31
libicudt69.dll
libIlmThread-2_5.dll
libImath-2_5.dll
libIex-2_5.dll
bcrypt.dll  	10.0.22000.1
libgcrypt-20.dll	1.10.0.0
USERENV.dll 	10.0.22000.1
libjbig-0.dll
libdeflate.dll
libLerc.dll
liblzma-5.dll	5.2.5.0
libwebp-7.dll
dbghelp.dll 	10.0.22000.1
libdatrie-1.dll
DWrite.dll  	10.0.22000.258
USP10.dll   	10.0.22000.1
libgraphite2.dll
libtre-5.dll
libbrotlicommon.dll
libunistring-2.dll	0.9.10.0
libgpg-error-0.dll	1.44.0.0
dbgcore.DLL 	10.0.22000.1
CRYPTBASE.DLL	10.0.22000.1
bcryptPrimitives.dll	10.0.22000.376
CRYPTSP.dll 	10.0.22000.1
rsaenh.dll  	10.0.22000.282
NSI.dll     	10.0.22000.1
windows.storage.dll	10.0.22000.593
wintypes.dll	10.0.22000.527
mswsock.dll 	10.0.22000.1
winhttp.dll 	10.0.22000.1
KBDUS.DLL   	10.0.22000.1
uxtheme.dll 	10.0.22000.120
MSCTF.dll   	10.0.22000.527
DEVOBJ.dll  	10.0.22000.1
cfgmgr32.dll	10.0.22000.1
WINTRUST.dll	10.0.22000.527
MSASN1.dll  	10.0.22000.1
kernel.appcore.dll	10.0.22000.71
clbcatq.dll 	2001.12.10941.16384
OpenCL.dll  	3.0.1.0
dxcore.dll  	10.0.22000.1
AppXDeploymentClient.dll	10.0.22000.469
urlmon.dll  	11.0.22000.527
iertutil.dll	11.0.22000.593
netutils.dll	10.0.22000.434
srvcli.dll  	10.0.22000.613
Windows.ApplicationModel.dll	10.0.22000.593
OLEAUT32.dll	10.0.22000.1
propsys.dll 	7.0.22000.37
profapi.dll 	10.0.22000.1
Windows.FileExplorer.Common.dll	10.0.22000.593
Windows.StateRepositoryPS.dll	10.0.22000.65
windows.staterepositoryclient.dll	10.0.22000.65
mssprxy.dll 	7.0.22000.593
nvopencl64.dll	30.0.15.1259
cryptnet.dll	10.0.22000.1
drvstore.dll	10.0.22000.120
wldp.dll    	10.0.22000.120
nvapi64.dll 	30.0.15.1259
OpenCLOn12.dll
dxgi.dll    	10.0.22000.593
d3d12.dll   	10.0.22000.120
nvcompiler64.dll	30.0.15.1259
D3D12Core.dll	10.0.22000.120
imagehlp.dll	10.0.22000.1
nvspcap64.dll	3.23.0.74
ntmarta.dll 	10.0.22000.1
D3DSCache.dll	10.0.22000.65
twinapi.appcore.dll	10.0.22000.593
nvldumdx.dll	30.0.15.1259
nvwgf2umx.dll	30.0.15.1259
CLOn12Compiler.dll
mrmcorer.dll	10.0.22000.120
windows.staterepositorycore.dll	10.0.22000.65
bcp47mrm.dll	10.0.22000.65
Windows.UI.dll	10.0.22000.1
DXIL.dll    	10.0.19592.1000
TextShaping.dll
textinputframework.dll	10.0.22000.282
CoreMessaging.dll	10.0.22000.71
CoreUIComponents.dll	10.0.22000.132

Windows 10.0.22000
DrMingw 0.9.3

**Comment by gi-man** [comment] 2022-05-05 02:15
First, you should use the issue template to provide all the info around the issue (eg. What video card).

Most likely you have an issue with OpenCL. Make sure your GPU drivers are up to date. Remove the pre installed OpenCL compatibility stuff in the windows app. Run darktable-cltest and post the output. Try starting darktable with darktable --disable-opencl to help isolate the problem.

**Comment by parafin** [comment] 2022-05-05 07:28
Duplicate of #10767

**Closed by parafin** 2022-05-05 07:28 UTC
