### ISSUE TITLE
Pentax K200D

### ISSUE THREAD

**Issue by frdbonif** [darktable-org/darktable#11832] opened 2022-05-18 09:37 UTC
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

The RAW files from the K200D is reported in the interface as needing samples.  It is not however on the list of known cameras that do not have any samples.  As I no longer have the camera the samples I have been able to upload do not include DNG (I can't even remember if the camera supported DNG to be honest).

Thanks

**Comment by kmilos** [comment] 2022-05-18 09:40
Duplicate of https://github.com/darktable-org/darktable/issues/11012

**Closed** 2022-05-20 13:23 UTC
Labels: scope: camera support
