### ISSUE TITLE
When using double frames the results are different (unexpected) depending if applied in dartktable or in lightable on export only.

### ISSUE THREAD

**Issue by vancouverbluesea** [darktable-org/darktable#6155] opened 2020-08-30 23:42 UTC
**Describe the bug**

If we are to create 2 frames within one another (grey on the outside and white on the inside) and apply to the image - it will display okay and it will also export as expected. 
However - if we are to save the double frame (2 instances of the frame) and apply to a style only on export (for example - for instagram) it will not produce the expected result. The grey frame would be on the inside instead of on the outside.

**To Reproduce**

1. take an image and create 2 frames will attach picture and also dstyle

2. if the style is applied in dartkable mode - the image appears as expected
3. Then apply the style only on export as append style
4. See error the image looks with wrong frames
The settings I am using are blow
![darktable 2020-08-30_15-57](https://user-images.githubusercontent.com/69771189/91671900-57ced200-eadf-11ea-9af8-875fecb142d6.png)

**Expected behavior**

this is when the style is applied and this is how looks in darktable
![20200222_134505_0690](https://user-images.githubusercontent.com/69771189/91671469-cb6ee000-eadb-11ea-82fe-e0eabd94678e.jpg)
I applied the style within darktable but no during the export
![2020-08-30_16-20](https://user-images.githubusercontent.com/69771189/91671792-7b454d00-eade-11ea-81a7-bdb2b84e12ce.png)

**Screenshots**

This is how it looks if the style is applied only on export
![20200222_134505_0690_01](https://user-images.githubusercontent.com/69771189/91671482-ee00f900-eadb-11ea-9023-123908d30946.jpg)

![2020-08-30_16-37](https://user-images.githubusercontent.com/69771189/91671874-2ce47e00-eadf-11ea-8615-8f823e69bf07.png)

**Platform (please complete the following information):**
 - Darktable Version:  3.2.1
 - OS:  Linux PopOS 20.04
 -  yes
 -  Nvidia RTX 2070

**Additional context**

Attaching the style as a zip.
[bb_testframe.zip](https://github.com/darktable-org/darktable/files/5147658/bb_testframe.zip)

**Comment by vancouverbluesea** [comment] 2021-02-02 02:17
Just re-tested this behaviour in 3.4.0 and it is still present.

**Comment by johnny-bit** [comment] 2021-06-27 15:38
The issue was likely due to the bug in styles on export handling which was recently fixed and is part of 3.6 release. The 3.6 release will be released in ~6 days. If you're able to test current master - it should have the fix in it :)

If you can - please test and report back!

**Comment by johnny-bit** [comment] 2021-07-28 03:47
3.6 is already released for some time and i couldn't reproduce issue.

@vancouverbluesea - if it's not working on 3.6 please commend and I'll reopen.

**Comment by vancouverbluesea** [comment] 2021-07-28 04:31
> 3.6 is already released for some time and i couldn't reproduce issue.
> 
> @vancouverbluesea - if it's not working on 3.6 please commend and I'll reopen.

Hi @johnny-bit 
It is not working actually (the issue is still there) DT 3.6.0

**Closed** 2023-03-25 00:18 UTC
Labels: bug: pending, no-issue-activity
