### ISSUE TITLE
[minor but annoying] ISO126-46 view mode and fullscreen mode weird interactions

### ISSUE THREAD

**Issue by Fade78** [darktable-org/darktable#12417] opened 2022-08-31 14:16 UTC
**Reproduced by:**
- [gi-man](https://github.com/darktable-org/darktable/issues/12417#issuecomment-1236034114)
- [Jiyone](https://github.com/darktable-org/darktable/issues/12417#issuecomment-1236174625) (with issue summary)

___________________
Hello guys,

This is a new bug I found using **Darktable 4.0.0** on **Linux Ubuntu 22.04**, installed from [this recommanded PPA](http://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_22.04).

The ISO126-46 view is not consistent. It depends from where it is enabled.

1 - Select a picture in the lighttable, go to the darkroom, with all menus enabled (normal mode)
2 - Press CTRL-B to go in the ISO126-46 view mode, take a moment to appreciate the size of the white border and of your picture.
3 - Press CTRL-B to go back into the normal view mode
4 - Press ALT-W (french shortcut, I don't know for you) to go into fullscreen mode
(starting weird stuff)
5 - Without going back to the standard view, press CTRL-B: **[BUG1]** All menus reappears and the image is displayed with a white border except that it is smaller and the white borders are bigger
6 - press ALT-W to go back to the fullscreen mode: **[BUG2]** Nothing happen
7 - press ALT-W to go back to the fullscreen mode: the ISO126-46 view is now displayed in fullscreen mode, which, I think, should have happen at step 5.
8 - Press CTRL-B: **[BUG3]** the ISO126-46 mode is turned off but all menu reappears instead of staying in fullscreen mode.
![DarkTableFullscreeBug](https://user-images.githubusercontent.com/1572834/187699299-6c7e95ae-7ba6-4fed-88f5-c741d7445361.jpg)
 (no borders, menus)

**Comment by paperdigits** [comment] 2022-09-03 02:22
You should provide your OS details, how you installed darktable, at least.

**Comment by paperdigits** [comment] 2022-09-03 02:32
> That's a mess to understand so I'll just put the step to reproduce.

The bug reporting template is there so we can collect the information generally needed to fix something. By skipping it you're making others spend more time to get that information from you.

**Comment by gi-man** [comment] 2022-09-03 03:03
I was able to replicate on fedora 36 x11 kde, except step 1) it was lightable then darkroom. 

1 - Select a picture in the darkroom (lightable), go to the lightroom (darkroom), with all menus enabled (normal mode)

**Comment by Fade78** [comment] 2022-09-03 10:14
oups, you're right I messed up. It's first lighttable and then darkroom. I'll edit the main message.

**Comment by Jiyone** [comment] 2022-09-03 18:08
Can reproduce on Ubuntu 20.04.

To make short : the bug is that activating ISO 12646 mode while in fullscreen mode quits full screen mode without inverting the fullscreen flag. That's why alt+w does nothing : the flag was still "on", so switching the flag "off" does nothing because it was already not in fullscreen.

Activating ISO 12646 shouldn't quit full screen mode at all.

**Comment by AxelG-DE** [comment] 2022-09-06 05:15
ISO 12646 is also buggy when zooming, but that is known by @aurelienpierre, who coded this mode IIRC.

**Comment by jenshannoschwalm** [comment] 2022-09-10 17:07
Hopefully i understood fully, please try

**Comment by jenshannoschwalm** [comment] 2022-10-22 16:38
@TurboGit should be closed as fixed.

**Closed** 2023-02-25 20:49 UTC
Labels: no-issue-activity
