### ISSUE TITLE
"Diffuse or sharpen" doesn't use GPU during export

### ISSUE THREAD

**Issue by Zeo14** [darktable-org/darktable#11052] opened 2022-02-03 16:55 UTC
Hello,

When I try to export a raw which use "Diffuse or sharpen" module, my GPU is not used and the export is fully processed by the CPU which causes (very) longer export time.
Note that I don't have any problem when I visualize the image in the darkroom.

Here is the dt log file where error occurs : 
1398,588990 [default_process_tiling_cl_ptp] use tiling on module 'diffuse' for image with full size 6251 x 4167
1398,590146 [default_process_tiling_cl_ptp] (4 x 1) tiles with max dimensions 2112 x 4167 and overlap 64
1398,591193 [default_process_tiling_cl_ptp] tile (0, 0) with 2112 x 4167 at origin [0, 0]
1398,592096 [opencl memory] device 0: 140811264 bytes (134,3 MB) in use
1398,592800 [opencl memory] device 0: 281622528 bytes (268,6 MB) in use
1398,651393 [opencl memory] device 0: 422737920 bytes (403,2 MB) in use
1398,652164 [opencl memory] device 0: 563853312 bytes (537,7 MB) in use
1398,652891 [opencl memory] device 0: 572673024 bytes (546,1 MB) in use
1398,653616 [opencl memory] device 0: 713788416 bytes (680,7 MB) in use
1398,654341 [opencl memory] device 0: 854903808 bytes (815,3 MB) in use
1398,655066 [opencl memory] device 0: 996019200 bytes (949,9 MB) in use
1398,655791 [opencl memory] device 0: 1137134592 bytes (1084,5 MB) in use
1398,656523 [opencl memory] device 0: 1278249984 bytes (1219,0 MB) in use
1398,657264 [opencl memory] device 0: 1419365376 bytes (1353,6 MB) in use
1398,658027 [opencl memory] device 0: 1560480768 bytes (1488,2 MB) in use
1398,658771 [opencl memory] device 0: 1701596160 bytes (1622,8 MB) in use
1401,114098 [opencl_events_flush] could not get event info for '[Read Image (from device to host)]': -5
1401,116989 [opencl_events_flush] could not get event info for '[Read Image (from device to host)]': -5
1401,119789 [opencl_events_flush] could not get event info for '[Write Image (from host to device)]': -5
1401,122611 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,125033 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,127539 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,130036 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,132531 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,135012 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,137449 [opencl_events_flush] could not get event info for 'diffuse_pde': -5
1401,139640 [opencl_events_flush] could not get event info for 'diffuse_pde': -5
1401,141896 [opencl_events_flush] could not get event info for 'diffuse_pde': -5
1401,144084 [opencl_events_flush] could not get event info for 'diffuse_pde': -5
1401,146277 [opencl_events_flush] could not get event info for 'diffuse_pde': -5
1401,148488 [opencl_events_flush] could not get event info for 'diffuse_pde': -5
1401,151498 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,153952 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,156412 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,158845 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,161274 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,164582 [opencl_events_flush] could not get event info for 'diffuse_blur_bspline': -5
1401,167352 [opencl_events_flush] could not get event info for 'diffuse_pde': -5
1401,169536 [opencl_events_flush] could not get event info for 'diffuse_pde': -5
1401,172058 [opencl_events_flush] could not get event info for 'diffuse_pde': -5
1401,174279 [opencl_events_flush] could not get event info for 'diffuse_pde': -5
1401,182470 [opencl memory] device 0: 1560480768 bytes (1488,2 MB) in use
1401,184528 [opencl memory] device 0: 1419365376 bytes (1353,6 MB) in use
1401,189424 [opencl memory] device 0: 1410545664 bytes (1345,2 MB) in use
1401,191893 [opencl memory] device 0: 1269430272 bytes (1210,6 MB) in use
1401,198520 [opencl memory] device 0: 1128314880 bytes (1076,0 MB) in use
1401,205237 [opencl memory] device 0: 987199488 bytes (941,5 MB) in use
1401,211941 [opencl memory] device 0: 846084096 bytes (806,9 MB) in use
1401,221887 [opencl memory] device 0: 704968704 bytes (672,3 MB) in use
1401,228547 [opencl memory] device 0: 563853312 bytes (537,7 MB) in use
1401,235167 [opencl memory] device 0: 422737920 bytes (403,2 MB) in use
1401,241872 [opencl memory] device 0: 281622528 bytes (268,6 MB) in use
1401,248620 [opencl_diffuse] couldn't enqueue kernel! -5
1401,250289 [opencl memory] device 0: 140811264 bytes (134,3 MB) in use
1401,257137 [opencl memory] device 0: 0 bytes (0,0 MB) in use
1401,258883 [default_process_tiling_opencl_ptp] couldn't run process_cl() for module 'diffuse' in tiling mode: 0
1401,261953 [opencl_pixelpipe] could not run module 'diffuse' on gpu. falling back to cpu path

I suspect that it has something to do with GPU memory usage because I have noticed that if I try to export with a 50% reduce factor, the problem does not appear.
Here is an example where I have exported 7 raws with 50% reduce factor:
https://imgbb.com/sb4JXXx
We can see clearly 7 moderate peaks on GPU memory usage and load is balanced between GPU and CPU .

When I try to export the same raws at full resolution I have the error quoted above and computer activity looks like that : 
https://imgbb.com/Xxrq7rS
GPU memory is hardly used at the begining and suddenly GPU is not used anymore and all the export is done on CPU.

My config is : 

* darktable 3.8.0
* OS :  windows 10
* Memory            : 16GB
* Graphics card     : Nvidia Quadro T1000 with 4GB memory

**Comment by manu-p** [comment] 2022-02-03 20:08
Hi, maybe of importance, could you please post your cpu / gpu / memory settings?

**Comment by gi-man** [comment] 2022-02-03 21:18
I'm not sure why it is creating tiles with the amount of memory your system has. Make sure your host memory limit is set to a high value (the typical default is 1500). Since you have 16Gb of memory, you can easy go to 15000 or set to 0 (no limit). 

Also, go to windows settings, app, app & features, and search for OpenCL compatibility pack in the App list. Remove it if it is installed.

**Comment by elstoc** [comment] 2022-02-03 21:26
Also there have been some issues due to incorrect setting of the `opencl_memory_headroom` parameter in the darktablerc file. This needs to be set to the maximum amount of memory that your GPU requires without darktable running, or else darktable might try to write to memory that's used by your OS already. A little more information is available in [the user manual](https://docs.darktable.org/usermanual/3.8/en/special-topics/opencl/amd-ati/) and [this post](https://discuss.pixls.us/t/opencl-analysis-darktable-much-faster-with-opencl-disabled-something-wrong/28197/22)

**Comment by jenshannoschwalm** [comment] 2022-02-04 13:25
> Since you have 16Gb of memory, you can easy go to 15000 or set to 0 (no limit).

I think you suggested this elsewhere before. Setting this as above is not a good idea at all and might lead to really bad trouble.

The original issue reported is about a memory-hungry module (with a moderately large graphics card) trying to allocate opencl memory, that failed and so fall back to cpu tiling code. There is nothing magic here. But (accepted) - we need a better way to deal with such situations.

**Comment by gi-man** [comment] 2022-02-04 14:04
> Setting this as above is not a good idea at all and might lead to really bad trouble.

At 1500, it leads the system to trouble with the diffuse module since it seems to force it to create tiles. The tiles take longer to process and more so if I use multiple instances of the diffuse module. I can try to run some test to see how much memory is actually used exporting a 50mpix image with 3 instances of diffuse module at 20 iterations each (an extreme case). Would that be helpful to find an upper limit to the limit?

**Comment by ralfbrown** [comment] 2022-02-04 15:25
No need for experimentation, we know how much memory diffuse needs:  for each pixel, 16 * (6.25 + scales) bytes, where scales is min(log2(radius),10).  Iterations does not affect memory use.

So worst case, diffuse needs 260 bytes per pixel,  meaning a typical 24 megapixel image requires 6.2 GB on export, and a 50 mpix image needs 13 GB to avoid tiling.   That's why GPUs go into tiling where they don't with any other module, and needing up to 1024 pixels of overlap *on each edge* means the number of tiles goes up rapidly.  If your `opencl_memory_headroom` is set incorrectly, dt thinks it can use tiles of a certain size, but the memory allocation on the GPU then fails.

**Comment by Zeo14** [comment] 2022-02-04 21:16
Hi, 

I've tried to set memory limit to 15000 or 0 in dt setting panel but it has changed nothing.

My opencl_memory_headroom was set to '400' (Mo?)
I've changed it to 2000 and with this config, GPU has been used during all the export! (approximatively using half of my 4Go graphic memory)
Great!

What is the best way to fine tune this value?

Thanks for your help. :)

**Comment by elstoc** [comment] 2022-02-04 21:22
Use the `nvidia-smi` tool (I don't know if there's a Windows equivalent) to monitor how much ram your OS is using on your video card and set the headroom value to a bit more than that. Mine (on Linux) uses anything up to about 500Mb depending what applications I'm using so I've set my headroom to 600Mb (on a 6Gb video card).

**Comment by gi-man** [comment] 2022-02-04 21:42
Zeo14

The developers dont recommend the value at 0. I've used mine at 0 without issues in the past. I tested at 3000 and 1500 with OpenCL off and it forces the system to create tiles in some modules(eg. filmic). I'm keeping mine at 12000 in my 16gb system and it does not create tiles. With OpenCL On, it does not create tiles and I have the opencl memory headroom set to 800. I've not tried to find an optimal point for it, but I have 12gb of video card.

**Comment by jenshannoschwalm** [comment] 2022-02-05 09:24
> Use the `nvidia-smi` tool (I don't know if there's a Windows equivalent) to monitor how much ram your OS is using on your video card and set the headroom value to a bit more than that. Mine (on Linux) uses anything up to about 500Mb depending what applications I'm using so I've set my headroom to 600Mb (on a 6Gb video card).

Of course this aproach is correct :-) This leaves a safe dt solution for non-experienced users. The default of 0.4GB seemed right some time ago, with current gnome-shell and larger monitors this is definitely on the low side. I think it's much better (safer and likely as fast) to set this to 1GB or even enforce it to be that size

**Comment by ralfbrown** [comment] 2022-02-05 14:34
I was sure I saw a PR a few months ago that automatically increased the headroom if an OpenCL memory allocation failure occurred, but I can't find it now (including grepping for "headroom" in master).  Though if I'm not entirely hallucinating it, it only checked for -4 errors and here we have -5.

**Comment by gi-man** [comment] 2022-02-05 15:18
I searched for a similar tool as the nvidia-smi in windows and it was not that great. But I did discover that the Task Manager - Performance window has GPU charts and data. In idle, the system is using 0.4GB with chrome running. So a headroom of 600 or greater would be ok. 

It would be nice to be able to adjust these values under preferences like the others.

**Comment by ptilopteri** [comment] 2022-02-05 17:31
grep opencl_memory_headroom ~/.config/darktable/darktablerc

you will need to translate that to your windows commands

**Comment by Zeo14** [comment] 2022-02-06 20:54
Thanks all for you answers.

I've set opencl_memory_headroom to 1GB and this config works and is stable on my computer.

On another computer with an older GPU (nvidia GT 740M) with only 2GB memory, changing value of opencl_memory_headroom has not effect but I notice that decreasing opencl_number_event_handles helps to prevent the original error too.

**Comment by elstoc** [comment] 2022-02-06 21:00
So we can close this as "not a bug"?

**Comment by Zeo14** [comment] 2022-02-06 21:06
Yes, for me the issue is resolved. 

Maybe it could be right to update default values for theses parameters in next release but I let devs decide it.

**Comment by elstoc** [comment] 2022-02-06 21:10
Looks like this is being looked into as part of #11065 so I'll close this.

**Closed by elstoc** 2022-02-06 21:10 UTC
