### ISSUE TITLE
Question: Sony A7IV ILCE-7M4 support?

### ISSUE THREAD

**Issue by hedefalk** [darktable-org/darktable#11473] opened 2022-04-07 06:46 UTC
New user here and I'm not sure I understand if there's something I need to do to get support for my new Sony A7IV…? 

Reading issues here and release notes I got the feeling that support was added on 3.8.0 and I'm on 3.8.1, but I still get this error trying to open up a file:

![image](https://user-images.githubusercontent.com/116520/162136148-89ddb88d-1467-4783-bd1e-b88bf04974f7.png)

Thumbs on lighttable work fine.

The camera also is not listed under the list here https://www.darktable.org/resources/camera-support/

Thanks

**Comment by kmilos** [comment] 2022-04-07 06:59
Duplicate of https://github.com/darktable-org/darktable/issues/8523

Sony ILCE-7M4 is supported, just not in the lossless mode - you'll have to shoot uncompressed or lossy for the time being (or convert to DNG).

**Closed** 2022-04-07 19:37 UTC
Labels: duplicate

**Comment by nugecom** [comment] 2022-08-20 09:00
Is there an update on support for Sony A7iv lossless compressed files? Not sure why this issue is closed? My hard drive is filling up!

I ❤️ Darktable

**Comment by Nilvus** [comment] 2022-08-20 09:32
Just read why on comment above...

**Comment by nugecom** [comment] 2022-08-20 10:59
Do you mean that I should infer that there will be no support for Sony lossless compressed despite it saying 'for the time being'? Or am I not comprehending what I read before I posted what I thought was a polite request for further information on this issue?
