### ISSUE TITLE
darktable-cli does not use DNG embedded XMP data

### ISSUE THREAD

**Issue by Timvrakas** [darktable-org/darktable#9960] opened 2021-09-08 09:02 UTC
**Describe the bug/issue**
When using `darktable-cli` to render JPGs from DNGs, darktable does not use key information provided in DNG embedded XMP metadata, most notably crop settings.

**To Reproduce**
Part 1: Prepare Files
1. Take photo in ARW, import into Lightroom (as ARW)
2. Perform tilted crop in LR
3. "Save Metadata to Files" generating .XMP sidecar file
4. Export as DNG

In _separate_ folders (or DT will cheat and pick up the XMPs), perform four experiments:
`darktable-cli IMG.ARW arw_only.jpg`
`darktable-cli IMG.dng dng_only.jpg`
These produce reasonable JPG renders, but the crop described in the metadata is not performed.

`darktable-cli IMG.ARW IMG.xmp arw_sidecar.jpg`
`darktable-cli IMG.dng IMG.xmp dng_sidecar.jpg`
These produce a cropped JPG that matches the Lightroom processing.

Then use `exiftool` to extract the XMP data from the DNG:
`exiftool -xmp -b -w xmp IMG.dng` 
and then use that xmp file to generate a JPG:
`darktable-cli IMG.dng dmg_embedded.xmp dng_embedded.jpg`
This produces a solid black JPG 618x484px (wrong size)

But, if we copy these 3 lines from the Lightroom XMP into the EXIFTool XMP (into the rdf tag):

```
xmlns:tiff="http://ns.adobe.com/tiff/1.0/"
tiff:ImageWidth="5472"
tiff:ImageLength="3648"
```
and run:
`darktable-cli IMG.dng dmg_embedded.xmp dng_embedded_tweak.jpg`
This produces a correctly cropped JPG!

**Expected behavior**
Darktable should pull the XMP metadata directly from the DNG (as well as the uncropped size metadata that is present elsewhere in the DNG) and properly render the DNG, with embedded editing. I understand this won't ever match Lightroom exactly, but having the crop ignored is a significant flaw.

**Screenshots**
My test files are here:
https://ufile.io/pkk2256i

**Which commit introduced the error**
I am new to darktable, but I don't have a reason to suspect this is a regression.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable_

* darktable version : 3.6.0
* OS                : Win10 (19042.1165) (also occurs within PhotoPrism docker container)

**Comment by johnny-bit** [comment] 2021-09-08 13:39
Duplicate of #5992

This is not a bug but a missing feature. Please close this one and continue in #5992

**Comment by johnny-bit** [comment] 2021-09-08 18:47
Closing in favour if #5992

**Comment by johnny-bit** [comment] 2021-09-08 18:53
You CAN extract XMP from DNG using for example exiftool `exiftool -xmp -b -w xmp FILENAME.DNG` which should write out correct XMP that can be used by darktable. On windows if i'm not mistaken there should be possibility to still use exiftool.

**Closed** 2021-09-08 18:54 UTC
Labels: duplicate
