### ISSUE TITLE
Details Threshold has lost functionality

### ISSUE THREAD

**Issue by Dave22152** [darktable-org/darktable#9085] opened 2021-05-27 21:40 UTC
**Description** The Details Threshold appears inoperable with DT 3.5+2360.  The Details Threshold option was working with my copy of DT 3.5+2226

**To Reproduce**

1. Activate a module such as local contrast and enable the parametric mask option and activate the mask.  The display will become entirely yellow
2. Details Threshold slider has no effect on the mask when moved right or left
3. I also turned off the mask verified that the slider has no effect on the image, so it's not just an issue with the mask

**Screenshots** See attached.

1. Original image with DT 3.5+2360
2. Parametric mask activated with mask displayed
3. Mask display with Details Threshold moved left
4. Mask display with Details Threshold moved right
5. Correctly operating Details Threshold using DT 3.5+2226

**Which commit introduced the error** As mentioned, this seems to be a new error introduced since DT 3.5+2226

**Platform**

darktable version : 3.5.0+2360~ge734491a9
OS : Windows 10
Memory : 8 GB
Graphics card : AMD A8-7410 APU with AMD Radeon R5 Graphics, 2.20 Ghz
Graphics driver : Unk
OpenCL installed : Yes
OpenCL activated : No (Open CL always causes my system to lock up - different issue)
Xorg : Unk
Desktop : HP Pavalion
GTK+ : Unk
gcc : Unk
cflags : Unk
CMAKE_BUILD_TYPE : Unk

![1  Original Image](https://user-images.githubusercontent.com/61152378/119899887-beb7d500-bf11-11eb-8e13-3fa627230893.JPG)
![2  Mask activated](https://user-images.githubusercontent.com/61152378/119899888-beb7d500-bf11-11eb-9fcd-15444035b4cf.JPG)
![3  With Details Threshold slider adjusted to the left](https://user-images.githubusercontent.com/61152378/119899890-bf506b80-bf11-11eb-9c5e-3d3900cd740b.JPG)
![4  With Details Threshold slider adjusted to the right](https://user-images.githubusercontent.com/61152378/119899891-bf506b80-bf11-11eb-9733-a37a7cf82ba3.JPG)
![5  DT 3 5+2226 with Details Threshold slider adjusted to the left](https://user-images.githubusercontent.com/61152378/119899892-bf506b80-bf11-11eb-9573-a53abcac1502.JPG)

**Comment by johnny-bit** [comment] 2021-05-28 05:59
Since it's a relatively small gap in commits, would you be able to bisect the issue to make it easier for devs to trace it following https://github.com/darktable-org/darktable/wiki#finding-bug-causes ?

@jenshannoschwalm - would you need additional details to figure out the issue?

**Comment by jenshannoschwalm** [comment] 2021-05-28 07:11
I will have a look ... for me there is only one suspicious merged pr since introducing this feature.

**Comment by Dave22152** [comment] 2021-05-29 00:11
@johnny-bit, I can give it a try, but I've never tried a bisect before.

**Comment by jenshannoschwalm** [comment] 2021-05-29 03:56
There is no need for a bisect, the problem is "pretty clear". PR following

**Closed** 2021-05-29 06:47 UTC
Labels: bug: pending, scope: image processing

**Comment by Dave22152** [comment] 2021-05-29 19:24
@jenshannoschwalm, I just built the latest master and the masking works fine.  And FWIW, I was able to edit with earlier versions without any issue.  Thanks for your help!
