### ISSUE TITLE
On wayland popups show up top left instead of in the module section

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#12478] opened 2022-09-12 17:38 UTC
I don't know since which git version this happens for me. I cleaned my build directory to exclude residue on my side but it still happens. 

Darktable version is 4.1.0+345~g0f8640769-dirty and still shows the dirty moniker although I ran git clean -d -f  -x and git pull --rebase afterwards. 

Screen resolution is 2560x1440 and I am using the grey elegant default theme.

Any way to debug this?

**Comment by Nilvus** [comment] 2022-09-12 18:49
Your issue is not really precise. You don't precise correctly which popup (a screenshot could be useful). Anyway, popup position is not done by darktable (as all other Gtk apps) but by Gtk library. It's a known issue and exist since a long time. Note that doesn't mean that the issue is always here. Gtk position depends on many thing: where click is made, screen resolution, fullscreen or window mode, etc.
Bad popup position appears more often when the click is next to the edges of the screen.

**Comment by piratenpanda** [comment] 2022-09-12 19:25
I am sorry for not being precise enough. It not only happens to right click popups like this (image removed):
![popup](https://user-images.githubusercontent.com/920721/189738144-4bfac0b3-88d6-40d2-93c7-5c284b8fbc9d.png)
but also selections like filmic norms etc. It happens all the time now (it's never placed correctly and one can only change things by using the arrow key which is kinda annoying) and might be due to the gtk 4.8.0 update on arch.

**Comment by dterrahe** [comment] 2022-09-12 19:55
> Anyway, popup position is not done by darktable

This is not correct. darktable _uses_ gtk to place the popups where it wants them. 4.8 saw some changes to how this is done, to avoid the popup ending up, partially, off-screen but oviously this works correctly for most developers and users otherwise we'd have seen more complaints.

So for a bug report to be useful, we need to know what is _different_ in this situation to see what might be the cause of your issue. You don't even list the OS or window manager, but it would also be useful to know the exact gtk version installed. If you would be able to roll back to a previous version of the gtk libraries, and check if that makes the bug go away, that might further help pinpointing a culprit. Gtk updates, even to the "stable" gtk3 branch, have regularly caused issues.

Maybe Nilvus' "won't fix" response is triggered by this lack of information.

**Comment by elstoc** [comment] 2022-09-12 20:25
> oviously this works correctly for most developers and users otherwise we'd have seen more complaints

... or nobody uses the right-click popup (I can't remember the last time I used it)! Anyway, I cannot reproduce this using latest master (4.1.0+346~g26bbeab7c) on ArchLinux.

**Comment by Nilvus** [comment] 2022-09-12 21:10
Thanks @dterrahe for correcting my mistake here about position of popup. I've mixed some old issues about position related to Gtk and, as you said, lack of infos. So label update for more correct one at this state. I let you follow @piratenpanda precisions. You are more competent than me for this part.

@piratenpanda: remember that we provide a template to reduce missing infos.

As @elstoc, I can't reproduce. popup on right-click is right under slider, as it should and was.

**Comment by dterrahe** [comment] 2022-09-12 21:27
> ... or nobody uses the right-click popup

I'm reading the bug report as implicating all bauhaus popups, which means also (left-click) combobox list popup. I may be wrong though...

**Comment by piratenpanda** [comment] 2022-09-13 04:51
Yes it happens for every popup, be it right or leftclick:
![popup2](https://user-images.githubusercontent.com/920721/189811285-77e71e7c-bbf5-4dd2-b62e-a3e640485d27.png)

I'm running latest Arch with GNOME 42.2, gtk version is 4.8.0. I'll try if I can revert to earlier gtk versions.

**Comment by piratenpanda** [comment] 2022-09-13 05:32
Reverting gtk versions to 4.6.0. where the problem did not exist for sure and building again did not help. Installing 4.0 from the arch repo works just fine regardless of gtk version.

**Comment by Nilvus** [comment] 2022-09-13 06:04
darktable uses Gtk 3, not Gtk 4. Which Gtk 3 release you use?
Did you try reverting it?
I use master on Debian Sid and don't have your issue.

**Comment by mohms** [comment] 2022-09-13 09:02
I have the same issue on Fedora 36

gtk3 version 3.24.34
gtk4 version 4.6.7

**Comment by piratenpanda** [comment] 2022-09-13 11:33
Yeah, I'm also running on wayland. Might be the culprit.

**Comment by dterrahe** [comment] 2022-09-13 12:05
Thanks for the additional information!

I'll have to try to get wayland up and running then to see if this can be fixed. If I theorize, it might be that wayland reports the screen size incorrectly/differently, throwing off the placement calculation.

Is wayland no longer being advised against for use with dt because of color management issues?

**Comment by elstoc** [comment] 2022-09-13 12:31
AFAIK colour management is still WIP on wayland. Last I knew we were still recommending against using it with dt, certainly I doubt there are (m)any devs using it.

**Comment by gi-man** [comment] 2022-09-13 12:33
> I have the same issue on Fedora 36
> 
> darktable version 4.1.0~git345.0f864076-8516 gtk3 version 3.24.34 gtk4 version 4.6.7
> 
> **Update**: It seems like this only happens on wayland. When I log into gnome shell on Xorg everything works as expected. Maybe also worth noting is that window decorations are different between wayland and X:
> 
> Xorg: ![Screenshot from 2022-09-13 11-22-33](https://user-images.githubusercontent.com/8134686/189864723-2a44bbb6-bfde-4ffb-b762-a094947bf12e.png)
> 
> Wayland: ![image](https://user-images.githubusercontent.com/8134686/189864607-fd1dbf40-c1d2-4aba-a981-4081e3859cea.png)

I'm on Fedora 36. I normally use X11, but I just tried Wayland and I dont not have the issue. I'm on current master 4.1.0~git349

gtk3.x86_64                                          3.24.34-1.fc36  
gtk4.x86_64                                          4.6.7-1.fc36

**Comment by dterrahe** [comment] 2022-09-13 12:44
> I just tried Wayland and I dont not have the issue.

Interesting. Do any of those on wayland use a multi-monitor setup?

> certainly I doubt there are (m)any devs using it.

You are right. Maybe this should gradually change, so that we can do at least the minimum amount of testing. Depending on how easy it is to get both environments set up on the same machine.

But hardware support is an area where we'll always be heavily dependent on user feedback like this.

**Comment by mohms** [comment] 2022-09-13 13:15
> I'm on Fedora 36. I normally use X11, but I just tried Wayland and I dont not have the issue. I'm on current master 4.1.0~git349

weird that it doesn't show up for you, I'll try to dig around a bit more when I have time for it

> Interesting. Do any of those on wayland use a multi-monitor setup?

I do when my laptop is connected to the dock on my desk. Doesn't make a difference though.
Yeah, color management doesn't work on wayland, but for casual use with an uncalibrated monitor it's been working fine until now and the gnome experience on my laptop is way better with wayland which is the main reason to use it for me.

**Comment by mohms** [comment] 2022-09-13 13:21
time-wise this does correlate with me first noticing this bug

**Comment by parafin** [comment] 2022-09-13 13:26
The point, I guess, is that there should be some developer actually running darktable on Wayland as his main configuration and taking care of Wayland support.

**Comment by elstoc** [comment] 2022-09-13 13:28
Might be helpful if someone could update the title/description of the issue to mention Wayland.

**Comment by piratenpanda** [comment] 2022-09-13 13:30
I could test build without [#](https://github.com/darktable-org/darktable/pull/10853) later

**Comment by gi-man** [comment] 2022-09-13 14:31
> The point, I guess, is that there should be some developer actually running darktable on Wayland as his main configuration and taking care of Wayland support.

I would not mind using Wayland, but color management is still an issue with wayland. My monitor default brightness is too high, so I end up with too dark images without monitor calibration.

**Comment by dterrahe** [comment] 2022-09-13 15:13
> I could test build without #10853 later

Please test https://github.com/darktable-org/darktable/pull/12484 instead...

**Comment by piratenpanda** [comment] 2022-09-13 15:59
Works fine with https://github.com/darktable-org/darktable/pull/12484 thank you!

**Comment by Nilvus** [comment] 2022-09-13 16:47
Not related to main issue here but to answer @mohms comment about window decorations, it's just normal. Window decoration do not depend on app but on window manager. It could be different regarding desktop environment or display server used (here Wayland or Xorg).

And good to find main missing information that help fix that.

**Comment by TurboGit** [comment] 2022-09-13 17:04
> Might it be related to the PR #10853 being merged recently?

I was about to say that but since some user's don't have the issue with this PR merged looks like there is something else.

**Closed** 2022-09-14 07:46 UTC
Labels: understood: clear, scope: UI, bug: pending
