### ISSUE TITLE
Gimp unable to find Darktable plugin for version 4.8.1

### ISSUE THREAD

**Issue by elalexluna83** [darktable-org/darktable#17360] opened 2024-08-23 18:46 UTC
### Describe the bug

After upgrading darktable to 4.8.1 Gimp can no longer open raw files. It complains that a raw plugin is missing even though darktable is installed Darktable can open the file directly though.

### Steps to reproduce

Download Darktabel 4.8.1 and install it.

### Expected behavior

Raw Image Importer should "see" the plugin

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

darktable-4.8.1-win64.exe

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment] 2024-08-23 20:25
Gimp is looking for a specific string when running darktable -h.  That changed in 4.6 (temporarily reverted in 4.6.1); you'll need a newer version of the Gimp plugin which knows how to ask in the way that the Gimp and darktable projects agreed on to avoid any future such incompatibility.

**Comment by victoryforce** [comment] 2024-08-25 19:24
As already mentioned above, the developers of Gimp and darktable established new agreements about how the Gimp plugin should recognize the new version of darktable. This was implemented, and on the darktable side, the corresponding code is already in versions 4.8.x. On the Gimp side, the code was added to the codebase on May 25. The problem is that there hasn't been a single Gimp release since then.

The only thing you can do is ask in Gimp issue tracker to speed up their new release, as the current situation is causing you inconvenience.

Since we can't help from the side of darktable, I am closing this issue

**Closed by victoryforce** 2024-08-25 19:24 UTC
Labels: depends: external lib
