### ISSUE TITLE
Export preset not updating with Style

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#6124] opened 2020-08-28 10:23 UTC
**Describe the bug**
I've created a Style preset which I want to include in an Export preset.
But the existing Export preset will not update.

**To Reproduce**
I'm on Windoze 10, running 3.2.1
I have an Export preset called Instagram which epxorts to a set folder, at a set resolution and file format.
I decided I wanted to add a Style preset to this Export preset.
I add the Style.
I click on the hamburger and select Update preset Instagram`, and click Yes on the confirmation.
Select any other Export preset.
Then select Instagram Export preset.
Style has not been saved to the preset.

Apologies if this has been raised elsewhere.

**Comment by matt-maguire** [comment] 2020-08-28 11:18
I tried this on both Windows and Linux with DT 3.2.1, in both cases if I go to the "style" dropbown box just above the "export" button, and select a style, then "update preset" and click on "yes" to confirm, then the style seems to be saved into the preset, which I can see by going away to another presetthen coming back. I wonder if there was anything else strange about your preset that was preventing it from being saved properly. For example, if you modiy the quality slider and do a style update, is it preserved when you go away to another preset and come back?

**Comment by brucewilliamsphotography** [comment] 2020-08-28 11:22
Matt,
Nope, that didn't work.
I've just made the modifications I wanted and saved as a new preset. THAT
has at least worked! :)
Cheers,
Bruce Williams
------------------------------
brucewilliamsphotography.com
shuttersincpodcast.com
------------------------------
e-mail <studio@brucewilliamsphotography.com> | Twitter
<http://twitter.com/@audio2u> | LinkedIn
<http://au.linkedin.com/pub/bruce-williams/1/318/489> | Facebook
<http://www.facebook.com/audio2u>
------------------------------

**Comment by matt-maguire** [comment] 2020-08-28 11:49
Ok, so what I think is happening is that your instrgram preset is stored in the database in a legacy blob format, and for some reason it is not being upgraded correctly and storing the new preset information. When you create the new preset, it is automatically created using the latest blob schema, so no problem.

Do you know what darktable version you used to create the instagram preset in that database?

**Comment by brucewilliamsphotography** [comment] 2020-08-28 11:54
This version! 3.2.1.
I installed it on the laptop just before I hit the road a week ago, and
created the preset from scratch!
Weird, right?
Cheers,
Bruce Williams
------------------------------
brucewilliamsphotography.com
shuttersincpodcast.com
------------------------------
e-mail <studio@brucewilliamsphotography.com> | Twitter
<http://twitter.com/@audio2u> | LinkedIn
<http://au.linkedin.com/pub/bruce-williams/1/318/489> | Facebook
<http://www.facebook.com/audio2u>
------------------------------

**Comment by matt-maguire** [comment] 2020-08-28 12:15
That is weird -- you create a preset a week ago, it's somehow dodgy, but the one you create tonight is fine :-/  We might need to take a look at your data.db file to see what is going on there with the presets...

**Comment by brucewilliamsphotography** [comment] 2020-08-28 12:21
OK, here it is.

Cheers,
Bruce Williams.

**Comment by johnny-bit** [comment] 2020-08-28 12:51
Hey Bruce,
Unfortunatelly it didn't attach to github issue if you attached it via mail. Can you try and attach it via github? If github wont allow direct data.db then zip it and attach the archive :)

**Comment by brucewilliamsphotography** [comment] 2020-08-28 22:00
I've sent the file directly to Matt.
Cheers,
Bruce Williams
------------------------------
brucewilliamsphotography.com
shuttersincpodcast.com
------------------------------
e-mail <studio@brucewilliamsphotography.com> | Twitter
<http://twitter.com/@audio2u> | LinkedIn
<http://au.linkedin.com/pub/bruce-williams/1/318/489> | Facebook
<http://www.facebook.com/audio2u>
------------------------------

**Comment by matt-maguire** [comment] 2020-08-29 01:28
It's reproducible on linux and on both 3.2.1 as well as the master branch using Bruce's data.db (attached, with his tags stripped out). If you try adding a style to the "instagram" preset or change something like output quality, and then update the preset, the changes don't persist. It's a normal ver7 preset (ie. not legacy), fname is "jpeg" (fversion 2) and and sname is "disk (sversion 3). There is nothing obvious to me so far why changes to this preset aren't being saved.  

[data.zip](https://github.com/darktable-org/darktable/files/5144626/data.zip)

**Comment by matt-maguire** [comment] 2020-08-31 07:00
So found the problem Bruce. It crops up when the name you chose for your preset conflicts it a preset using the same name in another module. I pushed a fix, but in the meantime as a workaround, just choose a unique name for your presets that isn't used in any other modules.

**Comment by brucewilliamsphotography** [comment] 2020-08-31 07:51
Ahhh, good to know.
Thanks for the update, Matt.
Cheers,
Bruce Williams
------------------------------
brucewilliamsphotography.com
shuttersincpodcast.com
------------------------------
e-mail <studio@brucewilliamsphotography.com> | Twitter
<http://twitter.com/@audio2u> | LinkedIn
<http://au.linkedin.com/pub/bruce-williams/1/318/489> | Facebook
<http://www.facebook.com/audio2u>
------------------------------

**Closed** 2020-09-01 06:26 UTC
