### ISSUE TITLE
Color Lookup Table broken?

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/darktable#2968] opened 2019-09-20 17:53 UTC
**Describe the bug**
Did an edit with 2.7.0+1687~gbc430e37e. Downloaded latest git and built it, then reopened the previously edited image and noticed that color lookup table doesn't appear to be working correctly.  I've attached an export from 2.7.0+1687~gbc430e37e (_7D_9592_01.jpg) and current git (_7D_9592.jpg)
![_7D_9592](https://user-images.githubusercontent.com/1634891/65347658-762d0d80-dbad-11e9-9a48-14ab4f700d2c.jpg)
![_7D_9592_01](https://user-images.githubusercontent.com/1634891/65347664-77f6d100-dbad-11e9-8f19-ae134fe49547.jpg)

**To Reproduce**

Edit an image and make color lookup table adjustments in 2.7.0+1687~gbc430e37e or earlier.  Open the image in current git and compare the two.

**Expected behavior**
The images should look the same (preferably like the bottom one :-)).

**Screenshots**
attached exported images showing the problem

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version current git

**Comment by TurboGit** [comment] 2019-09-20 18:13
Does it reproduce if you go from 2.6.2 to current Git master?

**Comment by wpferguson** [comment] 2019-09-20 20:17
I did the same edit in 2.6.2, but quit after the color tables.  When I imported it in the latest git, it did not distort.

**Comment by wpferguson** [comment] 2019-09-20 20:20
Another data point.  Did the edit in 2.6.2, imported into 2.7.0+1687gbc430e37e, then opened with the latest git and it didn't distort.

**Comment by wpferguson** [comment] 2019-09-20 20:24
Another data point.  Took a fresh image, edited it in 2.7.0+1687gbc430e37e with a color lookup table and nothing else, imported into latest git and it distorted.

**Comment by wpferguson** [comment] 2019-09-20 20:30
Another data point.  Here's the console output...

[dt_ioppr_transform_image_colorspace_cl] module colorchecker must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorchecker must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorchecker must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace_cl] module colorin must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace_cl] module colorchecker must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorchecker must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorchecker must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace_cl] module colorin must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorchecker must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorchecker must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorchecker must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorchecker must be between input color profile and output color profile
[dt_ioppr_transform_image_colorspace] module colorin must be between input color profile and output color profile

**Comment by wpferguson** [comment] 2019-09-20 20:40
One last data point.  Duplicated a clean image of one of the distorted ones in latest git.  Did a color table lookup adjustment.  Opened in 2.7.0+1687gbc430e37e, and changed the color lookup table settings.  Opened latest git and imported the updated xmp.  Image did not distort.

**Comment by wpferguson** [comment] 2019-09-20 20:44
Oops, I lied.  Maybe the last data point.  Took an fresh image and only did a color table lookup adjustment in 2.7.0+1687gbc430e37e.  Imported into latest git and it distorted.

**Comment by thugcee** [comment] 2019-09-20 21:06
Same problem. Version 2.7.0+1778~g57d00fa4c (yesterday git master). Any adjustment in _color lookup table_ makes a total mess in colors. Happens for images which were already edited in older version of dt. After removing image from library, deleting xmp and importing image again, _color lookup table_ works normal.

**Comment by TurboGit** [comment] 2019-09-21 06:18
Yes, that probably a transient issue affecting only users of 2.7 dev version which had a broken iop_order for some time.

**Comment by TurboGit** [comment] 2019-09-21 06:18
To me this is the same issue as the crop&rotate one being debated in #2950

**Comment by chrik5** [comment] 2019-09-22 19:19
@TurboGit 

> Yes, that probably a transient issue affecting only users of 2.7 dev version which had a broken iop_order for some time.

What does some time means approximately? 

colorbalance messes up colors as well or turns images black. I guess this is a related issue. I edited the images in August 2019 with latest git master at that time.

**Comment by TurboGit** [comment] 2019-09-22 21:11
You may want to test:
#2974

This must be tested with images that have not been edited since September 16th.

**Comment by wpferguson** [comment] 2019-09-23 02:42
Tested and it works. Images edited before September 16th display correctly. New edits using bloom and color lookup table modules now work correctly.

If you edited an image with the corrupt iop order, you need to remove it from the database, probably git rid of the xmp file, then reimport it.

**Comment by TurboGit** [comment] 2019-09-23 05:10
You could also reorder the module manually.

Anyway fix merged now #2974.

Thanks.

**Closed by TurboGit** 2019-09-23 05:10 UTC
