### ISSUE TITLE
dynamic heap allocation problems causing crashes in darkroom also

### ISSUE THREAD

**Issue by MartinScharnke** [darktable-org/darktable#5997] opened 2020-08-17 01:15 UTC
**Describe the bug**
crash resulting from trouble with dynamic heap allocation, similar to #5963, but this occurs when using darkroom. 

Two different example console error logs attached:

[darkroom crash.txt](https://github.com/darktable-org/darktable/files/5081680/darkroom.crash.txt)
[darkroom crash2.txt](https://github.com/darktable-org/darktable/files/5081681/darkroom.crash2.txt)

**To Reproduce**

To reproduce: in darkroom, use the filmstrip to select images, and reject one clicking the x button on the overlay to the left of the star rating. It may take a few attempts to cause the crash :-{

**Expected behavior**

Expected behaviour is no crash!

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0~git166.65b998a6d
 - OS: Linux BARADDUR 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - OpenCL activated
 - GeForce GTX 1660
**Additional context**

**Comment by johnny-bit** [comment] 2021-05-18 18:28
Cannot reproduce on neither 3.4.1 nor on current master.

Closing for now. If you're able to reproduce please provide reproduction steps & new log files.

current master is (roughly) 3.5.0+2258

**Closed by johnny-bit** 2021-05-18 18:28 UTC
Labels: no-issue-activity
