### ISSUE TITLE
bug with styles since Friday 09-11-2020

### ISSUE THREAD

**Issue by LViatour** [darktable-org/darktable#6275] opened 2020-09-12 08:29 UTC
Problem between version darktable_3.3.0 ~ git605.a685d2730_amd64.deb
and Commits on Sep 11, 2020

Here is the problem:

applying a style to an image works but spas a second time. the second time darktable hangs.

In a terminal I have the following message:
[image_cache_allocate] failed to open image 4294967295 from database: no more rows available

I took in apt-cache the DT version of Thursday 10 and there no problem.

DT Master version on Ubuntu 20.04 updated.
Nvidia GeForce GTX 970M graphics card
drive 440,100

**Comment by johnny-bit** [comment] 2020-09-12 09:10
If you know commit ranges (and are able to build your own darktable) please take a look at https://github.com/darktable-org/darktable/wiki#finding-bug-causes - that way we can isolate a single root cause for error you're seeing.

Can we build a reproducer, that's minimum viable way to trigger problem? Say: pure clean config, 2 images in db, edit one changing something that's guaranteed not to fail (eg exposure) and make style out of that, then apply style in a way that triggers the bug.

**Comment by LViatour** [comment] 2020-09-12 09:28
I just installed the latest update.
I deleted the config / darktable folder to have a blank configuration.
I imported a raw photo folder.

I created a test style with just an exposure setting.

I applied the style to one image and then to another and darktable crashed.

**Comment by TurboGit** [comment] 2020-09-12 10:17
@LViatour : I just did that and was able to apply the style on more than 5 images, no crash :(

**Comment by LViatour** [comment] 2020-09-12 11:08
I just did a test again.
When I do a style and I only select the brightness, no problem. If do a style with the option "all" the style crashes DT

**Comment by LViatour** [comment] 2020-09-12 11:36
The problem is when only the "input color profile" is selected in the style.

**Comment by LViatour** [comment] 2020-09-12 11:44
I deleted the input color profile "from my styles and have no more problems .....
But I do not know why

**Comment by TurboGit** [comment] 2020-09-12 12:18
Thanks! I can reproduce with your latest information.

**Comment by TurboGit** [comment] 2020-09-12 12:33
Making progress:

```
23dc3a9980646ccec3b4370a046ea33177011c69 is the first bad commit
commit 23dc3a9980646ccec3b4370a046ea33177011c69
Author: Diederik ter Rahe <dterrahe@yahoo.com>
Date:   Sun Aug 30 08:18:30 2020 +0100

    cleanly enforce interface of iop module init vs reload_defaults

 src/develop/imageop.c    |  4 ++--
 src/iop/cacorrect.c      |  3 ---
 src/iop/colorin.c        |  3 ---
 src/iop/colormapping.c   | 22 +++++++++-------------
 src/iop/colorout.c       | 21 ++++-----------------
 src/iop/colortransfer.c  | 29 ++---------------------------
 src/iop/demosaic.c       |  3 ---
 src/iop/denoiseprofile.c | 47 +++++++++++++++++++++++++++++------------------
 src/iop/filmicrgb.c      |  3 ---
 src/iop/flip.c           | 14 +++-----------
 src/iop/hotpixels.c      |  3 ---
 src/iop/invert.c         |  2 --
 src/iop/lens.cc          |  3 ---
 src/iop/levels.c         |  8 +++++---
 src/iop/rawdenoise.c     | 12 ++++++++----
 src/iop/rotatepixels.c   | 20 --------------------
 src/iop/scalepixels.c    | 31 ++++---------------------------
 src/iop/spots.c          | 10 ----------
 src/iop/tonecurve.c      | 34 +++++++++++++---------------------
 19 files changed, 79 insertions(+), 193 deletions(-)
```

**Comment by TurboGit** [comment] 2020-09-12 12:37
Fix proposed, see #6278 .

**Comment by TurboGit** [comment] 2020-09-12 13:48
@LViatour : fixed on current master branch now.

**Closed** 2020-09-12 13:47 UTC
Labels: bug: pending, priority: high

**Comment by LViatour** [comment] 2020-09-12 15:40
A very big thank you
