### ISSUE TITLE
strange result when opening a fujifilm raw file in dark table

### ISSUE THREAD

**Issue by abhsrivastava** [darktable-org/darktable#6339] opened 2020-09-20 03:10 UTC
**Describe the bug**
I am using DarkTable 3.2.1 on MacOS (Catalina). I opened a fujifilm raw file in dark table. I didn't make any changes myself. Just double clicked in lighttable and the image opened in dark table. I see strange pattern in all highlights.

Here is what I see

https://imgur.com/a/fjTBifN

You see every highlight has a strange green patch on it. 

This is my file which I tried to open

https://drive.google.com/file/d/1fTSueYAe5KuDUUQ9CB__yMeD-Z0vg-y6/view?usp=sharing

You can download this file and then try to open in darktable 3.2.1 on MacOS.

**Expected behavior**
I expect the file to open without these green patches. 

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: macOS Catalina 10.15.6
 - I don't know about OpenCL
 - Graphic Card: AMD Radeon Pro 5500M, Intel UHD Graphics 630

**Additional context**

**Comment by chhil** [comment] 2020-09-22 01:43
I opened the file in the dev version of DT 3.3.0+783 I did not see the issue.
![image](https://user-images.githubusercontent.com/1119439/93837211-e4198280-fca2-11ea-9d35-8c66da5cc6c0.png)



However, when I view raw over exposed enabled then I am correctly seeing the pattern you are seeing.

![image](https://user-images.githubusercontent.com/1119439/93837264-0f03d680-fca3-11ea-9e5a-b941de017d85.png)

**Comment by chhil** [comment] 2020-09-22 01:44
I opened the file in the dev version of DT 3.3.0+783 I did not see the issue.
![image](https://user-images.githubusercontent.com/1119439/93837211-e4198280-fca2-11ea-9d35-8c66da5cc6c0.png)



However, when I view raw over exposed enabled then I am correctly seeing the pattern you are seeing.

![image](https://user-images.githubusercontent.com/1119439/93837264-0f03d680-fca3-11ea-9e5a-b941de017d85.png)

**Comment by johnny-bit** [comment] 2020-09-22 08:46
So... NOT A BUG :) you have clearly enabled raw overexposure indicator. Toggle it off and problem will disappear. Also, please close this issue :)

**Closed** 2020-09-25 04:21 UTC
