### ISSUE TITLE
Snapshot comparison is missing from 2.6.3 on Windows

### ISSUE THREAD

**Issue by infjb** [darktable-org/darktable#3406] opened 2019-11-13 11:52 UTC
A comparison slider should appear on top of the image when you select a snapshot which is different from the current stack.

To reproduce it edit a picture. Then select one of the steps different from the top most. Take a snapshot. Activate that snapshot. The select the top most step. 

A vertical slider should appear over the image to allow the comparison of the snapshot with the current step of the editing stack. But no slider appears.

OS: Windows 10
Version: 2.6.3

The comparison was working on version 2.6.2.

![Screenshot 2019-11-13 12 36 37](https://user-images.githubusercontent.com/57672052/68761425-50a00b80-0614-11ea-959c-f766bfa7baea.png)

**Comment by peterbud** [comment] 2019-11-13 12:03
Duplicate of #3224

**Closed** 2019-11-13 12:07 UTC
