### ISSUE TITLE
 [exposure module] exposure negative value with mask

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#15879] opened 2023-12-14 16:03 UTC
### Describe the bug

If I use a negative value for the exposure control, I can use a strongly low exposure value, say -10 EV, and everything is fine.

But if I use a mask, like a gradient, or an ellipsys, the exposure values less than -4 haven't any effect on the image. If you remove the mask, those values do have effect.

### Steps to reproduce

see descripcion

### Logfile | Screenshot | Screencast

see descripcion

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

nvidia 3050

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

no lua scripts

**Comment by ralfbrown** [comment] 2023-12-14 19:53
Works just fine (ellipse and gradient) in normal blend mode with Master on a NEF.

**Comment by piratenpanda** [comment] 2023-12-15 12:50
Also seeing this on latest master, AMD opencl. The changes between -10,-8,-6 in the masked area are subtle while without mask the image is much darker:

-8EV wo mask:
![grafik](https://github.com/darktable-org/darktable/assets/920721/f15ecfb7-d5a5-4663-b0ac-ffdf8fbbe8ef)

-8EV w mask applied inside the shape:
![grafik](https://github.com/darktable-org/darktable/assets/920721/d427a899-8212-4772-9edd-aad6b38d0fcc)

-8EV w mask applied outside the shape:
![grafik](https://github.com/darktable-org/darktable/assets/920721/1d797349-97ba-4ebe-8fe2-b273031d4028)

I'd also say inverting masks changes the effect

**Comment by paolobenve** [comment] 2023-12-15 18:09
I compiled master, and I can confirm the bug.

Let me say how I'm reproducing it:
- open dt
- load an image
- go to the exposure module
- set the exposure value to -20 EV (the slider is not enough, after putting the slider at -4 EV, minimum value, right click and write -20, then return) -> you'll get a perfectly black image. **That's ok.**

- now click on the mask button, and select the gradient, position it in the image -> you'll see the image again, one half with the original exposure, the other half with exposure corrected to -4 EV. The user correction of -20 EV cannot be achieved. **BUG**

You can move the exposure slider from -20 EV upward, and you'll begin to see changes when you reach -4 EV

I have opencl with nvidia geforge 3060 video card

**Comment by jenshannoschwalm** [comment] 2023-12-15 22:05
You are aware that there is some function defining the mask transition? A mask is no binary on/off switch?

**Comment by jenshannoschwalm** [comment] 2023-12-16 06:11
Can't confirm anything "not expected" here neither on nvidia nor cpu.

@piratenpanda not sure about your image (and another round of amd nice things :-) Could you provide raw & xmp please?

**Comment by piratenpanda** [comment] 2023-12-16 06:43
Sure, here you go https://www.pandainthecloud.de/nextcloud/index.php/s/jWwjwr2AR4LtciY

**Comment by jenshannoschwalm** [comment] 2023-12-16 08:18
I don't have cr3 supported here.

**Comment by TurboGit** [comment] 2023-12-16 14:17
@piratenpanda : Your mask is not 100%, it was set to 80% so that's expected.

**Comment by TurboGit** [comment] 2023-12-16 14:19
![image](https://github.com/darktable-org/darktable/assets/467069/9cc7c97e-e371-4ee6-98c0-f8f2b85093d0)

**Comment by piratenpanda** [comment] 2023-12-16 19:20
Stupid me, must have changed that unnoticed. Sorry

**Comment by jenshannoschwalm** [comment] 2023-12-17 10:06
> must have changed that unnoticed

Same happened to me some time ago :-)

@paolobenve same with you?

**Comment by paolobenve** [comment] 2023-12-18 02:45
No, mask's opacity is 100%, but there is something that produces an effect like if opacity were a different value....

My mask polarity is "-": is it correct?

If I switch to "+" the bug desappears.

A screenshot of the module options:

![Captura de pantalla_2023-12-17_21-40-46](https://github.com/darktable-org/darktable/assets/1417508/89831e05-2184-4bdd-ba73-64574db3e5d7)

**Comment by jenshannoschwalm** [comment] 2023-12-18 19:03
Can you reproduce with any non-cr3 file?

**Comment by paolobenve** [comment] 2023-12-18 19:19
yes, the bug is there with a NEF in 4.4.2, and opening the raw with the sidecar generated by 4.4.2 shows the bug

sidecar file:
[Messa 25º seminario 2017-06-05--06.30.55.NEF.xmp.zip](https://github.com/darktable-org/darktable/files/13707720/Messa.25.seminario.2017-06-05--06.30.55.NEF.xmp.zip)

**Comment by jenshannoschwalm** [comment] 2023-12-19 04:42
I checked and the **shape opacity was at 40%** using your xmp and changing that to 100% would be probably what you want. I agree that this is not obvious on first sight as you have to open the mask manager but clearly not a bug.

Feel free to open an new issue
1. here about user experience with visibility of that setting
2. maybe in the docs github if you think the manual is not good/precise enough.

Closing this now as the title and discussion leads to confusion.

**Closed by jenshannoschwalm** 2023-12-19 04:42 UTC
Labels: scope: image processing, OpenCL

**Comment by paolobenve** [comment] 2023-12-21 00:05
I don't understand where the opacity was at 40%.... The sliders showed opacity 100%!

**Comment by jenshannoschwalm** [comment] 2023-12-21 05:54
The slider you showed is the **overall** opacity of the masks blending. A shape has it's own opacity, that's shown in the mask manager as told above.
![Bildschirmfoto vom 2023-12-19 05-14-11](https://github.com/darktable-org/darktable/assets/50982232/65c65a8a-e072-4067-8959-0d00b93939c1)

**Comment by paolobenve** [comment] 2023-12-21 14:44
Ok, but cannot I change it?

**Comment by jenshannoschwalm** [comment] 2023-12-21 17:01
Of course you can :-) You have tooltips and manual :-)
