### ISSUE TITLE
Darktable 3.4 crashes on import

### ISSUE THREAD

**Issue by lsdphoto-git** [darktable-org/darktable#8060] opened 2021-02-01 15:23 UTC
I have set DT 3.4 official release running a recursive import from a folder with many sub-folders. Whilst this was in progress, under Collect Images, I tried to switch from ‘film roll’ to ‘camera’, thinking I could start to see the images from each camera as they were being loaded. At this point DT crashed.

I am on a McBook Pro running macOS 10.15.7

I attach a terminal dump and Mac crash report.

[Terminal.txt](https://github.com/darktable-org/darktable/files/5904759/Terminal.txt)
[CrashReport.txt](https://github.com/darktable-org/darktable/files/5904769/CrashReport.txt)

**Comment by Nilvus** [comment] 2021-02-06 09:27
Seems to be a duplicate of #7720. Some things have already been fixed on this side and will be fixed so in 3.4.1, which should be released today. I close this issue so. Feel free to reopen it if you reproduce the crash with 3.4.1. Be careful before that it's not related to some corrupted files (xmp essentially) by testing on some different folders/image and be sure that you reproduce.

**Closed by Nilvus** 2021-02-06 09:27 UTC
Labels: bug: fixed
