### ISSUE TITLE
SONY ILCE-7RM4A

### ISSUE THREAD

**Issue by bobek321** [darktable-org/darktable#9796] opened 2021-08-11 15:50 UTC
Hello,

I would be happy if Sony A7rIVa could be supported in Darktable that I use for over 3 years now. And love it. I uploaded one raw file at raw.pixls.us  - please let me know if you need any more samples.

Thanks, Aleksander

**Comment by kmilos** [comment] 2021-08-11 16:05
Duplicate of https://github.com/darktable-org/darktable/issues/9751

**Comment by LebedevRI** [comment] 2021-08-11 19:23
Duplicate of #9751

**Closed by LebedevRI** 2021-08-11 19:23 UTC
Labels: scope: camera support
