### ISSUE TITLE
File operations act on less files than confirmation dialog states

### ISSUE THREAD

**Issue by matz-e** [darktable-org/darktable#3154] opened 2019-10-14 18:29 UTC
**Describe the bug**
When, e.g., moving a group of files to the trash, the confirmation dialog asks to confirm the trashing the whole group, but deletes only the representative image of the group.

**To Reproduce**
1. Import a directory with, i.e., both CR2 and JPG images with the same filename stub
2. Ensure that images are grouped
3. Select one group in the lighttable
4. Note that the hint in the top center states "2 images of X in current collection are selected"
5. From the "Selected image[s]" operations, select "trash"
6. Accept the confirmation dialog "do you really want to send 2 selected images to trash?"
7. Note that only 1 image disappeared from the collection

Similar behavior present for other operations, e.g., copy.

**Expected behavior**
Both files of the group to be trashed just as the confirmation dialog asks

**Screenshots**
Sorry, don't have any screenshots right now.

**Platform (please complete the following information):**
 - OS: Fedora 30
 - Version latest master

**Additional context**
I looked through the source for this and found the corresponding queries where the confirmation dialog just selects `main.selected_images`, and the actual control job gets a different selection passed (mainly selecting the top image of the groups, there's another query already created skipping this step). I can attempt a PR since I use file management a lot on grouped images, but I'm quite new to the code base, and side effects to changes here are a little hard to gauge…

**Comment by dterrahe** [comment] 2020-01-08 20:20
I've been looking at this but I'm not confident that I understand exactly what the intended purpose of all the considerable complexity in the several layers of calls is. As @matz-e describes; the way the number of selected images is calculated is very straightforward; it just counts main.selected_images. But the collection passed to the actual control job is based on darktable.collection with several joins leading to just the group leaders being selected.

@TurboGit you seem to be one of last to touch dt_collection_get. Should it possibly just be called with different parameters?

**Comment by scorpi11** [comment] 2020-01-28 19:51
I'd be happy if this regression can be fixed in 3.0.1.

**Comment by jneer** [comment] 2020-02-07 22:41
Same for e.g. moving grouped images to different folder. 
Indeed, this used to work. This bug makes it a hassle to do a culling-trashing-moving workflow in Darktable with RAW+JPEG.

**Comment by matz-e** [comment] 2020-03-14 10:41
> This issue did not get any activity in the past 30 days and will be closed in 7 days if no update occurs. Please check if the master branch has fixed it since then.

Just compiled current `master`, still present.

**Comment by scorpi11** [comment] 2020-04-20 21:50
If someone is interested in debugging this, here is the resulting SQL query from dt_collection_get():

SELECT id FROM main.selected_images AS s JOIN (
    SELECT DISTINCT mi.id FROM images AS mi WHERE   (flags & 256) != 256  AND  (
        1=1 AND (
            film_id IN (
                SELECT id FROM main.film_rolls WHERE folder LIKE '/home/foo/darktable/2020/04/bar'
                OR folder LIKE '/home/foo/darktable/2020/04/bar/%'
            )
        )
    )
    AND (
        group_id = -1 OR id IN (
            SELECT id FROM (
                SELECT id, MIN(
                    ABS(id-group_id)*2 + CASE WHEN (id-group_id) < 0 THEN 1 ELSE 0 END
                )
                FROM main.images WHERE   (flags & 256) != 256  AND  (
                    1=1 AND (
                        film_id IN (
                            SELECT id FROM main.film_rolls WHERE folder LIKE '/home/foo/darktable/2020/04/bar'
                            OR folder LIKE '/home/foo/darktable/2020/04/bar/%'
                        )
                    )
                )
                GROUP BY group_id
            )
        )
    )
    OR (id = -1) ORDER BY filename, filename , version LIMIT ?1, ?2
)

**Comment by scorpi11** [comment] 2020-04-20 22:02
"SELECT * FROM main.selected_images" gives the correct result: the two desired IDs when a one group of two images is selected the the lighttable and grouping is enabled.

**Comment by scorpi11** [comment] 2020-04-21 09:49
This change fixes this issue for file operations in the lighttable when grouping is enabled. However, I have no idea if it has any bad side effects.
```

--- a/src/common/collection.c
+++ b/src/common/collection.c
@@ -820,7 +820,7 @@ uint32_t dt_collection_get_selected_count(const dt_collection_t *collection)
 GList *dt_collection_get(const dt_collection_t *collection, int limit, gboolean selected)
 {
   GList *list = NULL;
-  const gchar *query = dt_collection_get_query(collection);
+  const gchar *query = dt_collection_get_query_no_group(collection);
   if(query)
   {
     sqlite3_stmt *stmt = NULL;

```

**Comment by scorpi11** [comment] 2020-04-21 10:46
For consistent behaviour between UI dialogs and the actual operation, I think it's also a good idea to get the number of images from the same list of images that is used by the resulting job.

This is an example for dt_control_remove_images():

```
diff --git a/src/control/jobs/control_jobs.c b/src/control/jobs/control_jobs.c
index da645463d..064bb2556 100644
--- a/src/control/jobs/control_jobs.c
+++ b/src/control/jobs/control_jobs.c
@@ -1427,12 +1427,14 @@ gboolean dt_control_remove_images()
       dt_control_job_dispose(job);
       return TRUE;
     }
+    dt_control_image_enumerator_t *params = (dt_control_image_enumerator_t *)dt_control_job_get_params(job);
+    int count = g_list_length(params->index);
 
     dialog = gtk_message_dialog_new(
         GTK_WINDOW(win), GTK_DIALOG_DESTROY_WITH_PARENT, GTK_MESSAGE_QUESTION, GTK_BUTTONS_YES_NO,
         ngettext("do you really want to remove %d selected image from the collection?",
-                 "do you really want to remove %d selected images from the collection?", number),
-        number);
+                 "do you really want to remove %d selected images from the collection?", count),
+        count);
 #ifdef GDK_WINDOWING_QUARTZ
     dt_osx_disallow_fullscreen(dialog);
 #endif

```

**Comment by scorpi11** [comment] 2020-04-21 11:08
@TurboGit Any comments for the above changes? This issue seems to be introduced with commit 4d701428feb9211960d413e4c41d883d5158ac05.

The code in control/jobs/control_jobs.c wasn't touched for some years.

**Closed** 2020-04-22 07:56 UTC
Labels: no-issue-activity
