### ISSUE TITLE
improve File-Selection dialogue

### ISSUE THREAD

**Issue by Macchiato17** [darktable-org/darktable#7220] opened 2020-12-06 14:38 UTC
In my Windows 10 based darktable workflow, I start my work by importing an album-directory for RAW processing. My album-folders are stored in a NAS based directory and are typically named starting with the album date. Currently I have about 1000 folders here. After clicking on the root folder in the file-open dialogue, I need to wait quite some time until I'm able to select the desired folder for import.

**Desired solution**
I think of two independent improvements here: 
1. use a faster function to get the directory contents from the network drive. This should be a realistic option from my understanding, since opening the folder with Windows Explorer and display the 1000 sub-folder items takes about 1s, in darktable it takes 40s after clicking the "folder..." button.
2. Allow to paste a target folder path directly into the path selection like Windows Explorer allows the user to do. This would allow for direct selection of the target folder without the need of browsing from the top folder.

**Additional context**
Windows 10 professional 64 Bit / NAS based album folder / WiFi based network (Wi-Fi 5 (802.11ac) at ~500Mbit/s with low latency of 1-2ms)

**Comment by johnny-bit** [comment] 2020-12-06 16:05
This is GTK problem, not darktable's one, so please close this issue. Test if same problem happens with other gtk based apps (like gimp) and windows apps that use similar open dialog. Then file issue against gtk.

To enter location press ctrl+L on dialog and it shoudl allow you to enter location.

**Comment by Macchiato17** [comment] 2020-12-06 16:44
Thanks for your prompt reply. CTRL+L is a good hint :-). Gimp needs the same time as darktable to display the folder. So I close this issue here.

**Comment by Macchiato17** [comment] 2020-12-06 19:29
Hi johnny-bit,

I just got an answer from the GTK platform, which might perhaps be some information, which might be interesting, assuming this information being new to you ;-)

> Applications using GTK3 can already use GtkFileChooserNative to display the platform's native file selection dialog. Applications using GTK2 should consider porting to GTK3, given that GTK2 is going to be frozen once GTK 4.0 is out. From our perspective, this solves the problem.

Please feel free to close this issue, if this information was not really of any interest ;-)

Cheers and best regards,
Lars.

**Comment by johnny-bit** [comment] 2020-12-06 19:55
Can you link the issue you've created? darktable is already a gtk3 application, not gtk2. additionally darktable uses GtkFileChooserDialog to embed certain widgets in it for purpose of specifying import metadata (which is impossible with native file chooser). I still belive that performance issue is on gtk not on darktable as darktable uses provided api according to recommendations.

**Comment by Macchiato17** [comment] 2020-12-06 20:46
Sure, here's the link to the GTK issue: [https://gitlab.gnome.org/GNOME/gtk/-/issues/3453](url)

**Comment by johnny-bit** [comment] 2020-12-07 13:12
@Macchiato17 - there's some issue with this link. Clicking on it leads to weirdo-github-place instead of gnome's gitlab.

Also - as explained in that ticket it's not in scope of darktable to do anything to file select dialog, as we can't use native dialog, so the necessary speedup is to be done on gtk/gio side and thus this ticket should be IMO closed.

**Comment by parafin** [comment] 2020-12-07 13:16
I've fixed the link in @Macchiato17 post. I guess GTK folks aren't very interested in fixing non-native file selection dialog.

**Comment by johnny-bit** [comment] 2020-12-15 17:38
Well, this is an upstream issue. However in order to be compliant with GTK4 we'll have to redesign import dialog since gtk4 doesn't support adding widgets inside open dialog...

I'd say this now is "solved + works as intended" on darktable side and "upstream" on GTK/GIO side. GTK4 compatibility can be tackled in separate project/issues once GTK4 is released and I guess that GTK4 migration will be loads of work... so closing for now. @Macchiato17 - feel free to open new issue targeting migration of open dialog to something gtk4 compatible and proposing some alternative flow for import metadata :)

**Closed by johnny-bit** 2020-12-15 17:38 UTC
Labels: bug: upstream, feature: redesign
