### ISSUE TITLE
Issues with before/after view using snapshots

### ISSUE THREAD

**Issue by mlales** [darktable-org/darktable#3079] opened 2019-10-05 09:49 UTC
**Describe the bug**
Strange behavor of before/after view

**To Reproduce**
To reproduce the first issue:

 - I created before/after view using Snapshots and History (see Example1).
 - I noticed that zoom works only on active (after) but not on snapshot 
   (before) side (see Example2).
   Before/after comparisons really make sense when both sides are 
   viewed at the same zoom level.
   Therefore both sides should zoom in/zoom out simultaneously.

Now the second issue:

 - I collapsed left side panel to enlarge center area.
   When changing between vertical and horizontal split view
   (rotating with icon) the center area becomes weirdly "sliced"
   (see Example3, Example4, Example5).
   It seems this issue is limited to situations when at least one of
   the side panels is collapsed.
   When both panels are expanded it works OK.

**Expected behavior**
- Correctly display before/after view when changing horizontal/vertical split view
- Both sides (before/after) should zoom in/zoom out simultaneously

**Screenshots**
Example1:
![Example1](https://user-images.githubusercontent.com/56188259/66253210-f8e4c980-e764-11e9-88d5-7b50837614fc.JPG)
Example2:
![Example2](https://user-images.githubusercontent.com/56188259/66253211-fbdfba00-e764-11e9-8a3d-4c1e561e9f4f.JPG)
Example3:
![Example3](https://user-images.githubusercontent.com/56188259/66253213-013d0480-e765-11e9-9e0f-32b916500698.JPG)
Example4:
![Example4](https://user-images.githubusercontent.com/56188259/66253214-0306c800-e765-11e9-9a1a-df44977104d8.JPG)
Example5:
![Example5](https://user-images.githubusercontent.com/56188259/66253215-08641280-e765-11e9-813c-32ab8e90b968.JPG)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 2.7.0 (Screenshots are from 2.4.0, but problems still persist in 2.7.0)

**Additional context**
I originally posted this on Redmine/darktable bug tracker on 17th January 2018 (issue #11942)
Here is my correspondence with developers to provide you some additional info about these issues:

Issue #11942 has been updated by Peter Budai.

Confirmed, its very easy to repro.

Issue #11942 has been updated by Peter Budai.

I have done further research on this:
* The problem is not specific to Windows, all platforms are impacted
* There is indeed a bug, namely that the snapshot image is not rendered properly if _any_ of the sidepanels are changing their position after the snapshot was taken. So If you take a snapshot, then hide the left panel or the top panel (or any other), the snapshot will be rendered at the wrong coordinates. I have a solution for that (although still not perfect), PR will come shortly
* The other reported problem is with the situation when *after* the snapshot has been taken, the user changes the zoom. This is more controversial, and I'm not convinced that it's a bug. Let me explain: when the snapshot is taken, it takes into consideration the zoom factor. It is not documented, but if you zoom in first and then take a snapshot, this zoomed in picture will be used as your reference/overlay for comparison. If you change the zoom factor *after* you have taken the snapshot, that only affects the currently selected active image, but *NOT* the snapshot. I see here a few options:
** We need to document that the snapshot takes into account the zoom, and snapshot picture is not zoomable. Also we might document that if you want to compare image snapshots in a zoomed-in fashion, you need to take a snapshot of a zoomed in image, and not change the oom factor after that
** We might disable the zooming while snapshot is active, in order not to confuse users

Issue #11942 has been updated by Tobias Ellinghaus.

It's actually quite simple: snapshots are just screenshots. Anything you do to your view (zooming, panning, ...) won't affect the snapshot. There was some work once to make snapshots more powerful by storing history, source image, ... and reprocess it when needed, but that never got anywhere. It's still the right thing to do I think.

Issue #11942 has been updated by Peter Budai.

houz, right. I have managed to adjust the position of the snapshot for left or right panel hide/unhide, but as soon as you hide/unhide the top row or the filmstip at bottom, the current active image is rescaled, but the snapshot can be rescaled as it is a simple cairo surface.

Shall we make at least the change to work with sidepanel hide/unhide alone, knowing that top row and filmstrip changes won't work?

Issue #11942 has been updated by Tobias Ellinghaus.

Depending on aspect ratio of the image and zoom level the top/bottom panels should have the same effect as the left/right ones.

Thank you !

**Comment by AxelG-DE** [comment] 2019-10-05 13:43
As Tobias, @houz said (in your conversation protocol), this snapshot currently is merely a screenshot. So from that it behaves as "expected". Yes, the "before-part" moves, if you collapse side panels but the result is not what you might intend. Currently the best is to zoom before and snapshot by than.

I agree, the dream-case would be, the moment you snapshot, a separate .xmp will be generated and displayed, but that means you would render two complete raw pics. If that is, what everybody wants, I don't know :-)

**Comment by TurboGit** [comment] 2019-10-05 16:19
Indeed, not a bug. Closing. Maybe at some point we we'll have a live snapshot but not for next release for sure.

**Closed by TurboGit** 2019-10-05 16:19 UTC
