### ISSUE TITLE
Remove Haze does not work for certain images

### ISSUE THREAD

**Issue by bes1002t** [darktable-org/darktable#16746] opened 2024-05-06 21:15 UTC
### Describe the bug

When using feature "haze removal" I will see expected changes in most of my images. However in some images nothing happens when I move the slider to the very right side. Also moving it back to the very left side does not have any effect.

For some of the affected images (I know sounds fuzzy, but that's how it is), activating "chromatic abberations" function will fix the haze removal issue and I can then see the effect of "haze removal". 

In #2175 this issue is already described but was not reproducable.
Hope it will help if I attach one of the affected raws here.

https://drive.google.com/file/d/1Nb413hb8lf5EdHxz-9l2sdvbv7gmcVuo/view?usp=sharing

Note: currently it seems the upload does not work? The automatically inserted link just refers to the ticket itself and not to the file. I will retry tomorrow and provide information via cloud solution in worst case.

### Steps to reproduce

1. open an affected image
2. activate "haze removal"
3. nothing happens

### Expected behavior

apply the haze removal to the image

### Logfile | Screenshot | Screencast

https://drive.google.com/file/d/1YHm4yy3J9eacb5x-70iDxjXMEOdQgv-o/view?usp=sharing

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Describe your system?

- 16GB RAM
- Cinnamon Desktop Environment
- X11
- Nvidia driver from rpmfusion

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by jenshannoschwalm** [comment] 2024-06-12 05:07
First, i could not reproduce yet - on current master.

hazeremoval is in some ways a bit "difficult", the has-no-effect issue could be related to a number of problems as it a) possibly takes data from the preview pipe and b) there have been some issues with the guided filter that might be fixed in darktable master. To investigate this issue we would require a fresh log while having your issue done by using  `darktable -d pipe` using either current master or 4.8 after that arrives in the repo.

**Comment by ralfbrown** [comment] 2024-11-10 06:14
@bes1002t If you are able to run one of the available nightly or weekly builds, please test your problematic images with a current development version of darktable.  17650 is likely to have fixed the problem.

**Comment by ralfbrown** [comment] 2024-12-07 22:41
Feel free to re-open if current master or the upcoming 5.0 release shows this issue.

**Closed by ralfbrown** 2024-12-07 22:41 UTC
Labels: understood: unclear, scope: image processing

**Comment by bes1002t** [comment] 2025-03-29 13:22
Sorry for being quiet for so long. Waited for a new Darktable version and then lost track of this issue.  However, I ran into that issue again with Darktable 5.0.1 on Fedora 40.

I've uploaded the new image (raw and darktable files as well) to google drive:
[drive.go](https://drive.google.com/file/d/1c0roEnalgE8yJ4GU3MVwc2SFzBKRwxp9/view?usp=sharing)

Additionally I've added the debug log as @jenshannoschwalm suggested.
[haze_removal_debug.txt](https://github.com/user-attachments/files/19521286/haze_removal_debug.txt)

Unfortunately I do not have permissions to reopen the issue. However, comments are possible. 
Would be great if one of you could have a look into that issue.

**Comment by ralfbrown** [comment] 2025-03-29 15:19
Continued in #18501.  See also #18458.

**Comment by bes1002t** [comment] 2025-03-29 15:47
thanks for pointing this out. I added a comment to the other ticket, so everyone has the example data in this ticket as well. :)

**Comment by bes1002t** [comment] 2025-03-29 15:50
I read the ticket description of https://github.com/darktable-org/darktable/pull/18458, but this is quite different. The ticket is about an issue that came in with Darktable 5.0.1.

The issue I'm describing is in Darktable for a while. So the root cause might be different. What do you think? Should I explain my issue in https://github.com/darktable-org/darktable/pull/18458 again, or is it worth to open this ticket here again?

**Comment by bes1002t** [comment] 2025-03-29 17:06
I read the ticket description of https://github.com/darktable-org/darktable/issues/18501, but this is quite different. The ticket is about an issue that slows down Darktable if haze removal is used and it came in with Darktable 5.0.1.

The issue I'm describing is in Darktable for a while. So the root cause might be different. What do you think? Should I explain my issue in https://github.com/darktable-org/darktable/issues/18501 again, or is it worth to open this ticket here again?

**Comment by jenshannoschwalm** [comment] 2025-03-29 17:29
Don't use google drive at all ...

**Comment by bes1002t** [comment] 2025-03-29 17:51
Since Github does not allow this upload (most likely because of the size), is there any other service you prefer? :)

**Comment by jenshannoschwalm** [comment] 2025-03-29 18:05
Anything i don't have to register and using https

**Comment by ralfbrown** [comment] 2025-03-29 18:58
The slowdown was caused by the fix in 18458, which was needed to deal with downsampled images being processed differently from full-size images -- and that's likely the underlying cause for what you reported.

**Comment by bes1002t** [comment] 2025-03-30 00:46
> Anything i don't have to register and using https

https://limewire.com/d/rd2xG#gc4ziJZsXI
Maybe this works better than google drive.

**Comment by jenshannoschwalm** [comment] 2025-03-30 16:39
Yes, i got you monkey image. Exactly as i thought. Also all parts of the image that would account for ambient light are burnt-out (see highlight reconstruction stepping in) Not an issue for me.

**Comment by ralfbrown** [comment] 2025-03-30 17:40
Could we add a message to the module's UI when this is the case?
(I've never encountered the "doesn't work" situation because I only use the module when I'm trying to reduce the effects of actual haze.)

**Comment by jenshannoschwalm** [comment] 2025-03-30 17:52
I guess we could check for *relevant* calculated distance_max and the AO coefficients?

**Comment by bes1002t** [comment] 2025-03-30 17:57
I see, thanks for clarification! Yes I might use the module for the wrong purpose, but it works quiet well for this purpose in 90% of the cases. :P

**Comment by victoryforce** [comment] 2025-03-30 19:12
> It's a common misconception that this module increases local contrast (although many users seem to use it this way). The main idea is about calculation of ambient light and correcting for a calculated distance. In some/many images the data for ambient light are below a threshold value so it seems "the sliders don't work".

@elstoc @jenshannoschwalm 
What do you think, would it make sense to add such an explanation to the module description in the user manual?

**Comment by jenshannoschwalm** [comment] 2025-03-31 05:33
@ralfbrown after checking the code and some testing (added -d verbose logs about ambient light in #18632) it seems to me, we could check for `distance_max < 0)` as "there is no ambient light" and possibly do a control log or even a module header warning?
