### ISSUE TITLE
Vectorscope doen't fit in display area...Can it be rescaled??

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#8813] opened 2021-04-29 05:24 UTC
Running DT in windows the vectorscope display does not seem to display pane in the UI. Also restricting the scope to selection only works initially and it resets on any subsequent action performed in the UI so you can't select a region display in vectorscope and retain that and then try to make an edit using the vectorscope as a guide...

![image](https://user-images.githubusercontent.com/44409419/116505727-a9f00f00-a889-11eb-986c-7805578bf3c3.png)

**Comment by MStraeten** [comment] 2021-04-29 18:55
thats no bug, thats works as designed (at least for initial merge see https://github.com/darktable-org/darktable/pull/8005#issuecomment-825846223)
A demand for manual scaling, pan and scale etc. is known.
The vectorscope was merged to get more broad user feedback on the demands.
So better tag this as feature request ...

**Comment by todd-prior** [comment] 2021-04-29 19:00
Well at least for me its not much good if I can locate the primary color nodes as they are all off screen. If you want to adjust the hue to align or relative to these reference points you need to be able to see them no??

**Comment by MStraeten** [comment] 2021-04-29 19:14
if you have a look at #8005 there are some ideas on some related functions:
- ctrl+scroll to increase decrease the vectorscope/histogram (as is and also implemented for several graph areas in modules)
- shift+scroll to scale (it's shift double-finger-drag on my trackpad; i'm pretty sure other os have similar gestures for scrolling) maybe also shift+drag
- click+drag to move center (quite common, dragging around mask forms is possible this way with a trackpad on my macbook)
- doubleclick to reset to centered full range

The present implementation is known and done intentionally - so it’s more valuable to specify a requirement

**Comment by todd-prior** [comment] 2021-04-29 19:59
If you crop the primary row from a color picker you should get a vector scope with 6 arms. You should be able to manipulate the hue angle of these in reference to the anchor points....if you can see them....

**Comment by todd-prior** [comment] 2021-04-29 20:22
Most of those don’t work with my mouse on Windows anyway. Only ctrl scroll and its not much help. Another problem is now with my big monitor the histogram is tucked up in the corner way off to the side and its small. I have to either move my head or look at it almost from an angle…some day having the ability to position the scopes/histogram on the screen will be nice. But as it stands now I can’t get the whole vectorscope displayed and I’m not sure why that would be the default. It would seem you would default to show it all and allow people to zoom in if they wanted…maybe leverage the zoom controls by depressing the center mouse button as you do when you cycle between 100 200 and fit for the image display??

I’m not complaining just reporting how its working for me at the moment….

Thx for your feedback….

**Comment by difrkaguilar** [comment] 2021-04-30 06:50
Hello.
Really I don't know if this graph help in this issue, but I send the .svg just in case, modifications can be made.
I designed this graph similar to the vectorscope of Assimilate Scratch software, in a 1x1 box.

An option could be "Fit to area" or other scale the area to 1x1 maybe.

![vectorscope_02](https://user-images.githubusercontent.com/67672868/116656844-6239b800-a95b-11eb-96de-096a3975888d.png)

[Vectorscope_02.zip](https://github.com/darktable-org/darktable/files/6403323/Vectorscope_02.zip)

> some day having the ability to position the scopes/histogram on the screen will be nice.

By the way Assimilator Scratch have this floating panel over the canvas.

**Comment by todd-prior** [comment] 2021-05-02 02:53
@elstoc  I see you removed the bug tag. I did conflate two issues in the post. The scaling may be pending and and enhancement but I think my second issue ie the integration of restricting the scopes to the selection is not working correctly. Initially if you make a selection on any part of the image the scopes change to reflect that but you cannot make any change or adjustment based on this. The moment you go to a module to make any adjustment or change the scope is reset to the full image even though restrict to selection is still active in the picker dialogue. I would think that reason to have this would be to be able to base the display in the scope on a selected area of the image and make some adjustments that would be reflected by that....I am not sure ....so if not a bug then it seems an odd way that it is working and or it should be revisited....

**Comment by MStraeten** [comment] 2021-05-02 05:37
a bug is an unintended behaviour. The current implementation (just autoscaling) is an intended behaviour. (https://github.com/darktable-org/darktable/pull/8005/commits/3be638d68514f7fc82d6cca74479e347dc4842bb)
Full display and also manual scaling was available and explicitly removed to get this into the broad publicity and receive further requirements. So no bug but feature request.

Theres already a issue report on restriction of the histogram to color picker selection: https://github.com/darktable-org/darktable/issues/8680 so no need to have this here since this is not specific to vectorscope implementation.

**Comment by todd-prior** [comment] 2021-05-02 22:25
Thanks I hadn't seen 8680.......

**Comment by dtorop** [comment] 2021-05-03 04:19
Seeing this now. I will work on scaling, as suggested by https://github.com/darktable-org/darktable/pull/8005#issuecomment-825773266. There's certainly more work to be done...

I think that the current "hue ring" obviates a graticule overlay with known primaries/secondaries, as in https://github.com/darktable-org/darktable/issues/8813#issuecomment-829882246, but need to think this out more. At one point the hue ring had nodes on it a primaries/secondaries, but I eliminated those as a visual distraction. The primaries/secondaries should still be visible as sharp angles in the hue ring, but it would also be possible to put the nodes back in.

I've been imagining vectorscope as a tool for visualizing color balancing and such. The autoscaling setup may be particularly less useful for colorcheckers...

**Comment by difrkaguilar** [comment] 2021-05-03 05:17
This is another version of the same vectorscope but with some changes. As usual I left the .svg It was designed with inkscape.

![vectorscope_v01a](https://user-images.githubusercontent.com/67672868/116843189-285ff000-abad-11eb-99f8-49647d69d1ea.png)

![vectorscope_v01b](https://user-images.githubusercontent.com/67672868/116843193-2d24a400-abad-11eb-85ba-576bb439579f.png)

[Vectorscope_01.zip](https://github.com/darktable-org/darktable/files/6412958/Vectorscope_01.zip)

**Comment by todd-prior** [comment] 2021-05-03 19:18
> I've been imagining vectorscope as a tool for visualizing color balancing and such. The autoscaling setup may be particularly less useful for colorcheckers...

The main uses that I am aware of for a vectorscope include assessing the WB, saturation and hue components of the color in an image. To me if you were unable to see the hue ring and the sharp angles or intersections that define the primary colors you would not be able to make any accurate reference to those last two parameters. Finally again if you can't see the entire hue ring also it would be hard to gauge saturation in the traditional way normally defined in a vectorscope. Perhaps I am just way off base in my thinking.

**Comment by difrkaguilar** [comment] 2021-05-04 02:22
Could be something like this?
![vectorscope_03](https://user-images.githubusercontent.com/67672868/116954325-b5fb1880-ac5d-11eb-9100-5b1c5c3fb14c.png)

![vectorscope_04](https://user-images.githubusercontent.com/67672868/116954344-c3b09e00-ac5d-11eb-8e3e-12eff14e9177.png)

.svg
[Vectorscope_03.zip](https://github.com/darktable-org/darktable/files/6418754/Vectorscope_03.zip)

**Closed** 2021-05-09 09:27 UTC
Labels: feature: new, scope: UI
