### ISSUE TITLE
Darkroom view image back and image forward shortcut keys

### ISSUE THREAD

**Issue by eyedear** [darktable-org/darktable#5425] opened 2020-06-12 11:34 UTC
Currently the Darkroom View Image Back and Image Forward is assign to backspace and space bar. i have tried to change to left arrow and right arrow. the preference page allow you to change it but after closing the preference the left and right arrow key does not do anything. Is this a bug or am i doing something wrong

**Comment by elstoc** [comment] 2020-06-12 13:16
This is a duplicate of https://github.com/darktable-org/darktable/issues/5011. The arrow keys are hard-coded as shortcuts in the darkroom view for panning around a zoomed image.

**Closed** 2020-06-12 13:31 UTC
