### ISSUE TITLE
SONY RX100 M7

### ISSUE THREAD

**Issue by Flyingdishes** [darktable-org/darktable#3783] opened 2019-12-16 16:45 UTC
[DSC00192.zip](https://github.com/darktable-org/darktable/files/3969175/DSC00192.zip)
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by Flyingdishes** [comment] 2019-12-16 16:47
HI,
It seems that ARW drom RX100 M7 (or VII) is not recognized. I joined the ARW file in zip mode as it seems that ARW ypes are not allowed for upload.
Thanks for your kind support.
Flying.

**Comment by LebedevRI** [comment] 2019-12-16 16:48
Duplicate of https://github.com/darktable-org/rawspeed/issues/206
Supported in master for ~2 weeks now, since https://github.com/LebedevRI/darktable/commit/1ec96e4038cca29a5be00f062c7077e220956ea7

**Closed by LebedevRI** 2019-12-16 16:48 UTC
Labels: camera-support
