### ISSUE TITLE
In the Film roll, photos should only get focus after moving the mouse

### ISSUE THREAD

**Issue by m93a** [darktable-org/darktable#2704] opened 2019-06-09 13:31 UTC
## Introduction
In the Darkroom, PgUp and PgDn can be used to navigate between photos and R, 0-5, F1-F5 can be used rate and label them. If one wants to rate or label a different photo without navigating to it, they can just move the mouse over its preview in the Film roll and use R, 0-5, F1-F5 to change its rating, rather than the rating of the Darkroom's active photo. I'm going to call the photo that is active in the Darkroom an *“active photo”* and the photo preview that recieves rating and labels a *“focused photo”*.

![Image illustrating the distinction between active and focused photo](https://user-images.githubusercontent.com/1671665/59159386-309a7800-8ac9-11e9-97a1-35e8ef7a9fef.png)

## The Problem
Most applications which use mouseover to give focus to elements do so only when the mouse moves, not when the UI changes under the cursor. And it's reasonable to do so, because the user *intends* to give focus only when they move their mouse. Other times, when they work with the keyboard, they aren't even aware of the cursor's position, so they would think that the focus is broken and random elements get it.

However that's exactly what happens in darktable. When I forget my cursor on the film roll and use PgUp and PgDn to navigate between photos and try to use R, 0-5, F1-F5 to rate and label them, completely different photos will recieve the rating (ie. those that are currently under the mouse cursor which I'm unaware of). And when the view is set to only show non-rejected photos, rejecting a different photo by accident can mean losing it amongst 100ish photos I rejected earlier. This combined with #2702 leads to a very unpleasant experience.

## The Solution
Photos in the Film roll should only recieve focus when a mouse *moves* over them. When the Film roll UI updates, the active photo should gain focus and keep it until the mouse moves again.

## Platform
 - OS: Ubuntu 18.04.1
 - Version: 2.6.2 (and also 2.7.0~git1423.a63dd508e)

**Comment by m93a** [comment] 2019-06-09 13:46
A closely related but separate problem is that since the UI update in 2.7, previews in the Film roll don't *look* focused unless there's mouse over them. This means that ratings and color labels aren't shown in the Film roll at all unless there's a cursor above it. This renders the hotkeys almost useless because one never knows whether an action was actually made or not.

![Image demonstrating the problem](https://user-images.githubusercontent.com/1671665/59159666-7eb17a80-8acd-11e9-8564-067f664a1c64.png)

**Comment by AlicVB** [comment] 2020-02-02 11:15
I'll try to take care in my in-progress filemanager (and filmstrip) rewrite.
Note that due to the amount of work, this will take time to land in master...

**Comment by m93a** [comment] 2020-03-04 10:21
Shut up already, it's still a bug.

**Comment by Nilvus** [comment] 2020-03-04 18:24
It's not a bug. It's the actual behavior. It's could be changed but not a bug.

**Comment by AlicVB** [comment] 2020-03-21 19:16
closing, now that lighttable rewrite as landed in master

**Closed by AlicVB** 2020-03-21 19:16 UTC
Labels: bug: wip, no-issue-activity
