### ISSUE TITLE
Dumps occur (libdarktable.so)

### ISSUE THREAD

**Issue by waldbaer59** [darktable-org/darktable#14230] opened 2023-04-16 18:41 UTC
### Describe the bug

I am working with Darktable version 4.2.1 on Arch Linux. Developing RAW files of my Pentax K3 mk iii I sporadically experience memory access errors which come from libdarktable.so.

Here is a cutout of some lines in my system log. Note that my Arch Linux systems name is 'ALPHA'; I am using a standard kernel Linux ALPHA 6.2.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 13 Apr 2023 16:59:24 +0000 x86_64 GNU/Linux:

`Apr 16 20:14:18 ALPHA kernel: traps: worker res 1[5979] general protection fault ip:7f313ed73ce3 sp:7f30a7e66ce0 error:0

Apr 16 20:14:18 ALPHA kernel: traps: worker res 1[5982] general protection fault ip:7f313ed73ce3 sp:7f30a6663ce0 error:0

Apr 16 20:14:18 ALPHA kernel:  in libdarktable.so[7f313ec81000+43f000]

Apr 16 20:14:18 ALPHA kernel:  in libdarktable.so[7f313ec81000+43f000]

Apr 16 20:14:18 ALPHA kernel:  in libdarktable.so[7f313ec81000+43f000]

Apr 16 20:14:18 ALPHA kernel: traps: worker res 1[5980] general protection fault ip:7f313ed73ce3 sp:7f30a7665ce0 error:0

Apr 16 20:14:18 ALPHA kernel: traps: worker res 1[5984] general protection fault ip:7f313ed73ce3 sp:7f30a5661ce0 error:0 in libdarktable.so[7f313ec81000+43f000]

Apr 16 20:14:18 ALPHA kernel:  in libdarktable.so[7f313ec81000+43f000]

Apr 16 20:14:18 ALPHA kernel: traps: worker res 1[5978] general protection fault ip:7f313ed73ce3 sp:7f30a8667ce0 error:0

Apr 16 20:14:18 ALPHA kernel: traps: worker res 1[5977] general protection fault ip:7f313ed73ce3 sp:7f30a8e68ce0 error:0

Apr 16 20:14:18 ALPHA kernel:  in libdarktable.so[7f313ec81000+43f000]

Apr 16 20:14:18 ALPHA kernel:  in libdarktable.so[7f313ec81000+43f000]

Apr 16 20:14:18 ALPHA kernel: traps: worker res 1[5976] general protection fault ip:7f313ed73ce3 sp:7f30a9669ce0 error:0 in libdarktable.so[7f313ec81000+43f000]

Apr 16 20:14:18 ALPHA systemd[1]: Started Process Core Dump (PID 6007/UID 0).
`

### Steps to reproduce

This is not simple to replay. It happended quite often when I used the astronomical denoise feature and played with the values.

### Expected behavior

Not experience a memory access error.

### Where did you install darktable from?

distro packaging

### darktable version

4.2.1

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Describe your system?

X11, 

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by Nilvus** [comment] 2023-04-17 17:10
There's already at least 3 recent issues (closed because fixed) related to crash with astro photo denoise. So your issue is probably related to and had been fixed on actual master. Fix will be in future 4.4 release (on june). See especially that issue: #12662 and related fix: #13529

If you can, would be good to test actual master if you reproduce or not. Of course, think about keeping a backup of your .config/darktable folder as updating to master also update database (and there's no possibility to go back in previous release).
If you reproduce on master, please amend a more precise step-by-step. If it's fixed, think about closing that issue.

**Closed** 2023-04-22 14:08 UTC
Labels: duplicate
