### ISSUE TITLE
Film roll disappears from the collection after erase some images.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#11186] opened 2022-02-19 23:20 UTC
**Describe the bug/issue**
Sometimes when I am reviewing images by date that I want to delete from film roll collections, it happens that some film roll disappears from the collection after erase some images.

**To Reproduce**
1. Go to lighttable
2. Click on a film roll in Collections
3. Select an image or a group of images and delete (trash).

**Expected behavior**
When users are working with a film roll in the collections and selecting images for deletion, the list of film roll must keep the same order.

**Screencast**
https://user-images.githubusercontent.com/67672868/154822012-a1f46223-5e6d-4124-bbb1-b1239118fbd2.mp4

**Which commit introduced the error**
Not sure.

**Platform**
darktable version : 3.9.0~git439.a3525ed597-7332.1
OS: Fedora Linux 35 (Workstation Edition) x86_64
OS Type: 64-bit
Host: Gigabyte Technology Co., Ltd. Z390 AORUS MASTER
Kernel: 5.12.17-300.fc34.x86_64
Uptime: 3 hours, 31 mins
Packages: 3032 (rpm), 25 (flatpak)
Shell: zsh 5.8.1
Resolution: 3840x2160
DE: GNOME 41.4
WM: Mutter
WM Theme: Materia-dark-compact
Theme: Mc-OS-Transparent-1.3 [GTK2/3]
Icons: Os-Catalina-icons-master [GTK2/3]
Terminal: gnome-terminal
CPU: Intel® Core™ i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1070
GPU: NVIDIA GeForce GTX 1080 Ti
Nvidia Driver Version: 465.19.01
Memory: 4194MiB / 32036MiB
OpenCL installed: yes
OpenCL activated: yes

**Comment by difrkaguilar** [comment] 2022-02-19 23:29
I don't know if devs are working in collections section, but I assume that yes, because @AlicVB put this in a previous post.

> yep. I fear it's due to the bauhaus size computing. but not sure it's worth the pain to fix this specific now, considering that there will be change in this area soon...

_Originally posted by @AlicVB in https://github.com/darktable-org/darktable/issues/11183#issuecomment-1046058149_

**Comment by MStraeten** [comment] 2022-02-21 12:51
it seems to be a side effect of commit [271a4c1a44da63189a3c8dfcc23f88f5f1cf4872](https://github.com/darktable-org/darktable/pull/11157/commits/86445d57865d0494dc5bb9aaeaab32447c7cebd2) in https://github.com/darktable-org/darktable/pull/11157

After deleting a file the collection list seems to be updated and then instead of just highlighting the selected filmroll the whole list is filtered (a selection ist handled liek applying a filter)
This also occurs after restarting darktable with a selected filmroll

behaviour before the commit:
selecting a filmroll in the list of availabe filmrolls results in a highlighted filmroll within the list of available filmrolls.
This behaviour is identical after updating the collection caused by deleting an image or restarting darktable
after:
selecting a filmroll it in the list of availabe filmrolls results in a highlighted filmroll within the list of available filmrolls.
After updating the collection caused by deleting an image orrestarting darktable the list of filmrolls is filtered - so the filter set by selecting the filroll needs to be delete first before a different filmroll can be selected

thats a quite massive change in the usability, since selecting a filmroll to see the content is quite a different thing from an user experience view than filtering a list of collections

**Comment by Nilvus** [comment] 2022-02-28 11:42
@phweyland: it's seems to be a side effect on a fix you recently proposed. Could you check that?
See also related issue #11237 
Thanks

**Comment by phweyland** [comment] 2022-02-28 20:14
Agreed on the principle. Remains to understand how to achieve this...

**Comment by phweyland** [comment] 2022-03-01 09:43
@TurboGit I've not yet understood everything but I think we should revert [271a4c1a44da63189a3c8dfcc23f88f5f1cf4872](https://github.com/darktable-org/darktable/pull/11157/commits/86445d57865d0494dc5bb9aaeaab32447c7cebd2) as it is breaking something. And reopen  #11149.
Do I have to open a new PR or you do that directly on master ?

**Comment by TurboGit** [comment] 2022-03-01 17:11
@phweyland : Indeed, reproduced I have then reverted 271a4c1a44da63189a3c8dfcc23f88f5f1cf4872.

**Comment by TurboGit** [comment] 2022-03-01 17:11
Issue reopened.

**Comment by TurboGit** [comment] 2022-03-01 17:12
Closing this as now fixed.

**Closed by TurboGit** 2022-03-01 17:12 UTC
Labels: bug: pending
