### ISSUE TITLE
MAP: Cannot remove images from map macOS

### ISSUE THREAD

**Issue by a7hybnj2** [darktable-org/darktable#6098] opened 2020-08-26 09:27 UTC
**Describe the bug**

I dragged 2 images onto the map. After reading [this](https://www.darktable.org/usermanual/en/map_chapter.html) I tried to drag them off back into my filmstrip. They would temporally disappear but changing zoom makes them show back up. I have tried to drag them to other locations and nothing has worked while trying to remove the images. The only bug report I found that may have been applicable was \#6010 but I switched to a single monitor and tried again with the same results.

**To Reproduce**
On macos drag and image to the map. Then try to remove it.

**Expected behavior**
I expect there to be some way to remove an image from the map.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: macOS 10.15.6

**Additional context**

**Comment by a7hybnj2** [comment] 2020-08-26 09:37
Okay, I have more data:

I can remove the images from the map after adding but you first have to quit the and open darktable again. So, adding an image and immediately trying to remove it does not work.  
However, adding an image, quitting darktable, opening darktable, and removing the image does appear to work.

**Comment by Nilvus** [comment] 2021-06-20 12:59
@a7hybnj2: I close this issue as a lot of things have been improved this year in map part. The library behind (libosm-gps-map) had been hugely improved this past months after about 2 years without any update and with lot other things have been improved too in darktable about map view. I suggest you so to wait for 3.6, which will be released in about 2 weeks. You could then test again. If you reproduce on future 3.6, feel free to reopen or ask for it and provide your tests in a new comment.

I'm on Linux and just tested in actual master (future 3.6) and I can't reproduce your issue.

**Closed by Nilvus** 2021-06-20 12:59 UTC
Labels: no-issue-activity
