### ISSUE TITLE
darktable crashes when copy/pasting historystack within darkroom

### ISSUE THREAD

**Issue by andabata** [darktable-org/darktable#13537] opened 2023-02-05 13:49 UTC
When trying to copy/paste the history stack with in darkroom, darktable crashes. 
It doesn't write a logfile. but i captured the following output from the console.

[log.txt](https://github.com/darktable-org/darktable/files/10611168/log.txt)

this is darktable 4.3.0+468~g58970f3-dirty

**Comment by AxelG-DE** [comment] 2023-02-05 13:53
I reproduce it like this:

- open an edited RAW (in my case Nikon D750 NEF)
- duplicate to original
-  go to initial pic and ctrl+c
-  go to original-dupicate and press ctrl-v
- see error

the dumpfile is empty, but a redirected "-d all" gave me:
[20230205_dt-copy-crash.txt](https://github.com/darktable-org/darktable/files/10611174/20230205_dt-copy-crash.txt)

**Comment by wpferguson** [comment] 2023-02-05 18:18
@AxelG-DE that works really well
[console.log.txt](https://github.com/darktable-org/darktable/files/10611808/console.log.txt)

**Comment by TurboGit** [comment] 2023-02-07 14:38
Ok, cannot reproduce but I have a possible fix while reviewing the code around chunk pointed to by @wpferguson.

@wpferguson , @andabata : Can you check if the fix works on your side?

**Comment by TurboGit** [comment] 2023-02-07 18:41
@wpferguson , @andabata : I finally was able to reproduce and my PR was fixing the issue. So merged.

**Closed** 2023-02-07 18:40 UTC
Labels: priority: high, bug: pending

**Comment by wpferguson** [comment] 2023-02-07 20:06
Tested copy/paste and it worked, except it didn't respect the module order module order.

![pasted](https://user-images.githubusercontent.com/1634891/217353385-2bc6a2a6-2821-411b-a8b9-042c576d86c9.jpg)
![copied](https://user-images.githubusercontent.com/1634891/217353388-246202ae-7469-4259-be6e-e0e30c55f6d8.jpg)

@TurboGit don't know if you want to reopen this or I can make it a separate issue

**Comment by TurboGit** [comment] 2023-02-07 21:17
Yes, please open a separate issue I doubt this is new. Can you double check that this is reproducible on 4.2? TIA.
