### ISSUE TITLE
corruption of mask name

### ISSUE THREAD

**Issue by cridemichel** [darktable-org/darktable#13839] opened 2023-03-06 09:26 UTC
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
I created a mask thourgh "mask manager" as shown in the following screenshot:

<img width="270" alt="Screenshot 2023-03-05 alle 09 50 34" src="https://user-images.githubusercontent.com/15322138/223067658-a1a80af5-b702-4ffc-bb6e-ebfca0fb376e.png">

and when I click more than once on the mask named "ellipse #1" I get a corrupted text as shown in the following screenshot:

<img width="272" alt="Screenshot 2023-03-05 alle 09 50 41" src="https://user-images.githubusercontent.com/15322138/223068113-a3314590-c699-4c77-98ee-9a6a6a5ccf55.png">

**Platform**

* darktable version : e.g. 4.3.0+974~gda6754ee3-i386
* OS                :  OSX Ventura 13.2.1
* Linux - Distro    :  NA
* Memory            : 
* Graphics card     : AMD Radeon PRO 5500M + Intel UDH Graphics 630
* Graphics driver   :  1.2 (Feb  8 2023 20:47:03)
* OpenCL installed  : opencl 1.2
* OpenCL activated  : opencl 1.2
* GTK+              : stable 2.24.33
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by TurboGit** [comment] 2023-03-06 09:30
It is not a corrupted text but the current editing text that is not properly overlaid on top the label or more precisely the label which should be hidden when in edit mode. This is a known issue and hopefully will be fixed in 4.4.

**Comment by cridemichel** [comment] 2023-03-06 09:31
thank you for the prompt reply and the clarification!

best Cristiano

Cristiano De Michele
***@***.***

**Comment by zisoft** [comment] 2023-03-06 09:47
Duplicate of #13767

**Closed** 2023-03-06 20:50 UTC
Labels: understood: clear, scope: UI, bug: pending, release notes: pending
