### ISSUE TITLE
Segfault during launch when using recently updated pango-1.48.7 (MSYS2, Windows)

### ISSUE THREAD

**Issue by Thanatomanic** [darktable-org/darktable#9793] opened 2021-08-11 08:29 UTC
**Describe the bug/issue**
Recently MSYS2 updated pango from 1.48.5 to 1.48.7 (see https://github.com/msys2/MINGW-packages/commits/master/mingw-w64-pango). However, building `master` or `darktable-3.6.x` using this latest version causes darktable to segfault during startup. The main window does not even show.

When I restore the previous version of pango dt does not segfault (no rebuild necessary)
`pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-pango-1.48.5-1-any.pkg.tar.zst`

Reinstalling the newer version gives a segfault again
`pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-pango-1.48.7-1-any.pkg.tar.zst`

**Exception log**
[darktable_bt_JGQV70.txt](https://github.com/darktable-org/darktable/files/6966850/darktable_bt_JGQV70.txt)
[gdbus-nonce-file-LBOX70.log](https://github.com/darktable-org/darktable/files/6966857/gdbus-nonce-file-LBOX70.log) (binary file, not sure how useful)

**Gdb stack trace**
[stacktrace.txt](https://github.com/darktable-org/darktable/files/6966914/stacktrace.txt)

So, maybe an upstream issue. Not sure if this causes problems on Linux as well. But good to know for Windows builds anyway, I guess?

**Comment by johnny-bit** [comment] 2021-08-11 09:29
we know:
https://github.com/darktable-org/darktable/issues/9519
https://github.com/darktable-org/darktable/issues/9653

seems like break got introduced in 1.48.6-2

I have 1.48.7-r1 and never experienced issue so my thinking is that it's isolated to windows.
If upstream doesn't have report (be it either msys2 or pango) do you have account on gnome's gitlab to report pango issue?

**Comment by Thanatomanic** [comment] 2021-08-11 09:33
@johnny-bit Sorry for not searching first before reporting, but those issues seem to be closed without actually resolving anything. That's a little confusing. I agree that this should be reported upstream, but this is still an issue for darktable and people that build/package on Windows as well, right?
In any case, I don't have an account for GitLab (yet). I'll see what I can do.

**Comment by Thanatomanic** [comment] 2021-08-11 09:43
@johnny-bit Done: https://gitlab.gnome.org/GNOME/pango/-/issues/592

**Comment by johnny-bit** [comment] 2021-08-11 10:08
Thank you!

The 1st issue was closed but I thought that the person who closed the issue did create an issue report upstream... or maybe considered downgrading pango to be "solution enough". I've closed the 2nd report on the basis of it being duplicate of existing one.

Technically we could close this issue too since there's literally nothing that we can change in darktable to fix the issue. Backtrace points to simple creation of new spinbutton using normal gtk3 controll so I have no idea what else can be done.

Packaging wise - just downgrade pango (so it's upstream in msys2). Code wise - nothing (so it's upstream in pango).

**Comment by Mark-64** [comment] 2021-08-11 11:40
That's odd.
```
$ pacman -Q | grep pango
mingw-w64-x86_64-pango 1.48.7-1
```
I have pango 1.48.7 in my MSYS2 and I don't have the issue, although I had another one (#9745) after the last update.

**Comment by Thanatomanic** [comment] 2021-08-11 12:22
@Mark-64 That is odd indeed, so the issue may not be directly related to pango. What is your version of GTK?
```
$ pacman -Q | grep 'gtk\|pango'
mingw-w64-x86_64-gtk-update-icon-cache 3.24.30-1
mingw-w64-x86_64-gtk3 3.24.30-1
mingw-w64-x86_64-gtkmm3 3.24.5-1
mingw-w64-x86_64-pango 1.48.5-1
mingw-w64-x86_64-pangomm 2.46.1-1
```

**Comment by lb90** [comment] 2021-08-11 12:36
Could it depend on the selected pangocairo backend? See https://gitlab.gnome.org/GNOME/pango/-/blob/main/pango/pangocairo-fontmap.c#L84-92

You can try running with:
* `PANGOCAIRO_BACKEND=win32 darktable`
* `PANGOCAIRO_BACKEND=fontconfig darktable`

**Comment by Mark-64** [comment] 2021-08-11 14:54
both work in my case

**Comment by Mark-64** [comment] 2021-08-11 14:56
maybe it has nothing to do, but can you try to downgrade CMake instead of pango, like explained in #9745 and recompile?

**Comment by Thanatomanic** [comment] 2021-08-11 15:16
For clarity: my starting point is by removing `darktablerc` (config file) from `%LOCALAPPDATA%\darktable`.
Then, `PANGOCAIRO_BACKEND=win32 darktable` leads to a segfault using pango 1.48.7, but using `fontconfig` starts the program normally.

However, I can add something new. If I remove my config file, then run `PANGOCAIRO_BACKEND=fontconfig darktable`, correctly starting the program and then **choose any other theme than 'darktable' or 'darktable-icons'**, darktable can be correctly run afterwards by simply executing `./darktable`. 
So, the segfault can be prevented by something that has to do with the selected theme. @johnny-bit Something in darktable after all?

Oh, it gets even better. When you have another theme selected, run darktable normally and then switch back to either 'darktable-icons' or 'darktable' the program segfaults as well.

**Comment by lb90** [comment] 2021-08-11 15:22
Yes, this depends on the installed fonts and which fonts are used by the theme (or the gtk-font-name setting in /etc/gtk-3.0/settings.ini)

**Comment by lb90** [comment] 2021-08-11 15:23
Here's a fix: https://gitlab.gnome.org/GNOME/pango/-/merge_requests/405

**Comment by johnny-bit** [comment] 2021-08-11 15:41
> So, the segfault can be prevented by something that has to do with the selected theme. @johnny-bit Something in darktable after all?

Nah 😄 it's all pango font handling. 

Looks like @lb90 found the root cause and created a fix 😃

**Comment by johnny-bit** [comment] 2021-08-12 08:12
Since the release with the fix is alredy done and tagged (https://gitlab.gnome.org/GNOME/pango/-/tags/1.48.8) do we close this or wait for msys2 to have the package in repo?

**Comment by kmilos** [comment] 2021-08-12 08:22
[Bumped](https://github.com/msys2/MINGW-packages/pull/9359), should be available in a day or two ;)

**Comment by Mark-64** [comment] 2021-08-23 06:19
I think we can close here, pango has been updated in MSYS and the issue is no longer there

**Closed** 2021-08-23 07:15 UTC
Labels: duplicate, bug: upstream, scope: windows support
