### ISSUE TITLE
New crop module not precise to the pixel

### ISSUE THREAD

**Issue by derpafist** [darktable-org/darktable#10837] opened 2022-01-08 22:03 UTC
I like to crop my pictures to 4K, so that they can be viewed on a TV without scaling. Neither of the two crop modules allows to input the pixel numbers unfortunately, so you have to drag carefully until the desired dimensions are reached. This is easier if you zoom in first. 
The problem is that when you set the size to 3:2 and choose a hight of 2160, the exported image will have an hight of 2159 if you used the new crop module. The old one did not have this issue.

**Comment by spaceChRiS** [comment] 2022-01-09 15:27
This is likely a duplicate of #9738.

However, I wonder why you are setting exact pixel dimensions in the darkroom, as the image contents may hardly fit to the required output pixel size. I would at least suggest that you are cropping based on the output aspect ratio, and let darktable downscale to the required pixel dimensions during export. You have to be exact regarding the aspect ratios if you want to be exact to the pixel, as for some pixel dimensions the “known” aspect ratios are not exact (4096 by 2160 is not exactly 17 by 9). However, in the case of most 4k displays, 3840 by 2160 is exactly 16 by 9. This may not prevent you from the issue mentioned above, but yields imho a much more flexible workflow.

**Comment by derpafist** [comment] 2022-01-20 15:33
@spaceChRiS 
Sorry for replying this late. You are probably right that this is the same issue as in #9738. And you are definitely right, that sometimes it might not be possible to have pixel precise crops with certain aspect ratios. However in this case 2160 is divisible by 2. So an output of 3240x2160 pixels would exactly be 3:2. So the output I get is not 3:2. Maybe the person in #9738 is right and there is a rounding issue in the new crop module. 
Of course I could export with a hight of 2160 however when the crop module outputs a hight of 2159 the export module would have to interpolate. And because 2160 is no multiple of 2159 every single pixel of the output would be based on an interpolation. I am pretty sure this would harm image quality.

**Comment by jenshannoschwalm** [comment] 2023-01-20 17:29
@TurboGit can't close this myself ...

**Comment by TurboGit** [comment] 2023-01-20 18:40
Closed !

**Closed by TurboGit** 2023-01-20 18:40 UTC
Labels: no-issue-activity
