### ISSUE TITLE
Shortcut for toggle landscape portrait in crop module

### ISSUE THREAD

**Issue by ActarusLeGrand** [darktable-org/darktable#14575] opened 2023-05-25 02:51 UTC
At the right of the aspect word in the crop module. There is a cricle, when you left click on it or right click it toggle the crop portrait or landscape. Could you make it so it become a shortcut?

I do a lot of those and having a shortcut key would help a lot, right now I have to go and click on it and go back to the image over and over.

THanks - windows user.

**Comment by MStraeten** [comment] 2023-05-25 17:46
confirmed current master macos (no spiral, no item for the orientation toggle):
![image](https://github.com/darktable-org/darktable/assets/39386816/c17810b5-279e-4354-a0d2-6e85a1b37a9e)

**Comment by dterrahe** [comment] 2023-05-25 18:37
The button is part of the "format" dropdown so can be manipulated by setting the "button" _element_ of a shortcut to it. Visual mapping mode will do that for you. Unless you have tested my instructions above and found they don't work? _That_ would be a bug.

**Comment by dterrahe** [comment] 2023-05-25 18:40
Can you create a shortcut to the "aspect" dropdown and change its _element_ (in the lower halve of the shortcuts dialog) to "button"? Mapping mode should do this for you but I'm away from my development machine at the moment so cannot test why it doesn't work.

**Comment by dterrahe** [comment] 2023-05-25 18:47
Actually, it looks like the mapping mode _would_ work. Spiral or up/down arrow all mean that you can map a shortcut (just press the key you want to assign while hovering over the button) but arrow up/down _also_ means you can add it remove to/from quick access panel. Unless you have tried mapping a key (not press the mouse button; the tooltip explains that will open the shortcuts dialog) and it doesn't work; that would be a bug that I could investigate when I get home.

**Comment by ralfbrown** [comment] 2023-05-28 19:49
It does work as described for a recent master (4.3.0+2362).  When pressing the key combination to be assigned, you need to be hovering on the circular arrow rather than the word Aspect or the description of the aspect ratio -- if you're on either of those, the key gets assigned to the aspect ratio selection.

There is a possible very minor UI glitch once shortcuts are assigned.  While hovering over the "switch orientation" icon, the tooltip shows shortcuts assigned **both** to toggle orientation and select aspect ratio, and when hovering over the rest of the widget, the tooltip which is displayed shows only the shortcuts assigned to selecting the aspect ratio.

**Comment by dterrahe** [comment] 2023-05-28 21:34
> While hovering over the \"switch orientation\" icon, the tooltip shows shortcuts assigned both to toggle orientation and select aspect ratio, and when hovering over the rest of the widget, the tooltip which is displayed shows only the shortcuts assigned to selecting the aspect ratio.

This is intentional. With fallbacks enabled, a shortcut assigned to a combo (or slider) that has a "quad" button, like this orientation icon or a colour picker, can be extended with a left click to toggle that button. A shortcut specifically assigned to the button can not be extended to affect a different part of the widget.

**Comment by ActarusLeGrand** [comment] 2023-05-29 03:34
Thanks. It does record even when an arrow show, But ya the tooltip does not register the name of the tool and it's shortcut. I think it should show a spiral.

**Comment by dterrahe** [comment] 2023-06-02 01:00
I completely agree with you; the current cursors were only ever intended as placeholders. If you have the artistic skills that I lack, feel free to propose better mouse cursors as requested in #9483.

**Comment by dterrahe** [comment] 2023-06-03 17:19
duplicate of #9483

**Closed by dterrahe** 2023-06-03 17:19 UTC
