### ISSUE TITLE
Fujifilm X-T3: Incorrect color rendition

### ISSUE THREAD

**Issue by wilecoyote2015** [darktable-org/darktable#10413] opened 2021-11-14 21:23 UTC
**Describe the bug/issue**
In comparison to the other Cameras I am using with darktable (X-T10, X-E3, Nikon D40), the input profile for the X-T3 seems wrong: Colors are muted and a greenish color cast exists.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to the [Dpreview comparison tool](https://www.dpreview.com/reviews/image-comparison?attr18=daylight&attr13_0=fujifilm_xt3&attr13_1=fujifilm_xt10&attr13_2=apple_iphonex&attr13_3=apple_iphonex&attr15_0=raw&attr15_1=raw&attr15_2=jpeg&attr15_3=jpeg&attr16_0=160&attr16_1=200&attr16_2=32&attr16_3=32&normalization=full&widget=1&x=0&y=0)
2. Download Raw images for the X-T3 and T-T10
3. Import the Images to darktable

**Expected behavior**
Darktable should transform both images' input values properly so that they look (approximately) identical.

**Screenshots**
I am not sure if it is legal to share images generated from the DPreview sample images.

**Platform**

* darktable version : 3.7.0+1322~g4d27983f9
* OS                : Arch Linux 
* Memory            :  24 GB
* Graphics card     : Intel XE
* OpenCL installed  : yes
* OpenCL activated  : Tried with and without
* Xorg              : wayland
* Desktop           : sway
* CMAKE_BUILD_TYPE  : Release

 - Can you reproduce with another darktable version(s)? yes, with current stable
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? Yes

**Comment by kmilos** [comment] 2021-11-15 09:57
Indeed, it looks like the color matrix for A light instead of one for D65 somehow got merged in https://github.com/darktable-org/darktable/commit/afc12d4282ac521f947e20faca2bf3f1cc6845fb (could even be a bug in that version of ADC) @LebedevRI 

The correct one should be identical to X-T30, X-T4, X-E4, and X-S10 as confirmed by ADC 14.0, as they all use the same sensor:

`{ "Fujifilm X-T3", { 13426,-6334,-1177,-4244,12136,2371,-580,1303,5980 } },`

**Comment by kmilos** [comment] 2021-11-15 10:25
Note also that this camera was [used in dt before](https://github.com/darktable-org/darktable/issues/6965).

**Comment by Mangus78** [comment] 2021-11-15 13:04
> Note also that this camera was [used in dt before](https://github.com/darktable-org/darktable/issues/6965). @Mangus78
> 
> See also e.g. https://discuss.pixls.us/t/trying-to-tame-excessive-saturation-in-darktable-x-t3/18731

Agree, sometimes there seems to be some strange rendition both of colours and/or fine details in x-t3 raws (I haven't tried other fuji's cameras)
I tried like the op said downloading some test raw from dpreview.

X-t10 is indeed different from the x-t3 raw, BUT, the X-T30 seems almost identical to the X-T3 (but ATM I'm not using a very good monitor at all, even if it's calibrated).
X-T30 and X-T3 shares the same sensor, while the X-T10 is 2 generation prior.

**Comment by jakkul** [comment] 2022-03-06 21:00
I think that this might be just the way X-T3 renders colors in RAWs. Basically you can see this difference in DPreview as well. But there's a way out! You need to get yourself a colorchecker chart and calibrate using color calibration module in Darktable. If you don't have that, you can get RAW files with the charts photographed from the net! What I did:

1. I'm on Darktable 3.8.1, linux, hardware calibrated EA271q nec monitor.
2. I've found a portrait I made of my friend photographer holding an x-rite color checker lit by bigass broncolors. I've made it B-W for a joke but in this case it's no joke.
3. I've downloaded the RAW from dpreview's pages for X-T3 here https://www.dpreview.com/reviews/image-comparison?attr18=daylight&attr13_0=fujifilm_xt3&attr13_1=fujifilm_xt10&attr13_2=fujifilm_xt30&attr13_3=fujifilm_xt4&attr15_0=raw&attr15_1=raw&attr15_2=raw&attr15_3=raw&attr16_0=160&attr16_1=200&attr16_2=160&attr16_3=160&normalization=full&widget=1&x=0.8611172444248179&y=0.17340469328941951 ISO 160
4. same from Imaging Resource https://www.imaging-resource.com/PRODS/fuji-x-t3/fuji-x-t3THMB.HTM
5. built color profiles out of the 3 raws. I've set the WB first, then I've generated a calibration profile using color calibration module, no other changes.
6. now I've used these 3 profiles on photos of my wife and it proves to be very consistent! All 3 give much more pleasing tangerine-hotdog like skin! This is surprising given the fact that all 3 profiles are done using different cameras and different lighting!

**Comment by kmilos** [comment] 2022-12-29 10:48
This can be closed now? @Nilvus

**Closed** 2022-12-29 13:26 UTC
Labels: scope: camera support

**Comment by wilecoyote2015** [comment] 2023-03-15 09:01
@kmilos Hmm, I h
ave tested with current master and still, the color rendition differs greatly from the results of the calibration with a chart and also from the color rendition achieved with other cameras (for example, see the sample raws from imaging-resource or dpreview). 

I have profiled my X-T3 with a Datacolor Spyder Checkr 24 Chart according to the following article (point D):
https://ninedegreesbelow.com/photography/articles.html#profile-digital-camera
The resulting profile is attached: [icc_t3.zip](https://github.com/darktable-org/darktable/files/10977760/icc_t3.zip)

Below is a comparison of the standard dt input matrix (top) and my custom profile, with only exposure, crop, rotate and perspective and lens correction enabled:
![_DSF0824_dt](https://user-images.githubusercontent.com/1688125/225258843-cb15ccf3-52a2-46b1-b1d8-777f5deaf103.jpg)
![_DSF0824_custom](https://user-images.githubusercontent.com/1688125/225258846-16dcdcac-bab2-4213-8de9-de1644e28196.jpg)

**Comment by kmilos** [comment] 2023-03-15 11:19
Not much to be done TBH apart from custom profiling like this - the same sensor is in X-T30, X-T30 II, X-T4, X-E4 and X-S10, w/ identical color matrix for all (from Adobe DNG converter, like we do for any camera).

**Comment by lukelbd** [comment] 2026-09-03 18:40
Thanks @wilecoyote2015 for sharing the ICC! I applied it to my Fujifilm X-T4 library and results are great, appear much more accurate than the default standard matrix.

I'm not an expert in any of this stuff, but I used AI (ChatGPT) to quickly make a script that parses the contents of your ICC file. It confirms the file consists only of a linear matrix transformation, compatible with darktable's scene-referred workflow and the color calibration defaults as described in the [docs](https://docs.darktable.org/usermanual/development/en/module-reference/processing-modules/color-calibration/). The script extracted the following matrix transformation from your file:

```
Linear camera RGB -> XYZ D50 matrix:
[  0.596405,  0.454910, -0.087112 ]
[  0.145844,  1.232758, -0.378601 ]
[ -0.004333, -0.214691,  1.043930 ]
```

As a sanity check, I also made a script that uses [`dcamprof`](https://rawtherapee.com/mirror/dcamprof/dcamprof.html) to re-package the matrix transformation read from your ICC into a new ICC. I can confirm that switching between (1) the ICC shared by @wilecoyote2015 and (2) the ICC explicitly re-packaged from the above matrix produces virtually identical results in darktable. So I believe the above values are accurate. I've attached the relevant repackaged ICC if anyone wants to confirm (custom ICCs can be used in darktable by adding them to [`color/in`](https://docs.darktable.org/usermanual/development/en/module-reference/processing-modules/input-color-profile/) in the config directory). I've also attached the two AI-generated scripts used for these results.

Pinging @kmilos @LebedevRI : Would you folks consider merging a separate PR adding the above matrix extracted from @wilecoyote2015 's ICC profile as an "enhanced matrix" in [`colormatrices.c`](https://github.com/darktable-org/darktable/blob/master/src/common/colormatrices.c)? Would want it to appear as an option for the X-T3 along with any other Fuji cameras with identical sensors (including the X-T4 --- tested with my own images ---  and others I'm not aware of). The default standard matrix results appear artificially muddy and desaturated compared to images taken with other cameras that I've tried in darktable --- think this would help other Fujifilm users a lot.

---

Attachments:

- Matrix extraction script: [print_icc_matrix.py](https://github.com/user-attachments/files/31802952/print_icc_matrix.py)
- ICC re-packaging script:  [extract_linear_matrix_icc.py](https://github.com/user-attachments/files/31803458/extract_linear_matrix_icc.py)
- Re-packaged ICC profile: [Fujifilm X-T4 Enhanced Matrix.icc.zip](https://github.com/user-attachments/files/31803511/Fujifilm.X-T4.Enhanced.Matrix.icc.zip)
