### ISSUE TITLE
Problem with colors when opening in darktable

### ISSUE THREAD

**Issue by PerHei** [darktable-org/darktable#8404] opened 2021-03-05 19:38 UTC
I have a problem with the colors, when opening photos in darktable, dosnt matter if its Raw or Jpg, or different cameraes.
Tried Canon Digital Photo Professionel, same result, a little different colors, but still wrong. 
Windows picture is shows pitures right. 
I guess it must be a Windows problem, but has anyone a suggestion?

![Crazy colors](https://user-images.githubusercontent.com/80125872/110164037-223dd500-7df1-11eb-839d-b8f2cfcce56c.jpg)

**Comment by ptilopteri** [comment] 2021-03-05 20:16
provide the requested information so a suggest might be possible
but w/o the requested info, I really do not know.

**Comment by PerHei** [comment] 2021-03-05 21:48
Which requested information is that?

**Comment by da-phil** [comment] 2021-03-06 00:01
> Which requested information is that?

The questions which were in the issue template, see https://github.com/darktable-org/darktable/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

It's important for the developers to understand exactly software versions, used hardware (esp. GPU), whether OpenCL was turned on, etc. Just check the template above and try to answer as many questions as possible, this will increase the chance of addressing the issue you have.

**Comment by MStraeten** [comment] 2021-03-06 08:41
if you can reproduce the same behaviour using canons dpp, then it doesn’t seem to be a darktable issue. 
you might provide a raw file showing this so it’s possible to check, if this also appears if different hardware is used.
Btw: did you also opened such raw file in the darkroom? If it‘s ok there, then just the included jpg might be corrupted

**Comment by PerHei** [comment] 2021-03-06 09:19
i'm reasonably sure it's not darktable. I testet "darktable-cltest" and it looks like OpenCL is not available. So a new/other driver, for the CPU Intel(R) HD Graphics 620. So i have to try, to figure it out, without crashing the pc. Not an expert in that.

![image](https://user-images.githubusercontent.com/80125872/110201588-1d663900-7e64-11eb-83b9-f0073d09061a.png)

**Comment by johnny-bit** [comment] 2021-03-06 10:13
You clearly have graphics driver issues at least. Possible problems are also memory or gpu issues. I remember on my old laptop I had similar look in graphics intensive apps and games where sometimes blue channel would go missing or things would glitch out - the reason was faulty GPU (and I had to buy new laptop because glitches started appearing more and more frequently)

If the problem is still visible in other applications there's nothing darktable devs can do to help you. You have to check your computer for any damages in GPU/CPU/RAM, make sure your drivers are up to date etc. Make sure also that your files are not corrupted because weird look of just images is a sign of file corruption (so HDD problem).

Since it's not a darktable bug, I'll need to close this issue. I recommend doing above. And for non-software specific help forum I can recommend discuss.pixls.us where there are more people able to help you.

**Closed by johnny-bit** 2021-03-06 10:13 UTC
Labels: bug: upstream, bug: won't fix, understood: unclear
