### ISSUE TITLE
DT 4.8: Color Picker in Framing module not working correctly

### ISSUE THREAD

**Issue by caigner** [darktable-org/darktable#17329] opened 2024-08-14 21:41 UTC
### Describe the bug

When using the color picker the picked color is not the one which is used to paint the frame border.

### Steps to reproduce

1. Open Framing module
2. Active Color Picker for border color
3. Select color on image

### Logfile | Screenshot | Screencast

![darktabe_framing_color_picker2](https://github.com/user-attachments/assets/a166682d-0440-48ac-992a-ff4f209255b1)
![darktabe_framing_color_picker](https://github.com/user-attachments/assets/56e63653-5108-4411-a80a-c354ee31ef84)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.8.0

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo Linux

### Describe your system?

Laptop without GPU.

### Are you using OpenCL GPU in darktable?

No

**Comment by jenshannoschwalm** [comment] 2024-08-15 04:20
Duplicate of #17175, has been fixed in master already.

**Closed by jenshannoschwalm** 2024-08-15 04:20 UTC
Labels: duplicate, Fixed in master
