### ISSUE TITLE
Exported jpg is partially burned out

### ISSUE THREAD

**Issue by dirk-vanda** [darktable-org/darktable#12734] opened 2022-10-30 06:00 UTC
**Describe the bug/issue**

This is what is see in Darktable

![Screenshot_2022-10-30_06-38-35](https://user-images.githubusercontent.com/32796771/198864287-49b38e56-1272-4782-9096-2e75ef874b44.png)

This is what the exported jpg file lookslike

![Screenshot_2022-10-30_06-42-50](https://user-images.githubusercontent.com/32796771/198864361-6b9133f0-eb63-4542-aa2a-bc3d07219b26.png)

**To Reproduce**
First I used 'Color balance rgb'

![Screenshot_2022-10-30_06-46-30](https://user-images.githubusercontent.com/32796771/198864489-8934561a-8c3a-4815-9bbf-34f2a1119208.png)

Then I used the 'Contrast equalizer'

![Screenshot_2022-10-30_06-47-09](https://user-images.githubusercontent.com/32796771/198864505-2ae8fd3f-9c62-4528-91b4-33c400b0cecd.png)

I didn't use masks.

**Platform**

* darktable version :4.0.1
* Linux - Distro    : Ubuntu 20.04.5 LTS
* Graphics card     : none
* Desktop           : xfce

**Comment by Nilvus** [comment] 2022-10-30 07:53
Could you please post the raw (post it in a cloud and provide the link here) and jpg?
It will be hard to understand your strange issue without them.

**Comment by pehar1** [comment] 2022-10-30 08:49
For me this looks somewhat similar to https://discuss.pixls.us/t/something-wrong-with-darktable-4-1-0-git272-5a1a1845-1-clipped-highlights/32540. There was also an github issue created about that not too long ago, can't find it at the moment.

**Comment by Nilvus** [comment] 2022-10-30 17:20
Thanks @pehar1: seems really similar. So this issue is probably a duplicate. I let this issue opened few days waiting for your feedback @dirk-vanda. This will probably need to continue on #12442. No need to have 2 issues for same thing.

**Comment by pehar1** [comment] 2022-10-31 07:36
@dirk-vanda please also send the corresponding xmp (history) and your export parameters (screenshot of export module). This makes it easier to reproduce the issue and to find a solution or workaround for you.

**Comment by dirk-vanda** [comment] 2022-10-31 09:38
@pehar1 @Nilvus 
The requesed files raw, xmp ans jpg are here: https://drive.google.com/drive/folders/1Z94iFVVzLlIYt6BOGJ6Bnso2K1seHLd1?usp=sharing
Thanks in advance,
Dirk

**Comment by Jiyone** [comment] 2022-10-31 10:11
@dirk-vanda don’t you change parameters of exposure and filmic before the changes you described?

**Comment by dirk-vanda** [comment] 2022-10-31 16:09
> @dirk-vanda don’t you change parameters of exposure and filmic before the changes you described?

In this edit I did not changed Exposure and Filmic. 
- Exposure default +0,5 EV
- Filmic defaults:
![Filmic rgb, Screenshot_2022-10-31_16-58-33](https://user-images.githubusercontent.com/32796771/199054132-f8d47d8c-27b8-4ad5-a18e-c41c0f740e1a.png)

**Comment by Jiyone** [comment] 2022-10-31 17:51
> In this edit I did not changed Exposure and Filmic.

That’s certainly why you have those artefacts.
This doesn’t explain why the preview is not updated taking account of filmic’s reconstruct effect

**Comment by pehar1** [comment] 2022-11-01 07:24
First of all : the xmp you uploaded is definetely not the one you used for export. It only contains some basic modules, not _exposure_, not _filmic rgb_, not _colorbalance rgb_... But nevertheless I was able to reproduce the issue.

About the image: large parts of the sky are overexposed (raw data clipped). The threads mentioned above explain why the observed artifacts occur. I do not want to repeat that here. To avoid :

- Do not push already clipped areas more and more by using _exposure_, _filmic rgb_, _colorbalance rb_g... At some point filmics highlight reconstruction will become active and create these artifacts. This effect depends on the resolution, which explains the difference between the view in the darkroom and the exported jpg. You can disable filmics hl reconstruction by setting threshold to +6 eV and transition to 0.25 eV.
- Best solution : do not clip raw data at sensor level, choose a lower exposure at time of shooting the image. Somewhat stronger noise is easier to handle than clipped areas.

By the way : in the module _raw black/white point_ the white point has a wrong value (16300 instead of 15360 as reported by `exiftool`). This is a known problem with many Sony cameras. The white point also has an influence on the functionality of the hl reconstruction.

**Comment by dirk-vanda** [comment] 2022-11-01 17:01
Thank you all for your work on Darktable. I hope to have contributed in some way by reporting this issue.
@pehar1 thanks for explaining the cause and the workaround.

**Comment by Nilvus** [comment] 2022-11-01 19:32
I close this issue as it is a duplicate of #12442. If needed, I suggest to continue on #12442 issue. No need to have 2 issues for same thing. Thanks for your contributions here.

**Closed by Nilvus** 2022-11-01 19:32 UTC
Labels: duplicate, understood: unclear, reproduce: peculiar, scope: image processing
