### ISSUE TITLE
Recently used collection dropdown has weird entries

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7864] opened 2021-01-15 14:15 UTC
On a current build of master (clean build / clean install/ no db present )

The recently used collections appears weird. 
![image](https://user-images.githubusercontent.com/1119439/104735342-7ae4e000-5767-11eb-9841-cb4312aa43ec.png)

**Comment by elstoc** [comment] 2021-01-15 23:26
I think you need to explain what you think is weird about this and perhaps add some additional context.

**Comment by chhil** [comment] 2021-01-16 03:14
Is it supposed to show the collections or just criteria to select based on double clicking of the list ?

Double clicking items moves those items randomly. Sometimes it shows me images , sometimes nothing.

![RecentCollection](https://user-images.githubusercontent.com/1119439/104795803-f5991400-57d6-11eb-917b-308d197fcc3e.gif)

**Comment by elstoc** [comment] 2021-01-16 10:39
Ok so the recently used collections is a list of the things you've done recently in the collect module. You can click (single-click, not double-click) to reload those collections back into the collect module. The text describes the search you did.

For example, `film roll %` means that (in collect) you selected "film roll" from the drop-down and didn't filter it. If you click on `film roll %` in the recently used collections module, that reloads the chosen search criteria into the collect module. Because that collection is now the one you most recently used, it jumps to the top of the list.

None of the entries you've shown seem odd. I suspect the behaviour in your screencast is because you're double-clicking.

**Comment by chhil** [comment] 2021-01-16 11:56
Should double click be disabled then?

**Comment by elstoc** [comment] 2021-01-16 13:00
No. Just don't do it.

**Comment by ralfbrown** [comment] 2021-06-20 18:16
I think we can close this one as "working as designed".  Might be worth adding some of the details from Chris's post above to the `module-reference/utility-modules/shared/recent-collections/` page of the documentation to avoid future user confusion.

**Comment by johnny-bit** [comment] 2021-06-20 19:45
Is not a bug: is a feature!

**Closed by johnny-bit** 2021-06-20 19:45 UTC
Labels: bug: invalid
