### ISSUE TITLE
Gradient mask → nonsensical controls visualization

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#8291] opened 2021-02-21 11:04 UTC
Linux, 64 bit, dt 3.4.1.

1. Open this https://discuss.pixls.us/t/play-raw-vulcan-stone-sunset/9618 with xmp file from the attachment to this post.
2. Open color calibration module
3. Open editing gradient mask.
4. Hover mouse over gradient line to see it's parameters visualized.
5. Observe messy lines like it the screenshot attached. Looks like it works properly, problem is with visualization only.

![gradient mask](https://user-images.githubusercontent.com/65483426/108622988-78079a00-744d-11eb-9c48-5eca64ff908f.png)

[2018-07-27__7M33870.ARW.zip](https://github.com/darktable-org/darktable/files/6017565/2018-07-27__7M33870.ARW.zip)

**Comment by chhil** [comment] 2021-02-21 11:23
Bugs have a template, please use it to provide as much information that a developer can look at and analyze.

**Comment by ralfbrown** [comment] 2021-02-21 17:10
I can confirm minor corruption  in current master, but nothing near as bad as what you're seeing.  This is probably the same underlying problem as #7362 - "extreme" lens corrections get a bad distortion transform in lens.cc (the problem goes away if you turn off the lens correction module).  And that in turn is probably because it has to simulate the transform in one direction using successive approximation on the transform for the opposite direction.

**Comment by ralfbrown** [comment] 2021-05-04 02:20
This appears to have been fixed in master as of about two weeks ago.  @timur-davletshin please confirm and close this issue if that is correct.

**Comment by johnny-bit** [comment] 2021-06-13 18:16
I can confirm that the error is fixed on master. No longer reproducible with `darktable 3.5.0+2526`

**Closed by johnny-bit** 2021-06-13 18:16 UTC
Labels: no-issue-activity
