### ISSUE TITLE
Can no longer compile git master using Debian Stable 11.6, gcc (Debian 10.2.1-6) 10.2.1 20210110

### ISSUE THREAD

**Issue by KarlMagnusLarsson** [darktable-org/darktable#13951] opened 2023-03-17 17:52 UTC
**Introduction**
I can no longer build darktable master branch using Debian Stable 11.6 with gcc (Debian 10.2.1-6) 10.2.1 20210110 after commit https://github.com/darktable-org/darktable/commit/e2c8b233a72bcdbf884047c2cf4cc16cd1bf4730. 

gcc (Debian 10.2.1-6) 10.2.1 is standard for Debian stable 11.6.

```
CMake Error at cmake/compiler-versions.cmake:40 (message):
  GNU C compiler version 10.2.1 is too old and is unsupported.  Version 12+
  is required.
```

---------------------------------------------------------------

**Describe the bug/issue**
If I clone git repo and run cmake I get:
```
CMake Error at cmake/compiler-versions.cmake:40 (message):
  GNU C compiler version 10.2.1 is too old and is unsupported.  Version 12+
  is required.
Call Stack (most recent call first):
  CMakeLists.txt:155 (include)


CMake Error at cmake/compiler-versions.cmake:43 (message):
  GNU C++ compiler version 10.2.1 is too old and is unsupported.  Version 12+
  is required.
Call Stack (most recent call first):
  CMakeLists.txt:155 (include)
```

`-- Configuring incomplete, errors occurred!`

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. git clone --recurse-submodules --depth 1 https://github.com/darktable-org/darktable.git
git submodule update --init
2. cd darktable
mkdir build
cd build
3. cmake ..

**Expected behavior**
-- Configuring done
-- Generating done

**Which commit introduced the error**
https://github.com/darktable-org/darktable/commit/e2c8b233a72bcdbf884047c2cf4cc16cd1bf4730

_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. release-4.3.0-1232-ge2c8b233a7
* OS                :Linux debian 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
* Linux - Distro    : Debian stable v11.6
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : gcc (Debian 10.2.1-6) 10.2.1 20210110
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by zisoft** [comment] 2023-03-17 18:40
See #13943

**Comment by Nilvus** [comment] 2023-03-17 18:51
I close this one as it's a duplicate of #13943. Not same distrib but same cause.

**Closed by Nilvus** 2023-03-17 18:51 UTC
Labels: duplicate
