### ISSUE TITLE
New preferences causes the window to shift on selection of the widest text tab 

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#4836] opened 2020-04-28 10:49 UTC
darktable-3.1.0+1346~g532efbf17-win64

@elstoc 
Its preference related but not buttons related.

The cpu/gpu/memory one is the widest and when that tab is clicked, the window of its preferences moves right. No other tab shows this behavior.
I have added a ruler to show the pixel shift.

![image](https://user-images.githubusercontent.com/1119439/80441677-02b06300-8929-11ea-825c-32d9c085a030.png)

![image](https://user-images.githubusercontent.com/1119439/80441690-09d77100-8929-11ea-8597-a2560a3a9569.png)

**Comment by elstoc** [comment] 2020-04-28 11:25
I suspect this needs a CSS change to make the minimum width a little wider. It only seems to happen on the themes with larger base fonts (e.g. 'darktable.css') but not on those with smaller fonts (e.g. 'darktable-elegant-grey.css') @Nilvus

**Comment by Nilvus** [comment] 2020-04-28 16:03
Thanks @chhil but that was not useful. I follow #4825 PR (but indeed better to have an issue than posting a closed PR). I can't reproduce your issue. I was not having not when working on CSS and not have that now. But if you that on that category is just that it's the longest one.

@elstoc: not sure a minimum width will be the good way but I will test. It seems to be more an hover setting to adjust.

@chhil: as it seems you use darktable default theme, could you precise your OS font used and font size?

**Comment by elstoc** [comment] 2020-04-28 16:06
I get it on darktable and darktable-icons themes.

**Comment by Nilvus** [comment] 2020-04-28 16:07
> I get it on darktable and darktable-icons themes.

Of course, that's only font related... and difference between normal font and bold one...

**Comment by elstoc** [comment] 2020-04-28 16:08
I think my default font is Arial 10

**Comment by elstoc** [comment] 2020-04-28 16:09
> On first reading I don't understand that was only when this line is selected...

Text goes bold when it's selected

**Comment by Nilvus** [comment] 2020-04-28 16:13
> I think my default font is Arial 10

So you don't have that behavior. I use Cantarell 12 and don't have that behavior. But after setting on 16, i have this behavior.

And the only reason of that behavior it's about the text goes bold. When we increase font size, the difference of visible size between regular and bold one increase. So on default small fonts and regular ones (like Arial, Cantarell, etc) on 10, 12 or even 14 sizes, the difference is ok to not have that move. So minimum lenght would made a problem: for small font, that will let too much space on the right of text and if someone use a too big font, that could be not sufficient. So hard to set the good length for all people.

So I will something like finding another way than bold for selected text... Will made some tests to find the better way.

**Comment by elstoc** [comment] 2020-04-28 16:16
> So you don't have that behavior.

I **do** have that behaviour. The width changes when I select cpu/gpu/memory with those two themes.

**Comment by Nilvus** [comment] 2020-04-28 16:17
> > So you don't have that behavior.
> 
> I **do** have that behaviour. The width changes when I select cpu/gpu/memory with those two themes.

That depend on font size so depending on font size used, that could be seen on other themes.

On my side with my default OS config with Cantarell 14, I don't have this behavior on any themes.

**Comment by elstoc** [comment] 2020-04-28 16:21
I get the same issue if I change my system font to Cantarell 14.

**Comment by elstoc** [comment] 2020-04-28 16:22
Maybe you're getting gnome-specific behaviour again?

**Comment by Nilvus** [comment] 2020-04-28 16:22
> Maybe you're getting gnome-specific behaviour again?

No, it can't be gnome specific here. Sure about that.

**Comment by elstoc** [comment] 2020-04-28 16:23
why can't it?

**Comment by Nilvus** [comment] 2020-04-28 16:32
Because it's just font and length used. And as I said (I will not like to repeat it, sorry but that bother me...), the buttons of headerbar were at first possible by darktable code, so it was not only environment specific. And a desktop environment could of have effects on how to manage windows and not should have effects on the content. The first mistake was that darktable code allow to change things. Last thing, that was discussed on PR last year, CSS capture screens, etc. And nobody last year ask about that or find strange that I have (and so other developers) buttons on headerbar. Last thing, as I said, yesterday problem was the first one since I work on darktable and specifically about a part who could be managed directly by the desktop environment. I've worked since more than a year on all CSS parts of darktable without any other problem like the one we see yesterday.

Here it's only a font effect. So I hope we are not with discussion yesterday and now on some Gnome bashing. Some like it (like me) not other...
If one time we see a different behavior regarding of the desktop environment used on the content of darktable, that's will just mean a not good coded part.

And by the way I just see that I made a mistake on changing font... I of course have the issue with the Cantarell 14 and again it's about bold text.

**Comment by elstoc** [comment] 2020-04-28 16:37
Not gnome bashing, just saying things are different between Desktop Environments and trying to explain why you might be getting different results. Anyway, the issue doesn't bother me because I don't use those themes - I was just trying to be helpful.

**Comment by Nilvus** [comment] 2020-04-28 17:20
Ok, I've seen too much bashing on the web like that so I probably seen it too quickly. But I think user mistakes (like I just made on changing theme/font and testing here about font and this issue) is more frequent than the environment. Of course, it could be a possibility for UI part, I think it will rarely be. So the last thing to check most of the time.

Said that, I've made some tests and put italic instead of bold to confirm what I think: same behavior so that confirm having on sidebar a different length on not selected category and selected one is not a good thing. I don't see any CSS trick to be sure someone will not have this issue (and I'm quite sure if we let this issue alive, when darktable 3.2 will be released, some users will go there to post a new issue). So, adding min length would not work in all case (too much space seeing on some, and the issue for others on the extreme).

The only thing I see is to remove the bold option. So to replace bold option, keep the selected category visible and the sidebar effect we want, I propose to replace that by a left border.

To avoid this issue by replacing it by a left border, this need to set the border existing even if not selected (so on both normal and hover one ; and set border left color to the same background color to hide the border when not selected). Here the result:
![Capture-20200428191736-230x289](https://user-images.githubusercontent.com/45535283/80517187-fa861100-8984-11ea-8e7b-05bc3cfeae31.png)

I test that with some fonts and size with the biggest one was Arial 20. Not possible to have same behavior in all cases with bold or italic one, but ok with that change.

@elstoc and @chhil: what do you think about this fix?

**Comment by elstoc** [comment] 2020-04-28 17:38
It's a shame that something like that has to stop us using bold text but your alternative looks fine. Quite similar to what the old preferences window did (but was an underline before).

**Comment by Nilvus** [comment] 2020-04-28 20:17
> It's a shame that something like that has to stop us using bold text but your alternative looks fine. Quite similar to what the old preferences window did (but was an underline before).

Totally agree about that. I've improved a little bit by making the border a little less contrasted and so more balanced. Waiting for your new preferences PR to be merged to propose the CSS (will need to adjust CSS for that too).

**Comment by chhil** [comment] 2020-04-29 07:47
>as it seems you use darktable default theme, could you precise your OS font used and font size?

I am on windows 10. Use the darktable-icons theme. I believe the default windows system font is being used Segoe*.  Don't know where to look for font size.

-----
Why is there a extra button to save theme tweaks?
I was under the impression that all changes are saved by the save button in the header.


![image](https://user-images.githubusercontent.com/1119439/80572284-a1b58780-8a1b-11ea-8d4d-067dfa4d23fb.png)

**Comment by elstoc** [comment] 2020-04-29 07:52
@chhil: after much discussion the 'save changes' and 'exit without saving' buttons have been removed in a new commit this morning - most changes are now saved when exiting the window (with 'X' button or 'ESC' key). The theme tweaks are the main exception to this - because the CSS is saved to an external file, and also so that you can see the effect of your changes immediately. Basically everything in this window applies immediately.

**Comment by chhil** [comment] 2020-04-29 09:17
Just made a new build, I see that the buttons are gone.

So now how does one exit without saving?

**Comment by Nilvus** [comment] 2020-04-29 09:20
> > as it seems you use darktable default theme, could you precise your OS font used and font size?
> 
> I am on windows 10. Use the darktable-icons theme. I believe the default windows system font is being used Segoe*. Don't know where to look for font size.

Finally no more useful. This issue needs to forgot using bold text (or any text that change length of text when its state changed. A fix on its way.

**Comment by elstoc** [comment] 2020-04-29 09:20
You can't any more. It couldn't be done consistently with all tabs and there were questions over the buttons so it has been reverted for now. It may be reintroduced in the future if it can be done consistently with the shortcuts, presets and general tabs (which all have 'commit now' behaviour hard-coded into them).

**Comment by Nilvus** [comment] 2020-04-29 09:23
> Just made a new build, I see that the buttons are gone.
> 
> So now how does one exit without saving?

Simply just undo what you set and don't want to save. Many settings were already not cancelled even with the exit without saving button. The preferences were not consistent that way. For example, I change the theme or a shortcut, it's saved, even when clicking on Exit without saving button. Strange. But if i change some others settings that could be change and not saved when clicking on the exit without saving button before. Not consistent at all so better by now to not have buttons and save settings when changed. So revert back a setting cancel it.

**Closed** 2020-04-29 10:41 UTC

**Comment by chhil** [comment] 2020-04-29 11:45
Used darktable-3.1.0+1365~gcf6de44e7-win64 , change looks good. Thank you @Nilvus .

**Comment by Nilvus** [comment] 2020-04-29 11:56
> Used darktable-3.1.0+1365~gcf6de44e7-win64 , change looks good. Thank you @Nilvus .

Good to read that.

**Comment by ptilopteri** [comment] 2020-04-29 12:26
The way this option has changed makes it very difficult to return to a previous setting changed inadvertently unless there are only two options.

example:  if I mistakenly change "cpu/gpu/memory" "host memory limit .." 
there is no obvious method/path to discard the change.

perhaps the "drop down box" should include an option "revert"
or ... 

perhaps <escape> should revert "any" changes

but the decided option must be prominetly advertised somehow

**Comment by elstoc** [comment] 2020-04-29 12:28
Double click on the label reverts back to default. Hover over the label to see what the default is.

**Comment by ptilopteri** [comment] 2020-04-29 12:36
> Double click on the label reverts back to default. Hover over the label to see what the default is.

@elstoc: reverts back to default.  THAT is not a problem but one cannot revert back to the previous setting.  That is the problem.

**Comment by elstoc** [comment] 2020-04-29 12:38
You couldn't do that on the version before my change either. Everything changed as soon as you changed it.

**Comment by elstoc** [comment] 2020-04-29 12:40
Either way the most common way to inadvertently change settings in the old preferences window was by scrolling, and you don't need to scroll the window any more.
