### ISSUE TITLE
Windows: Crash on entering darkroom

### ISSUE THREAD

**Issue by Eros-DS** [darktable-org/darktable#16768] opened 2024-05-11 18:57 UTC
### Describe the bug

When selecting the raw image for post production, or when switching/clicking in the "darkroom" the program closes completely without the possibility of working on the images

### Steps to reproduce

1. Selecting the raw image for post production
2. The program stops

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

darktable 4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Are you using OpenCL GPU in darktable?

None

**Comment by MStraeten** [comment] 2024-05-11 19:42
without more information no one can help since it’s not a general issue.
so give some more information, logfile, … 
see https://www.darktable.org/about/faq/#faq-windows-logs

**Comment by Eros-DS** [comment] 2024-05-11 20:09
I don't know how to explain it in other ways because the problem is very
simple.  When I want to select a RAW image directly from Darktable from the
folders on my desktop and go to the "Darkroom" section (to then start my
edits), the Darktable program stops

Il sab 11 mag 2024, 21:42 Martin Straeten ***@***.***> ha
scritto:

**Comment by ralfbrown** [comment] 2024-05-12 03:49
Telling us that the program crashes is no more useful in getting the bug addressed than telling a mechanic that your car doesn't work.   Please provide the requested logs so that we can understand what the actual problem is.

Does the crash happen for any raw file from **any** camera?  Any raw file, but only from a specific camera model?  Only specific raw files? (you can download files from many different camera models from raw.pixls.us)
Does the crash happen with JPEGs?  Does the crash happen with images in a different folder?  (special characters in the path have caused problems in the past)
Does the crash happen if you reset darktable's configuration?  (rename the .config/darktable directory to something else)

**Comment by Eros-DS** [comment] 2024-05-12 08:24
Does the crash occur with any raw file from any camera?  - I have a camera
and I only use this one so I don't know what happens to other cameras.

Some raw files, but only from a specific camera model?  - I only use one
camera

Only specific raw files?  - 90% of RAW files don't work

Does the crash occur with JPEGs?  - No

Does the crash occur with images in a different folder?  - Yes

Does the crash occur if you reset the darktable configuration?  - I don't
know how I could do it but I uninstalled Darktable and redownloaded it 3
times

Il dom 12 mag 2024, 05:50 Ralf Brown ***@***.***> ha scritto:

**Comment by MStraeten** [comment] 2024-05-12 08:53
giving more unspecific information doesn’t help. I can edit images from several cams every day on a windows machine without such issues. Does this information help in your case - obviously not.
So if you’re interested to get help, be more specific, provide raw files that fails, log files - help the developers to reproduce your case (not my or their scenario) but keep in mind: most of them aren’t using windows and so they need log files to get an idea what might happen on your machine.

please read the windows related chapters of the faq: just uninstall/reinstall doesn’t affect your configuration - you need to do this manually

**Comment by Eros-DS** [comment] 2024-05-12 09:00
I would like to be more specific but I don't know where to get and how to
verify the information you need.

If you can tell me what exactly the information you need would be, I will
gladly try to provide it to you

Il dom 12 mag 2024, 10:53 Martin Straeten ***@***.***> ha
scritto:

**Comment by gi-man** [comment] 2024-05-12 17:22
How to create a log is explained here:  https://www.darktable.org/about/faq/#faq-windows-bugs

Also in the FAQ it will show you the path to the log.

**Comment by victoryforce** [comment] 2024-05-23 18:43
> If you can tell me what exactly the information you need would be, I will gladly try to provide it to you

Did we not explain clearly enough how to get the necessary information or have you lost interest in this issue?

**Comment by Eros-DS** [comment] 2024-05-23 21:00
I'm sorry but I'm not able to go into specifics and provide specific files
or code or anything.

The only thing I could possibly do is just a demo recorded screen video to
show the moment it breaks.

For this reason I prefer not to waste your time, sorry.

Il gio 23 mag 2024, 20:43 Victor Forsiuk ***@***.***> ha
scritto:

**Comment by victoryforce** [comment] 2024-05-24 07:52
> The only thing I could possibly do is just a demo recorded screen video to show the moment it breaks.

So you're a better Windows user than I am, because I still need to figure out which programs in Windows make screen videos. 🙂 But the video of the screen will not give us any information we need, it only visualizes the fact that the program crashes.

> I'm sorry but I'm not able to go into specifics and provide specific files or code or anything.

No code or anything needed. Just specific file. You need to enter `%LOCALAPPDATA%\Microsoft\Windows\InetCache\darktable` in the path field of File Explorer. You probably can't _navigate_ to this folder in File Explorer because the path to it contains hidden folder that aren't shown in File Explorer by default. In the open folder you will see the `darktable-log.txt` file. After that, we may also ask you to run certain programs from the command line.

If this is difficult for you, then first disable OpenCL in the darktable settings (processing > OpenCL) and check if this helps to avoid crashes. There are chances that it can help in your case.

**Comment by victoryforce** [comment] 2024-06-27 12:40
I still don't understand what is going on and what is the problem with providing the specified file if there is an instruction with all the necessary steps for this, but since no information has been provided, I have to close this issue.

**Closed** 2024-06-27 12:41 UTC
Labels: understood: incomplete, scope: windows support
