### ISSUE TITLE
double entries in exposure values of a 'new preset'

### ISSUE THREAD

**Issue by diefau** [darktable-org/darktable#13461] opened 2023-01-28 15:22 UTC
I made this little patch, because I don't understand why there are two doubled values.
Maybe it is useful?

```
--- darktable-4.2.0/src/gui/presets.c	2023-01-28 15:40:07.777994863 +0100
+++ presets.c	2023-01-27 00:46:42.914132294 +0100
@@ -38,15 +38,15 @@
 #include <stdlib.h>
 
 
-const int dt_gui_presets_exposure_value_cnt = 24;
+const int dt_gui_presets_exposure_value_cnt = 22;
 const float dt_gui_presets_exposure_value[]
-    = { 0.,       1. / 8000, 1. / 4000, 1. / 2000, 1. / 1000, 1. / 1000, 1. / 500, 1. / 250,
-        1. / 125, 1. / 60,   1. / 30,   1. / 15,   1. / 15,   1. / 8,    1. / 4,   1. / 2,
-        1,        2,         4,         8,         15,        30,        60,       FLT_MAX };
+    = { 0.,       1. / 8000, 1. / 4000, 1. / 2000, 1. / 1000, 1. / 500, 1. / 250,
+        1. / 125, 1. / 60,   1. / 30,   1. / 15,   1. / 8,    1. / 4,   1. / 2,
+        1,        2,         4,         8,         15,        30,       60,      FLT_MAX };
 const char *dt_gui_presets_exposure_value_str[]
-    = { "0",     "1/8000", "1/4000", "1/2000", "1/1000", "1/1000", "1/500", "1/250",
-        "1/125", "1/60",   "1/30",   "1/15",   "1/15",   "1/8",    "1/4",   "1/2",
-        "1\"",   "2\"",    "4\"",    "8\"",    "15\"",   "30\"",   "60\"",  "+" };
+    = { "0",     "1/8000", "1/4000", "1/2000", "1/1000", "1/500", "1/250",
+        "1/125", "1/60",   "1/30",   "1/15",   "1/8",    "1/4",   "1/2",
+        "1\"",   "2\"",    "4\"",    "8\"",    "15\"",   "30\"",  "60\"", "+" };
 const int dt_gui_presets_aperture_value_cnt = 19;
 const float dt_gui_presets_aperture_value[]
     = { 0, 0.5, 0.7, 1.0, 1.4, 2.0, 2.8, 4.0, 5.6, 8.0, 11.0, 16.0, 22.0, 32.0, 45.0, 64.0, 90.0, 128.0, FLT_MAX };
```

**Comment by victoryforce** [comment] 2023-12-09 20:34
@diefau Thanks for the suggestion to improve darktable and sorry that your issue was overlooked. You simply should have offered a pull request instead of a patch in an issue, since issues are used to report problems and developers first of all pay attention to those that are reports of rather serious bugs in the program and can be reproduced.

The problem with duplicates that you noticed has already been fixed in PR #15230.

**Closed by victoryforce** 2023-12-09 20:34 UTC
Labels: bugfix, no-issue-activity
