### ISSUE TITLE
GCC10.1 (probably) compilation spams warnings

### ISSUE THREAD

**Issue by Thanatomanic** [darktable-org/darktable#5377] opened 2020-06-10 10:06 UTC
When using build.sh as described in the README.md or the manual Windows build instructions on an updated MSYS2 environment on Windows 10 using GCC 10.1, the initial build process spams a lot of warnings such as the following (excerpt). ~~I have not tested this with a manual compilation, but the same warnings may appear there.~~
Edit: this also happens on Fedora 32 with GCC 10.1.

```
[ 16%] Built target rawspeed
Scanning dependencies of target rawspeed_get_number_of_processor_cores
[ 16%] Building CXX object src/external/rawspeed/src/librawspeed/common/CMakeFiles/rawspeed_get_number_of_processor_cores.dir/GetNumberOfProcessorCores.cpp.obj
cc1plus.exe: warning: command-line option '-Wold-style-declaration' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wtraditional' is valid for C/ObjC but not for C++
[ 16%] Linking CXX static library librawspeed_get_number_of_processor_cores.a
[ 16%] Built target rawspeed_get_number_of_processor_cores
Scanning dependencies of target darktable-rs-identify
[ 16%] Building CXX object src/external/rawspeed/src/utilities/identify/CMakeFiles/darktable-rs-identify.dir/rawspeed-identify.cpp.obj
cc1plus.exe: warning: command-line option '-Wold-style-declaration' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
cc1plus.exe: warning: command-line option '-Wtraditional' is valid for C/ObjC but not for C++
[ 16%] Linking CXX executable darktable-rs-identify.exe
[ 16%] Built target darktable-rs-identify
```

This seems to apply mostly to the building of rawspeed, but occasionally there is a similar warning later on:

```
[ 26%] Building CXX object src/CMakeFiles/lib_darktable.dir/common/splines.cpp.obj
cc1plus.exe: warning: command-line option '-Wold-style-declaration' is valid for C/ObjC but not for C++
...
[ 35%] Building C object src/CMakeFiles/lib_darktable.dir/common/imageio_j2k.c.obj
cc1plus.exe: warning: command-line option '-Wold-style-declaration' is valid for C/ObjC but not for C++
...
Scanning dependencies of target tonemap
[ 67%] Building CXX object src/iop/CMakeFiles/tonemap.dir/introspection_tonemap.cc.obj
[ 67%] Linking C shared module libtonecurve.dll
cc1plus.exe: warning: command-line option '-Wold-style-declaration' is valid for C/ObjC but not for C++

```

There seems to be something wrong with the compiler warning suppression. It would be preferable to have a warning-free compilation.

**Comment by MStraeten** [comment] 2020-06-10 10:34
it's recommended to use the instructions in https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.txt (also mentioned in Readme.md)

**Comment by coffeeandspaceships** [comment] 2020-06-11 23:06
These messages are telling you that the warnings that have been asked for are redundant when you are compiling C++, because the C++ language itself will not allow whatever C antipattern or deprecated thing the -W option would normally check for if compiling C.

So it's like your bridge has a first sign saying "ignore the next warning sign: that guy doesn't know what he's talking about and we fixed that stuff already." 

Or at least that's normally what the problem is, but for some reason it does seem that darktable has worked out imageio_j2k.c is C, and then the warning appears anyway, which suggests the CMake config has the same flags for both compilers.

**Comment by rabauke** [comment] 2020-06-20 21:11
I can reproduce these warnings on Ubuntu 20.04 using GCC 10.0.1 20200411.

Basically programmers are asking the compiler here to warn about certain kinds of constructs which are valid but poor C when compiling C++ sources. The compiler complains in response that he will not warn because these C constructs are illegal in C++ anyway, where the compiler would throw an error message.

In my view this should be fixed. It produces a lot of noise and makes it more difficult to find  new real code issues. These compiler warnings hint to an erroneous cmake configuration.

**Closed** 2020-06-22 13:15 UTC
