### ISSUE TITLE
problems instantaneous

### ISSUE THREAD

**Issue by cjose38** [darktable-org/darktable#13202] opened 2022-12-26 13:30 UTC
Hello,

snapshots aren't quite snapshots anymore.
maybe that's why the compression erases the snapshot.
on screenshot below:
I took a snapshot "white balance (22)"
I applied a style...
wanting to compare the result with my initial snapshot, I realize that it is different and corresponds to line 22 of the current history and not the one memorized initially.
https://imgbb.com/WKKF4sB

I made a video:
https://youtu.be/dI5iWWy8ARU

4.2 OM-1 version.
w10.

**Comment by Nilvus** [comment] 2022-12-26 17:45
@TurboGit: seems related to applying a style after creating a snapshot. Didn't test but if needed, @cjose38 first report on french forum: https://forums.darktable.fr/showthread.php?tid=6339&pid=54014#pid54014

**Comment by TurboGit** [comment] 2022-12-27 08:07
In this scenario it is expected and not a bug. You're applying a style after selecting original. This means that you are just destroying the history stack and then the reference to the snapshot. The real issue here is that dt should detect this case and erase the snapshot as done when the history stack is compressed.

**Comment by cjose38** [comment] 2022-12-27 08:19
can't we "freeze" the snapshot as before rather than deleting it?

**Comment by TurboGit** [comment] 2022-12-27 16:33
That's hard but probably feasible and will remove some limitations. We could indeed have a new SQL table for storing the snapshot history and use this instead of the standard history to compute the proper rendering. This will avoid also to have to delete snapshot when compressing the history. I'll assigned this to me.

**Comment by TurboGit** [comment] 2022-12-27 16:34
And this won't be in 4.2.1 but in 4.4.

**Comment by TurboGit** [comment] 2022-12-27 20:46
See #13212, should be usable.

**Comment by cjose38** [comment] 2022-12-30 09:12
juste une remarque complémentaire, la fonction "freeze" doit déjà exister quelque part car il est possible d'avoir un instantané d'une autre photo. il il a, alors, 2 * devant le nom de l'instantané avec un commentaire "cet instantané provient de la photo ... ".
cet instantané est zoomable, ...
![Capture](https://user-images.githubusercontent.com/110188504/210053738-ec514fdf-eb15-4d4a-afbf-136c3abcc8e9.JPG)

**Comment by TurboGit** [comment] 2022-12-30 10:21
@cjose38 : No, there is no freeze needed in this case. The picture exists and the history recorded and fully clean (no compression has been done).

**Comment by cjose38** [comment] 2022-12-30 10:59
merci pour l'info.

**Comment by TurboGit** [comment] 2023-02-01 11:11
Done.

**Closed by TurboGit** 2023-02-01 11:11 UTC
Labels: priority: low, feature: redesign, understood: clear, release notes: pending
