### ISSUE TITLE
Auto + or Neg Selections in Color Zones and RGB Tone Curve dont seem to be working...

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#5443] opened 2020-06-13 02:41 UTC
Expected behaviour...ctrl or shift click on the second picker (range picker) will auto generate a curve in the positive or negative direction based on the selection or initially the whole image....doesn't seem to be working ...not in Color Zones or RGB Tone curve...

It appears to be selecting the range or hue or saturation value but it is not producing the curve based on that range and ctrl or shift click selection...

Running Windows 10 2004
DT version   3.1.0+2031~g4a1331495
-->
![image](https://user-images.githubusercontent.com/44409419/84558006-87024e00-acfd-11ea-8219-6b1ee17d1cee.png)
![image](https://user-images.githubusercontent.com/44409419/84558032-b44efc00-acfd-11ea-96ee-370b57038f02.png)

**Comment by dterrahe** [comment] 2020-06-13 12:19
This is an intended behavior change with the recent color picker refactor:
Now instead of holding the modifier key shift or ctrl while clicking the picker button, you hold it while making the range selection. This means you can switch between positive and negative curves without having to switch the button off and back on (with the required modifier). You just select the range again immediately, holding the modifier. And since you can now also grab the corner of the range to expand/reduce it, you can quickly switch between the two for the same range.

**Comment by todd-prior** [comment] 2020-06-13 13:11
Thanks sorry I was not aware....





Sent from Outlook Mobile

**Comment by todd-prior** [comment] 2020-06-20 03:26
@dterrahe Tried your suggestion still nothing. I can see the histogram display changing behind the tone curve but the curve remains linear with no change no matter where or how I draw the range...I will  build a newer one...I am on  3.1.0+2031~g4a1331495  so not that old but maybe it is some other issue??

**Comment by dterrahe** [comment] 2020-06-20 05:37
In reality, it only matters whether you hold the CTRL or SHIFT key at the _end_ of making the range selection. So you drag an area while holding the mouse key, then press the CTRL key and hold it while letting go of the mouse.

**Comment by parafin** [comment] 2020-06-20 06:41
IMHO it should be the other way around - modifier should be remembered from the mouse down action.

**Comment by dterrahe** [comment] 2020-06-20 07:11
If you hold ctrl or shift all the time while dragging, it doesn't make a difference. Do I agree that in principle it would be nice to remember from button down, so it doesn't matter if you let go in the middle? Maybe. That also means if you remembered you wanted to press ctrl but you forgot in the beginning, now you can't correct later during your drag. So maybe best would be ctrl pressed at any time during the drag. But then what if you press ctrl first and then change to shift?

So in the end I decided I'd go with what would be easiest (trivial) to implement and would still make sense in practice and otherwise would be easy to get used to. If you want to implement the considerable hacks needed (I think) to achieve a different behavior then please do so. And then maybe we could have a vote to see if it is worth it...

If you have a really elegant solution I would be honestly very happy to see it!

**Comment by todd-prior** [comment] 2020-06-21 03:56
@dterrahe @parafin In my case no combination is working. I can see for example if I am in color zones that if selecting a range for hue  or saturation it goes to the right one, ie the vertical line and the gray background indicating the range will change but there in no positive or negative curve created the curve remains linear...

**Comment by dterrahe** [comment] 2020-06-21 11:47
This turned out to be a Windows only problem where it apparently hadn't been tested yet.

Many thanks @todd-prior for reporting this and preventing it from going out with the 3.2 release broken. Please kindly confirm if with the changes in #5591 it now works for you.

**Comment by TurboGit** [comment] 2020-06-21 16:43
@todd-prior : I have reopened waiting for your feedback on this. If you do not compile yourself please let us know.

**Comment by dterrahe** [comment] 2020-06-21 17:34
@parafin would you please test/confirm working on osx?

**Comment by coffeeandspaceships** [comment] 2020-06-21 23:09
Working for me on Windows.

I pulled master @  3f399bdf87e34eab95e2c17cd062a67b81a2f219 and merged `dterrahe/fix-picker-modifier` then built.

I have also checked that the source tree I built from contains dterrahe's changes, so I am definitely testing the right thing!

If there are specific tests of GUI functionality on Windows I'm always happy to test.

**Comment by todd-prior** [comment] 2020-06-22 01:46
Thanks everyone...sorry I was on vacation this week and the weather in my part of Canada was sunny and in the 30"s so no time to be at the computer...looks like the issue was located and resolved from the comments above...thanks to any and all that pressed on to sort it out.....grateful as always to everyone continuing to improve the software....

**Closed** 2020-06-25 15:58 UTC
Labels: bug: pending
