### ISSUE TITLE
3.4.0 does not work on windows 10 on several PC

### ISSUE THREAD

**Issue by andreilabato** [darktable-org/darktable#7512] opened 2020-12-28 09:11 UTC
**Describe the bug**
being admin, I installed DT 3.4.0 on DT 3.2.1 with uninstall previous version selected. Launching DT 3.4 with same user after install, black startup window appears then close without error.

**To Reproduce**
this behavior has been reproduced by other persons as reported on french DT forum
https://forums.darktable.fr/showthread.php?tid=5482

**Expected behavior**
I expect that as in DT 3.2.1, after the black lauch window close, another white window open to start DT.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Windows 10=>Version: 20H2- installed 18/08/2020. Version OS: 19042.685. Experience: windows feature experience pack 120.2212.551.0
 - OpenCL activated 
 - graphics card: Nvidia GeForce GTx 745 -driver 26.21.14.3107
 - Processeur Intel® Core™ i7-4790 CPU @ 3.60GHz  3.60 GHz
 - installed memory 16,0 Go
 - operating system 64 bits

**Additional context**
 - Can you reproduce with another Darktable version?=> DT 3.2.1 can be reinstalled after without any problem
 - Is the issue still present using an empty/new config-dir=>Yes. I deleted C:\users\xxx\AppData\Local\darktable. darktable folder has been created but remained empty.

**Comment by johnny-bit** [comment] 2020-12-28 09:56
There has to be some crash report or something, because without those we're essentially running blind.

Please look for any files after 3.4 crash in `C:\Users\username\AppData\Local\Microsoft\Windows\Temporary Internet Files\darktable\` and/or in `C:\Users\username\AppData\Local\Temp\darktable-*`

We need those to even begin investigation.

**Comment by andreilabato** [comment] 2020-12-28 10:17
in C:\Users\username\AppData\Local\Temp there is no darktable pre-fixed file, neither darktable folder
C:\Users\username\AppData\Local\Microsoft\Windows\Temporary Internet Files is a shortcut that cannot be reached. This shortcut has been created 18/8/2020=>linked to Win 10 update????

**Comment by andreilabato** [comment] 2020-12-28 10:38
did some tests launching exe:
C:\Program Files\darktable\bin>darktable-cli.exe
darktable.configdir: directory 'C:\Users\username\AppData\Local\darktable' fails to open.'

C:\Program Files\darktable\bin>darktable-cltest.exe
darktable.configdir: directory 'C:\Users\username\AppData\Local\darktable' fails to open.'

C:\Program Files\darktable\bin>darktable-generate-cache.exe
darktable.configdir: directory 'C:\Users\username\AppData\Local\darktable' fails to open.'

**Comment by johnny-bit** [comment] 2020-12-28 10:55
does "username" have any diacritic/special characters in them?

**Comment by andreilabato** [comment] 2020-12-28 11:02
yes I believe. 
My username is C:\Users\andré\AppData\Local\darktable 
which is coded by windows: C:\Users\andr├®\AppData\Local\darktable

**Comment by johnny-bit** [comment] 2020-12-28 11:10
then we're missing some path widening somewhere :/

**Comment by andreilabato** [comment] 2020-12-28 11:14
problem did not appear in previous DT versions I have been using for 2 years now. May be this info could help identify impacted new code...

**Comment by johnny-bit** [comment] 2020-12-28 11:20
there are over 2000 commits to darktable since 3.2.1 so it might be hard to identify actually ;) darktable needs more windows devs (or even testers testing dev versions on path with weird characters) to be able to spot (and fix) issues before release...

**Comment by andreilabato** [comment] 2020-12-28 11:24
I confirm that on same PC, using another username without special character (Corine), DT 3.4.0 starts correctly

**Comment by johnny-bit** [comment] 2020-12-28 11:28
Probably the change that introduced problem was PR #5086 - that was the change that I see that could affect paths...

Pingign @codingdave

**Comment by johnny-bit** [comment] 2020-12-28 12:35
Duplicate of #7489

**Comment by johnny-bit** [comment] 2020-12-28 12:35
Hey @andreilabato - If you don't mind I'll close this in favour of #7489 - it's essentially the same issue. Let's continue there, OK?

**Closed by johnny-bit** 2020-12-28 12:35 UTC
Labels: scope: OS support

**Comment by codingdave** [comment] 2020-12-28 14:43
Can anyone having this issue please start darktable from the console providing the `-d dev` switch?

FILE_ATTRIBUTE_DIRECTORY
