### ISSUE TITLE
Right clicking on parametric mask values should open the fine tuning dialog

### ISSUE THREAD

**Issue by darkbasic** [darktable-org/darktable#12980] opened 2022-11-24 09:29 UTC
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/1047358/203746599-892ad54a-a089-4982-920c-bd4d99258cda.png)

Right clicking on parametric mask values doesn't open the dialog to fine-tune the value or enter a specific numeric value. For consistency it should do so, like when you right click on the boost factor.

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/1047358/203747009-dffaa3f6-047a-4dca-b0a8-2e5ce72ba437.png)

It should open the fine-tuning dialog like when you right click on the boost factor.

**Alternatives**

**Additional context**

**Comment by TurboGit** [comment] 2022-11-24 14:48
> For consistency it should do so

The fine tune control is for sliders, so here I do not see consistency as an issue.

**Comment by darkbasic** [comment] 2022-11-24 14:50
> The fine tune control is for sliders, so here I do not see consistency as an issue.

With sliders you can't input a value with your keyboard.

**Comment by darkbasic** [comment] 2022-11-24 14:51
You even have a picker which tells you which values you are sampling and then you have to move a slider to set them: keyboard would be much more effective.

**Comment by TurboGit** [comment] 2022-11-24 14:52
> With sliders you can't input a value with your keyboard.

Sure you can!

**Comment by darkbasic** [comment] 2022-11-24 14:53
> The fine tune control is for sliders

By the way this is also a slider: a range slider but still a slider.

**Comment by darkbasic** [comment] 2022-11-24 14:53
> Sure you can!

Sorry I meant with the **range** sliders.

**Comment by darkbasic** [comment] 2022-11-24 14:58
I think I've created some confusion: `boost factor` is a slider and you can right click it to manually insert a value with the keyboard.
Input is a **range** slider and you can't do so.

**Comment by darkbasic** [comment] 2022-11-24 14:59
What I suggest is opening the same dialog that you open when right clicking on normal sliders whenever you right click on the four values (0.30 0.42 0.55 0.68) of the range slider. Right clicking on the range slider itself should have no effect.

**Comment by dterrahe** [comment] 2022-11-24 18:30
Please consider that some of the "obvious" ideas may not have been implemented because technically they are not so trivial. The "bauhaus" slider pop-up code is tightly integrated with the slider code itself so cannot be easily transplanted to range sliders. Moving _one_ of the sliders could also move (or be restricted by) the other sliders and making sure the markers overlay the normal non-pop-up markers, so there are no unwanted jumps, is a separate, again non-trivial, problem. Besides, it has been suggested regularly that range sliders should be redesigned/replaced completely, which would make this effort a waste.

You might want to consider that making suggestions like these is really about motivating individuals to do work _you_ may find worthwhile whereas _they_ may not be convinced (yet). Strategies that generally have been shown to be less effective are trivialising and shaming. They may actually put people off getting involved.

**Comment by darkbasic** [comment] 2022-11-24 18:59
> Strategies that generally have been shown to be less effective are trivialising and shaming

I don't know where you actually got the idea that I was trying to trivialize the issue or shame someone. There has been some confusion because we were talking about different sliders but it was never my intention to trivialize anything.

**Comment by darkbasic** [comment] 2022-11-24 19:06
> Moving one of the sliders could also move (or be restricted by) the other sliders and making sure the markers overlay the normal non-pop-up markers, so there are no unwanted jumps, is a separate, again non-trivial, problem

This shouldn't be too difficult to solve: I've coded a similar range slider for Angular Material a couple of years ago and it's just a matter of either limiting the minimum and maximum values to the boundaries set by the other sliders or setting the outer/inner slider to the same value of the one you are modifying.

Please don't take this as an attack or an attempt to minimize the issue, I'm just trying to give my two cents.

**Comment by dterrahe** [comment] 2022-11-24 19:10
> I don't know where you've got the idea

I didn't. Those comments were general ones. The first sentence of my reply applies here. Your suggestion has been discussed regularly (you could not know this! Unless you've been following dt dev channels for a while) and hasn't been picked up (yet?) for the reasons I mentioned. If you want to change this, I've tried to help by pointing out what you'd have to (and should not) do.

**Comment by dterrahe** [comment] 2022-11-24 19:18
> This shouldn't be too difficult to solve

> Please don't take this as an attack or an attempt to minimize the issue

Hm...

**Comment by darkbasic** [comment] 2022-11-24 19:29
@dterrahe you've listed **several** issues which could prevent such a fix from landing and I've gave you my two cents about **one** of them which I've already implemented in a similar component. If GTK somehow makes it more difficult please tell me why, otherwise I see no point in whatever you're trying to achieve. I'm not asking anybody to code anything for me, I'm reporting what in my opinion should be a desirable feature and I'm trying to get some feedback whether this should be implemented and how. I appreciate your feedback

**Comment by darkbasic** [comment] 2022-11-24 19:32
> Hm...

@dterrahe you've listed **several** issues which could prevent such a fix from landing and I've gave you my two cents about **one** of them which I've already implemented in a similar component. If GTK somehow makes it more difficult please tell me why, otherwise I see no point in whatever you're trying to achieve. I'm not asking anybody to code anything for me, I'm reporting what in my opinion should be a desirable feature and I'm trying to get some feedback whether this should be implemented and how. I appreciate your technical feedback but at this point I'm also feeling personally attacked.

**Comment by dterrahe** [comment] 2022-11-24 19:42
> I'm also feeling personally attacked.

?

I've said that this suggestion has been made before so that probably quite a few people would appreciate your contribution when it is submitted. You need no further approval in advance.

What did you expect exactly?

**Comment by darkbasic** [comment] 2022-11-24 19:48
First you suggest that I might get better results by not trivializing issues and shaming people, then I ask you to please not get offended if I disagree with one of your points and you accuse me once again of trivializing. That I didn't expect, everything else was fine.

**Comment by elstoc** [comment] 2022-11-25 22:53
This is a duplicate of https://github.com/darktable-org/darktable/issues/6695

**Comment by elstoc** [comment] 2022-11-25 23:04
> This shouldn't be too difficult to solve: I've coded a similar range slider for Angular Material a couple of years ago and it's just a matter of either limiting the minimum and maximum values to the boundaries set by the other sliders or setting the outer/inner slider to the same value of the one you are modifying whenever you go off range.

I'm sure others would be interested in a solution, if you think you could implement one. The problem is likely less that no developer wants it and more that no developer wants it _enough_ to do the work required to implement it. As an alternative I currently use right-click on the slider followed by Ctrl+scroll to do finer-scale adjustments. While the popup would be nice, this solution is sufficient for me.

**Comment by Nilvus** [comment] 2022-11-26 10:45
I close this issue as it's a duplicate. No need to have 2 FR for same thing. All those comments remains interesting and now this is link to #6695.

**Closed by Nilvus** 2022-11-26 10:45 UTC
