### ISSUE TITLE
Innacurate cropping behaviour

### ISSUE THREAD

**Issue by bug2k19** [darktable-org/darktable#9069] opened 2021-05-26 11:27 UTC
Darktable 3.4.1 with a scan of a photo, I zoom in to 100% and use the crop/rotate module to straighten and crop to the picture. When I then close the crop module the crop changes and is no longer lined up how I set it. If I also zoom out to fit the entire photo  on screen, the crop changes again and not where it was originally set.

The effect seems worse when the preview resolution is set to 1/4 instead of 'original' but is still present.

I've tried it on the latest git version (3.5.0+2362~gc89f6bace) and the issue is still present. It's interesting that it does not noticably happen with all images, I ran through 3 on the git version and looked like it had been fixed, the next one had the same issues as above. I've just ran through some more on the current 3.4.1 build and after a few more images the issue still seems to be present even with 'original' selected for preview image

Here is a screenshot of the crop on one of the images:
![dt_crop1](https://user-images.githubusercontent.com/50246800/119651988-7dde9400-be1d-11eb-849a-6671f651e3ab.jpg)

This is what it looks like when the crop/rotate module is closed:
![dt_crop2](https://user-images.githubusercontent.com/50246800/119652015-833bde80-be1d-11eb-8359-47623678b61a.jpg)

..and when zoomed fully out:
![dt_crop3](https://user-images.githubusercontent.com/50246800/119652035-88992900-be1d-11eb-82b8-0d30ddbe7a47.jpg)

I note that when zoomed to 100%, using the arrow keys to scroll up/down the image the crop appears to change with each key press.

This computer is running a 4K screen with 175% scaling set in the KDE display section.

Again this issue does not seem consistent, it does not noticably happen with every image, on some it is more obvious than others.

* darktable version : 3.4.1  and  3.5.0+2362~gc89f6bace
* OS                : Linux - kernel 5.12.6
* Linux - Distro    :  Arch
* Memory            :  32GB
* Graphics card     :  AMD RX580
* Graphics driver   : amdgpu
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : 1.20.11
* Desktop           :  KDE

**Comment by AlicVB** [comment] 2021-05-26 11:43
hmmm I've just tried on several images and I can't reproduce...
Some questions : 
1. as you use git master, can you try the new "crop" module and see if it has the same issue (I think so, but better check it)
2. in your second image, the white and black borders are part of the uncropped image or are garbage from outside the image ?
3. by any chance, can you try to reproduce with non-hdpi scaling ?

thanks in advance !

**Comment by bug2k19** [comment] 2021-05-26 12:38
I've tried the new crop module and the result is the same.
The white should be the outer white border of the photograph which was on the edge of the scan bed, the black is outside of the original full size image.
I've disabled desktop scaling and the result is the same. I've also tried on the same machine with the Openbox window manager and the result is the same.
Testing this with the option 'reduce resolution of preview image' set to 1/4 makes the effect much more noticable, but again not on every image.
Thanks.

**Comment by ralfbrown** [comment] 2021-05-26 14:46
I've never seen anything like this in dt, but since you are talking about scanned images -- what file format?  I'm thinking in particular that TIFF files allow virtual borders, i.e. their header can specify that the image is 200x200 located at position 50,100 within a canvas of size 400x500.

**Comment by bug2k19** [comment] 2021-05-26 19:16
Yes, they are tiff files, created with Vuescan. I've been working on some of these for a couple of weeks on my laptop and not had any issues. It was only when I started working on them with my desktop computer that I noticed the issue.

**Comment by johnny-bit** [comment] 2021-06-19 10:58
would you be able to post sample files for analysis?

**Comment by johnny-bit** [comment] 2021-07-20 06:56
understood unclear. closing.

Please send reguested samples for analysis and the issue will be reopened.

**Closed by johnny-bit** 2021-07-20 06:56 UTC
Labels: no-issue-activity, understood: unclear
