### ISSUE TITLE
[3.2.1] Lighttable: thumbnails not displayed in Retina/HiDPI resolution

### ISSUE THREAD

**Issue by arru** [darktable-org/darktable#6312] opened 2020-09-16 19:52 UTC
**Describe the bug**
Since 3.2.1., the lighttable does no longer display thumbnails in Retina/HiDPI resolution, and there is no apparent way to configure this either.

**To Reproduce**
1. Wipe Darktable config dir clean
1. Install a fresh 3.2.1. Mac OS X build on a machine with Retina monitor
1. Import some images

**Expected behavior**
On the two test machines I'm using (see below), Darktable _3.0.2._ displays thumbnails in full resolution supported by hardware. 

**Observed behavior**
* Thumbnails appear pixelated (possibly also not correctly interpolated, looks like nearest neighbor)
* Problem also appears on culling view and timeline (even at full size in those views)
* Changing _GUI thumbs and previews DPI scaling factor_ setting does not remedy this
* Problem seems to affect only thumbnails and thumbnail-derived image views: the rest of the UI and _darkroom image correctly displays Retina/HiDPI resolution_

**Screenshots**
Note difference in resolution between UI widgets and thumbnails.

![thumbnail quality](https://user-images.githubusercontent.com/536156/93384782-95fd1d00-f865-11ea-98b8-87c093b554d1.png)

**Platform (please complete the following information):**
 - Darktable Version:  3.2.1.
 - OS: Mac OS X 10.15.5
 - Issue appears whether OpenCL is on or off

Test machine A: 2014 27" iMac Retina 5K - AMD Radeon R9 M295X 4 GB
Test machine B: 2019 15" MacBook Pro - Intel UHD Graphics 630 1536 MB

**Additional context**

**Comment by parafin** [comment] 2020-09-16 20:26
Duplicate of #5947, which is already fixed in master (hopefully).

**Closed by parafin** 2020-09-16 20:26 UTC
