### ISSUE TITLE
crop and rotate - inaccurate aspect ratio

### ISSUE THREAD

**Issue by caiux** [darktable-org/darktable#7465] opened 2020-12-26 14:59 UTC
**Describe the bug**
The aspect ratio of the exported image is off by less that one percent or so, meaning that a squared image is not squared. Same behaviour for any aspect ratio.

**To Reproduce**
It is hard to reproduce. It appears when cropping/rotating images, but may also depend on the actual workflow, or to the use of decrease resolution for previewing images. In the screenshot below, from left to right:

1. Crop of the original image (no rotation, full resolution preview)
2. Crop of the original image (no rotation, 1/4 resolution preview)
3. Crop after rotattin by 0.95 degrees (1/4 resolution preview)

**Expected behavior**
Aspect ratio is exact (plus/minus one pixel for non integer ratio)

**Screenshots**

![Screenshot 2020-12-26 at 14 55 13](https://user-images.githubusercontent.com/10013246/103153763-b7d23e00-478a-11eb-879e-21d3d4ec0695.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: macos Catalina 10.15.7

**Additional context**
May have been present in previous versions.

**Comment by Nilvus** [comment] 2021-06-20 21:08
Many bugs have been fixed in actual master. And some about ratios and percent minor error. So this is now probably fixed. On my side, exports are good and I can't reproduce (in actual master, so future darktable 3.6). darktable 3.6 will be out in about 2 weeks.
I close this one as it is probably fixed. Feel free to reopen (or ask for it) if you reproduce with darktable 3.6 when you will have it. Of course, provide as much infos as you can to explain your tests and the best way to reproduce.

**Closed by Nilvus** 2021-06-20 21:08 UTC
Labels: no-issue-activity
