### ISSUE TITLE
Sony ILCE-6100

### ISSUE THREAD

**Issue by dabba17** [darktable-org/darktable#4604] opened 2020-04-04 11:38 UTC
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment] 2020-04-04 11:39
Duplicate of #4589

**Closed by LebedevRI** 2020-04-04 11:39 UTC
Labels: scope: camera support
