### ISSUE TITLE
OpenCL priority not working for multiple GPUs

### ISSUE THREAD

**Issue by rajkhand** [darktable-org/darktable#10216] opened 2021-10-17 05:53 UTC
I run this command
`darktable-cli arecibo.orf arecibo.orf.xmp test.jpg --core -d perf -d opencl`

following is the relevant output

    ```
0.021208 [opencl_init] opencl_scheduling_profile: 'default’
    0.021210 [opencl_init] opencl_library: ‘’
    0.021212 [opencl_init] opencl_memory_requirement: 768
    0.021213 [opencl_init] opencl_memory_headroom: 400
    0.021215 [opencl_init] opencl_device_priority: '!Intel(R) UHD Graphics 630 [0x3e92],/!Ellesmere,/Ellesmere,/Ellesmere,/*'

    0.317430 [opencl_priorities] these are your device priorities:
    0.317432 [opencl_priorities] image preview export thumbs preview2
    0.317437 [opencl_priorities] 0 0 0 0 0
    0.317442 [opencl_priorities] 1 1 1 1 1
    0.317446 [opencl_priorities] show if opencl use is mandatory for a given pixelpipe:
    0.317448 [opencl_priorities] image preview export thumbs preview2
    0.317451 [opencl_priorities] 0 0 0 0 0

    8.912390 [dev_process_export] pixel pipeline processing took 7.339 secs (8.153 CPU)
    [export_job] exported to test.jpg' 9.465691 [opencl_summary_statistics] device 'Intel(R) UHD Graphics 630 [0x3e92]' (0): 221 out of 221 events were successful and 0 events lost 9.467400 [opencl_summary_statistics] device 'Ellesmere' (1): NOT utilized 8.912390 [dev_process_export] pixel pipeline processing took 7.339 secs (8.153 CPU) [export_job] exported to test.jpg’
    9.465691 [opencl_summary_statistics] device ‘Intel(R) UHD Graphics 630 [0x3e92]’ (0): 221 out of 221 events were successful and 0 events lost
    9.467400 [opencl_summary_statistics] device ‘Ellesmere’ (1): NOT utilized
```

**Comment by gh-cnj** [comment] 2021-11-14 22:01
With the MacOS build, something definitely changed from 3.4 to 3.6…  I'd reverted to 3.4, but with Monterey, that no longer appears to support OpenCL acceleration(?).  With 3.6, I tried the same config, and then a fresh config with manual preferences, and then trying changing from "default" to the "very fast gpu" option; in all cases, only the first graphics card appears to be being used (which happens to be the integrated Iris graphics, rather than the Radeon or an eGPU).

0.172245 [opencl_init] opencl: 1
0.172246 [opencl_init] opencl_scheduling_profile: 'very fast GPU'
0.172248 [opencl_init] opencl_library: ''
0.172250 [opencl_init] opencl_memory_requirement: 768
0.172252 [opencl_init] opencl_memory_headroom: 400
0.172253 [opencl_init] opencl_device_priority: '2,1/2,1/2,1/2,1/2,1'
0.193152 [opencl_init] discarding CPU device 0 `Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz'.
0.193189 [opencl_init] device 1 `Intel(R) UHD Graphics 630' supports image sizes of 16384 x 16384
0.193197 [opencl_init] device 1 `Intel(R) UHD Graphics 630' allows GPU memory allocations of up to 384MB
[opencl_init] device 1: Intel(R) UHD Graphics 630
     GLOBAL_MEM_SIZE:          1536MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
     DRIVER_VERSION:           1.2(Oct 14 2021 00:50:32)
     DEVICE_VERSION:           OpenCL 1.2
…
0.210819 [opencl_init] device 2 `AMD Radeon Pro 5500M Compute Engine' supports image sizes of 16384 x 16384
0.210821 [opencl_init] device 2 `AMD Radeon Pro 5500M Compute Engine' allows GPU memory allocations of up to 2044MB
[opencl_init] device 2: AMD Radeon Pro 5500M Compute Engine
     GLOBAL_MEM_SIZE:          8176MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
     DRIVER_VERSION:           1.2 (Oct 14 2021 00:44:05)
     DEVICE_VERSION:           OpenCL 1.2
1.163698 [opencl_init] OpenCL successfully initialized.
1.163699 [opencl_init] here are the internal numbers and names of OpenCL devices available to darktable:
1.163701 [opencl_init]          0       'Intel(R) UHD Graphics 630'
1.163702 [opencl_init]          1       'AMD Radeon Pro 5500M Compute Engine'
1.163703 [opencl_init] FINALLY: opencl is AVAILABLE on this system.
1.163704 [opencl_init] initial status of opencl enabled flag is ON.

1.165468 [opencl_priorities] these are your device priorities:
1.165469 [opencl_priorities]            image   preview export  thumbs  preview2
1.165470 [opencl_priorities]            0       0       0       0       0
1.165472 [opencl_priorities]            1       1       1       1       1
1.165473 [opencl_priorities] show if opencl use is mandatory for a given pixelpipe:
1.165474 [opencl_priorities]            image   preview export  thumbs  preview2
1.165475 [opencl_priorities]            1       1       1       1       1





0.134855 [opencl_init] opencl: 1
0.134856 [opencl_init] opencl_scheduling_profile: 'very fast GPU'
0.134858 [opencl_init] opencl_library: ''
0.134860 [opencl_init] opencl_memory_requirement: 768
0.134862 [opencl_init] opencl_memory_headroom: 400
0.134863 [opencl_init] opencl_device_priority: '*/!0,*/1,0*/*/!0,*'
0.134866 [opencl_init] opencl_mandatory_timeout: 200
0.134868 [opencl_init] opencl_size_roundup: 16
0.134869 [opencl_init] opencl_async_pixelpipe: 0
0.134871 [opencl_init] opencl_synch_cache: active module
0.134873 [opencl_init] opencl_number_event_handles: 25
0.134875 [opencl_init] opencl_micro_nap: 1000
0.134876 [opencl_init] opencl_use_pinned_memory: 0
0.134877 [opencl_init] opencl_use_cpu_devices: 0
0.134879 [opencl_init] opencl_avoid_atomics: 0
0.134880 [opencl_init]
0.134996 [opencl_init] found opencl runtime library '/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL'
0.135018 [opencl_init] opencl library '/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL' found on your system and loaded
0.135022 [opencl_init] found 1 platform
0.150988 [opencl_init] found 3 devices
0.151016 [opencl_init] discarding CPU device 0 `Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz'.
0.151032 [opencl_init] device 1 `Intel(R) UHD Graphics 630' supports image sizes of 16384 x 16384
0.151041 [opencl_init] device 1 `Intel(R) UHD Graphics 630' allows GPU memory allocations of up to 384MB
[opencl_init] device 1: Intel(R) UHD Graphics 630
     GLOBAL_MEM_SIZE:          1536MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
     DRIVER_VERSION:           1.2(Oct 14 2021 00:50:32)
     DEVICE_VERSION:           OpenCL 1.2
0.161585 [opencl_init] device 2 `AMD Radeon Pro 5500M Compute Engine' supports image sizes of 16384 x 16384
0.161588 [opencl_init] device 2 `AMD Radeon Pro 5500M Compute Engine' allows GPU memory allocations of up to 2044MB
[opencl_init] device 2: AMD Radeon Pro 5500M Compute Engine
     GLOBAL_MEM_SIZE:          8176MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
     DRIVER_VERSION:           1.2 (Oct 14 2021 00:44:05)
     DEVICE_VERSION:           OpenCL 1.2
1.097480 [opencl_init] here are the internal numbers and names of OpenCL devices available to darktable:
1.097481 [opencl_init]          0       'Intel(R) UHD Graphics 630'
1.097482 [opencl_init]          1       'AMD Radeon Pro 5500M Compute Engine'
1.097483 [opencl_init] FINALLY: opencl is AVAILABLE on this system.
1.097484 [opencl_init] initial status of opencl enabled flag is ON.
1.098570 [opencl_priorities] these are your device priorities:
1.098571 [opencl_priorities]            image   preview export  thumbs  preview2
1.098572 [opencl_priorities]            0       0       0       0       0
1.098573 [opencl_priorities]            1       1       1       1       1
1.098574 [opencl_priorities] show if opencl use is mandatory for a given pixelpipe:
1.098575 [opencl_priorities]            image   preview export  thumbs  preview2
1.098576 [opencl_priorities]            1       1       1       1       1

0.146387 [opencl_init] opencl_device_priority: '*/!0,*/2,1,0*/*/!0,*'
0.146570 [opencl_init] found 1 platform
0.160782 [opencl_init] found 3 devices
0.160811 [opencl_init] device 0 `Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz' supports image sizes of 8192 x 8192
0.160813 [opencl_init] device 0 `Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz' allows GPU memory allocations of up to 16384MB
11.201460 [opencl_init] device 1 `Intel(R) UHD Graphics 630' supports image sizes of 16384 x 16384
11.201462 [opencl_init] device 1 `Intel(R) UHD Graphics 630' allows GPU memory allocations of up to 384MB
[opencl_init] device 1: Intel(R) UHD Graphics 630
     GLOBAL_MEM_SIZE:          1536MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
     DRIVER_VERSION:           1.2(Oct 14 2021 00:50:32)
     DEVICE_VERSION:           OpenCL 1.2
11.212744 [opencl_init] device 2 `AMD Radeon Pro 5500M Compute Engine' supports image sizes of 16384 x 16384
11.212746 [opencl_init] device 2 `AMD Radeon Pro 5500M Compute Engine' allows GPU memory allocations of up to 2044MB
[opencl_init] device 2: AMD Radeon Pro 5500M Compute Engine
     GLOBAL_MEM_SIZE:          8176MB
     MAX_WORK_GROUP_SIZE:      256
     MAX_WORK_ITEM_DIMENSIONS: 3
     MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
     DRIVER_VERSION:           1.2 (Oct 14 2021 00:44:05)
     DEVICE_VERSION:           OpenCL 1.2
14.641327 [opencl_init] OpenCL successfully initialized.
14.641328 [opencl_init] here are the internal numbers and names of OpenCL devices available to darktable:
14.641329 [opencl_init]         0       'Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz'
14.641331 [opencl_init]         1       'Intel(R) UHD Graphics 630'
14.641332 [opencl_init]         2       'AMD Radeon Pro 5500M Compute Engine'
14.641333 [opencl_init] FINALLY: opencl is AVAILABLE on this system.
14.641334 [opencl_init] initial status of opencl enabled flag is ON.
15.441499 [opencl_init] benchmarking results: 0.135012 seconds for fastest GPU versus 0.130938 seconds for CPU.
15.441507 [opencl_init] due to a slow GPU the opencl flag has been set to OFF.
15.441548 [opencl_priorities] these are your device priorities:
15.441550 [opencl_priorities]           image   preview export  thumbs  preview2
15.441566 [opencl_priorities]           0       0       0       0       0
15.441568 [opencl_priorities]           1       1       1       1       1
15.441569 [opencl_priorities]           2       2       2       2       2
15.441570 [opencl_priorities] show if opencl use is mandatory for a given pixelpipe:
15.441595 [opencl_priorities]           image   preview export  thumbs  preview2
15.441598 [opencl_priorities]           1       1       1       1       1


Regardless of the settings, the opencl_priorities ends-up in increasing order from device 0.  This includes "default":
0.156231 [opencl_init] opencl_scheduling_profile: 'default'
0.156232 [opencl_init] opencl_library: ''
0.156234 [opencl_init] opencl_memory_requirement: 768
0.156236 [opencl_init] opencl_memory_headroom: 400
0.156237 [opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'

**Comment by MStraeten** [comment] 2021-11-15 09:50
unfortunately macos changes several stuff with each release. 
At least for a MacbookPro 16 (2019) with internal AMD Radeon Pro 5500M OpenCL is supported with onCPU GPU and dedicated GPU with darktable 3.6 with monterey.
If you want to use both GPU then you'd better stay with default setting because "very fast gpu" sends everything to the dedicated gpu. The device priority setting is only valid for "default"

did you override "opencl_device_priority" settings?

**Comment by gh-cnj** [comment] 2021-11-15 15:12
I believe I stand corrected…  it looks like the  actual default setting is now "multiple GPUs" rather than "default", if  I removed the existing config (rm ~/.config/darktable/darktablerc) and this is from where my confusion stemmed.

Indeed, if I restart, and change the configuration manually to "default" and enable opencl, I see the expected interpretation of the priorities…

0.287299 [opencl_priorities]            image   preview export  thumbs  preview2
0.287301 [opencl_priorities]            0       1       0       0       1
0.287303 [opencl_priorities]            1       -1      1       1       -1
0.287305 [opencl_priorities] show if opencl use is mandatory for a given pixelpipe:
0.287307 [opencl_priorities]            image   preview export  thumbs  preview2
0.287309 [opencl_priorities]            0       0       0       0       0

…  thanks for pointing-out the PEBKAC issue.

**Comment by johnny-bit** [comment] 2022-01-15 09:44
> Indeed, if I restart, and change the configuration manually to "default" and enable opencl, I see the expected interpretation of the priorities…

Closing since works as intended :)

**Closed by johnny-bit** 2022-01-15 09:44 UTC
Labels: bug: invalid, scope: hardware support
