### ISSUE TITLE
Contrast equalizer: lags when dragging 

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#3674] opened 2019-12-06 19:32 UTC
In dt 3.0.0rc2+66~gee083f665
Expand contrast equalizer.
Grab one of the nodes (indicated by a circle)
using left-mouse-click and drag it up then down
then up again. The motion and update is not fluid (as expected),
but very jumpy. openCL on or off makes no difference.

**Platform:**
Latest Manjaro/KDE. Ryzen 3900X. GTX-1660. Nvidia.

**Comment by AxelG-DE** [comment] 2019-12-07 20:50
With OpenCL working, I cannot confirm. Very smooth. CPU (9900K) loads 14-20% and nvidia-smi shows me 85% on device0 and ~35% on device1.

Then I started dt with --disable-opencl. CPU is loaded ~85% and the behaviour is like you explained above.

Are you sure, your opencl works really propperly? (watch nvidia-smi)
I have had performance issues, when you had an driver update but not yet rebooted, for instance

**Comment by ClaesGitHub** [comment] 2019-12-08 10:13
> Does my openCL work properly?
I believe that it does work correctly. Using the dt benchmark my present clockings are 2.879 seconds (with openCL) versus 8.404 seconds (without openCL).

**Comment by AxelG-DE** [comment] 2019-12-08 11:44
As you have a specific issue now, I would recommend not to use that benchmark to check, as it uses darktable-clip, which potentially could react differently.

So I suggest, you open a terminal window, start _watch nvidia-smi_ and observe it, while you drag the equaliser node.

**Comment by ClaesGitHub** [comment] 2019-12-08 13:42
Nice idea :-) Thank you -- but the output looks normal to me.

**Comment by AxelG-DE** [comment] 2019-12-08 22:07
Darned...
May I kindly ask, what you consider "normal" in that respect? 

Why I feel some similarities to #2724? Just now it is you instead of me? :-/  :)

**Comment by aurelienpierre** [comment] 2019-12-14 04:30
The contrast equalizer, like the curves, redraw the graph after the pipe is recomputed, and the pipe is recomputed every time you touch the settings. It's just a matter of inverting the sequence. In tone equalizer, the graph is drawn before the pipe is recomputed, maybe you can test and see if it feels more responsive.

**Comment by upegelow** [comment] 2019-12-14 07:57
> The contrast equalizer, like the curves, redraw the graph after the pipe is recomputed, and the pipe is recomputed every time you touch the settings. It's just a matter of inverting the sequence. In tone equalizer, the graph is drawn before the pipe is recomputed, maybe you can test and see if it feels more responsive.

That's probably the cause of this issue. I have experienced similar problems when developing the parametric masks feature some time ago. The gradientsliders would also act very bumpily. The solution has been to emit the value changed signal not with every mouse moved event but only with some heuristically chosen delay. The pixelpipe calculation is anyhow too slow to reprocess everything each time.

https://github.com/darktable-org/darktable/blob/ceb3c9e43de38b6af422211fa12c86bf59ce128e/src/dtgtk/gradientslider.c#L278-L285

`darktable.develop->average_delay` stores a gliding average of the typical pixelpipe processing time.

**Comment by upegelow** [comment] 2019-12-15 20:46
Should be fixed now.

**Closed by upegelow** 2019-12-15 20:46 UTC

**Comment by AxelG-DE** [comment] 2020-01-03 22:48
> > The contrast equalizer, like the curves, redraw the graph after the pipe is recomputed, and the pipe is recomputed every time you touch the settings. It's just a matter of inverting the sequence. In tone equalizer, the graph is drawn before the pipe is recomputed, maybe you can test and see if it feels more responsive.
> 
> That's probably the cause of this issue. I have experienced similar problems when developing the parametric masks feature some time ago. The gradientsliders would also act very bumpily. The solution has been to emit the value changed signal not with every mouse moved event but only with some heuristically chosen delay. The pixelpipe calculation is anyhow too slow to reprocess everything each time.


Sorry digging up this closed issue, I am just wondering if similar thing might be the reason for #2724? I'd be so happy if WB would be responsive in the first place, even I start to learn to live with it...
