### ISSUE TITLE
Zooming out produces black artefacts

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#15416] opened 2023-10-14 16:19 UTC
### Describe the bug

When using ctrl+scroll to zoom out, if _rotate and perspective_ is used with cropping, black areas show up.

### Steps to reproduce

1. Get the image and sidecar from https://tech.kovacs-telekes.org/files/2023-10-14-zoom-out/
2. Zoom in/out using Ctrl+wheel. For maximum effect, zoom in strongly, move the preview area to the edge of the image, then zoom in.
3. Observe the artefacts.

### Expected behavior

Show no artefacts.

### Logfile | Screenshot | Screencast

https://tech.kovacs-telekes.org/files/2023-10-14-zoom-out/capture.mp4

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+908~g84906440ed

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Describe your system?

X11, Nvidia

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVidia 1060/6GB, 525.125.06

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Same behaviour with OpenCL on and off.
With OpenCL off, I get a huge log on the console, starting with:

    157.1727 [dt_interpolation_compute_pixel4c] problem at (607,252) in 25fx348  1157.1728 [dt_interpolation_compute_pixel4c] problem at (608,252) in 25fx348  1157.1728 [dt_interpolation_compute_pixel4c] problem at (609,251) in 25fx348  1157.1728 [dt_interpolation_compute_pixel4c] problem at (607,253) in 25fx348
    1157.1728 [dt_interpolation_compute_pixel4c] problem at (608,253) in 25fx348  1157.1728 [dt_interpolation_compute_pixel4c] problem at (609,253) in 25fx348  1157.1728 [dt_interpolation_compute_pixel4c] problem at (607,254) in 25fx348  1157.1729 [dt_interpolation_compute_pixel4c] problem at (608,254) in 25fx348

**Comment by jenshannoschwalm** [comment] 2023-10-14 20:38
1. Clearly a log formatting error here (missing newline and printing hex)
2. I recently added that debug log info, until then we silently wrote a zero. For some reason we are out of valid input data to do the pixelwise interpolation.

I tried here but can't reproduce so far. Could you check:
1. issue depending on any of the interpolators? (we had issues with lanc3 until recently)
2. depending on active modules (ashift or crop)?
3. depending on darkroom main window size or the border size?

**Comment by kofa73** [comment] 2023-10-15 06:46
This is how the log looks like on the screen:
![image](https://github.com/darktable-org/darktable/assets/3177739/64fd8cc8-492e-408b-9323-2c86e39118c2)

Interpolators were the default:
![image](https://github.com/darktable-org/darktable/assets/3177739/daa65b00-3242-4a30-95d2-3d95a4809aa7)

I get the same with both set to bilateral:
![image](https://github.com/darktable-org/darktable/assets/3177739/3a6ab07a-e779-4f1c-bf6c-d910af417d9e)

Same issue if I resize the window (from maximised on a 4K screen to small):
![image](https://github.com/darktable-org/darktable/assets/3177739/064eb77f-b908-4130-9b1b-3eced769b34d)

Simply turning off ashift (that's _rotate and perspective_, right?) produces:
![image](https://github.com/darktable-org/darktable/assets/3177739/ac0459fd-0168-46d3-8de9-f6c29e3d4990)

Then, zooming in/out:
![image](https://github.com/darktable-org/darktable/assets/3177739/f7f29bc4-7e47-49d2-9bea-ce56ba01c142)

There are no new log entries in the terminal, though.

Turning _rotate and perspective_ back on, with no cropping in the module produces interpolation error messages on the console. Zooming out fully only shows part of the image (compare the navigation preview with the editor preview -- this is with zoomed out as far as Ctrl+scroll goes):
![image](https://github.com/darktable-org/darktable/assets/3177739/6436330e-0de6-4f2f-a578-10bac249b524)

**Comment by kofa73** [comment] 2023-10-15 07:00
I'll try to bisect later today.

**Comment by pehar1** [comment] 2023-10-15 07:40
It took a while until I could reproduce... , about one minute of zooming and panning.
I could reproduce occasionally (very rare) if

- in "_Rotate and perspective_" "_Automatic cropping_" is set to "_Largest area_" or "_Original format_" (independent of interpolator used, checked _Lanczos3_, _Bilinear_ and _Bicubic_)
- the artefacts are dependent on the position of the mouse cursor on the canvas during CTRL-scrolling. Centering the mouse corsor on the canvas I never could reproduce, with positions near the edges it is much more likely. The black areas get larger the more one move the mouse cursor in the direction of the image corners during scrolling.


If I do not commit the "_Largest area_" cropping in "_Rotate and perspective_" and CTRL-scroll out, I get a very stange effect (possibly related) : 

Set image size to "_Fit_" (ALT-3)
![issue15416-fit](https://github.com/darktable-org/darktable/assets/104291381/27b349fc-e4d3-4a0d-b955-82ac058ba28d)

Move the mouse cursor clearly in the direction of the upper left corner, then CTRL-scroll out
![issue15416-cursor-top-left](https://github.com/darktable-org/darktable/assets/104291381/05bf28e3-59c0-4b3a-9e0e-ee37ce1ff0a9)

Set image size to "_Fit_" (ALT-3) again, then move the mouse cursor clearly in the direction of the bottom right corner, then CTRL-scroll out
![issue15416-cursor-bottom-right](https://github.com/darktable-org/darktable/assets/104291381/18037eb4-d281-4bd5-b43d-fec7126f88eb)

I could **not** reproduce if

- in "_Rotate and Perspective_" "_Automatic cropping_" is set to "_Off_" and cropping is done with module "_Crop_"

**Comment by kofa73** [comment] 2023-10-15 07:45
Thanks for confirming! Strangely though, I can reproduce this any time, with small or big window, with or without OpenCL.

**Comment by jenshannoschwalm** [comment] 2023-10-15 08:00
Ok, i can reproduce the log data (only reported if non-opencl).

I still can't confirm the artefacts though.

Please note while bisecting, don't care about the logs, that has been added recently.

**Comment by kofa73** [comment] 2023-10-15 09:24
kofa@eagle:~/darktable$ git bisect good
    09fa2c909b8a00a9648ed17d0550a2867a2b10e7 is the first bad commit
    commit 09fa2c909b8a00a9648ed17d0550a2867a2b10e7
    Author: Diederik ter Rahe <dterrahe@yahoo.com>
    Date:   Mon Oct 2 17:02:12 2023 -0400
    
        concentrate zoom handling in develop.c

**Comment by jenshannoschwalm** [comment] 2023-10-15 18:38
@dterrahe any quick idea on this ?

**Comment by dterrahe** [comment] 2023-10-15 19:26
> ### Steps to reproduce
> 1. Get the image and sidecar from https://tech.kovacs-telekes.org/files/2023-10-14-zoom-out/

Would you be able to provide a more minimal xmp (that doesn't give me a missing lut file error) to help speed up reproduction? Unless of course this _only_ happens with slow xmps (using multiple d&s instances).

> @dterrahe any quick idea on this ?

My first guess, if this only happens when the cursor is outside the image area while the zoom is adjusted, that the code that tries to keep the same point under the cursor is at fault. Or that the image doesn't get correctly repositioned afterwards. I'm currently working on deep further adjustments in this area, so rather than trying to fix this in code I'm about to replace anyway, I'd like to have a quick test case that I can use to verify that the new code doesn't suffer the same problem.

**Comment by jenshannoschwalm** [comment] 2023-10-15 19:39
Another idea here would be bad `roi_in` or `roi_out` resulting from slightly different scales. That might lead to out of bounds of output data ... i also couldn't reproduce yet, the logs are just misleading (as long as roi_in is correct but we can't test that in the interpolation function)

**Comment by pehar1** [comment] 2023-10-16 06:19
Removed all the "heavy" modules, removed "LUT 3D", removed "Color look up table", compressed history stack on kofa's xmp. Can still reproduce. Moving the mouse cursor outside the center (near edges) I can reproduce easier.
The attached xmp is **not** zipped, extension zip only added to be able to upload.
[2023-10-14_08-19-06_P1020106_01.RW2.xmp.zip](https://github.com/darktable-org/darktable/files/12912709/2023-10-14_08-19-06_P1020106_01.RW2.xmp.zip)

**Comment by kofa73** [comment] 2023-10-16 13:59
@dterrahe, @pehar1 : Sorry about the heavy modules. I've removed the old sidecar and uploaded a minimal one. As @pehar1 , the problem can be reproduced with the minimal set, too.

**Comment by dterrahe** [comment] 2023-10-16 14:24
@pehar1 thanks a lot!

Submitting clear bug reports like this, with easy ways to reproduce, whenever they encounter strange behavior in a development version, is one of the most helpful assistance users can provide to the project. You've directly helped to make the next release better.

I found the issue and implemented a fix that solves it with my testing. It will be included in a large intrusive PR that I'll hopefully submit today, but if it looks like that will take some time to merge I will also submit a separate PR just addressing this. Your feedback on the big PR would be appreciated though... ;-)

**Comment by dterrahe** [comment] 2023-10-16 14:37
Sorry @kofa73 ! I didn't mean to not mention you and hadn't seen your update before pressing send. What I said above of course was meant for both of you (and all other proactive testers). Many thanks again!

**Comment by kofa73** [comment] 2023-10-16 14:47
> Sorry @kofa73 ! I didn't mean to not mention you and hadn't seen your update before pressing send. What I said above of course was meant for both of you (and all other proactive testers). Many thanks again!

No worries, this is not a competition -- and @pehar1 _did_ improve on the original report - thanks! It's us users who have to thanks the devs (and it is in our own interest that reports are detailed, so fixes come quicker). :)

**Comment by todd-prior** [comment] 2023-10-16 18:11
@dterrahe  Just more of a comment but this issue made me think of it.... For some time now I have noticed what appears to be visible tiling or segmented processing in tiles of my screen while ctrl mouse scrolling... I have not changed any hardware. It could I suppose be some part of the more recent changes to opencl... i guess I should try this without.... In anycase I didn't note it in the past....I have a 3060TI and it never seemed to show this.... Its not an issue the image corrects but it is sort of visually distracting... is anyone aware of a change in the processing of screen previews that might have introduced that??  I'll try to capture it and take a small video and start a new topic just curious....

**Comment by kofa73** [comment] 2023-10-16 18:25
@todd-prior : I think you're seeing a new feature: https://github.com/darktable-org/darktable/blob/master/RELEASE_NOTES.md#performance-improvements
> When panning or zooming, a low resolution placeholder used to be shown until the image was fully recalculated. Now the part of the previous high quality preview that is still visible is moved or resized and only the edges are temporarily shown in low quality.

It does look a bit strange at times, even though it's supposed to be better than before.

**Comment by todd-prior** [comment] 2023-10-16 18:43
> @todd-prior : I think you're seeing a new feature: https://github.com/darktable-org/darktable/blob/master/RELEASE_NOTES.md#performance-improvements
> 
 
> It does look a bit strange at times, even though it's supposed to be better than before.


Hey thanks for digging that up. When it first started I thought there was maybe something wrong or some code that needed ironed out... That does sound like what I am seeing..... you are a great resouce as always...thx again

**Comment by todd-prior** [comment] 2023-10-16 19:52
Thanks for your reply and input. The very short answer is that I think I do remember and I think it was sort of accepted as it is normal for other programs to sort of freeze or blur and then update with the final image.... likely years of this behaviour... so the random tiles initially was a bit of a concern as I thought someting was wrong with my system or settings.... I will go home tonight and scroll around on a bunch of images.... perhaps the previous behaviour was not too bad for me as my 3060TI is fairly quick at updating but for others maybe this new approach is a better option??

**Comment by dterrahe** [comment] 2023-10-16 23:29
@kofa73 @pehar1 Would you be able to give #15436 a try please? It isn't complete yet (slidershow and, according to CI, export) doesn't work yet, so it is just about seeing how zooming/panning and switching between cropped/uncropped works for you.

**Comment by kofa73** [comment] 2023-10-17 05:05
Thanks! I can test it in the afternoon.

**Comment by kofa73** [comment] 2023-10-18 07:57
> @kofa73 @pehar1 Would you be able to give #15436 a try please?

Sorry about the delay, had a long day yesterday. I tested this morning and I can no longer reproduce this in the darkroom -- thanks!

**Comment by kofa73** [comment] 2023-10-18 08:14
> * were you aware that, before this change, when the amount of zoom was changed, the _whole_ image became temporarily low res, until after you stopped changing the zoom level when a new high resolution image was calculated and shown.

Yes.

> * did you prefer that behavior, even though for most of the screen you would see low res for longer?
> * do you think that was just because of habit or because it was more "even" or some other reason?
> * do you expect to get used to the new behavior and if so, do you think it will eventually feel "better"?

Yes, I think it's mostly the "uniformity" / "evenness", but also what I am used to. It may also have to do with the fact that when I stop dragging the image, there are changes and movement 'in the corner of my eye' (the newly visible parts along the edges).

**Closed** 2023-10-27 14:28 UTC
