### ISSUE TITLE
FR: color balance rgb: unique identification of shadows/midtones/highlights sliders

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9952] opened 2021-09-07 09:32 UTC
the sliders purpose of a shadows/midtones/highlights slider in color balance rgb dialog as well as the luminance/hue/chroma slider on 4 ways tab results from their gui position since they share the same name.

From a gui design point thats quite reasonable; regarding history stack tooltip and shortcuts this has weaknesses: The sliders aren't identificable. 
The NG Input allows to assign each slider to hardware sliders, so there's a new use case for identificable sliders not available at design time of the gui.

![image](https://user-images.githubusercontent.com/39386816/132319818-c36a861e-b878-4a7e-a90f-58dac2d0379b.png)

**Describe the solution you'd like**
use an additional unique name for defining NG shortcuts or history stack tooltip (from a UI aspect a quite more convincing solution)

**Alternatives**
quick&not-that-dirty working solution: using a unique name for each slider e.g. naming scheme 'x shadows' with x =c for chroma, s for saturation, b for brilliance 
(similar naming scheme for 4 ways tab sliders)

![image](https://user-images.githubusercontent.com/39386816/132319447-5963f389-737a-44d1-99c8-99407f2411b4.png)
_a pr for that is just a few mouseclicks away_ ;)

**Comment by dterrahe** [comment] 2021-09-07 10:16
The method to support this kind of situation is to provide a _section_ argument to the call to `dt_bauhaus_widget_set_label`.

This has been done in the original color balance and in the color calibration modules, so look there for inspiration.

This is a duplicate of #9736

**Comment by MStraeten** [comment] 2021-09-07 11:06
> so look there for inspiration.
unfortunately this is exceeds my programming skills - need to understand what exactly is happening there.
Just adding characters to a description for a quick&not-that-dirty working solution is just having luck with a try and error aproach ;)

**Comment by dterrahe** [comment] 2021-09-07 15:05
It is not that complicated.

Normally, `dt_bauhaus_slider_from_params` sets the label (and action name, which is used for QAP and shortcuts (and vimkeys and lua) from the $DESCRIPTION that is set in the params_t comment blocks. However, if the params fields are arrays, this step is skipped so that you can use something like `dt_bauhaus_widget_set_label(widget, N_("chroma"), N_("shadows"));`

In this case, params_t _doesn't_ contain arrays, so you'd have to manually temporarily disable generating labels. You can do this using a pair of 
```
++darktable.bauhaus->skip_accel
--darktable.bauhaus->skip_accel
```
statements.

Since this is all very repetitive for each parameter, and there are a lot of them, you might want to put this in a function or macro.

Converting params_t to contain arrays might still be handy (and it would help the descriptiveness of the history tooltip) but be careful because the order of fields in `chroma` is different from `saturation` and `brilliance` (and to fix that would require a different version of params.)

**Comment by MStraeten** [comment] 2021-09-07 18:48
I'm not sure if i understood what you tried to explain. 
Adding `dt_bauhaus_widget_set_label(g->chroma_midtones, N_("chroma"), N_("shadows"));` in the code after `g->chroma_shadows = dt_bauhaus_slider_from_params(self, "chroma_shadows");` results in an segfault, but `dt_bauhaus_widget_set_label(g->chroma_midtones, N_("c"), N_("shadows"));` is fine. 
Then i can assign an accel to the slider - but i don't like the idea to change stuff i really don't understand.

**Comment by dterrahe** [comment] 2021-09-07 19:16
I'll have a look

**Closed** 2021-09-09 09:37 UTC
Labels: feature: enhancement, scope: UI
