### ISSUE TITLE
Darktable si chiude da solo

### ISSUE THREAD

**Issue by Luisa92M** [darktable-org/darktable#16360] opened 2024-02-20 10:45 UTC
### Describe the bug

Nel momento in cui seleziono l'immagine da lavorare su Darktable e passo all'interfaccia "Camera Oscura", l'applicazione si chiude da sola senza nessun tipo di errore.

### Steps to reproduce

Carica l'immagine - Seleziona Immagine - Clicca su "Camera Oscura" 

### Expected behavior

Darktable dovrebbe farmi lavorare sull'immagine

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Home 23H2

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by victoryforce** [comment] 2024-02-20 11:01
@Luisa92M You have not provided any information that would allow us to reproduce your problem. It is clear that darktable does not crash on every file for all users. So it's clear that your problem is caused by a specific image file. You must provide this file, only then we can try to reproduce the crash and find the cause.

**Comment by victoryforce** [comment] 2024-02-26 22:38
@Luisa92M Closing this for now as there is no data to investigate. You can still provide the required data, the issue can be reopened.

**Closed by victoryforce** 2024-02-26 22:38 UTC
