### ISSUE TITLE
Add support for lua 5.4

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#5906] opened 2020-08-10 12:55 UTC
**Describe the bug**
darktable doesn't build with lua 5.4

**To Reproduce**
Try to build darktable 3.2 or master on Fedora 33 (rawhide).

**Comment by parafin** [comment] 2020-08-10 13:37
Who said it should? It’s not a bug.

**Comment by wpferguson** [comment] 2020-08-10 16:26
5.4 has been out for just over a month (released 29 June).  There are compatibility issues in the language, libraries and API with 5.3.  5.3 is still supported.  It's currently at 5.3.5 with a 5.3.6 release planned.  I would like to see at least 5.4.1, so that it can settle, before we start implementing it.  It will also require code changes to the lua-scripts repository as some functions have changed.  We could shoot for darktable 3.6.

In the meantime, the 5.3 libraries could be installed for darktable to build against, or the internal lua interpreter could be used.

**Comment by wpferguson** [comment] 2020-10-07 16:54
First try.  Replaced 5.3.3 with 5.4.  Updated all the CMake* stuff.  Left the -DLUA__COMPAT_5_3 flag on in the lua 5.4 Makfile.  Compiled OK, and darktable started with script_manager running OK.  Started a script from script_manager without problem.  Let the testing begin...

**Comment by parafin** [comment] 2020-10-07 16:58
I guess for a switch to Lua 5.4 to make sense, LUA__COMPAT_5_3 shouldn't be used, otherwise it's not really an update, is it?

**Comment by wpferguson** [comment] 2020-10-07 17:57
Actually in the current src/external/lua/src/Makefile the -DLUA_COMPAT_5_2 flag is still enabled :-D.  Before I tried 5.4, I upgraded the current to 5.3.6 and removed the compat flag.  I didn't uncover any problems with testing, though I didn't test extensively.  One note, the official lua distribution of 5.3.6 comes with the -DLUA_COMPAT_5_2 enabled by default, so any packaged 5.3 lua library is probably built in lua 5.2 compatibility mode.

The lua 5.4.0 distribution comes with -DLUA_COMPAT_5_3 enabled by default.  I figure that the distributions will probably leave it that way when they package it.  I'll test with and without it and see what problems I uncover.

I don't think it makes sense to go to 5.4 until most distributions start using it as the default.  Right now it seems that 5.3.3 is the most widely used, in my very unscientific research :).

**Comment by parafin** [comment] 2020-10-07 18:29
I see, so it makes sense to remove LUA_COMPAT_5_2 and leave LUA_COMPAT_5_3. But if the code also works without LUA_COMPAT_5_3 it would mean upgrade to future 5.5 will be painless;)

**Comment by wpferguson** [comment] 2020-11-08 19:08
Backported debian Lua 5.4.0 packages to Ubuntu 18.04 so that I could install and build against it.  Successfully built darktable with external lua 5.4 libraries.  darktable runs and script_manager executes seemingly fine.

**Comment by cryptomilk** [comment] 2021-02-17 06:51
This is still valid!

**Comment by wpferguson** [comment] 2021-02-17 16:17
It's on the [roadmap](https://github.com/darktable-org/darktable/issues/8052) for 3.6

**Comment by Nilvus** [comment] 2021-06-20 18:31
As @wpferguson create an issue for Lua 3.8 roadmap where adding support for lua 5.4 is set, do we need this one open? I think  #9165 3.8 roadmap is sufficient to keep. @cryptomilk: is it ok for you to close this one?

**Comment by wpferguson** [comment] 2021-06-20 19:55
I'll go ahead and do a PR in the next day or 2 so it can go into 3.7 early and get plenty of testing.  It's fine for me if you close it.

**Closed** 2021-06-20 20:11 UTC
Labels: lua, no-issue-activity
