### ISSUE TITLE
Crash when applying offset

### ISSUE THREAD

**Issue by FalCT60** [darktable-org/darktable#12186] opened 2022-07-16 20:24 UTC
**Introduction**
dt 4.0 Ubuntu 20.04 - upgraded from repos
---------------------------------------------------------------

**Describe the bug/issue**
When applying offset to a file, dt crashes. On restart, no offset has been applied.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. select a picture and open geotagging module
2. set an offset from the currently selected picture's time
3. click the lock (or not, it behaves the same way whatever the state of the lock)
4. click Apply offset button
5. wait a few seconds before dt crashes and returns to the desktop

**Expected behavior**
Would not the time be adjusted according to the offset ?
At least, this is what I would have expected.
O-Kay, I just was sarcastic because I have spent more than one hour trying to understand what the Hell I could be doing wrong. Do not feel offended.
I did not remember geotagging was such a pain. Well, I used it before 3.0, so ... ;-)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0
* OS                : linux
* Linux - Distro    : Ubuntu 20.04
* Memory            : 16 Go
* Graphics card     : CPU
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  :No

**Comment by pehar1** [comment] 2022-07-17 08:37
Confirmed with 4.1.0-26-g407f53c46, Ubuntu 20.04
Immediate Segfault, no backtace written. Output with `-d all` after clicking button _Apply offset_ : 
```
32.867750 [lighttable] expose took 0.0000 sec
32.985900 [sql] /home/ph/darktable/master/src/common/selection.c:497, function dt_selection_get_list(): prepare "SELECT m.imgid FROM memory.collected_images as m WHERE m.imgid IN (SELECT s.imgid FROM main.selected_images as s)"
32.986071 [images to act on] new cache (visible) : 544 
32.986090 [add_job] 0 | 32.986098 time offset | queue: 0 | priority: 032.986109 
32.986161 [run_job+] 04 367438645.712952 32.986196 time offset | queue: 0 | priority: 432.986209 
an error occurred while trying to execute gdb. please check if gdb is installed on your system.
backtrace written to /tmp/darktable_bt_D5INP1.txt
Speicherzugriffsfehler
```

**Comment by brucewilliamsphotography** [comment] 2022-07-17 11:13
Oh, came here to reply to MY thread about this issue, and found this thread.
Good to see some progress has been made on this front. :)

**Comment by kmilos** [comment] 2022-07-17 11:48
Duplicate of https://github.com/darktable-org/darktable/issues/12077 ?

**Comment by FalCT60** [comment] 2022-07-17 14:59
Oops ! my bad ! :-(
Well, I know why : I first had in mind the geotagging module, so I did search for "geotag" and did not find anything relevant.
I wrote my text with the title "Geotagging makes dt crach when apply", but then as I was describing the issue and realized it was more precisely related to offset handling, I changed the title for the one currently used.
But I did not think to do a new search using "offset". Sorry.
Maybe some admin could merge both reports or simply c;lose this one, since Bruce's is older.
Rgrds,

**Comment by Nilvus** [comment] 2022-07-17 15:04
@FalCT60: the only to merge this is to make a link (done by @kmilos AND copy/paste on it main infos. I let you do that last part of course. I close this issue so.

**Closed by Nilvus** 2022-07-17 15:04 UTC
Labels: duplicate

**Comment by victoryforce** [comment] 2022-07-17 15:51
> an error occurred while trying to execute gdb. please check if gdb is installed on your system.

@pehar1 It would be really helpful if you could provide a backtrace. Not much can be said without it.

**Comment by pehar1** [comment] 2022-07-18 06:00
Not on my computer at the moment. Will try to provide a backtrace asap, but don't know when it will be possible. Lot of other work to do...

**Comment by pehar1** [comment] 2022-07-18 07:21
Created backtrace, see https://github.com/darktable-org/darktable/issues/12077#issuecomment-1186849509
