### ISSUE TITLE
Using reject in image preview with filtered view does not fully advance to the next image

### ISSUE THREAD

**Issue by konig12** [darktable-org/darktable#6848] opened 2020-11-11 04:15 UTC
**Describe the bug**
When rejecting images from the light table image preview, the next image is not selected. As a result, pressing reject again will un-reject the previous image instead of rejecting the next one. See the steps below for more details.

**To Reproduce**
Start in the light table view with multiple images, all with 1 star
- Set the view to >= 1 star
- Select the first image by clicking on it
- Enter the image preview by pressing and holding W
- Reject the image (press R). Note that the next image appears (expected), but is not selected and does not have a white border (not expected)
- Reject again. Note that the rating does not change (not expected), but that the current image is now selected.
- exit the image preview by releasing W. Note that the first image is now un-rejected.

Note that the mouse must not move while performing these steps.

**Expected behavior**
When performing the reject in the steps above I would expect the next image to be selected in addition to being shown. The end result should be the following workflow:
- Select the first image by clicking on it
- Enter the image preview by holding W
- Reject the first image by pressing R, the second image appears
- Reject the second image by pressing R, the third image appears
- etc

Note that this is the behavior when not using the image preview, but simply hovering the cursor over the first image.

**Platform (please complete the following information):**
 - Darktable Version: Master (3.3.0). Also reproducible on 3.2.1.
 - OS: Arch linux

**Other info**
- This seems to be related to https://github.com/darktable-org/darktable/issues/6333, though I do not see the issue reported there.

**Comment by AlicVB** [comment] 2020-11-11 12:29
hm... I can't reproduce with the steps you give :( I've tested with&without filmstrip, with mouse in the middle or on the borders...
I remember to have fix something in this area recently. Which commit do you compile ?

Not related to this issue : are you aware of alt-w ? that would save you the "pain" to keep w key hold...

**Comment by konig12** [comment] 2020-11-12 00:21
I am running 3.3.0+1486~g132b636fe (according to the about window in darktable).

As for alt+w, I am aware of it. I personally find the non-toggling version more intuitive, as I end up switching back and forth quite often. I also usually remap it to the V key so that I can comfortably do that and rate images with just the left hand.

I see the same bug with alt+w.

**Comment by konig12** [comment] 2020-11-12 00:23
git log reports that master is: 132b636fedd39ee42d43be4a5de5e84f7bff077e

**Comment by konig12** [comment] 2020-11-12 00:35
Also, this seems related to #5983 . Looks like that was fixed by you as well.

**Comment by potocpav** [comment] 2020-11-17 14:14
Perhaps a duplicate of #6506?

**Comment by konig12** [comment] 2020-11-17 15:11
I do not believe it is a duplicate of #6506 . That issue is fixed, and I am not able to reproduce that behavior in master. The same build still exhibits this bug.

**Comment by AlicVB** [comment] 2020-11-18 18:41
@konig12 : I've finally managed to reproduce. PR #6973 should fix this

**Comment by konig12** [comment] 2020-11-19 00:21
Sounds good. I can confirm that the bug is fixed on that branch, though I did see another rating issue on import: the default rating of 1 was ignored. I'm assuming this is independent.

**Closed** 2020-11-19 07:28 UTC
