### ISSUE TITLE
Crop and rotate resets itself

### ISSUE THREAD

**Issue by hyphone** [darktable-org/darktable#8289] opened 2021-02-20 23:09 UTC
Describe the bug

Very often when I enter the darkroom from the library my crop and rotation settings resets itself and get's added as a new step in the history as if I have done it.

To Reproduce

- Select an image from the lighttable and double click on it
- often (I cannot find the pattern when it happens or not, seems random) the crop and rotation settings are lost (or better resetted because a new history entry appears that says "crop and rotation")

Platform (please complete the following information):

- Darktable Version: 3.4.1
- Fedora 33
- Fedora RPM

This is the same as https://github.com/darktable-org/darktable/issues/7749
But as the bot marked it with no-issue-activity and said I should re-open one I did it here. 

https://user-images.githubusercontent.com/6410852/108610810-e9f1cc00-73d8-11eb-8fad-edee080f7758.mp4

**Comment by johnny-bit** [comment] 2021-02-21 08:55
Duplicate of #7749

Please - add the video to original report and add comment that the problem exists in 3.4.1 still. There is absolutely no need to re-report non-closed issues.

**Closed by johnny-bit** 2021-02-21 08:55 UTC
