### ISSUE TITLE
Color mapping crashes Darktable

### ISSUE THREAD

**Issue by prabhath-mp** [darktable-org/darktable#9357] opened 2021-06-28 14:11 UTC
Darktable crashes everytime I click 'Acquire target' while color mapping

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to '...'refer to the process highlighted in this video on YouTube https://youtu.be/iXyrPT0pFug
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.4.1.1
* OS                : Win10 (Patchlevel)
* Linux - Distro    : NOt applicable

Processor	Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz   2.90 GHz
Installed RAM	8.00 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

* Memory            : 
* Graphics card     : Nvidia Geforce 940 Mx
* Graphics driver   : Standard

I have no clue about what the following means (I presume they're related to Linux? OS?)
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no** Other version didn't even start on my laptop (I tried 3.0 version that is available in your archive)
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both** I can access RAW files and export them (Gimp plugin works too); however, when I try to apply colour map from another image or from a saved preset, Darktable just crashes (no matter how many times I try)
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no** No
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no** How do I try this?
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by johnny-bit** [comment] 2021-06-28 16:10
The issue is fixed in current master and release 3.6. Release 3.6 will be officially announced this Saturday 3rd July 2021.

**Comment by Nilvus** [comment] 2021-06-28 19:53
@johnny-bit: so maybe this could be closed if it's fixed?

**Comment by johnny-bit** [comment] 2021-06-28 20:29
@prabhath-mp I'll close this issue. Please check out 3.6 on Saturday 😀

**Closed by johnny-bit** 2021-06-28 20:29 UTC
Labels: bug: fixed

**Comment by jmviade** [comment] 2021-08-14 13:45
Hi, 
I'm still using the old version 3.4 because the new version 3.6 dosen't execute the "import" process properly under Windows 10, I sent a issue report weeks ago, so could it be possible to fixe this bug also for the version 3.4 too?

**Comment by johnny-bit** [comment] 2021-08-14 14:00
@jmviade - the import issue you are experiencing is already fixed and the fix will be part of 3.6.1. The fix for color mapping is in 3.6.0. We do not plan on making any new 3.4.x release nor would it make sense to do so. The 3.6.1 release waits currently for a single fix to be reviewed and incorporated into 3.6 branch so the 3.6.1 release is comming soon.
