### ISSUE TITLE
darktable 3.4 (Linux/Ubuntu) crashes when rejecting NEF+JPG pair image in zoom mode or culling mode

### ISSUE THREAD

**Issue by mlaverdiere** [darktable-org/darktable#7658] opened 2021-01-03 15:10 UTC
darktable 3.4 crashes when rejecting NEF+JPG pair image in zoom mode or culling mode (with display on "all but rejected").

Does not happen with other pair (like DNG+JPG) or with single image (NEF *or* JPG).

Does not happen in file manager mode.

I'm on Ubuntu 20.10 on a Dell XPS 13 without any special graphic card

See crash report attached.
[darktable_bt_9DZSW0.txt](https://github.com/darktable-org/darktable/files/5761774/darktable_bt_9DZSW0.txt)

**Comment by johnny-bit** [comment] 2021-01-03 15:15
Duplicate of https://github.com/darktable-org/darktable/issues/7445

**Comment by johnny-bit** [comment] 2021-01-03 15:15
Fixed in https://github.com/darktable-org/darktable/pull/7569

3.4.1 can't come fast enough :/

**Closed by johnny-bit** 2021-01-03 15:15 UTC

**Comment by mlaverdiere** [comment] 2021-01-03 15:27
Sorry, I did search for an existing report on this issue but didn't find this one, Glad it will be fixed in 3.4.1. Thanks for the good work!
