### ISSUE TITLE
export module: Piwigo, Unknown file created on Export

### ISSUE THREAD

**Issue by Dero99** [darktable-org/darktable#15752] opened 2023-11-26 22:48 UTC
### Describe the bug

Images exported to Piwigo are incorrectly tagged as NEF within Piwigo and export out of Piwigo as NEF

### Steps to reproduce

Select NEF images and select Piwigo as target.  enter server name and log in info, select a current album or create new, jpg, Export.
The images correctly send to Piwigo (self hosting v13.8.0).  
View image in Piwigo, image info >20231121_0012.NEF<. It is a jpg NOT NEF.  Export out of Piwigo, resultant file is xxx.NEF, but is a jpg.

### Expected behavior

Piwigo show correctly jpg

### Logfile | Screenshot | Screencast

apache error_log during DT export:

[Fri Nov 17 14:24:23.995364 2023] [proxy_fcgi:error] [pid 1277:tid 140107512071936] [client 192.168.64.1:51202] AH01071: Got error 'PHP message: PHP Notice:  Unknown: file created in the system's temporary directory in Unknown on line 0'
[Fri Nov 17 14:27:28.174407 2023] [proxy_fcgi:error] [pid 1277:tid 140107545642752] [client 192.168.64.1:51240] AH01071: Got error 'PHP message: PHP Notice:  Unknown: file created in the system's temporary directory in Unknown on line 0'
[Fri Nov 17 14:30:28.855489 2023] [proxy_fcgi:error] [pid 1277:tid 140107595998976] [client 192.168.64.1:51258] AH01071: Got error 'PHP message: PHP Notice:  Unknown: file created in the system's temporary directory in Unknown on line 0'
[Fri Nov 17 14:33:17.033911 2023] [proxy_fcgi:error] [pid 1277:tid 140107889743616] [client 192.168.64.1:51269] AH01071: Got error 'PHP message: PHP Notice:  Unknown: file created in the system's temporary directory in Unknown on line 0'
[Fri Nov 17 14:36:25.163603 2023] [proxy_fcgi:error] [pid 1277:tid 140107730282240] [client 192.168.64.1:51279] AH01071: Got error 'PHP message: PHP Notice:  Unknown: file created in the system's temporary directory in Unknown on line 0'
[Fri Nov 17 14:39:10.458736 2023] [proxy_fcgi:error] [pid 1277:tid 140107579213568] [client 192.168.64.1:51297] AH01071: Got error 'PHP message: PHP Notice:  Unknown: file created in the system's temporary directory in Unknown on line 0'

### Where did you install darktable from?

an online forum

### darktable version

4.5.0+1289~g7bd67db3-dirty

### What OS are you using?

Mac

### What is the version of your OS?

14.1.1 (23B81)

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Apple

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This has been occurring with all DT versions since Piwigo export was fixed last month.

**Comment by TurboGit** [comment] 2023-11-27 18:51
> View image in Piwigo, image info >20231121_0012.NEF<. It is a jpg NOT NEF. Export out of Piwigo, resultant file is xxx.NEF, but is a jpg.

Looks like the  original filename is recorded, is that an issue? Is the file viewable on Piwigo? What is the issue?

**Comment by TurboGit** [comment] 2023-11-27 22:05
I don't see this using the Piwigo online service (not self hosted). And still cannot see what is wrong? When the picture is uploaded there is no filename, there is a name given to it. In your case it seems that .NEF is associated as label to the exported picture, but you can see it and this does not break Piwigo, right? So maybe confusing, but not a bug.

Again, I don't see this... Maybe you are referring to the filename on the server side, stored by Piwigo? I cannot verify that with a non self hosted service.

**Comment by Dero99** [comment] 2023-12-01 14:29
Sorry, I’m not sure how. I didn’t see it in the master branch.  I download the latest OSX builds off of pixls.usDarrellOn Dec 1, 2023, at 12:06 AM, Pascal Obry ***@***.***> wrote:﻿
@Dero99 : Did you get a chance to test my PR?

**Comment by Dero99** [comment] 2023-12-01 14:50
I downloaded recent nightly build, 4.5.0+1377~gca67684661. Not sure if your fix has been applied to it.  That build still has Piwigo naming issue.

**Comment by TurboGit** [comment] 2023-12-01 15:26
@Dero99 : Indeed not merged into master because I'm not sure the fix is correct (I cannot test).

You need to use the following PR: #15768

If easier to you I can push the branch into the main Git repository. Let me know.

**Comment by Dero99** [comment] 2023-12-01 16:05
I’ve created a test Piwigo server that you can send images to from DT or see my xxxx.NEF image.  If you email me from a private email account, I’ll reply to you with URL and log in info.

***@***.***

D

**Comment by TurboGit** [comment] 2023-12-01 16:12
@Dero99 
I need your e-mail :) Mine is public and you can find it in the Git repo: anyway : pascal@obry.net

I'll delete this message when you get my e-mail.

**Comment by TurboGit** [comment] 2023-12-01 17:08
After testing with @Dero99 server my PR works so I'll merge it soon for it to be in 4.6.

**Closed** 2023-12-01 17:20 UTC
Labels: bug: pending
