### ISSUE TITLE
Greyscale JPEGs crash on Mac

### ISSUE THREAD

**Issue by Stokestack** [darktable-org/darktable#3920] opened 2019-12-29 05:14 UTC
**Describe the bug**
Scrolling the thumbnail browser was crashing. It turns out that this file was the culprit.

**To Reproduce**
1. Go to Import and select the attached file.

**Expected behavior**
Imports fine. The file shows up fine in Apple Preview.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Mac OS 10.15.2
 -  No
 - 
Intel UHD Graphics 630 1536 MB graphics
Radeon Pro Vega 20

**Additional context**

Crash log attached.

**Comment by MStraeten** [comment] 2019-12-29 23:41
cannot reproduce on catalina: just browsed through a collection having >1000 images in the lighttable without any issues. With and without opencl enabled.
please give some more details ...

**Comment by Stokestack** [comment] 2019-12-30 08:47
Well, I imported my desktop. It appears that most of the images in the browser are coming from five subdirectories down:

Desktop/Qt training/widget sliderware source code/demos/cityengine/flags

However, when I build the same hierarchy on another volume and copy the same images into that lowest-level directory, I can import the hierarchy and it doesn't crash.

**Comment by Stokestack** [comment] 2019-12-30 09:11
It all comes down to one JPEG. Import the attached JPEG.
![gas](https://user-images.githubusercontent.com/196304/71575272-60878800-2aba-11ea-9322-6b0188e83ae5.jpg)

**Comment by Stokestack** [comment] 2019-12-30 09:16
Interestingly, the thumbnail is displayed when you select this file in the Import dialog.

**Comment by Stokestack** [comment] 2019-12-30 09:23
[DTCrashLog.txt](https://github.com/darktable-org/darktable/files/4009373/DTCrashLog.txt)

**Comment by jenshannoschwalm** [comment] 2019-12-30 11:37
On linux can't reproduce. exiv2 related?

**Comment by chhil** [comment] 2019-12-30 11:45
Does the quality of the jpeg remain the same or does github compress it and change it?

I did not have an issue on my windows version of DT.

The exif info is not present, I think it probably got stripped on github.
![image](https://user-images.githubusercontent.com/1119439/71580715-d413ae80-2b27-11ea-9929-c850c832c27d.png)

**Comment by MStraeten** [comment] 2019-12-30 13:15
ok can reproduce it on osx:
lldb output:
```
2019-12-30 13:58:32.784994+0100 darktable[51916:9128925] flock failed to lock maps file: errno = 35
2019-12-30 13:58:32.785224+0100 darktable[51916:9128925] flock failed to lock maps file: errno = 35
2019-12-30 13:58:34.134798+0100 darktable[51916:9128806] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=51916
2019-12-30 13:58:34.134930+0100 darktable[51916:9128806] SecTaskCopyDebugDescription: darktable[51916]/0#-1 LF=0
2019-12-30 13:58:34.135559+0100 darktable[51916:9128806] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=51916
2019-12-30 13:58:34.135631+0100 darktable[51916:9128806] SecTaskCopyDebugDescription: darktable[51916]/0#-1 LF=0
2019-12-30 13:58:34.136134+0100 darktable[51916:9128806] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=51916
2019-12-30 13:58:34.136372+0100 darktable[51916:9128806] SecTaskCopyDebugDescription: darktable[51916]/0#-1 LF=0
2019-12-30 13:58:34.136674+0100 darktable[51916:9128806] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=51916
2019-12-30 13:58:34.136741+0100 darktable[51916:9128806] SecTaskCopyDebugDescription: darktable[51916]/0#-1 LF=0
darktable(51916,0x1000d9dc0) malloc: Incorrect checksum for freed object 0x129870908: probably modified after being freed.
Corrupt value: 0xe7e2e2e2e0e0e0e3
darktable(51916,0x1000d9dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Process 51916 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff6e33e7fa libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff6e33e7fa <+10>: jae    0x7fff6e33e804            ; <+20>
    0x7fff6e33e7fc <+12>: movq   %rax, %rdi
    0x7fff6e33e7ff <+15>: jmp    0x7fff6e338a89            ; cerror_nocancel
    0x7fff6e33e804 <+20>: retq   
Target 0: (darktable) stopped.

```

I imported it with an empty database,  crashes after beeing imported. last log messages:
```
37,720322 [sql] ~/src/darktable_debug/src/common/image.c:249, function _image_local_copy_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id AND i.id = ?1"
darktable(51950,0x10d0cadc0) malloc: Incorrect checksum for freed object 0x7fa4caaaaf88: probably modified after being freed.
Corrupt value: 0xe7e2e2e2e0e0e0e3
darktable(51950,0x10d0cadc0) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      GSETTINGS_SCHEMA_DIR=/opt/local/share/glib-2.0/schemas/ XDG_DATA_DIRS=  -d al

```

**Comment by MStraeten** [comment] 2019-12-30 13:57
it fails on generating the preview - so also with darktable-generate-cache.
even after opening it with gimp, change the colorprofile and overwrite as jpeg.
after converting it into rgb mode it can be processed, also after converting it back to greyscale in gimp.
it seems to be the original greyscale mode darktable or a used library can't cope with.

imgamagick identify reports:
JPEG 709x928 709x928+0+0 8-bit Gray 256c 142556B 0.000u 0:00.00
mogrify <file> -type Truecolor converts the image into a format darktable can handle.
converting it back with -type Grayscale results in the old behaviour, so it seems, darktable can't process 8 bit Grayscale images (at least on osx, so it seems to be an issue of a used library)
 
Workaround: 
use imagemagicks `mogrify <file> -type Truecolor` to convert the image into a format darktable can handle.

**Comment by rudolphfroger** [comment] 2020-07-13 06:59
I can confirm this bug too. For me it's also a greyscale jpeg image. If anyone is interested I can provide the image which crashes Darktable on macOS (Catalina). I get the same error: "Incorrect checksum for freed object 0x...: probably modified after being freed".

If I can help in any way to trace this bug, please let me know.

**Comment by johnny-bit** [comment] 2021-05-18 17:48
I think we'll need sample JPEG images with weird grayscale applied to them and a way to crash dt on non-mac env with it.

**Comment by Stokestack** [comment] 2021-05-19 07:16
"weird grayscale applied?" Also, there's an image attached above.

**Comment by johnny-bit** [comment] 2021-05-19 08:15
@Stokestack - can you change title of this issue to something like "darktable on macos crashes on grayscale jpegs"? Would problably bring more attention to the problem. The issue doesn't happen on linux with attached file (nor any grayscale jpeg i had) so I think the problem is somehow limited to macs (which is weird)

**Comment by Stokestack** [comment] 2021-05-19 08:22
Sure, done.

**Comment by parafin** [comment] 2021-05-20 08:43
Since it's JPEG, maybe it is related to used JPEG library. There are 2 of them - original jpeg, and libjpeg_turbo. I think my builds have switched to libjpeg-turbo at some point, so the question is which one (and what version) is used on Linux and Windows where it does not crash. Most Linux distributions have switched to libjpeg-turbo some time ago I think, but it still leaves a questions of version.

**Comment by geni1105** [comment] 2023-02-04 14:28
Could not reproduce with darktable 4.2.0 (macOS 11.3, Intel-based iMac) - works, no crash. Tested with the example file from this issue and with a greyscale jpeg that I created myself.

I somebody else would confirm, we could close this.

**Comment by zisoft** [comment] 2023-03-08 17:27
Cannot reproduce with the provided sample on current master, macOS 13.2.1 Ventura, Intel based.

**Comment by ralfbrown** [comment] 2023-07-13 03:31
With two reports that the problem can no longer be reproduced (and various changes to grayscale images along the way), I think it's safe to close this issue raised on a version seven releases ago.

**Closed by ralfbrown** 2023-07-13 03:31 UTC
Labels: reproduce: confirmed, scope: software support, no-issue-activity, scope: macos support
