### ISSUE TITLE
ILCE-7SM3 .ARW files not opening

### ISSUE THREAD

**Issue by palluvian** [darktable-org/darktable#8733] opened 2021-04-20 00:33 UTC
I recently installed darktable to process photos from the Sony A7SIII (ICLE-7SM3) and immediately ran into an issue when trying to edit .ARW files. After importing, everything would appear normally in lighttable. But in darkroom, I would try to open an .ARW photo and get a message saying that:

darktable could now load filename.ARW, switching to lighttable now.

The photos I've tried all work just fine in other programs (like lightroom). Oddly enough the metadata is displayed correctly, and the photo appears normally in lighttable. A screenshot is attached.

Thanks so much for any help and working on this. I would love to be able to use darktable full-time and to support the devs however I can, once I get the hang of it!
![Capture](https://user-images.githubusercontent.com/82850309/115319718-ea57da80-a16f-11eb-95ae-25efc6d3ff1d.PNG)

* darktable version : 3.4.4.1
* OS                : Windows 10 20H2

 - Can you reproduce with another darktable version(s)? **not sure how to try this**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**

**Comment by kmilos** [comment] 2021-04-20 08:28
Duplicate of #8632

**Comment by johnny-bit** [comment] 2021-04-20 10:13
Duplicate of #8632

**Closed by johnny-bit** 2021-04-20 10:13 UTC
Labels: scope: camera support
