### ISSUE TITLE
Tags DT 3.1 not committed to database ?

### ISSUE THREAD

**Issue by mimijojo** [darktable-org/darktable#4034] opened 2020-01-05 13:31 UTC
With Darktable release 3.1.0~git299.40c7be068, editing tags seem to work, but edits seems not to be committed to the database before closing DT.

Easy to reproduce : When closing DT and reopening BT, all the tag edits seem to be lost.

**Comment by phweyland** [comment] 2020-01-07 10:40
I cannot reproduce (3.1.0+303~ga2a202f86).
Could you please make some snapshots to describe what you do and what you get ?

**Comment by johnny-bit** [comment] 2021-02-07 19:25
Fixed by  #4112 IMO - the PR was not properly connected to the issue

**Closed by johnny-bit** 2021-02-07 19:25 UTC
Labels: incomplete, no-issue-activity, scope: DAM
