### ISSUE TITLE
Crash in duplicate manager

### ISSUE THREAD

**Issue by pcouderc12** [darktable-org/darktable#9888] opened 2021-08-28 10:45 UTC
**Describe the bug/issue**
I have many difficults with duplicate manager, that I feel unable to describe how to reproduce. But this one is easy to reproduce..
Context : under debian bullseye with dartktable 3.6 from http://download.opensuse.org/repositories/graphics:/darktable/Debian_Next
Similar problems with 3.4 versions .

**To Reproduce**
1- goto an empty  test directory
2- remove /home/me/.config/darktable
3- add yven1.png (not provided, but I shall provide it if it matters) and attached files in test directory
4- start darktable and import yven1.png
It crashes.
Attached files are issued from previous executions of darktable.

The crash is a bug in itself, but current contents of .xml files may help finding other duplicate manager bugs. 

I am not allowed to import xmp files!!!
I have added a txt to them...

[yven1.png.xmp.txt](https://github.com/darktable-org/darktable/files/7070651/yven1.png.xmp.txt)
[yven1_01.png.xmp.txt](https://github.com/darktable-org/darktable/files/7070652/yven1_01.png.xmp.txt)
[yven1_02.png.xmp.txt](https://github.com/darktable-org/darktable/files/7070653/yven1_02.png.xmp.txt)

**Comment by johnny-bit** [comment] 2021-08-28 11:37
Please provide all the details required by issue template, that includes crash logs, xmp files and if needed sample files with crashes.

Currently this report lacks all info.

**Comment by pcouderc12** [comment] 2021-08-28 11:47
Sorry, I clicked by mistake before the report is fully filled.

**Comment by johnny-bit** [comment] 2021-08-28 12:03
Please provide crash log, you've provided just xmp files.

**Comment by pcouderc12** [comment] 2021-08-28 12:28
ok, where is it..?

**Comment by johnny-bit** [comment] 2021-08-28 12:32
in `/tmp/` there should be some files starting with `darktable_` which are crash logs... or you could run darktable in console and paste console output to file and attach the file here (don't paste crash log directly)

**Comment by pcouderc12** [comment] 2021-08-28 16:37
It is not a verbose log....  :
nous@pcouderc:~/projets/yven$ darktable
[defaults] found a 64-bit system with 8028220 kb ram and 8 cores (0 atom based)
[defaults] setting high quality defaults
Killed
nous@pcouderc:~/projets/yven$


I find nothing with ;
nous@pcouderc:~/projets/yven$ locate darktable  | grep tmp
nous@pcouderc:~/projets/yven$

**Comment by johnny-bit** [comment] 2021-08-28 17:11
weird. Please provide the png file that causes problems. I can't reproduce using just xmps.

**Comment by ralfbrown** [comment] 2021-08-28 17:53
Based on the pasted output, I would guess that darktable exhausted system memory and was terminated by the out-of-memory killer.  Possibly a broken PNG causing huge allocations.  If you have a system-monitoring app installed, you can try setting it to show memory use with frequent updates (once per second or even faster) and see whether there is a spike.

@pcouderc12 The database `locate` uses is only updated periodically (typically daily), so just-created files won't show.  But we know the exact directory, so `ls /tmp/darktable_*.txt` will show any backtrace files.  I don't expect you to see any, as it looks like dt is killed without getting a chance to write a backtrace.

**Comment by johnny-bit** [comment] 2021-08-28 18:14
@ralfbrown - I fully agree with your analysis. Just now noticing that @pcouderc12 has 8GB ram.

**Comment by pcouderc12** [comment] 2021-08-29 06:33
I am sorry that I do not success (today) to pastebinit yven1.png certainly because my link is bad and it is 180M size. It was produced by scanning at good precision a A4 page with old photos on it.I doubt it is incorrect png as display (from Magick) opens it without problem. Moreover, I process it in darktable without problem (basic processing : only crop and rotate).

I think memory exhaustion is a good explanation, but only (or mainly) in duplicate manager. Crash occurs 5s after I have started to import the file.

@ralfbrown : I have done an updatedb before locate, and there is definitely no /tmp/darktable* file.

**Comment by johnny-bit** [comment] 2021-08-29 08:00
So... What you're asking darktable to do is to process 45-60Mpix image while having only 8GB ram. That's asking for trouble TBH.
I don't know your workflow but I can imagine that since it's a scan of multiple photos you crop the image to the photo you're processing and do the processing... Well that would be OK if you had at least 2 times the amount of ram you have to have some breathing room, otherwise you're running into wall of physical limits of storing image representation in memory. You could "cheat" a bit with increasing swap to something like at least 32GB.
IMO better alternative would be to crop scan into individual photos and then process photos one-by-one. That would be less resource intensive.

If that answers your problems please consider closing the issue.

**Comment by jenshannoschwalm** [comment] 2021-08-29 10:09
I don't think a "won't fix" is good.

I think we should do a safety check while importing *and* when opening in darkroom and at least display a warning like "begging for trouble, are you sure to continue?"

**Comment by johnny-bit** [comment] 2021-08-29 11:37
OK, then at best it's a new feature - calculate how much mem it'd take to process image and go "you sure about that? that's a lot of image for that amount of mem" :P

**Comment by jenshannoschwalm** [comment] 2021-08-29 11:39
Fully agreed

**Comment by johnny-bit** [comment] 2021-08-29 15:55
@pcouderc12 - please retitle the issue and state core need in description (eg warning if user has not enough ram in order to process image) or close this isue and open a new feature request for it. Thanks!

**Comment by pcouderc12** [comment] 2021-08-29 18:05
mmm, I am very sorry, I am a developer too.
I cannot accept that a crash is not a bug.  You can say : "in darktable we consider that crash is not a bug" and do what you want  with my issue, but I shall not close it myself  ;) I know you are brave developers, and I say that  with full respect. But I shall not do that myself.... And no, it is not a new  feature, it is a bug. Sorry... 
But it is to you to put it in high or low priority...
Again with my full respect for your fantastic job.

**Comment by parafin** [comment] 2021-08-29 18:13
application being killed by OOM is not a crash, and even not a bug unless memory leak is the cause

**Comment by johnny-bit** [comment] 2021-08-29 18:25
@pcouderc12 - OOMkiller killing app for OOMing isn't crash. Crash is something that would produce backtracte or memdump or whatever. In your case it's just "Killed".
since you're dev too you're welcome to help implement a feature that would warn user if image about to be imported/loaded would cause OOM. Or if you think it's legitimate 'crash' help debug and fix 'bug'. For starters - build with RelWithDebInfo and run dartable under gdb doing same stuff that leads to 'crash' should be enough to point you in right direction.

**Comment by pcouderc12** [comment] 2021-08-30 07:26
Thank you for your explanations and suggestions. In my case " crop scan into individual photos and then process photos one-by-one." solves my problem". But there remain 2 problems.

"user_anguish" : when your program crashes without any message or explanation, you are lost. You cannot let your user alone, lost without any hope, any explanation. As a developer,  I consider that when my user has a problem, it is my problem, not his problem, should it only be to not bothered again by the same problem from another user. You must trap the crash and give the user a friendly message.

"eternal_crash" : not only darktable crashes, but the data base is corrupted and you can no more open darktable : it crashes again and again . A "simple" user cannot recover from this "error"... I did by removing .config/darktable, but a "simple" user cannot do that...

@johnny-bit Sure, someday,I shall be gald to contribute more. But for the moment, my better way of contributing is to report issues...

**Comment by parafin** [comment] 2021-08-30 07:41
I don't think it's possible to trap OOM kill. Moreover it can happen even when other application leaks memory, so it's not obvious how helpful it would be.

But, I guess, it's possible just not to try allocate that much memory, knowing how much is available. It will require doing some internal memory accounting, which is IMHO an overkill for such an edge case. This talk about "user anguish" is more suitable for commercial software development, not open source projects. I mean it's still a valid argument, but priorities of volunteer developers lies elsewhere compared to businesses selling software licenses. Again, patches are welcome.

As for "eternal crash" - I looked over the bug report, and it's the first time you mention it. Please be more elaborate when reporting bugs.

**Comment by johnny-bit** [comment] 2021-08-30 08:33
I think we do have a scan for db consistency on startup that shows possible recovery steps AND db backups...

The problem with mem is more complex - if there's no overcommit on system, mem allocations should afaik return NULL, which could be handled (and I think we handle NULLs gracefully usually). If there's overcommit though? Then app gets killed by EXTERNAL forces with no way to catch it. It just gets sigkill and it's done. This is in no way shape or form darktable bug.

**Comment by pcouderc12** [comment] 2021-08-30 08:38
I agree it is not obvious to process OOM, and I think the best is to prevent it, and it is not easy...

And yes, I had not reported the "eternel_crash" maybe because my mind was focused on the "bug" which appears to be a OOM kill...
I have still tried to send yven1.png but my link is too bad. I shall try again with better link.
Thanks again all developers for darktable.

**Comment by pcouderc12** [comment] 2021-09-01 08:10
yven1.png is availabe here
https://www.tolsupport.fr/download/yven1.png

**Closed** 2023-03-25 00:21 UTC
Labels: feature: enhancement, no-issue-activity
