### ISSUE TITLE
Discard history does not remove Lightroom emulated steps

### ISSUE THREAD

**Issue by bakubo** [darktable-org/darktable#7594] opened 2021-01-01 07:30 UTC
**Describe the bug**

Discard history does not remove automatically created emulation steps when a photo file + Lightroom XMP file are imported.  It should remove those steps just like it does for ones explicitly added by the user.  This issue (and related Lightroom XMP import issues) was discussed in this thread:

[https://discuss.pixls.us/t/importing-lightroom-xmp-sidecars/20668](url)

As we know, it is impossible to do a good job trying to reproduce Lightroom editing so I don't want it but, naturally, I want all the metadata (tags, star ratings, color labels).  I would prefer to have the choice to only get the metadata, but selecting all my photos and using discard history for my ~120k photos would be acceptable.  Unfortunately, that is broken too.

**To Reproduce**

Import a Lightroom edited photo file with Lightroom XMP sidecar file.  Then discard history.  You will see that it does not discard the automatically created emulation steps.

**Expected behavior**

I expect that discard history will remove everything except the mandatory steps.  It should remove steps I add and also steps the Lightroom importer added.

**Screenshots**

Before discard history:

![dt_discard_history_before](https://user-images.githubusercontent.com/49921933/103435127-ef8b2b00-4c4d-11eb-92b0-324a78f1898a.jpg)

After discard history:

![dt_discard_history_after](https://user-images.githubusercontent.com/49921933/103435138-13e70780-4c4e-11eb-8d8c-3f3f81ed8700.jpg)

Everything after step 11 in the above screenshots are operations that darktable tried to emulate from the Lightroom XMP sidecar file.

**Platform (please complete the following information):**
 - Darktable Version:  3.2.1 and 3.4.0
 - OS:  Windows 10
 - 
 - 

**Additional context**

**Comment by MStraeten** [comment] 2021-01-01 08:35
please provide a lightroom xmp so those that doesn’t use lightroom are able to reproduce ...

**Comment by bakubo** [comment] 2021-01-01 09:08
Yes, I should include a Lightroom XMP file.  I tried to drag and drop one here like I did for the screenshots, but I got an error saying the file type is not supported.  How shall I upload it?

**Comment by parafin** [comment] 2021-01-01 09:38
Change extension to .txt.

**Comment by bakubo** [comment] 2021-01-01 10:02
Thanks.  I thought about that while I was brushing my teeth awhile ago and just got back to the computer and see that you suggested it too. :-)  Here it is.

[DSC01746.xmp.txt](https://github.com/darktable-org/darktable/files/5758794/DSC01746.xmp.txt)

**Comment by MStraeten** [comment] 2021-01-01 14:12
in the moment you just can get rid of the adobe stuff when compressing the history stack with selected history pos 0 in darkroom. 
it seems the lightroom stuff is applied when opening the image in darkroom and having no history.
**workaround:** 
after initial import - discard history & quit darktable. 
then delete the lightroom xmp
restart darktable --> opening the image in darkroom doesn't import modules

**Comment by bakubo** [comment] 2021-01-01 22:40
Yes, I know that compress history works.  See the thread I linked to.  It would mean opening individually tens of thousands of photo into darkroom and doing the compress history for each one manually.

I just now tried your workaround on one test file.  You are correct that if I discard history (history is not discarded at this point), quit darktable, delete the Lightroom XMP file, and then restart darktable, open the image in darkroom I see that now the history has been discarded.  That is pretty strange, but it seems to work.  It seems rather strange though because it seems what you are saying is that after the initial import darktable will continue to read the Lightroom XMP each time the photo is opened in darkroom and will re-import the old Lightroom editing steps.

The big problem for me and probably most people is that in practice this is a rather difficult thing to do for tens of thousands of files for 2 reasons:

1.  It would mean deleting all the Lightroom XMP files for tens of thousands of photos.
2.  I have the Lightroom XMP files because I also use Lightroom so don't really want to delete them.

Okay, I know that is a personal problem, but it applies to probably many other people too. :-)  As a workaround you have found something that seems to work.  I do hope though that the discard history command would discard the history of all non-mandatory steps without the need for this difficult and very painful workaround.

Thank you!

**Comment by bakubo** [comment] 2021-01-02 03:08
By the way, I also have a related feature request:

**Importer for Lightroom XMP sidecars should allow only getting metadata #7595**

[https://github.com/darktable-org/darktable/issues/7595](url)

**Comment by bakubo** [comment] 2021-01-03 00:14
I am still playing around with this trying to understand what is going on.  As we know, while in darkroom if you select step 0 in the history stack and then click on **compress history stack** it will get rid of all the emulated Lightroom editing steps.  You don't even have to remove the XMP file because the next time you start up darktable and open that image in darkroom the steps are still gone.  But if you do essentially the same thing in lighttable where you select the image and click on **discard histor**y it doesn't work properly.  Very strange.  I think that in lighttable the **discard history** command should work the same as the **compress history stack** command when step 0 is selected.  In lighttable you can select more than one image to use with **discard history** and even select all images.

**Comment by phweyland** [comment] 2021-01-09 20:48
> But if you do essentially the same thing in lighttable where you select the image and click on **discard history** it doesn't work properly.

Not sure 100% but I can suggest an explanation. when one imports folders, the images are not developed on the fly (except if your preference is not to use embedded jpeg for thumb) for performance reasons. In that case a image is only developed (and get an history) when you open it in darktable. So before, the image has no history stack.
So it is possible that changing the preference to not to use embedded jpeg, you experience a better behavior of compress history stack ...

**Comment by bakubo** [comment] 2021-01-10 07:31
Thank you for your reply.  I just now tried it 2 times with **don't use embedded preview JPEG but half-size raw** checked and then again with it unchecked.  The results were the same in both cases:  in lighttable I select the photo I just imported, click on discard history, and then open the photo in darkroom.  The Lightroom emulated steps are still there.

**Comment by bakubo** [comment] 2021-02-10 07:51
While in darkroom if you select step 0 in the history stack or click on the **reset parameters** button
and then click on **compress history stack** it will get rid of all the emulated Lightroom editing steps. You don't even have to remove the XMP file because the next time you start up darktable and open that image in darkroom the steps are still gone. But if you do essentially the same thing in lighttable where you select the image and click on **discard history** it doesn't work properly. Very strange. I think that in lighttable the **discard history** command should work the same as the **compress history stack command** when step 0 is selected **reset parameters** button. In lighttable you can select more than one image to use with discard history and even select all images.

**Comment by mikaelstaldal** [comment] 2021-08-09 14:35
I just reproduced this bug in Darktable 3.6.0.

**Comment by phweyland** [comment] 2021-08-09 15:17
When one clears the history dt restarts the dev as it was the first time.
At the first dev time, lightroom_import() is called ...

So the @MStraeten workaround above IS the solution: remove (or rename) the lightroom xmp before importing or cleaning the history.

**Comment by bakubo** [comment] 2021-08-11 22:22
> When one clears the history dt restarts the dev as it was the first time.
> At the first dev time, lightroom_import() is called ...
> 
> So the @MStraeten workaround above IS the solution: remove (or rename) the lightroom xmp before importing or cleaning the history.

If all the XMP files are deleted then you also don't import the keywords, star ratings, etc. either.  So, that IS NOT the solution. :-)

**Comment by phweyland** [comment] 2021-08-11 23:15
> If all the XMP files are deleted then you also don't import the keywords, star ratings, etc. either. So, that IS NOT the solution.

The only one which has to be deleted is the lightroom one ...

**Comment by johnny-bit** [comment] 2021-08-12 07:59
Couple things here...

1. There IS a workaround. Better - there are 2 workarounds. One is remove lightroom xmp file after import and then distard history, second is to compress history starting from original. Either way works.
2. Feature Request #7595 covers the part of setting how to threat lightroom xmp imports. Interesting [comment from @mikaelstaldal](https://github.com/darktable-org/darktable/issues/7595#issuecomment-895279035) which suggests choosing even minutae details...
3. The suggestion for "discard history" to work as "compress history with step 0 selected" is a bit misguided. Discard history flushes all processing data in order to clean pipe throughly. Compress history doesn't do that. We need discard history to be able to flush everything since we have no way to guarantee that starting pipe from step 0 wouldn't leave pipe in unworkable state in case of some bug.

Soooo... essentially there's no bug here. This "works as intended". The way forward here would be to focus on #7595 with maybe additional conditionals about re-starting pipe...

@bakubo - if you agree let's close this in favour of #7595

**Comment by johnny-bit** [comment] 2021-09-13 17:21
closeing in favour of #7595

**Closed by johnny-bit** 2021-09-13 17:21 UTC
Labels: bug: invalid

**Comment by theclosesthing** [comment] 2024-04-05 07:50
The Bug is still there. I deleted all xmp files, restarted lightroom.
Go to darkroom (double-click or pressing 'd'), there is already an history stack. This seems to be already a bug in my opinion, because i use fresh RAW - files (.NEF).

I can remove the history stack in darktable view for one image each time by klicking on step 0 in the history stack. But there is no way to remove this history stack for all my pictures in lighttable view. 
'discard history' just doesn´t work.

This is a bug, discard history should really discard all the history, like when i press on step 0 in the history stack in darkroom view.
