### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by Roiyaru** [darktable-org/darktable#11720] opened 2022-05-04 10:09 UTC
Device: Lenovo Xiaoxin Pro16_82L5
System: Windows11_beta22610.1
CPU: AMD 5800H
GPU: RTX3050

I downloaded version 3.8.1 from Github and installed it, after the installation was completed it opened and could not be applied.

[darktable_bt_O4V0L1.txt](https://github.com/darktable-org/darktable/files/8619366/darktable_bt_O4V0L1.txt)
[darktable_bt_PGP4L1.txt](https://github.com/darktable-org/darktable/files/8619367/darktable_bt_PGP4L1.txt)
[darktable_bt_Y283L1.txt](https://github.com/darktable-org/darktable/files/8619369/darktable_bt_Y283L1.txt)
![屏幕截图 2022-05-04 180827](https://user-images.githubusercontent.com/36790001/166662365-0af09f41-4687-4ece-8f2b-cb8a801c4d4a.png)

**Comment by kmilos** [comment] 2022-05-04 11:50
Duplicate of https://github.com/darktable-org/darktable/issues/10767

Please search before opening new issues.

**Comment by Roiyaru** [comment] 2022-05-04 11:55
> 的 [#10767 ](https://github.com/darktable-org/darktable/issues/10767)
> 
> 请在打开新问题之前进行搜索。

Okay, I'll take care of that in the future. Thanks.

**Closed** 2022-05-04 12:00 UTC
