### ISSUE TITLE
UI → Images changing positions

### ISSUE THREAD

**Issue by ghost** [darktable-org/darktable#3570] opened 2019-11-25 21:37 UTC
Steps to reproduce:
1. Open big collection
2. Probably not needed but make sure it is sorted by time and press reset button in lighttable → collect images
3. Scroll list down to the bottom
4. Notice position of image in row you are opening
5. Press "d"
6. Now press space to jump to next or backspace to previous image
7. Press "l"

Problem:
Images changed their positions in lightroom mode. It's very annoying bug when working with big collections and you need go back and forth often.

**Comment by wpferguson** [comment] 2019-11-26 00:22
If you're talking about the last image you edited in darkroom being positioned at the top left in lighttable when you return to lighttable, that's by design.

**Comment by timur-davletshin** [comment] 2019-11-26 04:02
@wpferguson it keeps position when one image was edited. If many - no, it jump to random position. Even more — very first picture on the top could change it's position. What is the point of that?

**Comment by Nilvus** [comment] 2020-04-18 17:30
@AlicVB: should probably be fixed by your last rework. So maybe to be closed?

**Comment by johnny-bit** [comment] 2020-12-22 13:50
This is fixed in 3.2.1 and current master :)

**Closed by johnny-bit** 2020-12-22 13:50 UTC
Labels: no-issue-activity
