### ISSUE TITLE
Mask manager is broken in master

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#13119] opened 2022-12-11 10:18 UTC
Just a reminder that we have some pending issues in mask manager, affecting all OSs:
1) "delete this shape" doesn't work at all
2) "remove from group" remove all the shapes from group
See #12655 and #12656, also [here](https://discuss.pixls.us/t/cant-delete-brush-mask-bug-or-user-error/34048)

I rebuilt 4.01 and mask manager is working fine, so this is a serious regression and maybe we should try to fix this before 4.2.
On my side I will try to perform a bisect.
Thank you

**Comment by MStraeten** [comment] 2022-12-11 10:56
confirmed with current master osx build

**Comment by Mark-64** [comment] 2022-12-11 11:14
Unfortunately bisect was not clean, I had to skip some commits due to another issue in the gui which didn't allow me to perform the test (right click didn't work).
So here below is the result

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
bcd1eb559cb04a090acb65aac91e7ec95fc0a615
e14544e533eb791925790c05993b27f4171163c1
446c121859f4a8db2a2a401db4d42fe1fbbc5fc5
969a2d55b668bd96895186ffd92f2bb2951e9605
6505a1019ea7fed1499cee7be3e629f93f730dca
84a7c4aa093ec84c4ca5700ec9ec002b6d640f7d
3f6de2d7c58313affaf06298b07e7c6c732b9964
We cannot bisect more!
```
@dterrahe can you have a look? These seem to be yours

**Comment by Nilvus** [comment] 2022-12-11 16:48
Remains just few days before 4.2 but it would be good if this could be fixed for, so why I set that for 4.2 milestone.

**Comment by dterrahe** [comment] 2022-12-11 18:52
If anybody could test #13125 maybe it is still feasible to squeeze it into 4.2 (@TurboGit ?)
It looks fairly contained; the main risk I see is memory leaks (not that I necessarily believe there is one).

I'm not sure what your 1) refers to.

From the discussion in https://github.com/darktable-org/darktable/issues/12656 this works as intended or at least is not a regression; for me 4.0.1 seems to show the same behavior. So "fixing" that at this juncture is _much_ more fraught and not something I myself would particularly want to touch.

**Comment by Mark-64** [comment] 2022-12-11 20:22
> I'm not sure what your 1) refers to.

It means that shapes can never be deleted in mask manager, even after deleting them in all modules and compressing history stack, it is mentioned in [this comment](https://github.com/darktable-org/darktable/issues/12656#issuecomment-1288091430) in #12656

**Comment by dterrahe** [comment] 2022-12-11 20:38
I don't seem to have that problem. For me "deleting this shape", even when still used by a module, works fine. Would somebody be able to provide steps to reproduce the situation?

**Comment by dterrahe** [comment] 2022-12-11 20:55
> #13125 solves both issues

Thank you! I'll mark it as fixing this issue (which will automatically close it if @TurboGit merges). https://github.com/darktable-org/darktable/issues/12656 will stay open as a separate issue in case someone new steps up who wants to have some fun with masks.

**Closed** 2022-12-12 08:32 UTC
Labels: priority: high, scope: UI, bug: pending
