### ISSUE TITLE
Darktable loses focus after creating tag

### ISSUE THREAD

**Issue by tendant** [darktable-org/darktable#4619] opened 2020-04-05 17:04 UTC
**Describe the bug**
Darktable loses focus after creating/assigning tag.

**To Reproduce**
1. Open Darktable
2. Switch to Lighttable view
3. Select a photo
4. Ctrl - T to open tag input
5. Type a few characters and Type Enter
6. Tag input box will disappear, Darktable will lose focus and not respond to any keyboard events. Have to click on Darktable again to focus the application.

**Expected behavior**
After tag photo using Ctrl-T, Darktable should continue have focus and respond to keyboard event.

**Screenshots**
![Screen Shot 2020-04-04 at 7 55 19 PM](https://user-images.githubusercontent.com/37181/78504905-beb0b080-7724-11ea-81be-ff855c00cdf1.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1.2, (Downloaded from https://github.com/darktable-org/darktable/releases/download/release-3.0.1/darktable-3.0.1.2.dmg"
 - OS: macOS Catalina 10.15.4
 - No

**Comment by parafin** [comment] 2020-04-05 18:20
macOS window manager is pure shit. Please try running darktable in fullscreen mode, I think it can't happen then.

**Comment by tendant** [comment] 2020-04-05 18:29
Thanks for looking into this. Just tried fullscreen mode, it has the same issue.

**Comment by phweyland** [comment] 2020-04-06 13:44
I cannot reproduce this on debian 10.
Is there any other contexts showing this issue ?

**Comment by parafin** [comment] 2020-04-06 19:09
I can confirm this on macOS 10.14. It's most likely Quartz-specific issue. I've pushed a fix (or rather workaround, since this is stupid), so next release will include it, whenever that may be. GTK might be to blame here too BTW, but who knows.

**Closed by parafin** 2020-04-06 19:09 UTC

**Comment by tendant** [comment] 2020-04-06 22:24
Thanks @parafin for fixing it so quickly! Can't wait to try it soon.
