### ISSUE TITLE
Exiting darkroom changes the selected image (when you navigated in darkroom)

### ISSUE THREAD

**Issue by EC1000** [darktable-org/darktable#3786] opened 2019-12-16 23:26 UTC
**Describe the bug**
Going back from the darkroom to the lightable loses the image which had focus on the darkroom. Instead, it goes back to the image I entered the darkroom from. 

**To Reproduce**
1. In the lightable, use a collection with more than 1 image. 
2. Go to the darkroom from image A (with double-click or menu) 
3. In the darkroom, change to image B 
4. Exit to the lightable (with double-click or menu)
5. You are back to image A. 

**Expected behavior**
Previously (2.6), going back from darkroom to lightable used to keep the same photo selected. On 5. above, it should stay on image B. 

**Platform**
 - OS: Linux Mint 19.1 Cinnamon
 - Version: 3.0.0rc2~git115.eff9c65e1

**Comment by AlicVB** [comment] 2019-12-17 08:13
If I understand well, it has been changed on purpose : 
if a selection as been done in lighttable or filmstrip, we must ensure not to drop it !
Now if you don't have any selection>1 when entering darkroom, and you switch image there, the selected image should follow.

I'll close it for now. Feel free to reopen if I've not understand your issue !

**Closed by AlicVB** 2019-12-17 08:13 UTC

**Comment by EC1000** [comment] 2019-12-17 09:28
I just have 1 image selected when entering darkroom, but the selected image doesn't follow when I come back to lighttable.

**Comment by AlicVB** [comment] 2019-12-17 10:17
Ok, so there's a problem... I'll have a look

**Comment by AlicVB** [comment] 2019-12-17 21:22
Well, after some tests, I can't reproduce... Some questions : 
1. how do you change images inside darkroom : filmstrip, accels ?
2. is your initial image a grouped one ?
3. anything special in your configuration ? (nb of image per row, culling, ...)
4. can you reproduce with a "fresh" config dir ? (rename your config dir to test)

**Comment by EC1000** [comment] 2019-12-18 01:10
I did some more test: the problem occurs only when I have 1 image per row (filemanager view). 

For the others questions just in case: 
1. filmstrip or accels (spacebar)
2. same problem either with ungrouped or grouped image.
3. One image per row in filemanager view
4. yes

**Comment by AlicVB** [comment] 2019-12-18 11:16
Ok , I've found it, and the PR #3804  should fix it.

Thanks for reporting, but please try to specify any special configuration you are using when writing issues (here the '1 image per row') this would have saved me some time ! Thanks...

**Comment by EC1000** [comment] 2019-12-18 12:31
Thanks.
I had not realized first it happened only with 1 image per row (I guess I must use this configuration quite often), I'll try to check more thoroughly next time.
