### ISSUE TITLE
cannot use 'w' key on french keyboard

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#9752] opened 2021-08-07 12:11 UTC
**Describe the bug/issue**

The w key seems dead.

**To Reproduce**
1. Go to 'shortcut' in preference
2. Double-click on any action
3. Clic on '`w`' to define this key as shortcut for the action 
4. See error, nothing happens
5. Clic on `atl+w` to define this key as shortcut for the action
6. See error, the key shortcut is defined as `alt+`

**Expected behavior**

The `w` key should be active and properly used to define a shortcut. 

**Platform**
* darktable version : current master
* OS                : Linux / GNOME 3.38
* Linux - Distro    : Debian/sid

**Comment by TurboGit** [comment] 2021-08-07 12:12
@dterrahe : I have assigned this to you as most probably a regression due to Input NG. TIA.

**Comment by ralfbrown** [comment] 2021-08-07 12:56
I saw something very similar late last night, generating a shortcut for `shift+alt+`.  That came from attempting to define `shift+alt+h` after discovering that my existing `alt+h` shortcut is instead being treated like plain `h`and popping up the shortcut list while being held....  (so it looks like the recent PR to remove the legacy shortcut code has a regression)

**Comment by dterrahe** [comment] 2021-08-07 13:15
This must have broken when I introduced "hold" shortcuts. A workaround (but not a _solution_, obviously) is to first delete the current definition of W (preview) and then assign it to something else.

There's still, I think, a similar/related issue with defining modifiers as fallbacks (which is the only case when shift+alt+ would be a valid shortcut). I need to carefully analyse and fix these issues simultaneously I think.

**Comment by dterrahe** [comment] 2021-08-07 13:54
> existing `alt+h` shortcut is instead being treated like plain `h`

Apologies for the lack of QA. This is due to me deciding that "modifier+hold shortcut" should be treated as "hold shortcut" to allow multi-modifier (ctrl _and_ shift _and_ alt) from midi. The problem was that defining midi key A=ctrl, key B=shift and C=alt, would lead to pressing A being treated correctly as ctrl modifer, but B would now register as ctrl-B.

Looks like I'll need to treat modifiers as special case (on top of them being hold shortcuts).

**Closed** 2021-08-15 08:05 UTC
Labels: priority: high, bug: pending
