### ISSUE TITLE
On Mac OS, no more able to open darktable after changing language

### ISSUE THREAD

**Issue by ciuliene** [darktable-org/darktable#16414] opened 2024-03-06 06:13 UTC
### Describe the bug

On Mac OS Ventura 13.6.4, I tried to change the language, then a message appeared saying that the application needed to be restarted, so I closed it but now I can't open it anymore

### Steps to reproduce

1. Change language
2. Close the application
3. Try to open it

### Expected behavior

darktable should open normally after changing the language

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

darktable-4.6.1-x86_64

### What OS are you using?

Mac

### What is the version of your OS?

Ventura 13.6.4

### Are you using OpenCL GPU in darktable?

None

**Comment by MStraeten** [comment] 2024-03-06 06:24
not reproducible, please run darktable from terminal via `/Applications/darktable.app/Contents/MacOS/darktable -d common` and report the output

**Comment by ciuliene** [comment] 2024-03-06 07:15
> not reproducible, please run darktable from terminal via `/Applications/darktable.app/Contents/MacOS/darktable -d common` and report the output

```
darktable 4.6.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.2.0
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> DISABLED - Compressed LUTs are NOT supported
  GraphicsMagick         -> DISABLED
  ImageMagick            -> ENABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.0002 application_directory: /Applications/darktable.app/Contents/MacOS
     0.0003 darktable.datadir: /Applications/darktable.app/Contents/Resources/share/darktable
     0.0004 darktable.plugindir: /Applications/darktable.app/Contents/Resources/lib/darktable
     0.0005 darktable.localedir: /Applications/darktable.app/Contents/Resources/share/locale
     0.0006 darktable.configdir: /Users/ciuliene/.config/darktable
     0.0007 darktable.cachedir: /Users/ciuliene/.cache/darktable
     0.0008 darktable.sharedir: /Applications/darktable.app/Contents/Resources/share
     0.0009 darktable.tmpdir: /private/var/folders/sr/7cqwdtwd1vx3cv1gsc5n48vr0000gn/T
     0.0010 new_xdg_data_dirs: (null)
     0,1219 [dt_worker_threads] using 6 worker threads
     0,1224 [dt_get_sysresource_level] switched to 1 as `default'
     0,1224   total mem:       8192MB
     0,1224   mipmap cache:    1024MB
     0,1224   available mem:   4096MB
     0,1224   singlebuff:      64MB
     0.1247 [opencl_init] opencl disabled via darktable preferences
     0.1248 [opencl_init] opencl library '/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL' found on your system and loaded, preference 'default path'
     0.1248 [opencl_init] found 1 platform
[opencl_init] found 2 devices

[dt_opencl_device_init]
   DEVICE:                   0: 'Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz'
   PLATFORM, VENDOR & ID:    Apple, Apple, ID=-1
   CANONICAL NAME:           appleintelrcoretmi57360ucpu230ghz
   DRIVER VERSION:           1.1
   DEVICE VERSION:           OpenCL 1.2 
   DEVICE_TYPE:              CPU, unified mem
   GLOBAL MEM SIZE:          8192 MB
   MAX MEM ALLOC:            2048 MB
   MAX IMAGE SIZE:           8192 x 8192
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1 1 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                1000
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   *** marked as disabled ***

[dt_opencl_device_init]
   DEVICE:                   1: 'Intel(R) Iris(TM) Plus Graphics 640'
   PLATFORM, VENDOR & ID:    Apple, Apple, ID=16925952
   CANONICAL NAME:           appleintelriristmplusgraphics640
   DRIVER VERSION:           1.2(Jan  9 2024 00:49:59)
   DEVICE VERSION:           OpenCL 1.2 
   DEVICE_TYPE:              GPU, unified mem
   GLOBAL MEM SIZE:          1536 MB
   MAX MEM ALLOC:            384 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      256
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 256 256 256 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   /Applications/darktable.app/Contents/Resources/share/darktable/kernels
   KERNEL DIRECTORY:         /Users/ciuliene/.cache/darktable/cached_v3_kernels_for_AppleIntelRIrisTMPlusGraphics640_12Jan92024004959
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   CL COMPILER COMMAND:      -w -cl-fast-relaxed-math  -DUNKNOWN=1 -I/Applications/darktable.app/Contents/Resources/share/darktable/kernels
   KERNEL LOADING TIME:       0.0134 sec
[opencl_init] OpenCL successfully initialized. internal numbers and names of available devices:
[opencl_init]		0	'Apple Intel(R) Iris(TM) Plus Graphics 640'
     0.1593 [opencl_init] FINALLY: opencl is AVAILABLE and NOT ENABLED.
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	-1	0	0	-1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	0	0	0	0
[opencl_synchronization_timeout] synchronization timeout set to 200
   UNIFIED MEM SIZE:         1536 MB reserved for 'appleintelriristmplusgraphics640'
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	-1	0	0	-1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	0	0	0	0
[opencl_synchronization_timeout] synchronization timeout set to 200
     0,3465 [dt_worker_threads] using 6 worker threads
```

**Comment by victoryforce** [comment] 2024-03-06 08:49
@ciuliene It's not directly stated in your bug report, but I can guess that the language the darktable interface switched to was Italian. Can you check if this bug is reproduced if you switch the language to en@truecase or French for example?

Since with your current darktablerc you cannot run the program, there are several options to solve this:
- rename the darktablerc file or even delete it if it doesn't contain settings that are valuable to you
- delete the line containing `ui_last/gui_language=` in darktablerc
- insert `LC_ALL=C` before darktable when starting from the command line to ignore the language specified in the configuration file

@zisoft Am I correct that this darktable release was built in homebrew?

**Comment by zisoft** [comment] 2024-03-06 09:02
> @zisoft Am I correct that this darktable release was built in homebrew?

Yes, this is the homebrew build. Anything special here with the italian locale?

**Comment by ciuliene** [comment] 2024-03-06 09:30
> @ciuliene It's not directly stated in your bug report, but I can guess that the language the darktable interface switched to was Italian. Can you check if this bug is reproduced if you switch the language to en@truecase or French for example?
> 
> Since with your current darktablerc you cannot run the program, there are several options to solve this:
> 
> * rename the darktablerc file or even delete it if it doesn't contain settings that are valuable to you
> * delete the line containing `ui_last/gui_language=` in darktablerc
> * insert `LC_ALL=C` before darktable when starting from the command line to ignore the language specified in the configuration file
> 
> @zisoft Am I correct that this darktable release was built in homebrew?

Thank you, removing the `ui_last/gui_language=` line fixed the issue. No issue after setting to language en@truecase and French.

**Comment by zisoft** [comment] 2024-03-06 09:52
Confirmed that the fix is still not included.
I will prepare a PR at homebrew to fix that.

**Comment by zisoft** [comment] 2024-03-06 14:46
I have now created a PR at [homebrew/core](https://github.com/Homebrew/homebrew-core/pull/165243) to include the patch.

**Comment by zisoft** [comment] 2024-03-06 18:02
PR is accepted and merged.

**Closed by zisoft** 2024-03-06 18:02 UTC
Labels: bug: upstream, scope: macos support
