### ISSUE TITLE
Shadows and highlights dissapearing from quick access panel

### ISSUE THREAD

**Issue by Asanoth** [darktable-org/darktable#15692] opened 2023-11-19 20:04 UTC
### Describe the bug

Whenever I open "manage presets" in darkroom, shadows and highlights dissapear from quick access panel. 

### Steps to reproduce

1. Add shadows and highlights to QAP (usually I have shadows, highlights and white point).
2. Open "manage presets"
3. Close "manage presets"

### Expected behavior

Shadows and highlights should not dissapear from QAP. 

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

10 Pro

### Are you using OpenCL GPU in darktable?

No

**Comment by ralfbrown** [comment] 2024-06-22 10:25
Unable to reproduce with 4.8.0.
Closing since there have been a number of changes to the QAP code.  Feel free to reopen if it still happens for you in the new release.

**Closed by ralfbrown** 2024-06-22 10:25 UTC
Labels: scope: UI, no-issue-activity
