### ISSUE TITLE
Intermittent bug in module manager

### ISSUE THREAD

**Issue by sg456** [darktable-org/darktable#13420] opened 2023-01-23 21:38 UTC
I'm running dt 4.2 downloaded from darktable.org

I'm seeing intermittent random behavior with the module manager.

It's not consistent, annoyingly, but I managed to record the behavior on a screen capture (attached).

With the quick access panel displayed, if I open the module manager via the hamburger icon, remove a slider from the quick access pane, then add a different slider, something else will disappear from the the quick access panel when I close the module manager window.
I'm not sure that I really expect anyone else to be able to replicate it, as it's intermittent with me.

**Expected behavior**
My custom set of sliders should remain as set when closing the module manager.

**Screencast**
My file is too large for Github - please here the thread I created on Pixls.us: https://discuss.pixls.us/t/is-there-a-bug-with-the-quick-access-module-layout/34887/6

**Platform**

* darktable version: 4.2
* OS                :Win 11 Pro 21H2

* Memory            : 16GB
* Graphics card     : Nvidia GTX1650
* Graphics driver   : Nvidia creators (as opposed to gaming) version
* OpenCL installed  : yes
* OpenCL activated  : yes

**Additional context**
AlicVB on Pixls notice that I have 2 instances of a color balance rgb slider in the quick access configuration in the module manager - I don't know why! It shouldn't be possible to do that. The preset I have in the module manager goes back quite a long way, (at least to dt.40 via several dev builds) and through several versions of the preset.

I've noticed this issue very occasionally for some time, going back to dt 4.0 (at least) but have never been able to consistently reproduce it.

I have dt 4.3 287 installed with a fresh database, and I cannot reproduce the issue. I'm wondering if there could be some corruption or something weird in my dt 4.2 configuration folder.
Please let me know if there's any info I can provide that would help.
Thanks all :-)

**Comment by Nilvus** [comment] 2023-01-24 19:43
That could be possible it's a possible corruption on your configuration folder. Unfortunately, this will be quite hard to check. If you can't reproduce on 4.3, that means, we can do nothing there. If this could be related to your configuration folder, it will be better for you to test which file do that. To test, it's not difficult, just save both configuration folder (new one without issues and old with the issue). After, copy files one by one of old configuration folder with issue to the new without. Launch darktable after then test.

I suggest to began with darktablerc, library and data files, they store link to images and your settings. You could also do both test with 4.2 and 4.3.

As you don't reproduce on 4.3 and so nothing actually to do on darktable code, I will close that issue. To have more help or feedback about issue related to your side, pixls.us forum is there for that. If after some tests you could find a reproducible way and you find that it's probably related to darktable code, so you can so ping me to reopen.

But before closing, as @AlicVB answer to pixls.us, @AlicVB: what's your view on that and my answer?

**Comment by AlicVB** [comment] 2023-01-24 20:13
Some questions : 
- does it happens with other presets ?
- if it does, do they have some "double" entries too ?
- what happens if you remove one of the entry in double ?

The idea here is to determine if : 
- the issue comes from this "corrupt" preset
- the corruption can be reproduce

Thanks !

@Nilvus : I would say that this issue need to be kept open, until we are reasonably sure this can't be reproduced with master...

**Comment by sg456** [comment] 2023-01-25 02:02
Thanks or the input, @AlicVB and @Nilvus
I have been able to reproduce the behaviour, although with a different module, on dt 4.3 287 running with configdir, cachedir and tempdir pointing to an empty folder.

Steps as follows:
Start dt.
Import a folder of photos.
start the module manager from the preset list drop-down.
duplicate the scene-referred preset, name it "sg2"
Select this preset.
add the "tone curve>on/off" widget to the quick access panel
exit module manager, select "sg2" from the drop down.
click the quick access tab, see that the tone curve on/off is present.
open module manager again from the drop down.
add "color balance rgb>chroma>midtones" to the quick access panel.
close module manager.
Watch as the tone curve widget disappears...............

Here's a link to a screen capture of the above sequence of events: https://drive.google.com/file/d/1FyadyfUN5sH4WVs2TUVqwIrAX5ZBxmKp/view?usp=sharing
Does this help?

**Closed** 2024-01-21 00:19 UTC
Labels: understood: incomplete, reproduce: peculiar, no-issue-activity
