### ISSUE TITLE
Version 4.4.1 and 4.4.0 not starting after install on Macbook Pro with M1 Pro ARM

### ISSUE THREAD

**Issue by 7h0mas-R** [darktable-org/darktable#14826] opened 2023-07-02 17:35 UTC
### Describe the bug

I just tried to replace version 4.2.1 with 4.4.1 (and now also with 4.4.0)
Downloaded the dmg from darktable.org for Mac with ARM processor.

After installing to the Applications folder, the program will not start and throws an error:
```
"darktable“ ist beschädigt und kann nicht geöffnet werden. Es empfiehlt sich, das Objekt in den Papierkorb zu bewegen.
(Darktable is corrupted and cannot be opened. It's recommended to move the object to the recycling bin.)
``` 
I tried to download again and also tried to start it with CTRL pressed (bypass Mac security). Both did not help.

### Steps to reproduce

1. Download dmg from https://github.com/darktable-org/darktable/releases/download/release-4.4.1/darktable-4.4.1-arm64.dmg
2. Double-click and move Darktable Icon to Applications folder
3. Double-click Darktable Icon

or

3. Hold CTLR, click Darktable icon and select "Open"

Downloaded 4.2.1 again - working as expected.

### Expected behavior

darktable should start

### Where did you install darktable from?

darktable.org

### darktable version

5.2.1

### What OS are you using?

Mac

### What is the version of your OS?

macOS Monterey

### Describe your system?

- System: Macbook Pro 2021
- Chip: Apple M1 Pro
- OS: macOS Monterey (12.6.7)

4.2.1 worked seamlessly

### Are you using OpenCL GPU in darktable?

None

**Comment by davve2** [comment] 2023-07-02 17:50
I did exactly the same update the other day. This command (in the terminal) solved it

xattr -d com.apple.quarantine ~/Downloads/darktable-4.4.1-arm64.dmg

However I'm now stuck with this bug that is limiting my editing, if you get it working please check if you can confirm that bug

#14822

**Comment by kmilos** [comment] 2023-07-02 17:51
Duplicate of https://github.com/darktable-org/darktable/issues/14746

**Closed** 2023-07-02 18:08 UTC
Labels: scope: macos support
