### ISSUE TITLE
import: "apply metadata" issues

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#7854] opened 2021-01-14 23:35 UTC
A couple of possibly related issues with the new options in the import module:

If you tick "apply metadata", the metadata fields are active and can be selected, though for some reason, clicking on the "preset" drop-down doesn't do anything:

![Screenshot_2021-01-14_23-33-10](https://user-images.githubusercontent.com/9555491/104661650-e3c54d00-56c0-11eb-984f-91f65f1c59a9.png)

If you un-tick "apply metadata", the metadata fields are deactivated, as expected. However, only the "preset" and "tags" labels are greyed out (to indicate that the fields are inactive). This should be changed so that all fields are visually inactive.

![Screenshot_2021-01-14_23-34-50](https://user-images.githubusercontent.com/9555491/104661747-1c652680-56c1-11eb-893f-9aba59c5f0ec.png)

darktable 3.5.0+639~gc77f1ff43 on ArchLinux

**Comment by elstoc** [comment] 2021-01-14 23:41
Tagging @TurboGit @phweyland - I'm not entirely sure how this works but hopefully you'll know where to look.

**Comment by phweyland** [comment] 2021-01-15 00:11
I'll look at it.

**Comment by phweyland** [comment] 2021-01-15 00:20
>  clicking on the "preset" drop-down doesn't do anything:

I cannot reproduce this. Does that happens with a new empty db ? 



> However, only the "preset" and "tags" labels are greyed out (to indicate that the fields are inactive).

You right. These active labels are related flags (which appear when you unselect write xmp). 
But when these flags are not visible, yes these labels should be disabled. I'll fix that.

**Comment by phweyland** [comment] 2021-01-15 00:27
> darktable 3.5.0+639~gc77f1ff43

The PR #7846 has been merged in between with some code refactoring on this part. Would be nice if you check if the first issue is still there. TIA.

**Comment by elstoc** [comment] 2021-01-15 08:44
> The PR #7846 has been merged in between with some code refactoring on this part. Would be nice if you check if the first issue is still there. TIA.

Yes. Same issue with 3.5.0+650~gf51e05e40 and a clean config directory

**Comment by phweyland** [comment] 2021-01-15 11:16
Thanks for testing. 
I've fixed the second issue.
Enabling / disabling presets occurs in the same part of code. I still do not reproduce the issue and I don't see anything wrong in the code so far... (I should be blind somehow...).

... the preset list is locked, so it must present.
What could explain this combo box remains disabled ? ...
Anybody else with the same issue ?

**Comment by elstoc** [comment] 2021-01-15 14:48
@phweyland presumably you can't reproduce the issue with a clean config either? I'm running two different versions (one tracking master and one for development) and both are exhibiting the issue.

**Comment by elstoc** [comment] 2021-01-15 15:21
I've put some in some debug messages and it appears that none of the code in the while loop that iterates through `SELECT name, op_params FROM data.presets WHERE operation = 'metadata'` is being executed. So the issue is that the combobox is empty.

Still no idea why though.

**Comment by phweyland** [comment] 2021-01-15 15:32
Thank you for that.
Do you have presets in metadata editor ?

**Comment by elstoc** [comment] 2021-01-15 15:37
Yes I see the presets in the metadata editor.

**Comment by phweyland** [comment] 2021-01-15 17:14
Following the presets query idea.... What do you have in data.presets table for metadata ?
Here what I have (after having started a clean db):

![image](https://user-images.githubusercontent.com/23012047/104757210-84f0e980-573b-11eb-8038-335f6f5de1db.png)

I could also make a try with your data.db if you don't mind to share it, the one started with a clean db.
If there is any error I'll try to understand why...

**Comment by elstoc** [comment] 2021-01-15 17:26
> What do you have in data.presets table for metadata
I thought of that - I tried running the same SQL directly in the database and it looked fine. Here's my clean data.db...

[data.db.zip](https://github.com/darktable-org/darktable/files/5822075/data.db.zip)

I've gone down a few blind alleys now - I can't figure it out.

**Comment by phweyland** [comment] 2021-01-15 18:03
> data.db.zip

Thanks. No chance. The content seems correct and, it still works for me.

Just an idea. Sometime ago I've introduce an addon to sqlite, ICU. Could you check if you have "ICU not found" in your build ?

The difference between our dt installations is only the environment (no images, no db, ...) ... maybe other thing that ICU.

**Comment by elstoc** [comment] 2021-01-15 18:07
ICU shows as found

**Comment by phweyland** [comment] 2021-01-15 19:44
Maybe an obvious one: do you have any sqlite claim on the console ?

If you could be kind enough to replace the query part with this one and make a try, that could give some indication (unless you already done, of course):

```
  sqlite3_stmt *stmt;
  int rc = sqlite3_prepare_v2(dt_database_get(darktable.db), "SELECT name, op_params FROM data.presets WHERE operation = 'metadata'", -1, &stmt, NULL);
  printf("sqlite prepare %d\n", rc);
  while((rc = sqlite3_step(stmt) == SQLITE_ROW))
  {
    void *op_params = (void *)sqlite3_column_blob(stmt, 1);
    int32_t op_params_size = sqlite3_column_bytes(stmt, 1);

    char *buf = (char *)op_params;
    char *metadata_param[DT_METADATA_NUMBER];
    uint32_t metadata_len[DT_METADATA_NUMBER];
    uint32_t total_len = 0;
    for(unsigned int i = 0; i < DT_METADATA_NUMBER; i++)
    {
      metadata_param[i] = buf;
      metadata_len[i] = strlen(metadata_param[i]) + 1;
      buf += metadata_len[i];
      total_len +=  metadata_len[i];
    }
    printf("sqlite step len %d\n", total_len);
    if(op_params_size == total_len)
    {
      gtk_list_store_append(model, &iter);
      // column 0 give the name, the following ones the different metadata
      gtk_list_store_set(model, &iter, 0, (char *)sqlite3_column_text(stmt, 0), -1);
      for(unsigned int i = 0; i < DT_METADATA_NUMBER; i++)
      {
        gtk_list_store_set(model, &iter, i+1, metadata_param[i], -1);
      }
    }
  }
  printf("sqlite end %d\n", rc);
  sqlite3_finalize(stmt);
```

My output is the following:
```
sqlite prepare 0
sqlite step len 43
sqlite step len 57
sqlite step len 55
sqlite step len 60
sqlite step len 74
sqlite step len 72
sqlite step len 27
sqlite end 0
```

TIA

**Comment by elstoc** [comment] 2021-01-15 20:03
Yeah I did something similar. I just get
```
sqlite prepare 0
sqlite end 0
```

**Comment by phweyland** [comment] 2021-01-15 20:43
> but I just don't know why that SQL is returning no rows, when every other select from the presets table everywhere else in darktable seems to be working.

Yes, that is the question...
That seems not to be linked to the query itself. This specific part of the code has not changed for while.
This should be more a question of machine context ...

One of the last change was to move all this stuff from a popup dialog to a view/lib/plugin. From sequencing standpoint that can make a difference. But why it works on my machine and  not on yours ?

On a clean db, if init_preset of metadata doesn't run before gui_init of import, the presets table can be empty...
Eliminating this hypothesis is simple. Relaunch dt without cleaning up the newly created db... I'm sure you have already checked that, right ? :smiley: Reading the code this is possible as init_preset and gui_init are called sequentially for each module...

**Comment by elstoc** [comment] 2021-01-15 21:17
> Relaunch dt without cleaning up the newly created db... I'm sure you have already checked that, right ?

Yes - already checked that.

Something interesting though: I've added the following code snippet to `libs/import.c` immediately after the call to `dt_import_metadata_init`

```
  sqlite3_stmt *stmt;
  int rc = sqlite3_prepare_v2(dt_database_get(darktable.db), "SELECT 1 FROM data.presets where operation = 'colorcorrection'", -1, &stmt, NULL);
  printf("sqlite prepare %d\n", rc);
  while((rc = sqlite3_step(stmt) == SQLITE_ROW))
  {
    printf("sqlite row\n");
  }
  printf("sqlite end %d\n", rc);
  sqlite3_finalize(stmt);
```
This returns
```
sqlite prepare 0
sqlite row
sqlite row
sqlite row
sqlite end 0
```
I get similar results (non-zero rows returned) if I replace 'colorcorrection' with any of the iop preset operations - I've tried filmic, exposure, lowlight. 

However, if I replace it with 'collect', 'metadata', 'modulegroups' or 'ioporder' (lib modules) I consistently get 0 rows

**Comment by elstoc** [comment] 2021-01-15 21:31
It looks to me like darktable deletes and re-inserts all hard-coded presets every time it launches so it's entirely possible that the metadata presets don't exist yet when the import lib is loaded. If I add my own user-generated preset to the metadata module and restart darktable this appears in the combobox fine.

![Screenshot_2021-01-15_21-31-29](https://user-images.githubusercontent.com/9555491/104780688-0dda4600-5779-11eb-937f-343f98139bb7.png)

**Comment by phweyland** [comment] 2021-01-16 10:23
Well done ! Thanks for your help.

Preventing dt to erase presets before inserting the hard-coded ones is probably not the right way to solve this (some hard-coded presets may be removed and they need to be cleaned up).

So we need to refresh the combobox after initialization (and BTW any change) of the metadata presets ...
I'll look at this.

**Closed** 2021-01-18 10:51 UTC
