### ISSUE TITLE
v3.4 - darktable crashes when clicking an image in culling dynamic zoom

### ISSUE THREAD

**Issue by jobec** [darktable-org/darktable#7423] opened 2020-12-24 09:47 UTC
**Describe the bug**
After switching to culling in lighttable and setting it's mode to dynamic zoom, clicking any image crashes darktable.

ctrl+clicking an image does **not** crash it.

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: Windows 10 (1904)
 - No openCL

**Traceback**

[darktable_bt_0ULKW0.txt](https://github.com/darktable-org/darktable/files/5739105/darktable_bt_0ULKW0.txt)

**Comment by TurboGit** [comment] 2020-12-24 11:51
Cannot reproduce in current master.

**Comment by TurboGit** [comment] 2020-12-24 11:58
But can be reproduce in 3.4.0, so fixed since.

**Comment by johnny-bit** [comment] 2020-12-24 12:02
So... Will be fixed in release 3.4.1, right?

**Comment by AlicVB** [comment] 2020-12-24 12:12
I confirm @TurboGit observation, in fact I have fixed it in https://github.com/darktable-org/darktable/commit/5c2d13c1367c93d4a921055c6832fc53bf22591b
Thanks for the report !

**Closed by AlicVB** 2020-12-24 12:12 UTC
Labels: bug: fixed

**Comment by TurboGit** [comment] 2020-12-24 12:54
And this commit is on 3.4.x branch so will be part of 3.4.1.
