### ISSUE TITLE
image is shown although it doesn't match filter criteria

### ISSUE THREAD

**Issue by j-schneid** [darktable-org/darktable#6078] opened 2020-08-23 19:39 UTC
When filtering a collection (narrowing down the current selection) e.g. by adding a color label, images may be shown which don't have that color label but a different one.

![color_label_filter_bug](https://user-images.githubusercontent.com/34659835/90987049-2a869f00-e588-11ea-981d-a327785914e5.png)
Example screenshot: Thumbnail on the right has no red label but is shown although color label red is set as filter.

It also shows if I select any other label, or if I filter by time span, by stars.

I can't see what makes this image different from others. I can't provide steps to reproduce this behaviour.

Current version 3.2 on Windows 10

**Comment by maboleth** [comment] 2020-08-23 23:18
Works on my end in git-master version. All colors are sorted as should.

**Comment by johnny-bit** [comment] 2020-08-24 09:00
can you try backing up your config dir, then start afresh, reimport dir with file with problems and check if tag issue is still present?

I've tried to replicate your issue to no avail. (3.2.1 and current master, both on linux)

**Comment by johnny-bit** [comment] 2021-05-18 18:32
Closing as "cannot reproduce". There were recent changes to `collections` module, which might help alleviate this case.

**Closed by johnny-bit** 2021-05-18 18:32 UTC
Labels: no-issue-activity
