### ISSUE TITLE
[FR] Darkroom Style module for faster workflow

### ISSUE THREAD

**Issue by B2F** [darktable-org/darktable#14076] opened 2023-03-31 16:42 UTC
**Is your feature request related to a problem? Please describe.**

I like to work with styles but sometimes the style would suit to only a part of the picture, using masking capabilities. To do this currently requires to create a mask and to apply it to each modules used by the style separately.

**Describe the solution you'd like**

A style module in the Darkroom with the following components:

**** Select list to choose a style
**** The usual mask bar with opacity, paint tools etc
**** Apply button

Each time you apply a style using the above selection, modules are instantiated using the selected style file settings for their value and the above mask settings is also referenced in each of those modules.

I don't know if a preview of the combo style + mask could be done before applying it (seems like it could be hard to implement or not good performance wise),  but this doesn't need to be. Otherwise, this sounds like feasible feature using only existing logic ?

I would code it myself but as a stranger to this code base and with few C/++ skill, I don't know were to start.

**Comment by B2F** [comment] 2023-03-31 16:45
Also this module could have a override / replace checkbox. I see it as a handy evolution / replacement for the existing style select button list in the darkroom view.

**Comment by ralfbrown** [comment] 2023-07-25 02:54
Adding the "same" mask to multiple modules only works for raster masks and drawn masks, not parametric or drawn+parametric (since the parametric settings will select different sets of pixels on each module).  For raster masks, you'd also need to be able to select which module generates the raster.

Overall, this would be tricky to implement both on the pixelpipe side and on the UI side....

**Comment by ralfbrown** [comment] 2024-01-12 05:30
A workaround is now possible with the new "overlay" module added by #15465 .  Make a duplicate of the image, add the style to the duplicate, then use the duplicate as an overlay and select which portion of the image you want the style to apply to by adding a mask to the overlay module.

**Closed by ralfbrown** 2024-01-12 05:30 UTC
Labels: feature: new, difficulty: hard, scope: UI, scope: image processing, no-issue-activity

**Comment by B2F** [comment] 2024-02-21 19:19
Interesting, thanks.
I was initially thinking that a straightforward way to paint with styles could be interesting. That module would be presenting the list of style, we could pick one and the overlay you mention would then be apply automatically.
Not tried yet as I'm still using 4.6
