### ISSUE TITLE
`$(WIDTH.EXPORT)` and `$(HEIGHT.EXPORT)` not working as intended

### ISSUE THREAD

**Issue by jchnkl** [darktable-org/darktable#13987] opened 2023-03-20 12:37 UTC
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

`$(WIDTH.EXPORT)` and `$(HEIGHT.EXPORT)` not working as intended. The output file will always contain `0` instead of the actual export size

**To Reproduce**

* Export a file with `$(WIDTH.EXPORT)` and `$(HEIGHT.EXPORT)` set, e.g.
  `/tmp/$(FILE_NAME)-$(WIDTH.EXPORT)x$(HEIGHT.EXPORT)`

* The exported file will look like this: `/tmp/my_file-0x0.ext`

**Expected behavior**

Use the actual exported width / height instead of `0`.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

```
$ darktable --version

this is darktable 4.2.0
copyright (c) 2009-2022 johannes hanika
https://github.com/darktable-org/darktable/issues/new/choose

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.0.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support disabled
  libheif support enabled
  libjxl support disabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled
```
```
$ uname -a
Linux monolith 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

* Linux - Distro    : Ubuntu 22.04.1 LTS
* Memory            : 64GB
* Graphics card     : Nvidia
* Graphics driver   : 
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

darktable was installed from the OpenSUSE OBS build service

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **NO**

I ran darktable with `--configdir /tmp`, discarded the history and WIDTH.EXPORT / HEIGHT.EXPORT were properly set.
After that I ran my regular darktable, exported the very same picture with discarded history and it did not work.
Only after discarding the history _again_ it would set the proper width / height.
I've copy/pasted (overwrite) the history from edit to a picture with discarded history and w/h works!
I've tried with another picture, same behavior
-> Attached you'll find the XMP of the edit

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **YES**
 - Do you use lua scripts? **NO**

Github does not support XMP files..
[2021-07-23T05:23:14+0200_0097.arw.xmp.txt](https://github.com/darktable-org/darktable/files/11017828/2021-07-23T05.23.14%2B0200_0097.arw.xmp.txt)

**Comment by pehar1** [comment] 2023-03-24 06:24
Not able to reproduce with 4.3.0+1357~g0efd7a97ad on Ubuntu 22.04. Can you show the entries of the export dialog you are using when the issue appears?

**Comment by jchnkl** [comment] 2023-03-27 11:11
Here's a screenshot:

![image](https://user-images.githubusercontent.com/1392715/227925269-3d58b776-28ad-42b4-9695-06e418c2bbed.png)

I use this string for export:

```
/some/folder/export/$(FILE_NAME)$(TITLE+_$(TITLE))$(DESCRIPTION+_$(DESCRIPTION))_$(WIDTH.EXPORT)x$(HEIGHT.EXPORT)$(CATEGORY0(intent)+_$(CATEGORY0(intent)^^))
```

Is there an easy way to obtain the dev env or the dev version? Like a docker container or so?

**Comment by TurboGit** [comment] 2023-03-27 12:23
Cannot reproduce on 4.3, so probably fixed already and will be part of 4.4.

**Comment by TurboGit** [comment] 2023-03-27 15:45
> Didn't get around to report that, also because it's hard to reproduce, but I'll do it if it still happens in 4.4.

There was some fixes in mask but better try to report before 4.4 is out because there is very little chance it gets fixed otherwise. So if you have some time to get a reproducer do not hesitate. TIA.

**Comment by jchnkl** [comment] 2023-03-28 10:16
> There was some fixes in mask but better try to report before 4.4 is out because there is very little chance it gets fixed otherwise. So if you have some time to get a reproducer do not hesitate. TIA.

Thanks for the encouragement! I'll try and do my best :)

Should I close this one and reopen if the export variables don't work for me in 4.4 or leave it open and wait?

**Comment by TurboGit** [comment] 2023-03-28 11:17
Yes, I'll close this for now and we can reopen if needed.

**Closed by TurboGit** 2023-03-28 11:17 UTC

**Comment by debajit** [comment] 2025-04-27 04:41
I am still seeing the issue when I export an entire collection (consisting of 22 images). I used the export filename pattern:

```
$(FILE_FOLDER)/Exports/$(EXIF.YEAR)_$(EXIF.MONTH)_$(EXIF.DAY)_$(TITLE// /_)_$(SEQUENCE)_$(WIDTH.EXPORT)_x_$(HEIGHT.EXPORT)
```

This is with Darktable 5.0.1 on Arch Linux (installed via package manager)
