### ISSUE TITLE
Interface settings lost and no more histogram in darkroom

### ISSUE THREAD

**Issue by cerlienkus** [darktable-org/darktable#7469] opened 2020-12-26 16:34 UTC
**Describe the bug**
Hello,
I've just installed darktable 3.4 on windows 10 and I've got some issues with the UI.
First time opening it was as usual then, after doing some edits I closed it.
After reopening I realised that UI was changed and there was an issue with the histogram wich had disappeared.

I unistalled it and deleted the configuration directory and reinstalled and it behaved normally. Unfortunately I opened it again and got the issue back

**To Reproduce**

I did not significant changes in the preferences. Only changed the process workflow from screen referred to scene referred and cromatic adaptation from legacy to modern

**Expected behavior**
when I open the program, the UI should appear in this manner:

![image](https://user-images.githubusercontent.com/69572937/103155237-12c16080-479e-11eb-94f9-708ef0e451d3.png)
and histogram:
![image](https://user-images.githubusercontent.com/69572937/103155253-32f11f80-479e-11eb-857d-4ccfebcad819.png)

**Screenshots**
this is how UI and histogram appeared when the issue arose itself:

![image](https://user-images.githubusercontent.com/69572937/103154963-d5f46a00-479b-11eb-9523-282b796f3ce4.png)
![image](https://user-images.githubusercontent.com/69572937/103154976-f0c6de80-479b-11eb-859a-98b5da3ff713.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: Windows 10
 - It seems the problem persists indepently from activation or deactivation of OpenCL Check
 - Graphic card: NVIDIA GeForce GTX 1050 Driver Version: 27.21.14.5241

**Additional context**
As I said, I unistalled dt 3.4 and got rid of configuration directory and seemed to have solved the issue but I got it back again.

**Comment by johnny-bit** [comment] 2020-12-26 16:48
Duplicate of #7467

**Comment by johnny-bit** [comment] 2020-12-26 16:49
@cerlienkus - please continue in #7467 - it seems that you and @Lorenzoeffe have same root cause. we need to find a common cause for this.

**Closed** 2020-12-26 16:50 UTC
