### ISSUE TITLE
Exporting isn't fully working on windows with Nikon D810 NEF

### ISSUE THREAD

**Issue by pixmin** [darktable-org/darktable#2113] opened 2019-02-18 20:16 UTC
When exporting a NEF from a Nikon D810 on Windows, 2/3 of the image is black (as if 2/3 of the image is missing). Exporting the same NEF file from Linux (same 2.6 Darktable version) works just fine.

Happy to supply the NEF, exported JPG or XMP file.

**Comment by pixmin** [comment] 2019-02-18 20:18
Adding scaled JPG for preview of the problem
![dsc_3389_win_scaled](https://user-images.githubusercontent.com/244678/52974673-b089be80-33c2-11e9-8891-67d88d142333.jpg)

**Comment by pixmin** [comment] 2019-03-18 08:17
Just to confirm, after installing Ubuntu with Darktable 2.6.1, I can confirm that exporting the same photo works just fine.

I have tried to disable all modules but there is always a large portion of the photo that is only black (that black part isn't always the same)

**Comment by johnny-bit** [comment] 2020-12-20 13:53
I've tested current master with raw samples from raw.pixls.us and seen no problem with them... I've lso tested on 3.2.1 on windows...

Is the issue still present for you in say 3.2.1? If yes - can you provide xmp (and if you can the NEF file?)

**Comment by johnny-bit** [comment] 2021-01-20 06:59
After checking it further and seeing different "part of image is black on export" report I'd say it might be related to OpenCL problems. If the problems aren't present on linux but are on windows, then my recommendation would be to look into graphics drivers on windows. And trying with OpenCL disabled...

Anyway - Closing for now, since bug report mentions old version and a lot of things changed in last 2 years since the report was made. If the problem is still present on newest release - please open a new issue :)

**Closed by johnny-bit** 2021-01-20 06:59 UTC
Labels: no-issue-activity, understood: unclear
