### ISSUE TITLE
New Styles crashes Darktable

### ISSUE THREAD

**Issue by phenrypereira** [darktable-org/darktable#16803] opened 2024-05-16 02:02 UTC
### Describe the bug

Creating new Styles from the styles menu in the light table quits Darktable without any error or "not responding" messages

### Steps to reproduce

1. Launch Darktable
2. In the light table select an image
3. In the Styles menu, click Create
4. In the "Create New Style" window, click Clear Selection
5. Click any checkbox

### Expected behavior

It is expected that in the Create new style window I can easily define which modules to add, remove or reset state to the default in the style I am creating.

### Logfile | Screenshot | Screencast

[darktable_log.txt](https://github.com/darktable-org/darktable/files/15328647/darktable_log.txt)

### Where did you obtain darktable from?

an online forum

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 22.04

### Describe your system?

System: KDE Neon 6 (Ubuntu 22.04)
RAM: 16GB (dual-channel)
CPU: AMD Ryzen 3 3200G

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This doesn't happen when I create new styles from an image opened in the dark room.

**Comment by wpferguson** [comment] 2024-05-16 02:23
Can't reproduce on 22.04 running current master

**Comment by gi-man** [comment] 2024-05-16 02:31
Duplicate of https://github.com/darktable-org/darktable/issues/16096, https://github.com/darktable-org/darktable/issues/16140, and https://github.com/darktable-org/darktable/issues/16513. Fixed in master

**Closed** 2024-05-17 02:32 UTC
Labels: Fixed in master
