### ISSUE TITLE
(3.8.1) Could not Export Image

### ISSUE THREAD

**Issue by Jasonious530** [darktable-org/darktable#11211] opened 2022-02-23 15:31 UTC
Unable to export images in DT 3.8.1

Images are from a Canon EOS sl3 in .cr3 format, then converted with AdobeDNG before adding to my DT library.

I have tried numerous file formats and tried both edited and unedited images from my library. (I do have **auto-apply sharpen** selected I just realized, so I guess none of the images are "unedited")

I bumped up the **Host Memory Limit for Tiling** to 2500 and then 4000 as recommended in another issue but it did not work.

I also tried to change the destination folder from a folder/subfolder to my desktop but I had the same results.

![2022-02-22 (1)](https://user-images.githubusercontent.com/90074921/155350036-8b32b035-a230-4106-9d64-e59690312928.png)
![2022-02-23](https://user-images.githubusercontent.com/90074921/155350057-259c3bb4-848a-4df3-bbfa-76f1f68a3aeb.png)

**Comment by gi-man** [comment] 2022-02-23 15:55
Jason, I think you should provide more information to aid in this issue. Based on the logo, I think this is in Windows 10. OpenCL active? Can you provide an output of the DT log file to see what error the export has?

**Comment by Jasonious530** [comment] 2022-02-23 16:12
Yes, Windows 10.

The only Error report generated was unrelated to export, but here it is:

Source
darktable photo workflow software

Summary
Stopped responding and was closed

Date
‎2/‎22/‎2022 8:27 PM

Status
Report sent

Description
A problem caused this program to stop interacting with Windows.
Faulting Application Path:	C:\Program Files\darktable\bin\darktable.exe

Problem signature
Problem Event Name:	AppHangB1
Application Name:	darktable.exe
Application Version:	3.8.1.0
Application Timestamp:	00000000
Hang Signature:	cc95
Hang Type:	134217728
OS Version:	10.0.19044.2.0.0.768.101
Locale ID:	1033
Additional Hang Signature 1:	cc953e6bfbbcaad024165209f99731ba
Additional Hang Signature 2:	d083
Additional Hang Signature 3:	d08396106ea80345e2cd983a275258fc
Additional Hang Signature 4:	cc95
Additional Hang Signature 5:	cc953e6bfbbcaad024165209f99731ba
Additional Hang Signature 6:	d083
Additional Hang Signature 7:	d08396106ea80345e2cd983a275258fc

Extra information about the problem
Bucket ID:	1902a9eb2eba0297f0d88d3a9aafa528 (1213875382419170600)

**Comment by Jasonious530** [comment] 2022-02-23 16:30
I installed OpenCL and OpenGL compatibility app from microsoft store. DT will not open now and wrote a .txt error
[darktable_bt_HKVTH1.txt](https://github.com/darktable-org/darktable/files/8126064/darktable_bt_HKVTH1.txt)

**Comment by parafin** [comment] 2022-02-23 16:44
Well, remove it.

**Comment by Jasonious530** [comment] 2022-02-23 17:07
Uninstalled OpenCL/GL compatibility and did a fresh install of DT 3.8.1 and restarted my PC
DT opens now
Export still broken
Looking for the log, but INetCache does not exist in the Windows folder indicated above.

**Comment by Jasonious530** [comment] 2022-02-23 17:10
darktable-log.txt returns no results anywhere in my C:\Users

**Comment by TurboGit** [comment] 2022-02-23 17:14
Is that expected that you have double back-slash as all directory separator in the export module?

**Comment by Jasonious530** [comment] 2022-02-23 17:19
I used the file finder to select the locations. should I enter the location in manually?

**Comment by Jasonious530** [comment] 2022-02-23 17:21
Entered the export location manually with single backslashes and it still did not work.

**Comment by gi-man** [comment] 2022-02-23 18:25
Jason:

Run from cmd:
darktable -d all
then provide the log. The log you posted is empty. 

Also the INetCache is a hidden folder on windows. If you copy/paste the folder link it will work.

**Comment by Jasonious530** [comment] 2022-02-23 18:45
[darktable-log.txt](https://github.com/darktable-org/darktable/files/8126968/darktable-log.txt)


Okay, found the hidden folder and attached the darktable-log.txt that was there.

**Comment by gi-man** [comment] 2022-02-23 18:55
Microsoft Windows [Version 10.0.22000.493]
(c) Microsoft Corporation. All rights reserved.

C:\Users\[USERNAME]>cd..

C:\Users>cd..

C:\>cd program files/darktable/bin

C:\Program Files\darktable\bin>darktable -d all

C:\Program Files\darktable\bin>

**Comment by Jasonious530** [comment] 2022-02-23 18:55
I noticed that when I use the file finder button in the Export module, it does add double backslashes to the directory, BUT when the error pops up it only shows one backslash. When I tried to type the location in manually with only one backslash, the error showed the location as having NO backslashes
![2022-02-23 (3)](https://user-images.githubusercontent.com/90074921/155387983-b3b39f12-beda-48a1-8890-c79a30a749cb.png)
![2022-02-23 (4)](https://user-images.githubusercontent.com/90074921/155387999-d8d3f6e2-0da3-4b17-86cc-461c66c9c3b6.png)
.

**Comment by Jasonious530** [comment] 2022-02-23 18:59
Ok, Heres the .txt after the cmb prompt

[darktable-log.txt](https://github.com/darktable-org/darktable/files/8127046/darktable-log.txt)

**Comment by gi-man** [comment] 2022-02-23 20:27
Your graphics card is blacklisted and the log sys it is OpenCL off, therefore that is not the cause of the problem.

Did you try to export while using the cmd darktable -d all? I dont see any export.
What is the full path of your raw images? C:\ ... I want to verify for special characters in the path.

**Comment by Jasonious530** [comment] 2022-02-23 20:37
I have onboard graphics only. Ok, I exported while using the cmd darktable -d all, then I closed DT and foind the newly modified darktable-log.txt.

The full path of my raw images I added to the library is
C:\Users\jason\Desktop\Photography\Imports\February

The path I am trying to export them too is
C:\Users\jason\Desktop\Photography\Exports

[darktable-log.txt](https://github.com/darktable-org/darktable/files/8127639/darktable-log.txt)

**Comment by Jasonious530** [comment] 2022-02-23 20:38
The paths are copy and pasted from windows

**Comment by Jasonious530** [comment] 2022-02-23 20:45
C:\\Users\\jason\\Desktop\\Photography\\Exports\\$(FILE_NAME)

**Comment by Jasonious530** [comment] 2022-02-23 20:46
There's double slashes when I paste it, but when I submit the comment it changes it to one slash between

**Comment by gi-man** [comment] 2022-02-24 00:29
I tried to read the log file on my cellphone earlier today. That was a mistake while using the -d all command. It is very long. :-) In hindsight -d perf was probably enough. 

I see that the export is developed and it looks to me without errors:
39.723776 [dev_process_export] pixel pipeline processing took 7.267 secs (32.594 CPU)
but then:
[imageio_storage_disk] could not export to file: `C:\Users\jason\Desktop\Photography\Exports\022222IMG_51920226.jpg'!
39.886935 [run_job-] 04 355040382.272873 39.886993 export | queue: 3 | priority: 039.887035 

The folder is not write protected, correct? I'm not sure what is going on.

**Comment by Jasonious530** [comment] 2022-02-24 00:33
Correct, It is not a write protected file. I just created it via windows explorer before adding these pictures to it. I have also tried using other locations on my PC with no luck.

**Comment by Jasonious530** [comment] 2022-02-24 01:57
So i just tried to export with **Target Storage** set to 'send as email" and it exported a .jpg to C:\Users\jason\AppData\Local\Temp

Here's a screenshot of where and how I found it.

![2022-02-23 (7)](https://user-images.githubusercontent.com/90074921/155442099-be4880e0-7b99-44df-80e4-0c1ebf07542a.png)

Could it be an issue with DT **File on disk** target within the module? or maybe the extra slashes that appear in the file path within the module, and then disappear in the error message? 

I appreciate all the support by the way!! This is my first time trying DT and also my first time on github.

**Comment by gi-man** [comment] 2022-02-24 03:24
Ive reached the max of my limited expertise. I'm just trying to rule out stuff. Like I said, it is not OpenCL. I dont see a failure in the image generation process (export). I see that I just cant record the image. 

I'm running win11 with DT 3.9.0+219~g06ad12bae. I'm able to export images. Therefore I dont think there is an issue with DT code, but someone with more expertise will need to evaluate. 

Just another random idea, do you have an antivirus installed? Could it be blocking DT?

**Comment by Jasonious530** [comment] 2022-02-24 03:32
No worries. I'll continue to try different things and update here if anything bears fruit. 

I do have AVG Free and Malwarebytes(Free) installed, however neither alerted me of anything. I will check those now.

**Comment by Jasonious530** [comment] 2022-02-24 04:04
I added an Exception in AVG Free to include C:\Program Files\darktable and all subfolders and I was able to export an image. DT successfully wrote the .jpg to the destination folder. AVG did not alert me during any of the attempts I had made thus far and it usually adds frequently used software to the exception list automatically.

**Comment by gi-man** [comment] 2022-02-24 04:20
Therefore it is solved? If yes, can you close the issue?

**Closed** 2022-02-24 05:44 UTC
