### ISSUE TITLE
Edit history spammed with bad module

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#13801] opened 2023-03-03 08:20 UTC
![badlenscorrect](https://user-images.githubusercontent.com/10678620/222667579-96b675bd-4f29-44bc-93c1-05c3fbc9f2bb.png)

Compiling the latest master, I noticed this behavior as I was making some edits. My camera/lens combo is not automatically detected, but this condition seems to lead to the weird history behavior in the left pane.

Whenever any module is changed, all modules that have a warning are appended to the edit history. I can duplicate the behavior with white balance+color calibration as well. Every time I adjusted the tone equalizer, lens calibration was appended to the history.

Platform: archlinux
Darktable version:4.3.0+896~g4e4e7b65d7

**Comment by MStraeten** [comment] 2023-03-03 09:31
seems to be a duplicate to https://github.com/darktable-org/darktable/issues/13737

**Comment by groutr** [comment] 2023-03-03 19:26
@MStraeten, yes this might be a duplicate. However, this issue also uncovered another bug I noticed this morning.

**Comment by TurboGit** [comment] 2023-03-03 21:49
> However, this issue also uncovered another bug I noticed this morning.

What is this issue you are talking about?

**Comment by groutr** [comment] 2023-03-03 21:50
> > However, this issue also uncovered another bug I noticed this morning.
> 
> What is this issue you are talking about?

The issue that is tagged above (#13812)

**Comment by TurboGit** [comment] 2023-03-03 21:55
> The issue that is tagged above (#13812)

Ah I was looking at this and I can reproduce. Something recent I suppose?

**Comment by groutr** [comment] 2023-03-03 22:02
> > The issue that is tagged above (#13812)
> 
> Ah I was looking at this and I can reproduce. Something recent I suppose?

Relatively recent, I think. The last build I did (4.3.0.r768.g0f1ebfba40) did not have the issue.

**Comment by TurboGit** [comment] 2023-03-04 10:26
Should be fixed.

**Closed by TurboGit** 2023-03-04 10:26 UTC
