### ISSUE TITLE
Colormapping reset does not work after target clusters acquired.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7942] opened 2021-01-20 10:41 UTC
Build type : Debug.
Master : 3.5.0+755~g1fd4e1b42

Acquire target from image.
Try to  reset module, nothing happens, the acquired colors remain.

Compress history to just before color mapping.
Open the color mapping module, the acquired colors are still there.

Change the number of clusters and this will get rid of the colors. 
But reset module  this and colors come back.

Restart DT. Acquired colors are still there.

**Comment by johnny-bit** [comment] 2021-01-20 15:04
This works as intended in the colormapping module. It's cross-image, cross everything and acquired data *stays*

**Comment by mchhil** [comment] 2021-01-20 15:30
If it works as intended, how do you reset it after colors are acquired? Does reset even work? Why does it persists across dt restarts even when the module is not enabled?

**Comment by todd-prior** [comment] 2021-01-20 16:53
There was some previous discussion on this here    https://github.com/darktable-org/darktable/issues/6381#issue-709415062

**Comment by johnny-bit** [comment] 2021-01-20 18:05
Closing as "works as intended".

You don't have to clear the source, simply acquire new source and it'll work. Changing the patches size etc works, so no problem there. Just assume `colormapping` is "one of those quirky modules" and as long as it works as intended it's all good ;)

**Closed by johnny-bit** 2021-01-20 18:05 UTC
Labels: bug: invalid
