### ISSUE TITLE
Improve and simplify preferences content

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#7050] opened 2020-11-24 17:10 UTC
**Is your feature request related to a problem? Please describe.**

darktable become more and more configurable on each release. Globally it's a good thing but we need to take care about not overload preferences. They're probably already a little bit. Saying that, it's hard to see which settings are surplus. Maybe all are welcomed and needed.

Said that, by checking settings, some are specific to a module and could be moved. For example, a setting for white balance and a setting for color balance. But maybe more could be moved.

This comes from previous discussion in some PR or issues like  #6706, #7021 or #6704

**Describe the solution you'd like**

We already have some modules, in lighttable, with specific preferences like metadata editor or export ones. The idea would be to moved really specific settings to a module in the module.

That could simplify a little bit preferences window and so help finding remaining settings more quickly and at the same time, having specific settings of a module directly accessible in the module or part of lighttable. 

We just need to be careful to only moved some specific settings. To avoid moving too much settings (that could be the risk), I think only some settings for a specific part of a darktable view could be moved. For example, moving settings for darkroom, it's no but moving a setting for a darkroom module, that could be yes as it's a specific part of the view and not related to the view or many parts of the view. Hope I'm clear here about the limit to fix.

The idea here is to discuss about that and see how that could be moved for next release. That could be for the next minor one 3.4.1 or next major one, depending on choices discussed.

Some settings I think they can be moved:

**- In lighttable tab:**
_delimiters for size categorise_
_overlay txt sidecar over zoomed images_

They can be moved in star overlays menu as they are related to information and display of thumbnail, visually, like all other options in star overlays menu.

**- In darkroom tab:**
_ white balance slider colors_: could be moved in white balance module
_colorbalance slider block layout_: could be moved in color balance module

Those are just ideas and could be changed/completed/updated, etc. It's all about discussing that and find the best way for a better experience. We need to remember some things for that discussion:

- Avoid to have in the future an overloaded preferences window
- Be sure all choices are consistent between them
- Avoid having also too many places for settings (that's the main reason for my suggestion to limit setting to be moved to specific part of a view, cited above here)

@elstoc, @jenshannoschwalm, @TurboGit, @aurelienpierre, @AlicVB, @johnny-bit: your views are welcomed here.

**Comment by AlicVB** [comment] 2020-11-24 18:11
@Nilvus : first, I completely agree.

Now for the part I know the best : 
- `overlay txt sidecar over zoomed images` is not used anymore... good catch. Just done a PR to remove it.
- `delimiters for size categories` : I would really prefer to remove that from pref and to put that in the overlay menu, but I'm not sure where, as currently all items of the menu are for the current size, and the above pref is to define the category of size... Maybe you have some idea ?

**Comment by AxelG-DE** [comment] 2020-11-24 18:14
I am not asked in the first place here, but here is my ideas:

1) like other software, have an expert mode, which holds lots of advanced stuff and in normal mode it is hidden
2) I do not opt for spreading prefs into the modules, that ends up in having the prefs spread all over the system.
- hence have a module-specific tab in prefs where all module spefic thingies go into and can be grouped by module name

**Comment by Nilvus** [comment] 2020-11-24 18:25
>     * `overlay txt sidecar over zoomed images` is not used anymore... good catch. Just done a PR to remove it.

And one less. Great.

>     * `delimiters for size categories` : I would really prefer to remove that from pref and to put that in the overlay menu, but I'm not sure where, as currently all items of the menu are for the current size, and the above pref is to define the category of size... Maybe you have some idea ?

Not sure as I never use it and I'm quite sure few users will use it. I'm even not really sure myself of how to set them (tooltip is not clear). If I'm not wrong, you could choose just 2 limits of size for thumbnails and how to display them. If I'm not wrong, I see 2 possibilities. In both, add that with a sort of min/max instead of a separator to simplify and so add it on top of overlay menu, just before title to set it and so then have the options for current size set. But of course, that would need that part of the menu could be adjusted dynamically, independently of this first setting. I don't know if this is possible). The other way would be to add that setting in bottom bar, at the left of the combobox used to select thumbnail mode (culling, file navigator...)

**Comment by Nilvus** [comment] 2020-11-24 18:32
> I am not asked in the first place here, but here is my ideas:

All views are welcomed!

>     1. like other software, have an expert mode, which holds lots of advanced stuff and in normal mode it is hidden

It's an idea, even if I don't like it. Having an expert mode for me is the risk to not limit settings and so overload preferences, even if we add it. And darktable is mainly made for users who want advanced possibilities to process their images. But it's just my opinion.

>     2. I do not opt for spreading prefs into the modules, that ends up in having the prefs spread all over the system.

That's why I write that we should limit that to few options for specific module. And if you look carefully darktable, you will see that they are already settings in many specific places like metadata editor, export module, color picker in darkroom, filmic rgb, etc. So, the idea is to only move some settings like those I write: one setting for a specific module could be on the module. No more.

At the opposite, for example, we have only 2 settings actually for map view but I would not move them outside preferences as it's not a specific part (module) of darktable).

>     * hence have a module-specific tab in prefs where all module spefic thingies go into and can be grouped by module name

That could also be an idea to discuss. Good catch. We also need to be careful to not multiply tabs too much but 1 or 2 more is ok.

**Comment by johnny-bit** [comment] 2020-11-24 19:11
The problem with devising "a solution" is with discoverability of settings and place taken by them.

I took a look at current master preferences window and there's not so much settings IMO :)

And let's deal with individual problems and how to place them:
Personally I'm no fan of "expert mode", it usually implies bad options design. Let's say that in my opinion darktable has expert mode via external text editor & edit of darktablerc :)
Module specific settings are problematic, just look at mentioned wb or color balance settings: those are just single options. Having those settings directly in module, connected not with processing but with how module looks is imo wasting modue GUI (also wb & cb have "click header for fun time" easter egg way of changing that setting... but it's not easily discoverable). An option would be to further extend and complicate module ui code by allowing access to some menu... but then where? module headers have multi instance menu (not a place to deal with module ui option) and module preset menu (also not a place to put setting).

OK, so let me discuss settings per tab:
- general - IMO no changes needed
- import
  - whole import section is already in import options in import file/dir (except maybe rating). so if we could add rating to import dialog options this setting section is "repeat of what's available". I don't remember what controlls import metadata preset (metadata editor?) but it's a bit more work for documentation
  - whole session options is (can't check right now) repeat of tethering settings. so whole import tab out ;)
- lighttable
  - first 3 and 5th settings are native to collect images modue and if i'm not mistaken there's an ongoing pr to sort it out
  - couple other settings (for presets for utility modules etc) should probably be in totally different "interface" tab, but it still has to be inside preferences option
  - the "delimiters..." option is necessary, however it's a bit hard to understand how to use it at first, but that's just a job for docs/better tooltip ;)
- darkroom - would just need a bit of reorganization... and maybe some settings moved to generic "interface" tab?
- other views - is almost empty... could work as generic catch-all for interface ;)
- processing - is imo "perfect" but dunno
- security - is imo "perfect"
- cpu/gpu/memory - is a bit of hard tab ;) most settings there are autodetected.
- miscellaneous
  - interface section could be moved to generic "interface" tab
  - tags could be chucked to tags module, but i have no opinion
  - multi-instance shortcuts should stay - the shortcuts tab is for assinging shortcuts and not for shortcut options
  - other
    - 1st april game - that setting should also depend on availability of said game, as i added compile option that disables game completely ;)
    - pass storage backend could be moved to either security or storage.
    - playing audio files is enabled only in lighttable, but that setting is security dependent so... dunno ;)

Overall what that gives us? IMO - just moving settings around and not really much limiting the size of settings ;)

**Comment by elstoc** [comment] 2020-11-24 19:21
I know I suggested some of these things but I pretty much agree with @johnny-bit's summary. Probably a few little things that can be changed but most aren't particularly worth it and are just a case of moving things around amongst the tabs.

**Comment by elstoc** [comment] 2020-11-24 19:28
I would suggest a "modules" tab that has two sections: "utility modules" and "processing modules". This tab could take some of the load from both the darkroom and lighttable tabs (since the "utility module" settings really don't belong on the lighttable tab anyway)

**Comment by grubernd** [comment] 2020-11-24 19:30
I agree with the basic sentiment: Don't put too many details into the prefs.

I think that the preferences should only hold settings that are global or span multiple tools.

Anything specific to a certain tool belongs into the tool.

But: leave everything in the `darktablerc` so settings are still transferable and more important searchable by text. Having the presets as a database blob is already cumbersome enough.

@AlicVB .. why is txt overlay preference setting not needed anymore? Is it always displayed now?

@johnny-bit please let us move the "initial import rating" also to the import dialog away from settings. it is an evil metadata killer setting that needs to be out in the open where it happens.

**Comment by elstoc** [comment] 2020-11-24 19:37
> Anything specific to a certain tool belongs into the tool.

Again it's a question of discoverability (where to put it so that it's obvious) and space (don't increase the size of modules unnecessarily). So agree that where a module has lots of settings it makes sense to have a settings button. Otherwise prefs is the way to go. With processing modules, for example, most modules don't save settings from one image to the next, so it's a question of where to put a single option in a discoverable way so it's obvious that it's a persistent setting. I'm not sure I know a good answer.

**Comment by AlicVB** [comment] 2020-11-24 20:18
@grubernd : not needed anymore as overlays content are now configurable and sidecar_txt (don't remember the exact name) is among the available variables.

**Comment by Nilvus** [comment] 2020-11-24 20:18
> The problem with devising "a solution" is with discoverability of settings and place taken by them.
> 
> I took a look at current master preferences window and there's not so much settings IMO :)

That's not my idea, just a thing to discuss ;-) The only thing I'm sure is that we have to be careful in the future to not multiply settings. Too many settings could kill the idea of settings ;-)!

> Personally I'm no fan of "expert mode", it usually implies bad options design. Let's say that in my opinion darktable has expert mode via external text editor & edit of darktablerc :)

Good catch, we already have that expert mode with darktablerc file.

> Module specific settings are problematic, just look at mentioned wb or color balance settings: those are just single options. Having those settings directly in module, connected not with processing but with how module looks is imo wasting modue GUI (also wb & cb have "click header for fun time" easter egg way of changing that setting... but it's not easily discoverable). An option would be to further extend and complicate module ui code by allowing access to some menu... but then where? module headers have multi instance menu (not a place to deal with module ui option) and module preset menu (also not a place to put setting).

Good point here for those 2 ones.

>     * general - IMO no changes needed

I agree.

>     * import
>       
>       * whole import section is already in import options in import file/dir (except maybe rating). so if we could add rating to import dialog options this setting section is "repeat of what's available". I don't remember what controlls import metadata preset (metadata editor?) but it's a bit more work for documentation

I totally agree too. That could be kept only in dialog windows.

>       * whole session options is (can't check right now) repeat of tethering settings. so whole import tab out ;)

Hmm, I don't have access to tethering (no compatible camera) and so I have only session options in import tab, so needed to be kept in preferences but could be moved yes and merge with another tab (for example "other views" which have really few settings ; eventually by rename tab)

>     * lighttable
>       
>       * first 3 and 5th settings are native to collect images modue and if i'm not mistaken there's an ongoing pr to sort it out
>       * couple other settings (for presets for utility modules etc) should probably be in totally different "interface" tab, but it still has to be inside preferences option

Yes, there's a PR (for 3th one): #6797

>       * the "delimiters..." option is necessary, however it's a bit hard to understand how to use it at first, but that's just a job for docs/better tooltip ;)

At least yes, a better doc/tooltip is needed. But I think it could also be moved (but with the limit to better explicit it and I don't know how by now).

>     * darkroom - would just need a bit of reorganization... and maybe some settings moved to generic "interface" tab?

For this one, I disagree, all settings are good there (I don't talk here about the 2 module specific, my answer is above). This tab has been improved just few days ago by @TurboGit by splitting in 2 sections. That's already a good point but maybe we could improve it another way.

>     * cpu/gpu/memory - is a bit of hard tab ;) most settings there are autodetected.

So, do you mean to not kept this tab? I had previously posted an issue about updating settings (I closed it today): #5328

>     * miscellaneous
>       
>       * interface section could be moved to generic "interface" tab

Totally agree.

>       * tags could be chucked to tags module, but i have no opinion

Good idea.

>         * 1st april game - that setting should also depend on availability of said game, as i added compile option that disables game completely ;)

So could maybe be removed. But this bullshit game is some annoying than some old developers want to keep...

>         * pass storage backend could be moved to either security or storage.
>         * playing audio files is enabled only in lighttable, but that setting is security dependent so... dunno ;)

I think you point all things to be moved and yes, those settings could be moved to security tab. By also moving "interface" section in general tab, that would let place to move "other views" tab content and "session" section in "import" tab to that misc tab. That way, we just remove 2 tabs and make all tabs more consistent. Like that.

> Overall what that gives us? IMO - just moving settings around and not really much limiting the size of settings ;)

Yes, mostly but the first word I put here is to "improve" preferences content. We are on it. And we have already on no more used option that @AlicVB see and removed already. And with your comment, we also quite few settings to remove (import ones) at least as they are already elsewhere.

The question remaining after that is who is ok to do that? Unfortunately, I put the proposal but don't have coding skills to do that.

**Comment by johnny-bit** [comment] 2020-11-24 20:45
> I had previously posted an issue about updating settings (I closed it today): #5328

Why had you closed it though? those settings do need an update and thinking :)

> The question remaining after that is who is ok to do that?

Dunno, we'll see :)
Please sum up what needs to be done - it's usually very easy to code if you know exactly what needs to be done rather than scan whole issue thread on github ;)

**Comment by AlicVB** [comment] 2020-11-24 21:21
about delimiters docs, a small proposal here : #7055 together with the removing of the sidecar txt one

**Comment by TurboGit** [comment] 2020-11-24 22:31
I'm also leaning toward an expert mode and for me all prefs at the same place seems better.

**Comment by wpferguson** [comment] 2020-11-25 03:23
> Let's say that in my opinion darktable has expert mode via external text editor & edit of darktablerc :)
Amen

**Comment by jenshannoschwalm** [comment] 2020-11-25 06:16
Just a few ideas.

1. If we have module-specific preferences we must make sure that these are handled good for styles, presets and copy&paste of history. One example leading to confusion is the exposure module.

2. There are preferences because of 'we could not fully agree on how to implement' or 'are we really sure it works'. One example is the 'database' section. I think the default options are pretty good and will work fine in 99.9%. I would suggest to remove them all from the preference interface and leave it to 'expert mode' via text editor :-)

3. What is the reason to have 'high quality thumb processing from size' and 'delimiters for size categories' expose as preference at all? I think they should be removed as a preference and at relevant code sections should use the 'prefer performance over quality' setting.

4. Number of background threads? Also something that is not really necessary as a preference as the technical background is pretty clear.

**Comment by Nilvus** [comment] 2020-11-26 14:00
> > I had previously posted an issue about updating settings (I closed it today): #5328
> 
> Why had you closed it though? those settings do need an update and thinking :)

It's because this issue is no longer followed and you write here that settings are mostly autodetected. But ok, would be good to update them too (I think at least some things in that issue could already be updated from what had been discussed. They could be updated with that preferences update. I reopen the issue so!

> Please sum up what needs to be done - it's usually very easy to code if you know exactly what needs to be done rather than scan whole issue thread on github ;)

I will do that soon, just waiting a little to see new feedback and then will propose a sum of our discussion.

**Comment by Nilvus** [comment] 2020-11-26 14:08
> Just a few ideas.
> 
>     1. If we have module-specific preferences we must make sure that these are handled good for styles, presets and copy&paste of history. One example leading to confusion is the exposure module.

The discussion quickly go to forget that idea of module-specific preferences.

>     2. There are preferences because of 'we could not fully agree on how to implement' or 'are we really sure it works'. One example is the 'database' section. I think the default options are pretty good and will work fine in 99.9%. I would suggest to remove them all from the preference interface and leave it to 'expert mode' via text editor :-)

I totally agree. Expert mode is (and could stay) darktablerc file and options like that do not need to stay in preferences.

>     3. What is the reason to have 'high quality thumb processing from size' and 'delimiters for size categories' expose as preference at all? I think they should be removed as a preference and at relevant code sections should use the 'prefer performance over quality' setting.

Those 2 settings are quite different. 'high quality thumb processing from size' have quite some options and difficult to remove them. And it's worse for 'delimiters for size categories' as it's not related to thumb quality but to different sizes for setting possibily different overlays with star menu icons. So could not be integrated with 'prefer performance over quality'

>     4. Number of background threads? Also something that is not really necessary as a preference as the technical background is pretty clear.

Related indeed to my #5328 issue and so, if no more necessary, should be removed.

**Comment by johnny-bit** [comment] 2020-11-26 14:08
> this issue is no longer followed and you write here that settings are mostly autodetected

The point of the issue was to actually figure out better autovalues for autodetecting, and let me assure you I am thinking about it, just haven't had time for it and with feature freeze comming i just chucked it to "I'll work on this for 3.6 or somebody smarter will pick it up earlier ;)"

>waiting a little to see new feedback and then will propose a sum of our discussion. 

:heart:

**Comment by phweyland** [comment] 2020-12-11 20:21
My two cents.

If a preference is only related to a plugin I would like to see it in (close to)  that module. I've coded some of them in that spirit, unfortunately in different ways, but that's the way we (I) learn: metadata (preferences button), tagging (different buttons change the display), export selected (preferences button for exported metadata). I wanted to do the same for LUT 3D folder but I've failed to convince. Another one is expected by some people is about image information (to select the information the user is interested in).
The improvement I see is to have a consistent way to do so. And also to save space on the screen.

I suggest to add an optional entry at the bottom of the presets menu. Any candidate module could submit its preferences routine. 

The specific plugin preferences can then been removed from global preferences.

**Comment by Nilvus** [comment] 2020-12-20 15:30
Just a quick message here: I don't forget that, I'm just quite more busy this month than what I expected on start. Will come back on that ASAP. I hope before the end of the month. It would be good to see some changes for 3.4.1 and on top of first work related to that by @phweyland.

**Comment by Nilvus** [comment] 2021-01-02 17:38
Here, the summarize of all our discussions. Or maybe a try, I hope that I will not forget something.

To start, that @elstoc statement to have in mind and apply:

> Again it's a question of discoverability (where to put it so that it's obvious) and space (don't increase the size of modules unnecessarily). So agree that where a module has lots of settings it makes sense to have a settings button. Otherwise prefs is the way to go. With processing modules, for example, most modules don't save settings from one image to the next, so it's a question of where to put a single option in a discoverable way so it's obvious that it's a persistent setting. I'm not sure I know a good answer.

We are also mainly agree that we don't want an expert mode in preferences window and that the expert is and should remain darktablerc file.

Then @johnny-bit sum:

> The problem with devising "a solution" is with discoverability of settings and place taken by them.

That's in the way to @elstoc statement and I totally agree.

> Module specific settings are problematic, just look at mentioned wb or color balance settings: those are just single options. Having those settings directly in module, connected not with processing but with how module looks is imo wasting modue GUI (also wb & cb have "click header for fun time" easter egg way of changing that setting... but it's not easily discoverable). An option would be to further extend and complicate module ui code by allowing access to some menu... but then where? module headers have multi instance menu (not a place to deal with module ui option) and module preset menu (also not a place to put setting).

That's indeed in the same way as first @elstoc statement here. So, when we have only one or two options for a module, let's keep them in general preferences window. But I disagree to the last thing and @phweyland work show that it's a good place to set preferences option in preset menu (maybe we could consider is more a setting menu (presets are some sort of settings of a module as they saved how the module is configured).

But of course, all settings in a module should be accessed the same way. By now, with @phweyland work, we have made (or as a WIP), those modules:

- import
- collect,
- image infos
- metadata editor

Will remains, at least:

- export one: move preferences settings to preset menu as all others

>     * import

Thanks to @phweyland work, we now have this part changed and many import settings in preferences removed and moved completely in preset menu of import module (there's just a bug I pointed out in #7294 PR as I don't see the preferences menu). We could consider that **done**, the issue should probably be fixed soon.

>     * lighttable
>       
>       * first 3 and 5th settings are native to collect images modue and if i'm not mistaken there's an ongoing pr to sort it out
>       * couple other settings (for presets for utility modules etc) should probably be in totally different "interface" tab, but it still has to be inside preferences option

Collect preferences are also already moved in Collect module (preset menu too) and It's much better that way as we have quite some options to better quickly set/change that way. So **done**!

>       * the "delimiters..." option is necessary, however it's a bit hard to understand how to use it at first, but that's just a job for docs/better tooltip ;)

Finally, this is good to keep it in general preferences window. And thanks to @AlicVB, we now have a much better doc/tooltip to better understand how to use it. So, I think we could consider this **done** too!

>     * darkroom - would just need a bit of reorganization... and maybe some settings moved to generic "interface" tab?

This tab would probably need a specific discussion after all other parts. That tab is a little messy.

>     * other views - is almost empty... could work as generic catch-all for interface ;)

If we moved "other" part in miscellaneous tab (see below), then I would be to move other views settings in miscellaneous tab (we need to keep each tab without scrollbars.

>     * processing - is imo "perfect" but dunno
>     * cpu/gpu/memory - is a bit of hard tab ;) most settings there are autodetected.

Maybe those two tabs could be merged. I'm not sure about the correct name to use for the tab but those are all about some sort of performances in processing. Processing color and how to better use resources. But we could also keep those 2 tabs.

cpu/gpu/memory are maybe autodetected but that's not always good and that needs to be improved (but it's another issue I had opened some months ago).

>     * miscellaneous

I'm here to not really move anything here. Interface section could be moved in general tab yes but it's also good in that tab. So, it's the only thing to move for me (or not, I don't care here).

Tags part should stay here as it have only 2 settings and regarding first statement, too few settings to create a specific settings menu in tag module. And more, those 2 settings are not settings we will change often (if we change them!)
    
>         * 1st april game - that setting should also depend on availability of said game, as i added compile option that disables game completely ;)

I would even be to remove that setting and let it only in darktablerc. Many of us don't want that silly and unuseful game (I would like to see it completely removed from code) and by default it is now deactivated. So let's keep it deactivated and hide that setting.

>         * pass storage backend could be moved to either security or storage.
>         * playing audio files is enabled only in lighttable, but that setting is security dependent so... dunno ;)

I'm on to move them in security tab. That would need to made 2 sections in security tab so. A sort of "Confirm" one for all actual security settings and so "other" for those 2 ones.

**Comment by Nilvus** [comment] 2021-01-02 17:45
After that summarize, what's to do if we are all agree:

- Move preferences button in export module, in it's preset menu, like in metadata, import or collect module
- Remove april 1st game in miscellaneous  tab and only let that setting in darktablerc file (keep as deactivated by default)
- Move the 2 following settings (pass storage backend and playing audio files) in security tab
- So split security tab in 2 sections : "Confirm" (or other name if someone have a better idea) for actual settings in that tab and "other" one for 2 settings moved from misc tab
- Moved then settings in other views in miscellaneous tab (with section name "other views" so)
- I would merged processing and cpu/gpu/memory tabs together (but not sure to new name to use). Maybe just keep "processing" in tab name and then actual settings in processing could have something like "processing images" to make a difference

With all that, would remain probably a discussion if we reorganize a little bit darkroom tab or not. And if yes, how.

**Comment by Nilvus** [comment] 2021-02-17 16:48
Just as a reminder, what's done and what's remain to do (if someone wants to work on it):

- [ ] Move preferences button in export module, in it's preset menu, like in metadata, import or collect module
- [ ] Remove april 1st game in miscellaneous tab and only let that setting in darktablerc file (keep as deactivated by default)
- [ ] Move the 2 following settings (pass storage backend and playing audio files) in security tab
- [ ] So split security tab in 2 sections : "Confirm" (or other name if someone have a better idea) for actual settings in that tab and "other" one for 2 settings moved from misc tab
- [ ] Moved then settings in other views in miscellaneous tab (with section name "other views" so)
- [ ] I would merged processing and cpu/gpu/memory tabs together (but not sure to new name to use). Maybe just keep "processing" in tab name and then actual settings in processing could have something like "processing images" to make a difference

**Comment by AlicVB** [comment] 2021-03-21 19:09
issue #8529 raise a problem mentionned by @elstoc earlier in this long thread : currently "general" modules setting are split in 2 : utility modules in lighttable and processing modules in darkroom. The problem is that lot of utility modules are also in darkroom (and even some utility modules are actually inside darkroom section... To solve that, here is a proposal of a new reorganisation : 
We remove : 
- lighttable tab
- darkroom tab
- other views tab
- misc - interface section

and replace them with something like : 
```
interface :
- general :
    sort built-in presets first
    mouse wheel scrolls modules side panel by default
    always show panels' scrollbars
    method to use for getting the display profile
- thumbnails/previews
    thumb use raw file instead of embedded JPEG from size
    high quality thumb processing from size
    delimiters for size categories
    pattern for the thumbnail extended overlay text
    pattern for the thumbnail tooltip (empty to disable)
    
modules :
- Utility modules
    use single-click in the collect module
    expand a single utility module at a time
    scroll to utility modules when expanded/collapsed
    rating an image one star twice will not zero out the rating
    pattern for the image information line
    position of the image information line
    pretty print the image location
    hide built-in presets for utility modules
- Processing modules
    expand a single processing module at a time
    only collapse modules in current group
    expand the module when it is activated, and collapse it when disabled
    scroll to processing modules when expanded/collapsed
    show right-side buttons in processing module headers
    show mask indicator in module headers
    hide built-in presets for processing modules
    display of individual color channels => maybe to be explained a little better ??
    white balance slider colors => inside module parameters ??
    colorbalance slider block layout => inside module parameters ??

views :
- lighttable
    show scrollbars for central view
- darkroom
    pen pressure control for brush masks
    smoothing of brush strokes
    border around image in darkroom mode
    show scrollbars for central view
    demosaicing for zoomed out darkroom mode
    reduce resolution of preview image
    show loading screen between images
- slideshow
    waiting time between each picture in slideshow
```
That won't change the number of tabs and each tab content is less that current "darkroom" tab (the bigger one)...
What do you think ?
@Nilvus : I would esp. get your opinion on this as it interfere quite a bit with the list of task above...

**Comment by elstoc** [comment] 2021-03-21 19:34
I don't object to the idea of another reorganisation, but remember it's not long since we did the last one so it would be good not to do this too regularly (it would be nice for users to be able to get used to where things are). There will always be some issues of things that don't quite fit - for example the image information line stuff doesn't really (from a user point of view) sit with "utility modules" - but we can discuss the specifics.

In terms of future-proofing, I'd prefer to have more tabs than bigger ones, because then we won't need to worry about them getting crowded for a while. There's plenty of vertical space for additional tabs, and plenty of horizontal space for longer descriptions of those tabs.

Where an individual module has multiple preferences associated with it, I agree that it makes complete sense to move those preferences to the module itself. For those single options in the processing modules section it makes less sense to me. In general processing modules don't have any settings that persist between images so I'd rather keep those where they are.

**Comment by AlicVB** [comment] 2021-03-21 20:31
> I don't object to the idea of another reorganisation, but remember it's not long since we did the last one so it would be good not to do this too regularly (it would be nice for users to be able to get used to where things are).

agree, but imho currently pref organisation is quite messy, esp. in the interface area... So that's an attempt to solve that (but I agree that multiples changes are not the best)



> for example the image information line stuff doesn't really (from a user point of view) sit with "utility modules"

not sure this specific example is representative as image info line is absolutely not a pressing module (even from a newcomer point of vue, I think). One of the most difficult module is modulegroups (but hopefully it doesn't have any pref)



> In terms of future-proofing, I'd prefer to have more tabs than bigger ones, because then we won't need to worry about them getting crowded for a while. There's plenty of vertical space for additional tabs, and plenty of horizontal space for longer descriptions of those tabs.

agree (again) : that's why all tab content are smaller than before. The "biggest" tab with my proposal would be the "module" one (and maybe the most likely to grow). Maybe we can split that in 2 tabs : "modules interfaces" and "modules options" (I prefer to keep "utility" and "processing" modules side by side in the same tab to reduce the user confusions) "tag" section from misc tab could go to there then...


> Where an individual module has multiple preferences associated with it, I agree that it makes complete sense to move those preferences to the module itself. For those single options in the processing modules section it makes less sense to me. In general processing modules don't have any settings that persist between images so I'd rather keep those where they are.

+1 in fact, there was '???' in my proposal, but for some reason, they didn't paste... (I've readded them)

I'll try to come with a more complete proposal, that include what we just discuss and @Nilvus previous ideas, so we can have a more complete view of all that...

**Comment by elstoc** [comment] 2021-03-21 20:36
> not sure this specific example is representative as image info line is absolutely not a pressing (processing?) module

My point was more that it's not obviously a "module" (which tend to be associated with things on the side panels that can be expanded/collapsed). IMO stuff like that sits better with the view settings.

**Comment by AlicVB** [comment] 2021-03-21 21:37
second attempt with the full pref dialog (sorry for spamming the thread) : 
```
interface (16.5)
- general :
    interface language
    sort built-in presets first
    mouse wheel scrolls modules side panel by default
    always show panels' scrollbars
    method to use for getting the display profile
- thumbnails/previews
    prefer performance over quality
    thumb use raw file instead of embedded JPEG from size
    high quality thumb processing from size
    delimiters for size categories
    pattern for the thumbnail extended overlay text
    pattern for the thumbnail tooltip (empty to disable)

Theme (4+fill)
    theme
    use system font size
    font size in points
    GUI controls and text DPI
    modify selected theme with CSS tweaks below

modules interface (18.5)
- Utility modules
    expand a single utility module at a time
    scroll to utility modules when expanded/collapsed
    hide built-in presets for utility modules
- Processing modules
    expand a single processing module at a time
    only collapse modules in current group
    expand the module when it is activated, and collapse it when disabled
    scroll to processing modules when expanded/collapsed
    show right-side buttons in processing module headers
    show mask indicator in module headers
    hide built-in presets for processing modules
- Keyboard shortcuts with multiple instances
    prefer expanded instances
    prefer enabled instances
    prefer unmasked instances
    selection order

modules options (19)
- Utility modules
    use single-click in the collect module
    rating an image one star twice will not zero out the rating
    pattern for the image information line => integrated into the module at some point
    position of the image information line => integrated into the module at some point
    pretty print the image location
    omit hierarchy in simple tag lists
    disable the tags entry completion
- Processing modules
    display of individual color channels => maybe a better name ???
    white balance slider colors
    colorbalance slider block layout
- Import session options (still needed ???)
    base directory naming pattern
    sub directory naming pattern
    keep original filename
    file naming pattern    
    
views (13.5)
- lighttable
    show scrollbars for central view
- darkroom
    pen pressure control for brush masks
    smoothing of brush strokes
    border around image in darkroom mode
    show scrollbars for central view
    demosaicing for zoomed out darkroom mode
    reduce resolution of preview image
    show loading screen between images
- slideshow
    waiting time between each picture in slideshow

processing :
  (unchanged)

cpu/gpu/memory :
  (unchanged)

security (15)
- confirmations
    ask before removing images from database
    ask before erasing images from disk
    ask before discarding history stack
    send files to trash when erasing images
    ask before moving images from film roll folder
    ask before copying images to new film roll folder
    ask before removing empty folders
    ask before deleting a tag
    ask before deleting a style
    ask before deleting a preset
- other
    password storage backend to use
    executable for playing audio files

storage :
  (unchanged)

shortcuts :
  (unchanged)
  
presets :
  (unchanged)

lua options :
  (unchanged)
```
- numbers after the tab name correspond to it's size in "normal elements" units. Previous biggest tab was darkroom with a size of 22.5.
- I'm not satisfied of the position of "executable for playing audio files", but I've no idea where to put it, so I let it with password storage like before...

@phweyland : to be sure, the import options here at still needed, and can't be moved to the import module itself, right ? (I fail to remember the recent discussions about this point)
@Nilvus : I've not merged "processing" and "gpu/cpu/memory" as I think they are not related to the same things (one for general perfs and one for default darkroom pipe options)
@elstoc : about the info line, I wonder if we shouldn't move the prefs into the module, eventually even inside presets so we can quickly switch between patterns (possibly depending of the image type)

**Comment by elstoc** [comment] 2021-03-21 21:50
> about the info line, I wonder if we shouldn't move the prefs into the module, eventually even inside presets so we can quickly switch between patterns (possibly depending of the image type)

I don't know. I know it's called "image information" but the thumbnail overlay and tooltip patterns are basically the same thing (the export file naming also uses the same variables), and the info line position preference definitely belongs with the darkroom view settings. I'm not sure what the best solution is here - I don't know if it's even possible to come up with something consistent so I'm just throwing out objections to see if it prompts new ideas.

**Comment by Nilvus** [comment] 2021-03-21 22:17
@AlicVB: I agree with @elstoc. I think we need to be simple here and preferences are globally good. Just some little things to move. No problem on proposing something else but for me General tab is the tab that is great as it is and shouldn't be change.

**Comment by AlicVB** [comment] 2021-03-22 18:20
@Nilvus : you save me hours of work :)
The only question that remain : what to do with issues like #8529 ? we can put "hide built-presets" prefs for utility and processing modules side by side in misc interface, but if we want to be consistent, we also have to do that for most of the others...
I wonder if we should not keep the actual status-quo, even if not perfect...

**Comment by Nilvus** [comment] 2021-03-23 21:57
> I wonder if we should not keep the actual status-quo, even if not perfect...

I think so, except that I think (we were agree on that here) that the todo I sum on this issue remains to be done:




> Just as a reminder, what's done and what's remain to do (if someone wants to work on it):
> 
>     * [x]  Move preferences button in export module, in it's preset menu, like in metadata, import or collect module. Thanks to @phweyland
> 
>     * [ ]  Remove april 1st game in miscellaneous tab and only let that setting in darktablerc file (keep as deactivated by default)
> 
>     * [ ]  Move the 2 following settings (pass storage backend and playing audio files) in security tab
> 
>     * [ ]  So split security tab in 2 sections : "Confirm" (or other name if someone have a better idea) for actual settings in that tab and "other" one for 2 settings moved from misc tab
> 
>     * [ ]  Moved then settings in other views in miscellaneous tab (with section name "other views" so)
> 
>     * [ ]  I would merged processing and cpu/gpu/memory tabs together (but not sure to new name to use). Maybe just keep "processing" in tab name and then actual settings in processing could have something like "processing images" to make a difference

**Comment by Nilvus** [comment] 2021-06-20 13:14
It would be good if this can be finish for 3.8, without or without a search feature, depending on where we end this.

**Comment by Nilvus** [comment] 2021-06-20 13:15
> Just as a reminder, what's done and what's remain to do (if someone wants to work on it):
 
* [x]  Move preferences button in export module, in it's preset menu, like in metadata, import or collect module. Thanks to @phweyland
* [ ]  Remove april 1st game in miscellaneous tab and only let that setting in darktablerc file (keep as deactivated by default)
* [ ]  Move the 2 following settings (pass storage backend and playing audio files) in security tab
* [ ]  So split security tab in 2 sections : "Confirm" (or other name if someone have a better idea) for actual settings in that tab and "other" one for 2 settings moved from misc tab
* [ ]  Moved then settings in other views in miscellaneous tab (with section name "other views" so)
* [ ]  I would merged processing and cpu/gpu/memory tabs together (but not sure to new name to use). Maybe just keep "processing" in tab name and then actual settings in processing could have something like "processing images" to make a difference

**Comment by johnny-bit** [comment] 2021-07-17 13:43
Hey, see if #9550 covers the issue in whole :)

**Closed** 2021-07-19 18:10 UTC
Labels: bug: wip, feature: redesign, scope: UI
