### ISSUE TITLE
Unable to import Raw images into darktable

### ISSUE THREAD

**Issue by KarthickSK** [darktable-org/darktable#13195] opened 2022-12-24 12:04 UTC
Whenever i import any Raw file(.DNG) it says the 'Filename.DNG' is not available
I tried with all import options and nothing works
The images were taken using iPhone 14 pro max

Please refer screenshot
<img width="905" alt="Screen Shot 2022-12-24 at 17 26 49 PM" src="https://user-images.githubusercontent.com/33551628/209435248-4d83e1ed-a621-4108-be08-c111858717ca.png">
<img width="727" alt="Screenshot 2022-12-24 at 5 33 12 PM" src="https://user-images.githubusercontent.com/33551628/209435260-6cab4f13-21e4-4014-a01a-a636c2e36331.png">

**Comment by kmilos** [comment] 2022-12-24 12:19
iPhone DNGs are not supported yet (i.e. the "recent" ones since gen 12).

Please search before opening new issues.

@Nilvus Please close as duplicate of https://github.com/darktable-org/darktable/issues/7578

**Comment by KarthickSK** [comment] 2022-12-24 12:25
Hey @kmilos thanks for your reply
Will it be supported anytime soon?

**Comment by Nilvus** [comment] 2022-12-24 12:56
@KarthickSK: it will be supported when someone provide RAW on pixls.us (maybe it's done, I didn't check) and a developer will spent time to work on it, and then his work will be added on Rawspeed (used by darktable to recognize RAW) by his maintainer. This could be quick or not.

**Comment by Nilvus** [comment] 2022-12-24 12:57
Oh, see: https://www.darktable.org/resources/camera-support/ and https://raw.pixls.us/

**Closed by Nilvus** 2022-12-24 12:56 UTC

**Comment by kmilos** [comment] 2022-12-24 13:06
If you like experimenting, you can also try building w/ the linked rawspeed PR.
