### ISSUE TITLE
macOS Ventura drop down menus don’t respond to the mouse clicks 

### ISSUE THREAD

**Issue by JackP-Z** [darktable-org/darktable#13151] opened 2022-12-14 22:35 UTC
On the macOS Ventura 13.1 some drop down menus don’t respond to the mouse clicks including the zoom menu (the mouse wheel works), contrast equalizer, framing (the sliders work fine) and probably few other menus.

**Comment by gi-man** [comment] 2022-12-15 01:06
This sound like a duplicate of https://github.com/darktable-org/darktable/issues/12727

**Closed** 2022-12-15 07:08 UTC

**Comment by JackP-Z** [comment] 2022-12-23 00:11
The problem persists using dt 4.2.0 on macOS Ventura.

**Comment by MStraeten** [comment] 2022-12-23 14:12
that’s because it’s not fixed upstream yet …

**Comment by JackP-Z** [comment] 2022-12-23 14:26
Thanks for the info. I’m unfamiliar with the dt development process and was expected it working in the 2022 Xmas release.
Merry Xmas & Happy New Year to all dt developers and contributors of a superb tool.


On Dec 23, 2022, at 9:12 AM, Martin Straeten ***@***.***> wrote:


that’s because it’s not fixed upstream yet …
