### ISSUE TITLE
Impossible to create HDR image with 3 picts seems in different orientations

### ISSUE THREAD

**Issue by Pat-sz** [darktable-org/darktable#14028] opened 2023-03-26 14:59 UTC
**Describe the bug/issue**
My camera, a Canon EOS 550D (old: buy 15 years ago), has a bug. For 3 pictures take with bracketing mode, the third is considering in another orientation. Darktable refused to generate the DNG HDR and told me that all picts need to be with the same size and the same orientation, else if I change the orientation of the third pict to have the same as the others.

**To Reproduce**
1. Go to 'selected images'
2. Click on 'Create HDR'
3. See an error message in the middle of light table (by the hell, the message is not very visible in a gray box behind the photos).

I don't know if you can change the RAW information in the file to create the bug. If necessary, I can give you my original photos.

**Expected behavior**
Create a DNG file when the file has, in fact, the same size and the same orientation.

**Screenshots**
![2023-03-26 16_30_32-darktable](https://user-images.githubusercontent.com/84800325/227782967-91abc129-0215-486f-8ad2-7cb4096b0248.png)

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**

* darktable version : 4.3.0+63~gc207f2ef3
* OS                : Windows family 11 (but dev mode active and run a linux version of darktable)
* Memory            : 16 Go
* Graphics card     : AMD Radeon RX 6500M
* Graphics driver   : AMD default
* OpenCL installed  : yes
* OpenCL activated  : yes
* Xorg              : unknow
* Desktop           : unknow
* GTK+              : unknow
* gcc               : unknow
* cflags            : unknow
* CMAKE_BUILD_TYPE  : unknow

**Additional context**
I reproduce the error with my other installed version 4.2.0 of Darktable. This version is a Windows version, but it seems to me less stable. 
I reproduce the error on my Linux mint 21.1 Cinnamon version of Darktable 4.2.0 without OpenCL because desactivated Graphic card due to incompatible driver.

**Comment by jenshannoschwalm** [comment] 2023-03-27 07:13
> I don't know if you can change the RAW information in the file to create the bug.

Please note that darktable will **never** modify any photo file (raw or other)! So what you described will not be fixed in dt.

You could use a tool that modifies raw files like `èxiftool` (and should do so in your szenario)

**Comment by victoryforce** [comment] 2023-03-28 13:24
@Pat-sz Would it be possible for you to provide access to the images you demonstrated the problem with?

**Comment by victoryforce** [comment] 2023-03-28 16:02
This is very strange. I can't reproduce your problem.

On my system (Windows 10), darktable creates HDR from these files without any problems. Tested not only on the current development version, but also on the 4.2.0 version installed on my system.

I see your screenshot and understand that this situation somehow happened when trying to create HDR in your darktable, but I don't understand how it could be. Can you really reproduce this problem with exactly those copies of the images that are uploaded to dropbox? Are these really the original files from the camera? Perhaps in the process of experimenting with images, you inadvertently corrected them with some program?

The CameraOrientation field that you wrote about in the second comment belongs to the Canon MakerNotes data. darktable does not read the orientation from this field, only from the standard Exif field, which has the same value in all three files I downloaded.

**Comment by wpferguson** [comment] 2023-03-28 16:22
Tried on Ubuntu 22.04 with current master and could not reproduce.

**Comment by Pat-sz** [comment] 2023-03-28 16:22
Ok, I'm on linux, and with the uploaded images, DT creates the HDR. I think the Exif change is correct, but the database was not refreshed on Windows. I'll just test on DT linux, it's OK with my "original" photos where I changed the exif on the problematic photo. What surprises me is the fact that I restarted DT before to check if the exif change was effective and solved the problem (or maybe not). I'm rebooting on Windows to check.

**Comment by Pat-sz** [comment] 2023-03-28 16:37
OK, I'm on Windows. I confirm, now it's just a database refresh issue. I just refreshed the Exif data, and now the HDR is OK.
Sorry for the last exchanges, Exif edits fix my camera bug.

**Comment by Pat-sz** [comment] 2023-03-28 16:39
Thanks, I close the issue

**Comment by victoryforce** [comment] 2023-03-28 19:34
@Pat-sz So my guess was correct that the files I was testing on were already fixed. But I think your original problem could also be fixed without having to edit the Exif. As far as I understand, in such cases when the camera is pointing up, it can randomly choose the orientation of either 0 degrees or 180 degrees. This possibility must be taken into account and we should not prohibit the creation of HDR in this situation.

Therefore, I want to ask you to share the original files on which this problem will be reproduced and I will try to improve the behavior of darktable in such cases.

**Comment by Pat-sz** [comment] 2023-03-29 08:39
Indeed, @victoryforce, before my camera started to bug, I had, several times, this same problem when my camera was tilted around 45° from the horizon plane, the sensor did not give the same orientation for all photos in the same series. The movement vibration of the mirror and the focal plane shutter can change the position of the sensor and creates a different orientation for two same photos. I think this is a problem that is not specific to me.
I deleted the photos and replaced with the original photos taken from my SD card.

Here is the previous link to my dropbox: https://www.dropbox.com/sh/w24zsndvd7pani7/AADXRN1PcDG3poCn9kge7cyda?dl=0

**Closed** 2024-03-24 00:18 UTC
Labels: no-issue-activity
