### ISSUE TITLE
request: permit more zooming of the map 

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#6196] opened 2020-09-04 11:01 UTC
Having a maximum zoom of 1:1 with openstreetmap's level 19 is not enough in various cases:

- if you want to position more precisely the markers
- if you have a cluster of markers which hide the map below them

I'm thinking that a 4x more zoom should be allowed in order to work better with the markers

**Comment by Nilvus** [comment] 2020-09-04 15:44
Think about searching issues (open and closed ones before). This has already been posted. Duplicate of #5172

**Comment by paolobenve** [comment] 2020-09-04 17:33
it's not the same issue. #5172 is about the map not scaled properly on certain hardware. This issue is about giving the user the possibility to zoom the map more that he/she can zoom it now

**Comment by Nilvus** [comment] 2020-09-04 20:41
It's the same as it is not a darktable issue. Read again issue I linked...

**Comment by johnny-bit** [comment] 2020-09-05 09:38
Please file issue with https://github.com/nzjrs/osm-gps-map as darktable is only a consumer of interface provided by osm-gps-map and any mapping issue such as this should be raised with them. (also ping them about tagging a new release ;) )

**Closed** 2020-09-05 09:52 UTC

**Comment by quovadit** [comment] 2020-11-05 21:07
I created an issue at osm-gps-map as requested (https://github.com/nzjrs/osm-gps-map/issues/72)
But as there is no reaction after 9 days, and the last issue was closed 2017 (!) I do not really expect it to be solved...

Is there a chance, that a darktable developer fixes this for osm-gps-map?
After all it is a function relevant for darktable

**Comment by johnny-bit** [comment] 2020-11-05 21:52
That project needs maintainer. Badly... And most recent action was merging of a pr in 2019 :)
