### ISSUE TITLE
Subsecond variable for naming pictures

### ISSUE THREAD

**Issue by fguiotte** [darktable-org/darktable#3163] opened 2019-10-15 12:48 UTC
**Is your feature request related to a problem? Please describe.**
I would like to name my pictures with a naming convention independent of the cameras or darktable. In this case, android's way with the timestamp of the photo as a name is perfect.

Exif time variables in darktable are good but are currently limited to the second. This is a problem to create unique filenames now that most cameras can take several photos per second.

**Describe the solution you'd like**
The solution here would be to create a new variable `$(EXIF_SUBSEC)` to match the corresponding Exif field.

**Additional context**

```shell
> exiv2 -g SubSecTime IMG_0574.CR2
Exif.Photo.SubSecTime                        Ascii       3  01
Exif.Photo.SubSecTimeOriginal                Ascii       3  01
Exif.Photo.SubSecTimeDigitized               Ascii       3  01
```

**Comment by johnny-bit** [comment] 2021-08-08 15:53
I Just got bitten by it with 3 IMGs (turns out 7FPS actually manages to do images in subsecond. who would've thought)

The problem is that we would have to at the same time introduce similar subsec variable to time using `gettimeofday()` function. and enhance the data by additional precision throughout the darktable... this makes problem not really that hard in terms of code, but hard in terms of amount of changes necessary...

**Comment by ralfbrown** [comment] 2023-02-09 05:17
Can we close this?  We've had $(EXIF.MSEC) and $(MSEC) for nearly a year now.

**Closed** 2023-02-09 07:19 UTC
Labels: feature: enhancement, difficulty: hard, scope: DAM, no-issue-activity
