### ISSUE TITLE
in crop/rotate switching between "darktable" to "lighttable" back to "darktable" breaks, then goes core upon quit :(

### ISSUE THREAD

**Issue by UsefGeorge** [darktable-org/darktable#8650] opened 2021-04-10 23:28 UTC
bugs in crop & rotate
1) erase * in .config/darktable
2) erase the sidecar for the test picture
3) run darktable
4) import that singular picture ( ,JPG, it displays correctly )
5) rotate picture -138 ( or so degrees )
6) automatic cropping NO ( square picture rotates )
7) save settings ( quit program )

8) restart darktable
9) crop a rectangle inside the 138 degree rotated picture by moving the crop lines inside the picture (not the sliders )
10) switch to "lighttable" view
11) switch back to "darktable" view

The crop lines are gone
the margin sliders dont crop anymore, but something appears to be happening in the background

This happens in 3.4.1, as well as the Latest ( 3.6 ?,   april 10, 2021 )

quiting now gets u the usual core dump
(gdb) bt
#0  0x00007ffff2fea305 in __memmove_avx_unaligned_erms () at /lib64/libc.so.6
#1  0x00007ffff7d9032c in _default_process_tiling_roi._omp_fn.1 () at /home/darktable/DARKTABLE/darktable.master/darktable/src/develop/tiling.c:1144
#2  0x00007ffff799adce in gomp_thread_start () at /lib64/libgomp.so.1
#3  0x00007ffff7b10432 in start_thread () at /lib64/libpthread.so.0
#4  0x00007ffff2f866d3 in clone () at /lib64/libc.so.6
(gdb) 

Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported 
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc Where do u find this info?

Fedora 32
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory      16gig      : 
* Graphics card     : some geforce nvidia
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**

**Comment by johnny-bit** [comment] 2021-06-13 20:13
Is the issue still present in current master for you? recently a fix got merged in - https://github.com/darktable-org/darktable/pull/9153 which prevents crop and rotate from crashing. Could you check if the issue is fixed for you?

**Closed** 2023-03-25 00:19 UTC
Labels: no-issue-activity
