### ISSUE TITLE
Wrong propotions in collection dialogue on Windows

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#11428] opened 2022-03-29 16:04 UTC
**Introduction**
I previously reported about the different arrow sizes in the collections dialogue shown in the screenshot below. The arrow in front of the dropbox is now bigger but the input field is even smaller than before. I would suggest to change the proportions and move the arrow to the left so the relevant date in the input box would show.
---------------------------------------------------------------

**Screenshots**
https://user-images.githubusercontent.com/78697169/160655234-5391caac-8ed2-4a38-8728-e00b54fcbc3e.png

![inmatning_folder](https://user-images.githubusercontent.com/78697169/160655568-2d452127-add3-48cf-a50f-d20800b86a14.png)

**Platform**

darktable version : 3.9.0+798~g8152dd9d6

OS : Win10 19042.1288

Memory : 32 GB

Graphics card : Gigabyte GeForce RTX 2070 SUPER OC 3X

Graphics driver : 30.0.14.9613

OpenCL installed : yes

OpenCL activated : yes

**Comment by Nilvus** [comment] 2022-03-29 19:54
Already known one and huge work in progress related to collections and filter. It's not Windows issue as it appears on all systems. Duplicate of #11183 so I close this issue.

**Closed by Nilvus** 2022-03-29 19:54 UTC
Labels: duplicate
