### ISSUE TITLE
Gruped mode with filter "all except rejected" shows both images

### ISSUE THREAD

**Issue by elman22** [darktable-org/darktable#1955] opened 2018-12-31 22:59 UTC
I have RAW+JPG of the same image, both not rejected with rating 1 star. Working with lighttable.
1. No filters or grouping, both images are visible in lighttable - expected result
2. Click "grouped images" icon - only RAW is visible - expected result
3. Select view "all except rejected" - both images are visible - unexpected result. I would assume that only RAW should be visible.
4. Select view ">=1" - only RAW is visible - expected result

**Comment by LiranV** [comment] 2019-01-12 21:11
I can confirm the same behavior.
Also happens with "unstarred only".

**Comment by LiranV** [comment] 2019-02-03 20:46
Opened a merge request with a fix #2052

**Comment by Nilvus** [comment] 2019-06-19 14:10
@TurboGit : this one seems to be forgotten to be closed. PR #2052 merged seems to have fixed that.

**Comment by elman22** [comment] 2019-06-19 19:57
I have 2.6.2, but this issue is not fixed. So #2052 fixes another issue.

**Comment by LiranV** [comment] 2019-06-19 20:23
@elman22 It does fix the issue, but it was not really merged into 2.6.2 (@TurboGit).

**Comment by Nilvus** [comment] 2019-06-19 21:07
@elman22 : to complete LiranV, it will be merged in next release. And with all things merged on master, that will probably be for 2.8 released at the end of the year.

**Comment by Nilvus** [comment] 2019-06-19 21:18
@elman22 : this PR was merged with milestone 2.6.2 indeed but I verify, it was not merged on 2.6.2 but it's merged on master one, so it's fixed but will be on next release, probably 2.8 one. @TurboGit : what do you think of that milestone but not integrated on 2.6.2 ?

**Closed** 2020-01-13 18:23 UTC
Labels: bug: fixed
