### ISSUE TITLE
Masks done before crop show up outside image after crop

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3010] opened 2019-09-26 06:04 UTC
**Describe the bug**
Used brush masks in retouch module.
Then cropped the image,
Revisited retouch to for more brush masking.
Some of the brush masks were outside the crop as seen in the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/1119439/65662065-f1307100-e050-11e9-994d-3b0bd9cbbf12.png)

**Platform (please complete the following information):**
 - OS: Win10
 - Version darktable-2.7.0+1862~g879f1e5f9-win64

**Comment by TurboGit** [comment] 2019-09-26 09:57
Cannot reproduce.

**Comment by jenshannoschwalm** [comment] 2019-09-26 20:32
Could you send the xmp file for that image please?

**Comment by chhil** [comment] 2019-09-27 02:44
@jenshannoschwalm XMP zip attached.
[P1137439.RW2.zip](https://github.com/darktable-org/darktable/files/3660679/P1137439.RW2.zip)

**Comment by jenshannoschwalm** [comment] 2019-09-27 05:39
Thanks for sharing.

Did you ever remove that image from darktables collection and reimport it before you tried to compress the history?

1. If so - the problem is pretty obvious. if you look at the iop_orders of used modules you will see same values "39" for various different modules. So when compressing modules will be removed in a way not easy to predict. Also you might see strange visual things because the order in the processing pipeline is not correct.

1. If not -  any way to share the data from main.history for that image?

I think that's another example for the new iop_order problems. 

#3016 is intended to fix this (you have to remove that file from the database and must **also** remove the xmp file)

**Comment by chhil** [comment] 2019-09-27 05:55
> Did you ever remove that image from darktables collection and reimport it before you tried to compress the history?

I honestly dont recall. I have had so many issues that I have been seeing and one of them is related to removing images from a collection  that were imported twice and I dont know if I did that on this folder.

> main.history

Not sure what you mean.
But I have attached the config folder and maybe you are looking for 
`select * from history where imgid = 1369`

I got the image id from the image info  from 
![image](https://user-images.githubusercontent.com/1119439/65745444-564f9980-e119-11e9-8268-0fd2f7aca5aa.png)


[darktable_config.zip](https://github.com/darktable-org/darktable/files/3661048/darktable_config.zip)


I will try #3106 but that would mean re editing it, if I understand what is being requested.

**Comment by jenshannoschwalm** [comment] 2019-09-29 06:58
Could you try again with current master after removing file from database and removing xmp file?

**Comment by chhil** [comment] 2019-09-29 07:02
Couldn't reproduce on a clean darktable-2.7.0+1898~ge37281ae4-win64.

**Comment by jenshannoschwalm** [comment] 2019-09-29 11:23
maybe you can close this issue for now.

**Closed** 2019-09-29 11:44 UTC
