### ISSUE TITLE
ARW "Lossless Compressed" (Sony ILCE-7M4) not loaded into darkroom

### ISSUE THREAD

**Issue by kymbalon** [darktable-org/darktable#14659] opened 2023-06-06 20:15 UTC
### Describe the bug

When double-clicking a preview of an ARW file in the new format variant "Lossless Compressed RAW" (as saved by a Sony alpha 7 IV camera alias ILCE-7M4) in the lighttable view, it is not opened in the darkroom view. Instead, an error message is displayed reading

> failed to read camera white balance information from 'DSC00001.ARW'!
> darktable could not load 'DSC00001.ARW', switching to lighttable now.

"Normal" uncompressed ARW files from the same camera are opened without problem.

### Steps to reproduce

1. Choose "Lossless Comp[ressed] Large Size" as RAW format on the camera (Sony ILCE-7M4);
2. Load image files in the given format into darktable;
3. Double-click an ARW format file in the lighttable view.

### Expected behavior

darktable should support Sony Compressed RAW files.

### Where did you install darktable from?

darktable.org

### darktable version

4.2.1

### What OS are you using?

Mac

### What is the version of your OS?

macOS 10.15.7

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

$ /Applications/darktable.app/Contents/MacOS/darktable  --version
this is darktable 4.2.1
copyright (c) 2009-2023 johannes hanika
https://github.com/darktable-org/darktable/issues/new/choose

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.0.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support enabled
  libheif support enabled
  libjxl support enabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled

**Comment by kmilos** [comment] 2023-06-06 20:19
This is a known issue, and also listed as such in the release notes.

Please search before opening new issues.

Duplicate of https://github.com/darktable-org/darktable/issues/12064, https://github.com/darktable-org/darktable/issues/10556

**Closed** 2023-06-06 22:11 UTC
Labels: duplicate

**Comment by kymbalon** [comment] 2023-06-07 13:56
Sorry, I searched for "ARW" which seemed to be the most significant keyword for me.

**Comment by kmilos** [comment] 2023-06-07 14:04
> Sorry, I searched for "ARW" which seemed to be the most significant keyword for me.

Fair enough, so I'm adding these to release notes as well: https://github.com/darktable-org/darktable/pull/14664
