### ISSUE TITLE
intel neo opencl crash on Manjaro (dt 3.2.1)

### ISSUE THREAD

**Issue by blitzgneisserin** [darktable-org/darktable#6180] opened 2020-09-02 12:25 UTC
Intel Neo Opencl (intel-compute-runtime) crashes (?) when running darktable-cltest. Anyway it does not appear to be functional.
I am on a Manjaro system that I installed today. Intel i7 quad core, dual graphics with Nvidia+Intel, 16 GB RAM, HP pavilion laptop, Intel GPU is Intel Iris Plus Graphics G7.
backtrace:
[darktable_bt_N2S2P0.txt](https://github.com/darktable-org/darktable/files/5162201/darktable_bt_N2S2P0.txt)
Hope this is useful.

**Comment by parafin** [comment] 2020-09-02 12:32
Just remove it. This is not a darktable bug. This is a duplicate of many other reports already existing here.

**Closed by parafin** 2020-09-02 12:32 UTC
