### ISSUE TITLE
Star rating issue on import and double clicking 1 star to reset to 0 star

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6904] opened 2020-11-14 11:16 UTC
3.3.0+1591~g0aeaa230b

2 issues with ratings

1. Import rating not at 1 star but no stars though preference is set to import with 1 star rating.
![image](https://user-images.githubusercontent.com/1119439/99145876-6ff2ce00-2698-11eb-95cc-47a88715b6da.png)

2. Double clicking a 1 star does not change the rating to 0 although preference. Luckily the shortcut of pressing a number works.
![image](https://user-images.githubusercontent.com/1119439/99145889-88fb7f00-2698-11eb-9d0f-16c7a3d7205c.png)

**Comment by chhil** [comment] 2020-11-14 11:19
If you rate 2 stars then double clicking of first star resets to 0 stars correctly, but cannot reset to 0 when only 1 star is given.

**Comment by chhil** [comment] 2020-12-13 01:04
Current master. 3.3.0+2084~ga89402a4f
WSL Ubuntu.

Preferences -> initial import rating 1 star.
![image](https://user-images.githubusercontent.com/1119439/102000390-f4268880-3d0c-11eb-92df-d9509c606388.png)

Imported new folder of raw + jpeg (Fuji raf+jpeg)
Raw files got a 1 star and jpeg got no stars.

![image](https://user-images.githubusercontent.com/1119439/102000412-1a4c2880-3d0d-11eb-8816-e9889e75ba29.png)

**Comment by chhil** [comment] 2020-12-22 10:01
Bump

**Comment by sjjh** [comment] 2020-12-30 08:03
I can confirm with darktable 3.4 (under Ubuntu 20.04), that the initial import rating setting does _not_ work. Importing CR2 raws leads to 0 stars, although setting is set to 1 star.

**Comment by bilddateien** [comment] 2020-12-30 08:37
same here with 3.4.0 on debian buster

**Comment by mfg92** [comment] 2021-01-03 16:54
> 
> 
> I can confirm with darktable 3.4 (under Ubuntu 20.04), that the initial import rating setting does _not_ work. Importing CR2 raws leads to 0 stars, although setting is set to 1 star.

Same on Windows 10

**Comment by chhil** [comment] 2021-02-01 00:55
Still an issue.
Current Master darktable 3.5.0+891~gc672080f5
Jpegs don't get star rating always 0 on import. Raw files honor the preference.
![image](https://user-images.githubusercontent.com/1119439/106403749-28d5d700-6456-11eb-9bf0-9a1f79d645b4.png)

**Comment by sjjh** [comment] 2021-03-04 09:37
I can just repeat my [comment](https://github.com/darktable-org/darktable/issues/6904#issuecomment-752366792), that with current darktable 3.4.1 (Ubuntu 20.04) the darktable import preference setting initial rating of one star for RAWs still does *not* work. I currently don't know if there are any divergent star rating settings in the camera, that could be the case. Independently from the in-camera settings, I prefer to overwrite the values by darktable. So maybe it would be a good idea to provide an option in the preferences dialog to define the precedence (camera vs. darktable)to honor both use cases.

**Comment by sjjh** [comment] 2021-06-19 13:23
Reading the section
> Furthermore, a problem regarding the star rating during import has been fixed. Here, the user now has the option of specifying whether a rating should be taken from within the camera or whether a rating should be specified for all imported images during import.

from https://github.com/darktable-org/dtorg/blob/fd65558d29dd715c8348b8fdf288bca6cabfdf82/content/blog/2021-07-03-darktable-3.6/index.md it seems, that the initial rating issue is solved.

**Comment by johnny-bit** [comment] 2021-06-19 13:59
The improvements in import module fix the import rating problem and since I've recently tested pretty much extensively rating I'd say the issue is fixed.

Thanks for updating it @sjjh !

Closing!

**Closed by johnny-bit** 2021-06-19 13:59 UTC
Labels: no-issue-activity
