### ISSUE TITLE
Add Different Database Support i.e MySQL etc.

### ISSUE THREAD

**Issue by seanfletcher** [darktable-org/darktable#9075] opened 2021-05-26 23:18 UTC
**Is your feature request related to a problem? Please describe.**

I have over 25,000 Photos to work with and would love to be able to store the database in mysql that is more efficient, not only for that it would allow multiple clients (instances, and Devices) to access the database at the same time 
because it can take up to 5 or more seconds to give a photo a rating or change a filter in the "Collect Images" module that i don't have when my library is under 1000 photos currently i have to just make temporary libraries for the projects i am working on and then importing the xmp data into the master library later on

**Describe the solution you'd like**

support for the possibility of any kind of data back end 
i.e. MySQL for example but could be PostgreSQL what ever else 
the function of dt_query() should pass the query to a internal module/function for what ever data back end is in the settings i.e.
the directory structure in the main code folder would be as follows (for example only)
db-handlers/mysql
db-handlers/sqlite

and we don't need to make mysql the default continue to default to sqlite but offer others for more advanced users

**Alternatives**

wrapper scripts to generate temporary/smaller databases i.e. 
dt-wrapper <NAME_OF_IMAGE_FOLDER>
which creates a database file in ~/.config/darktable/<NAME_OF_IMAGE_FOLDER>.db
which makes editing easier but then i have to jump back to the master database to group and sort photos across projects/events

i do stock/outdoor photography work so i like to find the best of thousands of images across large amounts of time 

**Additional context**

i hope i don't get ignored on this

**Comment by ralfbrown** [comment] 2021-05-27 00:36
It's not the database causing the slowdown you are experiencing.  Work is in progress to speed up the inner workings of the Collections module so that it isn't constantly recomputing what it needs to display as you modify the metadata of your photos.  See, among others, #9058 and #9067.

**Comment by seanfletcher** [comment] 2021-05-27 02:33
Still would be nice for multi client access but good to know your working on speeding up things;

**Comment by parafin** [comment] 2021-05-27 04:35
This is a duplicate of #5904. Just switching to a different DB doesn’t magically allow for multi-client work.

**Closed by parafin** 2021-05-27 04:35 UTC

**Comment by TurboGit** [comment] 2021-05-27 06:26
> I have over 25,000 Photos to work with and would love to be able to store the database in mysql that is more efficient,

That's not what I read many times, maybe things have changed but SQLite is certainly not slow or slower than MySQL.

**Comment by TurboGit** [comment] 2021-05-27 06:28
And darktable is not for computer scientist only. So having to install a MySQL or PostgreSQL instance is certainly not a solution I'd like to see on darktable.

**Comment by seanfletcher** [comment] 2021-05-27 21:40
@TurboGit i was not saying it had to be default; default to the easiest but advanced users could choose; mysql was designed to handle multiple connections and handle them correctly
