### ISSUE TITLE
Garbage in metadata fields

### ISSUE THREAD

**Issue by FalCT60** [darktable-org/darktable#13025] opened 2022-11-27 20:02 UTC
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

When opening the Metadata editor module from the lighttable, fields get garbaged with ghosts of the modules below,
And when trying to fill the fields, vertical bars stay after each character. 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Lighttable : Open the Metadata editor module
2. Before you click on anything, you can see ghosts of "Keywords", "Geolocalisation" and "Export" resp. in the fields "Title", "Author" and "Diffuser". 
3. Fill any field
4. See what happens - cf. attached screenshot.

**Expected behavior**

**Screenshots**
![MetadataGarbage](https://user-images.githubusercontent.com/49912948/204156521-3dd2f623-f15f-4141-b8b7-25ad2f61285d.png)

**Which commit introduced the error**
dt 4.0.1

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.1 from repo
* OS                : Linux
* Linux - Distro    : Ubuntu 22.04
* Memory            : 32 Go
* Graphics card     : Mesa Intel HD graphics 620 (KBL GT2)
* OpenCL installed  : No
* Desktop           : GNOME 42.5

**Comment by Nilvus** [comment] 2022-11-29 20:03
Probably something related to your system. This place hadn't change since a time and such thing would have been posted before. I can't reproduce and never reproduce such thing on my side. I use Gnome 43 (and quite some of previous Gnome releases before) with all darktable releases (and development ones that I use daily) and never seen that.

Could you precise which theme you use? And if you use default darktable theme, which font is set on your Ubuntu system? Could you test if you have same thing by changing font used by Ubuntu system. On Gnome, you could use Gnome tweaks app to check and change font used.

**Comment by FalCT60** [comment] 2022-11-30 18:22
Hello,
Yes, obviously something related to my system. :-(
I am currently using the default theme, and using other fonts than Ubuntu Regular 11 / Sans Regular 11 / Ubuntu Mono Regular 13 / Ubuntu Bold 11 did not help.
I took three screenshots of the Preferences tab that, I hope, could help :
On the first, one can see some kind of transparency that lets the thumbnails behind appear through the text field.
Moreover, the text on the left is shifted about four lines up.
![Capture d’écran du 2022-11-30 18-50-08](https://user-images.githubusercontent.com/49912948/204875594-b42890ee-7c4d-4ca7-af12-47cdab9770b1.png)
The second screenshot shows what happens if I drag the bottom of the window towards the top and then towards the bottom again.
![Capture d’écran du 2022-11-30 18-50-59](https://user-images.githubusercontent.com/49912948/204875609-635d3985-cbb9-4892-81c9-adad5ca5e46f.png)
And the third if I drag the right side towards the left and then straight towards the right.
![Capture d’écran du 2022-11-30 18-52-23](https://user-images.githubusercontent.com/49912948/204875646-d8bd20ae-3703-4bb7-9f00-65e429e02bee.png)
Maybe a redraw problem, but how can I help solving ? What do I need to provide ?

**Comment by parafin** [comment] 2022-11-30 19:05
This looks like GPU driver bug or hardware problem perhaps.

**Comment by FalCT60** [comment] 2022-11-30 20:36
Darktable is the only software that behaves this way, and I do not rmember that it did occur with 4.0.0.
Other software (ghb, Krita, VLC, SiriL, Inkscape, scribus, MusE, Audacity, Audacious, etc.) all run fine on this machine. A fujitsu Lifebook pro E-557 with 32 GB RAM and classic 1TB SSD.
I just got a dt update (!?) and thought it would solve the problem, but no.
Just for information, the repo si rob Savoury's, but I do not think it might be relevant.
OK, the same dt version works fine on another laptop (Dell Latitude E5540), so it really has to do with the fujitsu or something running on it, but that only affects dt. :-/

**Comment by parafin** [comment] 2022-12-01 07:55
The point is that this isn’t a darktable bug. It might be a bug in GTK library or its dependencies (like cairo) though. Or maybe your window manager or compositor. Try switching to different DE.

**Comment by FalCT60** [comment] 2022-12-01 15:32
OK. I am not sure whether I try to find what I have installed on this machine that causes this, or if I reinstall the OS from scratch.
Could you please leave this issue in standby until, say, mid-january ?
I will of course report and close it before if I can find what is wrong.

**Comment by Nilvus** [comment] 2022-12-01 17:20
I think it's better to close it (we have a lot of issues and letting such ones opened do not help to be sure which ones darktable team can work). It remains possible to comment a closed issue and ping us (me for example) if more infos to see if the issue could be reopen.

Another thing regarding your issue. I don't know rob Savoury's repo. The recommended repo is OBS one (see install page on darktable.org website). It's rare but already seen that some package built have specific issues. Such thing is probably more related to what @parafin explains here, so probably not package used but would be good to test/use package from OBS repo.

**Closed by Nilvus** 2022-12-01 17:20 UTC
Labels: bug: upstream, understood: unclear, reproduce: peculiar, scope: UI

**Comment by FalCT60** [comment] 2022-12-08 20:04
Hello,
Sorry, but this behaviour is reproducible as soon as the computer is a laptop and bound to an external HD monitor.
I just tested with the second computer, which I previously wrote it was not affected - yes, but as soon as I attach it to its docking station and use my TV as an external monitor, then this occurs.
But if I deacivate the external display and use only the laptop's, the display is not fooled anymore.
I had faced this in the past with another software - VLC - and it had been found that it was related to hidpi.
It just took me some time to remember this and give it a try with my second laptop.
For information : the main laptop is a Fujutsu Probook E557, the _spare_ one is a Dell Latitude E5540.
Rgrds

**Comment by Nilvus** [comment] 2022-12-08 20:21
Seems that this remains specific to your side (or there's another component needed to find to reproduce). I use darktable on my laptop, linked nearly always on a 4K monitor screen (32"). On Hidpi setting and screen, I can't reproduce.
My system is Debian Sid with Gnome 43. Maybe there's something else, or something specific to Gtk library version used on your side for such configuration. darktable use Gtk 3, on my side, my Gtk version is 3.24.35-2.

**Comment by FalCT60** [comment] 2022-12-23 18:07
Hello,
As I just wrote on the list, the issue is now gone and it may really has been a problem with my previous install, as I was pointed to.
I removed the ppa which dt was installed from, removed dt and followed the install instruction on git.
After that, all works fine.
We will never know what could be wrong, but thank to both nilvus and parafin for your analysis.
Merry Christmas to the team. :-)
