### ISSUE TITLE
Nikon Z 9

### ISSUE THREAD

**Issue by lorax4096** [darktable-org/darktable#11067] opened 2022-02-05 22:25 UTC
Can you add support for the Nikon Z 9?  I uploaded some raw samples as you request.  It has three types of raw, compressed, high efficiency * (star), and high efficiency.  All of them are only 14 bit.

**Comment by kmilos** [comment] 2022-02-06 07:59
Duplicate of https://github.com/darktable-org/darktable/issues/10889

**Comment by lorax4096** [comment] 2022-02-11 13:34
It would be helpful if https://raw.pixls.us/ was updated to indicate that Z 9 samples had been submitted.  They aren't listed on the website and the samples directory doesn't have them.  I'm not sure if it is something you can do, but it would save effort on both the side of potential submitters (not having to take and upload samples) and on your side (not having to repeatedly mark issues as dups).

**Comment by kmilos** [comment] 2022-02-11 13:39
> It would be helpful if https://raw.pixls.us/ was updated

It has unfortunately indeed not been updated since 2021-12-31

> on your side (not having to repeatedly mark issues as dups)

There is at least something you could do here on your side: search before opening a new issue. 😉

**Comment by Jan-Jan** [comment] 2022-02-20 10:52
I wanted to buy this camera, but it makes no sense without Darktable support. Is there anything else that can be contributed (beyond the uploads that @peti and @lorax4096 have already done)?

P.S. Thank you to @peti and @lorax4096 for their uploads

**Comment by kmilos** [comment] 2022-02-20 12:00
In any case, I wouldn't shoot in the new high efficiency modes, as that will take even longer to implement.

**Closed** 2022-08-05 07:03 UTC
Labels: duplicate, scope: camera support
