### ISSUE TITLE
Shortcuts don't work reliably

### ISSUE THREAD

**Issue by dgrasberger** [darktable-org/darktable#10870] opened 2022-01-12 13:41 UTC
rating shortcuts (0-5, r) don't work reliably. sometimes the do. sometimes not. sometimes a message about switching to relative encoding

**Comment by MStraeten** [comment] 2022-01-12 13:57
you know about https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title= ?
the template is useful to provide issue reports with all relevant information.

**Comment by dterrahe** [comment] 2022-01-12 16:55
> sometimes a message about switching to relative encoding

Are you using a midi controller? 

I'm just guessing, because you are not telling us anything making it almost impossible for us to suggest (or implement) solutions. You have to help us help  you. That's what the template is for, but also, that's why you want to give as much detail as makes sense. Clearly, these shortcuts work for a lot of/most people (or many would have filed issues), so please explain what is _different_ in your case.

**Comment by dgrasberger** [comment] 2022-01-14 21:09
I do have a MIDI controller. Funny you should guess that.

There's not much to recreating the error, just  try to rate a photo in the lighttable or darkroom view. Sometimes  it works. Sometimes (up to 5 times) it reports that after x more down actions it will switch to relative encoding. Sometimes it rates the photo 0 even  you hit, say, 3. 

Windows 10. DT 3.8. Plenty of RAM and disk (everything worked fine through 3.6). In fact, I rolled back to 3.6 since 3.8 is unusable for me. At least the db format didn't change.

**Comment by dterrahe** [comment] 2022-01-14 21:17
I guessed that, because the "relative encoding" message comes from the midi module. So if you get that message while you are trying to change the rating, then dt is receiving midi messages and trying to interpret them. If your controller is not plugged in, as you say, maybe there is a midi interface or a software midi component that is sending these messages. But since you are not telling me anything about your setup, the only thing I can suggest to help you, is to put the line `plugins/midi/devices=-` in your darktablerc file. Good luck!

**Comment by dgrasberger** [comment] 2022-01-14 22:59
Thanks, that seems to have worked from an initial test.

I apologize for the lack of detail, I am a retired coder and I know how important the details are. But for Darktable, I'm just a user frustrated at something that seems completely broken from a rewrite of a module that didn't need to be rewritten. I appreciate the work y'all do.  For. Sure.

**Comment by dterrahe** [comment] 2022-01-14 23:18
> a rewrite of a module that didn't need to be rewritten

Thanks for your considered opinion. The module was completely rewritten to add features that could not possibly be supported by the old approach.

In open source, there are no "just users". There are community members, who all try to contribute, for example by testing or at least providing useful bug reports, in exchange for receiving a free program, and there are leeches. Programmers are generally less motivated by the latter, but nevertheless try to be helpful to them, just in case there is a contributor hiding inside.

**Comment by ptilopteri** [comment] 2022-01-14 23:22
so as a "retired coder" you should respect that you understand little of the dt 
code and uttering such as "completely broken from a rewrite of a module that didn't
need to be rewritten" is completely beyond your scope of understanding and 
apologize for such.  also having understanding "for how important the details are", 
you still do not provide any "details".

please close the issue as satisfied, or provide details requested that may enable
the programmers to understand and/or solve the issue.

being a "retired coder" you will appreciate and understand this request.

**Comment by dterrahe** [comment] 2022-01-15 17:22
Probably mostly duplicate of #10785 and therefore hopefully closed by #10812 in 3.8.1

If the problem persists after release of 3.8.1 feel free to reopen with more information.

**Closed by dterrahe** 2022-01-15 17:22 UTC
Labels: understood: incomplete
