### ISSUE TITLE
New versions of a photo in 3.4.0 get same number as existing versions

### ISSUE THREAD

**Issue by risbac** [darktable-org/darktable#7935] opened 2021-01-19 22:48 UTC
**Describe the bug**
After importing some old photos, I have created a new version of one of them (which had already 3 version, v0, v1 & v2). The new version has number v1, instead of v3. That's surprising, and it deleted the export of my initial v1 (since I have set export to erase). 

It's doing that on some photos, but not on others. I can't understand yet why it's doing it only on some photos. It's not the date, some older photos are fine. 

**To Reproduce**
1. Select a photo, create a new version
2. Check the version, it can be the same as an existing version.

**Expected behavior**
It should increment the version number above the latest version. 

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Ubuntu 20.10
 - OpenCL activated 
 - Intel graphic card / Nvidia graphic card

**Comment by chhil** [comment] 2021-01-20 10:50
What does new version mean?
Did you have duplicates previously created?
Were these duplicates imported ?
Were the duplicates following the naming convention that dt uses while creating them?

**Comment by risbac** [comment] 2021-01-20 13:10
i'm creating new versions using CTRL+D. Then I export them to JPG and in the name of the JPG file, I have the Version number. This way, I never erase a version with another one.

Example, I have a RAW, with 3 versions, version 0, version 1 & version 2. When I export JPG, they have _v0.jpg, _v1.jpg, _v2.jpg. 

So my current problem is that for a RAW file, I had v0, v1 & v2, I press CTRL+D on the first one (v0), and it creates a new clone, but with v1 instead of v3. Then I have 2 v1 clones. And when I export in JPG, the 2nd v1 is erasing the first one. 

Also, since I'm writing XMP for each photo, it's also erasing the other XMP. And I rely on XMP a lot, so it's also erasing the editing done on some photos, not just a JPG. 

I'm attaching a screen capture showing a photo with this problem. Two V1, two V2 : 
![Darktable_duplicated_versions](https://user-images.githubusercontent.com/8427678/105178739-bcd7a280-5b28-11eb-927b-7fa661ef40fa.jpg)

**Comment by chhil** [comment] 2021-01-20 13:50
I am using current dev branch and just creating dups I cannot mimic your problem. 


Your v1 and v2 dups were prior to the upgrade to 3.4 and creating dups after the upgrade creates the problem you indicate?

**Comment by risbac** [comment] 2021-01-20 13:53
Yes they existed before the upgrade to 3.4. And I can't replicate that on every photo ! It's happening only on some (december 2019), and some photos taken a few days before that don't show this problem. So it's difficult for me to replicate it :-(

**Comment by mchhil** [comment] 2021-01-20 14:26
You should provide the details of which version you were on prior to the upgrade; it will help the devs debug it.

**Comment by risbac** [comment] 2021-01-20 14:50
I was using the previous version of DK, official one. I was compiling at the end of 2019, but I didn't do it last year. Would you need to know the version of DK that I was using when I have imported and worked on the photos which are creating the pb ? That's more complicated to determine for me.

**Comment by ptilopteri** [comment] 2021-01-20 15:00
did you make the dups and rename them before importing into dt?

**Comment by risbac** [comment] 2021-01-21 08:14
How can you rename a dup ? I don't even know how to rename a new version. I simply use CTRL+D to create new versions of photos, I have XMP for every version. I don't rename anything, I don't think I'm doing anything very special, just use the standard commands & options.

I work with 2 computers and use a replication of all the RAW & XMP, to update the local database of Darktable (I don't sync the database, I don't have the same photos on both computers, one is only to work on specific sets on the go). Both computers have the same version of DK.

**Comment by Nilvus** [comment] 2021-01-21 08:19
> How can you rename a dup ? I don't even know how to rename a new version. I simply use CTRL+D to create new versions of photos, I have XMP for every version. I don't rename anything, I don't think I'm doing anything very special, just use the standard commands & options.

Just use duplicate manager in darkroom to rename all clones of the same image as you want. Names applied are just default ones regarding what's known in database and existing XMP by darktable.

**Comment by risbac** [comment] 2021-01-21 08:23
Ah ok, I see where it is. And l almost never used that, and the photo where I see this problem of duplicated versions has no renamed clones, I just checked. Only the standard 0, 1, 2.

**Comment by Nilvus** [comment] 2021-01-21 17:39
> Ah ok, I see where it is. And l almost never used that, and the photo where I see this problem of duplicated versions has no renamed clones, I just checked. Only the standard 0, 1, 2.

The standard should so be your v0, v1, etc. If not, so just rename them and you will have what you want. Just precise if this ok for you now as on what you describe I just see the normal behavior of darktable and just a misuse of this feature that you visibly don't know well.

i'm waiting for your feedback to see if we could close (you could do it if ok for you) this issue.

**Comment by Nilvus** [comment] 2021-01-21 17:43
To complete, I suggest you to read (it's really fast) what's about duplicate manager in the manual: https://darktable-org.github.io/dtdocs/module-reference/utility-modules/darkroom/duplicate-manager/

And as you will see on it, you could also set the version in the metadata editor in lighttable (right panel).

**Comment by elstoc** [comment] 2021-01-22 15:57
> And as you will see on it, you could also set the version in the metadata editor in lighttable (right panel).

I think you're confusing the version _number_ (which is hard-coded by darktable when an image is imported or a duplicate created) and the _version name_ (which is an optional metadata description)

**Comment by Nilvus** [comment] 2021-01-22 18:43
> I think you're confusing the version _number_ (which is hard-coded by darktable when an image is imported or a duplicate created) and the _version name_ (which is an optional metadata description)

No, I'm not confusing, just explain that the user could set a version name (could be a version number) there. I know that version number is hard-coded and can't be changed.

**Comment by elstoc** [comment] 2021-01-22 19:09
Then renaming versions is beside the point of this issue - two duplicates of the same image should never be given the same version number, which is the issue that's being reported here.

**Comment by Nilvus** [comment] 2021-01-22 20:03
> Then renaming versions is beside the point of this issue - two duplicates of the same image should never be given the same version number, which is the issue that's being reported here. I can't reproduce this issue but then I don't have very many old edits in my copy of master.

I agree but that's not what I understand here. Maybe I'm wrong but @risbac doesn't seems to know well how to use clone. And darktable doesn't set vX versions, but only X version number. So as @risbac suggest that he have vX (the v is not set by darktable), I suppose it's not really darktable automatic naming. But some things on this issue suppose so, and that's why I add label "understood: unclear". I never see issues in automatic version in darktable.

Said that, @risbac, please be more precise on this issue. How do you add the "v" in your number versions? Or you do it wrong and have this issue, or that hide, as @elstoc suggest an issue in specific cases. So you need to be more precise to help.

**Comment by elstoc** [comment] 2021-01-22 20:13
> darktable doesn't set vX versions

I just assumed the "v" was hard-coded into the overlay pattern

**Comment by Nilvus** [comment] 2021-01-22 20:48
> > darktable doesn't set vX versions
> 
> I just assumed the "v" was hard-coded into the overlay pattern i.e. `V$(VERSION)`

I don't have that on my side, just $(VERSION).

**Comment by elstoc** [comment] 2021-01-22 20:59
The "V" is not part of the variable, it's hard coded text i.e. the following in preferences

![Screenshot_2021-01-22_20-58-23](https://user-images.githubusercontent.com/9555491/105545991-abdb8c80-5cf4-11eb-98fc-96c219a35051.png)

gives the following tooltip

![Screenshot_2021-01-22_20-57-59](https://user-images.githubusercontent.com/9555491/105546007-b433c780-5cf4-11eb-901c-0bbc848fccc1.png)

**Comment by elstoc** [comment] 2021-01-22 21:08
> I work with 2 computers and use a replication of all the RAW & XMP, to update the local database of Darktable (I don't sync the database, I don't have the same photos on both computers, one is only to work on specific sets on the go)

This looks like a possible culprit. How are you doing this?

**Comment by Nilvus** [comment] 2021-01-22 21:20
> The "V" is not part of the variable, it's hard coded text i.e. the following in preferences

Of course, it's hard-coded, by the user, not darktable. That doesn't change what I want to be sure here. Of course, the issue could also be on darktable, but also on the user side.

**Comment by risbac** [comment] 2021-01-23 08:46
Ok, so let's me explain : you see V0 V1 V2 because I have put " • V$(VERSION)"
I don't use names for versions. So what you see is really the version NUMBER, not the name. 

![Capture d’écran de 2021-01-23 09-28-04](https://user-images.githubusercontent.com/8427678/105573503-54720680-5d5e-11eb-9e27-c2ea28eb7391.png)

So I have 5 versions of this photo in the lighttable, but only 3 XMPs. The "second" version 1 has deleted the XMP of the first one, and same for the "second" version 2. Since I'm re-reading settings from the XMPs when I open Darktable, I think it has deleted the editing of the original V1 & V2 as well (I need to check the history of changes on them to confirm). And since my export in JPG are also including the version number, I have lost my initial V1 & V2 Jpegs. 

So at least on this photo, it's a serious problem in my view, it could be deleting some work. 

So far, I didn't see it happening on other photos, but I didn't edit many photos since

**Comment by risbac** [comment] 2021-01-23 08:47
![Capture d’écran de 2021-01-23 09-47-05](https://user-images.githubusercontent.com/8427678/105573743-fe9e5e00-5d5f-11eb-9e86-bc8d7092bab1.png)

**Comment by TurboGit** [comment] 2021-01-23 08:58
First I have not read everything, sorry then if my questions are stupid. Let's go back a bit.

> So I have 5 versions of this photo in the lighttable, but only 3 XMPs.

First this should never happen. How is that possible? This may be the root cause of the problem. If you have 5 versions on the lighttable you should have 5 XMP no ? Or maybe you are changing the XMP write option from time to time.

Anyway, we need to understand how you came to this situation first, there is no need to try to understand what is happening because of this at this point.

So please, can you clarify ?

**Comment by risbac** [comment] 2021-01-23 09:05
Yes, I should have 5 XMPs. I'm not changing the XMP write option, I'm using the same options for a long while. I really don't remember changing this option. And anyway, even if I was not writing XMPs, would it be normal to have photos with the same version numbers in the database ? Those versions numbers are saved in the local DT database, right ? Otherwise, if it was relying only the XMPs, I would see only 3 versions. 

It happened simply when I cloned this photo twice. It was imported in January 2020, so quite likely with the official Xmas version of 2019. I worked on it back in January I guess, doing 2 clones (v1 & v2). Last week, I went back on this photo, and decided to do more clones. That's when the troubles began : it created those new v1 & v2 instead of v3 & v4. i didn't notice it immediately, until I didn't find my v3 and v4 jpegs, but instead updated v1 & v2 jpegs. Took me a while to understand what was going on. 

Since, I didn't find any other photo which had the problem (including photos taken & imported at the same period, I tried to create new clones and it went fine).

**Comment by TurboGit** [comment] 2021-01-23 09:12
@risbac : so this looks like some corruption somewhere, this is not a normal behavior, probably not a bug in dt has we have never seen such report. So I'm more for a corruption of the db leading to this issue. What should we do ? No idea, we cannot workaround an issue that we have no idea how to reproduce or how it happened. So either we get this information or we close this PR for now.

**Comment by parafin** [comment] 2021-01-23 09:19
Most DB corruptions **are** DT bugs;)

**Comment by TurboGit** [comment] 2021-01-23 09:22
Yes somehow :) I was thinking of a crash due to OS lib or wrong OpenCL support...

**Comment by parafin** [comment] 2021-01-23 09:30
Well, well-designed DB won't have inconsistencies even in case of SW/HW crashes (unless we're talking about actual hardware data corruption in RAM/disk). Using foreign keys and transaction getting us closer to that.

**Comment by risbac** [comment] 2021-01-23 09:33
Do you have a unicity constraint on photo ID + version in the database? I will look at the SQLite dB by curiosity.

**Comment by elstoc** [comment] 2021-01-23 09:36
No the constraint is just on id. I'm sure your database has somehow got the wrong versions in it (iirc darktable uses the maximum version column to work out the next version number). I'd still like to know how you're managing your single collection with 2 PCs.

**Comment by risbac** [comment] 2021-01-23 09:44
I write XMPs for all photos. All raws & XMPs are synched on my NAS. So on both computers, for the selected folders, I have the exact same content. The only manual operation I have to do is to reimport the folders each time there were modified by the other computer, to read the new XMPs and import the new versions. It's quite fast to do. And with NAS sync, the XMPs are saved on the fly. Then I have a real back up from the NAS to a cloud back up.

**Comment by elstoc** [comment] 2021-01-23 09:45
Thanks. I think we can probably rule that out then. If darktable found a conflicting version number in that operation it would just overwrite the existing record.

**Comment by TurboGit** [comment] 2021-01-23 11:29
Well it may be that you have created a duplicate before re importing from the NAS. I suppose such a case would create image with the same version. We cannot cope with wrong usage like this one. As @elstoc we use the MAX(id) to create the new duplicate, so somehow the database didn't have the proper information and so create a duplicate number.

**Comment by elstoc** [comment] 2021-01-23 11:39
> Well it may be that you have created a duplicate before re importing from the NAS. I suppose such a case would create image with the same version. 

I'm not sure - it appears that the revised xmp files are only getting into the database via an import operation, in which case this should never happen and sounds like there must be a bug somewhere (though it may be a bug on an old version of dt that messed the database up). If the xmp version matches a version already in the database, the import should just overwrite the existing version in the db - it should not create a new record, and neither should the duplication of an image within darktable.

**Closed** 2022-06-25 10:14 UTC
Labels: understood: unclear, no-issue-activity
