### ISSUE TITLE
"perspective correction"'s "automatic cropping=original format" incompatible with orientation

### ISSUE THREAD

**Issue by moy** [darktable-org/darktable#2346] opened 2019-04-06 18:25 UTC
**Describe the bug**
In module "perspective correction", using "automatic cropping=original format" doesn't work when the "orientation" module is active: the rectangle doesn't properly follow the mouse, and the 4-directional arrows in the middle of the rectangle is not displayed.

**To Reproduce**
1. Open an image
2. Activate "orientation", and rotate the image (e.g. by 90°)
3. Activate "perspective correction" and chose "automatic cropping=original format"
4. Click on the image

**Expected behavior**
The cropped rectangle follows the mouse and a 4-directional arrows drawing is shown in the middle.

**Platform (please complete the following information):**
 - OS: Ubuntu
 - Version: Git master

Original report (french): https://forums.darktable.fr/showthread.php?tid=3512

**Comment by TurboGit** [comment] 2019-04-07 09:11
Just to be sure, this is not a regression I suppose and can already be reproduced on 2.6.2, right?

**Comment by moy** [comment] 2019-04-07 11:35
I didn't test before reporting, but yes, it can be reproduced on the stable version.

Note that the "crop and rotate" module doesn't have this problem (crop and rotate is disabled while the perspective correction is selected).

**Comment by TurboGit** [comment] 2019-04-07 15:59
Ok, good to know this is not a regression due to my fixes and delicate changes on orientation handling :)

**Comment by leclercj** [comment] 2019-04-07 21:50
Bug already present in 2.6.2 indeed. I met it several times, but was not able to identify the conditions for reproduction. Thanks @moy to have circle this down.

**Comment by TurboGit** [comment] 2019-04-09 15:56
A nice one :) The fix was not trivial! Anyway now fixed.

**Closed by TurboGit** 2019-04-09 15:57 UTC
Labels: bug
