### ISSUE TITLE
Ctrl+Shift+D issue on lightable

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#10732] opened 2021-12-29 12:13 UTC
Duplicate image virgin shortcut (shift+ctrl+d) is open the selected item in the darkroom instead of making duplicate in the lighttable. The shortcuts is working only in the lighttable. It was worked well at all place in th dt3.6

To Reproduce:

- select an item at the lighttable
- press shift+ctrl+d

* darktable version : 3.8.0
* OS                : Linux - 5.4.0-91-generic
* Linux - Distro    : Linux Mint 20.2 Cinnamon

**Comment by Nilvus** [comment] 2021-12-29 19:13
Shortcuts have been completely reworked to be more powerful and allow midi devices. And so some shortcuts could have been forgotten. You just have to set them in new shortcuts dialog window.

Anyway, @dterrahe: maybe this one could be fixed by default for 3.8.1 (or 4.0)?

**Comment by vsz1lu** [comment] 2021-12-30 13:13
> Shortcuts have been completely reworked to be more powerful and allow midi devices. And so some shortcuts could have been forgotten. You just have to set them in new shortcuts dialog window

There are only one option to assign shortcut for duplicate virgin and set by default. The problem is: make virgin duplicate in darkroom, but open the image and make duplicate in the lighttable.

![Képernyőkép – 2021-12-30 13-53-55](https://user-images.githubusercontent.com/57588193/147754848-3c95e9f5-5a04-4fbc-a416-9572568417b8.png)

**Comment by dterrahe** [comment] 2021-12-30 14:15
You are right, duplicate virgin is broken in lightroom.

The problem is that many of these shortcuts lived in two places; in the "thumbtable" (bottom of screen) and in the "selected image[s]" module (at the right side). Pre 3.8 the duplicates were disabled in a hackish way (that however allowed control on a per-shortcut basis). InputNG is somewhat more structured and shortcuts are dis-/enabled on library/module level. But virgin duplicate is the exception in that it doesn't have a button in the module.

When I've got time, I'm going to try to add the "virgin" duplicate option to the "duplicate" button in the "selected image[s]" module via a ctrl+click. That then also allows a shortcut which sends the "ctrl-activate" effect, restoring previous functionality.

**Closed** 2022-01-02 16:13 UTC
Labels: feature: enhancement
