### ISSUE TITLE
Graphical glitch in the histogram while color picking (rgb module)

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#11003] opened 2022-01-26 20:16 UTC
I'm getting graphical glitches in the histogram while color picking in the **rgb curve** module.

**Reproduce**

Open the RAW file from this thread:
https://discuss.pixls.us/t/darktables-filmic-rgb-defaults-render-this-desaturated/29068

with this xmp file (sorry for zip, xmp is not allowed for upload):
[P1200988.RW2.zip](https://github.com/darktable-org/darktable/files/7945223/P1200988.RW2.zip)

Go to the rgb curve module, select the color picker and drag the cross around in the picture.
Now the graphical glitch is appearing  **occasionally** within the histogram (see screenshot).

**Screenshots**

![Bild1](https://user-images.githubusercontent.com/57685590/151239185-879ec345-ebde-4ace-a4d4-13439ff9b5ad.jpg)

**Platform**

* darktable version : 3.8.0
* OS                : Win10 64bit
* Memory            :  16 GB
* Graphics card     : Intel/Nvidia
* Graphics driver   : 
* OpenCL installed  : yes
* OpenCL activated  : no

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-01-27 08:49
In the vectorscope display the glitch is appearing as a little speck.


![Bild2](https://user-images.githubusercontent.com/57685590/151323947-9579c6de-b00a-4bee-a47c-93a36b975290.jpg)

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-01-27 13:12
Maybe it's related to demosaic **RCD**? When I switch to another method the glitch is gone. 
Also turning on demosaic color smoothing seems to help.

**Comment by Nilvus** [comment] 2022-01-27 19:26
@jenshannoschwalm: if this could be related to RCD demosaicer, maybe your view could be helpful here.

**Comment by jenshannoschwalm** [comment] 2022-01-28 06:39
I will have a look tonight

**Comment by jenshannoschwalm** [comment] 2022-01-28 10:52
@c-h-r-i-s-t-i-a-n 
before me looking into this deeper (i tried this morning for a short time and couldn't trigger the issue yet), a few answered questions will help
1. what setting are you using in preferences->pixel interpolator (scaling)? What you see could be the result of using lanczos3.
2. It seems you are taking histogram data in point mode. Does the issue persist in area mode?
3. Do you see a difference between OpenCL on/off?
4. Is the issue persisting if you switch off modules that might correct chromatic aberration (lens ...)? I ask this because such low-level artefacts could also produced here by lensfun algo as can be regularly seen while working on monochrome images.

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-01-28 13:07
1. Also occurs with other interpolator methods like bilinear, bicubic.
2. issue persists in area mode. 
3. issue persists with opencl on.
4. issue persists when leaving on only:  blackpoint/white bal/demosaic/rgb curve/input output profile
5. the glitch in the histogram can also be triggered in the **tone curve** module.

**Comment by jenshannoschwalm** [comment] 2022-01-28 13:38
Leaves me clueless atm, just to make sure: it's only happening with RCD?

**Comment by jenshannoschwalm** [comment] 2022-01-28 16:43
Just tried for some time to trigger the issue and couldn't reproduce it a single time. I confess i don't fully understand the way the histogram data are fed but any demosaicer might do some overshoots but like this? I have never observed something like that on PPG, RCD or LMMSE (those are the ones i know the code quite well).

I also tried with "performance mode" or downscaled previews btw.

Maybe it would help to see a video to get a clue? Could you produce one?

**Comment by TurboGit** [comment] 2022-01-28 17:49
Maybe @dtorop can shed some light on the histogram stuff?

**Comment by jenshannoschwalm** [comment] 2022-01-28 17:57
@TurboGit @Nilvus could you reproduce the issue?

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-01-28 19:13
Video:

https://user-images.githubusercontent.com/57685590/151607371-559fb3ec-f5b4-4401-9214-2290b212087d.mp4

**Comment by dtorop** [comment] 2022-01-28 19:38
Hmmm. Interesting video. And seriously confusing, as the appearance is so glitchy.

Out of curiosity, what is the "display profile" and "histogram profile" settings? Right click the toggle gamut or softproofing buttons at the bottom right of the center view to see these in a pop-up menu. If the display profile is non-standard (e.g. it's a calibrated screen), it may be helpful to upload the ICC profile.

**Comment by jenshannoschwalm** [comment] 2022-01-28 19:51
The "range numbers" look a bit strange

**Comment by jenshannoschwalm** [comment] 2022-01-29 07:39
I still can't reproduce as reported but there is something not working correctly with the shadowed histogram data presented in the rgb-curve module.

![Bildschirmfoto von 2022-01-29 08-31-38](https://user-images.githubusercontent.com/50982232/151652089-4f9ee8e3-e85a-4df0-b92b-f7dbf48e7f93.png)

You can see low-signal data at the right side of both histograms. If you scroll though the demosaicers you will see that changing in the main hist correctly. But in the rgb-curve histo this is not always correct like here
![Bildschirmfoto von 2022-01-29 08-37-53](https://user-images.githubusercontent.com/50982232/151652296-e70edfae-e04a-45aa-851c-d3840a262680.png)

For me it seems to be a gtk widget update problem ???

**Comment by TurboGit** [comment] 2022-01-29 09:26
@jenshannoschwalm : I'll try to reproduce today.

**Comment by TurboGit** [comment] 2022-01-29 12:12
Tried, tried hard and cannot reproduce on my GNU/Linux box. Either a Gtk+ issue or a general issue only seen on Windows. Would be hard to say.

@wpferguson : as you build on Windows can you try to reproduce this with the RAW + xmp linked on first comment? 

@windows-users: If you read this, can you test and report is you reproduce or not? TIA.

**Comment by gi-man** [comment] 2022-01-29 17:09
I'm in windows 11 with 3.9.0+116~gc543d2cb2

I cant reproduce this (with or without OpenCL). I tried to click in the same areas as the posted video.

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-01-29 17:11
> The "range numbers" look a bit strange

Which numbers do you mean?

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-01-29 17:14
> Out of curiosity, what is the "display profile" and "histogram profile" settings? Right click the toggle gamut or softproofing buttons at the bottom right of the center view to see these in a pop-up menu. 

display profile = system
softproof profile = sRGB
histogram profile= sRGB

I'm not using a calibrated screen / icc stuff. 

On my linux laptop (manjaro) I'm also not able to reproduce the glitch.

**Comment by wpferguson** [comment] 2022-01-29 19:25
Tried to reproduce and couldn't in either windows or linux with current master

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-01-30 15:49
Could reproduce this also with a Canon CR2 raw file.

**Comment by dtorop** [comment] 2022-02-02 02:42
> display profile = system softproof profile = sRGB histogram profile= sRGB
> 
> I'm not using a calibrated screen / icc stuff.

A long shot, but if you change "display profile" to something known, such as sRGB (or really anything on the list except for system), does the problem still occur?

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-02-02 14:06
Yes, problem still occurs.

**Comment by jenshannoschwalm** [comment] 2022-02-02 14:35
@dtorop i looked into the histogram code somewhat deeper yesterday, also watching the video again and tried to understand what's going on.

Form my current understanding it seems we have possibly two different issues.

1. The helper histograms inside the modules are not updated if data are read from pipeline cache. (You can do whatever changes visible output like switching on/off the highlights reconstruction module offering a nice purple cast - the main histo is changed always, the modules histo is **not**) This is easy to understand, as in ```dt_dev_pixelpipe_process_rec``` we immediately go to ```post_process_collect_info```, where we only update the main histo but do not check/update inside the modules. (This can and should probably be fixed there)
2. This leaves out: where are the **wrong** data for the main histogram are coming from? I looked at the histo `Worker` code and there we use `c/realloc` for the histogram buffer. (From the docs this should be aligned for the largest native datatype, which would be 8 on windows ...) But the code seems to assume we are simd aligned - this would take/write bogus data.

What do you think?

**Comment by dtorop** [comment] 2022-02-02 15:10
@jenshannoschwalm These are both really good points. Regarding 2), all that code seems heavily optimized for decade-old CPUs/compilers, and could use some attention.

I spent a bit of time looking at the pixelpipe code:

 - In the normal case for a "modern" pixelpipe, the final histogram is calculated from gamma input. But as gamma nowadays is usually just after colorout, it makes sense to instead calculate this from colorout input, which saves a colorspace hop.
 - But this cause caching problems. If colorout is cached, we don't have access to its input.
 - Probably the right thing to do then is just not update the histogram. But if I turn off caching for colorout, I see some interesting noise in the upper part of the preview image.

I haven't traced this noise, but wonder if this is connected to 2), or yet another bug. Here is a diff which can trigger the bug for me:

```diff
modified   src/develop/pixelpipe_hb.c
@@ -1110,7 +1110,7 @@ static int dt_dev_pixelpipe_process_rec(dt_dev_pixelpipe_t *pipe, dt_develop_t *
   // do not get gamma from cache on preview pipe so we can compute the final histogram
   if((pipe->type & DT_DEV_PIXELPIPE_PREVIEW) != DT_DEV_PIXELPIPE_PREVIEW
      || module == NULL
-     || strcmp(module->op, "gamma") != 0)
+     || !(strcmp(module->op, "colorout") == 0 || strcmp(module->op, "gamma") == 0))
   {
     dt_dev_pixelpipe_cache_fullhash(pipe->image.id, roi_out, pipe, pos, &basichash, &hash);
     cache_available = dt_dev_pixelpipe_cache_available(&(pipe->cache), hash);
```

(Also, because the gamma is never fetched from cache, some later code that handles no gamma input data for the histogram is irrelevant.)

Yet another thing is that colorout always asks for Lab input data, which doesn't seem to make sense anymore when the pipeline up until then could be in RGB -- an unnecessary hop?

Maybe the question is just who will work on fixes. I have some time, if it helps... Of course none of this may fix this unsual Windows bug.

**Comment by jenshannoschwalm** [comment] 2022-02-02 16:28
> all that code seems heavily optimized for decade-old CPUs/compilers, and could use some attention.

Absolutely, it just make the code less clear.

> I see some interesting noise in the upper part of the preview image

confirmed :-)

> none of this may fix this unsual Windows bug

Yes, can be. But i think it's worth to use the dt_aligned versions of alloc and friend to make sure. I remember other issues also related to different aligns between windows/linux.

> Maybe the question is just who will work on fixes. I have some time, if it helps

Good. I think we both have grossly the same ideas here so go ahead :-)

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-02-02 17:22
BTW **CPU** : Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz

**Comment by jenshannoschwalm** [comment] 2022-09-11 10:31
@dtorop @c-h-r-i-s-t-i-a-n coming back to this - i can't reproduce any longer now!  

From my current understanding the issue is likely related to the (now updated) pixelpipe cache code. As we have a module expanded we do (and did) reweigh the cacheline of the module with the inside gtk widget. NOW very likely we have correct data from the cache, with the old cache code - likely not as there were only 5 cachelines and overwritten data was often taking place.

Could you check?

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-09-11 17:44
Which version? Bug is still there in 4.0.0.

**Comment by jenshannoschwalm** [comment] 2022-09-11 18:01
In master from today ...

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-09-11 19:46
It's still occuring in 4.1.0+338.

**Comment by jenshannoschwalm** [comment] 2022-09-11 21:13
Thanks for testing...

**Comment by jenshannoschwalm** [comment] 2022-11-15 06:39
@c-h-r-i-s-t-i-a-n i checked this after some time - and after finding some very old pixelpipe-cache bug possibly resulting in wrongly read histogram data from the preview pixelpipe.

I can't reproduce any longer, could you please check & confirm the fix and possibly close the issue?

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-11-15 08:25
Is this in master? If not how can I integrate the patch?

**Comment by jenshannoschwalm** [comment] 2022-11-15 10:17
In master

**Comment by jenshannoschwalm** [comment] 2022-11-15 12:33
I can't reproduce in top histogram any more...

**Comment by Mark-64** [comment] 2022-12-29 07:46
Can't reproduce, Windows 11, DT 4.2, nVidia 1060

**Comment by dtorop** [comment] 2022-12-29 14:38
Just looking at this again, after long hiatus. I should have a bit more time and would finally like to modernize/rework the common/histogram.c code, for all the reasons above (it's optimized for obsolete compilers/CPUs and may have alloc bugs on Windows). This could be a follow-up to cleanup of the common colorpicker code (#13216).

Is part of the weirdness because of pixelpipe's handling of histograms and colorpickers? Unless recent work by @jenshannoschwalm changed this, the pixelpipe will update per-module histogram/pickers after processing that module, but if the module output is pulled from the cache, these aren't updated. I dabbled a while back with a fix for this via forcing re-processing of iops which needed histogram output. This added a bunch of special-case code and processing. Wouldn't it be better if the pixelpipe cache included not just the iop's output data but also the associated histogram? (And picker data as well?)

**Comment by jenshannoschwalm** [comment] 2022-12-29 16:18
@dtorop there is a pending PR still but that is not related to histogram code.

I am somewhat surprised about this "but if the module output is pulled from the cache". From how i understand the pixelpipe code i would say that a module might possibly get a cached buffer (from a module earlier in the pipeline) as input. That's btw how the important hint for expanded modules works. An expanded module is very likely to change a parameter so it wants it's input to be available. And a heavy-processing module (A) passes a hint to the next module (B) in the pipeline to take it's (B) input as "important" to avoid reprocessing (A). Or do we misunderstand here?

**Comment by dtorop** [comment] 2023-02-28 16:42
I'm curious if this bug is reproducible now that #13330 is merged, as that PR altered a bunch of the histogram-calculating code?

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2023-02-28 18:20
Hi, I can still reproduce it (V 4.3.0+558, build on Feb-10).

![grafik](https://user-images.githubusercontent.com/57685590/221943963-746abfb3-d9db-4927-ad33-8dce2f40e60b.png)

**Comment by dtorop** [comment] 2023-02-28 19:16
> Hi, I can still reproduce it (V 4.3.0+558, build on Feb-10).

Well, being able to reproduce a bug is at least a start to the process of fixing it!

I'm off the table for dt work for a bit (weeks, at least), but it is good that github auto-reminds once the report goes fallow -- that will be about the right interval for me.

**Closed** 2023-04-11 11:18 UTC
Labels: understood: incomplete, reproduce: peculiar, scope: UI, scope: image processing, bug: pending
