### ISSUE TITLE
Segfault when clicking login to piwigo

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#10933] opened 2022-01-20 16:47 UTC
**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to 'Enter server address and username and password'
2. Click on 'login'
3. Segmentation fault

It seems to me to be a glib related error and not a Darktable error?

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.0
* OS                :  Linux kernel 5.15.0-2 and kernel 5.15.0-3
* Linux - Distro    : Debian Sid (Unstable)
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
gdb backtrace file provide:
[darktable_bt_2JVGG1.txt](https://github.com/darktable-org/darktable/files/7907014/darktable_bt_2JVGG1.txt)

**Comment by TurboGit** [comment] 2022-01-20 17:02
Ok I have added a possible fix for this here : https://github.com/darktable-org/darktable/pull/10931

**Comment by TurboGit** [comment] 2022-01-20 17:02
If you can test it would be nice!

**Comment by mir07** [comment] 2022-01-20 17:50
It fixes the segfault but introduces a new problem. The album list is an empty list (not even the option to create a new album is available) and clicking 'refresh album list' results in an error message 'cannot refresh albums'.

**Comment by mir07** [comment] 2022-01-20 17:55
> It fixes the segfault but introduces a new problem. The album list is an empty list (not even the option to create a new album is available) and clicking 'refresh album list' results in an error message 'cannot refresh albums'.
Correction: It is not a empty list. This list is NULL.

**Comment by TurboGit** [comment] 2022-01-20 21:46
> > It fixes the segfault but introduces a new problem. The album list is an empty list (not even the option to create a new album is available) and clicking 'refresh album list' results in an error message 'cannot refresh albums'.
> > Correction: It is not a empty list. This list is NULL.

I cannot reproduce. I see "create new album" and was able to publish a new picture into an existing album.

**Comment by mir07** [comment] 2022-01-20 22:03
First something that could be a difference. I am using the 3.8.0 source from debian Sid.
Right after login a pop-up error is displayed saying 'Cannot refresh albums'. See attached screenshot where you can see that the album list is completely empty.

![2022-01-20_22-53](https://user-images.githubusercontent.com/2576455/150429353-4670842b-d288-4ce3-9c03-ae117454202d.png)

**Comment by mir07** [comment] 2022-01-20 22:05
> First something that could be a difference. I am using the 3.8.0 source from debian Sid. Right after login a pop-up error is displayed saying 'Cannot refresh albums'. See attached screenshot where you can see that the album list is completely empty.
> 
> ![2022-01-20_22-53](https://user-images.githubusercontent.com/2576455/150429353-4670842b-d288-4ce3-9c03-ae117454202d.png)
So maybe you have made other changes than 'if(value == NULL) return;' in static void _piwigo_album_changed(GtkComboBox *cb, gpointer data) ?

**Comment by mir07** [comment] 2022-01-20 22:13
Where can I find the content of 'storage/piwigo/last_album'

**Comment by TurboGit** [comment] 2022-01-20 22:15
In `~/.config/dakrtable/darktablerc`

Also, you need to test with Git sources. If you cannot, no problem.

**Comment by mir07** [comment] 2022-01-20 23:19
I found what causes the problem:
~/.config/dakrtable/darktablerc had this content
storage/piwigo/last_album=
Change it to this (name of a known album)
storage/piwigo/last_album=Flowers
everything works as expected?

![2022-01-21_00-18](https://user-images.githubusercontent.com/2576455/150437463-28d052a5-1c9e-47e0-a623-3a68a7998d08.png)

**Comment by mir07** [comment] 2022-01-20 23:28
It is btw easy reproducible.
1) Choose an album from the dropdown list and leave darktable running
2) Go to piwigo and delete all images in the chosen album
3) Go to darktable click 'refresh album list'
4) album list is empty and every click on the  'refresh album list' pops up the 'Cannot refresh albums'.

IMHO is seems that the code for generating the album list fails if there are empty albums in piwigo. As soon as I add an image to the empty album a click on the refresh button and the list gets populated correct again.

**Comment by mir07** [comment] 2022-01-20 23:36
To sum it up there exists two bugs:
1) If the setting in darktablerc looks like this: storage/piwigo/last_album=
it fails since in cannot handle a NULL last_album
2) If an album in piwigo is empty it also fails.

Since both bugs shows similar behavior I bet they are triggering the same bug in plugin. My guess is a foreach loop somewhere which if not run at least once causes the album list to be uninitialized.

**Comment by TurboGit** [comment] 2022-01-21 07:55
This is strange I cannot reproduce with server piwigo.com (I'm not self hosted).

Note that `storage/piwigo/last_album=` is not a `NULL` album name but an album name with an empty string. Anyway I still cannot reproduce.

**Comment by mir07** [comment] 2022-01-21 08:31
Do you know which version of piwigo is deployed at piwigo.com?

**Comment by TurboGit** [comment] 2022-01-21 08:38
Yes, that's Piwigo 12.2.0

**Comment by mir07** [comment] 2022-01-21 09:50
Same as my version. I can however not guaranty that my installation is the same, or even configured the same way as piwigo.com so differences is absolutely in play.

**Comment by TurboGit** [comment] 2022-01-21 11:27
Yes, not sure what could be the issue. I have tried with some albums name with characters outside of UTF-8 range to see if I could create a crash or an issue with the refresh. But all seems to work again.

I'll probably merge the PR today which fixes some issues and we'll continue this in another issue if we can reproduce.

**Closed** 2022-01-21 18:28 UTC
Labels: bug: pending
