### ISSUE TITLE
Some GUI elements in import parameter section wrongly localized

### ISSUE THREAD

**Issue by Thanatomanic** [darktable-org/darktable#8263] opened 2021-02-18 13:01 UTC
**Describe the bug**
Despite the interface language set to English, some of the labels in the section 'parameters' under 'import' in the lighttable are localized (in my case Dutch). This should not happen. See screenshot below.

**Screenshots**
![image](https://user-images.githubusercontent.com/6567747/108359566-6ffeee80-71f0-11eb-837b-c472ce574dc1.png)

**Platform:**
 - dt 3.5.0+1135~gdca46cdea
 - OS: Windows 10

**Additional context**
I have compiled darktable myself in a clean build-directory. I have removed the config directory, but this does not affect the bug.
These are my Windows language settings:
![image](https://user-images.githubusercontent.com/6567747/108360462-8b1e2e00-71f1-11eb-96de-7d25db3fce28.png)
The Regional format is the only thing set to Dutch, but this should definitely not influence the dt interface afaik.

**Comment by Thanatomanic** [comment] 2021-02-18 13:05
I can confirm that setting the OS Regional format to English, changes the remaining interface labels to English as well.

![image](https://user-images.githubusercontent.com/6567747/108361099-58c10080-71f2-11eb-88e2-deda58719ace.png)

**Comment by parafin** [comment] 2021-02-18 13:26
What happens if you try to re-select English in darktable preferences (choose another then English)? Application restart is needed. Or setting ui_last/gui_language=C in darktablerc.

**Comment by Thanatomanic** [comment] 2021-02-18 13:30
Steps I took:
1. Launch darktable
2. Change language to French
3. Close & relaunch
4. The interface is in French, except the earlier mentioned Dutch words
5. Change language to English
6. Close & relaunch
7. The interface is in English, except the earlier mentioned Dutch words

At Step 4:
![image](https://user-images.githubusercontent.com/6567747/108363971-cde20500-71f5-11eb-8374-0b568e5bc78e.png)

**Comment by Nilvus** [comment] 2021-02-18 17:52
I can reproduce. I use french and I just change language to Deutsch then restart darktable. I have still same text in french like all the UI is in Deutsch language.

![2021-02-18_18-49](https://user-images.githubusercontent.com/45535283/108399288-3e028200-721a-11eb-8dbe-93964b3ac954.png)

Same thing if I then change language for Espanol. All UI changed in Espanol language except those lines, that remains in french.

@phweyland: as you work on that part, could you check? Probably some refresh missing thing?

**Comment by phweyland** [comment] 2021-02-18 18:36
> could you check? Probably some refresh missing thing?

I have no idea ... I just see they are exactly the texts which are defined in darktableconfig.xml.in.
Can you see the same issue in map settings ? In preferences of collect images ?

**Comment by phweyland** [comment] 2021-02-18 18:40
On my side, with the current master I see the translated messages in the right language (when translation exists sure :) )

**Comment by Nilvus** [comment] 2021-02-19 12:34
> On my side, with the current master I see the translated messages in the right language (when translation exists sure :) )

I use Ubuntu 20.10 (so Debian based). The issue is not on the language but a refresh one. It appears when you change language and restart darktable and only on those lines.

Indeed, the issue is also in new options in map view. See screenshot below. No issue seen elsewhere and all translation are correctly applied except those 2 parts (I could have missed another part of course). They are both related to your recent work @phweyland and it's seems to be an update of those lines that is not done.

![2021-02-19_13-29](https://user-images.githubusercontent.com/45535283/108505057-c16db300-72ae-11eb-9772-e0f14fe97194.png)

I use daily darktable in french. I have reproduced yesterday and today the issue with same steps:

1. have darktable in french
2. open preferences and set language in espanol (or deutsch)
3. restart darktable
4. see those lines always in french and the rest of the UI in the new language (espanol or deutsch)

Maybe related to something missing in the file you name: darktableconfig.xml.in?

**Comment by phweyland** [comment] 2021-02-19 14:47
>  it's seems to be an update of those lines that is not done.

Agreed.
I agree also that if there was no translation at all something is that new code would be missing.
But why it's sometimes done (even on your side) and sometimes else not done ?
The refresh of the translated part is unknown for me ... @TurboGit any direction to look for this bug ?

**Comment by phweyland** [comment] 2021-02-19 14:48
@Nilvus, have you tried to clean up build and dt folders and rebuild ?

**Comment by Nilvus** [comment] 2021-02-19 17:53
> @Nilvus, have you tried to clean up build and dt folders and rebuild ?

Always done. I compile with a script that update my clone master, remove those folders then compile master.

**Comment by TurboGit** [comment] 2021-02-19 18:09
I can reproduce too... Let me check but this seems very weird !!!!

**Comment by phweyland** [comment] 2021-02-19 18:11
Are the tooltips also impacted ?

**Comment by phweyland** [comment] 2021-02-19 18:27
Something strange. In the routines (preferences.c) to create/manage the preferences I use this for example:
`  GtkWidget *w_label = gtk_label_new(_(dt_confgen_get_label(key)));`
But in conf_gen.h we have:
`   _insert_shortdescription("ui_last/import_ignore_jpegs", _("ignore JPEG images"));`
So it seems the translation is done twice.
If that's the cause there are 2 possibilities:
- do not declare the parameter with ui = "yes" in darktableconfig.xml.in
- or do not translate in those routines (don't use _())

would that make sense ?

**Comment by TurboGit** [comment] 2021-02-19 18:36
Found, fix coming.

**Comment by TurboGit** [comment] 2021-02-19 18:40
Should be fixed now. A quite convoluted issue due to too early loafing of the confgen db.

**Closed** 2021-02-19 18:39 UTC
Labels: bug: pending, scope: UI, scope: translation, understood: clear

**Comment by Nilvus** [comment] 2021-02-19 18:59
Indeed, it's fixed. I can't reproduce. Good work!
