### ISSUE TITLE
LUA scripts using external_command like OpenInExplorer are not working in DT 4.8 (Windows)

### ISSUE THREAD

**Issue by FlorianK84** [darktable-org/darktable#17176] opened 2024-07-21 06:52 UTC
### Describe the bug

Some LUA scripts using the external_command function, such as OpenInExplorer, are not working anymore. 

### Steps to reproduce

1. Start darktable in debug mode: darktable -d lua
2. Try to open a file using OpenInExplorer
3. The logfile **%localappdata%\Microsoft\Windows\Temporary Internet Files\darktable\darktable-log.txt** shows an error: **The filename, directory name, or volume label syntax is incorrect.**
4. Checking **%temp%\run_command.bat** shows the whole batch command in quotes: **"explorer.exe /select, "C:\path\to\my\IMG.CR3""**
5. The correct command is: **explorer.exe /select, "C:\path\to\my\IMG.CR3"**
6. Disabling **command = _quote_windows_command(command)** in lib/dtutils/system.lua makes the LUA script OpenInExplorer work again

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment] 2024-07-21 09:01
Duplicate of #17408

**Closed** 2024-07-21 09:03 UTC
Labels: lua

**Comment by wpferguson** [comment] 2024-07-22 01:50
This was fixed 2 weeks ago. Your scripts should have updated automatically unless you turned it off.  If that's the case, then go into the lua directory and do a git pull.

**Comment by wpferguson** [comment] 2024-07-22 02:07
Just tested ext_editor and OpenInExplorer on 4.8.0 and both worked without error.

**Comment by FlorianK84** [comment] 2024-07-23 05:58
Autoupdate was enabled and scripts were up to date, however, _quote_windows_command was the problem. After you removed it from lib/dtutils/system, OpenInExplorer works as expected.
