### ISSUE TITLE
Crash when changing photo

### ISSUE THREAD

**Issue by halojenproductions** [darktable-org/darktable#11950] opened 2022-05-31 08:54 UTC
Unhandled exception when selecting a different photo in the film roll.

- Opened a photo in darkroom. 
- Switched to a different photo.
- Crash.

`darktable.exe caused an Access Violation at location 00007FF8681D13F4 in module libmodulegroups.dll Reading from location FFFFFFFFFFFFFFFF.`

The photo I'm switching to happens to be the last photo on the film roll -- I'm not sure if that's relevant.
It seems to be only crashing when opening that one particular photo.
Total of four photos in this set.
I've had this a few times in the past but I'm not if it was always the last photo. 
This time it's reproducible, which is why I'm logging it.
I can open the offending photo from lighttable, but if I switch to the previous photo and then to this one again, it'll crash.
It crashes whether I use the mouse or the keyboard.

darktable 3.8.1 on Windows 10
.CR2
log attached.
[darktable_bt_BON4M1.txt](https://github.com/darktable-org/darktable/files/8803636/darktable_bt_BON4M1.txt)

**Comment by emko** [comment] 2022-06-20 01:59
i get this same problem on linux side

Thread 1 "darktable" received signal SIGSEGV, Segmentation fault.
0x00007fff9da83c65 in ?? () from /app/lib/darktable/plugins/lighttable/libmodulegroups.so

**Comment by emko** [comment] 2022-06-20 02:40
tested out latest master this problem does not happen anymore

**Comment by ptilopteri** [comment] 2022-06-20 03:22
if the problem is no more, please close this issue.

**Closed** 2022-06-21 21:28 UTC
