### ISSUE TITLE
Header Info Line Dissappears When Collapsing A Module In Darkroom.

### ISSUE THREAD

**Issue by darkelectron** [darktable-org/darktable#4242] opened 2020-02-06 18:33 UTC
**Describe the bug**

In darkroom, whenever I collapse any module the header info line(# image of #...) will disappear until I continue to another photo or single click a photo in the filmstrip.

**To Reproduce**

1. open a photo in darkroom
2. make sure the header info line is visible(the darktable logo should be visible)
3. expand any module and then collapse it

**Expected behavior**

Info line does not disappear.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0 
 - OS: Archlinux 
 - 
 - 

**Additional context**

Current Workaround: single click a photo in the filmstrip refreshes the info line.

**Comment by Nilvus** [comment] 2021-01-17 22:06
Can't reproduce on last master (so 3.4 also) in Linux. So I close this issue. Feel free to reopen with more infos if your reproduce the issue in last darktable release.

**Comment by ralfbrown** [comment] 2021-01-18 06:28
It's still present in current master on Linux.  I had actually looked into this in 3.1.0-something but somehow never got around to trying for an actual fix.    There are various places where the hinter message is unconditionally set to the empty string, including in `dt_iop_request_focus` which gets called when a module loses focus, either because another gains focus or it is collapsed.  The correct behavior would be to restore the default message.

A quick `git grep` also shows unconditional clearing in liquify.c (multiple occurrences), toneequal.c, and blend_gui.c (two occurrences).

To reproduce:
1. Open an image from the lighttable by double-clicking or by selecting one image and pressing `D`.
2. In darkroom, notice the hinter message "1 image of NN (#NN) in current collection is selected" above the center view (expand the top info bar if necessary)
3. Open any processing module, even one that doesn't use hinter messages, such as Exposure.
4. Close that module.
5. Notice that the hinter message has disappeared.
6. To get the hinter message to reappear, you need to switch to another image and back or to lighttable and back.

**Comment by Nilvus** [comment] 2021-01-18 08:36
My bad, indeed now I can reproduce. So good to see a fix for that.

**Closed** 2021-01-18 18:36 UTC
Labels: bug: wip, reproduce: confirmed, scope: UI
