### ISSUE TITLE
Color picker sample hovering window is cropped

### ISSUE THREAD

**Issue by lbilli** [darktable-org/darktable#9908] opened 2021-08-31 12:37 UTC
When hovering on a color picker sample a window pops up with color details.
More often than not that window is too narrowly cropped as shown here:

![ss1](https://user-images.githubusercontent.com/12815378/131501107-97dc2bc9-d6db-4c9a-89be-40b686917045.png)

Occasionally, the full view is displayed:

![ss2](https://user-images.githubusercontent.com/12815378/131501251-bed41ad5-d6f4-4746-9eea-4b491f9b62f7.png)

The behavior does not appear to be entirely deterministic with the cropped version being the one appearing the vast majority of the times.

dt: 3.7.0~git899.a8833f00f9 provided by openSUSE
distro: openSUSE Tumbleweed
graphic: Integrated Intel
openCL: no
desktop: Plasma/KDE

**Comment by Mark-64** [comment] 2021-08-31 13:35
Can't reproduce in Windows 10 with current git master. I tried 100 times, never have a crop windows

**Comment by jade-nl** [comment] 2021-08-31 14:37
I can confirm this.

* darktable 3.7.0+920~g20124fb31 **and** darktable 3.6.0
* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Comment by Nilvus** [comment] 2021-08-31 19:44
This is probably more related to Gtk than darktable. We have seen some similar glitches in combobox position or such things with different behavior regarding Gtk version used. So probably something that couldn't be fixed by darktable team.

I can't reproduce too on my side and never had cropped window too here (and nothing elsewhere in darktable). I'm using last master on Ubuntu 21.04 (Gtk 3.24.30).

Having some that can reproduce and some that can't like @Mark-64 or me here let me go to Gtk issue than darktable one.

@lbilli and @jade-nl: could you check and post here which Gtk3 release you have?

**Comment by lbilli** [comment] 2021-08-31 20:19
Gtk: 3.24.30

Also, same behavior with a fresh configdir.

**Comment by lbilli** [comment] 2021-08-31 20:34
A little insight: while experimenting it looks like the font size might play a role.

After unchecking "use system fonts", which I usually keep checked, the buggy behavior persists when the font size is 9 or 10 but disappears for 11 or 12.

**Comment by Nilvus** [comment] 2021-08-31 21:02
> After unchecking "use system fonts", which I usually keep checked, the buggy behavior persists when the font size is 9 or 10 but disappears for 11 or 12.

Good catch, I can reproduce too now with a small font. Quite strange. I doubt this could be fixed by CSS. I can't check Gtk settings with Gtk Inspector Tool for such popover but I tested to set margin/padding and min-width without any changes. Maybe this is fixed in Gtk code.

@Mark-64: maybe ou will have an idea here on how to fix that. Or @dterrahe as I remember you work recently on color picker module?

**Comment by jade-nl** [comment] 2021-09-01 06:08
@Nilvus 

> could you check and post here which Gtk3 release you have?

* Gtk+          : 3.24.5-1

To be complete:

Also confirmed: I have *use system font size checked*. Turning it off and having a font size set to 11 or higher does solve the problem. Setting a lower size triggers this again.

**Comment by Nilvus** [comment] 2021-09-01 07:51
@jade-nl: it's not about having system font size checked. It's always checked on my side and I don't have the issue. It's all about small font size.

**Comment by Mark-64** [comment] 2021-09-01 07:57
I believe I am onto something, it seems to be signal mishandling, as the callback _sample_tooltip_callback() in colorpicker.c is called multiple times when moving the mouse on the sample.
I will now try to find a fix.

**Comment by dterrahe** [comment] 2021-09-01 08:01
For me it only seems to happen when the picker tooltip textview widget gets created. Internally, the textview is kept around between different tooltips popups until gtk decides to destroy it and then a new one is created next time. So what I suspect is that if the markup text is inserted immediately after the view was created, but before it is realised by the tooltip code, gtk forgets that it still needs to correctly size the view. But only if the font size is small. This reminds me a little of the spinbox crash we had a little while ago where pango messed up for certain fonts. So I suspect this to be a gtk bug/regression and maybe somebody should bisect gtk and report it there. But I'm trying to find a quick workaround. If it gets too dirty, I will give up though and wait till gtk fixes this.

For me, if I move between two colorpicker tooltips, the problem fixes itself. i.e. if the same tooltip is reused and has its markup inserted after it was already realized by a previous call, then it works correctly.

**Comment by Mark-64** [comment] 2021-09-01 08:07
Yes.
changing to this

```
static gboolean _sample_tooltip_callback(GtkWidget *widget, gint x, gint y, gboolean keyboard_mode,
                                         GtkTooltip *tooltip, const dt_colorpicker_sample_t *sample)
{
  static GtkWidget *view;
  gboolean res = FALSE;

  if(!view)
  {
    const gchar *name[] = { N_("mean"), N_("min"), N_("max") };

    gchar **sample_parts = g_malloc0_n(12, sizeof(char*));

    sample_parts[3] = g_strdup_printf("%22s(0x%02X%02X%02X)\n<big><b>%14s</b></big>", " ",
                                      sample->rgb_vals[0], sample->rgb_vals[1], sample->rgb_vals[2], _("RGB"));
    sample_parts[7] = g_strdup_printf("\n<big><b>%14s</b></big>", _("Lab"));

    for(int i = 0; i < 3; i++)
    {
      const dt_aligned_pixel_t *rgb_disp = (i == 0) ? &sample->picked_color_display_rgb_mean :
                                           (i == 1) ? &sample->picked_color_display_rgb_min
                                                    : &sample->picked_color_display_rgb_max;
      const dt_aligned_pixel_t *rgb_hist = (i == 0) ? &sample->picked_color_rgb_mean :
                                           (i == 1) ? &sample->picked_color_rgb_min
                                                    : &sample->picked_color_rgb_max;
      const dt_aligned_pixel_t *lab = (i == 0) ? &sample->picked_color_lab_mean :
                                      (i == 1) ? &sample->picked_color_lab_min :
                                                 &sample->picked_color_lab_max;

      sample_parts[i] = g_strdup_printf("<span background='#%02X%02X%02X'>%32s</span>",
                                        (int)roundf(CLAMP((*rgb_disp)[0], 0.f, 1.f) * 255.f),
                                        (int)roundf(CLAMP((*rgb_disp)[1], 0.f, 1.f) * 255.f),
                                        (int)roundf(CLAMP((*rgb_disp)[2], 0.f, 1.f) * 255.f), " ");

      sample_parts[i + 4] = g_strdup_printf("<span foreground='#FF7F7F'>%6d</span>  "
                                            "<span foreground='#7FFF7F'>%6d</span>  "
                                            "<span foreground='#7F7FFF'>%6d</span>  %s",
                                            (int)roundf((*rgb_hist)[0] * 255.f),
                                            (int)roundf((*rgb_hist)[1] * 255.f),
                                            (int)roundf((*rgb_hist)[2] * 255.f), _(name[i]));


      sample_parts[i + 8] = g_strdup_printf("%6.02f  %6.02f  %6.02f  %s",
                                            (*lab)[0], (*lab)[1], (*lab)[2], _(name[i]));
    }

    gchar *tooltip_text = g_strjoinv("\n", sample_parts);
    g_strfreev(sample_parts);

    view = gtk_text_view_new();
    gtk_widget_set_name(view, "colorpicker-tooltip");
    g_signal_connect(G_OBJECT(view), "destroy", G_CALLBACK(gtk_widget_destroyed), &view);

    GtkTextBuffer *buffer = gtk_text_view_get_buffer(GTK_TEXT_VIEW(view));
    gtk_text_buffer_set_text(buffer, "", -1);
    GtkTextIter iter;
    gtk_text_buffer_get_start_iter(buffer, &iter);
    gtk_text_buffer_insert_markup(buffer, &iter, tooltip_text, -1);
    gtk_tooltip_set_custom(tooltip, view);

    res = TRUE;
    g_free(tooltip_text);
  }

  return res;
}
```
the problem disappears, but detection of mouse-over becomes a bit unreliable...

**Comment by dterrahe** [comment] 2021-09-01 08:17
> but detection of mouse-over becomes a bit unreliable...

That's because you now only produce an updated tooltip when gtk destroyed the previous one. But gtk tries to keep those around (to be able to deal with frequent updates) so it only sporadically deletes them.

> the problem disappears

That is interesting though, because I thought the problem only occured when the widget was just created, but you _always_ just create the widget...

So maybe (I'm just speculating) the problem occurs when the widget gets _updated_ before it has been shown...

**Comment by dterrahe** [comment] 2021-09-01 08:24
If I connect this
```
static void _map_tooltip(GtkWidget *widget, gpointer user_data)
{
  gtk_widget_queue_resize(widget);
}
```
using
`    g_signal_connect(G_OBJECT(view), "map", G_CALLBACK(_map_tooltip), &view);
`
(immediately after `gtk_widget_set_name`) the problem also seems to go away. Please verify!

**Comment by jade-nl** [comment] 2021-09-01 08:50
@Nilvus 

> it's not about having system font size checked. It's always checked on my side and I don't have the issue.

That makes it even more interesting: I have the system font size checked (always have, just temporarily turned it off to check the font size thing) and I **DO** have this issue.

**Comment by Mark-64** [comment] 2021-09-01 08:54
@dterrahe Yes this workaround does the trick.

**Comment by Mark-64** [comment] 2021-09-01 09:04
@dterrahe I can file a bug in Gtk.
Do you propose a PR or you want me to do it?

**Comment by dterrahe** [comment] 2021-09-01 09:13
Simply calling `gtk_widget_map(view);` _after_ `gtk_tooltip_set_custom(tooltip, view);` also works, for me.

I assume that means set_custom adds it to an already existing window, because if you call map too early it crashes (as the documentation predicts) ...

If that works for you as well, I'm happy for you to submit a PR.

**Comment by Mark-64** [comment] 2021-09-01 10:20
Yet it works. PR coming.
Do you still believe we have to open a Gtk bug?

**Comment by dterrahe** [comment] 2021-09-01 10:49
> Do you still believe we have to open a Gtk bug?

I believe so because I don't think we should ever have to call gtk_widget_map. Maybe gtk_widget_show/_all, but that doesn't help. And it is strange that it works fine for bigger font sizes but not small ones.

If someone feels like bisecting gtk (or trying with an old version) then we could verify if it used to work before and therefore if it is a regression there. I haven't seen this bug before, but can't guarantee that I ever tested with small fonts.

On the other hand, we seem to have a working workaround...

BTW: exact same fix is required in history.c !

**Closed** 2021-09-02 11:17 UTC
Labels: understood: clear, reproduce: confirmed, scope: UI, bug: pending
