### ISSUE TITLE
FR: Have a way to disable modules from running on OpenCL

### ISSUE THREAD

**Issue by hatsunearu** [darktable-org/darktable#5669] opened 2020-06-30 02:01 UTC
**Is your feature request related to a problem? Please describe.**
Considering issues like #3756, I feel that a global "turn off all OpenCL" is not too fine grained enough. I'm wondering if it is possible to blacklist certain problematic modules from running on OpenCL. 

**Describe the solution you'd like**
A button in the preset menu that has a check mark that lets you blacklist a module from running on OpenCL, falling back to the CPU implementation. This could also be used to communicate that there is no OpenCL implementation available.

It could also be done on a global module basis, not a module instance basis, by putting this info in the settings panel.

**Comment by coffeeandspaceships** [comment] 2020-06-30 18:41
Can you give an example of a problematic module? In the forthcoming 3.2 there is now a test suite to help with the risk that OpenCL results and CPU results might differ, and any new modules will have to pass this test. There's been quite a bit of troubleshooting of existing modules as @ralfbrown works through improving performance.

I guess this might be a good feature to have until all OpenCL regressions have been found and fixed but it does feel a bit like fixing the wrong problem...

**Comment by hatsunearu** [comment] 2020-06-30 19:48
#3756 is a great example. It's an upstream issue that AMD is pretty much saying "whatever lol" and we can't workaround here, except my proposal which is a user-defined blacklist of modules.

And I wouldn't give a damn if it were some deprecated thing like tone mapping but it's local contrast which is very popular.

**Comment by coffeeandspaceships** [comment] 2020-06-30 20:33
Great point. I'd forgotten how fragile some of the OpenCL drivers are in *unpredictable* ways that neither the poor customer who bought that card or the darktable team can have any control over!

In fact this might even help with the block list for certain cards; instead of blocking a card because it misbehaved once on one person's machine, the source tree could still maintain a block list but you could then opt to over-ride it using your feature. So OpenCL could then be
- on by default
- off by default on a narrow selection of chipsets that are known to be particularly bad news
- fully controllable to be on or off, whichever way the default is

**Comment by hatsunearu** [comment] 2020-06-30 20:39
> Great point. I'd forgotten how fragile some of the OpenCL drivers are in unpredictable ways that neither the poor customer who bought that card or the darktable team can have any control over!

Tell me about it... ROCm sucks for anything other than ML. AMD dropped support for using the CPU as an OpenCL device too.

> In fact this might even help with the block list for certain cards; instead of blocking a card because it misbehaved once on one person's machine, the source tree could still maintain a block list but you could then opt to over-ride it using your feature. So OpenCL could then be

Probably a good idea--making an auto block list would be cool, but that's kind of a feature creep. A manual block mechanism would be good enough to be honest. 

I mean, just think about how complex that would have to be, it would have to read what device it is using, what driver it is using, and a whole bunch of stuff.

**Comment by coffeeandspaceships** [comment] 2020-07-02 21:19
> I mean, just think about how complex that would have to be, it would have to read what device it is using, what driver it is using, and a whole bunch of stuff.

Agreed, but I'd say it's a bit too far in the other direction now; the blocklist is *compiled in*, not configured at runtime, and includes entire classes of chipset/OS combinations blocking mature, stable, and performant drivers on the basis of one or two adverse reports on early versions of the drivers. For example, Neo Intel on Windows is blocked, yet RocM which is considerably more troublesome is NOT blocked.

That makes me think of another possible "halfway house" - move from using a compiled-in list (change header file and recompile) to having a configuration file shipped by default with the same list, maintained with the same somewhat too high granularity as it is now. Given the complex OpenCL config you can already carry out by changing config files it doesn't seem unreasonable to expose the short blocklist and allow end users to change it if they want. Thoughts?

**Comment by hatsunearu** [comment] 2020-07-02 21:23
I think an actual list is a bad idea. I'm gonna change the title. I really meant "add a way to disable OpenCL for certain modules on *my machine*".

Maintaining the list will need to become a full time job. That's no good.

**Comment by aurelienpierre** [comment] 2020-07-02 22:16
I have been thinking about that for some time. You need to add a Gtk checkbox in the module hamburger menu that sets `(dt_dev_pixelpipe_iop_t *piece)->process_cl_ready = TRUE | FALSE`.

**Comment by jenshannoschwalm** [comment] 2020-07-06 11:51
> You need to add a Gtk checkbox in the module hamburger menu ...

Is this really a good idea? Even more menu specific options? (I know about suspected cl problems for specific modules)

It might lead to user problems and thus raised issues but wouldn't a preferences/opencl-issues submenu be the better way?

**Comment by rabauke** [comment] 2020-07-10 20:26
> It might lead to user problems and thus raised issues but wouldn't a preferences/opencl-issues submenu be the better way?

Considering that disabling OpenCL for a particular module globally would affect all pixel pipes (including those for thumbnails and dia show), I would also prefer an additional preferences submenu over a checkbox in the module's hamburger menu in the darkroom view. Having this option in the module's hamburger menu would mean that you have to pic an _arbitrary_ image and open it in the darkroom view to modify the setting. Such a solution feels not very intuitive to me.

**Comment by SaltyBet** [comment] 2020-07-21 00:49
> #3756 is a great example (the module in question is local contrast). It's an upstream issue that AMD is pretty much saying "whatever lol" and we can't workaround here.

FWIW, [AMD is actively working on a fix](/RadeonOpenCompute/ROCm-OpenCL-Runtime/issues/103#issuecomment-660136723).

**Comment by MStraeten** [comment] 2021-08-17 13:05
bringing this back to life ;)

after running several performance measurements on different images on two machines with different cpu and gpu power i found that some module benefit from gpu processing but others doesn't or are quite slower if using gpu. This is depending on the system configuration, so there's no "one size fits all"

So being able to customize the use of opencl per module can be useful to tweak performance:
- if cpu is faster in general - just enable opencl for the modules that will benefit
- if gpu is faster in general - just disable opencl for the modules where opencl results in a noticeable slow down

**Describe the solution you'd like**
1. extend module code to perform opencl processing according to a user customization
2. use darktablerc for a per module customization e.g. 
`plugins/darkroom/filmicrgb/opencl=false` 
or a separate opencl section
`opencl/filmicrgb/opencl=false `
that will evaluated on run time (default: true if opencl is enabled in general;  --disable-opencl or `opencl=FALSE` in darktablerc overrides these settings)

**Alternatives**
in case gpu is faster in general the user can delete the opencl kernel that slows down the processing ;)

The discussion here went into reasoning about some automatic stuff depending on chipsets. But thats too much 'one size fits all' approach.
I even don't see it in an per module hamburger menu option, since  it's not straightforward to identify what needs to be tweaked. It doesn't make sense to tweak per image - since tweaking will cost more time than the optimized configuration will save on processing.
But if there's a noticeable effect in general (e.g. low variance of logged processing times) it might make sense to be able to customize this. It's not about getting the best possible processing time but even a better over all performance (which may be even worse in a few cases).

**Comment by luator** [comment] 2022-08-31 10:02
Just bumping to prevent the bot from closing it, as I think it's still relevant.
I recently noticed that while most modules benefit from OpenCL, the diffuse or sharpen module takes much (~10 times) longer on my (relatively old) GPU compared to the CPU.  So an option to selectively disable OpenCL for that module would be really cool.

**Comment by jenshannoschwalm** [comment] 2022-11-07 15:25
There has been #12545 for this problem.

**Comment by darkbasic** [comment] 2022-11-21 16:36
> ROCm sucks for anything other than ML

Fortunately you won't have to use ROCm for long: RustiCL is going to support radeonsi very soon.

> So being able to customize the use of opencl per module can be useful to tweak performance:
if cpu is faster in general - just enable opencl for the modules that will benefit
if gpu is faster in general - just disable opencl for the modules where opencl results in a noticeable slow down

I think we can do better: benchmark each and every module and enable OpenCL for those who are faster than CPU.

**Comment by jenshannoschwalm** [comment] 2022-11-21 18:38
> I think we can do better: benchmark each and every module and enable OpenCL for those who are faster than CPU.

That's not a good idea for many reasons. dt is a much more complex beast than a simple benchmark. If you really want to dig into this, read discussion and maybe even source of #12545, that's exactly about this topic.

**Closed** 2024-03-21 00:17 UTC
Labels: feature: redesign, difficulty: hard, scope: UI, scope: image processing, scope: hardware support, no-issue-activity
