### ISSUE TITLE
ILCE-7CM2  (Sony a7C mk2)

### ISSUE THREAD

**Issue by benkyd** [darktable-org/darktable#15656] opened 2023-11-14 14:41 UTC
No support for new Sony A7Cii, With guidance can patch if needed
![image](https://github.com/darktable-org/darktable/assets/36240171/016d1aa3-d62d-4f6a-8939-8cdcbbe2fd85)
![image](https://github.com/darktable-org/darktable/assets/36240171/201899c5-10ae-4e9d-83bf-9e69d77aa32d)

**Comment by kmilos** [comment] 2023-11-14 14:57
Duplicate of https://github.com/darktable-org/darktable/issues/15521

Please search before opening new issues.

**Closed by kmilos** 2023-11-14 14:57 UTC
Labels: scope: camera support

**Comment by benkyd** [comment] 2023-11-14 15:03
> Duplicate of #15521
> 
> Please search before opening new issues.

Apologies, GitHubs search is terrible, I searched for A7CII and also ILCE7CM2 and found nothing!
