### ISSUE TITLE
Lighttable - Selecting and deselecting images in dynamic zoom culling mode is confusing

### ISSUE THREAD

**Issue by jobec** [darktable-org/darktable#5991] opened 2020-08-16 18:10 UTC
**Describe the bug**

In the culling -> dynamic zoom of the lighttable, selecting images works in a weird way. `Ctrl + click` is the only way to select **and deselect** images.

* Single clicking an image does not select it.
* `shift+click` doesn't select a range of images
* After having a a few images selected, the only way to deselect them is by `ctrl+click` on every one of them. While you would expect clicking a random other image to undo the selection.

**Expected behavior**

Like a file manager. meaning:

* Single click select just that image and undoes whatever was already selected.
* `ctrl + click` adds an image to the selecting
* click on an image => `shift + click` on another one adds both images an all of them in between to the selection
* `shift + arrow-key` expands the selecting in the direction of the arrow key.

That way of working would even make the fixed and dynamic zoom modes obsolete.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Linux Mint 19.4

**Comment by AlicVB** [comment] 2020-08-20 09:37
Yep, that's by design : any select-unselect action in filmstrip require the use of a controller key. To achieve what you want you need to use alt-click (note that on some WM, alt-click is grabbed by the WM, so you may have to disable that)
We know that it's not really discoverable, especially because the docs are currently under reconstruction, so new features have not been documented yet.

The reason behind is to never change the selection in the back of user, and this is what will happen with filmstrip if you want to switch to another image by clicking on its thumbnail...



> That way of working would even make the fixed and dynamic zoom modes obsolete.

absolutely not. I think you have missed the point of dynamic mode here ;)

I'm closing as invalid for now, but thanks for the report anyway !

**Closed by AlicVB** 2020-08-20 09:37 UTC

**Comment by TurboGit** [comment] 2020-08-23 16:59
@jobec: you need to understand that on the filmstrip a single-click select the image for the darkroom. So to select a single one, or a range without opening it in the darkroom it is required to use other ways for the selection. Hence the Ctrl or Shift modifiers, at then end we do not try to confuse users, we do our best to provide a good experience.
