### ISSUE TITLE
Language setting do not affect timestamps in the image information panel

### ISSUE THREAD

**Issue by leonwulf** [darktable-org/darktable#5883] opened 2020-08-07 14:34 UTC
**Describe the bug**

I use a self-compiled version of darktable on macOS. In the current master as well as previous versions I noticed that I get timestamps with a wrong format in the image information panel. For example: `六 2020/06/27 21時44分47秒`

My system language and the language in darktable are set to English. Changing the language in the darktable settings does not affect the timestamp.

I tried to analyse the bug a little further:
The timestamp is generated using `strftime` here: [src/libs/metadata_view.c#L296](https://github.com/darktable-org/darktable/blob/master/src/libs/metadata_view.c#L296).
The formatting depends on the current locale, so I inserted a few lines of debug code:
Both `setlocale(LC_ALL, NULL)` and `setlocale(LC_TIME, NULL)` return `zh_TW`.

My environment variables are as follows:

```sh
$ env | grep LC
LC_CTYPE=UTF-8
$ locale       
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**To Reproduce**

Run darktable on macOS from the command line:
```sh
GSETTINGS_SCHEMA_DIR=/opt/local/share/glib-2.0/schemas/ \
XDG_DATA_DIRS=/opt/local/share \
/opt/darktable-master/bin/darktable \
--configdir ~/.config/darktable-master \
--cachedir ~/.cache/darktable-master
```

**Expected behavior**

The timestamp format should match the language setting.

**Platform:**
 - Darktable Version: current master
 - OS: macOS 10.15.6

**Comment by ptilopteri** [comment] 2020-08-07 15:12
perhaps you have too much set in env which is not necessary

env | grep LC
yields nothing

/opt/darktable/bin/darktable 
[init] moving database into new XDG directory structure
toplevel (function)


but I am on linux (openSUSE Tumbleweed) and have no idea
about any macOS.

ps: "current master" as a version is a moving target and not really 
describing your environment.

**Comment by leonwulf** [comment] 2020-08-07 15:39
Thank you for the reply!
I think my environment variables are just the defaults from macOS. I just wanted to show that I have not set `LC_ALL=zh_TW`.

Could you test if the timestamp format changes if you switch to another language in the settings?
So instead of `Fri 08/07/20 17:33:31` it should say `Ven 07.08.2020 17:33:38` if you switch to french.

**Comment by ptilopteri** [comment] 2020-08-07 15:47
I do not have any *-lang packages installed as I have no need.  Why don't you try:
  "export LC_ALL=en_US.UFT-8 LANG=en_US.UFT-8 darktable"
and see if that changes your display.

**Comment by leonwulf** [comment] 2020-08-07 15:53
Running darktable with export LC_ALL=en_US.UFT-8 LANG=en_US.UFT-8` did not make a difference.

**Comment by parafin** [comment] 2020-08-07 16:40
Locale settings on macOS are somehow different from Linux, but I don't know in which way. Language preferences affect locale settings unpredictably since there is some mismatch going on between POSIX standard and macOS implementation. There was a start script from gtk-mac-bundler which dealt with some of these peculiarities, but updates to macOS security checks makes it impossible to use, so DMG package now exposes these issues the same as manually build version. I don't know how it should work so I haven't tried reproducing the effects of the script in C code.

**Comment by leonwulf** [comment] 2020-08-11 17:31
I found the script that you mentioned: https://github.com/darktable-org/darktable/blob/f4b7b5593551bfae59fdeb9f9a9830101428773e/packaging/macosx/darktable-cli.sh
As far as I can tell, its task is to set `LANG`,  `LC_MESSAGES` and  `LC_COLLATE`.
I just tested in version 3.2.1 and they have no effect on the timestamps.
The only environment variable that made a difference is `LC_ALL`. I think I made a mistake somewhere, when testing this previously.
Now `LC_ALL` determines the formatting of the timestamp consistently.

Another observation I made: On the release tag, the timestamp format is `pt_BR` and on the master branch it is `zh_TW`, if you don't set `LC_ALL`.

My question is: What do you think should be the correct behaviour?
The timestamp locale should be determined by:
a) Your environment settings (`LC_ALL`)
b) The language settings of darktable

**Comment by johnny-bit** [comment] 2020-09-11 10:32
@leonwulf - can you check how it works on current master? @parafin merged some change that should generally help with this case.

**Comment by parafin** [comment] 2020-09-11 15:06
My commit fixed locale being zh_TW, I think it now sticks to C, so dates are always in english, whatever the chosen language in the preferences. Setting LC_ALL on the other hand affects the date format as expected. I'm investigating this issue.

**Closed** 2020-09-12 20:53 UTC
Labels: bug: wip, difficulty: trivial, priority: low, reproduce: confirmed, scope: OS support, understood: clear
