### ISSUE TITLE
Unhanded Exception

### ISSUE THREAD

**Issue by spoung45** [darktable-org/darktable#2599] opened 2019-05-20 01:33 UTC
**Describe the bug**
Darktable crashes on start

**Expected behavior**
The program to open.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 2.6.2

**Additional context**
[darktable_bt_XMJF2Z.txt](https://github.com/darktable-org/darktable/files/3195952/darktable_bt_XMJF2Z.txt)

**Comment by peterbud** [comment] 2019-05-20 05:27
Your AMD OpenCL driver is either outdated or wrong. 
Pls read: https://www.darktable.org/about/faq/#faq-windows-opencl and follow the instructions there to check your OpenCL setup. Alternatively start draktable without opencl as described here: https://www.darktable.org/usermanual/en/darktable_and_opencl_still_fubar.html

**Comment by spoung45** [comment] 2019-05-22 00:18
This is the graphics specs. don't see how to not get it to run with open CL.

Graphics Card Manufacturer - Powered by AMD
Graphics Chipset - AMD Radeon(TM) Vega 8 Graphics
Device ID - 15DD
Vendor ID - 1002
SubSystem ID - 8535
SubSystem Vendor ID - 103C
Revision ID - C4
Bus Type - PCI
Current Bus Settings - PCI
BIOS Version - 016.002.000.006
BIOS Part Number - 113-RAVEN-107
BIOS Date - 2018/03/13 16:07
Memory Size - 1024 MB
Memory Type - DDR4
Memory Clock - 400 MHz
Core Clock - 201 MHz
Total Memory Bandwidth - 12 GByte/s
Memory Bit Rate - 0.80 Gbps
2D Driver File Path - /REGISTRY/MACHINE/SYSTEM/CurrentControlSet/Control/Class/{4d36e968-e325-11ce-bfc1-08002be10318}/0000
OpenGL® API Version - 4.6
OpenCL™ API Version - 2.0

**Comment by peterbud** [comment] 2019-05-24 07:52
@spoung45 , if you don't read 2 paragraphs at the link I have provided, then I believe there is no point on opening an issue.

**Comment by spoung45** [comment] 2019-05-24 13:05
I have read the link how to the how to dossable Open CL. Where is the option to disable Open CL? Nowhere do I see an option to disable Open CL in the properties tabs of the program. The Open CL test gives the same error.

This is the latest driver from AMD, downloaded from their website 3 days ago. On brand new 2 week old laptop.

**Comment by peterbud** [comment] 2019-05-24 20:45
Quote:
>  As has been said before OpenCL systems come with a huge variety of setups: different GPU manufacturers, different GPU models, varying amounts of GPU memory, different drivers, different distributions etc. Many of the potential problems will only appear with a very specific combination of those factors.
As we developers of darktable on our computers only have access to a small fraction of those variations, please understand that we might not be able to fix your specific problem. There is not much we can do, if there is no way for us to reproduce.
If nothing else helps, the best option might be to start darktable with
**darktable --disable-opencl**

**Comment by johnny-bit** [comment] 2020-12-22 13:31
've checked around and the problem is (or rather was) caused by buggy AMD drivers. The problem affected not only darktable, but other opencl apps, such as luminar or some adobe stuff.

Duplicate of #2562

**Closed by johnny-bit** 2020-12-22 13:31 UTC
Labels: no-issue-activity
