### ISSUE TITLE
iphone<Enter your camera name here>

### ISSUE THREAD

**Issue by kpstuhr** [darktable-org/darktable#9139] opened 2021-06-02 21:27 UTC
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by Nilvus** [comment] 2021-06-03 14:34
You precise nothing here. What's your issue? Except iphone in title, we have nothing. Please update title and amend your post.

**Comment by johnny-bit** [comment] 2021-06-03 19:38
If it's for RAW files it might be a duplicate of #7578
If it's for HEIF files it might be a duplicate of #4989 which could be solved by #8800

Closing :) please track mentioned issues or fill new issue follwing full [Camera Support Guide](https://github.com/darktable-org/darktable/wiki/Camera-support)

**Closed** 2021-06-03 19:43 UTC
Labels: scope: camera support, understood: unclear
