### ISSUE TITLE
Importing single jpeg potrait image crashes  darktable (win64)

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#2982] opened 2019-09-24 04:42 UTC
**Describe the bug**
Importing a single jpg portrait image crashes the app. Next time reopening app will have the pic in it at times or will be displaying pics from the previous film roll that was active prior to import.
It's not an issue with landscape pics.
It's not an issue when you import a folder with raws and jpgs. Except when you double click on the portrait to edit and the app dies.
It's not an issue when you import the single raw file for the portrait jpg.
Only issue when you import the portrait jpg or import folder and double click on the imported portrait JPEG.

On restarting after crash, the imported folder is visible, but images don't show up and that folder cannot be removed. (folder 24092019 in image).
![image](https://user-images.githubusercontent.com/1119439/65483616-82211400-deba-11e9-8fc4-e765fb98acb5.png)

**Platform (please complete the following information):**
 - OS: Win10 
 - Version :darktable-2.7.0+1804~g9819978c2-win64

**Comment by leclercj** [comment] 2019-09-24 05:16
I'm using the exact same 2.7.0+1804~g9819978c2 on Win7 and I can reproduce. No specific error message in the console.
The same operation with a portrait picture in raw format is working fine.

**Comment by chhil** [comment] 2019-09-24 05:23
> I'm using the exact same 2.7.0+1804~g9819978c2 on Win7 and I can reproduce. No specific error message in the console.

I run it with "C:\Program Files\darktable\bin\darktable.exe" -d all and C:\Users\chill\AppData\Local\Microsoft\Windows\INetCache\darktable\darktable-log.txt is empty.

**Comment by TurboGit** [comment] 2019-09-24 08:00
I cannot reproduce this on Linux.

**Comment by phweyland** [comment] 2019-09-24 16:40
=> dt_free_align issue in imageio_jpeg.c. Preparing a fix.

@TurboGit is there a way to instruct developers under Linux to make sure that a dt_alloc_align() is followed by a dt_free_align() instead of free() (as letting free() is not an issue on Linux) ?

**Comment by parafin** [comment] 2019-09-24 17:09
Well. for debugging you could allocate a little bit more memory in dt_alloc_align, return pointer shifted by that amount and undo the shift in dt_free_align. Then ordinary free will crash. Obviously it's not a good idea for normal release build. Otherwise I don't think it's possible.

**Comment by phweyland** [comment] 2019-09-24 17:15
sorry, I may have not been clear enough. dt_free_align() works perfectly. But I see more and more usage of dt_alloc_align() coming (malloc changed to dt_alloc_align()) but free() is not changed to dt_free_align(), making windows crash without message.
Under Linux free() works fine, so the person making the change doesn't detect the issue created on windows. So I was wondering if there were a mean to inform Linux people to make both (dt_alloc_align and dt_free_align) changes at once.

**Comment by parafin** [comment] 2019-09-24 17:28
That's what I proposed, they will be informed by dt crashing;) (given that they try to use debug build)

**Comment by phweyland** [comment] 2019-09-24 17:38
This time I've understood ! :)

**Closed** 2019-09-24 20:20 UTC
Labels: bug
