### ISSUE TITLE
Some buttons not working on macOS + darktable v3.8

### ISSUE THREAD

**Issue by tomtomtls** [darktable-org/darktable#10876] opened 2022-01-12 22:09 UTC
**To Reproduce**
1. Go to 'Darkroom'
2. Click on 'Presets' (or Ctrl + Click)
3. Create a new preset or duplicate one (same behaviour)
4. Try to add a widget to Quick Settings or a module to a group
5. The "+" button do not open the list where one should select the widget or module

Other context / same behaviour regarding another button
1. Go to 'Darkroom'
2. Click on the arrow at the bottom of the screen to show/hide thumnails
3. Nothing happens
4. Use the Shift + Cmd + b shortcut 
5. Thumbnails are shown or hidden as expected

**Expected behavior**
First case: a list with modules or widgets should allow the user to choose an item to be added to Quick Settings or another group
Second case: thumnails are supposed to be hidden when the button / arrow is clicked

**Screencast**
https://mesphotosetvideos.fr/CannotAddWidgetorModule.mov

**Which commit introduced the error**
I am using darktable v3.8 as a fresh installation (not an update)

**Platform**

* darktable version : 3.8 and another set of tests with 3.8.0+59_ge758e1366
* OS                : OSx Big Sur 11.6.2
* Memory            : 16 Go
* Graphics card     : Intel UHD Graphics 617 1536 Mo
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
 - Can you reproduce with another darktable version(s)? yes with version 3.6.1 also installed from scratch ; same behaviour on 2 different Mac hardware (MBA 2019 / Mac mini)
 - Can you reproduce with a RAW or Jpeg or both? both
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes
 - Do you use lua scripts? no
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by tomtomtls** [comment] 2022-01-14 21:33
More details: I just managed to launch DT in debug mode to catch info. And... the menu widget menu was almost accessible: can you see it behind the module window? (!)

<img width="415" alt="Capture d’écran 2022-01-14 à 22 16 23" src="https://user-images.githubusercontent.com/34109191/149587864-c1b75220-cd06-4e48-a929-0e9e1289de5e.png">

Not sure if it is linked to the problem since I could not reproduce it for the moment, but launching the app in debug mode forced (my native) french language, whereas I set darktable to use english.

**Comment by geni1105** [comment] 2022-01-15 20:38
I have the same issue (iMac 27'', macOS 11.6.2), but only in fullscreen mode: the dialog does not work, nothing happens when the + buttons are pressed. Also the red window close button partly does not react.

The following sequence often seems to put it into normal working mode: hide the dialog (yellow button), cmd-tab to change to a different application like the web browser, retrieve the dialog from there again (by clicking on its icon in the dock). 

Luckily, in window mode everything seems to work as expected! 
   
Starting darktable from the command line and in debug mode, I get the following error messages (no idea if it is related or not):
(darktable:3593): GLib-GObject-WARNING **: 20:48:28.119: invalid cast from 'GtkMenuBar' to 'GtkWindow'
(darktable:3593): Gtk-CRITICAL **: 20:48:28.119: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed

**Comment by tomtomtls** [comment] 2022-01-15 20:53
Thank you for the windows mode tip! I always work in full screen mode, but as soon as I switched to windows mode I could set my own preset!!!

**Comment by Nilvus** [comment] 2022-01-19 11:52
So that's seems a specific MacOS bug when in full screen. You just have now to wait that a developer who work on MacOS see that and start testing/working on that.

**Comment by tomtomtls** [comment] 2022-01-19 12:16
Ready to help / test if needed.

**Comment by tomtomtls** [comment] 2022-03-28 19:49
Up to get a fix if possible 🤞🏼

**Comment by tomtomtls** [comment] 2022-05-28 13:31
Another up to -hopefully- get a fix.
Still willing to help as much as possible, just tell me what I can do 👍

**Comment by MStraeten** [comment] 2022-05-29 05:29
did you check if that might be an upstream bug in gtk?

**Comment by tomtomtls** [comment] 2022-07-05 09:03
Not sure how I can do that (somewhere in gtk project follow up I guess?), but I will check darktable v4 since UI seems to be heavily rebuilt.

**Comment by jbrogaard** [comment] 2022-08-04 20:25
> Not sure how I can do that (somewhere in gtk project follow up I guess?), but I will check darktable v4 since UI seems to be heavily rebuilt.

As of today no change/fix. Users, many working I guess in fullscreen mode, are not aware of the work-around and will think it's not working alltogether.

**Comment by Drill01** [comment] 2023-01-06 13:26
Hello, I'm new to Darktable and I'm having the same issue. A lot of commands do not respond. Unfortunately, in my case, nothing changes even if I leave full-screen mode and use windows mode. 
Mac mini Arm M1 - MacBook Pro Arm M1 Pro

**Comment by parafin** [comment] 2023-01-06 14:03
> Hello, I'm new to Darktable and I'm having the same issue. A lot of commands do not respond. Unfortunately, in my case, nothing changes even if I leave full-screen mode and use windows mode.
> Mac mini Arm M1 - MacBook Pro Arm M1 Pro

Your issue is a duplicate of #12727 most likely.

**Comment by Nilvus** [comment] 2023-01-31 17:29
An old issue, probably fixed. A last package had been done to fix some Gtk issues. See there: https://discuss.pixls.us/t/current-osx-build/13213/596
@tomtomtls and @jbrogaard: could you test if downloading last darktable MacOS package updating few days ago in link above, and post feedback here if your issue is fixed? @tomtomtls: if fixed, think about closing your issue yourself. Thanks.

**Comment by geni1105** [comment] 2023-02-04 15:12
Still does not work in fullscreen mode unfortunately (macOS 11.7.3, Intel; tested with official darktable 4.2.0, self-built 4.3.0+ from current master, and @MStraeten's latest build). 

Behavior is the same on all, and a bit improved compared to my earlier comment: '+' buttons to manage darkroom presets do not react, but after cmd-tab'ing to a different application and back it usually works.

**Comment by Campano** [comment] 2023-08-10 23:21
Not sure if this comment can help, if it's the same issue of not, nor what data might be of use so I'm just going to throw some stuff here.

There are usability issues on my configuration:
- installed yesterday through homebrew
- Apple M1 Pro - OS X Ventura 13.4.1
- Darktable 4.4.2
- the issues only seem to occur when using Darktable on my Lenovo monitor (connected to the mac through a docking station). When putting the window on the macbook screen it seems to behave OK, even with the monitor still connected.

There are:
- select boxes that seem to have missing items, like the preset selector only showing two options when there are in fact more
- buttons not responding, like the close button of the presets config window
- difficult to control scrolling behaviors. 

<details>

<summary>Click to see gif screenshot</summary>

![darktable](https://github.com/darktable-org/darktable/assets/1384759/d159e4b5-65f3-4ce6-8edd-b279f3d2b2db)

</details>

Please let me know if I can help or if I should open / follow another ticket.

**Comment by MStraeten** [comment] 2023-08-11 05:28
the issue seems to be a gtk issue - see https://github.com/darktable-org/darktable/issues/14856 (there’s also a link to an arm build using a gtk3 version that doesn’t show that behaviour - but has a redraw issue ;) )

**Comment by MStraeten** [comment] 2023-08-11 05:30
Closing this since gtk related - a newer gtk version doesn’t behave this way but shows ne issues ;)

**Closed by MStraeten** 2023-08-11 05:30 UTC
Labels: priority: high, understood: clear, scope: UI, bug: pending, scope: macos support
