### ISSUE TITLE
still problems opening Fujifilm X-T5 RAW files

### ISSUE THREAD

**Issue by Ishiido** [darktable-org/darktable#16387] opened 2024-02-26 17:41 UTC
When I open a RAW file shot with X-T5 and Fujinon 70-300 I find a broad black band at the right and the left of the picture. Seems to be specific for this combination as I do not see this in shots with 18-55, 55-200 or 100-400.

I could provide a file and appreciate any idea.

Tested with flathub version of darktable 4.2.1 and 4.6.1.

**Comment by Ishiido** [comment] 2024-02-27 16:39
Sorry for the silly question: files are too large, how can I contribute them?

**Comment by ptilopteri** [comment] 2024-02-27 18:53
you can put them on a file sharing service and provide the url here.

**Comment by Ishiido** [comment] 2024-02-28 17:41
Thanks again for your patience. 
The files can be found for a while here:

https://we.tl/t-iAbrfyroQP

I added pics made with Fujinon 10-24 and 18-135 (showing no problem) and one made with 70-300 which shows the black frame on the left and the right edge.
Thank you very much for looking into this problem.

**Comment by ptilopteri** [comment] 2024-02-28 18:00
I do not seem to see any "black frome"
see:
  http://wahoo.no-ip.org/~paka/Screenshot_20240228_125207.png
  http://wahoo.no-ip.org/~paka/Screenshot_20240228_125047.png

removed your xmp files and imported and again see no problem.

suggest you mv ~/.config/darktable/darktablerc ~/.config/darktable/XXdarktablerc
then start dt as:  darktable --library :memory:
import the images and see if you still have "flack frame"

**Comment by LebedevRI** [comment] 2024-02-28 18:24
I've seen this kind of issue (and others, where image is solid black) before,
and this is by far not the first time it's being reported.
There's likely "new" race conditions in darktable.

(unsubscribing from the issue)

**Comment by Ishiido** [comment] 2024-02-29 08:37
OK. I am a little puzzled. 

> I do not seem to see any "black frome" see: http://wahoo.no-ip.org/~paka/Screenshot_20240228_125207.png http://wahoo.no-ip.org/~paka/Screenshot_20240228_125047.png
> 

These are not the pics provided. Question was why is there a black frame in one of my pics (not in all).

> removed your xmp files and imported and again see no problem.

As far as I know I did not provide xmp files but only raws.


> 
> suggest you mv ~/.config/darktable/darktablerc ~/.config/darktable/XXdarktablerc then start dt as: darktable --library :memory: import the images and see if you still have "flack frame"

Yes, nothing changed. 
![klara_frame](https://github.com/darktable-org/darktable/assets/8094969/2e68ebae-f122-4d97-bb1d-9ba99cba302a)



> I've seen this kind of issue (and others, where image is solid black) before, and this is by far not the first time it's being reported. There's likely "new" race conditions in darktable.
> 
> (unsubscribing from the issue)

Thanks for that - so I guess format of T5 and the newer H2 and maybe also H2S is not fully supported in the raw libs. And there will be no solution. I also saw narrow black frames in digikam ...

Thanks again for looking.

**Comment by Ishiido** [comment] 2024-02-29 10:49
Ah! 
I just found out something else: the effect seems to be connected with camera settings. 
The T5 has a crop mode calls “sport mode”. The black bands on the side appear also with other lenses when this mode is turned on. Good to know - seems to be a bug anyway!

**Comment by kmilos** [comment] 2024-02-29 11:04
Good catch. Sems like a duplicate of https://github.com/darktable-org/darktable/issues/5729 then.

**Closed** 2024-02-29 11:05 UTC
