### ISSUE TITLE
Color mapping module (reset issue).

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#6381] opened 2020-09-26 03:38 UTC
**Describe the bug**
In the color mapping module when parameters are set and used in images as expected, if click reset parameters button doesn't reset anything. Because only clean the colors inside the target clusters, but not the colors inside the source clusters or the previous selection of numbers of clusters.

**To Reproduce**
1. Go to darkroom and select an image from the filmstrip.
2. Click on color mapping module, activate it
3. Click acquire as source
4. Select other image from the filmstrip
5. Click acquire as target and the color mapping is applied as expected.
**-- error --**
6. Click reset parameters icon and here is the error. The acction don't have effect. The source clusters continue with the old parameters of colors, number of clusters and everything else.

**Expected behavior**
Reset button, as it's name indicate, must put all parameters at theirs defaults values.

**Platform**
 - Darktable Version: 3.2.1
 - OS: Windows 10
 - OpenCL activated
 - ASUS POSEIDON Nvidia GeForce GTX1080Ti 11 GB
 - GIGABYTE Nvidia GeForce GTX 1070 8GB

**Screenshots**
<img width="250" alt="Color Mapping issue" src="https://user-images.githubusercontent.com/67672868/94329229-516d3200-ff87-11ea-911f-e0d54a298057.PNG">

**Comment by johnny-bit** [comment] 2020-09-26 07:42
It looks like it was designed this way to allow user to have single source and multiple targets. Sorta like ease-of-life reset and not full reset.

There are couple ways to solve it, like for example having 2 additional buttons - `clear source` and `clear target` which would allow clearing of clusters without affecting anything else and thus unlock posibility of having hard reset possible.

I'd like to gather what others thing tho :)

**Comment by TurboGit** [comment] 2020-09-26 08:03
Exactly the source is kept, for me this is of course correct and I don't see why adding another button is needed.

Either you come back to the module later and you can still apply the transformation to another image, or you acquire another source when needed. Having the source left in the module is in no way preventing any further action. So my vote is to do nothing and let this as it is (as been designed).

**Comment by todd-prior** [comment] 2020-09-27 05:23
@TurboGit  On windows in 3.2 the second you try to adjust the sliders for eq or dominance after selecting your source and target the module clears itself....I have seen this posted by another couple of users on FB and Reddit

**Comment by todd-prior** [comment] 2020-09-27 05:37
[darktable 2020-09-27 01-33-58.zip](https://githu@TurboGit  VIdedarktable-org/darktable/files/5287769/darktable.2020-09-27.01-33-58.zip)
@TurboGit The attached video shows it happening...

**Comment by johnny-bit** [comment] 2020-09-27 06:23
Todd this is different issue. Care to open another?

niedz., 27 wrz 2020, 07:37 użytkownik todd-prior <notifications@github.com>
napisał:

**Comment by johnny-bit** [comment] 2020-09-27 08:21
Ah, sorry - it is present - it's bug #6328, but still - totally different than this one ;)

**Comment by todd-prior** [comment] 2020-09-27 13:04
I had but it got no attention yet and this one I thought might be related and was being discussed so I commented...sorry





Get Outlook for Android

**Comment by johnny-bit** [comment] 2020-12-15 19:48
Seems like the module works as intended and the current behaviour is described in docs https://darktable-org.github.io/dtdocs/module-reference/processing-modules/color-mapping/

Closing this for now - Ping me to reopen if you disagree!

**Closed by johnny-bit** 2020-12-15 19:48 UTC
Labels: bug: invalid

**Comment by todd-prior** [comment] 2020-12-15 23:48
I just tried it on a recent build I did a day or so ago….ironically it crashes DT. Before I think if I recall the error was just selecting the target button cleared the source data that had been selected. Now at least on my machine it loads color patches in the source grid and then promptly crashes with no warning or errors….I have run with debug all but can’t seem to trap a log file …maybe I am not looking in the right place??

**Comment by johnny-bit** [comment] 2020-12-16 08:27
@todd-prior I can't replicate the crash on current master... If you can and have replication steps - please open new issue :) If you find any more problems in color mapping, feel free to open issues about it. This here is just about reset not working as expected (but working as intended)
