### ISSUE TITLE
I cannot import pictures to the software

### ISSUE THREAD

**Issue by RichStudios** [darktable-org/darktable#6091] opened 2020-08-25 17:01 UTC
Hi, I have been trying to import pictures onto the software but they wont load onto the light table

**Comment by MStraeten** [comment] 2020-08-25 18:09
Please provide more info on your system and your steps to reproduce ist.
Btw: theres a bug report template available (https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title=) It makes sense to use it since it asks for a few helpful informations

**Comment by johnny-bit** [comment] 2020-08-25 19:30
While we wait for you to provide full details, I'll repeat what I said in https://www.reddit.com/r/DarkTable/comments/ifo1fe/problem_with_importing_files/

Get yourself a known good file, get yourself a known good release from darktable.org, make sure that your system or config being a problem (eg I know loads of problems with antivirus we had recently). Once you do that, please report back!

**Comment by johnny-bit** [comment] 2020-12-15 21:09
Lack of info. Closing. Feel free to comment with more info and I'll reopen and we'll investigate the issue.

**Closed by johnny-bit** 2020-12-15 21:09 UTC
Labels: no-issue-activity
