### ISSUE TITLE
Export module uses completely wrong path

### ISSUE THREAD

**Issue by halojenproductions** [darktable-org/darktable#13423] opened 2023-01-24 07:22 UTC
Export module target path is set right but the path it exports to is completely wrong.

**To Reproduce**
Edit a photo in a folder that has dashes in the name. E.g. `2022-06-01`
Set target storage to `$(FILE.FOLDER)\\$(FILE.NAME)` (it was originally `$(FILE_FOLDER)/$(FILE_NAME)` but I changed it when trying to figure out what was going wrong).
Export.

Instead of saving to the expected folder it makes up a completely different folder and filename with ("_no_name" appended to the folder name).

**Expected behavior**
Save jpegs into the same directory as the raws.

**Screenshots**
![image](https://user-images.githubusercontent.com/40622702/214233652-5d6e54b8-9b56-48c2-8234-4905f5a23f35.png)

**Which commit introduced the error**
4.0.1 and 4.2 both do this.

**Platform**
* darktable version : 4.0.1 and 4.2
* OS                : Win10

**Additional context**
It worked fine last time I used 4.0.1 but I tried 4.2 anyway. After thinking about what has changed, I came upon the _assumption_ that it's not handling the dashes in the folder name. I haven't confirmed this.

**Comment by gi-man** [comment] 2023-01-26 02:06
> $(FILE.FOLDER)\\$(FILE.NAME)

I think the double \\ is a problem.

**Comment by halojenproductions** [comment] 2023-03-04 00:31
It's not that. I get the same result with every combination of `/`, `//`, `\`, `\\`, `FILE.FOLDER`, `FILE.NAME`, `FILE_FOLDER`, and `FILE_NAME`.

**Comment by victoryforce** [comment] 2023-03-04 10:01
I cannot reproduce this issue with your steps on Win10, tested with the current development version and with darktable 4.2. All exported images are written to the expected locations.

What do you mean by "it makes up a __completely__ different folder and filename"? Without examples of source folder and file names, expected export names, and actual names, this statement contains little information. It's great that you provided a screenshot, let's take a look at it.

`$(PICTURES_FOLDER)/Darktable` in the screenshot is the default base folder for importing images. `_no_name` is appended to the folder name during the import process when the "copy & import" operation is performed (this is the default value of the `import job` variable). So the folder in your screenshot where darktable is exporting to is obviously the folder with the imported images. Next, the file name obviously matches the folder name, they contain the same date. So from the information on the screenshot, we can conclude that it shows exactly the expected behavior: save jpegs into the same directory as the raws.

So please clarify. Even better would be to reproduce and describe in more detail the unexpected behavior on darktable 4.2.1, preferably with a clean configdir.

**Comment by halojenproductions** [comment] 2023-03-04 22:04
This is the full path to the source file and where I expected it to save the jpeg (I didn't change anything about my workflow from prior to upgrading dt*). 
`B:\User Profile\Pictures\Photographs\Infrared, Full spectrum, Ultraviolet\Infrared\Sony a200 IR\2022-06-01`.
Perhaps the issue is actually the commas like this bug turned out to be https://github.com/darktable-org/darktable/issues/11045

*I just reread your comment about "copy & import" and checked for sidecar files in the above directory but there weren't any. I then did "add to library" and imported the same files and it wrote the sidecars just fine. 
I've never intentionally used the "copy & import" function but I guess I could have clicked it accidentally

**Comment by victoryforce** [comment] 2023-03-05 11:29
> *I just reread your comment about "copy & import" and checked for sidecar files in the above directory but there weren't any. I then did "add to library" and imported the same files and it wrote the sidecars just fine. I've never intentionally used the "copy & import" function but I guess I could have clicked it accidentally

If I understood you correctly, it turned out that darktable works as expected, it's just that you accidentally imported the image into another folder.

If so, please consider closing the issue, as there is no bug in darktable.

P.S. You can always see the folder the image is in by looking in the Image Information module.

**Closed** 2023-04-24 14:06 UTC
Labels: bug: won't fix
