### ISSUE TITLE
IOP cache broken

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#12120] opened 2022-07-03 21:11 UTC
There is a cache mechanism in the pipeline that puts the output of modules in memory. In each module, it uses a hash of the parameters and compares it with what is in cache to invalidate it only when needed. When a module gets its parameters changed, this cache used to allow only the downstream modules to get recomputed, so not the earlier modules.

It's been at least several weeks that this mechanism is broken. When changing parameters in a late module, like the colorimetric intent in output color profile, the whole pipeline gets recomputed from scratch. This affects the CPU and the OpenCL pathes.

**Comment by jenshannoschwalm** [comment] 2022-07-04 09:34
#11877 and #11876

should have fixed that at least for the mentioned modules. Did you test on master or on your branch (possibly have missed those?) I tried to reproduce this morning and could not confirm the issue yet

**Comment by aurelienpierre** [comment] 2022-07-04 13:48
> Did you test on master or on your branch (possibly have missed those?) 

Yes, I tried both.

**Comment by jenshannoschwalm** [comment] 2022-07-04 14:15
Do you have detail mask enabled in your xmp?

**Comment by ralfbrown** [comment] 2022-07-05 13:34
Also keep in mind that the IOP cache is very small (only eight entries).  If there are more modules than that downstream of the one whose parameters got changed, the module's input is no longer in cache.  That forces a full recompute.

**Comment by TurboGit** [comment] 2022-07-06 09:23
@ralfbrown : We already discussed that some time ago. What I don't remember is why did we not increase the cache size? Is there any drawback?

**Comment by jenshannoschwalm** [comment] 2022-07-06 09:46
I don't know how to do that right now but wouldn't it be good if the cachelines for "critical modules" would have a much higher priority for being kept? (Notorious ones would be D&S and the new laplacian highlights)

**Comment by ralfbrown** [comment] 2022-07-06 17:58
@TurboGit: we already increased the size from five to eight.  A proper caching system would also need to keep track of memory used by the cache and memory needed by iops, so that it could grow as big as possible without impairing the speed of the pipeline or triggering the OOMKiller.  That's why the size was only modestly increased, since its memory usage is on top of the limit set for the pixpipe.

@jenshannoschwalm That is indeed a good idea.  Currently there are two (IIRC) modules which are basically frozen into cache - the input to the currently-focused module being one, and the output of the final module being the other (so that the histogram can be switched around without triggering a pixpipe run).

The existing cache is extremely simplistic and could use a full rewrite....

**Comment by jenshannoschwalm** [comment] 2022-07-07 04:31
Indeed there is this "important" test making sure the mentioned module data have a high priority in cache via `dt_dev_pixelpipe_cache_get_important`

For me the problem seems to be we "pollute" the cache by modules that are executed so fast that re-processing wouldn't hurt much. For OpenCL we have a conf key that might even further hurt.

If we want to keep cachelines at 8 that would be likely ok if we measure the time while processing the module and use that as weight.

**Comment by jenshannoschwalm** [comment] 2022-07-08 16:27
I looked through all the related code and i think i know how to do a good proposal for this. @TurboGit you can assign me if you want me to do it.

**Comment by ralfbrown** [comment] 2022-07-08 18:46
BTW, since nearly all substantial memory allocations (one image row or larger) now go through just a couple of dt_* functions, it will be fairly straight-forward to track total memory allocations and kick something out of cache when a new request would exceed the max allowed.  So there won't be a need for the rewritten caching to have an explicit limit on the number of items.  Much like Linux's disk cache, it can just grow until something else needs the memory.

**Comment by aurelienpierre** [comment] 2022-07-11 21:32
> BTW, since nearly all substantial memory allocations (one image row or larger) now go through just a couple of dt_* functions, it will be fairly straight-forward to track total memory allocations and kick something out of cache when a new request would exceed the max allowed

That wouldn't work for OpenCL, also keep in mind that modules that start executing OpenCL kernels may fall-back to CPU if the allocated time is exceeded.

I have found new weird things, like toggling on/off filmic highlights mask or changing the colorimetric ICC intent (with LCMS2 on) consistenly trigger a full pipe recomputation. Filmic mask only calls `dt_dev_reprocess_center(self->dev);` and the ICC intent calls `dt_control_queue_redraw_center();`.

**Comment by aurelienpierre** [comment] 2022-07-11 21:41
What is even weirder is that module params changes call `gui_changed()` wich calls `dt_dev_add_history_item(darktable.develop, module, TRUE);` (git blame: 5 months ago) which calls `_dev_add_history_item(dev, module, enable, FALSE);`  (git blame : 20 months ago) which calls `dt_dev_invalidate_all(dev);` (git blame: 13 years ago), doing full pipe cache invalidation. But every param change doesn't necessarily trigger a full pipe recompute, so the behaviour is not even consistent with the code.

**Comment by ralfbrown** [comment] 2022-07-12 04:35
> > BTW, since nearly all substantial memory allocations (one image row or larger) now go through just a couple of dt_* functions, it will be fairly straight-forward to track total memory allocations and kick something out of cache when a new request would exceed the max allowed
> 
> That wouldn't work for OpenCL, also keep in mind that modules that start executing OpenCL kernels may fall-back to CPU if the allocated time is exceeded.

In fact it would work properly if the allocation request is what triggers removing items from the cache.  When the OpenCL kernel falls back, if the additional memory needed by the CPU path would cause allocations+cache to exceed the limit, some of the cache gets freed to be able to satisfy the request.

**Comment by giannissc** [comment] 2022-07-12 14:40
I can also verify this is happening. It is immediately obvious when using heavy modules like the highlights reconstruction with the guided laplacians or the diffuse or sharpen module. Is there anything that I can do to help?

**Comment by jenshannoschwalm** [comment] 2022-09-03 16:20
There is also #12393 - that should have fixed this issue.

**Comment by jenshannoschwalm** [comment] 2022-09-08 09:26
There has been #12439, I can't reproduce this issue any more...

**Comment by jenshannoschwalm** [comment] 2022-10-22 16:52
@aurelienpierre @TurboGit i think this issue can be closed as fixed via all the pixel pipe cache work for now.

**Comment by jenshannoschwalm** [comment] 2022-11-12 17:18
No one closing this?

**Comment by elstoc** [comment] 2022-11-12 18:33
I don't mind closing it if you're sure it's fixed.

**Comment by jenshannoschwalm** [comment] 2022-11-12 19:40
Yes i am sure in the generic meaning as in title and following discussion.

If there **is** a remaining bug it would be a very specific one that should be discussed and tracked down in another issue.

**Closed** 2022-11-12 19:59 UTC
Labels: bug: pending
