### ISSUE TITLE
White Balance Problem

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#12910] opened 2022-11-15 18:43 UTC
I recently had cause to totally rebuild my Manjaro/Arch/XFCE system on which I reinstalled the latest dt git version 4.1.0+997~g49764adbe2.
I copied over , from my backup, all of my images and then added the entire set into a newly created library.
I now notice that in the processing structure all of the 'as shot' white-balance settings have been retained and the color-calibration settings are marked as 'invalid'.
A full rebuild is probably unusual for most people but I do think that this constitutes a long term problem that needs to be addressed.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by TurboGit** [comment] 2022-11-15 19:36
> A full rebuild is probably unusual for most people but I do think that this constitutes a long term problem that needs to be addressed.

Which problem? There is a vague description but I do not see what is going on. Certainly I do not see the cause of the WB issue, and I don't see why it would be because of rebuilding a full system. So to help here we will need lot more information.

**Comment by gi-man** [comment] 2022-11-15 19:40
Please use the template.

**Comment by Nilvus** [comment] 2022-11-16 19:07
On what I understand, this seems to be a duplicate of #12801 and #12134 and #11377. I let this open one or two days waiting for more infos before closing. If issues linked there are your issue, please close as you will have all needed infos.

**Closed** 2022-11-17 22:09 UTC
Labels: duplicate, understood: unclear
