### ISSUE TITLE
Panasonic DMC-G7 hardcoded CFA is no longer valid

### ISSUE THREAD

**Issue by Fowlet** [darktable-org/darktable#6988] opened 2020-11-19 21:12 UTC
When loading a RAW (.rw2) file from a Panasonic Lumix G7, the colors are wrong, seems like no green channel?

Example:
https://drive.google.com/file/d/10f5CN9Mw_GmI_7aQSlfv1YI675IyLIzS/view?usp=sharing

The RAW file that produced this:
https://drive.google.com/file/d/1H1kc8w09lrIp261RmtBw8FEfUKgkmmFJ/view?usp=sharing

**Comment by Nilvus** [comment] 2020-11-19 21:51
Could you provide the XMP also that display that? Did you check white balance settings and which darktable version do you use?

**Comment by Fowlet** [comment] 2020-11-19 22:45
XMP:
https://drive.google.com/file/d/1OKDmriPmKpxEDfCVHFBaCHHzPnMSUPRv/view?usp=sharing

The above WB is "camera" preset. All WB settings all produce varying shades of magenta.

Version 3.2.1 on Windows. Also tested on Ubuntu, version 2.4.2-1 (i.e. the one apt installs by default on 18.04).

The files open fine in e.g. RawTherapee.

**Comment by Nilvus** [comment] 2020-11-20 17:39
I can easily reproduce that, even in master and with new color calibration module that has a powerful white balance option. With that module (and with white balance, I can improve colors and have a more balance and remove pink but it's hard on that image to restore all parts. The G7 doesn't seem to have a full set of white balance support as you can see here: https://github.com/darktable-org/darktable/blob/master/src/external/wb_presets.c (check around line 8272 to see that the G7 has few lines for white balance supports as, other like the G5 or the GX8 I have, have many more lines). So I suspect that should be the cause. And if I'm not wrong, that would mean work to improve the white balance presets. But only someone with a G7 could do that, so it will be hard to have better support.

You could see on that article, how to work on improving and propose a better white balance support. This is not easy but not really hard and needs a colorchecker: https://encrypted.pcode.nl/blog/2010/06/28/darktable-camera-color-profiling/

**Comment by Nilvus** [comment] 2020-11-20 17:41
@johnny-bit: I just see that you add on april a lot of finetuned wb presets for panasonic bodies. Do you have some idea about that issue and how hard is it to set a correct white balance?

**Comment by johnny-bit** [comment] 2020-11-20 19:45
Not really. This more likelly is some problem with the raw itself, because the error is present in dt 3.0.x,  3.2.1 as well as current master...

Maybe it's more for @LebedevRI ?

**Comment by LebedevRI** [comment] 2020-11-20 19:54
@Fowlet was that raw file copied directly from camera's flash card, as a file, and it wasn't modified by any software?

**Comment by chhil** [comment] 2020-11-20 19:55
I tried some random G7 raws from https://www.photographyblog.com/reviews/panasonic_lumix_dmc_g7_review/sample_images with current master.
Did not see the problem.

**Comment by chhil** [comment] 2020-11-20 20:07
I compared the exif info of a g7 file off the web and the one shared here.

The CFA pattern seems to be reversed.

![image](https://user-images.githubusercontent.com/1119439/99845089-17d93180-2b9a-11eb-8ab9-4a54e7208d47.png)

**Comment by chhil** [comment] 2020-11-20 20:32
Since I was bored, I tried changing the CFA pattern in the raw....didn't help :(

```
Find group for CFA pattern (IFD0)
F:\portableapps\exiftoolgui>exiftool "-cfapattern*" -G1 P1000571.RW2
[IFD0]          CFA Pattern                     : [Green,Blue][Red,Green]

Update the group:cfapttern to reverse colors)
F:\portableapps\exiftoolgui>exiftool -IFD0:cfapattern="[Blue,Green][Green,Red]"
P1000571.RW2
    1 image files updated
See if colors were reversed.
F:\portableapps\exiftoolgui>exiftool "-cfapattern*" -G1 P1000571.RW2
[IFD0]          CFA Pattern                     : [Blue,Green][Green,Red]
```

**Comment by LebedevRI** [comment] 2020-11-20 20:43
> The CFA pattern seems to be reversed.

Yep.

> Since I was bored, I tried changing the CFA pattern in the raw....didn't help :(

That's because we don't read the CFA specified in the EXIF, which is why this issue is here :]

**Comment by chhil** [comment] 2020-11-20 20:51
> That's because we don't read the CFA specified in the EXIF, which is why this issue is here :]

In that case why do G7 raws from the web work?

**Comment by LebedevRI** [comment] 2020-11-20 20:53
> > That's because we don't read the CFA specified in the EXIF, which is why this issue is here :]
> 
> In that case why do G7 raws from the web work?

The more appropriate question is, why @Fowlet's raw doesn't.

**Comment by Fowlet** [comment] 2020-11-20 21:06
I'll try resetting the camera to factory settings and see how the RAWs come out. I did mess with the color space settings but the only options are sRGB or Adobe RGB, neither of which are exotic, right?

**Comment by LebedevRI** [comment] 2020-11-20 21:09
That didn't answer my question.

**Comment by Fowlet** [comment] 2020-11-20 21:18
Apologies, it was downloaded from the camera via USB. Only possible source of weirdness is I uploaded it to my home server and was opening it from there, but I did try downloading it and opening it from local also with the same result. The server protocol is Samba which I would be very surprised if it messed with the internals of files.

**Comment by LebedevRI** [comment] 2020-11-20 21:23
Downloaded with what? Plain file manager?

**Comment by Fowlet** [comment] 2020-11-20 21:30
Yes, in the linux case GNOME File Explorer, in the Windows case File Explorer.

New test:
I have factory reset the camera, formatted the SD card, set the capture mode to RAW and taken a picture. I have then connected the camera to a windows laptop via USB, and used darktable 3.2.1 to open the file from the camera as a "removable drive". Now things are more purple than magenta, as you can see in the below link.

I have uploaded the jpg, RAW and a darktable screenshot to google drive using the web interface, opening the files for upload directly from the camera/removable storage.
https://drive.google.com/drive/folders/1D2xb3UYxpGgsg3gPvq_gRH9YrIPv4rv1?usp=sharing

**Comment by chhil** [comment] 2020-11-20 21:38
@Fowlet 
Can you try shooting one with setting whitebalance to anything else than auto, something like shade or incandescent?

**Comment by Fowlet** [comment] 2020-11-20 21:47
Here is a folder with a picture taken with WB set to shade (or "cloud symbol" at least):
https://drive.google.com/drive/folders/1Lf0uL1uiVSJGUH2FI1y2_WvFX7F4zjnC?usp=sharing

**Comment by LebedevRI** [comment] 2020-11-21 06:16
> Yes, in the linux case GNOME File Explorer, in the Windows case File Explorer.

OK then.
Can you please contribute the original raw (https://drive.google.com/file/d/1H1kc8w09lrIp261RmtBw8FEfUKgkmmFJ/view?usp=sharing), or some similar affected image to https://raw.pixls.us/ please ?

**Comment by LebedevRI** [comment] 2020-11-24 06:19
@Fowlet ping

**Comment by LebedevRI** [comment] 2020-12-03 18:33
@Fowlet ping

**Comment by LebedevRI** [comment] 2020-12-10 18:48
Unless @Fowlet resurfaces with an CC0 sample, this won't be fixed.

**Comment by todd-prior** [comment] 2021-01-17 21:26
> Since I was bored, I tried changing the CFA pattern in the raw....didn't help :(
> 
> ```
> Find group for CFA pattern (IFD0)
> F:\portableapps\exiftoolgui>exiftool "-cfapattern*" -G1 P1000571.RW2
> [IFD0]          CFA Pattern                     : [Green,Blue][Red,Green]
> 
> Update the group:cfapttern to reverse colors)
> F:\portableapps\exiftoolgui>exiftool -IFD0:cfapattern="[Blue,Green][Green,Red]"
> P1000571.RW2
>     1 image files updated
> See if colors were reversed.
> F:\portableapps\exiftoolgui>exiftool "-cfapattern*" -G1 P1000571.RW2
> [IFD0]          CFA Pattern                     : [Blue,Green][Green,Red]
> ```

Change it in rawspeed directory....cameras.xml and it fixes the issue..

**Comment by LebedevRI** [comment] 2021-01-17 21:30
Yep, and will break all the cameras where the existing CFA was correct.
I'd like to address this properly, but for that i need someone affected to contribute an appropriate sample to RPU..

**Comment by todd-prior** [comment] 2021-01-17 21:34
I was just helping someone on the FB forum with the issue... so I thought I would mention it....seems like some images firmware or software v1 use the BGGR and newer ones or maybe is CFA hardware and if so some are made with different filters on the sensor are GBRG??  The later was version 2.2 of the panasonic software.??  Bit out of my league here but I can likely dig up the two images...RPU?? Rawspeed update page?? thx for responding

**Comment by LebedevRI** [comment] 2021-01-17 21:38
@todd-prior assuming that the images are straight from camera, and were copied via a card reader and file manager (i.e. were not modified/copied via some manufacturers/etc program), just tell them to contribute one such image to https://raw.pixls.us (adding a link to this disscussion in the upload's comment field)
I'll take it from there.
Thanks!

**Comment by todd-prior** [comment] 2021-01-17 23:28
Will do





Get Outlook for Android

**Comment by LebedevRI** [comment] 2021-01-18 13:04
Perfect, sample acquisition confirmed.
Please forward my thanks.

**Comment by todd-prior** [comment] 2021-01-18 16:27
Will do….

**Comment by Martin-Wegner** [comment] 2021-01-28 10:16
Same problem here. All my RAW photos of my Panasonic Lumix G70 are pink :(

**Comment by todd-prior** [comment] 2021-01-28 16:01
@Martin-Wegner  Its an easy hack to fix it or have you done so??

**Comment by Martin-Wegner** [comment] 2021-01-28 18:36
> @Martin-Wegner Its an easy hack to fix it or have you done so??

Yes, thanks, it works now with:

```
			<Color x="0" y="0">GREEN</Color>
			<Color x="1" y="0">BLUE</Color>
			<Color x="0" y="1">RED</Color>
			<Color x="1" y="1">GREEN</Color>
```

**Comment by todd-prior** [comment] 2021-01-28 20:26
You got it perfect…..

**Comment by codeman38** [comment] 2021-02-10 04:35
Just got a Lumix G7 a couple weeks ago and encountered this same issue. I can confirm that the XML change from @Martin-Wegner fixes the colors for me.

**Comment by LebedevRI** [comment] 2021-03-21 14:42
My apologies for completely dragging this out :(
I seem to have completely dropped the ball on camera support for the last few months.

**Closed** 2021-03-21 14:41 UTC
Labels: no-issue-activity, scope: camera support
