### ISSUE TITLE
[darkroom] filmstrip does not get updated & show grey boxes instead

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#5318] opened 2020-06-05 14:16 UTC
**Describe the bug**

In filmstrip I sometimes merely see grey boxes rather than the thumbnail (yes I use darktable-generate-cache -m 6)
I see this already for quite some time in dt-3.1.0

When I scroll those thumbnails out of the screens boundaries and back, they get updated...

pls. see attached screencast.

**Expected behavior**

thumbnails should be updated more or less instantly...

**Screencast**

[dt_filmstrip_20200605_B-2020-06-05_16.00.41.mp4.zip](https://github.com/darktable-org/darktable/files/4736571/dt_filmstrip_20200605_B-2020-06-05_16.00.41.mp4.zip)

**Platform (please complete the following information):**
* darktable version : 3.1.0+1940~gdb00837d1
* OS                : Linux - kernel 5.6.15-gentoo
* Distro            : Gentoo Base System release 2.6
* Processor         : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
* Memory            : 32 GB (4 x 8 GB) + 5GB Swap
* Graphics card0    : GeForce GTX 1060 6GB
* Graphics card1    : GeForce RTX 2070 SUPER
* Graphics driver   : nvidia-drivers-440.82-r3
* OpenCL installed  : Yes (opencl-headers-2020.03.13-r1)
* OpenCL activated  : Yes
* Xorg              : xorg-server-1.20.7
* Desktop           : KDE 5
* GTK+              : gtk+-3.24.16
* gcc               : x86_64-pc-linux-gnu-9.3.0
* cflags            : CFLAGS="-march=native-O2-mtune=native-pipe"
* CMAKE_BUILD_TYPE  : "Release"

**Comment by AlicVB** [comment] 2020-06-05 14:28
Seems like we miss some redraw... but where ?
Can you share more infos about this ?
- Can you reproduce ?
- Does it happen when you change view from lighttable to darkroom ? Or does it need some other steps?

Thanks

**Comment by TurboGit** [comment] 2020-06-05 14:38
Not sure if this still the case but I remember that sometime the thumbs mip is not available and we need to reschedule a redraw for a bit later and do that until all redraw have been successful.

**Comment by AxelG-DE** [comment] 2020-06-05 14:39
- Yes I can reproduce on altered and unaltered images
- Yes, just changing from lighttable to darkroom is already enough to "trigger this"

Attached recording tries to answer your question.
Can I do anything else to support analysis?

[dt_filmstrip_20200605_C-2020-06-05_16.35.36.mp4.zip](https://github.com/darktable-org/darktable/files/4736680/dt_filmstrip_20200605_C-2020-06-05_16.35.36.mp4.zip)

**Comment by TurboGit** [comment] 2020-06-05 14:39
@AlicVB : I cannot reproduce systematically but I have experienced that recently but I do not remember having seen this in 3.0.2.

**Comment by AxelG-DE** [comment] 2020-06-05 14:46
> @AlicVB : I cannot reproduce systematically but I have experienced that recently but I do not remember having seen this in 3.0.2.

by mistake I wrote 3.0.1, now corrected. I see it since some time in 3.1.0

**Comment by AlicVB** [comment] 2020-06-05 15:38
yep, certainly a missing redraw from my lighttable/filmstrip redraw. The question is where ?
And yes, the resheduled redraw is integrated in the thumbnail code already.
Let's see if I manage to reproduce or if I can find a the problem by reading the code...

**Comment by AlicVB** [comment] 2020-06-05 15:42
>     * Yes, just changing from lighttable to darkroom is already enough to "trigger this"

Just to be sure to search in the right direction,
- in which layout are you in lighttable (filemanager, zoomable, expose, preview) ?
- how do you switch to darkroom ? double-click or shortcut ?

**Comment by AxelG-DE** [comment] 2020-06-05 16:12
>     * in which layout are you in lighttable (filemanager, zoomable, expose, preview) ?

"expose, preview" confuse me a bit. lighttable merely has three options (zoomable light table, filemanager, culling) ---> what am I missing? :)

Actually I can reproduce it from filemanager and zoomable. 

From **culling** is **not reproducable.**

Typically I double click, but in my video I used to click on the "darkroom" in the top bar and just now I tested with shortcut. **All three ways reproduce the error**.

**Comment by AlicVB** [comment] 2020-06-05 16:26
@AxelG-DE : my bad, it was culling not expose (and preview is alt-W)... Anyway that's good news that you can't reproduce from culling, where filmstrip is already active. Your answer will help me. Thanks !

**Comment by AlicVB** [comment] 2020-06-05 18:13
ok, that should be fixed in PR #5320 
a tricky one : in fact if the image was not anymore visible in the thumbnail after the resizing (old margins greater than new size), `gtk_queue_draw` do nothing and so doesn't force the image refresh !

Thanks for the report

**Closed** 2020-06-05 21:02 UTC

**Comment by AxelG-DE** [comment] 2020-06-05 21:37
Thanks for the fast reaction!

I am afraid I need to open a new BR anyway :-)
What happened to me this evening (tested three times with starting dt newly), at the beginning I can scroll the filmstrip with the mousewheel and suddenly no more reaction.... Need to investigate...

**Comment by Nilvus** [comment] 2020-06-06 10:15
> Thanks for the fast reaction!
> 
> I am afraid I need to open a new BR anyway :-)
> What happened to me this evening (tested three times with starting dt newly), at the beginning I can scroll the filmstrip with the mousewheel and suddenly no more reaction.... Need to investigate...

Just a thing (to be sure) before open a new one: do you always remove build folder (and destination one) before compiled again master? It's better to avoid some wrong overrides to delete those folder before any new compile.

**Comment by AxelG-DE** [comment] 2020-06-06 12:14
> do you always remove build folder

yes I do. I use a self made script, which takes care of that, always. Thanks for caring!
