### ISSUE TITLE
Leica D-LUX 7

### ISSUE THREAD

**Issue by carminecare** [darktable-org/darktable#8158] opened 2021-02-09 09:30 UTC
Y have the following problem when open files from my new Leica D-LUX 7.
I have uploaded the raw file to https://raw.pixls.us/
Thank you for help

Nino Care

![Schermata 2021-02-09 alle 10 26 11](https://user-images.githubusercontent.com/76827223/107343200-67f0d180-6ac1-11eb-8acd-0fb57809b44e.png)

**Comment by carminecare** [comment] 2021-02-09 10:30
Also with this we have the same problem
![Schermata 2021-02-09 alle 10 44 54](https://user-images.githubusercontent.com/76827223/107345471-e0f12880-6ac3-11eb-8a85-f609e282ce1e.png)

**Comment by LebedevRI** [comment] 2021-02-19 08:27
Duplicate of #7931.

**Closed by LebedevRI** 2021-02-19 08:27 UTC
Labels: scope: camera support
