### ISSUE TITLE
Double Demosaic

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#6500] opened 2020-10-11 00:57 UTC
This is a feature request for double demosaicing. I love darktable and greatly appreciate all the work that has gone into it. If there is one feature from Rawtherapee I would like to see included in darktable it is double demosaicing. That is the ability to choose an algorithm using two different methods (eg. Amaze + Vng4) on different parts of the image. For instance, the Amaze algorithm tends to give nicer results on higher frequency details, and Vng4 on lower frequency - yet more often than not we encounter images with both - such as images with both trees (higher freq) and sky (lower freq). Double demosaicing gives the best of both worlds. As per Rawtherapee, a threshold mask should be displayed with white showing for Amaze, and black for Vng4, and a contrast threshold slider allowing the user to choose how much of the mask is black and how much white - in other words, how much (and which parts) of the image is being affected by each.

I have focused on Amaze and Vng4 so far primarily because they are two algorithms darktable already has, and also because they work well for the concept (that is one part of double should be for high freq, the other for low freq). However the concept could apply to as many different algorithms as desired.

Is there any interest in this?

**Comment by jade-nl** [comment] 2020-10-11 19:08
I'm definitely in favour of this feature request.

The demosaic module in RawTherapee is rather nice and something like that would be a nice extension of the, very simple version that darktable offers at the moment.

RawTherapee just added a few more (the bilinear ones in development version). Not sure if darktable would need as many as RT, but it could sure use a double demosaic to start with.

Starting with a good demosaic method does increase in a positive way, for example, the way one can tackle noise. Right now you have to make a choice between high or low frequency even though many images have both.

So yea / ~~nay~~ for this request.

**Comment by SZim92** [comment] 2020-11-22 08:26
Duplicate of #3513.

**Comment by heckflosse** [comment] 2020-11-24 15:36
Just for information: The new ones in RT dev (+ bilinear) are (for low ISO files) almost equivalent to the (+ VNG4) ones, but way faster for the second demosaicer.

**Comment by johnny-bit** [comment] 2020-12-20 17:27
Closing in favour of #3513

**Closed by johnny-bit** 2020-12-20 17:27 UTC
Labels: no-issue-activity
