### ISSUE TITLE
Display mask isn't functioning under certain modules [DT 3.7]

### ISSUE THREAD

**Issue by Dave22152** [darktable-org/darktable#9744] opened 2021-08-06 13:24 UTC
**Description**

Displaying a mask under certain modules results in a grey screen instead of highlighting the affected areas in yellow.  Occurs in DT 3.7 but not 3.6.0.1

**Did you buy darktable from an application store ?**

No

**Additional Details**

While the mask is not displayed, drawn and parametric masking will work as expected. I've found this happens with local contrast, tone curve, color reconstruction, and shadows and highlights.  Other modules such as exposure and color balance RGB will properly display the mask.

I suspected that this might be happening with modules that follow Filmic, but I found it also happens with the sharpen module, which is enabled prior to Filmic, so it doesn't appear to be dependent upon the pipeline.

**To Reproduce**

Activate a module such as local contrast in DT 3.7 and apply a drawn or parametric mask.  Enable the display mask feature and the entire display will go grey instead of highlighting the masked regions.  

**Screenshots**
The attached screenshot shows an elliptical mask applied to local contrast (I cranked up the module for effect).  While the system will show the mask elements, the mask display is not highlighted

![Local Contrast Display Mask Anamoly](https://user-images.githubusercontent.com/61152378/128516805-bf51fc7e-312b-42bb-ad8a-a004792a4f7f.JPG)

**Which commit introduced the error**
As noted, this started in 3.7

**Platform**
darktable version : 3.7.0+601~gf0e6c14fb
OS : Windows 10
Memory : 8 GB
Graphics card : AMD A8-7410 APU with AMD Radeon R5 Graphics, 2.20 Ghz
Graphics driver : Unk
OpenCL installed : Yes
OpenCL activated : No (Open CL always causes my system to lock up - different issue)
Xorg : Unk
Desktop : HP Pavalion
GTK+ : Unk
gcc : Unk
cflags : Unk
CMAKE_BUILD_TYPE : Unk

**Comment by johnny-bit** [comment] 2021-08-06 14:14
Duplicate of #9699 and #9676. Fixed in  #9723.

**Closed by johnny-bit** 2021-08-06 14:14 UTC
Labels: duplicate, bug: fixed
