### ISSUE TITLE
Export Problems on Mac OS

### ISSUE THREAD

**Issue by jguneratne** [darktable-org/darktable#3963] opened 2019-12-30 21:32 UTC
**Describe the bug**
I am using Darktable 3.0 on a mid-2011 iMac, running OSX El Capitan (10.11.6) with AMD Radeon HD 6770M 512 MB graphics card. Open CL is not an option on this computer. I exported a batch of photos, most of which worked without a problem, but 5 of them exported completely black. I tried both .jpg and .tiff formats, but the format didn't make a difference. The photos that exported as black were using the same modules as the photos that exported without a problem, so I don't think it's related to the modules. I was able to open the 5 problem images in Darktable 3.0 on my laptop (mid 2012 MacBook Pro, running OSX Mojave with Intel HD Graphics 4000 1536 MB, Open CL support activated in Darktable), and the photos exported without a problem. 

**To Reproduce**
 I don't know how to reproduce the problem because it only happens on certain images, and the modules used are the same as photos that export correctly. 

**Expected behavior**
I would expect photos to export as they appear in their RAW format after developing in Darktable, not as an entirely black frame.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Mac OSX 10.11.6 El Capitan
 - OpenCL not available for this computer 
 - AMD Radeon HD 6770M 512 MB 

**Additional context**
Clearing the history stack did solve the problem for one of the image.

**Comment by MStraeten** [comment] 2019-12-31 06:39
please check if filmic rgb is used with rgb power norm like in https://github.com/darktable-org/darktable/issues/3865. 
then the issue is fixed with https://github.com/darktable-org/darktable/pull/3890 in current master. Maybe check with https://discuss.pixls.us/t/current-osx-build/13213/46

**Comment by jguneratne** [comment] 2020-01-03 16:14
Thanks for your reply. I read through #3865, but I'm not a developer so I don't know how to check the power norm. Can you please describe the process for checking/troubleshooting?

I should also add that my images are not black in either the lighttable or darkroom modules, only black upon export.

**Comment by MStraeten** [comment] 2020-01-03 18:04
Have a look on the second tab of the filmic rgb module - check the setting of ‚preserve chrominance‘ - there you can select luminance Y or max rgb instead.

**Comment by jguneratne** [comment] 2020-01-04 17:54
Yes, Filmic RGB is used with RGB power norm, both in my images that exported correctly and that exported as black. I didn't change this setting during the develop process of the images. Do you suggest changing it to solve the problem, or is the ideal setting?

**Comment by MStraeten** [comment] 2020-01-04 18:48
Ok, then you can try a build of current master where the issue is fixed or switch to luminance Y or rgb max -  these modes have slightly different color effects (more intensive red or blue) - it’s explained in https://youtu.be/zbPj_TqTF88

**Comment by jguneratne** [comment] 2020-01-05 21:50
Thanks. Changing to either Luminance Y or Max RGB results in images that export correctly.

**Comment by aurelienpierre** [comment] 2020-01-13 20:39
Duplicate of #3865

**Closed by aurelienpierre** 2020-01-13 20:39 UTC
