### ISSUE TITLE
Unable to edit single image from folder

### ISSUE THREAD

**Issue by michmill1970** [darktable-org/darktable#18043] opened 2024-12-22 17:27 UTC
### Describe the bug

In previous versions of Darktable I could right click on an image in Finder (Mac) and open the image in Darktable.  Darktable would then open the image in the darkroom view for editing.

In 5.0, the image doesn't open in darkroom view.  If Darktable is not currently running, the image and the folder are not visible in the collections section of the lighttable view. If Darktable is running, the image and folder are visible in the collections.

### Steps to reproduce

On MacOS 14.7.1 and Darktable IS NOT running
1. Open a folder in macOS finder that contains an image
2. Right click on the image and open with Darktable

### Expected behavior

Open the image in Darkroom view like it did in 4.8.1

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

5.0

### What OS are you using?

Mac

### What is the version of your OS?

macOS 14.7.1 Sonoma

### Describe your system?

M1 MacBook Pro.  64 GB RAM, 1 TB SSD

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Apple M1

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I've reproduced the issue on 2 different machines.  One machine has a default darktable.rc file, the other has Library=:memory:.

**Comment by zisoft** [comment] 2024-12-22 17:42
duplicate of #17539 

This is a restriction we have to live with on macOS. It was necessary to fix a crash on import (see https://github.com/darktable-org/darktable/pull/17298).

On macOS it is not possible to distinguish between only a single file passed as parameter on command line or multiple files, so we do not request to open the darkroom here.

**Closed by zisoft** 2024-12-22 17:42 UTC
Labels: scope: macos support
