### ISSUE TITLE
Canon RF50mm F1.8 STM misrecognised as RF50mm F1.2 L USM

### ISSUE THREAD

**Issue by robintschoetschel** [darktable-org/darktable#11581] opened 2022-04-21 08:09 UTC
**Summary
Canon RF50mm F1.8 STM  is misrecognised as RF50mm F1.2 L USM despite exiv2 showing the correct information

** To reproduce
Import the sample image in darktable 3.8.1 (mac os x) and check image information

** Platform
Mac OS X 12.3.1
Darktable 3.8.1. (dmg from https://www.darktable.org/install/)

```
$ exiv2 --version
exiv2 0.27.2
$ exiv2 -pv --grep lens/i IMG_0001.JPG 
0x0016 CanonCs      LensType                    Short       1  61182
0x0017 CanonCs      Lens                        Short       3  50 50 1
0x0095 Canon        LensModel                   Ascii     138  RF50mm F1.8 STM
0xa432 Photo        LensSpecification           Rational    4  50/1 50/1 0/1 0/1
0xa434 Photo        LensModel                   Ascii      16  RF50mm F1.8 STM
0xa435 Photo        LensSerialNumber            Ascii      11  1101002771
```

Sample image: https://user-images.githubusercontent.com/27958524/164408818-a3dfa0d0-0a1e-40eb-b19c-dd4994a9adaa.JPG

**Comment by kmilos** [comment] 2022-04-21 10:03
Possible duplicate of https://github.com/darktable-org/darktable/issues/10070 and other Canon lens identification issues, especially with RF lenses (they all have a shared `CanonCs.LensType=61182`).

A temporary workaround is to put in your `~/.exiv2` config file:

```
[canon]
61182=0
```

In which case you will get the correct `Photo.LensModel`, without the "Canon" prefix though...

**Comment by robintschoetschel** [comment] 2022-04-21 10:12
> Possible duplicate of #10070 and other Canon lens identification issues, especially with RF lenses (they all have a shared `CanonCs.LensType=61182`).
> 
> A temporary workaround is to put in your `~/.exiv2` config file:
> 
> ```
> [canon]
> 61182=0
> ```
> 
> In which case you will get the correct `Photo.LensModel`, without the "Canon" prefix though...

Thanks!

**Closed** 2022-06-24 19:18 UTC
Labels: no-issue-activity
