### ISSUE TITLE
Fujifilm X-A10

### ISSUE THREAD

**Issue by michalzkosmosu** [darktable-org/darktable#3585] opened 2019-11-27 09:13 UTC
So far, the RAW files from my camera, Fujifilm X-A10, have not been running in any software available on Linux – neither Darktable nor RawTherapee. With hope I was checking every version of both programs, but it was always the same – the RAF files didn't even open. Since I only use Linux, it means that my camera is lying unused. Recently in version 4.7 of RawTherapee for the first time something changed – the RAF files started to open and some sliders even work (like an exposure), but others don't do anything (like a color mixer). They still don't even open in Darktable. It would mean a lot to me if I could use this camera in Linux.

Sample RAF: http://www.robmydobrze.pl/pliki/DSCF6141.RAF
(I tried to add it to raw.pixls.us, but it said someone had already done it.)

I use Xubuntu 19.10 and Darktable 2.6.3 (snap).

**Comment by LebedevRI** [comment] 2019-11-27 09:14
Duplicate of #3534.

**Closed by LebedevRI** 2019-11-27 09:14 UTC
Labels: camera-support
