### ISSUE TITLE
Doesn't handle HEIF/HEIC mirroring

### ISSUE THREAD

**Issue by g2p** [darktable-org/darktable#13321] opened 2023-01-10 15:06 UTC
Follow-up to [this comment](https://github.com/darktable-org/darktable/issues/13306#issuecomment-1375968666) on #13306, I can confirm that Darktable 4.2.0 (built here with fully updated dependencies, Exiv2 BMFF…: https://github.com/flathub/org.darktable.Darktable/pull/100) displays https://raw.githubusercontent.com/link-u/avif-sample-images/master/kimono.mirror-horizontal.avif mirrored: the character looks to the left, when I open in Firefox or eog it looks to the right.  The orientation module has no effect.

Needs something like https://github.com/strukturag/libheif/pull/555 to fix.

**Comment by kmilos** [comment] 2023-01-10 15:11
As I already explained, we turn any image transformation in both libheif and libavif off currently, because we cannot reach the same functionality with the two libraries at the moment (libheif 1.14.2 and libavif 0.11.1).

So this is by design.

Any transformation (rotation) that was done in https://github.com/darktable-org/darktable/issues/13306 was a side-effect of Apple putting orientation in Exif which is handled like it is for any other format like JPEG via the orientation module (and works incidentally because we turned transformations off in libheif).

**Comment by kmilos** [comment] 2023-01-10 15:13
[When libheif exposes the same functionality as libavif](https://github.com/strukturag/libheif/pull/555), this can be perhaps revisited, but for now I don't see a better way of handling this than having to manually use the orientation module for this formats at the moment (apart from Apple files that have the Exif data).

**Comment by kmilos** [comment] 2023-01-11 10:47
@Nilvus It actually might be an idea to leave this open (and include AVIF & rotation in the title) - we'll have to revisit this anyway once libheif gets this capability, so maybe better not to leave the risk for it to slip through?

(#13306 will get closed when the PR is merged...)

**Comment by Nilvus** [comment] 2023-01-11 17:39
@kmilos: ok but so maybe #13306 is a duplicate to close instead of that one or you consider those 2 different issues?

**Closed** 2023-07-24 08:37 UTC
Labels: bug: upstream, understood: clear, no-issue-activity
