### ISSUE TITLE
Collection filter modes not working (or very unintuitive)

### ISSUE THREAD

**Issue by CarlAndersson** [darktable-org/darktable#14944] opened 2023-07-25 10:40 UTC
### Describe the bug

The "and not" mode on a collection filter gives me the exact same results as the "and" mode.
Tested with filename, rating, and search filters.
The "or" mode is also not doing what it says, e.g.
```
rating 
    all
or filename
    PC230370
```
will match only the single file. It should match all files since they all have any rating, thus matching the first half of the "or" operation.
Testing something simple like
```
rating
    all
or rating
    all
```
returns no matching images, which does not make sense at all.

### Steps to reproduce

1. Open a collection with at least two images
2. Add a new collection filter of the "filename" type
3. Set the filename filter to the filename of one of the files
4. Toggle the filter to ensure it's working
5. Set the "combination operator" to "and not"
6. Toggle the filter - it keeps the same image as in "and" mode

### Expected behavior

Remove the matched images, not show only those.

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2, also tested with 4.2.1

### What OS are you using?

Mac

### What is the version of your OS?

12.6.7

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment] 2023-08-04 10:19
I tried all the steps you described and cannot reproduce.
For me, everything works exactly as expected.

Are you sure there is no other filter active on your side?

**Comment by CarlAndersson** [comment] 2023-08-04 19:29
Quite sure, unless there's something I'm missing in the interface.
Check the screen recording for a demonstration of this behavior.


https://github.com/darktable-org/darktable/assets/20397548/1d105557-3469-4e2b-b676-f214bdc57181

**Comment by zisoft** [comment] 2023-08-05 06:06
Can still not reproduce on current master: 


https://github.com/darktable-org/darktable/assets/4083281/8c4bdef4-bd01-4e01-8ec0-0002fce6378c

**Comment by victoryforce** [comment] 2023-08-18 14:14
I manage to reproduce the bug.

> Can still not reproduce on current master

@zisoft The "steps to reproduce" specified in the issue must be performed not on the default state of the filters, but when there are no other filters. Exactly as we see in the video attached to the issue. If there are other filters in front, the problem does not appear.

**Comment by zisoft** [comment] 2023-08-18 19:31
@victoryforce: Thanks for pointing that. The pinned filters are always active so I could not reproduce.

I think I have fixed this, can you please verify?

**Comment by victoryforce** [comment] 2023-08-18 20:31
Yeah, I'll check tomorrow.

**Comment by victoryforce** [comment] 2023-08-19 19:04
> I think I have fixed this, can you please verify?

This particular bug has been fixed by your PR, but unfortunately it introduces another problem. More details in the comment to PR.

**Closed** 2023-08-21 13:35 UTC
Labels: reproduce: confirmed, scope: UI
