### ISSUE TITLE
Halos/artifacts with contrast equalizer

### ISSUE THREAD

**Issue by Mangus78** [darktable-org/darktable#9255] opened 2021-06-16 09:43 UTC
I always encountered this strange behaviour:
when I activate contrast equalizer, pushing up the contrast in the mid-coarse frequency area, even just a little bit, it introduces strange halos.
Here an example but I can reproduce it with every single images from different cameras with the same parameters:
![immagine](https://user-images.githubusercontent.com/7537334/122196150-451f6100-ce97-11eb-90c6-ed30e18092e6.png)

If I pull up a little bit the mid-coarse frequencies, that happens (see under the cat belly):
![immagine](https://user-images.githubusercontent.com/7537334/122196419-857edf00-ce97-11eb-90e3-d1bafd07d77e.png)

With the new "details threshold" slider, if I set it a little bit to the left, the halos almost disappear:
![immagine](https://user-images.githubusercontent.com/7537334/122196672-b8c16e00-ce97-11eb-98ff-3b4ae5a11c9b.png)

I'm using the latest github version compiled from source but I can reproduce it even with older stable versions and on different PCs.

I'm on ubuntu 21.04, openCL with different Nvidia cards on 3 different pc.

**Comment by aurelienpierre** [comment] 2021-06-16 09:47
For the record, this is a fringe, not a halo. Please post the RAW + XMP.

**Comment by Mangus78** [comment] 2021-06-16 10:07
Just tried something and it seems to appear when the contrast equalizer is used in combination with the tone equalizer set with a contrast tone curve (similar behaviour using a tone curve for the same thing).
![immagine](https://user-images.githubusercontent.com/7537334/122199813-bd3b5600-ce9a-11eb-8f72-f7bb6a9b6869.png)
![immagine](https://user-images.githubusercontent.com/7537334/122199875-cb897200-ce9a-11eb-9fde-732c12b197ba.png)

[DSCF5902.zip](https://github.com/darktable-org/darktable/files/6662113/DSCF5902.zip)

**Comment by wpferguson** [comment] 2021-06-16 15:19
Have you tried adjusting the edges curve in contrast equalizer?  It's purpose is to control halos

**Comment by elstoc** [comment] 2021-06-16 20:40
See [the manual](https://darktable-org.github.io/dtdocs/module-reference/processing-modules/contrast-equalizer/#edge-tab) for illustrations of the effect you're describing. The edges curve can indeed be used to mitigate this.

**Comment by Mangus78** [comment] 2021-06-17 13:13
> See [the manual](https://darktable-org.github.io/dtdocs/module-reference/processing-modules/contrast-equalizer/#edge-tab) for illustrations of the effect you're describing. The edges curve can indeed be used to mitigate this.

Yes I tried looking at the manual, the edge tab does something indeed, but it must be pushed real hard down to obtain some results, against just a little increase of the luma tab. Is it normal?
![immagine](https://user-images.githubusercontent.com/7537334/122403213-7aeb4500-cf7e-11eb-83ed-cf6c7a5d50c6.png)


Btw, i've used the wrong definition, it's more an artifact than an halos

**Comment by elstoc** [comment] 2021-06-17 13:37
> Is it normal?

Sorry I just know to play around with that curve when I see edge artifacts. I mostly use trial and error.

**Comment by johnny-bit** [comment] 2021-06-17 14:58
You're using tone equalizer in detail non-preserving mode and you're using sharpen after contrast equalizer (meaning you do double sharpening). The halos/fringes are made invisible on several conditions:

- use tone equalizer with edge-aware mode and detail preservation (makes feathers look better and thus alows for less sharpening)
- drop use of sharpen module (it's more prone to halos/fringes)
- adjust edges

if you combine above 3 the results will be more pleasing overal.

Also: it's IMO not a bug, quite contrary: you wanted double sharpening, you got double sharpening :) So app does what's asked for :P

Would you consider closing the issue?

**Comment by Mangus78** [comment] 2021-06-17 15:10
> You're using tone equalizer in detail non-preserving mode and you're using sharpen after contrast equalizer (meaning you do double sharpening). The halos/fringes are made invisible on several conditions:
> 
>     * use tone equalizer with edge-aware mode and detail preservation (makes feathers look better and thus alows for less sharpening)
> 
>     * drop use of sharpen module (it's more prone to halos/fringes)
> 
>     * adjust edges
> 
> 
> if you combine above 3 the results will be more pleasing overal.
> 
> Also: it's IMO not a bug, quite contrary: you wanted double sharpening, you got double sharpening :) So app does what's asked for :P
> 
> Would you consider closing the issue?

I humble disagree.
Even without sharpen and disabling the tone equalizer, I notice almost the same behaviour.
Yes, disabling the tone equalizer it gets better, but not so much indeed.
I usually use the tone equalizer without edge-aware with the "simple tone curve" preset, but maybe I will use the "tone curve" module instead even if it isn't "pure rgb approved".

The sharpen module is very useful if used without pushing it too much, in achieves great results.
I know that it is not suggested anymore, I can deal with it but why the relative option is still enabled by default in the options? Maybe it would be better disabled or removed entirely in the options panel. 

Anyway, thanks for the answers, I didn't know exactly and I supposed it could be a bug. If you think so, I can close the issue.

**Comment by aurelienpierre** [comment] 2021-06-17 15:51
This doesn't look like a programmatic issue (aka solution lies in code) but rather like an algorithmic issue (aka solution lies in math). It's basically a gradient reversal. There is no way to fix that, except rewriting the module with a completely different algo (which will probably have different side effects).

**Comment by johnny-bit** [comment] 2021-06-17 17:26
So to sum up - it's not a bug, to alleviate the issue you'd need to use (and somebody would have to develop) totally different module(s) based on different alogo(s).

There are side possibilities by using masks etc to sharpen specific patches that avoid gradient reversals, manually tuning different parts etc.

I'm closing as "not a bug", really.
TBH: there are no solutions, only tradeoffs.

**Closed by johnny-bit** 2021-06-17 17:26 UTC
Labels: bug: invalid
