### ISSUE TITLE
moving images fails, leaves xmp files in "from" directory.

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#4438] opened 2020-03-07 22:15 UTC
openSUSE Tumbleweed 20200305
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable 3.1.0~git796.3375f4f83
OpenCL on 
i7 12-core 36GB

opened dt to a collection on local drive containing 25 jpg images and matching xmp files.
selected all images
created directory on remote drive
selected "move" answered yes
the 25 jpg images were moved to the new location but the matching xmp files remained

it confused dt (lightroom), which thought or appeared to think images were in both location.
physically moved xmp files to new location.
dt still showed thumbs in both location but when attempting to open one of the images in darkroom mode, complained that image was not available.

selected entire collection in both locations and removed from dt
imported collection in new location and all appears well.

did not attempt again but can if needed.

**Comment by ptilopteri** [comment] 2020-03-07 23:15
attempted to select all images and move them back to a local drive in a different directory
dt asked if I really wanted to do this and I said "yes".
nothing happened, repeated and again nothing happened.  No images were moved.

removed collection from dt
physically moved the images back to a local drive in a new directory using mc
imported images
selected all images in collection and selected "move"
selected location and answered "yes"
images were moved to new location but xmp files were not moved.

**Comment by GrahamByrnes** [comment] 2020-03-08 11:21
Replicated the first step under Windows10, just moving to another subfolder, ie testfolder/test3 -> testfolder/test4.

**Comment by TurboGit** [comment] 2020-03-08 15:36
Now fixed.

**Closed** 2020-03-08 15:36 UTC

**Comment by ptilopteri** [comment] 2020-03-08 16:08
> Now fixed.

@TurboGit 
partially

I just selected a group and moved them successfully with xmp files

but selecting the group again to move again and initiating move
COPIES the images and xmp files to the new location and updates the library.db 
but does not remove the copied files.

please reopen

**Comment by TurboGit** [comment] 2020-03-08 16:54
@ptilopteri : I cannot reproduce that. I have tested with 3 images selected or with a group of 3 images. Moving to one new directory all copied with XMP (1 NEF and 3 xmp) moving back to previous location, all was copied and the new directory removed.

Anyway specific step to reproduce ? Which OS ?

**Comment by ptilopteri** [comment] 2020-03-08 17:31
disregard, pbkac

thanks much
