### ISSUE TITLE
RFC: Get rid of the 'Commit' button in the crop module

### ISSUE THREAD

**Issue by zisoft** [darktable-org/darktable#13657] opened 2023-02-17 08:00 UTC
I find the 'Commit' button in the crop module confusing because clicking on it simply does nothing.
There is also no visiual feedback when clicking on it.

It is not even mentioned in the user manual.

According to the manual the crop is applied when giving focus to another module, so what's the purpose of this button?

**Comment by Nilvus** [comment] 2023-02-17 20:56
When I first read your issue, I was asking myself: what commit button he talks about? I even didn't notice it for reasons you precise there. And I confirm that I reproduce your issue. This button just do nothing. @AlicVB: as you develop that module, what's your view on that one?

Maybe we could get rid of that one.

**Comment by AlicVB** [comment] 2023-02-17 21:21
that's quite funny because I just see it too...
git blame says that it comes from @dterrahe work on inputNG, in april 22 (!)

@dterrahe : I suppose that this is needed to allow a shortcut for crop applying ? In this case maybe we can hide it somehow ?

That said, I'm quite sure to know why it does nothing. This is certainly due to recent work that avoid unneeded pipe compute. I can certainly restore that, but I'm quite doubtful it has worked well (if we allow to apply a crop to the image while the module still focused, how to change crop again ?

**Comment by dterrahe** [comment] 2023-02-17 21:47
> In this case maybe we can hide it somehow ?

If there is a reason for the shortcut, then there is a reason for the button. If there isn't, both can be removed.

At the time I just converted pre-inputng accelerators to new-style ones and this was one of the few (the only one maybe) that was per-module without a widget, which isn't supportable anymore. I didn't extensively test the code _behind_ the shortcuts (but maybe I assumed that with a new visible button people would sooner start to wonder what it did, if anything :-) ).

But as you say, even _if_ it was needed previously, I don't think it is now.

**Comment by spaceChRiS** [comment] 2023-02-17 22:34
I was wondering the same, but I think there is at least something this button could/should do. I often struggle with what to do when I found a suitable crop and want to see it applied, but I do not have a module in mind to go to next, because I want to check how the crop looks like. Currently I have to select some other module to remove focus from the crop module to get the crop applied. It would be much more intuitive if the button would just remove focus from the crop module without closing it (if this is technically possible) to apply the crop without the need to select another module.

If the button would change to “change crop” if the module is not in focus and clicking it would re-focus the module and allow to change the crop, this would IMO make an intuitive and sound concept.

**Comment by HSUfineprint** [comment] 2023-02-18 02:26
If the button could be "show cropped image (viewing mode)" and "change crop (edit mode)" switcher will be fine. That we can adjust crop area by actually seeing without de-focus refocus the module.

**Comment by AlicVB** [comment] 2023-02-18 16:37
To resume (correct if I'm wrong) : 
1. this feature is broken from a long time, without any user complains -> this might indicate that this is not really used !
2. we may want to add a "new" feature to crop module, in order to "apply" the crop

Considering that, I would say that we need to remove the button first (esp. for 4.2.1 if not too late @TurboGit  ?) and try to implement 2.
This won't be straightforward, as module focus is a quite delicate area. If what we want to achieve is "just" to "see better" the crop effect on the image, we can also image that the button make the cropped area completely opaque. That would have the advantage to not touch the module focus, and to allow further recropping...

Tha bad news is that I have very few free time this days (until end of april at least), so I can remove the button, but someone will have to handle point 2. (or we have to wait...)

**Comment by Nilvus** [comment] 2023-02-18 17:16
As you said, we have no user complaints so point 2 could wait.

Having point 1 for 4.2.1 would be good.

**Comment by dterrahe** [comment] 2023-02-18 18:00
I'm not sure I see the big problem with collapsing the crop module (and thereby removing its focus) to see the result of the crop. There's not that much info in it you'd want to continue reading anyway. Or ctrl-clicking on the "stand-by" button (which is the "official" way of just removing focus). I just fear that by having many duplicate ways of achieving the same thing (removing focus) we make it _less_ clear what is happening. Magical thinking would make users click everything just be sure. Maybe twice for good measure and in different orders. And we'd have to add the same button to all the other similar modules (rotate+presp, gd, vignetting). To me, the header of the crop module does _exactly_ what is being described as the function of this supposedly necessary new button.

**Comment by zisoft** [comment] 2023-02-18 18:56
> Tha bad news is that I have very few free time this days (until end of april at least), so I can remove the button, but someone will have to handle point 2. (or we have to wait...)

If you are busy I can remove the button and provide a PR tomorrow, just let me know.

**Comment by AlicVB** [comment] 2023-02-18 20:45
> If you are busy I can remove the button and provide a PR tomorrow, just let me know.

thanks a lot, but I just see your msg once I have proposed the PR ;)

**Closed** 2023-02-19 16:35 UTC
Labels: feature: redesign, scope: UI, bug: pending
