### ISSUE TITLE
color calibration: some adaption settings breaks processing with opencl on intel gpu

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#9318] opened 2021-06-22 21:28 UTC
activating color calibration with 
adaption = linear Bradford or CAT16 or XYZ
and
"clip negative RGB from gamut" is unchecked
breaks OpenCL processing using intel on-cpu gpu
 
**To Reproduce**
1. edit opencl_device_priority to force preview or full pixel pipe to be processed on the intel gpu
2. activate color calibration
3. uncheck "clip negative RGB from gamut"
4. select adaption linear Bradford or CAT16 or XYZ
5. preview or full is black according to step 1

**workaround:**
the b/w setting are defined without having "clip negative RGB from gamut" checked
So maybe checking clip negative RGB from gamut in the presets might be a temporary solution

**Platform**
* darktable version : darktable 3.5.0+2648~g5586d4178
* OS                :  OSx
* Graphics card     : 
0.193262 [opencl_init]		0	'Intel(R) UHD Graphics 630'
0.193268 [opencl_init]		1	'AMD Radeon Pro 5500M Compute Engine'

**Comment by MStraeten** [comment] 2021-06-23 06:50
wasn't able to reproduce this with an intel on-cpu gpu with win10

**Comment by johnny-bit** [comment] 2021-06-23 06:58
Soo... The issue is about Intel(R) UHD Graphics 630 OpenCL on OSX... You say that Win10 is not affected. Can you check if linux is affected or is it just limited to Intel on-cpu GPU on OS X?

**Comment by jade-nl** [comment] 2021-06-23 07:04
This does not seem OSX specific.

I'm running Linux (Debian 10/Buster) on an AMD CPU with an NVidia Graphics card and can reproduce this behaviour.

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.10)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Hardware**

* CPU              : AMD Ryzen 5 3600 6-Core Processor
* GPU              : GeForce RTX 2060 SUPER 7979 MiB

**Comment by MStraeten** [comment] 2021-06-23 08:42
Since no longer osx specific it seems to be a duplicate to #9315

**Comment by aurelienpierre** [comment] 2021-06-23 09:35
Won't fix. If you don't clip negatives in the program, then you leave the NaN handling to the driver's heuristics.

**Closed by aurelienpierre** 2021-06-23 09:35 UTC
Labels: bug: pending, scope: image processing

**Comment by johnny-bit** [comment] 2021-06-23 09:43
@aurelienpierre - sure, however:

> So maybe checking clip negative RGB from gamut in the presets might be a temporary solution

the B&W presets don't clip negatives. Proposed workaround would solve the issue?

**Comment by aurelienpierre** [comment] 2021-06-23 10:57
ah, then just edit presets.

**Comment by johnny-bit** [comment] 2021-06-23 11:11
OK, - pr here: https://github.com/darktable-org/darktable/pull/9322
