### ISSUE TITLE
lighttable: collection module height cannot be adjusted when in folder view

### ISSUE THREAD

**Issue by 01McAc** [darktable-org/darktable#9708] opened 2021-08-02 16:07 UTC
In my folder view in lighttable there are heaps of folders I imported to dt. I can only see a tiny bit of them as the module is too small. So there is actually more to display. Issue: _Ctrl+Scroll mouse doesn't work when in folder view_ but it does work when in film roll view. See #1 in screenshot 
![Screenshot_20210802_154934](https://user-images.githubusercontent.com/88337479/127890609-b97af715-7c7e-48c9-9bb1-158bae962ee5.jpg)

**Comment by TurboGit** [comment] 2022-03-04 12:56
I cannot reproduce this.

**Comment by TurboGit** [comment] 2022-03-04 12:56
@elstoc : How did you reproduced?

**Comment by TurboGit** [comment] 2022-03-04 15:51
AFAIK we are not rewriting the collection module but the collection filtering (a new lib module).

**Comment by elstoc** [comment] 2022-03-04 15:56
@TurboGit see [this comment](https://github.com/darktable-org/darktable/pull/10733#issuecomment-1015826610). That PR's changes have already impacted the Ctrl+scroll functionality.

**Comment by TurboGit** [comment] 2022-03-04 16:59
Indeed, anyway since I cannot reproduce let's close this for now.

**Closed by TurboGit** 2022-03-04 16:59 UTC
Labels: reproduce: confirmed, scope: UI, bug: pending, no-issue-activity
