### ISSUE TITLE
DT segfaults when applying feathering radius during cloning in retouch module

### ISSUE THREAD

**Issue by rkc-rkc** [darktable-org/darktable#3076] opened 2019-10-04 17:01 UTC
**The BUG**
DT freezes and eventually segfaults when applying feathering radius in retouch module.

**Steps**
- Select retouch module
- Select cloning tool
- Using 'path' tool add a cloning region
- Change blend option to 'parametric mask'
- Adjust feathering radius
- DT freezes and eventually segfaults

**Platform**
Ubuntu 18.04.3
Version 2.6.2 from PPA

Backtrace : [darktable_bt_SUA38Z.txt](https://github.com/darktable-org/darktable/files/3691538/darktable_bt_SUA38Z.txt)

**Comment by TurboGit** [comment] 2019-10-05 16:24
Cannot reproduce with last dev version. Maybe fixed. Closing for now.

**Closed by TurboGit** 2019-10-05 16:24 UTC
