### ISSUE TITLE
Extra tags added on export

### ISSUE THREAD

**Issue by jefflundberg** [darktable-org/darktable#9999] opened 2021-09-13 22:16 UTC
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

Extra tags are added on export

**To Reproduce**
1. Add tag `5` to an image in a collection
2. Add tag `52` to a different image in the same collection
3. Export the image tagged as `52` as a JPEG (8-bit)

**Actual behavior**

The image has tags `5` and `52`

**Expected behavior**

The exported image should only have the tag `52`

**Screenshots**
![image](https://user-images.githubusercontent.com/62454/133162599-c63a467c-c268-46be-915b-ceedb1c6bc7b.png)

![image](https://user-images.githubusercontent.com/62454/133162683-7e60efca-88dd-460a-a113-9a8b40320a45.png)

**Platform**

* darktable version : 3.6.0
* OS                : Win10 (19043.1202)

**Additional context**

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
[xmp.txt](https://github.com/darktable-org/darktable/files/7157608/xmp.txt)

**Comment by elstoc** [comment] 2021-09-13 22:23
This might be a duplicate of https://github.com/darktable-org/darktable/issues/9949

**Comment by domosbg** [comment] 2021-09-18 07:34
Tested it with 3.6 -> works as described -> buggy
Tested it with the last windows insider preview (3.7.0+1046) -> bug is fixed. Tags on the exported images are as expected.

Windows insider program version can be downloaded under:
[https://discuss.pixls.us/t/darktable-insider-program-9-12/26908](https://discuss.pixls.us/t/darktable-insider-program-9-12/26908)

Installation instructions and hints can be found here:
[https://discuss.pixls.us/t/darktable-windows-insider-program/25740](https://discuss.pixls.us/t/darktable-windows-insider-program/25740)

**I recommend to read and understand the installation instructions before the installation of the preview in order to avoid influencing the production installation of darktable 3.6.**

I think, the issue can be closed.

**Comment by johnny-bit** [comment] 2021-09-18 08:36
Thanks for confirming @domosbg

**Closed by johnny-bit** 2021-09-18 08:36 UTC
Labels: duplicate, scope: DAM, bug: fixed
