### ISSUE TITLE
darkroom view: shortcut Alt+2 can produce a constant flickering / jittering

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#4286] opened 2020-02-13 15:10 UTC
**Describe the bug**

In darkroom view: In certain cases using the Alt+2 shortcut to zoom fill an image causes the image area to constantly jitter/flicker (_seizure_ if you want). It can be stopped by using Alt+1 or Alt+3.

**To Reproduce**

0. start darktable development version (easier to recreate conditions that lead to this behaviour)
1. preferences -> GUI options -> *show scrollbars for center view* should be set to *lighttable + darkroom*
2. open a roughly 4:3 image in darkroom view that is larger than the available image area
3. enable the filmstrip
4. adjust the height of the filmstrip and/or the side panels to make the image fit nicely. As in: borders around the image are as small as possible and evenly thick on all four sides (see screenshot below)
5. press Alt+2 (Alt+1 or Alt+3 to stop the jitter)

**Expected behavior**

Alt+2 to zoom fill the image as advertised.

**Screenshots**
This shows the layout and borders needed as mentioned in reproducibility step 4:
![Screenshot_2020-02-13_15-40-18](https://user-images.githubusercontent.com/56407344/74445936-7806ae80-4e77-11ea-857e-cec6fcbffc88.png)

**Platform:**

* darktable Version:
&nbsp;&nbsp;&nbsp;Stable 3.0.0
&nbsp;&nbsp;&nbsp;Development 3.1.0+639
* OS     : Linux - kernel 4.19.0-8-amd64
* Distro : Debian Buster (rel. 10.3)
* Graphics card   : NVIDIA GF104 [GeForce GTX 460] (rev a1)
* Graphics driver : NVIDIA x86_64 Kernel Module 390.116
* OpenCL activated : No
* Xorg : 7.7+19
* GTK+ : 3.24.5-1

After confirming the issue I filed this report on behalf of someone else, that user's specs are:

* darktable version : development 3.1.0-584
* OS : Linux 4.15.0-76
* Distro : Ubuntu 18.04.3 LTS
* Graphics card : Nvidia GeForce RTX 2060
* Graphics driver : Nvidia Driver 430.50
* OpenCL activated : Yes
* Using X11
* GTK+ : 3.22.30-1ubuntu4

**Additional context**

 - I filed this on behalf of someone else who mentioned it on pixls.us: [This thread](https://discuss.pixls.us/t/bug-darkroom-shortcut-alt-2/16392)

 - Can you reproduce with another Darktable version?
Seen in both stable 3.0 and mulitple development versions (+584, +615, +621 and +639)

 - Can you reproduce with a RAW or Jpeg or both?
Don't think it is relevant but: Yes, seen with both RAW and jpeg images.

 - Is the issue still present using an empty/new config-dir
Yes, it is. Starting clean (no files in config dir) doesn't change anything.

**Comment by mcv100** [comment] 2020-02-17 01:41
Can confirm this bug on 3.10+665 on Windows 10, with OpenCL activated on an AMD RX 480.

I don't need any of the steps to reproduce (also not the GUI scrollbar setting); just resize the Darktable window untill the unzoomed image fills the grey area. Then press Alt + 2 and the jittering starts.

**Comment by jade-nl** [comment] 2020-03-19 11:34
This has not yet been picked up by anyone.

**Comment by jenshannoschwalm** [comment] 2020-03-19 15:16
Hi @jade-nl, i have observed some flickering as you describe in a totally diffent situation while doing wrong stuff with the color picker. Since the last of my commits i haven't seen it again. Nevertheless i suspect some re-triggering/re-entrance of pipeline recalculation, but don't understand the problem yet.

Could you check again with today's master - (some things in darktables redrawing have changed over the last weeks)? If still existing i would look at it. @TurboGit ping!

**Comment by jade-nl** [comment] 2020-03-19 15:43
I just tried to repeat this on master (3.1.0+967) and I cannot get it to flicker. Retried on stable 3.0.1 and it does flicker.

I reported this one for someone on pixls.us. I'll ask if he can check on his side and will report back.

**Comment by jade-nl** [comment] 2020-03-19 16:46
This was just posted by the person I reported this for:

_dt 3.1.0+811 : flicker/jitter as described.
dt 3.1.0+963 : the flicker/jitter does no longer appear. The reason for this different behaviour is, that the setting GUI options -> miscellaneous -> show scrollbars for center view -> ligthtable and darkroom is now completely ignored. Instead of keeping the magnification and showing scrollbars, the image is now scaled down if sidebars are widened or filmstrip is made higher._

_One bug has been replaced by an other… , or the feature to have scrollbars is gone :cry: ._

I used Alt-2 and Alt-3 so I did not notice this when checking in my previous reply. I can confirm what he's saying though: Scrollbars are a goner....

**Comment by jenshannoschwalm** [comment] 2020-03-19 17:05
> setting GUI options -> miscellaneous -> show scrollbars for center view -> ligthtable and darkroom is now completely ignored. Instead of keeping the magnification and showing scrollbars, the image is now scaled down if sidebars are widened or filmstrip is made higher.

> Scrollbars are a goner...

Personally i didn't use scrollbars while testing - never user them in fact. I just tried and can't see any problem. 3.1.0+967 on fedora31. Also i see a border as usual and defined by option. Of course the sliders are only visible if scaling requires it. So what **exactly** is the problem for me to understand precisely?

**Comment by jade-nl** [comment] 2020-03-19 17:32
> Personally i didn't use scrollbars while testing - never user them in fact.

Same here, but as a courtesy to another pixls.us user I investigated his problem and was able to reproduce it.

> So what exactly is the problem for me to understand precisely?

You are not able to reproduce this on dt 3.0.0 or 3.0.1 with the steps given in the first post I made? The 4:3 requirement isn't really needed, just makes fitting the image a bit easier.

As you know I'm not a developer but what I think is going on here is that an oscillation point is reached between these three states when you use Alt-2 (Zoom fill):
![sliders](https://user-images.githubusercontent.com/56407344/77095932-e4dd0d80-6a0e-11ea-93df-a67c42138ae9.png)

1 no scrollbars, 2 vertical scrollbar and 3 horizontal scrollbar. One state seems to cancel another state which calls for a third one, which cancels.... You hopefully get it.

**Comment by jenshannoschwalm** [comment] 2020-03-19 18:29
Ok i now see the scrollbars are disabled in some situations here too, this seems to interfere with the filmstrip switch. The flicker i can't reproduce so far. It seems - as you describe - to be related to the question: which scrollbar(s) should be displayed and when is this decision done.

I will have a look at it and fix it after understanding. Atm i have no clue as i have never touched that code before so this needs some time consuming code reading. Just hold on for a while ...

**Comment by jenshannoschwalm** [comment] 2020-03-21 15:43
I did a pr which has just been merged to master.

Could you check again about the "jitter"? What i see is a double resizing while enlarging but i can't see any sort of oscillation and after reading&understanding the code that seems very unlikely.

Could you check your testcase again and either close this issue or maybe record a video if still existing?

**Comment by jade-nl** [comment] 2020-03-21 16:47
One of the problems has been solved: The vertical and horizontal scrollbars are back (Thanks!).

The original problem however is still present: https://fromsmash.com/seJc~6twAE-dt

As you can see in the video I open an image in darkroom, resize the filmstrip to make it fit snugly and you see *working*.
Not long after that I press Alt-2 and you can see what happens. I used Alt-3 to make it stop.
I press Alt-1 and the scrollbars appear due to the larger size.
Press Alt-2 again and the jitter starts again, pressed Alt-3 to stop.

Used: darktable 3.1.0+999~gc250dda10

About the video: Not sure how long that is going to be available. If you miss it let me know I upload it again.

**Comment by jenshannoschwalm** [comment] 2020-03-21 17:30
ok. That really looks ugly :-)

I have to find a situation triggering this so i can get into debugging. I have a vague idea already ...

**Comment by jenshannoschwalm** [comment] 2020-03-22 05:53
Ok. I can reproduce now with other conditions than you described. Hold on

**Comment by jade-nl** [comment] 2020-03-22 15:32
Just rebuild and tested: jitters/seizure seems to be fixed. I'll ask if pehar agrees.

**Comment by jade-nl** [comment] 2020-03-22 17:19
Quoting pehar:

---start quote---
Just updated (master dt 3.1.0+1016). I can still force the jitter, but the behaviour is slightly different as before. Can be reproduced this way :

- preferences -> GUI options -> show scrollbars for center view should be set to lighttable + darkroom
- adjust the height of the filmstrip and/or the side panels to make the image fit nicely
- press Alt+2, no jitter (in contrast to before)
- widen sidebar (left or right) slowly, jitter starts when scrollbar (horizontal or vertical) is needed

If one moves the mouse faster when widening the sidebar, the jitter can not be forced anymore. The behaviour varies slightly depending on the hardware. On a new (fast) system (CPU with 6 cores, hyperthreading + Nvidia 2060 GPU) it is easier to force the jitter.
The actual behaviour is a considerable improvement, but there are still (rare) cases where jitter can occur. **In my opinion the actual status is OK.**
---end quote---

Closing this issue.

PS: Thanks @jenshannoschwalm for the time and effort!

**Closed** 2020-03-22 17:19 UTC
Labels: no-issue-activity
