### ISSUE TITLE
UI glitch - overlay in culling view

### ISSUE THREAD

**Issue by mlales** [darktable-org/darktable#3469] opened 2019-11-17 20:11 UTC
**Describe the bug**
Overlay with image info does not allways match the frame of the image,
depending on orientation and layout of images in view.

**Screenshots**
Example 1: This is OK:

![Culling 3a](https://user-images.githubusercontent.com/56188259/69013251-4a948c80-097e-11ea-859e-82dda87fab32.JPG)

Example 2:

![Culling 2a](https://user-images.githubusercontent.com/56188259/69013266-6a2bb500-097e-11ea-97d6-72f23d7891e8.JPG)

Example 3:

![Culling 1a](https://user-images.githubusercontent.com/56188259/69013273-83ccfc80-097e-11ea-9034-ce30ebda3ca2.JPG)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.0.rc1

**Comment by blitzgneisserin** [comment] 2019-11-18 09:40
Confirmed, dt 3.0rc1 for Linux

**Comment by arigit** [comment] 2019-12-14 00:17
Here's another glitch, where the image info and the color label is misaligned with the image. Looks like the label/info placement algorithm is not adapting well to culling mode.

These are pretty standard nikon nefs from a d500 in normal (full) resolution mode

![image](https://user-images.githubusercontent.com/652673/70839762-4ff9c100-1ddc-11ea-922d-2ccc3e8e4a04.png)

The misalignment in culling mode happens no matter how many NEFs I include in the culling view, even when working with a single image:

![image](https://user-images.githubusercontent.com/652673/70839870-f5149980-1ddc-11ea-8ffa-4d75cf5dd279.png)

Hoping this can be addressed before DT 3.0 final. I know this is cosmetics but many of us spend hours and hours in culling mode :)

**Comment by arigit** [comment] 2019-12-14 02:10
@TurboGit just for awareness/visibility. Not sure if this is a tough issue to address or hopefully a quick win. Hopefully the latter :)

**Comment by AlicVB** [comment] 2019-12-14 09:30
> Hoping this can be addressed before DT 3.0 final

nope, there's very little chance that it will happen : we are far too close to the release !
I'll try to have a look and fix it for 3.01, but no promise, as usual ;)

Note that it's not as simple as it seems because we need to keep some sort of uniformity for the overlays, and in culling each image has a different size (not to speak that the font as it's drawn actually is not adapted for small sizes...)

**Comment by arigit** [comment] 2019-12-14 17:53
Fully understood, thanks @AlicVB for jumping in! Culling mode is great - I'm sure there will be plenty more feedback coming in as people discover it and start to use it.

**Comment by arigit** [comment] 2020-01-21 04:14
Master branch not yet fixed, this may take some time. the 30 day period for this bot seems too short for DT's development cycles

**Comment by AlicVB** [comment] 2020-05-08 20:00
Should be fixed in master now

**Closed by AlicVB** 2020-05-08 20:00 UTC
Labels: feature: enhancement, no-issue-activity
