### ISSUE TITLE
idioma

### ISSUE THREAD

**Issue by gui89087i787656789** [darktable-org/darktable#16189] opened 2024-01-26 23:56 UTC
### Describe the bug

Quando eu mudo o idioma para portugues do brasil ele não mudar de idioma continua no portugues

### Steps to reproduce

configuração> linguaguens
![Captura de Tela (1)](https://github.com/darktable-org/darktable/assets/157856073/6de6f462-3573-4878-94f2-90281784942e)

### Expected behavior

mudar de idioma

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

windows 10

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by victoryforce** [comment] 2024-01-27 06:33
> Quando eu mudo o idioma para portugues do brasil ele não mudar de idioma continua no portugues

This description of the problem is not very clear, did you expect the language to change immediately? If so, it doesn't work like that, the language is changed for the next darktable run.

If the language has not changed even for the next run, then please show me your Regional settings in Windows.

**Comment by kasav81** [comment] 2024-01-27 11:55
I tried 4.6.0 under Gentoo Linux and had a similar problem, right after starting dt everything's in English, after opening an image and returning to the lighttable parts of the UI get translated while parts (like all presets) stay in English (the language in the settings menu is already set to German according to my systems localization). When starting darktable with --disable-opencl everything's displayed correctly but not after disabling opencl in the settings menu.
As recursive import isn't working under 4.6.0 I switched back to 4.4.2 which doesn't show any localization problems.
I even tried this under a Debian-VM with a passed through GPU and at the first start dt-4.6.0 showed the same behavior but from the second or third start everything was displayed correctly - this was with a completely empty db and on a freshly installed system though...

**Comment by gui89087i787656789** [comment] 2024-01-27 12:44
então denovo usar o app normalmente até ele se recuperar nas ediçãoes, demorou quanto tempo pra ele ir para o elemão

**Comment by victoryforce** [comment] 2024-01-27 14:26
> então denovo usar o app normalmente até ele se recuperar nas ediçãoes, demorou quanto tempo pra ele ir para o elemão

Unfortunately, I don't speak Portuguese, and online translators give a translation that seems to make no sense. In addition, apart from the fact that I cannot understand what you wrote, it is clear that what you wrote does not answer the questions I asked.

@jpellegrini could you please help with this issue?

**Comment by jpellegrini** [comment] 2024-02-04 15:41
I'll take a look later today

**Comment by jpellegrini** [comment] 2024-02-05 01:25
en: I have started dt in English, changed the language to pt_BR, closed, started again and the UI was all in Portuguese... I'm not sure what could have gone wrong with @gui89087i787656789  Maybe it's a Windows-only problem? (I only have Linux)

pt: eu iniciei o dt em Inglês, mudei a linguagem para pt_BR, fechei o programa, iniciei de novo e a interface estava toda em Português. Não tenho certeza do que houve com o @gui89087i787656789  Talvez seja um problema somente no Windows? (Eu somente tenho Linux)

**Comment by jpellegrini** [comment] 2024-02-05 16:14
> All I asked for was help with an accurate translation of the answers of the issue author (I have a strong suspicion that Google translates inaccurately).

He said "então denovo usar o app normalmente até ele se recuperar nas ediçãoes, demorou quanto tempo pra ele ir para o elemão"

Which I can translate somehow like "So again I use the software normally until it recovers in editions (?), it took how long for it to switch to german"

**Comment by jpellegrini** [comment] 2024-02-05 16:15
> Which I can translate somehow like "So again I use the software normally until it recovers in editions (?), it took how long for it to switch to german"

Confusing, indeed.

**Comment by victoryforce** [comment] 2024-04-06 14:59
@jpellegrini Thanks again for your help. Since the author of the issue did not respond, all I can do is close the issue.

**Closed by victoryforce** 2024-04-06 14:59 UTC
Labels: no-issue-activity, scope: windows support
