### ISSUE TITLE
geoloc no longer exposed in lua

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#2218] opened 2019-03-15 21:10 UTC
The geocoordinates are no longer exposed in lua. The documented key is image.latitude and such, that was recently changed to image.geoloc.latitude (and such) but those values are not exposed (field "geoloc" not found for type dt_lua_image_t).
@TurboGit

**Comment by TurboGit** [comment] 2019-03-15 22:09
Indeed, this is due to my change to clean-up the geoloc support over all the base code.

```
luaA_struct_member(L, dt_image_t, geoloc.longitude, protected_double); // set to NAN if value is not set
luaA_struct_member(L, dt_image_t, geoloc.latitude, protected_double); // set to NAN if value is not set
luaA_struct_member(L, dt_image_t, geoloc.elevation, protected_double); // set to NAN if value is not set
```

Because on the image struct the longitude, latitude and elevation are now in a struct.

Is there a way to map those lua field into a specific name? I mean keep the new struct but have them referenced as before on Lua side?

**Comment by TurboGit** [comment] 2019-03-15 22:25
BTW, how to reproduce? I may have a fix? Or you can try the attached patch? Thanks.

[0001-New-version-of-Lua-struct-binding-with-takes-a-speci.patch.txt](https://github.com/darktable-org/darktable/files/2973117/0001-New-version-of-Lua-struct-binding-with-takes-a-speci.patch.txt)

**Comment by trougnouf** [comment] 2019-03-15 22:48
Your patch works, thank you for the quick fix! The error was produced in https://github.com/trougnouf/dtMediaWiki

**Comment by TurboGit** [comment] 2019-03-16 06:38
Merged, thanks.

**Closed** 2019-03-16 06:38 UTC
Labels: bug
