### ISSUE TITLE
Show which preset is selected for export in the name bar of the export module

### ISSUE THREAD

**Issue by tpinfold** [darktable-org/darktable#17442] opened 2024-09-08 02:16 UTC
Previously the ability to see which preset had been selected in the name bar of processing modules had been added to DT. This is a very handy feature. It would also be good if this was extended to the export module. In my case I have presets for JPG, Tiff and PNG. It would be helpful to see which preset was selected without going into the preset hamburger to check.

**Comment by zisoft** [comment] 2024-09-08 04:58
Duplicate of #16964

**Closed** 2024-09-08 08:07 UTC
Labels: feature: enhancement, scope: UI
