### ISSUE TITLE
At the start he goes wrong

### ISSUE THREAD

**Issue by MirkoMaestri** [darktable-org/darktable#10814] opened 2022-01-06 08:24 UTC
Dell Inc. Vostro 5568
BIOS
Versione
1.17.0
Data
08/10/2021
Motherboard
Produttore
Dell Inc.
Modello
0927W0
Versione
A00
Sistema operativo
Edizione
Microsoft Windows 10 Pro (64 bit)
Versione (Build)
21H2 (10.0.19044)
Dispositivi e driver
Processore
Intel® Core™ i7-7500U CPU @ 2.70GHz
Grafica
Intel® HD Graphics 620
NVIDIA GeForce 940MX
Citrix Indirect Display Adapter
Audio
Realtek Audio
Audio Intel® per schermi
NVIDIA Virtual Audio Device (Wave Extensible) (WDM)
Networking e I/O
Realtek PCIe GBE Family Controller
Intel® Dual Band Wireless-AC 3165
Bluetooth Device (Personal Area Network)
Fortinet Virtual Ethernet Adapter (NDIS 6.30)
Fortinet SSL VPN Virtual Ethernet Adapter
PPPoP WAN Adapter
VirtualBox Host-Only Ethernet Adapter
LogMeIn Hamachi Virtual Ethernet Adapter
Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
TAP-Windows Adapter V9
Wintun Userspace Tunnel
Intel® Wireless Bluetooth®
Memoria
16 GB
Storage
Samsung SSD 860 EVO 1TB
Intel SSD Pro 5450s Series No Opal

[darktable_bt_9I1KF1.txt](https://github.com/darktable-org/darktable/files/7820422/darktable_bt_9I1KF1.txt)
[darktable_bt_PJVVF1.txt](https://github.com/darktable-org/darktable/files/7820423/darktable_bt_PJVVF1.txt)
[darktable_bt_1NYMF1.txt](https://github.com/darktable-org/darktable/files/7820424/darktable_bt_1NYMF1.txt)

**Comment by parafin** [comment] 2022-01-06 08:41
Duplicate of #8700.

**Closed by parafin** 2022-01-06 08:41 UTC
