### ISSUE TITLE
Regression: Exif data (creator and copyright and more) not imported any longer

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#5703] opened 2020-07-05 09:20 UTC
**Describe the bug**
When importing Files or Folders the images lose embedded exif data.

**To Reproduce**
1. Use latest master (e.g. fe371fc65)
2. Have an image that contains copyright / creator information
3. Import that image
4. Check if the "image information module" is showing that information

**Expected behavior**
The information shall exist there. This is working in 3.0.2 and missing in master

**Platform (please complete the following information):**
 - Darktable Version: fe371fc65
 - OS: Manjaro

**Comment by codingdave** [comment] 2020-07-05 09:24
reverting 4a15b29463a7d890448602a73ba5e5eeabe5750c helps

**Comment by jade-nl** [comment] 2020-07-05 09:56
Here's the bisect data:

> 
> ea6f8e58e8c6fe547c77f86c81ca24a709bc3abb is the first bad
> commit ea6f8e58e8c6fe547c77f86c81ca24a709bc3abb
> Author: phweyland <philippe.weyland@laposte.net>
> Date:   Wed Jun 17 21:56:27 2020 -0300
> 
>     xmp update fix
>     - clean up metadata and tags before updating from xmp (t
>     - some signal raise moved from common to libs (dead lockp_data)
>     - some fixes  where grouped images are added to images l
> 
> :040000 040000 d60b6cb2e5fa7eecffdae85c45f9a7954492dd8f 85dd8f9896c378026b11 M      src

BTW: This isn't limited to metadata already present in the RAW. It also applies to metadata supplied in the preferences and/or import screen.

**Comment by jenshannoschwalm** [comment] 2020-07-05 13:22
> When importing Files or Folders the images lose embedded exif data.

Is this really correct? I think i can reproduce but i would say that most (maybe even all) data read from the sidecar is lost.

**Comment by phweyland** [comment] 2020-07-05 14:08
@codingdave 
ea6f8e5 intended to fix #5486 where removed info in xmp file were not reflected in dt (when setting to check xmp file changes on dt start). I've then cleaned up the xmp info before reading the new ones.
As exif data (from raw file) are read before xmp info, the issue you describe seems possible. I'll look at it.

@jenshannoschwalm 
>  would say that most (maybe even all) data read from the sidecar is lost.

This sounds different. Could you elaborate a bit more please ?

**Comment by jenshannoschwalm** [comment] 2020-07-05 14:28
To reproduce:
1. Add some user tag like location
2. refresh exif data

After this the user defined data are not existing any more.

**Comment by phweyland** [comment] 2020-07-05 14:43
@jenshannoschwalm thanks, got it.

**Comment by codingdave** [comment] 2020-07-05 18:02
Hi @phweyland I have tested your PR and it seems to fix the error I mentioned in this case. Thank you.

**Comment by phweyland** [comment] 2020-07-05 18:26
> I have tested your PR and it seems to fix the error I mentioned in this case

Thanks for testing it again.

@jenshannoschwalm & @jade-nl your related issues should be fixed too.

**Comment by jenshannoschwalm** [comment] 2020-07-05 20:21
Can't test. But the code looks correct.

**Comment by jade-nl** [comment] 2020-07-06 07:01
@phweyland : Yep, tested it and it is fixed.

Thanks!

**Closed** 2020-07-06 07:29 UTC
