### ISSUE TITLE
 macOS Ventura, dt 4.2 and 4.3: modules menu not working

### ISSUE THREAD

**Issue by caiux** [darktable-org/darktable#13207] opened 2022-12-27 11:08 UTC
**Describe the bug/issue**

In darkroom mode, when opening the hamburger menu of a module, moving the mouse pointer does not highlight any menu items. When clicking on an item, the item is not selected. However, it may randomly work as expected.

**To reproduce**

1. Go to darkroom
2. Click on a module hamburger menu (three horizontal lines)
3. Move over the menu with the mouse
4. Menu items are not highlighted, nor are selectable by clicking on them

**Expected behavior**

Mouse hovering/clicking should work.

**Screencast**

https://user-images.githubusercontent.com/10013246/209657748-fe8e0a6f-4c41-49a5-afab-53deb9e69ecb.mov

**Platform**

* darktable version : 4.2 and 4.3
* OS : macOS Ventura 13.1
* Processor : M1
* Memory : 16 GB
* OpenCL installed : no
* OpenCL activated : no
* Xorg : Quartz

**Comment by kmilos** [comment] 2022-12-27 11:17
Duplicate of https://github.com/darktable-org/darktable/issues/12727

Please search before opening new issues.

**Closed** 2022-12-27 11:28 UTC
