### ISSUE TITLE
pic is black in the dark room

### ISSUE THREAD

**Issue by jblmf** [darktable-org/darktable#14597] opened 2023-05-28 08:56 UTC
### Describe the bug

I can see all images correctly in the light room but once I want to visualize one in the darkroom it remains black... No matter which one is selected. I just downloaded the app and the issue immediately occured. 

### Steps to reproduce

Go to the lightroom
Select any picture
Click on "darkroom"
The selected picture gets black

### Expected behavior

darktable should make the picture visible in the darkroom

### Logfile | Screenshot | Screencast

<img width="1233" alt="Capture d’écran 2023-05-28 à 09 38 23" src="https://github.com/darktable-org/darktable/assets/134834535/2e3ef38b-015d-4a24-bb15-d3437d19f673">
<img width="1235" alt="Capture d’écran 2023-05-28 à 09 38 39" src="https://github.com/darktable-org/darktable/assets/134834535/f4eefe10-0bc2-40cb-a5ce-a8add93c74d5">

### Where did you install darktable from?

darktable.org

### darktable version

darktable-4.2.1_arm64.dmg

### What OS are you using?

Mac

### What is the version of your OS?

Mac OS Ventura 13.0

### Describe your system?

<img width="269" alt="Capture d’écran 2023-05-28 à 10 53 56" src="https://github.com/darktable-org/darktable/assets/134834535/dad6725e-23a8-4095-a505-77a1438451d6">

### Are you using OpenCL GPU in darktable?

None

**Comment by MStraeten** [comment] 2023-05-28 10:15
not reproducible with my current master build based on that information. 
in lighttable you see the embedded jpg generated by your cam. Did you change any configurations in darktable?  
please provide the affected raw + generated xmp
based on the screenshot it's just guessing since the M1 macbook air even wit 8GB should be capable to process images

**Comment by ralfbrown** [comment] 2024-01-20 19:01
Closing because we have had two features releases since this report, the reporter never provided the requested files, it was not reproducible, and there haven't been any other reports of this problem.
If this display problem still occurs in 4.6, please open a new issue *and provide the requested files*.

**Closed by ralfbrown** 2024-01-20 19:01 UTC
Labels: understood: incomplete, no-issue-activity
