### ISSUE TITLE
Importing folder changes "collect images" mode to "film roll"

### ISSUE THREAD

**Issue by l0b0** [darktable-org/darktable#10418] opened 2021-11-15 09:59 UTC
**Introduction**

**Describe the bug/issue**

I always set the "collect images" mode to "folders" whenever Darktable changes it back to "film roll" (it's happened a bunch of times), and finally I've been able to see it in action. I just tried to import a folder, and the mode changed again.

**To Reproduce**

1. Go to lighttable mode
2. Change the "collect images" mode to "folders"
2. Click the "folder…" button in the "import" tab toolbox
3. Check to import recursively (I haven't tested whether this is necessary)
4. Click OK

**Expected behavior**

The "collect images" mode should stay unchanged.

**Screencast**
(I'll see if I can create a screencast once the import is finished. It takes a few hours for ~50k images.)

**Platform**

* darktable version : e.g. 3.4.1
* OS                : Linux - kernel 5.10.79
* Linux - Distro    : NixOS 21.05
* Memory            : 16G
* Graphics card     : AMD Radeon RX 5500
* Graphics driver   : unknown
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : 1.20.11
* Desktop           : GNOME
* GTK+              : unknown

**Additional context**

 - Can you reproduce with another darktable version(s)? **untested**
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **untested**
 - Do you use lua scripts? No

**Comment by aurelienpierre** [comment] 2021-11-15 10:20
It's not a bug. When you import images, you create a film roll (≠ folder). It seems logical that the view is updated to this. A film roll can be equal to a folder or be a subset of that folder content, in which case it is not a folder anymore.

**Comment by parafin** [comment] 2021-11-15 11:22
I would say it's not a bug, but a feature request. Import always worked like that - switches collection to just imported folder using film roll mode. It's possible in theory to do the same using folders mode. Some prefer fill rolls, some folders (like me), so it can be a preference maybe (though I really hate adding more options)? Another possibility is not to touch collect module after importing, but that would be surprising for most, since it is expected to be able to see the just imported images.

**Comment by elstoc** [comment] 2021-11-15 12:42
Agreed. Now that we've separated the import preferences from the global prefs dialog, adding a "default mode" option (film roll / folder) should be fairly uncontroversial. That default could be used both for import and for when you press the reset button on the module.

**Comment by aurelienpierre** [comment] 2021-11-15 12:47
Another option…

This is our future : 
![image](https://user-images.githubusercontent.com/2779157/141784633-2a5e855a-03b6-491b-a774-38f302e4fcda.png)

**Comment by elstoc** [comment] 2021-11-15 13:02
I see nothing wrong with flexibility. As I said, we've already separated the preferences out for the collections module so another option will in no way look like the silly screenshot you've added.

**Comment by aurelienpierre** [comment] 2021-11-15 13:07
Flexibility means failure to choose a consistent design, a bloat of options to loose users, and many possible combinations of settings that will never be tested for their interactions. Just because we can make everything optional doesn't mean that we should nor that it's good. GUI design is also about providing a consistent UX through a guided path, not making everything flip-flop-able for the joy of the expert user who mistakes control with over-engineering.

**Comment by elstoc** [comment] 2021-11-15 13:10
> failure to choose a consistent design

Disagreement is what causes this - in this case some users who love the concept of "film rolls" and others who just don't get the point. So we get an option because it's the easiest way to settle the discussion.

**Comment by aurelienpierre** [comment] 2021-11-15 13:13
Exactly my point. Failure to choose. Settling a discussion by avoiding a choice is what causes bloat.

The number of prefs is growing at an alarming rate.

**Comment by elstoc** [comment] 2021-11-15 13:13
Who chooses?

**Comment by aurelienpierre** [comment] 2021-11-15 13:21
Whoever cares the most, otherwise consensus, finally, vote.

**Comment by elstoc** [comment] 2021-11-15 13:25
Ok I vote for adding a preference ;-p

**Comment by aurelienpierre** [comment] 2021-11-15 13:28
Personally I don't give a fuck about filmstrips, I never understood the principle and I only ever used it as folders, meaning they are fully redundant, so ditch it and make folders the new way. But not a new pref for this, it's not worth it.

**Comment by elstoc** [comment] 2021-11-15 13:31
> Personally I don't give a fuck about filmstrips

You mean film rolls but I agree. I don't see the need for both folders and film rolls in the collect module since they are basically the same thing.

**Comment by parafin** [comment] 2021-11-15 13:41
I agree that new configuration options should be avoided at all costs. My suggestion for the import process is to use folders mode if it's currently selected in collect module and filmroll mode otherwise. It doesn't cover reset button, but I personally don't mind that.
Another possibility is to merge filmroll mode with folder mode somehow, voiding this whole discussion. E.g. allow limiting the depth of folders view, so with depth == 0 it would become the same as film roll mode. It doesn't create a new preferences, because similar one exists already for filmrolls and it's really needed. Or alternatively add a "flatten" button to folders view to dynamically switch between modes, saving last chosen mode in darktablerc. That wouldn't be a real configuration option IMHO and is fine.

**Comment by l0b0** [comment] 2021-11-15 21:13
Sorry, I didn't expect my suggestion to be controversial. Basically, if I set something in the UI I would expect that setting to stay that way until *I* change it. I'm not suggesting any new settings. The view changing when importing is not intuitive to me (I've not seen any other photo managers do that), "film roll" is an anachronism and I never liked that view.

**Comment by quovadit** [comment] 2021-11-16 07:33
The concept of filmrolls was the one thing I absolutely did not understand for a very long time when I started using dt.
And I am still irritated, that every import switches my view to filmroll (although I never use filmrools).

I understand, that it is expected to be able to see the just imported images after importing.

But I don't agree, that automatically changing to filmroll is the best way to achieve this, because first of all, it does not always work:
when importing using directory naming patterns, you get multiple filmrolls for one import, and the first one gets selected.
So while it works in most cases, switching to filmroll does not always show the just imported images.

A clean (but sill not very intuitive) solution would be to change the collection to 'import timestamp' >= now()

But the biggest problem for me is the fact, that dt does something automatically, which I do not realise immediately.
Yes, it's nice, that imported images are shown automatically, but the next time I use the collections module I'm irritated.

So in my opinion, there are two solutions:
1. let the user define, what should happen after import
  - a) option in import dialog
    - there already is an option 'keep this window open', we could extend this to: what should happen after clicking 'import'
  - b) popup when import finished
    - 'Successfully imported x images [to y folders]. What do you want to do?' 
    - switch to filmroll / switch to folder / switch to tag / switch to import timestamp / do nothing
    - Checkbox 'Remember this decision', possibility to change it in import preferences
2. show what automatically happended, and make it easy to change it again
  - automatically collapse import module, and expand 'collections' + 'recently used collections' modules
  - extend the toast-message: 'imported x images. changed collection to filmroll/folder/tag/datetime...
  - so the user knows what happens, and can change it with one click in the expanded 'recently used' module


The reset button is a different story...
Although I think this is not as important as the import-topic above, there should be a way to define my default collection.
Maybe not a simple choice filmroll/folder in preferences, but a 'default'-flag in one preset ('use this preset as default').

**Comment by bluemoon1945** [comment] 2021-11-17 18:04
I support the proposal of quovadit. For me, personally, the current behavior is irritating, I don't see why we should not improve it.

**Comment by l0b0** [comment] 2022-01-17 00:17
ping.

**Comment by l0b0** [comment] 2022-03-20 19:20
Still relevant.

**Comment by Solarer** [comment] 2022-05-13 21:36
I think @l0b0's original point was missed. (please correct me if I am wrong)

Isn't his point that the collection module switches its display from this
<img src="https://user-images.githubusercontent.com/2805109/168390863-382fcfb9-4f39-4f45-97ed-51b7d43cacc7.png" width=50% height=50%>

to this
<img src="https://user-images.githubusercontent.com/2805109/168390988-068b682d-aad1-4905-8a0b-c400d803b39d.png" width=50% height=50%>

after importing images? 

This discussion drifted off slightly in the direction to what images darktable should display after the import. That is not the same. 
The fact that darktable automatically OPENS my newly imported pictures and SHOWS the last film roll to me is not bad (yes, it can confuse people but I do not think that @l0b0 wanted to talk about that here). His point was: Why does import have to change something in the UI of the collections module?

**Comment by l0b0** [comment] 2022-07-13 11:48
Still relevant.

**Comment by vancouverbluesea** [comment] 2022-09-17 18:17
This issue is still present in 4.0.1
Not a deal breaker but irritating (when the user repeats the steps).
Personally - I divide HDR / panorama etc. in separate folders so I don't mix them. When something like this happens - I go back and forth to the presets - constantly. 
Again - I can live with it but it would have been nice if the user can choose.

**Comment by TurboGit** [comment] 2022-09-17 20:15
Should be fixed in #12514. No new preferences, just that if the collection is set to folder or filmroll we keep it when importing.

**Comment by vancouverbluesea** [comment] 2022-09-17 21:11
Thank you Pascal!

**Closed** 2022-09-18 13:54 UTC
Labels: feature: redesign, scope: UI
