### ISSUE TITLE
3.0.0 (color balance and graduated density) not working with DNG (Leica)- black output MacOS 10.14.6 (18G2022)

### ISSUE THREAD

**Issue by adulau** [darktable-org/darktable#3860] opened 2019-12-25 07:33 UTC
**Describe the bug**``
3.0.0 (color balance and graduated density) not working - black output MacOS 10.14.6 (18G2022)

`**To Reproduce**

1. Go to 'color balance or graduated density' module
2. Enable the module
3. Output of the image is always black (whatever the parameters)

**Expected behavior**

In version 2.6 those modules were working.

**Screenshots**

**Platform (please complete the following information):**
 - MacOS 10.14.6 (18G2022)
 - 10.14.6 (18G2022)
 - OpenCL is not available

**Additional context**

 - This can be only reproduced with RAW images (DNG from Leica) - it works as expected on JPEG.

**Comment by pphotography** [comment] 2019-12-25 10:48
Cannot reproduce that with dt 3.1.0~git10.af8b11a17 on Ubuntu 18.04 with/without OpenCL.
I took Leica RAW files from
https://rawsamples.ch/index.php/en/leica
https://www.kenrockwell.com/leica/m9/sample-photos-3.htm

Can you tell us which Leica camera u use or provide example files?

**Comment by aurelienpierre** [comment] 2019-12-25 22:42
Seems related to RGB/Lab on-the-fly conversions, might be the same as #3865.

**Comment by adulau** [comment] 2019-12-26 10:16
Indeed, if I disable the "filmic RGB module", the other modules work as intended. It sounds like to be a related issue.

Nevertheless, the sample DNG file (from a Leica M10) is available there as requested by @pphotography :

https://www.foo.be/sample-leica/L1002530.DNG

The file is in CC-0 (public domain) feel free to share it and/or use it for test cases.

**Comment by MStraeten** [comment] 2019-12-27 22:09
seems to be fixed with https://github.com/darktable-org/darktable/pull/3890

**Comment by adulau** [comment] 2019-12-27 23:36
Thanks a lot. Is there a daily/nightly build available for testing?

**Comment by MStraeten** [comment] 2019-12-28 07:53
try https://discuss.pixls.us/t/current-osx-build/13213/45

**Comment by adulau** [comment] 2019-12-28 09:53
Thanks a lot but I run Mojave. I'll compile it and we will make some tests.

**Comment by johnny-bit** [comment] 2020-12-28 20:08
Duplicate of #3327

**Closed by johnny-bit** 2020-12-28 20:08 UTC
Labels: no-issue-activity
