### ISSUE TITLE
"Image Information" panel in lighttable shows some probably incorrect info when multiple images are selected

### ISSUE THREAD

**Issue by grudgingly** [darktable-org/darktable#16547] opened 2024-03-30 20:57 UTC
### Describe the bug

A few of of the fields in the `image information` panel in the lighttable show the info for the first selected image, instead of `<various values>` when these values differ between the selected images. The fields in question (that I've seen) are `ISO`, `datetime`, `export width`, and `export height`.

### Steps to reproduce

In lighttable, select some images taken at different times, at different ISOs, and which are cropped to different sizes.

In the `image information` panel, the `ISO`, `datetime`, `export width`, and `export height` values shown will be those of the first image in the selection.

### Expected behavior

Darktable should display `<various values>` in these fields in this situation.

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Arch Linux

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Mainly reporting so that someone can check if this is in the upcoming 4.8 version and fix if necessary.

**Comment by wpferguson** [comment] 2024-03-31 00:46
Where is your mouse pointer?  If it's over one of the selected images, then the values for that image are displayed.  If the mouse pointer is off to the side, then <various values> is displayed.

**Comment by grudgingly** [comment] 2024-03-31 00:48
It's away from the images, and `<various values>` is displayed in most of the other fields.

**Comment by wpferguson** [comment] 2024-03-31 00:59
I can reproduce for export height and export width.  ISO and datetime taken show <various values>

**Comment by grudgingly** [comment] 2024-03-31 01:55
I've just noticed that the opposite is happening too - even though all the images in my current collection and selection have a crop factor of `1.0`, `<various values>` is displayed for `crop factor` when not hovering over any images.

**Comment by zisoft** [comment] 2024-03-31 05:49
Duplicate of #15687 

The reason is the two fields _35mm equiv focal length_ and _crop factor_ which are not read from the database but calculated.

Turn off the display of these fields to get correct results.

**Closed** 2024-03-31 05:50 UTC
Labels: duplicate

**Comment by victoryforce** [comment] 2024-04-01 19:37
@grudgingly A PR (#16556) has been created to fix this bug.
