### ISSUE TITLE
Rejected images in culling mode not updated on lighttable behind

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5075] opened 2020-05-15 20:51 UTC
**Describe the bug**
When rejecting an image in culling mode (with all except rejected mode set) and go back to lighttable filemanager view, rejected images are still.

Go to rejected filter mode and see new rejected images there. Go back to all except rejected mode, rejected images are no more there (so update is made).

This probably means a some refresh missing between culling mode and lighttable.

**Expected behavior**
Having rejected images correctly updated on lighttable regardless of filters sets when rejected them or set anything else on culling mode.

Tested on commit 6e4adf93f83e8f420557c266ede54ca7a0c19484.

@AlicVB: another one for you!

**Comment by Nilvus** [comment] 2020-05-15 20:52
Colorlabels and stars are updated correctly, so it's only rejected images.

**Comment by AlicVB** [comment] 2020-05-16 10:42
And another one I can't reproduce :(
Here are the steps I have done : 
- In filemanager, set the all except rejected filter
- Enter culling with X or ctrl-X with filmstrip visible or not
- reject one of the image by clicking on the cross or with the 'R' shortcut
- the image "disappear" from the center view
- press X to return to filemanager

=> the rejected image is not here

What I'm doing wrong ? (tested with your exact commit, to be sure it was not fixed by a more recent commit)

**Comment by Nilvus** [comment] 2020-05-16 15:32
Quite annoying as you're not doing anything wrong. That's the exact steps for this issue. The only difference is the result. On my side (testing again just now) the result is:

=> the rejected is still there

Just 2 things I've just see about that one:
- it's seems that if it's the first image rejected, the image is not here, but if not, the image are still there. And last thing: when images are still there, just one scroll up make them disappear (even if there's no scroll needed (on what I've test, I just have 5 images so all displayed at once).

**Comment by Nilvus** [comment] 2020-05-16 16:01
@AlicVB: seems to be another tricky one. I just come back to a day in mountains and take a lot of photos (first big exit since we are "free") and I've just began to reject some images; No issue. If I come back to the film roll I have this issue, I still have it. And the only difference is on film roll I have the issue, I have only 5 images (and 4 images per row).

Tested on a film roll with only 2 images, no issue. On a film roll with 4 images (so a complete row), I also have the issue. And on same case (even with 3 images), when I reject an image with r shortcut, the following image is also rejected (I'm sure I press r just once). Make few tries, I (rarely) sometimes have rejected images disappear when I have 3 or 4 images. But never with 5 and if shortcut used, the following image is also rejected.

The following image rejected with r shortcut seems to also happen when having more images. Quite annoying and another issue...

**Comment by AlicVB** [comment] 2020-05-16 17:57
So... let's try to get a very precise step by step, because I can't reproduce...
- it happens all the time if you have 5 images in the film roll with 4 images per row. Right ?
- In collect module, you have just the filmroll, no other line ?
- filter set to all except reject and sort by filename ?
- What mode of culling do you use ? dynamic or fixed ?
- Anything special for the selection ?
- Filmstrip visible in culling mode ? (if I remember well, it's no) ?
- How do you reject an image ? shortcut, click on the icon ?
- how do you return to filemanager ? shortcut or bottom combobox

And if I can't reproduce after that, maybe we can do some sort of direct debugging on the french chat ?

**Comment by AlicVB** [comment] 2020-05-16 18:05
oh, and can you test launching darktable in terminal with -d lighttable arguments ?
When you are in culling and you reject an image, a message you be written to the terminal. Can you copy-paste it ? Thanks

**Comment by Nilvus** [comment] 2020-05-16 19:00
> So... let's try to get a very precise step by step, because I can't reproduce...
> 
>     * it happens all the time if you have 5 images in the film roll with 4 images per row. Right ?
Yes

>     * In collect module, you have just the filmroll, no other line ?

Yes

>     * filter set to all except reject and sort by filename ?

Yes
 
>     * What mode of culling do you use ? dynamic or fixed ?

I select an image and then press 'X'. Fixed if I'm not wrong.

>     * Anything special for the selection ?

Nothing else than described line above.

>     * Filmstrip visible in culling mode ? (if I remember well, it's no) ?

No filmstrip and no panels, no border, just two images (I always use culling mode to compare 2 images and no more, without any distraction.

>     * How do you reject an image ? shortcut, click on the icon ?

Mainly with shortcut. But trying to make that issue more precise, I no longer use shortcut as I've found another issue (describe above) but I will repeat him: when a reject the left image, the following right image is also rejected. Reproducible all times (this issue is more annoying than the initial one). And if I use click on the icon, only the rejected image is... rejected. But on both, I have the issue initially describe here.

>     * how do you return to filemanager ? shortcut or bottom combobox

Always shortcut (X) as I've hide all panels/toolbars.

> And if I can't reproduce after that, maybe we can do some sort of direct debugging on the french chat ?

That will be faster. I could be on the chat if necessary all the evening.

**Comment by Nilvus** [comment] 2020-05-16 19:03
> oh, and can you test launching darktable in terminal with `-d lighttable` arguments ?
> When you are in culling and you reject an image, a message you be written to the terminal. Can you copy-paste it ? Thanks

I only have those 2 lines when rejecting the left image on 2 images I have on culling:

```
97,593619 done in 0,0111 sec
104,350158 done in 0,0114 sec
```

And when I go back (with x shortcut) to lighttable view (filemanager), I have 2 images (forgot to precise that this 2 images rejected and not only the one rejected appears only in same conditions as the initial issue). I I click on a red cross of one of the 2 images, I have those lines:

```
252,042281 reload thumbs from db. force=1 w=1290 h=923 zoom=4 rows=3 size=322 offset=3 centering=1...
252,044205 done in 0,0019 sec 0 thumbs reloaded
```

**Closed** 2020-05-18 09:22 UTC
