### ISSUE TITLE
Rotate and Flip options within Retouch tools

### ISSUE THREAD

**Issue by TheChewey** [darktable-org/darktable#15279] opened 2023-09-19 16:16 UTC
There has been many instances when retouching round objects within photos in order to match the curvature of surfaces. For instance a blemish or reflection on the iris of an eye, wanting to clone a portion of the iris from another section of the eye. You could also use this feature creatively for instance when wanting to replicate a bird to face a different way in another portion of the image. 

The only current way of achieving this is to crop the portion of the image you wish to clone and export it, then import it back as a watermark which you can then adjust to suit the edit

![Eye Issue](https://github.com/darktable-org/darktable/assets/145479462/65cce4d5-669a-4d5c-a04e-cb80126ccea6)
![Eye Retouch](https://github.com/darktable-org/darktable/assets/145479462/202290e8-131a-4926-98fb-1f36936c2f7e)

**Comment by ralfbrown** [comment] 2023-09-20 02:39
Basically a duplicate of #14026.

**Closed by ralfbrown** 2023-09-20 02:39 UTC
Labels: difficulty: hard, scope: image processing
