### ISSUE TITLE
Under and overexposure indication broken

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#4015] opened 2020-01-04 09:30 UTC
Picture speaks for itself:

![screenshot](https://user-images.githubusercontent.com/58066490/71763497-a21a9780-2eed-11ea-9a61-60c519452277.png)

Additional info: Debian 10, intel 64 bit, no OpenCL, both 3.0.0 and 3.1 master have this problem, both JPEG and raw tested.

**Comment by pphotography** [comment] 2020-01-04 11:14
Can't reproduce with 3.1.0~git289.f788bfff3 on Ubuntu 18.04 with and without OpenCL

**Comment by timur-davletshin** [comment] 2020-01-04 11:23
@pphotography I used same OBS build and my own dt 3.0.0 build.

**Comment by chhil** [comment] 2020-01-04 11:31
I havent seen this happen in a long time but I have definitely seen this behavior on my windows machine. I will see if I can find a issue I logged.

**Comment by timur-davletshin** [comment] 2020-01-04 11:49
Some additional info. Discarding history helps. It is some sort of module order:

[dt_ioppr_check_duplicate_iop_order] modules finalscale (71.000000) and gamma (71.000000) have the same iop_order
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 8762 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module gamma (0)(71.000000) and finalscale (0)(71.000000) have the same order image 8762 (dt_dev_read_history_no_image end)
[dt_ioppr_check_duplicate_iop_order] modules finalscale (71.000000) and gamma (71.000000) have the same iop_order
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 8762 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] module gamma (0)(71.000000) and finalscale (0)(71.000000) have the same order image 8762 (dt_dev_read_history_no_image end)
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_iop_order] module gamma (0)(71.000000) and finalscale (0)(71.000000) have the same order image 0 (dt_dev_pop_history_items_ext begin)
[dt_ioppr_check_duplicate_iop_order] modules finalscale (71.000000) and gamma (71.000000) have the same iop_order
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] module gamma (0)(71.000000) and finalscale (0)(71.000000) have the same order image 0 (dt_dev_pop_history_items_ext end)
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] module gamma (0)(71.000000) and finalscale (0)(71.000000) have the same order image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] gamma is not the last iop, last is watermark (76.000000) image 0 (dt_dev_modules_update_multishow)
[dt_ioppr_check_iop_order] module gamma (0)(71.000000) and finalscale (0)(71.000000) have the same order image 0 (dt_dev_modules_update_multishow)

Probably I just messed up some of my edits with pre 3.0.0 development builds just by importing them.

History file:
[_DSC0004.NEF.zip](https://github.com/darktable-org/darktable/files/4021860/_DSC0004.NEF.zip)

**Comment by timur-davletshin** [comment] 2020-01-04 11:54
So, it would be nice to know how to fix those edits :)

**Comment by pphotography** [comment] 2020-01-04 13:21
I can reproduce that effect with your XMP. It gets normal when I deactivate the orientation module. It is behind the exposure module where I don't think that it belongs there.
![Bildschirmfoto von 2020-01-04 14-17-02](https://user-images.githubusercontent.com/49001045/71766182-6687c980-2efd-11ea-8fec-6195a64a1321.png)


After going back to the first history stack the orientation module appears before the exposure module and everything is fine.
![Bildschirmfoto von 2020-01-04 14-17-31](https://user-images.githubusercontent.com/49001045/71766174-54a62680-2efd-11ea-8631-7d184ea306d7.png)

**Comment by timur-davletshin** [comment] 2020-01-04 13:27
@pphotography I wonder how did it get there. Never used module reordering. Do we have some shortcut to reset order?

**Comment by timur-davletshin** [comment] 2020-01-04 14:13
@pphotography no, it didn't help me. Though pattern became different.

**Comment by junkyardsparkle** [comment] 2020-01-05 23:15
Looks like a case of ordering collision:

`[dt_ioppr_check_duplicate_iop_order] modules finalscale (71.000000) and gamma (71.000000) have the same iop_order`

**Comment by timur-davletshin** [comment] 2020-01-06 05:25
@junkyardsparkle yep, fixed it with find + xargs. There was another problem with wrong flip position (20 vs 16).

**Comment by jenshannoschwalm** [comment] 2020-03-21 17:01
@timur-davletshin is this issue still valid?

**Comment by jenshannoschwalm** [comment] 2020-04-11 08:54
@TurboGit This is as todo in projects pipe reordering. I really don't think this is valid as info tells us "old and wrong" iop_order. Or are you still looking for "automatic fixing" such stuff?

**Comment by TurboGit** [comment] 2020-04-11 09:00
> Or are you still looking for "automatic fixing" such stuff?

As far as I remember there is no way to fix all edits that were done in the period if Sept to Oct (maybe Nov) 2019. There pipe was highly broken and it is not possible to safely detect and fix this. The only solution is to change manually the pipe order with the new module.

Note that this affects only some devs having used the dev master version for a short period of time. That's the risk we all take when on master.

**Comment by jenshannoschwalm** [comment] 2020-04-17 08:28
Closing this issue?

**Closed** 2020-04-17 08:46 UTC
Labels: bug: pending, no-issue-activity, priority: high, reproduce: confirmed, understood: clear
