### ISSUE TITLE
Access violation in module libpango at start of darktable on windows

### ISSUE THREAD

**Issue by mfg92** [darktable-org/darktable#9653] opened 2021-07-27 19:59 UTC
I have compiled darktable on windows myself using the [official documentation](https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.md). I did this to be able to use the [canon_cr3 rawspeed branch of cytrinox](https://github.com/darktable-org/rawspeed/pull/271) to add cr3 support to darktable. After some try and error I was able to build and start darktable and to edit cr3 files.
After some days I pulled the latest changes and did the build again. Unfortunately, I got an exception directly during the start of darktable. I thought it is a cr3 related issue, so i created a new folder and pulled darktable again from git. This time I did no modifications to the project (did not change the rawspeed submodule). Then I compiled it, but I still get the "An unhandled exception occurred..." error. I have also updated MSYS2 using `pacman -Syu`.
All the time I have used the branch "darktable-3.6.x".

**Platform**
* darktable version : darktable-3.6.x d679c98e0b1b470a2d87cee88077987d15d5d77b
* OS                :  Win10 (21H1 19043.1110)
* Memory            :  32GB
* Graphics card     :  Radeon RX 480 8GB
* Graphics driver   :  27.20.21003.8013
* OpenCL installed  :  I guess so
* OpenCL activated  :  no ( I have used --disable-opencl)
* Xorg              :  -
* Desktop           :  -
* GTK+              :  -
* gcc               :  gcc.exe (Rev5, Built by MSYS2 project) 10.3.0
* cflags            :  unknown
* CMAKE_BUILD_TYPE  : unknown

**Backtrace**
```
this is darktable 3.7.0+512~g915f2cce3 reporting an exception:

-------------------

Error occurred on Tuesday, July 27, 2021 at 21:20:57.

darktable.exe caused an Access Violation at location 00007FFD7478760B in module libpango-1.0-0.dll Reading from location 0000000000000000.

AddrPC           Params
00007FFD7478760B 000002613692E120 00000261307D0000 00000261307D02A4  libpango-1.0-0.dll!pango_shape_with_flags
00007FFD74777DB8 0000026136C98450 0000000000000003 0000026136C982F0  libpango-1.0-0.dll!pango_layout_line_unref
00007FFD747791D3 0000000000000000 0000026136ED12A0 0000000000000004  libpango-1.0-0.dll!pango_layout_iter_copy
00007FFD7477ABC5 0000026136B1FCC0 0000000000000001 0000026136B1FCC0  libpango-1.0-0.dll!pango_layout_set_text
00007FFD7477C0AE 0000000000000000 00000261320CD760 000000616B9FEA00  libpango-1.0-0.dll!pango_layout_get_unknown_glyphs_count
00007FFD59E06D61 00000261320CD8F0 0000026132A05040 00000261308C6FD0  libgtk-3-0.dll!gtk_editable_get_editable
00007FFD59E07100 00000261308CDAB0 00007FFD7B6C8B10 00000261308CDAB0  libgtk-3-0.dll!gtk_editable_get_editable
00007FFD7B6A6034 0000026135397BE0 00007FFD7B6A3D3C 0000000000000020  libgobject-2.0-0.dll!g_type_create_instance
00007FFD7B68BE70 0000026100000001 0000000000000000 00000261000000CB  libgobject-2.0-0.dll!g_object_unref
00007FFD7B68D66E 00000261320AA160 00007FFD5A411B20 0000026136A209E0  libgobject-2.0-0.dll!g_object_new_with_properties
00007FFD7B68DECB 00000261320AA1C0 00007FFD787167D6 0000000000000000  libgobject-2.0-0.dll!g_object_new
00007FFD59F4A9DF 00007FFD5A84C5E2 0000026136CCC5E8 00007FFD5FD16460  libgtk-3-0.dll!gtk_spin_button_new_with_range
00007FFD5FD13047 000000616B9FEEA0 00007FFD5A84C5E2 000000616B9FEEA0  libpdf.dll!gui_init  [C:/msys64/home/matze/darktable2/src/imageio/format/pdf.c @ 642]
   640:   gtk_grid_attach(grid, dt_ui_label_new(_("dpi")), 0, ++line, 1, 1);
   641: 
>  642:   d->dpi = GTK_SPIN_BUTTON(gtk_spin_button_new_with_range(1, 5000, 1));
   643:   gtk_grid_attach(grid, GTK_WIDGET(d->dpi), 1, line, 1, 1);
   644:   dt_gui_key_accel_block_on_focus_connect(GTK_WIDGET(d->dpi));
00007FFD5A51F3B1 0000026136CF0760 0000000000000000 000002613548B500  libdarktable.dll!dt_imageio_load_modules_format.isra.0
00007FFD5A51FB96 0000000000000010 0000000000000010 0000000000000000  libdarktable.dll!dt_imageio_init  [C:/msys64/home/matze/darktable2/src/common/imageio_module.c @ 260]
   258:   iio->plugins_storage = NULL;
   259: 
>  260:   dt_imageio_load_modules_format(iio);
   261:   dt_imageio_load_modules_storage(iio);
   262: }
00007FFD5A4B420F 0002000000000001 00000261320AE970 0000026100000001  libdarktable.dll!dt_init  [C:/msys64/home/matze/darktable2/src/common/darktable.c @ 1086]
  1084: 
  1085:   darktable.imageio = (dt_imageio_t *)calloc(1, sizeof(dt_imageio_t));
> 1086:   dt_imageio_init(darktable.imageio);
  1087: 
  1088:   // load default iop order
00007FF7E7E528DA 00007FF7E7E51660 0000000000000010 0000000000000000  darktable.exe!main  [C:/msys64/home/matze/darktable2/src/main.c @ 92]
    90: #endif
    91: 
>   92:   if(dt_init(argc, argv, TRUE, TRUE, NULL)) exit(1);
    93:   dt_gui_gtk_run(darktable.gui);
    94: 
00007FF7E7E515B4 0000000000000022 0000000000000001 00007FF7E7E57090  darktable.exe!wmain  [C:/msys64/home/matze/darktable2/src/win/main_wrapper.h @ 15]
    13:   for(int i = 0; i < argc; i++)
    14:     _argv[i] = g_utf16_to_utf8(argv[i], -1, NULL, NULL, NULL);
>   15:   int res = main(argc, _argv);
    16:   g_strfreev(_argv);
    17:   return res;
00007FF7E7E513D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!__tmainCRTStartup  [C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 318]
00007FF7E7E51506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!mainCRTStartup  [C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 202]
00007FFD95E97034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFD97CE2651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.7.0.512
ntdll.dll   	10.0.19041.1110
KERNEL32.DLL	10.0.19041.1023
KERNELBASE.dll	10.0.19041.1110
msvcrt.dll  	7.0.19041.546
libintl-8.dll	0.19.8.0
libglib-2.0-0.dll	2.68.3.0
libdarktable.dll
ADVAPI32.dll	10.0.19041.1052
GDI32.dll   	10.0.19041.746
sechost.dll 	10.0.19041.906
win32u.dll  	10.0.19041.1110
ole32.dll   	10.0.19041.746
gdi32full.dll	10.0.19041.1110
RPCRT4.dll  	10.0.19041.1081
ucrtbase.dll	10.0.19041.789
msvcp_win.dll	10.0.19041.789
combase.dll 	10.0.19041.1081
USER32.dll  	10.0.19041.906
PSAPI.DLL   	10.0.19041.546
SHELL32.dll 	10.0.19041.1023
libiconv-2.dll	1.16.0.0
WS2_32.dll  	10.0.19041.546
libwinpthread-1.dll	1.0.0.0
libgcc_s_seh-1.dll
libstdc++-6.dll
libgomp-1.dll
libavif.dll
libcairo-2.dll
libcurl-4.dll
exchndl.dll 	0.9.3.0
libexiv2.dll
CRYPT32.dll 	10.0.19041.844
WLDAP32.dll 	10.0.19041.546
libgdk-3-0.dll	3.24.30.0
libgdk_pixbuf-2.0-0.dll	2.42.6.0
libgio-2.0-0.dll	2.68.3.0
IMM32.dll   	10.0.19041.546
SHLWAPI.dll 	10.0.19041.1023
SETUPAPI.dll	10.0.19041.844
libgmodule-2.0-0.dll	2.68.3.0
cfgmgr32.dll	10.0.19041.546
libgobject-2.0-0.dll	2.68.3.0
bcrypt.dll  	10.0.19041.1023
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libharfbuzz-0.dll
libicuin68.dll
libicuuc68.dll
libIlmImf-2_5.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
lua54.dll
libopenjp2-7.dll
libgtk-3-0.dll	3.24.30.0
liblcms2-2.dll
libpangocairo-1.0-0.dll	1.48.7.0
libpango-1.0-0.dll	1.48.7.0
libpng16-16.dll
libpugixml.dll	1.11.0.0
librsvg-2-2.dll
libsecret-1-0.dll
comdlg32.dll	10.0.19041.906
libsoup-2.4-1.dll
shcore.dll  	10.0.19041.1023
libsqlite3-0.dll
libxml2-2.dll
zlib1.dll
libtiff-5.dll
libpcre-1.dll
libdav1d.dll	5.1.0.0
libaom.dll
MSIMG32.dll 	10.0.19041.546
rav1e.dll
libfontconfig-1.dll
libfreetype-6.dll	2.11.0.0
libpixman-1-0.dll
libexpat-1.dll
VERSION.dll 	10.0.19041.546
mgwhelp.dll 	0.9.3.0
libbrotlidec.dll
libcrypto-1_1-x64.dll	1.1.1.11
libidn2-0.dll
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.11
libzstd.dll
dwmapi.dll  	10.0.19041.746
HID.DLL     	10.0.19041.546
IPHLPAPI.DLL	10.0.19041.546
DNSAPI.dll  	10.0.19041.1023
gdiplus.dll 	10.0.19041.1110
libffi-7.dll
libexif-12.dll
libsystre-0.dll
libltdl-7.dll
WINMM.dll   	10.0.19041.546
libcairo-gobject-2.dll
libfribidi-0.dll
libepoxy-0.dll
libpangowin32-1.0-0.dll	1.48.7.0
libbz2-1.dll
USP10.dll   	10.0.19041.546
libgraphite2.dll
libicudt68.dll
libHalf-2_5.dll
libIex-2_5.dll
libIlmThread-2_5.dll
libImath-2_5.dll
libpangoft2-1.0-0.dll	1.48.7.0
libthai-0.dll
COMCTL32.dll	6.10.19041.1110
USERENV.dll 	10.0.19041.572
libgcrypt-20.dll	1.9.2.0
libatk-1.0-0.dll	2.36.0.0
WINSPOOL.DRV	10.0.19041.1023
liblzma-5.dll	5.2.5.0
libdeflate.dll
libjbig-0.dll
libwebp-7.dll
libbrotlicommon.dll
dbghelp.dll 	10.0.19041.867
libunistring-2.dll	0.9.10.0
libtre-5.dll
libdatrie-1.dll
libgpg-error-0.dll	1.42.0.0
CRYPTBASE.DLL	10.0.19041.546
dbgcore.DLL 	10.0.19041.789
CRYPTSP.dll 	10.0.19041.546
rsaenh.dll  	10.0.19041.1052
bcryptPrimitives.dll	10.0.19041.1023
NSI.dll     	10.0.19041.610
windows.storage.dll	10.0.19041.1081
Wldp.dll    	10.0.19041.662
kernel.appcore.dll	10.0.19041.546
uxtheme.dll 	10.0.19041.1081
OLEAUT32.dll	10.0.19041.985
clbcatq.dll 	2001.12.10941.16384
propsys.dll 	7.0.19041.1023
profapi.dll 	10.0.19041.844
mswsock.dll 	10.0.19041.546
MSCTF.dll   	10.0.19041.1081
DEVOBJ.dll  	10.0.19041.546
WINTRUST.dll	10.0.19041.1110
MSASN1.dll  	10.0.19041.546
AppXDeploymentClient.dll	10.0.19041.1110
Windows.ApplicationModel.dll	10.0.19041.746
twinapi.appcore.dll	10.0.19041.964
mssprxy.dll 	7.0.19041.1023
winhttp.dll 	10.0.19041.1110
IconCodecService.dll	10.0.19041.1
WindowsCodecs.dll	10.0.19041.1023
mrmcorer.dll	10.0.19041.1023
iertutil.dll	11.0.19041.1081
windows.staterepositorycore.dll	10.0.19041.844
bcp47mrm.dll	10.0.19041.867
Windows.UI.dll	10.0.19041.746
WindowManagementAPI.dll
TextInputFramework.dll	10.0.19041.1081
InputHost.dll	10.0.19041.906
wintypes.dll	10.0.19041.1081
CoreMessaging.dll	10.0.19041.746
CoreUIComponents.dll	10.0.19041.546
ntmarta.dll 	10.0.19041.546
libpixbufloader-png.dll
mscms.dll   	10.0.19041.746
ColorAdapterClient.dll	10.0.19041.546
icm32.dll   	10.0.19041.546
libdarkroom.dll
libknight.dll
liblighttable.dll
libmap.dll
libosmgpsmap-1.0-1.dll
libslideshow.dll
libtethering.dll
libavif.dll
libcopy.dll
libexr.dll
libj2k.dll
libjpeg.dll
libpdf.dll
TextShaping.dll

Windows 10.0.19043
DrMingw 0.9.3
```

Thank you!

**Comment by johnny-bit** [comment] 2021-07-27 20:09
your report is a duplicate of previous report. Please see also closed issues when searching.

https://github.com/darktable-org/darktable/issues/9519

if it isn't yet reported, please report to upstream (msys2 i think?)

generally downgrade pango and it'll be fine and it's on upstream.

**Closed by johnny-bit** 2021-07-27 20:09 UTC
Labels: bug: upstream, duplicate, scope: windows support
