### ISSUE TITLE
Slow Exporting of RAW files to JPEG

### ISSUE THREAD

**Issue by blackzerotype** [darktable-org/darktable#16207] opened 2024-01-29 14:22 UTC
### Describe the bug

I noticed that after I did some edits on a few RAW files and started to export them into jpegs (atleast 80% resolution) it takes a very long time to complete. This is my time to edit RAW files in darktable and export them into jpegs. Before I was editing jpg photos and rename them. I am exporting atleast 16 photos per bulk for me to deliver to my client. Does it really take that long for darktable to convert edited RAW photos into JPEGs? Is there an ongoing issue? Is there anything I can do to make it faster? Many thanks in advance.

Please see the specifications of my computer:
- Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz
- 16.0 GB installed
- NVDIA GeFroce GTX 1050Ti graphics card

### Steps to reproduce

1. Go to lighttable view
2. Select folder where to export photos
3. Highlight photos to be exported
4. Update resolution from to 95-90 down to 80
5. Hit export button and waited for the process to complete

### Expected behavior

run faster (the same speed or even faster ) than when I was exporting from jpeg to jpeg

### Logfile | Screenshot | Screencast

![darktable_error3](https://github.com/darktable-org/darktable/assets/154827269/a83bbaa8-b7ee-4c7f-a0ce-27f56ceaca99)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6

### What OS are you using?

Windows

### What is the version of your OS?

Edition	Windows 10 Pro Version	22H2 Installed on	‎28/‎11/‎2022 OS build	19045.3930 Experience	Windows Feature Experience Pack 1000.19053.1000.0

### Describe your system?

- Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz
- 16.0 GB
- NVDIA GeFroce GTX 1050Ti

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVDIA GeFroce GTX 1050Ti

**Comment by gi-man** [comment] 2024-01-29 15:08
We will need a logfile from -d perf from an export to evaluate. It's hard to know what is "too long" without a duration in seconds. 15sec per image? 5min per image? The FAQ in darktable.org has details on how to generate the log.

An area to helps speed up the processing raw is GPU OpenCL working. I see that you have an Nvidia card, but do you have opencl on? An output of darktable-cltest can help discover if this is an issue. 

Please upload both files (please no copy/paste). 

- tag: incomplete

**Comment by blackzerotype** [comment] 2024-01-29 15:23
> In your preferences make sure you don't have a slow Intel GPU selected.

@TurboGit I will uncheck it and give it a shot. Thank you for responding.

**Comment by jenshannoschwalm** [comment] 2024-03-17 17:22
@blackzerotype issue still relevant ?

**Comment by victoryforce** [comment] 2024-05-10 12:15
@blackzerotype I assume that if the problem remained, you would have written about it. Since you forgot to report back, the problem is probably gone. Therefore, I close this issue. Feel free to comment further if the problem is still not completely resolved.

**Closed** 2024-05-10 12:15 UTC
Labels: scope: performance

**Comment by blackzerotype** [comment] 2024-05-14 13:39
> @blackzerotype I assume that if the problem remained, you would have written about it. Since you forgot to report back, the problem is probably gone. Therefore, I close this issue. Feel free to comment further if the problem is still not completely resolved.

@victoryforce So far exporting runs normal. Thank you.
