### ISSUE TITLE
Sony ILCE-6700

### ISSUE THREAD

**Issue by zinger565** [darktable-org/darktable#15017] opened 2023-08-06 10:18 UTC
Hi!

New camera owner here, looks like RAWs have already been uploaded to pixls.us

-----------------------------------------------------------------------------------------------------------------------------------------

Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by kmilos** [comment] 2023-08-06 12:17
Duplicate of darktable-org/rawspeed#507 and https://github.com/darktable-org/darktable/issues/15014

Please search before opening new issues.

**Comment by LebedevRI** [comment] 2023-08-06 15:52
Duplicate of https://github.com/darktable-org/darktable/issues/15014#issuecomment-1666765930

(@kmilos do you not have permission to close issues?)

**Closed by LebedevRI** 2023-08-06 15:52 UTC
Labels: scope: camera support

**Comment by kmilos** [comment] 2023-08-06 16:13
Nope.
