### ISSUE TITLE
Magenta cast on filmic in overexposed highlights

### ISSUE THREAD

**Issue by PaoloAst** [darktable-org/darktable#11944] opened 2022-05-30 13:02 UTC
I'm not able to understand if there is a bug open already, I apologize if I'm duplicating the request.

In a overexposed image the last V6 version, filmic tends to add a magents cast on overexposed parts.
I tried to change from V6 to V5 and choosing a different highlight reconstruction method without results.
I partially solved using the preserve chrominance method to "no" instead of "Max RGB
![Magenta cast](https://user-images.githubusercontent.com/43513892/170997928-012c7d02-e3c2-48a6-b33d-2e6264d3f340.png)
"

**Comment by MStraeten** [comment] 2022-05-30 13:25
there's clipping so you should use a combination of
- highlight reconstruction
- white relative exposure setting in filmicrgb/scene tab
- filmicrgb/reconstruct tab
unfortunately there's no one size fits all aproach, so it's not a bug

**Comment by PaoloAst** [comment] 2022-05-30 15:40
Dear Martin,
thank you 
I remember in the previous versions I was using "reconstruct in LCh" without generating such purple effect. 
the LCh mode should cancel any chroma information using shades of gray.
However, I've just rebuild a fresh installation and it seem the problem disappeared.

**Comment by Nilvus** [comment] 2022-05-30 16:12
> I've just rebuild a fresh installation and it seem the problem disappeared.

So good to close the issue. I do it this time.

**Closed by Nilvus** 2022-05-30 16:12 UTC
