### ISSUE TITLE
Compile error darktable-git 3.7.0.r1062.g294616acb8-1 (fre 17 sep 2021 11:09:20)

### ISSUE THREAD

**Issue by ClaesGitHub** [darktable-org/darktable#10016] opened 2021-09-17 09:15 UTC
```
/var/tmp/pamac-build-claesl/darktable-git/src/darktable/src/common/utility.c:422:5: error: ‘rsvg_handle_get_dimensions’ is deprecated: Use 'rsvg_handle_get_intrinsic_size_in_pixels' instead [-Werror=deprecated-declarations]
  422 |     rsvg_handle_get_dimensions(svg, &dimension);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.

```
Garuda Linux / AUR.

**Comment by Mark-64** [comment] 2021-09-17 09:25
duplicate of #10013

**Closed** 2021-09-17 09:44 UTC
