### ISSUE TITLE
input profile (module input color profile) of .ORF not correctly set after selecting a .JPG file

### ISSUE THREAD

**Issue by tjitsnijholt** [darktable-org/darktable#5954] opened 2020-08-14 13:43 UTC
Next steps are done with the newly released version 3.2.1 on a windows 10 machine.
The version was obtained from https://github.com/darktable-org/darktable/releases/tag/release-3.2.1

1) After importing a directory containing .JPG and .ORF (Olympus Raw File), and then selecting
a  .ORF and then entering darkroom, the input profile of the input color profile module is correctly set to the
standard color matrix.
2) Each time an other .ORF is selected from the filmstrip, the input profile is correct (standard color matrix).
3) When now selecting a .JPG from the filmstrip, the input profile is set to sRGB, which also is correct.
4) However, once selected a .JPG, selecting thereafter a .ORF file which has not been selected before, also gets the sRGB input profile, which is not correct, should be the standard color matrix.  (this results in a much darker image).

I also tried this with a new fresh database, same result.

 - Darktable Version: 3.2.1
 - OS: windows 10
 - OpenCL activated
 - Graphics card: GTX1060 3G

Attached the zipped  .orf.xmp of a raw file which got the sRGB  input profile:

[9.ORF.zip](https://github.com/darktable-org/darktable/files/5074865/9.ORF.zip)

**Comment by tjitsnijholt** [comment] 2020-08-14 16:35
Just did a test on my linux mint 19.3 laptop. Same behaviour!

**Comment by junkyardsparkle** [comment] 2020-08-15 23:59
Nice job finding a reproducible case for this... I have also once or twice recently had .ORF files end up with sRGB for input profile; it seemed related to performing actions on the history of multiple selected files, but I never managed to figure out exactly when it was happening.

**Comment by jenshannoschwalm** [comment] 2020-09-08 18:15
Should also be fixed on current master as it's a duplicate of #6202

**Comment by junkyardsparkle** [comment] 2020-09-08 22:48
It's fixed as far as I can tell. I can no longer produce the issue with the steps given here or any of the other less methodical ways I had been noticing.

**Comment by parafin** [comment] 2020-09-09 19:47
Looks like the same issue as these others and I can confirm that it is fixed, so closing.

**Closed by parafin** 2020-09-09 19:47 UTC
Labels: bug: pending
