### ISSUE TITLE
Color/Spot picker can be used outside picture area, with different unwanted results.

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#3353] opened 2019-11-09 18:25 UTC
darktable 3.0.0rc0+82~g4c6df92a0

**Describe the bug**
When using the color/spot picker you are able to use it outside the image area. This produces (severe) unwanted results.

Depending on the module you try this with it (three examples):

- freezes/crashes dt (exposure module)
- produces a black (or blue) image (filmic rgb module)
- produces a black screen (WB module with spot)

The last two can be recovered by resetting the module.

**To Reproduce**
Use a 'picker', any picker, and click/select outside the image area.

**Expected behavior**
I expect nothing to happen. Click/select outside the image area should be ignored. As it is in version 2.6

**Platform (please complete the following information):**
 - OS: Linux Debian 10.1 (and also confirmed on up-to-date Gentoo)
 - Version  darktable 3.0.0rc0+82~g4c6df92a0

EDIT: words

**Comment by AxelG-DE** [comment] 2019-11-09 18:26
I confirm this

**Comment by blitzgneisserin** [comment] 2019-11-09 20:07
very similar behavior here

**Comment by junkyardsparkle** [comment] 2019-11-09 22:28
I couldn't reproduce the crash/freeze with the exposure module on an image first imported by recent master, however, on a random image from further back in time the freeze happened as soon as I clicked on the picker button, without any further action (image view was showing the default "image-minus-edges" selection)... so there might be more going on with this one.

**Comment by junkyardsparkle** [comment] 2019-11-09 22:40
The situation with the gray value slider in filmic RGB is especially ugly; the resulting zero value is out of normal bounds, and the response of the black and white sliders is to go insane and hide their labels... the labels don't come back after gray is restored to a sane value, or even by reseting the module; the sliders must be double-clicked.

**Comment by jade-nl** [comment] 2020-01-15 06:01
Update after getting a *Stale issue message*  in my in-box:

This issue is still relevant for the current dt versions. Just re-checked using:

- 3.0.0 (stable)
- 3.1.0-362-g39a47f6aa

Only one thing has changed since initially posting this issue: I haven't seen any crashes/freezes when testing to see if this is still relevant.

Just in case the initial description wasn't clear enough:

The picker can be used in the grey "border" area around the image (crossing the border itself is _not_ possible).

**Comment by jade-nl** [comment] 2020-01-26 10:25
I asked Aurelien on IRC about the bot closing this issue even though activity has taken place. He said he disabled the bot and I was hoping that he would re-open this issue as well. Guess not.

Can somebody reopen it, this isn't solved and tags have been added.

**Comment by parafin** [comment] 2020-01-26 10:49
It seems that just commenting is not enough to prevent auto-close - one has to remove no-issue-activity tag from the issue. Do you have permissions to do it?

IMHO it wasn't the best idea to enable this bot.

**Comment by jade-nl** [comment] 2020-01-26 10:58
> one has to remove no-issue-activity tag from the issue. Do you have permissions to do it?

I don't think I do. And if the bot is set up correctly I would think that a normal user shouldn't be able to this.

> IMHO it wasn't the best idea to enable this bot.

I agree. A good culling might be in order and certain issue's could/should be automatically closed but this particular bot needs to be tuned before it is let out of its box. Then again, this is my 2c.....

**Comment by parafin** [comment] 2020-01-26 11:07
> > one has to remove no-issue-activity tag from the issue. Do you have permissions to do it?
> 
> I don't think I do. And if the bot is set up correctly I would think that a normal user shouldn't be able to do this.

I don't think it has anything to do with a bot. Either you can modify labels in the issue or you don't. Do you have a cogwheel icon on the right where labels are?

**Comment by jade-nl** [comment] 2020-01-26 11:16
Nope, no cogwheel. Just, in this case, 5 labels, nothing else.

Check with 2 different browsers, just in case.

- Linux, Devian buster 10.2
- Firefox 68.4.1esr (64-bit)

**Comment by parafin** [comment] 2020-01-26 11:28
So it's very inconvenient - only developer can stop the issue from being closed.

@aurelienpierre, either disable this bot, or rewrite its logic. Having developer to do some manual action defeats the whole purpose of this automation.

**Comment by aurelienpierre** [comment] 2020-01-26 22:49
@parafin ok, will do. Sorry about the inconvenience.

**Comment by chhil** [comment] 2020-01-27 03:40
For people subscribed to all emails it is very difficult to spot the issues that one has logged and take necessary actions in the barrage of emails by the bot every day.

**Comment by johnny-bit** [comment] 2020-02-26 11:16
I've tried to follow code back to where it may cause problems. It seems that it's due to weird area clamping in `color_picker_proxy.c` but I can't find how it's bound to image area. With little bit of testing it seems that color picker area is bound between click-point and nearest image dimmension and you can't get past it (meaning that you can go from waaaay over corner to just about corner of image. any corner). this can be seen on all 6 screnshots (5th to show i can't get past top image corner and is bound by bottom corner despite me starting waay below bottom corner (like on 4th screenshot). Click without drag is possible on any area outside image (6th screenshot).

![bottom left corner area](https://user-images.githubusercontent.com/10687765/75339709-581cb500-5891-11ea-9460-24c595d7af93.png)
![top left corner area](https://user-images.githubusercontent.com/10687765/75339765-69fe5800-5891-11ea-8083-36b49a66bf01.png)
![top right corner area](https://user-images.githubusercontent.com/10687765/75339797-7a163780-5891-11ea-8caf-808b3e601a74.png)
![bottom right corner area](https://user-images.githubusercontent.com/10687765/75339825-8c907100-5891-11ea-96a1-8ec8fa62cb21.png)

dragging from screenshot 4 location to screenshot 3 location shows area bound by image box:
![bottom to top area](https://user-images.githubusercontent.com/10687765/75339888-ac279980-5891-11ea-9445-4f9d92e17887.png)

clicking anywhere is possible (area is on the right - that small white dot)
![click anywhere](https://user-images.githubusercontent.com/10687765/75339924-b8135b80-5891-11ea-9da7-bb1007e84c6a.png)

Pinging @TurboGit since `color_picker_proxy` is mostly his work ;)

**Comment by Nilvus** [comment] 2020-03-07 10:27
@TurboGit: probably to be closed as solved by last #4431 PR

**Comment by TurboGit** [comment] 2020-03-07 11:03
Right, closing. Thanks for the notice.

**Closed by TurboGit** 2020-03-07 11:03 UTC
Labels: bug: pending, difficulty: average, priority: medium, scope: image processing

**Comment by johnny-bit** [comment] 2020-03-07 11:12
Yup, solves all problems I've mentioned earlier, so `darktable 3.1.0+793~ged4000535` works and one cannot pick area outside of image. There are some issues with zoom + picking near border area but I'd need to formulate proper test case.

**Comment by jade-nl** [comment] 2020-03-07 11:38
Fashionable late to my own party, but: Yes, issue is solved.

Thanks all!

**Comment by jenshannoschwalm** [comment] 2020-04-11 08:51
@TurboGit You still have this as todo in projects pipe reordering ...

**Comment by TurboGit** [comment] 2020-04-11 09:04
Are you speaking of this:
https://github.com/darktable-org/darktable/projects/4

I did not create this (Aurélien did I suppose) and I just found about it now, that's why I was confused!

**Comment by jenshannoschwalm** [comment] 2020-04-11 09:06
Right
