### ISSUE TITLE
Darktable 4.4.0 arm64 macOS binaries - app is damaged and cannot be opened error

### ISSUE THREAD

**Issue by krusli** [darktable-org/darktable#14769] opened 2023-06-24 11:56 UTC
### Describe the bug

A download of the release from Releases or from the official website results in this error. I downloaded the arm64 binary for macOS (I am running Monterey 12.5.1).

I successfully managed to launch darktable by clearing attributes by using this command:

`xattr -cr /Applications/darktable.app`

(from https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/).

From what I've gathered it's likely that the published app doesn't match the app when it is signed (see https://stackoverflow.com/questions/22458027/mac-dmg-oddity-signing-and-damaged-applications).

---

After reviewing the install instructions (https://www.darktable.org/install/#macos), there is a different error listed there with a similar resolution, but I am not sure that it is the exact same issue (different error message).

### Steps to reproduce

1. Download darktable from https://www.darktable.org/install/ (https://github.com/darktable-org/darktable/releases/download/release-4.4.0/darktable-4.4.0-arm64.dmg)
2. Open .dmg, copy .app to Applications
3. Open darktable

### Expected behavior

darktable should be able to launch

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0

### What OS are you using?

Mac

### What is the version of your OS?

Monterey 12.5.1

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment] 2023-06-24 12:20
Duplicate of #14746.

Please search before opening new issues.

**Closed** 2023-06-24 15:55 UTC
Labels: scope: macos support
