### ISSUE TITLE
Misleading message when deleting images from Lighttable

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#4558] opened 2020-03-26 17:31 UTC
The message box which pops up when you delete images can be incorrect.

I selected two images then pressed the Delete key and got the message below where dt thinks I only want to delete one image.
![Screenshot from 2020-03-26 17-19-55](https://user-images.githubusercontent.com/16868433/77677152-37767680-6f87-11ea-923a-d9a6d2512787.png)
This seems to be because I've left the cursor hovered over another image. It is NOT selected.

With the mouse away from the images, the message is ok -
![Screenshot from 2020-03-26 17-19-39](https://user-images.githubusercontent.com/16868433/77677315-68ef4200-6f87-11ea-89f3-59f67f0957f3.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1+dirty
 - OS:  Ubuntu 18.04

**Comment by elstoc** [comment] 2020-03-31 20:29
It's not just the message: It will actually delete the image you're hovering over. Looking at the code I think this might be intended functionality.

I believe the way it's intended to work is that if you select one or more images, you have to either have your mouse over one of them or outside the centre view entirely to delete the selection.

It seems non-obvious in the example you've given but if you were to scroll away from the selected images it does make more sense to delete the image your mouse is over.

This is from the code...

```
  /** Here's how it works
   *
   *             mouse over| x | x | x |   |   |
   *     mouse inside table| x | x |   |   |   |
   * mouse inside selection| x |   |   |   |   |
   *          active images| ? | ? | x |   | x |
   *                       |   |   |   |   |   |
   *                       | S | O | O | S | A |
   *  S = selection ; O = mouseover ; A = active images
   *  the mouse can be outside thumbtable in case of filmstrip + mouse in center widget
   **/
```

**Comment by AlicVB** [comment] 2020-03-31 20:36
I confirm, this is how dt works : basically, it's "hovered image first". In some places it's not the case, but this will be fixed, it's on my todo...
Now there's still some counting error sometimes if you have grouped images. This is on my todo list too

**Comment by RawConvert** [comment] 2020-04-01 14:09
I think the "hovering" functionality is wrong and unnecessary. Rip it out!!  I've never seen any other file manager type of functionality where deleting items depends on where you leave the mouse.  dt should surely work simply and intuitively like other software people habitually use, namely you select items with clicks, ctrl clicks, shift clicks etc, then tell it to delete, and it deletes the selected items and nothing else.

**Comment by AlicVB** [comment] 2020-04-01 16:36
> I think the "hovering" functionality is wrong and unnecessary. Rip it out!!

Certainly not ! It's how darktable works from the beginning. Yes, it's not "like the other software" but once you're used to that, you'll discover that it allow lot of things you can't do with "classic" behavior (or at least not so straightforward)
I'll close as won't fix, sorry !

**Closed by AlicVB** 2020-04-01 16:36 UTC

**Comment by RawConvert** [comment] 2020-04-02 10:34
You say it's how dt works from the beginning but I can't see any mention of hovering in the manual where deletion is covered.  Software is usually about continuous improvement bit by bit and sometimes that means removing things that might have seemed like a good idea but are not really.  This hovering "feature" is confusing and though you might get used to it, that doesn't make it any better.  How many newcomers will see the silly message, wonder what is going on, possibly delete the wrong image, waste their time, report a bug, waste your time, and so on.....  As a developer perhaps you should ask in the forum what people think and guard against being too invested in the status quo.

**Comment by paolobenve** [comment] 2020-08-11 07:30
I think the behaviour is counter-intuitive, only a user which is very inside dt will understand this feature and use it.

Other users are surely confused, and myself got some wrong image deleted, which I couldn't recover :-(

**Comment by ptilopteri** [comment] 2020-08-11 13:44
@paolobenve 
It is as with any software, a learning experience.  You didn't notice that the image below the mouse marker was *always* highlighted?  Or that actions got performed on the highlighted image, the one below the mouse marker?
There will always be something that you personally find "counter intuitive" but others do not and there will always be an uncounted "group" that feels the same way as you.  It is and has been for *many* years, the way of darktable.

**Comment by paolobenve** [comment] 2020-08-11 14:48
Well, maybe the problem is with the evidence of the selection? it might be necessary to give more visibility to the actual selection, i.e. the mouse hover one?

**Comment by ptilopteri** [comment] 2020-08-11 15:28
I do not have capability to "reopen" an issue and believe it wasted effort.

But I also have not found use for and have disabled "Trash" where ever possible.

"Bad behavour" is opinion and has not been shared by the dev's.

fwiw: everyone will loose images/files one time or another from carelessness or laziness or ... and then one must rely on their backups to recover.

The optimal solution is to become familiar with the software you choose to employe.

**Comment by RawConvert** [comment] 2020-08-16 16:33
@AlicVB , @ptilopteri , another user with deletion issues at #5987 !!
