### ISSUE TITLE
crash on mac 3.6.1.5

### ISSUE THREAD

**Issue by SoupyGit** [darktable-org/darktable#10087] opened 2021-09-26 04:35 UTC
**Did you buy darktable from an application store ?**
No, downloaded .dmg from https://github.com/darktable-org/darktable/releases/tag/release-3.6.1

**Describe the bug/issue**

Mac 10.12.6, darktable 3.6.1.5.dmg from github. Before downloading this version, I had uninstalled the old version (3.6), and rearranged my folder structure and image filenames. Thus all my film rolls were crossed out in collections. I ran darktable-generate-cache, removed each film roll one by one until there were none left, then tried to import a new folder. Only a few images imported before darktable crashed. The program may also crash if I click on the (partially) imported collection and change the ‘view’ from 5 star to all. If that doesn’t make it crash, double clicking on the collection will. Sometimes, it will simply crash upon opening.

Note: After these crashes, I uninstalled 3.6.1.5, reinstalled 3.6.0.3, and it did not crash. So 3.6.1.5 introduces the error.

Here is the .txt after running darktable -d all
[darktable crash on import -d all.txt](https://github.com/darktable-org/darktable/files/7230714/darktable.crash.on.import.-d.all.txt)

Final lines before crash are:

dyld: lazy symbol binding failed: Symbol not found: _aligned_alloc
Referenced from: /Applications/darktable.app/Contents/MacOS/…/Resources/lib/darktable/libdarktable.dylib
Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _aligned_alloc
Referenced from: /Applications/darktable.app/Contents/MacOS/…/Resources/lib/darktable/libdarktable.dylib
Expected in: /usr/lib/libSystem.B.dylib

Magick: abort due to signal 6 (SIGABRT) “Abort”…
Abort trap: 6

When I look in finder, libSystem.B.dylib is present in /usr/lib.

Not sure if this is related, or a problem of note:

(process:3870): GLib-GObject-CRITICAL **: 20:26:25.903: g_object_set: assertion ‘G_IS_OBJECT (object)’ failed
0.736241 output profile XYZ identity built-in' color space XYZ ’ not supported for work or histogram profile

**Which commit introduced the error**
3.6.1.5

**Platform**
* darktable version : 3.6.1.5
* OS                : Mac 10.12.6
* Memory            : 4 GB 1600 MHz DDR3
* Graphics card     : NVIDIA GeForce GT 650M 512 MB and Intel HD Graphics 4000 1536 MB (crashes on both)
* OpenCL installed  : Y
* OpenCL activated  : Y

 - Can you reproduce with another darktable version(s)? No. 3.6.0.3 did not crash.
 - Do you use lua scripts? No.

**Comment by parafin** [comment] 2021-09-26 07:39
Thanx for reporting. I didn't catch this, but latest build supports only macOS 10.15+. This is due to rawspeed update, specifically commit https://github.com/darktable-org/rawspeed/commit/138171fe92b255f7202094032cee80706082f8f0 which switches to aligned_alloc function available only on macOS 10.15+ as default. The problem is that aligned_alloc is reported as available by https://github.com/darktable-org/rawspeed/blob/develop/cmake/Modules/memory-align-alloc.cmake#L11 check, because that check is stupid and doesn't know about deployment targets - aligned_alloc indeed is present in the header, but it's not actually available. I guess some additional #ifdef's are needed here.
Pinging @LebedevRI

**Comment by SoupyGit** [comment] 2021-09-26 09:38
Thanks, does this mean 3.6.0.3 is going to be the last available version for Mac prior to 10.15? Or that a fix of the problem will enable future versions, such as 3.8, to be available for Mac prior to 10.15?

Every time I try to update my Mac it becomes unusable, which is why I continue with such an old version... Might finally be time for that new CPU.

**Comment by LebedevRI** [comment] 2021-09-26 10:04
@parafin i believe the problem is on your end.
As you can see for yourself, rawspeed commit used by darktable master, https://github.com/darktable-org/rawspeed/commits/d063134f27f7eee4bc870852b82488e9bf61bccb, i believe, does not actually use `aligned_alloc`:
https://github.com/darktable-org/rawspeed/runs/3575043568?check_suite_focus=true#step:4:208

**Comment by parafin** [comment] 2021-09-26 11:12
Well, I'm building darktable, not rawspeed, and aligned_alloc is detected in CI there: https://github.com/darktable-org/darktable/runs/3585046306#step:4:232

So there seem to be some difference in cmake code between rawspeed and darktable I guess.

**Comment by LebedevRI** [comment] 2021-09-26 11:21
I see.
https://github.com/darktable-org/darktable/runs/3585046152#step:4:10 is not sufficient,
you need https://github.com/darktable-org/rawspeed/runs/3575043568?check_suite_focus=true#step:4:14

**Comment by parafin** [comment] 2021-09-26 11:34
I think there is a problem with -mmacosx-version-min=10.7 that prevents weak linking working on macOS and darktable use it for CUPS support. So it's not possible to enable globally. Maybe we could enable it just for rawspeed, I will take a look.

**Comment by parafin** [comment] 2021-09-27 08:13
I tried setting CFLAGS and CXXFLAGS to -mmacosx-version-min=10.7, but cmake still reports "-- Looking for aligned_alloc - found". Maybe it depends on Xcode version? About weak linking I confused -mmacosx-version-min= with -D__MAC_OS_X_VERSION_MAX_ALLOWED=, -mmacosx-version-min= should be fine, but I don't see how it can affect CHECK_CXX_SYMBOL_EXISTS, since deployment target doesn't actually prevent code from using the symbols from newer OS versions, it just uses weak linking for them.

@LebedevRI, to summarize - I have no idea why rawspeed CI reports aligned_alloc not available. I think this should be solved with explicit checks for deployment target either in cmake or C++ code, unless you know how to make CHECK_CXX_SYMBOL_EXISTS take deployment target into account.

**Comment by LebedevRI** [comment] 2021-09-27 08:34
Can you see if deleting https://github.com/darktable-org/darktable/blob/3a42bcc8ea0a54d040fce3f1cce3725bf5abec60/src/external/CMakeLists.txt#L34-L35 helps?

**Comment by parafin** [comment] 2021-09-28 07:25
@LebedevRI, indeed that was it! I see from the git log that it was you who added those flags back in 2017. Shall I revert 33103e39d6?

Also one note - adding -mmacosx-version-min= explicitly to CFLAGS doesn't seem to be required (at least for this), and looking at cmake description of CMAKE_OSX_DEPLOYMENT_TARGET cmake adds it by itself.

@SoupyGit, to answer your question about macOS support: I will update 3.6.1 package for macOS once we resolve this issue to support macOS 10.7+. But we will drop support for macOS versions older than 10.14 (maybe 10.14 too) this or next year, either for 3.10 or 3.8 major darktable release. So if your hardware doesn't support macOS 10.14/10.15, then you should start thinking about upgrade if you want to continue to get latest darktable updates.

**Comment by LebedevRI** [comment] 2021-09-28 07:28
> @LebedevRI, indeed that was it!

I see. Thanks for confirming. I guess the check fails without `-w` because there is
a clang diagnostic about using something that isn't available until later deployment target.

>I see from the git log that it was you who added those flags back in 2017. Shall I revert [33103e3](https://github.com/darktable-org/darktable/commit/33103e39d67e73c80dc872d1c08226a09799cb8f)?

No, i need to fix this in rawspeed.

> Also one note - adding -mmacosx-version-min= explicitly to CFLAGS doesn't seem to be required (at least for this), and looking at cmake description of CMAKE_OSX_DEPLOYMENT_TARGET cmake adds it by itself.

Well, it seemed to be needed when i tried. Strange.

**Comment by SoupyGit** [comment] 2021-09-28 11:32
Thanks so much for the work on this!

> But we will drop support for macOS versions older than 10.14 (maybe 10.14 too) this or next year, either for 3.10 or 3.8 major darktable release.

I pray your drop it next year, not this, and dt 3.8 works on macOS 10.7+! At 3.8 I will consider darktable 99% feature complete. Of course the show will go on, and many great things will be added after that, but for my usage, the only thing I really wish I had now but don't is deconvolution sharpening, which is coming in 3.8 with Diffuse and Sharpen module. I understand old gear cannot be supported forever and I need to upgrade soon, but to be able to keep this laptop running until it dies with dt 3.8 would be a dream.

**Comment by LebedevRI** [comment] 2021-09-28 13:09
> > @LebedevRI, indeed that was it!
> 
> I see. Thanks for confirming. I guess the check fails without `-w` because there is a clang diagnostic about using something that isn't available until later deployment target.
> 
> > I see from the git log that it was you who added those flags back in 2017. Shall I revert [33103e3](https://github.com/darktable-org/darktable/commit/33103e39d67e73c80dc872d1c08226a09799cb8f)?
> 
> No, i need to fix this in rawspeed.
@parafin TBN i don't believe this is a blocker for you, since you can just drop those two lines before building your package.
This isn't a generally-reasonable solution because generally submodule can't be expected to respect
whatever the warning flags specified by the parent build, but for one-off build it's fine.

**Comment by parafin** [comment] 2021-09-28 14:34
OK, I will drop these 2 lines in darktable-3.6.x branch and rebuild the 3.6.1 package.

Let's keep this ticket open then until real fix is introduced in rawspeed to fix this issue in master darktable branch.

**Comment by parafin** [comment] 2021-09-28 21:51
@SoupyGit, could you please try this package: https://github.com/darktable-org/darktable/releases/download/release-3.6.1/darktable-3.6.1.6.dmg?

@LebedevRI, FYI, just plain reverting 33103e3 results in CI build failure on Linux: https://github.com/darktable-org/darktable/runs/3737675489?check_suite_focus=true#step:5:443

**Comment by SoupyGit** [comment] 2021-09-29 00:47
> @SoupyGit, could you please try this package: https://github.com/darktable-org/darktable/releases/download/release-3.6.1/darktable-3.6.1.6.dmg?

Works! No crash, images import as expected. Thank you!

**Comment by Nilvus** [comment] 2021-10-04 20:22
> > @SoupyGit, could you please try this package: https://github.com/darktable-org/darktable/releases/download/release-3.6.1/darktable-3.6.1.6.dmg?
> 
> Works! No crash, images import as expected. Thank you!

Great, so this issue could be closed. I do it, think about closing next time when issue is fixed to help darktable team see which issues remains to work on. Thanks.

**Comment by SoupyGit** [comment] 2021-10-05 05:57
I didn't know I had authority to close. Will keep that in mind for any future issues.
Also, Parafin said this

> Let's keep this ticket open then until real fix is introduced in rawspeed to fix this issue in master darktable branch.

I don't know code, but my understanding of the above conversation was that the current fix was not the real fix in rawspeed, therefore devs wanted issue to remain open. Forgive me if misinterpreted.

**Comment by parafin** [comment] 2021-10-05 13:41
this issue is not solved in master

**Comment by Nilvus** [comment] 2021-10-05 16:37
Ok, sorry if I misunderstood.

**Comment by parafin** [comment] 2021-10-16 16:24
@LebedevRI, do you have any timeline on fixing this issue in rawspeed? If not, I think I will apply the workaround from darktable-3.6.x branch to master, since current state is unusable on macOS 10.14, which I still have.

**Closed** 2021-11-01 16:28 UTC
Labels: bug: wip, scope: macos support

**Comment by LebedevRI** [comment] 2021-11-07 21:54
> @LebedevRI, do you have any timeline on fixing this issue in rawspeed? If not, I think I will apply the workaround from darktable-3.6.x branch to master, since current state is unusable on macOS 10.14, which I still have.

I don't have any timeline, much like i didn't even bother to see this comment before today.
It's effectively on best-effort life-support. I've fixed it in https://github.com/darktable-org/rawspeed/pull/317 now.
