### ISSUE TITLE
GPR-Pictures flipped upside down in editing Area

### ISSUE THREAD

**Issue by hansekiter** [darktable-org/darktable#2854] opened 2019-08-13 09:14 UTC
**Describe the bug**
GPR-Raw Files are imported into Darktable but are flipped upside down in the big editing area.
Were in the small preview (upper left corner) its displayed correctly. 

The GoPro also did 2 Pictures one GPR one JPG. The JPG is correcly orrientated. The GPR-Raw File not

**To Reproduce**
Import GPR File. 
Sometimes is already flipped by now.
If not open the GPR File in the darkroom (Dunkelkammer). 
Now the image should be displayed upside down in the big editing area and right way up in the preview.
While zooming in and out the GPR File the image is also right way up for a short period of time. 

**Expected behavior**
I expect the Pciture to be right way up in the editing area. 

**Screenshots**
Screenshot 1: Here the preview (upper left) is looking good while in editing area the image is flipped. 
Screenshot 2: Here you can see the Lighttable with some JPGs and some GPRs. All are taken witht the GoPro 

![Screenshot1](https://user-images.githubusercontent.com/53862597/62929831-8cc89380-bdbb-11e9-99c6-0528813d174d.PNG)
![Screenshot2](https://user-images.githubusercontent.com/53862597/62929832-8d612a00-bdbb-11e9-82b1-c4dc78153964.PNG)

**Platform :**
 - OS: 		Win 10
 - Version: 1903	
 - Build:	18362.267
 
**Camera :**
 - Vendor:	GoPro
 - Model :	HERO7 Black 
 
**Additional context**
exiv output for Picutre shown in Screenshot1: 

PS C:\exiv2\bin> .\exiv2.exe -pt pr 'C:\<PATH>\in_work\GOPR1034.GPR'
Exif.Image.NewSubfileType                    Long        1  Primary image
Exif.Image.ImageWidth                        Long        1  4000
Exif.Image.ImageLength                       Long        1  3000
Exif.Image.BitsPerSample                     Short       1  16
Exif.Image.Compression                       Short       1  JBIG B&W
Exif.Image.PhotometricInterpretation         Short       1  Color Filter Array
Exif.Image.ImageDescription                  Ascii      30  C:\DCIM\100GOPRO\GOPR1034.GPR
Exif.Image.Make                              Ascii       6  GoPro
Exif.Image.Model                             Ascii      12  HERO7 Black
Exif.Image.Orientation                       Short       1  top, right
Exif.Image.SamplesPerPixel                   Short       1  1
Exif.Image.PlanarConfiguration               Short       1  1
Exif.Image.Software                          Ascii      16  HD7.01.01.70.00
Exif.Image.DateTime                          Ascii      20  2019:08:02 10:52:59
Exif.Image.TileWidth                         Long        1  4000
Exif.Image.TileLength                        Long        1  3000
Exif.Image.TileOffsets                       Long        1  14622
Exif.Image.TileByteCounts                    Long        1  3409792
Exif.Image.XMLPacket                         Byte      4442  (Binary value suppressed)
Exif.Image.CFARepeatPatternDim               Short       2  2 2
Exif.Image.CFAPattern                        Byte        4  0 1 1 2
Exif.Image.ExifTag                           Long        1  14180
Exif.Photo.ExposureTime                      Rational    1  1/1507 s
Exif.Photo.FNumber                           Rational    1  F2.8
Exif.Photo.ExposureProgram                   Short       1  Auto
Exif.Photo.ISOSpeedRatings                   Short       1  100
Exif.Photo.DateTimeOriginal                  Ascii      20  2019:08:02 10:52:59
Exif.Photo.DateTimeDigitized                 Ascii      20  2016:03:25 15:55:23
Exif.Photo.ApertureValue                     Rational    1  F2.8
Exif.Photo.ExposureBiasValue                 SRational   1  -1/2 EV
Exif.Photo.MaxApertureValue                  Rational    1  F2.8
Exif.Photo.MeteringMode                      Short       1  Average
Exif.Photo.LightSource                       Short       1  Unknown
Exif.Photo.Flash                             Short       1  No flash function
Exif.Photo.FocalLength                       Rational    1  3.0 mm
Exif.Photo.FocalPlaneXResolution             Rational    1  72
Exif.Photo.FocalPlaneYResolution             Rational    1  72
Exif.Photo.SensingMethod                     Short       1  One-chip color area
Exif.Photo.FileSource                        Undefined   1  Digital still camera
Exif.Photo.SceneType                         Undefined   1  Directly photographed
Exif.Photo.ExposureMode                      Short       1  Auto
Exif.Photo.WhiteBalance                      Short       1  Auto
Exif.Photo.DigitalZoomRatio                  Rational    1  1.0
Exif.Photo.FocalLengthIn35mmFilm             Short       1  15.0 mm
Exif.Photo.SceneCaptureType                  Short       1  Landscape
Exif.Photo.GainControl                       Short       1  None
Exif.Photo.Contrast                          Short       1  Normal
Exif.Photo.Saturation                        Short       1  Normal
Exif.Photo.Sharpness                         Short       1  Normal
Exif.Image.DNGVersion                        Byte        4  1 3 0 0
Exif.Image.DNGBackwardVersion                Byte        4  1 1 0 0
Exif.Image.UniqueCameraModel                 Ascii      18  GoPro HERO7 Black
Exif.Image.LocalizedCameraModel              Ascii      18  GoPro HERO7 Black
Exif.Image.CFAPlaneColor                     Byte        3  0 1 2
Exif.Image.CFALayout                         Short       1  Rectangular (or square) layout
Exif.Image.BlackLevelRepeatDim               Short       2  2 2
Exif.Image.BlackLevel                        Rational    4  0/256 0/256 0/256 0/256
Exif.Image.WhiteLevel                        Short       1  16383
Exif.Image.DefaultScale                      Rational    2  4000/4000 3000/3000
Exif.Image.DefaultCropOrigin                 Rational    2  0/1 0/1
Exif.Image.DefaultCropSize                   Rational    2  4000/1 3000/1
Exif.Image.ColorMatrix1                      SRational   9  18331/10000 -8166/10000 -2478/10000 1391/10000 8961/10000 -367/10000 822/10000 662/10000 2597/10000
Exif.Image.ColorMatrix2                      SRational   9  10344/10000 -4210/10000 -620/10000 -2315/10000 10625/10000 1948/10000 93/10000 1058/10000 5541/10000
Exif.Image.AnalogBalance                     Rational    3  1000000/1000000 1000000/1000000 1000000/1000000
Exif.Image.AsShotNeutral                     Rational    3  552916/1000000 1000000/1000000 545842/1000000
Exif.Image.BaselineExposure                  SRational   1  0/100
Exif.Image.BaselineNoise                     Rational    1  100/100
Exif.Image.BaselineSharpness                 Rational    1  100/100
Exif.Image.BayerGreenSplit                   Long        1  0
Exif.Image.LinearResponseLimit               Rational    1  100/100
Exif.Image.CameraSerialNumber                Ascii      15  C3281325945692
Exif.Image.AntiAliasStrength                 Rational    1  100/100
Exif.Image.ShadowScale                       Rational    1  1/1
Exif.Image.CalibrationIlluminant1            Short       1  3
Exif.Image.CalibrationIlluminant2            Short       1  23
Exif.Image.BestQualityScale                  Rational    1  1/1
Exif.Image.OriginalRawFileName               Ascii       9  RAW FILE
Exif.Image.ActiveArea                        Long        4  0 0 3000 4000
Exif.Image.ProfileName                       Ascii      18  GoPro HERO7 Black
Exif.Image.ProfileEmbedPolicy                Long        1  0
Exif.Image.OpcodeList2                       Undefined 8468  (Binary value suppressed)
Exif.Image.NoiseProfile                      Double      2  0.000156201000208966 4.88001994369824e-08

exiv output for Pictures shown in Screenshot2: 

PS C:\exiv2\bin> .\exiv2.exe -pt pr 'C:\<PATH>\in_work\GOPR0988.GPR'
Exif.Image.NewSubfileType                    Long        1  Primary image
Exif.Image.ImageWidth                        Long        1  4000
Exif.Image.ImageLength                       Long        1  3000
Exif.Image.BitsPerSample                     Short       1  16
Exif.Image.Compression                       Short       1  JBIG B&W
Exif.Image.PhotometricInterpretation         Short       1  Color Filter Array
Exif.Image.ImageDescription                  Ascii      30  C:\DCIM\100GOPRO\GOPR0988.GPR
Exif.Image.Make                              Ascii       6  GoPro
Exif.Image.Model                             Ascii      12  HERO7 Black
Exif.Image.Orientation                       Short       1  top, right
Exif.Image.SamplesPerPixel                   Short       1  1
Exif.Image.PlanarConfiguration               Short       1  1
Exif.Image.Software                          Ascii      16  HD7.01.01.70.00
Exif.Image.DateTime                          Ascii      20  2019:07:30 12:43:07
Exif.Image.TileWidth                         Long        1  4000
Exif.Image.TileLength                        Long        1  3000
Exif.Image.TileOffsets                       Long        1  14792
Exif.Image.TileByteCounts                    Long        1  3929500
Exif.Image.XMLPacket                         Byte      4442  (Binary value suppressed)
Exif.Image.CFARepeatPatternDim               Short       2  2 2
Exif.Image.CFAPattern                        Byte        4  0 1 1 2
Exif.Image.ExifTag                           Long        1  14192
Exif.Photo.ExposureTime                      Rational    1  1/1270 s
Exif.Photo.FNumber                           Rational    1  F2.8
Exif.Photo.ExposureProgram                   Short       1  Auto
Exif.Photo.ISOSpeedRatings                   Short       1  100
Exif.Photo.DateTimeOriginal                  Ascii      20  2019:07:30 12:43:07
Exif.Photo.DateTimeDigitized                 Ascii      20  2016:03:25 15:55:23
Exif.Photo.ApertureValue                     Rational    1  F2.8
Exif.Photo.ExposureBiasValue                 SRational   1  -1/2 EV
Exif.Photo.MaxApertureValue                  Rational    1  F2.8
Exif.Photo.MeteringMode                      Short       1  Average
Exif.Photo.LightSource                       Short       1  Unknown
Exif.Photo.Flash                             Short       1  No flash function
Exif.Photo.FocalLength                       Rational    1  3.0 mm
Exif.Photo.FocalPlaneXResolution             Rational    1  72
Exif.Photo.FocalPlaneYResolution             Rational    1  72
Exif.Photo.SensingMethod                     Short       1  One-chip color area
Exif.Photo.FileSource                        Undefined   1  Digital still camera
Exif.Photo.SceneType                         Undefined   1  Directly photographed
Exif.Photo.ExposureMode                      Short       1  Auto
Exif.Photo.WhiteBalance                      Short       1  Auto
Exif.Photo.DigitalZoomRatio                  Rational    1  1.0
Exif.Photo.FocalLengthIn35mmFilm             Short       1  15.0 mm
Exif.Photo.SceneCaptureType                  Short       1  Landscape
Exif.Photo.GainControl                       Short       1  None
Exif.Photo.Contrast                          Short       1  Normal
Exif.Photo.Saturation                        Short       1  Normal
Exif.Photo.Sharpness                         Short       1  Normal
Exif.Image.GPSTag                            Long        1  14634
Exif.GPSInfo.GPSVersionID                    Byte        4  2.2.0.0
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  North
Exif.GPSInfo.GPSLatitude                     Rational    3  53deg 36' 11.135"
Exif.GPSInfo.GPSLongitudeRef                 Ascii       2  East
Exif.GPSInfo.GPSLongitude                    Rational    3  6deg 43' 32.022"
Exif.GPSInfo.GPSAltitudeRef                  Byte        1  Above sea level
Exif.GPSInfo.GPSAltitude                     Rational    1  41.6 m
Exif.GPSInfo.GPSDifferential                 Short       1  Without correction
Exif.Image.DNGVersion                        Byte        4  1 3 0 0
Exif.Image.DNGBackwardVersion                Byte        4  1 1 0 0
Exif.Image.UniqueCameraModel                 Ascii      18  GoPro HERO7 Black
Exif.Image.LocalizedCameraModel              Ascii      18  GoPro HERO7 Black
Exif.Image.CFAPlaneColor                     Byte        3  0 1 2
Exif.Image.CFALayout                         Short       1  Rectangular (or square) layout
Exif.Image.BlackLevelRepeatDim               Short       2  2 2
Exif.Image.BlackLevel                        Rational    4  0/256 0/256 0/256 0/256
Exif.Image.WhiteLevel                        Short       1  16383
Exif.Image.DefaultScale                      Rational    2  4000/4000 3000/3000
Exif.Image.DefaultCropOrigin                 Rational    2  0/1 0/1
Exif.Image.DefaultCropSize                   Rational    2  4000/1 3000/1
Exif.Image.ColorMatrix1                      SRational   9  18331/10000 -8166/10000 -2478/10000 1391/10000 8961/10000 -367/10000 822/10000 662/10000 2597/10000
Exif.Image.ColorMatrix2                      SRational   9  10344/10000 -4210/10000 -620/10000 -2315/10000 10625/10000 1948/10000 93/10000 1058/10000 5541/10000
Exif.Image.AnalogBalance                     Rational    3  1000000/1000000 1000000/1000000 1000000/1000000
Exif.Image.AsShotNeutral                     Rational    3  579186/1000000 1000000/1000000 518219/1000000
Exif.Image.BaselineExposure                  SRational   1  0/100
Exif.Image.BaselineNoise                     Rational    1  100/100
Exif.Image.BaselineSharpness                 Rational    1  100/100
Exif.Image.BayerGreenSplit                   Long        1  0
Exif.Image.LinearResponseLimit               Rational    1  100/100
Exif.Image.CameraSerialNumber                Ascii      15  C3281325945692
Exif.Image.AntiAliasStrength                 Rational    1  100/100
Exif.Image.ShadowScale                       Rational    1  1/1
Exif.Image.CalibrationIlluminant1            Short       1  3
Exif.Image.CalibrationIlluminant2            Short       1  23
Exif.Image.BestQualityScale                  Rational    1  1/1
Exif.Image.OriginalRawFileName               Ascii       9  RAW FILE
Exif.Image.ActiveArea                        Long        4  0 0 3000 4000
Exif.Image.ProfileName                       Ascii      18  GoPro HERO7 Black
Exif.Image.ProfileEmbedPolicy                Long        1  0
Exif.Image.OpcodeList2                       Undefined 8468  (Binary value suppressed)
Exif.Image.NoiseProfile                      Double      2  0.000156201000208966 4.88001994369824e-08

PS C:\exiv2\bin> .\exiv2.exe -pt pr 'C:\Users\domin\Desktop\in_work\GOPR0988.JPG'
Exif.Image.ImageDescription                  Ascii      32  DCIM\100GOPRO\GOPR0988.JPG
Exif.Image.Make                              Ascii      30  GoPro
Exif.Image.Model                             Ascii      30  HERO7 Black
Exif.Image.Orientation                       Short       1  top, left
Exif.Image.XResolution                       Rational    1  72
Exif.Image.YResolution                       Rational    1  72
Exif.Image.ResolutionUnit                    Short       1  inch
Exif.Image.Software                          Ascii      24  HD7.01.01.70.00
Exif.Image.DateTime                          Ascii      20  2019:07:30 12:43:07
Exif.Image.YCbCrPositioning                  Short       1  Centered
Exif.Image.ExifTag                           Long        1  158
Exif.Photo.ExposureTime                      Rational    1  1/1270 s
Exif.Photo.FNumber                           Rational    1  F2.8
Exif.Photo.ExposureProgram                   Short       1  Auto
Exif.Photo.ISOSpeedRatings                   Short       1  100
Exif.Photo.ExifVersion                       Undefined   4  2.21
Exif.Photo.DateTimeOriginal                  Ascii      20  2019:07:30 12:43:07
Exif.Photo.DateTimeDigitized                 Ascii      20  2019:07:30 12:43:07
Exif.Photo.ComponentsConfiguration           Undefined   4  YCbCr
Exif.Photo.CompressedBitsPerPixel            Rational    1  0.003367
Exif.Photo.ShutterSpeedValue                 SRational   1  1/1024 s
Exif.Photo.ApertureValue                     Rational    1  F2.8
Exif.Photo.ExposureBiasValue                 SRational   1  -1/2 EV
Exif.Photo.MaxApertureValue                  Rational    1  F2.8
Exif.Photo.SubjectDistance                   Rational    1  Unknown
Exif.Photo.MeteringMode                      Short       1  Average
Exif.Photo.LightSource                       Short       1  Unknown
Exif.Photo.Flash                             Short       1  No flash function
Exif.Photo.FocalLength                       Rational    1  3.0 mm
Exif.Photo.MakerNote                         Undefined 2312  (Binary value suppressed)
Exif.Photo.FlashpixVersion                   Undefined   4      .

Exif.Photo.ColorSpace                        Short       1  (0)
Exif.Photo.PixelXDimension                   Long        1  4000
Exif.Photo.PixelYDimension                   Long        1  3000
Exif.Photo.InteroperabilityTag               Long        1  656
Exif.Iop.InteroperabilityIndex               Ascii       4  R98
Exif.Iop.InteroperabilityVersion             Undefined   4  1.00
Exif.Photo.ExposureIndex                     Rational    1  4294967190/2
Exif.Photo.SensingMethod                     Short       1  One-chip color area
Exif.Photo.FileSource                        Undefined   1  Digital still camera
Exif.Photo.SceneType                         Undefined   1  Directly photographed
Exif.Photo.CustomRendered                    Short       1  Normal process
Exif.Photo.ExposureMode                      Short       1  Auto
Exif.Photo.WhiteBalance                      Short       1  Auto
Exif.Photo.DigitalZoomRatio                  Rational    1  1.0
Exif.Photo.FocalLengthIn35mmFilm             Short       1  15.0 mm
Exif.Photo.SceneCaptureType                  Short       1  Landscape
Exif.Photo.GainControl                       Short       1  None
Exif.Photo.Contrast                          Short       1  Normal
Exif.Photo.Saturation                        Short       1  Normal
Exif.Photo.Sharpness                         Short       1  Normal
Exif.Photo.DeviceSettingDescription          Undefined   4  0 0 0 0
Exif.Photo.SubjectDistanceRange              Short       1  Unknown
Exif.Photo.BodySerialNumber                  Ascii      30  C3281325945692
Exif.Image.GPSTag                            Long        1  686
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  North
Exif.GPSInfo.GPSLatitude                     Rational    3  53deg 36' 11.135"
Exif.GPSInfo.GPSLongitudeRef                 Ascii       2  East
Exif.GPSInfo.GPSLongitude                    Rational    3  6deg 43' 32.022"
Exif.GPSInfo.GPSAltitudeRef                  Byte        1  Above sea level
Exif.GPSInfo.GPSAltitude                     Rational    1  41.6 m
Exif.GPSInfo.GPSTimeStamp                    Rational    3  10:42:44
Exif.GPSInfo.GPSDateStamp                    Ascii      11  2019:07:30
Exif.Thumbnail.Compression                   Short       1  JPEG (old-style)
Exif.Thumbnail.XResolution                   Rational    1  72
Exif.Thumbnail.YResolution                   Rational    1  72
Exif.Thumbnail.ResolutionUnit                Short       1  inch
Exif.Thumbnail.JPEGInterchangeFormat         Long        1  44020
Exif.Thumbnail.JPEGInterchangeFormatLength   Long        1  18164

**Comment by LebedevRI** [comment] 2019-08-13 15:57
You didn't attach a sample.

**Comment by hansekiter** [comment] 2019-08-14 09:20
Sorry, attached the two reffered GPR Pictures in a zip. GPR-Files are blocked for upload.
[sample_pictures.zip](https://github.com/darktable-org/darktable/files/3500659/sample_pictures.zip)

**Comment by jenshannoschwalm** [comment] 2019-08-19 18:11
Can't reproduce this with the provided files on current 2.7dt on fedora 30.

**Comment by TurboGit** [comment] 2019-08-19 18:32
Orientation has been fixed in 2.7 indeed. In some cases going from 2.6 to 2.7 it may be needed to fix orientation which was buggy in 2.6.x.

**Closed by TurboGit** 2019-08-19 18:32 UTC
