### ISSUE TITLE
Check xmp on start not working on Windows

### ISSUE THREAD

**Issue by Jognu** [darktable-org/darktable#5697] opened 2020-07-02 23:30 UTC
**Describe the bug**
I use darktable with the parameter "check xmp on start" to update the database with the modifications of the xmp from an other computer (the files are synchronise).
But when I open darktable after the modification of the xmp, there is no window that appear to ask what to do with the modifications.

**To Reproduce**
Enable the parameter on the configuration.
Close darktable.
Edit the xmp with a visible change.
Open darktable : no window and the changes are not visible.

**Platform :**
 - Darktable Version: 3.0.1 and also try with 3.0.2
 - OS: Windows 10

**Additional context**
Same behavior on two computers (same configuration on the two).

**Comment by Mark-64** [comment] 2020-07-04 06:08
I can't reproduce the issue using DT git master on Windows 10 or Ubuntu.
I have done a test folder with RAW files from several different brands, to check filename-related problems.
The crawler dialog with xmp files changed appears normally, and the modified xmp are applied.
Please help us making a check starting from a clean, newly imported folder. 
Even better, use two clean configurations folder, using the commands 
`darktable --configdir "C:\temp\Config1"`
and
`darktable --configdir "C:\temp\Config2"`
(or whatever path you like)
Start alternatively the two configurations, set the .xmp options in preferences and see if you still have the issue.
Thank you

**Comment by Jognu** [comment] 2020-07-06 22:31
I tried what you propose (with the version 3.0.2, Windows 10, French OS) :
- two differents configdir with a test folder containing one RAW file
- I only change the configuration to enable the "look for updated xmp files on startup"
I still have the issue, no dialog appear when I modified the file on Config1, close darktable and open with Config2 (I see the "previous version", no dialog).

**Comment by esq4** [comment] 2020-07-09 04:14
The path to directory with photos contains characters other than the "en" locale?

**Comment by Mark-64** [comment] 2020-07-09 09:03
Tried with DT 3.0.2 and I do see the dialog when I change some setting.
It could be something filename-related, then. 
@Jognu Can you please post the filepath where the files are and one filename too ?

One thing is different between 3.0.2 and current git master, though.
In 3.0.2 the dialog only show the modified files, while in master it shows all files, same behaviour in Windows and Linux. It seems now all .xmp are "touched", maybe the timestamp is updated or so.
I m not sure this is something desireable.

**Comment by Jognu** [comment] 2020-07-09 21:56
That's it !
The folder was "F:\Photos à traiter".
I tried with "F:\test" and it works, it's indeed due to the "à" on the filepath.

**Comment by esq4** [comment] 2020-07-10 04:50
Try to patch the "src/control/crawler.c" **like** in "[crawler: Hopefully better fix for](https://github.com/darktable-org/darktable/commit/dd18f18b3138f0e6530cc0c8f2ca6ca874a9c755#diff-675c7aff34ee6adb83fef1d83bbd0b03) #4133" (**attention!!!** in the commit itself is also a mistake, _correct as here_.)
 
```
      xmp_path[len++] = 'x';
      xmp_path[len++] = 'm';
      xmp_path[len++] = 'p';
      xmp_path[len] = '\0';

      struct stat statbuf;
--      if(stat(xmp_path, &statbuf) == -1) continue; // TODO: shall we report these?
++      // on Windows the encoding might not be UTF8
++      gchar *xmp_path_locale = g_locale_from_utf8(xmp_path, -1, NULL, NULL, NULL);
++      const int stat_res = stat(xmp_path_locale, &statbuf);
++      g_free(xmp_path_locale);
++      if(stat_res == -1) continue; // TODO: shall we report these?

      // step 1: check if the xmp is newer than our db entry
      // FIXME: allow for a few seconds difference?
      if(timestamp < statbuf.st_mtime)
```

**Comment by johnny-bit** [comment] 2021-06-20 07:32
Tested on win 10 update 21H1, darktable 3.4.1.1

path to file contained "weird" characters: `D:\Obrazy\do_test_lr_dt_photos\z żółć na wóz\SA700584.ARW` (playraw file). Updated xmp outside of darktable and restarted darktable with "scan for updated xmp on startup" enabled. The "updated xmp sidecar files found" dialog correectly listed updated file along with updated timestamp.

Closing :)

**Closed by johnny-bit** 2021-06-20 07:32 UTC
Labels: no-issue-activity
