### ISSUE TITLE
UI Win 10: blinking text cursor non visible in empty text box

### ISSUE THREAD

**Issue by markusb** [darktable-org/darktable#7615] opened 2021-01-01 22:19 UTC
When clicking on any empty text box, the blinking cursor is not visible.

This is the same bug as described in #3940 (closed), but unresolved in darktable 3.4.

**To Reproduce**
1. Open darktable 3.4
2. Click on any empty text field
3. See that there is no visible cursor, so you don't get any visual feedback which field is active
4. Type a character
5. See that the character appears in the selected field together with a blinking cursor

**Expected behavior**
1. Open darktable 3.4
2. Click on any empty text field
3. See that there is a visible cursor, so you get visual feedback which field is active

**Screenshots**
The same screen shots from #2940 apply

**Platform (please complete the following information):**
 - Darktable Version: 3.4
 - OS: Windows 10
 - OpenCL not activated, graphics card does not support OpenCL
 

**Additional context**
This is using darktable downloaded from here: https://github.com/darktable-org/darktable/releases/download/release-3.4.0/darktable-3.4.0-win64.exe

**Comment by Nilvus** [comment] 2021-01-01 22:30
It's not fixed because it's not directly a darktable issue. But how fonts set with CSS are set on Windows. It's all explained in #3940 you pointed out. Related to how fonts are considered in Windows, based on Pango library. So please close this issue as we can't do anything here.

I suggest you to just add last CSS code on CSS editor in preferences as a workaround. This CSS code can't be used in darktable.css file directly in darktable as it would breaks other things, especially on other OS.

**Comment by johnny-bit** [comment] 2021-01-01 23:06
The bug is outside of darktable's scope. Good news is that the problem was fixed (seemingly) on pango side of things, so we hope that there'll be new release of pango WITH the fix and that darktable can be built with newest pango.

this is the fix fixing the issue: https://gitlab.gnome.org/GNOME/pango/-/merge_requests/217

in the mean time, please use workaround mentioned in #3940

**Closed by johnny-bit** 2021-01-01 23:06 UTC
Labels: bug: upstream, bug: won't fix

**Comment by Mark-64** [comment] 2021-01-02 08:56
I am the author of #3940 and for me the issue has indeed been fixed upstream, I have just tested with gtk3-widget-factory.
With DT 3.4 on Windows 10 I have no issue with the theme darktable-elegant-darker (Roboto font installed). However I heve the issue with the theme darktable
@markusb Can you test by selecting the theme darktable-elegant-darker and/or using the workaround in the last post of #3940 ?

**Comment by markusb** [comment] 2021-01-02 18:48
I tried. Indeed with the theme darktable-elegant-darker it does work.

So in this case this is a problem with the 'darktable' theme now.

**Comment by Nilvus** [comment] 2021-01-02 19:26
> @Mark-64 I tried. Indeed with the theme darktable-elegant-darker it does work. The Roboto font is not installed.
> 
> So in this case this is a problem with the 'darktable' theme now.

It can't be a problem about darktable theme. It's a font issue (so not darktable one). On elegant themes, we set different fonts, so one could be used or the other. In darktable theme, the only difference on that issue, is that he use OS font. So if you still had that issue, change Windows default OS font. Just don't forget too that darktable use Gtk as graphic library, and Gtk is a Linux graphic library on start, and fonts set in Gtk are set by Pango library. So, definitely not CSS and/or darktable issue here.

**Comment by Mark-64** [comment] 2021-01-02 19:51
@markusb Unfortunately we DT Windows users have to fight not only with DT issues, but also with Gtk ones. BTW I have just found another Gtk bug which affects the darktable-elegant themes (typeface bold is not honored).
So the best compromise so far seems to use the darktable theme with the workaround of putting the following lines
```
entry
{
  font-family: sans;
}
```
in preferences / general / css tweaks

**Comment by markusb** [comment] 2021-01-02 21:35
I tried this, if I put

    {
      font-family: sans;
    }

in preferences / general / css tweaks the cursor works. Is this documented in the release notes ?

As a side remark, the bug is still there in darktable, so I think the bug should not be closed as there is no fix available yet. It should be closed after the upstream stuff has been fixed and a version of datrktable with the fixes is released.

**Comment by Nilvus** [comment] 2021-01-02 21:59
What do you not understand on our answers? The css code is a workaround ti a Gtk/Pango issue, not a darktable one. And that workaround can't be added in darktable code as it would cause other issue in other OS.

So, it can't be on release notes. As we already answer: IT'S NOT A DARKTABLE BUG.

**Comment by parafin** [comment] 2021-01-03 09:55
Well, it can be considered a bug in darktable Windows binary package, which is hosted in this project, so this bug tracker is probably the right place to report issues in it. But I don't think it's useful to keep this bug open - the issue is already understood and decided to wait for upstream to fix it (plus workarounds suggested). Keeping an open issue for every upstream problem (and there are more than one) will just pollute the darktable bug list with unactionable reports. People just have to search for closed bugs too when searching if the issue was already reported and fixed.
As for release notes - maybe it's worth adding a "known issues" section to them, but we don't have it right now.

**Comment by Nilvus** [comment] 2021-01-03 10:06
It's more a Gtk/Pango bug than darktable one and the CSS code is a workaround. A workaround that works but we don't want it on other OS. So, if as you suggested, it could be added only in Windows binary package, that's a good idea indeed.

**Comment by Mark-64** [comment] 2021-01-03 20:00
But the Pango issue has been fixed upstream, as I said I tested with gtk3-widget-factory and the cursor works now, unlike when I opened the issue in Gnome.
The fact that still doesn't work in DT, and now only for one of the themes is quite strange ad I suspect there are other issues with Pango Win32 backend.

**Comment by Nilvus** [comment] 2021-01-03 20:14
Good news guys: even if it's a workaround, the entry with font-family sans could be added safely in darktable.css. I have checked on my side and that doesn't break anything if it's only applied in darktable.css file. For elegant themes, we still have Roboto font that override this setting in darktable.css. That's #7659 issue that make me check more that. So, text in Windows should be better on 3.4.1. I will soon propose a PR with some CSS improvements (including fix for that issue).

**Comment by markusb** [comment] 2021-01-04 11:02
@Nilvus 
> What do you not understand on our answers? The css code is a workaround to a Gtk/Pango issue, not a darktable one. And that workaround can't be added in darktable code as it would cause other issue in other OS.
> 
> So, it can't be on release notes. As we already answer: IT'S NOT A DARKTABLE BUG.

I disagree with you here. Darktable, as shipped on Windows, contains the Gtk/Pango problem. The problem is in the code shipped by darktable, even if the underlying cause is with Gtk/Pango. For me as a user this makes no difference. The code I get has a bug. It is a bug in the darktable executable on Windows, so claiming it not to be a darktable bug is chickening out and not taking responsibility. Closing the bug, because it comes from a buggy library you use is just closing your eyes and throwing the problem over the fence.

For me the correct course of action is to keep the bug open, refer to the bug report in Gtk/Pango, and say that you'll add the fix as it becomes available and that this is out of your control. The interested user can then go and pester Gtk/Pango about the problem getting solved.

In the meantime, I understand that shipping a separate css with the workaround for windows seems not possible. So adding a remark to the release notes, informing the user about adding the css snippet to the css tweaks would be a good start. Even better would be adding the (commented out) css snippet to the default css tweaks, so that windows users can just uncomment it. This is something which works cross-platform, but needs some manual intervention by the user. Maybe a good compromise.

**Comment by Nilvus** [comment] 2021-01-04 11:15
> @Nilvus
> 
> > What do you not understand on our answers? The css code is a workaround to a Gtk/Pango issue, not a darktable one. And that workaround can't be added in darktable code as it would cause other issue in other OS.
> > So, it can't be on release notes. As we already answer: IT'S NOT A DARKTABLE BUG.
> 
> I disagree with you here. Darktable, as shipped on Windows, contains the Gtk/Pango problem. The problem is in the code shipped by darktable, even if the underlying cause is with Gtk/Pango. For me as a user this makes no difference. The code I get has a bug. It is a bug in the darktable executable on Windows, so claiming it not to be a darktable bug is chickening out and not taking responsibility. Closing the bug, because it comes from a buggy library you use is just closing your eyes and throwing the problem over the fence.

We want to help but if you don't read our answers and see what you want, It will be hard. You said yourself that is a Gtk/Pango problem here. I'm saying that it's not a darktable issue. I don't know how the Windows binary package is made and it's not relevant to darktable code but how the Windows package binary is made. And I'm not on Windows and not the maintainer of that package. And @parafin confirm that something could be done in Windows package binary, not in darktable code directly. That's just what I say. The issue remains on Gtk/Pango side more than on darktable one. And for developers, that makes a difference, because the real issue would be fixed correctly on Gtk/Pango side. A workaround as we propose (which will finally be added) is not a fix, even if for a user that doesn't make difference. Because, if one day the issue is fixed on Gtk/pango side, the workaround will need to be removed (and it could easily be forgotten).

Anyway, after that, I finally said (read again my last comment before your last one), that the CSS code could be implemented to fix that as it will finally not change themes on other OS... Please help us by understanding and take our comments. My last comment just begin by "Good news guys"... What do you want more?

**Comment by markusb** [comment] 2021-01-04 11:17
Just created a pull request for the change in preferences.c adding the Windows workaround commented in the default css tweaks.

**Comment by markusb** [comment] 2021-01-04 11:24
@Nilvus,

I'd like for darktable to become perfect. The road to perfection is a long and tiring and eternal. So in the meantime I attempt to work on the things which cross my path and which put off normal users. As guy pestering you here on Github I'm not a vanilla user anyway.

By the way, do you have a reference for the bug in Gtk/Pango ?

**Comment by parafin** [comment] 2021-01-04 11:24
Reading @Mark-64 comments raises a question - if upstream bug has been already fixed, then in which version and what version is currently used for building Windows package? Because it might indicate that another upstream bug exists.

**Comment by parafin** [comment] 2021-01-04 11:27
@markusb, you created PR to master branch of your fork instead of main repository.

**Comment by Nilvus** [comment] 2021-01-04 12:21
> Just created a pull request for the change in preferences.c adding the Windows workaround commented in the default css tweaks.

No need for that. As I said, I will propose a fix on CSS. It's done on my side, I have just some other tweaks in CSS to finish and will propose it. Please, just wait.

**Comment by Nilvus** [comment] 2021-01-04 12:23
And just see your PR, it's not a good way to add that here. It will also be shown on other OS. We don't want this. I will ping you when my PR will be posted. Probably in few hours.

**Comment by markusb** [comment] 2021-01-04 15:51
> @markusb, you created PR to master branch of your fork instead of main repository.

@parafin, sorry, shows my inexperience with this stuff. However @Nilvus seems to have a better idea/method anyway.
