### ISSUE TITLE
Canon 90D

### ISSUE THREAD

**Issue by telliers66** [darktable-org/darktable#4259] opened 2020-02-09 14:34 UTC
[Test-Erasme_MG_4510.zip](https://github.com/darktable-org/darktable/files/4177012/Test-Erasme_MG_4510.zip)

CR3 aren't supported on linux, can you help the world?

Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by johnny-bit** [comment] 2020-12-18 16:20
Duplicate of #3980

**Closed by johnny-bit** 2020-12-18 16:20 UTC
Labels: duplicate, scope: camera support
