### ISSUE TITLE
Selection is not working correctly in filmstrip

### ISSUE THREAD

**Issue by robyquin** [darktable-org/darktable#14462] opened 2023-05-09 18:59 UTC
### Describe the bug

**Selection is not working correctly in filmstrip (darkroom).**

In stripfilm I select multiple images (shift + left button), then I leave and select only one, the previous images remain selected.

The same thing happens if I come from multiple images selected in Lighttable and move to Darkroom.

### Steps to reproduce

1. in Lighttable I select multiple images (white flowers and butterfly)
2. I switch to Drakroom and in stripfilm I see these selected images
3. Now, in filmstrip, I select another image (red flower)
4. images with white flowers remain selected

![01](https://github.com/darktable-org/darktable/assets/50750713/1f6cc555-08e9-466c-be04-23a509661948)

### Expected behavior

What I would expect from the selection in the filmstrip is to have a behavior similar to what you find on the lighttable.

### Where did you install darktable from?

github.com/darktable-org

### darktable version

4.3.0+2188~gf2f04d4834

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Are you using OpenCL GPU in darktable?

None

**Comment by robyquin** [comment] 2023-05-09 19:14
The problem is solved if we comment the code related to **DT_THUMBNAIL_SEL_MODE_MOD_ONLY**

https://github.com/darktable-org/darktable/blob/a15f636ae12722edadd06dc56f320ae9cef36789/src/dtgtk/thumbnail.c#L953-L954

https://github.com/darktable-org/darktable/blob/a15f636ae12722edadd06dc56f320ae9cef36789/src/dtgtk/thumbtable.c#L558-L562

https://github.com/darktable-org/darktable/blob/a15f636ae12722edadd06dc56f320ae9cef36789/src/dtgtk/thumbtable.c#L615-L619

https://github.com/darktable-org/darktable/blob/a15f636ae12722edadd06dc56f320ae9cef36789/src/dtgtk/thumbtable.c#L2241-L2245

https://github.com/darktable-org/darktable/blob/a15f636ae12722edadd06dc56f320ae9cef36789/src/dtgtk/thumbtable.c#L2373-L2377

**Comment by AlicVB** [comment] 2023-05-09 20:20
If I understand correctly, what you see is here by design : 
- We try very hard to avoid unwanted drop of the selection while working with filmstrip (darkroom or culling)
- In filmstrip, single click change the active image, so we can't use that for changing selection too.

That's why you need to use modifier keys to change selection in filmstrip (ctrl or shift)

**Comment by robyquin** [comment] 2023-05-10 07:09
> If I understand correctly, what you see is here by design :
> 
>     * We try very hard to avoid unwanted drop of the selection while working with filmstrip (darkroom or culling)
> 
>     * In filmstrip, single click change the active image, so we can't use that for changing selection too.
> 
> 
> That's why you need to use modifier keys to change selection in filmstrip (ctrl or shift)

OK! Now it’s clearer!

But while I agree with this choice, on the other hand I consider it dangerous to keep the selection coming from another environment (like Lighttable)

In filmstrip we do not have the complete view of the selection, so in lighttable I get help from the filters of the collection, going to darkroom, I would like to have no selection and then select images of interest

**Comment by robyquin** [comment] 2023-05-10 10:20
I would like to be clearer, I think there are areas of ambiguity (**???**).
User side the theme of the selection looks like this:

![selection_memo dot](https://github.com/darktable-org/darktable/assets/50750713/c2c09da4-d283-4473-84f7-4f2e2412de65)

**Comment by Nilvus** [comment] 2023-05-11 18:27
There's no ambiguity @robyquin. Just a design choice (I do not agree with this choice). Unfortunately, this do not really move and had been discussed a lot. Maybe one time darktable will have a way to select like all other software on that part. See related issue here: #6025

As 4.4 will be feature freeze in just few days, this will not change for next release. But could be a good Christmas if this change on 4.6.

Your issue is so a duplicate of #6025. So I suggest you to close this one and continue discussion on #6025.

**Closed** 2023-05-11 19:13 UTC
Labels: duplicate, bug: invalid, feature: redesign, scope: UI
