### ISSUE TITLE
Sony ILCE-6700

### ISSUE THREAD

**Issue by DirkRotgans** [darktable-org/darktable#15125] opened 2023-08-28 09:02 UTC
I own a newly bought Sony ILCE-6700 (A-6700).
I updated Darktable to version 4.2.2, I used this program alread for 2.5 years with my Sony NEX-5R, ILCE-5100 and ILCE-7 and with my Panasonic Lumix FZ200.
In the latest version I cannot edit the ILCE-6700 .raw files (both compressed and uncompressed). They load and preview in the Lighttable, but do not open in the Darkroom. (gives a warning that it can not read the White Balance data).
I now use work around via Adobe .DNG converter, these are being loaded in the Darkroom but I cant denoise (profiled) although it finds the ILCE-6700 and the Sony lenses in the lenscorrection menu when Lensfun database is selected

**Comment by kmilos** [comment] 2023-08-28 09:08
Duplicate of https://github.com/darktable-org/rawspeed/issues/507 and https://github.com/darktable-org/darktable/issues/15014

Please search before opening new issues.

**Closed** 2023-08-28 09:12 UTC
Labels: duplicate, scope: camera support

**Comment by DirkRotgans** [comment] 2023-08-28 09:15
Hello all,

the ILCE-6700 has the same sensor and processor setup as the Cinema line camera FX30. This is supported in Darktable 4.2.2.
Is it possible to use this camera type temporary??
