### ISSUE TITLE
Crash on implementing details threshold

### ISSUE THREAD

**Issue by xenonsailor** [darktable-org/darktable#9804] opened 2021-08-13 21:03 UTC
**Describe the bug/issue**
In darkroom, Windows 10 64bit, dt 3.6.0.1, editing image in darkroom. current open module Local Contrast. I opened parametric mask and applied details threshold. after a couple of seconds I get an unhandled exception attached

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Go to local contrast
2. Open parametric mask
3. Click on details threshold
4. Move slider to left or right
5. darktable crashes and closes

**Expected behavior**
module works

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.6.0.1
* OS                : Win10 64
* Memory            : 
* Graphics card     : nVidia
* Graphics driver   : nVidia
[darktable_bt_ZOSD80.txt](https://github.com/darktable-org/darktable/files/6985095/darktable_bt_ZOSD80.txt)

* OpenCL installed  : yes
* OpenCL activated  : yes

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **not able to try**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes
[IMG_4212.dng.xmp.txt](https://github.com/darktable-org/darktable/files/6985141/IMG_4212.dng.xmp.txt)
**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by johnny-bit** [comment] 2021-08-14 13:55
The crash in your backtrace has no connection to details threshold but rather `dt_import_session_path`... and usually crash on such thing would crash pretty much immediately instead of couple seconds.

I cannot reproduce your issue on Win10 with dt 3.6.0.1 nor with recent windows insider versions.

Wold you be able to create eg screen recording of error if the error happens reliably?

**Comment by xenonsailor** [comment] 2021-08-15 06:35
Hi Hubert,
Thank you for looking into this for me.
I played around with a couple of images and the behaviour is not
consistent. It repeated on the same image, but then worked fine. However dt
crashed on opening another image, but is OK at the moment. So I don't know.
I suspect the files were corrupt somehow. If it happens again I will try
and record it and raise it again but at the moment it's behaving itself.
Best regards,
Andrew

**Comment by johnny-bit** [comment] 2021-08-15 06:54
This seems like path issue rather than file corruption. Couple fixes for windows path handling are comming in 3.6.1 (to be released soon). In the mean time - I'd recommend closing this issue and open new one once you manage to find reproducible behaviour leading to crash.

**Comment by xenonsailor** [comment] 2021-08-15 07:41
Will re-open if still reproducible after 3.6.1

**Closed** 2021-08-15 07:40 UTC
