### ISSUE TITLE
global saturation - color balance rgb

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#10835] opened 2022-01-08 19:48 UTC
When increasing the global saturation using **color balance rgb** some colors are darkened / getting black.

Is this by design?

* darktable version : 3.9.0
* OS                : Win10 

![Bild1](https://user-images.githubusercontent.com/57685590/148657651-d40953f0-fbd7-43eb-a01d-35f3672168b7.jpg)

**Comment by johnny-bit** [comment] 2022-01-08 20:38
I see quite a bit of noise there, which might get amplified and create visual problems.

See:
* https://docs.darktable.org/usermanual/3.8/en/special-topics/color-management/color-dimensions/ 
* https://eng.aurelienpierre.com/2021/04/the-srgb-book-of-color/
* https://cie.co.at/eilvterm/17-22-073

As you can see pushing saturation causes certain colours to go along certain axis that the more saturated the more dark those are.

**Comment by flannelhead** [comment] 2022-01-12 17:54
Would you mind sharing the RAW with a suitable license? I've seen some artefacts like that previously and would be interested to have a look.

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-01-12 20:55
Should be this one:

https://www.dpreview.com/reviews/image-comparison/download-image?s3Key=6641b9cbeec04777b85655fad61e4b4d.raf

**Comment by flannelhead** [comment] 2022-01-13 13:13
Couldn't reproduce the issue locally on darktable 3.8.0. You indicated using 3.9.0 - which specific git revision is in question? Are you using OpenCL? Would you mind sharing the XMP (sidecar) that produces these black pixels?

There was a quite similar issue that was fixed for 3.8.0, see https://github.com/darktable-org/darktable/issues/10416.

**Comment by ptilopteri** [comment] 2022-01-13 14:36
you opened it, and *you* CAN close it, please

**Closed** 2022-01-13 14:53 UTC
Labels: scope: image processing

**Comment by flannelhead** [comment] 2022-01-13 15:08
As far as I can tell, 3.9.0 is not a specific darktable version (although there is a `release-3.9.0` tag just before `release-3.8.0` which indicates the start of development of the next generally available version). A self-built development build usually gets named `3.9.0-gsomething` where the "something" is the git revision (this is shown in the upper left corner of the darktable window where the logo is). Builds from revisions succeeding the `release-3.9.0` tag get the `3.9.0` suffix there. Therefore I would still like to know which precise git commit are you referring to - I wonder if there's a regression because some 3.9.0 build is showing the artefact for you but 3.8.0 is not. It might also be caused by some different compile flags or something else specific to your environment but also that would be good to know.

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-01-13 15:16
The exact version was:

darktable-3.9.0+64~g765860b01-dirty-win64

And that was my very first use of MSYS.

**Comment by flannelhead** [comment] 2022-01-14 08:11
I can't reproduce on 765860b01 but what bothers me is that it is more recent than 3.8.0 where the black pixels caused by saturation adjustment should have been already fixed. Thus this is probably a new issue and may be related to your environment.

Could you please tell more details about your environment? It seems to be Win10, but it is interesting whether you have OpenCL activated or not, what is your GPU (if any) and the graphics driver. Please see also the information asked in the bug report template (you can see it when opening a new bug report).

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2022-01-14 13:02
* darktable version : 3.9.0+64~g765860b01-dirty-win64
* OS                : Win 10 64bit
* Linux - Distro    : -
* Memory            : 16 GB
* Graphics card     :  internal Intel + nvidia
* Graphics driver   : 
* OpenCL installed  : yes
* OpenCL activated  : NO
* Processor : Intel(R) Core(TM) i7-3720QM CPU   2.60 GHz

I forgot to mention that I´ve set **GMIC=OFF** in the build options.
