### ISSUE TITLE
RawSpeed:Unable to find camera in database: 'Canon' 'Canon EOS 2000D' ''

### ISSUE THREAD

**Issue by slickw9** [darktable-org/darktable#5552] opened 2020-06-19 02:19 UTC
**Describe the bug**
I am learning to use Darktable with a new camera to me.  I am on Ubuntu 18.04.4 and on my first and every attempt to open an imported file in darkroom I get an error stating it was unable to load camera white balance information from 'Canon - EOS 2000D - RAW ( 
Then it goes off the edge and where the image should show to make edits is like a frozen image of the lighttable with all the thumbnails.

**To Reproduce**

**Expected behavior**
I expected to see a preview i can edit

**Screenshots**
NONE

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: Ubuntu 18.04.4

**Additional context**
I did as it requested and uploaded a CR2 file to raw.pixls.us.

I used command line to open the program and see the error info better, I'll copy and paste it below:

dad@LenovoLaptop:~$ darktable
RawSpeed:Unable to find camera in database: 'Canon' 'Canon EOS 2000D' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (IMG_0162.CR2) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 166: Camera 'Canon' 'Canon EOS 2000D', mode '' not supported, and not allowed to guess. Sorry.
[temperature] failed to read camera white balance information from `IMG_0162.CR2'!
[temperature] `Canon Canon EOS 2000D' color matrix not found for image
[temperature] failed to read camera white balance information from `IMG_0162.CR2'!
RawSpeed:Unable to find camera in database: 'Canon' 'Canon EOS 2000D' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!

**Comment by johnny-bit** [comment] 2020-06-19 07:56
This is a duplicate of #3994

You haven't specified which version of darktable you have problems with, there is no problem opening 2000D images on either 3.0.2 or current master.

**Comment by LebedevRI** [comment] 2020-06-19 11:56
Duplicate of #3994.

**Closed by LebedevRI** 2020-06-19 11:56 UTC

**Comment by slickw9** [comment] 2020-06-19 18:02
I just installed from the repository so should be the new one.  I'll check
when home.  Same thing on new install on wondering but doesn't freeze

**Comment by slickw9** [comment] 2020-06-19 18:03
Not a duplicate because the other reports show fixed but mine isn't.

**Comment by LebedevRI** [comment] 2020-06-19 18:04
"the new one" in the repository, yet it is 2+ years old by now.

**Comment by slickw9** [comment] 2020-06-19 21:14
Did I say "the new one?". I dont really know how new it is.

My Windows version of Darktable is 3.0.2
The Ubuntu version of Darktable is 2.4.2

**Comment by slickw9** [comment] 2020-06-19 21:27
OK, i just saw I said it should be the new one, sorry.  I assumed at the time.
