### ISSUE TITLE
lighttable thumbnails : (-\+) overlay icon does not always activates upon modification

### ISSUE THREAD

**Issue by AlexBelz** [darktable-org/darktable#2922] opened 2019-09-08 08:13 UTC
Hello,
I observed a bug confirmed in the IRC.

1) import a collection made of JPG files
2) open a picture in darkroom
3) apply Curve modifiction (in my case, adding light in the shadows)
4) go back to lighttable
5) Observed result : the icon at the topright  (-\+) is not shown, while I would expect it to be.
6) go back to darkroom
7) apply white balance correction
8 ) go back to light table -> Observed result : the icon is now visible !
As if the "curve" was not enough to trigger the icon, and adding "white balance" was necessary... strange !

I'm running darktabke v2.6.2 , freshly re-installed, on Windows 10.
my pictures = JPG 24 Mpixels , taken by Nikon D5600

IRC folks suggests that the issue could come with large pictures ; but 80% pictures fails ; 20% do not.
Example with 2 pictures edited in darkroom : 
![image](https://user-images.githubusercontent.com/55029991/64485422-0f107000-d221-11e9-96ec-424836cf088c.png)

**Comment by TurboGit** [comment] 2019-09-10 07:57
I cannot reproduce with current master. So probably already fixed and will be part of next release.

**Closed by TurboGit** 2019-09-10 07:57 UTC
