### ISSUE TITLE
Were the default settings for the input colour profile changed recently? 

### ISSUE THREAD

**Issue by GNY-001F2** [darktable-org/darktable#7036] opened 2020-11-23 16:36 UTC
I haven't used darktable in a while, specifically I haven't used version 3.2. I changed my settings to the new scene-referred workflow and found that by default my settings were really weird, with the colours being extremely dark out of the box and the blacks in dark zones being completely crushed even after raising the exposure.

So I checked the settings between some of my older edited photos (including those with filmic v3) and newer rolls which I had not yet uploaded to the program and I found that the input colour profile settings had changed.

Previously it was:

Input Profile: standard colour matrix
Working Profile: linear 2020 RGB
gamut clipping: off

The Input Profile has changed to Adobe RGB.

Now I don't quite understand the reason behind this change, because I was never certain which colour profile is used with the "standard colour matrix". I simply edit my photos on my laptop screen (2560x1440 on a T460p), which is obviously neither calibrated for colour accuracy nor 10-bits capable. In fact, if I am not mistaken, Rec.2020 is a wider colour space than Adobe RGB, while the standard colour matrix for my camera (Sony a6000), if I understand the module correctly, should be 11 bits wide.

Was this an intentional change or did I botch something in my settings? I don't know if my changing the settings to scene-referred from display-referred caused the change.

**Comment by aurelienpierre** [comment] 2020-11-29 02:33
The default color space depends on the file you open. Is it a raw ? If it is, Adobe RGB makes no sense. If it is a TIFF or a JPEG saved in Adobe RGB, then it's normal.

**Comment by GNY-001F2** [comment] 2020-12-02 19:13
@aurelienpierre It was definitely a raw. I don't know why it happened, because it didn't happen to all the files - just some of them. Nuking the edit history (i.e. create new in duplicate manager) and then ensuring the input colour profile is "Standard Colour Matrix" should be good enough, right?

**Comment by davenicko** [comment] 2020-12-04 22:03
I had this problem when importing a folder with raw and jpeg images fir my fuji X-T1. When importing the color space is set correctly to sRGB for the jpeg but also for the raw files. If I move the raw files to a different directory (i.e. no jpegs in the dir) the correct color space is selected. I assume that this may be limited to cameras who store their raw files with an extension which comes after jpeg alphabetically (raf in my case). This didn't seem to happen with my Canon (raw files are CR2) but I only tested with a processed raw file - not with a coupled raw and jpeg file by selecting raw+jpeg in camera.

**Comment by parafin** [comment] 2020-12-05 08:59
> I had this problem when importing a folder with raw and jpeg images fir my fuji X-T1. When importing the color space is set correctly to sRGB for the jpeg but also for the raw files. If I move the raw files to a different directory (i.e. no jpegs in the dir) the correct color space is selected. I assume that this may be limited to cameras who store their raw files with an extension which comes after jpeg alphabetically (raf in my case). This didn't seem to happen with my Canon (raw files are CR2) but I only tested with a processed raw file - not with a coupled raw and jpeg file by selecting raw+jpeg in camera.

What you describing is most likely #6202

**Comment by davenicko** [comment] 2020-12-05 09:20
Yes indeed! And it looks like there may be an interim fix.

Thank you!

Dave

**Comment by GNY-001F2** [comment] 2020-12-05 16:11
@davenicko I think I imported RAW+JPEG before I checked the files I believe, but curiously enough since my camera is a Sony A6000, meaning the raws are labelled .arw, so the JPEGs being AFTER should not have caused anything.

Very strange.

**Comment by davenicko** [comment] 2020-12-05 16:55
Indeed - I wonder if this would happen with my Canon, but as it has a smashed rear screen it will be difficult for me to change it to raw+jpeg to test. 

Presumably if you copy the raw file alone to a new directory and import it from there it would apply the correct input color profile? If so then it is probably #6202 as mentioned by parafin and looks like it will be fixed for the 3.4 release.

**Comment by GNY-001F2** [comment] 2020-12-05 19:48
Yeah, new raws are being imported with the standard colour matrix: no problems there.

**Comment by ptilopteri** [comment] 2020-12-06 01:04
aiui, the file must not exist in the library/db or will be recognized.

if you want to import it new
remove the image from the collection
delete the xmp file

now import the image.  not necessary to put the image into a new directory

**Comment by johnny-bit** [comment] 2020-12-18 16:43
most likely duplicate of #6202

**Closed by johnny-bit** 2020-12-18 16:43 UTC
Labels: duplicate
