### ISSUE TITLE
Windows: Import silently fails for special charachters (e.g. umlauts)

### ISSUE THREAD

**Issue by Profoktor** [darktable-org/darktable#9629] opened 2021-07-25 16:22 UTC
**Describe the bug/issue**

When importing ("add to library") from a path containing an umlaut, the path and images are being resolved in the importer and darktable states that the images have been successfully imported. However, this is not the case and the collection/film roll as well as the images are missing

**To Reproduce**

in lighttable:
1. "import" -> "add to library.."
2. Select a path containing an umlaut
3. The importer can resolve the path and lists the images
4. select all and click "add to library"
5. The importer states that <number of images> have been added to the database
6. check collection / film roll - import failed

When inspecting the database:
1. There is an entry for the film roll, with an encoding error (e.g. C:\LadegerÃ¤t)
2. There are no entries for the images

**Expected behavior**

Option 1: Allow special characters / normalize encoding
Option 2: Give a meaningful error message. It took me half an hour to figure out the import was just failing

**Platform**

* darktable version : 3.6.0
* OS                : Win10 20H2 19042.1110

**Comment by MmAaXx500** [comment] 2021-07-25 16:52
Same with `á`, `é`, `í`, `ó`, `ö`, `ő`, `ú`, `ű`.
OS: Win10 21H1

I can get around it with removing these characters, import the images and with the built-in move, move to the correctly named folder.

**Comment by Nilvus** [comment] 2021-07-25 17:29
Duplicate of #9475 and #9596, fixed in master by #9498 (should be in a probable 3.6.1).

**Closed by Nilvus** 2021-07-25 17:29 UTC
