### ISSUE TITLE
CTD when renaming shape in Win10

### ISSUE THREAD

**Issue by MyOwnSling** [darktable-org/darktable#9886] opened 2021-08-28 03:47 UTC
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
When I attempt to rename a shape, I get an immediate crash message followed by a CTD. This behavior seems to happen at any point during usage (i.e., right after opening the app and after I've been editing for an hour or so).

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Double-click an image in lighttable
2. Create a new shape (reproducible with all shapes I've tried) and add it to the image
3. Click the shape to highlight it and click it again to start editing the name
4. Enter a new name and press the Enter button
5. Experience the CTD

**Expected behavior**
Shape renames successfully without a crash

**Which commit introduced the error**
Will add if/when I can produce

**Platform**
* darktable version : 3.6.0
* OS                : Win10 - Version 21H1 - OS build 19043.1165 - Experience pack 120.2212.3530.0
* Memory            : 16GB
* Graphics card     : nvidia RTX2070
* Graphics driver   : nvidia 27.21.14.6089

**Additional context**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format, others not attempted**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Do you use lua scripts? **no**
 - this is darktable 3.6.0 reporting an exception:

-------------------

Error occurred on Friday, August 27, 2021 at 21:19:31.

darktable.exe caused an Access Violation at location 00007FFB90D86EB4 in module libgobject-2.0-0.dll Reading from location FFFFFFFFFFFFFFFF.

AddrPC           Params
00007FFB90D86EB4 0000000000000005 0000000000000002 0000000000000001  libgobject-2.0-0.dll!g_type_check_instance_cast
00007FFB4C2C5AD7 C094100000000000 C07FB00000000000 00000124B69A0000  libmasks.dll!0x7ffb00005ad7
00007FFB6711AA51 00000124B6B4E3A0 00007FFB779567D6 00000124B69F11E0  libgtk-3-0.dll!0x7ffb0000aa51
00007FFB90D670E3 00000023201FDDD0 00007FFB90D8A01B 00000023201FDDD0  libgobject-2.0-0.dll!g_closure_invoke
00007FFB90D7EE9B 00000124CFC360F0 00007FFB90D6B993 0000012400000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFB90D7EFE8 00000124CC49C700 00000023201FDFA0 00000023201FDF0C  libgobject-2.0-0.dll!g_signal_emit
00007FFB67176A5B 0000000000970070 00000000000000C4 00000124D0257D00  libgtk-3-0.dll!gtk_cell_renderer_spinner_new
00007FFB90D66ECE 00000124B69A02AC 00000023201FE099 0000000000000030  libgobject-2.0-0.dll!g_closure_invoke
00007FFB90D78EF9 00000124B6A54C40 0000000000000000 00000124F8F86200  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFB90D7EB84 00000124F8F86200 0000000000000001 0000012400000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFB90D7F159 0000000000000002 00000124B67C0000 00000124CC7E6078  libgobject-2.0-0.dll!g_signal_emit_by_name
00007FFB671D5DAE 0000000000000000 00007FFB9C956FFF 00000124BF6B4590  libgtk-3-0.dll!gtk_editable_get_editable
00007FFB90D66ECE 0000000000000000 0000000000000020 0000000000000018  libgobject-2.0-0.dll!g_closure_invoke
00007FFB90D78EF9 00000124CC8069D0 0000012400000000 00000124F8F86200  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFB90D7DFE4 00000023201FE680 00007FFB676BF7C3 00000000000000A0  libgobject-2.0-0.dll!g_signal_emitv
00007FFB671459D8 00000023201FE794 00007FFB67323B22 00000023201FE79C  libgtk-3-0.dll!gtk_identifier_get_type
00007FFB67145E98 00000124B6ADE180 0000FF0D90D6F857 00007FFB676BF7C3  libgtk-3-0.dll!gtk_identifier_get_type
00007FFB6714601B 00000124F8F86200 00000124F8EF12C0 0000002300000000  libgtk-3-0.dll!gtk_identifier_get_type
00007FFB671472E9 00000023201FEB48 00000023201FEB48 00000124B89F7560  libgtk-3-0.dll!gtk_bindings_activate_event
00007FFB671DB1BE 0000000000000000 00007FFB90D87A00 00000023201FEC20  libgtk-3-0.dll!gtk_entry_reset_im_context
00007FFB67112D16 0000012400000000 00000124B69A2A00 0000000000000000  libgtk-3-0.dll!0x7ffb00002d16
00007FFB90D66DFB 00000124B89FCF30 00007FFB671DAAE0 00000124B89D7250  libgobject-2.0-0.dll!g_closure_invoke
00007FFB90D78933 00000124B89F7E90 0000000000000000 00000124F8F86200  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFB90D7E854 00000124F8F86200 00007FFB90D6B202 0000012400000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFB90D7EFE8 00000124F8F86200 00007FFB90D86936 0000012400000000  libgobject-2.0-0.dll!g_signal_emit
00007FFB673C3425 000000000000FFC7 00000124F90FA9D0 00000124B6893C70  libgtk-3-0.dll!gtk_requisition_copy
00007FFB673E52E3 00000023201FF040 00007FFB90D8A286 00007FFB76A091B0  libgtk-3-0.dll!gtk_window_propagate_key_event
00007FFB673E982B 0000000000000000 0000000000000000 0000000000000000  libgtk-3-0.dll!gtk_window_activate_key
00007FFB67112D16 00000124B68B0D88 0000000000000000 0000000300000000  libgtk-3-0.dll!0x7ffb00002d16
00007FFB90D66ECE 0000000000000000 0000000000000000 0000000000000000  libgobject-2.0-0.dll!g_closure_invoke
00007FFB90D78933 00000124B89F7E90 0000000000000000 00000124CC350370  libgobject-2.0-0.dll!g_signal_handler_disconnect
00007FFB90D7E854 00000124CC350370 0000000000000000 0000012400000000  libgobject-2.0-0.dll!g_signal_emit_valist
00007FFB90D7EFE8 00000124CC350370 00007FFB90D86936 0000000000000000  libgobject-2.0-0.dll!g_signal_emit
00007FFB673C3425 0000012400000000 00007FFB673EBC7A 0000012400000000  libgtk-3-0.dll!gtk_requisition_copy
00007FFB672713A1 FFFFFFFF00000000 00007FFB9E95E703 00007FFB9E95EB96  libgtk-3-0.dll!gtk_lock_button_set_permission
00007FFB67273308 0000000000000000 00007FFB68546680 0000000000000000  libgtk-3-0.dll!gtk_main_do_event
00007FFB6850F56A 00000023201FF3D0 00000124B89C6310 00007FFB9E95E040  libgdk-3-0.dll!gdk_event_free
00007FFB685466BF 00000124B6A59750 00007FFB778FB62D 0000000000000000  libgdk-3-0.dll!gdk_win32_drag_context_get_type
00007FFB778F88F4 0000000000000002 00000124CFCA6B50 00000124CFCA6B50  libglib-2.0-0.dll!g_clear_list
00007FFB778FBA46 0000000000000001 00000124B6A2FD10 00000124B6A46C10  libglib-2.0-0.dll!g_main_context_check
00007FFB778FBF6C 0000000000000000 0000000000000000 00007FFB76C670C0  libglib-2.0-0.dll!g_main_loop_run
00007FFB672721ED 0000000000000000 00007FF717B926E0 00000124B6A47480  libgtk-3-0.dll!gtk_main
00007FFB76A0B27C 00007FFB00000001 00000124B6A2FD10 00007FFB00000001  libdarktable.dll!dt_gui_gtk_run
00007FF717B92A6C 00007FF717B91660 0000000000000010 0000000000000000  darktable.exe!0x7ff700002a6c
00007FF717B915B5 000000000000005A 0000000000000000 00007FF717B97090  darktable.exe!0x7ff7000015b5
00007FF717B913D4 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff7000013d4
00007FF717B91506 0000000000000000 0000000000000000 0000000000000000  darktable.exe!0x7ff700001506
00007FFB9D2A7034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFB9EC22651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.6.0.0
ntdll.dll   	10.0.19041.1110
KERNEL32.DLL	10.0.19041.1151
KERNELBASE.dll	10.0.19041.1151
msvcrt.dll  	7.0.19041.546
libintl-8.dll	0.19.8.0
ADVAPI32.dll	10.0.19041.1052
libglib-2.0-0.dll	2.68.3.0
sechost.dll 	10.0.19041.906
ole32.dll   	10.0.19041.746
RPCRT4.dll  	10.0.19041.1081
ucrtbase.dll	10.0.19041.789
combase.dll 	10.0.19041.1081
libdarktable.dll
GDI32.dll   	10.0.19041.746
libiconv-2.dll	1.16.0.0
PSAPI.DLL   	10.0.19041.546
win32u.dll  	10.0.19041.1151
gdi32full.dll	10.0.19041.1110
msvcp_win.dll	10.0.19041.789
SHELL32.dll 	10.0.19041.1151
USER32.dll  	10.0.19041.1151
libcairo-2.dll
WS2_32.dll  	10.0.19041.546
exchndl.dll 	0.9.2.0
libgdk_pixbuf-2.0-0.dll	2.42.4.0
libgdk-3-0.dll	3.24.29.0
IMM32.dll   	10.0.19041.546
SETUPAPI.dll	10.0.19041.1151
libgio-2.0-0.dll	2.68.3.0
cfgmgr32.dll	10.0.19041.1151
libgobject-2.0-0.dll	2.68.3.0
SHLWAPI.dll 	10.0.19041.1023
bcrypt.dll  	10.0.19041.1023
libharfbuzz-0.dll
libpango-1.0-0.dll	1.48.5.0
libpangocairo-1.0-0.dll	1.48.5.0
zlib1.dll
libgtk-3-0.dll	3.24.29.0
libwinpthread-1.dll	1.0.0.0
libgcc_s_seh-1.dll
libstdc++-6.dll
comdlg32.dll	10.0.19041.906
libgomp-1.dll
shcore.dll  	10.0.19041.1023
libavif.dll
MSIMG32.dll 	10.0.19041.546
libfontconfig-1.dll
libpixman-1-0.dll
libfreetype-6.dll	2.10.4.0
libpng16-16.dll
libcurl-4.dll
CRYPT32.dll 	10.0.19041.844
WLDAP32.dll 	10.0.19041.546
libgmodule-2.0-0.dll	2.68.3.0
libexiv2.dll
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libpcre-1.dll
libicuin68.dll
libIlmImf-2_5.dll
libicuuc68.dll
libjpeg-8.dll
libjson-glib-1.0-0.dll
libopenjp2-7.dll
liblcms2-2.dll
libpugixml.dll	1.11.0.0
libsecret-1-0.dll
libsoup-2.4-1.dll
librsvg-2-2.dll
libsqlite3-0.dll
libtiff-5.dll
libxml2-2.dll
mgwhelp.dll 	0.9.2.0
dwmapi.dll  	10.0.19041.746
VERSION.dll 	10.0.19041.546
gdiplus.dll 	10.0.19041.1151
DNSAPI.dll  	10.0.19041.1151
IPHLPAPI.DLL	10.0.19041.546
libffi-7.dll
WINMM.dll   	10.0.19041.546
libcairo-gobject-2.dll
libepoxy-0.dll
libfribidi-0.dll
libpangowin32-1.0-0.dll	1.48.5.0
USP10.dll   	10.0.19041.546
libgraphite2.dll
libthai-0.dll
libpangoft2-1.0-0.dll	1.48.5.0
COMCTL32.dll	6.10.19041.1110
WINSPOOL.DRV	10.0.19041.1023
libatk-1.0-0.dll	2.36.0.0
libaom.dll
rav1e.dll
libdav1d.dll	5.1.0.0
libexpat-1.dll
libbrotlidec.dll
libbz2-1.dll
libidn2-0.dll
libcrypto-1_1-x64.dll	1.1.1.11
libnghttp2-14.dll
libpsl-5.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.11
libzstd.dll
libexif-12.dll
libltdl-7.dll
libsystre-0.dll
libHalf-2_5.dll
libIex-2_5.dll
libIlmThread-2_5.dll
libImath-2_5.dll
libicudt68.dll
libgcrypt-20.dll	1.9.2.0
USERENV.dll 	10.0.19041.572
libjbig-0.dll
libdeflate.dll
liblzma-5.dll	5.2.5.0
libwebp-7.dll
dbghelp.dll 	10.0.19041.867
libdatrie-1.dll
libbrotlicommon.dll
libunistring-2.dll	0.9.10.0
libtre-5.dll
libgpg-error-0.dll	1.42.0.0
CRYPTBASE.DLL	10.0.19041.546
dbgcore.DLL 	10.0.19041.789
CRYPTSP.dll 	10.0.19041.546
rsaenh.dll  	10.0.19041.1052
bcryptPrimitives.dll	10.0.19041.1023
NSI.dll     	10.0.19041.610
windows.storage.dll	10.0.19041.1151
Wldp.dll    	10.0.19041.662
kernel.appcore.dll	10.0.19041.546
uxtheme.dll 	10.0.19041.1081
OLEAUT32.dll	10.0.19041.985
clbcatq.dll 	2001.12.10941.16384
propsys.dll 	7.0.19041.1023
profapi.dll 	10.0.19041.844
mswsock.dll 	10.0.19041.546
MSCTF.dll   	10.0.19041.1081
DEVOBJ.dll  	10.0.19041.1151
WINTRUST.dll	10.0.19041.1151
MSASN1.dll  	10.0.19041.546
OpenCL.dll  	2.2.8.0
AppXDeploymentClient.dll	10.0.19041.1110
nvopencl64.dll	27.21.14.6089
cryptnet.dll	10.0.19041.906
nvapi64.dll 	27.21.14.6089
nvcompiler64.dll	27.21.14.6089
winhttp.dll 	10.0.19041.1151
IconCodecService.dll	10.0.19041.1
WindowsCodecs.dll	10.0.19041.1151
Windows.ApplicationModel.dll	10.0.19041.746
twinapi.appcore.dll	10.0.19041.964
mssprxy.dll 	7.0.19041.1151
libpixbufloader-png.dll
mscms.dll   	10.0.19041.746
ColorAdapterClient.dll	10.0.19041.546
icm32.dll   	10.0.19041.546
textinputframework.dll	10.0.19041.1151
CoreMessaging.dll	10.0.19041.746
CoreUIComponents.dll	10.0.19041.546
wintypes.dll	10.0.19041.1081
ntmarta.dll 	10.0.19041.546
libdarkroom.dll
libknight.dll
liblighttable.dll
libmap.dll
libosmgpsmap-1.0-1.dll
libslideshow.dll
libtethering.dll
libavif.dll
libcopy.dll
libexr.dll
libj2k.dll
libjpeg.dll
libpdf.dll
libpfm.dll
libpng.dll
libppm.dll
libtiff.dll
libwebp.dll
libxcf.dll
libdisk.dll
libemail.dll
libgallery.dll
liblatex.dll
libpiwigo.dll
libashift.dll
libatrous.dll
libbasecurve.dll
libbasicadj.dll
libbilat.dll
libbilateral.dll
libbloom.dll
libborders.dll
libcacorrect.dll
libcacorrectrgb.dll
libcensorize.dll
libchannelmixer.dll
libchannelmixerrgb.dll
libclahe.dll
libclipping.dll
libcolisa.dll
libcolorbalance.dll
libcolorbalancergb.dll
libcolorchecker.dll
libcolorcontrast.dll
libcolorcorrection.dll
libcolorin.dll
libcolorize.dll
libcolormapping.dll
libcolorout.dll
libcolorreconstruct.dll
libcolortransfer.dll
libcolorzones.dll
libcrop.dll
libdefringe.dll
libdemosaic.dll
libdenoiseprofile.dll
libdither.dll
libequalizer.dll
libexposure.dll
libfilmic.dll
libfilmicrgb.dll
libfinalscale.dll
libflip.dll
libgamma.dll
libglobaltonemap.dll
libgraduatednd.dll
libgrain.dll
libhazeremoval.dll
libhighlights.dll
libhighpass.dll
libhotpixels.dll
libinvert.dll
liblens.dll
liblensfun.dll
liblevels.dll
libliquify.dll
liblowlight.dll
liblowpass.dll
liblut3d.dll
libgmic.dll
libfftw3-3.dll
libGraphicsMagick++-12.dll
libopencv_core452.dll	4.5.2.0
libopencv_videoio452.dll	4.5.2.0
tbb.dll
libopenblas.dll
OPENGL32.dll	10.0.19041.1081
libopencv_imgcodecs452.dll	4.5.2.0
libopencv_imgproc452.dll	4.5.2.0
libgfortran-5.dll
GLU32.dll   	10.0.19041.1081
libquadmath-0.dll
libmask_manager.dll
libmonochrome.dll
libnegadoctor.dll
libnlmeans.dll
liboverexposed.dll
libprofile_gamma.dll
librawdenoise.dll
librawoverexposed.dll
librawprepare.dll
librelight.dll
libretouch.dll
librgbcurve.dll
librgblevels.dll
librotatepixels.dll
libscalepixels.dll
libshadhi.dll
libsharpen.dll
libsoften.dll
libsplittoning.dll
libspots.dll
libtemperature.dll
libtonecurve.dll
libtoneequal.dll
libtonemap.dll
libvelvia.dll
libvibrance.dll
libvignette.dll
libwatermark.dll
libzonesystem.dll
libbackgroundjobs.dll
libcamera.dll
libcollect.dll
libcolorlabels.dll
libcolorpicker.dll
libcopy_history.dll
libdarktable_label.dll
libduplicate.dll
libexport.dll
libfilmstrip.dll
libfilter.dll
libgeotagging.dll
libglobal_toolbox.dll
libhinter.dll
libhistogram.dll
libhistory.dll
libimage.dll
libimage_infos.dll
libimport.dll
libioporder.dll
liblighttable_mode.dll
liblive_view.dll
liblocation.dll
libmap_locations.dll
libmap_settings.dll
libmasks.dll
libmetadata.dll
libmetadata_view.dll
libmodulegroups.dll
libmodule_toolbox.dll
libnavigation.dll
libratings.dll
librecentcollect.dll
libselect.dll
libsession.dll
libsnapshots.dll
libstyles.dll
libtagging.dll
libtimeline.dll
libviewswitcher.dll
libview_toolbox.dll
libpixbufloader-svg.dll
TextShaping.dll

Windows 10.0.19043
DrMingw 0.9.2

**Comment by johnny-bit** [comment] 2021-08-28 10:06
Duplicate of #9504
Fixed in https://github.com/darktable-org/darktable/pull/9514
Will be part of 3.6.1 release.

**Closed by johnny-bit** 2021-08-28 10:06 UTC
Labels: duplicate, bug: fixed

**Comment by MyOwnSling** [comment] 2021-08-28 16:17
I didn't remove the "open issues only" filter when searching for duplicates. Sorry for the noise.
