### ISSUE TITLE
contrast equalizer → mix value reset after reopening

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#8197] opened 2021-02-12 16:41 UTC
1. Open any image.
2. Enable "contrast equalizer" module with any settings and change "mix" value. Close module.
3. Leave to lighttable mode.
4. Open same picture in darkroom mode and open "contrast equalizer" module.

Notice "mix" value was reset to 1.000 while curve remains correct. Same happens if I just press "compress history stack" button inside darkroom mode without closing and opening picture again.

P.S. Linux, Intel, 64 bit, dt 3.4.1.

**Comment by hgmarty** [comment] 2021-02-12 16:53
Yes,
but visualize the courb.
If before you have choose 0.5 for mix value, the courb has decreased by half in the next time you open the module and you have notice the value in 1.

**Comment by Mark-64** [comment] 2021-02-12 16:55
I think this is not a bug. Please note that changing "mix" is actually scaling up or down the curve.
When you reopen darkroom, it is the scaled curve that is applied and that is correct.
It is a different GUI representation of the same thing.

**Comment by Mark-64** [comment] 2021-02-12 16:56
@hgmarty oops... you anticipated me

**Comment by timur-davletshin** [comment] 2021-02-12 16:58
@Mark-64 so, explain me why this "mix" value is saved if I just close module and proceed this editing within one darkroom session?

**Comment by elstoc** [comment] 2021-02-12 17:19
Yep indeed this is not a bug - please see [the documentation](https://www.darktable.org/usermanual/en/module-reference/processing-modules/contrast-equalizer/)

**Comment by hgmarty** [comment] 2021-02-12 17:19
And ?
What does it change ?
During a session, it's registered in this form curve +  value and when you close darkroom, it's saved only with curve

**Comment by elstoc** [comment] 2021-02-12 17:20
It alters the curve. The altered curve is saved when you exit the module and hence no need for the mix parameter any longer because it's already done its job.

**Comment by TurboGit** [comment] 2021-02-12 19:22
We had discussed long time ago to make this mix saved into the module. Would be less confusing.

**Comment by timur-davletshin** [comment] 2021-02-12 19:25
So maybe it's worth to reopen it, if this behavior is so confusing?

**Comment by TurboGit** [comment] 2021-02-12 21:17
Let's keep this open for this.

**Comment by elstoc** [comment] 2021-02-12 21:22
It would make it more consistent with the "mix" parameter in color zones, which does seem to be retained between sessions.

**Comment by TurboGit** [comment] 2021-02-12 21:36
> It would make it more consistent with the "mix" parameter in color zones, which does seem to be retained between sessions. Presumably in this case we could then leave the curve visually unaltered, which might allow for more precise setting of the curve, on a large scale, to be subsequently reduced in effect by mix.

What does color zones? Retaining the curve would be 100% equivalent to use the uniform blending opacity.

**Comment by elstoc** [comment] 2021-02-12 21:44
I haven't looked at exactly how color zones uses the mix slider (and probably wouldn't understand it if I did) but it doesn't change the curve. If the mix slider (in contrast eq) is essentially doing the same thing as uniform blending (presumably this is the case now, in terms of the effect of the module), I suppose that begs the question of whether the mix slider is needed at all.

**Comment by TurboGit** [comment] 2021-02-12 22:32
In fact no 100% equivalent because the mix can have negative value and so invert the effect.

**Comment by TurboGit** [comment] 2021-02-14 14:58
See #8219 - a bit more work than I expected but it was nice to do a bit of coding :)

**Comment by TurboGit** [comment] 2021-02-26 09:49
This is done, closing.

**Closed by TurboGit** 2021-02-26 09:49 UTC
Labels: feature: enhancement
