### ISSUE TITLE
4.2.0 version does not support Simplified Chinese

### ISSUE THREAD

**Issue by duocoding** [darktable-org/darktable#13622] opened 2023-02-12 07:45 UTC
Why 4.2.0 does not support Simplified Chinese, but only TaiWan Chinese?

<img width="732" alt="image" src="https://user-images.githubusercontent.com/48700579/218299197-b6169114-566c-49e6-875f-c7da0c1f487d.png">

**Comment by MStraeten** [comment] 2023-02-12 07:58
because no one completed the translation for simplified chinese. 

if you want to have a proper translation this is the way to get it: https://github.com/darktable-org/darktable/wiki/Translating-darktable

**Comment by kmilos** [comment] 2023-02-12 08:17
Duplicate of https://github.com/darktable-org/darktable/issues/13620

Please search before opening new issues.

**Comment by duocoding** [comment] 2023-02-12 09:04
thx😀

**Closed** 2023-02-12 09:17 UTC
Labels: duplicate

**Comment by HSUfineprint** [comment] 2023-02-13 01:40
Actually, it's duplicate of #13315.
