### ISSUE TITLE
one-channel grayscale png output

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#15246] opened 2023-09-14 13:57 UTC
**Is your feature request related to a problem? Please describe.**

PNG format have grayscale feature, but dt can exporting only in RGB.

Size comparison of a sample 4x5" scanned b/w neg - 3200dpi:
tiff 16bit deflate with predictor graycsale - dt export: 276,1 MB
png 16bit RGB - dt export: 382 MB 
png 16bit grayscale - dt export converted to gray in GIMP: 264,7 MB

Exporting PNG in grayscale instead of RGB can saving 20-30% storage space on b/w images with high-res digital cameras and mid/large format scanned films.

**Comment by kmilos** [comment] 2023-09-14 14:37
Duplicate of https://github.com/darktable-org/darktable/issues/9266

Please search before opening new issues.

**Closed by kmilos** 2023-09-14 14:37 UTC
