### ISSUE TITLE
Auto-save every x minutes to prevent losing all changes when darktable crashes

### ISSUE THREAD

**Issue by daniel-j-h** [darktable-org/darktable#8768] opened 2021-04-24 07:33 UTC
Hey folks :wave:

every now and then darktable crashes on me, for whatever reasons. If I can reproduce it, I'm opening issues here. But often they seem to occur at random, and especially when a lot of masks and retouching already has happened.

Now the frustrating part in darktable crashing is not the crash itself, but that the user loses all changes for this particular image. In some cases I have spent hours e.g. using the retouch and tone equalizer module with lots and lots of masks, just to see it all being gone after a darktable crash.

What I have found out by pure experimentation is that if I switch to the lighttable, darktable seems to save the xmp sidecar. This means I can "save" my changes every half an hour or so switching to the lighttable and back. But this seems like a hack and not intended.

Can we provide some kind of auto-save option, to save the xmp sidecar files with all the edits done so far e.g. every 5 minutes or so?

**Comment by parafin** [comment] 2021-04-24 09:41
Duplicate of #7830

**Closed by parafin** 2021-04-24 09:41 UTC
