### ISSUE TITLE
Panasonic DC-G9M2

### ISSUE THREAD

**Issue by DC-G9M2** [darktable-org/darktable#16347] opened 2024-02-18 14:01 UTC
I just uploaded a whole raw sample set for the new Panasonic DC-G9M2 under CC0 license to
https://raw.pixls.us/ 

I hope it helps to get support of the raw file format in darktable!

If it not fullfil your needs, please let me know!

**Comment by LebedevRI** [comment] 2024-02-18 14:44
@DC-G9M2 thank you for contributing samples, but i believe we already have a full sample set.
Duplicate of https://github.com/darktable-org/darktable/issues/15679.

**Closed by LebedevRI** 2024-02-18 14:44 UTC
Labels: scope: camera support

**Comment by DC-G9M2** [comment] 2024-02-18 14:56
OK. I thought the more the better but apparently that is not the case... 😀
Thank you for your answer, I hope support can be created.



Op zo 18 feb 2024 om 15:44 schreef Roman Lebedev ***@***.***>:

**Comment by LebedevRI** [comment] 2024-02-18 15:02
See https://github.com/darktable-org/rawspeed/pull/529
