### ISSUE TITLE
Segmentation faults in lighttable

### ISSUE THREAD

**Issue by trougnouf** [darktable-org/darktable#4893] opened 2020-05-01 22:50 UTC
I've been getting very frequent crashes in lighttable as of today, browsing a large (2437) directory.

I'm using the branch steroid-filmic from @aurelienpierre on Arch Linux. I don't know if it's related to filmic v4 (I notice that the commits are gone, squashed? I'm now on 92d9da9669b3bcc4ca39f3919fbf6ce337635b94 ), some other commit, or just another package update.

My setup is AMD+Nvidia dual GPU so it doesn't help being exotic, and I can't go back to master (at least on this folder) because my db is updated.

I've included the auto-generated log files, I don't know if these can help pinpoint the problem / direction, as well as my darktablerc.

[darktable_bt_K65NJ0.txt](https://github.com/darktable-org/darktable/files/4566542/darktable_bt_K65NJ0.txt)
[darktable_bt_QFOUJ0.txt](https://github.com/darktable-org/darktable/files/4566546/darktable_bt_QFOUJ0.txt)
[darktable_bt_RSW2J0.txt](https://github.com/darktable-org/darktable/files/4566547/darktable_bt_RSW2J0.txt)
[darktable_bt_OXHVJ0.txt](https://github.com/darktable-org/darktable/files/4566544/darktable_bt_OXHVJ0.txt)
[darktable_bt_G33TJ0.txt](https://github.com/darktable-org/darktable/files/4566646/darktable_bt_G33TJ0.txt)
[darktable_bt_THDVJ0.txt](https://github.com/darktable-org/darktable/files/4566690/darktable_bt_THDVJ0.txt)

[darktablerc.txt](https://github.com/darktable-org/darktable/files/4566550/darktablerc.txt)

**Comment by Nilvus** [comment] 2020-05-02 08:29
Issues are for master or released versions. On actual master, I don't have any crash. So, before posting an issue like that, please test if you have same crash with the actual master (so without any "not merged" PR). If you are then sure the issue is about an open PR, it's on the PR that you have to post the issue, as all open PR are work in progress.

Test and check actual master and if issue is only related to filmic v4 PR, close this issue and go discuss that on filmic v4 PR actually open. Thanks.

**Comment by trougnouf** [comment] 2020-05-02 09:32
I switched to master and it did freeze right after export (which seems to be when most freezes occur)
[darktable_bt_RCRNJ0.txt](https://github.com/darktable-org/darktable/files/4567400/darktable_bt_RCRNJ0.txt)

I'm exporting to Wikimedia Commons (dtmediawiki), I haven't ran into issues exporting locally. I will try to make the issue consistently reproducible but I likely won't be able to work on it until next weekend.

**Comment by johnny-bit** [comment] 2021-05-18 16:51
We're at filmic v5 now ;) and I tried to break my `3.5.0+2258` ver to no avail with huuuge library and opencl enabled on nv's  1060 GPU.

**Closed by johnny-bit** 2021-05-18 16:51 UTC
Labels: no-issue-activity

**Comment by trougnouf** [comment] 2021-05-18 19:36
I'm still very consistently experiencing this issue; whenever I export an image with dtMediaWiki, darktable crashes shortly thereafter.
I guess the original post is not accurate, it's not necessarily lighttable, the crash can happen anywhere. The issue is thus most likely related to the Lua bindings (unless I made a mistake with dtMediaWIki?). My workflow has been to get used to it, and restart darktable before exporting if I want to restore the same state.
I guess I should make a small test to reproduce this issue without a Wikimedia Commons upload and reopen a new issue once it's pinpointed.

**Comment by johnny-bit** [comment] 2021-05-18 19:48
Since I don't use LUA things I have builds with lua disabled most of the time (except when I mess with things that include any mention of lua and on my production builds) so I might not be able to notice lua problems.
That being said, dtMediaWiki is your code, right? Mabe there's some weirdo interaction or something is off with handling that needs to be solved with lua-scripts devs?

Try to reproduce with minimal set and then increase complexity. If you manage to pinpoint the issue using current master then please open a new issue.
