### ISSUE TITLE
darktable does not connect to my Sony A7 camera

### ISSUE THREAD

**Issue by Armando59** [darktable-org/darktable#11163] opened 2022-02-17 10:12 UTC
gphoto does recognize my camera, I can even shoot with the --capture-tethered command, but darktabkle doesn't work.
attached details
env LANG=C gphoto2 --auto-detect
Model                          Port                                            
----------------------------------------------------------
Sony Alpha-A7 (Control)        usb:001,007 

env LANG=C gphoto2 --port usb: --abilities
Abilities for camera             : Sony Alpha-A7 (Control)                     
Serial port support              : no
USB support                      : yes
Capture choices                  :
                                 : Image
                                 : Trigger Capture
Configuration support            : yes
Delete selected files on camera  : yes
Delete all files on camera       : no
File preview (thumbnail) support : yes
File upload support              : yes

camctl.log
1,002685 [camera_control] creating new context 0x562fa45fc700
1,016947 [camera_control] loaded 2498 camera drivers.
3,586050 [camera_control] loaded 37 port drivers.
3,600534 [camera_control] 0 cameras connected
6,414672 [camera_control] loaded 38 port drivers.
6,425989 [camera_control] 1 cameras connected
6,426022 [camera_control] found new Sony Alpha-A7 (Control) on port usb:001,013
40,061223 [camera_control] destroy darktable camcontrol

**Comment by Armando59** [comment] 2022-02-17 10:14
DarktTable 3.8.0

**Comment by Nilvus** [comment] 2022-03-13 12:22
Which sony A7 mark you use? Actually mark 3 and mark 4 are not supported by gphoto. Having gphoto2 detect your camera doesn't mean it could deal with it. If gphoto do not support it, darktable won't too. There's some issues reported in gphoto github ones (gphoto2 and libgphoto2) about support for mark 3 and mark4 (seems that mark 2 is not totally supported).
So if you use mark 3 or mark 4, think about closing this issue as it's probably not darktable related. Thanks!

See for example: https://github.com/gphoto/gphoto2/issues/272 or https://github.com/gphoto/libgphoto2/issues/514

**Closed** 2022-05-13 11:09 UTC
Labels: bug: upstream, no-issue-activity

**Comment by reinvantveer** [comment] 2023-10-08 11:17
@Nilvus we might consider re-opening this? There is support for the A7, but there's a latency issue, it seems. 
This works:
`env LANG=C gphoto2 --wait-event=3s --port usb: --capture-image-and-download`
Fewer than 3s fails. But it's doable, for sure.

DarkTable appears to reject the camera outright though, I don't know why. I ran
`darktable -d camctl 2>1 >camctl.log`
Which states `22.0556 [camera_control] loaded 0 camera drivers.` Don't know if this is expected or not.
[camctl.log](https://github.com/darktable-org/darktable/files/12840480/camctl.log)

**Comment by reinvantveer** [comment] 2023-10-08 11:19
Entangle offers some capabilities for tethered capture, but as a front end it's rather rudimentary. I'd love to see better support for my Sony cam in DT.

**Comment by victoryforce** [comment] 2023-10-08 14:33
> @Nilvus we might consider re-opening this?

There is no need for this, as the problem is not in the darktable code.

> There is support for the A7, but there's a latency issue, it seems. This works: `env LANG=C gphoto2 --wait-event=3s --port usb: --capture-image-and-download` Fewer than 3s fails. But it's doable, for sure.

We use gphoto2 to work with cameras. If gphoto2 doesn't support the camera (or doesn't support it well), there's nothing darktable can do about it. Also, we build packages for macOS and Windows with the latest available versions of gphoto2, and we have no influence on official distribution builds. In summary, if you want better tethering support for your camera, you should raise an issue in [this library's repository](https://github.com/gphoto/libgphoto2/issues).

> DarkTable appears to reject the camera outright though, I don't know why. I ran `darktable -d camctl 2>1 >camctl.log` Which states `22.0556 [camera_control] loaded 0 camera drivers.` Don't know if this is expected or not. [camctl.log](https://github.com/darktable-org/darktable/files/12840480/camctl.log)

It's not darktable who rejects it. Your log file shows that you are using a snap package. This package is not provided by us and it is  simply does not give the program access to tether the camera (snap is a sandboxed format). See https://github.com/darktable-org/darktable/issues/14623#issuecomment-1751768953

@TurboGit What do you think of the warning on the darktable download page that we don't recommend a third-party snap package due to currently broken functionality?

**Comment by reinvantveer** [comment] 2023-10-08 15:25
> Your log file shows that you are using a snap package. This package is not provided by us

Oh this is definitely my mistake. I should have gone with the flatpak or the apt repo.

**Comment by reinvantveer** [comment] 2023-10-08 15:50
> warning on the darktable download page

Am I correct in understanding that the flatpak installation suffers from the same sandboxing issue, lacking USB access? The flatpak installation method is one that the website recommends: https://www.darktable.org/install/#universal-package-formats
Maybe the warning should be here too.

What's the recommended installation method for Ubuntu 20.04 that includes USB connected cameras? 22.04 still suffers from many driver compatibility issues.

**Comment by ptilopteri** [comment] 2023-10-08 15:58
> > warning on the darktable download page
> 
> Am I correct in understanding that the flatpak installation suffers from the same sandboxing issue, lacking USB access? The flatpak installation method is one that the website recommends: https://www.darktable.org/install/#universal-package-formats Maybe the warning should be here too.

perhaps you should read that as "the website shows available" rather than recommends.

I believe that building for yourself is the *only* recommended method of/for installation.

> What's the recommended installation method for Ubuntu 20.04 that includes USB connected cameras? 22.04 still suffers from many driver compatibility issues.

**Comment by victoryforce** [comment] 2023-10-08 16:28
> Am I correct in understanding that the flatpak installation suffers from the same sandboxing issue, lacking USB access?

No, unlike snap, [flatpack is created correctly](https://github.com/flathub/org.darktable.Darktable/blob/master/org.darktable.Darktable.json#L24-L25).

> What's the recommended installation method for Ubuntu 20.04 that includes USB connected cameras?

A fresh version of darktable is difficult to build natively in an Ubuntu 20.04 environment (certain packages are too old in this release for some requirements of recent darktable versions). I'm building an AppImage in a 20.04 environment, but I'm using third-party PPAs for that.

Therefore, if you are forced to use this old version of Ubuntu, then flatpack can provide you with a fresh version of darktable. Or, if you're not afraid to use development snapshots, you can try nightly builds in AppImage format.

**Comment by reinvantveer** [comment] 2023-10-08 16:43
OK thanks, I'm more than happy to use flatpak then :+1:

**Comment by reinvantveer** [comment] 2023-10-08 17:18
For future reference: my Sony A7R IV is supported just fine in DarkTable, also as tethered cam. Set the camera to USB pc remote control (tab Network1 page 1/3), choose PC remote control connection method USB, plug in using USB-C and flatpak-installed DarkTable will be able to detect it.

**Comment by TurboGit** [comment] 2023-10-09 06:47
> @TurboGit What do you think of the warning on the darktable download page that we don't recommend a third-party snap package due to currently broken functionality?

Probably a good idea yes!

**Comment by victoryforce** [comment] 2023-11-01 18:18
@TurboGit I suggest a text like the following:

`Currently, we cannot recommend installing the darktable snap package, as it does not support tethering functionality due to the lack of the necessary permissions.`

@paperdigits What is your opinion on this?

**Comment by paperdigits** [comment] 2023-11-01 18:30
I don't think we should recommend anything, that is just asking for people to complain. 

I'd much rather just have a note that not all features are available in the snap package currently.

**Comment by paperdigits** [comment] 2023-11-01 20:37
I try to minimize the noise from users. 

I had a request to enable Wayland support in the flatpak build... I said no, nobody is using Wayland, we're not equipped to support it, and it isn't ready for our use case. That didn't go well. You can trade "Wayland" for "snap" or "flatpak" or any other technology that people like to have an opinion about. Its just noise and its a distraction.

The darktable project doesn't recommend any packages for unix-like systems. If we do, then we should build and maintain those packages so we as a project can ensure quality. 

We list 3rd party packages as a convenience. What's the point of listing it if we don't in some way recommend it?

OBS is there because the community supports it.

Flatpak is there because I personally support it.

Snap... ??? I guess we shouldn't list it.

**Comment by victoryforce** [comment] 2023-11-01 21:25
> Snap... ??? I guess we shouldn't list it.

It won't help at all. Ubuntu users just see it in the app store. If they can't read on the program's website that this snap is of very poor quality (and so we are not to be blamed for its shortcomings), they simply won't know about it.

The worst thing is that a large part of users will not suspect that the cause of their problems is a low-quality snap build, and will consider that the program itself is of poor quality. I'm trying to avoid that.

> We list 3rd party packages as a convenience. What's the point of listing it if we don't in some way recommend it?

See above.

> The darktable project doesn't recommend any packages for unix-like systems. If we do, then we should build and maintain those packages so we as a project can ensure quality.

Exactly! I absolutely agree, you can only recommend those things, the quality of which you can ensure. _We are not saying that we recommend anything third-party._ It is exactly the opposite. We cannot guarantee the quality of a snap package that is not under our control, and we know that it is currently of very poor quality. All we can do is warn users about this fact. And this is a responsible approach, because it avoids unnecessary frustration of users and saves their time.

**Comment by TurboGit** [comment] 2023-11-03 13:25
As a first step we could add a note on the release notes about limitations of snap. It won't help lot of users but at least the issue with snap will be made aware to those reading the release notes and in turn they will engage the discussion with users about snap being a bad option. What do you think?

**Comment by victoryforce** [comment] 2023-11-06 20:20
> As a first step we could add a note on the release notes about limitations of snap.

To be honest, I don't understand why we are talking about the first step. What prevents us from taking all the step we should be taking to protect users from a poor quality build? What's stopping us from simply putting text on the site's downloads page detailing the specific darktable snap flaws?

> It won't help lot of users

Why not help them?

> discussion with users about snap being a bad option.

This wording makes it sound like snap is an inherently bad format. It's not, and I didn't mean to write text that would give users that impression. The limitation of darktable snap is, I firmly believe, a result of sloppy half-assed packaging, not a limitation of the technology.
