### ISSUE TITLE
resulting image has several parts in black - imagen resultante al exportar

### ISSUE THREAD

**Issue by subegv** [darktable-org/darktable#16451] opened 2024-03-13 11:51 UTC
### Describe the bug

I have the following problem when I export image, but it didn t happen before. 

* File: tiff
*Adobe rgb
* To print - width 70 cm
* Resolution: 300

Other Data:
Darktable 3.4.1.1
Windows 10

****Problem: When I export and I save it, the resulting image has several parts in black.
 

### Steps to reproduce

export - tiff - Adobe rgb - print 70 cms. - 300 - save in folder

### Expected behavior

Darktable should save correctly the image

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

3.4.1.1

### What OS are you using?

Windows

### What is the version of your OS?

Windows 10

### Describe your system?

RAM 8
DARKTABLE VERSION: 3.4.1.1

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

It never happened before, I never had problems with this same exportation before.

**Comment by MStraeten** [comment] 2024-03-13 12:13
RAM 8 seems to be an issue ... how many parallel ram consuming tasks?

**Comment by subegv** [comment] 2024-03-13 12:22
I look for the necessary RAM, and it seems it is enough. Before never happen. 

I don understand your question: how many parallel ram consuming tasks?
When I with Darktable I don not do other tasks

Thank youy

**Comment by ralfbrown** [comment] 2024-03-13 13:08
You're using a version of darktable which is over three years old - we've had six major releases since then, with many bugfixes.  Including at least one that fixed black squares in exported files.

**Comment by subegv** [comment] 2024-03-13 13:13
Thank you. I know that I am using an old version. 
Do you know why that problem of the black squares happens?


> You're using a version of darktable which is over three years old - we've had six major releases since then, with many bugfixes. Including at least one that fixed black squares in exported files.

**Comment by pehar1** [comment] 2024-03-13 16:43
Nobody will be willing to invest time in supporting such an outdated version. Please update to the current version 4.6.x and test whether the issue persists.

**Comment by subegv** [comment] 2024-03-13 16:53
> Nobody will be willing to invest time in supporting such an outdated version. Please update to the current version 4.6.x and test whether the issue persists.

Thank you. Do I have to unisntall the old one to install the new one?

**Comment by ptilopteri** [comment] 2024-03-13 17:31
you *should* not but usual caveats apply, backups are a Good Idea
at least backup your configuration directory

and since your dt version is so old, there will be quite a few configuration changes that have been implemented since version 3.4.1 and perhaps shortcut key strokes.

**Comment by subegv** [comment] 2024-03-14 11:33
The reality is that I already downloded the last version. 
One problem I had was that it did not recognize my camera and lens. 
Nobody could explain me how I could solve this problem.
That is why I decided to go back to the old one.
But I will try to work with the last one again.

**Comment by victoryforce** [comment] 2024-04-02 18:36
> But I will try to work with the last one again.

@subegv Is your problem no longer reproduced on the latest version?

**Comment by subegv** [comment] 2024-04-03 10:00
I already download the last version. At least, now it recognices my camera and lens.  But I would try again with the photo. I will tell you when I do it.

**Comment by jenshannoschwalm** [comment] 2024-04-14 06:36
Closing this for now, feel free to open a new issue if issue persists in 4.6.1

**Closed by jenshannoschwalm** 2024-04-14 06:36 UTC

**Comment by subegv** [comment] 2024-04-30 10:00
> > But I will try to work with the last one again.
> 
> @subegv Is your problem no longer reproduced on the latest version?

Hi. With the last version I do not have the problem of the image in black. But it does not recognize lens and camera again with some pictures. Could you help me how to solve this?
![CAMARA U OBJETIVO NO ENCONTRADO](https://github.com/darktable-org/darktable/assets/163299754/853f6dfb-1058-46bf-ae63-b1fe561ae63f)

**Comment by subegv** [comment] 2024-04-30 11:02
> > But it does not recognize lens and camera again with some pictures. Could you help me how to solve this? thank you!
> 
> Please head over to https://discuss.pixls.us/c/software/darktable/19 for end user support (this is a lensfun related issue, not a darktable one), and restrict GitHub interaction to dt development and actual bugs.

Sorry, I think this  is a problem with darktable not with the camera.
