### ISSUE TITLE
export impossible

### ISSUE THREAD

**Issue by capish** [darktable-org/darktable#6486] opened 2020-10-09 11:58 UTC
aucun affichage de l'image dans la table lumineuse .
donc l'image traitée n'est pas affichée pour l'export et celui ci ne fonctionne pas.
Bug Bloquant

**Comment by MStraeten** [comment] 2020-10-10 04:17
Please check your filters in lighttable first. If no image is visible and you didn’t delete it you might have changed the star rating not matching the filter.
But that’s just speculation, so please give more information (see https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title= for needed information)

**Comment by capish** [comment] 2020-10-11 12:36
[image: image.png]


Hello,
I did some tests on Saturday.
The problem is due to the "display" filter which, depending on the case,
prevents display in the light table.
The filter should be set to "all" by default to avoid pb
This is what is done, by default, when importing a single image
thanks for your advices
best regards
rio

Le sam. 10 oct. 2020 à 06:17, Martin Straeten <notifications@github.com> a
écrit :

**Comment by johnny-bit** [comment] 2020-12-15 19:30
So... as I understand the problem is fixed by changing display filters...

**Closed by johnny-bit** 2020-12-15 19:30 UTC
Labels: no-issue-activity

**Comment by capish** [comment] 2020-12-17 01:28
Yes changing the display  filters fixed the problem 
Thanks



⁣Télécharger BlueMail pour Android ​

Le 15 déc. 2020 à 20:30, à 20:30, Hubert Kowalski <notifications@github.com> a écrit:
