### ISSUE TITLE
Collection filters / new rule / "35mm equiv focal lenght"

### ISSUE THREAD

**Issue by DarekGH** [darktable-org/darktable#17867] opened 2024-11-20 15:45 UTC
Needed when the film roll contains photos from cameras with different crop factors. When we make a filter with a physical focal length of e.g. 17 - 30mm, it can give the result: 17-30 when the photo was taken with an FF camera, 25-45mm for a DX camera and 46-81mm for a 1inch camera. Of course, such a result does not say anything about the angle of view used to take the photo. However, when we create a filter according to "35mm equiv focal legth" we will get a result with the same angles of view for each sensor size.
Darek

**Comment by victoryforce** [comment] 2024-11-20 16:28
Duplicate of #15482.

**Closed** 2024-11-20 16:28 UTC
