### ISSUE TITLE
problems exporting files after edit in raw, sometimes it exports, sometimes not, darktable locks, cpu goes to 70 centigrade!

### ISSUE THREAD

**Issue by mlytle0** [darktable-org/darktable#11146] opened 2022-02-15 23:21 UTC
**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.0
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : Manjaro rolling release XFCE
* Memory            : 8 GB
* Graphics card     : Motherboard, Intel
* Graphics driver   : i915
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

I really like this version, the new modules are amazing, but now with version 3.8.0 running on two Dell systems an I5 and I7 of older vintage, I find that after editing ANY raw fie from my Lumix FZ300, converting to .PNG or .JPEG and exporting only works intermittently, usually locks up darktable such that I just have to kill the application.  While this is happening. the CPU  fan is howling and temperatures go north of 70 degrees celsius, even after I've shut down darktable.  I have to shut down the computer as it never returns to a normal temperature.  Almost as though some stub of the program is still running after I've killed the application.  Both computers are running Manjaro, XFCE versions with rolling updates.  Install comes from the Manjaro installer, and updates on whatever schedule the new versions are released.   I also notice that regardless of how I set it in the preferences, the .xmp files are never written, even in those cases when it actually manages to export a .jpeg from the raw file after processing.  I am open to changing settings, but I can't imagine a missetting that would cause this behavior, and what I'm doing is very ordinary, not exotic.

This has never happened to me with any prior version of darktable, been using it for 2 years now.  I'm hoping I'm not the only one reporting this.  Since it's on two computers and started with this version, I feel it's a bug, these are Optiplex  790 and 8020 Dell machines older but very reliable.

**Comment by TurboGit** [comment] 2022-02-16 08:56
I will close this ticket as there is no information that we can use to know what is wrong.

Please on your side check which module is doing that. Use a simple expose, is that exporting ok? If yes use another module that you used to use and check if it exports ok... and so on. We need to find the cause and from your report it is just impossible. TIA.

**Closed by TurboGit** 2022-02-16 08:56 UTC

**Comment by mlytle0** [comment] 2022-02-16 14:55
The module causing this is one of the new ones, diffuse or sharpen. Good to know, as I can continue using this program, just not use that module. It just didn't occur to me that if a module worked on the screen edit, that it would have any effect on writing out the corrected file many edits and modules later.
     On Wednesday, February 16, 2022, 02:56:23 AM CST, Pascal Obry ***@***.***> wrote:  
 
 


I will close this ticket as there is no information that we can use to know what is wrong.

Please on your side check which module is doing that. Use a simple expose, is that exporting ok? If yes use another module that you used to use and check if it exports ok... and so on. We need to find the cause and from your report it is just impossible. TIA.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mlytle0** [comment] 2022-02-16 16:12
The module causing this is one of the new ones, diffuse or sharpen. Good to know, as I can continue using this program, just not use that module. It just didn't occur to me that if a module worked on the screen edit, that it would have any effect on writing out the corrected file many edits and modules later.
     On Wednesday, February 16, 2022, 02:56:25 AM CST, Pascal Obry ***@***.***> wrote:  
 
 


Closed #11146.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TurboGit** [comment] 2022-02-16 17:26
> It just didn't occur to me that if a module worked on the screen edit, that it would have any effect on writing out the corrected file many edits and modules later.

It just need lot more memory, on screen the image is small at export time it will have a far bigger definition! You probably need more memory or tweak the preferences (there was already discussions about this).

**Comment by mlytle0** [comment] 2022-02-16 18:05
That worked, I increased my 'Host memory limit in MB for tiling' from the 1500 default to 4000 MB and that took care of it.
Still don't see the sidecar .xmp files, so I don't know whether that's a setting or what. In preferences under storage I have the three options for the .xmp set to the defaults, with the dots in front to confirm that.
     On Wednesday, February 16, 2022, 11:26:46 AM CST, Pascal Obry ***@***.***> wrote:  
 
 



It just didn't occur to me that if a module worked on the screen edit, that it would have any effect on writing out the corrected file many edits and modules later.


It just need lot more memory, on screen the image is small at export time it will have a far bigger definition! You probably need more memory or tweak the preferences (there was already discussions about this).

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
