### ISSUE TITLE
OM Systems OM1

### ISSUE THREAD

**Issue by greymont** [darktable-org/darktable#11274] opened 2022-03-05 21:24 UTC
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by greymont** [comment] 2022-03-05 21:28
I just uploaded normal resolution, hand-held high-resolution, and tripod-mounted high-resolution images. These will be slightly different than the Olympus EM-1 Mark iii images. I used the new company name rather than Olympus for these.

**Comment by Nilvus** [comment] 2022-03-06 08:36
Please search before posting. This is a duplicate of already existing one, just few lines below in issues. See #11258

**Closed by Nilvus** 2022-03-06 08:36 UTC
Labels: duplicate, scope: camera support

**Comment by algreen05** [comment] 2022-03-07 09:41
I have checked OM-1 support in the latest git version from RAW files uploaded on the internet and the camera is not supported.

**Comment by Nilvus** [comment] 2022-03-07 12:21
Of course, but an issue to add support is already opened, just 2 days before this one. Read my comment better.
