### ISSUE TITLE
Artifacs in surface blur module

### ISSUE THREAD

**Issue by rabauke** [darktable-org/darktable#7141] opened 2020-11-30 20:15 UTC
**Describe the bug**
Surface blur module creates artifacts (but no blur).

**To Reproduce**

- Go to darkroom view.
- Enable surface blur module with default parameters.

**Expected behavior**
Some edge-preserving smothening.

**Screenshots**
![Bildschirmfoto vom 2020-11-30 20-58-35](https://user-images.githubusercontent.com/1159508/100658946-266cd900-3350-11eb-80e6-1accda21ceb9.png)

**Platform (please complete the following information):**
dt from git master (with some local tweaks)
```
this is darktable 3.3.0+1931~gff954dcf6
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled
```

**Additional context**

The specific artifacts are not reproducible, and vary from one program invocation to another. Issue can be observed with and without `--disable-opencl` option.

**Comment by ralfbrown** [comment] 2020-11-30 22:38
We've seen this before, and thought it was fixed....  It's some sort of race condition, and how many bands you get in the image depends on how many threads are running since each thread gets a horizontal slice of the image (you can see them change if you use the -t N flag to darktable to set the number of threads).

Can you provide the image and XMP?  Maybe I can reproduce the problem with them.

**Comment by rabauke** [comment] 2020-12-03 18:13
I tried to debug this. But I am unable to reproduce this issue currently.

**Comment by johnny-bit** [comment] 2020-12-15 19:34
Wouldn't this be basically a duplicate of #4984?

**Comment by rabauke** [comment] 2020-12-15 23:34
@johnny-bit Probably yes.

**Comment by johnny-bit** [comment] 2020-12-18 18:06
I've looked more into this and it seems exactly the same issue as #4984 :/ I hate multithreading bugs... I swear I saw on my edits this problem once and then it disappeared with adjusting sliders, never to reappear again :/

**Closed by johnny-bit** 2020-12-18 18:06 UTC
Labels: bug: pending, duplicate, reproduce: random
