### ISSUE TITLE
Attribution of OpenStreetMap in Map tool

### ISSUE THREAD

**Issue by SK53** [darktable-org/darktable#4977] opened 2020-05-10 12:59 UTC
**Describe the bug**

OpenStreetMap is not credited on screen as is **required** by OSM's [copyright](https://www.openstreetmap.org/copyright) T&Cs. The widget used provides a call to access attribution, it should be used.

**To Reproduce**

1. Go to "Map"
2. Look for visible evidence of an OSM copyright statement (e.g., bottom right or bottom left of map)
3. Not present => error

**Expected behavior**

A visible statement (c) OpenStreetMap contributors bottom left or bottom right of similar size to the lat/lon display

**Screenshots**

![Screenshot (1)](https://user-images.githubusercontent.com/5452818/81499834-2b8c0d00-92c6-11ea-84cb-4b62009f02ef.png)

**Platform (please complete the following information):**
 - Darktable Version:  3.0.2
 - OS:  Windows 10.
 -  N/a
 -  N/a

 

**Additional context**

**Comment by parafin** [comment] 2020-05-10 13:03
Duplicate of #3443

**Closed by parafin** 2020-05-10 13:03 UTC
