### ISSUE TITLE
crop & rotate guides are right of the image when activated

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/darktable#2950] opened 2019-09-16 21:18 UTC
**Describe the bug**

If I open the crop and rotate module the guides for cropping are right next to the image instead on it. This is current master: 0c527aec183d4aaf23104a87be2cf88ca58b8a67

See https://xor.cryptomilk.org/pics/darktable_crop.png

**Comment by ptilopteri** [comment] 2019-09-16 21:56
I am running the same current master oc527ae, but do not have what you display.  

Can you try without your ~/.config/darktable/darktablerc, 
darktable --configdir /dev/null

maybe it is related to a setting you had which has changed.  I had a similar problem and slowly tested changing local settings until I had what I expected.

good luck

**Comment by AxelG-DE** [comment] 2019-09-17 05:24
I am on g0c527aec1 and have no issue

on the dev-maillinglist there is a bit crypto message, where Alexander talk about "broken transformation module" (Pascal asked already to drop this here). I wonder, this could be the similar issue and at least we do have no more a single-case issue

**Comment by cryptomilk** [comment] 2019-09-17 05:53
This only happen on a portrait picture, if I expand the module (not activating it).

**Comment by PaoloAst** [comment] 2019-09-17 06:21
I'm confirming the issue

**Comment by AxelG-DE** [comment] 2019-09-17 06:24
I confirm for portrait!

Interestingly the grid was inside the pic unless I tried to change the grid-mode (new installation, was not on my preferred golden ratio, yet)

**Comment by TurboGit** [comment] 2019-09-17 07:41
How do you reproduce? With an old edit? I tried, and tried again (with portrait picture, switching images with filmstrip to/from portrait/landscape, etc...) and cannot reproduce this issue :(

**Comment by AxelG-DE** [comment] 2019-09-17 10:16
For my case, I came from 
- lighttable/culling mode, 
- selected a set of 4 portraits, 
- doubble clicked on one
- opened up crop&rotate
- switched on grid (grid inside pic) 
- changed grid to golden ratio and now plopped to outside the pic, as illustrated in initial post

**Comment by TurboGit** [comment] 2019-09-17 12:05
Still cannot reproduce! Questions:
- is that with a new edit or old picture?
- was the crop/rotate activated before?
I suppose not as the report state that the module is opened but not activated.

I'm wondering if this is not an issue with the orientation module. If old edit, what is the current history stack? Is resetting orientation with the orientation module fixes the issue?

**Comment by cryptomilk** [comment] 2019-09-17 13:44
I think you're right an it is an issue with the orientation module. If I go back in the history before the orientation is applied. It seems to work correctly now.

**Comment by cryptomilk** [comment] 2019-09-17 13:47
Is it maybe the order now? The crop&rotate module comes before the orientation module in the pipe order. Does the crop&rotate rely on orientation?

**Comment by cryptomilk** [comment] 2019-09-17 17:50
As you can see from the screenshot the picture has been taken with the camera in portrait orientation. So the initial rotation is in the exif.

If I click on the guides to crop the image, it shows negative values: -4026 x -6084

**Comment by AxelG-DE** [comment] 2019-09-17 18:10
For my case, I was in a hurry on the way to the office, so currently no info about orientation, as I'm in Gym now...

I used an unedited photo, opened c&r and when I was fiddling with changing the grid, the module got activated

**Comment by aurelienpierre** [comment] 2019-09-18 14:29
current IOP order defines (as of 86ed8400f14250684f4c960385fa20ccbb293f82):
` _ioppr_move_iop_before(_iop_order_list, "flip", "clipping", dont_move);`

aka flip (orientation), before clipping (cropping). 

So, this means the default order is not honoured.

**Comment by junkyardsparkle** [comment] 2019-09-18 19:17
There's another case where a module is placed out of order in #2954 (currently closed), btw.

**Comment by cryptomilk** [comment] 2019-09-19 06:16
@aurelienpierre I dunno what you mean exactly, I've freshly imported those pictures, so how could the order be wrong?

**Comment by TurboGit** [comment] 2019-09-19 06:57
@cryptomilk : that's worrisome indeed! we really need to understand what is going on and more importantly how to reproduce!

**Comment by AxelG-DE** [comment] 2019-09-19 06:59
As I can reproduce, I'll support, as soon I am at home, my Fotos where also fresh ones

**Comment by AxelG-DE** [comment] 2019-09-19 18:59
Darned :-(
All over sudden, I cannot reproduce anymore... 

Without changes, except laptop was in hibernation, suddenly dt crashed upon startup with "munmap_chunk(): invalid pointer" 
After one start with --configdir /tmp and afterwards dt starts normal again... 
Ever since above effect is gone :-/

I just notice, an unedited photo now has many more items in a virgin history stack than before, like gamma, input and output color profile, raw black/white...
Donno, is related.... 

I'll check on my PC later...

**Comment by AxelG-DE** [comment] 2019-09-19 19:16
now back to my PC, I cannot reproduce either :-(((

An old topic came back anyways. When cropt & rotate is activated, and I just open and close the module, I get a new entry in the history stack
![Screenshot_20190919_211147_cut](https://user-images.githubusercontent.com/49004103/65273971-a085b900-db22-11e9-8034-1dbb55b10067.png)

Indeed, I can compress, but such behaviour feels less confident...

**Comment by AxelG-DE** [comment] 2019-09-19 19:34
@PaoloAst 
can you still confirm?

@cryptomilk did you update to current master 752a88b9d and do you still have the issue?

**Comment by leclercj** [comment] 2019-09-19 19:59
@AxelG-DE, may be you could open a new issue for your new finding (new entry in the history stack each time crop&rotate is expended/collapsed).
At least this one I can reproduce easily.
To my observation, this one has to deal with timing: When crop&rote opens, it has to update the screen to display the full picture + the crop line. It take a small lapse of time.
- If I click again quickly to close it back during this lapse of time, before the end of the opening operation, then a new entry appears in the history stack.
- If I click more slowly on open/close, then no new entry in the history stack.

**Comment by ptilopteri** [comment] 2019-09-19 20:09
current git-master

I get a new entry on the history stack by merely expanding the crop and rotate module on
new image, old image, cropped image, ...

**Comment by AxelG-DE** [comment] 2019-09-19 20:13
@leclercj 
you are right, I shouldn't have mixed things here, sorry for confusion

@ptilopteri I meant, whether you still can confirm the original issue from this bugreport... Just now I see your update, does that mean you are at the same page than me, suddenly you cannot reproduce the issue from @cryptomilk anymore? That would be top strange

**Comment by TurboGit** [comment] 2019-09-19 20:14
> I get a new entry on the history stack by merely expanding the crop and rotate module on
> new image, old image, cropped image, ...

That's a different issue, a bug there since a long time... If you compress the history there is no more new entries for every click on the same module.

**Comment by ptilopteri** [comment] 2019-09-19 20:18
I was merely responding to your comment about the appearance of "crop and rotate" on top of the history stack.

I do *not* observe offset crop and rotate guides, and cannot remember ever seeing that condition.

**Comment by AxelG-DE** [comment] 2019-09-19 20:25
@ptilopteri 
that was my bad, again a sorry, I mixed something, you are totally right

**Comment by PaoloAst** [comment] 2019-09-19 20:58
> @PaoloAst
> can you still confirm?
> 
> @cryptomilk did you update to current master [752a88b](https://github.com/darktable-org/darktable/commit/752a88b9d853cd6413ee0d436431807e3cf8eaae) and do you still have the issue?

Yes. It is still present.
I definet "C" shortcut to activate the module "C&R". On a portrait photo, I press "C" to activate it and a white frame appears around the photo without the possibility to crop it. The resolution displayed over the picture says zzzzz x yyyyy, where yyyy is a negative number

**Comment by leclercj** [comment] 2019-09-19 21:10
@PaoloAst in the pipeline, do you have crop&rotate upper than orientation, or lower ?

![Capture d’écran du 2019-09-19 23-03-28](https://user-images.githubusercontent.com/22872204/65281268-7936e800-db32-11e9-9bfe-7d5c1e9388a6.png)

**Comment by PaoloAst** [comment] 2019-09-19 21:21
> @PaoloAst in the pipeline, do you have crop&rotate upper than orientation, or lower ?
> 
> ![Capture d’écran du 2019-09-19 23-03-28](https://user-images.githubusercontent.com/22872204/65281268-7936e800-db32-11e9-9bfe-7d5c1e9388a6.png)

Before editing, I've deleted the darktablerc file, so my pipeline should be the "official" one. It happens only on portrait photo. Do you want to have an example picture together with xmp file?

**Comment by AxelG-DE** [comment] 2019-09-19 21:36
@PaoloAst 
I think, what @leclercj meant was more in the direction of aruellien, due to what ever reason, the sequence might change.
For me, orientation (now) comes before c&r
so, could you pls provide a screenshot of yours, pls. especially the one with error?

**Comment by PaoloAst** [comment] 2019-09-19 21:53
[2019-08-26 Lalibela.zip](https://github.com/darktable-org/darktable/files/3633352/2019-08-26.Lalibela.zip)
![Schermata da 2019-09-19 23-51-20](https://user-images.githubusercontent.com/43513892/65283957-9b336900-db38-11e9-83b7-be023128f2ca.png)
![Schermata da 2019-09-19 23-49-47](https://user-images.githubusercontent.com/43513892/65283958-9b336900-db38-11e9-81e0-f3463194474d.png)

**Comment by PaoloAst** [comment] 2019-09-19 21:55
![Schermata da 2019-09-19 23-53-56](https://user-images.githubusercontent.com/43513892/65284060-d170e880-db38-11e9-86c6-e29bd452916f.png)
If you play with C&R, then you press "reset" on the iop module

**Comment by cryptomilk** [comment] 2019-09-20 06:35
The issue is that if I look into the 'active modules' the orientation comes after the c&r module. If I move the orientation down, so it comes **before** c&r it works correctly!

So the questions is, why do I have an invalid sequence?

**Comment by leclercj** [comment] 2019-09-20 09:31
in the xmp from @PaoloAst I'm surprised to see a float number ("8.01562") for clipping iop_order. I was expecting an integer (namely "21"). What could be the cause of that ?

<rdf:li darktable:num="8" darktable:operation="clipping" darktable:enabled="1" darktable:modversion="5" darktable:params="0000000000000000000000000000803f0000803f0000000000000000cdcc4c3ecdcc4c3ecdcc4c3fcdcc4c3ecdcc4c3fcdcc4c3fcdcc4c3ecdcc4c3f000000000000000000000000010000000000000000000000" darktable:multi_name="" darktable:multi_priority="0" **darktable:iop_order="8.01562"** darktable:blendop_version="9" darktable:blendop_params="gz11eJxjYGBgkGAAgRNODGiAEV0AJ2iwh+CRyscOAAdeGQQ="/>

**Comment by TurboGit** [comment] 2019-09-20 09:36
> So the questions is, why do I have an invalid sequence?

That's indeed the real question. No idea on my side. I cannot reproduce. This is very strange.

**Comment by AxelG-DE** [comment] 2019-09-20 19:20
for me c&r is also above rotation, if I look at (activated modules), however I do not have the initial issue/problem anymore

But I ever thought, the history stack is the relevant one. There rotation is on pos 6 and c&r is on pos 8

Hmmmmm

**Comment by AxelG-DE** [comment] 2019-09-20 19:25
![Screenshot_20190920_212336](https://user-images.githubusercontent.com/49004103/65353267-fde63c80-dbec-11e9-9aa8-d2692dc465fd.png)

**Comment by parafin** [comment] 2019-09-22 07:09
1. What is the sequence of actions that causes iop order to switch? I thought that it's stored in DB/XMP now, so upgrading DT shouldn't change it...
2. This particular bug should be fixed for real (not just by saying that iop order is to blame) - if user can move c&r module, then crop guides should be displayed correctly Independent of its position.

**Comment by leclercj** [comment] 2019-09-22 08:58
In my view, there is no point to allow crop&rotate before orientation.
Reading the code, my current thinking is we are just missing some iop order rules
- orientation(flip) before crop&rotate(clipping) is one of them
and we may miss many others, present as upgrade rules, but not in-forced later:
- ashift before orientation(flip)
- crop&rotate(clipping) before liquify
- ...

**Comment by AxelG-DE** [comment] 2019-09-22 09:21
@cryptomilk I have similar question than @parafin 
when you open a fully unedited foto, where does orientation show up in the sequence of active modules or (what I assume) is it not even activated by default and kicks-in the moment you touch c&r?

For me it looks like this on a virgin foto:
![Screenshot_20190922_112024](https://user-images.githubusercontent.com/49004103/65385126-12305380-dd2b-11e9-8693-92dbd1b79e21.png)

**Comment by jenshannoschwalm** [comment] 2019-09-22 12:25
I think i have an idea about the problem, please correct if not so.

My situation, i work on dt master for months and have a database containing pictures imported during the last half year or so, many have **not** been touched since months, some have been extensively used and tested. So there are history data quite old and some very new (after commits inserting before unseen basic modules with a new iop_order).

While working on history compression i had to look into the database much more than i ever desired. There are two very strange things

1. Select one picture and discard history. Then add a lot of modules in darkroom mode and quit. If you look into the history database you see: 
![nonsense](https://user-images.githubusercontent.com/50982232/65387037-19fbf200-dd43-11e9-8360-7bb143263a18.png)

2. First thought, pretty dangerous to have iop_orders of completely different modules so close together.

3. Then i looked into the history database sorting by module name and found these:
![0](https://user-images.githubusercontent.com/50982232/65387056-77903e80-dd43-11e9-86f3-6306d13e99fe.png)
![1](https://user-images.githubusercontent.com/50982232/65387057-7c54f280-dd43-11e9-8935-2b1202cce785.png)
![2](https://user-images.githubusercontent.com/50982232/65387060-80811000-dd43-11e9-92cd-22d5c1ede747.png)

My conclusion is, at least the iop_order values written to the database **and** the sidecar files are wrong. I guess these are related: #2905 #2918

**Comment by TurboGit** [comment] 2019-09-22 14:59
Yes, that looks correct to me. The iop_order is dynamic and computed as a float. A new active module which must be between two currently active modules will get its iop_order by dividing the iop_order of the module before and after : (before + after) / 2.

So indeed iop_order for a given module can change from one image to another.... But the algorithm ensure (at least it should but there is maybe a bug, we will know when someone can have a reproducer) that modules are in a specific order that works.

**Comment by jenshannoschwalm** [comment] 2019-09-22 16:21
Ok thanks for helping here.

**Comment by BigSerpent** [comment] 2019-09-22 19:49
I think it can be caused by some inconsistency between the current state of the ordering in dt and the order rules at the time the image was imported. I've searched a little and found opposite collections of images. One collection represent correct behavior, and the second - incorrect one. Both coexist at the same time in the same session.
[DSC02738.ARW.zip](https://github.com/darktable-org/darktable/files/3640100/DSC02738.ARW.zip)
[DSC05276.ARW.zip](https://github.com/darktable-org/darktable/files/3640101/DSC05276.ARW.zip)

**Comment by TurboGit** [comment] 2019-09-23 05:11
May be fixed by #2974 

Could you test latest master with new edits? Or file edited before Sep 16th?

**Comment by cryptomilk** [comment] 2019-09-23 06:27
My issues are gone.

**Comment by TurboGit** [comment] 2019-09-23 06:48
Great! So problem is solved, but even if now I kind of understand what was going on, I'm still mystified by the fact that I was not able to reproduce :( I think that to reproduce a specific set of module must have been activated prior to  the Sep 16th wrong patch.

**Comment by PaoloAst** [comment] 2019-09-23 06:49
Thank you! Now it works! Great

**Comment by TurboGit** [comment] 2019-09-23 06:52
Ok, closing now.

**Closed by TurboGit** 2019-09-23 06:52 UTC
Labels: bug

**Comment by TurboGit** [comment] 2019-09-23 15:32
@cryptomilk & @all:
I would appreciate if you could test the re-introduction of the new iop order which should not affect old edits at all:

#2979

Thanks!

**Comment by BigSerpent** [comment] 2019-09-23 16:55
So, current git master works OK for the problematic images after their history stack has been discarded. If unmodified, the previous effect exist.
