### ISSUE TITLE
The fusion setting of the equalizer module is not displayed correctly after switching from one photo to another

### ISSUE THREAD

**Issue by lepolau** [darktable-org/darktable#3044] opened 2019-09-29 13:18 UTC
I use the equalizer module by adjusting the fusion level.
I set the level to 0.300 for example, When I return to this photo after processing another one (or after closing the software), the fusion level setting is displayed at 1.0. However, no change in the display of the image, this evolution is apparently not taken into account in the processing.
This problem is also visible at a preset, the recorded value (e. g. 0.300) is not displayed as it is when the preset is recalled. It appears at 1.00, but the processing performed on the photo apparently corresponds to the recorded value of 0.300.

I use darktable 2.6.2 on debian 10

**Comment by junkyardsparkle** [comment] 2019-09-29 20:27
This is [the intended behavior](https://darktable.gitlab.io/doc/en/correction_group.html#equalizer) for that slider. The changes to the nodes produced by moving it are saved, but its own value is not.

It's possible that this could be made somehow clearer in the GUI, so maybe you want to edit this issue to be a request for that.

**Comment by lepolau** [comment] 2019-09-30 06:45
Thank you for your quick answer, and sorry I had to miss reading this paragraph in the manual.
I think above all that it was a bug, the operation is not necessarily the one you expect from a standard parameter. But since that's your intention, I'll try to get used to it first.
Thank you and congratulations for the work done.

**Closed** 2019-09-30 06:45 UTC
