### ISSUE TITLE
Canon EOS 2000D

### ISSUE THREAD

**Issue by justcomplaining** [darktable-org/darktable#3994] opened 2020-01-02 09:04 UTC
Sample files:
https://drive.google.com/file/d/1CFt8tiz389boluoZobXLMiBk_1P2Zvbj/view?usp=sharing

**Comment by LebedevRI** [comment] 2020-01-02 12:10
Duplicate of 68da658fdcaf12ea590ee070353407cc10074907.
That camera is supported for a while now.

**Closed by LebedevRI** 2020-01-02 12:10 UTC
Labels: camera-support, duplicate

**Comment by justcomplaining** [comment] 2020-01-02 13:47
Ok, then https://www.darktable.org/resources/camera-support/ is not up to date and I haven't figured out how to find the denoise profiles... I vaguely remember it to be working in the past, maybe it's an issue of the windows build.
