### ISSUE TITLE
RAW images are darkend in darkroom after displaying a JPG

### ISSUE THREAD

**Issue by robMate** [darktable-org/darktable#6272] opened 2020-09-11 23:07 UTC
**Describe the bug**

After opening a JPG in Darkroom all afterwards selected RAWs (CR2, RAF in my case) are darkened and can not be rescued. My only fix so far is to delete the .config/darktable folder and the xmp files. If no JPG gets selected, the RAW images behave as expected.

**To Reproduce**
1. Import images
2. Double-click a JPG to open it in darkroom
3. Open a RAW file by double-clicking on one in the filmstrip on the bottom.
4. The raw is way to dark and can not be fixed with modules

**Expected behavior**
The Raw file should be displayed normally.

**Screenshots**
Images are imported and a JPG is opened in darkroom, RAWs are displayed normal (highlighted with a red border).
![jpg_selected_raw_look_normal](https://user-images.githubusercontent.com/5657121/92977787-316d4700-f48e-11ea-8add-10bc12acde1a.png)
Both RAW images were opened by double-clicking them and are dark now.
![raws_dark_after_jpg](https://user-images.githubusercontent.com/5657121/92979791-1bfb1b80-f494-11ea-8f59-d2d9083d0654.png)

Example images RAW/JPG and xmp files
[IMG_0824.CR2.zip](https://github.com/darktable-org/darktable/files/5211776/IMG_0824.CR2.zip)
[_MG_0071.CR2.zip](https://github.com/darktable-org/darktable/files/5211774/_MG_0071.CR2.zip)
[jpgs_and_xmp.zip](https://github.com/darktable-org/darktable/files/5211775/jpgs_and_xmp.zip)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - Package: https://www.archlinux.org/packages/community/x86_64/darktable/
 - OS: Manjaro 19.02
 - OpenCL support: not available

**Additional context**

- It changes only raw images, JPG behave as expected
- If no JPG gets selected at one point RAWs don't get darkened. 
- After deleting the config-dir and xmp files the raw images are displayed normal again.

**Comment by jenshannoschwalm** [comment] 2020-09-11 23:29
A duplicate of many other issues like #6202, has been fixed already in master.

**Closed** 2020-09-12 06:27 UTC
