### ISSUE TITLE
Sony DNG converted raw only TCA supported with embedded lens correction

### ISSUE THREAD

**Issue by dtrtuser** [darktable-org/darktable#15647] opened 2023-11-13 16:31 UTC
### Describe the bug

DNG converted ARW raw files only get partial lens correction with default Embedded Metadata lens correction: the image is corrected for TCA but distortion and vignetting are ignored.

The original raw file is properly corrected for all 3 (TCA, Distortion and Vignetting) when using Embedded Metadata lens correction.

Tested with Sony A7 IV and A7R II images. I tried to upload a sample image but it is too big for github.

I am using DNG Converter version 14.2.0.1028 with the following conversion preferences:

![DNG_Converter_Params](https://github.com/darktable-org/darktable/assets/99996405/137a5e20-6810-47bd-9f28-0e58c5f8bf82)

![lens_correction](https://github.com/darktable-org/darktable/assets/99996405/e835c8ba-26ad-4d4e-9810-75fdd1580e84)

### Steps to reproduce

Convert Sony ARW (raw) file to DNG using Adobe DNG converter (for cameras/lens that support Embedded Metadata).
Import in darktable.
Go to darkroom and turn on "lens correction". The default correction method is "embedded metadata".
TCA correction is applied, but distortion and vignetting correction are ignored.

### Expected behavior

Expecting to have all 3 lens corrections applied: TCA, Distortion and Vignetting

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce RTX 3050

**Comment by kmilos** [comment] 2023-11-13 16:57
Possible duplicate of https://github.com/darktable-org/darktable/issues/15574?

**Comment by dtrtuser** [comment] 2023-11-14 23:03
> Possible duplicate of #15574?

It could be. Please let me know if I should close this one.

**Closed** 2024-11-09 00:21 UTC
Labels: no-issue-activity
