### ISSUE TITLE
Sony A6700 support

### ISSUE THREAD

**Issue by kishkaru** [darktable-org/darktable#15014] opened 2023-08-06 00:36 UTC
Opening issue to add support for the newly released **Sony A6700** (Sony ILCE-6700), released on Aug 3, 2023.

The camera has a new 26 MP (6192 x 4128) APS-C sensor, so likely won't map correctly to the existing A6600 format (24MP).
The A6700 writes RAW as Lossless Compressed or Compressed. It does not support Uncompressed RAW.

I was going to add RAW samples to https://raw.pixls.us/, but looks like someone else beat me to it.
Let me know if more samples are needed than the provided ones.

**Comment by kmilos** [comment] 2023-08-06 08:04
Duplicate of https://github.com/darktable-org/rawspeed/issues/507

**Comment by kishkaru** [comment] 2023-08-06 08:08
Whoops, my bad. I didn't search in the rawspeed repo. Closing this one.

**Comment by kishkaru** [comment] 2023-08-06 08:09
Whoops, my bad. I didn't search in the rawspeed repo. Closing this one.

**Closed** 2023-08-28 19:53 UTC
Labels: scope: camera support
