### ISSUE TITLE
Unable to select an option from hamburger menu (Mac, multiple monitors)

### ISSUE THREAD

**Issue by andreypudov** [darktable-org/darktable#14861] opened 2023-07-10 15:57 UTC
### Describe the bug

I have many presets, but I am unable to select any except first four of them.

### Steps to reproduce

1. Go to Color menu
2. Enable Color Calibration
3. Try to select a preset
4. You will not be able to select a preset that is behind short listshortlist

### Logfile | Screenshot | Screencast

![image](https://github.com/darktable-org/darktable/assets/9801177/e9e1de16-66aa-41e7-8a63-2b392a794bad)

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1

### What OS are you using?

Mac

### What is the version of your OS?

13.4 (22F66)

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment] 2023-07-10 18:49
Likely duplicate of #14278. Do you have multiple monitors?  Can you scroll using arrow keys?

**Comment by andreypudov** [comment] 2023-07-11 09:45
> Likely duplicate of #14278. Do you have multiple monitors? Can you scroll using arrow keys?

No, arrow keys don't work as well.

**Comment by Nilvus** [comment] 2023-07-11 18:21
So as a duplicate, better to close it and continue discussion on #14278. No need to have 2 issues for same one (and visibly a tricky one).

**Closed by Nilvus** 2023-07-11 18:21 UTC
Labels: duplicate, scope: UI, scope: macos support
