### ISSUE TITLE
Crop tool enhancement

### ISSUE THREAD

**Issue by JohannMaierhofer** [darktable-org/darktable#14294] opened 2023-04-22 08:20 UTC
I sometimes crop images and like to fit them to TV resolutions like HD, Full HD or UHD. Sometimes I also like to keep the aspect ratio but like to have the hight of the image to match the Full HD or UHD hight. For this I need to be able to create the correct size in pixels.

With current crop tool this is very complicated. The sliders in the menu do not help. I need to change the size of the crop area with the mouse. But with mouse it is also not very easy to set a dedicated size, as with moving the mouse, the size of the crop area changes rapidly.

My proposal would be to have a second tab in the crop module that allows to set four values directly. These are the x/y coordinates of the left upper corner of the crop area and the the width/hight of the crop area. This would make the setting of a dedicated size much easier.

As a further improvement could be some default templates for setting e.g. Full HD or UHD crop sizes. But this is not so important as I can create such templates also myself.

**Comment by ralfbrown** [comment] 2023-04-22 12:52
dt uses resolution-independent coordinates internally, since that's the only way to get the same cropping regardless of zoom level or downsampling (navigation preview or "trade speed for accuracy" peformance preference).  If you need a specific pixel size, set it in export options.

Duplicate of #12177, #10837, #7847, and probably others.

**Closed** 2023-04-22 12:52 UTC
Labels: duplicate

**Comment by JohannMaierhofer** [comment] 2023-04-22 15:38
I accept if you say that this enhancement is not possible.
I just don't understand your proposal. I do not want to rescale the image to a certain size. I want to extract an area of the image with a certain size and keep it during export without rescaling.
Today I can do this by adapting the crop rectangle with the mouse. DT displays the pixel size of the rectangle while I move the mouse. It is just a lot of mouse moving to match the desired size. 
Thus if it is possible to calculate the pixel size of the selected area from the internal coordinates it should be also possible to enter the size and translate it into the internal coordinates.
But as I am doing this not very often I can live with my current way to crop.

**Comment by spaceChRiS** [comment] 2023-04-23 14:46
@JohannMaierhofer, this is a request that comes from time to time that I really do not understand. But maybe you can explain it such that it eventually makes sense …

Let's assume I have an image in an aspect ratio as it comes from the camera/scanner/whatever, let's say about 4:3 ratio:
![image](https://user-images.githubusercontent.com/16524534/233845735-b3c9d2e5-f10c-4987-bbe6-75219aa82ab1.png)

Now I want to prepare it for appearing in a movie, so I want it in full HD resolution. The aspect ratio is 16:9, so I crop it to that aspect ratio by removing as little “content” of my image:
![image](https://user-images.githubusercontent.com/16524534/233846437-3da87a23-2007-4c62-bada-626c01e948f0.png)

If I would crop to exact 1920 px by 1080 px, I would e.g. get this:
![image](https://user-images.githubusercontent.com/16524534/233846501-c01d9e3b-d08b-486f-9f6a-18732004f126.png)

Here I am a bit lost: Why would one want such a crop? There must be a proper use case as this was requested a couple of times in the past, but for now, nobody was able to show a real use case. Maybe @JohannMaierhofer, you can help out and make me understand? Really, I want to understand.

**Comment by JohannMaierhofer** [comment] 2023-04-23 16:19
Hello, the scenario where I use this is to extend the focal length of the lens. I take images of animals that are far away. Even with the longest focal length e.g. 300mm an animal may be visible small on the image. As I am just interested to have the animal visible, I crop the image to keep the animal but removing the parts around it.
The 24M pixel of the image allow to select a subset with sufficient resolution. A crop with the third of the original area extends the focal length thus by a factor of 2, e.g. from the 300mm to 600mm.
But I do not want to crop too much so that when I view the image at e.g. 100% on a PC monitor or TV it does not have to get upscaled by the PC or TV.
Thus depending on how small the animal appears on the original image I may crop to UHD or even Full HD resolution.
I hope this explains why I use do this kind of crop.
In the meantime I found an easy was for me. I simply store a preset of crops to a certain size and then I simply apply the preset and then move the crop area to the place that I want to crop. The preset itself sets the desired size.

**Comment by spaceChRiS** [comment] 2023-04-23 20:23
> the scenario where I use this

This sounds to me that the feature you want is rather a minimum crop dimension than an exact crop dimension, to not accidentally crop too far. While up-scaling is not so uncommon, especially in video production, I can at least understand the rationale behind your request. Maybe it's worth to do another feature request regarding a minimum crop pixel dimension, at least to get some feedback by the devs if such a feature would be something fitting into darktable.

Regarding the limits you are using, I want to mention that the pixel dimension is only loosely related to the actual resolution of an image. So even if you are cropping to exact 1920 px  by 1080 px, the actual resolution may be much lower such that you get a blurry picture. On the other hand, depending on the actual viewing situation, upscaling in combination with sharpening might be a reasonable approach even for lower pixel dimensions, as you and not the PC or TV where the image is viewn have full control over the upscaling. Therefore, I doubt that there is one minimum size that fits all circumstances. Still I see value in an optional minimum dimension.

**Comment by JohannMaierhofer** [comment] 2023-04-24 08:21
Yes, a minimum dimension feature would be a good alternative solution.
I think that there may be another use case where this could be useful. Instead of viewing the image at PC or TV someone may want to create a paper copy of the cropped area e.g. as photo or for a magazine. In that case you want a certain minimum resolution e.g. 300 pixel per inch for a good quality print. If you know the size of the image on paper you multiply with the minimum resolution and you get a minimum pixel size.
A potential feature in DT may even allow to enter either a minimum pixel size or minimum resolution together with the paper size. Then you do not have to do the translation by your own.

**Comment by parafin** [comment] 2023-04-24 10:32
I think you should just judge the result - just because DPI is high, doesn't mean there are any details in there (bad lens, bad focus, too many MP in the sensor and so on). Furthermore you may want to crop a little bit more and upscale a little to get a better composition. No reason to artificially limit yourself this way. If you use lens correction, all pixels are interpolated anyway. And demosaic itself is also interpolation.

**Comment by ralfbrown** [comment] 2023-04-24 12:57
> If you use lens correction, all pixels are interpolated anyway. And demosaic itself is also interpolation.

Also if you do any rotation or perspective correction.
