### ISSUE TITLE
Severe display issue on some portrait images (generated cache issue from darktable)

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#5269] opened 2020-06-01 07:50 UTC
**Describe the bug**
Portrait images could sometimes be shown with pixel offset display. This result in strange image. See 2 examples below:

**To Reproduce**
A way to reproduce (but not reproducible all times) is to display images in culling mode (I use always 2 images at the same time) and after displaying landscapes images, showing new portrait images could result on this artefact.

But, I can reproduce near all the times this issue by rotate to the left a portrait image in lighttable (so with left rotate button in selected images module on the right panel.

This issue has been discussed with @AlicVB and @aurelienpierre yesterday and could be related to  a Gdk issue when rotating the image. What's strange is I never reproduce the issue if rotating on the right.

By discussing with @AlicVB, we find that's probably be a cache generating issue has all portrait images displayed this way have cache images with the issue.

**Expected behavior**
Always have images displayed correctly on portrait ratio.

**Screenshots**
![issue2](https://user-images.githubusercontent.com/45535283/83387385-ece10280-a3ec-11ea-81f4-86f0530f92a1.png)
![issue1](https://user-images.githubusercontent.com/45535283/83387388-ee122f80-a3ec-11ea-8f57-56037d8cdb29.png)

And a generated jpg picked up on cache (mipmap 3 here but could be picked up same way on all generated mipmaps cache):
![22538](https://user-images.githubusercontent.com/45535283/83387437-0aae6780-a3ed-11ea-843f-9c304e15edf0.jpg)

**Platform (please complete the following information):**
 - Darktable Version: one of the last master
- No OpenCL compatible card so CPU work only here.

**Comment by AlicVB** [comment] 2020-06-01 13:17
As @aurelienpierre has mentioned on the French chat, it's very probably a rounding error in the exporting size. I know that there has been recent change on this area @TurboGit ?
Here, it's like we have an image with a final with set set to `w` although we write only `w-1` pixels for each lines... so the first pixel of the second line is placed at the end of the first line, and so on...

@Nilvus : just to be sure, can you launch dt with `-d cache` and see where from where the mipmap of the rotated image is computed when you click on the rotation button ? You should have something like : `[mipmap_cache] generate mip 5 for image 356 from scratch` (remember the id of the corresponding image before) Thanks !

Note that in the test process, I've found another issue with rotate button (#5274) but I don't think they are related

**Comment by jenshannoschwalm** [comment] 2020-06-01 14:52
When debugging such there is -d imageio recently introduced giving information for export.

I don't think it's a scaling problem, there is probably a related problem mentioned by @TurboGit in #5232 . I guess the pipeline data line length is wrong somehow.

**Comment by TurboGit** [comment] 2020-06-01 16:18
Arg!!! Very bad regression. Ok, I'll try to reproduce and then found the wrong commit.

**Comment by TurboGit** [comment] 2020-06-01 16:27
@Nilvus : Cannot reproduce for now. One question can you reproduce this "bad" effect at export time ?

**Comment by TurboGit** [comment] 2020-06-01 16:56
Ok, found a way to reproduce:
- I use a collection with 200 pictures
- I set 13 thumbs per row
- I delete the dev history to force a recomputation of the thumbs

I have generally 4 to 6 wrong thumbs.

The first wrong commit is 6fd4eb7ddf0817c324efbdfd78801299ad8a91.

@jenshannoschwalm : this is your last commit to try fixing again this infamous issue :( Can you have a look ? Hope you'll be able to reproduce otherwise I can test on my side as I can reproduce. Let me know.

**Comment by jenshannoschwalm** [comment] 2020-06-01 17:28
There are some questions for me. 
1. Is it always the same images or somewhat random?
2. If you can reproduce on the same image again, b) does this change when applying a crop? b) does the issue persist when changing the lighttable size? c) could you share the -d imageio log please

3. If the issue is sometimes present for an image and sometimes not, again the -d imageio log would be good.

Will have time tomorrow to get into this... Still at work having very bad days.

**Comment by TurboGit** [comment] 2020-06-01 17:51
For 1 : No not always the same.
For 2: : don't know as my procedure is to delete the history stack.
For 3 : I'll see if I can find some patterns

**Comment by TurboGit** [comment] 2020-06-01 17:56
One more thing : it happens only for vertical pictures.

**Comment by TurboGit** [comment] 2020-06-01 18:04
Really strange:

Full redraw if thumbs on my collection (200 picture), this thumb was not properly generated:

`35,611454 [dt_imageio_export] imgid 238, pipe 4924x7374, range 180x110 --> exact 1, upscale 0, corrected 1, scale 0,014781665, size 74x110`

I then selected only this image on the lighttable and delete the history stack just for this one:

`143,841616 [dt_imageio_export] imgid 238, pipe 4924x7374, range 180x110 --> exact 1, upscale 0, corrected 1, scale 0,014781665, size 74x110`

So it looks like the issue depends on some other rendering being done before which match the report from @Nilvus.

**Comment by jenshannoschwalm** [comment] 2020-06-01 18:40
Could it be `iscale` in `dt_mipmap_buffer_t` ?

**Comment by TurboGit** [comment] 2020-06-01 19:05
I found one issue, iscropped is set to 1 (TRUE) for all vertical images.

**Comment by TurboGit** [comment] 2020-06-01 19:48
@jenshannoschwalm : I have pushed #5277 which is probably a workaround more than a fix. Can you comment on this PR?

**Comment by TurboGit** [comment] 2020-06-01 20:37
@jenshannoschwalm : Note that this is suspicious to me (my patch kill it for thumbs export):

```
      if(exact_size && !thumbnail_export)
      {
        scale = fmin(fmin((double)(width-1) / (double)(pipe.processed_width), max_scale),
                     fmin((double)(height-1) / (double)(pipe.processed_height), max_scale));
      }
```
In case width is initialize with pipe.processed_width and height with pipe.processed_height, the sale will be close to 1 but very little less. (max_scale is 1.0). So the rounding errors could come from this. What do you think ?

**Comment by jenshannoschwalm** [comment] 2020-06-01 21:36
I thought about this. Indeed the "scaling correction" can be wrong if width<height. Not just smaller than 1. I think I understand the issue, will try tomorrow and open even another pr if I get it working.

**Comment by tomaszg7** [comment] 2020-06-01 23:20
I hit the same problem with some images. I see it however mostly in exported files. However I noticed a related problem (occurring on the same photo) when I enable OpenCL: then I either get all black frame or weird bright border on the bottom right part of photo. I saw the problem at commit 0d825a4ceb42a97fc2c365c55bf4bb8ee6714f2c and just pulled 05c4c39a51f716412ccd699a42bc9763f3427e0e and it is still there (both shearing and bloom versions). It disappears when I turn off Orientation module.

Attaching downscaled sample of photo:
![artifact](https://user-images.githubusercontent.com/16195733/83463481-6c62e600-a46e-11ea-96f6-40a9921aea92.jpg)

**Comment by Nilvus** [comment] 2020-06-03 07:29
@TurboGit or @jenshannoschwalm: this issue is closed but you end it by talking about a possible related issue remaining (with some specific size). Do you want me to let this issue open or better close it?

**Comment by TurboGit** [comment] 2020-06-03 07:53
Let's close this one. We would need another one I suppose.

**Closed** 2020-06-03 08:19 UTC
Labels: bug: pending, difficulty: hard, priority: high, scope: image processing

**Comment by jenshannoschwalm** [comment] 2020-06-03 08:30
Yes. It's a different problem, atm I think that the cropping parameters lead to a modified pipeline size, probably a rounding error there.
