### ISSUE TITLE
Denoise profiled: central image goes black

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#7906] opened 2021-01-17 13:02 UTC
DT current git master, nVidia 1060 GPU

This seems to be a corner case in denoise profile, the central image goes black in specific conditions.
To reproduce:

- open an image in darkroom
- apply a preset including wavelet, for example the built-in preset "wavelets: chroma only"
- change mode to "non-local means" or "non-local means auto"
- see the central image going black

The issue is observed in both Linux and Windows, but only with OpenCL active.
It is not related to the recent fixes in denoise profiled, as it happens also in 3.4

**Comment by Nilvus** [comment] 2021-01-17 20:33
I can reproduce too. @rawfiner: maybe you will have an idea there?

**Comment by TurboGit** [comment] 2021-01-18 11:03
@Nilvus : I'm removing **understood: clear** as this is intended to use when we know what is going on and how to fix.

**Comment by Nilvus** [comment] 2021-01-18 11:11
> @Nilvus : I'm removing **understood: clear** as this is intended to use when we know what is going on and how to fix.

Ok

**Comment by TurboGit** [comment] 2021-01-18 11:22
Probably because the preset is initialized with 0 for all parameters:

```
  dt_iop_denoiseprofile_params_t p;
  memset(&p, 0, sizeof(p));
```

And so when we come back from wavelet to another mode we get wrong rendering. The whole structure in the preset must be initialized with default parameters.

**Comment by TurboGit** [comment] 2021-01-18 11:26
Should be fixed.

**Closed by TurboGit** 2021-01-18 11:26 UTC
Labels: bug: pending, priority: high, reproduce: confirmed

**Comment by Nilvus** [comment] 2021-01-18 11:38
> Should be fixed.

Indeed, it is. Thanks.

**Comment by rawfiner** [comment] 2021-01-18 11:43
Thank you @TurboGit !
