### ISSUE TITLE
Problem in Downloading

### ISSUE THREAD

**Issue by GitParitosh** [darktable-org/darktable#14934] opened 2023-07-24 04:14 UTC
### Describe the bug

Upon Downloading on Mac OS Ventura 13.4.1, the following messages popup.
![WhatsApp Image 2023-07-24 at 09 18 15](https://github.com/darktable-org/darktable/assets/135813176/b605c6be-fa75-426a-868e-59f32d97d351)
![WhatsApp Image 2023-07-24 at 09 26 30](https://github.com/darktable-org/darktable/assets/135813176/3c01eb86-be22-4088-a157-7e1f3a8ee5fd)

### Steps to reproduce

1. Download Application from website
2. attempt to open application 

### Expected behavior

open

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2-xarm64

### What OS are you using?

Mac

### What is the version of your OS?

macOS Ventura 13.4.1

### Are you using OpenCL GPU in darktable?

I dont know

**Comment by zisoft** [comment] 2023-07-24 05:01
duplicate of #14746 

Please search before opening new issues

**Comment by MStraeten** [comment] 2023-07-24 05:02
Have a look at https://www.darktable.org/install/
and next time search before posting the same topic again …

**Comment by MStraeten** [comment] 2023-07-24 05:02
Duplicate

**Closed** 2023-07-24 05:01 UTC
Labels: scope: macos support
