### ISSUE TITLE
crtl+z after compress history stack in darkroom resets history stack

### ISSUE THREAD

**Issue by MStraeten** [darktable-org/darktable#3855] opened 2019-12-24 21:20 UTC
After compress history stack in darkroom ctrl+z doesn't undo this but discards the history stack.
this behaviour doesn't occur in lighttable.

**To Reproduce**
1. open edited mage in dakroom
2. Type ctrl+z
3. history stack remains unchanged
4. Click "compress history stack"
5. Type ctrl+z
6. History stack is discarded

**Expected behavior**
if the history stack can't be restored it should be unchanged, not discarded.

**Platform (please complete the following information):**
 - OS: OSX
 - Version 3.0 but also current master 
 - OpenCL reproducible with active and inactive

**Comment by pphotography** [comment] 2019-12-24 22:20
Can confirm that with 3.1.0~git10.af8b11a17 on Ubuntu 18.04.

But when I press CTRL-Z again or CTRL-Y the history stack comes back.

**Comment by johnny-bit** [comment] 2020-12-21 22:42
The issue is present in 3.2.1, however it is not present in current master (3.5.0+111~g3cca160f9)

I'm Closing since I can't replicate on master using replication steps. Probably fixed by 55bb0c3 or some other work around #6015

If the issue is still present for you - please commend and I'll reopen so we can investigate!

**Closed by johnny-bit** 2020-12-21 22:42 UTC
Labels: bug: fixed

**Comment by MStraeten** [comment] 2020-12-22 09:52
confirmed

**Comment by johnny-bit** [comment] 2020-12-22 10:34
Umm... 
confirmed = "the issue isn't present on master so this can stay closed"
or
confirmed = "the issue is present still on master, please reopen"
?

**Comment by MStraeten** [comment] 2020-12-22 12:42
confirmed your first sentence - not present. So it can stay closes
