### ISSUE TITLE
Lighttable not refreshing

### ISSUE THREAD

**Issue by mir07** [darktable-org/darktable#5922] opened 2020-08-11 15:35 UTC
When opening darktable lighttable shows correct all pictures in film role but configure thumbnails overlay with mouse hover does not work - only no or permanent works. Another issue is opening an image in darkroom and returning to lighttable will keep the image from darkroom behind images from film role messing up the work space in lighttable completely. Whether the 2 issues is related or not is difficult to say. I have attached a screenshot of both issues.

darktable: 3.2.1
OS: Debian Unstable
DE: Mate 1.24
GPU: 2 Nvidia. One GTX 1050 and the other is GTX 1050 Ti
Configured to use opencl with default and this in darktablerc:
opencl_device_priority=!GeForce GTX 1050,*/!GeForce GTX 1050 Ti,*/GeForce GTX 1050 Ti,*/GeForce GTX 1050 Ti,*

![lighttable_thumbnails_problem](https://user-images.githubusercontent.com/2576455/89917331-f78ff300-dbf8-11ea-82d8-914d205880b4.png)
![lighttable_back_from_darkroom](https://user-images.githubusercontent.com/2576455/89917349-fced3d80-dbf8-11ea-940e-bacc4b39e923.png)

**Comment by mir07** [comment] 2020-08-11 15:38
Forgot to mention that before upgrading from 3.0.2 these problems were not there.

**Comment by mir07** [comment] 2020-08-11 16:16
I have just tried changing DE to XFCE, it did not make any difference. Disable or enable compositor makes no difference as well.

**Comment by esperlu** [comment] 2020-08-11 16:18
v 3.2.1

Can not reproduce that behaviour on a Debian stable with single GPU (GeForce GTX 970). Could that be related to your multiple GPU configuration?

**Comment by mir07** [comment] 2020-08-11 16:22
> v 3.2.1
> 
> Can not reproduce that behaviour on a Debian stable with single GPU (GeForce GTX 970). Could that be related to your multiple GPU configuration?

I could be that but using multiple GPU's has worked before 3.2.1.

**Comment by kofa73** [comment] 2020-08-11 16:52
Have you tried disabling OpenCL? If that fixes it, you can try investigating whether it has to do with the multi-GPU setup. If it does not, it has nothing to do with OpenCL, multi-cards or not.

**Comment by mir07** [comment] 2020-08-11 17:05
> Have you tried disabling OpenCL? If that fixes it, you can try investigating whether it has to do with the multi-GPU setup. If it does not, it has nothing to do with OpenCL, multi-cards or not.

I have tried darktable --disable-opencl. It did not make any difference.

**Comment by mir07** [comment] 2020-08-11 21:36
It gets very viered. If I remove my darktablerc file and starts darktable everything works and when a close darktable it creates a darktablerc file. Then one would expect darktable would work in exactly the same way when you start darktable again? But the next time I start darktable it behaves as describe in this bug. darktablerc file
[darktablerc.txt](https://github.com/darktable-org/darktable/files/5059585/darktablerc.txt)

 attached

**Comment by mir07** [comment] 2020-08-11 22:05
BTW. When I run darktable from the command line I see a lot of these lines in the console:
[_ioppr_check_rules] found rule flip clipping module clipping (16) is before flip (20) image 460 (dt_dev_read_history_no_image end)
Could this be a hint?

**Comment by mir07** [comment] 2020-08-11 22:18
I might also add that I have build darktable from git as well:
3.2.x branch: Same behavior.
master branch: Same behavior.

**Comment by morsch** [comment] 2020-08-12 17:13
I have the same issue. Ubuntu 20.04, GeForce GTX 1080 (just the one), driver version 440.100.

The last viewed darkroom image shows through in the lighttable view. Happens both with OpenCL enabled and disabled.

I have one observation to add: In lighttable view, making the window as small as possible and back to the regular size gets rid of the "background" image in the resized areas. Or to put it another way, if I set the darktable application window to take up a small part of the screen, open an image in darkroom, return to lighttable and then maximise the window, only a small part of the lighttable will have the image as the background.

**Comment by morsch** [comment] 2020-08-12 17:18
Oh, I think I figured it out: Switching to a different theme fixed the issue. I had made some HiDPI theming tweaks in the previous version (which may be superflous now). I removed my `themes` folder (in `~/.config/darktable`), and now the default darktable theme does not exhibit the issue anymore either.

**Comment by TurboGit** [comment] 2020-08-12 17:33
Indeed and "old" theme won't be properly supported in new dt. Hopefully this weird issue is fully resolved for everyone.

**Comment by mir07** [comment] 2020-08-12 18:31
> Indeed and "old" theme won't be properly supported in new dt. Hopefully this weird issue is fully resolved for everyone.

I can confirm that removing all css files from ~/.config/darktable solves the issue. It seems that darktable the first time you start a new version darktable uses the default *.css files and first after initial start begins using the user specific *.css files in
~/.config/darktable. Perhaps the initial upgrade process should make a backup of the themes folder and nuke the user themes files in ~/.config/darktable/themes?

**Comment by mmhh76** [comment] 2020-08-13 21:06
I also have similar problem with lighttable. First I thought it was problem with my compiled developer version Darktable 3.3 and with the compiled version of lensfun 0.3.95. I compiled in Ubuntu 20.04. I also have Windows 10 on this computer, and on WIndows I am using the stable version of Darktable 3.2.1. Installed it in Windows like you usually do. But the same problem is in 3.2.1. So I guess no problem with my compiled version nor Ubuntu nor drivers.

The problem I have is that when you are in darkroom and then go back to lighttable, it will be grey. You can't see any photos in lighttable. But only if you have all your photos on one line, from the left to the right. So let say you have 5 photos and you choose to show 5 photos on one line, and you open up the last image on that line, then the lighttable will be grey(after you go back from darkroom). I don't know if this problem is in Darktable 3.0.2. But the problem is there now. I tried to turn off OpenCL, tried to change buffer size and other settings, but still same problem. The only thing that works is to go from "file manager" to "culling" or "zoomable light table".

**Comment by kofa73** [comment] 2020-08-13 21:21
I've also seen that (grey lighttable), but clicking on the filmstrip in the collect module was a quick workaround. I think that is a different issue.

**Comment by AlicVB** [comment] 2020-08-20 10:42
@mmhh76 : indeed, this seems a different isue that this one. Can you check if it's covered by one of the remaining issues with zoomable lightable ? And if not open a new issue ?
Thanks !

Speaking of the current issue, if I understand well, this was a due to some old user defined css files. In this case, there's nothing we can do.... So I'm closing.

**Closed by AlicVB** 2020-08-20 10:42 UTC
