### ISSUE TITLE
New iop_order: add way to choose/keep module order on created style and copy/paste options

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4261] opened 2020-02-09 15:43 UTC
**Describe the bug**
@TurboGit: I actually rework some old images, with old legacy order. I created a default style with 3.0 order and default modules I applied automatically on new imported images. When I open an old image on darkroom which have legacy order, then I applied my default style with 3.0 order. Modules are correctly applied but remains in legacy order. I always need to select new 3.0 module order manually.

**Expected behavior**
Also applying module order with a style.

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0 git 584
 - OS: Ubuntu 19.10

**Comment by TurboGit** [comment] 2020-02-09 16:16
@Nilvus : This issue was reported by @aurelienpierre IIRC, but I was not able to reproduce. Any step by step way to reproduce this 100% of the time ?

**Comment by Nilvus** [comment] 2020-02-09 17:18
> @Nilvus : This issue was reported by @aurelienpierre IIRC, but I was not able to reproduce. Any step by step way to reproduce this 100% of the time ?

First step is to have :
- an old image with a different order (custom or legacy one).
- and a style with a 3.0 modules order with new modules

On my old legacy images, I have some for example with local contrast below filmic (so before in pipeline). On my style, local contrast is above (so after in pipeline) filmic RVB, like it is on 3.0 module order. Applying this style on legacy images and you have this issue : local contrast remains below filmic/filmic RVB and doesn't move above.

If needed, I could send you style, RAW and legacy XMP on framateam.

**Comment by TurboGit** [comment] 2020-02-09 18:29
I see this is not the issue discussed in fact. The current behavior is the expected one. Indeed currently when we copy/paste the iop-order of the target image is kept as-is.

That being said we can have different strategy as I said in the announce for the merging of the new iop-order implementation. We need to think of what can be provided as strategy ? What makes sense ? How to have a UI to convey the behavioral control, etc. From there we will be able to enhance the current support !

**Comment by Nilvus** [comment] 2020-02-09 19:08
> I see this is not the issue discussed in fact. The current behavior is the expected one. Indeed currently when we copy/paste the iop-order of the target image is kept as-is.
> 
> That being said we can have different strategy as I said in the announce for the merging of the new iop-order implementation. We need to think of what can be provided as strategy ? What makes sense ? How to have a UI to convey the behavioral control, etc. From there we will be able to enhance the current support !

So this is more a feature request. I think that the simple and best solution is just to consider that module order has to be saved (and applied) on a created style.

Just a thing : when we create a style, we want to apply modules we choose to render something, and by that we know that module order is important. So if I want to apply a style, I also want his order, so change the image order. Or If I want a different order, I will create another style with the module order I want.

If we talk about a copy/paste action, I think that's quite the same but maybe in some cases, I can understand that image module order needs to be keep. But why not simply add an option on copy/paste dialog windows on lighttable to select which order we want : source image or target one ?

And I would say that adding a default preference on preferences window to applied legacy, custom or 3.0 order for example on all these actions would be good (of course, with the possibility to overwritten last ideas).

**Comment by TurboGit** [comment] 2020-02-09 19:15
I have set this as enhancement request. I think I agree with all you wrote. I'll try to write down some design goal to see how this feels to others.

**Comment by TurboGit** [comment] 2020-02-09 19:17
>  If I created a style is to have modules applied and its order.

This is the most difficult one. How did you create a style ? Just by copying some modes on one image ? But you can also add later some other modules from another image with possibly a different order version ? So at the end, what is the order of a style ?

**Comment by Nilvus** [comment] 2020-02-09 19:18
> > If I created a style is to have modules applied and its order.
> 
> This is the most difficult one. How did you create a style ? Just by copying some modes on one image ? But you can also add later some other modules from another image with possibly a different order version ? So at the end, what is the order of a style ?

I applied manually modules and order on an image. Just to be sure on what I have, order I want and render I want. Then, I create the style from that image.

**Comment by TurboGit** [comment] 2020-02-09 19:19
So as for copy/paste we probably want the iop-order version to be selected when creating or modifying a style.

**Comment by Nilvus** [comment] 2020-02-09 19:19
> So as for copy/paste we probably want the iop-order version to be selected when creating or modifying a style.

Yes

**Comment by TurboGit** [comment] 2020-02-09 19:20
>  Then, I create the style from that image.

But as I said you can later modify the style. Select a style and another picture in lighttable and you can update the style by replacing or adding new modules. This other image may not have the same iop-order as the image initially used to create it.

**Comment by TurboGit** [comment] 2020-02-09 19:21
At the end we agree, we want a way to select the iop-order version when creating or modifying a style.

**Comment by TurboGit** [comment] 2020-02-09 19:22
But we really want to be sure we cover all the cases!

**Comment by Nilvus** [comment] 2020-02-09 19:24
> > Then, I create the style from that image.
> 
> But as I said you can later modify the style. Select a style and another picture in lighttable and you can update the style by replacing or adding new modules. This other image may not have the same iop-order as the image initially used to create it.

Yes, I know. That's indeed the difficult part. Or maybe, just have an option to select different cases (like module order options on darkroom or something similar). For example :
- Original style order and new applied modules (same as actual custom option)
- Only original one
- 3.0 one

Of course, I don't have think a lot here, just ideas that needs to be improved. And I agree, we want a way to choose iop-order and cover all the cases.

**Comment by Nilvus** [comment] 2020-02-09 19:26
Or consider that replacing/adding new modules needs to be done in an order, so have an option to keep the order : 3.0 one or target or source image or source style.

**Comment by AlicVB** [comment] 2020-02-09 20:49
> But as I said you can later modify the style. Select a style and another picture in lighttable and you can update the style by replacing or adding new modules. This other image may not have the same iop-order as the image initially used to create it.

Does it make sens to update a style from an image with a different module order ? If not, we can also just kindly inform user that it's not possible and abort...
If one want absolutely that feature, there's always the possibility to apply the style first and update it after.

**Comment by GrahamByrnes** [comment] 2020-02-09 22:33
> Does it make sens to update a style from an image with a different module order ? 

If I understand, yes it does: I edited quite a lot of images under 3.0.0rc1, since that was when I moved into dt. In most cases, I dragged the channel mixer to before the base-curve. However, where this was saved in a style, the order was automatically swapped back to the then-default. So if I had kept a style from then, it would be useful to have it take the new (3.0.0) default. As it happens, I didn't save any styles, but it's possible...

**Comment by junkyardsparkle** [comment] 2020-02-10 05:30
> Does it make sens to update a style from an image with a different module order ?

It absolutely does for many use cases. I think this will probably end up being most important for people using modules like the 3DLUT which really need to be in the right place depending on the LUT being used, etc.

Anyway, my thoughts on implementation are: just include a checkbox in the dialogs for style creation and copy/paste similar (but maybe distinct?) to the ones for selecting all other modules. If selected, current ordering is included, otherwise not. Same for updating styles from the lighttable view. One thing to keep in mind is that while a source image for copy or style creation may have a custom order, *that order may or may not be relevant to the specific modules selected for inclusion*... so it really makes sense to let the user select in each case.

**Comment by GrahamByrnes** [comment] 2020-02-10 09:03
(Although it may be a marginal issue and there is a case for not over-populating the UI with buttons & check-boxes).

**Comment by Nilvus** [comment] 2020-02-10 16:31
> (Although it may be a marginal issue and there is a case for not over-populating the UI with buttons & check-boxes).

It's not a major issue of course but I will not say that a marginal one. With the recent possibility of changing order and the fact that order have impact on images, it's important to have possibility to apply the order. About old images processed again with new order, yes this will be limited in time, but not for the new 3.0 possibility to change order.

Here, the idea is not to add lot of buttons but quite one option (with just a dropdown list for example in one or two places).

**Comment by TurboGit** [comment] 2020-02-10 17:57
First step : #4271 

Next step is to support style & module order. This will require modifying the database schema.

**Comment by TurboGit** [comment] 2020-02-11 15:17
The PR is ready for testing.

**Comment by TurboGit** [comment] 2020-03-04 17:42
Closing as implemented and merged.

**Closed by TurboGit** 2020-03-04 17:42 UTC
Labels: difficulty: average, feature: enhancement, scope: codebase
