### ISSUE TITLE
[Culling] add row-by-row srcolling, eg. shift+scroll

### ISSUE THREAD

**Issue by AxelG-DE** [darktable-org/darktable#2565] opened 2019-05-12 16:40 UTC
**Is your feature request related to a problem? Please describe.**
This Feature Request is acc. to the discussions in the (very nice, btw) PR #2539 from @AlicVB 

I would like to use culling in two scenarios:
- before editing I select 1* and 2* prior edit, only 2* will get edited
- after editing they are 3* and now I select 4* and 5*. That is the 2nd attempt, using culling

Current git master's culling mode, once it is used in >=4 pics view, the scrolling or better to say, what you see/experience during scrolling, can be very confusing, when you have different aspect ratio in your selection (3:2, 2:3, 2:1, 1:1) after editing.

Depending on the aspect ratio, sometimes the 
- **first row** shows picture n°1,2 and 
- **second row** n°3;4 or it is

next moment/scroll
- **first row** shows maybe n°3,4,5, and
- **second row** n°6

next moment/scroll
- yet again different

So it is really hard (maybe only for me) to have a clear impression, what you are looking at (it is a bit better, when you also have the filmstrip in mind)

**Describe the solution you'd like**
I would like to scroll row by row, when pressing _Shift_ during scrolling

So, Shift-Scroll would than do:
- n°1;2 out of sight
- **first row** n°3,4
- **second row** n°5,6 _and so forth_

Here it is getting tricky, because;
- either it forces to omit those one-pic in a line or
- even other sortings, e.g. in 6-pic view (4+2) will be difficult or 
- further tricky with odd numbers of view, like 5-pic, 7-pic

**Describe alternatives you've considered**
As I have described [here on #2539](https://github.com/darktable-org/darktable/pull/2539#issuecomment-493652698), I would be already satisfied, if the number of pics per row would not change while scrolling. It should always stay on 2 by 2 (if zoom=4). Currently it sometimes jump to 3pics in first row and 1 pic in 2nd row. That finally makes the left most pic of first row jump to middle pic in first row. Very confusing in my opinion

**Additional context**
I know, my dreams may jeopardize or make things extremely complex, when now the exposure and culling might be on the way to be merged/fusioned

**Comment by AxelG-DE** [comment] 2019-05-18 21:41
@AlicVB 
So for the sort order I have ammended her on "alternatives". Is that o.k., or you would need that really in a separate issue?

**Comment by AlicVB** [comment] 2019-05-18 21:53
no pb.
But I'm not convinced we should change how images sizes and positions are computed... Let's wait for other opinions...
By the way (and even if it didn't solves totally your issue) have you seen that you now can use pageup/pagedown shortcut to navigate in culling ?

**Comment by AxelG-DE** [comment] 2019-05-19 05:33
I saw page up and page down now. It does here for me exactly the same than mouse wheel.

I am surprised, you are not convinced to change the size and computation. 
Did you try a set of pics (let's say ~40) with some portraits, which have more ~4 landscape pics in between and set the zoom=4? If no, plesae try by your self :)

The more I see it, the more I consider this a bug, I can really see no sense to suddenly switch three  in a row, when the portrait comes to 1st row :smile:

**Comment by AxelG-DE** [comment] 2019-05-19 10:48
May I attach some screenshots, where I think the order 3-1 makes sense, and where I think it makes no sense...

makes sense:
![Screenshot_20190519_114727](https://user-images.githubusercontent.com/49004103/57980993-89c73c80-7a32-11e9-805c-a814188a870b.png)

makes no sense:
![Screenshot_20190519_120724](https://user-images.githubusercontent.com/49004103/57981004-9a77b280-7a32-11e9-912f-b79856a10af2.png)
![Screenshot_20190518_082148](https://user-images.githubusercontent.com/49004103/57981016-b9764480-7a32-11e9-947e-e401d513f0b3.png)
would make sense, if 2nd row would be soomed propperly
![Screenshot_20190519_120755](https://user-images.githubusercontent.com/49004103/57981012-ae231900-7a32-11e9-8dcb-417b3a29675c.png)

**Comment by AlicVB** [comment] 2019-05-19 10:54
@AxelG-DE : 
- pageup/pagedown shouldn't do the same than mouse wheel... if you see images 2,3,4,5, it should jump to 6,7,8,9 and so one... Just tested here and it seems to works as expected...
- For the second point, it's more tricky than that : with the actual behavior, images placements are done to let maximum space to each images. If you test it with 4 portraits, for example, they will be put on 1 line (depending of you screen ratio) because, it's more efficient like that. In contrary, if you show 3 panos, they will be in 1 column, etc... So either we lost this (and it would be a pity, that's why I'm "not convinced") either we stay like that.
Note that There may be cases where the computation fail (I've faced some) We'll have to fix them ! (I've to admit I don't fully understand the computation logic atm)

**Comment by AlicVB** [comment] 2019-05-19 11:00
@AxelG-DE :  msg crossing... So you seems to face the cases where computation fail :( We'll have to fix them at some point (I'm currently working on another point, so it'll have to wait a little, except if someone else want to take it)

**Comment by AxelG-DE** [comment] 2019-05-19 14:51
@AlicVB
My bad! I puzzled with arrow down. Embarrassed... 

Anyhow, I get the feeling, we are at the same page now, with those 3pics in 1st and one in 2nd row. 

Not urgent, once we fixed this (understood, is tricky) we can close here, I guess.

**Comment by AlicVB** [comment] 2019-05-19 17:58
@oexler : help... :)
if you have a moment, can you have a look at this ? There seems to be cases where the computation of size/positions of images fail... and I don't understand what the code is doing here. It's original code from your (really great) exposé PR. It now start here in the code : https://github.com/darktable-org/darktable/blob/c57a56ca090ef9c1f9bf43dc44b260d1098814e6/src/views/lighttable.c#L2075
Thanks !

**Comment by AxelG-DE** [comment] 2019-06-16 11:58
@AlicVB 

I wonder, what I found today is related to this topic here, or a different new issue...

I just noticed, when I go thru a collection with culling and zoom = 1, _some_ pictures show in different size (pic smaller, bigger border).

![Screenshot_20190616_134604](https://user-images.githubusercontent.com/49004103/59563756-677b0b80-903e-11e9-96a8-4b0291b0b436.png)


- that is a cropped one.
- so I move to darkroom, touch the crop one more time (without actual adjusting) and afterwards back to lighttable it looks like all the others (pic bigger, smaller border):

![Screenshot_20190616_134646](https://user-images.githubusercontent.com/49004103/59563759-6c3fbf80-903e-11e9-9667-dbbf9c84836a.png)

**Comment by AlicVB** [comment] 2019-06-16 12:15
at first sight, I would say it's more a ratio computation error...
If you still have some image with this problem, can you check in lighttable what is their ratio value, before the problem and after ? (you should be able to guess the value using using the collection module with ratio filter and try-error)
Thanks

**Comment by AxelG-DE** [comment] 2019-06-16 12:39
yes I still have some
I'm not sure I got you right....
What do you want me to see in the collection module and how to do?

In my opinion, they re 3:2 before and after. Also above, when you check the corners, you can see, there is no change in aspect ratio...

As I said, easily I got you wrong :)

**Comment by AxelG-DE** [comment] 2019-06-16 12:44
If you ask me, this IS related to our issue here.

Why I say so,
If an effected picture is in position one of four (1/4) or 2/4, then I have that funny 3pics in one row and one in the second row, regardless they are all in landscape and not like above a portrait orientation...

**Comment by AlicVB** [comment] 2019-06-16 12:55
Great that you still have some problematic images :)
dt doesn't recompute ratio each time. The value is stored in the database. Here, I think your last error is due to dt recording a wrong aspect ratio in some cases. It would produce exactly that if for example dt as registered as "too square" or "too panoramic" ratio.
To know which ratio is registered for an image, I don't think there's an easy way. We either have to read directly the database or to (mis-)use the collection module : 
- reset the actual collection
- use the ratio filter
- try each value, until you get the image you want

(if you know how to read sqlite databases, ratio is store in the image table)

**Comment by AxelG-DE** [comment] 2019-06-16 15:48
I'm not an expert in fetching that info from database but if someone tells me the correct sqlite3 command....

**Comment by AlicVB** [comment] 2019-06-16 17:06
something like `select aspect_ratio from images where id=??;` (replace `??` by the id of the image)
if you manage to get the values, please post aspect_ratio values before (when the image still has the problem) and after (once you change something in darkroom and everything is ok)
To be sure, please retrieve the values with dt closed.
Thanks a lot for your help

**Comment by AxelG-DE** [comment] 2019-06-16 18:51
@AlicVB 

first of all, it is my turn to show gratitude :)

Sqlitestudio did the trick for me...

You have been very correct!

The pics I checked, they are all from my Olympus EM5, which has a "natural" aspect ratio of 4:3. As I prefer the 3:2, I crop respectively.

So the picture in question had 1.3 in aspect_ratio (dt was closed) and after I touched that crop field again (not really moved anything there), it shows now the correct 1.5

So indeed on my NEF-files from Nikon we may not find this I assume....

I admit, that case is not related to the issue above (which still puzzles me), now the question is, where does this "mistake" of aspect ratio comes from and is there a chance to do anything?

**Comment by AlicVB** [comment] 2019-06-16 19:39
Great !
So now we "only" need to find why dt sometimes register wrong value for aspect ratio :)
One question : how do you crop the images from 4:3 to 3:2 ?
- manually inside darkroom ?
- with a preset/style in darkroom ?
- with a style in lighttable ?
- directly inside the camera with some settings ?

**Comment by AxelG-DE** [comment] 2019-06-16 19:56
Manually inside darkroom, always.
Sometimes I drag that crop window a bit, sometimes I merely touch it, so that clicking  on the modules name will take the action

**Comment by AlicVB** [comment] 2019-06-16 20:16
ok thanks
next question (again) : can you reproduce the problem ? I'm currently trying to play with crop & rotate, but I can't reproduce so far ...

**Comment by AxelG-DE** [comment] 2019-06-16 21:08
I still have some pics with that issue left.

You mean, I should take not edited photos, crop them and see, whether they do the same things? What are you aiming at?

I can try but now need to go to sleep :-)

Cheers
 Axel

**Comment by AxelG-DE** [comment] 2019-06-20 09:37
@AlicVB 

I did crop several pictures, which initial aspect_ratio was 1.3 to 3:2=1.5
- the cropss I did, was in several manners (just crop 3:2 in center, draw smaller crop windows)
- After 1st crop they stay on 1.3
- After I closed sqlitestudio and went back into dt (always closed in beteween), and cropped again, some even with free aspect ratio or 1:1, then they suddenly change the aspect ratio in the data base
- to me that seems pretty repeatable
- is it possible, my database even not fully corrupted, from time to time does not allow dt to store the values inside? If so, could this be a reason for my preformance issues I have reported at other place (on purpose not linking now)
- if you need sample RAW pics in 4:3 from my Oly, I could send to you by Smash but need an email addy....

**Comment by AlicVB** [comment] 2019-06-26 16:36
@AxelG-DE : I've only managed to reproduce your issue once in many many try.
That said I have maybe a fix for that here : https://github.com/AlicVB/darktable/tree/aspect_ratio_fix I don't know if you are able to test it. If not, ask me, I'll explain how to do that manually, the change is quite small.

**Comment by AxelG-DE** [comment] 2019-06-26 18:07
@AlicVB

thanks a lot for staying tuned. 

At the moment we have 34°C in the EVENING in shade....... Way tooooooo much for a north European. No way to go to top floor to the office and start the PC. Forgive me.

Next week I'll leave for vaca. There's a risk this topic may sleep until 20th July :-)

**Comment by AlicVB** [comment] 2019-06-26 19:59
@AxelG-DE : no problem, very hot here too, but the computer is in the coolest place of the house ;)
and holidays are coming too... Anyway, this can wait a little !

**Comment by AlicVB** [comment] 2019-06-28 20:14
@AxelG-DE : ok, I think I've found the problem of the latest bug (the one with aspect ratio, not the main bug of this issue) It has just been pushed to master... Please test when you are back, but no hurry...

**Comment by AxelG-DE** [comment] 2019-06-29 08:58
@AlicVB 
I tested and I can confirm, aspect ratio is recorded correctly, now.
You are great! Thank you so much...

Now I am dreaming of getting above issue solved, that the number of picture per row do not change, without reason (from end-user's point of view ;->> )

**Comment by AxelG-DE** [comment] 2019-07-02 18:39
Here is the one and only situation, where a jump to 3+1 makes sense...
![Screenshot_20190702_203509](https://user-images.githubusercontent.com/49004103/60537541-10955780-9d09-11e9-8d2d-03eb1a8494d5.png)

**Comment by AxelG-DE** [comment] 2019-07-19 22:08
@AlicVB 
did you work on this topic?
I am on 2.7.0+1540~g5e84e1520 and suddenly the behaviour is **way better** now. I could accept to close this case.

**Comment by AxelG-DE** [comment] 2019-10-05 11:19
@AlicVB 
just a humble update, it still works like this :smile: 
![Screenshot_20191005_131445](https://user-images.githubusercontent.com/49004103/66254147-a6120e80-e772-11e9-927e-2dfed35d0b9d.png)

**Comment by AlicVB** [comment] 2019-10-05 12:36
yes, I know :(
The problem is that I don't really understand the image placement / sizing algorithm. I've asked @oexler, the original author, for help, with no answer atm...

**Comment by AxelG-DE** [comment] 2019-10-05 13:32
I hope for the best, as this is really annoying :-/

Thanks for everything! :slightly_smiling_face:

**Comment by AxelG-DE** [comment] 2020-05-21 04:20
I just checked, this issue still persists

**Comment by johnny-bit** [comment] 2021-05-21 14:46
How does it work now?

**Comment by Solarer** [comment] 2023-07-25 22:11
Working on a fix for the thumbnail placement but it will not include the row-scrolling feature

**Comment by Solarer** [comment] 2023-07-26 07:53
Working on a fix for the thumbnail placement but it will not include the row-scrolling feature

**Comment by Solarer** [comment] 2023-07-28 20:42
Hello @AxelG-DE, I found the issue of the thumbnail placement and fixed it. You can try it and see if it works. Also I applied some other placement improvements that are more noticable if you combine images with very different aspect ratios.

I did not address your request to scrolling `row by row` because I think it would not work well. Think about scrolling with 5 thumbs in a 3,2 setup. First you would get 3,2,3,2,3,2 and so on but what if you have a wider image and the 3 thumbs don't fit in a row? You would get 3,2 -> 2,1,2 and now you are stuck forever with a lonely picture in a row. Next iteration will be 1,2,2 and then again 2,2,1 even if we could display all thumbs in two rows again, we are stuck with 3 rows and one of them with a single image.

Can you get your usecase covered by using color label and then use filemanager layout while filtering out all images you do not need?

**Comment by Solarer** [comment] 2023-09-11 14:39
I propose to close this feature request.

I was able to fix all alignment issues of images with different aspect ratios in culling via pr #14966 and #15197 but I do not think it is feasible to implement the requested row-by-row scrolling without running into weird edge cases (see my previous post).
It is simpler to apply a color tag, filter out all other images and use file manager layout on the remaining images. There it is possible to scroll row by row.

**Comment by victoryforce** [comment] 2023-09-17 13:27
> I propose to close this feature request.

@AxelG-DE Do you agree with this? Can we close this FR?

**Comment by AxelG-DE** [comment] 2023-10-27 16:34
@Solarer sorry I did not feedback to you. Somehow I oversaw your comments, donno why. I will check right away!
thanks to @victoryforce who pinged me on IRC

**Comment by AxelG-DE** [comment] 2023-10-27 17:02
@Solarer 
- I am fine to drop the scrolling row by row, as I understand your view
- I do not fully get your point about color labels. I do sort the pictures by star rating, (very good = 4*, brilliant=5*) how can an additional colour label help?
- most importantly, I still found e.g. 6pics, that it goes 3/3 3/3 3/3 and suddenly 4/2 4/2 3/3 3/3 and also I found one weird scenario, it went 3/3 3/3 3/3 2/2/2 3/3 3/3 2/2/2 3/3 3/3....
pity is, this set of pics I cannot make public e.g. via screen cast. Either I find other pics with the same behaviour, or we need to find a way, I send a screen cast to you personally (e.g. we could exchange emails via PM on IRC, or is there another smart way? AFAIK there is no PM here on github, is it?)

**Comment by Solarer** [comment] 2023-10-28 19:50
> how can an additional colour label help?

Culling allows you to view a subset of your images. If you select some images and then enter culling, you will only see those images. Filemanager Layout has always a fixed number of images per row.
You could combine these features by applying a temporary color label to some images and then filtering everything else out in Filemanager view. That is a little hack to somehow fullfil your row-by-row scrolling. But it is a little bit of a hassle.

>  I still found e.g. 6pics, that ...

Can you turn them completely dark and then export as jpeg? I should not be able to recover anything from the jpeg if you make them very dark. You could also just draw black color over them with gimp or paint. I only need the right resolution to test what the issue is.

**Comment by AxelG-DE** [comment] 2023-10-29 07:53
actually I am planning to make a screenrecording, so that you can see, what happens. A jpg export won't help, I guess. But it is a concert I shot in Paris, where cameras where actually not permitted :), hence I cannot publish them. So still appreciate a way how to exchange email addy. Are you member of pixls.us, then I can PM you there.

**Comment by Solarer** [comment] 2023-10-29 12:03
I created an account.

We can try with the screen recording but images would make it easier. As I said, you can turn them completely black and then share the blackened images. I do not need to see what is on them.

**Comment by AxelG-DE** [comment] 2023-11-01 20:18
So I did send you an email, however as explained, this video can be published I think and so I post it here as well, so others can see as well, what bothers me :-)

Please only use for analysis, not for re-share


https://github.com/darktable-org/darktable/assets/49004103/62f1f0a3-df21-42fb-829f-9c514bd8b05f

**Comment by Solarer** [comment] 2023-11-01 21:15
Thanks for providing the video, Axel. It helped a lot in understanding what you mean.

As you mentioned in your mail, it does indeed work as intended. The algorithm tries to places the images in a way so that they can be as big as possible - for easier inspection and comparison. Every time you scroll, the best positioning will be reevaluated. The algorithm does not care how images were displayed before and therefore the positioning can change a lot if you have mixed aspect ratios.
This was not introduced by my recent code change but maybe it is now more noticeable.
The "official" use case for culling is to compare a selection of similar images and not to scroll through a full collection. Similar images usually have the same aspect ratio - so the process is less disorienting (you would also scroll through fewer images).

Can you try the following 2 ideas and see if one of them works for you?
1. Limit culling to one or two images and enable filmstrip at the bottom. You can make the filmstrip as big as you want to have a perfect overview of previous and next images.
![image](https://github.com/darktable-org/darktable/assets/2805109/7c110bc1-111c-4e37-8e2f-2cacf57e5529)

2. Use the first mode (Filemanager) and limit to 3 or 2 images per row. You said in your mail that you would be fine if you always see three images even if that means that placement is not ideal. That is precisely what Filemanager layout does for you.
![image](https://github.com/darktable-org/darktable/assets/2805109/afa5a4f4-b55e-4301-8ad1-5a127c58b794)

**Comment by AxelG-DE** [comment] 2023-11-02 18:08
Dear @Solarer, 

thank you for your feedback and your willingness to dig into this. All your comments and proposals they are valid and would work.

My video maybe appears like I purposely or carelessly disregarded the intention of culling (no worries, I do not feel offended :slightly_smiling_face:  ). Not intentionally but there might be a little truth in it.

- I do shoot timelapse and wide open (35/1.4 on FX). The latter forces you to shoot many to have a sharp one, at least on DSLR due to inaccuracies of phase-AF. 
- So I did start from many pics with similar content
- More than one cam in one set makes the mix, which finally made me run into above topic
- But I also admit, culling became for me, what the name intended, using it to sort out the pictures I shot (because I remember, the proposals you made, they also lead into some ugly things) and hence I started to behave ignorant to the initial intention of culling otherwise it would merely have the ctrl-x-mode, not also the x-mode, where I can scroll thru the whole colelction :-) 


The split 4/2 to me looks odd, no matter what reasoning behind. I think here the algo is really doing something odd.

![grafik](https://github.com/darktable-org/darktable/assets/49004103/02d26e13-60dc-4d4b-acae-57aa4eb2f842)


-- BTW I think the help text, when mouse hover on the two culling icons in darkroom, they are puzzled. The one I can scroll is called fixed and the one which I cannot scroll is called dynamic. Confusing :-)

![grafik](https://github.com/darktable-org/darktable/assets/49004103/40d3fc68-bcc1-4a5f-b7c1-9f69e46e7bad)

**Comment by Solarer** [comment] 2023-11-02 20:28
> The split 4/2 to me looks odd, no matter what reasoning behind

It does. But I think the "issue" here is that the first 3 images of the first row are almost as wide as the images of row 2. Because of that the placement of image no.4  would be equally bad in both rows - so I place the image in row one to have it out of the way. Otherwise the next row might not fit either.

I know there are some cases like this where a human would place the pictures a little different. But to mimic that logic I would need to loop over all images multiple times and try a bunch of placements to find the best one. It could be done but slower computers might have an issue with that. And bad performance when scrolling is really annoying.

> fixed and dynamic

Those two words refer to the number of images displayed, not the ability to scroll 😉 
I get your point but I did not pick the names. Feel free to suggest an alternative in a new issue. 🙂

**Comment by Solarer** [comment] 2023-11-02 20:29
The overlay looks indeed weird. Can you open a new issue for that? It is too big and takes space away from the actual image

**Comment by AxelG-DE** [comment] 2023-11-02 21:11
So finally we will close here? I will not argue against :-)

**Comment by AxelG-DE** [comment] 2023-11-02 21:18
> The overlay looks indeed weird. Can you open a new issue for that? It is too big and takes space away from the actual image

Done #15556

**Closed** 2024-10-28 00:23 UTC
Labels: feature: enhancement, difficulty: hard, no-issue-activity
