### ISSUE TITLE
Inverted or incorrect colours in filmstrip and main image

### ISSUE THREAD

**Issue by tduell** [darktable-org/darktable#7404] opened 2020-12-22 22:06 UTC
**Describe the bug**

I am experiencing image display issues with builds of release-3.5.0-111-g3cca160f9 and release-3.5.0-127-g54fc5b4dd on Fedora 33.
With these builds, when I start darktable some of the images in the filmstrip appear to have inverted colours, e.g. all light areas such as sky are shown black. Selecting one of these images the full image is also displayed this way.
If I revert to a build of release-3.5.0-80-g94892dc6d, when started the filmstrip still shows the affected images in inverted colours, but when those images are selected the full display has correct colours and the filmstrip image is corrected.

**To Reproduce**
With builds of either release-3.5.0-111-g3cca160f9 or release-3.5.0-127-g54fc5b4dd

1. start darktable, some images in the filmstrip show inverted colours
2. select an affected image
3. the full image display is also shown inverted
4. revert to build release-3.5.0-80-g94892dc6d
5. start darktable
6. images in filmstrip shown with inverted colours in dt versions noted above are still shown inverted
7. select an affected image
8. the full display image is shown in correct colours and that image in the filmstrip has its colurs corrected.
-->

**Expected behavior**
Image colours to displayed correctly in filmstrip and main display

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: noted above
 - OS: Linux, Fedora 33
 -  No OpenCL
 - Nvidia GTX 750Ti, nouvou driver

**Additional context**

**Comment by johnny-bit** [comment] 2020-12-22 23:13
This is obviously unwanted behaviour but I can't replicate at all (i use opencl, haven't checked the CPU path)

Can you please:
1. Try with empty config & cache dirs? including empty db
2. what are your iinput/working/output profiles?
3. can you start with `-d all` (obviously with clean confgin) and gdb output in case there's some backtrace available?

Since it may be related to recent optimization work like eg #7391:
- Do you compile yourself? If so - what are your compiler & compilation flags?
- If you can replicate issue on newer commits but not on older, you have great range for bisect, you can try help analyze source of issues like described here: https://github.com/darktable-org/darktable/wiki#finding-bug-causes 9in your case `git bad 3cca160f9` + `git good 94892dc6d`

**Comment by tduell** [comment] 2020-12-23 00:47
Hello Hubert,

On Tue, 2020-12-22 at 15:14 -0800, Hubert Kowalski wrote:
> This is obviously unwanted behaviour but I can't replicate at all (i use
> opencl, haven't checked the CPU path)

Some of your questions or requests are beyond my ken, so sorry to have to ask
for clarification

> Can you please:
>    1. Try with empty config & cache dirs? including empty db

Do you mean the darktable dirs in my .config and .cache dirs?

>    2. what are your iinput/working/output profiles?

sRGB

>    3. can you start with -d all (obviously with clean confgin) and gdb output
> in case there's some backtrace available?

OK, I'll try that if a test of the effect of the haze module doesn't help (see
below).

> Since it may be related to recent optimization work like eg #7391:
>  * Do you compile yourself? If so - what are your compiler & compilation
> flags?

I do compile myself, using Fedora's rpmbuild and the .spec file developed by
Germano Massullo.
A bit more research is required by me at the moment to be sure about compiler
and flags used as the .spec file specifies both clang and GCC are required, but
not immediately obvious to me which is actually being used for the build.

>  * If you can replicate issue on newer commits but not on older, you have
> great range for bisect, you can try help analyze source of issues like
> described here:      
> https://github.com/darktable-org/darktable/wiki#finding-bug-causes 9in your
> case git bad 3cca160f9 + git good 94892dc6d

OK, I looked at that, and see it's related to the haze module which I do use on
some images. I'll install one of the bad behaving builds and see if turning off
the haze module has any effect.
I don't have a good command of git, always building from current master.
Managing to get a source from a specific commit will require some research.

Hopefully this is of some help, and that I can soon satisfy your other requests.

Cheers,
-- 
Terry Duell <tduell@iinet.net.au>

**Comment by tduell** [comment] 2020-12-23 01:02
I have now installed one of the bad behaving builds (release-3.5.0-127-g54fc5b4dd) and see that switching the haze module off for images that show the inverted colours solves the problem...i.e. without haze module the image colours are displayed correctly.

**Comment by ralfbrown** [comment] 2020-12-23 04:24
Duplicate of #7391, hopefully fixed by #7406 (but I can't replicate the problem on my system, so I'm not sure that will fix it).

**Comment by johnny-bit** [comment] 2020-12-23 06:24
Duplicate of #7391

**Closed** 2020-12-23 06:24 UTC
