### ISSUE TITLE
Resize Image Information module

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#6641] opened 2020-10-26 11:32 UTC
The Image Information module only uses a small portion of the left hand side panel (on a 1920x1080 monitor), yet forces you to scroll to see pertinent information.

Would it be feasible to either:
a) Let it consume all available left hand side real estate(1), or
b) add a resize handle to the bottom of the module which would allow the user to extend its depth?

(1) this would of course depend on the value set by "expand a single module at a time"

Cheers.

**Comment by elstoc** [comment] 2020-10-26 11:53
@brucewilliamsphotography: you can already resize the image information module with `Ctrl+scroll`

**Comment by brucewilliamsphotography** [comment] 2020-10-26 12:17
I can't seem to get that to work. Tried over the bottom edge, as well as
over the module title panel.
Cheers,
Bruce Williams
------------------------------
brucewilliamsphotography.com
shuttersincpodcast.com
------------------------------
e-mail <studio@brucewilliamsphotography.com> | Twitter
<http://twitter.com/@audio2u> | LinkedIn
<http://au.linkedin.com/pub/bruce-williams/1/318/489> | Facebook
<http://www.facebook.com/audio2u>
------------------------------

**Comment by elstoc** [comment] 2020-10-26 12:21
You've managed to find the two places it doesn't work! Just hover over the centre of the module and scroll. If it's not working please let us know what your current version and OS is.

**Comment by johnny-bit** [comment] 2020-11-26 11:07
I've just checked to make sure I have it right.
So image information module is resizable without a problem, but i found it very reliable to first click on any information and then use ctrl+scroll on the module - that way it resizes ALWAYS :)

If you're still having issues with current master, please tell us right away, especially what's your version, os and window manager are (sometimes window maangers can interfere a bit or there may be some weirdo gtk bug). I hope you no longer have any issue and can close this issue :)

**Comment by brucewilliamsphotography** [comment] 2020-11-26 11:48
I can get the info panel to scroll in order to see the information which is hidden.
But what I was asking for was a deeper module i.e. using more screen real estate for that module.
Some folks here have suggested that a ctrl+scroll will allow the module to expand, but that has not been my experience.
I'm running Linux Mint 19.3 with Cinnamon DE v4.4.8
Linux kernel is 5.4.0-55-generic
Tried both darktable 3.2.1, and 3.3.0 build 1217.
System is AMD Ryzen 2700x, 32GB RAM, Gigabyte GTX1050Ti 4GB card

**Comment by elstoc** [comment] 2020-11-26 12:08
Hmm works fine for me on 3.2. Where are you hovering the mouse when you ctrl+scroll? You need to hover your mouse over the actual content (i.e. the box that actually shows all of the image information)

**Comment by johnny-bit** [comment] 2020-11-26 12:12
Well - I just tried on 3.3.0+1787~g24e7212c1 in the following way: click in image info module, keeping mouse there ctrl+scroll and it enlarges/shrinks the module appropriately.
Interestingly enough I don't have this problem on dt 3.2.1 neither... 

The ctrl+scroll in module is implemented for many modules with PR #6408 by @dterrahe in generic way, so if one place doesn't work that means more won't work. Can you try with most recent master you can get and try ctrl+scroll on history, colorpicker, masks manager, duplicate manager, recent collections, snapshots & styles and see which one works and which doesn't? Generally it should work on ALL of those.

**Comment by johnny-bit** [comment] 2020-11-26 12:42
@brucewilliamsphotography - can you try for now checking the sizes you have configured in darktablerc? `grep windowheight darktablerc` ?

**Comment by brucewilliamsphotography** [comment] 2020-11-26 20:39
Here's the output of that grep command (dt 3.2.1)....
plugins/darkroom/colorpicker/windowheight=200
plugins/darkroom/duplicate/windowheight=400
plugins/darkroom/history/windowheight=1000
plugins/darkroom/snapshots/windowheight=200
plugins/lighttable/collect/windowheight=
plugins/lighttable/metadata_view/windowheight=285
plugins/lighttable/recentcollect/windowheight=1000
plugins/lighttable/style/windowheight=400

**Comment by brucewilliamsphotography** [comment] 2020-11-26 20:46
Actually, now I'm concerned that that info has come from a directory that isn't where my current config lives!
How can I be certain which is my current config directory?

**Comment by dterrahe** [comment] 2020-11-26 21:02
You could look at the file timestamps?

This looks like it is from master, not 3.2.1, correct?

**Comment by johnny-bit** [comment] 2020-11-26 21:54
@brucewilliamsphotography - interestlingly it looks like it did change settings as witout touching those usually none are in config by default.

as a "workaround" for image information module, can you change
`plugins/lighttable/metadata_view/windowheight` line to say
```
plugins/lighttable/metadata_view/windowheight=1000
```
?

**Comment by hlecleme** [comment] 2020-11-28 11:10
I could reproduce this issue. I'm not exactly sure what is happening. When debugging it, it seems that `event->delta_y` is always 0 when scrolling, so there is no change to the height of the widget. The values stored in the configuration are the default ones, probably set when the `_scroll_wrap_resize` is called (e.g. on widget draw).

- Darktable master e65a8d2aab323eb6d213b8936ecf8bdd7aced231
- OS: Ubuntu 18.04 with Gtk 3.22.30

When applying the following patch, the change of widget height using Ctrl+Scroll seems to work, but I'm not at all sure that it still works in the configurations or Gtk versions (as I don't exactly know when/how the `delta_y` should be used).

```
diff --git a/src/gui/gtk.c b/src/gui/gtk.c
index ad9e39235..15c6047f7 100644
--- a/src/gui/gtk.c
+++ b/src/gui/gtk.c
@@ -3155,7 +3155,25 @@ static gboolean _scroll_wrap_scroll(GtkScrolledWindow *sw, GdkEventScroll *event
 
   if(event->state & GDK_CONTROL_MASK)
   {
-    dt_conf_set_int(config_str, dt_conf_get_int(config_str) + increment*event->delta_y);
+    int delta = 0;
+    switch(event->direction)
+    {
+      case GDK_SCROLL_UP:
+        delta = -1;
+        break;
+      case GDK_SCROLL_DOWN:
+        delta = 1;
+        break;
+      case GDK_SCROLL_SMOOTH:
+        delta = (int)event->delta_y;
+        break;
+      case GDK_SCROLL_LEFT:
+      case GDK_SCROLL_RIGHT:
+      default:
+        break;
+    }
+
+    dt_conf_set_int(config_str, dt_conf_get_int(config_str) + increment*delta);
 
     _scroll_wrap_resize(w, NULL, config_str);
   }
```

**Comment by johnny-bit** [comment] 2020-11-28 11:36
Thanks @hlecleme ! that gives me an idea!

**Comment by johnny-bit** [comment] 2020-11-28 11:49
Well... PR #7108 should help it :) essentially is the same as proposed by @hlecleme's but using the way recommended by gtk manual ;)

**Closed** 2020-11-29 19:32 UTC
Labels: no-issue-activity
