### ISSUE TITLE
crash when using dynamic tool shortcut in lighttable view

### ISSUE THREAD

**Issue by grubernd** [darktable-org/darktable#6657] opened 2020-10-27 19:33 UTC
**Describe the bug**
when a shortcut assigned to any "dynamic" entity is used in lighttable view (file manager, culling) after darkroom was used at least once, dt crashes instantly. if you only ever stay in lighttable, no crash will happen.

although the dynamic tools control shortcuts are meant to be held down, a single keystroke will make the crash happen.

**To Reproduce**
1. cleaned out ~/.config/darktable (not important)
2. assigned shortcut to dynamic tool control, e.g. image operations -- exposure -- exposure -- dynamic : E -- but any other _dynamic_ will do the same
3. import one image (doesn't matter how many)
3. **change once from lighttable to darkroom** - this is a crucial step
4. change back to lighttable
5. use keyboard shortcut .. crash

**Platform (please complete the following information):**
 - Darktable Version: darktable_3.2.1-1.1_amd64.deb
 - OS: BunsenLabs Lithium (debian 10)

**Comment by elstoc** [comment] 2020-10-28 13:17
I can reproduce this on 3.2 but not on current master so it looks like it may have been fixed by #6584

**Comment by johnny-bit** [comment] 2020-12-15 18:25
Not replicable on current master (seems like indeed fixed by #6584 :smile:)

**Closed by johnny-bit** 2020-12-15 18:25 UTC
Labels: no-issue-activity
