### ISSUE TITLE
Seach module with "fra" shows framing and crop and rotate

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7134] opened 2020-11-30 07:35 UTC
Current master.

Reason why crop and rotate shows up when search module has text "fra"?

![image](https://user-images.githubusercontent.com/1119439/100580757-89d51780-330c-11eb-8dc6-f7e16a80cf9c.png)

**Comment by parafin** [comment] 2020-11-30 09:10
Because it has a keyword "reFRAme". Duplicate of #6902.

**Closed by parafin** 2020-11-30 09:10 UTC
