### ISSUE TITLE
Filmstrip behaviour in Maps

### ISSUE THREAD

**Issue by brucewilliamsphotography** [darktable-org/darktable#7355] opened 2020-12-19 06:03 UTC
I'm currently looking at 3.3.0 build 2078, on Linux Mint 19.3.

The filmstrip behaviour in the Maps module is not consistent with other parts of the app.
Try the following:

* in Lighttable view, you select a handful of images
* switch to Maps module
* select any OTHER image in your filmstrip

The images which were selected in the Lighttable view remain selected.
The image you just clicked on does NOT get selected.

Unless I misunderstand the Maps module, the previously selected images should become deselected, and the newly clicked-on image should become the only image selected.

As it is, you have to switch back to the Lighttable view in order to change the range of selected images before you drop them on the map.

**Comment by Nilvus** [comment] 2020-12-19 07:53
Duplicate of #7000, #7020 and #7264.
Please read 3.2 article to understand how it's work in filmstrip and so close this issue. The behavior could be discussed on #7000 issue.

**Comment by johnny-bit** [comment] 2020-12-19 09:35
I agree it takes a bit of getting used to... #7000 can be used as a hub to figure out the best approach, in the mean time there's https://darktable-org.github.io/dtdocs/module-reference/utility-modules/shared/filmstrip/ with this bit:

> If you wish to select multiple images in the filmstrip, use Alt+click to select the first image and then Ctrl+click to add to or remove images from the selection or Shift+click select a range of images.

So to sum up: "Not the best way, but at least there is a way..." I wonder what would be the best way so that filmstrip is universal across all views in behaviour, since in darkroom it's normal to work on single image and in map it's normal to work on group of images...

**Closed by johnny-bit** 2020-12-19 09:35 UTC
Labels: duplicate, scope: UI
