### ISSUE TITLE
Nikon Z2 2

### ISSUE THREAD

**Issue by Jacques0573** [darktable-org/darktable#8348] opened 2021-02-27 17:42 UTC
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment] 2021-02-27 17:48
Duplicate of #6898 / #7282.
These cameras are supported in dt master, i'm not sure what's the status for stable releases.

**Closed by LebedevRI** 2021-02-27 17:48 UTC
Labels: scope: camera support

**Comment by johnny-bit** [comment] 2021-02-28 20:49
Support for those cameras will be present in 3.6 release coming july.

**Comment by Jacques0573** [comment] 2021-02-28 22:08
Merci pour la réponse

Le dim. 28 févr. 2021 à 21:49, Hubert Kowalski <notifications@github.com> a
écrit :
