### ISSUE TITLE
Move Integration Tests

### ISSUE THREAD

**Issue by elstoc** [darktable-org/darktable#7198] opened 2020-12-05 10:14 UTC
In the past year or so the addition of integration tests and expected result pngs has increased the size of the darktable repo from ~500Mb at version 3.0 to ~1.7Gb today, and it's only going to get larger. A lot of developers and users have no need for these additional files and they take up unnecessary space on hard drives. I normally run three different repos and on none of them do I need the integration tests as I mostly just do GUI work. So that's probably 3Gb of bloat on my drive to no purpose.

Please can these files be moved to an optional submodule or something to reduce the bloat.

**Comment by parafin** [comment] 2020-12-05 10:28
Using submodule will mostly defeat the purpose of splitting, since it's too cumbersome to exclude a submodule from git updates - most people won't do it. Instead it should be either just some file share that can be downloaded (e.g. using rsync or wget) or a separate git repository. First option will require some hosting, second one can still use github. But storing data files in git isn't the best use of git, so first option is better.

**Comment by dterrahe** [comment] 2020-12-05 10:28
It is too late to reduce the _repo_ size by now; removing the binaries will still keep them in history. It will only affect the working directories (and since I use multiple worktrees...)

But this only increases the urgency with which to take this decision.

**Comment by parafin** [comment] 2020-12-05 10:29
shallow clones will become smaller though, but again not many people use that feature

**Comment by elstoc** [comment] 2020-12-05 10:31
> It is too late to reduce the repo size by now

Yes I suspected as much. Shame.

**Comment by dterrahe** [comment] 2020-12-05 10:32
> Instead it should be either just some file share that can be downloaded (e.g. using rsync or wget) or a separate git repository. First option will require some hosting, second one can still use github. But storing data files in git isn't the best use of git, so first option is better.

Agreed. My initially thoughts that this would lead to a lot of data churn during github CI, but then I realised it rebuilds all its vms over the net each time anyway...

However that might still impact the choice of file hosting.

**Comment by parafin** [comment] 2020-12-05 10:36
I don't know about GitHub Actions, but in GitLab CI there is such thing as cache, which can remove the need to download the test data each and every time.

**Comment by TurboGit** [comment] 2020-12-05 10:36
I'm not for moving them outside of main repo, the integration tests are important enough to be there for every developer to be aware of them and encourage them to run the tests before proposing a PR. I'm doing that all the time now and I have already been able to spot issues with the tests, that's an invaluable test suite.

**Comment by parafin** [comment] 2020-12-05 10:38
Integration tests infrastructure can stay and its scripts amended with downloading the test data instead of using it from git repo itself. There is no problem here.

**Comment by elstoc** [comment] 2020-12-05 10:45
Most of the people who clone the repo do so only to build the application. Many of the developers do not touch iop code - really it's overkill to run all of the integration tests when changing a bit of CSS, for example.

**Comment by TurboGit** [comment] 2020-12-05 10:49
> shallow clones will become smaller though, but again not many people use that feature

Well shallow clones will still need to clone last version of every expected.png and those are rarely updated so at the end the download will be the same.

**Comment by dterrahe** [comment] 2020-12-05 10:49
An issue with using git for binaries is that it makes it very expensive to later on swap better images for existing ones, because you are now carrying both of them forever. Having a separate hosting means it is basically cost-free to add as many test cases as you want. Meaning we could have more and better tests without worry. With git, you _better_ worry!

**Comment by TurboGit** [comment] 2020-12-05 10:50
> Most of the people who clone the repo do so only to build the application.

And I don't want to speed more time handling another repository for the test. This is an important part of my work and my time is precious far more than my disk space or bandwidth.

**Comment by dterrahe** [comment] 2020-12-05 10:58
The _tests_ should definitely stay in git; I think we are discussing just the images.

I really do understand your concern, but I really think if we are serious about building comprehensive tests, we will hit a point sometime in the future where it becomes unsustainable and we'll have to find a different solution _anyway_. But by then we can't back out the damage already done.

I've always understood putting binaries in git is a bad idea. Maybe there are best practices out there that make an exception for test data, but our test data is quite large by the nature of RAWs.

**Comment by parafin** [comment] 2020-12-05 11:13
> > shallow clones will become smaller though, but again not many people use that feature
> 
> Well shallow clones will still need to clone last version of every expected.png and those are rarely updated so at the end the download will be the same.

I was talking about when test data will be moved out of git repo.

**Comment by parafin** [comment] 2020-12-05 11:14
> > Most of the people who clone the repo do so only to build the application.
> 
> And I don't want to speed more time handling another repository for the test. This is an important part of my work and my time is precious far more than my disk space or bandwidth.

Well, there should be also a script for uploading the data then. But I understand that someone will have to implement and support it.

**Comment by TurboGit** [comment] 2020-12-05 11:30
> Well, there should be also a script for uploading the data then.

And then you break the link between the commit to fix/change dt and the corresponding updade of the regression test. The traceability is important.

**Comment by parafin** [comment] 2020-12-05 12:46
No you don't, you just never delete files, only add (which is the same with git basically). It all can be worked out correctly, but I'm not saying it's simple. Simple is what we have currently.

**Comment by AxelG-DE** [comment] 2021-01-02 03:45
> I'm not for moving them outside of main repo, the integration tests are important enough to be there for every developer to be aware of them and encourage them to run the tests before proposing a PR. I'm doing that all the time now and I have already been able to spot issues with the tests, that's an invaluable test suite.

Please allow me to amend my point of view:
- how many people of the users of the git repo are really using it? I mean not amongst the devs, amongst all, who build master
- There are ppl like me, who are riding master, in order to help
- At the same time I will not become a git-professional, as I have enough around my head. Means anything goes wrong, I mess up my repo, what will do is have a fresh clone. And the time is not too long ago, I merely had 6Mbit DL-speed
- Also I have a daily backup (yes I know, I could exlude) and not beeing so happy the nightly run getting longer and longer

"Important for me" sound a bit selfish in my ears, sorry to be frankly

**Comment by elstoc** [comment] 2021-01-15 15:57
@TurboGit shall I close this now then?

**Comment by TurboGit** [comment] 2021-01-15 16:44
Sure, closing now.

**Closed by TurboGit** 2021-01-15 16:44 UTC
