### ISSUE TITLE
Slider controls with left-click hold on mouse should lock to currently selected slider

### ISSUE THREAD

**Issue by tmab2003** [darktable-org/darktable#8946] opened 2021-05-13 01:17 UTC
Whenever I am holding left-click and sliding any of the controls and my mouse moves up or down to an adjacent control, the other sliders also move to where my mouse is. This is extremely frustrating. I wish there was a way to lock the slider that can change based on where I started my left-click? And then I should be able to move left/right freely without having to keep it perfectly horizontal...

Am I missing a configuration somewhere for this?

**Comment by Jiyone** [comment] 2021-05-13 21:50
I have the same issue on MacOS 10.15.7.
Very frustrating :(

**Comment by RawConvert** [comment] 2021-05-14 23:43
@tmab2003 , you probably need to say what version of dt and what OS.
I just briefly tried this on Ubuntu and dt 3.5.0+1966 and slider movement is fine.  I can move the mouse vertically up and down right over other sliders but only the original slider is affected.

**Comment by tmab2003** [comment] 2021-05-15 01:57
Interesting - I'm on MacOS Big Sur 11.3.1 running Darktable version 3.4.1.

**Comment by johnny-bit** [comment] 2021-05-15 09:11
I just checked on linux with darktable 3.4.1: if you hold LMB then you can go around whole screen and not affect any other slider except the one you started with.
Same thing on windows with darktable 3.4.1.1

So... Maybe only macs are affected that way? @MStraeten or @parafin - can you guys confirm? maybe it's some gtk-on-mac problem?

**Comment by parafin** [comment] 2021-05-15 10:36
I can confirm it on Mac, but have no desire to look into it. Just one more macOS GTK port peculiarity to add to the list.

**Comment by facorazza** [comment] 2021-08-06 12:28
Commenting so that this issue does not get closed. This is quite an annoying behaviour and is still present on 3.6

**Comment by johnny-bit** [comment] 2021-08-06 12:40
This is mac-only issue as it seems, because it doesn't happen on windows 7/10 nor any linux wm that i managed to test on.

**Comment by juhanipaasonen** [comment] 2021-12-10 19:43
This bothers me as well. I would like to have a look at this. To be fair, I'm not familiar with darktable codebase, gtk, or projects of this size, so let's see if anything comes out of it. Any pointers on, well, anything are highly appreciated. I had a quick glimpse on the codebase, and it looks like bauhaus is the place I want to start my search at.

**Comment by juhanipaasonen** [comment] 2021-12-10 21:32
I did a bit of testing (I'm running Big sur). The sliders start jumping, if the tooltip of the slider has appeared before you start to drag. If you manage to start the drag before the tooltip appears, the drag is locked to the single slider. This holds for all the types of dragging I could figure out (click and drag with one finger, click with one finger and drag with another, three finger drag, with and without mouse lock by tapping).

Unfortunately disabling the tooltips (Shift+T) doesn't fix the jumpiness. I guess it only makes the tooltips invisible?

So, at least there is a workaround, but it's tricky to be fast enough.

**Comment by isaac84** [comment] 2022-06-16 23:35
I agree this is annoying and can confirm it's still an issue in darktable 3.8.1 running on Catalina 10.15.7 but I understand it probably won't be fixed as its an issue with the GTK port.

**Comment by juhanipaasonen** [comment] 2022-07-05 10:09
Can confirm, this works as expected in darktable 4.0.0. on 11.6.6. I suppose this ticket can be closed?

**Comment by parafin** [comment] 2022-07-05 17:43
Miracle confirmed, though I think it still behaves a little bit different from Linux. Anyway, closing.

**Closed by parafin** 2022-07-05 17:43 UTC
Labels: bug: upstream, no-issue-activity, scope: macos support
