### ISSUE TITLE
Perpective correction module: retain user choice

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#9213] opened 2021-06-10 12:53 UTC
The Crop and rotate module retains some user settings, like automatic cropping, aspect and guides.

However, the Perspective module doesn't retain some similar settings: guides, automatic cropping

Usually the user that uses these settings for one image wants to apply them to all images.

They should be made permanent.

**Comment by Nilvus** [comment] 2021-06-10 20:08
Which darktable version do you use? Think about precise that (and for some, other infos like OS, etc.) on each issue (as asked on bug report explanation). Thanks.

**Comment by paolobenve** [comment] 2021-06-11 06:20
3.4.1 on ubuntu. And I could verify that the behaviour is the same in 3.5.0, compiled on my pc

**Comment by AlicVB** [comment] 2021-06-11 20:29
I confirm the behavior.... but although it's clear that guide value should be kept, I'm not so sure for the automatic cropping, as there's 2 values (contrary to crop&rotate module) we may expect that user will choose a different setting for different images...

fyi, perspective module and crop & rotate will certainly see some important changes for 3.8 !

**Comment by paolobenve** [comment] 2021-06-12 08:51
> although it's clear that guide value should be kept, I'm not so sure for the automatic cropping, as there's 2 values (contrary to crop&rotate module) we may expect that user will choose a different setting for different images...

Well, I'd say that resetting that control to off or retaining the previous value doesn't change anything for the user that changes that setting every time, while it makes a great difference for the user that always mantain the same value.

Besides that, I'd say that the off value is used rarely if the perpective is corrected, so having off as default value doesn't favour anyone.

**Comment by Nilvus** [comment] 2021-07-11 10:41
@AlicVB: maybe this could be linked to your rework of perspective and rotate parts (PR #9456)? And so be closed when your PR will be merged.

**Comment by Nilvus** [comment] 2021-11-21 10:49
@paolobenve: as perspective is now deprecated for 3.8 and a new rotation and perspective is added to replace it, I close this issue. I think the best would be that you test that new module when 3.8 will be out (for Christmas) and if the issue is still there, it will be better to post a new issue. Of course, if you could already test actual master (future 3.8), it will be better as this could provide better feedback for 3.8 release.

**Closed by Nilvus** 2021-11-21 10:49 UTC
Labels: feature: enhancement, scope: UI
