### ISSUE TITLE
Darktable 3.6.0.1 not starting

### ISSUE THREAD

**Issue by krisakos** [darktable-org/darktable#9975] opened 2021-09-10 07:40 UTC
hello there, i am having a great issue with Darktable 3.6.0.1
i download it, all fine.
i install it, all fine.
when i click to open it there's a message appearing:

![image](https://user-images.githubusercontent.com/90444392/132817882-d34820e8-f328-496e-926d-367dc0ff79ea.png)

and the file it creates is this -that i have no clue what to do...

[darktable_bt_6BX380.txt](https://github.com/darktable-org/darktable/files/7142039/darktable_bt_6BX380.txt)

i tried uninstalling and reinstalling, downloading it again, restarting the PC but nothing worked.

any clues?

i use Win10

thanks in advance!

**Comment by johnny-bit** [comment] 2021-09-10 08:22
The problem is with igdrcl64.dll which is either amd or intel driver thingie. See for example https://community.amd.com/t5/drivers-software/problems-with-igdrcl64-dll-solved/td-p/105803

It's problem with drivers, so you need to upgrade your graphics card drivers.
As a workaround you can edit darktable shortcut and pass `--disable-opencl` to let it skip opencl initialization.

Since there's nothing we can do (really, tre drivers crash on darktable querying if there are devices available!) closing this issue.

**Closed by johnny-bit** 2021-09-10 08:22 UTC
Labels: bug: won't fix, bug: upstream, scope: hardware support

**Comment by krisakos** [comment] 2021-09-10 12:05
thank you very much! i'll check it out right now!
