### ISSUE TITLE
Segfault with current master on opening/revisiting a previous edit

### ISSUE THREAD

**Issue by codingdave** [darktable-org/darktable#5489] opened 2020-06-16 08:56 UTC
**Describe the bug**
Darktable crashes with a previously edited image. I have isolated the image and when I try to import that image + xmp into a fresh darktable environment the crash is reproducible.

**To Reproduce**
1. Import the provided NEF + XMP
2. You will get a Segfault

**Expected behavior**
No Segfault, opening the raw like every other raw file.

**Platform (please complete the following information):**
- c167ee8dc9752e70bd42caf24f9f5f3d5901646b
 - OS: Manjaro
 - OpenGL: Yes
 - nvidia-440x

https://drive.google.com/drive/folders/1q46UEVCoGewbWSL1RPf9uPs3ljHIla8p?usp=sharing

**Comment by codingdave** [comment] 2020-06-16 09:38
dt 3.02 (Windows) opens the file without error.

**Comment by TurboGit** [comment] 2020-06-16 12:57
@codingdave : well this image has been opened with a dev version of darktable as there is the hash values in the XMP file.

```
   darktable:history_basic_hash="9d9db76e8845ca28f95dcc0fdc4e62e8"
   darktable:history_auto_hash="16ddf8b7620566315c8735f78ccf069f"
   darktable:history_current_hash="16ddf8b7620566315c8735f78ccf069f">
```

So at this stage hard to tell what is wrong. Possible a picture opened with a buggy dt ?

I'm not sure when it has been opened with 3.0.2 but sure it that is the case the xmp may be corrupted.

**Comment by MStraeten** [comment] 2020-06-16 13:13
seems to be similar to https://github.com/darktable-org/darktable/issues/5351.  Maybe a full cleanup oft the build environment can help (it did in my case ...)

**Comment by phweyland** [comment] 2020-06-16 13:27
not sure that can help. unning with debug I get this:

```
Thread 48 "worker res 0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff5aa8d700 (LWP 23100)]
process_sse2_cmatrix_fastpath_simple._omp_fn.7 ()
    at /home/philippe/git/dt/src/iop/colorin.c:1161
1161        __m128 input = _mm_load_ps(in);
```

**Comment by johnny-bit** [comment] 2020-06-16 15:40
the mm_load_ps is for loading input pixels into sse buffers so... alignment issues? similar to #3209?

**Comment by phweyland** [comment] 2020-06-16 19:30
an additional detail. when I've opened the image with xmp the first time I got the seg fault but the image was imported. then, even removing the xmp file, dt still crashes (same log) opening this image.

**Comment by codingdave** [comment] 2020-06-16 19:46
> @codingdave : well this image has been opened with a dev version of darktable as there is the hash values in the XMP file.
> 
> ```
>    darktable:history_basic_hash="9d9db76e8845ca28f95dcc0fdc4e62e8"
>    darktable:history_auto_hash="16ddf8b7620566315c8735f78ccf069f"
>    darktable:history_current_hash="16ddf8b7620566315c8735f78ccf069f">
> ```
I don't know the meaning of the hash values but they might confuse because I have replaced the original NEF file (that was showing a person) by a NEF from the same session (showing the otter) while keeping the same error. If the hash values incorporate the hash over the NEF they are obviously wrong now.

> I'm not sure when it has been opened with 3.0.2 but sure it that is the case the xmp may be corrupted.
This NEF+XMP fails with the current master but works with 3.0.2. So for me this sounds like a regression that we need to look after before the next release.

> seems to be similar to #5351. Maybe a full cleanup oft the build environment can help (it did in my case ...)
I dont think so. This is a linux build. I always delete the build directory before building.






> not sure that can help. running with debug I get this:
> 
> ```
> Thread 48 "worker res 0" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fff5aa8d700 (LWP 23100)]
> process_sse2_cmatrix_fastpath_simple._omp_fn.7 ()
>     at /home/philippe/git/dt/src/iop/colorin.c:1161
> 1161        __m128 input = _mm_load_ps(in);
> ```
> an additional detail. when I've opened the image with xmp the first time I got the seg fault but the image was imported. then, even removing the xmp file, dt still crashes (same log) opening this image.

And it looks like others can reproduce that same issue (_mm_load_ps), repeated crashes.

**Comment by phweyland** [comment] 2020-06-16 21:46
> If the hash values incorporate the hash over the NEF they are obviously wrong now.

No, the hash includes only development data.

**Comment by TurboGit** [comment] 2020-06-19 08:37
I had a look at this, and the issue is that the iop-order in this edit is a mess:

```
   darktable:iop_order_version="0"
   darktable:iop_order_list="invert,0,cacorrect,0,hotpixels,0,rawdenoise,0,denoiseprofile,0,bilateral,0,rotatepixels,0,scalepixels,0,lens,0,hazeremoval,0,ashift,0,colorin,0,colorout,0,demosaic,0,flip,0,gamma,0,highlights,0,rawprepare,0,sharpen,0,temperature,0,clipping,0,liquify,0,spots,0,retouch,0,exposure,0,mask_manager,0,tonemap,0,toneequal,0,graduatednd,0,profile_gamma,0,equalizer,0,negadoctor,0,nlmeans,0,colorchecker,0,defringe,0,atrous,0,lowpass,0,highpass,0,lut3d,0,colortransfer,0,colormapping,0,channelmixer,0,basicadj,0,colorbalance,0,rgbcurve,0,rgblevels,0,basecurve,0,filmic,0,filmicrgb,0,colisa,0,tonecurve,0,levels,0,shadhi,0,zonesystem,0,globaltonemap,0,relight,0,bilat,0,colorcorrection,0,colorcontrast,0,velvia,0,vibrance,0,colorzones,0,bloom,0,colorize,0,lowlight,0,monochrome,0,grain,0,soften,0,splittoning,0,vignette,0,colorreconstruct,0,clahe,0,finalscale,0,overexposed,0,rawoverexposed,0,dither,0,borders,0,watermark,0"
```

Version 0 means that it is a custom iop-oder.

And the order registered into the XMP is quite wrong. `gamma` is not the last module and `rawprepare` not the first one :(

This cannot possibly work. I'm wondering if this is not another instance of the transient bug we had back in Sept.

The only solution I could possible see is to detect this situation and revert to new iop-order. But I'm reluctant doing this because it could well be a corner case and there is many other ways to have a broken order, so how to detect all those cases?

@codingdave : the solution on your side is simple.

Set iop_order_version to 2 instead of 0 and remove completely the line iop_order_list.

**Comment by jenshannoschwalm** [comment] 2020-06-20 08:23
@TurboGit we could look through a large number of issues related to wrong history order but i am pretty sure **this** pattern has been reported several times.
1. rawprepare not being the first
2. gamma "somewhere"


So - yes - it might be a corner case but one that will a) always lead to a crash and b) is always wrong. So i think it would be a really good thing if there was a check for such a xmp mess while importing.

**Comment by TurboGit** [comment] 2020-06-20 11:17
Ok, I'll see if something safe can be done for this.

**Comment by TurboGit** [comment] 2020-06-20 17:24
See #5582.

**Comment by ralfbrown** [comment] 2020-06-20 19:10
Saw similar corruption today in an xmp given as an example that made my code misbehave (the misbehavior is legit, but the xmp is broken as well).  In that case, there were multiple occurrences of the same multi-instance of a module.
```
darktable:iop_order_version="0"
darktable:iop_order_list="rawprepare,0,invert,0,temperature,0,highlights,0,cacorrect,0,hotpixels,0,rawdenoise,0,demosaic,0,denoiseprofile,0,bilateral,0,rotatepixels,0,scalepixels,0,lens,0,hazeremoval,0,ashift,0,flip,0,clipping,0,liquify,0,spots,0,retouch,0,exposure,0,exposure,1,exposure,1,mask_manager,0,tonemap,0,toneequal,0,graduatednd,0,profile_gamma,0,equalizer,0,colorin,0,channelmixerrgb,0,negadoctor,0,nlmeans,0,colorchecker,0,defringe,0,atrous,0,atrous,1,atrous,1,atrous,2,atrous,1,atrous,2,atrous,1,atrous,2,lowpass,0,highpass,0,sharpen,0,lut3d,0,colortransfer,0,colormapping,0,channelmixer,0,basicadj,0,colorbalance,0,rgblevels,0,basecurve,0,filmic,0,rgbcurve,0,filmicrgb,0,colisa,0,tonecurve,0,levels,0,shadhi,0,zonesystem,0,globaltonemap,0,relight,0,bilat,0,colorcorrection,0,colorcontrast,0,velvia,0,vibrance,0,colorzones,0,colorbalance,1,colorbalance,2,colorbalance,1,colorbalance,2,colorbalance,1,colorbalance,2,bloom,0,colorize,0,lowlight,0,monochrome,0,grain,0,soften,0,splittoning,0,vignette,0,colorreconstruct,0,colorout,0,clahe,0,finalscale,0,overexposed,0,rawoverexposed,0,dither,0,borders,0,watermark,0,gamma,0"
```

**Comment by TurboGit** [comment] 2020-06-20 20:05
@ralfbrown :
I don't think that have the same module instance twice will make dt crash. Have you tried removing the duplicate and import again? Do you still see issues?

If so, please can you give me access to the RAW + xmp to test on my side ? Thanks.

**Comment by ralfbrown** [comment] 2020-06-20 20:11
Wasn't crashing, but was causing issues with the values of module->iop_order (which in turn caused my code's misbehavior).  See #5576.

**Comment by TurboGit** [comment] 2020-06-21 17:29
@ralfbrown : I see, so maybe something to check too. But is this a "Sep 2019" kind of issue or something that could happen today? Can you point me to the XMP ? Do we have an idea about the date of the edit ?

I'd like to ensure we are not making "invisible" a current bug by systematically going back to a 3.0 iop-order.

**Comment by ralfbrown** [comment] 2020-06-21 17:40
The XMP is posted in #5576.  I wasn't able to cause the same issue with current master, so whatever causes it may already have been fixed.

**Comment by TurboGit** [comment] 2020-06-25 15:59
Ok, so closing at this stage.

**Closed** 2020-06-25 15:59 UTC
Labels: bug: pending
