### ISSUE TITLE
[Dev 3.3.0-xxx] Edits getting stuck with "working...." when in modules Local Contrast ,colorzone,retouch

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6147] opened 2020-08-30 05:22 UTC
The working label in main view and main view frozen. Clicking other steps in history shows change in preview thumbnail and histogram, but main view is stuck.
![image](https://user-images.githubusercontent.com/1119439/91651635-a57e1700-eaac-11ea-8bff-6fe69b5f8083.png)

![image](https://user-images.githubusercontent.com/1119439/91651685-600e1980-eaad-11ea-997e-876d04d252ff.png)

Using the "X" to close it, closes DT but process is still running and needs to be killed in process explorer.

Started from darktable-3.3.0+388-g9f5640d35-win64
Happens in my current darktable-3.3.0+420-gba3fd4736-win64 too.

this is darktable 3.3.0+420-gba3fd4736

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.1.0
  Colord support disabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

Image and xmp attached
[P1081339.zip.txt](https://github.com/darktable-org/darktable/files/5146375/P1081339.zip.txt)

**Comment by Mark-64** [comment] 2020-08-30 06:32
DT 3.3.0+389~gd048573163d on Windows 10.
I can't reproduce with the provided image. Playing with Local Contrast, colorzone, retouch works as expected.

**Comment by chhil** [comment] 2020-09-01 05:22
This used to happen sometime back. It went away and I closed it , but its back.

https://github.com/darktable-org/darktable/issues/4751

**Comment by johnny-bit** [comment] 2020-12-31 20:06
This might be interminent issue with your setup TBH. I'll close this for now and next time similar thing happens - try and run darktable in terminal with `-d all` and provide relevant output part when darktable is stuck so we can better evaluate what's exactly "stuck".

If you are able to - running darktable in profiler when such thing happens might be beneficial, then we'll know for sure what's spinning.

**Closed by johnny-bit** 2020-12-31 20:06 UTC
Labels: no-issue-activity
