### ISSUE TITLE
crash due to threading race condition in darkroom when activating bottom image roll

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#8073] opened 2021-02-02 12:27 UTC
**Describe the bug**
I think I just clicked on the bottom bar cursor icon to also include other images in this image roll and then DT just crashed.
I have the feeling that that new threads creating/showing the thumbnails in the bottom image roll somehow caused a race condition. 
Here is a backtrace: [darktable_bt_RXT2X0.txt](https://github.com/darktable-org/darktable/files/5911043/darktable_bt_RXT2X0.txt)

**To Reproduce**
So far I couldn't reproduce again.

**Platform (please complete the following information):**
* Darktable Version: lastest master (3.5.0+903~g641608706) + https://github.com/darktable-org/darktable/pull/8067 applied
* OS: Ubuntu 20.04
* OpenCL activated: yes

**Comment by johnny-bit** [comment] 2021-06-28 11:24
I think this got fixed in #8431  which prevents action on non-inited paren.
for completness sake i added #9356 just in super edge case

Closing this if you don't mind since reproduce might be super hard to do.

**Closed by johnny-bit** 2021-06-28 11:24 UTC
Labels: no-issue-activity

**Comment by da-phil** [comment] 2021-06-28 11:41
> I think this got fixed in #8431 which prevents action on non-inited paren.
> for completness sake i added #9356 just in super edge case
> 
> Closing this if you don't mind since reproduce might be super hard to do.

Looks fine for me, I also was not able to reproduce the crash in a recent version from master.
