### ISSUE TITLE
Windows: Import fails with path containing special characters

### ISSUE THREAD

**Issue by Smurffson** [darktable-org/darktable#9596] opened 2021-07-22 19:52 UTC
**Introduction**
Import failure on Windows 10
Darktable v3.6

**Describe the bug/issue**
Trying to import the content of a folder containing special characters like accents, Umlauts or any non-english characters fails silently.
You will get an success message, but nothing is imported (see description below). Renaming the folder solves the problem.

**To Reproduce**

1. Create a folder containing special characters (eg öä è â)
2. Click on import, "add to library", select folder
3. select all images in folder, click on "add to library"
4. Sucess message "imported xxx images"
5. lighttable shows no images, film roll doesn't exist, no images found when trying to search for any of them (by date, ...), Timeline doesn't show any recent images from the corresponding period

6. Rename folder, try again - import works as expected

**Expected behavior**
Obviously: Properly import images to library

**Screenshots**
![image](https://user-images.githubusercontent.com/69250333/126700168-7a89be6e-1ddf-4928-b259-74169d52540d.png)
![image](https://user-images.githubusercontent.com/69250333/126700203-e1b4ae63-7e74-4b7b-9d13-1a5eea0bb425.png)

Filmroll is missing:
![image](https://user-images.githubusercontent.com/69250333/126700314-0cf6dcca-e06c-4955-923e-a2015c093f00.png)

can't find folder:
![image](https://user-images.githubusercontent.com/69250333/126700348-a81cec7e-81fa-4618-8454-25955d3d428c.png)
![image](https://user-images.githubusercontent.com/69250333/126700411-c385af0b-5ff5-4b7d-a56c-f5e6dd419197.png)

**Which commit introduced the error**
no issue with Darktable 3.4.x

**Platform**

* darktable version : 3.6.0
* OS                :  Windows 10 Pro x64 21H1 - latest patches (build 19043.1110)
* Memory            : 32GB
* Graphics card     : Nvidia Quadro K2000M
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by ralfbrown** [comment] 2021-07-22 20:01
Duplicate of #9475, fixed in master by #9498.

**Closed** 2021-07-22 20:05 UTC
