### ISSUE TITLE
Smart Masks

### ISSUE THREAD

**Issue by larsemil** [darktable-org/darktable#14322] opened 2023-04-25 08:50 UTC
**Describe the solution you'd like**

I would like smart masks / selections like those in Lightroom. For example to select only the sky. Or only the model.

**Comment by TurboGit** [comment] 2023-04-25 10:03
> I would like smart masks / selections like those in Lightroom. For example to select only the sky. Or only the model.

We can already achieve that. See the latest videos done recently by Boris Hajdukovic here:

https://discuss.pixls.us/t/editing-moments-with-darktable/11770/821

It's not done like Lr but certainly can achieve a lot!

**Comment by ralfbrown** [comment] 2023-04-25 13:22
Duplicate of #13175, #12316, #10439, #2670, and more.

**Closed by ralfbrown** 2023-04-25 13:22 UTC
Labels: duplicate
