### ISSUE TITLE
Running into unhandled exceptions various times

### ISSUE THREAD

**Issue by gamue** [darktable-org/darktable#7627] opened 2021-01-02 14:42 UTC
**Describe the bug**

I've tried the new version of darktable and in the 30min I've tried it the application crashed 4 times due unhandled exceptions. 

**To Reproduce**

Everytime I did something different like changing the selection with one of the pre-defined options or import a folder. Sorry that it's not so helpful, but hope the backtrace could help you identifying the problem and root cause.

[darktable_bt_2QA0W0.txt](https://github.com/darktable-org/darktable/files/5760376/darktable_bt_2QA0W0.txt)
[darktable_bt_6W0OW0.txt](https://github.com/darktable-org/darktable/files/5760377/darktable_bt_6W0OW0.txt)
[darktable_bt_36LUW0.txt](https://github.com/darktable-org/darktable/files/5760378/darktable_bt_36LUW0.txt)
[darktable_bt_IGMZW0.txt](https://github.com/darktable-org/darktable/files/5760379/darktable_bt_IGMZW0.txt)

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Win10

**Additional context**

**Comment by johnny-bit** [comment] 2021-01-02 15:47
Interesting...

- `darktable_bt_2QA0W0.txt` - this one is similar to #7592 - but I have no idea why would that happen
- `darktable_bt_6W0OW0.txt` - like above
- `darktable_bt_36LUW0.txt` - like above...
- `darktable_bt_IGMZW0.txt` - like above, however closes call is fortunately dlose to dt_culling_change_offset_image... but that gises us nothing...

Generally it looks like we have no idea why something would call dtgtk_button_override_background_color with null button.

If you don't mind, I'd close this as a duplicate of #7592

As a "fix" you could try starting darktable with empty config dir as well as empty databases, that should do the trick. Generally we have unhandled null somewhere and we can't trace where (or maybe it was fixed already and I'm browsing master code while 3.4.0 code is different by couple weeks of coding already)

**Closed by johnny-bit** 2021-01-02 15:47 UTC
