### ISSUE TITLE
Window Sizes too big on Laptop screen

### ISSUE THREAD

**Issue by marcellotogg** [darktable-org/darktable#8438] opened 2021-03-08 12:52 UTC
On my laptop screen (res. 1920 x 1080) the import window (and others) are shown too high. The window cant close because the ok or enter field is not visible (under the bottom).
Please resize the windows for this resolution.
System W10 pro german
Darktable 3.4.1

**Comment by Nilvus** [comment] 2021-03-08 19:07
For such resolution, that shouldn't be the case. Could you post a screenshot please? And precise which theme you use and which font size? With so few infos, it will be hard to understand the issue. I use a laptop with 1440x900 with 11px font size and an elegant theme (grey one, but for size, all elegant theme use same font) and have no issue like that one.

**Comment by Deraen** [comment] 2021-03-13 12:24
I think I'm encountering the same problem. Maybe this screenshot from 4k screen helps. The file dialog gets wider than the screen. The right sidebar content also gets really wide and uses scrollbar, the left one doesn't have the problem.

This started quite recently so I think it regressed in 3.4.1, I definitely used 3.4.0 without this problem.

The problem happens with "darktable" and "darktable-icons" themes, but not other variants.

![image](https://user-images.githubusercontent.com/648087/111029793-4c9e1c80-8407-11eb-9210-762712de3f49.png)

**Comment by Deraen** [comment] 2021-03-13 12:40
Tested with latest theme file from git and could reproduce the problem.

Bisected the problem to commit eb8d1713963e5b5b79097ca0077c68547a1b49fc, and specficially adding the font-family rule to entry and textfield elements:

```
@@ -306,6 +306,7 @@ textview
   min-height: 0;
   min-width: 0;
   padding: 0px;
+  font-family: sans;
 }
```

**Comment by Deraen** [comment] 2021-03-13 12:55
As side note, the reason why I don't use those theme variants is that I want to use Ubuntu font for the UI, which also should be my GTK default font, but I also have Roboto font available, and it has precedence on those variants, so I've used "darktable" (hadn't noticed the icons previously, switching to that now) them and added `* { font-family: Ubuntu; }` rule on my settings.

**Comment by Nilvus** [comment] 2021-03-13 13:08
> Tested with latest theme file from git and could reproduce the problem.
> 
> Bisected the problem to commit [eb8d171](https://github.com/darktable-org/darktable/commit/eb8d1713963e5b5b79097ca0077c68547a1b49fc), and specficially adding the font-family rule to entry and textview elements:
> 
> ```
> @@ -306,6 +306,7 @@ textview
>    min-height: 0;
>    min-width: 0;
>    padding: 0px;
> +  font-family: sans;
>  }
> ```

That is a workaround for Windows (for blink cursor not visible in entry and textview, a Pango library bug specific to Windows), and it's strange that you have such issue with that.

Your screenshot above is strange. What's that sort of big black pop-up window above darktable one?

**Comment by Nilvus** [comment] 2021-03-13 13:09
> As side note, the reason why I don't use those theme variants is that I want to use Ubuntu font for the UI, which also should be my GTK default font, but I also have Roboto font available, and it has precedence on those variants, so I've used "darktable" (hadn't noticed the icons previously, switching to that now) them and added `* { font-family: Ubuntu; }` rule on my settings.

You can use that on you side but using 'serif' instead of 'Ubuntu' should be the same and less font used related. Couldn't be added in darktable code as Ubuntu font doesn't work on other OS and many Linux distrib.

And changing that one would break what it solved on Windows. Quite bad thing!

**Comment by Nilvus** [comment] 2021-03-13 13:12
Another thing: I use a laptop sometimes with a 1440x900 screen and another computer with full HD screen (1920x1080) and I sometimes test darktable default theme (with same Ubuntu font) and never see this issue. So, I'm quite sure there's something else that cause this issue. Maybe a combo between some things, and not only CSS file, font or screen resolution. Could you post a better screenshot and precise font size you use (a screenshot of font settings in your OS would be great.

**Comment by Nilvus** [comment] 2021-03-13 13:13
Oh, and could you test that PR to see if you have same issue: https://github.com/darktable-org/darktable/pull/8346

**Comment by Deraen** [comment] 2021-03-13 13:17
> Your screenshot above is strange. What's that sort of big black pop-up window above darktable one?

That's the import file dialog.

**Comment by Deraen** [comment] 2021-03-13 13:20
> Oh, and could you test that PR to see if you have same issue: #8346

I can reproduce the problem with darktable.css from that PR also.

**Comment by Nilvus** [comment] 2021-03-13 13:25
> That's the import file dialog.
> 
> Or the top ~20 pixels? That is just i3 statusbar.

Ok, I never had that on my side, with Ubuntu size. Will be hard to help if we can't reproduce. Could you provide more infos I asked:
 - all your font settings (a screenshot is the easier way to show that)
 - your screen resolution and laptop size (13", 14"... ?)
 - precise button you click on (import folder, image or from camera) where you have that
 - and post a screenshot of the general tab of preferences window

**Comment by Nilvus** [comment] 2021-03-13 13:28
@Mark-64: your help is needed about the font-family:sans line that cause this issue here. As you probably remember, that was a workaround for a pango issue on Windows. The issue is officially fixed. Anyway, how this is updated in Windows? Is this included in darktable Windows package? If yes, is the Pango fix included in last 3.4.1.1 package? Or to be simple, if that line is removed (see @Deraen comment above pointed the commit and line), do you still have blink cursor in entries or not?

All that could help to check if this line is always needed or could now be removed (if Pango fix is included or could be for 3.6).

**Comment by Deraen** [comment] 2021-03-13 13:37
Seems like this is related to my fontconfig settings, now that I disabled this I don't get huge dialogs (and this also fixed the reason why I had to manually set Ubuntu font, numbers were using strange font.)

Less certain now if my problems is the same as the original reported has.

```
~/.config/fontconfig/conf.d master*
❯ cat 20-emoji.conf.disabled
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
        <match>
                <test name="family"><string>sans-serif</string></test>
                <edit name="family" mode="append" binding="strong">
                        <string>Noto Color Emoji</string>
                </edit>
        </match>
        <match>
                <test name="family"><string>serif</string></test>
                <edit name="family" mode="append" binding="strong">
                        <string>Noto Color Emoji</string>
                </edit>
        </match>
        <match>
                <test name="family"><string>Apple Color Emoji</string></test>
                <edit name="family" mode="append" binding="strong">
                        <string>Noto Color Emoji</string>
                </edit>
        </match>
</fontconfig>
```

I don't really have any system option dialogs to take screenshots from, I just have gtk settings.ini. Anyway, other details are 32" 4k monitor, and the problems happened on any file dialogs ("image...", "folder...", select target folder for export).

```
❯ cat ~/.config/gtk-3.0/settings.ini
[Settings]
gtk-icon-theme-name = Suru
gtk-theme-name = Yaru
gtk-font-name = Ubuntu 10
```

![image](https://user-images.githubusercontent.com/648087/111031751-c1765400-8411-11eb-9317-44dacea2cbe7.png)

So yeah, my problem is probably caused by my config. Though not sure why the font-family change for affect file dialogs like that.

**Comment by johnny-bit** [comment] 2021-03-13 18:27
@Deraen - your problem seems to be different one than one @marcellotogg has. Yours comes from fontconfig causing problems in text length calculations causing dialog to be too wide. @marcellotogg described problem as dialog being "too high" meaning imo too long, so the buttons are not visible.

@marcellotogg - The height settings for dialog are either calculated or taken from GSettings (external stuff) that might influence all gtk-based applications. If you have eg GIMP can you check if it's windows are affected too (although GIMP is gtk2 while darktable is gtk3 based... huh, i wonder which app is gtk3 based that can be used to check if problem afffects all gtk-based apps)

**Closed** 2021-05-05 16:14 UTC
Labels: no-issue-activity, scope: UI, understood: incomplete
