### ISSUE TITLE
Organize existing images like 'copy & import' does

### ISSUE THREAD

**Issue by caigner** [darktable-org/darktable#11308] opened 2022-03-10 11:20 UTC
The _copy & import_ module let's you sort your images into base and sub directories with a pattern like this one:

`$(JOBCODE)/$(EXIF_YEAR)/$(EXIF_YEAR)-$(EXIF_MONTH)-$(EXIF_DAY)/`

I'd like to suggest adding an _'organize'_ feature to the _selected images[s]_ module which allows the user to organize the selected images according to the same patterns and options. This should move images and corresponding sidecar files to the new location.

**Comment by quovadit** [comment] 2022-03-10 20:04
you can use the lua-script contrib/rename_images

![image](https://user-images.githubusercontent.com/5677563/157745575-e4c865b9-1ba9-483a-87fa-44b0a75c75f4.png)

**Comment by caigner** [comment] 2022-03-11 09:15
> you can use the lua-script contrib/rename_images

That might be a solution for experts like you, but please remember that most darktable users are probably photographers and amateurs. 

I myself have no idea how lua scripting works and I would prefer to have just a button to click on.

**Comment by Nilvus** [comment] 2022-03-11 09:28
This is so a duplicate of #2247

Note that this is harder to add in Lighttable and have some cons. Adding such thing would need to operate on filesystems AND database.

I so close and let you continue, if you want to add infos, on #2247.

Note that this could be added one day or never, depending if someone want to take time to code and test such feature.

**Closed by Nilvus** 2022-03-11 09:28 UTC
Labels: duplicate
