### ISSUE TITLE
Highlight reconstruction dependent on viewport and export is also broken 

### ISSUE THREAD

**Issue by progo** [darktable-org/darktable#3022] opened 2019-09-26 17:41 UTC
**Describe the bug**

Highlight reconstruction with "reconstruct color" option can achieve great feats with incredibly little data. But my problem with it is now that what darktable shows differs from what it exports.

**To Reproduce**
1. Enable highlight reconstruction
2. Enable  "reconstruct  color"
3. Fiddle with the exposure, bring it down
4. Possibly see funky business on the sky
5. If not, zoom in and pan around the image; the viewport changes and some artifacts should show. At least on mine.

**Expected behavior**
The exported file should always show deterministically the best possible outcome, no artifacts because that's what you can get in DT darkroom mode. I don't really care if there are occasional artefacts while developing... of course it would help a lot if there were none.

**Screenshots**

Below a snapshot of what it looks like on darktable how it should be. Then a view how it usually looks when I pan around for a bit. Finally, the third shot shows how it is exported every time (export settings don't affect the outcome)

![good-highlight-recovery](https://user-images.githubusercontent.com/667146/65710392-9bcd8180-e09b-11e9-9573-e567dbedd57b.jpeg)

![good-bad-highlight-recovery](https://user-images.githubusercontent.com/667146/65711261-34b0cc80-e09d-11e9-9eac-b94f888b689a.jpeg)

![bad-highlight-recovery](https://user-images.githubusercontent.com/667146/65710395-9bcd8180-e09b-11e9-9c2a-2a0a0d48cfaa.jpeg)

**Platform (please complete the following information):**
Gentoo linux + darktable 2.6.2

The source file DNG+XMP if this is sensor data dependent. Free to use!

[source_file_xmp.zip](https://github.com/darktable-org/darktable/files/3659088/source_file_xmp.zip)

**Comment by parafin** [comment] 2019-09-26 20:16
Have you tried turning on "high quality" export setting in preferences?

**Comment by progo** [comment] 2019-09-27 05:16
> Have you tried turning on "high quality" export setting in preferences?

Yes, it's enabled. The effect remains even if I export without resizing.

**Comment by johnny-bit** [comment] 2020-12-20 14:29
Well, this is reproducible on both current master & 3.2.1 - just import example file and I can see the patterns (and it's also present in exported file).

On the other hand - I tried to re-edit the image quickly using modernized workflow to 'save' the clouds but it's a bit challenging...

**Comment by jenshannoschwalm** [comment] 2021-05-04 06:07
@progo is this still valid?

If so, can you still reproduce after setting preferences->processing->pixel_interpolator_scaling to bicubic?

**Comment by progo** [comment] 2021-05-04 07:22
> If so, can you still reproduce after setting preferences->processing->pixel_interpolator_scaling to bicubic?

It is still valid with 3.4.1

I switched to bicubic interpolator and it didn't have any effect. I tested this using the file I included.

**Comment by jenshannoschwalm** [comment] 2021-05-04 17:59
I had a deeper look. You probably have recognized that the whole sky area is completely blown out leaving mostly just one color channel within the sensor range.

Color reconstruction simply can't work with such data and generates artefacts on it's own leading to the somewhat maze-like pattern. That is further distorted & worked on by other modules. That is interpolated either for display in darkroom or for export and that leads to slightly different visuals. BUT the main point is, you have to expect such artefacts using the algo on such data.

I think you should concider changing to Lum based correction or even better treat the manual exposure not hurting your sensor :-))))

I don't concider this to be a bug at all...

**Comment by progo** [comment] 2021-05-05 08:46
> I think you should concider changing to Lum based correction or even better treat the manual exposure not hurting your sensor :-))))
> 
> I don't concider this to be a bug at all...

I tend to agree that the algorithm is working overtime here and I shouldn't expect perfect results.

But consistency at preview/export would go a long way restoring the content to the best of its ability.

**Comment by jenshannoschwalm** [comment] 2021-05-05 10:52
> But consistency at preview/export would go a long way restoring the content to the best of its ability.

I don't understand this, please explain.

Please concider to close this issue.

**Comment by progo** [comment] 2021-05-05 11:00
> I don't understand this, please explain.

Consider the first two screenshots from the first post. They exhibit the same image with same processing parameters. Nothing is different between the images other than where I have zoomed in the image. These artefacts just appear from nowhere because I panned the view. The algorithm has done quite a good job actually as shown in the first screenshot. It could do it once, it could do it twice, I am hopeful.

**Comment by johnny-bit** [comment] 2021-06-28 12:28
Sooo... essentially the preview not matching export in this case is limitation of ROI system and is not a bug but a feature?

**Comment by jenshannoschwalm** [comment] 2021-06-28 16:25
In a way. Feature always sounds sort of positive and this is an annoying behaviour of the algorithm. It's also not good anyway but i didn't try to understand the code yet. I vaguely remember a discussion about re-implementation. It's one of the remaining weak points of dt.

**Comment by kanyck** [comment] 2021-07-22 19:37
I have the same issue:
![snap0034](https://user-images.githubusercontent.com/2641120/126699018-88471f6f-7c53-4c4a-807f-fb972f334fa9.jpg)
Platform

*  darktable version : 3.6.0
* OS : Linux - kernel 5.11.0-pf8
*  Linux - Distro : Gentoo
* Memory : 16G
* Graphics card : [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev cf)
* Graphics driver : amdgpu
* OpenCL installed : yes
* OpenCL activated : does not matter -- artifacts are there in both cases
* Xorg : 1.20.11-r2
* Desktop : Compiz
* GTK+ : 2.24.33 3.24.29
* gcc : 11.1.0-r1
* cflags : "-march=native -O3 -flto=3 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -msse3"

**Comment by jenshannoschwalm** [comment] 2022-09-11 09:53
@TurboGit  analysis and work on highlights reconstructions confirm this is an issue that can't be resolved due to the nature of the algo and ROI stuff. I would close with "no-fix"

**Comment by TurboGit** [comment] 2022-09-11 15:57
Agreed. Thanks for the notice.

**Closed by TurboGit** 2022-09-11 15:57 UTC
Labels: bug: won't fix, scope: image processing, bug: pending, no-issue-activity
