### ISSUE TITLE
Windows 10 - Changing interface language doe not happen 

### ISSUE THREAD

**Issue by smartgoblin** [darktable-org/darktable#8657] opened 2021-04-11 15:43 UTC
Hello.

When changing the application language to any other than EN the application stays in EN even after an application restart (even computer restart)

Problem on system with:

- OS: Windows 10
- Language preferences: EN United states
- Darktable 3.4.11

**Comment by Nilvus** [comment] 2021-04-12 16:01
Hi,

Language is changed only when you restart darktable, so it's always necessary to restart darktable.

Maybe it's a specific Windows 10 issue as I can't reproduce on Linux. But as I know some users using darktable in french and Windows 10, It's not sure it's darktable issue, even in Windows. What do you have if you try to change theme for example? Is this applied (it's done immediately, without restart).

Could you try another test: hide a panel, for example, left panel in lighttable or darkroom view (Shift+Ctrl+L to hide/show left panel). Restart darktable and check if that panel is always hidden or not. To be precise, if darktable save correctly last state view or not. Maybe you have some writing issue in darktablerc file (where such settings are saved).

**Comment by MStraeten** [comment] 2021-04-15 07:20
not reproducible with current master built for win10 (installed with standard config directory location)
so further infos are needed...

**Comment by smartgoblin** [comment] 2021-04-17 12:33
Themes are kept and hidden panels also.
It is only the language setting that is not applied.
What kind of information can I provide?

**Comment by smartgoblin** [comment] 2021-04-28 15:43
> 
> 
> not reproducible with current master built for win10 (installed with standard config directory location)
> so further infos are needed...

I have tried on another computer and have the same behaviour.  What other info do you need?

**Comment by johnny-bit** [comment] 2021-05-29 07:27
I tried that recently on win7pro and win10 and couldn't reproduce on both. I was using darktable 3.4.1.1

here's my scenario:
1. Open up fresh install of dt: it's in pl.
2. switch lang to en & reestart darktable
3. opens up in en
4. switch from en to pl & restart
5. opens up in pl
6. switch to sl & restart
7. open up - is sl.
8. switch back to en & restart.

I tried with username that has PL characters in path (`ó`) as we had some problems with that previously, but it made no effect.

> I have tried on another computer and have the same behaviour. What other info do you need?

hmmm... can you try disabling antivirus? but if you say all other settings are saved except for language then it's very weird...

I think it's also possible to specify language config via `--conf` param on commandline and if your dt shortcut has it on, then the config will be overriden every time, so make sure it's not doing tat?

**Comment by johnny-bit** [comment] 2021-06-19 10:25
I'm gonna close this since I'm 100% certain it should work. In exactly 2 weeks a new version comes out: 3.6 with new fixes (and bugs :P) I was not able to reproduce the problem with 3.4.1.1 on 2 different windows versions, i also cannot reproduce with current master on win 10...

If you ARE able to reproduce following recommended restart of dt (as eg described in https://github.com/darktable-org/darktable/issues/8657#issuecomment-850787145) then I guess what we'll need is:
- darktablerc before and after language change to see that the value did change
- how you run darktable (and make sure the language isn't overwritten with conf param)

Once provided reliable reproduction steps I'll reopen so we can investigate deeper.

**Closed by johnny-bit** 2021-06-19 10:25 UTC
Labels: no-issue-activity, understood: unclear
