### ISSUE TITLE
Critical issue during launch of Darktable ... Not possible to launch it ...

### ISSUE THREAD

**Issue by MythicMike** [darktable-org/darktable#6833] opened 2020-11-10 12:49 UTC
Hello,

I encounter the following issue when I am trying to launch Darktable:
![DarkTable_Issue_Capture](https://user-images.githubusercontent.com/60297051/98675280-5715b000-235a-11eb-9287-8911cc6aa476.PNG)

You will find also the log which has been generated:
[darktable_bt_VURPT0.txt](https://github.com/darktable-org/darktable/files/5517286/darktable_bt_VURPT0.txt)

Darktable version:
- 3.2.1 - Windows 64

My configuration is the following:
- Windows 10 Family - v20H2
- OS version 19042.572
- Windows Feature Expereince Pack 120.2212.31.0
- Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz   2.50 GHz
- RAM 12,0 Go
- SSD 500 Go
- HDD 1 To
- Nvidia 1050 gtx - 2Go

Please note that this version was previously working correctly, may be the issue encountered is linked to some last window updates (e.g. security, ...)

Many thanks for your help and work

Brs

Michel

**Comment by parafin** [comment] 2020-11-10 13:07
Log is empty, so it's useless (it should contain a backtrace). A lot of issues on Windows are caused by Intel video drivers, you can search for these bug reports here (look for closed one too) and check if they match your configuration (drivers version). In these cases starting with --disable-opencl option helps.

**Comment by MythicMike** [comment] 2020-11-11 17:28
Thanks for your feedback,

Retested today with the option setting "--disable-opencl" --> it works.

However, if launched in the simple way, obviously, as mentioned above, the application crashes during the launch
In attachment the generated log file (I checked it is not empty).

Brs

Michel
[darktable_bt_KMRTT0.txt](https://github.com/darktable-org/darktable/files/5525700/darktable_bt_KMRTT0.txt)

**Comment by parafin** [comment] 2020-11-11 18:28
Looking at backtrace it's definitely the same Intel driver issue. So closing as a duplicate and not a darktable bug.

**Closed by parafin** 2020-11-11 18:28 UTC
