### ISSUE TITLE
Lighttable view shows some edited images with black patches

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#9577] opened 2021-07-20 12:57 UTC
M1 Mac Current release.

Seeing these black patches on images in lighttable view.

![Screenshot at Jul 20 18-17-08](https://user-images.githubusercontent.com/1119439/126327203-6a240466-ac8f-422a-9cc3-8bac198fdeae.jpg)

When the images are double clicked and opened in darkroom they appear fine in the main view and thumbnail in the filmstrip, but other images that that had black patches still have black patches in the filmstrip.
Clicking on other filmstrip with black patch image, opens the image fine and the image in the filmstrip clears the black patches.

**Comment by Nilvus** [comment] 2021-07-20 15:44
Please provide al infos needed asked in issue template as darktable version, OS used, graphic card, opencl activated or not, etc.

This could be a duplicate of #9399

**Comment by chhil** [comment] 2021-07-21 00:05
DT : 3.6.0.3
Build Type : Release.
OS : Big Sur
Architecture : M1 MAC
Opencl : On off doesn't matter. Though I don't even know if there is opencl on the M1 Mac Big Sur.

**Comment by chhil** [comment] 2021-07-21 00:19
For each of the images that had the black patches in lighttable (i.e. the thumbnail only, darkroom view was fine) I unchecked `click negative RGB from gamut` and checked it again. This got rid of the black patches in lighttable. 

There was this one image which had black patches in lighttable and darkroom, which did not remove the black patches. I had to disable denoise profiled module, which got rid of it, and reenabling it again did not bring them back, but the work around fixed my black patch issue.

**Comment by Nilvus** [comment] 2021-07-21 17:30
> For each of the images that had the black patches in lighttable (i.e. the thumbnail only, darkroom view was fine) I unchecked `click negative RGB from gamut` and checked it again. This got rid of the black patches in lighttable.
> There was this one image which had black patches in lighttable and darkroom, which did not remove the black patches. I had to disable denoise profiled module, which got rid of it, and reenabling it again did not bring them back, but the work around fixed my black patch issue.

This was so a duplicate of #9399. About denoise profile, you have your other issue so I close this one. Thanks.

**Closed by Nilvus** 2021-07-21 17:30 UTC
Labels: understood: unclear
