### ISSUE TITLE
Collection filters apply only to first collection

### ISSUE THREAD

**Issue by pasta-farian** [darktable-org/darktable#12174] opened 2022-07-15 02:27 UTC
**Did you buy darktable from an application store ?**

No

**Describe the bug/issue**

Collection filters apply only to the first collection

**To Reproduce**

1. In lighttable, Select a collection (film roll or folder) containing pictures with a variety of star ratings
2. Choose "add more images" to expand the selection to a second collection
3. Select a second collection, also containing pictures with a variety of star ratings
4. Set the range rating in collection filters to, e.g., 3 stars. 

You'll still see all the pictures from the second collection, regardless of their rating.

**Expected behavior**

You should only see pictures rated with 3 stars.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 4.0.0
* OS                : e.g. Linux - kernel 5.13.0-52
* Linux - Distro    : e.g. Ubuntu 20.04
* OpenCL installed  : no

**Comment by mlaverdiere** [comment] 2022-08-20 11:19
I'm also experiencing this (or a similar) problem I think: I'm using a collection preset to only retrieve RAW pictures (with various file extensions, like nef, dng and raf) with red colour label. Now, when I want to filter these pictures with the preset "no stars filter", some pictures with stars are still displayed (but some are discarded, so correctly filtered). I'm not sure yet, but the problem seems to be related to recently starred pictures...

I'm on darktable 4.0.0, with opencl on Fedora 36.

**Comment by mlaverdiere** [comment] 2022-08-22 11:00
After some more tests, I confirm that I can reproduce this issue. It's exactly like what is described by the OP: as soon as you have more than one collection selected (or more than one condition set in the collection module), the star filtering is not working. This is probably a regression, as I was not facing this problem in previous versions.

**Comment by dlobraico** [comment] 2022-09-26 02:35
Also seeing this issue on Fedora 36.

**Comment by pasta-farian** [comment] 2022-12-30 20:35
This appears to be fixed in 4.2

**Comment by victoryforce** [comment] 2022-12-31 07:03
@pasta-farian if this is not an issue anymore, please consider closing it.

**Comment by pasta-farian** [comment] 2022-12-31 16:34
I thought I had closed it. Trying again

**Comment by pasta-farian** [comment] 2022-12-31 16:35
Closing.

**Closed** 2022-12-31 16:35 UTC
