### ISSUE TITLE
"Mix" in Contrast Equaliser not getting stored in XMP

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#7550] opened 2020-12-29 23:24 UTC
3.4.0+dirty    Ubuntu 18.04

Suppose you've set Mix to something other than 1, and the module switched on, and hence you have an XMP which should have your value in it.  Now load this sidecar onto a different raw (in lighttable). Take the raw into darktable.  The Mix is 1 not the value you expect.  It's also 1 if you load it onto the original raw.

**Comment by ralfbrown** [comment] 2020-12-30 00:09
That's by design -- the "mix" value is applied directly to the coefficients set in the graph, and only the final, scaled coefficients are stored.
It's documented: https://darktable-org.github.io/dtdocs/module-reference/processing-modules/contrast-equalizer/

**Comment by johnny-bit** [comment] 2020-12-30 07:13
Mix is visual sugar in many places. Works as intended :) closing :)

**Closed by johnny-bit** 2020-12-30 07:13 UTC

**Comment by RawConvert** [comment] 2020-12-30 15:50
Ok,  I assumed Mix would be stored.  Contrast Equalizer does not seem to be included in the 3.4 PDF I recently downloaded from one of the announcement links.  Clearly it's in the "online" version.  The latter is better in my view because the modules are in alphabetical order.  Also the PDF has them by module group, presumably messy if the groups change.  How about making the PDF like the online manual?

**Comment by johnny-bit** [comment] 2020-12-30 15:52
Here's the usermanual PDF generated with new usermanual: https://www.darktable.org/usermanual/en/darktable_user_manual.pdf

**Comment by ralfbrown** [comment] 2020-12-30 15:53
As you will have seen in the announcement, there are currently two manuals in parallel (for English) as darktable transitions to the new manual I referred to.  You clearly downloaded a PDF of the legacy manual.
