### ISSUE TITLE
v3.4 "R"-key pressed BUG - full crash.

### ISSUE THREAD

**Issue by XAndrey** [darktable-org/darktable#7445] opened 2020-12-25 08:13 UTC
**Describe the bug**

In lighttable mode in full screen preview as Alt+W, i want to reject current foto: i have pressed "r" key and then i have crach window - see screenshot. It occurs every time!

**To Reproduce**

**Expected behavior**

As in older version - NO crash windows and preview next foto on screen.

**Screenshots**
![Darktable 3 4 new bug R key](https://user-images.githubusercontent.com/20306883/103127134-afea9f00-46a1-11eb-830b-ab9e5a52e7e7.jpg)

darktable.exe caused an Access Violation at location 00000000637C6382 in module libdarktable.dll Reading from location 0000000000000000.

[darktable_bt_I60GW0.txt](https://github.com/darktable-org/darktable/files/5741507/darktable_bt_I60GW0.txt)

[darktable_bt_U385V0.txt](https://github.com/darktable-org/darktable/files/5741506/darktable_bt_U385V0.txt)

[darktable_bt_X0F8V0.txt](https://github.com/darktable-org/darktable/files/5741504/darktable_bt_X0F8V0.txt)

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: Windows 7

**Additional context**

**Comment by johnny-bit** [comment] 2020-12-25 08:33
This is most likelly a culling mode bug, that's already fixed and being prepared for 3.4.1 release.

@AlicVB - can you confirm?

**Comment by Nilvus** [comment] 2020-12-25 15:19
And probably specific to Windows. I often use 'r' shortcut in culling or file manager mode and never had crash, in Linux.

**Comment by airflow2010** [comment] 2020-12-25 21:08
I just wanted to report a problem with reproducable crashes when "R"ejecting the last picture shown in culling mode. This sound similar, but it doesn't happen here when I'm in "W"-fullscreen-mode, just in culling. And yes, it's the Windows 3.4 version. The comment of @johnny-bit makes me hope it's the one he is referring to.

By the way, there is another change of behaviour of culling mode with this version, which I consider a bug: When I select a number of pictures which I like to cull (fixed zoom mode), I'm always starting *at the end* of the selection. Which is counter-intuitive (I'd like to start at the beginning, not the end) and which was behaving differently (correctly) in earlier versions.

**Comment by pahl34** [comment] 2020-12-26 17:12
I can confirm that there is a reproducible crash with dt 3.4 running on Windows, when using the 'R' shortcut in culling mode.
I am not sure whether it is the same problem originally described here.

For me, it is 100% reproducible this way:

1. Load a collection of images shot in RAW + JPG
2. Go to culling mode, fixed zoom, 2 images
3. Collapse grouped images
4. Set the View filter to "all except rejected"
5. Scroll with the mouse whell once so that images 2 and 3 of the film strip are shown.
6. Hover with the mouse over the *left* image (image 2 from the film strip) and press "R".

Interestingly, the crash does not occur if the grouped images are extended, or if in step 6 the right image (image 3 of the film strip) is rejected. The bug also does not occur in case the GUI button for reject is clicked with the mouse instead of pressing "R".

@XAndrey: Based on these Steps to reproduce, do you think this is the same bug? Especially, were you using culling and did you have grouped images collapsed when the crash occured?

I suggest to also read #6566, which was entered against dt 3.2.1 (win 10) and might be releated.

**Comment by XAndrey** [comment] 2020-12-26 21:24
> @XAndrey: Based on these Steps to reproduce, do you think this is the same bug? Especially, were you using culling and did you have grouped images collapsed when the crash occured?

Yes, indeed. It's in culling mode. Pictures was grouped raw+jpeg and collapsed. View filter was "all except rejected". Then i gone to full screen preview with Alt+W.  And then press "R". - it crashes.

**Comment by Nilvus** [comment] 2020-12-26 21:59
@XAndrey: and so do you have same crash with raw only, so not collapsed with jpg or other file?
Maybe there's something related to raw+jog collapsed.

**Comment by XAndrey** [comment] 2020-12-27 08:54
> @XAndrey: and so do you have same crash with raw only, so not collapsed with jpg or other file?
> Maybe there's something related to raw+jog collapsed.

Yes. It repeats only in raw+jpg collapsed and in full screen preview. In thumbs mode - no crash, if not collapsed group - no crash.

**Comment by pahl34** [comment] 2020-12-27 11:18
For me, this is reproducible *without* the Alt+W, as mentioned above.
I did a quick screencast of me reproducing this bug, sorry for the quality, used the first tool I could find on google. See attached.

I definitely think that this problem and similar problems are related to the grouped images. See the film strip issue (6566) I linked earlier - in that case I also discovered after a while that this was related to grouped images (which should narrow down the root cause quite strongly, I'd hope).

I can also kind of reproduce what @airflow2010 reported, although I am not 100% sure I understood his/her report correctly:
The bug as I described it above can be circumvented by skipping step 5 (mouse scrolling into the collection). Thus, if "R" is used on the very first image shown, then the crash does not occur. If then "R" is continously used, then finally, when removing the very last image, the crash also occurs.
@airflow2010: Did you have grouped images collapsed and the view filter "all except rejected" active when this happend to you?

**Just a guess:**
I would guess that all mentioned problems might share the same root cause. This root cause I would expect to be some problem with handling of grouped images in case they get removed from the currently shown set of images - maybe some invalid pointer when accessing the datastructure holding the currently shown images internally.

I am a bit surprised that this does not seem to happen under Linux, based on what @Nilvus writes - but I know too little about the differences of course and I fully respect that darktable is mainly developed for Linux.
I'll try to install Debian in Oracle Virtual Box when I find time and see if I can reproduce it there. If someone who has dt 3.4 already running under Linux should have time to try again

https://user-images.githubusercontent.com/60848211/103169620-a8f89380-483d-11eb-93d0-bd4a94dae5a0.mp4

 the steps 1-6 (or what can be seen in my video), this would of course also be very helpful. As I mentioned, for me this reproduces the crash 100%, so it should be quick to try out whether it also occurs under Linux.

**Comment by Nilvus** [comment] 2020-12-27 13:36
> I am a bit surprised that this does not seem to happen under Linux, based on what @Nilvus writes - but I know too little about the differences of course and I fully respect that darktable is mainly developed for Linux.

I never said that. Just read better. When I answer that could be specific to Windows, nothing before could say that it was RAW+JPG group related. So, not the same thing. And as I never import/use JPG in darktable (it's not for that for me), I of course can't reproduce... Since now we know it's related to RAW+JPG groups.

**Comment by pahl34** [comment] 2020-12-27 14:28
@Nilvus To be honest, what you write sounds quite offensive. I hope this is just a misunderstanding. I am sad to say that this is not the first time I read responses like this from a darktable Dev. I am also sad to say that this starts a bit to take away my motivation spending a lot of time on my error reports, as I did so far. 

To make it clear, I think that darktable is amazing and my only goal is to help. Nothing I ever write about an error should be taken personal or emotional (I personally think this is a general 'best practice' in SW development).

I was trying to be polite and defensive in my last post, but it looks like I failed.

I agree, you did not say that this is a Windows only problem. I just wanted to point again to the fact that we should double check on Linux. I don't know whether I find time for that, as my Debian setup failed and I have little free time.

**Comment by johnny-bit** [comment] 2020-12-27 14:36
@pahl34, @Nilvus & others - please assume no offence intended. English isn't many people's first (or 2nd or even 3rd) language learned and some things just get lost in translationg and in one languange might sound totally fine in english might sound offensive and vice versa.

So to limit this - we have reproducibility steps and I'll try to reproduce to best of my abilities using dt 3.4.0 as well as current master and report back.

**Comment by Nilvus** [comment] 2020-12-27 15:05
@pahl34: that was not my intend. So sorry if you see that that way. I had just thought you make a mistake by reading me and just wanted to avoid misunderstanding about what you answered and the fact it is not reproducible in Linux (there I don't know as I said ; what I can't reproduce was the first post of this issue and my answer was on that, not on complementary things precised after). It's not offensive of course and was not the purpose. Indeed, as @johnny-bit said, many of us (included me) are not english native speakers.

**Comment by pahl34** [comment] 2020-12-27 15:43
Okay, sorry then for the misunderstanding on my side! I should not have taken it personal myself.
Let's then get back to the real topic and wait for what @johnny-bit investigates. :-)

**Comment by airflow2010** [comment] 2020-12-27 19:12
I'd like to clarify how I trigger this bug, because it seems that it might even be simpler than the way @pahl34 describes it. For example, I don't use grouping/collapsing of pictures at all. I also don't have JPGs imported in darktable, just the RAW-files. The view-mode I use in lighttable and culling mode is "unstarred only", as this is the way my workflow is designed - in the beginning I rate the pictures "away" (until I sorted out which ones I'd like to keep and continue to edit) :-)

So my way of reproducing this bug is like this:

1. set view to "unstarred only"
2. in lighttable-view, select 2 pictures
3. change to culling-mode (fixed zoom, view is still on "unstarred only")
4. reject any one of the pictures (this works)
5. reject the other picture (darktable crashes)

**Comment by airflow2010** [comment] 2020-12-27 20:55
Additional remark: As there was some discussion whether this could be a "windows only"-bug, I wanted to find out, booted into my Linux-environment (Ubuntu 20.04) and installed darktable 3.4.0 via OBS. Result: **This is also happening with the Linux-version.**

**Comment by AlicVB** [comment] 2020-12-27 23:00
@airflow2010 : I'm not in a position to test anything actually, but what you describe in your last post is a known bug : if for any reason culling mode as no image to show at some point it crash.

The good news is that it's already fixed in master and will be included in 3.4.1

I think that the original bug raised by @XAndrey is the same too (culling and full preview use same code path) I'll try to test and confirm once back...

**Comment by techexo** [comment] 2020-12-30 14:52
Hello,
I come from #7503 (where you'll be able to find the crashes logs and the configuration). In my case, I have grouped RAW+JPEG that I reject both at the same time using the "rate_group" LUA script, while in full screen preview (Alt+W). The issues don't occur every time I reject, but were a bit random.
To sum up:
* I use the groups collapsed (so I have one thumbnail for two pictures)
* I use the explorer view (not the culling mode, if I understood correctly what that is)
* **I use the full screen preview, rejecting with `r` (group rejection with LUA script) and scrolling through the collection**
* I don't use any particular filter for my collection (like starred, unstarred and so on), so this is inconsistent with @pahl34 suggestion above, as they are not removed from my display or anything:

> This root cause I would expect to be some problem with handling of grouped images in case they get removed from the currently shown set of images

The issue could thus occur, in my opinion, because of a group rejection, or because of a rejection in full screen mode.

**Comment by AlicVB** [comment] 2020-12-30 15:56
I've tried hard to reproduce without success...
What I can say for now : 
1. @airflow2010 steps trigger another bug which is already fixed in master and will be in 3.4.1
2. the other bugs which involve grouping etc... *seems* different but I can't reproduce them :(
3. the backtraces doesn't help either as they lack important infos and their content doesn't make any real sens. I would say that the backtrace problem is specific to windows builds, So I hope that someone under linux manage to reproduce the bug and get a more useful backtrace
4. @pahl34 : your video show another small glitch : in the main view top triangles should be hidden. I'll take care

I don't know what I can do to go further... Eventually, what would be great is if one of you can do one of this : 
- try to reproduce on linux (and get a useful backtrace)
- try current master and see if the issue is still present

**Comment by johnny-bit** [comment] 2020-12-30 16:10
Cannot reproduce on current master on linux. (haven't had the time to test on 3.4.0 on linux)

**Comment by AlicVB** [comment] 2020-12-30 16:32
Hopefully, the bug is the same as the one I've already fix :)
... and just a precision : I've tried to reproduce on 3.4.0

**Comment by pahl34** [comment] 2020-12-31 12:42
I now tested on Debian 10 running in Oracle VirtualBox on my Windows 10 host.

I used again my own steps to reproduce:

1. Load a collection of images shot in RAW + JPG
2. Go to culling mode, fixed zoom, 2 images
3. Collapse grouped images
4. Set the View filter to "all except rejected"
5. Scroll with the mouse whell once so that images 2 and 3 of the film strip are shown.
6. Hover with the mouse over the left image (image 2 from the film strip) and press "R".

With darktable master (3.5.0~git273.1d772a434) I was not able to reproduce the crash.

With darktable 3.4 I was able to reproduce the crash. The backtrace:
[darktable_bt_UHA6V0.txt](https://github.com/darktable-org/darktable/files/5757267/darktable_bt_UHA6V0.txt)

I also tried the way described by @airflow2010 on current master and was not able to reproduce.

@AlicVB: It seems that the bug you fixed on master was indeed the same one. Does the backtrace maybe give a hint that this is indeed the bug you already fixed?

**Comment by AlicVB** [comment] 2020-12-31 17:15
@pahl34 : that's really great news ! indeed your backtrace point to the fixed bug.

I've thought at this issue again and I think we are combining the issue already fixed with another one which will be fixed by PR #7569 I'll mark this PR as fixing this issue.

@XAndrey @airflow2010 : once PR #7569 is merged, if you managed to reproduce with master or 3.4.1 once released, just ask to reopen.

Anyway, thanks for your help !

**Closed** 2020-12-31 17:47 UTC

**Comment by XAndrey** [comment] 2020-12-31 18:36
> 
> 
> @pahl34 : that's really great news ! indeed your backtrace point to the fixed bug.
> 
> I've thought at this issue again and I think we are combining the issue already fixed with another one which will be fixed by PR #7569 I'll mark this PR as fixing this issue.
> 
> @XAndrey @airflow2010 : once PR #7569 is merged, if you managed to reproduce with master or 3.4.1 once released, just ask to reopen.
> 
> Anyway, thanks for your help !

Is there any easy way to build windows 64bit exe? Because on download page no 3.4.1 version for Windows.

**Comment by johnny-bit** [comment] 2020-12-31 18:56
@XAndrey - there's no "3.4.1" released yet, just a 3.4 branch that has commits that will become 3.4.1

if you're feeling up to compiling - see https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.txt

**Comment by XAndrey** [comment] 2021-01-01 10:10
> 
> 
> @XAndrey - there's no "3.4.1" released yet, just a 3.4 branch that has commits that will become 3.4.1
> 
> if you're feeling up to compiling - see https://github.com/darktable-org/darktable/blob/master/packaging/windows/BUILD.txt

It looks like not an easy way :(

**Comment by naisanzaa** [comment] 2021-04-12 21:23
This happens on Mac M1 as well. Crashes whenever using 'R' in Lightroom to reject an image.

**Comment by pahl34** [comment] 2021-04-13 10:19
@naisanzaa : There is meanwhile a 3.4.1.1 Release that has a fix for this Bug.
