### ISSUE TITLE
Entering long strings in the metadata editor expands the entire right sidebar.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/darktable#9172] opened 2021-06-06 06:16 UTC
**Describe the bug/issue**
When a string is entered into a text box in the metadata editor that is longer than the width of the right sidebar, instead of the text wrapping to a new line, the entire right sidebar expands in width to match the contents of the text box, with a horizontal scrollbar appearing at the bottom.

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Select any image.
2. Type a long string into any text box in the metadata editor module.
3. Watch the entire right sidebar expand in size.

**Expected behavior**
The right sidebar's size remains the same and the text in the text box wraps to the next line.

**Screenshots**
Before entering the long string:
![Before](https://user-images.githubusercontent.com/3303477/120914514-4e712800-c664-11eb-9cdb-39148912be07.png)
After entering the long string:
![After1](https://user-images.githubusercontent.com/3303477/120914518-54ff9f80-c664-11eb-8735-c4a6433504d6.png)
![After2](https://user-images.githubusercontent.com/3303477/120914519-55983600-c664-11eb-9a85-eff177cc568b.png)

**Platform**

* darktable version : master revision efc30a4
* OS                : Linux
* Linux - Distro    : Fedora 34
* GTK+              : gtk3-3.24.29-1.fc34

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? Yes: Darktable 3.4.1.

**Comment by Nilvus** [comment] 2021-06-06 20:30
I never enter long strings in that module but I experience same thing with export module (especially when using Piwigo export part and enter a long server name. It's always possible to resize correctly the right sidebar after restarting darktable.

**Comment by phweyland** [comment] 2021-06-10 07:27
At some point dt_ui_scroll_wrap() has been introduced and may be concerned. Pinging @dterrahe. Any thought about this ?

**Comment by dterrahe** [comment] 2021-06-10 08:47
I'm not seeing this in 3.4.1 or my working branch (which is a few weeks old master) _if_ there are spaces in the long string. If there are _no_ spaces, then yes, the sidebar will expand/scroll to show the whole long "word".

This has only spaces, no new lines:![image](https://user-images.githubusercontent.com/1549490/121494361-954a7f00-c9d0-11eb-99c8-38a18bcb0e6a.png)

But in your screenshot there _are_ spaces, so I don't know why you are getting different behavior.

Wrapping is set with
`    gtk_text_view_set_wrap_mode(GTK_TEXT_VIEW(textview), GTK_WRAP_WORD);
`
It could (maybe _should_) be changed to `GTK_WRAP_WORD_CHAR` but that might not solve your issue...

**Comment by schwerdf** [comment] 2021-06-10 12:36
I first started noticing this when I upgraded to Fedora 34. On macOS, I get the same behavior as you (sidebar only expands when there are no spaces in the text).

**Comment by dterrahe** [comment] 2021-06-10 13:05
After upgrading my Debian from gtk 3.24.24 to 3.24.29 (from experimental repository) I'm starting to see the same behavior. In Windows/MSYS2 as well (which already carries 3.24.29).

So I would say it is a gtk regression somewhere in the layouting engine. I don't see anything obvious jumping out of the changelog just yet.

As expected GTK_WRAP_WORD_CHAR doesn't solve the issue.

**Comment by dterrahe** [comment] 2021-06-10 13:12
Maybe this one https://github.com/GNOME/gtk/commit/25879ea37e8918a28187dd382e7704051a38f011

**Comment by johnny-bit** [comment] 2021-06-10 14:27
Oh great. It's an upstream bug :/ @schwerdf - can you yell at them at https://gitlab.gnome.org/GNOME/gtk and link here please? :) and since I think there's nothing darktable can do here would you mind after that closing hte issue?

**Comment by schwerdf** [comment] 2021-06-10 15:55
Am I the best person to make a GTK bug report? I know nothing about GTK development or what part of GTK is at fault, so my bug report would amount to "Somewhere between versions 3.24.24 and 3.24.29, word wrap in Darktable text boxes started malfunctioning."

**Comment by johnny-bit** [comment] 2021-06-10 19:00
That's exactly what is needed :) and you're the first to notice so 😉

czw., 10 cze 2021, 17:55 użytkownik August Schwerdfeger <
***@***.***> napisał:

**Comment by Nilvus** [comment] 2021-06-10 20:05
So, if it's Gtk issue, we should so close this issue, as darktable team can't do anything on this.

**Comment by schwerdf** [comment] 2021-06-16 04:25
GTK bug report created: https://gitlab.gnome.org/GNOME/gtk/-/issues/4042

**Closed** 2021-06-16 04:25 UTC
Labels: bug: pending, bug: upstream, scope: UI

**Comment by johnny-bit** [comment] 2021-06-16 05:29
Thank you!
