### ISSUE TITLE
ILCE-7RM5

### ISSUE THREAD

**Issue by AidenKitamura** [darktable-org/darktable#13035] opened 2022-11-28 15:08 UTC
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

Hi, I uploaded 5 files named as follows:
A7R5-LosslessCompressedLarge5000kColorChecker
A7R5-LosslessCompressedMedium5000kColorChecker
A7R5-LosslessCompressedSmall5000kColorChecker
A7R5-LosslessUncompressed5000kColorChecker
A7R5-LossyCompressed5000kColorChecker

The 5 raw files are of the same target which is an x-rite color checker classic under 5000k light. All of them are shot using Sony 35mm GM f1.4 of 1/30s, iso 100 and f1.4 with WB manually set to 5000k.

**Comment by kmilos** [comment] 2022-11-28 15:17
Thanks for providing the samples missing in https://github.com/darktable-org/darktable/issues/12985

**Comment by LebedevRI** [comment] 2022-11-28 16:09
Thank you for the samples. But i must ask, what prompted you to provide color target shots?

**Comment by AidenKitamura** [comment] 2022-11-29 01:25
> Thanks for providing the samples missing in #12985
> 
> Any chance you can also provide the cropped raws?

Yes. Please let me know what are the requirements for the cropped raws. Currently I would only be able to provide cropped raws of LosslessUncompressed and LossyCompressed since the other 3 lossless compressed files are not even supported by adobe lightroom.

**Comment by AidenKitamura** [comment] 2022-11-29 01:29
> Thank you for the samples. But i must ask, what prompted you to provide color target shots?

Well, there are several reasons...
1. There are no legal issues with shooting color target.
2. There are no privacy issues with shooting color target.
3. It could be used to create camera color correction profile.

**Comment by LebedevRI** [comment] 2022-11-29 01:57
I agree that this is better than nothing,
but hopefully we've adjusted the wording
on RPU to discourage that in the future...

The problem is that these images e.g. make it really hard to e.g. verify crop.

**Comment by AidenKitamura** [comment] 2022-11-29 03:32
> I agree that this is better than nothing, but hopefully we've adjusted the wording on RPU to discourage that in the future...
> 
> The problem is that these images e.g. make it really hard to e.g. verify crop.

Sure, understood. Let me know if there's anything else I need to do.

**Comment by kmilos** [comment] 2022-11-29 06:54
> the other 3 lossless compressed files are not even supported by adobe lightroom.

They are not supported by darktable either, but don't see how that is relevant to the APS-C crop camera setting.

**Comment by AidenKitamura** [comment] 2022-11-29 07:00
> > the other 3 lossless compressed files are not even supported by adobe lightroom.
> 
> They are not supported by darktable either, but don't see how that is relevant to the APS-C crop camera setting.

Sorry I've misunderstood what you meant... I thought you want me to manually corp them. If it is the APS-C cropped raw that is needed, I will be taking them shortly after and will update here once I have updated these raws.

**Comment by kmilos** [comment] 2022-11-29 07:08
Yes, the RPU instructions should be clear that what is needed are combinations of _out of camera_ compression, size, and aspect ratio/crop.

**Comment by AidenKitamura** [comment] 2022-11-29 13:56
> Yes, the RPU instructions should be clear that what is needed are combinations of _out of camera_ compression, size, and aspect ratio/crop. Thanks.

Hi, uploaded the raw files named as follows:
1. A7R5-S35-LosslessCompressedMedium
2. A7R5-S35-LosslessCompressedSmall
3. A7R5-S35-LosslessUncompressed
4. A7R5-S35-LossyCompressed

Lossless Compressed Large is not support under S35 mode.

**Comment by deepbend** [comment] 2022-12-04 11:11
Hi I placed the request about 10 days ago, it is nice to see someone else has the same issue. My reply I got was "please do what the place holder text says to do". I did not understand this, and when I replied explaining this the next reply was "closed this as not planned" which I thought was very rude. It was a very cryptic message and presumed that the ticked had been removed.
I appreciate the work done and producing and maintaining the software but this is no excuse for treating people in this manner.
I have been forced to start using Rawtherapee as this works with the ARW file system though I still prefer Darktable.
Having followed this feed I now understand my camera better and what you need up loading. 
So do you want me to also upload files to you? I still have some questions though.
1. Can I use the link at the beginning of this feed.
2. Can I upload one file with all photo files in or do they have to be done individually.
3. Can it be any subject.
4. Do camera setting have to be identical for full and cropped images and do they need to be with same zoom setting and distance from the subject.
5. How long is it likely to be when the new version update will be released when I can use the ILCE-RRM5 files in Darktable.
6. How will this be communicated to users so they know when to perform an update.
Kind Regards
Howard

**Comment by kmilos** [comment] 2022-12-12 16:17
Please test the suggested PR, especially wrt the crop.

**Comment by LebedevRI** [comment] 2022-12-12 17:40
@AidenKitamura since crop was specifically requested by @kmilos i've accepted those uploads.
Please, consider (re-?) contributing both image sets, but taken in daylight.
It's really hard to tell if the crop is right, based on these samples.

**Comment by kmilos** [comment] 2022-12-13 10:18
@LebedevRI It's not only this one, but seems there are a few Sony cameras that can output an APS-C sized raw from a FF sensor (e.g. there is already both samples for ILCE-7S in the RPU db), so it's worth investigating whether a new mode (i.e. different crop) is needed in rawspeed for those:

https://github.com/darktable-org/darktable/issues/11494
https://github.com/darktable-org/darktable/issues/12064

**Comment by AidenKitamura** [comment] 2022-12-14 09:12
> @AidenKitamura since crop was specifically requested by @kmilos i've accepted those uploads. Please, consider (re-?) contributing both image sets, but taken in daylight. It's really hard to tell if the crop is right, based on these samples.

OK. I will redo both image sets using the same lens and manual settings on a tripod. In order to avoid any legal issues, I'll be taking photos beside some natural scenaries, and I could only do so at weekends. Will update once I've uploaded the new raws.

By the way, please let me know if you have any more specific requirements, e.g. turn off noise reduction, etc.

**Comment by LebedevRI** [comment] 2022-12-14 13:57
Thank you!

> By the way, please let me know if you have any more specific requirements, e.g. turn off noise reduction, etc.

Not particularly. Just do it at daylight, with low ISO.

**Comment by LebedevRI** [comment] 2022-12-23 13:11
> hi, just uploaded the new set.

Thank you for the contribution! Verified the 9-sample set replacing existing verified samples.

**Comment by LebedevRI** [comment] 2023-02-05 23:31
I believe this is supported in master now.

**Closed by LebedevRI** 2023-02-05 23:31 UTC
Labels: scope: camera support

**Comment by da-phil** [comment] 2023-02-15 22:22
I just compiled DT from master and tried to open a A7RM5 image and got the following result:
``````
1,6726 [rawspeed] (DSC00939.ARW) virtual rawspeed::RawImage rawspeed::ArwDecoder::decodeRawInternal(), line 146: Unsupported compression 7
[libraw_open] extensions whitelist: `cr3'
[temperature] failed to read camera white balance information from `DSC00939.ARW'!
     1,6788 [dt_imageio_export_with_flags] mipmap allocation for `unused' failed
[temperature] failed to read camera white balance information from `DSC00939.ARW'!
[temperature] `Sony ILCE-7RM5' color matrix not found for image
[temperature] failed to read camera white balance information from `DSC00939.ARW'!
[temperature] failed to read camera white balance information from `DSC00939.ARW'!
[colorin] could not find requested profile `standard color matrix'!
````

So there is still something missing?
I tried pictures from the camera review sample gallery on dpreview.com:
https://www.dpreview.com/sample-galleries/0641980724/sony-a7r-v-sample-gallery/5312848263

**Comment by kmilos** [comment] 2023-02-15 22:47
@da-phil For the umpteenth time: Sony lossless is currently not supported. Uncompressed and lossy compressed work.

**Comment by da-phil** [comment] 2023-02-16 10:57
> @da-phil For the umpteenth time: Sony lossless is currently not supported. Uncompressed and lossy compressed work.

thanks for the info and sorry for the dumb question :/
what is left to make the lossless format working? is there anything we can do to support this development?

**Comment by kmilos** [comment] 2023-02-16 11:12
> is there anything we can do to support this development?

No, unless you're a highly skilled C++ developer.

**Comment by da-phil** [comment] 2023-02-16 13:01
I'm doing software development in C++ for a living but usually don't have enough time for private coding projects currently :/ 
But once I own the camera (planned in the next few months) I really need to find a way how to deal with lossless format in DT...

**Comment by kmilos** [comment] 2023-02-16 13:14
> I really need to find a way how to deal with lossless format in DT...

There is a work in progress patch you can help test and improve: https://github.com/darktable-org/rawspeed/pull/386

> I'm doing software development in C++ for a living

Great, so you should be able to start figuring stuff out on your own then!
