### ISSUE TITLE
Lightroom crashes while rejecting groups of pictures - dt 3.4 win10

### ISSUE THREAD

**Issue by techexo** [darktable-org/darktable#7503] opened 2020-12-27 20:20 UTC
In darktable 3.4 on Windows 10, the program crashed repeatedly while sorting newly acquired pictures. It happens while using the "rate_group" lua script to reject groups of photos (`r`), while being in "zoom view" (shortcut `Alt+Z`).

**To Reproduce**
1. Enable using the script manager the last version of rate_groups script
2. Use the grouped view to have RAW + JPG compacted in groups
3. "Zoom" on a group of picture, and scroll through the following groups with the mouse
4. Reject some groups of pictures. After a while, error message appears.

**Expected behavior**
Nothing more than not crashing :)

**Logs**
[darktable_bt_1O1YV0.txt](https://github.com/darktable-org/darktable/files/5745105/darktable_bt_1O1YV0.txt)
[darktable_bt_2ZPYV0.txt](https://github.com/darktable-org/darktable/files/5745106/darktable_bt_2ZPYV0.txt)
[darktable_bt_E8P1V0.txt](https://github.com/darktable-org/darktable/files/5745107/darktable_bt_E8P1V0.txt)
[darktable_bt_KHAFW0.txt](https://github.com/darktable-org/darktable/files/5745108/darktable_bt_KHAFW0.txt)

**Platform:**
 - Darktable Version: 3.4
 - OS: Windows 10
 - OpenCL Activated
 - GeForce RTX 2060, driver Geforce 452.06

**Additional context**
 - Can you reproduce with another Darktable version?: I used this module before with darktable 3.0 & 3.2 and never had this issue
 - Did you compile Darktable yourself? If so which compiler was used, with what options?: No, I used the 3.4.0-win64 setup

**Comment by johnny-bit** [comment] 2020-12-28 06:58
Duplicate of #7445

**Comment by johnny-bit** [comment] 2020-12-28 07:04
Your logs look exactly like the logs from #7445 :) Please continue there, share your setup and replication steps :)

**Closed by johnny-bit** 2020-12-28 07:04 UTC
