### ISSUE TITLE
[3.4.0] aarch64 build failure (xmmintrin.h)

### ISSUE THREAD

**Issue by Germano0** [darktable-org/darktable#7428] opened 2020-12-24 15:00 UTC
darktable 3.4.0 Linux aarch64 build fails because it needs xmmintrin.h but it is a header is for x86 intrinsics
https://kojipkgs.fedoraproject.org//work/tasks/9767/58189767/build.log
https://koji.fedoraproject.org/koji/taskinfo?taskID=58189767

**Comment by parafin** [comment] 2020-12-24 15:12
It was caused by @johnny-bit in #6179, that include needs to be wrapped in #ifdef __SSE2__. Also there were already some fix for ppc about that, maybe it needs to be reviewed.

**Comment by TurboGit** [comment] 2020-12-24 15:19
Should be fixed in master and will be in 3.4.1.

**Closed** 2020-12-24 15:18 UTC

**Comment by Germano0** [comment] 2020-12-24 17:20
I successfully backported https://github.com/darktable-org/darktable/commit/d10c290fb3b47bbc8fd90d6d1d7935b900c1caf6 to 3.4.0 in Fedora
https://src.fedoraproject.org/rpms/darktable/blob/master/f/7428.patch

**Comment by TurboGit** [comment] 2020-12-25 08:26
Great ! Thanks for the feedback.
