### ISSUE TITLE
3.0.0rc0 MacOS 10.14.6 History stack losing adjustments.

### ISSUE THREAD

**Issue by blj86** [darktable-org/darktable#3340] opened 2019-11-09 02:49 UTC
**Describe the bug**
I will try to be as clear as I possibly can but this is quite odd.  I can reproduce it but I have no idea when it is going to happen.

When attempting to compare a previous image state with the current image state there seems to be an issue where all edits between the current image state and the clicked image state just completely remove themselves from the stack.

**To Reproduce**
I can't seem to narrow it down to a specific series of actions as it seems to feel like a somewhat random occurrence but I will do by best to explain.

1. Edit an image as you normally would.  In my case I move through my edit and often have to re adjust modules as I go to makes some tweaks here and there.
2. Make sure I have the top most entry in the stack selected then compress the stack.
3. Create snapshot of current image state.
4. Click the image state I want to compare against.
5. History stack seems to lose the edits at this point.

**Expected behavior**
I expect all edits between where I click earlier in the history stack and the actual current state of the image to stay intact unless I compress to remove those edits.

**Platform (please complete the following information):**
 - OS: MacOS 10.14.6
 - Version darktable 3.0.0rc0

**Additional context**
I am not sure if you guys will be able to reproduce or not.

This is a clean install of both MacOS (as I needed to get rid of Catalina) as well as a clean install of darktable 3.0.0rc0.  At no time was another version of darktable installed.

This issue seems to be random at when it happen but so far every 3.0.0rc0 edit I have tried to do has experienced this issue during the edit. 

I have tried to start darktable with the 
-d all
flag as I am not sure what I need to log specifically to get more information and currently having issues getting debugging to work.  Still trying.

**Comment by parafin** [comment] 2019-11-09 12:20
Yeah, I'm not able to reproduce this with a fast test... Not sure how to debug this issue.

**Comment by blj86** [comment] 2019-11-09 16:37
Agreed I was not able to find a swift way to reproduce either and I really tried.  It feels very random when it happens.  On discuss.pixls MStraeten has seen the issue happen as well but again really hard to reproduce easily.  Seems like occasionally if you back out of darkroom and go to lightable (before the random issue happens) it doesn't happen.  But I have now also have had it just not happen.

**Comment by Nilvus** [comment] 2019-11-13 09:32
@blj86 : some commits have been merged to fix some issues on history these last days. Your issue is probably solved. Could you check what behavior you now have with last master version ? If ok for you, think of closing this issue.

**Comment by blj86** [comment] 2019-11-13 13:12
@Nilvus I would say it is safe to close this issue.  This issue has proven to be very difficult to reproduce consistently even in the initial rc0.  I have not experienced the issue since the original report so hard to say what the cause was.  If it shows up again in the future we can always start a new report.

**Closed** 2019-11-13 13:15 UTC
