### ISSUE TITLE
Difference between NEF and DNG files

### ISSUE THREAD

**Issue by dortusermac** [darktable-org/darktable#14687] opened 2023-06-09 23:43 UTC
### Describe the bug

I noticed that the result of editing a NEF file vs a DNG (converted from the first one) is completely different. Even trying with many different modules I am not able to get the same results. The DNG file was generated using Adobe DNG Converter so I guess it keeps the same info as the original NEF out of the camera.

### Steps to reproduce

1. Import a NEF and a DNG file to RT.
2. Apply edit modules to NEF file
3. Copy the history stack from the NEF file to the DNG file

### Expected behavior

Give the same output coming from both files.

### Logfile | Screenshot | Screencast

![Screen Shot 2023-06-09 at 7 36 04 PM](https://github.com/darktable-org/darktable/assets/128921681/91045460-cda0-4df2-a199-cc67dd198b01)
![Screen Shot 2023-06-09 at 7 36 16 PM](https://github.com/darktable-org/darktable/assets/128921681/73cf057d-f695-4aa7-b99d-a2cb9418b470)
![Screen Shot 2023-06-09 at 7 36 24 PM](https://github.com/darktable-org/darktable/assets/128921681/ed34ac93-cefd-405b-9e07-f821a297cb1f)

### Where did you install darktable from?

darktable.org

### darktable version

4.0.0

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 10.15.7

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

![Z50_FromCamera](https://github.com/darktable-org/darktable/assets/128921681/166c314b-fc55-4a61-94cb-a9501a30f075)
![Z50_FromDNG](https://github.com/darktable-org/darktable/assets/128921681/106ddeac-eac8-4a55-949e-34ecb6a2dc94)
![Z50_FromNEF](https://github.com/darktable-org/darktable/assets/128921681/2f699166-99bf-4d84-a814-820fa9a7754c)

**Comment by ralfbrown** [comment] 2023-06-10 00:57
We'd need the NEF, DNG, and XMP files to properly diagnose.  Just from your screenshots, it looks like the DNG conversion is either applying the white balance coefficients to the raw data, or adjusting the white/black points.  So if you copy either of those settings from the NEF to the DNG, the colors will be off, because they don't match what's actually in the file.

**Comment by gi-man** [comment] 2023-06-10 11:41
> so I guess it keeps the same info as the original NEF out of the camera.

Why do you think this is the case?

**Comment by jenshannoschwalm** [comment] 2023-06-10 13:49
> ### Steps to reproduce
> 
>     1. Import a NEF and a DNG file to RT.
> 
>     2. Apply edit modules to NEF file
> 
>     3. Copy the history stack from the NEF file to the DNG file

I think you should have a deeper look into the manual ... 
1. This is `darktable` not `RT`
2. You should first try to understand what adobe converter does with your raw file. 
3. Basically this is a duplicate of many, many, many questions that all are about "Why isn't my image in darkroom looking like..."

**Comment by dortusermac** [comment] 2023-06-12 01:26
> > ### Steps to reproduce
> > ```
> > 1. Import a NEF and a DNG file to RT.
> > 
> > 2. Apply edit modules to NEF file
> > 
> > 3. Copy the history stack from the NEF file to the DNG file
> > ```
> 
> I think you should have a deeper look into the manual ...
> 
>     1. This is `darktable` not `RT`
> 
>     2. You should first try to understand what adobe converter does with your raw file.
> 
>     3. Basically this is a duplicate of many, many, many questions that all are about "Why isn't my image in darkroom looking like..."

Yes, sorry I wanted to sat DT instead of RT and I didn't know this is a duplicated topic. 
But just to clarify, my concern is not about  make my NEF image looks like the JPG, this is the topic I found many many times. I attached the 3 pictures and I am really pleased about the results in Darktable. My concern is about the DNG files only.
Thanks for your time anyway.

**Comment by dortusermac** [comment] 2023-06-12 01:28
> > so I guess it keeps the same info as the original NEF out of the camera.
> 
> Why do you think this is the case?

Because the DNG is a raw file in the sense that I can change the WB, but also if i open the NEF and DNG files in LR with same WB parameters I have exactly the same results.

**Comment by dortusermac** [comment] 2023-06-12 01:30
> We'd need the NEF, DNG, and XMP files to properly diagnose. Just from your screenshots, it looks like the DNG conversion is either applying the white balance coefficients to the raw data, or adjusting the white/black points. So if you copy either of those settings from the NEF to the DNG, the colors will be off, because they don't match what's actually in the file.

I attached the 3 files, NEF, DNG and JPG on top of the screenshots with the results after editing them in DT.

**Comment by ralfbrown** [comment] 2023-06-12 13:14
All of the  image files in your original post are JPEGs.

**Comment by jenshannoschwalm** [comment] 2023-08-12 03:00
closing for now as we can't analyse further without the files.

**Closed by jenshannoschwalm** 2023-08-12 03:00 UTC
Labels: no-issue-activity
