### ISSUE TITLE
Crop module will crop again if closed while working

### ISSUE THREAD

**Issue by emko** [darktable-org/darktable#11615] opened 2022-04-23 20:00 UTC
**To Reproduce**
add a crop
close crop module while it says working

If you close crop module while its 'working...'  it will crop your image again

**Screencast**
https://streamable.com/aoci97

* darktable version : 3.8.1
* OS                : Fedora 35
* Memory            :  32gb
* Graphics card     : 970
* Graphics driver   : Nvidia

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes, but less likely as 'working...' is really fast

**Comment by elstoc** [comment] 2022-04-23 20:06
I've seen this as well, usually when diffuse/sharpen is running and I expand crop by mistake (then immediately collapse).

@AlicVB any ideas?

**Comment by da-phil** [comment] 2022-04-24 11:10
Yup, can reproduce too, you just need to keep opening and closing the crop module

https://user-images.githubusercontent.com/810285/164973574-0304da9b-997b-4115-807b-b0c5fdeb143f.mp4

**Comment by jenshannoschwalm** [comment] 2022-04-26 05:33
Isn't this related to using `DT_SIGNAL_DEVELOP_PREVIEW_PIPE_FINISHED` ?

**Comment by AlicVB** [comment] 2022-04-29 17:07
I can't exactly reproduce as during dt is "working" the UI is blocked for me (so I can't play with other modules)
As this issue looks like #11668 can someone check if my PR #11686 fix that one too ? TIA

**Comment by elstoc** [comment] 2022-04-29 17:28
Nope. Still the same on current master (after merging your PR). Add a couple of longish-running "diffuse or sharpen" instances, crop the image and then just repeatedly expand/collapse the crop module:

https://user-images.githubusercontent.com/9555491/165993713-289ce84b-24f6-49e9-86c2-c8cbb3027433.mp4

**Comment by AlicVB** [comment] 2022-04-29 20:12
@elstoc : second try with PR #11689 if you can test it... TIA
I've finally managed to reproduce, I think, but the fact that there's heavy iop doesn't really matters for me (as, I repeat, my UI is stuck during long processing, I don't know why)

Here is the step I've done : 
- add diffuse & sharpen instance with preset "sharpen medium"
- wait for the pipe end (working msg disappear)
- open crop module and do some crop
- wait again
- unexpand crop module
- wait again => now the images seems to be loaded in cache, so not more "wait"
- click as a mad on the crop header to expand/collapse it very quickly
- At some point, I get the problem

**Comment by jenshannoschwalm** [comment] 2022-04-29 21:06
Well i definitely can reproduce.
If crop is enabled and the module is expanded, doesn't it trigger the `gui_focus()` *in* mode? In any case the callback is executed **after** the preview pipe is finished.

Wouldn't that be a problem if either
1. module header is de-expanded immediately (before preview pipe is finished)
2. immediately changing to another image - calling `gui_focus()` in *out* mode

so something like a race condition?

At least this seems to be so for me while investigating this

**Comment by jenshannoschwalm** [comment] 2022-04-29 21:18
About the non-responsive UI, isn't this so because of the status of the preview ready flag?

**Closed** 2022-05-01 09:41 UTC
Labels: reproduce: confirmed, scope: UI, bug: pending
