### ISSUE TITLE
Color balance RGB not included in Style panel

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#11423] opened 2022-03-29 11:50 UTC
Ubuntu 20.04   dt Build is   3.9.0+846~gab4f9caaf   built today
You create a style by clicking the icon next to "compress history stack" but the resulting panel has no entry for the above module despite it being switched on at the time.

**Comment by Nilvus** [comment] 2022-03-29 20:13
Try to be clearer in your issues and also respect template issue. It helps. I had read 2 times this one to understand correctly. A good step-by-step and clear is to respect template issue. And sometimes screenshot helps too. Thanks.

I update label as first time I launch and test, I didn't see color balance rgb style so I reproduced. But just first time. Now, even if I restart darktable or change image displayed, I always have color balance rgb.

@aurelienpierre: in case you have some idea about that as you add this module? Maybe a refresh issue first time create style dialog window is displayed?

**Comment by TurboGit** [comment] 2022-03-30 09:51
I cannot reproduce. So a step by step procedure would be nice.

**Comment by RawConvert** [comment] 2022-03-30 10:54
I can't reproduce either this morning. But @Nilvus & I have both seen it!  Perhaps some weird initialisation thing.

**Comment by TurboGit** [comment] 2022-05-05 11:38
No, cannot reproduce. I'll close this and we will revisit if a step by step reproducer is provided.

**Closed by TurboGit** 2022-05-05 11:38 UTC
Labels: understood: incomplete, reproduce: peculiar, bug: pending

**Comment by aurelienpierre** [comment] 2022-05-05 21:33
Anyway, modules are handled all the same as far as styles are concerned, there is nothing particular to this module.
