### ISSUE TITLE
Latest version 4.2.1 not available for Ubuntu 22.10 (Kinetic) using deb/apt package repository

### ISSUE THREAD

**Issue by julian-alarcon** [darktable-org/darktable#14074] opened 2023-03-31 08:42 UTC
**Did you buy darktable from an application store ?**

No, using Ubuntu APT repository.

**Describe the bug/issue**

**To Reproduce**

Set the apt repository https://download.opensuse.org/repositories/graphics:/darktable/xUbuntu_22.10/ . Try to install latest Darktable version, older version 4.0.1 is available.

**Expected behavior**

Darktable 4.2.1 should be installable

**Platform**

* OS                : e.g. 5.19.0-38-generic
* Linux - Distro    : e.g. Ubuntu 22.10

**Comment by TurboGit** [comment] 2023-03-31 08:49
Please report this to the Ubuntu maintainer we don't have a way to fix that. TIA.

**Comment by kmilos** [comment] 2023-03-31 08:50
The darktable.org project is not responsible for packaging for various Linux distros.

Please also search before opening new issues, as this is a duplicate of e.g. https://github.com/darktable-org/darktable/issues/11839

**Closed by TurboGit** 2023-03-31 08:49 UTC

**Comment by kmilos** [comment] 2023-03-31 08:53
See also https://discuss.pixls.us/t/are-the-obs-repos-for-darktable-dead/16928/99
