### ISSUE TITLE
Fujifilm X-H2 Support 

### ISSUE THREAD

**Issue by raphadasilva** [darktable-org/darktable#12703] opened 2022-10-24 07:02 UTC
Just downloaded a RAF file on https://raw.pixls.us/, and the database already contains samples.

If I can do anything more, tell me.

**Comment by kmilos** [comment] 2022-10-24 09:27
Duplicate of https://github.com/darktable-org/rawspeed/pull/382 and https://github.com/darktable-org/darktable/issues/12584.

> If I can do anything more, tell me.

Please search before opening new issues.

**Closed** 2022-10-25 16:43 UTC
Labels: duplicate, scope: camera support
