### ISSUE TITLE
Enabling Framing causes DT to crash

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3064] opened 2019-10-03 08:41 UTC
**Describe the bug**
During a session, framing was working and at one point framing started crashing DT on any image I tried to add a frame.
Ran dt with "-d all". The log file generated when it crashed on activating the framing module is attached.

[darktable-log.txt](https://github.com/darktable-org/darktable/files/3685133/darktable-log.txt)

The last line of the log has a path, this path doesn't exist on my system.
"file F:/msy80.s6459/ho46me/85"

Version : darktable-2.7.0+1933~g6e33f89a8-win64

OS : Win 10

Temporary Workaround :  Copy framing from a history of another image and paste it into the image from lightable view. This allows me to get into framing module and make changes if necessary.

**Comment by TurboGit** [comment] 2019-10-03 13:29
I cannot reproduce. Where is framing in the pipe?

**Comment by chhil** [comment] 2019-10-03 13:56
@TurboGit 
Tried it on another image that it crashed the app before.
It crashed it again.

Took a dup of the image and compressed its history to defaults.
![image](https://user-images.githubusercontent.com/1119439/66132812-46512180-e613-11e9-917a-8d0e56e0bf26.png)
Then enabled framing and poof dt crashes and disappears.
Since it was reproducible, I enabled logging. Right at the end are the following.
[darktable-log.txt](https://github.com/darktable-org/darktable/files/3686412/darktable-log.txt)


pixelpipe cacheline 0 used 3 by 1350452679623572522
pixelpipe cacheline 1 used 2 by 5394152556660471374
pixelpipe cacheline 2 used 0 by 7220456060753609582
pixelpipe cacheline 3 used 5 by 5348915782130753085
pixelpipe cacheline 4 used 4 by 4412357676228267234
cache hit rate so far: 0.111
48.105963 [dev_pixelpipe] took 0.011 secs (0.125 CPU) initing base buffer [full]
48.159956 [dev_pixelpipe] took 0.051 secs (0.375 CPU) processed `raw black/white point' on CPU, blended on CPU [full]
[dev_pixelpipe] module `framing' min: (0.000000; 0.000000; 0.000000) max: (1.205627; 1.071301; 1.094113) [preview]
Assertion failed: cache->size[k] >= size, file F:/msys64/home/chill/darktable/src/develop/pixelpipe_cache.c, line 153

**Comment by chhil** [comment] 2019-10-04 04:42
If it helps, the assertion happens because cache->size[k] is equal to size

**Comment by chhil** [comment] 2019-10-04 05:11
@TurboGit 
>Where is framing in the pipe?

I went and added the module and it shows up right at the end.  As soon as I enable it , it crashes.

![image](https://user-images.githubusercontent.com/1119439/66182573-455fd480-e693-11e9-9129-9c1097a625d5.png)

**Comment by chhil** [comment] 2019-10-04 11:13
Did a clean/kosher test.

Empty DB.
Imported raw files only and no xmp imported.
Selected an image , double clicked.
in darktable selected framing module and enabled it. It crashed.

The log still shows same error
Assertion failed: cache->size[k] >= size, file F:/msys64/home/chill/darktable/src/develop/pixelpipe_cache.c, line 153

**Comment by chhil** [comment] 2019-10-05 03:21
@TurboGit 

The crash on an **assert ** triggered the thought  process.
Builds that crash on framing are debug builds. The release one doesn't crash. 
Should this be of concern that it gets hidden in release builds?

**Comment by TurboGit** [comment] 2019-10-05 10:31
> If it helps, the assertion happens because cache->size[k] is equal to size

Looking at the assert it fails because cache->size[k] is inf to size.

Maybe you can add printf() before the assert to display both values and see what is happening? Maybe some non initialized values?

**Comment by chhil** [comment] 2019-10-05 10:40
@TurboGit 
>  cache->size[k] is inf to size

Don't understand what you mean by inf.


Line 153 : ` assert(cache->size[k] >= size);`
When I had debugged it, the values being equal trigger the assert.

**Comment by TurboGit** [comment] 2019-10-05 11:20
the assert(expression) means check that expression is TRUE otherwise stop with message.

So if the values are equal all should be fine we have ">=", that's what I suspected that cache->size[k] was inferior to size or the assert macro is quite broken.

**Comment by chhil** [comment] 2019-10-05 12:13
@TurboGit 
My apologies, you are right.... stepped through it...it crashes when its less. So right after whats shown in the image it crashes. 
I unfortunately don't know what its trying to do but when I enable framing, the size variable bumps up from what it was prior. The previous values of size and cache->size[k] were same and equal to the current value of cache->size[k] .

![image](https://user-images.githubusercontent.com/1119439/66254664-031fbb80-e797-11e9-85f4-27d4f8e66ac2.png)

**Comment by TurboGit** [comment] 2019-10-07 11:51
Should be fixed, the assert was in fact wrong.

**Closed** 2019-10-07 11:51 UTC
Labels: bug

**Comment by chhil** [comment] 2019-10-07 12:06
When DT is work in progress, which build would you recommend using , debug or release?

**Comment by TurboGit** [comment] 2019-10-07 12:47
I would say RelWithDebInfo a good compromise between Debug (slow and clean to be use with gdb) and Release (fast but cannot be debugged).

**Comment by chhil** [comment] 2019-10-07 13:05
Thank you. Will change the build type in my build.
