### ISSUE TITLE
Original of duplicated image shown in every film roll when collapse grouped images is on

### ISSUE THREAD

**Issue by rkowalke** [darktable-org/darktable#6980] opened 2020-11-19 07:10 UTC
**Describe the bug**
When mode **collapse grouped images** is **on** in lighttable and you then duplicate an image of some id (say 123), this image with id 123 is additionally shown in every other film roll. That issue still remains after trashing the duplicate and can only be solved by closing and restarting darktable.

**To Reproduce**
1. Go to 'lighttable'
2. Ensure that 'collapse grouped images' is on
3. Duplicate some image
4. Switch to any other film roll
5. Scroll down to the last image
6. Check the image id

**Expected behavior**
The image should be shown **only** in the associated film roll.

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+1698~g64cb5814e
 - OS: Manjaro Linux
 - OpenCL activated YES
 - NVidia GeForce GTX 750 Ti 

**Additional context**
If you first duplicate the image and then enable mode "collapse grouped images", everything works as expected.

![duplicate_image](https://user-images.githubusercontent.com/27403857/99633032-8acd9580-2a3e-11eb-9a6b-af91a8a67597.png)
![wrong_film_roll](https://user-images.githubusercontent.com/27403857/99633037-8c975900-2a3e-11eb-98c3-39138b289ebd.png)

**Comment by johnny-bit** [comment] 2021-06-13 13:47
No longer reproducible on `3.5.0+2526` :)

Closing :)

(if you do manage to reproduce on current master - please comment and I'll re-open immediately for further investigation. hopefuly the issue is fully fixed.)

**Closed by johnny-bit** 2021-06-13 13:47 UTC
Labels: no-issue-activity
