### ISSUE TITLE
Darktable 3.0.2 Immediately crashes with segmentation fault (Arch Linux)

### ISSUE THREAD

**Issue by cponce** [darktable-org/darktable#5864] opened 2020-08-03 15:27 UTC
this is darktable 3.0.2 reporting a segfault:

warning: Currently logging to /tmp/darktable_bt_AHBHO0.txt.  Turn the logging off and on to make the new setting effective.
#0  0x00007f70ddc87c3f in wait4 () at /usr/lib/libc.so.6
#1  0x00007f70ddea71f2 in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddbf73e0 in <signal handler called> () at /usr/lib/libc.so.6
#3  0x00007f7092fe2f29 in  () at /usr/lib/libclang-cpp.so.10
#4  0x00007f7092fe93b9 in clang::ASTStmtReader::VisitRequiresExpr(clang::RequiresExpr*) () at /usr/lib/libclang-cpp.so.10
#5  0x00005593305e3628 in  ()
#6  0x0000000000000000 in  ()

=========

  Id   Target Id                                       Frame 
* 1    Thread 0x7f70d7bfb040 (LWP 2845) "darktable"    0x00007f70ddc87c3f in wait4 () from /usr/lib/libc.so.6
  2    Thread 0x7f70d768b700 (LWP 2846) "gmain"        0x00007f70ddcb005f in poll () from /usr/lib/libc.so.6
  3    Thread 0x7f70d6e8a700 (LWP 2847) "pool"         0x00007f70ddcb571d in syscall () from /usr/lib/libc.so.6
  4    Thread 0x7f70d6689700 (LWP 2848) "gdbus"        0x00007f70ddcb005f in poll () from /usr/lib/libc.so.6
  5    Thread 0x7f70d5bf7700 (LWP 2849) "worker 0"     0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  6    Thread 0x7f70d53f6700 (LWP 2850) "worker 1"     0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  7    Thread 0x7f70d4bf5700 (LWP 2851) "worker 2"     0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  8    Thread 0x7f70bffff700 (LWP 2852) "worker 3"     0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  9    Thread 0x7f70bf7fe700 (LWP 2853) "worker 4"     0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  10   Thread 0x7f70beffd700 (LWP 2854) "worker 5"     0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  11   Thread 0x7f70be7fc700 (LWP 2855) "worker 6"     0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  12   Thread 0x7f70bdffb700 (LWP 2856) "worker 7"     0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  13   Thread 0x7f70bd7fa700 (LWP 2857) "kicker"       0x00007f70ddc82571 in clock_nanosleep@GLIBC_2.2.5 () from /usr/lib/libc.so.6
  14   Thread 0x7f70bcff9700 (LWP 2858) "worker res 0" 0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  15   Thread 0x7f70a7fff700 (LWP 2859) "worker res 1" 0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  16   Thread 0x7f70a77fe700 (LWP 2860) "worker res 2" 0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  17   Thread 0x7f70a4c7d700 (LWP 2863) "darktable"    0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0

=========

Thread 17 (Thread 0x7f70a4c7d700 (LWP 2863)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70d438e469 in  () at /usr/lib/beignet//libcl.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 16 (Thread 0x7f70a77fe700 (LWP 2860)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb715e in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 15 (Thread 0x7f70a7fff700 (LWP 2859)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb715e in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 14 (Thread 0x7f70bcff9700 (LWP 2858)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb715e in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7f70bd7fa700 (LWP 2857)):
#0  0x00007f70ddc82571 in clock_nanosleep@GLIBC_2.2.5 () at /usr/lib/libc.so.6
#1  0x00007f70ddc87e87 in nanosleep () at /usr/lib/libc.so.6
#2  0x00007f70ddc87dbe in sleep () at /usr/lib/libc.so.6
#3  0x00007f70ddeb6d0b in  () at /usr/lib/libdarktable.so
#4  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7f70bdffb700 (LWP 2856)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb8499 in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7f70be7fc700 (LWP 2855)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb8499 in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7f70beffd700 (LWP 2854)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb8499 in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7f70bf7fe700 (LWP 2853)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb8499 in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7f70bffff700 (LWP 2852)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb8499 in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7f70d4bf5700 (LWP 2851)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb8499 in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7f70d53f6700 (LWP 2850)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb8499 in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f70d5bf7700 (LWP 2849)):
#0  0x00007f70ddba8e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f70ddeb8499 in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f70d6689700 (LWP 2848)):
#0  0x00007f70ddcb005f in poll () at /usr/lib/libc.so.6
#1  0x00007f70dd98a168 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f70dd93ac03 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007f70dcdc31a8 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007f70dd964511 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f70d6e8a700 (LWP 2847)):
#0  0x00007f70ddcb571d in syscall () at /usr/lib/libc.so.6
#1  0x00007f70dd984c9b in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007f70dd90c803 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007f70dd968d5b in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007f70dd964511 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f70d768b700 (LWP 2846)):
#0  0x00007f70ddcb005f in poll () at /usr/lib/libc.so.6
#1  0x00007f70dd98a168 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f70dd93b221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f70dd93b272 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007f70dd964511 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f70ddba2422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f70ddcbabf3 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f70d7bfb040 (LWP 2845)):
#0  0x00007f70ddc87c3f in wait4 () at /usr/lib/libc.so.6
#1  0x00007f70ddea71f2 in  () at /usr/lib/libdarktable.so
#2  0x00007f70ddbf73e0 in <signal handler called> () at /usr/lib/libc.so.6
#3  0x00007f7092fe2f29 in  () at /usr/lib/libclang-cpp.so.10
#4  0x00007f7092fe93b9 in clang::ASTStmtReader::VisitRequiresExpr(clang::RequiresExpr*) () at /usr/lib/libclang-cpp.so.10
#5  0x00005593305e3628 in  ()
#6  0x0000000000000000 in  ()
[Inferior 1 (process 2845) detached]

**Comment by parafin** [comment] 2020-08-03 15:36
duplicate of #5842

**Closed by parafin** 2020-08-03 15:36 UTC
