### ISSUE TITLE
Panasonic DC-TZ200D

### ISSUE THREAD

**Issue by Phm92190** [darktable-org/darktable#15757] opened 2023-11-27 18:12 UTC
Raw samples have been uploaded to https://raw.pixls.us/ !

Raw images are displayed in the lighttable view (rw2 format is correctly recognized) but cannot be opened in the darkroom view due to lack of white balance file

I tend to think that this camera is very similar to my previous one, TZ101, which is handled by darktable

**Comment by LebedevRI** [comment] 2023-11-27 18:19
@Phm92190 thank you for contributing the samples!

**Comment by kmilos** [comment] 2023-11-27 18:23
Duplicate of https://github.com/darktable-org/darktable/issues/14963 and https://github.com/darktable-org/rawspeed/pull/509

Should already be working in the development builds, and planned for the next release.

**Closed by kmilos** 2023-11-27 18:23 UTC
Labels: scope: camera support
