### ISSUE TITLE
Duplicates not showing up in darkroom filmstrip

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7147] opened 2020-12-01 03:48 UTC
Current master 3.3.0+1931~g4d0071658

Duplicates not showing up in filmstrip. See duplicates have 2 images, while filmstrip shows only 1. Maybe be related to recent grouping changes.

![image](https://user-images.githubusercontent.com/1119439/100694791-c27cfb80-33b5-11eb-9ef3-972dd1c7e684.png)

**Comment by chhil** [comment] 2020-12-01 03:52
Filter was tag based in lighttable. The dup did not have the tag so was not being displayed.

Should dups have tags copied when dup made?

**Comment by ptilopteri** [comment] 2020-12-01 04:00
in my experience and in the test I just made the dup's have same tags
even if I opt for "original".

**Comment by chhil** [comment] 2020-12-01 04:20
Maybe some fringe case. It has always worked and continues to work with tags being copied. I don't know how I ran into this scenario.

**Comment by Nilvus** [comment] 2020-12-01 08:36
Press group icon on top right bar (next star, help and prefs icons) to show clones or hide them. Same behavior as on lighttable.

**Comment by chhil** [comment] 2020-12-01 09:01
I never enable my group icon , this makes sure all my dups always get displayed, except in this odd case I ran into that I reported.

**Comment by Nilvus** [comment] 2020-12-01 09:27
Maybe, but on my side, I have duplicates in filmstrip or not regardless of group icon state, as wanted and normal behavior. What's your group icon state? I use same master as you just one commit below but commit more you have is a language update.

**Comment by chhil** [comment] 2020-12-01 09:57
It happened only  for this one image :)
What I see is the duplicate is the 3rd one, probably 2 prior ones were deleted. 

Image was edited a few days ago , a few  of master builds ago, maybe 3 days ago.

**Comment by chhil** [comment] 2020-12-04 02:05
Happened again...

Lighttable the selected image has a duplicate. 
See grouping icon, it's not enabled for collapse.
See the tag filter.
![image](https://user-images.githubusercontent.com/1119439/101111505-568ed300-3601-11eb-8843-cef537e287e1.png)

Darkroom view that shows duplicate but not present in filmstrip
![image](https://user-images.githubusercontent.com/1119439/101111665-a79ec700-3601-11eb-8f7d-65915a9ece68.png)

Now I set filter to show the filename and you can see the dup that was created using original. The tags are not there in the dup causing it to not get displayed.
![image](https://user-images.githubusercontent.com/1119439/101111916-3875a280-3602-11eb-95c3-37bdd0e49716.png)


Note : If I remove the dup and start afresh, it works fine.

**Comment by johnny-bit** [comment] 2020-12-31 21:27
This sounds not like a filmstrip or lighttable problem, but something about duplicate not always coping a tag? or not refreshing it?

**Comment by johnny-bit** [comment] 2021-06-25 20:37
Tested it to hell and back (with various tags, heavy or not so heavy filtering etc) and couldn't reproduce on `3.7.0+1~g05bdc45ac` so I'd consider this issue "fixed".

Closing this for now - if you manage do reliably reproduce or reproduce enough to be concerned please comment so we can test further.

**Closed by johnny-bit** 2021-06-25 20:37 UTC
Labels: no-issue-activity
