### ISSUE TITLE
Version 3.6.01 for windows doesn't import exif data 

### ISSUE THREAD

**Issue by MatteoS5** [darktable-org/darktable#9567] opened 2021-07-19 13:52 UTC
Hi I started using darktable for windows with version 3.4 and I have not encountered any problems.
After upgrading to version 3.6 I noticed that when adding or copying images to the library the exif data is not imported and if I save the image it is saved without exif.
It also no longer recognizes my camera (Fujifilm S5pro) for importing files directly from darktable although I have installed zadig as suggested. (which instead worked fine with the previous version. 

Camera Fujifilm finepix S5pro
System windows 10 home 64 bit
download from www.darktable.org

Thanks so much

**Comment by kmilos** [comment] 2021-07-19 15:50
The Exif problem seems to be a regression in exiv2.

Don't know if that's related to the import problem or not...

**Comment by Nilvus** [comment] 2021-07-19 18:26
I doesn't have this issue on my side and I use an old Exiv2 library release. So this should probably be related to Exiv2 indeed. I let this open in case someone else see another thing about that issue.

**Comment by kmilos** [comment] 2021-08-06 07:28
The fix for this regression has been merged upstream, should you want to [patch your exiv2](https://github.com/Exiv2/exiv2/pull/1796/files#diff-bd28aafd4c87975a3a236af74c2200db447587fa0bb4f43ba9beb98738c77b2a) in the meantime.

**Comment by johnny-bit** [comment] 2021-08-06 11:15
I see that the issue is fixed on exiv2 side and it looks like 0.27.5 is planned to be released on 30th sep 2021...

If we were to have 3.6.1 release packaged before that should we add *known bugs* that if package is build with exiv 0.27.4 the issue with RAF files might pop up or recommend building with 0.27.3?

**Comment by kmilos** [comment] 2021-08-06 11:37
Either is ok... Might as well prefer w/ 0.27.3 as CR3 support is not merged in yet.

**Closed** 2021-12-02 21:56 UTC
Labels: bug: upstream, no-issue-activity
