### ISSUE TITLE
Recently used collections don't show recent film rolls anymore.

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#11747] opened 2022-05-07 12:56 UTC
First of all, the new collection filters is completely over-engineered, no offense to whoever did that, but it's just taking too much space for functionality that I never needed before, and it just overall feels like progress (or the attempt thereof) just got once again in the way of productivity.

But now, the recently used collections module is only showing collection filters, and not film rolls:

![Screenshot_20220507_145319](https://user-images.githubusercontent.com/2779157/167255413-7d5afa1a-9e45-45fc-9588-d6d67057b3bd.png)

That is very annoying.

**Comment by elstoc** [comment] 2022-05-07 13:09
I agree about the new filters. I don't know why you still have "recently used collections" though. I thought this was removed now.

**Comment by aurelienpierre** [comment] 2022-05-07 13:16
Ok so I found out about the "history" button in collections module, and it's just adds another click to access something I need very often.

Can we please revert to the "recent collections" module, remove that useless history button sitting alone on its row, and have recent collections always one click away ? I can live with the filters module collapsed forever, but the current state is too much real estate is lost to cosmetics with degraded functionality.

**Comment by aurelienpierre** [comment] 2022-05-07 13:18
BTW the "filters" module just feels like it should have been a popup window triggered from a contextual right-click menu in the filter toolbar.

**Comment by AxelG-DE** [comment] 2022-05-07 14:15
This module of the filter bar on top of the image collection has some odity:

to reproduce, do the following:
1) click on 1 star
2) now select 3-4 star and you get:
![image](https://user-images.githubusercontent.com/49004103/167257845-80def5bc-eb4b-4396-a435-4c1fe4e2e5c9.png)
I assume, this is the correct one

NOW
3) click on1str or 2star (to definitely unselect former selection) and subsequently on three star
4) select a range from three star to 4star and you get:
![image](https://user-images.githubusercontent.com/49004103/167257878-cec83650-af85-469c-9c42-ccce7ba03279.png)
- see the holow 3rd star?
- this is odd to me...

if it is on me: 
- those guys who like the "collection filters module" may have it on the left bar
- for those who where fine with the filter selection on top of the image collection for almost decades (me since dt 1.x), I want to have the old and very intuitive (yes, THAT bad word) filter bar back: 
![image](https://user-images.githubusercontent.com/49004103/167258029-68222786-5331-4850-94e4-8f0db572489f.png)


For me it is like a classical odometer with a real gauge rather than that modern digital bullshit. I can see the pointer, without actually looking there, but digital, I need to pay 100% attention and even move my head fully towards it to see...

**Comment by elstoc** [comment] 2022-05-07 14:17
I also preferred the simplicity of the old bar and found it easier to read.

**Comment by AlicVB** [comment] 2022-05-07 15:46
Well... its me :)

Now, tbh, I'm quite confuse. I started this huge work months ago. everything has been transparent in the process, There was issues to solve with the previous situation and feature to add (see the many issues and FR about that or the very long PRs)

Current implementation has been a group work, fully transparent. I've tried hard to please and to take account of as much comments as I can. If you read back the huge thread corresponding to the 2 PR #11066 and #10733, you'll see that things have take long time to settle... because it's a very difficult and tedious task...

And now that it has land into master, at less than 1 week from freeze... no, we can't go back, I'm sorry. The only way forward imho is to improve the current implementation... and you all know (I hope) that I'm ready to do that ;)
So, please... invest some time to use and learn (easy) the new filtering module... take account of all that it solve and allow... and propose some enhancements based on that...

I'll reply to individual issues in next msg...

(PS : I'm sorry to be so rude, but I daily face "that was better before" remarks and injunction in my real work... and that's just nonsense... done by people that (on purpose or not) ignore the reality and how the real world has changed)

**Comment by AlicVB** [comment] 2022-05-07 16:09
> Ok so I found out about the "history" button in collections module, and it's just adds another click to access something I need very often.

Some wanted to put the history in the hamburger menu... as it can be seen as some sort of "automatic" preset. I've finally preferred to put it here, more visible, to avoid hiding that functionality.
To mitigate the issue, you can affect a shortcut to directly show the history list under your cursor, that even avoid you to move your mouse (and your eyes)



> * see the holow 3rd star?

That's typically a bug... of course not done on purpose... I'll take care






> * those guys who like the "collection filters module" may have it on the left bar

and managing 2 paths in the code ? and keeping 2 different UI for doing the exact same things ? (I've already found, fixed issues, reduce the amount of duplicated code during my work on that point)
Not to speak that lot of people involved in the discussion has request to be able to have the filters available in the top bar to be able to work with closed panels (which is legitimate)




> * I want to have the old and very intuitive (yes, THAT bad word) filter bar back

We already had this discussion some days ago... and @Nilvus and I have already answer that exact point... To resume, you can get everything you had before, and more, with no added click...



> I also preferred the simplicity of the old bar and found it easier to read.

and for me (and others) that's the contrary ;)
we also have to keep in mind that current implementation has been done to take a little less space horizontally, in order to let user put many filters in the top bar...

**Comment by AlicVB** [comment] 2022-05-07 17:48
@AxelG-DE : see #11751

**Comment by aurelienpierre** [comment] 2022-05-07 18:00
> Now, tbh, I'm quite confuse. I started this huge work months ago. everything has been transparent in the process, There was issues to solve with the previous situation and feature to add (see the many issues and FR about that or the very long PRs)

I'm sorry but I saw none of either the PR nor the FR.

> (PS : I'm sorry to be so rude, but I daily face "that was better before" remarks and injunction in my real work... and that's just nonsense... done by people that (on purpose or not) ignore the reality and how the real world has changed)

The previous state of things was a simple solution to a simple problem. The current state of things is a bulky complicated solution to… what problem exactly ? It's not a matter of old stuff being better, it's a matter of keeping simple tasks simple and efficient, which current approach fails at. 

Not to mention the redundancy of the feature… We used to have one vertical toolbar, now we have that plus a full widget in sidebar.

> Some wanted to put the history in the hamburger menu... as it can be seen as some sort of "automatic" preset. I've finally preferred to put it here, more visible, to avoid hiding that functionality.

But why, oh why, delete the recently used collection module ? The current way takes a full line-height for the button, that's as much as the old module once collapsed, which had the option of staying open all the time for frequent use.

**Comment by AxelG-DE** [comment] 2022-05-07 19:17
> no, we can't go back, I'm sorry. 

Is it?
Not a convincing statement to me.

**Comment by Nilvus** [comment] 2022-05-07 19:43
I'm quite surprised here.

> I'm sorry but I saw none of either the PR nor the FR.

PR's from @AlicVB have been draft here for nearly 3 months!
And I'm quite suprised @elstoc by your reactions here as you answer on those PR and I don't remember that you say something near what we have here.

About FR, there's no direct FR but some statement from some users about:
- actual filters on collections too complicated. And math boolean symbols are not easy to understand for not maths or developer users
- multiple people ask to add filters they want on top bar (was in a PR from @phweyland as I remember where he add search field and color labels icons
- and I probably forgot some

> The previous state of things was a simple solution to a simple problem. The current state of things is a bulky complicated solution to… what problem exactly ? It's not a matter of old stuff being better, it's a matter of keeping simple tasks simple and efficient, which current approach fails at.

Seems that was not so simple for all people (I don't talk about me, old way and new way are good for me. They all have advantages and disadvantages).
Anyway, you could of course dislike that but your way is not the only good way. The only thing is that it takes more place but it's quite more powerful for me. I find some selections/filters that could be done quicker with new way (the opposite is also true).

> Not to mention the redundancy of the feature… We used to have one horizontal toolbar, now we have that plus a full widget in sidebar.

This is explained in PR by @AlicVB. The goal is not to kept both. But how do you allow with that horizontal toolbar to:
- simply add filter to top bar (as I said, asked by multiple people)
- allow users to better understand boolean (so by removing them and use and/or...)
- fix actual not intuitive way to select one or multiple lines in treeview with "old" filters (I call that not intuitive because shortcut are needed, ctrl for some things, shift for others ; and that come back to another issue you open today!)

> But why, oh why, delete the recently used collection module ? The current way takes a full line-height for the button, that's as much as the old module once collapsed, which had the option of staying open all the time for frequent use.

As I don't use it, I will just answer that I even didn't see the need of this one (even if I understand that some need it). This module was space lost for me. And a bad UI.
Just to say that we all have different ideas, views of what's good or not. This need to be take care of. And I don't see that on that issue. I would like to read more constructive things and suggestions to improve what that work adds.

**Comment by Nilvus** [comment] 2022-05-07 19:47
> > no, we can't go back, I'm sorry.
> 
> Is it? Not a convincing statement to me.

Sorry but I don't see convincing statement against too. And you just make confusion (about stars filters) between intuitive (or not) and habit (always hard to change).

I'm quite sad to see all those hard answers here, without real constructive one.
@AlicVB work was nearly 3 months of hard work, many comments and answer, none of this way. I'm even quite surprised that it's not discouraged here to work on darktable.

Maybe there's better ways to fix what his work (and mine for fine-tuning his UI) try to fix/improve. But I never see, nor in comments on his PR, nor here, any other solution proposed.

**Comment by AxelG-DE** [comment] 2022-05-07 19:52
>  But I never see, nor in comments on his PR, nor here, any other solution proposed.

I proposed very clearly, I want to have previous, simple, working, intuitive filter line back, as it was.

Sorry, your statement is disregarded.

**Comment by Nilvus** [comment] 2022-05-07 19:55
> > But I never see, nor in comments on his PR, nor here, any other solution proposed.
> 
> I proposed very clearly, I want to have previous, simple, working, intuitive filter line back, as it was.
> 
> Sorry, your statement is disregarded.

That is because not all are agree with you. And here I don't talk only about stars filters.

**Comment by elstoc** [comment] 2022-05-07 20:04
> I'm quite sad to see all those hard answers here, without real constructive one

I'm afraid I stopped contributing to the other PR (the collect rewrite) for that very reason - I found it hard to make constructive contributions because I wasn't sure how it could be improved. I wasn't the biggest fan of the new functionality (I think I did comment in that direction at least once) but I didn't have better ideas and it's really hard to make such contributions without something better to suggest, especially because it seems ungrateful when someone has put in so much work. Doesn't necessarily make such opinions wrong though. 

I guess it's easier when someone else starts the ball rolling. I really don't want to offend anyone and I am grateful for all contributions, but some things don't necessarily need improving, and I prefer simple to easy-to-use. When it comes to UI, intuitive is not a dirty word.

**Comment by AlicVB** [comment] 2022-05-07 20:07
Ok, let's go forward... I fear this issue is going nowhere
I'll close this issue
- the original problem has been fixed (a lib not remove from build directory)
- I've open a FR with a proposal for the collection history
- the bug on the rating is fixed and merged in master

That is *not* an attempt to avoid any controversial discussion, if you want to open other issues, FR, please do it, as usual. but stay constructive and state clearly what is the problem for you, in your workfow, etc...
esp. @AxelG-DE : you're concern about the visual and intuitivity of the rating filter may deserve an issue.

**Closed by AlicVB** 2022-05-07 20:07 UTC
Labels: controversial

**Comment by Nilvus** [comment] 2022-05-07 20:10
Thanks @elstoc for this clear answer. I understand. A really good reason so!
I agree that intuitive is not a dirty word. But be careful where and how we use it. Just that.

**Comment by TurboGit** [comment] 2022-05-07 20:20
> I proposed very clearly, I want to have previous, simple, working, intuitive filter line back, as it was.

To be fair most people don't like changing or moving forward. I do feel that @AlicVB work is going on the right direction and it will get time to stabilized and pleased everyone. We cannot rework such big piece of code without some "issues", moving forward is the only way.

That's remind me all the haters about the new GNOME 3.0 when it comes out and now look around how good and complimentary are the comments. We could also talk about the systemd introduction to replace init.d and also the pulse audio.... So many hard comments on those projects at the beginning and now almost no one will revert to something else just because people don't like changing or seeing things differently.

Let's some time for all this to stabilize please and be constructive.

**Comment by elstoc** [comment] 2022-05-07 20:28
> To be fair most people don't like changing or moving forward

That's true, but while newer is sometimes better, it's also sometimes not better, or even worse. Saying "you just don't like change" is too easy a way to dismiss criticism you don't like and justify a decision that's already been made.

**Comment by Nilvus** [comment] 2022-05-07 20:33
> That's true, but while newer is sometimes better, it's also sometimes not better, or even worse. Saying "you just don't like change" is too easy a way to dismiss criticism you don't like and justify a decision that's already been made.

I agree but the opposite is also true. Nothing simple here. The thing here is not to dismiss criticism but have constructive one. And we have not real one by now. That's why @AlicVB open a new issue to try to have some. If there's a way to please anybody, I would like to know it. Seems that by now, it's not found.

**Comment by elstoc** [comment] 2022-05-07 20:39
I'm open to suggestions on how to make negative comments about things without offending people - I do usually just stay silent, but that occasionally leads to things being merged that I'd prefer hadn't been. Sometimes people have to be able to express negative opinions without being required to suggest an alternative, and I'm not sure how to do that because such comments are so often dismissed with "that's not constructive". What if "do nothing" is a better solution than "do something"? That's still a valid comment sometimes.

**Comment by TurboGit** [comment] 2022-05-07 20:52
> I'm open to suggestions on how to make negative comments about things without offending people

That's not simple I agree. But the first step is to use the actual new way for some time to see if you can get to it. All new comers to darktable have a quite long time of learning. That was the case for us when we started using darktable. That's the case for us too each time we rethink part of darktable. As we are all adult we will certainly converge to something better than what was done before even if the first step is not fully correct and has issues. At least that had always been the case until now, so let's keep faith on our way to discuss and find proper solutions.
