### ISSUE TITLE
Title field not set when exporting

### ISSUE THREAD

**Issue by Aurelien-yeu** [darktable-org/darktable#2917] opened 2019-09-06 16:09 UTC
When exporting to JPEG 8bits quality 100%, sometime exported files does not have 'title' field set and GPS coordinates have their precision set to incorrect value

**To Reproduce**
seems quite random but happen maybe at a 50% rate...

**Expected behavior**
Title field set and correct value for coordinates precision should be set for every export profile

**Platform:**
Kubuntu 18.10
 DT 2.6.2

**Comment by phweyland** [comment] 2019-09-08 15:16
Which storage do you use (disk, flickr, ... ) ?
Could you attach faulty exported images and dt snapshots showing the internal data ?

**Comment by Aurelien-yeu** [comment] 2019-09-17 10:46
Hello,
I export to disk. I seems to appear ramdomly as I didn't get any faulty export for a few days and today 2 on the same file (different export size).
here are the images requested : 1 ok (1024px) and not ok (960px), and a DT snapshot with export parameters 

Thank you


![2019-09-09-IMG_9225-sun rise at sea-0-fb](https://user-images.githubusercontent.com/52784206/65034985-6eb8fa80-d948-11e9-8efb-4154329d93fc.jpg)
![2019-09-09-IMG_9225-sun rise at sea-0-1024px](https://user-images.githubusercontent.com/52784206/65034987-6eb8fa80-d948-11e9-9815-a6752718b6d1.jpg)

**Comment by Aurelien-yeu** [comment] 2019-09-17 10:48
Sorry I forgot the screenshot ;)

![Screenshot_20190917_124011](https://user-images.githubusercontent.com/52784206/65035392-5a293200-d949-11e9-80c0-ffe96e2f7dbe.png)

**Comment by phweyland** [comment] 2019-09-17 13:28
Hi Aurelien,
The 2 images have a the same title and no gps data (ok based on your snapshot). 

![image](https://user-images.githubusercontent.com/23012047/65045560-50aac480-d95f-11e9-9fe7-0cceae5ebf1d.png)

So the given examples seem ok to me ...

**Comment by Aurelien-yeu** [comment] 2019-09-17 13:51
I agree with you : Title, description and (No !) GPS data are correct...
Hum, it might be a Digikam related problem, then. I'll investigate with DK team and keep you informed if you want.

How did you extract those info ?

Thank for your kind replies !

**Comment by phweyland** [comment] 2019-09-17 16:07
> How did you extract those info ?

`C:\ProgFiles\exiftool\exiftool.exe -a -u -g1 -w txt` and the name of the file. It should be possible to do the same with exiv2...

**Comment by elstoc** [comment] 2020-03-13 08:10
Possible duplicate of https://github.com/darktable-org/darktable/issues/4355. Try the workaround suggested in that issue (de-select 'develop history' in the 'edit metadata exportation' window)

**Comment by Aurelien-yeu** [comment] 2020-03-16 18:35
> Possible duplicate of #4355. Try the workaround suggested in that issue (de-select 'develop history' in the 'edit metadata exportation' window)

Hi elstoc,

I tried the workaround and I'm happy to inform you that it solved my issue.
Thanks !

Aurelien

**Comment by elstoc** [comment] 2020-03-16 18:46
Ok thanks for checking. Probably worth closing this one as a duplicate as the investigation is a bit further on in the other issue.

**Closed** 2020-03-16 18:46 UTC
Labels: no-issue-activity
