### ISSUE TITLE
Enhance "Overwrite on Changed" option for Export to Disk feature to account for missing files

### ISSUE THREAD

**Issue by pozix604** [darktable-org/darktable#16632] opened 2024-04-16 20:21 UTC
**Is your feature request related to a problem? Please describe.**

The "file on disk" target storage includes an option to "overwrite if changed", which is great because you can export images to disk, and then re-export them, knowing that the export will not waste time re-exporting if the image has not changed.

However, if the exported image is somehow missing (e.g. moved since originally exported), the feature still says "skipping (not modified since export)". 

**Describe the solution you'd like**

It would be very useful if the export can _check_ to see if the file exists, then decide to skip it if it does. If the file does not exist (e.g. moved since originally exported), then re-export it.

This would allow for using this feature to keep an exported "mirror library" that is updated with the latest changes.

If original behavior is needed, perhaps this could be a checkbox option.

**Comment by steph72** [comment] 2024-04-16 20:32
A similar observation has been made by me quite a while ago in #15404. 

The "overwrite if changed" feature would be really great and useful if it worked like its naming suggests. 

The way it works now ("don't export the picture if it has been exported before") is of little practical use imho.

**Comment by jenshannoschwalm** [comment] 2024-04-19 17:11
Duplicate of #15404

**Closed by jenshannoschwalm** 2024-04-19 17:11 UTC
