### ISSUE TITLE
Highpass Mask Error

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#7916] opened 2021-01-18 02:07 UTC
**Describe the bug** I have been masking (both line and brush) while using the highpass module. What I am noticing is that there are changes being made to the image, by highpass, that are outside of the mask. Below are 2 clips from an image at 100%. This area is NOT contained within the mask. The main elements are NOT showing change (which is correct) but the sky-background is severely impacted.
![without](https://user-images.githubusercontent.com/6267270/104863904-451d3400-58ec-11eb-9283-119cc3b7647a.png)
![with](https://user-images.githubusercontent.com/6267270/104863911-4e0e0580-58ec-11eb-8e25-62c7a49d71e2.png)
The masked area is not included in these images and is well away from this location.
Using the highpass module with the following settings: sharpness/contrast and opacity are all at 50%: blend mode is softlight.

**To Reproduce**
Open highpass module
Draw a containment area on the image
Set sharpness/contrast to 50%
put blend 50% softlight in place
notice change in bare sky area.

**Expected behavior**
Areas outside of the containment mask should not be impacted by the highpass module
**Screenshots**
above

**Platform (please complete the following information):**
darktable 3.5.0+508~g76fb1aaa7
 - OS: Manjaro/Arch
 - OpenCL No
 - Quadro K1000M graphics card /Nvidia

**Additional context**
 - I have been able to reproduce with all recent git versions.
 - This is with RAW data ... I do not process JPGs
 - Are the steps above reproduce with a fresh edit (removing history) ... Yes
 - Attach an XMP if this is necessary
 - Did you compile Darktable yourself? No ... Arch/git
 - Is the issue still present using an empty/new config-dir The issue remain after a full rebuild.

**Comment by davidvj** [comment] 2021-01-18 03:48
This issue may be relevant with non-masked images also

**Comment by MStraeten** [comment] 2021-01-18 06:22
An issue report without any relevant information is useless. Use
https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title= 
this gives you an idea which information is needed

**Comment by parafin** [comment] 2021-01-18 06:53
Once again the whole report is commented out

**Comment by parafin** [comment] 2021-01-18 07:39
I've edited the report, but we really need #7566 resolved

**Comment by johnny-bit** [comment] 2021-01-18 09:57
Highpass module clips output luminance on whole image, seems like you have to blend in different space. By default it's Lab but should be scene refered RGB if you have highlights there (and sky is a tad bright in your pic)

generally highpass is display-refered module working in Lab space, so the effect you're seeing is bacisally "works as intended"

**Comment by johnny-bit** [comment] 2021-01-18 12:57
Yeah, closing - this is working as indended in blending modes. Use non clipping blending for high pass or make sure that there's noting before highpass that would make it exceet max luminosity so blending won clamp it.

Since highpass needs to work in conjunction with blending modes and highpass possibilities are (IMO) mostly covered by other modules (some of them work in scene refered space!) then closing this as 'works as intended'.

**Closed by johnny-bit** 2021-01-18 12:57 UTC
