### ISSUE TITLE
darktable crashes when using Surface Blur module

### ISSUE THREAD

**Issue by Dave22152** [darktable-org/darktable#8910] opened 2021-05-09 22:20 UTC
**Issue:** Upon activation of the Surface Blur module, darktable becomes sluggish and unresponsive, and will then crash.

**To Reproduce:** Activate Surface Blur.  System will slow and changes to module settings will take a long time to process.  At some point darktable will crash.  Using the new detail threshold slider seems to accelerate the occurrence, but I've had this happen even without using it.

**Platform**

darktable version : 3.5.0+2053~g47ec421cd
OS : Windows 10
Memory : 8 GB
Graphics card : AMD A8-7410 APU with AMD Radeon R5 Graphics, 2.20 Ghz
Graphics driver : Unk
OpenCL installed : Yes
OpenCL activated : No (Open CL always causes my system to lock up - different issue)
Xorg : Unk
Desktop : HP Pavalion
GTK+ : Unk
gcc : Unk
cflags : Unk
CMAKE_BUILD_TYPE : Unk 

**Additional context**
I have not seen this issue with previous builds, however I don't use the module very often.
[darktable_bt_GDDA30.txt](https://github.com/darktable-org/darktable/files/6448518/darktable_bt_GDDA30.txt)
[darktable_bt_JVB120.txt](https://github.com/darktable-org/darktable/files/6448521/darktable_bt_JVB120.txt)

**Comment by ralfbrown** [comment] 2021-05-10 02:10
Surface blur is one of the three most compute-intensive modules in darktable, so it's expected to slow down recomputation on changing other sliders.  So slowness is expected, but obviously not crashes.

 It's also (depending on slider settings) the most memory-hungry module on CPU.  Given that the cause of the crash looks like access via null pointer, I wonder whether it's running out of memory....

**Comment by jenshannoschwalm** [comment] 2021-05-14 18:14
@Dave22152 there has been a fix for bilateral code some days ago. The crash log you shared showed your system crashing exactly in that module. Please check if the issue persists and report or close this issue if everything is fine :-)

**Comment by Dave22152** [comment] 2021-05-15 19:19
@jenshannoschwalm, I just installed 3.5.0+2226 and the problem no longer occurs.  I'll close the issue.  Thanks!

**Comment by Dave22152** [comment] 2022-02-14 14:13
Hello, I've seen this issue consistently now on 3.8.1 on a new machine so I'm reopening the report instead of opening a new one.

To recreate the issue, I open the surface blur module and begin adjusting settings and then deactivate and reactivate to stress the system.  DT will crash and create a backtrace after a couple of minutes.  The issue happens whether OpenCL is activated or turned off.  Masking seems to accelerate the process, but crashes still occur with no masking.

The Windows resource monitor shows that RAM usage is well below its limit and there's no significant instances of hard faults.  As I mentioned, I am using a new machine:

darktable version : 3.8.1
OS : Windows 11
Memory : 16 GB
Graphics card : NVIDIA GeForce 3060
Graphics driver : Unk
OpenCL installed : Yes
OpenCL activated : Occurs when activated or off
Xorg : Unk
Desktop : PowerSpec G511: AMD Ryzen 5 5600X 3.7GHz Processor; NVIDIA GeForce RTX 3060 12GB GDDR6; 16GB DDR4-2666 RAM; 500GB Solid State Drive
GTK+ : Unk
gcc : Unk
cflags : Unk
CMAKE_BUILD_TYPE : Release

Backtrace attached below

[darktable_bt_WU3MH1.txt](https://github.com/darktable-org/darktable/files/8061358/darktable_bt_WU3MH1.txt)

**Comment by jenshannoschwalm** [comment] 2023-02-25 21:22
Still valid?

**Comment by Dave22152** [comment] 2023-02-25 23:12
Let me check and I’ll let you know.  Thanks!

**Comment by Dave22152** [comment] 2023-02-26 20:00
I just spent the last 20 minutes exercising the module with no crash.  I’d say that you could close the issue.  Nice work!

 

Dave G.

**Closed** 2023-02-26 20:02 UTC
