### ISSUE TITLE
Import of folder with subfolders of images broken in 4.6

### ISSUE THREAD

**Issue by pozix604** [darktable-org/darktable#16122] opened 2024-01-15 20:30 UTC
### Describe the bug

Importing of folders with subfolders containing images is broken. A success message displays saying that X number of images imported, but they are not. Recursive directory enabled. All files on local disk.

### Steps to reproduce

Create new Darktable library.

Start Darktable.

Click "Add to library".

Enable recursive directory.

Try to import a folder with image files in this folder. Works.

Try to import a folder with subfolders containing image files. Does not work.

### Expected behavior

Darktable should've imported the images.

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6

### What OS are you using?

Linux

### What is the version of your OS?

Debian 12

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel Iris Xe

**Comment by kmilos** [comment] 2024-01-16 06:42
Duplicate of #15894

Please search before opening new issues.

**Closed by kmilos** 2024-01-16 06:42 UTC
Labels: Fixed in master
