### ISSUE TITLE
Can't change mask transparency on a Mac

### ISSUE THREAD

**Issue by osvik** [darktable-org/darktable#5843] opened 2020-07-30 20:39 UTC
Control + Mouse wheel does not change the opacity of a mask. It always stays at 0%. Other key combinations that I've tried also don't change the opacity. Size and softness work.

Darktable 3.0.2 on Mac OSX 10.14.6

**Comment by MStraeten** [comment] 2020-07-31 07:39
not reproducible with current master so it seems to be fixed with upcoming 3.2

**Comment by parafin** [comment] 2020-07-31 07:53
It sounds one of those cases when opacity is stuck at zero. Could you attach ~/.config/darktable/darktablerc file?

**Comment by osvik** [comment] 2020-07-31 12:28
Sure @parafin Attached it is. Thanks.
[darktablerc.txt](https://github.com/darktable-org/darktable/files/5006975/darktablerc.txt)

**Comment by parafin** [comment] 2020-08-11 09:25
What's strange is that in your attached darktablerc you have opacity set to 1.0, not zero. Anyway, I can't reproduce the issue with darktable 3.2.1, so please upgrade and retry. If the issue is gone, please close this ticket.

**Comment by osvik** [comment] 2020-08-19 22:05
![Captura de ecrã 2020-08-20, às 00 03 31](https://user-images.githubusercontent.com/678916/90694290-ae831300-e278-11ea-9c42-684849e6b536.png)

I've upgraded and the issue continues in Darktable 3.2.1 on Mac OSX 10.14.6.

**Comment by parafin** [comment] 2020-08-20 07:59
Please attach darktablerc once again and describe exact steps how to reproduce it. What kind of mouse do you use? Could you try with some other device (e.g. if you're using Apple mouse, then try with ordinary one or touchpad if it's a notebook).

**Comment by osvik** [comment] 2020-08-20 09:43
This is the mouse:
![IMG_20200820_102420](https://user-images.githubusercontent.com/678916/90753454-ecb01f00-e2d8-11ea-94dd-388011a3f068.jpg)

This is the file:
[darktablerc.txt](https://github.com/darktable-org/darktable/files/5102053/darktablerc.txt)

- Darktable 3.2.1 on Mac OSX 10.14.6
- Moving the mouse wheel changes the size of a circle mask
- Shift + mouse wheel changes the feather size
- Control + mouse wheel doesn't do anything
- Alt + mouse wheel changes the size of a circle mask
- Cmd + mouse wheel changes the size of a circle mask
- The control key does work.

![Captura de ecrã 2020-08-20, às 11 42 27](https://user-images.githubusercontent.com/678916/90754529-49600980-e2da-11ea-85ab-77c28676b214.png)

**Comment by parafin** [comment] 2020-08-20 10:55
What I meant with exact steps is something like this (what I tried to do to reproduce):

1. start with fresh config except for your darktablerc:
```
mv ~/.config/darktable ~/.config/darktable.bkp
mkdir ~/.config/darktable
mv ~/Downloads/darktablerc.txt ~/.config/darktable/darktablerc
```

2. start darktable 3.2.1 installed from DMG

3. import an image with no xmp

4. add a circular mask

5. it displays opacity 100% - this is already different from your description, and you actually have 100% opacity set in darktablerc

6. try to change it with Ctrl+scroll - it works all the way from 5% to 100% both ways, tried trackpad and ordinary mouse

So I suspect we're missing some important step here. Are you trying to change opacity of some existing mask on already processed image? Does it happen with freshly imported image with no history? Please try some different scenarios and describe them in details. More information is needed.

**Comment by johnny-bit** [comment] 2021-05-18 18:31
There were changed to opacity + scroll handling code. Should work quire nice.

Echoing parafin's comments - we need more info. Closing for now. Please provide more info if you still have problems on either 3.4.1 or current master and I'll re-open the issue.

**Closed by johnny-bit** 2021-05-18 18:31 UTC
Labels: no-issue-activity
