### ISSUE TITLE
IOP bug with corrupted datas

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#12346] opened 2022-08-18 17:31 UTC
**Describe the bug/issue**

An old IOP bug is back! @TurboGit: I know you will not like that one.

**To Reproduce**
1. Be sure to have 2 instances of diffuse & sharpen module on destination image (EDIT : I also see with 2 instances of denoise (profiled) module ; this issue is unfortunately not always reproducible).
2. Copy development on another image (I test it with image that have only one instance of diffuse & sharpen)
3. Paste it to the destination image with 2 instances of diffuse & sharpen
4. See the error:

![image](https://user-images.githubusercontent.com/45535283/185458054-900a64f3-4132-4a0b-bffe-53c7da5516a3.png)

**Expected behavior**

No issue and image correctly displayed.

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : latest master
* Linux - Distro    : Debian Sid

**Comment by Nilvus** [comment] 2022-08-18 17:35
Copy/paste is in overwrite mode. No issue of course when erase option is selected.

**Comment by TurboGit** [comment] 2022-08-18 18:08
> Copy/paste is in overwrite mode. No issue of course when erase option is selected.

We have only two modes: overwrite / append. Can you clarify which mode you are using? If overwrite I would say that this is probably expected.

**Comment by TurboGit** [comment] 2022-08-18 18:08
@Nilvus : And indeed I don't like this one :)

**Comment by Nilvus** [comment] 2022-08-18 20:53
> > Copy/paste is in overwrite mode. No issue of course when erase option is selected.
> 
> We have only two modes: overwrite / append. Can you clarify which mode you are using? If overwrite I would say that this is probably expected.

Oups, my bad. This issue append only on append mode, not overwrite. On overwrite mode, no issue.

**Comment by TurboGit** [comment] 2022-08-19 07:34
The copy/paste is done from darkroom, right?

**Comment by Nilvus** [comment] 2022-08-19 08:39
> The copy/paste is done from darkroom, right?

Both darkroom or lighttable. And no difference, issue appears in both cases.

**Comment by todd-prior** [comment] 2022-08-25 16:30
Any chance this might be due to that change in the pipeline  for processing diffuse module during the use of crop and perhaps other situations...maybe now there is a conflict . I forget the commit but I could look it up...??

**Comment by Nilvus** [comment] 2022-08-25 18:58
Possible. I have had since some aw with 2 diffuse instances, without this issue but many with the issue. Can't find another thing in common than 2 instances of diffuse module. But a lot of images with the issue do not have crop module enabled anyway. The issue is quite regular but not always...

**Comment by todd-prior** [comment] 2022-08-25 19:43
Ya I don't think it was due to the crop rather it was a way to relax or not run the diffuse module unless it was determined the action would change the pixel values if I recall.... So it helps with jittering display while cropping etc...but it made me think that if you don't calculate it might be okay in the current pipe but if you parachute it in via a style it might not have the right data....

**Comment by Nilvus** [comment] 2022-08-25 20:39
> Ya I don't think it was due to the crop rather it was a way to relax or not run the diffuse module unless it was determined the action would change the pixel values if I recall.... So it helps with jittering display while cropping etc...but it made me think that if you don't calculate it might be okay in the current pipe but if you parachute it in via a style it might not have the right data....
> 
> It was this one I was thinking of...but its pretty recent...not sure if the problem happened before this??
> 
> [ee6c586](https://github.com/darktable-org/darktable/commit/ee6c586a9811a3638e5cd5edefb0172189cb447d)

Thanks for providing this. I will test before this commit this this weekend.

**Comment by jenshannoschwalm** [comment] 2022-08-26 19:46
Not sure atm if the duplicate of a module is reflected in the iop hash used for caching.

**Comment by Nilvus** [comment] 2022-08-28 10:50
Seems that it's not related to diffuse & sharpen module. I just had same issue with 2 denoise (profiled) module on destination image. I could confirm that commit cited by @todd-prior is not the cause. What's more strange is I can't reproduce on all image with 2 instances. By now, I didn't succeed to find a more reproducible step by step.

What is sure is that this IOP is not completely fixed but more peculiar by now... I will come back here if I found a more reproducible way.

**Comment by Nilvus** [comment] 2022-08-28 11:52
Is one of you could test those XMP (on following zip file) and check if you reproduce the issue or not on your side:

[2021-08-06-Montrichard-000.zip](https://github.com/darktable-org/darktable/files/9439583/2021-08-06-Montrichard-000.zip)

001 one (on file name) is the source (so one to copy development) and so 002 is the one to paste on. That second XMP have 2 instances of diffuse & sharpen and I have the issue with that one.

**Comment by TurboGit** [comment] 2022-08-28 16:24
For the record, I have been able to reproduce and I don't think that's the same issue than previous similar reports. Fact is that this sounds strange, as a "corrupted" pixelpipe somehow. If I reset the diffuse module or the color calibration one everything is OK, that this is pixel mess as seen on your report is cleared and the image looks fine. So it does not seem to be related to multiple instance...

**Comment by jenshannoschwalm** [comment] 2022-08-28 17:34
I have seen such corrupted data on several occasions. A "pixel pipe mess" could be related to a module getting bad input data from a wrongly iop cache buffer.

Does the bad data shown vanish after using a different roi either by scaling or moving around?

**Comment by Nilvus** [comment] 2022-08-28 21:01
Indeed, if I reset the issue disappear but by now, I only have that issue when having 2 instances of same module.

On record I posted here, I made some tests and the issue appear only if module order (v3.0 RAW in both source and destination RAW anyway) is checked. Uncheck it before posting and no issue.

Seems that this confirm "pixel pipe mess" you both suggest.

> Does the bad data shown vanish after using a different roi either by scaling or moving around?

Yes. but deactivate crop module make issue come back. But note that I have had this issue without crop module nor rotate & perspective or even old similar modules.

**Comment by TurboGit** [comment] 2022-08-29 08:12
@Nilvus : Have you tested with 3.8 to at least know if it is a recent issue?

Good that you confirm that a reset solves the issue. And that's why I think it is not the same issue I have been tracking down when implementing the new module-order and multi-instance as the only way to fix that was to clear all the history.

If it doesn't occur in 3.8 then we'll be able to bisect this issue. At this time I have no idea about what is going wrong!

**Comment by TurboGit** [comment] 2022-08-29 08:21
BTW, when viewing a corrupted image on the darkroom I always get a good image when going back on the history below the `color calibration` module. Is that your case too?

**Comment by TurboGit** [comment] 2022-08-29 08:25
Another test also shows that the issue occurs only when you copy a `color calibration` module. Do a partial copy and copy all modules except `color calibration` and you shouldn't have the problem. Can you also confirm this on your side?

**Comment by TurboGit** [comment] 2022-08-29 11:11
I'm onto something:

```
cannot get iop-order for diffuse instance 4
[dt_ioppr_check_iop_order] history module not used but enabled!! diffuse 4(2147483647) image 6797 (dt_dev_read_history_no_image end)
```

Editing the XMP and disabling the module seems to fix the issue...

**Comment by TurboGit** [comment] 2022-08-29 14:38
@Nilvus : See #12403.

**Closed** 2022-08-30 18:10 UTC
Labels: priority: high, understood: clear, reproduce: confirmed, scope: image processing, bug: pending
