### ISSUE TITLE
Lens correction and gradient

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#10139] opened 2021-10-03 00:47 UTC
darktable master, but the same behaviour happens in 3.6

If I add a gradient with the lens correction module off, I'm presented an horizontal line at the image center. Moving it up/down, it remains an horizontal line.

If I add the gradient with the lens correction modul on, again I'm presented an horizontal line at the image center. But when I move it up/down, it becomes a curve, with curvature proportional to the distance from the center, and changing its "side" when it passes through the center.

It seems that the gradient is always generated as the lens correction was off and transformed according to the lens correction. I think that this shouldn't be the behaviour: _the gradient line applied when the lens correction is on should remain a line._

Besides that, sometimes I could clearly see that moving the gradient line with the lens correction off activates the lens correction module, but I couldn't find a way to reproduce it.

Another little issue: lens correction on (resp. off), the gradient is curved (resp. straight); activate (resp. deactivate) lens correction: the gradient doesn't change, but as soon as you begin moving it, it get straight (resp. curved). _If the straight/curved must change, it should change immediately when the lens correction is activated/deactivated_.

**Comment by wpferguson** [comment] 2021-10-03 01:00
I can't reproduce with current git master.  I used the exposure module, added a gradient and moved it all around.  Lens correction never came on and the line always remained straight wherever it was on the image.  I also tried the graduated density filter and didn't have a problem.

**Comment by paolobenve** [comment] 2021-10-03 01:09
@wpferguson you couldn't reproduce _the last part_ of the issue

**Comment by wpferguson** [comment] 2021-10-03 01:20
Yes, and yes.  Still had a straight line

**Comment by paolobenve** [comment] 2021-10-03 01:37
Was the photo taken with low focal length (grandangular)? You see lens correction effects only at low focal length

**Comment by wpferguson** [comment] 2021-10-03 01:39
17mm

**Comment by elstoc** [comment] 2021-10-03 09:43
All shapes are drawn on the base image (the raw file) and then transformed through the pipe along with the rest of the image. So a line will be modified by any distorting modules (such as lens correction). This is entirely as expected, but you can often reverse this distortion (to some extent) by changing the curvature of the line.

**Comment by AlicVB** [comment] 2021-10-03 10:30
as @elstoc explained, this is "by design" : this is well explained here : https://darktable-org.github.io/dtdocs/darkroom/masking-and-blending/masks/drawn/#shape-distortions

for gradient specific case, you can use mouse scroll to change the line curvature if needed.

I'll close this for now. Feel free to reopen if I've miss something !

**Closed by AlicVB** 2021-10-03 10:30 UTC

**Comment by paolobenve** [comment] 2022-01-17 13:35
> All shapes are drawn on the base image (the raw file) and then transformed through the pipe along with the rest of the image. So a line will be modified by any distorting modules (such as lens correction). This is entirely as expected, but you can often reverse this distortion (to some extent) by changing the curvature of the line.

I was thinking on this reasoning, and I'd add:
- the current behaviour has its logic, and it's the simplest implementation possible
- another possible implementation would be to draw the shapes on the base image, but correcting it with the inverse of the lens correction
  - clearly, this would add complexity: a straight line would be broken into (many, if wide angle lens) segments
  - it could not add computation time; I suppose that shapes are mainly used in modules applied _after_ the lens correction module; in order not to add computation time, the original shape (not the segment-broken one) could be applied; if the lens correction is disabled, the segment-broken shape is applied instead

This alternative approach would give a big benefit: the shapes drawn by the user would corresponde to reality:
- I mean that a straight line in this new approach would corresponde to a straight line in the photographed subject
- on the contrary, now a straight line in the shape doesn't correspond to a straight line in reality, but to a curve, and the user that wants to shape a straight line or a polygon must do manually all the work of straighten a curve

Could we reopen this bug?

**Comment by AlicVB** [comment] 2022-01-17 17:09
This has been discussed many times already, and nobody has found another "working" way to do it...
Basically, your proposal is to store a sort of raster mask. I mean, what we store store for instance is "just" some points of a vectored shape. If we want to follow your proposal, we have no other way to store all the "transformed" points of the shape, which will have *lot* of other drawbacks.
Among lot of other ones, here's an example : 
1. apply lens correction
2. draw a path shape in whatever module after lens (a classic "bezier" one)
3. disable lens
4. try to modify slightly a position of a point of the shape
5. we have then no way to use some vector function (bezier curves in our case) to redefine the lines of the shape => the shape can't be modified anymore... and that's not acceptable !

Note that in fact, you don't need to have step 3. It's just here to show the issue even more...

**Comment by paolobenve** [comment] 2022-01-17 18:25
> try to modify slightly a position of a point of the shape

I don't know if I intended well... in my proposal the original shape (i.e. the one drawn by the user: biezer curve, straight line, circle, etc.) is the one that is managed at the UI level: user modifications would be made always to the original shape, and after every modification the transformed  shape will be generated.

I'm thinking in using the user-drawn shape after the lens correction module, and the transformed one before it or if it is not used.

In my mind it should work, the only complexity I see is the need of transform the original shape, but that will be done once for all when the shape is drawn/modified.

... or am I missing something?

**Comment by AlicVB** [comment] 2022-01-17 19:31
Hmm I have the feeling that there's some misunderstanding between us (that's easy with such a complex subject and my bad english...)

If I understand well your proposal, you propose to save the vector shape in the module reference where it's drawn. For example with exposure : in exposure input image reference.
That would solve your issue but will fail in this simple case : 
- draw a circle in exposure with center at 100x100 px in order to darken a specific sun reflect in the image.
- apply some rotation
- point 100x100 px in the exposure input reference is not the sun reflect anymore... your mask is void...

And that's valid for everything. The only reference we can rely on is the original image.

We have to keep in mind that there's distort modules everywhere in the pipe (for the beginning to the end) and we want among other things to keep the features that allow to : 
- ensure masks are still valid after having applied a distortion (means the "real" content of the shape is still the same)
- ensure that masks can be reused in multiple modules and points to the exact same "real" areas

**Comment by paolobenve** [comment] 2022-01-17 22:26
> If I understand well your proposal, you propose to save the vector shape in the module reference where it's drawn

No. I propose to save it where it is saved now, but to apply it as-it-is after the lens correction module, and transformed with the inverse of lens correction if applied before the lens correction (this case shouldn't happen very often)

> - ensure masks are still valid after having applied a distortion (means the "real" content of the shape is still the same)
> - ensure that masks can be reused in multiple modules and points to the exact same "real" areas

actually my proposal shouldn't create problem with this points (AFAIK)

**Comment by parafin** [comment] 2022-01-18 06:42
Your proposal creates problems if distortions are changed after mask is created (e.g. lens correction disabled) - you can’t really edit the mask after it was created. Your approach  only adds some optimization compared to what already has been considered, which doesn’t solve any real problems. Really, just read the discussion and AlicVB replies to you, it’s all there.
