### ISSUE TITLE
RFC: UI for raster mask visualizing

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#14389] opened 2023-05-01 09:45 UTC
**I would like to implement "raster masks visualizing"**

Would like to get comments on where the best position for the mask visualizing button would be.

This is what the interface looks like, 
![Bildschirmfoto vom 2023-04-30 17-38-33](https://user-images.githubusercontent.com/50982232/235435730-de1fa25f-0451-4b15-a133-8aba1f3e4e3a.png)

We currently have the button at the red position visible for other masks, i would not want to "even more clutter" that interface.

**How to proceed?**
1. Have a shared button used for all masks either at **G**reen or **Y**ellow
2. Add a button only used and visible for raster masks at either **G**reen or **Y**ellow

My personal choice would be **1-Y** (that means option 1 at yellow position) to have the same visible interface whatever the chosen mask is. What do you think? (Would not implement before getting 6 more votes :-)

**Comment by ralfbrown** [comment] 2023-05-01 13:51
Since we can only have one type of mask at a time, a shared button is the way to go.  For which the current 'red' position doesn't make any sense.  Of the other two, I definitely lean toward the yellow position.

**Comment by TurboGit** [comment] 2023-05-01 16:19
What about the _eye_ to show/hide the masking temporarily? It was good to have it next to the show-mask button.

**Comment by jenshannoschwalm** [comment] 2023-05-01 18:50
Yes, it would show the raster mask consumed here but calculated in the source module

**Comment by dterrahe** [comment] 2023-05-01 18:53
Would changing focus to source module be an option (when clicking header button)? If you'd want to make any adjustments, you'd have to go there anyway?

**Comment by jenshannoschwalm** [comment] 2023-05-02 20:59
Not for me a good option. I use the visualize-button to see the used mask for blending. Why not the raster? Of course I can switch modules or focus as now... but why?

**Comment by dterrahe** [comment] 2023-05-02 22:37
I meant it as an additional feature; having the mask button in the module header take you to the module the raster is taken from (do you could adjust it there). But this could be a control-click.

Still wondering if another button is needed than the one in the header for what you want (obviously its functionality needs to be extended to cover raster masks).

**Comment by jenshannoschwalm** [comment] 2023-05-03 04:49
> Still wondering if another button is needed than the one in the header for what you want (obviously its functionality needs to be extended to cover raster masks).

I don't think of a "new" button, it's just we have the existing button at a place where it wouldn't work (and doesn't make sense) for raster.

**Comment by dterrahe** [comment] 2023-05-03 17:09
> What about the _eye_ to show/hide the masking temporarily? It was good to have it next to the show-mask button.

It might be nice to be able to _toggle_ the current mask off/on using the x button. Currently it only switches off, but you need to remember which button you had before to switch it back on.

Would that be very different (slower?) than the _eye_ button? I guess the latter has the advantage it doesn't generate a history change (?) but presumably it does invalidate cache?

**Comment by jenshannoschwalm** [comment] 2023-05-03 17:57
I think we are talking / writing about different things. For me: we have the square mask button in the "mask refinement" line. Toggle it and you will the the used mask for blending, nice and necessary.

Unfortunatele - at least for me - we don't have this button for raster masks applied and i would like to have it too. So where to put that button? That was my initial question :-)

**Comment by dterrahe** [comment] 2023-05-03 18:11
We are talking about related things. As you point out, the current "display mask" button should have its functionality expanded to also cover raster masks, but then it also needs to be moved because it otherwise won't be visible when a raster mask is active. (there is already a duplicate of this button in the module header, but it doesn't have its full functionality; maybe it should have and maybe a duplicate would then not be needed)

Pascal's reaction was that if you _move_ the display mask button, that now the "temporarily toggle mask" button will be on its own when really in his opinion they belong together). It should maybe also be available for raster masks so that button (imho) has the same issues as the "display mask" button and the problem of moving both of them should be considered at the same time.

My remark about the "temporary toggle button" then is; maybe we don't _need_ that one; maybe toggling off and back on the masks should be so easily done with the "X" button that a separate button would not be needed.

So one _possible_ (not necessarily my preference) proposal would be to remove _both_ buttons, expand the functionality of the "show mask" button in the header (with ctrl/shift click; maybe it should also grab focus for the module so that the tooltip doesn't need to explain this) and expand functionality of the X button to allow it to toggle back on the previous mask.

Does that make it more clear or do you still think I'm polluting a simple discussion? Fine by me; I don't feel strongly about any of this.

**Comment by jenshannoschwalm** [comment] 2023-05-03 19:37
> Does that make it more clear or do you still think I'm polluting a simple discussion? 

Never thought so! Sorry if you got the impression by any of my words.


> Pascal's reaction was that if you _move_ the display mask button, that now the "temporarily toggle mask" button will be on its own when really in his opinion they belong together). It should maybe also be available for raster masks so that button (imho) has the same issues as the "display mask" button and the problem of moving both of them should be considered at the same time.

Aah. I see, understand your comment now and think you are right - both buttons should be kept together.
So a proposal would be too keep the "refinement line as is and duplicate the functionality for raster?

**Comment by dterrahe** [comment] 2023-05-03 20:52
> Never thought so! Sorry if you got the impression by any of my words.

No worries! I should have added tongue-in-check emoji...

**Closed** 2023-07-29 10:48 UTC
Labels: feature: new, scope: UI, no-issue-activity
