### ISSUE TITLE
GTK warning about escaping ampersand in style doesn't make sense

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7412] opened 2020-12-23 10:59 UTC
DT master.

Using a debugger to just step through code for my understanding.
A style was applied.
I did a ctrl+e to export.
There were exceptions thrown that I could see while debugging.

```
libstdc++.so.6!__cxa_throw (Unknown Source:0)
libexiv2.so.27![Unknown/Just-In-Time compiled code] (Unknown Source:0)
libexiv2.so.27!Exiv2::ExifKey::Impl::decomposeKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (Unknown Source:0)
libexiv2.so.27!Exiv2::ExifKey::ExifKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (Unknown Source:0)
libdarktable.so!dt_remove_exif_keys(Exiv2::ExifData & exif, const char ** keys, unsigned int n_keys) (\usr\include\c++\9\bits\basic_string.h:263)
libdarktable.so!dt_exif_read_blob(uint8_t ** buf, const char * path, const int imgid, const int sRGB, const int out_width, const int out_height, const int dng_mode) (\home\mchhil\darktable\src\common\exif.cc:1654)
libdarktable.so!dt_imageio_export_with_flags(const int32_t imgid, const char * filename, dt_imageio_module_format_t * format, dt_imageio_module_data_t * format_params, const gboolean ignore_exif, const gboolean display_byteorder, const gboolean high_quality, const gboolean upscale, const gboolean thumbnail_export, const char * filter, const gboolean copy_metadata, const gboolean export_masks, dt_colorspaces_color_profile_type_t icc_type, const gchar * icc_filename, dt_iop_color_intent_t icc_intent, dt_imageio_module_storage_t * storage, dt_imageio_module_data_t * storage_params, int num, int total, dt_export_metadata_t * metadata) (\home\mchhil\darktable\src\common\imageio.c:1027)
libdarktable.so!dt_imageio_export(const int32_t imgid, const char * filename, dt_imageio_module_format_t * format, dt_imageio_module_data_t * format_params, const gboolean high_quality, const gboolean upscale, const gboolean copy_metadata, const gboolean export_masks, dt_colorspaces_color_profile_type_t icc_type, const gchar * icc_filename, dt_iop_color_intent_t icc_intent, dt_imageio_module_storage_t * storage, dt_imageio_module_data_t * storage_params, int num, int total, dt_export_metadata_t * metadata) (\home\mchhil\darktable\src\common\imageio.c:644)
libdisk.so!store(dt_imageio_module_storage_t * self, dt_imageio_module_data_t * sdata, const int imgid, dt_imageio_module_format_t * format, dt_imageio_module_data_t * fdata, const int num, const int total, const gboolean high_quality, const gboolean upscale, const gboolean export_masks, dt_colorspaces_color_profile_type_t icc_type, const gchar * icc_filename, dt_iop_color_intent_t icc_intent, dt_export_metadata_t * metadata) (\home\mchhil\darktable\src\imageio\storage\disk.c:332)
libdarktable.so!dt_control_export_job_run(dt_job_t * job) (\home\mchhil\darktable\src\control\jobs\control_jobs.c:1368)
libdarktable.so!dt_control_job_execute(_dt_job_t * job) (\home\mchhil\darktable\src\control\jobs.c:300)
libdarktable.so!dt_control_run_job(dt_control_t * control) (\home\mchhil\darktable\src\control\jobs.c:319)
libdarktable.so!dt_control_work(void * ptr) (\home\mchhil\darktable\src\control\jobs.c:564)
libpthread.so.0!start_thread(void * arg) (\build\glibc-ZN95T4\glibc-2.31\nptl\pthread_create.c:477)
libc.so.6!clone() (\build\glibc-ZN95T4\glibc-2.31\sysdeps\unix\sysv\linux\x86_64\clone.S:95)
```

In terminal I see..
```
(darktable:27927): Gtk-WARNING **: 16:00:29.910: Failed to set text 'applied style `B&W High Contrast' on current image' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```

Style (from dtstyles) contents (formatted in an editor)

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<darktable_style version="1.0">
    <info>
        <name>B&amp;W High Contrast</name>
        <description>Applies a high contrast tone curve and makes the image monochrome.</description>
    </info>
    <style>
        <plugin>
            <num>0</num>
            <module>1</module>
            <operation>monochrome</operation>
            <op_params>00000000000000000000803f</op_params>
            <enabled>1</enabled>
        </plugin>
        <plugin>
            <num>1</num>
            <module>1</module>
            <operation>tonecurve</operation>
            <op_params>0000000077177d3bd067083e3f6ba63e5018553f0000803f00000000bcce3f3948e0903d5f9be93efade743f0000803f00000000</op_params>
            <enabled>1</enabled>
        </plugin>
    </style>
</darktable_style>
```

The & is correctly escaped in the style.

**Comment by dterrahe** [comment] 2020-12-23 11:15
This is not coming from the xmp but from the toast generated by
`dt_control_log(_("applied style `%s' on current image"), name);`
caused by #7390

I'll submit a fix shortly.

**Comment by TurboGit** [comment] 2020-12-23 11:33
@chhil : Can you test #7413 which should fix this issue ? TIA.

**Comment by chhil** [comment] 2020-12-23 11:43
Will test and report back.

**Comment by chhil** [comment] 2020-12-23 11:48
**Dont get the GTK warning anymore.** 

But the exceptions thrown and caught internally still happen when dt_remove_exif_keys is called.

**Comment by dterrahe** [comment] 2020-12-23 18:11
Those two things are most likely completely unrelated, so I would suggest #7413 be merged and you then either open a new bug with a name more descriptive of the exif issue or reopen this one and rename it.

**Closed** 2020-12-23 18:20 UTC

**Comment by chhil** [comment] 2020-12-24 01:44
I won't be opening a new issue for the exception. It seems to be by design based on the catch block comment.

```
      // the only exception we may get is "invalid" tag, which is not
      // important enough to either stop the function, or even display
      // a message (it's probably the tag is not implemented in the
      // exiv2 version used)
```

**Comment by dterrahe** [comment] 2020-12-24 10:29
As long as it isn't causing a crash?

**Comment by chhil** [comment] 2020-12-24 10:52
It was never crashing, was worrying about context switching that would happen for every export file.
