### ISSUE TITLE
Collections module sorting and display bug (Windows 11)

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [darktable-org/darktable#16069] opened 2024-01-09 10:02 UTC
### Describe the bug

When I open an image and then return to Lighttable, Collections module shows the list from the beginning, when in fact it is scrolled down. If I then single-click a film roll, it selects a film roll like 20 positions higher, but if I scroll the list, it updates and displays everything correctly. _(Like in the video, after first image I click, after second I scroll)_.

It also happens when an image is deleted from a film roll.

---

And also, in Collections settings when I select "descending order", it does not make any difference (sort by folder name is selected)

### Steps to reproduce

1. open darktable
2. scroll collections list
3. open a film roll and any image
4. return to lighttable
5. scroll or single-click any film roll

### Expected behavior

Show Collections consistently.

### Logfile | Screenshot | Screencast

https://youtu.be/WbO7kjgVx_I

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

Intel Iris Xe 96eu

**Comment by pehar1** [comment] 2024-01-09 14:59
Seems this is a duplicate of https://github.com/darktable-org/darktable/issues/14836

**Comment by zisoft** [comment] 2024-01-09 15:21
closed as duplicate of #14836

**Closed by zisoft** 2024-01-09 15:21 UTC
Labels: duplicate
