### ISSUE TITLE
User Manual update on Snapshot 

### ISSUE THREAD

**Issue by ActarusLeGrand** [darktable-org/darktable#14759] opened 2023-06-23 16:40 UTC
### Describe the bug

In the manual under Snapshot, probably p. 194 (v. 4.2)
Also https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/darkroom/snapshots/

Click on the name of the snapshot again to disable the overlay and return to your editing session. 

Ckicking on the name do not disable the overlay or return to the editing session. 

### Steps to reproduce

In the manual. darktable_user_manual 42
p.194 or [Manual ]((https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/darkroom/snapshots/))

### Where did you install darktable from?

darktable.org

### darktable version

4.4.0

### What OS are you using?

Windows

### What is the version of your OS?

10

### Are you using OpenCL GPU in darktable?

None

**Comment by MStraeten** [comment] 2023-06-24 20:06
The manual is correct: clicking name activates the display of the snapshot overlay, clicking again disables it. At least with my macOS build

**Comment by victoryforce** [comment] 2023-08-18 19:33
@ActarusLeGrand I'm going to close this issue because you suggest fixing the documentation to match the app's behavior, so an issue should be raised in the documentation repository.

Moreover, I also cannot reproduce the behavior you describe ("clicking on the name do not disable the overlay or return to the editing session") on any of my installations (Windows, Linux), so for me the behavior of the program is completely in line with the documentation. Try updating to the latest version (4.4.2) and running the program on an empty configuration and if the problem you describe continues to reproduce, please raise a new issue and add a screencast to understand what is happening.

**Closed** 2023-08-19 15:01 UTC
