### ISSUE TITLE
Diffuse: Additional sharpen presets

### ISSUE THREAD

**Issue by wilecoyote2015** [darktable-org/darktable#9839] opened 2021-08-19 18:27 UTC
Recently, two of my presets for the diffuse module have turned out to be relatively versatile for some real-world scenarios.
In contrast to the default lens blur presets, they are engineered more towards providing pixel-level sharpness and halo suppression, with the disadvantage of slight noise amplification. 
Regarding to my personal taste, the presets yield quite naturally looking sharpness for medium lens blur as well as slightly defocused portrait shots. The latter use case has been a lifesaver for me several times ;)

Given those presets could be useful for others, too, maybe it might be considerable to ship them with DT?
[presets_sharpen.zip](https://github.com/darktable-org/darktable/files/7017022/presets_sharpen.zip)

A comparison of two 1:1 crops without (first) and with (second) the strong sharpen preset is provided below.

![DSCF0124](https://user-images.githubusercontent.com/1688125/130124033-75e85148-1756-4890-9294-0693774e7e87.jpg)
![DSCF0124_01](https://user-images.githubusercontent.com/1688125/130124034-57a0c623-1e10-4f81-b2bd-c1258f966561.jpg)
![DSCF0132](https://user-images.githubusercontent.com/1688125/130124036-b748d92d-ef89-42f4-974d-78deef782c93.jpg)
![DSCF0132_01](https://user-images.githubusercontent.com/1688125/130124038-fc7d6e11-ef4f-42ff-bbc9-d5673a994a4b.jpg)

**Comment by elstoc** [comment] 2021-08-20 08:19
@aurelienpierre what do you think. The examples look pretty nice to me, but I haven't compared to the existing presets.

**Comment by domosbg** [comment] 2021-08-22 09:35
I tried the presets with my own pictures. 

Before 100% view:
![grafik](https://user-images.githubusercontent.com/88573684/130348590-6c28e0e8-10de-4bb3-bc3c-9c917462a449.png)

With sharpen_strong preset 100% view:
![grafik](https://user-images.githubusercontent.com/88573684/130348623-bb7baa80-b498-40df-91a0-3fdb2385c031.png)

From my amateur photografer point of view I think the preset increases the sharpness of the picture significantly when you look in the 100% view. I tried the other presets actually available in the sharpen and diffuse module, they all have other effects on the picture. So, for me, it seems not to be a duplicate of another preset.

But with my little experience in photografing I cannot says how often this kind of sharpness increasing is useful or what the use cases are. For me I only would use it when making extreme crops of pictures, what I normally would not do. Normally I crop maximum around 50% or less of the picture and export it to show online. In this case I couldn't see any effect of the presets in the final result.
But I'm definitely not the reference for semi-professional (or better) photografing and using of darktable. If more experienced users see more use cases for the presets and think that there are not to many preset at the end, then it could be useful to implement.

Besides, coming back to my beginners point of view, presets helps beginners to get faster results and are a good starting point to learn (if you choose a preset, you can see the effect on the picture and the module setting. That can help to understand better what's possible and how the settings are working).

**Comment by tpapp** [comment] 2023-03-27 12:56
I find this preset very useful, I would suggest that it is considered for inclusion (if someone with commit rights is willing to review it, please reopen the issue).

**Comment by tpapp** [comment] 2023-03-27 12:56
I find this preset very useful, I would suggest that it is considered for inclusion (if someone with commit rights is willing to review it, please reopen the issue).

**Comment by TurboGit** [comment] 2023-03-27 15:34
@tpapp : Presets proposed in #14041.

**Closed** 2023-03-29 16:37 UTC
Labels: feature: enhancement, scope: UI, scope: image processing

**Comment by trougnouf** [comment] 2023-09-06 16:21
@wilecoyote2015 Thank you for this preset. Can you provide your diffuse or sharpen workflow including this preset?
I've been using denoise - local contrast - sharpen demosaicing - lens deblur. Not quite sure what should be replaced here and where yours should come into place.
