### ISSUE TITLE
crash when editing an old image and disabling 'crop and rotate'

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#12798] opened 2022-11-06 18:20 UTC
**Describe the bug/issue**
I get a crash when I disable 'crop and rotate' (the only optional module I have enabled).

**To Reproduce**

1. Get the files from https://tech.kovacs-telekes.org/files/dt-crash-2022-10-06/
2. Open the raw
3. Disable 'crop and rotate'
4. See error (see log I uploaded).

**Expected behavior**
No crash

**Which commit introduced the error**
I don't know. I can bisect if I must, but I hope the logs are enough.

**Platform**

* darktable version : e.g. 4.1.0+865~g70da6dcc8
* OS                : `Linux 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Linux - Distro    : Ubuntu 22.04
* Memory            : 64 GB
* Graphics card     : N/A
* Graphics driver   : N/A (happens with and without OpenCL)
* OpenCL installed  : yes
* OpenCL activated  : yes, no (happens both ways)
* Xorg              : 7.7+23ubuntu2
* Desktop           : KDE 5.24.6-0ubuntu0.1 
* GTK+              : 3.24.33-1ubuntu2  
* gcc               : 11.3.0
* cflags            : N/A
* CMAKE_BUILD_TYPE  : Release, RelWithDebInfo, Debug (happens with all)

**Additional context**
The image was initially edited using some old version, whatever was current in May 2020.
The crash happens also if I reset 'crop and rotate', instead of disabling it.
There is no issue if I discard the history, the image can be loaded.

**Comment by kofa73** [comment] 2022-11-06 18:45
```
Thread 11 "worker res 1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcf7fe640 (LWP 74091)]
dt_dev_pixelpipe_process_rec (pipe=0x555558d0e000, dev=0x555558cf2bf0, output=0x7fffcf7ef278, cl_mem_output=0x7fffcf7ef280, out_format=0x7fffcf7ef288, roi_out=0x7fffcf7ef2a0, modules=0x7fffd411ef40 = {...}, pieces=0x7fffd4120760 = {...}, pos=87) at /home/kofa/darktable/src/develop/pixelpipe_hb.c:2046
2046              const float f = ((float *)(*output))[k];
```

**Comment by TurboGit** [comment] 2022-11-06 22:05
Can you share the picture + xmp ?

**Comment by TurboGit** [comment] 2022-11-07 07:04
@jenshannoschwalm : Do you reproduce?

**Comment by kofa73** [comment] 2022-11-07 07:25
Note that the crash also occurs on Windows using the 'Windows insider' build (4.1.0+865~g70da6dcc8, no OpenCL, Windows 10, 16 GB of RAM). The difference is, on my Linux machine, the image looks like how a raw would normally look without any processing modules: quite dark and flat, with a green cast, but still visible. On Windows, both on the lighttable and in the darkroom, it's almost completely black:
![image](https://user-images.githubusercontent.com/3177739/200250128-1cd9f89f-2400-45fb-8458-0697a3788b79.png)
![image](https://user-images.githubusercontent.com/3177739/200250192-a53ebda3-f915-4330-a710-e0527df40a58.png)

**Comment by jenshannoschwalm** [comment] 2022-11-07 08:25
Didn't try yet, will check asap

**Comment by kofa73** [comment] 2022-11-07 08:44
The log and the gdb output are from two different runs. In the log, this entry has weird-looking numbers:
```
#5  0x00007fbbfb0c1dc8 in dt_dev_pixelpipe_process (pipe=0x55de4f670710, dev=0x55de4f64b700, x=0, y=0, width=1190, height=788, scale=0.24059847) at /home/kofa/darktable/src/develop/pixelpipe_hb.c:2232
        roi = {x = -612437344, y = 32699, width = -612437136, height = 32699, scale = 1.05097385e-43}
        pos = 32699
        modules = Python Exception <class 'gdb.MemoryError'>: Cannot access memory at address 0x8bffffff78858b48
```

**Comment by jenshannoschwalm** [comment] 2022-11-07 09:00
I guess you have latest hlr pr's included? Did you check what happens while using `-d roi`?

**Comment by jenshannoschwalm** [comment] 2022-11-07 09:05
It looks like the locking pipedev is making it crash..

**Comment by kofa73** [comment] 2022-11-07 09:56
@jenshannoschwalm : please check updated https://tech.kovacs-telekes.org/files/dt-crash-2022-10-06/dt-log

**Comment by jenshannoschwalm** [comment] 2022-11-07 16:29
i can't reproduce here so far ...

**Comment by kofa73** [comment] 2022-11-07 16:50
Oh. I wonder why it was difficult to reproduce. My two installations (Linux, Win) are quite different and don't share the config file, either. Do let me know if you need more info.

**Comment by jenshannoschwalm** [comment] 2022-11-07 16:54
> Oh. I wonder why it was difficult to reproduce

It just crashed while closing dt in a regular way. So i have no idea what's going on yet.

**Comment by jenshannoschwalm** [comment] 2022-11-07 18:55
So far i get it crashing regularly, surprising is it seems to crash just "somewhere", sometimes while closing dt while munmap "something"

I also saw errors seemed to be in pixelpipe_cache cleanup (just once), several times it seemed to be in gamma whiele copy data.

No good guess atm what is happening. Do you have any other hints? Did you ever see something like this **not** related to crop & rotate?

**Comment by TurboGit** [comment] 2022-11-07 18:59
@jenshannoschwalm : Given your last comment I would say that this is probably some kind of memory corruption... the good news is that we have a hint... the bad news is that such error is very difficult to reproduce/understand & fix :(

**Comment by TurboGit** [comment] 2022-11-07 19:11
One possible idea...

Maybe there is some items not initialized when a module a deprecated and when we disable it we do some clean-up... and it crashes. Just a wild guess at this point...

**Comment by jenshannoschwalm** [comment] 2022-11-07 21:29
Yes, one idea. That would mean to test on other deprecated module? That might make this idea more valid.

Or something specific for c&rotate?

One other observation I made, disabling the module worked, I could change back to light table, edit another image and crash while quitting dt.

**Comment by jenshannoschwalm** [comment] 2022-11-08 05:46
Sort of "progress of understanding": while trying to get a valid cacheline we
1. find a cacheline with an identical hash
2. but the requested size is small than required thus leading to a later access "out of bounds"

Good because i can make sure in the pixelpipe cache code. Bad because there must be something somewhere else that leads to a wrong hash calculation.

**Closed** 2022-11-08 17:36 UTC
