### ISSUE TITLE
Seeing weird image size change in darkroom view after history paste from a raw to jpeg file.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#7577] opened 2020-12-31 10:15 UTC
Current Master
WSL Ubuntu

Since the animated gif is of a large size, you can find the steps to see visually what is happening...

.

https://www.dropbox.com/s/jyye680b0om8w92/ImageCrop.gif?dl=0

**Comment by johnny-bit** [comment] 2020-12-31 10:48
change gif to mp4 or mov an normally attach. Those are usually smaller than gifs in size when it comes to screencasts

**Comment by johnny-bit** [comment] 2021-06-25 20:47
The referenced GIF was removed, the issue contains no explaination/reproduction steps.

Closing due to not enough info.

Please comment after adding all necessary info and we'll re-open the issue for investigation.

**Closed by johnny-bit** 2021-06-25 20:47 UTC
Labels: no-issue-activity, understood: incomplete
