### ISSUE TITLE
Darktable 3.2.1/Open CL: RAWs are ugly dark after loading via filmstrip

### ISSUE THREAD

**Issue by herbert-50** [darktable-org/darktable#6411] opened 2020-09-29 20:10 UTC
**Describe the bug**
If a RAW is loaded for the first time into the darkroom by clicking it on the filmstrip, the development is too dark. This bug only occurs, when a JPG was loaded before in the darkroom. 

**To Reproduce**
- Use fresh images in JPG and RAW (fresh means with no xmp files from an edit before)
- import the images
- Load the jpg into the darkroom (via lighttable).
- Click on a fresh RAW on the filmstrip.
-> the RAW is displayed to dark
![darktable_241](https://user-images.githubusercontent.com/57417616/94610232-40326700-02a0-11eb-9ea6-1b5bfacf6c7b.png)

- Leave the darkroom
- Load the RAW via the lighttable.
- Click on 0-original in the history
- Click compress history stack to load the standard workflow modules
-> the RAW is displayed right
![darktable_243](https://user-images.githubusercontent.com/57417616/94610300-60622600-02a0-11eb-8f14-a77eeb03928b.png)

**Screenshots**

**Platform:**
 - Darktable Version: 3.2.1
 - OS: Ubuntu 18.04.3
 - OpenCL activated: YES (with "no" the bug does occur too)
 - GeForce GTX 1050 Ti/PCIe/SSE2

**Comment by johnny-bit** [comment] 2020-09-29 20:35
Known bug, fixed in master :)

**Comment by junkyardsparkle** [comment] 2020-09-29 23:08
The issue is that the input color profile is being set to sRGB for the RAW files; setting it back to "standard" fixes the problem. A workaround for 3.2.1 is to set the lighttable preference "don't use embedded preview JPEG...", which should keep this from happening to newly imported files (might require restarting darktable).

**Comment by parafin** [comment] 2020-09-30 09:31
Closing as duplicate of an already solved issue.

**Closed by parafin** 2020-09-30 09:31 UTC
