### ISSUE TITLE
Lighttable: can't select mulitiple thumbnails using Ctrl+Click with some window managers

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/darktable#5638] opened 2020-06-26 00:41 UTC
**Describe the bug**
In the new lighttable view, using Ctrl+Click to select multiple thumbnails no longer works. The behavior is the same as with no modifier key pressed. Shift+Click still works as expected for selecting a range of thumbnails.

**To Reproduce**
See above.

**Expected behavior**
Using Ctrl+Click should add the thumbnail clicked on to the current selection, as it did in previous lighttable view.

**Platform (please complete the following information):**
 - Darktable Version: current master
 - OS: Slackware ~current, xorg 1.20.5, gtk+3 3.24.12, Nvidia binary drivers v430.40

**Additional context**
Tested with fresh config. Since this seems like something which would have been noticed by now, I guess it might be another odd one like #4502 and not reproducible on most systems, but since that turned out to be fixable anyway, I'll go ahead and report it. ;-)

**Comment by Nilvus** [comment] 2020-06-26 08:19
Can't reproduce that on my side. So as you said, probably another odd one. Ctrl+click works great with both versions I tested:
- 3.1.0+2366~g54a0ddd6e
- 3.1.0+2375~gf4175b1b1

**Comment by junkyardsparkle** [comment] 2020-06-26 19:31
Thanks for confirmation. It's weird that Shift+click *does* work normally, but I don't know if that offers much in the way of clues...

**Comment by s5k6** [comment] 2020-06-28 18:09
Hi.  I can confirm this problem with both,

    3.1.0+1949~g4468052b4
    3.1.0+2384~g2919f88a0

Ctrl-click *only* selects the image clicked on, and deselects all
previously selected images.

**Comment by AlicVB** [comment] 2020-07-01 16:34
@junkyardsparkle @s5k6 so I think that I'll need to annoy you again to do some tests for me...
can you please add this in the code : 
- `printf("button release %d\n", event->state);` in dtgtk/thumbnail.c before line 668
- `printf("toggle %d\n", imgid);` in common/selection.c line 232
- `printf("toggle exist %d\n", exists);` in common/selection.c line 242

then check what messages are shown on terminal when you "ctrl-click" on a thumbnail. here it's something like : 
```
button release 276
toggle 170
toggle exist 0
```
where 170 is the id of the clicked image.
Thanks !

**Comment by junkyardsparkle** [comment] 2020-07-01 17:01
I'll do the debug build shortly, hopefully within an hour. Not an annoyance. :-)

**Comment by junkyardsparkle** [comment] 2020-07-01 17:59
@AlicVB I get same output as yours but with 260 instead of 276 for the button release.

**Comment by junkyardsparkle** [comment] 2020-07-01 18:13
I just noticed another odd little thing while paying attention to clicking behavior and Image IDs: in the image information window in the left panel, the information follows the mouse hover, but when I click on a thumbnail *with zero pointer movement* (probably hard to do with a mouse) the information changes to that of the previously selected image... slightly moving the pointer (a "hover" event) then "corrects" the information. Probably not related, but is this expected?

**Comment by AlicVB** [comment] 2020-07-01 18:53
> @AlicVB I get same output as yours but with 260 instead of 276 for the button release.

that's weird : that means that we are exactly the right thing to add the image to the selection... So the problem comes from elsewhere...
I'll have to think to some other debugging idea...

Just to be sure : it's not a refreshing problem : if you scroll until you hide completely the selected thumbnails and scroll back, you still have the wrong selection ?

For the second problem, I can't reproduce either... I'm starting to think that fluxbox is really doing bad things with gtk events...

**Comment by junkyardsparkle** [comment] 2020-07-01 19:09
The 260 vs. 276 isn't significant?

> Just to be sure : it's not a refreshing problem : if you scroll until you hide completely the selected thumbnails and scroll back, you still have the wrong selection ?

Yes, nothing changes. The refreshing takes place with a Ctrl+click, it's just that the result is exactly the same as a normal click event.

> For the second problem, I can't reproduce either... I'm starting to think that fluxbox is really doing bad things with gtk events...

I've never had any similar issues before (over too many years to count), but when I get a chance I'll try with Xfce... I don't have Gnome (or KDE) installed on the system. Maybe @s5k6 and I can narrow down things that are common to both of our environments...

**Comment by AlicVB** [comment] 2020-07-01 20:37
@junkyardsparkle : I have the feeling that when you click on a widget something weird happens. I incriminate fluxbox here, as it has already cause some problem in the past with wrong event raised...

With your second "bug" I would say that when you click, you get a leaving event along with the button-press event. That would also explain the #4502 bug. But I'm not sure at all how that can be related to the selection bug :(
I'll need some more thought...

**Comment by junkyardsparkle** [comment] 2020-07-02 00:48
Ok, I ran darktable directly from `xinit` to eliminate all other variables, and sure enough, `Ctrl+Click` worked normally. If these issues only affect the five people in the world running darktable on fluxbox, then you probably shouldn't worry about it much. ;-)

It's interesting that I haven't had similar issues with other apps, though... oh well. Maybe it's a sign that it's time to investigate some other WM options. Anyway, thanks for looking into it!

**Comment by AlicVB** [comment] 2020-07-02 19:31
@junkyardsparkle : just be patient, I'll have a serious look, but I'm quite short in time this days. I hope to have more time next week...

**Comment by junkyardsparkle** [comment] 2020-07-02 22:03
Just out of curiosity I tried using blackbox wm, to see if fluxbox may have inherited this from there. It didn't have the Ctrl+click issue, but it did have the same odd behavior refreshing the image info. Anyway, for now everything works fine under xfwm4, so there's no hurry on my part, but I'll leave the issue open (and make the title more specific).

**Comment by s5k6** [comment] 2020-07-05 08:46
This is not limited to Fluxbox.  I'm using FVWM and see the same issue.

There's been another bug related to non-mainstream window managers some time ago (https://redmine.darktable.org/issues/12387#change-37352).  Edgardo fixed it, so maybe he knows where to look for WM-related stuff?

**Comment by s5k6** [comment] 2020-07-05 09:00
Similar to what I've described in https://redmine.darktable.org/issues/12387#change-37352, I have configured my window manager to capture a left mouse click/drag on a window when the Hyper modifier (aka. Windows key or logo key) is held down. In that case, the window is raised (click) or moved along with the mouse pointer (drag).

When I disable this particular binding, the jumping disappears (FVWM allows to do so during runtime).  But this is not a workaround, the binding is there for  a reason.

The question would be if others can reproduce this bug (or its disappearance) when creating (or or deleting) such a key binding.

**Comment by junkyardsparkle** [comment] 2020-07-05 20:43
> The question would be if others can reproduce this bug (or its disappearance) when creating (or or deleting) such a key binding.

I tried darktable with FVWM2, since it's installed on my system, with no configuration beyond default, and didn't experience either of the issues I've described here, for whatever that's worth. If you can describe the simplest method for configuring the keybinding you describe, I can try it later.

Also, I tried a completely default config for fluxbox, as well as a couple of other WMs which happen to be installed, with the following results:

XFCE 4.12 - neither issue
Fluxbox 1.3.7 - both issues
Blackbox 0.74 - only second issue
FVWM 2.6.8 - neither issue
Windowmaker 0.95.8 - neither issue
Tab Window Manager 1.0.10 - neither issue

...for whatever that's worth.

**Comment by s5k6** [comment] 2020-07-18 23:12
I have just tested this, and can verify that the problem persists with darktable 3.1.0+2475~g08eba104b.

To test with FVWM: Put `Module FvwmCommandS` into your FVWM config file, wich would probably be `~/.fvwm2rc` or `~/.fvwm/config`, depending on your installation.  Maybe this module is already loaded, otherwise the following commands will hang/fail.

At the command line, type

    FvwmCommand 'mouse 1 A 4'

to unbind the handling of [Hyper+LeftClick], or type

    FvwmCommand 'mouse 1 A 4 nop'

to bind it to the no-operation function `nop` which does nothing.  I suggest to bind to `nop` to rule out the possibility that the bound operation has an effect.  But you could use `Raise` instead, which would raise a window when you left-click on it with the Hyper (aka. Logo, Windows) key held down.

As with the bug described in https://redmine.darktable.org/issues/12387#change-37352, when I disable bindings to [Hyper+LeftClick], then [Ctrl+LeftClick] on a thumbnail works properly (adds/removes the image from the selection), but the problem appears again when I bind [Ctrl+LeftClick] to any operation.

Darktable is the only program that shows this kind of behavior, [Ctrl+LeftClick] always works properly with the file selection dialogs of Gimp and Libre Office.

For the window managers you observe the problems with: Do you know whether they bind [Hyper+LeftClick] to anything?

Cheers
Stefan

**Comment by junkyardsparkle** [comment] 2020-07-19 06:45
> I suggest to bind to nop to rule out the possibility that the bound operation has an effect.

Binding to `nop` as described does indeed cause the issue for me in FVWM, where it didn't exist otherwise.

> For the window managers you observe the problems with: Do you know whether they bind [Hyper+LeftClick] to anything?

I only observed it in Fluxbox, and there it happens both with a default config where Mod4 + Mouse 1 is not bound to anything, and with the configuration I had been using, where this combination is used for moving windows (the default binding is Alt+Mouse 1, but GIMP and some other apps use this combination, so it's not a good choice).

So, I guess I didn't really shed any light on anything there... :roll_eyes:

**Comment by s5k6** [comment] 2020-08-02 09:47
@edgardoh, maybe I can draw your attention to this.  In 2019, you've fixed #12387 which seemed to also be related to the choice of window manager...

**Comment by s5k6** [comment] 2020-08-30 08:44
This bug persists with darktable 3.2.1 compiled from commit 3e323b355

**Comment by s5k6** [comment] 2020-09-27 13:07
This bug persists with release-3.3.0-845-g9bfedf80d

**Comment by stanford-scs** [comment] 2020-09-28 16:45
I'm having this problem with fvwm2 as well.  A workaround is to use the space bar to select or deselect images.  Like some of the other users, I have Alt- and Meta-Leftclick bound to a function, but not control leftclick.  In my `~/.fvwm2rc` file:

```
Mouse 1 FTSW        M       Move-or-Raise
Mouse 1 FTSW        4       Move-or-Raise

DestroyFunc Move-or-Raise
AddToFunc Move-or-Raise         "I" Raise
+                               "M" Move
```

**Comment by s5k6** [comment] 2020-10-31 10:07
The problem persists with current master darktable 3.3.0+1264~gf2e8fd9fe

**Comment by johnny-bit** [comment] 2021-06-29 09:00
Have you filled the issue with fluxbox and/or blackbox and/or fvwm too? It's imo pretty much out of scope of darktable to control external windowmanager behaviour. Also have you been able to test whether PR #8078 fixes the problems for you as it's competely rebuilt input system?

**Comment by johnny-bit** [comment] 2021-07-30 08:30
I've just closed one issue regarding weird flubxbox-only problem... Now - have the problems in the fluxbox, blackbox and fvwm have been raised in their respective bugrackers?
Have you checked if InputNG fixes/alleviates some of the issues?

**Comment by caigner** [comment] 2022-04-17 07:31
I am running Darktable 3.8.1 on Gentoo Linux (Fluxbox): Can't select multiple images with CTRL-Left Click or SHIFT-Left Click.
Selecting with SPACE bar works.

**Comment by ig9000** [comment] 2022-11-15 21:44
There's a recently reported issue with Fluxbox using Chromium-based browsers that seems related, might help with triangulation:

 https://sourceforge.net/p/fluxbox/bugs/1187/

**Comment by AlicVB** [comment] 2022-11-15 21:57
effectively that sound very similar. At least comment https://sourceforge.net/p/fluxbox/bugs/1187/#2b54/5ab0 would explain lot of things... and confirm that fluxbox is doing some weird things with gtk events... sending the leave event on mouse click and even worse before the press event ???

**Comment by ig9000** [comment] 2022-11-15 22:27
I'm not sure the Fluxbox devs pay any attention to the Sourceforge tickets, and the Github repository doesn't have issue tracking enabled, but maybe giving @mgumz a mention here will help to put it on the radar.

**Comment by mgumz** [comment] 2022-11-18 20:01
=)

so, fluxbox has quite an extensive keyboard-short-cut system. to apply it, fluxbox grabs the root window and then checks if the pressed keys are bound to fluxbox … and only if not, they are replayed to the lower windows.

you can remove the keys you want to use in darktable from ~/.fluxbox/keys … and then i do not see an issue. this situation is like that for ever: fluxbox wins over keyboard shortcuts it uses (or the user defines) and only then the application get it. i had to remap various keyboard shortcuts which are "useful" (lots of bindings via "alt") in blender...

**Comment by ig9000** [comment] 2022-11-19 23:18
@mgumz  Thanks for responding!

I understand that's the basis of how X works, but I don't think it explains the dysfunctional Ctrl+click described in this issue. I am experiencing that, but also with Shift+click as well. I obviously don't have assignments for these in my keys file causing the problem - they have always worked normally with other software. I think the pathological leave event which has been pointed to is worth taking a look at. The fact that it's causing problems on popular browsers means it's probably going to bite more people in the future.

I found a few other darktable issues mentioning fluxbox, most of which seem to be variations of this one, but I found particularly interesting #8542, which I can reproduce. That one would be hard to explain with a bad key binding, I think. :wink:

**Comment by mgumz** [comment] 2022-11-20 09:07
@ig9000 to rule out keybindings of fluxbox: provide the .fluxbox/keys file. minor not: also "mouse actions" are stated in the keysfile …

**Comment by ig9000** [comment] 2022-11-20 21:18
I can reproduce this issue and #8542 using [the default key file](https://github.com/fluxbox/fluxbox/blob/master/data/keys), Same with using a *completely empty* key file. Are you *not* able to reproduce them?

**Comment by caigner** [comment] 2023-05-25 06:17
I can confirm that in DT 4.2.x CTRL-click and SHIFT-click works as expected.
For me the issue is solved.

**Closed** 2024-05-21 00:17 UTC
Labels: bug: upstream, scope: UI, bug: pending, no-issue-activity
