### ISSUE TITLE
cannot display filmstrip in darkroom view

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#2462] opened 2019-04-27 15:05 UTC
**Describe the bug**
cannot display the filmstrip in darkroom view

**To Reproduce**
go to darkroom view
Primary-Shift-b to view bottom panel
Primary-Shift-f to view filmstrip

**Expected behavior**
filmstrip should appear
but nothing appears.  filmstrip does appear in map and print views,
just does not appear in darkroom view.  and Primary-f does toggle view 
of timeline in lighttable with bottom panel visible or not.

**Platform (please complete the following information):**
opensuse Tumbleweed 20190425
display 1920x1080

**Comment by Nilvus** [comment] 2019-04-27 15:10
Have you been on darktable prefs and shortcuts tabs to see if or which shortcuts is activated for filmstrip ? I've always used ctrl+f to show or hide filmstrip and it works great even on darkroom.

**Comment by ptilopteri** [comment] 2019-04-27 15:35
yes, 
`grep \<Primary\>f ./keyboardrc ./keyboardrc_default 
./keyboardrc:; (gtk_accel_path "<Darktable>/views/map/toggle film strip" "<Primary>f")
./keyboardrc:; (gtk_accel_path "<Darktable>/views/darkroom/toggle film strip" "<Primary>f")
./keyboardrc:; (gtk_accel_path "<Darktable>/views/tethering/toggle film strip" "<Primary>f")
./keyboardrc:; (gtk_accel_path "<Darktable>/views/print/toggle film strip" "<Primary>f")
./keyboardrc:; (gtk_accel_path "<Darktable>/views/lighttable/toggle timeline" "<Primary>f")
./keyboardrc_default:(gtk_accel_path "<Darktable>/views/map/toggle film strip" "<Primary>f")
./keyboardrc_default:(gtk_accel_path "<Darktable>/views/darkroom/toggle film strip" "<Primary>f")
./keyboardrc_default:(gtk_accel_path "<Darktable>/views/tethering/toggle film strip" "<Primary>f")
./keyboardrc_default:(gtk_accel_path "<Darktable>/views/print/toggle film strip" "<Primary>f")
./keyboardrc_default:(gtk_accel_path "<Darktable>/views/lighttable/toggle timeline" "<Primary>f")
`

**Comment by Nilvus** [comment] 2019-04-27 16:47
That's not really easy to read... 
So that not "Primary+Shift+f" to you use as you write on your first post but "Primary+f".
Apart of that, which version of darktable do you use ?

**Comment by ptilopteri** [comment] 2019-04-27 18:54
yes, my bad.  I use the default, Primary+f
and dt from git master, darktable-2.7.0~git1070.9a8348808-1225

**Comment by ptilopteri** [comment] 2019-04-27 19:01
and now 2.7.0~git1070.9a8348808-1225

**Comment by wpferguson** [comment] 2019-04-28 00:10
The difference is that timeline is not part of the bottom panel and filmstrip is.  To test, go to lighttable view and toggle the bottom panel on and off.  You'll see the bottom panel disappear and reappear, but the timeline doesn't change.  In darkroom view, if you toggle the bottom panel on and off, then the filmstrip disappears with the panel. I would say that they both should behave in the same manner, but I'm not sure which manner is correct.

**Comment by ptilopteri** [comment] 2019-04-28 03:03
problem is, I do not see the filmstrip in darkroom view with the bottom panel visible.  I cannot toggle
it on.
timeline is only visible in lighttable view and filmstrip is not visible in lighttable view, I understand.

I see no problem with the present settings for timeline or filmstrip.  afaics filmstrip serves no purpose
in lighttable view.

**Comment by Nilvus** [comment] 2019-04-28 13:58
@wpferguson : filmstrip is only for darkroom view. It is unuseful on lightable view.

You could have (on your choice) timeline on lighttable view and filmstrip on darkroom view. It's normal and logic. Apart of that, shortcuts and these functions are since a long time working great on darktable. So this issue is probably on your OS only. Try saving darktablerc on another folder to remove it from your home darktable folder. Of course with darktable closed. After that, relaunch darktable, it will create a default new darktablerc file. Try to see if shortcuts works great with the new darktablerc file (of course if necessary, verify shortcuts part of preferences dialog.

**Comment by ptilopteri** [comment] 2019-04-28 14:39
sorry, should have thought of running with blank darktablerc.  indeed provides filmstrip.  

guess next to compare new rc to old and try to find problem.

any other suggestions?

tks,

**Comment by Nilvus** [comment] 2019-04-28 14:49
Nope. I would made just what you suggest, compare both files to see what could cause the problem. If you find it, post it here would be a good idea.

**Comment by ptilopteri** [comment] 2019-04-28 15:19
looks like problem is following line in darktablerc
    darkroom/ui/bottom_visible=FALSE

removing that line, restarting dt, hide bottom panel, close dt
and errant line is back but dt now will toggle filmstrip.

perhaps dt lost track of the toggle state somehow, beyond my understanding.

the *only* change to darktablerc I made was to remove cited line.  closing and
restarting dt no longer show problem.

I can close this issue or you can or we can investigate further ???

tks for help.  you are patient

**Comment by ptilopteri** [comment] 2019-04-30 22:27
leaving as solved.  encountered some more er difficulties so replaced darktablerc and copied back matching entries from previous that showed plugins or personal information and computer memory/storage related information.  new rc is comsiderable smaller, > 20%

**Comment by mlaverdiere** [comment] 2023-07-14 11:01
I've just encountered the same bug on dt 4.4 on Fedora 39: no visible filmstrip in darkroom (just un blank bottom bar). Pressing ctrl-f makes the blank bar disappear and reappear, but no filmstrip, See screenshot attached. 

The same solution reported by @ptilopteri worked (with a slight variant), i.e. closing darktable and removing the following line from darktablerc: 

plugins/darkroom/0/filmstrip_visible=FALSE

Should this report be reopened or should I fill a new bug report?

![Capture d’écran du 2023-07-14 06-44-05](https://github.com/darktable-org/darktable/assets/30075133/7d029468-acc8-4d71-a7ec-20af3693938f)

**Comment by Nilvus** [comment] 2023-07-14 11:43
No need to reopened or even fill a new bug report. darktablerc store setting. If that line was to FALSE, that means that filmstrip will never be visible. So works as expected. I do not know why this line is like that but just removing it as you do or simply replace FALSE by TRUE let filmstrip works as you want.

**Comment by mlaverdiere** [comment] 2023-07-14 11:58
Well, that's the bug: how come this line got in dartablerc?

To my understanding, this line is not generated by selecting and option in the preferences or elsewhere in the gui to completely deactivate the filmstrip in the darkroom. And It's not expected that a blank bar appears instead of the filmstrip upon pressing ctrl-f...

**Comment by Mark-64** [comment] 2023-08-04 12:34
Same isssue here, DT 4.4.2 on Window 11.
I am sure I had the filmstrip when I first installed 4.4.2 (self compiled).
Then it disappeared while I was edidit some pics. I don't recall exactly what I did.
My darktablerc has no lines referring to filstrip

**Comment by zakfm** [comment] 2023-08-27 17:35
I have this same problem, but none of the solutions suggested in this post work for me.
I'll soon know all 504 lines of my darktablerc by heart. 
I can't find a single line with filmstrip or bottom=false.
I moved darktablerc to my home folder for storage, and restarted darktable. The film was still missing by typing ctrl+f which enlarges the bottom panel.
Also, no new darktablerc appeared.
I put the old one back in place. 
In desperation, I added a 505th line: "plugins/darkroom/0/filmstrip_visible=true".
This did nothing.
If anyone has a solution, thank you very much.

**Comment by zakfm** [comment] 2023-08-28 09:33
This morning I'm searching for darktablerc on my computer kde neon with Kfind.
Result: there are two of them:
This one I knew well:
/usr/share/darktable/darktablerc
And this one: /home/zwank/.config/darktable/darktablerc, which I opened.
I found "darkroom/ui/0/bottom_visible=FALSE" and "plugins/darkroom/0/filmstrip_visible=FALSE".
I corrected both lines to TRUE **and my thumbnails are back.** 

My concern now is that I can't find the /home/zwank/.config/darktable/ folder.
And also to understand how this problem happened.

**Comment by AlicVB** [comment] 2023-08-28 17:06
yes, `/home/zwank/.config/darktable/darktablerc` is the right one. The other one is the default base for first install (and should be readonly anyway)

I'm not able to reproduce the issue, but it would be really interesting to know which one of the 2 lines you mention is the problematic one. Can you please test : 
- close darktable
- open /home/zwank/.config/darktable/darktablerc
- add one of the 2 line, save and quit
- reload dt and see what happen to the filmstrip
- same with the second line (remove the first one)

that way we will have more clue about what is going on.
Thanks !

**Comment by zakfm** [comment] 2023-08-28 18:16
Hello,

When I set plugins/darkroom/0/filmstrip_visible to false= the thumbnails disappear.

When I set false to darkroom/ui/0/bottom_visible= the thumbnails stay there. And when I return to darktablerc, darkroom/ui/0/bottom_visible= is automatically set back to TRUE.

**Comment by AlicVB** [comment] 2023-08-28 21:14
Right, so the culprit is `plugins/darkroom/0/filmstrip_visible=FALSE`...
The next step is to imagine how this line can have been written here. I'll try to see in the code how this has been possible...

**Comment by zakfm** [comment] 2023-08-29 06:59
For information, my recent history was a big cleanup of different versions, snap, and the ubuntuhandbooks and opensuze repositories all in 4.4.2 then a reinstallation of the 4.4.1 ppa proposed by discover. At first, everything worked perfectly. Then in the afternoon, the thumbnails disappeared, but I don't know why. I'd just imported some old .nef films. I tried again today and all's well. Good luck in finding a solution to this problem, which has affected other people recently: [https://forums.darktable.fr/showthread.php?tid=6536&highlight=imagettes](url)

**Comment by zakfm** [comment] 2023-08-30 15:10
Like Timo573, when switching from the darkroom to the light table, I had a screen shake when closing dt. When I opened it again, the thumbnails had disappeared. I set plugins/darkroom/0/filmstrip_visible=FALSE back to TRUE. They came back.
I can't reproduce this fault on purpose.
I'll keep looking.

**Comment by AlicVB** [comment] 2023-08-30 15:20
@Timo573 @zakfm : do you mean you still can reproduce with 4.4 version of dt ?
What I mean is : 
- you have the bug
- you "solve" it by editing/removing darktablerc
- you can reproduce it (even not on purpose)

That would mean this bug can be triggered with new dt install, and not a "faulty" old version.
Thanks for your answer

(btw, considering the comment, I reopen the bug)

**Comment by zakfm** [comment] 2023-08-30 15:22
Absolutely

**Comment by AlicVB** [comment] 2023-08-30 16:02
oh great, I just manage to reproduce : 
1. open dt, switch to fullpreview mode
2. press "d" to enter darkroom
3. close dt

- dt closing need 2 try
- the thumbnails in darkroom are gone after that. 

The good new is that I know where's the issue for the second point. "Just" need to investigate the first one ;)

**Comment by AlicVB** [comment] 2023-08-30 16:44
ok, PR #15134 should fix it.

Note that you need to remove you problematic `plugins/darkroom/0/filmstrip_visible=FALSE` from darktablerc first. @TurboGit : considering the small number of impacted users, I'm not sure it's worth the pain to add a hacky fix to ensure `plugins/darkroom/0/filmstrip_visible` is always `TRUE` at startup... what do you think ?

**Comment by TurboGit** [comment] 2023-08-30 18:26
> @TurboGit : considering the small number of impacted users, I'm not sure it's worth the pain to add a hacky fix to ensure `plugins/darkroom/0/filmstrip_visible` is always `TRUE` at startup... what do you think ?

No, not needed to me. IIRC we had less than 5 peoples with this issue and we have given the workaround to fix that manually.

**Closed** 2023-08-30 19:30 UTC

**Comment by Timo573** [comment] 2023-09-03 18:58
> @Timo573 @zakfm : do you mean you still can reproduce with 4.4 version of dt ? What I mean is :
> 
>     * you have the bug
> 
>     * you "solve" it by editing/removing darktablerc
> 
>     * you can reproduce it (even not on purpose)
> 
> 
> That would mean this bug can be triggered with new dt install, and not a "faulty" old version. Thanks for your answer
> 
> (btw, considering the comment, I reopen the bug)

I remove darktablec, or actually change the name of it.  DT create new darktablec when opened and the filmstrip is there.  I then did my edits to it  and so after DT works fine.  
I think that reloading DT do not fix the issue.  I have had some other minor missing functions that did not get fixed when updating to 4.42. 
Difficult to explain what the other missing functions are but I try.  The whitebalance could not be corrected with color calibration. Trying the pipet change the colors very odd.  That got fixed and now selecting white color with pipet corects the colors. Another issue was that I could not get the info box opened when hovering mouse on the instances on right side of the darkroom view.  This is also working with new reloaded darktablec.

**Comment by AlicVB** [comment] 2023-09-03 20:02
Considering your other issues, can you open a new issue ? Attaching the faulty darktablerc might help... Thanks !

**Comment by Timo573** [comment] 2023-09-03 21:47
Mayby I should but I can not explain more than I did above.  I have use DT more than 2 years and I have no idea when and in what version these failures come.  About half a year ago I find it out by playing DT with my laptop insted of table top that I use regularry.  In that time I try to fix the info box issue and read instructions and manual but could not fix it.  Both of these were minor problems and did not bother me so I just used DT as it was.  I mean that it is possible these are operator failures.  If same happends again I will open new case.

**Comment by zakfm** [comment] 2023-09-04 08:17
Just for your information, the update to 4.4.2 was carried out automatically and immediately with discover, and I've had no problems whatsoever. Thank you

**Comment by Ehsanphotos12** [comment] 2023-09-07 10:10
I have the same issue with the Filmstrip in Darkroom. _Ctrl-f_ toggles it to an empty space where the _Filmstrip_ is supposed to be but it does not show the images. I also used _Ctrl-Shift-b_ before and after, with no difference. This issue started since I’ve installed _4.4.2_. Before, everything was working fine. I have tried all of the above solutions explained by others, but nothing worked. I should mention my _darktablerc_ did not contain any of the lines _darkroom/ui/0/bottom_visible=_ or _plugins/darkroom/0/filmstrip_visible=_ mentioned by others. I copy-pasted them and set the values to TRUE but they did not make any difference either. In desperation, I uninstalled Darktable and deleted all the files from my system and reinstalled it again. It worked fine for the first time. But when I restarted it later the issue came back again.

**Comment by Ehsanphotos12** [comment] 2023-09-08 11:36
> darktablerc

Thanks a lot for the reply and the tip 😀 I did not expect the file to be in some other folders out of _Darktable_. I found it in _C:\user\appdata…_. By chance any tips on closing the _Darktable_. This is also a new issue since _4.4.2_. Whenever I close the _Darktable_ a second window appears behind it which needs to be closed. It doesn't make a difference if I close the program in _Darkroom_ or _Lighttable_.

**Comment by Ehsanphotos12** [comment] 2023-09-08 11:54
> @Ehsanphotos12: Hi, there are 2 darktablerc. The one you inspected must be the system one. The one you need to check is in your home's hidden files. There you'll find the FALSE to change to TRUE. And then no more problems.

In my case the problem keeps coming back again. I had to go to _darktablerc_ and change the value to _TRUE_. I don’t know why it keeps changing🤔. Any ideas on that?

**Comment by AlicVB** [comment] 2023-09-08 11:58
@Ehsanphotos12 : as said earlier in this thread, I've fixed your issue. The fix will be part of next darktable version.
Normally, the TRUE value will appear only if you quit darktable from darkroom. So to mitigate your problem before the next release, you can always go back to lighttable before quitting.
Note that this also happen if lighttable is in fullpreview mode...

**Comment by zakfm** [comment] 2023-09-08 12:07
@Ehsanphotos12 : This is where the correction should be made: plugins/darkroom/0/filmstrip_visible=FALSE 
and,
As far as I'm concerned, this double closure only comes into play in the light table when closing the full-screen preview.
I think it's better this way.
And also,
where does your 4.4.2 come from ? Any other versions out there ?

**Comment by Ehsanphotos12** [comment] 2023-09-08 12:24
> 

@zakfm : Yes, that’s exactly what I did. And it works perfectly after that. However after 2-3 times closing the program it came back again and the value was changed to _FALSE_ on its own.
I download only from the official website: https://www.darktable.org/install/

**Comment by Ehsanphotos12** [comment] 2023-09-08 12:25
> @Ehsanphotos12 : as said earlier in this thread, I've fixed your issue. The fix will be part of next darktable version. Normally, the TRUE value will appear only if you quit darktable from darkroom. So to mitigate your problem before the next release, you can always go back to lighttable before quitting. Note that this also happen if lighttable is in fullpreview mode...

Thanks for the info. Yes, I will do that.

**Comment by fumblefox** [comment] 2023-12-06 14:56
Hi. I had the disappearing filmstrip problem too, DT 4.4.2 on Windows 10. After a couple of reinstalls and a lot of headscratching I found this thread. The Appdata\local\darktable\dartktable RC filmstrip to TRUE fix worked for me. Quitting from lighttable advice duly noted! Cheers all.
