### ISSUE TITLE
applying a style via a shortcut loses the history on undo

### ISSUE THREAD

**Issue by phil20099** [darktable-org/darktable#10639] opened 2021-12-15 14:10 UTC
**Background**
I have 3 styles that apply a red, green or blue B&W filter via a new instance of the colour calibration module.

I’ve added shortcuts (shift R, G, B) so I can quickly cycle through the filters to see which is the best filter for that particular image.

If I apply a style via the shortcut then undo the change, it loses the entire history stack.

I’m unsure when I first noticed the issue as I’ve only been using these shortcuts for the last few weeks.

Latest master 3.7.0~git1691.3513008bfc-1 on Ubuntu 20.04.

Another user has tested this and confirmed they can reproduce the issue.

**Minimal steps to reproduce**

1. Open an unprocessed image.
2. There are 11 items in the history stack - assuming scene referred and modern chromatic adaptation.
3. Normally I would apply lens correction, adjust the exposure etc but I’ve left these out.
4. Shift + B to apply the blue B&W filter [it doesn’t matter which shortcut you use].
5. Use control + z to undo the last step reverts to 8 items in the history stack i.e. not the original 11 nor one step back.. 

I would expect it to undo the last action.

History after step 4

![1](https://user-images.githubusercontent.com/60315272/146200490-32e37f4a-5e91-4537-aaef-c5e448acda88.png)

History after step 5

![2](https://user-images.githubusercontent.com/60315272/146200548-0b068a7c-7c9d-4568-9b34-81e9b910ef2a.png)

**Additional points**
Using redo via control + y works as expected i.e. it gets me back to the point before the undo so 12 items in the history stack.

The issue isn’t related to one image as it occurs on a play raw file by someone else.

On resetting the history stack from within darkroom it reverts back to the original 11 items in the history stack.

If I manually apply the style via the quick access menu (lower left in darkroom) undo works as expected.

Thanks to Claes for the below.
If you run darktable via the command line then on doing the undo it reports :

(darktable:16094): Gtk-CRITICAL **: 13:59:48.423: gtk_notebook_get_current_page: assertion 'GTK_IS_NOTEBOOK (notebook)' failed
[_dev_auto_apply_presets] missing mandatory module rawprepare for image 1008
[_dev_auto_apply_presets] missing mandatory module temperature for image 1008
[_dev_auto_apply_presets] missing mandatory module highlights for image 1008
[_dev_auto_apply_presets] missing mandatory module demosaic for image 1008
[_dev_auto_apply_presets] missing mandatory module flip for image 1008
[_dev_auto_apply_presets] missing mandatory module colorin for image 1008
[_dev_auto_apply_presets] missing mandatory module colorout for image 1008
[_dev_auto_apply_presets] missing mandatory module gamma for image 1008

Below is my style for the blue filter as a **txt** file rather than **dtstyle** file as dtstyle isn't a supported file type.
[B&W filter blue.txt](https://github.com/darktable-org/darktable/files/7720000/B.W.filter.blue.txt)

**Comment by ClaesGitHub** [comment] 2021-12-15 14:17
Verified -- also gives problems as per description above using dt-git 3.7.0-1685-g3513008bf
on Garuda Linux (arch).

**Comment by TurboGit** [comment] 2021-12-15 16:03
Does it work if you two `ctrl-z` in step 5? Maybe there is some missing grouping in the undo code when using shortcuts.

**Comment by ClaesGitHub** [comment] 2021-12-15 16:51
@TurboGit 
No. Same as above (and same messages in terminal).

**Comment by phil20099** [comment] 2021-12-15 18:59
_Does it work if you two ctrl-z in step 5?_

For me it does work.
1. Open an unprocessed image.
2. Apply lens correction and adjust the exposure (I wanted extra items in the history to see where a second control + z would take me).  So total 13 items in the history.
3. Apply the shortcut via shift & B for the blue B&W filter.
4. The first control + z gives me 8 items in the history stack as first mentioned.
5. A second control + z takes me back to just after step 2 i.e. total 13 items in the history, the original 11 + lens correction and exposure.

The terminal still reports the errors from the first control + z.

**Comment by ClaesGitHub** [comment] 2021-12-15 19:02
Hmmmm. But not here. I wonder why...
Will experiment more.

**Comment by ClaesGitHub** [comment] 2021-12-16 09:34
@TurboGit 
Two small clues found:
1) In original dtstyle from OP, dt complains about an unescaped ampersand in line 1. For that reason, I made a simply dtstyle myself (just invoking negadoctor). I assigned it to shortcut F8.
2) In dt preferences/processing, if I set _auto-apply chromatic adaptation defaults_ to **modern**, Pascal's two _ctrl-z_ works fine,
but if _auto-apply chromatic adaptation defaults_ to **legacy**, Pascal's two _ctrl-z_ have no effect.

**Comment by phil20099** [comment] 2021-12-16 11:33
_In original dtstyle from OP, dt complains about an unescaped ampersand in line 1_

I think this is because I had included an ampersand in the name of the new instance of the colour balance i.e. "B&W".

I've deleted and rebuild my styles and shortcuts and the errors about the ampersand no longer appear however I still have the issue with the history stack.

**Comment by TurboGit** [comment] 2022-10-19 08:00
Ok the issue is understood but hard to fix. When a style is applied the db is changed directly using the style information recorded into the db. The undo history items are then flagged as DT_UNDO_LT_HISTORY. But this clashes with the undo on the darkroom which is DT_UNDO_HISTORY which changes directly the develop history list. Also while in the darkroom an UNDO is done for DT_UNDO_HISTORY and not DT_UNDO_LT_HISTORY for this reason. This is mostly recording my finding, no fix yet in sight!

**Comment by TurboGit** [comment] 2022-10-19 08:55
@dterrahe : I need your help here.

The current way to apply a style via a shortcut is in `common/styles.c` : 
`  static void _apply_style_shortcut_callback(dt_action_t *action)`

This is ok when used via the lighttable.

I need another way of applying a style when in darkroom using the same key.

Is it possible to create a second callback routine in darkroom that will be triggered using the same shortcut? My idea is to add a check in both and use the current one when in lighttable and the new one when in darkroom.

TIA.

**Comment by dterrahe** [comment] 2022-10-19 13:07
Doesn't the shortcut work in all views? Then it just means at the beginning of the routine checking which view you are in and deciding what to do based on that.

**Comment by TurboGit** [comment] 2022-10-19 15:02
> Doesn't the shortcut work in all views?

Sure, but then I'll have to refactor some code to be able to do what I want. The current routine handling the style apply for the darkroom is in `views/darkroom.c` which is not accessible from `common/styles.c`. But I think I can do it. I was just trying to see if as signal in Gtk when a callback does not handle it is is passed to the next connected, etc.

**Comment by TurboGit** [comment] 2022-10-21 14:15
@phil20099 : Should be fixed now. Will be part of dt 4.2.

**Closed** 2022-10-21 14:14 UTC
Labels: priority: medium, understood: clear, reproduce: confirmed, difficulty: hard, bug: pending, release notes: pending

**Comment by phil20099** [comment] 2022-10-21 14:25
Fantastic, thank you.  I make use of shortcuts so this fix will be really useful.
