### ISSUE TITLE
Smarter masks 

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#13175] opened 2022-12-21 13:28 UTC
**Is your feature request related to a problem? Please describe.**

I would like smarter ways of defining masks for modules. 
I deliberately don't use the word 'better', because this is debatable. I would like the algorithms to have more built-in smartness. 

Selecting a subject is usually hard and involves a lot of work. Especially when the shape is more difficult, like a models' hand. 

Darktable gives a lot of control to the user, with different shapes, nodes, node-types, 7 different color-selection-sliders, feathering control and mask-combination.
Is this not enough? 

The answer is: It is too much. 
The more super-fine control I have, as a user, the more work I must do to get it right.

This is a philosophy-thing:  Suppose Darktable gave me full control over each individual pixel.
It would indeed be possible to get perfect results, but at a ridiculous cost.
Look at Lightroom, for example. As single (!) mouseclick separates a subject from the background.  So what if it is only 99% right?  So what if there are examples where it would not work perfectly?
It helps.   It automates all my manual work.  I can not get it much better in 50-100 mouseclicks!

**Describe the solution you'd like**
More intelligence built in to DT to help creating masks.  It does not need to be perfect, I am looking for assistance.  I don't want more control, I want more intelligence built in DT to help me.

Things that work for me:
- the magic laso of Gimp with its variable  sensitivity. When you hit the sensitivity right, you select the entire subject in a few mouseclicks.
- adding and removing bits of the mask, so when it's not perfect you can fix it easier. 
- Growing and contracting the mask per pixel

Things that might work:
- pixel based masks instead of shape/slider/node-based
- Add the not-yet-selected pixels in an enclosed area instead of increasing the feathering
- combining the pixel-contrast, sharpness and color-information to determine what is background and subject.

**Comment by MStraeten** [comment] 2022-12-21 13:57
> The answer is: It is too much.
The more super-fine control I have, as a user, the more work I must do to get it right.

there's no magic that can do complex stuff in a simple way without a price. darktable prioritizes control over simplification

regarding your solution:
keep in mind that even "intelligence" needs to be described in a way a developer can implement it .
If a mask can be described as a set of rules then it consumes a lot less memory than if it's a kind of bitmap - so your first suggestion of solution comes with a price slowing down a system that already needs a lot of effort spent to be tweaked for perfomance. 
And for your last suggestion: please provide the appropriate algorithms for that ;)

**Comment by dterrahe** [comment] 2022-12-21 15:41
Duplicate of #10439, #12205, #12316 combined with bitmap drawn masks (the many FRs for which I won't look up on my phone).

**Comment by rekcodocker** [comment] 2022-12-21 16:17
Like 'intelligent scissors' in the open source project Gimp. 

Control is nice, more control is also nice. But there comes a point where the learning curve becomes too steep. 
As to demands on CPU and memory: A computer is a one-time expense.  On the other hand, a user has to invest time for every single picture, just so the computer doesn't have to work too hard.  Time is the most precious most people have. 

As to algorithms: The intelligent scissors that Gimp has would be nice.
I understand it won't be possible to clone the code.  But the research and development has been done, the algorithm would work. 

At some point Darktable is just not going to be something you can recommend to innocent users. 
I understand it is really, really hard to take photo-editing experience and put it in code.  But that is what software is; it takes work away from people.

**Comment by TurboGit** [comment] 2022-12-21 16:26
> I understand it won't be possible to clone the code. But the research and development has been done, the algorithm would work.

Not so simple, the darktable masking is done based on shapes (vectors) and not pixel mask layer. So algorithm is one point, yet cannot be used as-is and the result won't be usable. So for now there is no easy solution.

**Comment by MStraeten** [comment] 2022-12-21 17:01
why should a developer spend time on doing stuff for users not willing to spend time theirself?
‚Innocent users‘ aren’t really targeted by darktable - there’re plenty of simpler tools available for those that doesn’t want to spend time on learning how to use darktable

**Comment by Nilvus** [comment] 2022-12-21 19:16
As it's a duplicate of some other issues, this probably do not have to remain opened. I can close it, waiting for feedback about that anyway, regarding discussion there.

But regarding your last comment, some things are discutable. First, I agree with all things reported by @TurboGit and @MStraeten. But also:

> As to demands on CPU and memory: A computer is a one-time expense. On the other hand, a user has to invest time for every single picture, just so the computer doesn't have to work too hard. Time is the most precious most people have.

Not all people can easily buy another computer. And life change or resources we have. So yes time is the most precious most people have but money to buy another computer is also limited for some people. Having a good computer for RAW processing is not something cheap. And it's worse if you need to use a laptop (with a correct screen, with at least 100% srgb gamut and good graphic card). It's more expensive since some months. So what powerful is needed is also something to take care.

So, there's probably some improvement possible but taking care of powerful needed remains important. It's all about compromise. And coding what you ask for is certainly not easy on a non pixel software (like Gimp is).

**Comment by spaceChRiS** [comment] 2022-12-23 15:40
> Not so simple, the darktable masking is done based on shapes (vectors) and not pixel mask layer. So algorithm is one point, yet cannot be used as-is and the result won't be usable. So for now there is no easy solution.

I thought about this topic a lot when I was using [rembg](https://github.com/danielgatis/rembg) for cutting out my son's soccer teammates from an ugly background, which saved me days of work compared to masking them in darktable (what I did the year before) or using gimp (which I tried this year first, with debatable success), and it turned out almost perfect (Only 1 of ~50 pictures had a minor glitch, where a background “island” was “forgotten” by the neural network). I wonder if it would be feasible to have a generic “raster mask emitter” module which is a no-op/pass-through in terms of the pipeline but generates a raster mask for later modules.

In a first step, it could simply export the current image at its current position in the pipe and load an external mask image as mask if the image is given. E.g., export as `<raw-filename>-mask_base-<instance>.jpg` and import `<raw-filename>-mask-<instance>.png` if present. The user could generate an external mask and save it as b/w png, which then would be read at the next pixel-pipe run. The export -> generate mask manually, e.g. with rembg or gimp -> import paradigm would ensure that the geometry of the raster mask is correct. The instance number would be needed to distinguish several modules.

As this workflow would be difficult to understand, the module could be hidden by default. It would only serve as a first step for prototyping new raster mask generators. Later, different algorithms could be implemented that directly generate a raster mask. I would not expect all masks to be fast, but early in the pipe, the number of recomputes would hopefully not be too high. Therefore, a button in the module to manually update the (cached) mask would maybe make sense.

Just some food for thoughts, maybe there are big disadvantages that I did not see …

**Closed** 2023-04-24 14:19 UTC
Labels: duplicate, no-issue-activity
