### ISSUE TITLE
Crash before start

### ISSUE THREAD

**Issue by seacritter** [darktable-org/darktable#7928] opened 2021-01-19 13:35 UTC
**Describe the bug**
I click the icon to start the program and I get an error message.  The error says:
An unhandled exception occurred.
Backtrace will be written to:
C:\...
If you report this issue, please share this backtrace with the developers.

I have an "OK" button and when I hit it, it exits.

Attached is the backtrace
![darktableerror](https://user-images.githubusercontent.com/77677454/105041509-13fa4c00-5a31-11eb-8252-ece6247b3932.jpg)
[darktable_bt_2L3BX0.txt](https://github.com/darktable-org/darktable/files/5836163/darktable_bt_2L3BX0.txt)

**Comment by johnny-bit** [comment] 2021-01-19 14:07
Unfortunately this backtrace is completely empty...

couple things you can try, in order:
0. make sure your drivers are up to date
1. try starting darktable with empty config directory (nothing in `C:\Users\[username]\AppData\Local\darktable`)
2. Make sure darktable is added to exceptions in your antivir

**Comment by johnny-bit** [comment] 2021-02-21 09:30
Since you haven't provided more info - I'm closing the issue report.

Please:
1. make sure your drivers (ALL OF THEM, especially graphics) are up to date
2. try starting darktable with empty config directory
3. make sure darktable is not being blocked by antivir or any such software

If you manage to reproduce your issue please comment here with all the necessary data and I'll reopen the issue.

**Closed by johnny-bit** 2021-02-21 09:30 UTC
Labels: no-issue-activity, understood: unclear
