### ISSUE TITLE
Minor translation error in German

### ISSUE THREAD

**Issue by Konzertheld** [darktable-org/darktable#7979] opened 2021-01-24 03:15 UTC
In Darktable 3.4.0: When a shortcut is changed to a key that has already been assigned, the confirmation dialogue has an inappropriate title. The last word is "acceleration". While shortcuts do accelerate work, it should be "Tastenbelegung" = key assignment. :)

Wenn man eine Tastenkombination ändert auf eine, die schon vergeben wurde, hat der darauf folgende Bestätigungsdialog den Titel "Konflikt bei der Beschleunigung". Es sollte wohl eher sowas wie "Konflikt bei der Tastenbelegung" sein. :)

Update:

Noch einer (see comment for English): Im Sichten-Modus heißen unten im Feld für den Modus die Optionen "dynamischer Zoom" und "manuelle Sortierung". Im Englischen heißt beides "zoom". Das hat mich irritiert, da ich die Dokumentation gelesen und zwei gleiche Begriffe erwartet hatte. Ich finde "Sortierung" allerdings sogar passender, also schlage ich "dynamische Sortierung" und "manuelle Sortierung" vor als Änderung.

**Comment by Konzertheld** [comment] 2021-01-24 18:47
Adding one more: In culling mode "fixed zoom" and "dynamic zoom" are translated differently ("manuelle Sortierung" and "dynamischer Zoom"). I found that confusing because those are two different terms (Sortierung and Zoom) while in English and therefore in the documentation two similar terms are used (two zooms). I kinda like "Sortierung" more so I vote for "manuelle" and "dynamische" Sortierung but I do not know if there are any guidelines such as sticking as closely as possible to the original.

ping @7547 as this issue was mentioned there and this comment might get lost (updated original description, too).

**Comment by johnny-bit** [comment] 2021-06-13 16:31
@MStraeten - can this issue be closed? it's regarding de translations and as you're the most recent translator for de I'd like to know your opinion if the issue is fixed.

**Comment by MStraeten** [comment] 2021-06-14 08:00
i think this can be closed - there were several changes in 3.5 so i really don't get the issue yet - i'm not using 3.4 ;)

**Comment by johnny-bit** [comment] 2021-06-14 08:22
@Konzertheld - I'm closing this based off of comments of native speaker. While ages ago i could theoreticall verify, all that was left of my German is "Guten Tag", "Alles Klar" und "nein". :P

If the problem's still there in current master - please create new issue and bother the translator ;)

**Closed by johnny-bit** 2021-06-14 08:22 UTC
Labels: no-issue-activity, scope: translation
