### ISSUE TITLE
Darktable not starting

### ISSUE THREAD

**Issue by Rnies125** [darktable-org/darktable#15700] opened 2023-11-21 19:17 UTC
### Describe the bug

Darktable installed and ran without problems, but stopped loading a few days later.  I uninstalled, reinstalled with no change.  Tried several things and finally went to a restore point on my brand new computer.  Darktable ran fine until the next day.  Will not load and run.  No error message either.  I noticed a couple of other folks saying the same thing on Facebook groups.

Asus Laptop_Q540VJ
Windows 11
RTX3050
i9-13900H

### Steps to reproduce

Click on app icon

### Expected behavior

Load and run

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2-win64.exe

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11

### Describe your system?

See above

### Are you using OpenCL GPU in darktable?

None

### If yes, what is the GPU card and driver?

Netgear RTX3050  w/ 16G plus 6G

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

I see what looks like the command window flash, then nothing.

**Comment by gi-man** [comment] 2023-11-21 20:13
Can you post the output of darktable-cltest?

**Comment by Rnies125** [comment] 2023-11-21 20:39
If you tell me how to do that in detail.  I'm new to Windows 11 and most of this in general. 
Ron

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 21, 2023 at 12:13 PM, ***@***.***> wrote:   


Can you post the output of darktable-cltest?

**Comment by gi-man** [comment] 2023-11-21 23:34
A very short version that i hope it is correct, Go to run, type cmd, Enter
type cd c:\program files\darktable\bin Enter
type darktable-cltest Enter
copy/paste the results.

**Comment by Rnies125** [comment] 2023-11-22 00:47
Thank you.  I am trying, but the window closes as soon as the test is complete.  I'll need to figure out where the results go or keep the window open.
Ron

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 21, 2023 at 3:35 PM, ***@***.***> wrote:   


A very short version that i hope it is correct, Go to run, type cmd, Enter
type cd c:\program files\darktable\bin Enter
type darktable-cltest Enter
copy/paste the results.

**Comment by ptilopteri** [comment] 2023-11-22 01:01
open the cmd window, then inside the window:
  cd c:\program files\darktable\bin   <Enter>
  darktable-cltest  <Enter>

and the window should remain open until you close it.

**Comment by Rnies125** [comment] 2023-11-22 01:44
Yeah, it doesn't.   It closes as soon as the test is done.  Less than a second.   That may be my problem. 
Ron

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 21, 2023 at 5:01 PM, ***@***.***> wrote:   


open the cmd window, then inside the window:
cd c:\program files\darktable\bin 
darktable-cltest 

and the window should remain open until you close it.

**Comment by gi-man** [comment] 2023-11-22 02:51
hmm. You are now the second person reporting a similar issue. The other one was thru the matrix chat channel. His started after a recent windows update. 

I just booted my windows system to test to see if I can reproduce. I will build the latest version of the darktable to test it too.

**Comment by Rnies125** [comment] 2023-11-22 03:13
I recorded a video of the cltest and I'm attaching screen captures.   Hope this helps.
BTW, I ran sfc/scanner and it did find and correct corrupt files, but still not working. 
Ron





Sent from Yahoo Mail on Android 
 
  On Tue, Nov 21, 2023 at 6:52 PM, ***@***.***> wrote:   


hmm. You are now the second person reporting a similar issue. The other one was thru the matrix chat channel. His started after a recent windows update.

I just booted my windows system to test to see if I can reproduce. I will build the latest version of the darktable to test it too.

**Comment by gi-man** [comment] 2023-11-22 03:52
Please log on to GitHub and attach the files there. Reply by email does not attach them.

I tested the old version and build to the current master and it works for me. I'm now doing all the windows updates to restart and test after the update.

**Comment by Rnies125** [comment] 2023-11-22 04:02
Ok, took a video of the cltest.  Screen captures attached. I hope.
![Uploading 1001207958_1700622602243.jpg…]()
![Uploading 1001207958_1700622593659.jpg…]()

**Comment by Rnies125** [comment] 2023-11-22 04:03
Ok, took a video of the cltest.  Screen captures attached. I hope.
![Uploading 1001207958_17006
![1001207958_1700622602243](https://github.com/darktable-org/darktable/assets/151675262/0a3674b5-d925-4080-bfc2-5905c9e0760e)
![1001207958_1700622593659](https://github.com/darktable-org/darktable/assets/151675262/afe752dc-9fa1-4d76-af0a-c0beef98a398)
22602243.jpg…]()
![1001207958_1700622593659](https://github.com/darktable-org/darktable/assets/151675262/afe752dc-9fa1-4d76-af0a-c0beef98a398)

**Comment by gi-man** [comment] 2023-11-22 04:33
One of the images loaded. I do notice a problem (it might be all of your problems). There is microsoft driver that causes issues. Please uninstall the OpenCL Compatibility App. 

Known Windows issues[¶](https://www.darktable.org/about/faq/#faq-windows-issues)
OpenCL will speed up the processing in darktable. Sometimes Windows 11 preinstalls an OpenCL Compatibility app and it causes faults on darktable. Uninstall the OpenCL Compatibility from Windows.

After all of the windows updates, my darktable is still working wihtout issues. But then there was a new update, 23H2. I started that update and will test tomorrow (too late now).

**Comment by Rnies125** [comment] 2023-11-22 05:38
Thank you.  That fixed it.
For the record I first stopped it from running in the background and tried to terminate the app. Unsuccessfully.   I uninstalled and Darktable now opens.
Now I just need to learn how to use it.
Ron

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 21, 2023 at 8:33 PM, ***@***.***> wrote:   


One of the images loaded. I do notice a problem (it might be all of your problems). There is microsoft driver that causes issues. Please uninstall the OpenCL Compatibility App.

Known Windows issues¶
OpenCL will speed up the processing in darktable. Sometimes Windows 11 preinstalls an OpenCL Compatibility app and it causes faults on darktable. Uninstall the OpenCL Compatibility from Windows.

After all of the windows updates, my darktable is still working wihtout issues. But then there was a new update, 23H2. I started that update and will test tomorrow (too late now).

**Comment by kmilos** [comment] 2023-11-22 08:20
Closing as duplicate of https://github.com/darktable-org/darktable/issues/14731 (and many more)

Please search before opening new issues.

**Closed by kmilos** 2023-11-22 08:20 UTC
