### ISSUE TITLE
Ctrl-z after pasting history stack resets the history stack

### ISSUE THREAD

**Issue by moy** [darktable-org/darktable#4883] opened 2020-05-01 12:29 UTC
**Describe the bug**

This is similar to  #3855, but in different conditions.

After pasting a history stack (Control-v) in darkroom, Control-Z doesn't undo, but resets the history stack completely.

**To Reproduce**

1. Go to darkroom and edit an image (A)
2. Go to another image (B) and copy some of the history stack (Control-c)
3. Go to image (A), still in darkroom and paste (Control-v)
4. Try to undo (Control-z)

**Expected behavior**

The just-pasted history stack should be removed. This is what happens in lighttable mode.

**Actual behavior**

Control-z resets the history stack completely. Changes performed in step 1. are discarded too.

Fortunately, Control-y brings back the history stack so initial changes are not lost permanently. However, I did not find any easy way to cancel the Control-v (best I could find is to find the history stack step before pasting and reset the history to this point manually).

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2
 - OS: Ubuntu 20.04
 - OpenCL activated

**Additional context**

 - Can you reproduce with another Darktable version? Was present in 3.0.1 too.
 - Still present using an empty/new config-dir.

**Comment by moy** [comment] 2020-06-06 19:37
Unfortunately, the bug is still there on master.

**Comment by johnny-bit** [comment] 2020-12-21 22:46
Similarly to #3855 - the issue IS present in 3.2.1, however it must've been fixed by @TurboGit some time after that.

Closing since I can't replicate on master(eg 3.5.0+111~g3cca160f9)...

That being said - I haven't tested on 3.4.0 tag nor on 3.4 branch so please comment if you can replicate problem on master or on 3.4 tag/branch!

**Closed by johnny-bit** 2020-12-21 22:46 UTC
Labels: no-issue-activity
