### ISSUE TITLE
Single install of darktable should allow selecting and loading more than one library

### ISSUE THREAD

**Issue by curiousercreative** [darktable-org/darktable#8613] opened 2021-04-05 11:59 UTC
**Is your feature request related to a problem? Please describe.**
Given a user without a DAM and with A LOT OF PHOTOS (100K+), it's often desirable to spread your photos across multiple "libraries". You might have a library per client, you might have a library for your personal photography vs work photography, etc. From my previous workflow, my partner and I have about a half dozen libraries.

**Describe the solution you'd like**
While I haven't fully vetted this, it appears that I can with a single install of darktable select one of many "libraries" (db files) to open in darktable. If this is the case, then we're just missing a user-friendly, GUI oriented method to:
1. Launch darktable, either with a statically defined default library (I believe this is the case currently) OR better would be to load the last selected library.
2. Within darktable, add a menu item to "Open/Switch library" where a file browser would allow a user to select a library.
3. Upon library selection, the GUI should refresh or reload with the newly selected library

I'm sure there are many considerations not captured above, but here's what I'm aware of:
1. "storage backends" - will a single shared location work for multiple libraries?

**Alternative Solution**
I'm trying to use darktable on both macOS and Pop!_OS (Ubuntu). On my Linux desktop, I don't think it'd be terribly difficult to write a GNOME desktop entry file for each persistent library and then I can launch them quite nicely that way and bypass CLI for this task. I don't know how to achieve the equivalent in macOS for my partner though.

**Additional context**
I'm attempting to migrate from Apple Aperture where this is supported. Here's a screenshot of their GUI menu:
![Screen Shot 2021-04-05 at 7 57 32 AM](https://user-images.githubusercontent.com/1696898/113571628-bbc0f800-95e4-11eb-9864-c2aa446cb033.png)

**Comment by curiousercreative** [comment] 2021-04-05 11:59
I'm new to darktable, so if there is an alternative workflow for me to consider, please share!

**Comment by johnny-bit** [comment] 2021-04-05 19:12
you can specify library to use via `--library` option https://www.darktable.org/usermanual/en/special-topics/program-invocation/darktable/

**Comment by curiousercreative** [comment] 2021-04-05 21:08
@johnny-bit yep! This issue is just an enhancement request to wire that to a GUI menu most simply

**Comment by quovadit** [comment] 2021-04-06 17:11
What's the reason why you want to use multiple libraries in darktable?

In lightroom it is recommended not to have too many photos per catalog, so the user is forced to distribute his photos to multiple catalog-files. 
I know lot of photographers who create a new lightroom-catalog every year, so they have no chance to  search for all images tagged with xy in the last 10 years.
I have 100K+ photos in darktable too, and never had problems.

So I see it as an advantage that there is no need for multiple libraries in dt.
If the option would be visible in the gui the user might think he has to use multiple libraries (like in lightroom)

**Comment by curiousercreative** [comment] 2021-04-06 17:43
@quovadit aside from performance considerations that you mention, division of libraries may allow for easier navigation within individual libraries. For example, I may want to collect all images of a certain star rating or of a certain tag. Does DT allows this filter combined with a folder filter?

The list of tags that you apply to your photos may be library specific as well. For a particular client, I may have 1000s of photos and need them tagged by person captured. Imagine you have lots of these types of jobs, your tag list will pollute very fast.

**Comment by AlicVB** [comment] 2021-04-06 18:03
> For example, I may want to collect all images of a certain star rating or of a certain tag. Does DT allow for this filter to be combined with a folder filter? It'd certainly be one less filter if you maintain multiple libraries.

yes you can :) (and even way more complex filters), you may want to have a look at the collect module in the usermanual 



> The list of tags that you apply to your photos may be library specific as well. For a particular client, I may have 1000s of photos and need them tagged by person captured. Imagine you have lots of these types of jobs, your tag list will pollute very fast.

Although, I think this example is more valid, this won't be solved with a new library : in fact dt has 2 library : one for the images and all that belongs to them. And one for all "global" datas, like presets, styles, defined tags, etc... so in that case, you may want to have new data lib too... but you will lost all your presets, etc... and that's not an option :(
But, as I've said, I can see the usecase where you want to have a specific lib for a set of images you don't want to mix with your usual work (a specific client command for example)

**Comment by curiousercreative** [comment] 2021-04-06 18:39
I'm glad

**Comment by bdemaistre** [comment] 2021-04-07 19:53
@quovadit :
> I have 100K+ photos in darktable too, and never had problems.

I have now a little more than 500k photos and many operations that where quite fast with less than 100k photos are now delayed by a few seconds : changing collect filters, going from darkroom to light table, changing keywords. I was thinking the only option will be to split the database so I am surprised to see you had no problem when the database growing large ?

**Comment by AlicVB** [comment] 2021-04-07 20:33
@bdemaistre : 500k ... that's a nice stress test :)

By any chance, do you use master ? There has been some improvements related to database queries recently. iirc, main goal was for startup, selections and import, but that may (or not) improved things elsewhere...

**Comment by curiousercreative** [comment] 2021-04-07 20:59
My builds are from the past couple of weeks off master. Import hangs when attempting to import recursive directory structure with 90K images. Other than that, I haven't noticed anything too slow. Curious to know about @bdemaistre build as well

**Comment by bdemaistre** [comment] 2021-04-08 05:54
@quovadit , @curiousercreative 
Yes I use master. I restarted from an empty database with 3.4 and it was taking more and more time to import and at 200k I was ready to give up. Then I found the discussion about the new import on github, and switched to master and the import is a lot better. Do you think I have a problem in the database and that I need to import again to a clean and empty database ?
I don't want to hijack this discussion, but If there is a limit between 200k and 400k where the performance drop significantly, and if it is not only my specific case, then it is important to allow to split to more than one library. 
Also I am still using the old AfterShot where you have both no limit in library size and multiple library + the ability to open and select a few library together to perform any search.

**Comment by johnny-bit** [comment] 2021-06-13 19:00
While it is a duplicate of #5749 I'll allow this to stay open since this one gained more traction than the older one.

**Comment by bdemaistre** [comment] 2022-06-09 18:13
I think this issue can be closed : 
1/ For the performance aspects on large database there was so much improvement since one year !  A database with 648k photos is fine (takes time when starting but after it is fine)
2/ For the filtering aspect in order to separete nicely by client and by client order : The hierachical keywords is one possibility to manage that, very easily and the filtering is very intuitive in the collections

**Comment by bdemaistre** [comment] 2022-06-09 20:00
I am following the master repository updates, but If I remember correctly it was mostly solved before the 3.8.0 version but also improved since then 


De: "Winston Hoy" ***@***.***> 
À: "darktable-org/darktable" ***@***.***> 
Cc: "Benoit de Maistre" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Jeudi 9 Juin 2022 21:22:22 
Objet: Re: [darktable-org/darktable] Single install of darktable should allow selecting and loading more than one library (#8613) 







For the performance aspects on large database there was so much improvement since one year ! A database with 648k photos is fine (takes time when starting but after it is fine) 
What version did you see improvements in?

**Comment by curiousercreative** [comment] 2022-06-13 15:52
I'm on 3.8.1 and I didn't notice a significant improvement. Regardless and ultimately, even with great performance at X library size, we're closing a feature request because workarounds exist to some of the underlying concerns. In reality, darktable's database is no different from any other application of databases. Sure, you can support multiple unrelated applications on a single database with some sort of namespacing, but why would you? Instead you'd logically divide each application to it's own dedicated database. Similarly, photo libraries (databases) often logically divide at this organizational level where you never want to see them together. Just because it's your preference (or tolerance) to put all of your photos into a single database doesn't mean it's not a worthy feature for consideration. I'd push for this issue to remain open as closing it signals that the project maintainers are uninterested or even opposed to this feature. Not a high priority? Sure, I understand. But someone like myself may be inspired to get this implemented as it's something of a workflow blocker.

**Comment by johnny-bit** [comment] 2022-06-13 19:45
I'm with @curiousercreative on this - the actual workaround is not performance one but using commandline options for choosing library files. As of now in-gui switching would be teeth-pullingly painful to do but as a FR it can live

**Closed** 2024-03-21 00:17 UTC
Labels: feature: redesign, difficulty: hard, scope: UI, scope: DAM, no-issue-activity
