### ISSUE TITLE
Action Nightly PKG broken

### ISSUE THREAD

**Issue by esteelstl** [darktable-org/darktable#8738] opened 2021-04-21 06:13 UTC
The Nightly PKG action is broken (https://github.com/darktable-org/darktable/actions?query=workflow:%22Nightly+PKG%22) and does not produce artifacts.

1. Go to 'https://github.com/darktable-org/darktable/actions?query=workflow:%22Nightly+PKG%22'
2. All recent actions failed (i think at 'Check if it runs'..)

**Comment by Nilvus** [comment] 2021-04-21 18:01
That's not new and this is a duplicate of #6856 but nobody that know that part have time to work on that. See last comment from @johnny-bit. @johnny-bit: do we let this issue open or close it as it seems this will not be solved soon (and it's not an important issue as this pkg build is not an official release)?

**Comment by johnny-bit** [comment] 2021-04-21 18:08
Not really a duplicate of #6856 - that issue was caused by missing libraries.

hmmm.... I wonder if i can...

**Comment by johnny-bit** [comment] 2021-05-18 10:02
Yay. Nightly building works... can close this and focus on different things ;)

**Closed by johnny-bit** 2021-05-18 10:02 UTC
Labels: scope: OS support
