### ISSUE TITLE
rating/rejecting in culling mode (multiple images) is applied to all images on screen

### ISSUE THREAD

**Issue by airflow2010** [darktable-org/darktable#13170] opened 2022-12-19 22:08 UTC
**Introduction**
This bug of darktable has already been described in the comments of [this FR](https://github.com/darktable-org/darktable/issues/7254#issuecomment-1257065991), which is already two years old. The problem has been around a while. As I consider it a bug, I decided to create a bug report for it.

**Describe the bug/issue**
The bug becomes active when the mouse is clearly and definitely over a specific image in culling mode (when multiple images are shown besides each other) and you want to act on it. In this case, it often (not always) happens that all displayed images are affected, instead of just the one where the mouse was over.

**To Reproduce**
1. Switch to culling mode
2. Move mouse over a specific image so it is surrounded by a white rectangle
3. Press a key for rating or rejecting ("1", "2", etc or "r")
4. Sometimes - not always - all images displayed on the screen are effected instead just the one.

I couldn't determine the difference in circumstances whether the problem happens or not. But it happens on a very regular basis - when I am in my normal culling workflow, it happens after 2-3 minutes typically.

**Expected behavior**
Action should only be applied to the image which has been selected by hovering over it.

**Screencast**
Here you have two examples of the same problem. In the [first example](https://youtu.be/KSKJKnIDKG0), I use the zoom-feature. In the [second example](https://youtu.be/rkHYabxZb2I), I don't. But the principle is the same. I used an additional software ("Screenkey") to display the keys I pressed during recording, so you can see exactly what I'm doing. In the comments of the video you see a more detailed explanation with the info of exact moment of problem.

**Platform**
* darktable version : stable 4.0.1
* OS                : Linux
* Linux - Distro    : Ubuntu 22.04
* Memory            : 16GB
* Graphics card     : NVIDIA GeForce GTX 980
* Graphics driver   : nvidia-driver-525

**Additional context**
This has been around for several versions and is a big frustration factor. Slows down the process and forces to change workflow. The problem however is systemic and shows in different corners/situations when using the application.

**Comment by Nilvus** [comment] 2022-12-19 22:14
Sorry but I can't let that opened. This is not a bug (in the sense of not wanted behavior). The issue is not about culling but about how to act on images and the effect on culling mode. It's a consequence of a choice. I do not say I agree with that choice, just that what you want is a FR and not a bug as you want that a choice made change. And I agree with you there. But, we have FR you link to opened and also that quite controversial discussion about how to act on images discussed since a time, that one:  #6025

We can't have multiple issues/FR opened for same thing. That do not help. Follow discussion on FR you link and  #6025 about how to act on images and what need to be changed. Note that there's also proposal to fix that by @Solarer:  #11112 and #10728

**Comment by Solarer** [comment] 2022-12-19 22:24
@Nilvus we believe @airflow2010 found a different bug and asked him to open a new issue.
Please leave this ticket open so that we can investigate ;)
He even provided a video after we asked for it

**Comment by Nilvus** [comment] 2022-12-19 22:35
Ok, if you think it's different, as you know well all that. And seems I missed closing that so all good. I change label.

**Comment by Solarer** [comment] 2022-12-20 07:43
What I can tell from the videos is that you magnify an image using `W` before the issue happens. So you leave culling to full screen mode, return to culling and then the rating or rejection fails.

As I mentioned previously, when you enter culling no image has a white border - you need to move the mouse or arrow keys first. Using `W` is the same as leaving and entering culling. So that is your bug. In your case a white border IS displayed but I think this is a graphical bug and does not represent what is truly active/hovered.

I have not looked into the code but the fix is probably: We need to add some code to check upon entering culling if there is a mouse hover. If yes, mark that image mouse over. If not, mark the first active image mouse over. 

It should also be investigated, why the image still has a white border even though it is not truly hovered. Those are two separate issues.

**Comment by AlicVB** [comment] 2022-12-20 11:26
I think @Solarer is right... @airflow2010 : can you confirm following : 
- do you manage to get this without returning from the full preview mode ?
- when you return from the full preview mode, if you move the mouse before pressing the rating key, do this still happen ?
- last, just to know, do you compile by yourself ? are you able to test git branch ? (this would simplify the test of a fix)

Thanks !

@Nilvus : I confirm this is a bug : in culling, when the mouse hover an image, pressing a rating key apply to the image under the cursor. Issue here is that *sometimes* it applies to all the images in view... this should be fixed, independently of @Solarer work...

**Comment by Solarer** [comment] 2022-12-20 11:27
@airflow2010 @AlicVB  I think I was able to reproduce it on master. Looks like a race condition.

1. Open culling and display a number of images e.g. 4
2. Place the mouse somewhere and move it over an image that you want to rate. Then **quickly** press a button to reject or star rate the image. The white border will flash and all 4 images will get rated. 

This does not happen if you wait a split second before pressing the button. It is a timing issue

**Comment by Nilvus** [comment] 2022-12-20 18:18
Thanks for your work and following that so guys. And sorry for my mistake, especially to you @airflow2010. Link to your discussion was missing and we have had quite few duplicate issues related how to act on images. Clear now that this is different.

**Comment by airflow2010** [comment] 2022-12-20 21:53
> I think @Solarer is right... @airflow2010 : can you confirm following :
> 
> * do you manage to get this without returning from the full preview mode ?

I am not sure. But I will check if it happens without coming from full preview mode as well. I will just continue my normal workflow and record the activity in the process. If it should happen in the other constellation, I can show it to you.

Sorry for not mentioning the use of "full preview mode" - I really wasn't condering it at all, because I thought there was no connection to culling mode.

> * when you return from the full preview mode, if you move the mouse before pressing the rating key, do this still happen ?

Yes, I am sure moving the mouse will not prevent the problem. Also, refering to @Solarer's assumption that it doesn't happen when you wait for more than a split-second after exiting the full preview mode - that's not case. In my second screencast I provided, you see several seconds of mouse moving over time image until i finally reject the image - and still the problem happens. But it still might be a timing issue, I had the same idea.

> * last, just to know, do you compile by yourself ? are you able to test git branch ? (this would simplify the test of a fix)

No I don't compile myself. I use the precompiled packages provided via OBS as noted on darktable's homepage. Would the "snapshot from the master branch" via OBS provide the necessary binaries for testing? If not and compilation is inevitable for testing an eventual fix, I will certainly be willing to look into it. As @Nilvus put it in another thread, this is a project based on the work of volunteers. I respect that, and if this effort helps in the process that's the least I can do.

**Comment by AlicVB** [comment] 2022-12-27 20:14
Ok I have done some tests, and I manage to reproduce that each time if I continuously move the pointer in the thumbnail while pressing shortcut...

So here is my step by step : 
- go to culling view with multiple images
- ensure no rating filter is applied (easier to see changes)
- hover one of the image
- move the mouse continuously inside the thumbnail
- press 'r'
- => see that all the visible image are rejected/unrejected

@dterrahe : May I ask you some help ? I have the feeling that we face the same bug we have fixed some time ago, where shortcuts were removing the image_hover by putting the focus on the module instead, but this time it's with shortcut + mouse move...
for information, in this case, src/dtgtk/culling.c:579 _event_leave_notify is called, which means that for some reason culling lost the focus...

I'm not sure how I can help you, but just ask if you need something !
thanks in advance

**Comment by AxelG-DE** [comment] 2022-12-31 11:41
Hi,

I also noticed that behaviour recently, but didn't happen always, hence I kept silent up to now.

Was that an issue of mine in the past? I remember such topic...

**Comment by AxelG-DE** [comment] 2022-12-31 11:48
A very old issue with similar story was #2558

**Comment by dterrahe** [comment] 2022-12-31 19:09
> src/dtgtk/culling.c:579 _event_leave_notify is called

This is because for extended shortcuts (key+mouse event) a grab is held for the duration of a shortcut move. In `_event_leave_notify` try changing
`  if(event->detail == GDK_NOTIFY_INFERIOR || event->mode == GDK_CROSSING_GTK_GRAB) return FALSE;`
to
`  if(event->detail == GDK_NOTIFY_INFERIOR || event->mode == GDK_CROSSING_GTK_GRAB || event->mode == GDK_CROSSING_GRAB) return FALSE;`

**Comment by AlicVB** [comment] 2023-01-02 21:04
thanks a lot @dterrahe for the tip !

A PR to fix this : #13260 

Note that same issue also exist in thumbtable. See PR description for a step by step...

**Comment by AxelG-DE** [comment] 2023-01-03 06:16
Thumbtable?...

**Closed** 2023-01-03 18:59 UTC
Labels: reproduce: random, scope: UI, bug: pending
