### ISSUE TITLE
Collections>folder empty if Network folders

### ISSUE THREAD

**Issue by flop25** [darktable-org/darktable#15340] opened 2023-09-27 13:59 UTC
### Describe the bug

Hello,

I searched first but found no similar issue or hint so here is my post

The Film rolls are displayed properly but Collections>folder remains empty. In the film rolls the folder is properly displayed in the tool tip
The Search field in Collections>folder is working

That's quite problematic since I can't move/rename folder within Darktable and Darktable is quite poor at synch'ing

### Steps to reproduce

Imported photos from a local NAS ( \\\NASNAME\path\etc...)
Successfully Imported and edited them in Darktable 

### Expected behavior

display the folders?

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

win11

### Are you using OpenCL GPU in darktable?

None

**Comment by gi-man** [comment] 2023-09-27 23:04
I think you should try to post a screenshot of the collection module and collection filters modiule. I'm not clear what the issue is from the description.

**Comment by flop25** [comment] 2023-09-27 23:17
Sure
here it goes:
at launch every Modules reinitialized, and then displaying Collections>folder. If I use %2023% in the search field of Collections>folder it does filter properly but nothing is displayed again in the folder list
![2023-09-28_01-13-02](https://github.com/darktable-org/darktable/assets/736909/45e6682b-3f81-462b-8bf1-a336ac226770)
![2023-09-28_01-11-14](https://github.com/darktable-org/darktable/assets/736909/f372f556-5317-48d3-842d-354c3b6abc26)

**Comment by gi-man** [comment] 2023-09-28 12:31
I'm not sure what's going on.

**Comment by flop25** [comment] 2023-09-28 12:36
You need more info/don't understand, or you are clueless about the cause(s)? ^^

**Comment by wpferguson** [comment] 2023-09-28 15:37
> You need more info/don't understand, or you are clueless about the cause(s)? ^^

Yes

I can't figure out from your description what problem you are having.  Perhaps you need to describe your system in more detail so that the problem description makes sense.  You say something about network folders.  How are they configured, what is there, how are they mounted, ?????"

Your screenshots don't appear to support your description or I don't understand what it is.  I understand that you don't want to share more information than you need to, but obscuring the filmroll (?)(Sorry, I don't speak French) doesn't give me enough information to figure out what you are trying to show me.

In order to fix a problem, we have to be able to understand it.  We can do that if we can reproduce it, then pick it apart until we know what is happening and causing the error you are seeing.  Then we can fix it.

**Comment by flop25** [comment] 2023-09-28 16:12
they have this
![image](https://github.com/darktable-org/darktable/assets/736909/c8edd821-0043-4918-a677-518de4743149)
I have this
![image](https://github.com/darktable-org/darktable/assets/736909/cd938dc3-028b-4718-a722-1d7282de552a)
Why

can't be clearer

**Comment by Nilvus** [comment] 2023-09-28 16:57
> sure. Thanks for helping. Just give me a clear feedback too, no need to lecture me. There is no need for you to know the full name of my folders; you should probably respect better privacy.

Keep cool, it's not about privacy or something else. it's just about path folder. Sometimes, specific path folders (or some characters) could cause issue that we can't reproduce without knowing that. The more precise infos we have, the more we could understand your issue and how to reproduce that. So the less we have, harder it is!

Here, we all have folders displayed so hard to understand why you don't have it with your infos. It could be possible that folders are not displayed because of a specific character (or maybe accents...) that cause a bug. But without knowing that (at least your base folder, sets on import tab in main preferences), will be hard to help more. Sometimes issues are caused by a specific and rare cause.
 
What are your settings on collections modules (click on hamburger menu then "préférences")?

**Comment by flop25** [comment] 2023-09-28 18:04
I'm totally cool, I even recognized I may have missed something very obvious to make it works.
There is two things colliding here; the difficulty to understand that a basic feature is not working (I get it, that's very unexpected)  and then finding the causes
Now Nilvus, thank you, you seem to finally understand what the issue is.
I have always been totally fine with giving to any of you, any details, but you just need to ask me what are the details you want. I can give you the md5 of each of the 40k pictures I have but I'm quite sure that's not helpful. I've made the effort of filling up the template then re-explaining quickly with screenshot. I'm just excepting a mutual respect with a proper feedback just as you did. You don't understand ? fine ! a re re explained it a third time with others words. No problem. Just acknowledge my efforts with some efforts too. I did dev and support of a popular script too for quite some times, so I know that's tedious.

So ! The paths of all files are the same for now:
 \\\NASNAME\several foldernames A-Za-z no space no special except for a _ sometimes\final folder name which may contain space or some special characters

So I scanned aaaaall the folders for all special characters . here is the most accurate representation I can guive you of the several hundreds of folders:
\\\[A-Z]{12}\[A-Za-z]{6}\[A-Za-z]{6}\[A-Za-z]{6}\[A-Za-z_]{6}\[0-9A-Za-z _\-°àâéêèëìïîôùû&]+

only one with a & and one with a °. A few with -. A dozen with accents. More than 50 with just [0-9A-Za-z _]

Oh and I don't have any specific settings since I reinitialized all Modules when doing the screenshots as written in the second post

What I've tried so far with your clue:
Added \\\[A-Z]{12}\[A-Za-z]{6}\aaa.jpeg : that's most upper folder that I can add in darktable
>still nothing in Collections>folder

I have added a LOCAL folder, perfectly named "I:\DONNEES\Images\_Creation" and it worked!
Added more local folders with special characters without issue:
![image](https://github.com/darktable-org/darktable/assets/736909/fd472630-7822-4e3d-8141-83f6d1d35e8a)

so that seems pretty clear that the determining factor here is the network path
I don't get why it would a windows thing with permissions etc since paths are displayed on thumbnails, the search field works and I can edit and export the pics. So it seems more like a parsing issue of the paths specific for the Collection Module

**Comment by Nilvus** [comment] 2023-09-28 20:04
I remember some issues about Windows Network paths. I can find that pull request merged 2 years ago about that (see the "initial" word on its title): #9774
Except a little PR after that one with small fixes, seems that there were no more updates. So maybe Windows Network paths is not complete on darktable. I don't know. I ping @Mark-64 as he works on that part.

**Comment by flop25** [comment] 2023-09-28 21:23
Thanks
I saw those discussions and others too, so I really thought everything was ok now, hence my report

**Comment by gi-man** [comment] 2023-09-28 23:42
What type of NAS system do you have? What's the communication protocol in windows? Are you mounting the NAS as a mapped network drive?

**Comment by flop25** [comment] 2023-09-28 23:53
That's a Western Digital NAS, Linux based. I don't do much except using their interface.
since I'm using the absolute path with \\\ it's not mapped.

**Comment by flop25** [comment] 2023-09-29 12:54
update: after digging in the options, its written : SMB2 + SMB3, NTLMv2, no active directory, no LLTD, no share aggregation, no NFS,
Anything interesting in that? Any specific settings to look after?

But again everything is fine with the read of the folder names and the access. Is it some kind of folder discover feature which is broken?

**Comment by flop25** [comment] 2023-09-29 13:05
update bis:
Mapping a drive letter to the network folder works
you might think that's a solution, but to be honest it's a temporary workaround for waiting a proper solution form Darktable

**Comment by gi-man** [comment] 2023-09-29 14:49
If it works, then it is a solution. :-)

I dont know much about how windows manages the NAS paths but I think doing the mapping gives it a "local" path to consistently find the files. Lets see if Mark-64 can chime in.

**Comment by wpferguson** [comment] 2023-09-29 15:28
When darktable wants a list of folders, or to open a file it sends a request to the operating system and the operating system returns the requested item, if it exists.  The operating system only knows about **LOCAL** resources.  I can't ask darktable to open an image on my google drive because the operating system doesn't have an interface to my google drive.  The windows `\\<server on the network>\resource` is not a local resource just as google drive is not a local resource.

If I mount (map to a drive letter) `\\<server on the network>\resource` then it's a local resource and the operating system can access it and make it available to darktable.  

If I'm on Linux or MacOS and I'm trying to access image files on my NAS, I have to mount the folder to the operating system and make it a local resource before I can access it.

**Comment by flop25** [comment] 2023-09-29 15:38
sure there is absolutely no issue into making such updates https://github.com/darktable-org/darktable/pull/9774 then pretending you don't support it
And it's not like everything else is working except that very specific feature

**Comment by wpferguson** [comment] 2023-09-29 15:44
@flop25 are you always rude to the people you're asking for help or am I just special?

**Comment by Nilvus** [comment] 2023-09-29 17:33
> sure there is absolutely no issue into making such updates #9774 then pretending you don't support it And it's not like everything else is working except that very specific feature

Again, keep cool. Really, @wpferguson just explains you simply how it works and you answer by being rude 2 times. We tried to help and you answer like that.

As he explains, you have to allow darktable to access external folders. Mapping is the way to do it so. Given that you find the solution and so it works and given your answer, I just close. Enough!

**Closed by Nilvus** 2023-09-29 17:33 UTC
Labels: understood: incomplete, scope: windows support
