### ISSUE TITLE
Color-picker in negadoctor crash Dt (Segmentation fault (core dumped))

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#8857] opened 2021-05-04 08:12 UTC
In negadoctor, the use of clolor_picker crash Dt

1. Load a scan
2. Click on 'color_picker icon'
3. See error

[darktable_bt_BN5Z20.txt](https://github.com/darktable-org/darktable/files/6419759/darktable_bt_BN5Z20.txt)
[terminal04052021.txt](https://github.com/darktable-org/darktable/files/6419760/terminal04052021.txt)

    darktable version : 3.5.0~git2052.5a55c65115-1 (Suze)
    OS : Linux - kernel 5.3.0-64 lowlatency
    Linux - Distro : Ubuntu studio 19.10
    Memory : 32Gb
    Graphics card : 2x Nvidia Geforce
    Graphics driver : 440.100
    OpenCL installed : yes
    OpenCL activated : yes
    Xorg : 1.20.5
    Desktop : xfce
    GTK+ : 2.24.32-Ubuntu1 + 3.24.12-1Ubuntu1
    gcc : 8.4.0-1Ubuntu1-19.10 + 9.2.1-9Ubuntu2
    cflags : -g -02
    CMAKE_BUILD_TYPE : none

    Can you reproduce with another darktable version(s)? no (Dt 3.4.1)
    Can you reproduce with a RAW or Jpeg or both? Dng, tif, jpg
    Are the steps above reproducible with a fresh edit (i.e. after discarding history)? yes
    Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes

**Comment by aurelienpierre** [comment] 2021-05-30 21:14
I don't reproduce. Do other color pickers behave the same ? Can you try with more modern GCC (at least 9, if possible 10) ?

**Comment by johnny-bit** [comment] 2021-06-19 11:08
I've checked, the error is:
```
[dt_unreachable_codepath] {unreachable} /usr/src/packages/BUILD/src/common/color_picker.c:608 (dt_color_picker_helper) - we should not be here. please report this to the developers.
```

which is pretty much here:

https://github.com/darktable-org/darktable/blob/4f5ece1ae43fb3d449105c6c7dd9ddb9bad398cf/src/common/color_picker.c#L591-L611

So it's CLEARLY file dependent problem.

@dim162 - can you send a sample file that produces this error?

also - can you try con current master? recently Hanno fixed monochrome picked handling in #9179 so maybe it fixed your problem? :)

**Comment by johnny-bit** [comment] 2021-07-20 07:01
@dim162 Please send at least one sample file for investigation since we can't reproduce and it looks like file-dependent problem.

**Comment by dim162** [comment] 2021-07-20 08:54
I had to move out to the new house & photo studio, also I sold all the
computers. We've got now power & internet, i gonna build a basic computer
to search the pictures. Give me some days!

Le mar. 20 juil. 2021 à 09:01, Hubert Kowalski ***@***.***> a
écrit :

**Comment by johnny-bit** [comment] 2021-07-20 11:47
OK. Wishing you well with setting up new house, studio and computer :)

**Comment by dim162** [comment] 2021-07-30 10:12
I set up a computer to work with Darktable. Since 3 months i was out of the
web, there are a lot of changes. Dt 3.6 is impressive & the problem, I
reported, has disappeared. I kept the images which were problematic &
everything is fine.

Le mar. 20 juil. 2021 à 13:47, Hubert Kowalski ***@***.***> a
écrit :

**Comment by johnny-bit** [comment] 2021-07-30 11:00
Great! So seems like the problem got fixed in the mean time :)

Hope new house, studio & PC will be good for you :)

I assume I can close this now. If not - plz comment.

**Closed by johnny-bit** 2021-07-30 11:00 UTC
Labels: bug: pending, scope: UI, scope: image processing
