### ISSUE TITLE
Darktable Tethering to Nikon D800 in v3.4.1.1

### ISSUE THREAD

**Issue by HixPix2021** [darktable-org/darktable#8370] opened 2021-03-01 11:05 UTC
**Describe the bug**
Darktable Tethering v3.4.1.1: Nikon D800 is found by the application, but returns only Skull images to folder.

**To Reproduce**
1. Connect camera to HP Pavilion Laptop
2. Create new session
3. Check and adjust settings - all control actions appear to function as expected.
4. Capture image
5. Wait for image to return to DT
6. ‘Skull’ image (.NEF File) appears in DT workspace, correctly named and also to Windows 10 folder \Pictures\Darktable$(YEAR). BUT not a viewable image. 

**Expected behavior**
As per reproduction text but with a viewable .NEF image in both DT and the Windows folder.

**Screenshots**
 

**Platform**
 - Darktable Version: v3.4.1.1
 - OS: Windows 10
 - OpenCL activated or no? Don’t know
 - Graphic Card: Intel HD Graphics 610 Driver Version: 25.20.100.6617 

**Additional context**

- Using Windows generic USB Driver, I didn't make any changes i.e. Zadig alternative as all camera remote controls operating as expected.

 - Can you reproduce with another Darktable version? [DH] Have never been able to execute DT Tethering. This is the closest I’ve managed over the years. 
 - 
 - Are the steps above reproduce with a fresh edit (removing history)?  - [DH]Yes
 - 
- Did you compile Darktable yourself? If so which compiler was used, with what options? – [DH] Installable version.

**Comment by HixPix2021** [comment] 2021-03-01 11:12
EXIF Data

File information:
  Local path: C:\Users\hicks\Pictures\Darktable$(YEAR)0227_Test #1\20210227_0001.nef
  File name:  20210227_0001.nef
  File size:  40,449,317 Byte

Start of image (SOI) not recognized.
The picture file is not readable.

**Comment by Nilvus** [comment] 2021-03-01 18:55
Thanks for reporting but duplicate of #8318. It's not same camera but same issue and with Windows. So closing this one.

**Closed by Nilvus** 2021-03-01 18:55 UTC
