### ISSUE TITLE
Purple color instead of white/gray after importing Olympus E-PL1 photos

### ISSUE THREAD

**Issue by FeralChild64** [darktable-org/darktable#15386] opened 2023-10-08 13:47 UTC
### Describe the bug

I'm using an Olympus E-PL1 as a "low cost trip camera" (I use it rarely - only for active trips when I don't want to risk breaking anything more expensive).
Today I have imported several RAW files and I could notice a very intense purple tint in areas which should be white or grayish - see the screenshot:

![Darktable-4 4 2](https://github.com/darktable-org/darktable/assets/48332137/4096c02e-fe04-440b-823c-2529ce240942)

This is just an example - most of my photos suffers from the same problem. I have already used old versions of Darktable with this camera before, and there were no problems till now.

### Steps to reproduce

1. Import photos from Olympus E-PL1
2. Go to _darkroom_, check the photos

### Where did you install darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo, AMD64

### Are you using OpenCL GPU in darktable?

No

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Attached:
- RAW file
- JPG from camera
- Darktable screenshot

[Opympus-problem.tar.gz](https://github.com/darktable-org/darktable/files/12840802/Opympus-problem.tar.gz)

**Comment by pehar1** [comment] 2023-10-08 14:06
Not a bug. You overexposed the sky/cloudes which leads to clipping. Use an apropriate highlight reconstruction method.

**Comment by FeralChild64** [comment] 2023-10-08 14:30
Why the overexposed areas are now pink and not white anymore? This does not make sense to me.

**Comment by paolodepetrillo** [comment] 2023-10-08 14:40
There are two different issues here - the magenta areas are overexposed but the purplish gray areas are not.

There is a [known issue with Olympus white level](https://github.com/darktable-org/rawspeed/issues/392) that causes it to be set incorrectly, so that it doesn't detect the overexposed areas and highlight reconstruction doesn't work on them. Changing the white point to 4000 in the raw black/white point module would fix that.

I'm not sure what is happening with the purplish color, it might be related to the way darktable tries to read and apply the camera's as shot white balance from the file?

**Comment by victoryforce** [comment] 2023-10-08 15:03
> Why the overexposed areas are now pink and not white anymore? This does not make sense to me.

This makes sense because this is what the overexposed areas actually look like before we apply some algorithms to them to get rid of the effect. Read [this section](https://docs.darktable.org/usermanual/development/en/module-reference/processing-modules/highlight-reconstruction/#clipping) on the documentation site.

**Comment by jenshannoschwalm** [comment] 2023-10-08 16:53
Indeed a duplicate of the mentioned issue.

**Comment by Nilvus** [comment] 2023-10-09 17:47
So better to close and if needed continue discussion on #392 issue.

**Closed by Nilvus** 2023-10-09 17:47 UTC
Labels: duplicate, bug: upstream
