### ISSUE TITLE
In lighttable star ratings on file manager bar do not act the same as the color ratings 

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#5044] opened 2020-05-14 16:17 UTC
openSUSE Tumbleweed 20200511
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable-3.1.0~git1589.5c657aea2
OpenCL on 
i7 12-core 36GB

On the lighttable view the star ratings on the file manager men bar do not behave the same color ratings.  The color ratings act as individual toggles, the star ratings only set the particular number of stars.  The single star rating should also act as a toggle the same as it does on the thumbnail displayed.

**Comment by Nilvus** [comment] 2020-05-14 16:40
Your issue is not clear. On what I understand, color labels and stars work the same way on the bottom left bar in lighttable view and it's normal. They're only to set images by another way but they're not here to show selected images. Imagine if you select few images with different stars or colors, which one shown on bottom bar? And no, stars should not act a single star rating, except (as it is) the first one, as stars is a number/order set (you can't have two stars without the first AND the second, etc.). It's different than color labels that could be set independently to an order or another color.

**Comment by ptilopteri** [comment] 2020-05-14 16:48
mouse clicking on a color rates selected image(s) that color, another click on the same color removes that color rating from selected image(s).

mouse clicking on a single star, rates selected image(s) a single star, another clock on the single star does nothing.  Contrary to clicking on the thumbnail star twice, which applies and then removes the rating.

I understand the difference with multiple stars, problem is *only* with a single star (rating).

clear a smud? :^)

**Comment by ptilopteri** [comment] 2020-05-14 16:49
/s/a smud/as mud

**Comment by AlicVB** [comment] 2020-05-14 16:56
That intended.
The problem is in fact that with bottom bar you act always on a set of images that can be rated with different values, contrary to the click on stars in thumbnails which affect just one image.
So the toggle can't apply here, apart from doing some clever things, which in fine may not be what the user expect at all !

**Comment by ptilopteri** [comment] 2020-05-14 17:13
I understand acting on a selected group as I wrote previously.  What I do not understand is different actions for the single star.  I feel the same if the keyboard shortcuts for applying star/color ratings worked differently.

I believe the present action is incorrect and unexpected and not consistent with least surprise.   I expected the selected images to have the single star rating removed.

**Comment by AlicVB** [comment] 2020-05-14 18:11
So not sure we understand each other then...
In fact, the only action which is different from the other is the toggle one, when you click directly on stars inside thumbnails. This action is performed only for this thumbnails, regardless of selection.

Now, if I understand well, you want this action (toggle) to work for stars click on the toolbar (bottom) as well as for shortcuts. Right ?

The problem then is that it's applied on several images with possibly different rating. Of course we can always "force" the things like we do for colorlabels.
Note that if we go this way, we need to do that for reject too, as it can act as a toggle, like the 1 star

So let's see what the other devs think about that... @TurboGit ?

**Comment by ptilopteri** [comment] 2020-05-14 18:17
> So not sure we understand each other then...
> In fact, the only action which is different from the other is the toggle one, when you click directly on stars inside thumbnails. This action is performed only for this thumbnails, regardless of selection.
> 
> Now, if I understand well, you want this action (toggle) to work for stars click on the toolbar (bottom) as well as for shortcuts. Right ?

Clicking on the *first* single star should only toggle the single star rating for any images selected.  The same as clicking on the two star rating will apply two stars to all selected images.
Clicking on the red dot will apply or remove the red dot to all selected images.  Or the blue or ...

> The problem then is that it's applied on several images with possibly different rating. Of course we can always "force" the things like we do for colorlabels.
> Note that if we go this way, we need to do that for reject too, as it can act as a toggle, like the 1 star

Definitely.  I expect the reject "x" to be a toggle.

> 
> So let's see what the other devs think about that... @TurboGit ?

**Comment by ralfbrown** [comment] 2021-06-19 07:06
On current 3.5.0 master, "r" for reject is indeed a toggle for all selected images, but like the stars, clicking on an image only affects the image clicked on.
See also #5151, which is a near duplicate.

**Comment by johnny-bit** [comment] 2021-06-19 10:08
since I had some time today and I wanted to test...

currently (ie 3.5.0+2575 which is couple days old) the stars in the bottom bar work correctly and single star toggle works the same on the toolbar as on the image so range select with various ratings and then clicking on 1 star sets all the ratings to 1 star and then clicking star again zeroes out rating. (unless the setting for not zeroing out is used)

I do wonder about maaaaybe adding reject button to bottom toolbar, but that is imo completely separate issue (or rather: FR)...

I would consider this issue then to be fixed, so closing it now :)

If I'm wrong please commend and I'll reopen to further discuss :)

**Closed by johnny-bit** 2021-06-19 10:08 UTC
Labels: feature: enhancement, no-issue-activity, scope: UI
