### ISSUE TITLE
Tiffen Q-13 Color Separation in ColorCalibrationModule?

### ISSUE THREAD

**Issue by bilddateien** [darktable-org/darktable#9295] opened 2021-06-20 14:14 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem - just a possible extension of a (new in dt 3.6) feature

**Describe the solution you'd like**
Are there any thoughts to add Tiffen Q-13 Color Separation Guide (ex Kodak 1527654) to the list of color checkers in the Color Calibration Module?
see https://www.bhphotovideo.com/c/product/714596-REG/Tiffen_EK1527654T_Q_13_Color_Separation_Guide.html

**Additional context**
I'd like to add some specification here but this is the only info I've available (not of much relevance I think)
[Kodak_Q-13_1527654.pdf](https://github.com/darktable-org/darktable/files/6682483/Kodak_Q-13_1527654.pdf)

**Comment by johnny-bit** [comment] 2021-06-20 16:36
I've been reading about it and I honestly can't say that it even should be included... It has semigloss finish making it harder to capture right, I haven't been able to find reference values for it (but according to what I could find it seems that pigments used are stable ~1-2y so the fade's rather quick) I don't know if they have enough patches to be useful at all...

All i could reliably find is that it's used to "visually inspect original with reproduction" which meant printed medium.

I'd leave the decision up to @aurelienpierre but I'm honestly not convinced.

**Comment by aurelienpierre** [comment] 2021-06-20 17:40
Find me the reference values (if possible in CIE Lab 1976 space), and I will include it.

**Comment by aurelienpierre** [comment] 2021-06-20 17:47
Although the matrix solve with such a low number of ill-distributed patches will probably be wonky.

**Comment by johnny-bit** [comment] 2021-06-20 18:08
All I could find with anything close to "reference":
https://deltae.picturae.com/wiki?title=Kodak_Color_Separation_Guide
https://deltae.picturae.com/wiki?title=Kodak_Gray_Scale

I think it's "not recommended" to use it in modern time, but what do i know ;)

**Comment by bilddateien** [comment] 2021-06-20 20:44
OK, to summarize:
- too few patches
- no good distribution in color space
- probably not very stable over time
- exact reference values not known (only approximates in above documents)

So it looks to me: not likely.
And that's why I asked 
> Are there any thoughts ...
and not: 
> Please add ...

I also had doubts because of the missing alignment marks.

**Comment by johnny-bit** [comment] 2021-06-20 20:53
OK then if you don't mind I'll close this one.

The Q-13 seems to be obsolete by today's standards or not really useful for digital photography purposes...

i found couple different newer ones, but i haven't dug deep into things like qp cards or wdkk charts sold at B&h or adorama

**Closed by johnny-bit** 2021-06-20 20:53 UTC
