### ISSUE TITLE
When i apply some watermarks, the preview image is darker and grayer, export is ok.

### ISSUE THREAD

**Issue by heikkiwaan** [darktable-org/darktable#9134] opened 2021-06-02 13:03 UTC
Hello.
I have 2 watermarks on a photo, i copy the watermarks from the history stack to another photo and i see that the preview image is getting darker and grayer.
When i export it, there is no change, works perfect. Just the preview image is dark and gray

---------------------------------------------------------------

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_

1. What i did was i had 2 watermarks, one default watermark from Darktable, another was a ,SVG file with text
2. i applied them to an image -> The preview image is darker and grayer now.
3. I did also copy the watermarks from the history stack and pasted only those 2 to another photo. The preview got darker and grayer.
4. i tried exporting images before and after applying the watermarks, and saw that the images are ok (Jpeg)

**Expected behavior**

I expected to see no change in darkness and grayness of the preview image when applying a watermark.

**Screencast**
https://www.youtube.com/watch?v=qTODcTHzVF0

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.5.0+2412~g1c305c71c   (Copiled from the source)
* OS                : Linux 5.8.0-53-generic
* Linux - Distro    : Ubuntu 20.04.2 LTS
* Memory            :  16GB
* Graphics card     : NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)
* Graphics driver   : Nvidia 460.80
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : Gnome
* GTK+              : 
* gcc               : gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
The version that came with Ubuntu, does not have that problem.

 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
yes
 
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
Output image is ok.

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
yes.

**Comment by johnny-bit** [comment] 2021-06-02 17:10
have you processed the files before pasting watermarks onto them?

**Comment by heikkiwaan** [comment] 2021-06-02 19:01
nope, i did not do any modifications, actually i even tried to do "Discard history" but that didn't help anything.

**Comment by AlicVB** [comment] 2021-06-02 19:34
@heikkiwaan : the problem comes certainly from the embedded jpeg : 
When you show untouched images, dt use the jpeg embedded in the raw file (produced by the camera). But when you edit the image, dt use it's own algorithm, which differ from the camera one and doesn't produce exactly same result...

If you want to be sure : check the preferences, and set "use raw instead of embedded jpeg" to "always" + discard the thumbnail cache
Then all your thumb will be processed using dt, and you shouldn't see any difference when pasting watermarks.

**Comment by johnny-bit** [comment] 2021-06-02 20:12
OK, so - applying only watermark to image processes image using "defaults" which do not produce 1:1 ooc jpeg results.

If you ONLY want to add watermark to image: use OOC JPEGs.

if you want to process raws - process raw and then add watermark.

Closing as "works as intended" :)

**Closed by johnny-bit** 2021-06-02 20:12 UTC

**Comment by heikkiwaan** [comment] 2021-06-04 09:42
no it does not work as intended, exporting a raw to jpg with and without watermarks arer ok, but the preview image is changing, but... never mind........ who cares how the preview looks like.

Enviado desde Mailspring (https://getmailspring.com/), la mejor aplicación de correo electrónico gratuita para trabajar
