### ISSUE TITLE
darktable won't open; Magick: caught exception 0xC0000005 Access violation 

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#15686] opened 2023-11-19 07:52 UTC
### Describe the bug

User is unable to open darktable on their Windows 11 system. Darktable log contains the message Magick: caught exception 0xC0000005 Access violation.
https://discuss.pixls.us/t/i-cant-get-darktable-to-work-anymore/40474

Could be related to https://github.com/darktable-org/darktable/issues/14733.

### Steps to reproduce

Try to open darktable.

### Where did you install darktable from?

darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

11

### Are you using OpenCL GPU in darktable?

None

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

This is the only log received so far, not very useful. I'll update this if the OP submits a more detailed log.
[darktable-log.txt](https://github.com/darktable-org/darktable/files/13402912/darktable-log.txt)

_No response_

**Comment by Memphis-Dev** [comment] 2023-11-20 11:57
I have the exact same issue. Previously working installation all of a sudden does not work anymore after the last Windows 11 update. I ran a "-d all" from command line, which should debug and log everything, but it does not add a whole lot:

Steps to reproduce
Try to open darktable.

Expected behavior
Run as previous

Logfile | Screenshot | Screencast
Attached

Commit
No response

Where did you install darktable from?
darktable.org

darktable version
4.4.2

What OS are you using?
Windows

What is the version of your OS?
11

Describe your system?
HP Laptop 15s-eq2xxx


Are you using OpenCL GPU in darktable?
YES

If yes, what is the GPU card and driver?
openclon12amdradeontmgraphics

[darktable-log.txt](https://github.com/darktable-org/darktable/files/13413689/darktable-log.txt)

**Comment by kofa73** [comment] 2023-11-20 14:49
> I have the exact same issue.

Your log does not contain the same _Access violation_ error message; your darktable version in the log is `darktable 4.5.0+1173~ge6ef3aa7e3`.

**Comment by Memphis-Dev** [comment] 2023-11-20 15:13
What are you talking about?

 

From my log:

========================================

version: darktable 4.4.2

start: 2023:11:20 12:44:43

 

*snip*

 

Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...Magick: caught exception 0xC0000005 "Access violation"...

 

 

 

How is that different?

 

 

Von: Kofa ***@***.***> 
Gesendet: Montag, 20. November 2023 15:50
An: darktable-org/darktable ***@***.***>
Cc: Memphis-Dev ***@***.***>; Comment ***@***.***>
Betreff: Re: [darktable-org/darktable] darktable won't open; Magick: caught exception 0xC0000005 Access violation (Issue #15686)

 

I have the exact same issue.

Your log does not contain the same Access violation error message; your darktable version in the log is darktable 4.5.0+1173~ge6ef3aa7e3.

**Comment by kofa73** [comment] 2023-11-20 15:31
It was a mistake on my part, I've deleted my comment immediately, but that did not recall the notification email that was sent to contributors. Sorry about that.

**Comment by Memphis-Dev** [comment] 2023-11-20 15:34
Ah, okay, I am following the thread via email, and it does not say that a comment was deleted.

It is all fine, I was just surprised to see that reply. 😊

Anyway, if there is any switch that I can add to the command line to get more debugging info (I used -d all), please let me know. As well as any other tests that I can run.

 

 

Von: Kofa ***@***.***> 
Gesendet: Montag, 20. November 2023 16:31
An: darktable-org/darktable ***@***.***>
Cc: Memphis-Dev ***@***.***>; Comment ***@***.***>
Betreff: Re: [darktable-org/darktable] darktable won't open; Magick: caught exception 0xC0000005 Access violation (Issue #15686)

 

It was a mistake on my part, I've deleted my comment immediately, but that did not recall the notification email that was sent to contributors. Sorry about that.

**Comment by gi-man** [comment] 2023-11-21 04:28
> If yes, what is the GPU card and driver?
> openclon12amdradeontmgraphics

These are microsoft opencl drivers that will cause you problems. You need to uninstall the OpenCL Compatibility app or disable that device via an edit to dartkablerc file. https://darktable-org.github.io/dtdocs/en/special-topics/mem-performance/#device-specific-opencl-configuration

**Comment by Memphis-Dev** [comment] 2023-11-21 05:37
Ah, thanks. I see now that someone asked about this in August 2023 elsewhere, and they have a very concise description of what is to be done (but is the same as your link). I guess Microsoft updated the driver and broke everything.
https://discuss.pixls.us/t/darktable-crashing-with-opencl-win-11/38929/5

**Comment by kmilos** [comment] 2023-11-22 08:21
Closing as duplicate of https://github.com/darktable-org/darktable/issues/14731 (and many more)

Please search before opening new issues.

**Closed by kmilos** 2023-11-22 08:21 UTC
Labels: scope: windows support
