### ISSUE TITLE
darktable 3.4.0  Windows 10 mouse freezes

### ISSUE THREAD

**Issue by meaningfullyhappy** [darktable-org/darktable#8010] opened 2021-01-27 00:21 UTC
**Describe the bug**

Running darktable 3.4.0 on Windows 10.
Mouse freezes requiring system hard reboot.
Drivers up to date, OS up to date.
Problem did not occur prior to darktable 3.4.0 install and use.
Problem does not occur when darktable not in use.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
 - 
 - 

Edition	Windows 10 Pro
Version	20H2
Installed on	‎11/‎29/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0
Edition	Windows 10 Pro
Version	20H2
Installed on	‎11/‎29/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

**Additional context**

**Comment by parafin** [comment] 2021-01-27 12:19
This is obviously a video driver or OS bug. Not sure what we can do about that. Try disabling OpenCL in preferences to probably avoid this issue.

**Comment by meaningfullyhappy** [comment] 2021-01-27 15:02
>Try disabling OpenCL in preferences to probably avoid this issue
The openCL entries in preferences (under cpu/memory/etc.) are marked "not activated".Could there be something else prompting this problem?
Perhaps the darktable community have heard of this issue--mouse freezing, windows 10, only when darktable is active--earlier and know what in the OS or video/mouse/graphics drivers is causing it.
It is so frustrating that just as I am getting comfortable with darktable I find myself having to hard reboot my system (something I haven't done since say, the early 2000's).  So much so I'm now testing out RawTherapee (which I find is hardly as "friendly" as darktable).
I appreciate any and every help from the darktable community.


    On Wednesday, January 27, 2021, 04:20:02 AM PST, parafin <notifications@github.com> wrote:  
 
 


This is obviously a video driver or OS bug. Not sure what we can do about that. Try disabling OpenCL in preferences to probably avoid this issue.

**Comment by parafin** [comment] 2021-01-27 15:15
This is a bug tracker for darktable, not a support forum. It's especially not a very good place to ask for help with general Windows OS problems since darktable is very short on Windows developers, most use Linux. I suggest to try this forum: https://discuss.pixls.us/c/software/darktable/19, but I won't close this ticket for now in case someone does have some ideas about this.

**Comment by meaningfullyhappy** [comment] 2021-01-27 15:24
Ok, thank you.I shall follow up with pixls.us and if I learn anything there, shall report that back here.


    On Wednesday, January 27, 2021, 07:16:07 AM PST, parafin <notifications@github.com> wrote:  
 
 


This is a bug tracker for darktable, not a support forum. It's especially not a very good place to ask for help with general Windows OS problems since darktable is very short on Windows developers, most use Linux. I suggest to try this forum: https://discuss.pixls.us/c/software/darktable/19, but I won't close this ticket for now in case someone does have some ideas about this.

**Comment by johnny-bit** [comment] 2021-06-20 08:21
I've been browsing win10 issues recently in order to either reproduce or close the issue and this one is interesting - It's actually 100% computer/os fault.

There are many reports of mouse freezing for users on windos 10 with various apps - the more resource hungry the more frequent freezes reported. It might be drivers issue - most frequently graphics or mouse driver related... OR it might be CPU related. Eg on my laptop i had to replace thermal paste & fan because spinning up anything intensive on windows caused hard freeze (while on linux the cpu got throttled to a crawl but still managed to work).

Closing the issue since I am certain that darktable can't do anything about windows freeze (except using less resources, but then it's an intensive algos-containing app). Try clearing up any driver issues, any thermal issues, keep an eye on task manager when darktable "causes" freeze (because omething else might spike at that moment causing freeze) etc :)

**Closed by johnny-bit** 2021-06-20 08:21 UTC
Labels: no-issue-activity
