### ISSUE TITLE
macOS: OpenCL kernel sources missing from darktable 3.8.1 bundle

### ISSUE THREAD

**Issue by chucko58** [darktable-org/darktable#11233] opened 2022-02-27 05:57 UTC
**Did you buy darktable from an application store ?**

Downloaded the .dmg from darktable.org

**Describe the bug/issue**

A machine on which OpenCL was working beautifully under darktable 3.8.0 fails darktable-cltest under 3.8.1. Nothing in the system configuration has changed.

These lines from darktable-cltest output strongly suggest a cause:

    0.130873 [opencl_init] device 1 `AMD Radeon HD - FirePro D500 Compute Engine' supports image sizes of 16384 x 16384
    0.130885 [opencl_init] device 1 `AMD Radeon HD - FirePro D500 Compute Engine' allows GPU memory allocations of up to 768MB
    [opencl_init] device 1: AMD Radeon HD - FirePro D500 Compute Engine 
         CANONICAL_NAME:           amdrade
         GLOBAL_MEM_SIZE:          3072MB
         MAX_WORK_GROUP_SIZE:      256
         MAX_WORK_ITEM_DIMENSIONS: 3
         MAX_WORK_ITEM_SIZES:      [ 256 256 256 ]
         DRIVER_VERSION:           1.2 (Jan 10 2022 21:29:11)
         DEVICE_VERSION:           OpenCL 1.2 
    0.131902 [opencl_init] options for OpenCL compiler: -w -cl-fast-relaxed-math  -DUNKNOWN=1 -I/Applications/darktable.app/Contents/share/darktable/kernels
    0.131958 [opencl_fopen_stat] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/rgb_norms.h'!
    0.131965 [opencl_md5sums] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/rgb_norms.h'!
    0.131992 [opencl_fopen_stat] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/noise_generator.h'!
    0.131996 [opencl_md5sums] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/noise_generator.h'!
    0.132004 [opencl_fopen_stat] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/color_conversion.h'!
    0.132009 [opencl_md5sums] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/color_conversion.h'!
    0.132018 [opencl_fopen_stat] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/colorspaces.cl'!
    0.132023 [opencl_md5sums] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/colorspaces.cl'!
    0.132029 [opencl_fopen_stat] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/colorspace.h'!
    0.132065 [opencl_md5sums] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/colorspace.h'!
    0.132082 [opencl_fopen_stat] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/common.h'!
    0.132087 [opencl_md5sums] could not open file `/Applications/darktable.app/Contents/share/darktable/kernels/common.h'!
    0.132093 [opencl_init] could not open `/Applications/darktable.app/Contents/share/darktable/kernels/programs.conf'!

At first I suspected a file permissions issue, but when I went to look at the directory containing the OpenCL kernel sources, it wasn't there!

    Hematite:darktable chucko$ pwd
    /Applications/darktable.app/Contents/share/darktable
    Hematite:darktable chucko$ ls -al
    total 0
    drwx------  2 chucko  admin   64 Feb 26 21:18 .
    drwx------  4 chucko  admin  128 Feb 26 21:18 ..
    Hematite:darktable chucko$ 

**To Reproduce**
1. Install darktable 3.8.1 on any Mac from the official .dmg installer.
2. Open a command line window and run 'darktable-cltest'. Observe a failure to activate OpenCL, with symptoms as quoted above.
3. Change directory to where the kernel sources should be, and list it.

**Expected behavior**
The OpenCL kernel sources should be part of the installed app, and darktable-cltest should find this particular system suitable for OpenCL use.

**Screenshots**
n/a

**Screencast**
n/a

**Which commit introduced the error**

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.1 as released for macOS
* OS                :  macOS 12.2.1. Also observed on macOS 10.14.6.
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 64GB
* Graphics card     : 2x AMD FirePro D500, 6GB each
* Graphics driver   : Apple
* OpenCL installed  : Yes
* OpenCL activated  : Yes
* Xorg              : n/a
* Desktop           : n/a
* GTK+              : n/a
* gcc               : Apple clang version 13.0.0 (clang-1300.0.29.30)
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? No, the behavior is new in release 3.8.1.
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both** N/A
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no** N/A
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`) N/A
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no** Didn't try, seems unrelated.
 - Do you use lua scripts? No
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by chucko58** [comment] 2022-02-27 06:06
This is the MD5 checksum of the .dmg file from which darktable was installed:

    Hematite:Downloads chucko$ md5sum darktable-3.8.1.dmg 
    a5ce20b6a171e8333a1779af336cc551  darktable-3.8.1.dmg
    Hematite:Downloads chucko$

**Comment by parafin** [comment] 2022-02-27 17:18
Can't reproduce on macOS 10.14. Correct path for OpenCL kernels is /Applications/darktable.app/Contents/Resources/share/darktable/kernels/, not /Applications/darktable.app/Contents/share/darktable/kernels/ (note missing Resources). /Applications/darktable.app/Contents/share shouldn't exist at all, the fact that it does on your system is suspicious. I suggest to re-install the package, first completely removing the existing app.

**Comment by parafin** [comment] 2022-02-27 17:26
Possible cause is that gtkosx_application_get_resource_path() might return different value on newer macOS versions. Which would be an upstream issue of gtk-osx-application. But that should break much more than just OpenCL. Could you show the output of `/Applications/darktable.app/Contents/MacOS/darktable -d dev` command?

**Comment by chucko58** [comment] 2022-02-27 17:28
I did as you suggested, deleted the installed app and reinstalled from the .dmg. The problem has gone away.

The output of 'darktable -d dev':

    Hematite:MacOS chucko$ ./darktable -d dev
    0.001005 application_directory: /Applications/darktable.app/Contents/MacOS
    0.001158 darktable.datadir: /Applications/darktable.app/Contents/Resources/share/darktable
    0.001249 darktable.plugindir: /Applications/darktable.app/Contents/Resources/lib/darktable
    0.001326 darktable.localedir: /Applications/darktable.app/Contents/Resources/share/locale
    0.001424 darktable.configdir: /Users/chucko/.config/darktable
    0.001482 darktable.cachedir: /Users/chucko/.cache/darktable
    0.001553 darktable.sharedir: /Applications/darktable.app/Contents/Resources/share
    0.001654 darktable.tmpdir: /private/var/folders/q2/8z7lh41512nbf25wr368083r0000gn/T
    0.001671 new_xdg_data_dirs: (null)
    
    (process:1391): GLib-GObject-CRITICAL **: 09:26:40.291: g_object_set: assertion 'G_IS_OBJECT (object)' failed
    [dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
    [dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
    [dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
    [dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
    [dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
    [dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
    [dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
    [dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
    [dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
    1.101245 kernel directory: /Applications/darktable.app/Contents/Resources/share/darktable/kernels
    1.114797 kernel directory: /Applications/darktable.app/Contents/Resources/share/darktable/kernels
    
    (darktable:1391): GLib-GObject-WARNING **: 09:26:41.700: invalid cast from 'GtkMenuBar' to 'GtkWindow'
    
    (darktable:1391): Gtk-CRITICAL **: 09:26:41.701: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed

**Comment by chucko58** [comment] 2022-02-27 17:32
That was launched from within the app's directory, I get the same results from my homedir.

**Comment by chucko58** [comment] 2022-02-27 18:18
That was on macOS 12.2.1, will try on the 10.14.6 system a little later.

**Comment by chucko58** [comment] 2022-02-27 22:02
After deleting and reinstalling darktable 3.8.1 from the DMG file, the laptop under 10.14.6 is still failing darktable-cltest with what appears to be an include path error:

[Beryl-darktable-cltest.txt](https://github.com/darktable-org/darktable/files/8149495/Beryl-darktable-cltest.txt)

Output of 'darktable -d dev' on that machine: 
[Beryl-darktable-d-dev.txt](https://github.com/darktable-org/darktable/files/8149499/Beryl-darktable-d-dev.txt)

**Comment by parafin** [comment] 2022-02-27 22:17
That’s expected, you need to re-run darktable (or cltest) several times until it succeeds. It’s a known macOS bug. All-in-all it looks like you had somehow corrupted package, which re-install has fixed. So closing.

**Comment by chucko58** [comment] 2022-02-27 22:18
darktable-cltest fails to compile bloom.cl because it can't find included file common.h.

I have confirmed that common.h exists in /Applications/darktable.app/Contents/Resources/share/darktable/kernels alongside all the OpenCL sources.

**Comment by chucko58** [comment] 2022-02-27 22:18
Can you point me to a description of the known bug?

**Closed by parafin** 2022-02-27 22:17 UTC
Labels: scope: macos support

**Comment by parafin** [comment] 2022-02-27 22:20
#2810
