### ISSUE TITLE
infos area text broken if variables contains invalid markup chars

### ISSUE THREAD

**Issue by Nilvus** [darktable-org/darktable#4981] opened 2020-05-10 19:23 UTC
@AlicVB: on all overlays modes where bottom image infos text area could be shown, this text is no more visible. Broken by commit 6ae2f2c504f0ef98c6ced5c523bf2c3e13fecb07

**Comment by AlicVB** [comment] 2020-05-10 20:45
hmm... I can't reproduce with current master.
Just to be sure : you don't see the text at the bottom with all mode that should show it : permanent extended, hover extended, mixed, block. I'm right ?
Have you something special in the pattern ?

**Comment by Nilvus** [comment] 2020-05-10 21:54
Yes, it's exactly that. And i don't have something special in pattern. With same CSS and previous commit, I have the text. When using your commit and after, no more text.

**Comment by Nilvus** [comment] 2020-05-10 22:26
I've made some tests and find the issue: a quite tricky one. I had made the mistake to add a & in a folder name (just one) and so on file name. And that's the one I was using when seeing the issue. I moved to some other folders and image infos are there. On the folder with the & in the name, when removing $(FILE_NAME) tag, text is back. I've tested again without your last commit and text was ok, even with the &.

**Comment by Nilvus** [comment] 2020-05-11 07:02
Just an add: seems to be because of gtk markup tag that doesn't like the &. I just see this error when launching darktable with the Terminal:

(darktable:132149): Gtk-WARNING **: 08:44:00.596: Failed to set text '2020-03-15-Bièvre & alentours-0005.RW2
1/1300 f/6,3 400mm ISO 200' from markup due to error parsing markup: Erreur à la ligne 1 : Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;

On my side, I will rename folder and images to fix that (it's indeed better to avoid using that character). But as It was working before your commit, if it could be fixed without too much difficulty it would be better. Maybe some other users have made the same.

**Comment by AlicVB** [comment] 2020-05-12 17:47
Well, that's tricky... In fact, we'll need to escape chars for markup on the variable replacement level. We can't do that on the thumbnail level, otherwise it will escape markup formats too...
I'll have a look asap

**Comment by jenshannoschwalm** [comment] 2020-05-13 07:08
Can't we prepare the markup string via `g_markup_escape_text` or `g_markup_printf_escaped` ?

**Comment by AlicVB** [comment] 2020-05-13 10:26
yes we can, but at variable replacement level, otherwise it'll also escape markup tags from the pattern which is not what we want. For example if we have the pattern` <b>$(FILE_NAME)</b>` we don't want to escape `<` or` >` symbols...

**Comment by AlicVB** [comment] 2020-05-13 18:39
@Nilvus : should be fixed in #5027

**Comment by GLLM** [comment] 2020-05-13 20:54
I have the same issue with a & character contain in my description field (IPTC) which I show on my extended overlay with a sticky preview.
Will test once merged ;)

**Closed** 2020-05-14 06:58 UTC
