### ISSUE TITLE
function dt_history_hash_read() takes a full second despite speedy HDD

### ISSUE THREAD

**Issue by calabi-yaui** [darktable-org/darktable#16160] opened 2024-01-21 12:28 UTC
### Describe the bug

After start, first adjustment on an image that causes a change in its histroy lead to DT to report a "slow disk" and the "deactivation of the auto-save feature for the current session". 

After that, each adjustment with a history change causes a freeze for about one second that appears in DTs output as follows:

```
    26,0940 [sql] ./src/common/history.c:1733, function dt_history_hash_read(): prepare "SELECT basic_hash, auto_hash, current_hash FROM main.history_hash WHERE imgid = ?1"
    27,0879 [sql] ./src/common/image.c:2833, function dt_image_write_sidecar_file(): prepare "UPDATE main.images SET write_timestamp = STRFTIME('%s', 'now') WHERE id = ?1"
```

This behavior seems new in DT 4.6 and is still persistent in the current master version 4.7.0~git321.9823ca7c-1+11209.1
It was first spotted on Linux Mint 21.1 but is the same now on 21.3 after the upgrade.

### Steps to reproduce

- start Darktable
- apply an adjustment on an image, e.g. a Fujifilm RAW File
- get a 1s freeze after each adjustment regardless of image

### Expected behavior

it should take considerably less time to write the XMP update

### Logfile | Screenshot | Screencast

    26,0940 [sql] ./src/common/history.c:1733, function dt_history_hash_read(): prepare "SELECT basic_hash, auto_hash, current_hash FROM main.history_hash WHERE imgid = ?1"
    27,0879 [sql] ./src/common/image.c:2833, function dt_image_write_sidecar_file(): prepare "UPDATE main.images SET write_timestamp = STRFTIME('%s', 'now') WHERE id = ?1

### Commit

4.6 release

### Where did you obtain darktable from?

OBS

### darktable version

4.7.0~git321.9823ca7c-1+11209.1

### What OS are you using?

Linux

### What is the version of your OS?

Mint 21.3

### Describe your system?

Images are on a 4TB HDD which tests as having an average write speed of about 95MB/s and 16ms access time as per Linux Mint 21.3 performance test.
Darktable resides on the system M.2 SSD.

32GB system memory and AMD 3800X CPU.

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GTX 1070 with driver 535.129.03

**Comment by calabi-yaui** [comment] 2024-01-21 14:00
Despite fighting this problem for three days, only now I realize that it seems to just happen in folders where background thumbnails are being generated. I guess this slows the HDD down to a level that is causing the aforementioned problems.

**Comment by calabi-yaui** [comment] 2024-01-21 18:05
Nope, just created a folder with three new images only and upon cropping the first, the 1s freeze is back again. 

It worked without the freeze a few hours ago when I added some new images to an existing folder but now the freeze is back again. No clue what the difference is.

**Comment by jenshannoschwalm** [comment] 2024-01-21 19:42
you should at least use '-d sql -d pipe' to see whats happening between reading history and writing xmp.

**Comment by calabi-yaui** [comment] 2024-01-22 03:46
The snipped was recorded using the '-d all' command. The '-d sql -d pipe' command seems to output the same. Here is a snipped while using it:

```
    50,7023 [sql] ./src/common/history.c:1737, function dt_history_hash_read(): prepare "SELECT basic_hash, auto_hash, current_hash FROM main.history_hash WHERE imgid = ?1"
    51,6859 [sql] ./src/common/image.c:2858, function dt_image_write_sidecar_file(): prepare "UPDATE main.images SET write_timestamp = STRFTIME('%s', 'now') WHERE id = ?1"
```

**Comment by jenshannoschwalm** [comment] 2024-01-22 17:53
Ok. The sql log is actually written after execution of the function. So `dt_image_write_sidecar_file()` is taken it's time. That can be of several reasons, slow disk ... Would you share the raw and xmp file?

**Comment by calabi-yaui** [comment] 2024-01-24 04:07
Yes, no problem. But I just tested other RAW files and it looks like the behavior is the same even for my older Canon 1ds III RAW files I have on disk. Here is an example after I used crop forth and back to see the effect of the freeze.
[Canon_1dsIII.zip](https://github.com/darktable-org/darktable/files/14032839/Canon_1dsIII.zip)

**Comment by jenshannoschwalm** [comment] 2024-01-24 06:17
From looking into source it's probably writing the history taking some time. Is your drive local or on a NAS/network? Any chance your disk spins down and has to wake up again? Can you reproduce after switching off the autosave feature?

**Comment by TurboGit** [comment] 2024-01-24 09:56
As hinted by @jenshannoschwalm the issue is probably not in the `dt_history_hash_read()` routine but some work between that. I would run with `-d all` and past there everything happening 10 steps before `dt_history_hash_read()` and up to `dt_image_write_sidecar_file()` call.

**Comment by TurboGit** [comment] 2024-01-24 09:58
And to be clear, looking at the code this slow down cannot be due to `dt_history_hash_read()` expect if there is a huge bug in sqlite3.

**Comment by calabi-yaui** [comment] 2024-01-25 07:47
The biggest issue, it seems, is, that it does not happen all the time. Just opened DT to provide the requested debug output on the same image i used for the debug output 3 days ago (https://github.com/darktable-org/darktable/issues/16160#issuecomment-1903133865) and now it is back to normal behavior, means: 1.2 milliseconds inbetween.

```
    28,1985 [sql] ./src/develop/develop.c:1390, function dt_dev_write_history_ext(): prepare "UPDATE main.images SET history_end = ?1 WHERE id = ?2"
    28,1986 [sql] ./src/common/iop_order.c:762, function dt_ioppr_write_iop_order(): prepare "INSERT OR REPLACE INTO main.module_order VALUES (?1, 0, NULL)"
    28,1987 [sql] ./src/common/iop_order.c:773, function dt_ioppr_write_iop_order(): prepare "UPDATE main.module_order SET version = ?2, iop_list = ?3 WHERE imgid = ?1"
    28,1987 [sql] ./src/common/history.c:1529, function _history_hash_compute_from_db(): prepare "SELECT history_end FROM main.images WHERE id = ?1"
    28,1988 [sql] ./src/common/history.c:1546, function _history_hash_compute_from_db(): prepare "SELECT operation, op_params, blendop_params, enabled, MAX(num) FROM main.history WHERE imgid = ?1 AND num <= ?2 GROUP BY operation, multi_priority ORDER BY num"
    28,1990 [sql] ./src/common/history.c:1583, function _history_hash_compute_from_db(): prepare "SELECT version, iop_list FROM main.module_order WHERE imgid = ?1"
    28,1990 [sql] ./src/common/history.c:1688, function dt_history_hash_write_from_history(): prepare "INSERT INTO main.history_hash (imgid, current_hash) VALUES (?1, ?2) ON CONFLICT (imgid) DO UPDATE SET current_hash=?2"
    28,1991 [sql] ./src/common/database.c:5366, function dt_database_release_transaction(): exec "COMMIT TRANSACTION"
    28,1993 [sql] ./src/common/image.c:401, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
    28,1994 [sql] ./src/common/image.c:546, function dt_image_path_append_version(): prepare "SELECT version FROM main.images WHERE id = ?1"
    28,1994 [sql] ./src/common/image.c:401, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
    28,1995 [sql] ./src/common/image.c:479, function _image_local_copy_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id AND i.id = ?1"
    28,2212 [sql] ./src/common/exif.cc:4577, function _exif_xmp_read_data(): prepare "SELECT filename, flags, raw_parameters,        longitude, latitude, altitude, history_end, datetime_taken FROM main.images WHERE id = ?1"
    28,2213 [sql] ./src/common/iop_order.c:471, function dt_ioppr_get_iop_order_version(): prepare "SELECT version FROM main.module_order WHERE imgid = ?1"
    28,2213 [sql] ./src/common/iop_order.c:889, function dt_ioppr_get_iop_order_list(): prepare "SELECT version, iop_list FROM main.module_order WHERE imgid=?1"
    28,2216 [sql] ./src/common/exif.cc:4338, function set_xmp_timestamps(): prepare "SELECT import_timestamp, change_timestamp, export_timestamp, print_timestamp FROM main.images WHERE id = ?1"
    28,2216 [sql] ./src/common/color_harmony.c:93, function dt_color_harmony_get(): prepare "SELECT type, rotation, width FROM main.harmony_guide WHERE main.harmony_guide.imgid = ?1"
    28,2216 [sql] ./src/common/exif.cc:4521, function dt_set_xmp_dt_metadata(): prepare "SELECT key, value FROM main.meta_data WHERE id = ?1"
    28,2217 [sql] ./src/common/exif.cc:4549, function dt_set_xmp_dt_metadata(): prepare "SELECT color FROM main.color_labels WHERE imgid=?1"
    28,2217 [sql] ./src/common/tags.c:723, function dt_tag_get_attached(): prepare "SELECT DISTINCT I.tagid, T.name, T.flags, T.synonyms, COUNT(DISTINCT I.imgid) AS inb FROM main.tagged_images AS I JOIN data.tags AS T ON T.id = I.tagid WHERE I.imgid IN (125422) AND T.id NOT IN memory.darktable_tags GROUP BY I.tagid  ORDER by T.name"
    28,2218 [sql] ./src/common/tags.c:723, function dt_tag_get_attached(): prepare "SELECT DISTINCT I.tagid, T.name, T.flags, T.synonyms, COUNT(DISTINCT I.imgid) AS inb FROM main.tagged_images AS I JOIN data.tags AS T ON T.id = I.tagid WHERE I.imgid IN (125422) AND T.id NOT IN memory.darktable_tags GROUP BY I.tagid  ORDER by T.name"
    28,2219 [sql] ./src/common/exif.cc:4177, function dt_set_xmp_dt_history(): prepare "SELECT imgid, formid, form, name, version, points, points_count, source, num FROM main.masks_history WHERE imgid = ?1 ORDER BY num"
    28,2220 [sql] ./src/common/exif.cc:4241, function dt_set_xmp_dt_history(): prepare "SELECT module, operation, op_params, enabled, blendop_params,        blendop_version, multi_priority, multi_name, num, multi_name_hand_edited FROM main.history WHERE imgid = ?1 ORDER BY num"
    **28,2317 [sql] ./src/common/history.c:1737, function dt_history_hash_read(): prepare "SELECT basic_hash, auto_hash, current_hash FROM main.history_hash WHERE imgid = ?1"
    28,2329 [sql] ./src/common/image.c:2858, function dt_image_write_sidecar_file(): prepare "UPDATE main.images SET write_timestamp = STRFTIME('%s', 'now') WHERE id = ?1"**
```
I restarted DT and got the freeze again:

```
    23,1995 [sql] ./src/develop/develop.c:1390, function dt_dev_write_history_ext(): prepare "UPDATE main.images SET history_end = ?1 WHERE id = ?2"
    23,1995 [sql] ./src/common/iop_order.c:762, function dt_ioppr_write_iop_order(): prepare "INSERT OR REPLACE INTO main.module_order VALUES (?1, 0, NULL)"
    23,1996 [sql] ./src/common/iop_order.c:773, function dt_ioppr_write_iop_order(): prepare "UPDATE main.module_order SET version = ?2, iop_list = ?3 WHERE imgid = ?1"
    23,1996 [sql] ./src/common/history.c:1529, function _history_hash_compute_from_db(): prepare "SELECT history_end FROM main.images WHERE id = ?1"
    23,1996 [sql] ./src/common/history.c:1546, function _history_hash_compute_from_db(): prepare "SELECT operation, op_params, blendop_params, enabled, MAX(num) FROM main.history WHERE imgid = ?1 AND num <= ?2 GROUP BY operation, multi_priority ORDER BY num"
    23,1997 [sql] ./src/common/history.c:1583, function _history_hash_compute_from_db(): prepare "SELECT version, iop_list FROM main.module_order WHERE imgid = ?1"
    23,1998 [sql] ./src/common/history.c:1688, function dt_history_hash_write_from_history(): prepare "INSERT INTO main.history_hash (imgid, current_hash) VALUES (?1, ?2) ON CONFLICT (imgid) DO UPDATE SET current_hash=?2"
    23,1998 [sql] ./src/common/database.c:5366, function dt_database_release_transaction(): exec "COMMIT TRANSACTION"
    23,2000 [sql] ./src/common/image.c:401, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
    23,2000 [sql] ./src/common/image.c:546, function dt_image_path_append_version(): prepare "SELECT version FROM main.images WHERE id = ?1"
    23,2000 [sql] ./src/common/image.c:401, function dt_image_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id and i.id = ?1"
    23,2001 [sql] ./src/common/image.c:479, function _image_local_copy_full_path(): prepare "SELECT folder || '/' || filename FROM main.images i, main.film_rolls f WHERE i.film_id = f.id AND i.id = ?1"
    23,2082 [sql] ./src/common/exif.cc:4577, function _exif_xmp_read_data(): prepare "SELECT filename, flags, raw_parameters,        longitude, latitude, altitude, history_end, datetime_taken FROM main.images WHERE id = ?1"
    23,2083 [sql] ./src/common/iop_order.c:471, function dt_ioppr_get_iop_order_version(): prepare "SELECT version FROM main.module_order WHERE imgid = ?1"
    23,2083 [sql] ./src/common/iop_order.c:889, function dt_ioppr_get_iop_order_list(): prepare "SELECT version, iop_list FROM main.module_order WHERE imgid=?1"
    23,2084 [sql] ./src/common/exif.cc:4338, function set_xmp_timestamps(): prepare "SELECT import_timestamp, change_timestamp, export_timestamp, print_timestamp FROM main.images WHERE id = ?1"
    23,2084 [sql] ./src/common/color_harmony.c:93, function dt_color_harmony_get(): prepare "SELECT type, rotation, width FROM main.harmony_guide WHERE main.harmony_guide.imgid = ?1"
    23,2085 [sql] ./src/common/exif.cc:4521, function dt_set_xmp_dt_metadata(): prepare "SELECT key, value FROM main.meta_data WHERE id = ?1"
    23,2085 [sql] ./src/common/exif.cc:4549, function dt_set_xmp_dt_metadata(): prepare "SELECT color FROM main.color_labels WHERE imgid=?1"
    23,2085 [sql] ./src/common/tags.c:723, function dt_tag_get_attached(): prepare "SELECT DISTINCT I.tagid, T.name, T.flags, T.synonyms, COUNT(DISTINCT I.imgid) AS inb FROM main.tagged_images AS I JOIN data.tags AS T ON T.id = I.tagid WHERE I.imgid IN (125422) AND T.id NOT IN memory.darktable_tags GROUP BY I.tagid  ORDER by T.name"
    23,2086 [sql] ./src/common/tags.c:723, function dt_tag_get_attached(): prepare "SELECT DISTINCT I.tagid, T.name, T.flags, T.synonyms, COUNT(DISTINCT I.imgid) AS inb FROM main.tagged_images AS I JOIN data.tags AS T ON T.id = I.tagid WHERE I.imgid IN (125422) AND T.id NOT IN memory.darktable_tags GROUP BY I.tagid  ORDER by T.name"
    23,2086 [sql] ./src/common/exif.cc:4177, function dt_set_xmp_dt_history(): prepare "SELECT imgid, formid, form, name, version, points, points_count, source, num FROM main.masks_history WHERE imgid = ?1 ORDER BY num"
    23,2086 [sql] ./src/common/exif.cc:4241, function dt_set_xmp_dt_history(): prepare "SELECT module, operation, op_params, enabled, blendop_params,        blendop_version, multi_priority, multi_name, num, multi_name_hand_edited FROM main.history WHERE imgid = ?1 ORDER BY num"
    23,2144 [sql] ./src/common/history.c:1737, function dt_history_hash_read(): prepare "SELECT basic_hash, auto_hash, current_hash FROM main.history_hash WHERE imgid = ?1"
    24,1999 [sql] ./src/common/image.c:2858, function dt_image_write_sidecar_file(): prepare "UPDATE main.images SET write_timestamp = STRFTIME('%s', 'now') WHERE id = ?1"
```

**Comment by calabi-yaui** [comment] 2024-01-25 07:54
OK, I just saw that the logs contain the Autosave time, and when works (after the upper code snippet of my previous post), it reports 

`28,2331 autosave history took 0,037096sec`

while when there is a freeze, it will output (after the lower code snippet of my previous post)

`24,2000 autosave history took 1,001950sec`

and will stop the autosave feature.

**Comment by jenshannoschwalm** [comment] 2024-01-25 11:54
If writing takes that long it's the disk. In any case we shouldn't continue autosaving as user experience while developing an image will be very bad. So what you observed is exactly the intended behavior.

**Comment by calabi-yaui** [comment] 2024-01-27 09:41
Thanks, that is very welcome. I just tested an edit of a 50MB RAF file on my system SSD and any changes on the modules are kind of instant, no freeze at all. Looks like you are right, the HDD is the bottleneck.

As said, any improvement would be most welcome as my personal experiences of using HDDs in the last ~30 year is that they nearly always kind of pre-annouce their failure, while SSDs are dead from one day into another. While I make regular backups, I don't do them as frequently as I should for time and speed reasons, which is why I would like to keep my images on a HDD, price-size ratio reasons aside.

**Comment by jenshannoschwalm** [comment] 2024-01-27 17:16
So closing for now.

**Closed** 2024-01-27 17:17 UTC
