### ISSUE TITLE
Could not load a DNG image

### ISSUE THREAD

**Issue by SugarSamoyed** [darktable-org/darktable#16009] opened 2024-01-02 19:50 UTC
### Describe the bug

RAW DNG format from an iPhone 14 pro seems to be creating a problem when i try and import it.

### Steps to reproduce

Import a DNG photo

### Expected behavior

load the format properly

### Logfile | Screenshot | Screencast

<img width="713" alt="Screenshot 2024-01-02 at 2 45 55 PM" src="https://github.com/darktable-org/darktable/assets/33992092/13acdc35-237e-45b5-9d78-01ef7ee7bda9">

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Mac

### What is the version of your OS?

MacOS 14 Sonoma

### Describe your system?

Macbook Pro 13 inch 2019

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment] 2024-01-02 21:16
> RAW DNG format from an iPhone 14 pro seems to be creating a problem when i try and import it.

@SugarSamoyed Is it in Apple ProRAW format?

**Comment by SugarSamoyed** [comment] 2024-01-02 22:20
> > RAW DNG format from an iPhone 14 pro seems to be creating a problem when i try and import it.
> 
> @SugarSamoyed Is it in Apple ProRAW format?

@victoryforce No idea. It's shot in RAW that's all I know.

**Comment by victoryforce** [comment] 2024-01-02 22:26
> @victoryforce No idea. It's shot in RAW that's all I know.

You can see this in the settings of the camera app: https://support.apple.com/en-us/HT211965

**Comment by kmilos** [comment] 2024-01-03 08:25
Apple ProRAW DNGs are not currently supported, as the release notes clearly state.

Duplicate of https://github.com/darktable-org/darktable/issues/7578

Please search before opening new issues.

**Closed by kmilos** 2024-01-03 08:25 UTC
Labels: scope: camera support
