### ISSUE TITLE
Fujifilm X-H2

### ISSUE THREAD

**Issue by etrigan63** [darktable-org/darktable#12584] opened 2022-10-04 13:23 UTC
The following files have been uploaded to https://raw.pixls.us:
* Fuji-X-H2-Compressed-Raw.RAF
* Fuji-X-H2-Lossless-Compressed-Raw.RAF
* Fuji-X-H2-Uncompressed-Raw.RAF

**Comment by kmilos** [comment] 2022-10-04 13:57
Duplicate of https://github.com/darktable-org/rawspeed/pull/382, please close.

**Closed** 2022-10-05 18:24 UTC
Labels: scope: camera support
