### ISSUE TITLE
[master] Build fails with "clones for «target_clones» attribute cannot be created"

### ISSUE THREAD

**Issue by kanyck** [darktable-org/darktable#9303] opened 2021-06-21 13:55 UTC
Building darktable-9999 fails.

* darktable version : master branch https://github.com/darktable-org/darktable.git +HEAD:refs/git-r3/HEAD
* OS                : Gentoo Linux - kernel 5.11.0-pf8
 ```
 * CFLAGS='-march=native -O3 -fno-semantic-interposition -flto=3 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed'
 * CXXFLAGS='-march=native -O3 -fno-semantic-interposition -flto=3 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed'
 * FFLAGS='-march=native -O3 -fno-semantic-interposition -flto=3 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed'
 * FCFLAGS='-march=native -O3 -fno-semantic-interposition -flto=3 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed'
 * F77FLAGS='-march=native -O3 -fno-semantic-interposition -flto=3 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed'
 * LDFLAGS='-Wl,-O1 -Wl,--as-needed -march=native -O3 -fno-semantic-interposition -flto=3 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe'
 * MAKEOPTS='-j3 -l3.5'
 * gcc (Gentoo 11.1.0-r1 p2) 11.1.0
 * g++ (Gentoo 11.1.0-r1 p2) 11.1.0
 * GNU ld (Gentoo 2.35.2 p1) 2.35.2
```
Build log:
https://disk.yandex.com/d/n3BtoV8k-XyFTw

**Comment by johnny-bit** [comment] 2021-06-21 14:53
CI does runs against GCC 11, so my guess is there are some problems with flags? Otherwise the CI would yell about 
```
src/common/iop_profile.c:1015:6: ошибка: clones for «target_clones» attribute cannot be created
 1015 | void dt_ioppr_transform_image_colorspace(struct dt_iop_module_t *self, const float *const image_in,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I think with `-march=native` we SHOULD skip `target_clones` since it really makes no sense when generating native builds, as per #7695 and IMO #7695 SHOULD be merged.

@kanyck - can you try building not via ebuild but via cmake and narrow down which flags cause problems?

@aurelienpierre & @n0s0r0g - what do you think?

**Comment by kanyck** [comment] 2021-06-21 15:11
@johnny-bit I think I shall try unset target_clones first as the most obvious reason. If the build still fails, I'll try to find flags causing problems. BTW, if by "flags" you meant CFLAGS I still have full control while using ebuild. If you meant cmake options, so yes, I'll have to build manually.

**Comment by aurelienpierre** [comment] 2021-06-21 19:17
> @aurelienpierre & @n0s0r0g - what do you think?

Dunno. We had to disable the target clones on Ming Win (aka GCC), and Clang doesn't support them, so I'm not sure of anything here.

**Comment by johnny-bit** [comment] 2021-06-21 20:24
Last I checked target_clones for clang was sloooooowly moving along, so clang might bring target clones to osx
on win the problem is in how clones get called - ifuncs do not work on windows. Now who'll find the solution to that faster - gcc or clang peps?

That being said IMO target clones is beneficial only when building binaries - so all the binary distro packages, flatpacks, appimages etc benefit from vectorized functions at the tiiiiny cost of increased compile time and sigle runtime overhead.

For "native" builds there's no point: compiler should generate optimized code for the machine it's being ran on, so even if clones do get created, the downside might be that the clone mechanism will introduce unnecessary overhead. So IMO #7695 is correct approach.

@kanyck - I meant CFLAGS.

**Comment by johnny-bit** [comment] 2021-06-24 21:13
@kanyck - build darktable without `-fno-semantic-interposition` flag - that way it should allow for `target_clones` to work.

once you do that check if you still have #6001 because I don't :)

**Comment by johnny-bit** [comment] 2021-06-25 07:23
Actually - @kanyck can you please file a bug report on GCC bugzilla and link to here?

The reason - `-fno-semantic-interposition` alone is enough to break `target_clones` and I spent more time on it than I should and I've seen NO indication that `target_clones` should not be used in conjuntion with `-fno-semantic-interposition`

**Comment by kanyck** [comment] 2021-06-25 11:17
With 
`CFLAGS="-march=native -O3 -flto=3 -fno-plt -fgraphite-identity -floop-nest-optimize -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -msse3"`
dt builds and seem to work fine. Excuse me for being so slow -- having hard time recovering from covid.
As for gcc bug report -- I'm not so experienced in gcc flags and their relations, so I'm afraid I'm not the right person to communicate with gcc devs, sorry. Yet I'm ready to do any needed testing.

**Comment by johnny-bit** [comment] 2021-08-13 08:32
GCC asks:

```
Can you please attach the problematic pre-processed source file (using -E
option)?
```

That would help GCC folks trace the issue.

**Comment by marxin** [comment] 2021-08-13 08:35
> That would help GCC folks trace the issue.

I've got a test-case now, thanks.

**Comment by johnny-bit** [comment] 2021-08-13 09:34
> I've got a test-case now, thanks.

That's great! Thanks!

**Comment by marxin** [comment] 2021-08-16 11:17
Just for your information, the issue is fixed in `gcc-11` branch now.

**Comment by johnny-bit** [comment] 2021-08-16 11:19
Thank you!!!

**Closed by johnny-bit** 2021-08-16 11:19 UTC
Labels: bug: upstream, scope: codebase, bug: pending, no-issue-activity
