### ISSUE TITLE
feature Import from camera : allow import of a single folder

### ISSUE THREAD

**Issue by Coqorico** [darktable-org/darktable#6363] opened 2020-09-23 18:27 UTC
**Is your feature request related to a problem? Please describe.**

I have a Canon camera which allows the creation of folders on the CF or SD card. When I import from the card in darktable using the import from a camera feature, all the pictures on the card are scanned and displayed in a single list. I have to wait for the scan of the whole card to be finished before I can import any picture.
When there are multiple folders to import, using different job names, this requires the scan of the whole card each time.

**Describe the solution you'd like**

It would be great to:
1 (shall) - Allow selecting and browsing a single folder of the camera or card, then scan only the selected folder to reduce the time required before import is possible.
2 (should) - Allow importing a whole folder without waiting for the card or the selected folder to be scanned. A preview of the content of each folder content could be provided by scanning and showing the first picture only.
3 (nice to have) - Allow importing the whole folder currently browsed in a click (on a dedicated button), without using ctrl-A then import.

**Alternatives**

When importing from a local disk folder, allow to copy / move raw files in a folder created by darktable, same as import from camera.
If this is made possible, the content of the card could be copied in a temporary local folder before it is imported with darktable. This would let darktable create folders and rename files and avoid the use of a third-party software to handle that before pictures are imported in darktable.

**Additional context**

**Comment by Nilvus** [comment] 2020-09-24 19:27
This one could be related to my old FR: #2762

**Comment by Coqorico** [comment] 2020-09-24 19:52
Hello Nilvus,
Indeed, it could be related and packaged together. Our issues are complementary as they relate to the ergonomics and features of the import from camera functionality.

**Comment by parafin** [comment] 2020-09-25 08:57
Just use card-reader or/and some other software (file manager, rapid photo downloader) instead of darktable's import from device functionality. Really, only import from folder should be used in darktable IMHO.

**Comment by Coqorico** [comment] 2020-09-25 09:45
I used import from folder, but it requires to use another tool to import the raw on the hard drive in order to generate the folders and rename the imported files.
I didn't know rapid photo dowldader, I'm having a look and it seems perfect, thanks for the advice! This seems to fulfill my needs.

**Comment by Nilvus** [comment] 2020-09-25 13:17
> Really, only import from folder should be used in darktable IMHO.

Why not use it? Import from SD card works great. We just talk about how to improve it.

**Comment by parafin** [comment] 2020-09-25 14:31
Importing from SD card with "import from device" dt feature is doubly questionable, because SD card should be accessed simply as files instead. There were cases with silent data corruption otherwise. The problem is that for "import from device" gphoto is used, over which we don't have much control. Another problem is that not enough manpower is spent (and I suspect is going to be spent) on this feature, so it's not very well tested and reliable. Same for tethering, but at least tethering is not duplicated functionality.

**Comment by Nilvus** [comment] 2020-09-25 16:51
Good downsides you point @parafin. On the other side, "import from device" allow to quickly import photo by copying them on hard disk AND rename/create folders by setting session options in preferences. And that is powerful and why I like using this feature.

**Comment by parafin** [comment] 2020-09-25 17:03
I understand, but what I'm saying that this functionality can and should be implemented in much more reliable and powerful way to be "mature" let's say. And there is already such solution (from what I hear) - Rapid Photo Downloader. I'm not sure if it makes sense to re-implement it inside dt.

**Comment by Coqorico** [comment] 2020-09-26 04:59
Well, we fall back to some classic issue: one tool to rule them all - but not very well-, or one tool per use - specific and efficient -
Rapid photo downloader appears to be the kind of tool I expected. Even though we can't scan only a folder of the card, it is possible to assign a different job for each picture, so it sorts and/or rename them accordingly.
Thanks for your feedback regarding darktable and this functionality.
I guess "import from device" will remain available as no functionality is removed as darktable evolves, but regarding what you are saying it could be hidden by default with an option to activate it in the preferences, option that could warn the user on its limitations, couldn't it?

**Comment by Nilvus** [comment] 2020-09-26 09:08
I love to have to all on one software and import from device works well from my use. I never had any file corruption with it.
@Coqorico: hidden it by default and warn the user on its limitations is not necessary. It works well as it is, so or this feature is improved to solve those limitations or let it as it is actually. We also need to be careful to not add too many settings in preferences. Overload it would not be a good thing too.

**Comment by TurboGit** [comment] 2020-09-26 09:23
I'm also for a all-in-one solution. Don't like to use ten software possibly with different UI for working on my picture. I'm not saying we should do all kind of fancy stuff but at least importing files from camera to hard drive should be properly supported.

Note that I'm not importing from camera directly but I do import from a card reader using the exact same dt support (as a card reader is seen as a camera) and I have never ever had a file corruption.

I'm just not using a direct camera cable so avoid connecting/unconnecting it from camera where I prefer to keep the connector well closed to avoid raining to enter there. So I always remove the card and connect it to a reader. But again from dt this is exactly the same.

**Comment by parafin** [comment] 2020-09-26 09:49
Using gphoto to import files from card reader is plain stupid, one should just mount it and copy files without involving an additional library, which limits functionality and introduce bugs and various problems. If such feature is desired, then someone should invest time into developing it inside the darktable. As of now there are people for whom the existing gphoto solution works, and others for whom it doesn't, but just because you fall into the first one, doesn't mean there is no problem.

**Comment by Nilvus** [comment] 2020-09-26 11:03
> As of now there are people for whom the existing gphoto solution works, and others for whom it doesn't, but just because you fall into the first one, doesn't mean there is no problem.

And the opposite is also right. Said that, we are agree, actual import from SD card needs to works great for all users. And so, the best would be to have this feature reworked and fully integrated in darktable.

**Comment by Coqorico** [comment] 2020-09-26 12:13
@TurboGit : having a all-in-one solution would be great, that was the motivation for my request. But as a lot of (great) work is in progress to improve raw development I would prefer not to slow down the pace on these core functionalities. As open and really efficient software exist (on GNU/Linux) to manage import from a card or a camera, I have a workaround that I can integrate in my workflow - that will be the first tool I use in addition to darktable.
Regarding the use of CF or SD card with a card reader, as mentioned by @Nilvus and by @TurboGit, that's also my way of working because it is faster than using the camera itself. It also works very well for me, I never had issues until now.
So if some developer would like to work on the "import from device" - and why not on the "import from folder" to allow moving and renaming raw files and folders - that would be great, but it is not for me an important priority. I do prefer improvements on RGB raw workflow :-)

**Comment by TurboGit** [comment] 2020-09-26 17:15
@parafin : I'm not sure what is plain stupid ! When using dt import feature I can:
- add some keywords
- add some metadata
- use a metadata preset
- select only some pictures as I see the thumbs
- specified the collection name
- the pictures are imported in a specific folder that is specified once in preference (and I do backup this folder until the pictures are moved to a safe storage)

So to be it is far better that just copying the files with nautilus or whatever file explorer.

**Comment by TurboGit** [comment] 2020-09-26 17:17
@Coqorico : I understand, and indeed having a full featured import module would be nice and maybe at some point some dev will start such big project. I certainly won't do that as the current import feature is always fitting my need but I certainly welcome any work in this direction.

**Comment by Coqorico** [comment] 2020-09-26 20:21
@TurboGit So let this request open for someone to start working on it. This discussion will for sure bring quite some inputs for the expected results!

**Comment by parafin** [comment] 2020-09-27 07:23
> @parafin : I'm not sure what is plain stupid !

I'm talking about how it's implemented, not its features. There is gphoto library that deals with communicating with various cameras - transferring of photos and tethering. So far so good, it makes total sense. Then there is IMHO an ill-conceived gphoto feature when it calls mounted card reader a camera and allows to transfer data from it. What is stupid here is that dt can read files itself, it can also copy them and do all that stuff, gphoto is not required. Instead we are using a library, which is known to cause various troubles (just search our bug tracker). If you want such import from card functionality a major dt feature, it needs to be re-implemented almost from scratch IMHO. Otherwise you end up dealing with gphoto bugs and limitations.

**Comment by TurboGit** [comment] 2020-09-27 08:30
@parafin : clearer now, and yes I agree with you it would be good to bypass gphoto in this case.

**Comment by phweyland** [comment] 2021-02-23 13:30
As gtk4 will limit the possibilities of file chooser (no preview, no way to interact with selected row without a button) it could make sense to revisit import "image...", without using gphoto if I understand properly.

The way I see it is (based on the different requests I've seen at this subject):
- use file chooser to select the (root ?(1)) folder.
- display the images list (as in camera dialog) with the options:
1. top level 
-- import  in place, as today with "image..." button versus copy / rename, as today "import from camera"
-- if copy / rename enable "jobcode" entry. Folder and file naming would follow the session settings.
-- if copy / rename preview of the destination folder
-- default display thumbnail (display could be skipped to speed up the list update)

2. displayed list
-- checkbox to give the possibility to display the thumbnails one per one
-- filename 
-- (EXIF ?) datetime
-- if copy / rename preview of destination filename
-- thumbnail (without gphoto) if activated

3. bottom
-- cancel / import button (as in camera dialog)

(1) if this works, a unique import button could replace both "image..." and "folder..."

Thoughts ? Advices ?

**Closed** 2021-03-13 18:06 UTC
Labels: difficulty: average, feature: enhancement, no-issue-activity, scope: DAM
