### ISSUE TITLE
Ctrl + Z needs 3 attemps to work

### ISSUE THREAD

**Issue by stephanovitch67** [darktable-org/darktable#3889] opened 2019-12-27 16:26 UTC
DT 3.0.0 Windows 10 1809
- OpenCL activated
 - GTX 1080

To undo a style preset, i need to click CTRL +Z at least 3 times before it work. Same happening in crop and rotate module with the angle slider
. Seems to work fine with the others modules

**Comment by TurboGit** [comment] 2019-12-28 15:39
Cannot reproduce. How to you apply the style ? I have tested from lighttable and darkroom a single Ctrl-Z works. Please describe all the steps to reproduce.

**Comment by stephanovitch67** [comment] 2019-12-29 00:24
Hi Pascal, i tried it two differents ways.
First in lighttable mode, when i apply a style using the style module on the right panel, it take two Ctrl-Z to work and undo
Second in darkroom, when i apply the style using the icon on the bottom left of the window, then it take three Ctrl-z to work and undo.
I tried many times( .tif and .raf files), restart my computer, and it's always the same.
To be honest, it's not a big deal, just annoying.
If i can help more to describe the bug, please let me know.
Thanks and regards 
Stéphane

**Comment by chhil** [comment] 2019-12-29 01:47
I have opened a separate issue some time ago for keyboard shortcuts not working when the right view is not active. Maybe its related.
https://github.com/darktable-org/darktable/issues/3859

**Comment by chhil** [comment] 2020-01-29 02:23
May be related to something that was fixed some time back for history stack undoing but did not make it to preset undoing.

https://github.com/darktable-org/darktable/issues/3204

**Comment by goodsignal** [comment] 2020-02-01 16:22
With the windows build (darktable-3.0.0-win64) keyboard shortcuts 'z' and 'ctrl-z' do not work at all in lighttable mode.

**Comment by johnny-bit** [comment] 2020-12-31 20:56
Cannot reproduce. Most likely fixed by @TurboGit with all the work put into history undo :) I remember me mentioning same exact issue and it being fixed, so closing this.

Obviously - if the issue is still reproducible on latest release and/or current master, please commend and I'll reopen!

**Closed by johnny-bit** 2020-12-31 20:56 UTC
Labels: no-issue-activity
