### ISSUE TITLE
After last Windows 10 update 2020-06-26 KB4561600

### ISSUE THREAD

**Issue by cembra123** [darktable-org/darktable#5644] opened 2020-06-27 08:18 UTC
After update darktable siply dont start. Log below.

this is darktable 3.0.1 reporting an exception:

-------------------

Error occurred on Saturday, June 27, 2020 at 09:30:44.

darktable.exe caused an Access Violation at location 0000000180004E38 in module Wintab32.dll Reading from location 0000000004B710D0.

AddrPC           Params
0000000180004E38 0000000000000000 0000000000000008 0000000000000000  Wintab32.dll!WTOpenW
000000018000503D 0000000000000008 000000000320B0F0 0000000000000064  Wintab32.dll!WTOpenW
000000018000154D 0000000000000000 00007FF9FF03D380 000000000320B0F0  Wintab32.dll!WTOpenA
000000006C1F999F 00000000032C9A30 0000000000000000 0000000000000000  libgdk-3-0.dll!gdk_win32_pixbuf_to_hicon_libgtk_only
0000000067F06C29 0000000000000000 0000000003238C18 0000000067F42208  libgobject-2.0-0.dll!g_closure_invoke
0000000067F19CB9 000000000323C1B0 00000000000000D7 0000000004843510  libgobject-2.0-0.dll!g_signal_handler_disconnect
0000000067F24377 0000000004843510 0000000000000001 00000000000000D7  libgobject-2.0-0.dll!g_signal_emit_valist
0000000067F24B48 0000000000000002 00007FF9FFEA5D21 000000006C23817E  libgobject-2.0-0.dll!g_signal_emit
0000000067F0AB93 000000006C255452 0000000000000200 00000000000BD110  libgobject-2.0-0.dll!g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv
0000000067F0D04C FFFFFFFFFFFF0000 0000000000000000 0000000000000002  libgobject-2.0-0.dll!g_object_notify
000000006C1CDBF8 000000000061F390 0000000000000000 0000000000000000  libgdk-3-0.dll!gdk_display_manager_open_display
0000000067F06E66 0000000000000003 00007FF9FFEB782E 0000000000000001  libgobject-2.0-0.dll!g_closure_invoke
0000000067F24713 0000000004849000 000000006C1FD6FA 0000000000000000  libgobject-2.0-0.dll!g_signal_emit_valist
0000000067F25389 0000000000000000 0000000000000008 000000000061F008  libgobject-2.0-0.dll!g_signal_emit_by_name
000000006C1FE4BD 000000006C23820A 0000000001A50000 000000000323D860  libgdk-3-0.dll!gdk_win32_display_get_type
000000006C1CDA38 0000000000000000 0000000000000000 000000000061F8A0  libgdk-3-0.dll!gdk_display_manager_open_display
0000000067859D61 000000000323D860 000000000061F8A0 0000000000000000  libgtk-3-0.dll!gtk_lock_button_set_permission
000000006785A6B5 00000000638FAC88 000000000324FD90 0000000000000000  libgtk-3-0.dll!gtk_init
00000000635E5F0E 00007FF900000001 000000000323D520 00007FF900000001  libdarktable.dll!dt_init  [D:/build/darktable/src/common/darktable.c @ 793]
0000000000403079 00000000004016A0 0000000000000010 0000000000000000  darktable.exe!main  [D:/build/darktable/src/main.c @ 92]
00000000004015F8 000000000000005A 0000000000000000 0000000000408600  darktable.exe!wmain  [D:/build/darktable/src/win/main_wrapper.h @ 15]
00000000004013EE 0000000000000000 0000000000000000 0000000000000000  darktable.exe!__tmainCRTStartup  [D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 334]
000000000040153B 0000000000000000 0000000000000000 0000000000000000  darktable.exe!mainCRTStartup  [D:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 223]
00007FF9FF036FD4 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FF9FFEDCEC1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

darktable.exe	3.0.1.0
ntdll.dll   	10.0.19041.207
KERNEL32.DLL	10.0.19041.292
KERNELBASE.dll	10.0.19041.292
msvcrt.dll  	7.0.19041.1
libintl-8.dll	0.19.8.0
ADVAPI32.dll	10.0.19041.1
libglib-2.0-0.dll	2.64.0.0
sechost.dll 	10.0.19041.1
libdarktable.dll
ole32.dll   	10.0.19041.153
RPCRT4.dll  	10.0.19041.1
ucrtbase.dll	10.0.19041.1
GDI32.dll   	10.0.19041.1
combase.dll 	10.0.19041.329
win32u.dll  	10.0.19041.329
gdi32full.dll	10.0.19041.329
USER32.dll  	10.0.19041.264
msvcp_win.dll	10.0.19041.1
SHELL32.dll 	10.0.19041.329
libiconv-2.dll	1.16.0.0
PSAPI.DLL   	10.0.19041.1
WS2_32.dll  	10.0.19041.1
libwinpthread-1.dll	1.0.0.0
libstdc++-6.dll
libgcc_s_seh-1.dll
libcairo-2.dll
libcurl-4.dll
CRYPT32.dll 	10.0.19041.21
WLDAP32.dll 	10.0.19041.1
exchndl.dll 	0.9.2.0
libexiv2.dll
libgdk-3-0.dll	3.24.14.0
libgdk_pixbuf-2.0-0.dll	2.40.0.0
IMM32.dll   	10.0.19041.1
SETUPAPI.dll	10.0.19041.1
cfgmgr32.dll	10.0.19041.1
bcrypt.dll  	10.0.19041.1
libgmodule-2.0-0.dll	2.64.0.0
libgobject-2.0-0.dll	2.64.0.0
libgphoto2-6.dll
libgphoto2_port-12.dll
libGraphicsMagick-3.dll
libgtk-3-0.dll	3.24.14.0
libjpeg-8.dll
libjson-glib-1.0-0.dll
libIlmImf-2_4.dll
liblcms2-2.dll
lua53.dll
libpango-1.0-0.dll	1.43.0.0
libpng16-16.dll
libpangocairo-1.0-0.dll	1.43.0.0
libpugixml.dll
libsoup-2.4-1.dll
libtiff-5.dll
libsqlite3-0.dll
libxml2-2.dll
zlib1.dll
libpcre-1.dll
libfontconfig-1.dll
MSIMG32.dll 	10.0.19041.264
libfreetype-6.dll	2.10.1.0
libpixman-1-0.dll
libbrotlidec.dll
mgwhelp.dll 	0.9.2.0
VERSION.dll 	10.0.19041.1
comdlg32.dll	10.0.19041.329
libidn2-0.dll
libnghttp2-14.dll
shcore.dll  	10.0.19041.264
SHLWAPI.dll 	10.0.19041.1
libpsl-5.dll
libssh2-1.dll
libssl-1_1-x64.dll	1.1.1.4
gdiplus.dll 	10.0.19041.329
dwmapi.dll  	10.0.19041.1
libcairo-gobject-2.dll
WINMM.dll   	10.0.19041.1
libepoxy-0.dll
libpangowin32-1.0-0.dll	1.43.0.0
libffi-6.dll
libexif-12.dll
libsystre-0.dll
libbz2-1.dll
libHalf-2_4.dll
libIlmThread-2_4.dll
libthai-0.dll
libpangoft2-1.0-0.dll	1.43.0.0
liblzma-5.dll	5.2.4.0
libzstd.dll
libharfbuzz-0.dll
COMCTL32.dll	6.10.19041.1
dbghelp.dll 	10.0.19041.1
libatk-1.0-0.dll	2.34.1.0
WINSPOOL.DRV	10.0.19041.1
USP10.dll   	10.0.19041.1
libtre-5.dll
libdatrie-1.dll
libgraphite2.dll
dbgcore.DLL 	10.0.19041.1
libgomp-1.dll
libgio-2.0-0.dll	2.64.0.0
libopenjp2-7.dll
librsvg-2-2.dll
libsecret-1-0.dll
libexpat-1.dll
libcrypto-1_1-x64.dll	1.1.1.4
libfribidi-0.dll
libltdl-7.dll
libIex-2_4.dll
libImath-2_4.dll
libbrotlicommon.dll
libunistring-2.dll	0.9.10.0
IPHLPAPI.DLL	10.0.19041.1
DNSAPI.dll  	10.0.19041.1
libgcrypt-20.dll	1.8.5.54720
libcroco-0.6-3.dll
libgpg-error-0.dll	1.37.0.0
CRYPTBASE.DLL	10.0.19041.1
CRYPTSP.dll 	10.0.19041.1
rsaenh.dll  	10.0.19041.1
bcryptPrimitives.dll	10.0.19041.264
NSI.dll     	10.0.19041.1
windows.storage.dll	10.0.19041.329
Wldp.dll    	10.0.19041.1
kernel.appcore.dll	10.0.19041.1
uxtheme.dll 	10.0.19041.1
OLEAUT32.dll	10.0.19041.329
clbcatq.dll 	2001.12.10941.16384
propsys.dll 	7.0.19041.1
profapi.dll 	10.0.19041.1
mswsock.dll 	10.0.19041.1
MSCTF.dll   	10.0.19041.329
DEVOBJ.dll  	10.0.19041.1
WINTRUST.dll	10.0.19041.1
MSASN1.dll  	10.0.19041.1
Wintab32.dll	2.1.2.1
IconCodecService.dll	10.0.19041.1
WindowsCodecs.dll	10.0.19041.207
TextShaping.dll
textinputframework.dll	10.0.19041.1
CoreUIComponents.dll	10.0.19041.1
CoreMessaging.dll	10.0.19041.264
ntmarta.dll 	10.0.19041.1
wintypes.dll	10.0.19041.329
Oleacc.dll  	7.2.19041.1

Windows 10.0.19041
DrMingw 0.9.2

**Comment by coffeeandspaceships** [comment] 2020-06-28 10:41
Can you try this with 3.0.2 please?

WinTab32.dll (implicated in your crash) was not changed by KB4561600. KB4561600 is an update to Adobe Flash support and affects a very specific set of files directly related to Adobe Flash only, so it seems really unlikely this is the cause.

**Comment by johnny-bit** [comment] 2020-12-15 21:56
Since 3.0.1 we've had couple releases and new release coming up shortly... It looks like an isolated incident. Try with newest release and clean config. Should work :) do keep in mind that antivir might messs things up.

Closing for now - if you still have problems, please reply and I'll reopen and we'll investigate the issue.

**Closed by johnny-bit** 2020-12-15 21:56 UTC
Labels: no-issue-activity
