### ISSUE TITLE
Canon EOS R S-RAW

### ISSUE THREAD

**Issue by ShaneMilton** [darktable-org/darktable#4674] opened 2020-04-10 17:59 UTC
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by ShaneMilton** [comment] 2020-04-10 18:04
This is Small RAW non Dual Pixel

**Comment by LebedevRI** [comment] 2020-04-10 18:05
Duplicate of https://github.com/darktable-org/darktable/issues/4673

**Closed by LebedevRI** 2020-04-10 18:05 UTC
Labels: scope: camera support
