### ISSUE TITLE
Script darktable-gen-noiseprofile is not working.

### ISSUE THREAD

**Issue by tomascapek** [darktable-org/darktable#4892] opened 2020-05-01 18:54 UTC
I tried to create noise profile for my Nikon D3s and I failed miserably. 

I used tutorial on server PIXLS.US, I created the shots and I downloaded them to local folder on my computer (Arch Linux, regularly updated). When I reached the last step - creating the profile itself, I was met with "an empty output":

> /usr/lib/darktable/tools/darktable-gen-noiseprofile -d "$(pwd)"
> ===> Check for required tools
> --> Check for images handling tools availability
> --> Check for images export tools availability
> --> Check for profiling tools availability
> --> Check for tethering tools availability
> ERROR: gphoto2 not found
> 
> gphoto2 is needed if you want this script to automatically take the
> required pictures.
> 
> 
> NOTE: Tethering tools are missing; you'll need to provide input images
> yourself.
> --> Check for pdf tools availability
> 
> ===> Check profiling directory
> 
> ===> List profiling input RAW images

Nothing more on the output. Pictures are in the current working directory.

So I started digging and my search lead me [here](https://github.com/darktable-org/darktable/blob/master/tools/noise/darktable-gen-noiseprofile#L400). The function `list_input_images` is from what I see, non-existent. I tried to replace it with my own, but I failed at it with horrible error messages. So I am writing this bug report. Is this a bug or my stupidity?

Also I am willing to provide RAW files of my profiling shots, if someone wants to create the profile for me. It would be much appreciated :)

**Platform:**
 - Darktable Version: 3.0.2
 - OS: Arch Linux
 - OpenCL support enabled
 - NVidia GTX 1060 6GB, NVidia drivers 440.82

**Comment by hatsunearu** [comment] 2020-10-01 04:53
Is this still reproducible on top of tree?

**Comment by johnny-bit** [comment] 2020-12-15 20:40
Several people since have provided couple new noise profiles so it might be one-off error.

@tomascapek - can you try again using current master build (or 3.2.1 ?)

**Comment by johnny-bit** [comment] 2021-06-13 13:34
the mentioned `list_input_images` is in `subr.sh` file which should be included by the script generating noise profiles. Since we've recenlty got several new noise profiles (and have rather steady input of noise profiles) it seems like the problem might be in your shell or config or whatever else...

Please re-try generating the noise profiles using either release 3.4.1 or current master or in case of problems - please post the full set somewhere and create a new issue so someone could help and generate the profiles for you...

In order to keep the ongoing issues tidy I'd have to close this one if you don't mind :)

**Closed by johnny-bit** 2021-06-13 13:34 UTC
Labels: no-issue-activity
