### ISSUE TITLE
Random magenta cast

### ISSUE THREAD

**Issue by juhavlintula** [darktable-org/darktable#10288] opened 2021-10-28 19:28 UTC
**Describe the bug/issue**
Sometimes when I open an image the first time in darkroom, it gets a magenta cast. See examples in [pixls.us](https://discuss.pixls.us/t/random-magenta-cast/26575/20).

**To Reproduce**
This has happened to me few times, but I haven't been able to reproduce it. Also, according to the thread in pixls.us, I'm not the only one.

**Expected behavior**
The camera white balance values read and applied properly.

**Screenshots**
Image opened the first time
![image](https://user-images.githubusercontent.com/18402158/139321396-f3f1e882-0c97-40a4-837f-6eb5b59899a7.png)
_as shot in camera_ applied the first time
![image](https://user-images.githubusercontent.com/18402158/139321505-8586fe94-9d5c-47ff-a84a-253270e75c9c.png)
_as shot in camera_ applied the second time
![image](https://user-images.githubusercontent.com/18402158/139321551-08877b08-4134-4a1f-b5a3-b804ab344389.png)
And discarding the history stack and reopening the image
![image](https://user-images.githubusercontent.com/18402158/139321616-aa649df6-2180-4693-bba0-e7c7420fe405.png)

**Which commit introduced the error**
Unable to specify.

**Platform**
* darktable version : 3.7.0+1332~gf3c26fb58
* OS                : Win10
* Graphics card     :  NVIDIA GeForce 940MX
* Graphics driver   : 496.13
* OpenCL installed  :  yes
* OpenCL activated  :  yes

**Additional context**
According to the thread in [pixls.us](https://discuss.pixls.us/t/random-magenta-cast/26575) this has also occurred in a Linux environment.

**Comment by nathancrabtree** [comment] 2021-10-30 08:35
I'm getting it with Arch, it's not happening as frequent with 3.7.0+1343~g24e5e76215 but it's still happening, for me it's more when using the colour pickers in either filmic or the new colour balance module masks tab, it's happened once with the colour picker with colour calibration. Also happening sometimes is the magenta cast appearing when zooming in but then goes when it renders.

**Comment by Nilvus** [comment] 2021-10-30 09:02
We've had an issue with Panasonic RAW caused by a rawspeed update introduced that but reading pixl.us forum let me think you're not using Panasonic RAW. The issue with Panasonic RAW was caused by -5 values on all 4 black levels in raw black/white point module.

**Comment by Nilvus** [comment] 2021-10-30 09:04
Update, seeing more screenshots, differences are on calibration modules values. Color pickers are not always good to set good values. So adjusting then values manually is often necessary. Anyway, if this happened differently automatically (without doing any action in the module) in same image is strange.

**Comment by juhavlintula** [comment] 2021-10-31 19:49
I didn't use any color pickers, just _as shot in camera_.

A clarification to
**How to reproduce**
1. Import images to dt (not processed before)
2. Open an image in darkroom
3. In few cases (<5% my estimate) see the magenta cast

**Comment by nathancrabtree** [comment] 2021-11-01 11:23
In my case the images import fine in darkroom and the cast appears sometimes with some modules, if I use the mouse wheel to zoom in and back out the cast goes I've noticed so I don't have to reset colour calibration anymore.

**Comment by AufDerMauer** [comment] 2021-11-05 06:43
I have the same issue with raw files from Panasonic Fz1000.
It happens after updating to darktable 3.6.1.

When I import raw files the black levels seems to be wrong. 
For the moment I changed back to a previous version of darktable.
Unfortunately the file import has had a bug with german umlauts. (I know it's already solved in 3.6.1)

**Comment by Nilvus** [comment] 2021-11-07 09:43
> I have the same issue with raw files from Panasonic Fz1000. It happens after updating to darktable 3.6.1.
> 
> When I import raw files the black levels seems to be wrong. For the moment I changed back to a previous version of darktable. Unfortunately the file import has had a bug with german umlauts. (I know it's already solved in 3.6.1)

This is specific to Panasonic RAW and explain in issues linked here. Just read them, the workaround (update black levels values) is explained (and easy to set).

**Comment by Nilvus** [comment] 2022-01-07 08:09
As this is fixed, I close it

**Closed by Nilvus** 2022-01-07 08:09 UTC
Labels: no-issue-activity
