### ISSUE TITLE
Map: Removing pictures from map is not possible when using two displays

### ISSUE THREAD

**Issue by karsten745** [darktable-org/darktable#6010] opened 2020-08-18 10:15 UTC
Hi, removing a picture from the map ("map" module) by pulling it over the filmstrip does not work, when my two displays are both active. With one of them it works well. 
Pulling the picture with the mouse or pen firstly removes the picture, but when clicking on any point of the screen after that, the picture appears again at the old location. After deactivating of one of the displays, it works with mouse and with pen.

- Darktable: 3.2.1 (package installed from the OBS repository) 
- OS: Linux Mint 20
- OpenCL: activated
- Graphics card: Intel Corporation HD Graphics 530
- Display 1:  1920x1200 display (EIZO CS2420)
- Display 2: 1920x1080 pen display (Wacom Cintiq 16)

Karsten

**Comment by Nilvus** [comment] 2021-06-20 13:01
@karsten745: I close this issue as a lot of things have been improved this year in map part. The library behind (libosm-gps-map) had been hugely improved this past months after about 2 years without any update and lot other things have been improved too in darktable about map view. I suggest you so to wait for 3.6, which will be released in about 2 weeks. You could then test again. If you reproduce on future 3.6, feel free to reopen or ask for it and provide your tests in a new comment.

I'm on Linux and just tested in actual master (future 3.6) and I can't reproduce your issue.

**Closed by Nilvus** 2021-06-20 13:01 UTC
Labels: no-issue-activity
