### ISSUE TITLE
Sony Alpha 1 (ILCE-1)

### ISSUE THREAD

**Issue by ashic** [darktable-org/darktable#8618] opened 2021-04-05 15:58 UTC
I just uploaded 6 samples (3 each for uncompressed, lossless compressed, and compressed for full frame and APSC respectively) to https://raw.pixls.us/ 

I don't yet see them listed when I search for ILCE-1. Is there something else I can do? Or any other way I can help get the Sony Alpha 1 supported in darktable? The images are seen in lighttable, but when I go to the darkroom view, it tells me that it can't process the images. The logs show the following error:

```[rawspeed] (A1_apsc_uncompressed.ARW) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 169: Camera 'SONY' 'ILCE-1', mode '' not supported, and not allowed to guess. Sorry.
```

**Comment by LebedevRI** [comment] 2021-04-05 16:08
Thank you for contributing the samples!
Ah, so that camera has more than one compression mode.
While this is partially a duplicate of #8523, the other modes should be supportable easily..

**Comment by ashic** [comment] 2021-04-05 16:14
@LebedevRI the samples aren't showing up when I search for ILCE-1; it did pick up the ILCE-1 and Sony labels on the upload form, but couldn't understand the mode for lossless compressed. Yes, lossless compressed is new to the A1. Is there something I did that prevented the upload somehow? 

Anyhow, really looking forward to darktable support. The camera is awesome, and I'd hate to have to boot to Windows to run DxO or something.

**Comment by ashic** [comment] 2021-04-05 16:27
Quick update... it appears that rawtherapee supports compressed and uncompressed, but not the new lossless compressed. I'm guessing the compressed and uncompressed file formats are the same as in previous Sony Alpha bodies, and it's just the model number check that's failing for darktable. Is there a way we can *tell* darktable to treat it like an A7r iv or similar file? I'm ok not shooting lossless compressed if it means I can use darktable for now.

**Closed** 2021-06-10 10:09 UTC
Labels: no-issue-activity, scope: camera support
