### ISSUE TITLE
Support lossless compressed raw files (gzip/xz)

### ISSUE THREAD

**Issue by pbo-linaro** [darktable-org/darktable#17449] opened 2024-09-08 19:23 UTC
**Is your feature request related to a problem? Please describe.**

I'm currently using a Sony A7III, and shooting with uncompressed RAW (48MB/file).
To limit the storage I need to keep my files, I compress those raw files using `xz -0`, which is a good balance between speed and compression ratio. It's better than gzip in my experience.
The average compressed file is around 30MB.
To edit those files again, I need to manually uncompress those.

**Describe the solution you'd like**

It would be nice if Darktable could natively compress/uncompress those raws when you import them, providing gzip and xz support.

Is there a technical reason while this approach is not implemented in RAW editing software in general?

Thanks!

**Comment by ralfbrown** [comment] 2024-09-09 01:57
Duplicate of #17086.  See the reasons there.

**Closed** 2024-09-09 02:12 UTC
Labels: duplicate
