### ISSUE TITLE
Crop - keystone correction: correction guide hard to adjust

### ISSUE THREAD

**Issue by kofa73** [darktable-org/darktable#6219] opened 2020-09-06 10:31 UTC
On Ubuntu 20.04 with KDE, self-compiled cd8e1df2.

When **'reduce resolution of preview image'** (**preview_downsampling**) is set to **1/4**, I find the guides for adjusting keystone in the crop module very hard to adjust; there is **no problem when the setting is left at 'original'**.
I have to very accurately target the control point until the cursor switches into cross-hairs (from the 4-way arrows). I do not recall this behaviour with previous versions.

**Comment by johnny-bit** [comment] 2020-09-06 11:44
are you able to check with recent official versions of darktable, meaning 3.0.2 and 3.2.1?

**Comment by kofa73** [comment] 2020-09-06 12:11
Yes, I'll build those versions and will check.

**Comment by kofa73** [comment] 2020-09-06 16:15
!(screenshots from 3.2.1 and master)[https://photos.smugmug.com/Other/Darktable-issues/Misc/i-BMpCXTc/0/f6a48b81/O/crosshairs.png]
The top is with darktable 3.2.1. As soon as the pointer touches the red circle, it switches to crosshairs, and the circle can be repositioned.
The bottom two crops are from the current master (5c7e12f9). Even when the pointer touches the red circle, it remains the 4-way  pointer; you have to move further inside the circle (until it no longer touches the red circle?) for it to switch to crosshairs.

Maybe it's not a problem for most; I find it harder, though not impossible, to position the point this way.

**Comment by johnny-bit** [comment] 2020-09-06 16:23
So the problem is in master but not in 3.2.1? Would you be willing to bisect the issue as described in https://github.com/darktable-org/darktable/wiki#finding-bug-causes ? that would narrow down the problem-causing commit.

**Comment by kofa73** [comment] 2020-09-06 16:55
Sure (I'm a dev, I know git bisect :-))

**Comment by kofa73** [comment] 2020-09-07 05:05
It's not a bug, but some setting, does not occur with a fresh darktablerc.

**Comment by johnny-bit** [comment] 2020-09-07 07:42
Then let's ping @GrahamByrnes because it's the author of the PR introducing preview downsampling :)

**Comment by GrahamByrnes** [comment] 2020-09-07 08:50
Yes, that was always a problem. It affects the UI because the coordinates for the guides are taken from the downsampled image, so there is a loss of resolution. That said, there might be something I can do, I'll take a look (although it may take some time).

**Comment by GrahamByrnes** [comment] 2020-09-12 10:01
If anyone else wants to have a go at this... feel free :-)

**Comment by ptilopteri** [comment] 2020-09-12 12:48
fwiw: I use this module 6 to 10 times a week during high school soccer season and little difficulty.  

I move the "corner" dots to approximately the four corners to base on the increase the zoom
to 100% and accurately place each corner.

**Comment by kofa73** [comment] 2020-10-04 20:35
@ptilopteri: did you set "enable reduce resolution of preview image (preview_downsampling)" to 1/4?

**Comment by ptilopteri** [comment] 2020-10-04 22:02
no, I only select keystone, full and drag the corner markers, then
increase image size to accurately place each

**Comment by kofa73** [comment] 2020-10-05 10:48
OK, so thanks for confirming that it works fine without downsampling. That is how it should work with downsampling turned on, too.

**Comment by GrahamByrnes** [comment] 2020-10-05 11:24
Indeed it should. You might like to look at the code in src/iop/clipping.c
and see what you can try changing. It would be good to get this cleaned up.

**Comment by TurboGit** [comment] 2020-10-05 12:18
@kofa73 @ptilopteri : can you test #6453 ? It should make grabbing the keystone control easier.

**Comment by TurboGit** [comment] 2020-10-05 12:18
@GrahamByrnes : You review on #6453 will be appreciated, nothing fancy but works for me.

**Comment by GrahamByrnes** [comment] 2020-10-05 12:27
Looks very simple ;-)

I'm at work now, no cmpiler, will check later...

**Comment by ptilopteri** [comment] 2020-10-05 12:50
@TurboGit 
Will be happy to test #6453, but How do I test #6453.
to date I just clone/get submodules and build
dummy here :) but I work hard at it.

**Comment by GrahamByrnes** [comment] 2020-10-05 13:16
You can just paste the 3 lines of code ino a recent clone and build :-)

**Comment by ptilopteri** [comment] 2020-10-05 13:40
ok, did that and rebuilt

but did not work and I did check that I pasted the 3 lines into the correct
location.

3160,3162d3159
< const float pr_d = darktable.develop->preview_downsampling;
< // slightly adjust the size of keystone control area depending on the downsampling
< const float ext = DT_PIXEL_APPLY_DPI(0.005f + ((1.0f - pr_d) / 100.0f)) / zoom_scale;

[ 84%] Built target toneequal
gmake: *** [Makefile:171: all] Error 2

still workking at it.

**Comment by ptilopteri** [comment] 2020-10-05 13:52
so I side-stepped the short method, copy-paste and dl'd the altered
clipping.c and build was successful, 

I do not see any functional difference in keystone operation in the 
manner I apply.

change is ok by me.

**Comment by kofa73** [comment] 2020-10-05 15:11
`git fetch origin pull/6453/head:pr6453` and then `git checkout pr6453`, then build. If you modified files locally, do a `checkout . ; git clean -d -f -x` as well.

**Comment by ptilopteri** [comment] 2020-10-05 15:21
@kofa73 tks, salted these instructions away for future use :)

**Comment by ptilopteri** [comment] 2020-10-05 15:42
@kofa73 and tested successfully

**Comment by kofa73** [comment] 2020-10-05 17:07
I can confirm that it works fine both at 1/4 and original size. Thanks for the quick fix.

**Comment by ptilopteri** [comment] 2020-10-05 17:40
maybe you need to close this issue if you consider it fixed?

**Comment by kofa73** [comment] 2020-10-05 17:55
I'd assume the issue is closed by the developers, once the PR is merged.

**Comment by TurboGit** [comment] 2020-10-05 17:57
Exactly and this has just happened now :)

**Closed** 2020-10-05 17:56 UTC
Labels: bug: pending
