### ISSUE TITLE
Modules fail to initialize introspection

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#5267] opened 2020-05-31 23:00 UTC
**Describe the bug**
Running dt on the console shows messages like these for all modules.
```
[iop_load_module] failed to initialize introspection for operation `highpass'
[iop_load_module] failed to initialize introspection for operation `monochrome'
[iop_load_module] failed to initialize introspection for operation `colorout'
[iop_load_module] failed to initialize introspection for operation `borders'
...
```

**Expected behavior**
This should not be seen ...

**Platform**
Fedora 32, CL does not matter
 

**Additional context**
Introduced in `introspection: add description and default to enums`

**Comment by johnny-bit** [comment] 2020-06-01 07:42
Caused by fb46a038203f69d4509c360d32cc0de73773a1c4 (which broke things in weird ways :) )
Worked around in 0750cbd1a3f3131a4ceb4b4e93bcb807b4b3e771 (the messages)
Fixed in 0d825a4ceb42a97fc2c365c55bf4bb8ee6714f2c

Proof that many people ride on bleeding edge master: #5266 + #5265

**Closed** 2020-06-01 07:47 UTC
