### ISSUE TITLE
Cannot edit raw images (RAF) in darktable 

### ISSUE THREAD

**Issue by cbochs** [darktable-org/darktable#8515] opened 2021-03-19 21:15 UTC
**Introduction**

darktable is failing to load `.RAF` files from my Fuji X-S10. I am only guessing, but it might just be that this camera is unsupported in darktable right now? Is there any way I can capture debug logs?

Edit: found debug logs. Any suggestions other than running `.\darktable -d all`?

**Error:** "darktable could not load 'DSCF0221.RAF', switching to lighttable now. please check the image (use exiv2 or exiftool) for corrupted data. if the image seems to be intact, please consider opening an issue at https://github.com/darktable-org/darktable"

**exiftool** output looks fine to me?
<details>
  <summary>Output</summary>

```
ExifTool Version Number         : 12.22
File Name                       : DSCF0221.RAF
Directory                       : D:/CALVIN_PC/Pictures/Calvin/2021_03_13_WalkInThePark
File Size                       : 57 MiB
File Modification Date/Time     : 2021:03:13 12:36:02-07:00
File Access Date/Time           : 2021:03:19 15:06:52-06:00
File Creation Date/Time         : 2021:03:13 12:36:02-07:00
File Permissions                : -rw-rw-rw-
File Type                       : RAF
File Type Extension             : raf
MIME Type                       : image/x-fujifilm-raf
RAF Version                     : 0102
Exif Byte Order                 : Little-endian (Intel, II)
Make                            : FUJIFILM
Camera Model Name               : X-S10
Orientation                     : Rotate 270 CW
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : Digital Camera X-S10 Ver1.02
Modify Date                     : 2021:03:13 13:36:00
Y Cb Cr Positioning             : Co-sited
Copyright                       :
Exposure Time                   : 1/3200
F Number                        : 3.2
Exposure Program                : Aperture-priority AE
ISO                             : 250
Sensitivity Type                : Standard Output Sensitivity
Exif Version                    : 0232
Date/Time Original              : 2021:03:13 13:36:00
Create Date                     : 2021:03:13 13:36:00
Components Configuration        : Y, Cb, Cr, -
Compressed Bits Per Pixel       : 3.2
Shutter Speed Value             : 1/3444
Aperture Value                  : 3.2
Brightness Value                : 9.48
Exposure Compensation           : 0
Max Aperture Value              : 2.8
Metering Mode                   : Multi-segment
Light Source                    : Unknown
Flash                           : No Flash
Focal Length                    : 18.0 mm
Version                         : 0130
Internal Serial Number          : FF02B6300381     Y56201 2020:12:14 C773101143DC
Quality                         : NORMAL
White Balance                   : Auto (white priority)
Saturation                      : 0 (normal)
White Balance Fine Tune         : Red +0, Blue +0
Noise Reduction                 : 0 (normal)
Fuji Flash Mode                 : Manual
Flash Exposure Comp             : 0
Focus Mode                      : Auto
AF Mode                         : No
Focus Pixel                     : 1281 1472
AF-S Priority                   : Focus
AF-C Priority                   : Release
Focus Mode 2                    : AF-S
AF Area Mode                    : Wide/Tracking
AF Area Point Size              : n/a
AF Area Zone Size               : n/a
AF-C Setting                    : Set 1 (multi-purpose)
AF-C Tracking Sensitivity       : 2
AF-C Speed Tracking Sensitivity : 0
AF-C Zone Area Switching        : Auto
Slow Sync                       : Off
Picture Mode                    : Aperture-priority AE
Exposure Count                  : 1
Shadow Tone                     : 0 (normal)
Highlight Tone                  : 0 (normal)
Lens Modulation Optimizer       : On
Grain Effect                    : Off
Color Chrome Effect             : Off
Crop Mode                       : n/a
Color Chrome FX Blue            : Off
Shutter Type                    : Mechanical
Auto Bracketing                 : Off
Sequence Number                 : 0
Drive Mode                      : Single
Drive Speed                     : n/a
Blur Warning                    : None
Focus Warning                   : Good
Exposure Warning                : Good
Dynamic Range                   : Standard
Film Mode                       : F2/Fujichrome (Velvia)
Dynamic Range Setting           : Manual
Development Dynamic Range       : 100
Min Focal Length                : 18
Max Focal Length                : 55
Max Aperture At Min Focal       : 2.8
Max Aperture At Max Focal       : 4
Image Stabilization             : OIS Lens; On (mode 1, continuous); 0
Image Generation                : Original Image
Image Count                     : 205
Flicker Reduction               : Off (0x0001)
Faces Detected                  : 0
Num Face Elements               : 0
User Comment                    :
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 4416
Exif Image Height               : 2944
Interoperability Index          : R98 - DCF basic file (sRGB)
Interoperability Version        : 0100
Focal Plane X Resolution        : 1882
Focal Plane Y Resolution        : 1882
Focal Plane Resolution Unit     : cm
Sensing Method                  : One-chip color area
File Source                     : Digital Camera
Scene Type                      : Directly photographed
Custom Rendered                 : Normal
Exposure Mode                   : Auto
Focal Length In 35mm Format     : 27 mm
Scene Capture Type              : Standard
Sharpness                       : Normal
Subject Distance Range          : Unknown
Serial Number                   : 0D062646
Lens Info                       : 18-55mm f/2.8-4
Lens Make                       : FUJIFILM
Lens Model                      : XF18-55mmF2.8-4 R LM OIS
Lens Serial Number              : 0DC05305
Composite Image                 : Not a Composite Image
PrintIM Version                 : 0250
Compression                     : JPEG (old-style)
Artist                          :
Thumbnail Offset                : 3984
Thumbnail Length                : 8827
Rating                          : 0
Image Width                     : 4416
Image Height                    : 2944
Encoding Process                : Baseline DCT, Huffman coding
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:2 (2 1)
Preview Image                   : (Binary data 5916519 bytes, use -b option to extract)
Raw Image Full Size             : 6384x4182
Raw Image Crop Top Left         : 13 6
Raw Image Cropped Size          : 6240x4160
Raw Image Aspect Ratio          : 3:2
Fuji Layout                     : 12 12 12 12
X-Trans Layout                  : GRBGBR BGGRGG RGGBGG GBRGRB RGGBGG BGGRGG
Raw Exposure Bias               : -0.7
Raw Image Width                 : 6276
Raw Image Height                : 4140
Raw Image Full Width            : 6384
Raw Image Full Height           : 4182
Bits Per Sample                 : 14
Strip Offsets                   : 5941248
Strip Byte Counts               : 53395776
Black Level                     : 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022
Geometric Distortion Params     : 416.5555556 0.3535211268 0.5 0.6126760563 0.7070422535 0.7908450704 0.8661971831 0.9352112676 1 1.06056338 -0.9283752441 -2.06072998 -3.087081909 -4.004226685 -4.834625244 -5.538131714 -6.103515625 -6.543609619 -6.543609619
WB GRB Levels Standard          : 302 391 844 17 302 661 490 21
WB GRB Levels Auto              : 302 596 549
WB GRB Levels                   : 302 594 549
Chromatic Aberration Params     : 416.5555556 0.3535211268 0.5 0.6126760563 0.7070422535 0.7908450704 0.8661971831 0.9352112676 1 1.06056338 0.0005187988281 0.0004577636719 0.0003967285156 0.0003356933594 0.000244140625 0.0001831054688 9.155273438e-005 0 0 0.000244140625 0.0003356933594 0.0004272460938 0.0005493164063 0.0006408691406 0.0007629394531 0.0009155273438 0.001068115234 0.001068115234 416.5555556
Vignetting Params               : 416.5555556 0.3535211268 0.5 0.6126760563 0.7070422535 0.7908450704 0.8661971831 0.9352112676 1 1.06056338 94.90234375 89.04345703 84.31445313 80.40820313 75.71142578 70.59619141 63.54296875 56.48095703 56.48095703
Aperture                        : 3.2
Blue Balance                    : 1.817881
Image Size                      : 6240x4160
Megapixels                      : 26.0
Red Balance                     : 1.966887
Scale Factor To 35 mm Equivalent: 1.5
Shutter Speed                   : 1/3200
Thumbnail Image                 : (Binary data 8827 bytes, use -b option to extract)
Circle Of Confusion             : 0.020 mm
Field Of View                   : 67.4 deg
Focal Length                    : 18.0 mm (35 mm equivalent: 27.0 mm)
Hyperfocal Distance             : 5.05 m
Light Value                     : 13.7
Lens ID                         : XF18-55mm F2.8-4 R LM OIS
```
</details>

---------------------------------------------------------------

**Describe the bug/issue**

**To Reproduce**
* Add `.RAF` image to through darktables lighttable
* Attempt to edit raw image in darktoom
* See error

**Expected behavior**

The raw `.RAF` file can be edited in darkroom.

**Screenshots**

_screenshot of darkroom_
![image](https://user-images.githubusercontent.com/2467016/111841803-26bfbe80-88c4-11eb-933e-ef7bab7c9130.png)

**Platform**

* darktable version : **3.4.1.1**
* OS : Win 10, Build 19042
* Memory : 32GB
* Graphics card : nVidia GTX 1060 6GB
* Graphics driver   : 461.92
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**

 - Can you reproduce with another darktable version(s)? **haven't tried other versions**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**

**Comment by cbochs** [comment] 2021-03-19 21:42
Running `.\darktable -d camsupport` I get:

```
========================================
version: darktable 3.4.1.1
start: 2021:03:19 15:40:34

[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 0 to 2097152
RawSpeed:Unable to find camera in database: 'FUJIFILM' 'X-S10' ''
Please consider providing samples on <https://raw.pixls.us/>, thanks!
[rawspeed] (DSCF0221.RAF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const string&, const string&, const string&), line 169: Camera 'FUJIFILM' 'X-S10', mode '' not supported, and not allowed to guess. Sorry.

(darktable.exe:4424): GLib-GObject-WARNING **: 15:41:00.206: invalid unclassed pointer in cast to 'GtkDarktableExpander'

** (darktable.exe:4424): CRITICAL **: 15:41:00.206: dtgtk_expander_get_expanded: assertion 'DTGTK_IS_EXPANDER(expander)' failed
```

How can I fix this?

**Comment by cbochs** [comment] 2021-03-19 22:09
Possibly related: https://github.com/lensfun/lensfun/pull/1322

**Comment by cbochs** [comment] 2021-03-19 22:11
Also, the [cameras.xml](https://github.com/darktable-org/rawspeed/blob/develop/data/cameras.xml) needs to be updated in the rawspeed repo, I presume

**Comment by cbochs** [comment] 2021-03-19 23:53
I'm not sure if this is entirely fixed, but I applied the above code changes to the XML files myself and it looks to be at least allowing me to edit RAF files now 🙂

**Comment by kmilos** [comment] 2021-03-20 12:51
Duplicate of #8512 and #8513

**Comment by johnny-bit** [comment] 2021-03-20 14:26
Thanks @kmilos

**Closed by johnny-bit** 2021-03-20 14:26 UTC
