### ISSUE TITLE
Top level folder (Root Folder) in lighttable disappears

### ISSUE THREAD

**Issue by yankee495** [darktable-org/darktable#3975] opened 2019-12-31 20:54 UTC
Possible 3.1 & 3.0 bug:

I accidentally downloaded 3.1.0+10~gaf8b11a17 which is a development version. It compiled fine. There were only 10 changes and I don't know what they are, but I'm guessing this bug is in DT 3.0 too. It may have been there since v2. I say that because I don't know if this is the expected behavior.

I was cleaning out and organizing my photos to copy to a new hard drive. In Lighttable under Collect Images, with Folder selected (not Film Roll), I've always had a top level folder and then folders below that. Like this.

->D7100

--->Stuff 1

--->Stuff2

---->Stuff3

I could remove D7100 and all of the folders below it would be removed. Tonight, after importing the D7100 folder, then closing and reopening Darktable, all I had was the list of folders like a Film Roll list, but I was in folder view.

Before closing DT, the D7100 folder was there and said 3504 but it just disappeared after reopening DT. I deleted the database and imported again. I did this a couple of times and it was the same.
I took a short break to think....what did I change?

Ok. I had a few stray photos in the D7100 folder, the root folder, and some other folders, and I had moved the photos to a folder called junk. It seems if you don't have any photos in the "bottom of the root folder", you loose the root folder because DT treats it like an empty folder instead of the root folder of all of the others. I put a single photo back into the D7100 folder to fix it and tried it twice. It works. I don't lose the top D7100 folder.

Now my D7100 folder says 3505. I had to add the single photo to the bottom of the root folder (D7100 folder), below the other folders, to keep the D7100 from disappearing. I'm sure this worked because with V2 because I had root folders of D3200, D7100 and a Misc folder. I also had images in all of the root folders.

**To Reproduce**
Import a set of folders with no photos in the root folder, only other folders.

Close and reopen Darktable into lighttable mode, folder view.

**Expected behavior**
The Root folder should remain in the list.

**Darktable Version:** 3.1.0+10~gaf8b11a17
**OS:** Mageia 7 x64

**Comment by Egocentrix** [comment] 2020-01-07 11:30
I haven't looked at the code, but I guess this is because darktable does not use the concept of folders internally. Even when importing a folder, it imports the photos *in* that folder and it just shows the folders that contain pictures, with their paths up to the first common parent.

I agree that this is not optimal, especially if you want to manage multiple folders spread around your hard drive. Implementing a 'root folder' concept is not going to be trivial though. Some questions that I can think of:
- What is a 'root folder'?
- What happens if you import multiple folders? Is each of them a root folder, or their common parent?
- What happens if you delete (all images from)a folder from the library? Should it also remove their parent folders if they are empty?

**Comment by yankee495** [comment] 2020-01-07 19:02
If it was a bug, I wanted to make sure developers were aware and I wanted to let users know I'd found a work around if root folder behavior is what you want. I always had images in the root folder so it took a while to figure out what was going on. If that's the proper operation I'll tell users in our group how it works and to keep an image to have root folder behavior. Thank you very much.

**Comment by johnny-bit** [comment] 2021-01-23 12:32
Well, It certainly isn't a bug. It's intended behaviour, simply because it's optimal to do it that way.

Currently "root" dir is present only if you imported folders AND imported it's parent, simply because then it can be easily checked in db without accessing filesystem, allowing for far quicker (and more predictable) behaviour.

Imagine how it would work if you hadn't had that and had images spread across user dir and several mountpoints... then "root" will become simply `/` and that's about as useful as file explorer (for example that would make paths like `/media/Canons/77D/2019/07_morning_walk` and `/home/johnny/Pictures/Darktable/dev_test/CanonD30WB` have common root and 4-5 dirs deep...

I'd say that "common root" behaviour would enhance nothing and further contribute to possible confusion...

(I'm closing this as it's not a bug but design decision. Feel free to request a feature that would mark common root to certain point or global or something like that, which you believe would enhance UI/UX/DAM in darktable)

**Closed by johnny-bit** 2021-01-23 12:32 UTC
Labels: no-issue-activity
