### ISSUE TITLE
Remove the need to use CTRL when trying to create an area selection with the color picker...

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#7526] opened 2020-12-28 21:33 UTC
Just a comment and I am not sure that others will agree or feel it is worth the effort. I suspect it was an attempt to simplify the color picker by removing the second selection picker and forcing the user to use ctrl to create an area however I just find this a more clumsy way to select that option. I have to look away and find the ctrl key and then look back and click the small picker icon. 

Would it be hard to a) insert a preference setting that would allow area as the default and not point. Essentially if you don't draw anything after you click you would have a point anyway. or b) recode so that after selecting the picker within the color picker module that you would single click on the image to leave a point or click hold and begin to draw to create an area selection??  Either of these methods would be easier IMO than having to introduce a ctrl click to create an area. Even using the old way you didn't have to slow down just select which picker mode from the small picker icon and go....its a small thing but I think it gets used a lot certainly I do and so using it in one of the two ways above that I suggested would seem more fluid to me....again its coming from my viewpoint and others may disagree.......

**Comment by johnny-bit** [comment] 2020-12-28 22:10
Duplicate of #7525

**Closed by johnny-bit** 2020-12-28 22:10 UTC
