### ISSUE TITLE
Support new M2 MAC without OpenCL support or ditch the OS altogether

### ISSUE THREAD

**Issue by erickpaquin** [darktable-org/darktable#15922] opened 2023-12-21 15:07 UTC
**Is your feature request related to a problem? Please describe.**

Because my new mac mini M2 doesn't have OpenCL built-in (and I can't find a way to install it either), darktable becomes pretty much useless because it takes forever to compute anything, makes the work at least 6 times longer than on my 10 year old Linux laptop.

Apple has switched to "Metal" instead of OpenCL and if we don't find a workaround for this then I'll be using my Linux laptop from now on, not a big issue, but my "photography" setup was on a mac, so now I'll have to switch.

**Describe the solution you'd like**
Make darktable use "metal" instead of "OpenCL" for the newer macs that don't have OpenCL anymore. If that cannot be done, I believe it is a waste of time to keep developing for macs. It's nice to "market" darktable as capable for macs but if the performance cannot result in an acceptable time during the workflow, then it's not worth it.

**Alternatives**
Optimize the code to only use CPU's and not rely on GPU engines might solve alot of issues.

**Additional context**
One particular observation that killed it for me was that whenever I use the export option "high quality resampling", if I click yes, on my new 16G memory mac, it takes about 30-35 seconds to export a jpg. When I turn this setting off, it takes about 4-5 seconds, insane. On my OpenCL linux machine with the setting on it takes about 3-4 seconds to generate the same image, about 10 times faster than on my new mac. So again, if this cannot be fixed, just ditch apple and keep moving.

Thanks.

**Comment by jenshannoschwalm** [comment] 2023-12-21 16:18
I am really surprised that opencl doesn't work on the latest apples.

**Comment by Christian-Kr** [comment] 2023-12-21 18:28
I am wondering why it takes so long. I have two m1 max and OpenCl is turned off in darktable. For me it feels pretty usable. Are you using the current stable or the git master branch?

Greetings

**Comment by erickpaquin** [comment] 2023-12-21 18:47
I'm using 4.4.2.

"usable" is a relative term I suppose.

My mac mini M2 is brand new, has 16G of Ram. 30+ seconds to render a jpeg compared to 3-4 seconds on my old Linux box, I consider this unusable, especially when you're trying to process 600+ images.

And that's not mentioning the time wasted in each normal edit steps and re-rendering on screen.

Seriously happy I have a Linux box to do my work in going forward. Just didn't think performance would be so bad on a brand new apple box.

I hate the fact that apple simply disabled OpenCL instead of leaving both options available but hey...I just think if darktable wants to keep supporting Apple boxes, they have to support it properly or stop saying it works on it, because as far as I'm concerned, it doesn't, for all intents and purposes.

Also, if there is not enough dev guys supporting this platform, another good reason to ditch it, waste of time otherwise.

I'm not bitching at the darktable team by the way, they do an amazing job, more than I'll ever care to do. I was just stating my current concerns and experience.

Thanks

**Comment by jenshannoschwalm** [comment] 2023-12-21 19:02
Not bitching - just suggesting to ditch? I'm not a native speaker but ...

About the title "Support new M2 MAC without OpenCL support or ditch the OS altogether" what sense should i make out of that?

I don't own an apple comp but a) from tests i saw there is OpenCL available https://browser.geekbench.com/v5/compute/6302682 and b) from dt apple users i didn't hear yet about OpenCL not being available.

**Comment by erickpaquin** [comment] 2023-12-21 19:14
Was deprecated in macos 10.14

https://developer.apple.com/library/archive/documentation/Performance/Conceptual/OpenCL_MacProgGuide/Introduction/Introduction.html#//apple_ref/doc/uid/TP40008312-CH1-SW1

**Comment by erickpaquin** [comment] 2023-12-21 19:18
What sense should I make out of that? If you don't use a mac in the first place, I don't know why you should.

**Comment by jenshannoschwalm** [comment] 2023-12-21 19:20
> Was deprecated in macos 10.14

So what? We know that for some time - and for sure this means the future may be dark - but until now they just kept it included and many mac users are happy opencl runners.

Not knowing what we do if **they** ditch it.

**Comment by jenshannoschwalm** [comment] 2023-12-21 19:21
> What sense should I make out of that?

Just read the title word-by-word :-)

**Comment by erickpaquin** [comment] 2023-12-21 19:26
OpenCL is not included in my latest mac, and no way for me to install it either, not without some crazy hacks anyways. If macos is to be supported long term, metal is the way to go it seems. That's apple's words, not mine.

**Comment by jenshannoschwalm** [comment] 2023-12-21 19:36
@MStraeten @parafin anything you can share?

**Comment by MStraeten** [comment] 2023-12-21 19:36
on my m1max macbook pro GPU is properly used via OpenCL. I also provided arm64 builds during development an didn't receive any hint of missing OpenCL support on apples arm64 chips.

maybe you need to enable it in the ~/.config/darktable/darktablerc file manually

**Comment by erickpaquin** [comment] 2023-12-21 19:43
I'm not at home right now, I'll dump the output when I comeback. I'll try enabling manually as well, but this morning I ran a similar dump output and it said something to the effect of "Not available AND not installed".

**Comment by MStraeten** [comment] 2023-12-21 19:51
then check the lines like
`cldevice_v5_appleapplem1max=0 250 0 16 16 128 0 0 0.000 0.000 0.500`
the seventh number should be 0 (1 disables that device) 
(see https://darktable-org.github.io/dtdocs/en/special-topics/mem-performance/#device-specific-opencl-configuration)
and also `opencl=TRUE` should be set

**Comment by apfelkraut** [comment] 2023-12-21 20:36
Sorry to hear @erickpaquin that you are having trouble. Can clearly read your frustration.

I am using darktable since a longer time on an Macbook Air M1 and am really happy. So a bit surprised about what you are reporting. I would assume (and hope) that this is just a local issue on your machine that could be solved.

2-3 suggestions:

If you have a freshly installed darktable, it might make sense to start and close it 2-3 times. If I remember correctly there were sometimes some challenges that the OpenCL kernel was not always properly initialized during the first time darktable was started. That might explain why you were initially told that OpenCL was "not available AND not installed".

In addition what might help if you share a bit more details on what you are actually doing, possibly a sample image and a step by step description incl. the resampling resolution. With that it might be much easier to reproduce on what you are struggling with.

And just to doublecheck, where are your files located? So in both cases on your local hard drive?

To give you some sample data. I exported Nikon D780 RAW files (14 bit compressed) with full resolution, no resampling, and the default OpenCL settings from my local hard disk:
- DT 4.2.2 (OpenCL deactivated via DT preferences): about 143 seconds for 100 images
- DT 4.2.2 (OpenCL activated via DT preferences): about 114 seconds for 100 images
- DT 4.6 (OpenCL activated via DT preferences): about 112 second for 100 images

**Comment by erickpaquin** [comment] 2023-12-21 21:00
ok I'm back home, here's the result of the cltest on my mac mini : 

`erickpaquin@kingmini ~ % /Applications/darktable.app/Contents/MacOS/darktable-cltest
     0.0258 [dt_get_sysresource_level] switched to 1 as `default'
     0.0259   total mem:       16384MB
     0.0259   mipmap cache:    2048MB
     0.0259   available mem:   8192MB
     0.0259   singlebuff:      128MB
     0.0259   OpenCL tune mem: OFF
     0.0259   OpenCL pinned:   OFF
[opencl_init] opencl related configuration options:
[opencl_init] opencl: OFF
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
[opencl_init] opencl library '/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL' found on your system and loaded
[opencl_init] found 1 platform
[opencl_init] found 2 devices

[dt_opencl_device_init]
   DEVICE:                   0: 'Apple M2 Pro'
   PLATFORM NAME & VENDOR:   Apple, Apple
   CANONICAL NAME:           appleapplem2pro
   DRIVER VERSION:           1.1
   DEVICE VERSION:           OpenCL 1.2
   DEVICE_TYPE:              CPU
   GLOBAL MEM SIZE:          16384 MB
   MAX MEM ALLOC:            4096 MB
   MAX IMAGE SIZE:           8192 x 8192
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1 1 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   FORCED HEADROOM:          400
   AVOID ATOMICS:            NO
   MICRO NAP:                1000
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   *** marked as disabled ***

[dt_opencl_device_init]
   DEVICE:                   1: 'Apple M2 Pro'
   PLATFORM NAME & VENDOR:   Apple, Apple
   CANONICAL NAME:           appleapplem2pro
   DRIVER VERSION:           1.2 1.0
   DEVICE VERSION:           OpenCL 1.2
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          10923 MB
   MAX MEM ALLOC:            2048 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      256
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 256 256 256 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   FORCED HEADROOM:          400
   AVOID ATOMICS:            NO
   MICRO NAP:                1000
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   *** marked as disabled ***
[opencl_init] no suitable devices found.
[opencl_init] FINALLY: opencl is NOT AVAILABLE and NOT ENABLED.`

I'll investigate further the output and try out some of your suggestions.

@apfelkraut , if you did the tests "without" resampling then we are not using the same conditions. I AM using resampling, it is the only way to get a proper quality output in my case. When I do not use resampling, the speed goes up tremendously, at least 6 times faster. So, perhaps you want to try with OpenCL disabled AND resampling ON and see how much speed difference you get.

FYI, I'm only testing with normal raw files from my Nikon D750. Not huge files here.

I'll check a few things and comeback shortly.

Thanks.

**Comment by erickpaquin** [comment] 2023-12-21 21:13
Also, here's what I have in my rc file : 

cldevice_v5_appleapplem2pro=0 1000 0 16 16 128 0 1 0.000000 0.000

7th digit is set to 0. 

Here's the opencl section, I've switched opencl to true but the processing time is the same : 

opencl=true
opencl_checksum=
opencl_device_priority=*/!0,*/*/*/!0,*
opencl_library=
opencl_mandatory_timeout=400
opencl_scheduling_profile=default
opencl_tuning_mode=nothing

I do not see a path for the opencl library...maybe I should put the path that was outputted in my test?

/System/Library/Frameworks/OpenCL.framework/Versions/Current/OpenCL

I guess there's no harm in trying. I'll see what happens.

**Comment by MStraeten** [comment] 2023-12-21 21:22
should be      
```
[opencl_init] found 1 platform
[opencl_init] found 1 device
```
sorry it's the eigth number that should be 0 --> so change the line to
`cldevice_v5_appleapplem2pro=0 1000 0 16 16 128 0 0 0.000000 0.000`

**Comment by jenshannoschwalm** [comment] 2023-12-21 21:26
Also, two platforms? Somehow the icd config has been modified, dt doesn't write but only reads that.

**Comment by jenshannoschwalm** [comment] 2023-12-21 21:28
You should only activate one device in this case. Dt 4.6 will be safe also with this wrong config.

**Comment by erickpaquin** [comment] 2023-12-21 21:37
Guys, it finally worked. You guys are magicians.  : )

These are the settings that made it work in the rc file : 

cldevice_v5_appleapplem2pro=0 1000 0 16 16 128 0 0 0.043073 0.000

opencl=TRUE
opencl_checksum=1665418315
opencl_device_priority=*/!0,*/*/*/!0,*
opencl_library=
opencl_mandatory_timeout=400
opencl_scheduling_profile=default
opencl_tuning_mode=nothing

Basically, first line, setting 8th number to 0 and then setting opencl to TRUE and also leaving the opencl_library alone, I initially put the path to the opencl library in there but that made my jpeg do a bunch of pixelized output, like white noize on tv.

I'm happy that we got it fixed, my jpeg outputs are now at a normal 3-4 seconds instead of 30-36!

I'm not sure if something needs to be fixed in DT. The initialization that it does at the beginning should have enabled these no? Anyways. Very happy of the results.

Thanks to everyone for the help. Back to my normal workflow setup!

**Comment by jenshannoschwalm** [comment] 2023-12-22 04:10
> I'm not sure if something needs to be fixed in DT. The initialization that it does at the beginning should have enabled these no?

For sure the devices were enabled (by default) the first time you started dt on your system. The question is, why were they disabled afterwards? dt does so if there we errors that couldn't be resolved? BTW dt 4.6 has some opencl things fixed, you should upgrade and maybe report afterwards ...

The interesting things here would be:
1. **Why** does darktable find **two** platforms? Did you try anything special to make opencl available? Or manually changed some icl stuff?
2. Could you a) remove the lines starting with `cldevice_v5` from your config file and b) delete all cl kernels and c) after doing so start darktable with `-d opencl` again and post that log? 

Closing this as **no bug** and a strongly misleading title for now - you might still post here and all additional info would be appreciated.

Also - i think all information is available in the manual. Did you read that before opening this issue? If so, what section did confuse you or what information was missing for you.

**Closed by jenshannoschwalm** 2023-12-22 04:10 UTC
Labels: scope: macos support

**Comment by parafin** [comment] 2023-12-22 10:37
There are two devices - CPU and GPU. I think it was like that on macOS since ages. Why is it strange to you? CPU OpenCL drivers exist on Linux and Windows too.

**Comment by jenshannoschwalm** [comment] 2023-12-22 12:41
Argh, stupid me. I just missed the cpu device. Was mislead by same platform name...
