### ISSUE TITLE
slide colors too similar between selected and unselected photos

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#6197] opened 2020-09-04 11:09 UTC
I'm referring to ligthttable view, but to filmstrip in the bottom in darktable and map views too.

Darktable uses three different grays for unselected, selected and hovered photo slides.

I consider that the three grays are too close one another, and they should be more differentiated, I usually I struggle to distinguish them.

Well, actually the _hovered_ gray is quite recognizable, while the selected/unselected ones are really very similar.

**Comment by difrkaguilar** [comment] 2020-09-05 00:14
I created a dark theme with more contrast between those elements. I'm optimizing it and hope in a few days sharing it everybody.

**Comment by Nilvus** [comment] 2020-09-05 18:24
> I created a dark theme with more contrast between those elements. I'm optimizing it and hope in a few days sharing it everybody.

It's not wanted to add directly on darktable new themes. So please consider proposing an update to actual theme (and if you can ping me as I'm the main CSS developer actually). I don't use dark theme even if I work on it, so I don't see all issues he can have.

**Comment by Nilvus** [comment] 2020-09-05 18:24
@difrkaguilar: last thing, and make sure to propose a theme consistent with others.

**Comment by difrkaguilar** [comment] 2020-09-06 03:51
@Nilvus Sorry for my english. I tried to do my best with the themes, changed One of your themes as could because I´m not a CSS developer. Just a designer with a lot of desires to help to get better the software. As you can see in these screen shots I only changed some colors in selected elements, sliders, on mouse over events and minor thinks, but I´m really messy with the code and typographics.
<img width="1920" alt="Capture_00" src="https://user-images.githubusercontent.com/67672868/92317781-929aa380-efd2-11ea-8a85-d91356725f23.png">
<img width="1920" alt="Capture_01" src="https://user-images.githubusercontent.com/67672868/92317784-975f5780-efd2-11ea-9ba9-d30a3613aaa8.png">

**Comment by Nilvus** [comment] 2020-09-06 08:18
@difrkaguilar: your theme is too dark. We choose some grey background on central view and thumbnails for good reasons. And we had already discussed and choose to not include colors in themes, for good reasons too. Those good reasons are mainly to let the place to image and reduce some optic illusions. You could understand that, partially, by reading first part about CSS of 3.0 article posted in darktable.org/blog: https://www.darktable.org/2019/12/darktable-30/ (and especially the reason why we add a grey theme and so some grey choices around images on all themes). After that, it's all remains about compromises.

So, as it is, even if it's seems a good work, that can't be include in master.

**Comment by Nilvus** [comment] 2020-09-06 08:20
@paolobenve: is it possible to have an answer to my first reply here? It could help to check and see if I can do something to improve it.

**Comment by difrkaguilar** [comment] 2020-09-06 10:07
@Nilvus Sorry for the off topic.
As I can see, related to the GUI you don't need any help, you can manage well enough everything with gray from 10 to 100% 👍
You have all the reasons to use the grey themes as you explain in https://www.darktable.org/2019/12/darktable-30/
Anyway will be well that check other projects, like Capture One to see the difference. This is one of the most used software by professional photographers around the world. And as you will see it have colors, darks and empathized too.
Almost every person I know who see darktable said the same: "Without doubt it seems to be a great software, but THE INTERFACE IS SO UGLY I CAN'T WORK IN IT".
That isn't my personal opinion. Maybe you should make a poll to hear other users opinions.
Greetings. Have a great day.

**Comment by Nilvus** [comment] 2020-09-06 10:36
I don't think the interface is so ugly and we have had many feedback saying the opposite you pretend. So we don't need to make a poll, we have had lot of feedback. The goal remains to let place to the image and work on it the best. If people prefer software with what they think is a better UI (even if they work with so wrong colors that they had optic illusions they even don't see), it's their problem. We don't search to please all people (it's even impossible), we search to make best software to work correctly on photos and colors.

The design on such software should be made around photos we work on, not only to please people... That's also isn't only my personal opinion, we have many users and developers who are pleased to use darktable for that reason.

I already tested Capture One and I don't like it's UI. Too dark and ugly for me. Don't forget that we are all different and aesthetic is subjective.

For people who prefers other software, they just have to use... other softwares. That's the beauty of diversity.

Now, as you said, it's off topic so I suggest to stop there. Thanks for your feedback anyway.

**Comment by paolobenve** [comment] 2020-09-07 08:48
@Nilvus in my first post a _too_ was missing at the end of the first paragraph.

The problem is that the grays for selected and unselected photos are too similar in lighttable view, and in map view in the filmstrip. Especially if selected and unselected photos are messed together, it is very hard to distinguish them:

![darktable](https://user-images.githubusercontent.com/1417508/92367873-49903f80-f0f7-11ea-81a1-a13936e8f589.png)

Hovered photos are more distinguishable, however.

**Comment by paolobenve** [comment] 2020-09-07 08:59
> I don't think the interface is so ugly and we have had many feedback saying the opposite you pretend. So we don't need to make a poll, we have had lot of feedback

But if a colored theme could be made available, why not add it among the other ones?

**Comment by johnny-bit** [comment] 2020-09-07 11:44
There might be a bit more of a contrast added but not much else.

> But if a colored theme could be made available, why not add it among the other ones?

Dark UI generally causes issues when processing images, eg oversaturation, wrong exposure adjustment etc. For all intents and purposes of photoediting UI should generally be kept roughly at medium gray level to act as an absolute neutral backdrop. That being said, some people do like dark ui and some people edit solely for darker environments (eg their website is dark, so photos need to look a bit more in place there or they know their image will be shown on dark wall in dark frame etc) so that's why the darker uis are kept. The color assesment mode is a standard ISO mode to asses colors and exposition of an image with as little risk of optical illusions as possible.

Keeping that in mind - adding too much color in ui may create negative effect, false colorizations etc, that's why there's little color in ui (unless that has specific purpose). And default themes are by design kept to have "good decisions by default". Which means there's no room for either black/high-contrast/colorful themes or themes with serif fonts.

Recognizing this limitations and users desire to still be able to configure UI to their preferences, users are absolutely free to create and publish their own themes and/or use CSS tweaks in preferences to set any color they like :)

**Comment by Nilvus** [comment] 2020-09-07 19:27
> > I don't think the interface is so ugly and we have had many feedback saying the opposite you pretend. So we don't need to make a poll, we have had lot of feedback
> 
> But if a colored theme could be made available, why not add it among the other ones?

I have answered to that in a previous comment (https://github.com/darktable-org/darktable/issues/6197#issuecomment-687722922) but thanks to @johnny-bit who made a more precise answer.

To simplify the goal is to have only by default themes related to what @johnny-bit and I have explained. But of course, anyone is free for himself (or share on forums like pixl.us for example) themes they made to other people.

But saying that is very hard to distinguish, is hard to read. On your screenshot, difference is perfectly visible. Anyway, I can understand that some people need better contrast (we don't all have good eyes). But, to succeed on that, I will need your eyes. I will try to propose something ASAP.

**Comment by Nilvus** [comment] 2020-09-07 19:28
@TurboGit: could you assign this issue to me please?

**Comment by TurboGit** [comment] 2020-09-07 20:18
@Nilvus : done !

**Comment by Nilvus** [comment] 2020-09-16 19:41
@paolobenve: could you test if contrast is good for you with those settings:

@define-color thumbnail_selected_bg_color @grey_65;
@define-color thumbnail_hover_bg_color @grey_85;
@define-color thumbnail_hover_fg_color @grey_90;

Just copy/paste them in the new CSS editor in preferences and then click save and apply. Be sure to be on darktable default theme or elegant-darker ones only (those settings are not suitable for dark and grey themes). Then check your thumbnails.

Could you taste also same lines but by increasing on first line 65 to 70. Be sure to check all differences and effet on hover and setting of star icons too.

I'm waiting now for your feedback and hope it will be good for you.

**Comment by paolobenve** [comment] 2020-09-18 12:54
> @define-color thumbnail_selected_bg_color @grey_65;
> @define-color thumbnail_hover_bg_color @grey_85;
> @define-color thumbnail_hover_fg_color @grey_90;

better that now, (darktable theme)

still better if:

@define-color thumbnail_selected_bg_color @grey_70;
@define-color thumbnail_hover_bg_color @grey_85;
@define-color thumbnail_hover_fg_color @grey_100;

**Comment by Nilvus** [comment] 2020-09-18 13:36
> better that now, (darktable theme)
> 
> still better if:
> 
> @define-color thumbnail_selected_bg_color @grey_70;
> @define-color thumbnail_hover_bg_color @grey_85;
> @define-color thumbnail_hover_fg_color @grey_100;

Thanks for your feedback. I can't set grey_100 in darker theme (90 is the highest for that theme) for consistency between theme. I can so add 90 on darker, 95 on dark one and 100 on grey theme. But of course, you could keep that on your preferences for you own taste and use!

So I will go for respectively 70, 85 and 90 on darker one and adjust other themes regardless those new settings. Thanks for your help.

**Closed** 2020-09-18 16:35 UTC
Labels: feature: enhancement
