### ISSUE TITLE
Hasselblad L2D-20c (Mavic 3 drone camera)

### ISSUE THREAD

**Issue by i-trusina** [darktable-org/darktable#10706] opened 2021-12-27 14:55 UTC
Darktable fails to open Hasselblad L2D-20c DNG file in Darkroom. Lighttable is showing preview correctly.

**Comment by PeterWem** [comment] 2022-01-12 06:27
Have you uploaded raw samples to raw.pixls.us?

**Comment by kmilos** [comment] 2022-01-12 07:40
Please search before opening new issues, that s is duplicate of https://github.com/darktable-org/darktable/issues/10852

**Closed** 2022-12-16 13:36 UTC
Labels: scope: camera support
