### ISSUE TITLE
Canon EOS 90D

### ISSUE THREAD

**Issue by JLMALHERBE** [darktable-org/darktable#4208] opened 2020-02-01 07:14 UTC
Please, is it possible for you to add support for Canon EOS 90D camera with Darktable. If you need more samples, i'm at your disposal.

Kind regards.

Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment] 2020-02-01 08:35
Duplicate of https://github.com/darktable-org/darktable/issues/3980

**Closed by LebedevRI** 2020-02-01 08:35 UTC
Labels: scope: camera support

**Comment by roigis** [comment] 2021-07-26 12:15
Hi ! I'm super interested in using darktable with my 90D. 
Please let me know if I can help.

TY!
