### ISSUE TITLE
Error when removing a picture in Lighttable

### ISSUE THREAD

**Issue by bm10440** [darktable-org/darktable#6361] opened 2020-09-23 16:48 UTC
Error when removing a picture in V3.2.1 Windows 64 bits.
The remove function in Lighttable removes all the pictures displayed on the screen instead of the selected picture.
See attached file for the description of the bug.
The problem is the same on 2 different computers, both with Windows 64 bits.
[Bug enlever 20200923.pdf](https://github.com/darktable-org/darktable/files/5269685/Bug.enlever.20200923.pdf)

**Comment by johnny-bit** [comment] 2020-09-23 18:30
You use "culling" mode which behaves very differently from "zoomable light table" and "file manager" modes. switch to file manager mode to be able to operate on single image.

This is not a bug but a way of how culling mode acts. Please see release log for darktable 3.0 to learn more about culling mode and check manual at https://darktable.gitlab.io/doc/en/lighttable_chapter.html#lighttable_culling

Please consider closing this bug :)

**Closed** 2020-12-15 19:51 UTC
Labels: bug: invalid
