### ISSUE TITLE
Strange blowouts when using Colour balance + non-opaque parametric mask together with filmic.

### ISSUE THREAD

**Issue by matt-maguire** [darktable-org/darktable#6315] opened 2020-09-17 06:33 UTC
Originally reported in:
https://discuss.pixls.us/t/is-this-a-3-2-darktable-bug/20247/12

When using colour balance with a parametric mask, and the blend opacity is around 80% or so, and the mask contrast is reduced to -.65 or so, and filmicrgb is enabled (with v3.0 module ordering), then it is possible to get these weird blowout effects appearing on your screen if you fiddle with the feathering slider. If I turn off filmic, I can't get these artifacts to appear, nor if I set the colourbalance blend mode opacity to 100%.

**To Reproduce**
open the following image + XMP:
https://drive.google.com/drive/folders/1gRgCkQQWghDxfqPZOqTyZeBtJrLGW4xl?usp=sharing

or check out the post in pixls.us (link given above).

**Expected behavior**
It should not be possible to produce these sorts of blowouts with these settings.

**Screenshots**
refer to https://discuss.pixls.us/t/is-this-a-3-2-darktable-bug/20247/12

**Platform (please complete the following information):**
 - Darktable Version: 3.3.0+766~g82963f4f0
 - OS: Manjaro Linux 20.0.3
 - OpenCL in on (but makes no difference if I turn it off) 
 - NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] driver: nvidia v: 440.100

**Additional context**
Original poster reported this on darktable 3.2.1 on WIndows.

**Comment by matt-maguire** [comment] 2020-09-17 06:37
Another interesting observation -- if I collapse the top panel of the darkroom view, then the main inage window resizes and the artifact disappears. Switching the top panel back on causes the artifact to return.

**Comment by matt-maguire** [comment] 2020-09-17 06:43
![Screenshot_20200917_164057](https://user-images.githubusercontent.com/35617965/93429586-baf49d00-f904-11ea-87c1-526c51c2ac8c.png)

**Comment by TurboGit** [comment] 2020-09-17 07:14
This only happens with `normal` bending mode but not `normal bounded`. Furthermore the parametric mask is not really good here, display it and you'll see that it creates strong transitions. Adding some blur and including a bit more progressiveness helps too.

**Comment by matt-maguire** [comment] 2020-09-17 07:26
In my case, I just tried to come up with a minimal configuration that could provoke the effect that was originally reported. I can’t imagine how I would ever arrive at this setup as a natural part of my workflow, but it seems at least one person has encountered it in their normal work, and the effect is quite strange that it makes me curious what is going on here.

**Comment by TurboGit** [comment] 2020-09-17 08:55
@matt-maguire : Yes I understand, but at this point I'm not sure it is a bug, most probably an consequence of the way masking works in dt.

**Comment by matt-maguire** [comment] 2020-09-17 11:22
Aurélien wrote some interesting remarks against the pixls.us post. I didn't quite follow what he meant by the equation he wrote, but his remarks do give me an idea where to look to get a handle on what is happening. If you think it is not worth investigating this any further, I'm happy for you to close this, and I'll continue to work through the maths for myself to get a better understanding of the colour balance module and the masking feature.

**Comment by TurboGit** [comment] 2020-09-17 11:47
@matt-maguire : I certainly think it is worth investigating further, anything we can do to improve dt even in some corner cases like this one is good!

**Comment by TurboGit** [comment] 2020-09-18 07:17
@matt-maguire : I have assigned this to you for investigation. Thanks!

**Comment by pitbuster** [comment] 2020-09-20 04:33
I think the problem is that some combinations of blending opacity and mask contrast can produce mask values outside the [0,1] interval, which may produce weird stuff when blending.

I think clamping here https://github.com/darktable-org/darktable/blob/master/src/develop/blend.c#L2843 should do the magic.

**Comment by TurboGit** [comment] 2020-09-22 17:19
Fixed in master.

**Closed** 2020-09-22 17:18 UTC
Labels: bug: pending, difficulty: hard, scope: image processing, understood: unclear
