### ISSUE TITLE
Latest master segfaults immediately (Bisected).

### ISSUE THREAD

**Issue by jade-nl** [darktable-org/darktable#8418] opened 2021-03-06 14:51 UTC
**Describe the bug**

Latest master immediately segfaults after starting.

**To Reproduce**
1. Start latest darktable development version.

**Expected behaviour**
To start nice and proper.

**Bisect info**

```
7c4dbe72a4519b39b75976a0d2553b3b26292dac is the first bad commit
commit 7c4dbe72a4519b39b75976a0d2553b3b26292dac
Author: ralfbrown <ralfbrown@users.noreply.github.com>
Date:   Thu Mar 4 01:03:24 2021 -0500

    apply changes requested in review

:040000 040000 bfc924d1fea09fa4456c15e5544d08a9aa76470a 9f0df341b7ae0cea03a5952cbe3c09ced41bad93 M      src
```

Ping: @ralfbrown 

**Version**

* darktable version : 3.5.0+1340 ge448e6d6d / 3.5.0+1344~g597a63805

**Platform**

* OS                : Linux (kernel 5.9.15-1)
* Distro            : Debian Buster (rel. 10.8)
* Graphics driver   : nvidia (460.39)
* OpenCL installed  : Yes (nvidia-opencl-common 460.39-1)
* OpenCL activated  : Yes
* Xorg              : 7.7+19

**Build info**

* Compiler      : gcc 8.3.0
* Cmake         : 3.13.4
* Glib          : 2.58.3-2
* Gtk+          : 3.24.5-1
* Exiv2         : 0.27.99.0
* Sqlite        : 3.27.2
* Optimization  : None

**Additional info**

Crashlog: [darktable_bt_QBR5Z0.txt](https://github.com/darktable-org/darktable/files/6095505/darktable_bt_QBR5Z0.txt)

this is darktable 3.5.0+1344~g597a63805
copyright (c) 2009-2021 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 6.2.3
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled

**Comment by ptilopteri** [comment] 2021-03-06 15:45
fwiw, doesn't crash for me on openSUSE Tumbleweed
openSUSE Tumbleweed 20210302
NVIDIA GF106 [GeForce GTS 450], 390.138
darktable 3.5.0+1344~g597a63805
bit depth is 64 bit
normal build
SSE2 optimized codepath enabled
OpenMP support enabled
OpenCL support enabled
Lua support enabled, API version 6.1.0
Colord support enabled
gPhoto2 support enabled
GraphicsMagick support enabled
ImageMagick support disabled
OpenEXR support enabled
OpenCL on
i7 12-core 36GB
kernel 5.10.16-1-default

**Comment by jade-nl** [comment] 2021-03-06 16:07
Just to make sure:

* got a fresh clone,
* build using gcc,
* build using clang

Doesn't make a difference, still segfaults on my side of things.

**Comment by TurboGit** [comment] 2021-03-06 16:14
Can you remove (and backup) your darktablerc and try again?

If it doesn't crash, please attach your darktablerc here.

All good on my side, but the commit you are referencing is having some part that we wanted to test which seems indeed to make trouble :)

**Comment by jade-nl** [comment] 2021-03-06 16:23
Moving darktablerc out of the way does prevent the segfault.

Not sure if I (and possible others) am happy having to reconfigure everything though.....

Any idea what the offending line(s) might be?

**Comment by TurboGit** [comment] 2021-03-06 16:28
Thanks. Can you in src/libs/export.c on the line: 

`+#if 1  //TODO: this code needs careful testing before removing the old code in the 'else' branch`

Replace the 1 by a 0 ?

**Comment by TurboGit** [comment] 2021-03-06 16:30
Do you have some Lua export modules ?

I cannot reproduce even with your darktablerc.

**Comment by jade-nl** [comment] 2021-03-06 16:34
Changed the line you pointed out and started the build process again.


Build stops with this error:

```
[ 59%] Built target collect
/home/jade/.local/git/darktable/src/libs/export.c:1056:13: error: '_destroy_child' defined but not used [-Werror=unused-function]
 static void _destroy_child(GtkWidget *widget, gpointer data)
```

Full build log [dt.build.2021.03.06.1729.log](https://github.com/darktable-org/darktable/files/6095688/dt.build.2021.03.06.1729.log)

**Comment by jade-nl** [comment] 2021-03-06 16:39
These are in my luarc file:

```
require "contrib/HDRMerge"
require "contrib/enfuseAdvanced"
require "contrib/gimp"
require "contrib/hugin"
require "contrib/rename-tags"
require "official/delete_long_tags"
```

**Comment by jade-nl** [comment] 2021-03-06 16:42
@TurboGit 

I just restored the *+#if 1 //TODO: this* line, removed luarc and rebuild darktable: No crashes/segfaults.

**Comment by jade-nl** [comment] 2021-03-06 16:50
These entries are safe:

```
require "contrib/rename-tags"
require "official/delete_long_tags"
```

The other 4 cause a segfault.

**Comment by TurboGit** [comment] 2021-03-06 17:05
Because the 4 others are export Lua modules.

**Comment by ralfbrown** [comment] 2021-03-06 17:08
> ```
> /home/jade/.local/git/darktable/src/libs/export.c:1056:13: error: '_destroy_child' defined but not used [-Werror=unused-function]
> ```

You would need to surround the _destroy_child function with `#if 0` and `#endif` for a succesful compile with `#if 0 //TODO`.  Although you narrowed the issue down to four Lua plugins, it still sounds like an interaction between something in those files and the change in the C code.

**Comment by TurboGit** [comment] 2021-03-06 17:56
Should be fixed in master. Can you double check all is good on your side?

**Closed** 2021-03-06 17:55 UTC
Labels: bug: pending, priority: high, reproduce: random, understood: incomplete

**Comment by jade-nl** [comment] 2021-03-06 18:04
That fixed the problem, thanks!
