### ISSUE TITLE
Crash while studying preferences shortcuts!

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#11595] opened 2022-04-22 10:48 UTC
I was just looking at Preferences, Shortcuts when it suddenly crashed

Platform
darktable version : 3.9.0+1244~gfe1008608-dirty
OS : Win10 19042.1288
Memory : 32 GB
Graphics card : Gigabyte GeForce RTX 2070 SUPER OC 3X
Graphics driver : 30.0.14.9613
OpenCL installed : yes
OpenCL activated : yes

[darktable_bt_W1P6K1.txt](https://github.com/darktable-org/darktable/files/8540228/darktable_bt_W1P6K1.txt)

**Comment by gi-man** [comment] 2022-04-22 11:09
What is the source of this windows build? (Eg. -dirty)

**Comment by bengtfalke** [comment] 2022-04-22 11:30
Nigthly builds:
https://github.com/darktable-org/darktable/actions/workflows/nightly.yml

**Comment by kmilos** [comment] 2022-04-22 12:56
> What is the source of this windows build? (Eg. -dirty)

Yeah, no idea why the CI generates the -dirty flag... Maybe [actions/checkout](https://github.com/darktable-org/darktable/runs/6104393157?check_suite_focus=true#step:3:1) is somehow different to what we usually do on local machines?

Sorry for the off-topic...

**Comment by Nilvus** [comment] 2022-06-24 19:18
@bengtfalke: as master had quite a lot of commits since your issue and never reproduced (on Linux), I close this. If you reproduce, ping me. Or wait to see/test 4.0 which will be out in about 10 days.

**Closed by Nilvus** 2022-06-24 19:18 UTC
