### ISSUE TITLE
enlarge canvas module don´t recognize the image orientation.

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#16051] opened 2024-01-07 00:00 UTC
### Describe the bug

First many thanks to @TurboGit and the other developers involved in this module enlarge canvas #a3c68d6. It is very nice the addition of it to the program.

I don't know if this behavior would classify as a bug, as I don't know if this happens only with Fuji files or with others as well.

When taking a picture with the camera in vertical position and importing it to darktable, if the automatic orientation is used, which displays the image vertically, when the enlarge canvas module is activated, it does not recognize that the image has been rotated with the orientation module before, and the slider layout is not correct as shown in the image.

### Steps to reproduce

![Screenshot from 2024-01-06 18-38-52](https://github.com/darktable-org/darktable/assets/67672868/36a0a977-5929-4bed-b21d-5d2196c45f4f)

### Where did you obtain darktable from?

OBS

### darktable version

4.7.0~git178.50ebd2fd-11134.1

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 37

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment] 2024-01-07 03:32
Actually, since Orientation is above Enlarge in your screenshot, it is being applied *after* enlarging the canvas.  So the canvas gets enlarged and then rotated.  Unexpected behavior for sure, but not actually a bug - remember that (unlike a pixel-based editor) operations are applied in pixelpipe order, not in the order in which you change settings.

@TurboGit would it make sense to move the new iop's default position after Orientation?  That would eliminate the unexpected behavior by putting it after both modules which perform image rotations.

**Comment by difrkaguilar** [comment] 2024-01-07 04:15
> Actually, since Orientation is above Enlarge in your screenshot, it is being applied _after_ enlarging the canvas. So the canvas gets enlarged and then rotated.

That's right the orientation module must be first.

**Comment by TurboGit** [comment] 2024-01-07 07:26
Makes sense, will do the change today.

**Comment by TurboGit** [comment] 2024-01-07 14:42
Should be fixed!

**Closed** 2024-01-07 14:42 UTC
Labels: scope: UI

**Comment by dtrtuser** [comment] 2024-01-09 07:25
Same issue with crop: if canvas is created and crop is not perfectly centered, then right/left and/or top/bottom border are no longer proportional to the percentages entered in the enlarge canvas module. So I would suggest that canvas module should come after crop too.

**Comment by TurboGit** [comment] 2024-01-09 10:11
> So I would suggest that canvas module should come after crop too.

No possible otherwise it comes after Retouch & Liquify and so you won't be able to fill the new content with those modules.
