### ISSUE TITLE
crashing when dragging around in light tables zoomable layout view

### ISSUE THREAD

**Issue by emko** [darktable-org/darktable#13165] opened 2022-12-19 00:30 UTC
When using the zoomable layout view in lighttable it will randomly crash darktable.

**To Reproduce**
go to lighttable and switch to zoomable view layout, drag the view up, this usually causes it to crash

https://user-images.githubusercontent.com/1070310/208330940-7fb69781-b02a-41cf-9e8c-af9e335f3471.mp4

**Platform**
* darktable version : 4.3.0+3~gd1c663b66
* Linux - Distro    : Fedora 37
* Memory            : 32gb
* Graphics card     :  rtx3080
* Graphics driver   : 525
* OpenCL installed  :  yes
* OpenCL activated  : yes
* Xorg              : yes
* Desktop           :  gnome
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

back traces 
```
#0  0x00007ffff201e2ee in __GI___libc_free (mem=mem@entry=0x1) at malloc.c:3362
#1  0x00007ffff4f1e8cd in g_free (mem=0x1) at ../glib/gmem.c:229
#2  0x00007ffff4e758d9 in g_closure_unref (closure=0x353c310) at ../gobject/gclosure.c:631
#3  0x00007ffff4e8a1e1 in handler_unref_R.part.0.lto_priv.0 (signal_id=<optimized out>, instance=instance@entry=0x553840, handler=0x4d8b140) at ../gobject/gsignal.c:771
#4  0x00007ffff4e8a53b in handler_unref_R (handler=<optimized out>, instance=0x553840, signal_id=<optimized out>) at ../gobject/gsignal.c:728
#5  handler_match_free1_R (instance=0x553840, node=0x70d7da0) at ../gobject/gsignal.c:595
#6  signal_handlers_foreach_matched_unlocked_R
    (instance=instance@entry=0x553840, mask=mask@entry=(G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA), signal_id=signal_id@entry=0, detail=detail@entry=0, closure=closure@entry=0x0, func=func@entry=0x7ffff7c6f1a0 <_dt_collection_changed_callback>, data=0x65fea50, callback=0x7ffff4e91e20 <signal_handler_disconnect_unlocked>) at ../gobject/gsignal.c:2925
#7  0x00007ffff4e8d28b in g_signal_handlers_disconnect_matched
    (instance=0x553840, mask=mask@entry=(G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA), signal_id=signal_id@entry=0, detail=detail@entry=0, closure=closure@entry=0x0, func=func@entry=0x7ffff7c6f1a0 <_dt_collection_changed_callback>, data=0x65fea50) at ../gobject/gsignal.c:3067
#8  0x00007ffff7b8b00e in dt_control_signal_disconnect (ctlsig=0x6ff900, cb=cb@entry=0x7ffff7c6f1a0 <_dt_collection_changed_callback>, user_data=user_data@entry=0x65fea50)
    at /home/emincavalic/Documents/Projects/darktable/src/control/signal.c:405
#9  0x00007ffff7c6ef6d in dt_thumbnail_destroy (thumb=thumb@entry=0x65fea50) at /home/emincavalic/Documents/Projects/darktable/src/dtgtk/thumbnail.c:1573
#10 0x00007ffff7c7489c in _thumbs_remove_unneeded (table=table@entry=0x326ad90) at /home/emincavalic/Documents/Projects/darktable/src/dtgtk/thumbtable.c:474
#11 0x00007ffff7c7768a in _move (table=table@entry=0x326ad90, x=<optimized out>, y=<optimized out>, clamp=clamp@entry=1) at /home/emincavalic/Documents/Projects/darktable/src/dtgtk/thumbtable.c:713
#12 0x00007ffff7c77aac in _event_motion_notify (widget=widget@entry=0x31fc150, event=0x9424c60, user_data=0x326ad90) at /home/emincavalic/Documents/Projects/darktable/src/dtgtk/thumbtable.c:1146
#13 0x00007ffff4699c57 in _gtk_marshal_BOOLEAN__BOXED
    (closure=0x3274b00, return_value=0x7fffffffd7d0, n_param_values=<optimized out>, param_values=0x7fffffffd830, invocation_hint=<optimized out>, marshal_data=<optimized out>) at gtk/gtkmarshalers.c:84
#14 0x00007ffff4e75fc0 in g_closure_invoke (closure=0x3274b00, return_value=0x7fffffffd7d0, n_param_values=2, param_values=0x7fffffffd830, invocation_hint=0x7fffffffd7b0) at ../gobject/gclosure.c:832
#15 0x00007ffff4ea3d86 in signal_emit_unlocked_R.isra.0
    (node=<optimized

https://user-images.githubusercontent.com/1070310/208330908-bb627fd6-c9c4-4d87-b9d1-9b7ff51861dc.mp4

 out>, detail=detail@entry=0, instance=instance@entry=0x31fc150, emission_return=emission_return@entry=0x7fffffffd940, instance_and_params=instance_and_params@entry=0x7fffffffd830)
    at ../gobject/gsignal.c:3796
#16 0x00007ffff4e92e16 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd9f0) at ../gobject/gsignal.c:3559
#17 0x00007ffff4e93633 in g_signal_emit (instance=instance@entry=0x31fc150, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
#18 0x00007ffff497b494 in gtk_widget_event_internal.part.0.lto_priv.0 (widget=0x31fc150, event=0x9424c60) at ../gtk/gtkwidget.c:7812
#19 0x00007ffff480cd7e in propagate_event_up (topmost=<optimized out>, event=<optimized out>, widget=0x31fc150) at ../gtk/gtkmain.c:2588
#20 propagate_event (widget=widget@entry=0x31fc150, event=event@entry=0x9424c60, captured=captured@entry=0, topmost=topmost@entry=0x0) at ../gtk/gtkmain.c:2691
#21 0x00007ffff480cea0 in gtk_propagate_event (widget=widget@entry=0x31fc150, event=event@entry=0x9424c60) at ../gtk/gtkmain.c:2725
#22 0x00007ffff480daf1 in gtk_main_do_event (event=<optimized out>) at ../gtk/gtkmain.c:1921
#23 gtk_main_do_event (event=<optimized out>) at ../gtk/gtkmain.c:1691
#24 0x00007ffff4539583 in _gdk_event_emit (event=0x9424c60) at ../gdk/gdkevents.c:73
#25 _gdk_event_emit (event=0x9424c60) at ../gdk/gdkevents.c:67
#26 0x00007ffff458c876 in gdk_event_source_dispatch.lto_priv () at ../gdk/x11/gdkeventsource.c:354
#27 0x00007ffff4f19cbf in g_main_dispatch (context=0x4ac790) at ../glib/gmain.c:3444
#28 g_main_context_dispatch (context=0x4ac790) at ../glib/gmain.c:4162
#29 0x00007ffff4f6f598 in g_main_context_iterate.constprop.0 (context=0x4ac790, block=1, dispatch=1, self=<optimized out>) at ../glib/gmain.c:4238
#30 0x00007ffff4f1928f in g_main_loop_run (loop=0x3d7f050) at ../glib/gmain.c:4438
#31 0x00007ffff480971d in gtk_main () at ../gtk/gtkmain.c:1329
#32 0x00007ffff7c8afc9 in dt_gui_gtk_run (gui=<optimized out>) at /home/emincavalic/Documents/Projects/darktable/src/gui/gtk.c:1278
#33 0x0000000000401090 in main (argc=<optimized out>, argv=<optimized out>) at /home/emincavalic/Documents/Projects/darktable/src/main.c:94
```

```

Thread 1 "darktable" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	     return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
Missing separate debuginfos, use: dnf debuginfo-install xorg-x11-drv-nvidia-cuda-libs-525.60.11-1.fc37.x86_64
(gdb) backtrace
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff200fee3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff1fbfaa6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff1fa97fc in __GI_abort () at abort.c:79
#4  0x00007ffff20040ae in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff211d465 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007ffff2019bbc in malloc_printerr (str=str@entry=0x7ffff2120018 "free(): invalid next size (fast)") at malloc.c:5660
#6  0x00007ffff201bada in _int_free (av=0x7ffff2156c80 <main_arena>, p=0x4c1c0f0, have_lock=0) at malloc.c:4518
#7  0x00007ffff201e343 in __GI___libc_free (mem=mem@entry=0x4c1c100) at malloc.c:3385
#8  0x00007ffff4f1e8cd in g_free (mem=0x4c1c100) at ../glib/gmem.c:229
#9  0x00007ffff4efb0e0 in g_data_set_internal (datalist=0x56cacc0, key_id=<optimized out>, new_data=<optimized out>, new_destroy_func=<optimized out>, dataset=0x0) at ../glib/gdataset.c:382
#10 0x00007ffff497473d in gtk_widget_set_parent_window (widget=0x56cacb0, parent_window=0x0) at ../gtk/gtkwidget.c:10725
#11 0x00007ffff4843fee in gtk_overlay_unrealize (widget=0x4db5cb0) at ../gtk/gtkoverlay.c:445
#12 0x00007ffff4e93554 in _g_closure_invoke_va (param_types=<optimized out>, n_params=<optimized out>, args=0x7fffffffd130, instance=<optimized out>, return_value=<optimized out>, closure=0x5a5190)
    at ../gobject/gclosure.c:895
#13 g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd130) at ../gobject/gsignal.c:3456
#14 0x00007ffff4e93633 in g_signal_emit (instance=instance@entry=0x4db5cb0, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
#15 0x00007ffff496d186 in gtk_widget_unrealize (widget=0x4db5cb0) at ../gtk/gtkwidget.c:5582
#16 0x00007ffff496d37f in gtk_widget_unparent (widget=0x4db5cb0) at ../gtk/gtkwidget.c:4674
#17 0x00007ffff47fa442 in gtk_layout_remove (container=<optimized out>, widget=widget@entry=0x4db5cb0) at ../gtk/gtklayout.c:1078
#18 0x00007ffff4e74a65 in g_cclosure_marshal_VOID__OBJECTv
    (closure=0x58b460, return_value=<optimized out>, instance=0x322e150, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x58b490) at ../gobject/gmarshal.c:1910
#19 0x00007ffff4e93554 in _g_closure_invoke_va (param_types=<optimized out>, n_params=<optimized out>, args=0x7fffffffd480, instance=<optimized out>, return_value=<optimized out>, closure=0x58b460)
    at ../gobject/gclosure.c:895
#20 g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd480) at ../gobject/gsignal.c:3456
#21 0x00007ffff4e93633 in g_signal_emit (instance=instance@entry=0x322e150, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
#22 0x00007ffff47267c5 in gtk_container_remove (container=0x322e150, widget=0x4db5cb0) at ../gtk/gtkcontainer.c:1907
#23 0x00007ffff7c74894 in _thumbs_remove_unneeded (table=table@entry=0x60f610) at /home/emincavalic/Documents/Projects/darktable/src/dtgtk/thumbtable.c:473
#24 0x00007ffff7c7768a in _move (table=table@entry=0x60f610, x=<optimized out>, y=<optimized out>, clamp=clamp@entry=1) at /home/emincavalic/Documents/Projects/darktable/src/dtgtk/thumbtable.c:713
#25 0x00007ffff7c77aac in _event_motion_notify (widget=widget@entry=0x322e150, event=0x53578e0, user_data=0x60f610) at /home/emincavalic/Documents/Projects/darktable/src/dtgtk/thumbtable.c:1146
#26 0x00007ffff4699c57 in _gtk_marshal_BOOLEAN__BOXED
    (closure=0x3263f00, return_value=0x7fffffffd7d0, n_param_values=<optimized out>, param_values=0x7fffffffd830, invocation_hint=<optimized out>, marshal_data=<optimized out>) at gtk/gtkmarshalers.c:84
#27 0x00007ffff4e75fc0 in g_closure_invoke (closure=0x3263f00, return_value=0x7fffffffd7d0, n_param_values=2, param_values=0x7fffffffd830, invocation_hint=0x7fffffffd7b0) at ../gobject/gclosure.c:832
#28 0x00007ffff4ea3d86 in signal_emit_unlocked_R.isra.0
    (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0x322e150, emission_return=emission_return@entry=0x7fffffffd940, instance_and_params=instance_and_params@entry=0x7fffffffd830)
    at ../gobject/gsignal.c:3796
#29 0x00007ffff4e92e16 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd9f0) at ../gobject/gsignal.c:3559
#30 0x00007ffff4e93633 in g_signal_emit (instance=instance@entry=0x322e150, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
#31 0x00007ffff497b494 in gtk_widget_event_internal.part.0.lto_priv.0 (widget=0x322e150, event=0x53578e0) at ../gtk/gtkwidget.c:7812
#32 0x00007ffff480cd7e in propagate_event_up (topmost=<optimized out>, event=<optimized out>, widget=0x322e150) at ../gtk/gtkmain.c:2588
#33 propagate_event (widget=widget@entry=0x4c027b0, event=event@entry=0x53578e0, captured=captured@entry=0, topmost=topmost@entry=0x0) at ../gtk/gtkmain.c:2691
#34 0x00007ffff480cea0 in gtk_propagate_event (widget=widget@entry=0x4c027b0, event=event@entry=0x53578e0) at ../gtk/gtkmain.c:2725
#35 0x00007ffff480daf1 in gtk_main_do_event (event=<optimized out>) at ../gtk/gtkmain.c:1921
#36 gtk_main_do_event (event=<optimized out>) at ../gtk/gtkmain.c:1691
#37 0x00007ffff4539583 in _gdk_event_emit (event=0x53578e0) at ../gdk/gdkevents.c:73
#38 _gdk_event_emit (event=0x53578e0) at ../gdk/gdkevents.c:67
#39 0x00007ffff458c876 in gdk_event_source_dispatch.lto_priv () at ../gdk/x11/gdkeventsource.c:354
#40 0x00007ffff4f19cbf in g_main_dispatch (context=0x4ac790) at ../glib/gmain.c:3444
#41 g_main_context_dispatch (context=0x4ac790) at ../glib/gmain.c:4162
#42 0x00007ffff4f6f598 in g_main_context_iterate.constprop.0 (context=0x4ac790, block=1, dispatch=1, self=<optimized out>) at ../glib/gmain.c:4238
#43 0x00007ffff4f1928f in g_main_loop_run (loop=0x45b5fe0) at ../glib/gmain.c:4438
#44 0x00007ffff480971d in gtk_main () at ../gtk/gtkmain.c:1329
#45 0x00007ffff7c8afc9 in dt_gui_gtk_run (gui=<optimized out>) at /home/emincavalic/Documents/Projects/darktable/src/gui/gtk.c:1278
#46 0x0000000000401090 in main (argc=<optimized out>, argv=<optimized out>) at /home/emincavalic/Documents/Projects/darktable/src/main.c:94
```

**Comment by gi-man** [comment] 2022-12-19 01:10
Please use the entire template to provide all the information that can help reproduce. Mainly: OpenCL, card, drivers, X11 or Wayland? Can you also describe your resources settings?

I cannot reproduce on Fedora 37 KDE X11, Nvidia 525.60.11   4.1.0~git1240.d1c663b6

**Comment by jenshannoschwalm** [comment] 2023-07-19 05:09
@emko is this still valid or can we close the issue?

**Comment by emko** [comment] 2023-07-19 19:15
just tested latest master still crashing

**Comment by jenshannoschwalm** [comment] 2023-07-20 05:24
Can't reproduce here, F38 and nvidia too.

**Comment by emko** [comment] 2023-07-20 06:46
> Can't reproduce here, F38 and nvidia too.

is there anything i can do ?

**Comment by emko** [comment] 2023-07-20 06:55
@jenshannoschwalm  if you have a chance could you try make the dt window kind of small, start dragging and drag your mouse all the way outside of the dt app window if you go around the bottom left corner this will cause a crash for me 100% of the time on the two machines i have

**Comment by jenshannoschwalm** [comment] 2023-07-20 15:22
Yes i could reproduce the crash. @AlicVB your baby ?

**Comment by jenshannoschwalm** [comment] 2023-12-07 15:50
@emko, could you try again? I tested thoroughly and couldn't reproduce any longer - there have been a number of related fixes.

**Comment by AlicVB** [comment] 2023-12-07 18:09
oops... forgot to close this one... It should be fixed in master, so I'm closing.
as usual, if the issue is still present on your side with git master (or the next dt version) feel free to reopen.

**Closed by AlicVB** 2023-12-07 18:09 UTC
Labels: priority: low, reproduce: confirmed, bug: pending, no-issue-activity
