### ISSUE TITLE
Add a cache buffer module

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#10884] opened 2022-01-14 01:50 UTC
The beginning of the pixelpipe is made of heavy technical modules that are better processed 1:1 but don't need to be recomputed often:
 * hot pixels,
 * highlights reconstruction,
 * demosaicing,
 * denoising.

Unfortunately, high-quality numerical methods to achieve these tasks are increasingly computationaly expensive. 

I propose to add a utility module after the last of these module that would cache the 1:1 output and serve it rescaled to the pixelpipe later. Downscaling to pipeline resolution would be made in there, everything before would be kept 1:1.

This module would have an "interactive" mode, recomputing and caching early pipeline (before itself) when any of the params of these earlier modules are changed, or a "manual" mode, updating the cache only upon request to avoid massive lags.

It could even cache its output in a shared buffer between preview and full pixel pipe, perhaps even for the export pipe.

It could also be movable in the pipeline, such that people could put it after diffuse and sharpen before they carry on with artistic retouch.

There is a precedent (Harry Durgin) of collapsing the early pipeline into TIFF and carrying on with this raster file for the sake of responsiveness.

**Comment by parafin** [comment] 2022-01-14 07:29
This reads as a crutch for existing pixelpipe cache. I never really got the hang of how it works to be honest. I guess this PR highlights existing cache shortcomings. My question is wouldn’t it be better to “fix” existing infrastructure instead of adding hacks like this? Adding manual cache control feels a lot like exposing unnecessary technical details of implementation instead of making them work correctly on their own… If we feel that nontheless this PR is a way forward, then another question would be do we really require two cache systems working in parallel? Maybe get rid of old one?

**Comment by ralfbrown** [comment] 2022-01-14 13:38
@phweyland That's pretty much how the existing pixpipe cache works. (Hash of pipe up to each module, when the pipe runs we back up from the output of the last module until we get a matching hash which is already cached and then work forward from there, caching results as we go.)

The main problem with the existing cache is that it's too small (just eight entries, increased from five about a year ago).  And **that** is the result of not tracking how much memory is used by cached buffers, so we need to be very conservative in its *fixed* size.

The proper fix is to let it cache as many buffers as there is available memory.  To do so, we also need to have the iops consistently allocate buffers through a central function instead of directly calling dt_alloc_align* so that the cache knows when it needs to drop entries in favor of a memory-hungry algorithm.

**Comment by phweyland** [comment] 2022-01-14 14:07
@ralfbrown I was not aware of this pixpipe cache, sorry.
But is there any way to keep only one cache, the last of the stable chunk of modules ?

**Comment by ralfbrown** [comment] 2022-01-14 18:11
If the pipe is sufficiently short, that would happen automatically (everything before the module being changed stays the same and therefore in cache).  The problem is that the pipe is growing ever longer, so it's ever more likely that the earliest modules get dropped by the time the pipe finishes running, resulting in a complete recompute when changing settings on any except the last few modules in the pipe.  There is provision for "freezing" a cache entry, but it doesn't work very well, in part due to the small size of the cache.

One quick (partial) fix may be to scale the cache size by the host memory limit -- the more mem dt is allowed to use, the more we can spare for caching the preview and full pixpipes.

**Comment by phweyland** [comment] 2022-01-14 18:39
Thanks for the explanation, I think I got it.
Therefore it may be useful to let the user qualify the last stable module manually, at the cost of recomputing all the pipe if he changes anything before...

**Comment by TurboGit** [comment] 2022-01-14 18:52
I'm no expert on the cache implementation but for sure the idea behind it is to recompute only when necessary. So I agree with @parafin, if there is a bug better fix it than adding another level of complexity/hack.

**Comment by ralfbrown** [comment] 2022-01-14 23:17
Not so much a bug as an inadequate implementation.
But that is better addressed by upgrading the implementation than by trying to layer something else on top.

**Comment by gi-man** [comment] 2022-01-17 22:28
> One quick (partial) fix may be to scale the cache size by the host memory limit -- the more mem dt is allowed to use, the more we can spare for caching the preview and full pixpipes.

I think this quick fix is worth it. This user had issues with export and memory. https://discuss.pixls.us/t/slideshow-and-tiling-on-a-mac-diffuse-and-sharpen-extremely-slow/28906/36?u=g-man

I could see the value in having a limit, but why it is 1500? Maybe a percent of total available system memory would be better (eg. use up to 80%), to allow for other processes.

**Comment by ralfbrown** [comment] 2022-01-18 02:53
Recent versions of dt (3.4+?) **do** adapt the host memory limit, but only when started without a darktablerc.  So if someone has been upgrading an installation for a while, the old limit will remain in the config.

**Comment by gi-man** [comment] 2022-01-18 03:28
Hmm, I see. I've done upgrades instead of clean installs, so that could explain the 1500 limit. 

FYI, the current manual says the default should be 1500. https://docs.darktable.org/usermanual/3.8/en/preferences-settings/processing/#cpu--gpu--memory

**Comment by johnny-bit** [comment] 2022-01-18 10:03
actually - the change was made in PR https://github.com/darktable-org/darktable/pull/9764 (so 3.8) and I believe changing DT_CURRENT_PERFORMANCE_CONFIGURE_VERSION was enough to trigger recalculation...

As for main issue - as @ralfbrown says it's a matter of pixelpipe cache implementation, and it's a big one. There are like 5 cached pixelpipes, all having separate cache line with different number of cached entries (eg 8 is only for full & preview. preview2 has 5, thumbnail & export have 2...)... Blah... Having central dynamic cache growing up to host limit would mean that dt could benefit a lot more from lots of ram making it more responsive... (At this point I must note that this topic is waaay above my skill level at the moment so I might be wrong but my experience tells me @ralfbrown is 100% correct here)

**Comment by jenshannoschwalm** [comment] 2022-01-18 12:15
> Having central dynamic cache growing up to host limit would mean that dt could benefit a lot more from lots of ram making it more responsive

Sure - increasing cache size would help. The amount of "help" is not so easy to estimatate, there is also the amount of ram available for tiling to concider. And the requirement for tiling ram depends on your gpu. Number of cpu cores also affects this depending on the specific module. So - not an easy task at all.

What triggers recalculations of cache data (at least here) most likely? Rescaling in almost 99% i would say, or in other words the roi concept.

And that leads directly to the initial problem / idea @aurelienpierre mentioned. Some early-in-the-pipeline technical modules would like to go 1:1 for best results and would only very rarely require recalculations at all. The most obvious atm is the laplacian guided highlights reconstruction, very cpu hungry, very good results but zooming in/out can be somewhat of a nightmare. (The usual trick - switch it on later wouldn't work for this module as editing other stuff will very likely depend on it's output).

So in general, processing data 1:1 until and including demosaic and mark that in cache as "not to be cleared from cache" until parameters in the early moduled had changed would make a lot of sense to me.

**Comment by elstoc** [comment] 2022-01-18 12:26
Would that make interactivity problematic when adjusting the parameters in those early modules?

**Comment by jenshannoschwalm** [comment] 2022-01-18 13:24
> Would that make interactivity problematic when adjusting the parameters in those early modules?

It should not :-) Changing a parameter would impair performance if we do 1:1 processing of those modules. But only once.

**Comment by elstoc** [comment] 2022-01-18 13:32
If a user is dragging a slider to find a good value though, it might be less interactive during that operation. Just something to consider.

**Comment by ralfbrown** [comment] 2022-01-18 15:22
When I was thinking about the whole pixpipe caching issue about a year ago, my idea was to allow multiple different areas to be cached for the same parameter hash, so zooming in or panning could benefit from just copying a portion of the cached buffer.  That of course works best if what is cached is 1:1 of the full image, but we don't want to run 1:1 all the time.  So one possibility is to run just the ROI at reduced resolution as now for as long as the user is actively changing a parameter, then fire off and cache a full-res recalculation when the UI goes idle.  That will require some changes to the pixpipe code as well....

**Comment by ralfbrown** [comment] 2023-02-09 06:47
Can we close this as addressed by the recent pixpipe cache reimplementation?

**Closed** 2023-02-09 10:19 UTC
Labels: no-issue-activity
