### ISSUE TITLE
White Balance Error - Darktable 4.4 (from source) and Hasselblad X2D

### ISSUE THREAD

**Issue by kkempter-getswift** [darktable-org/darktable#14744] opened 2023-06-22 01:07 UTC
### Describe the bug

I go to the white balance module, and click the eyedropper to get white balance from the image and I see this:

    31.5276 Trouble: [color calibration] white balance error (B0000213.3FR 42)
    33.3321 Trouble: [color calibration] white balance error (B0000213.3FR 42)
    34.6495 Trouble: [color calibration] white balance error (B0000213.3FR 42)
    34.6858 Trouble: [color calibration] white balance error (B0000213.3FR 42)
    34.6858 Trouble: [white balance] double application of white balance (B0000213.3FR 42)

### Steps to reproduce

1. go to white balance module
2. click the eyedropper
   for a .3FR image from a Hasselblad X2D

### Expected behavior

Not throw this error

### Where did you install darktable from?

darktable.org

### darktable version

darktable-4.4.0.tar.xz

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Describe your system?

LG gram (2022) 17Z90Q Ultra Lightweight Laptop, 17" (2560 x 1600) IPS Display, Intel Evo 12th Gen i7 1260P Processor, 32GB LPDDR5, 2TB NVMe SSD, FHD Webcam, WiFi 6E, Thunderbolt 4, Windows 11, Black

Intel Evo Platform Powered by 12th Gen Intel Core i7 Processor and Iris Xe Graphics

### Are you using OpenCL GPU in darktable?

I dont know

### If yes, what is the GPU card and driver?

 Iris Xe Graphics.

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

earlier versions did not support this camera's .3FR RAW files

**Comment by gi-man** [comment] 2023-06-22 18:21
Duplicate of https://github.com/darktable-org/rawspeed/pull/463#issuecomment-1535558878

**Comment by ralfbrown** [comment] 2023-07-10 19:20
Using anything but the reference (D65) white balance in the white balance module is expected and intended to produce those warnings.  Color calibration assumes a preliminary adjustment to D65 which it then adapts to the actual illuminant.

If you use the eye dropper in the white balance module, that is extremely unlikely to result in coefficients which match D65, so you'll get the warnings.

**Closed by ralfbrown** 2023-07-10 19:20 UTC
