### ISSUE TITLE
crashes when loading .nef files on windows 11

### ISSUE THREAD

**Issue by smneff** [darktable-org/darktable#17471] opened 2024-09-14 07:37 UTC
### Describe the bug

Dowloaded a picture from a trusted dropbox link where I was able to edit a jpeg file no problem. But when I import a nef file it crashes.  Then when i open darktable back up the nef file is in the main window i guess you would call it but when i click on it to load it crashes again.  There is no report in the event viewer or when I go through the command prompt commands to get one that way.  Any help would be greatly appreciated

### Steps to reproduce

![Screenshot (10)](https://github.com/user-attachments/assets/f6e1c968-568f-4358-9320-786e84d7444d)

This is what the screen shows then I click on the photo it says its loading and then it crashes.

I looked in all the obvious places for a log or crash report to no avail.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Windows

### What is the version of your OS?

windows 11

### Are you using OpenCL GPU in darktable?

None

**Comment by victoryforce** [comment] 2024-09-14 08:21
@smneff You forgot to provide the file on which darktable crashes.

**Comment by smneff** [comment] 2024-09-15 01:18
it's any .nef file.  I am unable to upload the file since it is unsupported in github.  is there another way you can help since it is so general?

**Comment by ralfbrown** [comment] 2024-09-15 02:50
You can put the file in a zip archive.  It may even be enough to just add a .txt extension to the filename to make Github accept it for upload.

**Comment by smneff** [comment] 2024-09-15 03:41
i zipped file along with the accompanying .xmp file

[
[.nef.zip](https://github.com/user-attachments/files/17004498/default.nef.zip)
](url)

**Comment by ralfbrown** [comment] 2024-09-15 04:33
Image loads just fine with 4.8.1 on Linux using a fresh configuration directory.  So there's likely something specific to your setup causing issues.  Since your screenshot shows the Lua script installer, we can rule out any Lua scripts causing problems since you haven't installed any yet.

I'll need to ask our resident Windows experts to guide you through trying an import using a fresh configuration directory and enabling debug logging with "-d common".

**Comment by victoryforce** [comment] 2024-09-15 10:02
Likewise, the problem does not reproduce on my Windows 11 installation.

@smneff Please, do the following:
- Launch some command processor. It can be cmd, powershell, Windows Terminal (what you are more used to, it doesn't matter what exactly).
- Copy-paste the following command to it: 
```
"c:\Program Files\darktable\bin\darktable.exe" -d common --configdir %USERPROFILE%\Documents\test-config-dir
``` 
You can specify any path to the configuration folder that is convenient for you (it is better if it is a new folder, it can be deleted later). Quotation marks around the darktable.exe path are required.
- Launch this command and work with darktable until it crashes.
- Find debug log using info at https://www.darktable.org/about/faq/#faq-windows-logs and attach it here.

**Comment by ralfbrown** [comment] 2024-11-17 08:31
Closing since the problem could not be reproduced and OP has not responded in two months.

**Closed by ralfbrown** 2024-11-17 08:31 UTC
Labels: understood: unclear, reproduce: peculiar

**Comment by smphayward** [comment] 2025-02-11 14:57
One more quick update.

I found this:

https://github.com/darktable-org/darktable/issues/14731

So I tried loading darktable from the commandline with `--disable-opencl` and sure enough it works!

I was able to edit an entire photo with no issues.
