### ISSUE TITLE
Canon EOS R6 Mk II

### ISSUE THREAD

**Issue by martinma64** [darktable-org/darktable#14243] opened 2023-04-17 21:25 UTC
Hi,
I just uploaded a RAW Image to
https://raw.pixls.us/ !

**Comment by MStraeten** [comment] 2023-04-18 05:21
for canon r6 mll support the camera must be also supported by libraw (https://www.libraw.org/)

**Comment by kmilos** [comment] 2023-04-18 05:48
Duplicate of https://github.com/darktable-org/darktable/pull/13684

Please search before opening new issues.

**Closed** 2023-04-18 18:05 UTC
Labels: duplicate, scope: camera support

**Comment by mkubecek** [comment] 2023-04-19 06:22
> Hi, I just uploaded a RAW Image to https://raw.pixls.us/ !

So did I, back in February (a full set of 8 files). Unfortunately the site still does not show them and as one does not provide contact for feedback, I have no idea why. And I couldn't find any contact so I cannot ask either. So let's hope you will be more lucky.

> for canon r6 mll support the camera must be also supported by libraw

Looked into this too; the libraw update policy is to only provide new camera support in major releases which come once in a year and a half to two years. As 0.21 was released in December 2022, the best we can hope for is June 2024.

**Comment by MStraeten** [comment] 2023-04-19 06:25
or earlier since the dt team also includes snapshots if they included new cameras - so be patient ...
