### ISSUE TITLE
Importing files with special characters in the path

### ISSUE THREAD

**Issue by FilipJanasz** [darktable-org/darktable#9837] opened 2021-08-19 09:27 UTC
**Describe the bug/issue**
I've been importing my photo collection into Darktable and noticed that a lot of file will fail to load. Common pattern is that as soon as the file name / file path contains non-english characters (in this case polish letters such as "ą ę ś ć ż ź") the file will fail to load and throw "error loading file" prompt.

![darktable_error](https://user-images.githubusercontent.com/6803433/130044705-93f6b846-d933-4aaa-bdc6-78ef2d309bfd.png)

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Create a file with a special character in the name / file path (e.g. "ę.jpg")
2. Try importing into Darktable (version 3.6.0)

**Expected behavior**
File should be added to the library

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version: 3.6.0
* OS                : Win10 10.0.19043

 - Can you reproduce with another darktable version(s)? Haven't tried
![darktable_error](https://user-images.githubusercontent.com/6803433/130044705-93f6b846-d933-4aaa-bdc6-78ef2d309bfd.png)

**Comment by johnny-bit** [comment] 2021-08-19 10:36
Cześć Filip,

The problem is known and fixed in current master, the fix will be part of 3.6.1 release which is "coming soon". There's no workaround currently, but if you feel adventurous you can check eg "Windows insider" test releases of 3.7 (master) branch https://discuss.pixls.us/t/darktable-windows-insider-program-8-15/26454?u=johnny-bit that allows one testing of features comming in darktable 3.8 :)

Closing since the issue is fixed.

**Closed by johnny-bit** 2021-08-19 10:36 UTC
Labels: duplicate, scope: DAM, bug: fixed

**Comment by FilipJanasz** [comment] 2021-08-19 11:55
Cześć Hubert!

Thanks for fast reply, I'll try the insider branch.
