### ISSUE TITLE
Crop aspect ratio does not rotate correctly

### ISSUE THREAD

**Issue by Solarer** [darktable-org/darktable#9241] opened 2021-06-14 20:41 UTC
**Describe the bug/issue**
Crop ratio can be rotated (e.g. 3:2 landscape to 2:3 portrait) by clicking on the small rotating arrow in the crop module. Using this two times in a row does not return to the original ratio. After that the behavior stays normal.

Choosing original image (correct)
![image](https://user-images.githubusercontent.com/2805109/121955457-48640100-cd60-11eb-8ff1-0bea0d6ec094.png)

Rotating by 90° (correct but maybe should be centered?)
![image](https://user-images.githubusercontent.com/2805109/121955586-6e89a100-cd60-11eb-8e0d-db70753dbd7b.png)

Rotating once more by 90° (**wrong**, should look like first screenshot!)
![image](https://user-images.githubusercontent.com/2805109/121955764-a0026c80-cd60-11eb-8ded-f964dcbd52d5.png)

Rotating once more (from now on it iterates between screenshot 2 and 3 but we never reach stage 1)
![image](https://user-images.githubusercontent.com/2805109/121955715-9547d780-cd60-11eb-852f-abca30a9a3c9.png)

* darktable version : 3.5.0+2526~gb3a4335e57
* OS                : Manjaro Linux

**Comment by elstoc** [comment] 2021-06-14 21:02
As far as I recall crop & rotate has always worked this way and we just ported the existing functionality to crop. The way it works now is predictable, though it may not be what you want. Consider if you had started with a portrait crop - then it _would_ be consistent. What if you'd started with a landscape crop that was slightly less than the full image? How should it work then?

**Comment by Solarer** [comment] 2021-06-14 22:15
I just checked a portrait picture. It is working as I would expect there - so my complaint is only about landscape pictures.
If I open a portrait picture and rotate the aspect ratio twice I end up where I was.

If I started with a landscape crop that is a little smaller than the original image, I would expect to end up there again after rotating twice. That is already the case for portrait pictures.

**Comment by elstoc** [comment] 2021-06-14 22:23
It must be because it's trying to retain the width when changing ratio (which works ok for portrait). We could change it to try and detect the aspect ratio of the underlying image and retain the height for landscape images I suppose. I think it's a feature rather than a bug but sounds a reasonable thing to try and improve.

**Comment by Solarer** [comment] 2021-07-15 06:06
Still open

**Comment by johnny-bit** [comment] 2021-07-15 10:51
AFAIK @AlicVB is not avail to look at the issue so bot will say "no activity" at least once or twice ;)

**Comment by johnny-bit** [comment] 2021-07-20 14:28
re-looking at this - isn't this duplicate of #6979 since both modules share AR rotation code?

**Comment by elstoc** [comment] 2021-07-20 14:33
I don't _think_ so. This one is more about the size of the crop when changing between portrait and landscape, the other is about the ratio being incorrect after changing orientation.

**Closed** 2023-03-25 00:20 UTC
Labels: feature: enhancement, scope: UI, no-issue-activity
