### ISSUE TITLE
Fujifilm GFX100II Lighttable works but Darktable generates error when opening or does not render when opened

### ISSUE THREAD

**Issue by CaptainMorgan12** [darktable-org/darktable#16475] opened 2024-03-16 20:06 UTC
### Describe the bug

1. open image in darktable
2. observe error:

**failed to read camera white balance information from ####.RAF!**

`darktable count not load ####.RAF switching to lighttable
please check that the camera model that produced the image is supported in darktable ....... if you are sure that the camera model is supported, please consider opening an issue at ......`

gThumb can open the .RAF image though incorrectly rotated, RawTherapee has also trouble opening the image.

When using flatpak it does open the image in darktable but image is black and does not render properly see log below.

### Steps to reproduce

Image: RAW, Uncompressed, Output Depth (bit) 16bit, Auto White Balance "White Priority", Color Space sRGB, Adjust image settings for Clarity +2, Dynamic Range 400, Sharpness +2, Smooth Skin Effect Weak, Color Chrome Effect Weak, Image Size 4:3. 
Image Width 11808
Image Height 8754
Strip Offset 2048
Strip Byte Counts 206734464
WB GRB Levels Standard 302 341 907 17 302 581 530 21
WB GRB Levels Auto 302 489 648
WG GRB Levels 302 489 648

See above

### Expected behavior

should open image so i can edit the RAW image file

### Logfile | Screenshot | Screencast

Ubuntu DarkTable:

<pre>darktable -d perf
     2.0449 [_gamepad_open_devices] opened game controller &apos;Atari Xbox 360 Game Controller&apos;

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: GFileInfo created without standard::is-hidden

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: file ../../../gio/gfileinfo.c: line 1633 (g_file_info_get_is_hidden): should not be reached

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: GFileInfo created without standard::is-hidden

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: file ../../../gio/gfileinfo.c: line 1633 (g_file_info_get_is_hidden): should not be reached

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: GFileInfo created without standard::is-hidden

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: file ../../../gio/gfileinfo.c: line 1633 (g_file_info_get_is_hidden): should not be reached

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: GFileInfo created without standard::is-hidden

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: file ../../../gio/gfileinfo.c: line 1633 (g_file_info_get_is_hidden): should not be reached

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: GFileInfo created without standard::is-hidden

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: file ../../../gio/gfileinfo.c: line 1633 (g_file_info_get_is_hidden): should not be reached

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: GFileInfo created without standard::is-hidden

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: file ../../../gio/gfileinfo.c: line 1633 (g_file_info_get_is_hidden): should not be reached

(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:11.313</font>: GFileInfo created without standard::is-hidden
</pre>

......

<pre>(darktable:59214): GLib-GIO-<font color="#A347BA"><b>CRITICAL</b></font> **: <font color="#12488B">13:05:47.027</font>: file ../../../gio/gfileinfo.c: line 1633 (g_file_info_get_is_hidden): should not be reached
RawSpeed:Unable to find camera in database: &apos;FUJIFILM&apos; &apos;GFX100 II&apos; &apos;&apos;
Please consider providing samples on &lt;https://raw.pixls.us/&gt;, thanks!
    65.4783 [rawspeed] (DSCF0087.RAF) bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData*, const std::string&amp;, const std::string&amp;, const std::string&amp;), line 171: Camera &apos;FUJIFILM&apos; &apos;GFX100 II&apos;, mode &apos;&apos; not supported, and not allowed to guess. Sorry.
    65.4784 [libraw_open] extensions whitelist: `cr3&apos;
    65.4785 [dt_dev_load_raw] loading the image. took 0.194 secs (0.000 CPU)
    65.4801 [temperature] failed to read camera white balance information from `DSCF0087.RAF&apos;!
    66.0820 [temperature] `FUJIFILM GFX100 II&apos; color matrix not found for image
    66.0821 [temperature] failed to read camera white balance information from `DSCF0087.RAF&apos;!
    66.0824 [temperature] failed to read camera white balance information from `DSCF0087.RAF&apos;!
    66.1068 [colorin] could not find requested profile `standard color matrix&apos;!
    66.2853 [histogram] took 0.000 secs (0.000 CPU) scope draw
    66.3158 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.3802 [histogram] took 0.000 secs (0.000 CPU) scope draw
    66.3974 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.4522 [histogram] took 0.009 secs (0.000 CPU) scope draw
    66.4640 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.5043 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.5336 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.5755 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.6179 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.6469 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.6732 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.7046 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.7346 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.7642 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.7927 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.8212 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.8505 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.8789 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.9101 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.9389 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
    66.9688 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)

Flatpak DarkTable

<pre>flatpak run org.darktable.Darktable -d perf
darktable 4.6.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -&gt; 64 bit
  Debug                  -&gt; DISABLED
  SSE2 optimizations     -&gt; ENABLED
  OpenMP                 -&gt; ENABLED
  OpenCL                 -&gt; ENABLED
  Lua                    -&gt; ENABLED  - API version 9.2.0
  Colord                 -&gt; ENABLED
  gPhoto2                -&gt; ENABLED
  GMIC                   -&gt; ENABLED  - Compressed LUTs are supported
  GraphicsMagick         -&gt; ENABLED
  ImageMagick            -&gt; DISABLED
  libavif                -&gt; ENABLED
  libheif                -&gt; ENABLED
  libjxl                 -&gt; ENABLED
  OpenJPEG               -&gt; ENABLED
  OpenEXR                -&gt; ENABLED
  WebP                   -&gt; ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

Gtk-<font color="#26A269"><b>Message</b></font>: <font color="#12488B">13:20:42.236</font>: Failed to load module &quot;canberra-gtk-module&quot;
Gtk-<font color="#26A269"><b>Message</b></font>: <font color="#12488B">13:20:42.240</font>: Failed to load module &quot;canberra-gtk-module&quot;
     1.2856 [_gamepad_open_devices] opened game controller &apos;Atari Xbox 360 Game Controller&apos;
     3.6105 [dt_dev_load_raw] loading the image. took 0.581 secs (0.125 CPU)
     4.4100 [histogram] took 0.000 secs (0.000 CPU) scope draw
     4.4337 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
     4.5128 [dev_pixelpipe] took 0.000 secs (0.000 CPU) initing base buffer [full]
     4.5195 [histogram] took 0.000 secs (0.000 CPU) scope draw
     4.5715 [histogram] took 0.000 secs (0.000 CPU) scope draw
     4.5904 [dev_pixelpipe] took 0.078 secs (0.241 CPU) [full] processed `rawprepare&apos; on CPU, blended on CPU
     4.6638 [dev_pixelpipe] took 0.073 secs (0.101 CPU) [full] processed `temperature&apos; on CPU, blended on CPU
     6.6171 [dev_pixelpipe] took 1.953 secs (13.269 CPU) [full] processed `highlights&apos; on CPU, blended on CPU
     9.0274 [resample_plain] plan 0.001 secs (0.001 CPU) resample 1.107 secs (7.853 CPU)
     9.1381 [dev_pixelpipe] took 2.521 secs (15.802 CPU) [full] processed `demosaic&apos; on CPU, blended on CPU
     9.1435 [dev_pixelpipe] took 0.005 secs (0.019 CPU) [full] processed `flip&apos; on CPU, blended on CPU
     9.1451 [dev_pixelpipe] took 0.001 secs (0.004 CPU) [full] processed `exposure&apos; on CPU, blended on CPU
     9.1492 [dev_pixelpipe] took 0.004 secs (0.021 CPU) [full] processed `colorin&apos; on CPU, blended on CPU
     9.1533 [dt_ioppr_transform_image_colorspace] IOP_CS_LAB--&gt;IOP_CS_RGB took 0.004 secs (0.016 CPU) [channelmixerrgb]
     9.1759 [dev_pixelpipe] took 0.027 secs (0.129 CPU) [full] processed `channelmixerrgb&apos; on CPU, blended on CPU
     9.2292 [dev_pixelpipe] took 0.053 secs (0.361 CPU) [full] processed `filmicrgb&apos; on CPU, blended on CPU
     9.2320 [dt_ioppr_transform_image_colorspace] IOP_CS_RGB--&gt;IOP_CS_LAB took 0.003 secs (0.017 CPU) [colorout]
     9.2399 [dev_pixelpipe] took 0.011 secs (0.049 CPU) [full] processed `colorout&apos; on CPU, blended on CPU
     9.2446 [dev_pixelpipe] took 0.005 secs (0.027 CPU) [full] processed `gamma&apos; on CPU, blended on CPU
     9.2471 [dev_process_image] pixel pipeline took 4.734 secs (30.025 CPU) processing `DSCF0087.RAF&apos;
     9.2581 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
     9.2581 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
     9.3546 [histogram] took 0.033 secs (0.124 CPU) scope draw
     9.3549 [dev_process_image] pixel pipeline took 0.097 secs (0.222 CPU) processing `DSCF0087.RAF&apos;
     9.3579 [dt_dev_process_image_job] loading image. took 0.000 secs (0.000 CPU)
     9.4089 [dev_pixelpipe] took 0.000 secs (0.000 CPU) initing base buffer [preview]
     9.4101 [dev_pixelpipe] took 0.001 secs (0.003 CPU) [preview] processed `rawprepare&apos; on CPU, blended on CPU
     9.4110 [dev_pixelpipe] took 0.001 secs (0.000 CPU) [preview] processed `temperature&apos; on CPU, blended on CPU
     9.4383 [dev_pixelpipe] took 0.027 secs (0.133 CPU) [preview] processed `highlights&apos; on CPU, blended on CPU
     9.4543 [dev_pixelpipe] took 0.016 secs (0.089 CPU) [preview] processed `demosaic&apos; on CPU, blended on CPU
     9.4609 [dev_pixelpipe] took 0.006 secs (0.019 CPU) [preview] processed `flip&apos; on CPU, blended on CPU
     9.4630 [dev_pixelpipe] took 0.002 secs (0.004 CPU) [preview] processed `exposure&apos; on CPU, blended on CPU
     9.4696 [dev_pixelpipe] took 0.007 secs (0.030 CPU) [preview] processed `colorin&apos; on CPU, blended on CPU
     9.4744 [dt_ioppr_transform_image_colorspace] IOP_CS_LAB--&gt;IOP_CS_RGB took 0.005 secs (0.021 CPU) [channelmixerrgb]
     9.4897 [dev_pixelpipe] took 0.020 secs (0.088 CPU) [preview] processed `channelmixerrgb&apos; on CPU, blended on CPU
     9.5564 [dev_pixelpipe] took 0.067 secs (0.424 CPU) [preview] processed `filmicrgb&apos; on CPU, blended on CPU
     9.5609 [dt_ioppr_transform_image_colorspace] IOP_CS_RGB--&gt;IOP_CS_LAB took 0.005 secs (0.020 CPU) [colorout]
     9.5681 [dev_pixelpipe] took 0.012 secs (0.068 CPU) [preview] processed `colorout&apos; on CPU, blended on CPU
     9.5742 [dev_pixelpipe] took 0.006 secs (0.035 CPU) [preview] processed `gamma&apos; on CPU, blended on CPU
     9.5832 [dt_ioppr_transform_image_colorspace_rgb] RGB--&gt;RGB took 0.009 secs (0.057 CPU) [final histogram]
     9.5858 histogram calculation 256 bins 2 -&gt; -1 compensate 0 3 channels 1091700 pixels took 0.003 secs (0.018 CPU)
     9.5868 [histogram] took 0.013 secs (0.075 CPU) final histogram
     9.5892 [dev_process_image] pixel pipeline took 0.180 secs (0.970 CPU) processing `DSCF0087.RAF&apos;
     9.5906 [histogram] took 0.000 secs (0.000 CPU) scope draw
    11.7199 [histogram] took 0.000 secs (0.000 CPU) scope draw
    11.7756 [histogram] took 0.000 secs (0.000 CPU) scope draw
    11.8088 [histogram] took 0.000 secs (0.000 CPU) scope draw
    11.8480 [histogram] took 0.000 secs (0.000 CPU) scope draw
    11.8745 [histogram] took 0.000 secs (0.000 CPU) scope draw

</pre>

</pre>

![image](https://github.com/darktable-org/darktable/assets/80182265/78a335c7-1735-45ba-858d-845121004ffd)

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

DarkTable .deb install Ubuntu 4.4.2, or DarkTable Flatpak install 4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Describe your system?

Wayland, AMDGPU, MacPro 2013 Apple Inc. MacPro6,1, Kernel Linux 6.8.0-060800-generic, AMD Radeon™ HD 7800 Series, Intel® Xeon® E5-1620 v2 × 8

### Are you using OpenCL GPU in darktable?

No

### If yes, what is the GPU card and driver?

See Above

**Comment by kmilos** [comment] 2024-03-16 22:23
The release notes clearly state Fujifilm lossy compressed raws are not currently supported. Only lossless compressed or uncompressed.

Please search before opening new issues.

**Comment by CaptainMorgan12** [comment] 2024-03-16 23:40
Not a duplicate, as i stated it doesnt work for "uncompressed" please read my full post.

**Comment by jenshannoschwalm** [comment] 2024-03-17 07:46
@CaptainMorgan12 could you provide such an image or give a link?

**Comment by CaptainMorgan12** [comment] 2024-03-17 19:36
Ok am trying to figure out where i can upload it and will provide a link.

**Comment by gi-man** [comment] 2024-03-17 22:52
You image open correctly for me in current master. From the flatpak, can you post -d common? How much memory your system has? 

By the way, dynamic range of that camera is impressive. Ive been evaluating getting one.

**Comment by gi-man** [comment] 2024-03-18 00:42
I can edit your image in darktable. If you post the logfile from -d common using flatpak, we might be able to find the root cause of the problem.

**Comment by kmilos** [comment] 2024-03-18 09:53
Closing as there is no issue w/ darktable and Fujifilm GFX10 II per se (apart from the known missing lossy mode support).

For user support feel free to continue over at https://discuss.pixls.us/c/software/darktable/19. Please use GitHub for actual, reproducible dt issues and development.

**Closed by kmilos** 2024-03-18 09:53 UTC

**Comment by jenshannoschwalm** [comment] 2024-03-19 05:48
@CaptainMorgan12 some comments from my side

1. Indeed impressive quality in dark areas :-)
2. Image fully working here
3. for some reason OpenCL is not activated for your flatpack
4. Even on my 8GB nvidia card it's already the demosaicer going into tiling mode, leaving out even more demanding modules as diffuse&sharpen.
5. Images that huge are very demanding, without OpenCL active and having at least 6GB there won't be a lot of fun :-)

**Comment by kmilos** [comment] 2024-03-19 17:11
FYI, works for me for these files on Windows w/o OpenCL (integrated Intel graphics not supported), so not sure if that's it...

**Comment by jenshannoschwalm** [comment] 2024-03-19 18:29
@CaptainMorgan12 you should for dt running with opencl with command line options "-d pipe -d opencl"

5sec sounds pretty bad to me.
