### ISSUE TITLE
Compilation against libavif-0.10.1 fails

### ISSUE THREAD

**Issue by tomaszg7** [darktable-org/darktable#17186] opened 2024-07-22 09:55 UTC
### Describe the bug

The commit 2da359d5b683eb0f9ab8a280a0626e9ec53e9e9b breaks compilation with older version of libavif library. On my system I have the version 0.10.1 and the result is:

```
FAILED: bin/CMak games-strategy/dunelegacyeFiles/lib_darktable.dir/imageio/imageio_avif.c.o 
/usr/bin/cc -DAVIF_DLL -DDT_HAVE_SIGNAL_TRACE -DGDK_DISABLE_DEPRECATED -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_24 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_MIN_REQUIRED -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DGTK_DISABLE_DEPRECATED -DGTK_DISABLE_SINGLE_INCLUDES -DHAVE_BUILTIN_CPU_SUPPORTS -DHAVE_CONFIG_H -DHAVE_ICU -DHAVE_ISO_CODES -DHAVE_KWALLET -DHAVE_LIBAVIF=1 -DHAVE_LIBHEIF=1 -DHAVE_LIBJXL -DHAVE_LIBRAW=1 -DHAVE_LIBSECRET -DHAVE_MAP -DHAVE_OPENCL -DHAVE_OPENJPEG -DHAVE_OSMGPSMAP_110_OR_NEWER -DHAVE_OSMGPSMAP_NEWER_THAN_110 -DHAVE_PRINT -DHAVE_SQLITE_324_OR_NEWER -DHAVE_WEBP -DLIBRAW_NODLL -DNATIVE_ARCH -DSQLITE_CORE -DSQLITE_ENABLE_ICU -DUSE_LUA -D_XOPEN_SOURCE=700 -Dlib_darktable_EXPORTS -I/home/tomaszg/src/gimp/git/darktable/b/bin -I/home/tomaszg/src/gimp/git/darktable/src -I/home/tomaszg/src/gimp/git/darktable/src/external/LuaAutoC -I/home/tomaszg/src/gimp/git/darktable/src/external/whereami/src -I/home/tomaszg/src/gimp/git/darktable/src/external/LibRaw -isystem /home/tomaszg/src/gimp/git/darktable/src/external -isystem /home/tomaszg/src/gimp/git/darktable/src/external/OpenCL -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/gtk-3.0 -isystem /usr/include/pango-1.0 -isystem /usr/include/cairo -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/webp -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib64/dbus-1.0/include -isystem /usr/include/elogind -isystem /usr/include/fribidi -isystem /usr/include/libpng16 -isystem /usr/include/pixman-1 -isystem /usr/include/harfbuzz -isystem /usr/include/freetype2 -isystem /usr/include/gio-unix-2.0 -isystem /usr/lib64/libffi/include -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/libxml2 -isystem /usr/include/lensfun -isystem /usr/include/librsvg-2.0 -isystem /usr/include/json-glib-1.0 -isystem /usr/include/openjpeg-2.5 -isystem /usr/include/libsecret-1 -isystem /usr/include/lua5.4 -isystem /usr/include/osmgpsmap-1.0 -isystem /usr/include/libsoup-2.4 -O2 -march=native -pipe -Wall -Wformat -Wformat-security -Wshadow -Wtype-limits -Wvla -Wold-style-declaration -Wmaybe-uninitialized -Wno-unknown-pragmas -Wno-error=varargs -Wno-format-truncation -Wno-error=address-of-packed-member -fopenmp -march=native -msse2 -g -mfpmath=sse -O2 -g -DNDEBUG -O2 -ftree-vectorize -std=c99 -fPIC   -Werror -Wfatal-errors -MD -MT bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o -MF bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o.d -o bin/CMakeFiles/lib_darktable.dir/imageio/imageio_avif.c.o -c /home/tomaszg/src/gimp/git/darktable/src/imageio/imageio_avif.c
/home/tomaszg/src/gimp/git/darktable/src/imageio/imageio_avif.c: In function ‘dt_imageio_open_avif’:
/home/tomaszg/src/gimp/git/darktable/src/imageio/imageio_avif.c:113:10: error: void value not ignored as it ought to be
  113 |   result = avifRGBImageAllocatePixels(&rgb);
      |          ^
compilation terminated due to -Wfatal-errors.
```

So, either the checks could be conditional, or darktable should require higher version of libavif. Reverting the commit makes darktable compile fine.

### Steps to reproduce

1. install libavif-0.10.1
2. try to compile darktable

### Expected behavior

darktable should compile

### Commit

2da359d5b683eb0f9ab8a280a0626e9ec53e9e9b

### Where did you obtain darktable from?

self compiled

### darktable version

HEAD

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Are you using OpenCL GPU in darktable?

Yes

**Comment by victoryforce** [comment] 2024-07-22 10:03
@tomaszg7 Thanks for reporting, but this is a duplicate of #17182. So, I'm closing this issue, you can track the progress in the mentioned issue.

**Closed by victoryforce** 2024-07-22 10:03 UTC
