### ISSUE TITLE
Build script fails on Fedora 38

### ISSUE THREAD

**Issue by lintujuh** [darktable-org/darktable#14527] opened 2023-05-17 17:00 UTC
### Describe the bug

I tried to build latest master on Fedora 38, but the build fails because clang-15 is missing. When I got the error, I tried to install all dependencies with `sudo dnf builddep darktable`, but it didn't solve the issue.

### Steps to reproduce

Just run the build script (./build.sh)

### Logfile | Screenshot | Screencast

Part of the configuration of the build files
```
-- Found desktop-file-validate
-- Found LLVM 16.0.2
-- Found clang compiler - /usr/bin/clang-15
-- Found clang opencl-c.h header in /usr/lib64/clang/15.0.7/include
-- Will be able to test-compile OpenCL programs. Nice.
```
Error in building
```
[  7%] Built target opencl-program-demosaic_other.cl
[  7%] Test-compiling OpenCL program demosaic_rcd.cl
/bin/sh: line 1: /usr/bin/clang-15: No such file or directory
gmake[2]: *** [share/darktable/kernels/CMakeFiles/opencl-program-demosaic_rcd.cl.dir/build.make:74: share/darktable/kernels/demosaic_rcd.cl.touch] Error 127
gmake[1]: *** [CMakeFiles/Makefile2:7734: share/darktable/kernels/CMakeFiles/opencl-program-demosaic_rcd.cl.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```
And the listing of /usr/bin/cl*
```
[lintujuh@fedora darktable]$ ls /usr/bin/cl*
/usr/bin/clang    /usr/bin/clang++-16  /usr/bin/clang-cl   /usr/bin/clear      /usr/bin/cluster
/usr/bin/clang++  /usr/bin/clang-16    /usr/bin/clang-cpp  /usr/bin/clockdiff
[lintujuh@fedora darktable]$ 
```

### Where did you install darktable from?

self compiled

### darktable version

4.3.0~975eabc5fb 

### What OS are you using?

Linux

### What is the version of your OS?

Fedora 38

### Are you using OpenCL GPU in darktable?

None

**Comment by Nilvus** [comment] 2023-05-18 08:19
Duplicate of #14488 and already fixed on master. Your master version is old. You need to update it (and think about searching before posting).

**Closed by Nilvus** 2023-05-18 08:19 UTC

**Comment by kmilos** [comment] 2023-05-18 09:57
This is a different error, but indeed the OP is some 1000+ commits behind and should check if the problem still persists on latest master.

**Comment by lintujuh** [comment] 2023-05-18 13:43
Sorry, I somehow messed with the version. The version that fails is 4.3.0+2328~gab646f9703

**Comment by kmilos** [comment] 2023-05-18 13:53
Pinging @jenshannoschwalm as he seems to be running F38 as well.

**Comment by jenshannoschwalm** [comment] 2023-05-18 14:38
No problem here with today's master. (Confess i never use `sudo dnf builddep darktable` but just install what i need)

`dnfdragora` is my friend here, while doing `./build.sh --prefix /usr/local --disable-game --disable-kwallet --disable-unity --build-type Release --install --sudo` i just watch what is missing and use `dnfdragora` to search & install.

**Comment by lintujuh** [comment] 2023-05-18 19:42
I understand that I can have a component missing, but what I'm wondering is that I get a message that c compiler is found at /usr/bin/clang-15, but listing /usr/bin doesn't show it.

**Comment by jenshannoschwalm** [comment] 2023-05-18 19:48
maybe some symbolic link remaining from update?

**Comment by lintujuh** [comment] 2023-05-18 20:03
Everything worked now when I purged the build directory. Looks like there was something that was carried over from F37. Thank you for the comments.
