### ISSUE TITLE
Darktable do not start at all when username contains non-latin characters.

### ISSUE THREAD

**Issue by FlugelArpeggio** [darktable-org/darktable#8859] opened 2021-05-04 11:39 UTC
Few weeks ago, I re-install Windows and darktable(version 3.4.1.1) because OS was corrupted. But unlike before re-installing Windows, darktable do not start at all. When I start darktable, a black background window(very similar with command prompt) pops up but it closes itself in a second, and nothing appear. I re-install darktable few times, but nothing changed.

One thing I think that can cause this problem is username. Because of I use Windows 10 Education, Username is automatically set to my name, which contains non-latin characters such as Korean. I see folder named 'darktable' generated in C:\Users\(My name)\AppData\Local, but after then, nothing happened. I don't know about how darktable works, but when I add a new account have English username, darktable was started and worked well. so I think this might happened by same reason. What causes this problem and how to solve it?

I'm not English-native speaker and it's first to me to use github, so I'm worried about this report is enough to solve this problem. If this report aren't enough to understand and solve this problem or has errors, please leave comments. I'll add or edit information as fast as possible. Thanks to read this.

**Platform**

* darktable version : 3.4.1.1
* OS                : Windows 10 Education (19042.928)
* Memory            : 32 GB
* Graphics card     : Radeon RX 580 4 GB
* Graphics driver   : version 21.3.1

**Comment by ralfbrown** [comment] 2021-05-04 12:09
Duplicate of #7489, which should have been fixed in master by #7721.

**Comment by Nilvus** [comment] 2021-05-04 18:46
The fix had been integrated in a specific 3.4.1.1 for Windows (has it was a Windows specific bug) and you precise that you use 3.4.1.1 (which is different from 3.4.1). Are you sure to have the good release? Could you uninstall darktable and reinstall from following link: https://github.com/darktable-org/darktable/releases/download/release-3.4.1/darktable-3.4.1.1-win64.exe

We had a lot of users who complains about that issue with 3.4.1 and they all confirm that the 3.4.1.1 fix that issue. If necessary, remove (save it before) darktablerc file (you will lost some settings) which is in folder named 'darktable' generated in C:\Users(My name)\AppData\Local

Please report here if it's ok (it should) and think about closing this issue if ok.

**Comment by FlugelArpeggio** [comment] 2021-05-05 06:16
> The fix had been integrated in a specific 3.4.1.1 for Windows (has it was a Windows specific bug) and you precise that you use 3.4.1.1 (which is different from 3.4.1). Are you sure to have the good release? Could you uninstall darktable and reinstall from following link: https://github.com/darktable-org/darktable/releases/download/release-3.4.1/darktable-3.4.1.1-win64.exe
> 
> We had a lot of users who complains about that issue with 3.4.1 and they all confirm that the 3.4.1.1 fix that issue. If necessary, remove (save it before) darktablerc file (you will lost some settings) which is in folder named 'darktable' generated in C:\Users(My name)\AppData\Local
> 
> Please report here if it's ok (it should) and think about closing this issue if ok.

I uninstalled and reinstalled darktable from that link, but nothing changed. One thing on my mind is darktable worked well before I re-installed Windows, which also have Korean username(because I'm Korean student, Seoul Metropolitan Office of Education which give Windows 10 Education Licence make me unable to edit my username). I think it might be occurred by some problem that we don't know in Windows, so I think about re-install Windows as soon as possible. I'll add some comments when some changes happened.

**Comment by johnny-bit** [comment] 2021-06-05 04:43
@FlugelArpeggio - have you managed to check if everything works as it should? For me darktable works with user with non-lat characters (like `ó`, `ń` and such), but i haven't tried with different character set (eg cyrylic, hangul).

**Comment by Nilvus** [comment] 2021-11-04 10:33
Should be fixed since 3.6.1 and/or some fix added for 3.8. So closing.

**Closed by Nilvus** 2021-11-04 10:33 UTC
Labels: bug: fixed, no-issue-activity, scope: windows support
