### ISSUE TITLE
Thumbnails overlays configuration back to defaults

### ISSUE THREAD

**Issue by difrkaguilar** [darktable-org/darktable#8810] opened 2021-04-28 21:16 UTC
**Describe the bug/issue**
In Fedora 34 I installed the master branch.
Every time I open darktable, in the Lighttable the thumbnails overlays configuration always return to their default state (overlays on mouse hover).

I set "permanent extended overlays" for size 2 (625px) then close darktable and open again and thumbnails overlay back to the state (overlays on mouse hover) again.

Even after set the "permanent extended overlays" option, if thumbnails are scaled at 314px, the option change to "overlays on mouse hover"

**Expected behavior**
The thumbnails overlays configuration must be as user set without change.

**Screenshots**
![Screenshot-20210428162502-3840x2160](https://user-images.githubusercontent.com/67672868/116471848-26abca80-a843-11eb-87cb-1b4443cbd893.png)

Screenshot 1 - Set the "permanent extended overlays" option for size 2 (625px) and closed darktable.

![Screenshot-20210428162945-3840x2160](https://user-images.githubusercontent.com/67672868/116472039-5bb81d00-a843-11eb-92a2-e8cb07be1861.png)

Screenshot 2 - I open darktable and thumbnails overlay back at other state (overlays on mouse hover).

![Screenshot-20210428162554-3840x2160](https://user-images.githubusercontent.com/67672868/116472270-acc81100-a843-11eb-8448-0dc0533f355b.png)

Screenshot 3 - With the option set to "permanent extended overlays" If thumbnails are scaled at 314px, the option change to "overlays on mouse hover".

**Platform**
darktable version : 3.5.0~git1913.1d12a51fa0-5765.2
Linux - Kernel: 5.11.15-300.fc34.x86_64 Fedora 34
OS: Fedora 34 (Workstation Edition) x86_64 
Host: Z390 AORUS MASTER 
Kernel: 5.11.15-300.fc34.x86_64 
Uptime: 35 mins 
Packages: 2052 (rpm), 11 (flatpak), 3 (snap) 
Shell: bash 5.1.0 
Resolution: 3840x2160 
DE: GNOME 40.0 
WM: Mutter 
WM Theme: Adwaita 
Theme: WhiteSur-dark-solid [GTK2/3] 
Icons: Mojave-CT-Classic [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-9700K (8) @ 4.900GHz 
GPU: NVIDIA GeForce GTX 1070 
GPU: NVIDIA GeForce GTX 1080 Ti 
Memory: 2219MiB / 32037MiB
Graphics driver   : 460.73.01
OpenCL installed  : yes
OpenCL activated  : yes

**Comment by AlicVB** [comment] 2021-04-29 17:39
I can't reproduce...
Can you do some tests, in order to track down the cause ? 
I'm interested by the following entries in darktablerc : 
- plugins/lighttable/overlays/... 
- plugins/lighttable/thumbnail_sizes

If you can do this : 
1. before starting dt you copy paste the lines
2. you start dt, and change the overlay mode (to "permanent extended" for example)
3. you close dt
4. and you copy paste the same lines of darktablerc

That will show us if this is a "saving" or a "loading" problem... Thanks a lot for your help !

**Comment by difrkaguilar** [comment] 2021-05-02 01:20
The firs time I installed it was working with this parameters.

darktablerc:

plugins/lighttable/overlays/1/0=0
plugins/lighttable/overlays/1/1=4
plugins/lighttable/overlays/1/2=4
plugins/lighttable/overlays/2/1=1
plugins/lighttable/overlays/2/2=4

plugins/lighttable/thumbnail_sizes=120|400



Now is working with this parameters.

plugins/lighttable/overlays/0/1=1
plugins/lighttable/overlays/0/2=4
plugins/lighttable/overlays/1/0=0
plugins/lighttable/overlays/1/1=4
plugins/lighttable/overlays/1/2=4
plugins/lighttable/overlays/2/1=1
plugins/lighttable/overlays/2/2=4

plugins/lighttable/thumbnail_sizes=120|400

At this moment i don´t have the issue, and the lighttable is working ok. It seems this happen just at the first start only.

**Comment by johnny-bit** [comment] 2021-06-02 08:07
I cannot reproduce at all... I'll pre-emptively close this if you don't mind. If we could get some concrete reproduction then of course I'll re-open and we can then investigate.

**Closed by johnny-bit** 2021-06-02 08:07 UTC
Labels: no-issue-activity, understood: incomplete
