### ISSUE TITLE
Masks in presets, styles, and mask manager

### ISSUE THREAD

**Issue by hodapp512** [darktable-org/darktable#8165] opened 2021-02-09 19:53 UTC
Masks are not preserved in presets, nor are they usable across multiple images. For example, enable masking on an local contrast module instance. Modify mask settings as desired. Create preset for that local contrast module. Apply preset to another image. Mask must be re-enabled, and settings must be re-configured. The mask manager also is unhelpful in this instance because it only stores masks created with the current image and doesn't give access to masks in other images.

Possible Solutions:

1) Give option to store preset with or without mask
2) Give option to store style with or without mask
3) Give option in mask manager to show masks from other images

**Comment by johnny-bit** [comment] 2021-02-09 20:05
This sounds like a duplicate of #7586

Please check if #7586 works for you and aguament that one and close this please :)

**Comment by hodapp512** [comment] 2021-02-09 20:19
Duplicates #7586

**Closed** 2021-02-09 20:19 UTC
