### ISSUE TITLE
edits and tags lost on exit or sometimes even between switching around

### ISSUE THREAD

**Issue by chrik5** [darktable-org/darktable#2242] opened 2019-03-17 21:06 UTC
**Describe the bug**
After editing a few images closing and opening darktable edits and tags are lost. Image previews shows last state until you enter darkroom and they get updated. Sometimes working on other images let latest edits and tags disappear. In some case pressing ctrl+z brings back the edits. Either my PC is dying or there is something wrong with darktable 2.7.0+717~g5c40fc801. ???

**To Reproduce**
1. Go to darkroom
2. edit a few images and attach tags
3. exit or work on more images in darktable and reopen it
4. edits and tags of the images disappear magically.

**Expected behavior**
Don't forget edits and tags.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Debian 9
 - Version 2.7.0+717~g5c40fc801

**Comment by TurboGit** [comment] 2019-03-17 22:19
This is very worrisome, but I cannot reproduce! Are you able to reproduce this issue each time? A precise sequence maybe?

**Comment by chrik5** [comment] 2019-03-18 08:45
short: **The strange behaviour seems to start if I use ctrl+c and ctrl+v to copy a history stack from one image to another?** 

> Are you able to reproduce this issue each time? 

Yes, after two or more reboots it is still there. Also removing the whole /opt/darktable dir, building from clean build dir and reinstalling makes no difference. 

I forgot to mention that I got skulls after removing images within darktable, closing and opening darktable again. It feels like if the database loses its memories. 

I startet to test this on another machine to exclude hardware issues using the same configs and database.

> A precise sequence maybe?

I'm thinking on this, but I'm not aware of any specific order/sequence? 

After some back and forth on the other machine: 
**It seems to start if I use ctrl+c and ctrl+v to copy a history stack from one image to another?** 

Copying the history stack works fine, but coming back to the images after some editing of other images resets the history stack to the previous state. This happens also for the image where the history stack has been copied from. Other edits not involving any copy and paste of history stacks are effected as well.

**Comment by MStraeten** [comment] 2019-03-18 11:36
are you using styles? i found similar behaviour in that case: #2212

**Comment by TurboGit** [comment] 2019-03-18 14:33
Should be fixed now. Thanks a lot for reporting.

**Closed** 2019-03-18 14:33 UTC
Labels: bug
