### ISSUE TITLE
Bottom film roll in darkroom should not auto center on selected image.

### ISSUE THREAD

**Issue by safield** [darktable-org/darktable#11699] opened 2022-04-30 23:02 UTC
I don't think this provides any benefit and is really disorienting and leads to me doing actions on images I do not intend.

**Comment by Nilvus** [comment] 2022-05-01 06:25
Saying what we don't want doesn't give what you would like. Better to propose something else.
We provide an issue template that give some clue about that like "expected behavior" part. Would be good to read it.

Note that I remember we discussed about that some time ago (can't find when and which PR by now) and I remember that most people who answer prefer the actual way. So don't forget that what you find bad could be found better for other people (the opposite is also true).

**Comment by pehar1** [comment] 2022-05-01 07:27
I like the way it is actually implemented. Only one example : clicking in filmroll on the image right (or left) of the active and centered image allows to move through the filmroll step by step without any mouse movement.

**Comment by safield** [comment] 2022-05-01 12:27
I dont know why I hate it so much, but I think it is mainly because it goes against the pattern of every single film roll style application I have used previously. 

I would prefer an option to turn it off. The alternative would be simple, dont move the film roll position based on image selection.

**Comment by Nilvus** [comment] 2022-05-01 12:31
> I dont know why I hate it so much, but I think it is mainly because it goes against the pattern of every single film roll style application I have used previously.

What is the pattern? Would help if, as I ask you, you explain behavior you would like.

**Comment by safield** [comment] 2022-05-01 12:36
Dont move the filmroll based on image selection. The darkroom film roll is a horizontally scrollable view. The currently selected image should be completely independent of the film roll position.

The solution would be a setting to change between the styles.

**Comment by Nilvus** [comment] 2022-05-01 12:37
> Dont move the filmroll based on image selection. The darkroom film roll is a horizontally scrollable view. The currently selected image should be completely independent of the film roll position.

That doesn't answer the main downside I add in my comment (see EDIT line)

**Comment by safield** [comment] 2022-05-01 12:42
Not a downside at all. That is actually the common pattern for scrollable views eith thumbnail items. You can have a selected item, and you can independently scroll the view away from the item. No problem. Its how every OS does it, it is not different than a scrolable file list on Windows, Mac, or Plasma or Gnome.

Overthinking things is how you get weird UX (and darktable is probably the weirdest I have seen).

Keep it simple.

**Comment by AlicVB** [comment] 2022-05-01 13:11
I wonder what is your workflow, and why you need that. I suspect we don't have the same use for the filmstrip...

> and leads to me doing actions on images I do not intend.

not sure which action you are speaking of...

Now the reason why it has been implemented that way is quite simple : filmstrip feature is designed to quickly switch between a set of images without leaving darkroom. It's also designed to allow to copy-paste from one image to another.
With that in mind, you absolutely need to know which thumbnail in filmstrip is your current image (remember that when you have a set of images they often are very similar...) as it's the "pivot" of the other actions...

**Comment by Nilvus** [comment] 2022-05-01 13:19
And if you find darktable UI, just be simple: use another software. My question was simple, your answer not.

**Comment by safield** [comment] 2022-05-01 13:19
If you want to quickly switch images like you say, why implement it this way? By moving the filmroll you are breaking spatial context of the position and are making it HARDER to quickly switch between images.

Eg I might want to quickly switch back and fourth between the second image in the filmroll and the second last. If you then move the film strip, guess what.....I no longer know what is the second and second last image anymore.

Your argument for knowing which image is selected holds no water, as the currently selected image highlight exists for this reason. If you lose it in the film roll by scrolling then maybe a 'jump to selected' button should be added, which is WAY less obtrusive than ALWAYS moving the film roll and always breaking spatial context.

**Comment by safield** [comment] 2022-05-01 13:23
To follow up on this, if Intake a rapid fire shot of 20+ images that look the same, having spatial context of the selected image os so important as the thumbnails all look the same.

I have made my argument clear, if you guys wanna stick with your against the grain UX design so be it.

**Comment by MStraeten** [comment] 2022-05-02 15:32
everybodys darling is everybodys fool - following everybodys ideas on the one and only good UX is the best way to achieve a bad UX design...
If darktable already has "the weirdest UX" then it's obviously not the tool for you. It's not that complex to fork darktable - but there's no fork around providing a non "against the grain UX design". You might ask yourself why ...

**Comment by emko** [comment] 2022-05-02 19:47
> everybodys darling is everybodys fool - following everybodys ideas on the one and only good UX is the best way to achieve a bad UX design... If darktable already has "the weirdest UX" then it's obviously not the tool for you. It's not that complex to fork darktable - but there's no fork around providing a non "against the grain UX design". You might ask yourself why ...

yes dt bottom film strip UX is weird, worst it has no scroll bar so trying to go to a image with a pen on a wacom tablet is a pain you have to keep opening images to the left or right so it slides over.... can't even use arrow keys to move the selected image ,  then when you want to switch back and forth between two images it shifts to center.  How do you see this as good UX? i guess i can get used to it but if there is a better way to do it and seems like every type of software follows the better method.

**Comment by safield** [comment] 2022-05-02 19:52
> but there's no fork around providing a non "against the grain UX design". You might ask yourself why ...

I think that question is better poised to the developers than me....but I would definitely be interested in hearing their answer. Generally open source projects are driven by developers, and lack the UX designers you find on commercial projects, so in my experience, you end up with a lot of poorly thought out 'programmer UIs'. Its just one of the small downside's to open source software, but a small price to pay.

**Comment by AlicVB** [comment] 2022-05-02 20:36
Well... I am a dt dev, @Nilvus too, and we both (not alone) are quite invested in the UI part...
We don't say that everything is perfect, we don't think either that nothing can be improved, but be sure that what is done is carefully though with a clear design and workflow in mind... and reviewed by other devs and users in the test phase.

Now I'm sorry, but my TODO list already exceed what I can do in the next decade... So I have to make priorities. Now comes a FR without the required infos, which don't answer our questions, which don't correspond to our vision and use a tonality... (let's don't put word here). Guess what : it won't finish on the top of the TODO ;)

But, you're lucky : opensource is magic : you just have to do it yourself, convince us that this can be useful, don't break existing workflow... and chance are that this will be integrated :) And be sure that it's not "just" talk : we have lot of recent examples where users who really wanted a feature have done it themself and it's in dt core now (some have even learn to write C code at the meantime)

**Comment by safield** [comment] 2022-05-02 20:42
> Well... I am a dt dev, @Nilvus too, and we both (not alone) are quite invested in the UI part...
> 
> We don't say that everything is perfect, we don't think either that nothing can be improved, but be sure that what is done is carefully though with a clear design and workflow in mind... and reviewed by other devs and users in the test phase.
> 
> 
> 
> Now I'm sorry, but my TODO list already exceed what I can do in the next decade... So I have to make priorities. Now comes a FR without the required infos, which don't answer our questions, which don't correspond to our vision and use a tonality... (let's don't put word here). Guess what : it won't finish on the top of the TODO ;)
> 
> 
> 
> But, you're lucky : opensource is magic : you just have to do it yourself, convince us that this can be useful, don't break existing workflow... and chance are that this will be integrated :) And be sure that it's not "just" talk : we have lot of recent examples where users who really wanted a feature have done it themself and it's in dt core now (some have even learn to write C code at the meantime)

What GUI framework does Darktable use?

**Comment by Nilvus** [comment] 2022-05-02 21:23
darktable use Gtk library.

I will just say some things about your statement @safield: just consider that what you find good or bad doesn't mean that others choices (it could be anything in life, like here of course UI, but not only) are the opposite. Being irritating because you're not agree will not help you too to have help or understand what you ask for. I do not say here that darktable has the best UI. darktable have things that needs to be improved. But darktable UI had hugely been improved since the arrival of 3.0 release and continue too. Last thing, it's not because others apps do it one way that is the only good way. Some things are, others are also just about habits. Most people use Windows, not because it has always been the best, just because it has been installed by default on most computers since times.
So please try to be more constructive and understand that what exist have been for reasons, even if a better way could be possible.

And again, if you don't like something, like a software with a "weird" UI, make your life simple, don't use it. If you want to use it, that's means there's quite some things you like. So just be precise on what you want/would like AND avoid judgments. That would be easier.

I will now unsubscribe again and forget that issue. And let another it if another developer want to take care of it. So please,do not ping me again here.

**Comment by abhijitvalluri** [comment] 2022-07-09 11:00
EXACTLY! This is soooooooooooooooooo annoying and does not help at all and makes me constantly click the wrong image!

**Closed** 2023-07-07 00:21 UTC
Labels: scope: UI, controversial, no-issue-activity

**Comment by KreativeLabs** [comment] 2024-07-04 21:17
I am learning Darktable and I cannot get used to this UX decision. Very hard to select photos on a filmstrip and not lose track of the items. Any solutions since?

**Comment by wpferguson** [comment] 2024-07-05 01:01
The issues concerning this are now in #16850

**Comment by AdamAnon** [comment] 2025-05-14 08:29
> I am learning Darktable and I cannot get used to this UX decision. Very hard to select photos on a filmstrip and not lose track of the items. Any solutions since?

Same. It's literally a deal breaker for me. I need an option to stop this auto centering. It's infuriating.  The UX is weird enough already, starting with all lowercase words in the UI, strange UI contrast that can't be addressed in the settings, maybe the CSS can be edited, but I don't wanna do that.

**Comment by MStraeten** [comment] 2025-05-14 14:04
you might use english truecase as a language ;)

**Comment by pehar1** [comment] 2025-05-15 09:27
> strange UI contrast that can't be addressed in the settings

???? Ten different themes available, selectable via preferences, fully user configurable by the user via CSS.

>[...] but I don't wanna do that

So don't blame others ...

**Comment by AdamAnon** [comment] 2025-05-15 09:52
> > strange UI contrast that can't be addressed in the settings
> 
> ???? Ten different themes available, selectable via preferences, fully user configurable by the user via CSS.
> 
> > [...] but I don't wanna do that
> 
> So don't blame others ...

All the default options suck and no, I shouldn't have to edit complex text files to configure a desktop application, that's ridiculous. Something like choosing the interface colors should be an option in the UI. I absolutely blame the devs. Darktable is the worst image editing and RAW editor I have seen so far. Raw Therapee has much better UI, features and options but, unfortunately, it's very laggy, glitchy and unstable and there have been no updates in nearly a year so another FOSS fail.

Anyway, I bought a copy of DxO PhotoLab. Other devs should have a look at this app an learn how to make a proper UI for a RAW Editor.

**Comment by AdamAnon** [comment] 2025-05-15 13:28
> - so there's no concept of "customers and customer satisfaction"

Thank you! Yes, this is exactly it. This is my experience with FOSS in the last three years as I'm gradually moving back to commercial software, it just never occurred to me to formulate it this way. If this philosophy changed and it FOSS developers would put end users more in focus, actually made software that people want to use and become less "developer centric" then FOSS would likely gain more traction on the desktop.  And this isn't only me who feels that way. Being free isn't good enough unless it works well.

**Comment by parafin** [comment] 2025-05-15 14:21
What exactly would developers gain from said “traction”? More complaining users like you, who contribute nothing? Sounds like a plan.

**Comment by MStraeten** [comment] 2025-05-15 14:53
it seems hard to understand, that the developers aren’t motivated by those complaining, that the result doesn’t fit mass market demands ;) the result must fit the developer’s demand, they share …
Stay with commercial software if you think money or a large user base is the main motivation for FOSS developers…
