### ISSUE TITLE
Bug report: Missing GUI elements when starting darktable via GIMP

### ISSUE THREAD

**Issue by onlinebowline** [darktable-org/darktable#7402] opened 2020-12-22 19:10 UTC
HI,

Forgive me, I'm a bit of a layman when it comes to GitHub and developing, but I'm trying to make this a useful bug report.

OS: Win10 (64bit)
darktable: 3.2.1
GIMP: 2.10.22

Bug details: I recently upgraded to both of the latest versions of GIMP and darktable. Since updating, when opening a NEF file in GIMP while having darktable set as my RAW image importer, some elements of the GUI are missing, for example, the gridlines on the 'Tone curve' module, plus the diagonal adjustment line are missing. Also, the horizontal line on the sliders in various modules are missing, for example, in the 'Tone equalizer' module, or the 'White balance' module. Note that these issues do not occur when I open darktable independent of GIMP, nor do they occur when I roll back to a previous version of Darktable (3.0.2) with all other factors remaining the same. Also, the lines are present as usual on the base curve module.

See below for images illustrating the bugs:

![Missing lines tone curve](https://user-images.githubusercontent.com/76492681/102923842-607d5680-4488-11eb-80cf-99ce286476b3.jpg)

![Missing slider lines white balance](https://user-images.githubusercontent.com/76492681/102923866-6bd08200-4488-11eb-8218-395d8d0ac7cc.jpg)

I have replicated this same issue on both my desktop and laptop. I have replicated the issue with more than one NEF file.  See below for a ink to one of my NEF files:

[https://1drv.ms/u/s!Asnc_aK5xUQptj5KAByWP9YtXS-y?e=zS72Gz](url)

Details about my systems:

Desktop:
Operating System: Windows 10 Pro 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
System manufacturer: custom build
Processor: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 CPUs), ~3.6GHz
Memory: 16384MB RAM 
OpenCL: 2.02.0005.0000
Card name: NVIDIA GeForce RTX 2080 Ti
Dedicated Display Memory: 11049 MB
GraphicsDriver Version: 27.21.14.5709

Laptop:
Operating System: Windows 10 Home 64-bit (10.0, Build 19041) (19041.vb_release.191206-1406)
System Manufacturer: HP
System Model: HP Pavilion Gaming Laptop 17-cd1xxx
Processor: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz
Memory: 16384MB RAM
OpenCL: 2.02.0005.0000
Card name: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Dedicated Display Memory: 5991 MB
Graphics Driver Version: 27.21.14.5241

I'm sorry, I don't know how to do a backtrace on Windows, but if you need more info about the bug, I will try to provide it. Just let me know.

Kind regards

**Comment by parafin** [comment] 2020-12-22 21:15
The whole GUI looks mangled, like wrong theme is applied. My guess that GIMP sets some environment variables that configures GTK in unexpected way for darktable.

**Comment by paperdigits** [comment] 2020-12-23 02:05
perhaps @prokoudine can help us with this one. Does gimp set some GTK theme environmental variables or something?

**Comment by onlinebowline** [comment] 2021-01-02 13:08
Just FYI, this bug still seems to be present in darktable 3.4.0.

As before, if you need any further information, or need me to try anything, please let me know.

Kind regards,

**Comment by johnny-bit** [comment] 2021-01-02 14:41
darktable look is css based and css needs to be loaded properly for it to work. the 3.2.1 release seen a lot of css rework and so it's possible that css is being incorrectly loaded... so my guess is that something in a way GIMP opens darktable might have something to do with the problem.

**Comment by onlinebowline** [comment] 2021-01-02 16:35
I have reported the issues to the GIMP folks in case it is GIMP related.

Here is the link for that thread:
[https://gitlab.gnome.org/GNOME/gimp/-/issues/6195](url)

**Comment by Jehan** [comment] 2021-01-02 18:55
Hi!

> so my guess is that something in a way GIMP opens darktable might have something to do with the problem.

As far as I can see, we just open darktable [like this](https://gitlab.gnome.org/GNOME/gimp/-/blob/gimp-2-10/plug-ins/file-raw/file-darktable.c#L383):

```
darktable --library ":memory:" --luacmd "dofile(/some/path/file-darktable-export-on-exit.lua)" --conf "plugins/lighttable/export/icctype=3" --conf "lua/export_on_exit/export_filename=something.exr" "input_file"
```

We have not touched this much (if at all) from the original contribution, I think. 🙂

If there is something wrong and which should be updated, we'd welcome the help. 😉

**Comment by johnny-bit** [comment] 2021-01-02 19:10
would it be able to redirect darktable output (from stdout and stderr) and have it presented to user? and if possible allow user to adddebug params (like unholly `-d all`)? That way we could instruct user to run some debug mode and analyze logs to see what's going on.

**Comment by Jehan** [comment] 2021-01-02 19:32
> would it be able to redirect darktable output (from stdout and stderr) and have it presented to user?

I think darktable shows some output on stdout and I don't think we want to show this each and every time to people, right? Because a popup with weird software message, for many, it usually means "*it's broken*". Or are you proposing some temporary hack just for @onlinebowline in order to debug this specific issue?

**Comment by parafin** [comment] 2021-01-02 19:35
It's not about the cmdline itself, but environment variables that might be set. So it would help to replace darktable with env and see what it prints.

**Comment by ptilopteri** [comment] 2021-01-02 19:37
agree, appears a *local* issue.  I can open raw files with gimp/dt on openSUSE Tw and
observe the same dt gui appearance as when I open dt normally.
darktable master 3e13e284f

**Comment by johnny-bit** [comment] 2021-01-02 19:39
> I think darktable shows some output on stdout and I don't think we want to show this each and every time to people, right?

Nah, darktable is usually silent when nothing breaks :)

Let's go with what @parafin said :)

**Comment by Jehan** [comment] 2021-01-02 19:43
Anyway I can have our CI rebuild the plug-in for Windows on some branch (not the main tree for now so no worrying about what other people would see) then @onlinebowline can just switch the plug-in binaries; I'll tweak it to output the command and the env contents. But not today. I'll try and do it tomorrow (feel free to ping me if I forgot and haven't done it within the week!).

**Comment by parafin** [comment] 2021-01-07 08:49
Looking at #7402 it would be interesting to check the contents of CSS and theme settings in preferences. So @onlinebowline, could you take a screenshot of preferences window when dt is opened from GIMP and when it's opened independently?

**Comment by onlinebowline** [comment] 2021-01-08 12:41
Here is the preferences window when dt opened independently:

![image](https://user-images.githubusercontent.com/76492681/104016690-b7846a80-51ae-11eb-9d8c-ccb3f87df4d1.png)

Here is the window when opened via GIMP:

![image](https://user-images.githubusercontent.com/76492681/104016735-cbc86780-51ae-11eb-98c1-b5268fbdc4ea.png)

Hope that helps.

Please let me know if there's anything else I can do.

Kind regards.

**Comment by johnny-bit** [comment] 2021-01-10 18:20
@Jehan - PING! :P

**Comment by Nilvus** [comment] 2021-01-17 23:04
@onlinebowline: could you just uncheck "modify selected theme with CSS tweaks below" in preferences and close them and then darktable. After that, could you test again launching darktable from Gimp to see if you still have the issue. Your issue could be related to user.css file (we have had recently a similar issue just for a wrong typo in italian translation).

**Comment by Jehan** [comment] 2021-01-18 15:08
Sorry all for the late intervention! This start of 2021 has made me late on quite some things!

Anyway I just looked at the code and saw that the stdout and stderr were already printed to stdout if `DARKTABLE_DEBUG` environment variable was set. Yet not the environment list. So since this code was already there, I added the environment list, and even pushed it to our main branches (2.10.x and 2.99.x). The CI is currently running, once it finishes, you can probably just swap the binaries for the plug-in.

But I realize we still have not updated the CI to build for Windows on the 2.10.x branch. Would you mind testing if the issue also exists on the development build @onlinebowline ? Find the dev version at: https://www.gimp.org/downloads/devel/
If it does (I think it will, because there is not much difference between the 2 branches, regarding this plug-in):

- Download this pipeline: https://gitlab.gnome.org/GNOME/gimp/-/jobs/1093426/artifacts/download
- Unzip it somewhere
- Start a `cmd` prompt.
- In the prompt, run:
```
setx DARKTABLE_DEBUG 1
```
Note: I am not a Windows user. This is apparently how you set an environment according to this [page I found](https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt). If you know better, don't hesitate to do your way. 🙂
- Close the prompt (apparently it should be set globally with `setx` if I understood correctly).
- Start GIMP from the downloaded archive (`gimp-w64/gimp.cmd`). It should open its own shell with stdout/stderr and environment listing. Then you can paste infos here.

**Comment by Jehan** [comment] 2021-01-18 15:10
P.S.: of course, maybe test what @Nilvus suggested first.

**Comment by onlinebowline** [comment] 2021-01-23 21:29
Sorry, I haven't had an awful lot of time to look at this recently, I will try tomorrow. If I can't manage tomorrow, I will do it as soon as I can. Thanks for the help folks.

**Comment by onlinebowline** [comment] 2021-01-25 18:58
> @onlinebowline: could you just uncheck "modify selected theme with CSS tweaks below" in preferences and close them and then darktable. After that, could you test again launching darktable from Gimp to see if you still have the issue. Your issue could be related to user.css file (we have had recently a similar issue just for a wrong typo in italian translation).

I have tried this, and it does not fix the problem.

Incidentally when I uncheck the box, and I click 'Save and apply' the box gets automatically re-checked. Is that supposed to happen? It seems odd to me. 

For the sake of clarity: I tried both ways - I have tried unchecking the box using the procedure @Nilvus suggested (i.e. without clicking 'Save and apply') and while the box remains unchecked when DT was re-launched, the GUI issue persisted. I also tried clicking 'Save and apply', the box remained checked and the GUI issue persisted.

I'll now see if I can try @Jehan 's suggestion and get back to you.

**Comment by onlinebowline** [comment] 2021-01-25 19:26
> * Download this pipeline: https://gitlab.gnome.org/GNOME/gimp/-/jobs/1093426/artifacts/download

@Jehan the link doesn't work for me.

Also, forgive me, I may need a hand with some of this - I've not done much like this before, so I may need a hint if I get stuck.

**Comment by Jehan** [comment] 2021-01-25 19:55
@onlinebowline Ah yes, there is a limited time for data retention.

This link should give you the direct link to the last successful build artifacts for the master branch: https://gitlab.gnome.org/GNOME/gimp/-/jobs/artifacts/master/download?job=win64-nightly

**Comment by Nilvus** [comment] 2021-01-25 20:02
> > @onlinebowline: could you just uncheck "modify selected theme with CSS tweaks below" in preferences and close them and then darktable. After that, could you test again launching darktable from Gimp to see if you still have the issue. Your issue could be related to user.css file (we have had recently a similar issue just for a wrong typo in italian translation).
> 
> I have tried this, and it does not fix the problem.
> 
> Incidentally when I uncheck the box, and I click 'Save and apply' the box gets automatically re-checked. Is that supposed to happen? It seems odd to me.

'Save and apply' is inside editor text, not outside, so you need to click on it only if you change something in the editor CSS AND want to apply it. Text is clear as it precise "apply".

> For the sake of clarity: I tried both ways - I have tried unchecking the box using the procedure @Nilvus suggested (i.e. without clicking 'Save and apply') and while the box remains unchecked when DT was re-launched, the GUI issue persisted. I also tried clicking 'Save and apply', the box remained checked and the GUI issue persisted.

First thing (without clicking on button and so box remains unchecked was the test wanted to check). Thanks.

**Comment by onlinebowline** [comment] 2021-02-02 18:26
@Jehan I managed to download and unzip the artifacts from the master branch. I also ran the setx successfully.

Now, I'm sure I'm being stupid, but GIMP doesn't seem to think I have DT when I install the master branch the way you suggested.

![image](https://user-images.githubusercontent.com/76492681/106644751-67b57b00-6583-11eb-981c-9379580cbc96.png)

DT is definitely there. I don't know what's going wrong.

Apologies if I'm being an imbecile. I'm not used to working with the master branch like this.

**Comment by Jehan** [comment] 2021-02-02 19:01
> Apologies if I'm being an imbecile.

Nobody is being an imbecile, no need to apologize. 🙂

Could you confirm me if the program is installed where the plug-in is apparently trying to run it from (`C:\Program Files\darktable\bin\darktable.exe`)?

**Comment by onlinebowline** [comment] 2021-02-02 19:15
> > Apologies if I'm being an imbecile.
> 
> Nobody is being an imbecile, no need to apologize. 🙂

:)

![image](https://user-images.githubusercontent.com/76492681/106650547-f11c7b80-658a-11eb-81e0-3cfd2496b1e5.png)

@Jehan Confirmed!

**Comment by onlinebowline** [comment] 2021-03-09 11:07
Sorry, I really don't know what my next steps are to investigate this issue - I don't really have the technical expertise to investigate on my own. @Jehan do you have any other suggestions that I could try, or anyone else for that matter?

Thanks again!

**Comment by Jehan** [comment] 2021-03-09 11:28
@onlinebowline Could you try to call:

```
C:\Program Files\darktable\bin\darktable.exe
```
in a `cmd` terminal and see if darktable opens properly with this?

Then run:

```
C:\Program Files\darktable\bin\darktable.exe --version
```

And tell us if this works fine too (this is what the code is trying to run in the part where it fails for you).

Note that there is a whitespace in the binary path (inside `Progam Files`) and I am guessing it has to be escaped, but I am not sure what is the escape character on Windows (on a Linux shell, it's usually `\`). I let you take care of fixing the path with proper escaping as needed.

**Comment by onlinebowline** [comment] 2021-05-12 13:14
Sorry, I haven't been able to do much investigating recently.

I did discover something interesting though @Jehan - I discovered that the issue only occurs if darktable is installed on my secondary hard drive (on both my desktop and  my laptop). The issue is still there with both current stable versions of darktable and GIMP installed (3.4.1.1 and 2.10.24 respectively).

Does that help to diagnose the problem?

**Comment by jenda69** [comment] 2021-05-14 20:41
Hello, I encountered same issue with interface mangled as in the first post. I'm on Windows 10, Darktable is on my secondary drive too. And I'm not starting the Darktable from Gimp. It appears like that if I import/open RAW file from the Windows Explorer.

I did short investigation and found that this happens when working directory is not set Darktable folder.
Example:
A) I start cmd.exe. Current working directory is C:\Users\MyUser\> and I type D:\Programs\Darktable\bin\darktable.exe -> Darktable starts with UI incorrectly displayed.
B) I start cmd.exe. Switch to D: and then "cd D:\Programs\Darktable\bin\". Current working dir is now bin directory. I start D:\Programs\Darktable\bin\darktable.exe just like last time -> it starts just fine, UI is correctly displayed. (I can add path to my raw file to the command and it opens just fine in this case, too)

I guess when program is started using associated file in Windows, working directory is not correctly set and it ruins the UI for some reason. GIMP probably doesn't set working directory, too.

**Comment by 21gs** [comment] 2021-09-11 20:40
I'm also having this issue

> I guess when program is started using associated file in Windows, working directory is not correctly set and it ruins the UI for some reason. GIMP probably doesn't set working directory, too.

This appears to be the case for me too on Windows 10, but I have always opened the associated files from Windows Explorer. Now when I do it is showing the UI incorrectly. If I open Darktable on its own, the UI displays correctly. I have tried removing Darktable and GIMP from my PC and reinstalling both the latest versions at the time of this reply.

**Comment by johnny-bit** [comment] 2021-09-11 21:01
So the problem might be that resources to be loaded are not being found due to invalid path locations... Now I wonder what paths darktable TRIES to open while called from "incorrect" path... Next question would be how to correct that.
@codingdave - would #5086 have something to do with darktable being called from incorrect relative working dir not being able to load resources?

**Comment by 21gs** [comment] 2021-09-11 21:01
@jenda69 Going off of your investigating and my uninstalling and still having the issue, I went full sledgehammer and scrubbed my registry of anything "darktable" after another uninstall. This fixed the issue!!! 

There was a key including darktable located at the path below that I suspect may have been the problem, but because I deleted all entries labeled "darktable" I can't be sure. I suspect it was this one because it sounds like it's something to do with the Darktable launching, and it is no longer present after installing again. Anyways, this fixed my issue but as always, **_please mess with your own registry at your own risk_**.

`HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FeatureUsage\AppLaunch`

**Comment by 21gs** [comment] 2021-09-11 21:08
@johnny-bit See my reply above, but also I may have spoke to soon. It seems to have temporarily fixed the issue but it comes back the next time launching from Explorer. Sounds like you are on the right track and it's perhaps getting stuck somewhere in the registry.

**Comment by 21gs** [comment] 2021-09-12 15:57
I believe I've found a workaround, but I still don't know what the root cause is or why this fixes it. Perhaps someone smarter than myself can figure it out.

It seems that the UI only breaks if opening a RAW file directly from my SD card to GIMP which then calls darktable to open. If I first move the RAW file to my C: drive and open it the same way, the UI opens correctly. Additionally, whichever method I use seems to 'stick' if I leave the file open in GIMP after editing in darktable. 

So it seems to go like this: 

1. open a RAW file from my SD card to GIMP
2. darktable gets called to open, UI is broken
3. edit file and close darktable, file opens in GIMP
4. leave file open in GIMP
5. now no matter where I open a file from the UI will be broken

And conversely, if I do the same thing but starting from opening the file from my C: drive, the UI is 'stuck' in a working state no matter where I open a file from. 

Hopefully this explanation makes sense. So far in my case the behavior described above is 100% reproducible. I'm curious if anyone else experiencing this issue can reproduce this behavior, and perhaps shed some light on what the problem may be.

**Comment by codingdave** [comment] 2021-09-22 15:33
Hi @21gs 

can you please start darktable from the command line with `C:\Path\To\darktable.exe -d dev Path\To\Image`?

If I understand you correctly there are these 2 scenarios:
1. open raw file in darktable via gimp shows a *working* darktable UI if and only if the raw file is on the C drive
2. open raw file in darktable via gimp shows a *non-working* darktable UI if and only if the raw file is on the SD card (lets call it D drive but use your real drive number below).

I want you to share the output from darktable for all scenarios below. Use cmd.exe.
1. - `cd \D C:\`
   - `C:\path\to\darktable\darktable.exe -d dev C:\path\to\image`
    
2. - `cd \D C:\`
   - `C:\path\to\darktable\darktable.exe -d dev D:\path\to\image`

3. - `cd \D D:\`
   - `C:\path\to\darktable\darktable.exe -d dev C:\path\to\image`
    
4. - `cd \D D:\`
   - `C:\path\to\darktable\darktable.exe -d dev D:\path\to\image`   
    
5. - `cd \D C:\path\to\darktable`
   - `C:\path\to\darktable\darktable.exe -d dev C:\path\to\image`
    
6. - `cd \D C:\path\to\darktable`
   - `C:\path\to\darktable\darktable.exe -d dev D:\path\to\image`

7. - `cd \D C:\path\to\image`
   - `C:\path\to\darktable\darktable.exe -d dev C:\path\to\image`
    
8. - `cd \D D:\path\to\image`
   - `C:\path\to\darktable\darktable.exe -d dev D:\path\to\image`

if you have spaces in the path, put double quotes around the parameter:
C:\Programs\darktable\bin\darktable.exe -d dev "D:\Images\2021 22 09\123.NEF"

@johnny-bit git branch --contains 3a42bcc8ea0a54d040fce3f1cce3725bf5abec60. #5086 got merged into 3.6 but this issue seems to stem from the 3.2.1 era.

**Comment by 21gs** [comment] 2021-09-30 15:14
@codingdave Hi Dave - see my results below. It seems like it opens broken consistently when the working directory is the SD card.

1. Working
2. Working
3. Broken
4. Broken
5. Working
6. Working
7. Working
8. Broken

Notice even in scenario #3, I am only working out of the D:\ drive but open the file from the C:\ drive, and the UI still breaks. What this means is still beyond me, hopefully this offers some insight to you or someone else.

**Comment by codingdave** [comment] 2021-09-30 15:25
Hi @21gs

> I want you to share the output from darktable for all scenarios below. Use cmd.exe.

Thanks for the feedback but the dt output is missing.

I just checked, windows does not show anything on the cmd line. So where are the logs? Anyone?

**Comment by 21gs** [comment] 2021-09-30 15:27
@codingdave correct there was no output to the command line so I figured you just meant the resulting behavior.

**Comment by codingdave** [comment] 2021-09-30 15:44
@21gs if you do 

> darktable.exe -d dev > D:\logfile.txt 
 
you should see some feedback. Please try if that works and paste the results here. Thanks.

**Comment by codingdave** [comment] 2021-09-30 15:47
If I start dt like that:

>D:\>"C:\Program Files\darktable\bin\darktable.exe" -d dev > D:\logd.txt

I get this feedback:

> dt_gui_load_theme: error parsing combined CSS: <data>:1:77Failed to import: Error opening file \Program Files\darktable\share\darktable\themes\darktable.css: No such file or directory

This will explain the behavior you describe

**Comment by 21gs** [comment] 2021-09-30 16:10
I do not see that error, see my output below when launching the same as scenario #3 with the broken UI.

>0.000096 application_directory: C:\program files\darktable\bin
0.000325 darktable.datadir: C:\program files\darktable\share\darktable
0.000410 darktable.plugindir: C:\program files\darktable\lib\darktable
0.000469 darktable.localedir: C:\program files\darktable\share\locale
0.012998 darktable.configdir: C:\Users\X\AppData\Local\darktable
0.014789 darktable.cachedir: C:\Users\X\AppData\Local\Microsoft\Windows\INetCache\darktable
0.014864 darktable.sharedir: C:\program files\darktable\share
0.014945 darktable.tmpdir: C:\Users\X\AppData\Local\Temp
0.014954 new_xdg_data_dirs: (null)
1.079079 kernel directory: C:\program files\darktable\share\darktable\kernels

**Comment by codingdave** [comment] 2021-09-30 16:12
The error shows up only on the command line for me, not the log files. Can
you confirm you see what I reported?

21gs ***@***.***> schrieb am Do., 30. Sept. 2021, 18:10:

**Comment by 21gs** [comment] 2021-09-30 16:13
Ah yes I do see that in the command line, sorry I missed that.

**Comment by codingdave** [comment] 2021-09-30 20:44
@21gs Do you find darktable.css under configdir or datadir (see your logs for the path). Do you find the file at "C:\Program Files\darktable\share\darktable\themes\darktable.css"?

**Comment by codingdave** [comment] 2021-10-01 06:19
I believe we have enough information to work on the case. I can reproduce it on windows.

**Comment by codingdave** [comment] 2021-10-01 22:58
If possible @21gs can you test that branch?

**Closed** 2021-10-02 10:15 UTC
Labels: understood: incomplete, scope: UI, scope: windows support

**Comment by 21gs** [comment] 2021-10-02 14:54
@codingdave please forgive my ignorance, but could you help me out with how I would go about doing that?

**Comment by codingdave** [comment] 2021-10-02 15:30
I'm not sure if you can download the build artifact. But you can build the
master branch out wait till the next release.
Warning: master is unstable and not meant for production!

21gs ***@***.***> schrieb am Sa., 2. Okt. 2021, 16:54:

**Comment by 21gs** [comment] 2021-10-02 15:32
That seems a bit over my head so I will wait til the next release, thank you for working on this!

**Comment by codingdave** [comment] 2021-10-02 15:33
You're welcome and thanks for helping us fix it!

21gs ***@***.***> schrieb am Sa., 2. Okt. 2021, 17:32:

**Comment by 21gs** [comment] 2021-10-02 15:35
No problem. Happy to report back if it's working correctly after the new release comes out if that would be useful.

**Comment by paperdigits** [comment] 2021-10-02 19:30
It would be better to grab one of the weekly darktable packages for windows that are provided on discuss.pixls.us and test it before the release, that way it can be a verified fix when the next release comes.
