### ISSUE TITLE
DT sending midi out all the time

### ISSUE THREAD

**Issue by bengtfalke** [darktable-org/darktable#10785] opened 2022-01-03 13:35 UTC
As soon as I start DT the midi out led on my Roland usb midi interface starts flashing. This indicates that DT sends midi out even if no midi controller is used or specified, This is not a normal behaviour of midi equipment and should be changed in my opinion as it is quite annoying and will affect all midi equipment.

darktable version : 3.8
OS : Win10 19042.1288
AMD Ryzen 9 3900 processor
Memory : 32 GB
Graphics card : Gigabyte GeForce RTX 2070 SUPER OC 3X
Graphics driver : 30.0.14.9613
OpenCL installed : yes
OpenCL activated : yes
M2 SSD disks
Roland UM-One usb midi interface
M-audio air 192/14 external midi based sound card

**Comment by dterrahe** [comment] 2022-01-03 14:45
duplicate of #10687

As a temporary solution disable all midi by adding the following line to darktablerc:
plugins/midi/devices=-

**Closed** 2022-01-15 10:07 UTC
Labels: scope: UI
