### ISSUE TITLE
nightly build - darktable macOS crashes on clicking any link in 'About darktable' dialog

### ISSUE THREAD

**Issue by pejax** [darktable-org/darktable#17692] opened 2024-10-19 11:45 UTC
### Describe the bug

See title

### Steps to reproduce

Click on 'About darktable'
Click on 'website' OR click on 'Credits -> Victor Forsiuk'

### Expected behavior

Display link in default browser

### Where did you obtain darktable from?

GitHub nightly

### darktable version

4.9.0+884~g0a688918e9

### What OS are you using?

Mac

### What is the version of your OS?

Sequoia 15.0.1

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

M1

**Comment by zisoft** [comment] 2024-10-19 17:08
This is a [bug in glib](https://gitlab.gnome.org/GNOME/glib/-/issues/3484), should be fixed with glib 2.82.2

**Comment by zisoft** [comment] 2024-10-23 16:56
glib 2.82.2 is now released and the issue is fixed.

**Closed by zisoft** 2024-10-23 16:56 UTC
Labels: bug: upstream, scope: macos support

**Comment by pejax** [comment] 2024-10-23 20:37
The links work now - but: closing the 'About' box (either window icon or close button) after clicking a link (http/mailto) crashes darktable.
