### ISSUE TITLE
Error: Unhandled Exception when attempting to open the Application 

### ISSUE THREAD

**Issue by drol343** [darktable-org/darktable#11452] opened 2022-04-03 01:59 UTC
**Describe the bug/issue**
After loading the software successfully... and then try to open the application... it gives me the error:
_An unhandled exception occurred.
Backtrace will be written to:
C:\Users\drolf\AppData\Local\Temp\darktable_bt_LNTPJ1.txt after you click on the OK button_
See Copy of Backtrace txt file at end of this report... 

**To Reproduce**
Please provide detailed steps to reproduce the behaviour, for example:
_1. Download Application
2. Install Application (Successfully)
3. Attempt to Open 
4. Get Error message as noted above_

**Expected behavior** 
_Application would Open_

**Screenshots** Upon trying to Open App: _NUMBER 1_
_![image](https://user-images.githubusercontent.com/76408572/161406459-029ba28f-6732-446d-b808-9428cf41d41f.png)_

**Screenshots** Upon trying to Open App as ADMIN: _NUMBER 2_
_![image](https://user-images.githubusercontent.com/76408572/161406512-6a0932eb-5e14-471e-9188-15e50d14d754.png)_

**Which commit introduced the error**
_Just Clicking on the Application in the Start Menu_

_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._A bisect is much appreciated and can significantly simplify the developer's job._

_I have to be honest... I did not understand the instructions. I am 71 years old and don't Code any languages._

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* [darktable-3.8.1-win64.exe](https://github.com/darktable-org/darktable/releases/download/release-3.8.1/darktable-3.8.1-win64.exe)
* OS                : _Windows 11; Ver 21H2;OS Build 22000.593; Experience Pack 1000.22000.593.0; Installed 2/21/22_  
* Memory            : _64 GB_
* Graphics card     : _NVIDIA GeForce GTX 1660 SUPER_
* Graphics driver   : _Ver 30.0.15.1123_
* OpenCL installed  : _??? OpenCL.dll in C:\Windows\System32 dated 1/11/2022 ??? 
* OpenCL activated  :  _Not sure???_
* Desktop           : _HP Envy Desktop, TE01-2250xt CTO_

**Additional context**
__Please provide any additional information you think may be useful, for example:__

[Darktable Backtrace - darktable_bt_LNTPJ1 4-2-2022.txt](https://github.com/darktable-org/darktable/files/8403640/Darktable.Backtrace.-.darktable_bt_LNTPJ1.4-2-2022.txt)

_I am just an average 71 year old PC user and I need Photo and Video software.
My PC is a current HP with; 64MB Ram; 1GB SSD; 2GB HDD; NVIDIA 1660 SUPER; WIN 11_

**Comment by Nilvus** [comment] 2022-04-03 07:06
Duplicate of #10767 and not a darktable issue. Read johnny-bit answer in #10767. Not directly as it's about an issue on OpenCL pack in Windows 11. We can't do anything here. You could test, waiting that this issue is fixed in OpenCL compatibility pack in Windows, to deactivate OpenCL support in darktable preferences (in processing tab). darktable processing should just be slower without OpenCL.

If you can't open darktable, you could open darktable shortcut launcher properties (with right-click on it) and add `--disable-opencl` after `darktable.exe` (put a space between them!).

**Closed by Nilvus** 2022-04-03 07:06 UTC
Labels: duplicate

**Comment by drol343** [comment] 2022-04-10 21:24
4/10/22
 
Anybody out there?
 
From: ***@***.*** ***@***.***> 
Sent: Tuesday, April 5, 2022 8:28 PM
To: 'darktable-org/darktable' ***@***.***>
Cc: ***@***.***
Subject: RE: [darktable-org/darktable] Error: Unhandled Exception when attempting to open the Application (Issue #11452)
 
Thanks for your input.
 
So, this product will not work with Windows 11 until OpenCL pack is fixed?
 
Would it make sense to just state that for now at your download site?
 
I tried what you asked as best I could… but to no avail???
 
"C:\Program Files\darktable\bin\darktable.exe" --disable-opencl

"C:\Program Files\darktable\bin\darktable.exe --disable-opencl”

 
"C:\Program Files\darktable\bin\darktable.exe" disable-opencl

"C:\Program Files\darktable\bin\darktable.exe disable-opencl”

**Comment by Penguin1950** [comment] 2022-08-11 19:58
I get the same thing when trying to start Darktable,  I am running Windows 10  not W11.  I don't think it's a w11 issue.

**Comment by drol343** [comment] 2022-10-11 08:07
Thanks for your input.
 
So, this product will not work with Windows 11 until OpenCL pack is fixed?
 
Would it make sense to just state that for now at your download site?
 
I tried what you asked as best I could… but to no avail???
 
"C:\Program Files\darktable\bin\darktable.exe" --disable-opencl

"C:\Program Files\darktable\bin\darktable.exe --disable-opencl”

 
"C:\Program Files\darktable\bin\darktable.exe" disable-opencl

"C:\Program Files\darktable\bin\darktable.exe disable-opencl”

**Comment by vevosuperior** [comment] 2024-07-07 10:40
I'm getting the same issue. Running windows 11
