### ISSUE TITLE
Darktable pink issues in Image with Panasonic Lumix G81

### ISSUE THREAD

**Issue by BenBeFree** [darktable-org/darktable#10322] opened 2021-11-03 13:19 UTC
Good day,

I have problems with overexposed and underexposed RAW images. For example, the highlights are displayed in pink. Even when I generate an HDR, the highlights are pink. In other programs like Lightroom and Affinity Photo I have no problems. My camera is a Panasonic Lumix DMC G81. In Lighttable, the pictures are still displayed reasonably. If I open the image in Darkroom, the errors occur. If I export the images as EXR, Darktable saves the pink highlights in the image.

<img width="1294" alt="2021-11-03 14_20_39-2021-10-23 15_58_52-Einstellungen png ‎- Fotos" src="https://user-images.githubusercontent.com/93045238/140067699-f11475a6-0004-4166-bf2b-857cf3307464.png">

It seems to be a problem with the Panasonic camera.
I just tested it with RAW images from my Samsung S9+ phone and everything seems to be OK. I also overexposed there, but there are no pink highlights.

Best regards
Ben

**Comment by BenBeFree** [comment] 2021-11-03 13:46
ExifTool Version Number         : 12.31
File Name                       : P1170144.RW2
Directory                       : K:/OneDrive/Darktable issue
File Size                       : 18 MiB
File Modification Date/Time     : 2021:10:23 13:27:13+02:00
File Access Date/Time           : 2021:11:03 14:37:52+01:00
File Creation Date/Time         : 2021:10:23 14:31:07+02:00
File Permissions                : -rw-rw-rw-
File Type                       : RW2
File Type Extension             : rw2
MIME Type                       : image/x-panasonic-rw2
Exif Byte Order                 : Little-endian (Intel, II)
Panasonic Raw Version           : 0360
Sensor Width                    : 4816
Sensor Height                   : 3464
Sensor Top Border               : 8
Sensor Left Border              : 8
Sensor Bottom Border            : 3456
Sensor Right Border             : 4600
Samples Per Pixel               : 1
CFA Pattern                     : [Blue,Green][Green,Red]
Bits Per Sample                 : 12
Compression                     : Panasonic RAW 1
Linearity Limit Red             : 2111
Linearity Limit Green           : 2111
Linearity Limit Blue            : 2111
ISO                             : 100
High ISO Multiplier Red         : 1
High ISO Multiplier Green       : 1
High ISO Multiplier Blue        : 1
Noise Reduction Params          : 5 100 4 4 4 200 8 8 8 400 16 16 16 800 32 32 32 1600 64 64 64
Black Level Red                 : 128
Black Level Green               : 128
Black Level Blue                : 128
WB Red Level                    : 620
WB Green Level                  : 256
WB Blue Level                   : 399
Num WB Entries                  : 7
WB Type 1                       : Fine Weather
WB RGB Levels 1                 : 620 256 399
WB Type 2                       : Cloudy
WB RGB Levels 2                 : 669 256 368
WB Type 3                       : Shade
WB RGB Levels 3                 : 718 256 348
WB Type 4                       : Tungsten (Incandescent)
WB RGB Levels 4                 : 414 256 600
WB Type 5                       : Flash
WB RGB Levels 5                 : 642 256 392
WB Type 6                       : D55
WB RGB Levels 6                 : 582 256 400
WB Type 7                       : ISO Studio Tungsten
WB RGB Levels 7                 : 414 256 600
Raw Format                      : 4
X Resolution                    : 180
Y Resolution                    : 180
Resolution Unit                 : inches
Software                        : Ver.1.5
Modify Date                     : 2021:10:23 13:27:13
Y Cb Cr Positioning             : Co-sited
Sensitivity Type                : Standard Output Sensitivity
Components Configuration        : Y, Cb, Cr, -
Compressed Bits Per Pixel       : 2
Light Source                    : Fine Weather
Image Quality                   : RAW
Firmware Version                : 0.1.5.0
White Balance                   : Daylight
Focus Mode                      : Manual
AF Area Mode                    : 1-area
Image Stabilization             : Off
Macro Mode                      : Off
Shooting Mode                   : Manual
Audio                           : No
Data Dump                       : (Binary data 24584 bytes, use -b option to extract)
Flash Bias                      : 0
Internal Serial Number          : XER1710100083
Panasonic Exif Version          : 0412
Color Effect                    : Off
Time Since Power On             : 00:03:17.82
Burst Mode                      : Auto Exposure Bracketing (AEB)
Sequence Number                 : 1
Contrast Mode                   : Unknown (0x13)
Noise Reduction                 : Standard
Self Timer                      : Off (0)
Rotation                        : Horizontal (normal)
AF Assist Lamp                  : Disabled and Not Required
Optical Zoom Mode               : Standard
Conversion Lens                 : Off
Travel Day                      : n/a
Battery Level                   : Medium
World Time Location             : Home
Program ISO                     : 100
Advanced Scene Type             : 1
JPEG Quality                    : n/a (RAW only)
Color Temp Kelvin               : 5500
Bracket Settings                : 7 Images, Sequence -/0/+
WB Shift AB                     : 0
WB Shift GM                     : 0
Flash Curtain                   : n/a
Long Exposure Noise Reduction   : Off
Panasonic Image Width           : 4592
Panasonic Image Height          : 3448
AF Point Position               : none
Num Face Positions              : 0
Lens Type                       : NO-LENS
Lens Serial Number              : 0000000
Accessory Type                  : NO-ACCESSORY
Accessory Serial Number         : 0000000
Lens Firmware Version           : 0.0.0.0
Faces Recognized                : 0
Title                           :
Baby Name                       :
Location                        :
Country                         :
State                           :
City                            :
Landmark                        :
Intelligent Resolution          : Off
HDR Shot                        : Off
Burst Speed                     : 0
Intelligent D-Range             : Off
Clear Retouch                   : Off
City 2                          :
Photo Style                     : Standard or Custom
Shading Compensation            : Off
WB Shift Intelligent Auto       : 0
Accelerometer Z                 : 256
Accelerometer X                 : 2
Accelerometer Y                 : 28
Camera Orientation              : Normal
Roll Angle                      : 0.8
Pitch Angle                     : -0.6
WB Shift Creative Control       : 0
Sweep Panorama Direction        : Off
Sweep Panorama Field Of View    : 0
Timer Recording                 : Off
Internal ND Filter              : 0
HDR                             : Off
Shutter Type                    : Mechanical
Filter Effect                   : Expressive
Clear Retouch Value             : undef
Touch AE                        : Off
Monochrome Filter Effect        : Off
Highlight Shadow                : 0 0
Time Stamp                      : 2021:10:23 12:27:13
Video Burst Resolution          : Off or 4K
Multi Exposure                  : Off
Red Eye Removal                 : Off
Video Burst Mode                : Off
Diffraction Correction          : Off
Focus Bracket                   : 0
Post Focus Merging              : Post Focus Auto Merging or None
Time Lapse Shot Number          : 0
Maker Note Version              : 0152
Scene Mode                      : Off
Highlight Warning               : No
Dark Focus Environment          : No
Text Stamp                      : Off
Baby Age                        : (not set)
Sub Sec Time                    : 499
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 1920
Exif Image Height               : 1440
Interoperability Index          : R98 - DCF basic file (sRGB)
Interoperability Version        : 0100
Sensing Method                  : One-chip color area
Scene Type                      : Directly photographed
Custom Rendered                 : Normal
Exposure Mode                   : Manual
Digital Zoom Ratio              : 0
Scene Capture Type              : Standard
Gain Control                    : None
Contrast                        : Normal
Saturation                      : Normal
Sharpness                       : Normal
PrintIM Version                 : 0250
Thumbnail Offset                : 34304
Thumbnail Length                : 3236
Encoding Process                : Baseline DCT, Huffman coding
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:2 (2 1)
Jpg From Raw                    : (Binary data 252041 bytes, use -b option to extract)
Crop Top                        : 8
Crop Left                       : 8
Crop Bottom                     : 3456
Crop Right                      : 4600
Make                            : Panasonic
Camera Model Name               : DMC-G81
Strip Offsets                   : 4294967295
Rows Per Strip                  : 3464
Strip Byte Counts               : 0
Raw Data Offset                 : 256512
Distortion Param 02             : 0
Distortion Param 04             : 0
Distortion Scale                : 1
Distortion Correction           : Off
Distortion Param 08             : 0
Distortion Param 09             : 0
Distortion Param 11             : 0
Gamma                           : 2.32421875
Focus Step Near                 : 0
Focus Step Count                : 0
Flash Fired                     : No
Zoom Position                   : 0
Lens Attached                   : No
Lens Type Make                  : 0
Focal Length In 35mm Format     : 0 mm
Aperture Value                  : 1.0
Shutter Speed Value             : 1/20
Sensitivity Value               : 0
Faces Detected                  : No
WB CFA0 Level Daylight          : 1603
WB CFA1 Level Daylight          : 1024
WB CFA2 Level Daylight          : 1024
WB CFA3 Level Daylight          : 2329
White Balance Set               : Daylight
WB Red Level Auto               : 2483
WB Blue Level Auto              : 1599
Orientation                     : Horizontal (normal)
White Balance Detected          : Auto
Exposure Time                   : 1/20
F Number                        : 0
Exposure Program                : Manual
Exif Version                    : 0230
Date/Time Original              : 2021:10:23 13:27:13
Create Date                     : 2021:10:23 13:27:13
Exposure Compensation           : -3
Max Aperture Value              : 1.0
Metering Mode                   : Multi-segment
Flash                           : Off, Did not fire
Focal Length                    : 0.0 mm
Sub Sec Time Original           : 499
Sub Sec Time Digitized          : 499
File Source                     : Digital Camera
Blue Balance                    : 1.558594
Red Balance                     : 2.421875
Shutter Speed                   : 1/20
Create Date                     : 2021:10:23 13:27:13.499
Date/Time Original              : 2021:10:23 13:27:13.499
Modify Date                     : 2021:10:23 13:27:13.499
Thumbnail Image                 : (Binary data 3236 bytes, use -b option to extract)
Advanced Scene Mode             : Off
Image Height                    : 3448
Image Width                     : 4592
Image Size                      : 4592x3448
Megapixels                      : 15.8
Focal Length                    : 0.0 mm

**Comment by MStraeten** [comment] 2021-11-03 16:31
since you didn't tell us the used darktable version - it seems to be the same issue as described in #10288

**Comment by BenBeFree** [comment] 2021-11-03 17:09
Sorry !

Further information is:
 
* darktable version : 3.6.0
* OS : Win 10 Build 19042
* Memory : 32GB
* Graphics card : Nvidia GTX 1070 Max Q Design
* Graphics driver : 27.21.14.6259
* OpenCL installed : yes
* OpenCL activated : yes

**Comment by Nilvus** [comment] 2021-11-04 18:51
It's a known issue on all Panasonic Lumix caused by a rawspeed issue. So please, check issue provided by @MStraeten. Just increase by 5 values on all 4 black levels in raw black/white point module. Then create a preset to automatically apply correct values on all new images. I so close this issue as this already known and fixed in actual rawspeed development branch (fix should come in darktable 3.8).

**Closed by Nilvus** 2021-11-04 18:51 UTC

**Comment by Nilvus** [comment] 2021-11-07 16:17
Now fixed in darktable master by update of rawspeed submodule. Should be so ok for 3.8.
