### ISSUE TITLE
Pipeline order: Spot removal / Crop&Rotate in the wrong order?

### ISSUE THREAD

**Issue by rekcodocker** [darktable-org/darktable#5780] opened 2020-07-20 21:19 UTC
**Is your feature request related to a problem? Please describe.**

I find I can not remove a spot with a part of the image I cropped out.
This makes no sense as the information is available... but it can not be used anymore when Crop is applied.

I wonder if these are not accidentily in the wrong order.
I think Spot Removal should be applied first, and Crop&Rotate later.

**Comment by ptilopteri** [comment] 2020-07-20 21:38
why would one want to remove blemishes in an area being discarded?

And what is stopping you from first removing a blemish/spot and later cropping w/o regard to module order?  You are not bound to work in the order the modules are applied.  And you can change the module(s) order.

If this satisfies your question, please close the issue.

**Comment by elstoc** [comment] 2020-07-20 22:31
> why would one want to remove blemishes in an area being discarded?

I suspect the issue is more that it's not possible to take the **source** for the spot removal (and retouch) from the cropped area. I find myself changing the module order quite often for the same reason. IMO it makes more sense to put spot/retouch before crop/rotate - the order was changed in 3.0.

This is the sort of issue you get without changing the module order:

![Screenshot_2020-07-20_23-29-46](https://user-images.githubusercontent.com/9555491/87992812-f596b080-cae0-11ea-9d7d-8b82fa186625.png)

**Comment by rekcodocker** [comment] 2020-07-20 22:42
> If this satisfies your question, please close the issue.



> > why would one want to remove blemishes in an area being discarded?
> 
> I suspect the issue is more that it's not possible to take the **source** for the spot removal (and retouch) from the cropped area. I find myself changing the module order quite often for the same reason. IMO it makes more sense to put spot/retouch before crop/rotate - the order was changed in 3.0.
> 
> This is the sort of issue you get without changing the module order:


This exactly. 
I am using a _discarded_ part of the image to remove a spot in the _visible_ part. 
It seems the pipeline order applies crop first and spot-fix later; this means the information is no longer available and it leads to visible artifacts.

**Comment by ptilopteri** [comment] 2020-07-21 00:17
ah, was not explained in your original comment and the particular situation not evident.

**Comment by HansBull** [comment] 2020-07-22 17:19
Not only Crop&Rotate, but also ashift.

**Comment by aurelienpierre** [comment] 2020-07-23 11:07
Then some other people will argue that doing it the other way around results in unnecessary slowdowns.

The pipeline is now re-orderable specifically to avoid these pointless discussions : Ctrl+Shit+drag and drop on the module GUI.

**Closed by aurelienpierre** 2020-07-23 11:07 UTC
