### ISSUE TITLE
Drawn Mask in Second Instance of Sharpen Module Crashes dt 3.2.1

### ISSUE THREAD

**Issue by dwright27** [darktable-org/darktable#7065] opened 2020-11-25 15:25 UTC
**Describe the bug**
In trying to further sharpen just one area of an image, I get an "Unhandled exception" error, upon which darktable crashes after clicking "OK". 

**To Reproduce**
1. Go to Sharpen module and create a second instance. 
2. Click on "Drawn Mask" and "add circle". 
3. Add the circle to the image and adjust sharpness amount and radius.

**Expected behavior**
A circular area of my image would be sharpened. (Is that what this means?)

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 10
 - I'm not sure what OpenCL is... 
 - Graphics card: NVidia GeForce GT 755M 
 - Graphics card driver version: 21.21.13.7654

**Additional context**
 - Haven't tried another version of dt. 
 - Issue reproduced with RAW; haven't tried JPG. 
 - Haven't tried on a fresh edit. 
 
[darktable_bt_8LUKU0.txt](https://github.com/darktable-org/darktable/files/5597567/darktable_bt_8LUKU0.txt)

**Comment by dwright27** [comment] 2020-11-25 15:27
Sigh. It happened again, but this time all I did was zoom in on the image I was working on. Sorry I'm new... I'll try rebooting my pc lol.

**Comment by johnny-bit** [comment] 2020-11-25 18:23
The issue stems from troubles the 3.2.1 release had with tone equalizer. I cannot replicate on current master.
If you're able to - please try and use recent master build for testing (the CI one is not ready for install yet, sorry about that).

I'd recommend you to try looking for newest build done by community member in https://discuss.pixls.us/t/darktable-3-3-windows-build/20639?u=johnny-bit  (and for osx https://discuss.pixls.us/t/current-osx-build/13213?u=johnny-bit)

If you can try recent build and it doesn't crash - please consider closing this issue :)

**Comment by johnny-bit** [comment] 2020-12-26 08:55
@dwright27 - please try newest release. the bug should be fixed there.

**Comment by johnny-bit** [comment] 2021-01-26 08:30
I assume the problem isn't there and close this... If you still have trouble on newest release, just reply and I'll reopen so we can investigate issue further.

**Closed by johnny-bit** 2021-01-26 08:30 UTC
Labels: no-issue-activity
