### ISSUE TITLE
color calibration ui: F source list issue

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#14975] opened 2023-07-30 18:07 UTC
### Describe the bug

you can select only the first and the last item in f source list by mouse scroll

### Steps to reproduce

1, go to first tba in color calibration 
2, select illuminant: F (fluorescent)
3, move the pointer over the F source list
4, scroll by mouse wheel

### Where did you install darktable from?

flatpak

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.04

### Are you using OpenCL GPU in darktable?

None

**Comment by Nilvus** [comment] 2023-07-31 16:06
I can't reproduce but I've had once a little issue when trying to do what you precise, where there's a missing hovering some time but I can click even if I have no hover visible. I've tried several times and issue I related appears only once (on first try).
Even if you can have hover effect, could you select other items (just go on it and click on it even if "hover" effect do not appear?

If it's just hover effect not always visible, this seems more a refresh Gtk issue (little one) than a darktable issue. Most of the time, I have correct hover effect and I always can click on each item.

**Comment by vsz1lu** [comment] 2023-08-02 06:11
Hi,

All items are selectable if I click to the list, but jump from first to the last and reverse if I just hold the pointer over the list.
Otherwise it's not critical bug J 

[](url)
[Képernyőfelvétel ekkor: 2023-08-02 08-05-09.webm](https://github.com/darktable-org/darktable/assets/57588193/4bd21600-9578-409e-92ed-fa71f5a35c85)

**Comment by Nilvus** [comment] 2023-08-02 11:49
So this is just a sort of hover refresh issue and probably so a Gtk one more than a darktable one. @dterrahe: as Gtk expert, could you confirm (and maybe close this issue if I'm right as we can't do anything)?

**Comment by dterrahe** [comment] 2023-08-02 11:56
The tooltip shows that a speed adjustment of *100 is set on that widget. You can remove it by switching on shortcut mapping mode (the button to the left of the settings button) and scrolling while hovering over the widget.

**Comment by Nilvus** [comment] 2023-08-02 12:23
So is that setting the good one? Maybe a quicker speed adjustment would be better?

**Comment by vsz1lu** [comment] 2023-08-02 14:02
ok, but all other dropdown lists (much more shorter or longer) working perfectly on mouse hover scroll. only this bastard not

**Comment by dterrahe** [comment] 2023-08-02 14:45
It looks like you may have inadvertently changed the speed of this one yourself, as by default all of the widgets are set to *1 speed.

**Closed** 2023-08-03 13:44 UTC
Labels: understood: incomplete, scope: UI
