### ISSUE TITLE
EXIF data for DNG files

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#6817] opened 2020-11-09 17:19 UTC
DNG files are currently missing some critical EXIF information. If I open the same DNG file in DigiKam the EXIF data is correctly extracted. Most important is SPEED, APERTURE and FOCAL LENGTH.
Of course other information woulld also be helpful but the above 3 itams are really needed to be added.
My Camera/Phone is a HUAWEI product.

**Comment by kmilos** [comment] 2020-11-10 10:14
Duplicate of #6686, patch already submitted there. Please close.

**Closed** 2020-11-13 13:13 UTC
