### ISSUE TITLE
Highlights reconstruction breaks haze removal

### ISSUE THREAD

**Issue by gmh42** [darktable-org/darktable#4092] opened 2020-01-12 16:15 UTC
**Describe the bug**
Haze removal appears to increase haze on certain images.  The behavior differs depending on when hazeremoval is performed relative to other operations.  The pixel processing order has not been reordered.

**To Reproduce**
Unzip the attached file and load it with the associated processing XMP file.
Enable Haze Removal with default parameters.  

**Expected behavior**
Apparent haze should be reduced.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0 (also latest 3.1.0 trunk)
 - OS: Windows 10 (also Ubuntu 18.04)
 - Same behavior with and without OpenCL
 - Nvidia K2200 431.94 (Windows), 435.21 (Ubuntu)

**Additional context**
The behavior differs depending on what previous operations have been done to the image.  The attached XMP sidecar contains the compressed history stack.  If I export the image as a TIFF or JPG and edit the exported file, haze removal works as expected.  I have no previous experience with Darktable source, however I poked around and added logging in src/iop/hazeremoval.c.  I noticed the comment about computing distance_max from the PREVIEW pixelpipe vs FULL pixelpipe.  In the case where haze removal is not working as expected, distance_max is -0.187453.  When editing the exported TIFF, distance_max is  0.381375
[DSCN1262.NRW.zip](https://github.com/darktable-org/darktable/files/4050818/DSCN1262.NRW.zip)

**Comment by aurelienpierre** [comment] 2020-01-13 17:42
Tested and reproduced, but this is actually caused by highlight reconstruction in any other mode than "clip highlights".

**Comment by rabauke** [comment] 2020-01-13 23:29
Remark: The bright parts of an image are crucial for estimating the global hazy background light and the local amount of haze. The sky in the provided image are completely blown out. The haze removal module requires a properly exposed image. The haze removal module is able to deal with clipping highlights in some small portions of the image but a completely blown out sky causes problems.

I would suggest to move the default position of the haze removal module to after highlights reconstruction and after exposure.

**Comment by aurelienpierre** [comment] 2020-01-14 20:59
Haze removal is already after highlight reconstruction, since highlights work on non-demosaiced raws. That's the cause of the issue: highlights reconstruction does something wrong, in any other mode than "clipping", that leads the haze removal to a mistake.

Also, exposure can be used to raise highlights past 100%, not sure if it's a good idea to put haze removal after as a default. Is there any kind of scaling parameters that could be introduced in haze removal to adjust for `max(RGB)` of the input ?

**Comment by jenshannoschwalm** [comment] 2020-01-14 21:39
There has been #3810 discussing the highlight reconstruction with @TurboGit so it's not limited to raws.

**Comment by aurelienpierre** [comment] 2020-01-14 21:47
It is a raw module:

https://github.com/darktable-org/darktable/blob/39a47f6aa1780fb1fcb6f95130802acadbdfbe59/src/iop/highlights.c#L91-L94

**Comment by jenshannoschwalm** [comment] 2020-01-14 21:58
Yes but it's working for non-raw images too.

**Comment by aurelienpierre** [comment] 2020-01-14 22:40
Right, but for raw images it expects a Bayer/Xtrans CFA and the IOP rules should prevent moving it around demosaicing.

**Closed** 2020-01-20 14:47 UTC
Labels: priority: medium, reproduce: confirmed, scope: image processing, understood: clear

**Comment by gmh42** [comment] 2020-02-02 16:53
The clamping added in commit e7acabb did eliminate increasing haze when Highlight Reconstruction of LCh is in use, however it did not restore expected functionality to the module.  With the sample image included in the bug report, the Haze Removal module now has no effect on the image when strength is positive.  Changing highlight reconstruction to clip does enable haze removal functionality.  Should I file a separate report for that issue?

**Comment by rabauke** [comment] 2020-02-02 17:24
@gmh42 What you describe here is exactly the expected behavior, not a bug. As I explained before your image is just not suited to remove haze by the implemented method. You image is terribly overexposed. The haze removal module requires a properly exposed input. You can fix this to some degree by placing an instance of the exposure module before the haze removal and reduce exposure to some degree.
