### ISSUE TITLE
darktable-4.4.0-arm64.dmg corrupted?

### ISSUE THREAD

**Issue by AlexC70** [darktable-org/darktable#14747] opened 2023-06-22 11:33 UTC
### Describe the bug

I've installed the new v.4.4 on my MacBook Pro M1 but when I try to launch it my Mac says that Darktable.app is corrupted and cannot be opened, and that I should put it into the trash. 
I'm on MacOs Ventura 13.4 build 22F66, the downloaded file is darktable-4.4.0-arm64.dmg.
I've tried downloading the file from the Darktable website with different browsers, always with the same result. 
I've also tried downloading the .dmg file directly from GitHub, again same result.
This is why I tend to think that the original file is really corrupted.

### Steps to reproduce

Simply installation

### Where did you install darktable from?

darktable.org

### darktable version

darktable-4.4.0-arm64

### What OS are you using?

Mac

### What is the version of your OS?

MacOs Ventura 13.4 build 22F66

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment] 2023-06-22 11:38
Duplicate of #14746

**Closed** 2023-06-22 14:52 UTC
