### ISSUE TITLE
rule's menu out of windows

### ISSUE THREAD

**Issue by dim162** [darktable-org/darktable#6647] opened 2020-10-27 08:45 UTC
The rule's menu of collect images modules appears out of windows, in fullscreen & floating windows

Dt 3.3.0~git1224.ccb6d04fb, ubuntu studio 19.10, opencl on, nvidia driver 440.100, 2x nvidia graphic cards

![Screenshot_2020-10-27_09-30-38_result](https://user-images.githubusercontent.com/10468352/97276660-cb6b3200-1837-11eb-9af9-60549dfd3b71.jpg)

**Comment by elstoc** [comment] 2020-10-27 10:44
You can scroll your mouse to get the list into view. I'm not sure how much control we have over its position.

**Comment by quovadit** [comment] 2020-10-27 16:26
I have the same problem (see my duplicate #6656)

The scrolling is very weird because the whole widget moves very slow and does not immediately stop moving.

For me this is no solution. Although the grouped display is nice, this feature (which I am using a lot!) is unusable for me now!

**Comment by dim162** [comment] 2020-10-27 17:08
After scrolling the menu in the windows & restart, the menu stay in the windows

**Comment by Nilvus** [comment] 2020-10-27 18:21
It's probably more a Gtk issue than darktable one.
I don't have this behavior in my system with last master and by using Ubuntu 20.10 with Gtk+ 3.24.23.

**Comment by quovadit** [comment] 2020-11-05 20:48
Is there anything that can be done in darktable so that the widget is always positioned inside of the dt-window?

**Comment by Nilvus** [comment] 2020-11-05 21:00
As I said, it's not a darktable issue. How menu is displayed depends on Gtk library version AND, sometimes, how your desktop environment deals with Gtk library. There's nothing we can do. On my side, with one of the more recent library version and Gnome 3.38 (was the same in Gnome 3.36), I don't have this issue.

**Comment by Nilvus** [comment] 2020-11-05 21:03
You should try with Gnome environment to check what you have on your side, and by updating your Ubuntu to 20.04 or 20.10 release. That should solve the issue.

**Comment by ptilopteri** [comment] 2020-11-05 21:03
nor does kde/plasma5 on openSUSE Tumbleweed

**Comment by quovadit** [comment] 2020-11-05 21:17
I use the latest Linux Mint (20), which is based on Ubuntu 20.04 with Cinnamon 4.6.7

I'd hoped there was a way to overrule the positioning, even if the source of the problem is outside of dt.

**Comment by dim162** [comment] 2020-11-05 21:50
just scroll the menu down & restart Dt

**Comment by quovadit** [comment] 2020-11-05 22:06
unfortunately this does not work for me, I have to scroll down every time 
But if there is nothing dt can do, I'll have to live with it (or switch desktop environment...)

**Comment by dim162** [comment] 2020-11-06 07:04
Mint 20 is known to have gtk problems! You have have to search in Mint
forums, etc

**Comment by quovadit** [comment] 2020-11-06 07:06
ok, thanks a lot!

**Comment by Nilvus** [comment] 2020-11-06 16:18
@dim162: as it's not a darktable issue and you seem to have found a workaround on your side, could you close this issue? This will help darktable team to show which issues remains to works on. Thanks.

**Comment by Nilvus** [comment] 2020-12-07 06:27
@TurboGit: this issue could be closed.

**Comment by TurboGit** [comment] 2020-12-07 11:56
Closed

**Closed by TurboGit** 2020-12-07 11:56 UTC
Labels: no-issue-activity
