### ISSUE TITLE
toneequal exception

### ISSUE THREAD

**Issue by phweyland** [darktable-org/darktable#2978] opened 2019-09-23 14:59 UTC
[darktable_bt_332L8Z.txt](https://github.com/darktable-org/darktable/files/3642709/darktable_bt_332L8Z.txt)

I don't know if that's related but it was just after ctrl-Z when I tried to move from simple to advanced tab.
After restart it fails again on the same move. 
The issue has gone when I reset the module.

Another point. toneequal is not retained in favorites from one session to the other.

**Platform (please complete the following information):**
 - OS: windows
 - Version 2.7

**Comment by phweyland** [comment] 2019-09-25 08:09
no time to tweak anything, just move from simple to advanced tab (2.7.0+1833~g0fb99354d).

[darktable_bt_ZW3N8Z.txt](https://github.com/darktable-org/darktable/files/3651310/darktable_bt_ZW3N8Z.txt)

**Comment by TurboGit** [comment] 2019-09-25 08:41
> Another point. toneequal is not retained in favorites from one session to the other.

Cannot reproduce that! But maybe it is just because it crashed and so the prefs are not written into darktablerc (only written when closing dt).

**Comment by phweyland** [comment] 2019-09-25 09:04
> > Another point. toneequal is not retained in favorites from one session to the other.
> 
> Cannot reproduce that! But maybe it is just because it crashed and so the prefs are not written into darktablerc (only written when closing dt).

Even when I exit dt properly I have this behavior. Now, I have removed darktablerc and it works properly. I've got back the old darktablerc file and ... it works properly too ...

**Comment by TurboGit** [comment] 2019-09-25 09:17
BTW, I have been able to reproduce the crash, but no idea how this could happen at this time :(

**Comment by phweyland** [comment] 2019-09-25 09:26
> BTW, I have been able to reproduce the crash, but no idea how this could happen at this time :(

When it happens it's quite constant but depending on the build it may not happen. Impression there is an initialization issue somewhere.

**Comment by TurboGit** [comment] 2019-09-25 09:55
Could you test with: https://github.com/darktable-org/darktable/pull/2999 ?

**Comment by phweyland** [comment] 2019-09-25 10:10
To do that I need to clone your repository, right ?

**Comment by phweyland** [comment] 2019-09-25 10:14
currently I've built with your previous change and it doesn't crash (which is not a proof unfortunately).
I'll replicate your last change too.

**Comment by phweyland** [comment] 2019-09-25 10:27
Just built. Does not hurt. No crash so far.

**Closed** 2019-09-25 10:57 UTC
Labels: bug

**Comment by TurboGit** [comment] 2019-09-25 11:02
I'm pretty sure the crash is fixed now on master. If not we'll reopen :)
