### ISSUE TITLE
Crop and Rotate resets to defaults very often when I enter darkroom

### ISSUE THREAD

**Issue by hyphone** [darktable-org/darktable#7749] opened 2021-01-08 14:21 UTC
**Describe the bug**
Very often when I enter the darkroom from the library my crop and rotation settings resets itself and get's added as a new step in the history as if I have done it.

**To Reproduce**
1. Select an image from the lighttable and double click on it
2. often (I cannot find the pattern when it happens or not, seems random) the crop and rotation settings are lost (or better resetted because a new history entry appears that says "crop and rotation")

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - Ubuntu 20.10
 - Flatpak from Flathub and deb from OBS

Does anyone else experience this since the new versions?

**Comment by lorempipsum** [comment] 2021-01-17 19:34
I'm using darktable on Windows and getting the same problem. Really frustrating!

**Comment by hyphone** [comment] 2021-02-20 22:17
This is still a problem for me with 3.4.1

**Comment by hyphone** [comment] 2021-02-21 09:22
- Darktable Version: 3.4.1
- Fedora 33
- Fedora RPM

https://user-images.githubusercontent.com/6410852/108610810-e9f1cc00-73d8-11eb-8fad-edee080f7758.mp4

**Comment by hyphone** [comment] 2021-03-13 15:04
I'm really wondering that no one else has this issue. It happens to me really every time when I select an image (working mostly with local copies).

**Comment by nemethmiklos** [comment] 2021-06-08 19:54
This occurred with me numerous times, it has something to do with the already quirky working crop and rotate tool. If the last tool you selected is crop & rotate, then you will get this error. It should not work this way, it is an error.

**Possible workaround until fixed:**
simply crop & rotate how you want, and select an other tool before you exit the darkroom to the lighttable.

**Comment by AlicVB** [comment] 2021-06-09 11:09
I can't reproduce... so either it is fixed in current master, either there's some other steps involved... Some questions : 
- by any chance, are you able to test the "master" branch and, if yes, reproduce the issue ?
- does it happen with a "fresh" install : rename all your config dir, lauch dt and import an image with no associated xmp
- open an image in darkroom, define a crop area, go back to lighttable, reopen the image in darkroom and go to crop&rotate module, is the previously defined cropped area still here, or has it been reset ?
- in you can test master, does it happens also in the new "crop" module ?

Thanks !

**Comment by nemethmiklos** [comment] 2021-06-09 13:04
I need a little time to test it, but I will!

**Comment by nemethmiklos** [comment] 2021-06-09 17:48
I tested it on the master branch and I could not reproduce it either. Aldo it works differently, than the version I used before. The older one remembered the latest used tool, and showed the tool every time I entered the darkroom. Maybe this caused the problem. The version from the master branch resets the tool view every time I enter the darkroom. The crop module works fine, too.

**Comment by Nilvus** [comment] 2021-06-20 21:01
I remember having this issue some times ago, especially with 3.3 master (so developement version that goes to 3.4.x releases. I can't reproduce too now in master. I think we can consider this issue fixed. @hyphone and @lorempipsum: feel free to reopen (or ask for it) if you can reproduce with darktable 3.6 which will be released in about 2 weeks.

**Closed by Nilvus** 2021-06-20 21:01 UTC
Labels: bug: pending, reproduce: peculiar, scope: image processing

**Comment by vvivanloc** [comment] 2021-10-16 09:45
I  was confused to. My crop settings were saved in xmp files but Darktable seems not apply cropping to thumbnails. Any hint to force a better preview in lighttable view?
