### ISSUE TITLE
Look for updated xmp files on startup doesn't work on darktable 3.6.0

### ISSUE THREAD

**Issue by elman22** [darktable-org/darktable#9527] opened 2021-07-13 21:31 UTC
**Describe the bug/issue**
I changed xmp on different PC, then synced to my main PC, but darktable didn't prompt me to update local DB from changed xmp.

**To Reproduce**
1. Import an image on PC1
2. Import an image on PC2
3. Modify image on PC2
4. Copy xmp from PC2 to PC1

**Expected behavior**
PC1 should prompt me to update local DB.

**Platform**

* darktable version : 3.6.0
* OS                : Manjaro Linux / Kernel 5.12.16
* Memory            : 16 GB
* Graphics card     : NVIDIA GeForce GTX 970
* Graphics driver   : 470.42.01
* OpenCL installed  : yes
* OpenCL activated  : yes, but darktable fails to enable it
* Desktop           : Plasma 5.22.3

 - Can you reproduce with a RAW or Jpeg or both? **both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - Do you use lua scripts?
   - What lua scripts start automatically? 
   > require "tools/script_manager"
require "official/import_filter_manager"
require "official/import_filters"
require "official/save_selection"
require "contrib/kml_export"
require "contrib/quicktag"
require "contrib/rate_group"
require "contrib/clear_GPS"
require "contrib/select_untagged"
require "contrib/photils"
   - What lua scripts were running when the bug occurred?
   > require "tools/script_manager"
require "official/import_filter_manager"
require "official/import_filters"
require "official/save_selection"
require "contrib/kml_export"
require "contrib/quicktag"
require "contrib/rate_group"
require "contrib/clear_GPS"
require "contrib/select_untagged"
require "contrib/photils"

**Comment by johnny-bit** [comment] 2021-07-14 07:00
Works flawlessly for me... on current master.

do you have `look for updated xmp files on startup` enabled?

also - do paths have non-ascii chars in them on linux? there was issue https://github.com/darktable-org/darktable/issues/9333 that said that the crawler might fail on that.

that's fixed by https://github.com/darktable-org/darktable/pull/9334 which will be part of 3.8 release.

**Comment by elman22** [comment] 2021-07-14 07:44
> do you have look for updated xmp files on startup enabled?

Yes. I also tried to disable it and enable again.

> also - do paths have non-ascii chars in them on linux?

There was `á` letter in path, but I think it used to work with letters like `ý`, `é` and `ó`. Will investigate later and let you know.

**Comment by elman22** [comment] 2021-07-14 16:14
I confirm that xmp changes are detected on paths with just ASCII chars. So I guess path normalization will fix this issue as well.

**Comment by johnny-bit** [comment] 2021-07-14 16:52
can you try compile current master or 3.6.1 branch and see if it works for you and if it does close the issue?

**Comment by johnny-bit** [comment] 2021-08-14 07:57
The issue is fixed on master and on 3.6.x branch. I forgot to say so and close this earlier.

**Closed by johnny-bit** 2021-08-14 07:57 UTC
Labels: scope: DAM, bug: fixed, no-issue-activity

**Comment by elman22** [comment] 2021-08-14 15:25
Sorry, I was unable to compile master. I will check it when 3.6.1 is released. Thanks a lot.

**Comment by elman22** [comment] 2021-09-28 08:47
I can confirm that this bug is indeed fixed in 3.6.1. Darktable even found some year old unprocessed xmp files 🙂
Thanks :+1:
