### ISSUE TITLE
White balance switches from 'spot' to 'camera'

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#3521] opened 2019-11-22 08:14 UTC
**Describe the bug**
After choosing the white balance preset 'spot' and applying a new white balance with the area picker correctly says 'preset: spot'.
When using the color picker on the left side or switching between 'point' and 'area' the preset on the right side in the white balance module says 'preset: camera' with the white balance chosen with spot

**Expected behavior**
'preset' in the white balance module should stay at 'spot' unless chosen otherwise.

**Screenshots**
1. Start with original white balance from camera
![Bildschirmfoto von 2019-11-22 09-03-50](https://user-images.githubusercontent.com/49001045/69408555-807f9b00-0d07-11ea-9180-80da1862658c.png)
2. Manually chosen white balance 
![Bildschirmfoto von 2019-11-22 09-04-03](https://user-images.githubusercontent.com/49001045/69408711-d2282580-0d07-11ea-85c5-7062e8eb222f.png)
3. White balance says 'preset: camera' after changing the color picker from 'area' to 'spot' (clicking on the picker next to it does the same)
![Bildschirmfoto von 2019-11-22 09-04-12](https://user-images.githubusercontent.com/49001045/69408837-056ab480-0d08-11ea-9f33-64ee7c80d389.png)

**Platform (please complete the following information):**
DT 3.0.0rc1~git11.dc641cdc9 on Ubuntu 18.04

**Additional context**
Similar to https://github.com/darktable-org/darktable/issues/3228

**Comment by junkyardsparkle** [comment] 2019-11-23 16:53
Glad to know it's not just me. I noticed while testing something with some downloaded RAW files that this seemed to **not** be happening in that case, so it's possible that it somehow depends on the type of camera RAW. I'll try to remember to test that further at some point.

**Comment by hqhoang** [comment] 2020-01-05 02:17
Just noticed it, too. Set preset to Spot, move back to Lighttable or to next image, then back and it's set to Camera, although the WB doesn't change. Currently on latest from master branch.

**Comment by hqhoang** [comment] 2020-02-05 14:47
just poking so that the ticket doesn't close itself. The problem is still on master branch as of today.

**Comment by johnny-bit** [comment] 2020-12-16 10:46
The problem is now fixed (probably got fixed somewhere along the way). Now wb works with image area as expected, adding color pickers on color picker module doesn't mess things. release 3.4 won't have this problem :) (and if it does - feel free to comment with new reproduction steps as I haven't been able to replroduce)

**Closed by johnny-bit** 2020-12-16 10:46 UTC
Labels: no-issue-activity
