### ISSUE TITLE
Some jpeg files are not loading

### ISSUE THREAD

**Issue by spaceChRiS** [darktable-org/darktable#3178] opened 2019-10-18 09:37 UTC
**Describe the bug**
The jpeg images from the panorama mode of my Samsung Galaxy S7 are not loaded by darktable, instead, the skull is showing. This even happens for very small files (e.g. the approx. 14 MegaPixel 7.4 MB file attached), so it is not about file size. Interesting is, that in my Ubuntu 16.04 install, the file manager (nautilus) does not produce thumbnails of these files, so darktable is not the only software struggling with these files. Other software, e.g. the eog image viewer, show the files.

**To Reproduce**
Open the attached picture in darktable, darkroom is not loading and instead the images is shown as skull in lighttable.

**Expected behavior**
The file should show as thumbnail in lighttable and it should be possible to edit it in darkroom.

**Platform (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version: 2.6.0 and 2.7.0+452 (g4a1d98e)

**Additional context**
Unfortunately I am not (yet) able to test with a more recent version as it is difficult to get the requirements sorted on this old OS. I hope I can upgrade the OS soon, but there are other projects in the way.

![20191018_105746](https://user-images.githubusercontent.com/16524534/67083884-3e10ee80-f19c-11e9-99ed-def8c018452c.jpg)

**Comment by spaceChRiS** [comment] 2019-10-18 09:39
For some reason (old browser?) the file is not uploading (and I cannot edit my post). I have to try it from another computer later. Sorry for the inconvenience.

**Comment by chhil** [comment] 2019-10-18 11:51
I confirm the issue on 2.7.0.2001 win 10.

**Comment by junkyardsparkle** [comment] 2019-10-18 22:07
Specifically, the rawspeed error is:

`Invalid SOS parameters for sequential JPEG
Unsupported marker type 0x58
[rawspeed] (borked.jpg) virtual std::unique_ptr<rawspeed::RawDecoder> rawspeed::RawParser::getDecoder(const rawspeed::CameraMetaData*), line 91: No decoder found. Sorry.
Invalid SOS parameters for sequential JPEG
Unsupported marker type 0x58
allocation failed???`

If you look at the output of `exiftool -U` for that file, you'll see a bunch of samsung binary makernotes, including a trailer with what appears to be 3MB worth of video... removing that with exiftool doesn't fix the issue, though.

**Comment by junkyardsparkle** [comment] 2019-10-19 00:03
It sounds like [Motion Panorama mode was removed](https://www.samsung.com/global/galaxy/what-is/motion-panorama/) from the S9/S10, and [no explanations](https://us.community.samsung.com/t5/Galaxy-S10/Motion-Panorama-Feature/td-p/731701) are [forthcoming](https://eu.community.samsung.com/t5/Galaxy-S9-S9/Motion-Panorama-gone-from-S9-after-last-update/td-p/981784), so maybe they realized the file format was broken. Some applications built on libjpeg-turbo *do* display an image despite the warnings (at least geeqie and chromium) so maybe there's a workaround. Best workaround is probably to not use those kinds of proprietary phone features, though. ;-)

**Comment by jenshannoschwalm** [comment] 2019-10-22 08:22
I think this issue should be closed as it's not a dt issue.

**Comment by TurboGit** [comment] 2019-10-22 08:28
Agreed, closing.

**Closed by TurboGit** 2019-10-22 08:28 UTC

**Comment by giammi56** [comment] 2022-02-25 11:46
Hi, I am experiencing something similar with jpg pano from an S7. DigiKam works flawlessly and some jpg are loaded into dt, but any are broken (i.e., 8bit skull icon and endless loading). Is there a workaround?

**Comment by AlicVB** [comment] 2022-02-25 12:04
@giammi56 : 
this is a bug on samsung side when writing the exif datas. As a workaround, I use : 
1. https://gist.github.com/bcyrill/e59fda6c7ffe23c7c4b08a990804b269
2.  direct use of imagemagick "convert"

point 2 is needed for the cases where 1 doesn't work for some reason... All this can be done inside some lua script if needed.

Anyway, it's clearly not a bug from darktable/rawspeed !

**Comment by spaceChRiS** [comment] 2022-02-25 12:29
I was working on a different solution during the last days. If you follow the links above, you will find that the darktable error is caused by a libjpeg error which is considered a warning which could be ignored by the application. They are suggesting that this could be fixed by ignoring the warning as it is a minor error in the jpeg file, as still the data can be read easily.

Not a C programmer (or a programmer at all), I tried anyway to follow this advice from the libjpeg guys here: https://github.com/spaceChRiS/darktable/commit/cbea493da415c7157d140150f448c9eccbe12816. I wonder if this idea could have a chance to be integrated in darktable.

My whole family (also the in-laws etc.) uses the S7, and while I avoid the pano mode, I cannot tell them to do so. Still, I want to manage pictures that I get from the family (from vacations etc.) in darktable, and following the fundamental advice to never alter an original file, I want to use the original jpegs. It's a pity that most software ignores the warning of libjpeg while darktable takes it serious.

> I'm guessing files taken using normal panorama (not Motion Panorama) mode work ok?

@junkyardsparkle, no, that's not the case, my s7 has only one panorama mode that generates those broken jpegs.

**Comment by giammi56** [comment] 2022-02-25 12:42
I am not saying it is a bug. It is for the solidity of dt to be able to open as many files as possible without requiring the use to dig google to find out about a detail. DIgikam and any image preview software correctly load such images, the first impression is that dt has a bug. I would strongly suggest adding something like @spaceChRiS developed.
