### ISSUE TITLE
[win10/dt:4.0.1] GUI hang for a minute on any changes.

### ISSUE THREAD

**Issue by bartoszek** [darktable-org/darktable#12697] opened 2022-10-23 13:42 UTC
**Describe the bug/issue**
I've somehow broken DT today 😢 Single image in my collection just hangs DT on every change: even touching the star rating or color labels for this image results in ¬90s 100% cpu_core grayed out hanged GUI. Turning off all filters doesn't alleviate the issue but strangely create a duplicate of the image and copying the profile seems to fix the issue somehow ¯\\\_(ツ)\_/¯ it looks like the source of the issue is a `retouch` tool with has ¬90 circle shapes in single instance for this image. Other images works fine with similar retouch applied they just cause ~3s GUI stutter when adjusting/adding the retouch shapes. 

**To Reproduce**
Well I can't really, perhaps `Xperf` counter file would be enough to tackle the issue?

**Screenshots**
![image](https://user-images.githubusercontent.com/1213348/197395955-7315f214-cc52-48c5-8e4a-9a67468ed1d9.png)

**Platform**
* DT version : 4.0.1
* OS Name:                   Microsoft Windows 10 Pro
* OS Version:                10.0.19044 N/A Build 19044

**Comment by bartoszek** [comment] 2022-10-24 13:11
@dterrahe I've dived a bit into the issue using windows profile recorder and looks like DT get stacked for ~50s in `gtk`
![Screenshot 2022-10-24 144448 darktable Windows Profile Analyzer gtk3](https://user-images.githubusercontent.com/1213348/197533445-07ef3224-1f25-48f1-b9bd-c6085a16f8c6.png)

Actual work done in `libdarktable.dll` starts after the `gtk` and is taking a sane amount of time. 
![Screenshot 2022-10-24 144448 darktable Windows Profile Analyzer darktable dll](https://user-images.githubusercontent.com/1213348/197532572-b2c38543-33b6-4e93-b199-1ccef51e19b4.png)
I'm not really into Win/GTK but was thinking about building DT with debug enabled to snipe the problem origin, but first like to ask if there is perhaps a debug build or symbols for the release binary available somewhere?

**Comment by kmilos** [comment] 2022-10-24 13:49
> but first like to ask if there is perhaps a debug build or symbols for the release binary available somewhere?

Unfortunately not, [the nightly builds](https://github.com/darktable-org/darktable/actions/workflows/nightly.yml) Release w/o symbols... I was actually thinking of switching that over to RelWithDebInfo so they are more useful...

In any case, very interested in what you find, as Debug builds are painfully slow for me - takes tens of seconds between GUI actions 😮

**Comment by dterrahe** [comment] 2022-10-24 14:02
> looks like DT get stacked for ~50s in `gtk`

I don't know how to read the output from this tool, but in itself it is not strange to see a _lot_ of events being processed in gtk with many many layers call stacks. So I'd like to know if that is indeed where most of the _time_ is spent. Is %weight in terms of (cpu or real) time? 73% is idle (but maybe that is outside of the period where dt seemed to hang?) so maybe there's some deadlock situation or disk access? Can't really dig in without reproducing.

**Comment by kmilos** [comment] 2022-10-24 14:08
Actually, I was wrong, it looks like we have "-g" added for all builds, so the nightlies (and the released installer) will have the symbols...

**Comment by bartoszek** [comment] 2022-10-24 19:50
@dterrahe IO Time for `darktable.exe` is minute, ~100ms in 221 events with ~1.7MB of data read comprise of just dlls.
![image](https://user-images.githubusercontent.com/1213348/197609039-e443beea-0652-4615-9937-b978bd7c9189.png)
CPU Time graph 
![image](https://user-images.githubusercontent.com/1213348/197611923-cf030ff8-5d60-4cbd-9a90-ec4b953b0cc9.png)

**Comment by dterrahe** [comment] 2022-10-24 20:27
But it _is_ idling most of the time? Strange.

**Comment by kmilos** [comment] 2022-10-24 21:34
Don't want be creating noise here, but just in case: in my VSCode debug sessions, I see contant loading/unloading of libgphoto2 related plugins when idle...

**Comment by dterrahe** [comment] 2022-10-24 21:44
I see that on linux too. Polling for any newly attached cameras. But this is not the gui thread so shouldn't cause a "hang" for minutes. TBH I have no idea here.

**Comment by bartoszek** [comment] 2022-10-25 08:27
@dterrahe nope, 73% idling on 8core system just means most of the time a single thread is working (1/8*100%=12.5% clearly visible on CPU time graph) WPR records complete system activity like `perf record` on Linux (discrepancy of 15% is a result of other system activities: 73%idle+12%darktable+15other tasks ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯)

**Closed** 2023-10-22 00:18 UTC
Labels: no-issue-activity
