### ISSUE TITLE
Change leader in group [Feature Request]

### ISSUE THREAD

**Issue by ohms-law** [darktable-org/darktable#9503] opened 2021-07-11 17:37 UTC
For me shooting Raw+JPG the grouping feature in lighttable view is invaluable.
Two features that I would like to suggest for the devs to consider:

1. In preferences an option to choose whether the raw or the same (base)named jpg should be leader of a group by default (on import)
2. A keyboard shortcut to toggle through the pictures within a selected group to choose the leader

Best regards

**Comment by wpferguson** [comment] 2021-07-11 19:51
Using lua scripts, we can solve both of these.

1. We could add a post import film filter to go through the film roll and make the jpeg the group leader
2. We could add a shortcut cycle though grouped images, selecting the next one and wrapping around at the end.  We could also add another shortcut to make the selected image the group leader.

**Comment by ohms-law** [comment] 2021-07-11 19:58
>     2\. We could add a shortcut cycle though grouped images, selecting the next one and wrapping around at the end.

That is precisely what I had on mind

**Comment by johnny-bit** [comment] 2021-07-11 20:31
Isn't this essentially a duplicate of #7030 ?

**Comment by wpferguson** [comment] 2021-07-12 00:04
More like different flavor of the same problem.  #7030 was I have raw+jpeg imported and the wrong one is the leader, how can I fix it.  This is don't let that happen and ....  I have a group of images, maybe duplicates, maybe jpeg, etc and I want a shortcut to go through them with optionally a second to make them the group leader (though I think it would be quicker to expand the group and just pick the leader with a click on the group icon).

**Comment by wpferguson** [comment] 2021-08-11 03:19
Added to my todo list

**Comment by ohms-law** [comment] 2021-08-12 11:09
Very cool. Thank you. For the other issue (preference on import), it might also provide a doable workaround (select all+toggle leader).

> (though I think it would be quicker to expand the group and just pick the leader with a click on the group icon).
That option is still there but it takes three clicks to toggle a leader on a stack consisting of two images. And those clicks need to be an a rather small target (group icon). After selecting a stack you would get the option to just press one keyboard shortcut as an alternative option.

Again, thank you very much for considering that option

**Comment by gregacom** [comment] 2021-12-16 21:45
Hi,
I would also like to have **JPEG** as a “group leaders” in the collection. How can I do that? I only process RAW files exceptionally. 
Is there any easier way without scripts to do this?

**Comment by AlicVB** [comment] 2021-12-17 18:37
@gregacom : considering the fact that dt is primarily designed for raw files, imho your FR can be seen as a "special" workflow need. And that's precisely for this situations that lua scripts are here !

**Comment by TurboGit** [comment] 2021-12-17 18:43
@AlicVB : Note that a group can be used for pictures similar and possibly all RAWs.

**Comment by AlicVB** [comment] 2021-12-17 18:44
yes, but that's not automatic afaik, and here, if I've understand well this is for automatically change the group leader...

**Closed** 2023-02-05 22:08 UTC
Labels: feature: enhancement, scope: UI, scope: DAM, lua

**Comment by ppareit** [comment] 2024-01-13 14:22
When importing a folder with both raw and jpegs, in my case .RAF and .JPG, files. How can I automatically select the jpeg as the group leader?

I see this issue is marked as completed, but I don't find the option.

**Comment by gregacom** [comment] 2024-01-14 08:21
I use Daktable only for raw files, that's why I always have lightroim
installed.  Darktable is not a 100% alternative to Lightroom.

**Comment by ptilopteri** [comment] 2024-01-14 13:33
darktable NEVER intended to be a replacement for lightoom but an alternative that is linux compatible.  lightroom is not know here.

**Comment by wpferguson** [comment] 2024-01-14 22:34
@ppareit there is now a script, contrib/jpg_group_leader.lua, that will change the group leader to the jpg image on import.  

If you already have collections of raw+jpg with the raw as the group leader, you can assign a key to the collection shortcut to change the leader to the jpg.
