### ISSUE TITLE
Fujifilm X-A10

### ISSUE THREAD

**Issue by mk989** [darktable-org/darktable#3537] opened 2019-11-23 11:21 UTC
According to issue #209 new .raw file updated. Please to add Fujifilm X-A10 to supported camera. If I can do anything else let me know.

**Comment by LebedevRI** [comment] 2019-11-23 11:25
Duplicate of https://github.com/darktable-org/darktable/issues/3534

**Closed by LebedevRI** 2019-11-23 11:25 UTC
Labels: camera-support
