### ISSUE TITLE
Nikon Coolpix P7700

### ISSUE THREAD

**Issue by osnews** [darktable-org/darktable#11796] opened 2022-05-13 12:54 UTC
Please support Nikon Coolpix P7700 in future releases of darktable too. I submitted three photos on https://raw.pixls.us/. If you need more photos please let me know. Thank you in advance.

**Comment by Nilvus** [comment] 2022-05-13 18:49
Duplicate of  #11356. Please search before posting.

**Closed by Nilvus** 2022-05-13 18:49 UTC
Labels: duplicate, scope: camera support
