### ISSUE TITLE
[Perspective module] When Crop to largest is set double clicking in the red box shown for cropping takes you to lightable view

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6888] opened 2020-11-13 10:38 UTC
3.3.0+1539~g5e4567c24

1. Use perspective module to align verticals.
2. Then select crop to largest area.
3. Red box shows largest area.
4. Now to actually crop, the first instinct is to double click (like one does n the crop module).
5. On double clicking you are taken to the lightable view with image selected.
6. Double click on the image to go back to darkroom.
7. Now all modules are collapsed and the image still has the red crop rectangle from perspective.
8. Search perspective, open that module and close it, to crop the image.

The only way to currently crop is to close the perspective module.

**Comment by chhil** [comment] 2020-11-20 13:20
Bump.

**Comment by TurboGit** [comment] 2020-11-20 13:51
In setp 5 when I'm moved to lighttable the crop is done on my side. And this is expected, double clicking on the image do move back from lighttable or darkroom. And when I go back to darktable the crop is visible but my module is still open. So I cannot reproduce, maybe some setting about the way you are set for single module open at a time ? Or something else...

**Comment by TurboGit** [comment] 2020-11-20 14:55
> Shouldn't the double click behave like in crop where the crop is done in darktable view itself?

No, in crop&rotate there is a button and you need to set the crop by double clicking on it.

**Comment by johnny-bit** [comment] 2021-06-25 20:22
I just checked in 3.7.0+1 and indeed - double click on image while doing crop inside c&r module does commit crop, while doing the same in perspective module when cropping switches to lighttable.

I think all similar operations should have similar behaviour. As I understand @AlicVB plans to do a bunch of revamps to C&R, Perspective corr & others so I guess it's up to him :)

**Comment by AlicVB** [comment] 2021-06-26 19:41
I will take care.
tbh, I've copied this feature from c&r to the new crop module, but I'm not really convinced. What it does internally is to force focus out of the module, but without collapsing it... We end with a state where you the module is still expanded, but don't has the focus (but this is not visible for the user) so to crop again, you have to expand another module and then expand again the crop module...

What I would propose is either :
1. not implement double-click at all => you have to manually quit the module
2. manually focus the module out *and* collapse it

Once implemented for the new crop module we will replicate it for the perspective module

**Comment by johnny-bit** [comment] 2021-06-26 19:44
Well, the crop behaviour with "hanging focus" sounds like a hack. So I'd recommend removing the hack (so no dbl click to apply crop)

**Comment by Nilvus** [comment] 2021-11-21 10:39
@chhil: could you test actual master and new "rotation and perspective" module? Is this new module ok now? If so, consider closing this issue. Thanks for your feedback here.

**Comment by chhil** [comment] 2021-11-22 07:26
Unfortunately, I am on a M1 Mac and can no longer build anything on Master.

**Comment by TurboGit** [comment] 2021-11-26 17:38
Just tested, this is still an issue on current master.

**Closed** 2021-11-26 22:08 UTC
Labels: scope: UI, bug: pending
