### ISSUE TITLE
Darktable not copying EXIF to GIMP

### ISSUE THREAD

**Issue by PV-2024** [darktable-org/darktable#16212] opened 2024-01-29 23:25 UTC
### Describe the bug

Clean install of Mageia v9, x86_64. Basically, you load a RAW image in to Darktable to process the image. The image in Darktable does show ALL the camera EXIF. On export to GIMP (closing Darktable), none of the EXIF is present with the image - it's been stripped.

Checking the data of the last known images that had the EXIF, the data shows;
GIMP 2.10.36 (current version - as was in Mageia8)
Darktable 3.8.0 (last version in Mageia 8 which had no problems)
Darktable 4.4.2 (current version in Mageia 9 which has the bug)

Clearly there's something wrong with Darktable. I have renamed directory /home/user/.cache/darktable so the application re-created the directory, but it made no difference. The settings to export EXIF are ticked, but it does not export.

It is not a GIMP problem, have tested with other applications.

### Steps to reproduce

- Ask image gallery application to open NEF RAW image in GIMP.
- Darktable opens up to edit image, all EXIF is displayed in Darktable,
- Close Darktable and GIMP loads the Darktable edited image for further editing, the EXIF is gone.
- Any further saving is meaningless as there's no EXIF, and I look like an idiot for uploading images with no EXIF.

### Expected behavior

Darktable should be passing ALL EXIF data of images to GIMP (or any other image editor)

### Where did you obtain darktable from?

distro packaging

### darktable version

4.4.2

### What OS are you using?

Linux

### What is the version of your OS?

Mageia 9

### Describe your system?

this is darktable 4.4.2
copyright (c) 2009-2023 johannes hanika
https://github.com/darktable-org/darktable/issues/new/choose

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.1.0
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support enabled
  libheif support enabled
  libjxl support enabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled

### Are you using OpenCL GPU in darktable?

None

**Comment by ralfbrown** [comment] 2024-01-30 01:35
Please make sure the metadata is enabled for export by clicking on the Export module's hamburger and selecting "preferences..."  Only the types of metadata with checkmarks set will be written to the resulting file.  For a few file formats like .jxl or .exr, there are further restrictions, like metadata only being written at all if **all** items are enabled.

**Comment by kmilos** [comment] 2024-01-30 07:01
See also https://github.com/darktable-org/darktable/issues/16121

**Comment by PV-2024** [comment] 2024-01-30 18:37
![Exif in Darktable - 20240130](https://github.com/darktable-org/darktable/assets/158109635/3c55f67d-89d2-48d9-93a8-c971be4f02c3)
EXIF in Darktable

![EXIF settings in Darktable - 20240130](https://github.com/darktable-org/darktable/assets/158109635/9283d605-9945-458e-bdff-0f7f107e6b51)
EXIF settings in Darktable

![No EXIF in GIMP - 20240130](https://github.com/darktable-org/darktable/assets/158109635/9f13f260-e6b7-4b6d-8cd8-37c97ec91db2)
No EXIF in GIMP sent by Darktable

**Comment by ptilopteri** [comment] 2024-01-30 22:34
works for me in openSUSE Tumbleweed 20240128 on dt master 4.7.0+410~gd352d3173

maybe you need to upgrade your version

**Comment by gi-man** [comment] 2024-01-31 00:32
Can you try opening darktable and exporting without going thru gimp to help troubleshoot?

**Comment by PV-2024** [comment] 2024-01-31 12:44
I copied / opened a photo in Darktable as stand alone, using the export in Darktable and checking that jpg file, the EXIF survives. However, that is useless to me as I cannot do further needed editing (what Darktable cannot do), so has to be sent to GIMP for further processing.

**Comment by kmilos** [comment] 2024-01-31 12:51
> the EXIF survives

There are basically two things to check here:

1. Whether the "dt to GIMP link" exports the same way as regular/standalone export and respects the export preferences (i.e. the metadata really ends up in the intermediate file the same way as regular export when all the boxes are checked) - one can use e.g. exiftool for this
2. If so, the bug is then on more likely on GIMP side and somebody has to dig there

**Comment by gi-man** [comment] 2024-01-31 13:03
There is a third possibility to what kmilos list. Are you using a LUA script?

**Comment by jenshannoschwalm** [comment] 2024-01-31 18:58
> > the EXIF survives
> 
> There are basically two things to check here:
> 
>     1. Whether the "dt to GIMP link" exports (EXR/XCF/TIFF?) the same way as regular/standalone export and respects the export preferences (i.e. the metadata really ends up in the intermediate file the same way as regular/standalone export when all the boxes are checked) - one can use e.g. exiftool for this
> 
>     2. If so, the issue is then more likely on GIMP side and somebody has to dig there

This can hopefully be done better with the new darktable to gimp API currently under development.

Do we **all** want to export metadata to gimp?

**Comment by PV-2024** [comment] 2024-03-04 09:42
Apologies for not replying sooner, I had to figure out how to do this in Darktable... image downsized as original would be astronomically large file sizes.

EXR copy of an image (EXIF not saved by Darktable) - 7.5MB
http://dski.net/misc/DSC_22277.exr
JPEG version of the same image as saved by Darktable (has kept all the EXIF). - 110k
http://dski.net/misc/DSC_22277.jpg

Image exported to GIMP using "Open with Gimp" which opens Darktable, then opens GIMP does not have any EXIF.

**Comment by kmilos** [comment] 2024-03-07 08:07
Closing as issue has been [confirmed upstream](https://gitlab.gnome.org/GNOME/gimp/-/issues/10903#note_2041369).

**Closed by kmilos** 2024-03-07 08:07 UTC
Labels: scope: DAM
