### ISSUE TITLE
[Color Calibration] Found when searching channel mixer and channel mixer preset no longer there

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#6905] opened 2020-11-14 11:25 UTC
It's getting confusing now...

There used to be a channel mixer. Now searching for channel mixer finds color calibration.

![image](https://user-images.githubusercontent.com/1119439/99146020-18556200-269a-11eb-8c5e-33eb3111a077.png)

**Comment by parafin** [comment] 2020-11-14 11:37
That's intended, color calibration replaced channel mixer and covers its functionality. What is the problem?

**Comment by chhil** [comment] 2020-11-14 11:44
I did not know it was removed and that it will pop up module that is not the string value I searched.

**Comment by parafin** [comment] 2020-11-14 11:48
Then I would say this is a duplicate of #6902.

**Closed by parafin** 2020-11-14 11:48 UTC

**Comment by chhil** [comment] 2020-11-14 11:54
Just adding a note, if older images had channel mixer it shows up. This appears to be standard behavior of deprecating modules.
