### ISSUE TITLE
Intel NEO opencl driver not used on latest git

### ISSUE THREAD

**Issue by piratenpanda** [darktable-org/darktable#11785] opened 2022-05-11 08:04 UTC
When running ./darktable -d opencl I get the following output:
```
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'libOpenCL.so.1'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
[opencl_init] opencl_synch_cache: active module
[opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded
[opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
   DEVICE:                   0: 'Intel(R) HD Graphics 5500 [0x1616]', NEW
   CANONICAL NAME:           intelrhdgraphics55000x1616
   PLATFORM NAME & VENDOR:   Intel(R) OpenCL HD Graphics, Intel(R) Corporation
   DRIVER VERSION:           22.11.22682
   DEVICE VERSION:           OpenCL 3.0 NEO 
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          6115 MB
   MAX MEM ALLOC:            2048 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      256
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 256 256 256 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   PERFORMANCE:              0.000000 (CPU 0.416323)
   DEFAULT DEVICE:           NO
   KERNEL DIRECTORY:         /opt/darktable/share/darktable/kernels
   CL COMPILER OPTION:       -cl-fast-relaxed-math
0.588703 [opencl_fopen_stat] could not open file `/home/BG/.cache/darktable/cached_kernels_for_IntelRHDGraphics55000x1616_221122682/demosaic_ppg.cl.bin'!
0.588744 [opencl_load_program] could not load cached binary program, trying to compile source
0.588858 [opencl_build_program] could not build program: CL_OUT_OF_HOST_MEMORY
0.588867 [dt_opencl_device_init] failed to compile program `demosaic_ppg.cl'!
[opencl_init] no suitable devices found.
[opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
[opencl_init] initial status of opencl enabled flag is OFF.
2,655621 [pixelpipe_process] [thumbnail] using device -1
2,694159 [pixelpipe_process] [thumbnail] using device -1
7,692590 [pixelpipe_process] [thumbnail] using device -1
```

And while I understand that this laptop is not made for heavy editing opencl still made it a lot faster than using the CPU paths. Anything I can do? @jenshannoschwalm

**Comment by parafin** [comment] 2022-05-11 08:17
Looks like compilation of OpenCL kernels failed due to lack of RAM... Which is somewhat surprising. Maybe you could try closing some other applications and/or adding swap space.

**Comment by piratenpanda** [comment] 2022-05-11 08:29
Nothing is running, ram is at 2.5 GB/8 GB, swap completely empty according to the system monitor

**Comment by parafin** [comment] 2022-05-11 08:50
Then it sounds like an OpenCL driver bug, which is much more likely situation;)

**Comment by jenshannoschwalm** [comment] 2022-05-11 10:48
Just from memory, I think you should try to use -d opencl -d verbose to see details what goes wrong while compiling kernels. The error  code might just reflect not-possible access.

**Comment by piratenpanda** [comment] 2022-05-11 10:50
this yields
```
/opt/darktable/bin/darktable -d opencl -d verbose
[opencl_init] opencl related configuration options:
[opencl_init] opencl: ON
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: 'default path'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
[opencl_init] opencl_synch_cache: active module
0.077989 [dt_dlopencl_init] could not find opencl runtime library 'libOpenCL'
0.078082 [dt_dlopencl_init] could not find opencl runtime library 'libOpenCL.so'
0.078850 [dt_dlopencl_init] found opencl runtime library 'libOpenCL.so.1'
[opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded
[opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
0.083746 [dt_opencl_write_device_config] writing data '0 250 0 16 16 128 0 0 0.000000' for 'cldevice_v4_intelrhdgraphics55000x1616'
   DEVICE:                   0: 'Intel(R) HD Graphics 5500 [0x1616]'
   CANONICAL NAME:           intelrhdgraphics55000x1616
   PLATFORM NAME & VENDOR:   Intel(R) OpenCL HD Graphics, Intel(R) Corporation
   DRIVER VERSION:           22.11.22682
   DEVICE VERSION:           OpenCL 3.0 NEO 
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          6115 MB
   MAX MEM ALLOC:            2048 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      256
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 256 256 256 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   PERFORMANCE:              0.000000 (CPU 0.416323)
   DEFAULT DEVICE:           NO
   KERNEL DIRECTORY:         /opt/darktable/share/darktable/kernels
   CL COMPILER OPTION:       -cl-fast-relaxed-math
0.086390 [dt_opencl_device_init] testing program `demosaic_ppg.cl' ..
0.086744 [opencl_fopen_stat] could not open file `/home/BG/.cache/darktable/cached_kernels_for_IntelRHDGraphics55000x1616_221122682/demosaic_ppg.cl.bin'!
0.086757 [opencl_load_program] could not load cached binary program, trying to compile source
0.086783 [opencl_load_program] successfully loaded program from '/opt/darktable/share/darktable/kernels/demosaic_ppg.cl' MD5: '5686b03526f3de9f60913b2d94703530'
0.086957 [opencl_build_program] could not build program: CL_OUT_OF_HOST_MEMORY
0.086965 [opencl_build_program] BUILD STATUS: -2
0.086968 BUILD LOG:
0.086971 
0.086973 [dt_opencl_device_init] failed to compile program `demosaic_ppg.cl'!
0.086987 [dt_opencl_write_device_config] writing data '0 250 0 16 16 128 0 0 0.000000' for 'cldevice_v4_intelrhdgraphics55000x1616'
[opencl_init] no suitable devices found.
[opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
[opencl_init] initial status of opencl enabled flag is OFF.
```

**Comment by gi-man** [comment] 2022-05-11 12:00
I noticed that the OpenCL header module we use is a commit from 09Dec2020. There are a few number of the commits since then addressing Intel memory.

**Comment by parafin** [comment] 2022-05-11 12:08
This a problem with implementation, not headers.

**Closed** 2022-05-11 14:43 UTC

**Comment by aurelienpierre** [comment] 2022-05-20 19:47
I can confirm that Intel Neo 22.11.22682 makes it crash here too (Fedora 36). dt would not even start.

**Comment by jenshannoschwalm** [comment] 2022-05-20 19:58
Can you confirm that it crashes too with an empty compiler option string? (just to keep track on it on gh)

**Comment by aurelienpierre** [comment] 2022-05-20 20:10
Yes.

**Comment by parafin** [comment] 2022-06-02 08:14
1. macOS code-path should work on Linux too, so you could try it. glib implementation doesn't work on macOS, since it checks for library file existence, which on macOS can be false, while dlopen still working (don't ask).
2. My understanding is that dt_gmodule_symbol can return TRUE even if *function is NULL, but it's the case only if said symbol does exist in the library and evaluates to NULL. If it doesn't exist (which is what I expect for not implemented function), then it should return FALSE. This is smth to be confirmed. Have you checked? And you could try to modify dt_gmodule_symbol function to check for NULL too if that's your suspicion.

**Comment by jenshannoschwalm** [comment] 2022-06-02 09:15
Thanks, about 1) i won't ask but undertand now, why there is a different codepath.
About 2) I didn't check yet but that was exactly my suspicion. Checking for linux won't hurt anyway. And also we might replace a NULL by a default "bug handler".

Does 22.11.22682 work on OSX btw.

**Comment by parafin** [comment] 2022-06-02 09:29
macOS uses its own OpenCL drivers, no idea who actually wrote them or what version it is (it's shipped with OS).

**Comment by jenshannoschwalm** [comment] 2022-06-03 09:47
I checked and all function pointers are ok.

There is at least a dependency problem in Fedora 36, in addition to the cl rpm package we need more, so after all i can currently confirm an issue almost like the one originally reported with failing to compile the kernels.

Not knowing what the reason is for this yet, llvm or intel compiler mismatch?

BTW what does dt -d opencl report in intel cl devices using OSX?

**Comment by parafin** [comment] 2022-06-03 17:02
```
$ /Applications/darktable.app/Contents/MacOS/darktable-cltest
[opencl_init] opencl related configuration options:
[opencl_init] opencl: OFF
[opencl_init] opencl_scheduling_profile: 'default'
[opencl_init] opencl_library: '/System/Library/Frameworks/OpenCL.framework/OpenCL'
[opencl_init] opencl_device_priority: '*/!0,*/*/*'
[opencl_init] opencl_mandatory_timeout: 200
[opencl_init] opencl_synch_cache: false
[opencl_init] opencl library '/System/Library/Frameworks/OpenCL.framework/OpenCL' found on your system and loaded
[opencl_init] found 1 platform
[opencl_init] found 2 devices

[dt_opencl_device_init]
   DEVICE:                   0: 'Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz'
   CANONICAL NAME:           intelrcoretmi53427ucpu180ghz
   PLATFORM NAME & VENDOR:   Apple, Apple
   DRIVER VERSION:           1.1
   DEVICE VERSION:           OpenCL 1.2 
   DEVICE_TYPE:              CPU
   GLOBAL MEM SIZE:          4096 MB
   MAX MEM ALLOC:            1024 MB
   MAX IMAGE SIZE:           8192 x 8192
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1 1 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   AVOID ATOMICS:            NO
   MICRO NAP:                1000
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   PERFORMANCE:              0.000000 (CPU 0.482911)
   DEFAULT DEVICE:           NO
   *** marked as disabled ***

[dt_opencl_device_init]
   DEVICE:                   1: 'HD Graphics 4000'
   CANONICAL NAME:           hdgraphics4000
   PLATFORM NAME & VENDOR:   Apple, Apple
   DRIVER VERSION:           1.2(Apr 27 2022 19:28:46)
   DEVICE VERSION:           OpenCL 1.2 
   DEVICE_TYPE:              GPU
   GLOBAL MEM SIZE:          1536 MB
   MAX MEM ALLOC:            384 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      512
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 512 512 512 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   MEMORY TUNING:            NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH:            16
   ROUNDUP HEIGHT:           16
   CHECK EVENT HANDLES:      128
   PERFORMANCE:              0.136205 (CPU 0.482911)
   DEFAULT DEVICE:           NO
   KERNEL DIRECTORY:         /Applications/darktable.app/Contents/Resources/share/darktable/kernels
   CL COMPILER OPTION:       -cl-fast-relaxed-math
   KERNEL LOADING TIME:       0.0134 sec
[opencl_init] OpenCL successfully initialized.
[opencl_init] here are the internal numbers and names of OpenCL devices available to darktable:
[opencl_init]		0	'HD Graphics 4000'
[opencl_init] FINALLY: opencl is AVAILABLE on this system.
[opencl_init] initial status of opencl enabled flag is OFF.
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	-1	0	0	-1
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	0	0	0	0
[opencl_synchronization_timeout] synchronization timeout set to 200
```

**Comment by sarunasb** [comment] 2024-10-17 16:45
`CL_OUT_OF_HOST_MEMORY` is back after upgrading to Ubuntu 24.10, kernel 6.11.0-8-generic x86_64. The following are set, which solved the issue with kernel 6.8:
```
export NEOReadDebugKeys=1
export OverrideGpuAddressSpace=48
```

```
$ clinfo -l
Platform #0: Intel(R) OpenCL Graphics
 `-- Device #0: Intel(R) Arc(TM) A770 Graphics
```
```
$ darktable -d opencl -d verbose
darktable 4.8.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.3.0
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  GMIC                   -> DISABLED - Compressed LUTs are NOT supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.0330 [dt_get_sysresource_level] switched to 1 as `default'
     0.0330   total mem:       31196MB
     0.0330   mipmap cache:    3899MB
     0.0330   available mem:   15598MB
     0.0330   singlebuff:      243MB
     0.0352 [opencl_init] opencl disabled via darktable preferences
     0.0353 [dt_dlopencl_init] found default opencl runtime library 'libOpenCL'
     0.0354 [opencl_init] opencl library 'libOpenCL' found on your system and loaded, preference 'default path'
     0.0595 [opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
     0.0595 [dt_opencl_write_device_config] writing data '0 250 0 16 16 128 0 0 0.000 0.000 0.250' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics'
     0.0595 [dt_opencl_write_device_config] writing data '600' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics_id0'
   DEVICE:                   0: 'Intel(R) Arc(TM) A770 Graphics'
   CONF KEY:                 cldevice_v5_intelropenclgraphicsintelrarctma770graphics
   PLATFORM, VENDOR & ID:    Intel(R) OpenCL Graphics, Intel(R) Corporation, ID=32902
   CANONICAL NAME:           intelropenclgraphicsintelrarctma770graphics
   DRIVER VERSION:           24.35.030872
   DEVICE VERSION:           OpenCL 3.0 NEO 
   DEVICE_TYPE:              GPU, dedicated mem
   GLOBAL MEM SIZE:          15474 MB
   MAX MEM ALLOC:            4096 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 1024 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   /usr/share/darktable/kernels
   KERNEL DIRECTORY:         /home/sarunas/.cache/darktable/cached_v3_kernels_for_IntelROpenCLGraphicsIntelRArcTMA770Graphics_2435030872
   CL COMPILER OPTION:       
   CL COMPILER COMMAND:      -w   -DINTEL=1 -I"/usr/share/darktable/kernels"
     0.0597 [dt_opencl_device_init] testing program `demosaic_ppg.cl' ..
     0.0598 [opencl_fopen_stat] could not open file `/home/sarunas/.cache/darktable/cached_v3_kernels_for_IntelROpenCLGraphicsIntelRArcTMA770Graphics_2435030872/demosaic_ppg.cl.bin'!
     0.0598 [opencl_load_program] could not load cached binary program, trying to compile source
     0.0598 [opencl_load_program] successfully loaded program from '/usr/share/darktable/kernels/demosaic_ppg.cl' MD5: 'f919c1055cc1da97c74dd88417fa2ea3'
     0.0598 [opencl_build_program] could not build program: CL_OUT_OF_HOST_MEMORY
     0.0598 [opencl_build_program] BUILD STATUS: -2
     0.0598 BUILD LOG:
     0.0598 
     0.0598 [dt_opencl_device_init] failed to compile program `demosaic_ppg.cl'!
     0.0598 [dt_opencl_write_device_config] writing data '0 250 0 16 16 128 0 0 0.000 0.000 0.250' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics'
     0.0598 [dt_opencl_write_device_config] writing data '600' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics_id0'
[opencl_init] no suitable devices found.
     0.0598 [opencl_init] FINALLY: opencl PREFERENCE=OFF is NOT AVAILABLE and NOT ENABLED.
```

**Comment by jenshannoschwalm** [comment] 2024-10-17 17:53
On 4.8.1 ?  Tried on master?

**Comment by sarunasb** [comment] 2024-10-17 18:16
> On 4.8.1 ? Tried on master?

Same issue in master, unfortunately… (4.8.1 is in standard Ubuntu 24.10 repository).

```$ /opt/darktable/bin/darktable -d opencl -d verbose
darktable 71719df
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> DISABLED
  Colord                 -> DISABLED
  gPhoto2                -> ENABLED
  GMIC                   -> DISABLED - Compressed LUTs are NOT supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  LibRaw                 -> ENABLED  - Version 0.22.0-Devel202403
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.0001 [dt starting] /opt/darktable/bin/darktable -d opencl -d verbose
     0.1500 [dt_get_sysresource_level] switched to 1 as `default'
     0.1500   total mem:       31196MB
     0.1500   mipmap cache:    3899MB
     0.1500   available mem:   15598MB
     0.1501   singlebuff:      243MB
     0.1688 [opencl_init] opencl disabled via darktable preferences
     0.1689 [dt_dlopencl_init] found default opencl runtime library 'libOpenCL'
     0.1689 [opencl_init] opencl library 'libOpenCL' found on your system and loaded, preference 'default path'
     0.1929 [opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
     0.1930 [dt_opencl_write_device_config] writing data '0 250 0 16 16 128 0 0 0.000 0.000 0.250' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics'
     0.1930 [dt_opencl_write_device_config] writing data '600' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics_id0'
   DEVICE:                   0: 'Intel(R) Arc(TM) A770 Graphics'
   CONF KEY:                 cldevice_v5_intelropenclgraphicsintelrarctma770graphics
   PLATFORM, VENDOR & ID:    Intel(R) OpenCL Graphics, Intel(R) Corporation, ID=32902
   CANONICAL NAME:           intelropenclgraphicsintelrarctma770graphics
   DRIVER VERSION:           24.35.030872
   DEVICE VERSION:           OpenCL 3.0 NEO 
   DEVICE_TYPE:              GPU, dedicated mem
   GLOBAL MEM SIZE:          15474 MB
   MAX MEM ALLOC:            4096 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 1024 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   /opt/darktable/share/darktable/kernels
   KERNEL DIRECTORY:         /home/sarunas/.cache/darktable/cached_v5_kernels_for_IntelROpenCLGraphicsIntelRArcTMA770Graphics_2435030872
   CL COMPILER OPTION:       
   CL COMPILER COMMAND:      -w   -DINTEL=1 -I"/opt/darktable/share/darktable/kernels"
     0.1932 [dt_opencl_device_init] testing program `demosaic_ppg.cl' ..
     0.1932 [opencl_fopen_stat] could not open file `/home/sarunas/.cache/darktable/cached_v5_kernels_for_IntelROpenCLGraphicsIntelRArcTMA770Graphics_2435030872/demosaic_ppg.cl.bin'!
     0.1932 [opencl_load_program] could not load cached binary program, trying to compile source
     0.1933 [opencl_load_program] successfully loaded program from '/opt/darktable/share/darktable/kernels/demosaic_ppg.cl' MD5: '00307dc3aba113767104183aa0e219ed'
     0.1933 [opencl_build_program] could not build program: CL_OUT_OF_HOST_MEMORY
     0.1933 [opencl_build_program] BUILD STATUS: -2
     0.1933 BUILD LOG:
     0.1933 
     0.1933 [dt_opencl_device_init] failed to compile program `demosaic_ppg.cl'!
     0.1933 [dt_opencl_write_device_config] writing data '0 250 0 16 16 128 0 0 0.000 0.000 0.250' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics'
     0.1933 [dt_opencl_write_device_config] writing data '600' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics_id0'
[opencl_init] no suitable devices found.
     0.1933 [opencl_init] FINALLY: opencl PREFERENCE=OFF is NOT AVAILABLE and NOT ENABLED.
```

**Comment by jenshannoschwalm** [comment] 2024-10-18 07:49
``` 
    0.1933 [opencl_build_program] could not build program: CL_OUT_OF_HOST_MEMORY
```

Annoying!

```
export NEOReadDebugKeys=1
export OverrideGpuAddressSpace=48
```

If we would have to suggest to add this while building, even more annying!

If any special "flags **must/should** be added to compile correctly we might want to include such options in the darktable building. Let me know if you are **sure** about such.

**Comment by sarunasb** [comment] 2024-10-18 13:50
> Annoying!

Agree.

I'm not sure about any flags. I don't remember where that fix came from. It is not a fix anymore anyway…

**Comment by sarunasb** [comment] 2024-10-18 14:11
> I'm not sure about any flags. I don't remember where that fix came from. It is not a fix anymore anyway…

Actually the flags were not for OpenCL kernels compile. So they are irrelevant here. (They were fixing something that was intoruced in Linux 6.8 that led to Intel GPUs not being detected.)

**Comment by sarunasb** [comment] 2024-12-03 19:21
> ```
>     0.1933 [opencl_build_program] could not build program: CL_OUT_OF_HOST_MEMORY
> ```

Hi,
is there anyhting I can do to provide any helpful info on this?

**Comment by sarunasb** [comment] 2024-12-03 19:23
Here is the verbose output:
```
$ darktable -d opencl -d verbose
darktable 4.8.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.3.0
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  GMIC                   -> DISABLED - Compressed LUTs are NOT supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.0152 [dt_get_sysresource_level] switched to 1 as `default'
     0.0152   total mem:       31196MB
     0.0152   mipmap cache:    3899MB
     0.0152   available mem:   15598MB
     0.0152   singlebuff:      243MB
     0.0174 [opencl_init] opencl disabled via darktable preferences
     0.0175 [dt_dlopencl_init] found default opencl runtime library 'libOpenCL'
     0.0175 [opencl_init] opencl library 'libOpenCL' found on your system and loaded, preference 'default path'
     0.0425 [opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
     0.0425 [dt_opencl_write_device_config] writing data '0 250 0 16 16 128 0 0 0.000 0.000 0.250' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics'
     0.0426 [dt_opencl_write_device_config] writing data '600' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics_id0'
   DEVICE:                   0: 'Intel(R) Arc(TM) A770 Graphics'
   CONF KEY:                 cldevice_v5_intelropenclgraphicsintelrarctma770graphics
   PLATFORM, VENDOR & ID:    Intel(R) OpenCL Graphics, Intel(R) Corporation, ID=32902
   CANONICAL NAME:           intelropenclgraphicsintelrarctma770graphics
   DRIVER VERSION:           24.35.030872
   DEVICE VERSION:           OpenCL 3.0 NEO 
   DEVICE_TYPE:              GPU, dedicated mem
   GLOBAL MEM SIZE:          15474 MB
   MAX MEM ALLOC:            4096 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 1024 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   /usr/share/darktable/kernels
   KERNEL DIRECTORY:         /home/sarunas/.cache/darktable/cached_v3_kernels_for_IntelROpenCLGraphicsIntelRArcTMA770Graphics_2435030872
   CL COMPILER OPTION:       
   CL COMPILER COMMAND:      -w   -DINTEL=1 -I"/usr/share/darktable/kernels"
     0.0427 [dt_opencl_device_init] testing program `demosaic_ppg.cl' ..
     0.0428 [opencl_fopen_stat] could not open file `/home/sarunas/.cache/darktable/cached_v3_kernels_for_IntelROpenCLGraphicsIntelRArcTMA770Graphics_2435030872/demosaic_ppg.cl.bin'!
     0.0428 [opencl_load_program] could not load cached binary program, trying to compile source
     0.0428 [opencl_load_program] successfully loaded program from '/usr/share/darktable/kernels/demosaic_ppg.cl' MD5: 'f919c1055cc1da97c74dd88417fa2ea3'
     0.0428 [opencl_build_program] could not build program: CL_OUT_OF_HOST_MEMORY
     0.0428 [opencl_build_program] BUILD STATUS: -2
     0.0428 BUILD LOG:
     0.0428 
     0.0428 [dt_opencl_device_init] failed to compile program `demosaic_ppg.cl'!
     0.0428 [dt_opencl_write_device_config] writing data '0 250 0 16 16 128 0 0 0.000 0.000 0.250' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics'
     0.0428 [dt_opencl_write_device_config] writing data '600' for 'cldevice_v5_intelropenclgraphicsintelrarctma770graphics_id0'
[opencl_init] no suitable devices found.
     0.0428 [opencl_init] FINALLY: opencl PREFERENCE=OFF is NOT AVAILABLE and NOT ENABLED.
```

**Comment by jenshannoschwalm** [comment] 2024-12-04 07:32
I absolutely don't know.

Searching the internet does not give big help, i just can say that all works fine on my intel notebook.

In `_opencl_build_program`

```
    (program, 1, &(cl->dev[dev].devid), cl->dev[dev].options, 0, 0);
```

should be 
```
    (program, 1, &(cl->dev[dev].devid), cl->dev[dev].options, NULL, NULL);

```

but i can't think of that as a problem.

**Comment by sarunasb** [comment] 2025-02-05 17:10
All is fine on newly installed systems (Ubuntu 24.04, 24.10 and Debian Sid).

```
$ darktable-cltest
darktable 4.8.1
Copyright (C) 2012-2024 Johannes Hanika and other contributors.

Compile options:
  Bit depth              -> 64 bit
  Debug                  -> DISABLED
  SSE2 optimizations     -> ENABLED
  OpenMP                 -> ENABLED
  OpenCL                 -> ENABLED
  Lua                    -> ENABLED  - API version 9.3.0
  Colord                 -> ENABLED
  gPhoto2                -> ENABLED
  GMIC                   -> DISABLED - Compressed LUTs are NOT supported
  GraphicsMagick         -> ENABLED
  ImageMagick            -> DISABLED
  libavif                -> ENABLED
  libheif                -> ENABLED
  libjxl                 -> ENABLED
  OpenJPEG               -> ENABLED
  OpenEXR                -> ENABLED
  WebP                   -> ENABLED

See https://www.darktable.org/resources/ for detailed documentation.
See https://github.com/darktable-org/darktable/issues/new/choose to report bugs.

     0.0118 [dt_get_sysresource_level] switched to 2 as `large'
     0.0118   total mem:       31144MB
     0.0118   mipmap cache:    3893MB
     0.0118   available mem:   21290MB
     0.0118   singlebuff:      486MB
     0.0138 [dt_dlopencl_init] could not find default opencl runtime library 'libOpenCL'
     0.0138 [dt_dlopencl_init] could not find default opencl runtime library 'libOpenCL.so'
     0.0139 [opencl_init] opencl library 'libOpenCL.so.1' found on your system and loaded, preference 'default path'
     0.0301 [opencl_init] found 1 platform
[opencl_init] found 1 device

[dt_opencl_device_init]
   DEVICE:                   0: 'Intel(R) Arc(TM) A770 Graphics'
   CONF KEY:                 cldevice_v5_intelropenclgraphicsintelrarctma770graphics
   PLATFORM, VENDOR & ID:    Intel(R) OpenCL Graphics, Intel(R) Corporation, ID=32902
   CANONICAL NAME:           intelropenclgraphicsintelrarctma770graphics
   DRIVER VERSION:           24.35.030872
   DEVICE VERSION:           OpenCL 3.0 NEO 
   DEVICE_TYPE:              GPU, dedicated mem
   GLOBAL MEM SIZE:          15474 MB
   MAX MEM ALLOC:            4096 MB
   MAX IMAGE SIZE:           16384 x 16384
   MAX WORK GROUP SIZE:      1024
   MAX WORK ITEM DIMENSIONS: 3
   MAX WORK ITEM SIZES:      [ 1024 1024 1024 ]
   ASYNC PIXELPIPE:          NO
   PINNED MEMORY TRANSFER:   NO
   AVOID ATOMICS:            NO
   MICRO NAP:                250
   ROUNDUP WIDTH & HEIGHT    16x16
   CHECK EVENT HANDLES:      128
   TILING ADVANTAGE:         0.000
   DEFAULT DEVICE:           NO
   KERNEL BUILD DIRECTORY:   /usr/share/darktable/kernels
   KERNEL DIRECTORY:         /home/sarunas/.cache/darktable/cached_v3_kernels_for_IntelROpenCLGraphicsIntelRArcTMA770Graphics_2435030872
   CL COMPILER OPTION:       
   CL COMPILER COMMAND:      -w   -DINTEL=1 -I"/usr/share/darktable/kernels"
   KERNEL LOADING TIME:       0.0192 sec
[opencl_init] OpenCL successfully initialized. internal numbers and names of available devices:
[opencl_init]		0	'Intel(R) OpenCL Graphics Intel(R) Arc(TM) A770 Graphics'
     0.0495 [opencl_init] FINALLY: opencl PREFERENCE=ON is AVAILABLE and ENABLED.
[opencl_init] opencl_scheduling_profile: 'very fast GPU'
[opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
[opencl_init] opencl_mandatory_timeout: 400
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	0	0	0	0
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		1	1	1	1	1
[opencl_synchronization_timeout] synchronization timeout set to 0
[dt_opencl_update_priorities] these are your device priorities:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		0	0	0	0	0
[dt_opencl_update_priorities] show if opencl use is mandatory for a given pixelpipe:
[dt_opencl_update_priorities] 		image	preview	export	thumbs	preview2
[dt_opencl_update_priorities]		1	1	1	1	1
[opencl_synchronization_timeout] synchronization timeout set to 0

```
