### ISSUE TITLE
Image shifts to purple when Full screen in Lighttable view

### ISSUE THREAD

**Issue by Jasonious530** [darktable-org/darktable#12205] opened 2022-07-19 15:43 UTC
Windows Version:

Edition	Windows 10 Home
Version	21H2
Installed on	‎12/‎26/‎2020
OS build	19044.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0

DT Version:

4.0.0

Issue:

When opening some images into the full screen view they shift to a purple hue and I cannot make them go back without duplicating them and deleting the purple version.

![2022-07-19 (2)](https://user-images.githubusercontent.com/90074921/179792019-3ca75162-f826-4fe9-ba32-1dc6c3b31c4f.png)
![2022-07-19](https://user-images.githubusercontent.com/90074921/179792028-7a8c4200-805a-44f6-ab2f-6cd5983b953f.png)

NOTE:

Image appears normal when exported

**Comment by Jasonious530** [comment] 2022-07-19 17:17
Here is what the image looks like in the Darkroom


![2022-07-19 (3)](https://user-images.githubusercontent.com/90074921/179810664-e37af277-ad70-4614-bf7a-210e87743c67.png)

**Comment by Jasonious530** [comment] 2022-07-19 17:30
I have onboard graphics: Intel UHD 620 and OpenCL support is greyed out in the processing tab of the preferences menu

**Comment by Nilvus** [comment] 2022-07-19 17:34
> It won't let me upload the .dng or the .xmp as it says they are unsupported file types here.

I know. Just post it on a cloud (or something like wetransfer or other) and post the link here

> The image is edited in darkroom, but appears normal when opening it in the darkroom view, Only the full screen view seems to be affected.
> Also, I have changed the thumbnails setting to Always show RAW file instead of embedded JPEG, but the issue persists.

Thanks. Did you test by restarting darktable after such change?

Definitely, affected RAW/XMP will be needed.

**Comment by Jasonious530** [comment] 2022-07-19 17:42
Here are the files from my onedrive.

https://1drv.ms/u/s!ArjGD-oBxrpngaFayko6VbIyJ2RXxw?e=QplVg5

Yes I have restarted DT several times with settings changes.

**Comment by Jasonious530** [comment] 2022-07-19 17:58
Note: I pasted the history stack to a different RAW unprocessed image and the colors shifted on the new image as well.

**Comment by gi-man** [comment] 2022-07-19 20:52
I tried your image and xmp on Windows 11 4.1.0+67~gb2d742c53 with and without OpenCL. I have AMD Ryzen CPU in my system.

Are you using a display calibration tool (running in the background)?

Start turning off some of the modules to see if you can find one module to be the cause. I would start turning off the sharpen one. Then try with camera reference for white balance instead of as shot.

**Comment by Jasonious530** [comment] 2022-07-19 21:31
No calibration tool. I just turned off modules one by one and checked after each one, and it went away after I turned off the Crop module.

**Comment by gi-man** [comment] 2022-07-19 21:51
This is very strange. 

If you turn on all the other module except the crop, no issues?

**Comment by Jasonious530** [comment] 2022-07-19 21:53
Yes, I went back and turned on the other modules and the issue did not return. I also reset the crop module and re-appplied a square crop, and the image looks as it should right now.

**Comment by luzpaz** [comment] 2023-07-03 18:35
Is this issue still reproducible ?

**Comment by ralfbrown** [comment] 2024-01-11 17:06
Closing as there has been no futher response from the OP in over a year.  If the issue is still present in 4.6, feel free to reopen or open a new issue.

**Closed as not planned by ralfbrown** 2024-01-11 17:06 UTC
Labels: understood: incomplete, no-issue-activity

**Comment by cayenneta** [comment] 2026-02-20 06:03
This is happening to me, the color calibration module is turning my unedited image purple, and it persists when I export. If I reset the modules the issue goes away but I don't want to lose my edits. Every time I click on a new image the issue applies to it, but only if the image is a .CR2 file from my old camera, now I use .CR3.
