### ISSUE TITLE
Culling to trash

### ISSUE THREAD

**Issue by davidvj** [darktable-org/darktable#5760] opened 2020-07-17 04:44 UTC
I have been using the 'culling-lighttable' where I have set 2 images for comparison. This follows a remake of an older image. The culling allows me to compare the old/new versions. At this point I wish to trash the lesser result. I select one image and click on 'trash' ... a message box asks me to confirm that I want to trash 2 (two)  both images ... that I certainly do not want.
Previously I made the mistake of agreeing and did loose 2 images!
1. lightroom > culling
2  set number of images to 2
3  select only one of the displayed images
4  click on selected-images > trash

Platform: Manjaro/Arch/XFCE
darktable 3.1.0+2466~ge328b89ea
OpenCL installed but not active.
Problem seen with RAW images

Problem has been seen for some time ...

**Comment by Nilvus** [comment] 2020-07-17 19:56
@AlicVB: maybe same thing that reject one some time ago?

**Comment by Nilvus** [comment] 2020-07-17 19:57
@AlicVB: on filmstrip, the 2 images are shown selected (and so not only the image selected on culling view).

**Comment by TurboGit** [comment] 2020-07-18 16:51
I think this is by design. The culling view holds selected the current pictures. There is no way to select one anyway in the new lighttable.

**Comment by Nilvus** [comment] 2020-07-18 18:30
Even if I don't use panels modules on filmstrip (and mainly use it to rate/reject images only), I'm not sure it's a good (and consistency) design in culling view, you can select (or not) an image. Or to be more precis, hovering an image making it selected (so show block overlay and a white border). And that way, it's possible to rate/reject that image only, not the others. Should be the same I think for all items in selected images.

**Comment by AlicVB** [comment] 2020-08-29 20:53
oups, forgot that one, sorry...
A @TurboGit said it's the "by design". In fact, your step 3 "select only one of the displayed images" can't be achieve by simply clicking on it. So when you go in the right panel to click on the button, dt try to apply the action to the 2 images on screen, which is expected.

Now the reason why you can't just select an image by clicking on it in culling is because this mode rely on selection for lot of things : defining the images to show in dynamic mode, limit the set of images to do culling for fix mode, ... So it's not desirable to change selection in this mode, except if the user know exactly what he's doing.

For your workflow, a solution is to use shortcut with the mouse hovering the photo you want to trash... Or maybe to use the "reject" rating, combined with the filter "show all except rejected", That way you can easily recover any error...

I'm closing for now as it works like expected. Feel free to reopen if I've not understand your issue

**Closed by AlicVB** 2020-08-29 20:53 UTC
Labels: no-issue-activity
