### ISSUE TITLE
Crashing when attempting to browse older edits

### ISSUE THREAD

**Issue by MartinScharnke** [darktable-org/darktable#15149] opened 2023-09-01 01:10 UTC
### Describe the bug

Browsing library.db entries for edits made 2019 or earlier results in freeze and enventual crash. Sometimes malloc() failure. Sometimes SEGFAULT.
Attempted to isolate by starting with no library.db and importing one of the offending images (which has an accompanying .xmp). Results in SEGFAULT.
Has been an issue for at least the last month in master for me.

### Steps to reproduce

With a blank database, attempt to import problem image - crash occurs
cf
With a blank database, attempt to import problem image without the existing xmp - no crash

### Expected behavior

darktable should allow me to browse and open thousands of existing edits without crashing

### Logfile | Screenshot | Screencast

[dt_-d_all.log](https://github.com/darktable-org/darktable/files/12491851/dt_-d_all.log)

### Where did you install darktable from?

self compiled

### darktable version

4.5.0+429~gefc8d2ff5

### What OS are you using?

Linux

### What is the version of your OS?

Debian Bookworm

### Describe your system?

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimizations enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support enabled, API version 9.2.0
  Colord support enabled
  gPhoto2 support enabled
  G'MIC support disabled (compressed LUTs will not be supported)
  GraphicsMagick support enabled
  ImageMagick support disabled
  libavif support disabled
  libheif support enabled
  libjxl support enabled
  OpenJPEG support enabled
  OpenEXR support enabled
  WebP support enabled

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeForce GTX 1660, 6144 MB, 525.125.06

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Have been having issue with every build of master for the last month or so.
As mentioned above - problem seems to be caused by the xmp.

[2019-01-01_17-15-46.99_DSC2478.NEF.xmp.txt](https://github.com/darktable-org/darktable/files/12491916/2019-01-01_17-15-46.99_DSC2478.NEF.xmp.txt)

**Comment by ralfbrown** [comment] 2023-09-01 05:01
No problem here except that the base curve graph looks really strange and highlights invert on a D7200 pics of mine I tried it with when the module is enabled.  Hovering on the basecurve entry in history indicates that it has zero nodes, i.e. no curve at all.

**Comment by MartinScharnke** [comment] 2023-09-01 05:12
Thanks for the feedback; one of the recurring messages that appears in the -d all log is complaint about basecurve and invalid parameters. But why should an older version of darktable managed, whereas the more recent crashes? Is there some deprecation that now makes accessing some older edits impossible?
  Somewhat related: In seeking to have stability, I have created a new database and imported all my images from 2020 and more recent. Rather than throw away all my edit histories for older images, is it possible to remove offending content from the .xmp files?

**Comment by ralfbrown** [comment] 2023-09-01 05:23
Got master to crash with a 2018 D7200 image of mine and corresponding sidecar.  Crash location is commit_params in basecurve.c when it tries to access the \#nodes-1 entry of the base curve while \#nodes is zero.  My guess would have been that `legacy_params` (last touched on August 9) broke, but as far as I can tell it isn't being called even though the module version in the sidecar is 5 and current version is 6.

**Comment by MartinScharnke** [comment] 2023-09-01 05:29
Glad you can reproduce something ... I imagine you would have managed to crash master had I sent you my original NEF to go with the sidecar I provided. I was convinced something was broken, and I'm not crazy!

**Comment by TurboGit** [comment] 2023-09-01 07:08
I'll have a look as this may well be a regression I have introduced while rewriting the incremental legacy_params support.

**Comment by TurboGit** [comment] 2023-09-01 07:48
This is now fixed in current master. Can you double check all is ok on your side? TIA.

**Closed** 2023-09-01 07:48 UTC
Labels: priority: high, bug: pending

**Comment by ralfbrown** [comment] 2023-09-01 13:05
Failing to pass back the new params struct would definitely cause problems....
No more crash with the fix, and the basecurve shows a proper graph.

**Comment by TurboGit** [comment] 2023-09-01 16:39
> Failing to pass back the new params struct would definitely cause problems....

Yep :( Probably a left over from the first iop I have migrated to the new incremental scheme. I have done some checks using grep to ensure all others iop have `*new_params` if there is a `legacy_params()` routine. Can't assess that all is ok at 100% now as I don't feel reviewing again all the iop code.

I have also updated the useless.c code `legacy_params()`.

I feel sorry for this stupid mistake and thanks the fields testing to catch those possible regressions when doing large and deep changes.

**Comment by MartinScharnke** [comment] 2023-09-01 21:40
Sorry to rain on the parade, but the problem does not appear fixed to me.
New pull and build: version 4.5.0+445~g0fcf57c4f
Same errors are recurring.
Backtrace:
[darktable_bt_FWRUA2.txt](https://github.com/darktable-org/darktable/files/12501634/darktable_bt_FWRUA2.txt)

**Comment by ralfbrown** [comment] 2023-09-02 02:40
Check the timestamp on 2019-01-01_17-15-46.99_DSC2478.NEF.xmp - it may have been overwritten with the corrupted data caused by the regression.  If it still has an old timestamp (and thus has not been corrupted), you might have a corrupted entry in the database, in which case you should try just applying the sidecar to the image instead of re-importing.

**Comment by MartinScharnke** [comment] 2023-09-02 04:24
The one sidecar is indeed recently modified; the snag is although many older edits are now accessible without crashing, there are still tens if not hundreds that are not. That's the risk that goes with running master, I guess. I will have to ditch all the corrupted sidecars.
