### ISSUE TITLE
Exported image with very different color from preview - Haze Removal problem

### ISSUE THREAD

**Issue by VictorCarlquist** [darktable-org/darktable#12116] opened 2022-07-03 14:49 UTC
**Describe the bug/issue**

I've edited the photo but when I export the image I get a dark and cold (blue) color, I'm using sRGB profile color on exporter. I've tested with OpenCL on/off and I got the same result.

I disabled the Haze Removal from history and the images starting to match with the preview.

**To Reproduce**
1. Import the file attached in this issue (jpg and xml)
2. Export image in jpg (sRGB profile)
3. Compare the image exported with the preview on darkroom, the image is blue
4. Disable the Haze Removal
5. Export image in jpg (sRGB profile)
6. The exported image matches with the preview. 

**Expected behavior**

It should match the same color that is showing up on preview.

**Screenshots**

Haze Removal: Enable

Darktable Preview                        /                               Exported
![image](https://user-images.githubusercontent.com/871273/177043402-517c5bdd-e39f-4b52-b38d-7174cb8e4c76.png)

Haze Removal: Disabled

Darktable Preview                        /                               Exported
![image](https://user-images.githubusercontent.com/871273/177045076-87f07d11-d904-4470-9a0a-92e5eab5d77e.png)

Original Images:

![IMG_20220701_201741](https://user-images.githubusercontent.com/871273/177043232-99bcf39a-b7a4-49ef-b073-4f5e2e942924.jpg)

![exported_IMG_20220701_201741_04](https://user-images.githubusercontent.com/871273/177043241-0d4cb615-d860-4513-9757-0df0aba805e5.jpg)

XMP file:

[IMG_20220701_201741.jpg .xmp.txt](https://github.com/darktable-org/darktable/files/9034988/IMG_20220701_201741.jpg.xmp.txt)

**Platform**

* darktable version : 4.1.0+22~gd39d5f66d
* OS                :  Linux - 5.15.0-39-generic 
* Linux - Distro    : Ubuntu 20.04
* Memory            :  16 GB
* Graphics card     :  GeForce GTX 960M 
* Graphics driver   : 470.129.06
* OpenCL installed  :  OpenCL 3.0 CUDA, SM_20 SUPPORT

**Additional context**

 - Can you reproduce with another darktable version(s)? yes with version 3.8 / 4.0 / 4.1
 - Can you reproduce with a RAW or Jpeg or both? JPEG
 - Are the steps above reproducible with a fresh edit? Yes
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? yes
 - Do you use lua scripts? No

**Comment by Nilvus** [comment] 2022-07-03 15:31
Probable duplicate of  #4435

**Comment by kofa73** [comment] 2022-07-05 04:59
Check also https://github.com/darktable-org/darktable/issues/10283
There we investigated different export sizes and quality options.

**Closed** 2022-07-05 05:22 UTC
Labels: duplicate
