### ISSUE TITLE
Nikon Z 7 ii

### ISSUE THREAD

**Issue by bdkramer** [darktable-org/darktable#9809] opened 2021-08-14 19:16 UTC
Nikon Z7ii raw samples have been uploaded to the raw.pixls.us repository.

**Comment by johnny-bit** [comment] 2021-08-14 19:36
Duplicate of #7282
Support for Nikon Z 7 II was part of 3.6 release (https://www.darktable.org/2021/07/darktable-360-released/):

> - Nikon Z 6_2 (14bit-compressed, 14bit-uncompressed, 12bit-compressed, 12bit-uncompressed)
> - Nikon Z 7_2 (14bit-compressed, 14bit-uncompressed, 12bit-compressed, 12bit-uncompressed)

**Closed by johnny-bit** 2021-08-14 19:36 UTC
Labels: duplicate, scope: camera support
