### ISSUE TITLE
Rating work flow not working with 3.2.1

### ISSUE THREAD

**Issue by Ch3nt3** [darktable-org/darktable#6506] opened 2020-10-11 18:23 UTC
**Describe the bug**
With the new version when importing images and setting the image selection to "no star" I select the first image and rate it with the desired star. The next image in line is shown, but not selected, therefore no rating can be assigned to the shown picutre. When moving the cursors a bit, the image becomes highlighted and a rating can be given.

**To Reproduce**
1. Go to light table view and select a film roll. Make sure all images have no star rating.
2. Click on "show" and select "no star"
3. Select the first image and apply a star rating (any)
4. See error: the image disappears, but the next image is not selected. No rating can be given to the subsequent image, before the image is highlighted by a slight cursor movement.

**Expected behavior**
1. Go to light table view and select a film roll. Make sure all images have no star rating.
2. Click on "show" and select "no star"
3. Select the first image and apply a star rating (any)
4. The image disappears. The next image is selected. The next image can be rated until no more images are shown and all images in the film roll have a star rating.

**Screenshots**
the two screenshots show the lightroom view before and after applying the star rating. 

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Fedora 31
 - OpenCL not available
 - graphics card drive not known

![Bildschirmfoto von 2020-10-11 20-22-32](https://user-images.githubusercontent.com/22591651/95686666-920fb100-0bff-11eb-8939-0c6a7f9e6b96.png)
![Bildschirmfoto von 2020-10-11 20-22-39](https://user-images.githubusercontent.com/22591651/95686670-93d97480-0bff-11eb-8757-a06d8df0707b.png)

**Comment by jonas-hagen** [comment] 2020-10-11 20:01
We have a similar issue here that might be caused by the same bug, so I report here rather than opening a new issue, as this might give some more context.

**To reproduce:**

1. Lighttable, select film roll
2. Select "view >= one star"
3. Scroll down
4. Rate an image to 0 stars

**Observation:**

1. Image disappears (because of "view >= one star")
2. Scroll resets to top

**Expected behaviour:**
Next image should be selected. Scroll should be unaffected.

**Platform:**
Darktable Version: 3.2.1
OS: Fedora 32

**Comment by AlicVB** [comment] 2020-10-11 20:35
yes, this is a known bug which is already fixed in master (future 3.4 version)
thanks for the report !

**Closed by AlicVB** 2020-10-11 20:35 UTC

**Comment by potocpav** [comment] 2020-11-17 14:33
Still can be reproduced in the latest master 1e01289 with settings imported from the 3.2.1-1 version. With factory settings (`rm ~/.config/darktable -rf`), the issue is fixed.
