### ISSUE TITLE
Importing images with "ignore JPEG files" selected still imports images to filesystem

### ISSUE THREAD

**Issue by junaru** [darktable-org/darktable#9184] opened 2021-06-07 05:37 UTC
**Describe the bug/issue**

Not sure if this is by design and working as inteded but JPEG files are still imported to filesystem even if "ignore JPEG files" is selected in settings. 

**To Reproduce**
1. Import same image in Fuji's compressed RAW and JPEG formats with "ignore JPEG files" selected: 
![Screenshot from 2021-06-07 07-59-28](https://user-images.githubusercontent.com/59161/120962143-d55af900-c767-11eb-9afd-70cc30b311e4.png)
2. Only the RAW file is present in filmroll:
![Screenshot from 2021-06-07 08-00-06](https://user-images.githubusercontent.com/59161/120962233-ff142000-c767-11eb-92e8-9397ecf493e4.png)
3. There is still JPEG file in the import folder
![Screenshot from 2021-06-07 08-00-30](https://user-images.githubusercontent.com/59161/120962369-47334280-c768-11eb-9d30-c59f83145212.png)

**Expected behavior**

JPEG's excluded from import to both filmroll and filesystem.

**Why described functionality is expected**

You shoot 100 photos in RAW but have JPEG enabled for mobile app sharing purposes.
You get home, select a range of photos that include both RAW and JPEG versions of the same photo and click import with "ignore JPEG files".
You get 200 files on filesystem but only 100 in fillmroll
You delete 80% of the filmroll photos in darktable and end up with 20 you want to keep.
You still have 100 extra JPEGs just sitting in your filesystem for photos you didnt even want to keep.

**Platform**

* darktable version :  3.4.1
* Linux - Distro    : Archlinux

**Additional context**

 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by phweyland** [comment] 2021-06-07 09:53
This is by design. 
dt 3.4 doesn't move the files.
With dt 3.6 you will still have to import in place (same behavior as dt 3.4) but also “copy and rename". In this last case, if "ignore jpeg" is checked, jpg files aren't copied.

**Comment by junaru** [comment] 2021-06-07 10:34
@phweyland Just noticed you redesigned the import dialog with https://github.com/darktable-org/darktable/pull/8734 Thank you!
Will test a build from master.

**Comment by Nilvus** [comment] 2021-06-07 16:39
@junaru: so I close this issue as the import dialog window as been completely redesigned for 3.6 and some parts are by design, as explained by @phweyland. Feel free to reopen if something remains or to answer if needed of course. Thanks.

**Closed by Nilvus** 2021-06-07 16:39 UTC
