### ISSUE TITLE
<primary>plus and <primary>minus no longer zoom image

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#4875] opened 2020-04-30 19:39 UTC
openSUSE Tumbleweed 20200428
NVIDIA GF106 [GeForce GTS 450], 390.132
darktable-3.1.0~git1383.0e7305a3d-2912.1.x86_64
OpenCL on
i7 12-core 36GB

I can no longer zoom image using <ctrl><+> or <ctrl><->
(gtk_accel_path "<Darktable>/global/zoom in" "<Primary>plus")
(gtk_accel_path "<Darktable>/global/zoom out" "<Primary>minus")

scroll wheel and two finger drag on mouse pad still work

**Comment by elstoc** [comment] 2020-04-30 20:08
Works for me, though "plus" seems wrong - at least on my keyboard layout, plus shows up in the shortcuts window as ``shift+=``

That's the problem with having default shortcuts that are non-alphanumeric characters - the key combination to get to them differs between keyboard layouts.

Can you try re-mapping to see if you still get the issue?

**Comment by ptilopteri** [comment] 2020-05-01 00:01
@elstoc , explain how/what you want me to remap.

fwiw: <ctrl><+> is quite generic for zooming in, even in window and especially in linux and has been standard in dt for since I can remember, re: 2009/2010

**Comment by elstoc** [comment] 2020-05-01 07:47
Sorry what I meant was try going into the shortcuts window and remapping the zoom shortcuts to a different pair of keys, then try mapping them back again, and see what happens. 

One thing I do notice is that I have to click on the image before the shortcuts will register. Does that make a difference?

**Comment by elstoc** [comment] 2020-05-01 09:44
> One thing I do notice is that I have to click on the image before the shortcuts will register.

Ok this might have been me: #4721 

This needs to change to pass keyboard focus to the centre image rather than the iop module clicked on. I'll submit a new PR.

**Comment by elstoc** [comment] 2020-05-01 15:58
See also #4891 for some related fixes. If this is merged the 'global' zoom options will be moved into the individual darktable/lightroom views, albeit with the same default key combinations <primary>+<plus/minus>.

**Comment by elstoc** [comment] 2020-05-01 20:33
As discussed in my PR #4881 I have been unable to reproduce any issues apart from the one I mentioned in the comments.

Tested on darktable 3.1.0+1390~gcc18fbf01, ArchLinux.

**Comment by ptilopteri** [comment] 2020-06-02 00:40
<primary><shift><+> works but <primary><keypad+> does not
this is still a problem

**Closed** 2020-06-05 09:37 UTC
Labels: no-issue-activity
