### ISSUE TITLE
Image appears too warmth when using some modules (ToneEQ or diffuse/sharpen or ....)

### ISSUE THREAD

**Issue by atomikdg** [darktable-org/darktable#17151] opened 2024-07-16 10:31 UTC
### Describe the bug

I saw this bug when switching between local contrast and local contrast fast (diffuse/sharpen). 
This seems not related to a particular operation using module. I had it with color balance rgb on/off (when off, if I reset the module the yellow/warmth colors disappears). 
Also when zooming, the colors came back to normal.

If you need more information let me know. 

Version: last 4.8.x ( 18026f9f50e97199a719627b0d61532e88aa4b23 ) but don't know when this bug came in. 

### Steps to reproduce

See videos here :  https://nx22856.your-storageshare.de/s/aNgjDZSmcxNkzyo

### Expected behavior

Image should be with "correct" colors

### Where did you obtain darktable from?

self compiled

### darktable version

4.8.x 18026f9f50e97199a719627b0d61532e88aa4b23

### What OS are you using?

Linux

### What is the version of your OS?

Opensuse tumbleweed 

### Describe your system?

Same behavior wayland and X11
32 Gb ram
8GB video nvidia

GTK+:
libgtk-3.so.0 => /lib64/libgtk-3.so.0 (0x00007fb0e7c00000)
libcolord-gtk.so.1 => /lib64/libcolord-gtk.so.1 (0x00007fb0e83dd000)

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

nvidia 550.100 RTX 3050 8Gb

**Comment by jenshannoschwalm** [comment] 2024-07-16 13:37
This is a not considered to be a bug I would say. You observe the effect of the very large filter radius.

If you want to avoid that You'd have to use the HQ button in darkroom.

**Comment by jenshannoschwalm** [comment] 2024-07-18 13:48
I can't reproduce here yet. Could you provide the image plus xmp, a log with '-d pipe' and the video while you reproduce the issue. That might help.

I guess you are sure your build is ok?

**Comment by atomikdg** [comment] 2024-07-20 09:05
Yes my build is ok I tried with clang and gcc: same behavior
Yesterday I have reproduced it (not with -d pipe). I'm trying today with -d pipe and give you the log

**Comment by atomikdg** [comment] 2024-07-20 09:25
Another info: The warmth colors are exactly like when color calibration module is OFF

**Comment by jenshannoschwalm** [comment] 2024-07-20 10:46
> Another info: The warmth colors are exactly like when color calibration module is OFF

Ok, so i might have to check with images where there is a big difference between colors before / after color calibration.

I would also be good if you could check if the issue is happening with the temperature settings "camera reference" and / or "as shot to reference"

**Comment by atomikdg** [comment] 2024-07-21 18:51
@jenshannoschwalm 

On the previous nextcloud link (first post) you will find:

-The XMP + NEF files
-Two new videos: bug_clang.mkv and bug_clang_expo/mkv
-Two log files (-d pipe) relatives to the videos
-A video with camera ref and as shot to ref --> I reproduced the bug with "camera reference". 
-A video when I activate or deactivate some modules

I can't reproduce it with gcc... but with clang 18.1.8 (I think I was wrong in my previous post but will try when I have some time).

**Comment by jenshannoschwalm** [comment] 2024-07-21 18:55
It would be **very / extremely** important to know if this is a clang-only issue!

**Comment by jenshannoschwalm** [comment] 2024-11-30 18:05
Closing as no proper info provided.

**Closed** 2024-11-30 18:06 UTC
Labels: no-issue-activity
