### ISSUE TITLE
libdarktable.so => not found

### ISSUE THREAD

**Issue by msdobrescu** [darktable-org/darktable#11307] opened 2022-03-10 10:44 UTC
**Describe the bug/issue**

The application runs properly, but searching for missing libs would bring tens of `libdarktable.so => not found` errors.

**To Reproduce**
Run the following check script:

```
#!/bin/bash

ifs=$IFS
IFS=':'

libdirs="/bin:/usr/bin:/lib:/lib64:/usr/lib:/usr/lib64" #"/:opt/bin:/opt/firefox/"
extras=

#  Check ELF binaries in the PATH and specified dir trees.
for tree in $PATH $libdirs $extras
do
        echo DIR $tree

        #  Get list of files in tree.
        files=$(find $tree -type f)
        IFS=$ifs
        for i in $files
        do
                if [ `file $i | grep -c 'ELF'` -ne 0 ]; then
                        #  Is an ELF binary.
                        if [ `ldd $i 2>/dev/null | grep -c 'not found'` -ne 0 ]; then
                                #  Missing lib.
                                echo "$i:"
                                ldd $i 2>/dev/null | grep 'not found'
                        fi
                fi
        done
done

exit 
```

**Expected behavior**
The placement of `libdarktable.so` should be moved on a standard path.

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : Linux
* Linux - Distro    : Gentoo
* Memory            : 61.6 GiB of RAM
* Graphics card     : NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : KDE Plasma Version: 5.23.5, KDE Frameworks Version: 5.90.0, Qt Version: 5.15.2
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by parafin** [comment] 2022-03-10 10:54
libdarktable.so shouldn't be moved anywhere, it's not a library to link against externally. Furthermore everything works fine, because libdarktable.so is always loaded before any of the plugins that link against it - linker doesn't have to find libdarktable.so for them. Basically there is no bug.

But, for tools such as cited script, current situation is indeed somewhat problematic. It can be solved by setting RPATH correctly for plugins, not by moving anything. Not sure if any of the devs is interested in implementing this, so feel free to propose a PR/patch to cmake files.

**Comment by msdobrescu** [comment] 2022-03-10 11:13
Sure, but I actually don't know how, otherwise I would have done it. As I see your Gentoo icon, would you care to direct me?

**Comment by parafin** [comment] 2022-08-11 08:25
This isn't fixed as far as I know.

**Comment by Nilvus** [comment] 2022-08-11 08:47
> This isn't fixed as far as I know.

Hmm, ok. I close it because you say there is no bug...

**Comment by parafin** [comment] 2022-08-11 08:53
It's not a bug in a sense that it doesn't cause any big problems, but it's still misconfigured cmake. I might take a look some day.

**Comment by msdobrescu** [comment] 2022-08-14 05:02
I build it with luet for MocaccinoOS based on Gentoo official emerge and I don't get the error anymore.

**Comment by parafin** [comment] 2022-08-16 11:15
@msdobrescu, sorry, just to confirm, you built the branch from PR #12314 and with those changes the error is gone, while unpatched 4.0 or master branch still produces the error, correct?

**Comment by msdobrescu** [comment] 2022-08-16 11:31
Yes, I can bring whatever branch I need, customize it, patch it, also do my custom builds. I did it locally.
I don't get the error anymore.

**Closed** 2022-08-16 11:40 UTC
Labels: feature: enhancement, bug: invalid
