### ISSUE TITLE
Darkroom image goes black if filmicRGB, local contrast and crop and rotate are used.

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#3987] opened 2020-01-01 16:02 UTC
I'm new to Darktable, drawn by the very interesting filmicRGB.  However I've soon hit a problem.  I see there are some closed issues involving black screens but I can't see an open one that matches my issue so here goes.

Issue: with very few tools in use, the Darkroom image window goes black if I use filmicRGB, local contrast and crop and rotate.  If any is switched off, the image re-appears.

System: Ubuntu 18.04.3    core i7
No graphics card/GPU, using i7 built-in graphics
Darktable 3.1.0~git125.05f1bf829

To reproduce:
Open RAW.  Open filmicRGB and make a few changes.
Open local contrast.
Open crop and rotate, select keystone / vertical, drag the two guides a little. Cllck OK.
Image goes black.

Apart from the 4 "mandatory" tools, only filmicRGB local contrast and "crop and rotate" are switched on. Switching any off causes the image to re-appear.
Export profile = sRGB(web safe)
Input profile=standard color matrix.   Working=linear rec2020 rgb   gamut clip=sRGB
Demosaic and black/white points not altered.
White balance can be on or off, doesn't affect black screen behaviour.
![Screenshot from 2020-01-01 15-54-14](https://user-images.githubusercontent.com/16868433/71643248-07347a00-2caf-11ea-8f3a-f51851f0b0b8.png)

[_6D_00258.CR2.xmp.txt](https://github.com/darktable-org/darktable/files/4014227/_6D_00258.CR2.xmp.txt)

With local contrast switched off -
![Screenshot from 2020-01-01 15-57-23](https://user-images.githubusercontent.com/16868433/71643277-8629b280-2caf-11ea-803b-9ba239c6a368.png)

Photo taken uniWB style so is green.  Using white balance makes no difference to the black screen behaviour.

**Comment by kanyck** [comment] 2020-01-01 17:30
I believe you're suffering from https://github.com/darktable-org/darktable/issues/3865
Seems to be fixed in git version. Try it or wait the devs to backport this pull request into 3.0.0.

**Comment by RawConvert** [comment] 2020-01-01 18:41
OK, thanks.  I'd quite like to compile Darktable but quickly got stuck when I tried recently.  I know this is not a help desk but if you could point me at a script that would be really great, for example rawtherapee has this - http://rawpedia.rawtherapee.com/Linux.  Even just the dependencies would be good, I found a list, but they didn't all work, if adding "dev" doesn't fix it I'm stuck!

**Comment by aurelienpierre** [comment] 2020-01-13 20:27
Duplicate of #3865

**Closed by aurelienpierre** 2020-01-13 20:27 UTC
