### ISSUE TITLE
Chromatic Aberrations introduces false colours if the crop is small

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#8191] opened 2021-02-11 21:29 UTC
dt 3.4 release   Ubuntu 18.04

Green and magenta artefacts appear to be generated by the CA module if you heavily crop an image, noticed whilst trying to take just one face from a group photo.

N.B. This is in the jpeg output, not just on the preview.

Suggested method to demo: take a raw with detail against brighter background. Make a small crop (say around 500 pixels square) with CA on. Output jpeg.  Hopefully see aberrations as below.  If not, adjust crop.  Amount of aberration seems to depend on actual crop dimensions.

Examples
1. full frame for reference
![_MG_3584-test-crane-whole-image-V0-sRGB](https://user-images.githubusercontent.com/16868433/107699954-b1524400-6cae-11eb-9bea-d4e4991fb8cf.jpg)

2. Crops
![_MG_3584-test-crane-V4-sRGB](https://user-images.githubusercontent.com/16868433/107700066-de9ef200-6cae-11eb-94bd-da16d5e9ef12.jpg)
[_MG_3584-test-crane-V4-sRGB-XMP.txt](https://github.com/darktable-org/darktable/files/5968509/_MG_3584-test-crane-V4-sRGB-XMP.txt)

These two are esp. bad. See the colour flipping from one image to the next.  And moving from edge to edge.
![_MG_3584-test-crane-V5-sRGB](https://user-images.githubusercontent.com/16868433/107700140-fa09fd00-6cae-11eb-9620-e005ceedd729.jpg)

![_MG_3584-test-crane-V2-sRGB](https://user-images.githubusercontent.com/16868433/107700151-feceb100-6cae-11eb-883a-8645f3e7a97c.jpg)

Larger crop seems ok -
![_MG_3584-test-crane-V1-sRGB](https://user-images.githubusercontent.com/16868433/107700162-02face80-6caf-11eb-9240-d1de79805cd1.jpg)

**Comment by jenshannoschwalm** [comment] 2021-02-12 10:17
Yes, that's a known issue of the correction algorithm not well suited to dt's concept of regions. Unfortunately there can't be done much good ... I will push a pr soon at least tackling some parts of this problem.

**Comment by RawConvert** [comment] 2021-02-12 11:58
Ok thanks.
Are regions related to the messages I sometimes get in the terminal window running dt - "numblock=X" ?

(I knew the preview sometimes has artefacts but thought the output was fine)

**Comment by paolodepetrillo** [comment] 2021-02-13 00:59
Not sure if this is related but I saw a similar issue [described here](https://github.com/Beep6581/RawTherapee/issues/5800). I was using RawTherapee at the time so filed the issue there but the code in Darktable is almost the same and the same file showed the same artifacts in Darktable.

Trying to review the code without actually understanding the theory of what it's doing, I did find a corner case that looked like an array being indexed improperly, described in [this comment](https://github.com/Beep6581/RawTherapee/issues/5800#issuecomment-646032052). Correcting the white balance prior to the CA correction avoided the corner case for my image. As far as I can tell the error in the corner case still exists but maybe would only be encountered in a case where the CA correction isn't going to be successful anyway?

**Comment by jenshannoschwalm** [comment] 2021-02-13 06:42
Thank you for reminding me of that issue. I think we can't escape that cornercase or at least i know of no solution it. But we could use a better warning

**Comment by RawConvert** [comment] 2021-02-13 11:17
Perhaps my example was not the best - I couldn't post the original I found this on.
However, it's not just a corner issue I think.  Here's an example from the middle of the image.  Does CA work beyond the crop to avoid bad boundary effects? - hopefully so!

CA on -
![9002-CA-on](https://user-images.githubusercontent.com/16868433/107848591-8a019100-6dec-11eb-8cd1-c297497dda7f.jpg)

CA off -
![9002-CA-off](https://user-images.githubusercontent.com/16868433/107848597-8f5edb80-6dec-11eb-9835-2c2b92417f87.jpg)

![9002-whole-frame](https://user-images.githubusercontent.com/16868433/107848600-938af900-6dec-11eb-8e4c-8df933f67f0c.jpg)

**Comment by jenshannoschwalm** [comment] 2021-02-13 12:06
@RawConvert the overall issue is **not** a cornercase at all. The current algo presents data even if the algo can't work reliably. Most likely visible when zooming in or cropping. If you zoom the image in darkroom windows is vastly different from what is exported. My "cornercase" comment was just referring to the rt issue @paolodepetrillo mentioned. In rt code it's mostly a cornercase, in dt it's not at all.

**Comment by RawConvert** [comment] 2021-02-13 13:29
Thanks for the info.  Out of interest though, does the algo work on just the crop pixels or more than that?

**Comment by jenshannoschwalm** [comment] 2021-02-13 14:39
> does the algo work on just the crop pixels or more than that?

I don't understand ...

**Comment by RawConvert** [comment] 2021-02-13 16:06
I'm assuming (perhaps wrongly) the maths/algo gets tricky at the boundaries of the image, and if so that might be more obvious with a small crop, as here.  So it could be better to correct the whole image and let the crop take its part, rather than just work on the crop area.

**Comment by jenshannoschwalm** [comment] 2021-02-13 16:49
That's one of the problems with darktable regions concept in the pipeline. If you crop, the size of the area that is presented to every module might not be large enough for the modules algorithm. One of several reasons a redesign of the pipeline is discussed from time to time.

**Comment by jenshannoschwalm** [comment] 2021-03-17 17:51
@TurboGit duplicate of issue closed when merging CA correction

**Comment by jenshannoschwalm** [comment] 2021-04-10 13:06
@RawConvert please concider this issue to be closed as fixed in master.

**Closed** 2021-05-10 18:30 UTC
Labels: no-issue-activity
