### ISSUE TITLE
Failure to import files if path contains letters "æ", "ø" or "å"

### ISSUE THREAD

**Issue by plevold** [darktable-org/darktable#9755] opened 2021-08-07 19:42 UTC
**Describe the bug/issue**
Darktable fails to import files if the path contains a Norwegian letter ("æ", "ø" or "å"). This probably applies to other letters/characters as well, but I haven't been able to precicely figure out which ones.

**To Reproduce**
1. Create a new folder C:\Users\<username>\Pictures\følder (notice the "ø" instead of "o")
2. In Darktable, click on "add to library"
3. Browse to folder
4. Click "add to library"
5. Darktable claims that 1 image was imported, but none appear in library

**Expected behavior**
By replacing the "ø" with "o" in the folder name the import works as expected.

**Screenshots**
Import dialog:
![image](https://user-images.githubusercontent.com/10157556/128611835-7cd51033-3c6d-450d-b473-7ee110559999.png)

Resulting view after import:
![image](https://user-images.githubusercontent.com/10157556/128611844-f95ebe84-aa07-4cde-b6f1-5bdc3200b9d5.png)

**Platform**
* darktable version : 3.6.0
* OS                : Win10 (19042.1110)
* Memory            : 16 GB
* Graphics card     : Intel i7-8665U (integreated graphics card)
* Graphics driver   : unkown
* OpenCL installed  : unkown
* OpenCL activated  : unkown

**Comment by johnny-bit** [comment] 2021-08-07 20:44
Duplicate of #9475, #9596 & #9629, fixed in master by #9498

**Closed by johnny-bit** 2021-08-07 20:44 UTC
Labels: duplicate
