### ISSUE TITLE
OpenCL tuning for memory issue in _opencl_get_unused_device_mem

### ISSUE THREAD

**Issue by jenshannoschwalm** [darktable-org/darktable#12001] opened 2022-06-07 08:32 UTC
**Introduction**
Since nvidia 515 driver series becoming available on some distributions there have been some users reporting crashing OpenCL if the tune-for-memory option is active.

I started investigating the changelog of the driver plus again OpenCL docs, not sure if we can have a correct and immediate fix for the problem.

**Describe the bug/issue**
This seems to be directly related to the algorithm that checks the available memory for a device.

Also at least @aurelienpierre reported occasional crashes with 510 driver series, so far not analysed enough to know for sure if this is the checking algorithm or modules taking more cl memory than allowed, wrongly setting parameters in the module's tiling_callback.

**To Reproduce**
Switchin on the tune memory option

**Expected behavior**

stable system

**Platform**

* darktable version : master
* Graphics card     : nvidia
* Graphics driver   : 515 series ???
* OpenCL installed  : yes
* OpenCL activated  : yes

 @TurboGit will further investigate tonight and see what can be done here ...

**Comment by elstoc** [comment] 2022-06-07 13:24
I don't get crashes myself, but the system freezes in the darkroom (with "working..." overlaid on the image) and eventually the UI becomes unresponsive and I have to `kill -9` darktable.

We might be better to remove this option for the time being (make it do nothing, and remove it from the prefs dialog) given how close we are to the release.

**Comment by gi-man** [comment] 2022-06-07 13:44
> I don't get crashes myself, but the system freezes in the darkroom (with "working..." overlaid on the image) and eventually the UI becomes unresponsive and I have to `kill -9` darktable. It happens on fresh edits during UI interaction (so no intensive modules being used) and can be reliably triggered by zooming the image slightly.
> 
> We might be better to remove this option for the time being (make it do nothing, and remove it from the prefs dialog) given how close we are to the release.

Are the system freezes due to GPU? I had a similar issue (slow UI) on the lighttable and the "working...", but it was happening when the system was using the CPU instead of the GPU. I switched to Very Fast GPU to force the use of GPU only.

**Comment by elstoc** [comment] 2022-06-07 13:47
No useful logs are output so I can't tell exactly what's causing it, but it only happens when the "tune OpenCL performance" pref is set to "memory size".

**Comment by jenshannoschwalm** [comment] 2022-06-07 13:53
In fact the nvidia 515 issues (eltoc didn't mention this but he is also using 515) seem to be linux related, maybe related to kernel interface. Unfortunately i am not able to test this in depth atm as my system doesn't offer the latest driver in "stable" yet due to other problems.

So i propose to extend the tuning menu by adding sort of good-old-headroom entries like

- 400MB, 400MB + transfer, 600MB, 600MB + transfer

so we can offer almost perfect settings also for those with unstable memory testing in an interactive way and will be able to support this hopefully in a more stable way.


Will do a suggesting pr tonight

**Comment by jenshannoschwalm** [comment] 2022-06-07 14:04
> No useful logs are output so I can't tell for certain exactly what's causing it, but it only happens when the "tune OpenCL performance" pref is set to "memory size" and not when it's set to "nothing".

That's what aurelienpierre has observed with 510 drivers too. I have **never** observed such an issue myself, could very well be a module taking too much mem and not correctly falling back to cpu instead of proper tiling.

**Comment by jenshannoschwalm** [comment] 2022-06-07 14:08
> Are the system freezes due to GPU? I had a similar issue (slow UI) on the lighttable and the "working...", but it was happening when the system was using the CPU instead of the GPU. I switched to Very Fast GPU to force the use of GPU only.

I observed that too. Highlights laplacian with "insane settings" tried to get the GPU but failed and on cpu it sometimes took very long (i observed minutes on 48Mpix images, absolutely crazy.) Also can be seen with D&S

**Comment by elstoc** [comment] 2022-06-07 14:21
> So i propose to extend the tuning menu by adding sort of good-old-headroom entries like 400MB, 400MB + transfer, 600MB, 600MB + transfer

What's the benefit of this over a separate entry for keying extra headroom manually?

**Comment by AxelG-DE** [comment] 2022-06-07 17:41
For me is same than @elstoc, it is not really crashing, but system kinda freezes with "working..." and you can still alt+F4 to quit, but dt is not leaving the memory. Typing _ps aux | grep darktable_ still lists it and you need to kill -9 to get rid of it.

Today I downgraded the nvidia-driver to x11-drivers/nvidia-drivers-470.129.06 and the freeze is gone (I have one pic with method, clearly freezes right away)

**Comment by elstoc** [comment] 2022-06-07 18:55
For me it still fails on the default "memory size" option but works ok on the 400Mb and 600Mb options.

**Comment by jenshannoschwalm** [comment] 2022-06-14 06:26
Closing this for now

**Comment by jenshannoschwalm** [comment] 2022-06-17 04:47
Re-opened this and renamed the title as there is another report #12030 indicating there is a problem - so far only reported on nvidia 515/516 driver series - in `void _opencl_get_unused_device_mem(const int devid)`

**Comment by gi-man** [comment] 2022-06-17 12:37
@jenshannoschwalm I will keep commenting in this thread instead of the other one. 

Last night I was thinking the difference between 0 and 1 in the headroom could be something like a division by zero. 

I think the other user was @AxelG-DE . I think he just downgraded and kept the old drivers. I will downgrade, test and then do a clean install of the 516 version to test again.

I have multiple - d opencl from yesterday but not -verbose. I can do that. But maybe next week since I have too many commitments this weekend.

I started to read the release notes from Nvidia for 516 and found some interesting changes and the direction they are going.  Sections 2.7 and 2.8 - https://us.download.nvidia.com/Windows/516.40/516.40-win11-win10-release-notes.pdf

**Comment by gi-man** [comment] 2022-06-20 03:13
I had a small amount of time to look into this today. -d opencl -d verbose with headroom 0 and headroom at 1 looked identical. I'm still in same build darktable 3.9.0+1752

I then tried using d-all and the only difference using the same image is when darktable is closing. With headroom=0 it stops here:
14.206251 [db maintenance] checking for maintenance, due to rule: 'on close'.
14.206545 [db maintenance] main: [0/826 pages], data: [4/92 pages].
14.206565 [db backup] checking snapshots existence.
14.207598 [db backup] found file: library.db-pre-3.9.0.
14.207670 [db backup] found file: library.db-snp-20220505170344.
14.207732 [db backup] found file: library.db-snp-20220512204238.
14.207793 [db backup] found file: library.db-snp-20220521194446.
14.207852 [db backup] found file: library.db-snp-20220529215401.
14.207911 [db backup] found file: library.db-snp-20220606160338.
14.207969 [db backup] found file: library.db-snp-20220613205105.
14.208467 [db backup] last snap: 20220613205108; curr date: 20220619223205.
14.208546 [undo] clear list for 2047 (length 0)
14.208565 [undo] clear list for 2047 (length 0)
14.333534 [undo] clear list for 2047 (length 0)
14.333560 [undo] clear list for 2047 (length 0)

With headroom=1
8.216293 [undo] clear list for 2047 (length 0)
8.216306 [undo] clear list for 2047 (length 0)
8.295393 [undo] clear list for 2047 (length 0)
8.295419 [undo] clear list for 2047 (length 0)
 [opencl_summary_statistics] device 'NVIDIA GeForce RTX 3060' (0): peak memory usage 1862936176 bytes (1776.6 MB)
 [opencl_summary_statistics] device 'NVIDIA GeForce RTX 3060' (0): 449 out of 449 events were successful and 0 events lost. max event=256
 [opencl_summary_statistics] device 'gfx90c' (1): peak memory usage 0 bytes (0.0 MB)
 [opencl_summary_statistics] device 'gfx90c' (1): NOT utilized

I noticed that with headroom=0, darktable stays running in the background(task manager) using ~260mb of memory and no CPU/GPU. I kill the task and I can run darktable again (database not locked). 

I will try downgrading the nvidia drivers tomorrow or anything else you want me to try.

**Comment by jenshannoschwalm** [comment] 2022-06-20 05:38
Thanks for your efforts! I would appreciate if you could post full log output for both cases: headroom=0 and headroom=400 

Your comments hint to some error while doing opencl cleanup, something i don't understand atm, so i am interested what happens here. -d opencl -d verbose are enough i think

**Comment by jenshannoschwalm** [comment] 2022-06-20 16:44
Thanks, so far i didn't find a clue what's going wrong...

**Comment by jenshannoschwalm** [comment] 2022-06-21 09:23
Just to let you know, have installed 515 here, same issue. Will track this down to understanding and possibly fix.

**Comment by gi-man** [comment] 2022-06-30 02:27
@jenshannoschwalm FYI Nvidia released a new driver today, 516.59. I'm on 4.1.0+19~g387e05538 using memory size on and large resources. I modified darktablerc to:

cldevice_v4_nvidiageforcertx3060_id0=0 and the problem returns.
cldevice_v4_nvidiageforcertx3060_id0=1 and no problems. Of course 400 is also no problem.

**Comment by gi-man** [comment] 2022-07-01 18:51
The part that has me thinking the most was the export via the lighttable vs darkroom. The export is a full use of the pipeline and it processing the image in GPU, but no crash or issue if I export from the lighttable without ever going into the darkroom. For now, the headroom greater than 0 works, so no big deal. The performance in my system is working pretty good.

**Comment by gi-man** [comment] 2022-08-11 13:26
Ive been using Fedora 36 on my system, but I noticed that nvidia updated the windows driver to 516.94. I switched to windows to test it. It continues to crash if set to zero.

**Comment by jenshannoschwalm** [comment] 2022-08-11 14:45
Thanks. I will reinvestigate later

**Comment by hqhoang** [comment] 2022-09-15 20:20
I did have the problem you described in the issue, with 515 but not 510. But for me, it's not just darktable, the whole Ubuntu 22.04 gnome-shell froze. The mouse cursor can still move but nothing else on the screen, music still plays, I can still switch to another terminal/console (Ctrl-Alt-F3). When switching back using Ctrl-Alt-F1 or Ctrl-Alt-F2, it gets me to the login screen, and after logging in it's just a black screen with the mouse cursor can still move around. Tried killing darktable from Ctrl-Alt-F3 terminal doesn't help. The only solution for me is to reboot. I also disabled all gnome extensions and deleted ~/.config/darktable and ~/.cache/darktable to start fresh. I pull and compile from master branch every one or two weeks.

I'm not sure if I should create a new issue, but with 515, I also found the above system freeze happens more often at the end of exporting multiple files (no OpenCL tuning). It has never happened in the middle of exporting, e.g. it can export 7 out of 8 photos just fine, but once it finishes exporting the last one, the freeze would happen. With 510, it happens maybe once every 2-3 weeks, but with 515, it's  once or twice a day. Let me know if there's anything you want me to try isolating since I likely can reproduce it somewhat consistently.

**Comment by gi-man** [comment] 2022-09-15 21:02
I think you should start a new issue for this and try to post some of the log. I've been using nvidia 515 of fedora 36 kde x11 on master for a while without these issues.

**Comment by jenshannoschwalm** [comment] 2022-09-15 21:39
@hqhoang absolutely no idea, I didn't have a single dt crash for months now and do I lot of Heav testing new opencl stuff.

The last issues I saw were related to dt trying to use so much of the graphics ram that likely some other apps got problems. Not sure about kde, I don't use it.

Also I am not aware of any other reports like yours right now.

As it happens so often it might be worth to always run dt with - d opencl -d tiling - verbose and open an issue with the log. That might be pretty long but might help.

Or maybe run dt under gdb with the above debug options.

A new issue with that log would likely help. But - no idea right now from my side.

**Closed** 2022-09-24 05:53 UTC
