### ISSUE TITLE
Image debug mode

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#4119] opened 2020-01-15 15:16 UTC
I think we should have a debug mode for developers and beta testers that allows to run the pixelpipe once for every code path (C, SSE2, OpenCL) and every OpenCL device (discrete/integrated GPU), then compute a root mean square error between C output and every other output, to ensure consistency between code paths. That would be especially helpful when reviewing PR.

That could be a checkbox to tick in preferences, then a text overlay in darkroom preview displaying RMSE stats.

**Comment by parafin** [comment] 2020-01-15 15:19
This is a duplicate of #3421

**Comment by aurelienpierre** [comment] 2020-01-15 15:22
But #3421 is an external script right ? It doesn't allow interactive editing and direct feedback.

**Comment by parafin** [comment] 2020-01-15 15:30
#3421 is a feature request for the same task, I don't think that we need 2 implementations of the same thing.

**Comment by aurelienpierre** [comment] 2020-01-15 15:48
The problem of using an external script on the output of the pipe is the integer encoding can hide some issues behind the quantization. Using float 32 buffers before uint conversion would be more reliable. Also, it's easier to debug corner cases by pushing the settings while having the stats in UI, and see how changing parameters affects the error. It's not really the same use case.

**Comment by parafin** [comment] 2020-01-15 16:00
Your idea seems to cover (or should cover) use case of #3421. If it's implemented inside dt, then there's no need for external script. All I'm saying that these 2 tickets should be merged, not that you should use solution from #3421.

**Closed** 2020-01-15 18:58 UTC
Labels: priority: low, scope: codebase, scope: image processing
