### ISSUE TITLE
Severe data loss

### ISSUE THREAD

**Issue by houz** [darktable-org/darktable#4776] opened 2020-04-20 12:44 UTC
In de8987c8f178f2a40aea43698990e8639fba0582 there were some changes to how metadata gets imported. This commit is severely broken.

- `import_apply_metadata` is referring to manually importing images and controls whether global overrides are applied! It has NOTHING to do with reading metadata from sidecar files!
- I don't know what those flags wrt. hidden and internal metadata mean, but they can't interfere importing things from sidecars either!

What currently happens is that with default configuration NO metadata from XMP files gets imported, and the subsequent write of the sidecar file writes it out WITHOUT all metadata. The result is that whenever you import an image or have dt re-read the metadata, you have lost all data.

For the time being I'll disable those checks so that the blow is hopefully not as bad.

**Comment by phweyland** [comment] 2020-04-20 13:08
>     * `import_apply_metadata` is referring to manually importing images and controls whether global overrides are applied! It has NOTHING to do with reading metadata from sidecar files!

That's the way it did work before. But that's why there were not any control on imported metadata in dt (everything was imported).
The goal of this (and maybe not well implemented) is to give the control. For example I don't want to import my name three times per image just because the the creator is set in the exif. 

> What currently happens is that with default configuration NO metadata from XMP files gets imported,

If that's the case that actually problematic and must be fixed.

**Comment by phweyland** [comment] 2020-04-20 13:23
> What currently happens is that with default configuration NO metadata from XMP files gets imported,
I see the bug. Selection of imported metadata shouldn't rely on `import_apply_metadata`.

**Comment by houz** [comment] 2020-04-20 13:29
Why is there a problem with importing the same thing several times? Keep in mind that there is an order to the fields. We first import exif, then iptc, then xmp, and each overwrites the previous as the value assigned to the key might be different. That is on purpose and essential for handling metadata properly.

**Comment by phweyland** [comment] 2020-04-20 13:37
> Why is there a problem with importing the same thing several times?

If I need them, no problem at all. If I don't that's just useless to have 200.000 records for nothing.

> Keep in mind that there is an order to the fields. We first import exif, then iptc, then xmp, and each overwrites the previous as the value assigned to the key might be different. That is on purpose and essential for handling metadata properly.

I think I've got this. My intention was not to change it.

Just to import what the user needs, discard what he doesn't need, and keep the db as clean as possible.

**Comment by houz** [comment] 2020-04-20 14:49
Sorry, I don't agree with that. darktable should always import all the data it sees. In fact, it should import way more than it currently does so you can use it to find images and change the settings from within darktable. But that's a topic for another day :smiley:

**Comment by houz** [comment] 2020-04-21 07:47
You just reintroduced the bug. Let me reiterate: Under no circumstances, no matter what is set in the config, may darktable not import ANY field in the sidecar it knows about.

Steps to reproduce:
```
$ mkdir foo
$ cd foo
$ cp /some/image.cr2 .
$ /opt/darktable/bin/darktable --configdir dt image.cr2
# go to lighttable, set metadata for the image, for example "name"
# enable the crawler in preferences
# close dt
$ vim image.cr2.xmp
# change metadata
$ /opt/darktable/bin/darktable --configdir dt
# dt finds the changed sidecar file. select it and tell dt to update the db from the xmp
# notice that the metadata did not get updated
```

Instead of using the crawler you can also set the name, remove the image from dt and import it again. It will come in without the name.

**Comment by phweyland** [comment] 2020-04-21 13:17
I can reproduce the crawler issue when I change a metadata value in xmp. I look at it.
A doubt. I don't know any metadata "name". Do I miss anything ?

> Instead of using the crawler you can also set the name, remove the image from dt and import it again. It will come in without the name.

The re import of an image with xmp imports whatever the content of the xmp.

**Comment by phweyland** [comment] 2020-04-21 14:19
>  `# dt finds the changed sidecar file. select it and tell dt to update the db from the xmp`

In fact I didn't get this detection for some reason. In that case, xmp info were not updated.
But once I get the detection and I tell dt to update from xmp, dt is updated with the new info.

So far I don't succeed in reproducing the issue you describe.

**Comment by phweyland** [comment] 2020-04-21 14:25
> Under no circumstances, no matter what is set in the config, may darktable not import ANY field in the sidecar it knows about.

By default settings your statement is perfectly valid to me, at least not to introduce unexpected behavior.

Now if the user doesn't want to (have to) manage some particular info and sets the ad hoc configuration, how this would be wrong ?

**Comment by houz** [comment] 2020-04-21 14:33
Then the user shouldn't use darktable. We can discuss if some metadata shouldn't be read from image files, but the xmp files must always be read. No matter what the settings are.

**Comment by houz** [comment] 2020-04-21 14:35
> I don't know any metadata "name"

Sorry, I meant creator. You put a name into that field, so my brain was confused.

**Comment by phweyland** [comment] 2020-04-21 14:35
> Then the user shouldn't use darktable. We can discuss if some metadata shouldn't be read from image files, but the xmp files must always be read. No matter what the settings are.

Is there any reason for that ?

**Comment by phweyland** [comment] 2020-04-21 14:38
> > I don't know any metadata "name"
> 
> Sorry, I meant creator.

Tested OK with creator also. I'm wondering what can make the difference.

**Comment by phweyland** [comment] 2020-04-21 14:45
Testing things I've noted an asymmetry between load sidecar file and write sidecar file.
The second one writes all info, history, metadata, tags, ... The first one only updates the history. @turbogit is that intentional ? Shouldn't it be symmetrical ?

**Comment by houz** [comment] 2020-04-21 14:53
> Is there any reason for that ?

The XMP is the place where dt stores its data. If the user sets any metadata it has to be kept of course.

> Tested OK with creator also. I'm wondering what can make the difference.

Are you trying with default config? That's why I started with a fresh configdir in my example.

**Comment by phweyland** [comment] 2020-04-21 15:05
> > Is there any reason for that ?
> 
> The XMP is the place where dt stores its data. If the user sets any metadata it has to be kept of course.
> 
> > Tested OK with creator also. I'm wondering what can make the difference.
> 
> Are you trying with default config? That's why I started with a fresh configdir in my example.

Yes, deleting everything in config , starting dt, import one image, set metadata, set the configuration flag for crawler, exit dt, modify xmp file, restart dt, on popup modify db, and check the metadata (need to hover the image to have the metadata updated on screen)


> > Is there any reason for that ?
> 
> The XMP is the place where dt stores its data. If the user sets any metadata it has to be kept of course.

Nothing different compared to db here. I still don't see what will be the negative or wrong effect of ignoring some of them (as soon as that's the user choice).

**Comment by TurboGit** [comment] 2020-04-21 21:11
> @TurboGit is that intentional ? Shouldn't it be symmetrical ?

I don't know. This was there before I came to dt, but it looks suspicious indeed. Maybe the commit log will enlighten us ? You are speaking of dt_exif_xmp_read() and dt_exif_xmp_write(), right ?

**Comment by phweyland** [comment] 2020-04-21 21:38
> You are speaking of dt_exif_xmp_read() and dt_exif_xmp_write(), right ?

Yes. "write sidecar files uses dt_exif_xmp_write(imgid, dtfilename) while "load sidecar files" uses     dt_exif_xmp_read(img, filename, history_only).

**Comment by TurboGit** [comment] 2020-04-22 11:34
@phweyland : Yes, "load sidecar files" should read metadata, if it is not the case it is a clear bug to me.

**Comment by phweyland** [comment] 2020-04-22 16:41
> Yes, "load sidecar files" should read metadata, if it is not the case it is a clear bug to me.

I've started to make the change, but, my mistake, this is not  "load sidecar files" but  "load sidecar file". The "s" makes the difference. This is not an xmp refresh. This is made to apply a given history to one or several images. Probably the user will not want to spray the metadata as well. 
Sorry for the confusion.

**Comment by phweyland** [comment] 2020-04-22 17:57
> This is not an xmp refresh. 

So how to refresh xmp on a specific image or folder ?
I've tried "refresh Exif" which only loads exif data, as it says, but ... overrides some xmp data (for example Exif.Photo.UserComment -> Xmp.dc.description) which are lost. 

> This commit is severely broken.

@houz Tobias, is the issue still alive ?

**Comment by TurboGit** [comment] 2020-06-05 08:10
Closing as it should be fixed.

**Closed by TurboGit** 2020-06-05 08:10 UTC
Labels: bugfix, no-issue-activity, priority: high
