### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Luch88** [darktable-org/darktable#10908] opened 2022-01-18 07:12 UTC
Really hope Im doing this the right way ..... 
![Screenshot_2022-01-18-09-01-20-888_com facebook katana](https://user-images.githubusercontent.com/97939537/149888225-50430a4d-56ae-492b-b0f1-82864f42cce1.jpg)
 Have been getting this error since yesterday. 

Got a recommendation to report it here ....

**Comment by elstoc** [comment] 2022-01-18 07:23
Please follow the instructions in the bug reporting template [here](https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=bug_report.md&title=) and provide as much information as possible. The dialog that appears tells you to share the backtrace file with us. You will need to navigate to the location given in the dialog and attach the text file to this issue.

**Comment by dterrahe** [comment] 2022-01-18 12:57
Please enter text rather than a screenshot of text. The github search functionality does not work on images, so it would be much harder to find this again later. The non-descriptive bug label doesn't help there either. Which all just works towards developers ignoring your issue, which is presumably not what you want.

**Comment by Luch88** [comment] 2022-01-18 16:02
It is really behind my knowledge. Not a coder - just followed the recommendation to report.....
I fount two of the bug reports . IDK if it is helpful. (can copy the content of the .txt if necessary ?
Have windows 10. intel(r) hd graphics 4600
Was working for a while with no problems till it happened. Was working on raw files.
[darktable_bt_5153F1.txt](https://github.com/darktable-org/darktable/files/7890455/darktable_bt_5153F1.txt)
[darktable_bt_1285F1.txt](https://github.com/darktable-org/darktable/files/7890456/darktable_bt_1285F1.txt)

**Comment by dterrahe** [comment] 2022-01-18 16:06
Duplicate of #10902

**Closed by dterrahe** 2022-01-18 16:06 UTC
