### ISSUE TITLE
“darktable.app” is damaged and can’t be opened. You should move it to the Bin.

### ISSUE THREAD

**Issue by Fedster** [darktable-org/darktable#14830] opened 2023-07-03 10:45 UTC
### Describe the bug

Hello, after I download Darktable 4.4.1 arm64 MacOS build, when I try to open it I get the message 

“darktable.app” is damaged and can’t be opened. You should move it to the Bin.

I have no idea why. I can install third party apps.

### Steps to reproduce

1 Download darktable-4.4.1-arm64.dmg from github or https://www.darktable.org/install/
2 Open the dmg
3 move Darktable.app to 'Applications'
4 Try and open Darktable, and get the error “darktable.app” is damaged and can’t be opened. You should move it to the Bin."

### Expected behavior

Darktable should open

### Logfile | Screenshot | Screencast

<img width="579" alt="Screenshot 2023-07-03 at 13 44 30" src="https://github.com/darktable-org/darktable/assets/7814163/c02a3879-358e-45f7-b0e3-35ec6377acd6">

### Where did you install darktable from?

darktable.org

### darktable version

4.4.1-arm64

### What OS are you using?

Mac

### What is the version of your OS?

Ventura 13.4.1 arm64

### Describe your system?

MacBook Pro running Ventura 13.4.1 arm64

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

NA

**Comment by kmilos** [comment] 2023-07-03 11:20
Duplicate of https://github.com/darktable-org/darktable/issues/14746

Please search before opening new issues.

**Closed** 2023-07-03 11:33 UTC
Labels: scope: macos support
