### ISSUE TITLE
"Inclusive" doesn't work when combining masks

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/darktable#8172] opened 2021-02-10 11:29 UTC
dt 3.5.0+1011~gcf8280351-dirty      Ubuntu 18.04

There seems to be a problem with the Combine Masks setting of "inclusive" when working with a parametric mask plus a drawn mask. Looking at the manual, 3.5.3.4 "combining drawn & parametric masks",  "inclusive" is an "OR" operation and the maths described means any pixel in either or both of the para and drawn masks will be in the resulting mask. However I'm finding this doesn't work. I think "inclusive" is useful, allowing a para mask to be expanded with brush work.

To demonstrate: take any image, add an exposure instance, choose para+draw, create a para mask (I did hue, hz).
Now draw something that's not currently yellow. All yellow disappears; ok.
Change "exclusive" to "inclusive". Now the whole image is yellow. I would expect the yellow now to be the para yellow plus the drawn area.

**Comment by TurboGit** [comment] 2021-02-10 12:14
Same with 3.4. & 3.2 BTW. So not sure we have a regression here. This will need more thought and a look at the documentation.

**Comment by TurboGit** [comment] 2021-02-10 18:19
Looking at the documentation the current behavior is correct. Please, double check and close the issue if you agree. TIA.

**Comment by RawConvert** [comment] 2021-02-10 19:23
What documentation do you mean pls?
I've been looking at this section from the manual 3.5.3.4 -

**Inclusive**
An alternative method of combining masks is to first invert each individual mask (subtract its value from 1.0), multiply
the inverted masks together, and finally invert the combined mask once again.
For a given pixel, the final mask will have a value of 1.0 if any of the individual masks are 1.0 at that location and it will
only have a value of 0 if all masks have a value of 0 at that location. This method of combination is known as inclusive.
Any individual mask can include a pixel by setting its value to 1.0, regardless of what the other masks do. Once a pixel is
fully included by a mask (its value is 1.0) there is no way for another mask to exclude it again.

So if we think about the pixels in neither mask, they are value 0 to begin with.  So invert to get 1.  Multiply together to get 1.  Invert to get 0.  So these pixels should not be part of the resulting mask, but they are, because the whole image is yellow.

What would be the point of a Combine Masks setting that always results in the whole image being selected?!

**Comment by todd-prior** [comment] 2021-02-12 04:28
@TurboGit 

Pascal, at least in Windows there is still at least one issue with the inclusive dialogue and perhaps others. I am going to look for feedback as I believe there are two bugs at least for windows.

So as you know up until recently in WIndows if you selected any mode other than exclusive the masking was corrupted and you had to reset the module and restart.

 My two observations testing tonight is that combined masks work fine in exclusive. If you overlap a drawn object with the parametric mask by default you mask only the area where both overlap or where they are both have a pixel value of one. Now if you invert the drawn mask you get the parametric mask except where they overlap as the drawn mask is now zero there  and only the parametric mask outside the drawn mask which is now 1 and 1 will show. Finally resetting the drawn mask and inverting the parametric mask will highlight everywhere inside the drawn mask  except the parametric mask portion overlapping as it is zero and all non parametric mask areas are now  1. All good so far.

The first thing that I find confusing is that the polarity for the drawn mask at default with a  value of 1 for a pixel value is shown as - polarity where as the parametric mask is +. I feel like they should all be positive signs when the result will be 1 and - when set to zero so this can be a bit confusing if you don't notice it.

Exclusive
Drawn -
Parametric
Output +
Input +

Inclusive
Drawn +
Parametric
Output -
Input -
There may be a reason for this but its a bit confusing

And the final bug which I don't recall back when I tested the masks a couple of years ago is you must use the toggle all channels to use inclusive mode; If you go strait to the mode in the drop down things get messed up...even if you correctly invert all the channels either before or after doing that. I think that is a bug or you should not be able to select it until the toggle all channels has been selected. At first I though it was because the output sliders are not visible so when you change the polarity you don't set that unless its visible but even revealing it and setting things correctly manually does not work.

If you do use the toggle all channels first then the same logical sequences listed above work as they should ie  inclusive and then inclusive where the drawn mask is inverted and then where the parametric mask is inverted will create the correct mask.....  If you accidently bypass the toggle all then I think the code is lost or missing a step  and you have to reset the module to get back

Also I am noticing that while editing the mask often drawn objects are not respecting the setting to show them and they disappear sometimes when the screen updates. It seems like you can usually get them back when you toggle the show drawn object button a few times. So clearly there appears to be a possible hiccup in the code here as well.

**Comment by todd-prior** [comment] 2021-02-12 04:36
![image](https://user-images.githubusercontent.com/44409419/107730366-38101c80-6cc1-11eb-8549-64826e975401.png)
Using toggle all
![image](https://user-images.githubusercontent.com/44409419/107730397-46f6cf00-6cc1-11eb-8a9b-ecc915d74726.png)
Inverting the channels first manually...then selecting inverted...
![image](https://user-images.githubusercontent.com/44409419/107730511-9e953a80-6cc1-11eb-87a1-a0ed30738aae.png)
Settings...and after doing this
![image](https://user-images.githubusercontent.com/44409419/107730563-bb317280-6cc1-11eb-9393-fb1de2c4bbe2.png)

**Comment by TurboGit** [comment] 2021-02-12 07:39
> So as you know up until recently in WIndows if you selected any mode other than exclusive the masking was corrupted and you had to reset the module and restart.

Just a side note that this bug was not Windows only.

**Comment by TurboGit** [comment] 2021-02-12 08:03
> The first thing that I find confusing is that the polarity for the drawn mask at default with a value of 1 for a pixel value is shown as - polarity where as the parametric mask is +. I feel like they should all be positive signs when the result will be 1 and - when set to zero so this can be a bit confusing if you don't notice it.

This has already been the case as far as I remember. Tested on 2.6 and current master:

2.6:

![Capture d’écran de 2021-02-12 08-59-55](https://user-images.githubusercontent.com/467069/107743459-2fdfcd80-6d11-11eb-9774-bd0909c73d4d.png)

master:

![Capture d’écran de 2021-02-12 09-02-14](https://user-images.githubusercontent.com/467069/107743482-3a01cc00-6d11-11eb-9f3c-e19bf5aa8413.png)

**Comment by TurboGit** [comment] 2021-02-12 08:05
I have also checked that the combining masks are working the same on 2.6 and 3.4 and seems to be what the doc described. So I'm not sure there is an issue (regression) with the masking in current master.

**Comment by todd-prior** [comment] 2021-02-12 13:34
@TurboGit 

Thanks for your reply.

I couldn't honesty remember if that was a change from the older versions or not and it may very well follow the math. It is just a bit strange that if you make a parametric mask and a drawn mask and start out in exclusive then the mask will be where both masks have a value of 1 yet when the user looks at the polarity the drawn mask shows inverted and the parametric is +. So in your head combining the masks you have to keep in your head that - for drawn means one and + means 0 for the drawn objects and the parametric is the opposite. I can deal with it but I bet it does confuse some....

**Comment by RawConvert** [comment] 2021-02-12 13:36
@TurboGit , I think your response above is less than adequate and doesn't do justice to the effort @todd-prior  and I have put in to try and improve the processing in this area.

You've mentioned a few times that you think masks are working in line with earlier versions of dt.  That doesn't mean they are correct!

You've said a couple of times it's working as per the "doc" but failed to say what the doc is, whereas I've quoted the manual and to the best of my belief this section clearly shows the "inclusive" mode is not working!

I've been thinking about dt masking for a while now and it seems to me that it has probably grown up piecemeal. Whilst there are several techy widgets, there is no user-focused model to help people use the facilities. I think what people would like are clear high-level principles supported by editing controls.

What are the high-level principles/model? Very simple, you have drawn masks, you have parametric masks, and you can combine them freely using the standard operators for sets.  That is, you can take the common part of 2 or more masks; the part shared by them all ("AND" operation).  This is perhaps the most common use case, and I suspect the only one most users are comfortable with, due to the complexity of the GUI.

Then you can take a mask (drawn or para) and add another mask to it. ("OR" operation).

Then you can take a mask (drawn or para) and remove from it another mask ("MINUS" operation)

The above operations are easy to visualise but to try and do them with the current processing is difficult or impossible.  There are multiple +/- buttons (5 of them), the Combine Masks dropdown, and the various channels (g, r,g,b etc), and the Mask Manager to contend with.  These things have a useful low-level purpose but the user is struggling to work out how it all fits together. It needs to be structured so that the user, starting with an image-based objective, like "I want to select that ship and change its contrast", and who understands the basic mask operations such as AND, OR, MINUS, can proceed without without brain-ache, frustration and wasted time.

In addition to AND, OR and MINUS there is of course "NOT", the inversion of a mask, and the +/- buttons for this.  It can be easier to visualise what you want to exclude from a module's effect rather than what is to be included.

"EXCLUSIVE OR" is another basic set operation where the resulting mask comprises the parts of two masks which are not in both of the masks.  I've never found I needed this but I don't see why it shouldn't be supported if the rest of the operations are.

The Mask Manager allows manipulation of drawn masks but not parametric ones, as far as I can see.  I think it's sensible not to distinguish between the two, they are all masks, and the para ones are so powerful that you really want to be flexible about processing with these.  The Mask Manager seems clunky to me, but I think it could be revised and built upon.  The idea of a tree structure where you combine "top level nodes" (=actual or derived masks) using the standard set operators seems good. Each node can have a tree under it whose parts can be combined.  You could go on down many levels.  At the end you have "elementary" masks which are either drawn or parametric.  In practice I can't imagine why you'd need more than say 3 levels, but who knows.  You could continue the current idea of moving masks up and down until you get the structure you need.  You'd need to be able to move the parts underneath a node with the node if you moved it.

A para mask can apply to the various channels - brightness, colour, saturation etc - but I think there are limitations because they all result in just one mask.  It would be good to have a separate mask for each if that's what you need.  E.g. you notice a "g" "grey" mask can accurately isolate an area you want to work on.  Except there's a coloured object within it you need to remove. So you take the "g" mask and subtract the "H" or "hz" mask.

The manual describes the arithmetic used for some of the operations.  Perhaps this needs reviewing?  I'm no expert but it sounds like working out pixel mask values is a bit like blend modes.  E.g. if using Exclusive mode (AND operation) and a mask pixel is "1" in one mask and 0.7 in another, what should the result be for scene-referred processing?  The average, geometric average, 1...?  (I assume values can be between 0 and 1 once para masks and blur etc. are taken into account)

dt's current processing allows a fair bit of the above processing to happen but it's tricky, confusing, poorly documented and buggy. It would be good to consider a substantial revision to mask processing, a valuable feature which not all raw processors have.

**Comment by todd-prior** [comment] 2021-02-12 13:39
There still is the issue if you do not press toggle all channels and go directly to the drop down and select inclusive then you get the wrong mask and you cannot get back with out losing the mask. You should be able to select inclusive and then adjust the channels to correct things but you can't so clearly selecting toggle all channels takes the code in the right direction but doing the mask manually by setting the channels your self and then selecting inclusive fail when I think it should not.....

**Comment by TurboGit** [comment] 2021-02-12 14:48
> You've mentioned a few times that you think masks are working in line with earlier versions of dt. That doesn't mean they are correct!

That mean that correct or not you cannot change the way it is working without breaking old edits. I'm not the original developer of the combine implementation  and I won't be the one to break things. So the subject of this issue ""Inclusive" doesn't work when combining masks" is not correct.

**Comment by TurboGit** [comment] 2021-02-12 14:50
> You've said a couple of times it's working as per the "doc" but failed to say what the doc is,

Haven't I sent a link previously :
https://www.darktable.org/usermanual/en/darkroom/masking-and-blending/masks/drawn-and-parametric/

**Comment by todd-prior** [comment] 2021-02-12 15:12
Depending  how you interpret things it doesn’t work fully. Right now it works as long as you hit toggle channels.

If you toggle the channels yourself and then select inclusive it does not work.

These two should be equivalent and they are not at least for me in the current master running Windows 10.

If they are not equivalent and one way produces the incorrect result and corrupts the output of the module this should be corrected when time permits..

**Comment by todd-prior** [comment] 2021-02-12 15:19
This manual text as described is not working…As I mentioned if you do go to the combo box the mask is not created properly…

“Inclusive mode
For this mode you set the “combine masks” combobox to inclusive mode and make sure that all polarity buttons of all the individual channels and of the drawn mask are set to negative (-). Your starting point is a mask where all pixels have a value of zero, i.e. no pixel is selected. You now adjust the parametric mask sliders to bring more and more pixels into the selection or you draw shapes on the canvas to select specific areas of your image.



You've said a couple of times it's working as per the "doc" but failed to say what the doc is,

Haven't I sent a link previously :
https://www.darktable.org/usermanual/en/darkroom/masking-and-blending/masks/drawn-and-parametric/

**Comment by TurboGit** [comment] 2021-02-12 15:30
Checked again against the doc and indeed inclusive does not match the maths. Now it would be good to know when has this been reversing!

**Comment by todd-prior** [comment] 2021-02-12 15:54
I am only speculating as again I cant remember but since it appears to work if you use the toggle all channels which now toggles on inclusive I am wondering if introducing this caused the issue. I think toggle all channels in the past just changed the channels and did not toggle the blending mode in the combo box.  I may be wrong but if so it may be related??  Just guessing…Really I never use all of these combinations that are possible and I think most people use a combination in exclusive so maybe that is why it never jumped out at anyone??


Checked again against the doc and indeed inclusive does not match the maths. Now it would be good to know when has this been reversing!

**Comment by TurboGit** [comment] 2021-02-12 22:02
Indeed the button that invert all masks is working as expected.

And now I see that just changing from excluding to including also works as expected. That is the whole image is selected in yellow. This is normal as at least one of the parametric channel include all the pixels. By inverting all the channels one by one you end up with the expected behavior. The same behavior that is directly accessible using the "invert all channels polarity".

Wasn't that the confusion? Or am I still confused?

**Comment by todd-prior** [comment] 2021-02-12 23:37
Okay so I will try to do this as best I can and I may be missing something but here I go.

Currently if you open a module and create a parametric and drawn mask it does so by default in exclusive mode.

This is the one thing I find strange. By definition this should mask only where both items are pixel values of 1. Fine and it does but as I mentioned earlier the drawn mask objects clearly have to be 1 or you would not get this mask and they are represented as negative polarity and the parametric mask (both input/output) are positive polarity so to me this seems strange and may be there is a reason but the mask works as expected if you come to adopt the fact that negative polarity for the drawn mask means the objects are 1 and the rest of the mask is zero where as the identical situation in the parametric mask if shown as positive.

That is weird to me but the mask works and once you know that you can combine things knowing how it will result.

The other part is more of an issue. From the manual and rightly so there should be no difference if you A) invert all the channels from default ..so drawn becomes + and both parametric channels are negative. Then you select inclusive and you should get the inclusive mask. Currently at least on windows you don’t. If you however move from the default situation of exclusive instead by using the toggle which toggles all the channels to the exact same settings that you manually tried and makes the change to inclusive then you get the right mask as I understand it to be, ie with any area that is 0 or 1 being masked and only areas where the drawn and parametric are both zero…again this is oddly to me when drawn Is + and the parametric mask is negative. Honestly it seems confusing but in any case this should give the same result and it does not….I can document it…

**Comment by todd-prior** [comment] 2021-02-13 04:23
To me I feel like the documentation description here is correct. 
 https://darktable-org.github.io/dtdocs/darkroom/masking-and-blending/masks/drawn-and-parametric/#typical-use-cases 

If you read it I feel that indeed for basic exclusive mode all the channels should be indicated as +. I believe this is their actual value in the software and how they perform but currently the drawn mask is shown - which would be zero for exclusive mode. So this I feel is just a display thing here.

After some experimentation what I find is that using the toggle all  button correctly inverts all the channels and selects inclusive and creates the right combined inclusive mask. It honors the existence of any parametric or drawn objects and makes the appropriate mask. This workflow inverts the "- polarity" drawn mask now shows here as + when it should be - but this appears again to be using the correct math and it is a display issue.

If you however you invert all the channels manually the parametric and drawn objects seem to be ignored and then when you select inclusive the entire mask is 1 and not zero where it should be. Also adding any objects or changing the parametric mask in this state inverted or otherwise has no impact. I would expect that using either route should lead to the same mask so some where in the code I think there is a hiccup....

Finally if you use the toggle all channels normally and then press it again  it would go back to exclusive and restore the correct mask and channel polarities and you can go back and forth by just repeatedly activating it. If you go in to inclusive mode by manual selection of the channels and using the drop down combo box  you can back out by reversing the manual steps but if you use toggle all to back out the mask is not restored and you have to restart
Visually this is an example
[Visual on Mask Results.pdf](https://github.com/darktable-org/darktable/files/5975147/Visual.on.Mask.Results.pdf)

**Comment by RawConvert** [comment] 2021-05-10 18:36
Just re-tested in  dt 3.5.0+1966~g12d7a9967-dirty.
Problem still present.

**Comment by ptilopteri** [comment] 2021-05-10 18:54
yes, but why test and report with non-current and dirty build?

**Comment by todd-prior** [comment] 2021-05-10 19:13
did you try the sigmoid module or some other PR...just means your code is not in sync with the master

**Comment by ptilopteri** [comment] 2021-05-10 19:17
remove the directories you build to, ie:
<somewhere>/darktable/bin 
<somewhere>/darktable/lib64 
<somewhere>/darktable/share

**Comment by RawConvert** [comment] 2021-05-10 19:27
I have those 3 folders under folder DT-Mast-2May21, so they are new with the build.
They also exist under previous builds, eg under DT-Mast-9Apr21, but surely the 2May build is not going to look there?
I can't see a darktable folder under Home or Computer (and hidden files are ticked to show)
Any ideas pls?!

**Comment by todd-prior** [comment] 2021-05-10 19:35
I think you need to delete your entire build directory and you need to do a clean reset of the master...the syntax escapes me but I will look it up if nobody provided it for you....Then you should be good to go...or do the clean reset and build it in a new directory called buildmaster or something..

**Comment by RawConvert** [comment] 2021-05-10 19:48
_I think you need to delete your entire build directory_
 => Not sure which dir you mean.  As I've said, I create a brand new one each time.
 _do a clean reset of the master_
 => How exactly do I do this pls?
_build it in a new directory called buildmaster or something_
 => DT-Mast-2May21 was a new dir!

**Comment by todd-prior** [comment] 2021-05-10 19:49
I think it is working better than before but you will need to show the output channels to see why you can have issues if channel polarity gets out of line. Using the "all channels" toggle to move between exclusive and inclusive works correctly as it did before. However if you set  inclusive from the drop down menu it will only toggle the output channel so you need to physically change the drawn mask and the input channel of the parametric mask manually and it matches the expecte inclusive result and you can reset things by manually reversing all of this which I am not sure you could do before. For the reverse going back via the menu to exclusive will again only toggle the output channel polarity back etc etc so basically again if you show all the channels and get the polarities reset  correctly  you get bacj to  the correct exclusive mask. I think this is better than before as I am sure I tried this to correct the previous behaviour and the mask would remain at some incorrect state. I am still not certain why a value of 1 essentially for the drawn mask is set to show a polarity that is negative and why the parameteric mask is positive in the exclusive state. The exclusive mask should mask areas where both the drawn mask and the parametric mask have a value of 1 so in my eyes this with be when both are + and not set at different polarities.  As long as you accept that negative polarity for the drawn mask = a value of 1 and you keep all the polarities strait I think the masks are giving the correct combinations....admittedly I just did a couple of quick checks.....

**Comment by RawConvert** [comment] 2021-05-10 19:51
Yes, it's a mess!

**Closed** 2023-03-26 00:19 UTC
Labels: no-issue-activity
