### ISSUE TITLE
Mac mini M2 on Sonoma 14.2.1 does not import any file

### ISSUE THREAD

**Issue by jacopobenetti2000** [darktable-org/darktable#16125] opened 2024-01-16 08:01 UTC
### Describe the bug

I tried both copy & import and add to library in both 4.6 and 4.4 dt but i have the same issue. I get the message (istantly) that all the images have been imported but don't show up in the collections (i tried every combination of filters). With the copy and import the message is "imported 0 images".

https://github.com/darktable-org/darktable/assets/116483964/8366bd33-2bfa-499e-8d6e-639f65f594d0

### Steps to reproduce

Import lighttable module
Add to library or copy & import
Select the files (in this case are canon RAWs)
Import 

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Mac

### What is the version of your OS?

Sonoma 14.2.1

### Are you using OpenCL GPU in darktable?

Yes

**Comment by zisoft** [comment] 2024-01-16 08:43
Import with "recursive subfolders" is broken.
This is already fixed in master.

Duplicate of #15894

**Closed** 2024-01-16 08:44 UTC
Labels: duplicate, Fixed in master
