### ISSUE TITLE
(Windows specific) "Elegant" themes - rendition of "light" fonts is bad

### ISSUE THREAD

**Issue by apostel338** [darktable-org/darktable#11945] opened 2022-05-30 14:30 UTC
Since _elegant_ will become the new default theme, I would like to point out that Windows has a problem with the rendition of the used "light" fonts. They are hard and uncomfortable to read.

This is Linux (KDE) default
![linux Screenshot 2022-05-30 135906](https://user-images.githubusercontent.com/96216629/171010644-a9e33f4d-9f36-48aa-8edb-ef41769dbcdc.png)

Windows default (Segoe)
![windows default Screenshot 2022-05-30 140512](https://user-images.githubusercontent.com/96216629/171010828-e4527c24-3a9f-465f-93eb-59cbad57f08d.png)

Windows size set to 10 to match Linux (Segoe)
![windows size 10 Screenshot 2022-05-30 140446](https://user-images.githubusercontent.com/96216629/171010902-7e151404-bd0e-4c60-8598-1bb6207ee88c.png)

I removed the “light” from the “Segoe UI light” in the Win 10 default line in darktable-elegant-darker.css. This fixes the readability for me.
![grafik](https://user-images.githubusercontent.com/96216629/171011073-fa37b188-3b31-4a53-a067-dcfd6ad94be7.png)

Windows default, "light" removed (Segoe)
![windows default light removed](https://user-images.githubusercontent.com/96216629/171011113-554c3bc5-555d-4756-8bd0-80554c25d40e.png)

Also with Roboto installed, which is no standard font for Windows, the light font is not optimal (although not as bad as Segoe). Here as well, it’s way better to remove the “light”.

Roboto default
![roboto default](https://user-images.githubusercontent.com/96216629/171011429-8c9dba22-ce9c-4562-9c1d-916e3d15afe7.png)

Roboto, "light" removed
![roboto light removed](https://user-images.githubusercontent.com/96216629/171011506-16e7c9f8-a17e-47c4-a350-a56a1159aef8.png)

I'm using up to date Windows 11. All settings that could impact the rendition are default.

**Comment by Nilvus** [comment] 2022-05-30 14:47
Thanks @apostel338 to provide such precise issue. Just a thing: your issue let think that is (only) grey related issue. It's NOT as I answer in pixls.us and issue about grey default as default. It's related to elegant themes, so darker, dark and grey theme and mostly Windows issue. To avoid bad understanding, it would be good if you could just remove grey word from title and issue. Thanks!

Seems so that removing light fonts could be a good way to improve a lot those elegant themes. Will test how this render on my side on Linux with Roboto. Will go back to see if this could be updated like that or if we need to find another way. Seems at least that setting Segoe instead of Segoe Light should be good.

Note that it's not installed by default on all OS. It was a choice from @aurelienpierre for really good reasons. Mostly because its packaged on most Linux distros but also because setting a font is also the best way to be sure a theme is rendered the way it was designed for. Of course, this need to installed Roboto fonts but it's easy to do that (manually) or by adding dependency on binaries packages.

**Comment by elstoc** [comment] 2022-05-30 14:53
> Mostly because its packaged on most Linux distros but also...

I'm not sure we even had a Windows version when this was done

**Comment by Nilvus** [comment] 2022-05-30 16:08
> > Of course, this need to installed Roboto fonts but it's easy to do that (manually) or by adding dependency on binaries packages.
> 
> Dependency of binary package is a Linux thing. No such luck for Windows or macOS packages. And even on Linux we don't really control what packagers specify as dependencies, there are a lot of distributions out there. So I think we either need to figure out how to ship fonts we want as part of darktable application itself, or figure out how to include fonts in Windows and macOS packages. First option is more universal since will include Linux too. I hope Roboto fonts license allows redistribution like this.

You're right. What I mean by dependency here was not only Linux dependency but also the idea to provide font in packages (if possible of course) as you say! But your answer is more precise and complete. Thanks.

**Comment by aurelienpierre** [comment] 2022-05-30 19:14
This screenshot has the signature look of a font anti-aliasing problem.

On my wife's laptop (Win 10), I had to test all possible Win font antialiasing options to find the one that didn't shit the bed with Gtk. Don't ask me which one worked, I don't remember, but you have to right click on the app's name in the menu, then launch it with some specific GUI parameters.

**Comment by Nilvus** [comment] 2022-06-01 20:29
And seems an anti-aliasing issue for light fonts on Windows. I've anyway tested (on Linux, I don't have Windows) to remove light font and this is not possible/wanted. It breaks the UI when anti-aliasing issue is not there (even Segoe UI Light when no Roboto fonts installed). That's logical of course.

So removing light fonts is a workaround with CSS for such issue but not a correct fix. So not possible to do that. As @kmilos said, probably GTK/Cairo/pango issue on Windows. We already have such one.

So I don't see anything by now we can do on darktable code. @apostel338: waiting for better, you could so update CSS as you want (just copy/paste code you change on preferences to avoid having it overrided by darktable updates.

Or/and you could check ClearType options on Windows to fix that. I have found that page to help: https://www.howtogeek.com/howto/28790/tweak-cleartype-in-windows-7/

I suppose options would be similar on more recent Windows releases.

**Comment by apostel338** [comment] 2022-06-01 20:51
I'm aware of the ClearType options, and there is another font smoothing option under performance -> visual effects.

**Comment by pehar1** [comment] 2022-06-02 05:15
> ... it can only see DT and not the OS?

Yes. You have to enter your CSS modifications in `preferences -> general` (https://darktable-org.github.io/dtdocs/en/preferences-settings/general/).

**Comment by apostel338** [comment] 2022-06-02 11:03
Thanks pehar1, it works for me too. `font-family: Segoe UI;` same effect like removing "Light" from the elegant css. So the future Win users can be offered two workarounds.

**Comment by kmilos** [comment] 2022-06-02 11:51
Just some more data points, trying to isolate GTK/Cairo/Pango by checking native apps...

Here's Visio using Segoe UI Light 10pt & 11pt, (w/ default 125% scaling for me):

![image](https://user-images.githubusercontent.com/4973094/171622093-625019d9-0a94-4d0a-a1ef-5ec653d4d8d8.png)

Here's paint.NET (also at 125% scaling; looks familiar?)

![image](https://user-images.githubusercontent.com/4973094/171622288-614f973f-1ca2-4776-9b25-8919111e84bd.png)

Here's Visio at 100% scaling (still looking better than paint.NET at 125%):

![image](https://user-images.githubusercontent.com/4973094/171622745-c58d7f46-c888-4284-9eae-a24d349bbc43.png)

For completeness, here's paint.NET at 100% scaling:

![image](https://user-images.githubusercontent.com/4973094/171623214-9205d6d8-8f50-4d37-a14d-5c51642f5d02.png)

**Comment by Nilvus** [comment] 2022-06-02 20:17
All that confirmed that is not a CSS or even darktable issue. Changing default CSS is not an option. Removing light fonts break theme as this set same font and similar "weight" for titles and content.

It's ok as a user workaround in preferences but not a good thing on main CSS. And maybe this will be one day fixed on Gtk/Pango Windows side.
This will be the good fix as it will also have effects for other apps.

@kmilos: your last comment could maybe be good to post on Gtk and/or Pango sides.

As we can't do anything better on darktable code, I close this one. Thanks to all for clarify this.

**Closed** 2022-06-02 20:20 UTC
Labels: bug: upstream, scope: windows support
