### ISSUE TITLE
Visual issue with Crop in Wayland

### ISSUE THREAD

**Issue by habys** [darktable-org/darktable#7471] opened 2020-12-26 17:47 UTC
**Describe the bug**
Cropped region of an image is visible after changing modes.

Attached photo should show the only indication of crop is a grey line above the image.

**To Reproduce**
Apply a crop in dark table mode, switch to light table, back to dark table and adjust the crop, it no longer hides the area outside of the crop. 

**Expected behavior**
The cropped region should be obscured by a solid color.

**Screenshots**
![20201226_12h34m54s_grim](https://user-images.githubusercontent.com/376016/103156526-4b017880-4777-11eb-89ef-66f15d208914.png)

**Platform (please complete the following information):**
 - Darktable Version: 3.4.0
 - OS: Arch Linux
 - OpenCL: Not enabled as it is not available.
 - SwayWM (Wayland) XWayland is not enabled.

**Additional context**
 - Can you reproduce with another Darktable version? No, it was not an issue with the previous recent versions:

    $ ls -tlr | grep dark
    -rw-r--r-- 1 root root   4406526 Oct 24 05:09 darktable-2:3.2.1-2-x86_64.pkg.tar.zst
    -rw-r--r-- 1 root root   4406180 Dec 21 18:08 darktable-2:3.2.1-3-x86_64.pkg.tar.zst
    -rw-r--r-- 1 root root   5064770 Dec 24 08:24 darktable-2:3.4.0-1-x86_64.pkg.tar.zst

 - Can you reproduce with a RAW or Jpeg or both? Both
 - Are the steps above reproduce with a fresh edit (removing history)? This happens on new images with no history, so I believe yes?
 - Did you compile Darktable yourself? If so which compiler was used, with what options? No, it is from the community arch package.

**Comment by AxelG-DE** [comment] 2020-12-27 08:11
I tried on Gentoo with 2.4.0 from repo and 3.5.0-185-ga6dc34f33

Both versions worked fine (just for a very short moment I thought I can reproduce, but clicking second time on c&r, it behaved normal)

**Comment by habys** [comment] 2020-12-28 02:28
I tried this again after building/installing the git package from the arch user repository. This package is build with these [instructions](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=darktable-git). I am seeing the same behavior. The program now reports it's version as "3.5.0+218~ga34246950". Please let me know if there is anything I can do.

My guess would be something to do with Wayland if it's hard to reproduce.

**Comment by AxelG-DE** [comment] 2020-12-28 06:24
@habys could you pls provide a screen recording e.g. with SimpleScreenRecorder.

Also when facing the issue, could you pls. repeatedly activate/deactivate the module? 
I'll be on the road today, hence reply won't be very swift...

**Comment by habys** [comment] 2020-12-31 22:57
Sorry this took a minute because it's still quite a hassle to record video from wayland. I ended up recording it on another machine via an HDMI capture.

https://youtu.be/NKZIuFVYmJY

**Comment by habys** [comment] 2020-12-31 23:04
Ah I missed your last request. I enabled and disabled the module to no apparent visual effect. This video should be small enough to attach directly.

https://user-images.githubusercontent.com/376016/103430490-9d390400-4b92-11eb-966e-ab2813f18c0c.mp4

**Comment by AxelG-DE** [comment] 2021-01-01 08:43
That is really odd...

I suggest adding something like "when using wayland" in the title of this issue.
What I can (and will) do, is point the devs in IRC to this issue...

**Comment by AxelG-DE** [comment] 2021-01-01 08:53
@habys I forgot to clarify one thing: you are aware, that crop&rotate needs to be finalized by 
- either double clicking on the image
- or single click on the "label" (means actually those words) of the module "crop and rotate"

First feedback from IRC in general: Wayland is not recommended to use for dt :blush:

**Comment by habys** [comment] 2021-01-01 16:46
I disagree! It's a relatively minor issue in exchange for running Wayland, which has been the only solution I've found to my screen tearing. I think it means in general that it's an issue they don't want to look at. I can't really complain. Thanks!

**Comment by Nilvus** [comment] 2021-11-21 10:45
As crop and rotate is now deprecated for 3.8 and a new crop module is added to replace it, I close this issue. @habys: I think the best would be that you test that new module when 3.8 will be out (for Christmas) and if the issue is still there, it will be better to post a new issue. Of course, if you could already test actual master (future 3.8), it will be better as this could provide better feedback for 3.8 release.

**Closed by Nilvus** 2021-11-21 10:45 UTC
Labels: no-issue-activity
