### ISSUE TITLE
Contrast equalizer mix slider resets when applying style.

### ISSUE THREAD

**Issue by chhil** [darktable-org/darktable#3836] opened 2019-12-23 02:32 UTC
To reproduce
Contrast equalizer preset sharpen used.
The mix slider reduced from 1 to 0.5. The module is expanded and visible.
Applied a style that adds 3 instances of denoise profiled.
After style is applied the mix slider returns to 1 but the slope of the lines made by mix 0.5 does not change.

The mix slider should not change its value.

Version 3.1 manual release build on win 10

**Comment by MStraeten** [comment] 2019-12-23 09:06
Works as designed. See doku: https://darktable.gitlab.io/doc/en/correction_group.html 3.4.4.2. Equalizer¶

**Comment by TurboGit** [comment] 2019-12-23 13:26
Duplicate of #3095.

**Closed by TurboGit** 2019-12-23 13:26 UTC
