### ISSUE TITLE
UI: color patches non aligned in color picker in Lab mode

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/darktable#3779] opened 2019-12-16 13:42 UTC
When putting several color patches in live samples section of the color picker in Lab mode, those are badly aligned:

![Capture](https://user-images.githubusercontent.com/43290988/70911360-0b576b00-2012-11ea-8acb-fbfcc0b6f12d.JPG)

Also the Lab values are not aligned and the whole thing seems a bit messy and difficult to read. In RGB mode everything works ok.

DT 3.0 RC2 on Windows 10, default theme

**Comment by Nilvus** [comment] 2019-12-16 14:27
This has been fixed since some times and I can't reproduce it anymore. And you don't seem to have monospace font used on sample data.
Which darktable version you use ? On which OS and which theme (seems to be the darktable default one) ?

**Comment by Mark-64** [comment] 2019-12-16 14:34
You are in RGB mode. The issue is only in Lab mode

**Comment by Nilvus** [comment] 2019-12-16 14:35
> You are in RGB mode. The issue is only in Lab mode

Anyway, you didn't answer to my question... It's better to help with more details.

**Comment by Mark-64** [comment] 2019-12-16 14:37
added info in the description

**Comment by Nilvus** [comment] 2019-12-16 14:38
Thanks, now I will see if this could be fixed with CSS only. As cells sizes are not fixed, negatives values or lower ones make the data length change so move the sample.

**Comment by Mark-64** [comment] 2019-12-16 14:43
Maybe the size is not enough when the numbers are negative.
If so, maybe the precision of Lab reading can be reduced to one digit after the decimal point.
After all RGB values have three significant digits only, Lab have four.

**Comment by Nilvus** [comment] 2019-12-16 14:54
> Maybe the size is not enough when the numbers are negative.
> If so, maybe the precision of Lab reading can be reduced to one digit after the decimal point.
> After all RGB values have three significant digits only, Lab have four.

It's not so simple. Sizes are dynamically adjusted and even if CSS allow to fix the size, it's not possible with Gtk+ CSS.

**Comment by Nilvus** [comment] 2019-12-16 15:13
@TurboGit : with CSS, I can't find a way as the size is related. Any idea on how to fix that ?

**Comment by Nilvus** [comment] 2019-12-16 15:21
@TurboGit : just thinking that a good fix could be to align on the left (with of course a little left margin) the sample and on the right (same with a little right margin) the sample text. That would force alignement and margin. Anyway, it's not possible with Gtk CSS rules as I know.

**Comment by TurboGit** [comment] 2019-12-16 17:02
Yes a good solution would be to align indeed. Is that this that is not possible with Gtk CSS?

**Comment by Nilvus** [comment] 2019-12-16 17:59
> Yes a good solution would be to align indeed. Is that this that is not possible with Gtk CSS?

I search, try habitual CSS, review official Gtk css pages on the web and some others ones but didn't find anything about that. Seems that Gtk doesn't want CSS alignment rules.

**Comment by Mark-64** [comment] 2019-12-17 17:51
@Nilvus 
Question: but is CSS/Gtk don't like alignment rules, why in RGB mode everything is perfectly aligned ?

**Comment by Nilvus** [comment] 2019-12-17 18:25
> @Nilvus
> Question: but is CSS/Gtk don't like alignment rules, why in RGB mode everything is perfectly aligned ?

RGB values are constant ones, not Lab values, who could have differents format (negatives or not, different number of numbers!), so total length doesn't change in RGB values as it change often in Lab ones. And that length change push the sample color on the left for some, not for other, so break taht way the alignment. That's just that!

**Comment by Mark-64** [comment] 2019-12-17 19:01
Ok, but then perhaps you can workaround the issue by passing to CSS not the Lab number directly, but a string formatted to have always the same lenght.
I have some knowledge of coding (mainly in C, not CSS), maybe I can help if you tell me where to look

**Comment by Nilvus** [comment] 2019-12-17 19:07
> Ok, but then perhaps you can workaround the issue by passing to CSS not the Lab number directly, but a string formatted to have always the same lenght.
> I have some knowledge of coding (mainly in C, not CSS), maybe I can help if you tell me where to look

I've tried all things I can with CSS (on a part and another, and even on both) but some needed CSS rules are not supported by Gtk to do that. I only see a change on Gtk/C code to fix that. And I don't know anything in Gtk/C coding. I only know that's on this file (starting around line 390) : https://github.com/darktable-org/darktable/blob/master/src/libs/colorpicker.c

You could see "live-sample" name and "live-sample-data" which are the CSS tags of, respectively, sample color and label text.

**Comment by Mark-64** [comment] 2019-12-17 20:28
Ok, I will look in the C code in the coming days

**Comment by Mark-64** [comment] 2019-12-18 17:38
I think I've fixed it. There was an incorrect formatting in some snprintf instruction, "%5.02f" is wrong as a and b values in Lab can have up to 6 characters, including the sign.
It must be changed to "%6.02f", or "%5.01f" keeping only one digit after the decimal point.

In the first case you have this
![Cattura2](https://user-images.githubusercontent.com/43290988/71109233-11da1400-21c5-11ea-8c8a-ee78a651d930.JPG)

in the second you get this
![Cattura1](https://user-images.githubusercontent.com/43290988/71109167-fa029000-21c4-11ea-9c13-48d5a6e49277.JPG)

I do prefer the second option. To me 4 significant digits for Lab are unnecessary, considering that with RGB mode you only have 3, or actually 2 and half.

Please advice which of the two options you like more, and I will do the PR

Marco

**Comment by TurboGit** [comment] 2019-12-18 18:20
Yes but then you now have 3 more chars per line. I suppose we want also to change the button remove by a simple X to gain spaces and then your solution will work. Thanks.

**Comment by Mark-64** [comment] 2019-12-18 18:30
Well, not if we give up one digit after the decimal point as shown in the second screenshot.
The precision is more than enough and better than RGB mode anyway.

**Comment by Nilvus** [comment] 2019-12-18 18:32
@Mark-64 : good work, way much better. As I never use Lab values, I don't have any idea (and don't care) if it's option 1 or 2 to be merged.
@TurboGit : I agree, a simple X would be better than the long and awful remove button. @Mark-64 : if you could change also that, that could be good. If you can finish that and propose a PR for that this week, I suggest to merge that on 3.0 as it's a simple fix to an UI glitch.

**Comment by TurboGit** [comment] 2019-12-18 18:32
@Nilvus : I'd like you view on #3809 

@Mark-64 : I use small panel right and left and anyway a cross X to delete seems very clear, does not break the translation and save lot of spaces making the values more spaced and more readable at the end.

**Closed** 2019-12-19 10:48 UTC

**Comment by pphotography** [comment] 2019-12-19 21:24
Can confirm fix in 3.0.0rc2~git130.92e7d3d4a on Ubuntu 18.04
