### ISSUE TITLE
Unintended slider adjustment when grabbing a slider and hovering over other sliders on OSX

### ISSUE THREAD

**Issue by Steeboo** [darktable-org/darktable#12061] opened 2022-06-18 10:24 UTC
When clicking on a slider and holding the LMB to drag the slider, it also adjusts other sliders when accidentally hovering over them. It does not happen always, but I was able to reproduce consistently when following these steps:

**To Reproduce**
Open a photo in darkroom on OSX (issue not found in windows) (tested on OSX Monterey)
Go to the local contrast module (or any other module with multiple sliders)
Left-click on the slider and hold
Drag the slider to a new value, but still hold the mouse button pressed
Wait 1-2 seconds
Now hover the mouse (still holding the left button) over the adjacent sliders
Note how adjacent sliders change values on hover

**Expected behavior**
When grabbing a slider, changing values should be constrained to the slider that was clicked on.

**Screencast**
Here is a screenrecording:
https://www.dropbox.com/s/cerr8y0y5815e4c/darktable%20sliders.mov?dl=0

**Platform**

* darktable version : 3.8.1
* OS                : OSx
* Memory            : 8gb
* Desktop           : Mac mini M1

**Comment by parafin** [comment] 2022-06-18 11:10
Duplicate of #8946

**Closed by parafin** 2022-06-18 11:10 UTC
Labels: scope: UI, scope: macos support
