### ISSUE TITLE
Before After function

### ISSUE THREAD

**Issue by Lorenzoeffe** [darktable-org/darktable#7474] opened 2020-12-26 19:46 UTC
Good morning,
I request the inclusion of the Before | After function in the "Darkroom" section.
Normally, to have a quick transition to what the image was like before and after editing, you use the "Development Queue" and possibly a "Snapshot" shot.
These two tools, however, have limitations: They cannot be recalled from a keyboard shortcut,
If you need to keep your gaze fixed on the image, the development queue becomes awkward to use,
If you zoom in and zoom out, the snapshot may not match, forcing you to rerun it with the same zoom percentage in use.

I therefore request that a "Before - After" function be added that works as a snapshot from the initial development point and self-adapts to a possible Zoom In Zoom Out.
This function could be initiated by a button or invoked via keyboard command.

**Comment by MStraeten** [comment] 2020-12-28 19:28
there's a template for feature requests: https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=feature_request.md&title=

i read following requests based on the current snapshot function in your text:

1. make snapshots accessible by shortcuts - it's already there: 
![image](https://user-images.githubusercontent.com/39386816/103238238-5bb61800-494a-11eb-852d-3aa70eec57b5.png)

2. zoom snapshot according to the current image - valid feature request
at least if using clipping you should do the "before" snapshot after clipping and not based on the initial image - but you're free to do it.

**Comment by Lorenzoeffe** [comment] 2021-01-02 15:10
A function that acts like this would be handy:
Divided the screen into 2 parts "as in the case of a snapshot" and report to the left how the image was at the beginning of the processing, when it was opened.
This regardless of the zoom level, or the machining queue performed.
This mechanism would be convenient if it worked and could remain active even when performing zom in zoom out

**Comment by johnny-bit** [comment] 2021-01-02 20:16
Essentially this request is:
Duplicate of https://github.com/darktable-org/darktable/issues/2784
Duplicate of https://github.com/darktable-org/darktable/issues/2315

**Closed by johnny-bit** 2021-01-02 20:16 UTC

**Comment by Neverest** [comment] 2021-01-03 14:18
> 
> 
> there's a template for feature requests: https://github.com/darktable-org/darktable/issues/new?assignees=&labels=&template=feature_request.md&title=
> 
> i read following requests based on the current snapshot function in your text:
> 
>     1. make snapshots accessible by shortcuts - it's already there in the preferences dialog:
>        ![image](https://user-images.githubusercontent.com/39386816/103238238-5bb61800-494a-11eb-852d-3aa70eec57b5.png)
> 
>     2. zoom snapshot according to the current image - valid feature request
>        at least if using clipping you should do the "before" snapshot after clipping and not based on the initial image - but you're free to do it.

Say I was moving one by one showing it to a person or just checking by myself, is there a way to on photo A I press a button and it shows the base picture then change to photo B and with that button it shows B's base picture?

I know of the snapshot one, but I would have to manually take them for each one instead of photo A, press B/A button, photo B, press B/A button.

**Comment by MStraeten** [comment] 2021-01-03 19:21
If you just want to see the base image, select the bottom entry 0 in the history stack. You don’t need snapshot if you just want to see thenimage at a decent state in the history
