### ISSUE TITLE
Arrow keys for image browsing do not work

### ISSUE THREAD

**Issue by ruffson** [darktable-org/darktable#6223] opened 2020-09-06 14:07 UTC
**Describe the bug**
When changing the keyboard shortcuts in such a way that in the `darkroom` view pressing the right arrow moves to the next image (instead of space) and the left arrow moves to the previous image (instead of backspace), the expected behaviour of moving forward and back with the arrow keys does not work. However when pressing `h` it shows that `Left` and `Right` are set appropriately and it is not possible to use `space` and `backspace` to move forward and back anymore.

**To Reproduce**
1. Go to the `shortcut` settings for the `darkroom view`
2. change the shortcut for `image forward` to the right arrow (`Right`) and the shortcut `image back` to the left arrow (`Left`)
3. go back to the lightroom view, double click am image to enter darkroom
4. try back and forward arrow key and observe that nothing is happening
5. press `space` and `backspace` to confirm that the former shortcuts do not work anymore either

**Expected behavior**
Changing the shortcuts should enable the user to use the set shortcuts.

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Fedora 32, X11
- No OpenCL

**Additional context**
- I freshly installed the program and changed very little else in the settings

**Comment by elstoc** [comment] 2020-09-06 18:04
This is a duplicate of #5011. Arrow keys currently have hard-coded functionality in the darkroom view.

**Closed** 2020-09-06 18:07 UTC
