### ISSUE TITLE
darktable 3.4.0 crashes when in culling view (ctrl+x) the last remaining image is deselected (ctrl+left click)

### ISSUE THREAD

**Issue by robertoswald** [darktable-org/darktable#7703] opened 2021-01-05 20:32 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform (please complete the following information):**
 - Darktable Version: 
 - OS: 
  -

**Comment by johnny-bit** [comment] 2021-01-05 20:33
Duplicate of #7445

**Comment by johnny-bit** [comment] 2021-01-05 20:34
Fixed in #7569 will be in 3.4.1, plz wait patiently :)

**Closed by johnny-bit** 2021-01-05 20:33 UTC
Labels: bug: fixed
