### ISSUE TITLE
Error opening database message

### ISSUE THREAD

**Issue by wildwhisp** [darktable-org/darktable#17292] opened 2024-08-08 05:46 UTC
### Describe the bug

I have been using Darktable for sometime. I got a message re a problem with the database. I tried downloading the latest version and I still get an error message re the database. The attempt restore does not remedy the issue.

![image](https://github.com/user-attachments/assets/96112caf-2c2c-4266-9c30-f24e2f52cc80)

### Steps to reproduce

Open

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1 and earlier

### What OS are you using?

Windows

### What is the version of your OS?

Windows11

### Are you using OpenCL GPU in darktable?

None

**Comment by gi-man** [comment] 2024-08-08 12:19
If restore doesnt fix it, then you need to use one of your database backups. If you navigate to the folder that has the database, you will likely see multiple database snapshots. Rename the current data.db to data.old and then rename the latest database snapshot to data.db. Hopefully your database backup is not too old. darktable default settings create a snapshot once a week.

**Comment by ralfbrown** [comment] 2024-08-08 14:42
What @gi-man said, except that I would use a snapshot *other* than the most recent one, since that's what darktable has been doing when you select "attempt restore".

data.db stores your presets, styles, user-defined map regions, and the like, but no image info or edits.  So that's what you'd lose if you are forced to delete it entirely.

**Comment by luzpaz** [comment] 2024-09-13 11:35
typo in title: 'dataabase' should be 'database'

**Comment by victoryforce** [comment] 2024-11-12 09:38
I suggest to close this issue, as there is no evidence that this situation is caused by any error in darktable. This could be the result of a hardware disk problem or an operating system crash while darktable was working with the database.

**Closed** 2024-12-02 21:24 UTC
Labels: scope: DAM
