### ISSUE TITLE
Artefacts at bottom of image - Fujifilm X100V cropping issue?

### ISSUE THREAD

**Issue by greenshaw-net** [darktable-org/darktable#8644] opened 2021-04-10 13:43 UTC
**Describe the bug/issue**
Photos processed in scene referred mode have an artefact - the bottom of the image (maybe just the bottom row of pixels) is either lightened (washed out white) or bright green, or black line. The issue is most obvious in exported images but also visible in the blocky preview you get when you zoom in in dark room and move the image to trigger "working...". The artefact doesn't show up once the blocky preview is replaced by the higher quality preview. If I re-process the image in display referred mode, I still get the artefact in the blocky preview but the high quality preview (once Working... disappears) and the exported image looks fine.

This is an issue even without me doing any custom processing - just the default modules / processing in scene referred mode is enough for it to show up. 

**To Reproduce**
1. Import RAF raw file in scene referred workflow.
2. Zoom in in dark room and move image so you can see bottom row - move around to trigger "Working..." blocky preview - this shows green artefacts at bottom of image
3. Export image (I used jpeg 98%) to see artifact covering bottom row of pixels 

**Screenshots**
In darktable:
![indarktable](https://user-images.githubusercontent.com/82271261/114271534-b828d900-9a09-11eb-8864-9988bd07e7e1.png)

After export:
![brightzoomed2](https://user-images.githubusercontent.com/82271261/114271672-78162600-9a0a-11eb-86e8-08303be70775.png)
![brightZoomed](https://user-images.githubusercontent.com/82271261/114271251-5caa1b80-9a08-11eb-8709-f5864d2909e5.png)
![greenZoomed](https://user-images.githubusercontent.com/82271261/114271254-616ecf80-9a08-11eb-9f38-abefd925027f.png)
![blackZoomed](https://user-images.githubusercontent.com/82271261/114271258-6469c000-9a08-11eb-8a26-acf825c65749.png)

**Platform**
HP Spectra x360 (13-4109na) laptop

* darktable version : 3.4.1
* OS                : Linux - kernel 5.11.11-1-default
* Linux - Distro    : OpenSUSE Tumbleweed
* Memory            : 8GB
* Graphics card     : Intel integrated
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           :  GNOME 3
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
Camera is Fujifilm X100V, RAW files are RAF (with lossless compression).

 - Can you reproduce with another darktable version(s)? **not tested**
 - Can you reproduce with a RAW or Jpeg or both? **not tested**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes**

**Comment by greenshaw-net** [comment] 2021-04-10 14:00
I've tested the X100F, X100T and X100V images from raw.pixls.us and the issue does not exist on the X100F and X100T raw files but does exist on all the X100V files so it looks like it is only the X100V raw images but it seems to be all X100V images both uncompressed and lossless compressed - not just my camera. I can confirm I have tested it on my own raw images from old 1.x firmware and new 2.x firmware and issue is the same from all firmware.

**Comment by greenshaw-net** [comment] 2021-04-10 14:39
The green artefacts shown in the blocky preview (Working...)  in darktable appear regardless of scene referred vs display referred workflow but the exported image seems much more affected if processed in scene-referred flow.

**Comment by johnny-bit** [comment] 2021-04-10 14:42
It seems like incorrect crop region affecting only X100V images.

**Comment by Mark-64** [comment] 2021-04-10 14:42
I noticed the same type of artifacts, with all RAW formats, limited to the first few pixels in the borders all around the image.
It appears for both the preview in darkroom and the exported image.
I believe it is related to the new RCD demosaicer and the corresponding dual demosaicers, which have become the default recently, as it doesn't show with Amaze.
To make it more evident, try with a test image like a USAF chart or similar, with tiny patterns.

**Comment by LebedevRI** [comment] 2021-04-10 14:57
> It seems like incorrect crop region affecting only X100V images.

It does look like unsufficient crop yes.

**Comment by jenshannoschwalm** [comment] 2021-04-10 15:22
Yes, in rcd we have a "border issue" with the outermost 5 pixels as they are not processed by rcd but by bilinear interpolation.

No, here it's not affected as it's fuji. Likely wrong rawprepare crop?

**Comment by jenshannoschwalm** [comment] 2021-04-10 23:56
@Mark-64 Marco, just to let you know, will fix the rcd border issue for 3.6. :-)

**Comment by johnny-bit** [comment] 2021-05-23 18:17
It's a bit weird. I just checked and it seems like different RAF-producing cameras are differently affected.

One test image I have from Fujifilm Finepix F100FS has weird magenta/violet/blue/black (depending on demosaicer) border on top and left corners, X-T20 has weirdo green/black border on right, X100V has mentioned weirdo border...

F100FS does not have enteries in raw.pixls.us - i got files from user reporting problem, but those can be ignored since it even requires rotate pixels ;) and is ancient camera AND doesn't have samples.

So I'd focus on cameras with known samples... 

The issue is present on dt 3.4.1 as well as current master (3.5.0+2332~gedb19dead)

I unassigned @LebedevRI from this issue since I am not sure whether it's rawspeed changes (i'm starting to doubt that) or other issues are at play.

**Comment by jenshannoschwalm** [comment] 2021-05-24 11:29
@johnny-bit it would be interesting to kwnow whether the artefacts disappear after increasing black point in rawprepare, maybe doubling. This would point to fuji demosaicer output ... (btw we had such issues with bayer sensors with green correction applied)

**Comment by johnny-bit** [comment] 2021-05-24 12:28
@jenshannoschwalm - increasing black point in rawprepare doesn't help with Finepix F100FS images, X-T20 nor X100V. Quite honestly it makes the borders worse (as in more visible)...

**Comment by jenshannoschwalm** [comment] 2021-05-24 12:36
What about cropping the borders in raw prepare to larger values in case the raw prepare defaults are wrong?

**Comment by johnny-bit** [comment] 2021-05-24 12:44
Checked using passthrough preset - does not affect F100FS (same magenta border), on X-T20 it looks like green border is on crop line (slicing it of removes green border), does not affect X100V (the green artefacts on the bottom are there, haven't tried cropping it more).

**Comment by jenshannoschwalm** [comment] 2021-05-24 17:48
I downloaded the rawpixls X100V file, i simply can't reproduce.

1. Any module tiling wrongfully?
2. really interested in a raw and xmp. Here i have
3. `Fujifilm - X100V - 14bit compressed (3 2).RAF`
4. `Fujifilm - X100V - 14bit uncompressed (3 2).RAF.xmp`
5.  `Fujifilm - X100T - 14bit uncompressed (3_2).RAF.xmp`
3. any special preferences?

**Comment by johnny-bit** [comment] 2021-05-24 18:50
1. Dunno. I have plenty of ram (and vram)
2. pure raw, discard history.
3. 4. & 5.
6. no special prefs. pretty much "stock" dt :)

Here's how to 'see' the issue: zoom to 100% (or greater) and go to bottom row. you'll see some weird green artifacts along bottom row while navidating the image and "working..." message is present. once image is fully rendered the problem is not visible. at least on X100V...

I wonder if it's due to opencl vs cpu path (i'm on cpu path currently thanks to some drivers mishaps)

**Comment by jenshannoschwalm** [comment] 2021-05-24 20:10
I see it now. This **is** an interesting problem, i can observe the same issue with **every** fuji image i have if i decrease the "crop bottom" value to zero. The 100V examples have that value set to zero. The issue is visible with markesteijn and VNG, the FDC also has the issue, it's just less visible because the colrs get "smeared".

Atm i am not sure whether this is a "sensor-cropping-data" issue related to rawspeed or wrong ROI calculation in the demosaicer module.

**Comment by jenshannoschwalm** [comment] 2021-05-25 03:34
More info, if using --disable-opencl this issue is only present with VNG! I concider this a pendig bug :-(

**Comment by jenshannoschwalm** [comment] 2021-05-25 05:37
Pinging @dtorop here as you did the latest work on VNG / xtrans stuff some years ago.

I am not aware of any VNG related issues with bayer sensors (but i have no images to test with data available on the lowest bottom lines with crop-bottom (in raw black/white point) set to 0.)

For xtrans this is certainly a bug in the VNG cpu code, it can be "fixed" by
1. an early return after the lin_interpolate step in vng
2. cropping the bottommost lines in raw black/white point. In the examples i tested the sensor pattern does not "fit perfectly", could this be a problem? Screenshot from the lowest lines
![Bildschirmfoto von 2021-05-25 07-28-49](https://user-images.githubusercontent.com/50982232/119444037-e436ba00-bd2a-11eb-9e70-7ff14a20467b.png)
3. Issues can only be seen at 100% (or export), i guess this is related to roi "corrections"

Some final comments
- The cl codepath is slightly different but shows same symptoms
- the initial description is a bit misleading, but also hints at a possible issue in `dt_iop_clip_and_zoom_demosaic_third_size_xtrans_f`

**Comment by dtorop** [comment] 2021-05-25 14:58
I'll take a look. It's been a while! I think the `dt_iop_clip_and_zoom_demosaic_third_size_xtrans_f` was something I worked on as well. My memory is that it basically works, but all that code needed another revision, as downscaling a mosaiced image to produce a mosaiced image is tricky. I had a revision in the works for Bayer -- unfinished -- and never revised X-Trans. The VNG code should be a pretty "reference" implementation, very close to what's in dcraw.

Anyhow, more in a bit.

**Comment by jenshannoschwalm** [comment] 2021-05-27 05:12
@dtorop my above comments might be leading in a wrong direction. If i change the size of the main window the issue might go away. I don't understand this yet but that might hint more to a roi miscalculation?

**Comment by dtorop** [comment] 2021-05-27 15:45
I was able to reproduce this here. I took a look at a few X100V raw files. It looks like there is a 1 pixel black border at the image bottom which isn't cropped off. Removing that gets rid of the glitch.

This aligns with what @johnny-bit (https://github.com/darktable-org/darktable/issues/8644#issuecomment-817147119) and @LebedevRI (https://github.com/darktable-org/darktable/issues/8644#issuecomment-817149202) thought:

> > It seems like incorrect crop region affecting only X100V images.
>
> It does look like unsufficient crop yes.

Test was to download X100V images from raw.pixls.us, then see what minimally processed dcraw output shows:

`dcraw -E -W -T -t 0 Fujifilm\ -\ X100V\ -\ 14bit\ uncompressed\ \(3\ 2\).RAF`

Then exam the resulting TIFF via GIMP.

top

![image](https://user-images.githubusercontent.com/2311860/119854989-8c8d7f80-bedf-11eb-83e6-eace4c34527a.png)

bottom

![image](https://user-images.githubusercontent.com/2311860/119855073-9ca55f00-bedf-11eb-91ce-8c63c12e56d5.png)

Even though that top border is 5 pixels, it appears that the top 7 pixels need to be cropped or else a black border appears in the preview pixelpipe output at image top. Maybe something about keeping things modulo 6?

Assuming this is really the problem/fix, I _think_ it's OK to revise the crop in rawspeed of an extant camera from darktable POV. It appears that existing imported images with histories will keep the crop setting they were imported with, and hence position-dependent edits won't break. But newly imported images or images with discarded histories will get the revised crop.

I haven't even begun to look at the code yet. Hoping that the above is the fix, and not a coding error. If not, I'll start looking at the code.

**Comment by jenshannoschwalm** [comment] 2021-05-27 17:57
Thanks you are right.

**Comment by jenshannoschwalm** [comment] 2021-06-01 19:11
@TurboGit i think this is also for the 3.6 milestone, unfortunately some cameras seem to be affected and probably must be fixed via rawspeed unless we don't want a really dirty hack in rawprepare ensuring a bottom crop of at least 1

**Comment by TurboGit** [comment] 2021-06-01 20:44
@jenshannoschwalm  : I've added the 3.6 milestone.

**Closed** 2021-06-10 10:09 UTC
Labels: bug: pending, scope: camera support, scope: image processing
