### ISSUE TITLE
Canon EOS Rebel T7

### ISSUE THREAD

**Issue by MoralCode** [darktable-org/darktable#2840] opened 2019-08-05 03:02 UTC
Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment] 2019-08-06 09:10
Duplicate of https://redmine.darktable.org/issues/12235.
It's supported back since darktable-org/rawspeed@dc2f059276a0ae0f06ef4cb8e6c9c52585c325ec

**Closed by LebedevRI** 2019-08-06 09:10 UTC
Labels: camera-support, duplicate
