### ISSUE TITLE
darktable 3.0.1 is hanging when opening a RAF file the first time

### ISSUE THREAD

**Issue by c-h-r-i-s-t-i-a-n** [darktable-org/darktable#4469] opened 2020-03-13 20:44 UTC
darktable 3.0.1 is hanging when opening a RAF file the first time.

Next time opening the same file is running fine. 

OS: Windows 10
![dt301](https://user-images.githubusercontent.com/57685590/76658175-cf319900-6573-11ea-89dc-3e53849c9e15.jpg)

**Comment by GrahamByrnes** [comment] 2020-03-14 19:08
Is it just the image file, ie XYZ1234.RAF, or is there a sidecar file of some sort with it?

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2020-03-14 19:21
Just the RAF file. When opening (with context menu 'open with darktable') XMP file is created, and then DT is hanging. I'm back to 3.0.0 now, where this error is not occuring.

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2020-04-23 19:23
Updated DT to 3.0.2 and the bug is still there.

**Comment by rawfiner** [comment] 2020-05-15 11:51
Is it only with one particular RAF file or all of them? Could you upload your RAF file to be able to test?
Is it compressed RAF or uncompressed?
I have no issue with my (compressed) RAF files (xt20 and xt3) on both dt 3.0.1 and dt master

**Comment by c-h-r-i-s-t-i-a-n** [comment] 2020-05-17 08:11
I'm back on 3.0.0 but if I remember correctly it happend with all my **X-E2** RAF files.
And it only occurs when opening the file with right-click-menu (open with darktable).

**Comment by rawfiner** [comment] 2020-05-17 15:58
I tried to open an X-E2 RAF file with darktable master on linux, but could not reproduce, so either the bug is corrected, either the bug does not affect darktable on linux

**Comment by johnny-bit** [comment] 2020-12-15 22:04
This might've been caused by lua issue. That was fixed with 3.2.1 and doesn't happen in current master. Closing for now, please comment if you're still having issue.

**Closed by johnny-bit** 2020-12-15 22:04 UTC
Labels: no-issue-activity
