### ISSUE TITLE
Mac arm build darktable.app 4.6.0 is damaged and can not be opened on Apple M2 OS 13.6.3 (22G436)

### ISSUE THREAD

**Issue by mingchen** [darktable-org/darktable#16002] opened 2024-01-01 19:46 UTC
### Describe the bug

Hardware: Apple M2
OS: 13.6.3 (22G436)
darktable Build: Arm build 4.6.0 

<img width="393" alt="image" src="https://github.com/darktable-org/darktable/assets/1002838/1e16e7c4-9b40-4259-aa5e-b1023f0f3da1">

### Steps to reproduce

1. Download the 4.6.0 release for Mac arm. Filename: darktable-4.6.0-arm64.dmg
2. Open darktable-4.6.0-arm64.dmg
3. Open System settings to allow open this file.
4. Reopen darktable-4.6.0-arm64.dmg then copy darktable.app to /Applications/
5. Go to /Applications/
6. Click to open darktable.app
7. See above error: darktable.app is damaged and can not be opened

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.6.0

### What OS are you using?

Mac

### What is the version of your OS?

13.6.3 (22G436)

### Are you using OpenCL GPU in darktable?

None

**Comment by zisoft** [comment] 2024-01-01 20:36
duplicate of #14746 

Please search before opening new issues.
This is clearly documented on the [macOS installation notes](https://www.darktable.org/install/#macos)

**Closed by zisoft** 2024-01-01 20:36 UTC
