### ISSUE TITLE
PTP Store Full error in tethering mode on Linux

### ISSUE THREAD

**Issue by leonixyz** [darktable-org/darktable#2542] opened 2019-05-09 11:35 UTC
**Describe the bug**
When shooting too many pictures in tethering mode, using sequenced capture mode or bracketed capture mode, Darktable looses connection to the camera.

**To Reproduce**
1. Attach to usb my Nikon D3300 and power on the camera
2. Start Darktable
3. Enter tethering mode

After that, any of the following will result in a camera connection lost error.

* Shoot a bracketed exposure using 5 brackets and 1 stop bracket steps.  
* Start a capture of 20 sequenced shots. Connection to camera will be lost after 9 shots.

**Expected behavior**
Connection to camera shall not be lost.

**Screenshots**
Non applicable

**Platform (please complete the following information):**
 - OS: Arch Linux `Linux 5.0.9-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 20 15:00:46 UTC 2019 x86_64 GNU/Linux`
 - Version: Darktable 2.6.2

**Additional context**
[Here are the logs of Darktable, and gphoto2](https://gist.github.com/leonixyz/a82e8dedf6b8d047f706f9ade227afbd). When running gphoto2 **after** Darktable looses the connection to the camera, also gphoto2 returns the same error "PTP Store Full". The difference is that gphoto2 is still able to `--capture-image-and-download` still though the error shows up in the logs.

If, instead, I only run gphoto2 in a clean state (after closing Darktable and restarting the camera, detach and reattach usb), everything is fine. That's why I'm posting this issue here: I was able to replicate the behaviour on Darktable, but not on gphoto2.

Please let me know if I can add anything to further help fixing this issue.

**Comment by johnny-bit** [comment] 2020-12-23 10:44
It seems that the issue might've been caused by lack of delay / non blocking shot...

I've recently made a PR that made it's way to 3.4 release - #7126 with it you should be able to finetune delays between shots so that camera is able to transfer images without filling up it's cache (or whatever's that called).

This "solution" is a bit fiddly, because it requires user to finetune delays between shots. In canon cameras without delay the camera automagically slows down and only makes another shot after it has enough space in it's internal memory (at least mine does that...)

The release 3.4 is happening in 2 days so I encourage you to test :) if it fixes your issue - please close the issue :)

**Comment by johnny-bit** [comment] 2021-06-27 15:31
We really need to look into tethering problems with bracketed shots on nikons. @houz mantioined in TODO comments in code that on nikons it'd be great if the shot was blocking. In this case it seems like we could wait for PTP error full, wait for error to clear and then continue? Dunno how to proceed here, but generally - too little devs familiar with tethering and having tetherable camera :/

**Closed** 2023-03-25 00:16 UTC
Labels: scope: software support, bug: pending, no-issue-activity
