### ISSUE TITLE
Snapshot zooming and panning not working.

### ISSUE THREAD

**Issue by bartoszek** [darktable-org/darktable#12688] opened 2022-10-22 12:38 UTC
I was trying to inspect some subtle changes done with retouch tool and noticed that Snapshot won't zoom alongside the base image 🤔 

Reproduce (pretty obvious)
1. Add snapshot
2. Turn on snapshot
3. Zoom in and pan
4. Snapshot won't zoom nor pan.

**Expected behavior**

Snapshot should follow zoom and pan of the base image.

**Screencast**

https://user-images.githubusercontent.com/1213348/197339254-433d47cc-f2bb-4afc-8812-3128c06639fa.mp4

**Platform**
Windows

**Comment by jenshannoschwalm** [comment] 2022-10-22 13:50
Sorry about this but snapshots are just like screenshots with a fixed size. So no scaling :-)

It has been asked / suggested several times but the chance to get it implemented is almost zero.

**Comment by Nilvus** [comment] 2022-10-22 13:56
And it's a duplicate of an issue I posted 3 years ago already. So yes, @jenshannoschwalm: seems you're right about the chance to get it implemented.
@bartoszek: I close, no need to have 2 issues for same thing.

**Comment by Nilvus** [comment] 2022-10-22 13:57
The issue:  #2784

**Closed by Nilvus** 2022-10-22 13:56 UTC
Labels: duplicate
