### ISSUE TITLE
New install will not open on MacOs 

### ISSUE THREAD

**Issue by tapickell** [darktable-org/darktable#14834] opened 2023-07-03 15:13 UTC
### Describe the bug

I got a new macbook pro and downloaded the 4.4.1 dmg for apple silicon.
When I open it it gives me an error about it being damaged and I should move it to the trash.
There is a ? popup that states the code does not match the signed code.
I also tried installing using brew, same issue.
I may try to install an earlier version as I know this worked on my last laptop.
<img width="264" alt="Screenshot 2023-07-03 at 10 03 09 AM" src="https://github.com/darktable-org/darktable/assets/1010618/fc863877-5f8a-45e5-b351-03d8d166380e">
<img width="394" alt="Screenshot 2023-07-03 at 10 03 18 AM" src="https://github.com/darktable-org/darktable/assets/1010618/689014c0-66eb-4295-bb10-52aef109ce8c">
<img width="284" alt="Screenshot 2023-07-03 at 10 03 36 AM" src="https://github.com/darktable-org/darktable/assets/1010618/9bfc228f-d267-422f-b2e1-5f5f82d59e06">

```
sha256sum ~/Downloads/darktable-4.4.1-arm64.dmg                                                                                                                   ─╯
49fd74e0b80b7b19b1652499ba0a1b585e5a504b9977cadd7040ae761f356d75  /Users/toddpickell/Downloads/darktable-4.4.1-arm64.dmg
```

I tested 4.4.0 with the exact same result.
I tested 4.2.1 and it opens and seems to work just fine.
If there was an Apple Silicon Nightly I would try that as well.

### Steps to reproduce

1. download dmg from website https://www.darktable.org/install/
2. open dmg and move app to Applications folder
3. open app with double click
4 see error message

### Expected behavior

Darktable should open

### Where did you install darktable from?

darktable.org

### darktable version

darktable-4.4.1-arm64.dmg

### What OS are you using?

Mac

### What is the version of your OS?

MacOs Ventura 13.4

### Describe your system?

Apple M2 Max

### Are you using OpenCL GPU in darktable?

None

**Comment by kmilos** [comment] 2023-07-03 15:21
Duplicate of https://github.com/darktable-org/darktable/issues/14746

Please search before opening new issues.

**Closed** 2023-07-03 15:23 UTC
Labels: scope: macos support
