### ISSUE TITLE
Nokia 9 PureView

### ISSUE THREAD

**Issue by dm30** [darktable-org/darktable#16180] opened 2024-01-24 15:16 UTC
Just uploaded some samples. Camera system uses 3 RGB Bayern sensors + 2 filter-less B&W, so I took 3 in colour and 1 in B&W. 
Let me know anything you  need.
Thank you.
Javier.

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by kmilos** [comment] 2024-01-24 15:56
Thanks you for the samples.

These should be regular DNGs and working w/ dt already.

Are you facing any particular issues?

**Comment by victoryforce** [comment] 2024-02-15 21:05
@dm30 Thanks for the samples!

I don't know who is responsible for raw.pixls.us and why these samples are still not available there, but I found other dng samples from Nokia 9 PureView cameras on the net and tested them. I haven't noticed any problems. Monochrome images are even detected as monochrome when imported. Therefore, I close this issue. Feel free to comment further if there's any problem.

**Closed by victoryforce** 2024-02-15 21:05 UTC
Labels: scope: camera support

**Comment by kmilos** [comment] 2024-02-16 06:46
> why these samples are still not available there

See https://github.com/darktable-org/darktable/issues/16281#issuecomment-1944241718

**Comment by victoryforce** [comment] 2024-02-16 17:04
> See [#16281 (comment)](https://github.com/darktable-org/darktable/issues/16281#issuecomment-1944241718)

@kmilos I can't grasp the logic.

If the problem is only that we have limited disk space, but "we need the sample", then we need to solve the problem by ensuring that the disk space is scaled when necessary. I don't think that with such a strong community there will be problems with donations to pay for the relevant resources.

"neither verified, nor deleted" is not a solution, it is an avoidance of a solution.

**Comment by LebedevRI** [comment] 2024-02-16 17:10
Yep, i acknowledge that the reasoning matches the common excuses of "my knees hurt today" and "the weather is bad today, maybe next day".
