### ISSUE TITLE
Collapsed groups in lighttable mode possible regression

### ISSUE THREAD

**Issue by timstanbrook** [darktable-org/darktable#4292] opened 2020-02-14 19:11 UTC
**Describe the bug**
It appears that some of the group functions are not handled properly in V3.

In lighttable mode when all groups are collapsed using G at top right, several functions including 'trash', 'move', 'copy', 'remove', 'duplicate', 'export' are only applied to the first member of the group rather than all images in the group.

Tagging appears to work ok, so attaching (or detaching) a tag to/from collapsed group affects all members. 

**To Reproduce**

- Use G at top right of lighttable view to 'collapse grouped images' 
- Select a group (which, for example, has 8 members) and click 'trash'
- A popup appears, saying 'do you really want to send 8 selected images to trash'.
- Click 'yes'.
- Only the first image is deleted leaving 7 not sent to trash. 
- This occurs every time.

Equivalent behaviour observed for remove, copy, move, duplicate, export.

**Expected behavior**

I would expect any of these functions applied to a collapsed group to behave the same way as if the group was expanded, all members were selected, then the function was applied. V2.6.x behaved  like that.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0
 - OS: Ubuntu 18.04

**Comment by AlicVB** [comment] 2020-02-15 10:15
I agree that we have to add consistency in this area. I've started to take care in my lighttable rewrite, but it's far from finished !

**Comment by timstanbrook** [comment] 2020-02-15 12:34
I just checked two more aspects of this. 
Rating works correctly. So for example, assigning 3 stars to the collapsed group sets 3 stars for all the group.
Rotate and reset rotation only affect the first image in the group when collapsed.

**Comment by AlicVB** [comment] 2020-03-17 11:39
Now that lighttable rewrite as landed in master, I'll work on that and more generally on unifying how "images to act on" is determined. That as started in lighttable rewrite . I "just" need to generalized it now !

**Comment by codingdave** [comment] 2020-04-17 19:03
These bugs are a showstopper for me and I'm happy to contribute here. @AlicVB did you start on something already? 

Kind regards
David

**Comment by AlicVB** [comment] 2020-04-17 20:18
Great !
No I've not started something on this area. I'm quite short in time, this days...
But I have a clear idea on how to do it (must be confronted to reality, thought) : 
- add new param to dt_view_get_images_to_act_on(...) to says if we want only visible images or also hidden (grouped) ones.
- use that function everywhere for lighttable / filmstrip actions

If you want to start something, no problem !

**Closed** 2020-05-11 08:58 UTC
Labels: bug: wip, difficulty: average, no-issue-activity, scope: UI

**Comment by scorpi11** [comment] 2020-05-18 08:40
This looks like a duplicate of #3154 which was fixed with a small fix in master, that I will prepare a PR für the 3.0.x branch.
