### ISSUE TITLE
FR: do not reset blending mode & masking settings when choosing a module preset

### ISSUE THREAD

**Issue by da-phil** [darktable-org/darktable#11134] opened 2022-02-13 22:39 UTC
**Is your feature request related to a problem? Please describe.**
I find module presets incredible helpful and use them all the time. Sometimes when I create a new module I'll start right away with creating a mask (drawn / parametric) because I already want to limit the effect to a dedicated image section.
When I then decide to go for a module preset (e.g. tone-equalizer - medium contrast) my masking settings get reset, which is quite annoying.

**Describe the solution you'd like**
IMHO a preset of a module should not change my masking settings.

**Additional context**
I looked at the code and learned how intertwined module presets and blending parameters (masking & blending mode & color space) are. I assume that there are use-cases where a preset also changes the blending color space and mode?
And changing the blending color space also means changing the parametric masking parameters (JzCzhz -> HSL/LAB).

**Comment by elstoc** [comment] 2022-02-14 07:32
Hmm I agree for drawn masks (since those will almost always be image-specific) but I do make use of parametric masks in presets. Perhaps include an option in the preset creation screen?

**Comment by elstoc** [comment] 2022-02-14 08:38
You've made an assumption about use case there though -- you're dealing with the use case you've described in your issue, but the existing functionality (storing and resetting blending based on the preset) is still a valid use case. Auto-logic like this will always satisfy some and annoy others.

**Comment by da-phil** [comment] 2022-02-14 08:46
But wouldn't there be a behavior which pleases everybody / all use-cases?
I'm not saying that we should remove the blending mode parameters from presets, I can see how this is a desirable functionality.
I'm just challenging the status quo, whether we can make presets a little bit smarter and not reset blending mode parameters in any case, but just in cases where preset blending mode parameters deviate from the default.

**Comment by elstoc** [comment] 2022-02-14 09:27
> but just in cases where preset blending mode parameters deviate from the default

But you're assuming that your desired behaviour is what everyone will want. Personally, I might start with a preset, experiment with some blending behaviour and then want to revert to the original preset when I decide that I don't like my edits. In this case I _want_ to remove the blending parameters, so you have solved a problem with your use case by introducing the same problem to mine.

> But wouldn't there be a behavior which pleases everybody / all use-cases?

This is what I was suggesting above: if we include a boolean option when creating/editing presets like "include blending parameters", that should satisfy all use cases.

**Comment by parafin** [comment] 2022-02-14 10:52
I think this is mostly a duplicate of #7586 and #8861

**Comment by elstoc** [comment] 2022-02-14 11:23
Agreed let's close this and continue the discussion on #7586

**Closed by elstoc** 2022-02-14 11:23 UTC
