### ISSUE TITLE
3.8 shortcuts doesn't work and doesn't show english letters

### ISSUE THREAD

**Issue by XAndrey** [darktable-org/darktable#10765] opened 2022-01-02 13:57 UTC
**Did you buy darktable from an application store ?**
No.

**Describe the bug/issue**
First: all my old shortcuts (from 3.6.1 version) doesn't work.
Second: all new and old shortcuts shows as ONLY Cyrillic letters instead of Latin letters.
For example: old shortcut for select all was "ctrl+a" now doesn't work, and shows as "ctrl+ф". But when i type it in latin language as "ctrl+a" darktable shows it like "ctrl+ф". And so with all other shortcuts.

**To Reproduce**
Set shortcut for "select all" action as "ctrl+a".
Lighttable mode.
Open a few files thumbs.
Press "ctrl+a" to select all files.

**Expected behavior**
Select all files

**Screenshots**
![assigned](https://user-images.githubusercontent.com/20306883/147878019-c414235f-e650-4655-a978-86d9fd92b7a9.jpg)
![not assigned](https://user-images.githubusercontent.com/20306883/147878023-789ab0e0-922f-40ae-84ff-83506df537f7.jpg)

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : 3.8.0
* OS                : Windows 7 Sp1

**Comment by dterrahe** [comment] 2022-01-02 15:05
> Guys, why did you broke shortcut function?

For fun!

Your problem looks similar to #9512 but as you can read there, that problem went away/was no longer reproduceable. If we can't reproduce a problem, we can't fix it. Reproducing a problem requires cooperation with the bug reporter, since they _have_ the problem whereas the developer has not (otherwise they would have fixed it in the development phase). If you want _your_ problem fixed (for free!) you may want to reconsider starting off by antagonizing the developer who would have to work closely with you for a bit to identify the cause of the problem. You don't _have_ to; you can do whatever you want! And so can we.

@esq4 do you still/again have the same issue or would you be able to suggest a cause/solution?

**Comment by XAndrey** [comment] 2022-01-02 15:38
OK, sorry if it looks offensive. But i have feel it so when get update and get some problems instead simply "new shortcut mechanics" and "you may need to reassign your shortcuts."
I deleted this sentense.

**Comment by dterrahe** [comment] 2022-01-02 16:07
> i have feel it so when get A FREE update and get some problems

Fully understood.

I feel the same way when we have had these changes in the development environment for half a year and nobody spent the time to test the nightlies and report this problem (apart from @esq4) and then expect a polished product without flaws after release. Of course we could tell people "this is a .0 release; if you can't tolerate issues, wait for the .1", but then no testing will take place until a month later.

"Users" correctly assume that it is hard to contribute to this project as a developer (coding in dt isn't easy) but they _could_ all be testers, especially since there is a whole infrastructure to produce daily snapshots/executables. Nobody gets paid to work on dt (apart from a few contributions) so if you are only taking and not giving anything back, at least be respectful about it. Or _do_ give back for example by getting involved in user feedback discussions or by testing early and providing useful bug reports and assistance in reproducing bugs. Ask any tester; it can be very satisfactory to catch a bug and help make sure it is fixed before release. And the response you'll get from developers is generally appreciative (depending on your attitude).

Until I get more info, I consider this a duplicate of #9512

**Comment by TurboGit** [comment] 2022-01-02 16:24
Fully agree with you @dterrahe ! Some time we really need to be clear on that.

**Closed by TurboGit** 2022-01-02 16:24 UTC
