### ISSUE TITLE
Thumbnails should not use GtkOverlay

### ISSUE THREAD

**Issue by houz** [darktable-org/darktable#4689] opened 2020-04-11 22:16 UTC
The new thumbnail code uses GtkOverlay to assemble its GUI. After consulting the GTK people in IRC they said that overlays are NOT meant to be used when the overlays overlap. They are only supposed to be put ontop the base widget. As a result it can happen that the image, which is quite big and NOT the base widget gets drawn over other overlays. Also, using regular widgets like GtkLabel is supposed to be a bad idea as these can have backgrounds that can get drawn and block some parts of the underlying stuff. I know that dt tries to remedy that in its CSS, but overall I think the design of the thumbnails needs to be revisited and everything has to be drawn in a single pass with cairo instead of using a GtkOverlay.

Once that is done we can also bring back the custom metadata overlay. I tried to add it in the current system but it doesn't work, the image always blocks the label I added.

**Comment by AlicVB** [comment] 2020-04-12 09:51
that depresses me...

Can you precise what is exactly your issue ? I'm not sure to understand "custom metadata overlay" which/where/mode/layout/...

**Comment by AlicVB** [comment] 2020-04-12 12:07
ok, after some tests, I suppose, you speak about the "extended overlays", right ?
Indeed, they appears below the image. It's due to your commit : https://github.com/darktable-org/darktable/commit/7603054909f55cc6958a695f62ee94370ad417de

according to @aurelienpierre you've put the gradient behind the image because it was drawn on top of stars otherwise. I've tested and I don't reproduce this issue. Here's for example what I see on screen before your commit and with a "ugly" red gradient for testing purposes : 
![Capture d’écran_2020-04-12_13-47-34](https://user-images.githubusercontent.com/1818223/79068222-a82acc00-7cc5-11ea-87c0-6f8f5087011b.png)
You can see that stars are still in shade of grey, without any red tint (verified in gimp)
Is that what you have too ?

**Comment by houz** [comment] 2020-04-12 12:07
https://github.com/darktable-org/darktable/blob/darktable-3.0.x/src/views/view.c#L1747-L1791

**Comment by houz** [comment] 2020-04-12 12:09
The gradient wasn't drawn on top of the stars but ontop of the image. Maybe that's not the case for you because, as I wrote, overlays are not supposed to overlay each other, so the results are random.

That being said, this issue is not about the gradient at all but the custom metadata overlay that you didn't port when you rewrote the lighttable.

**Comment by AlicVB** [comment] 2020-04-12 12:35
> https://github.com/darktable-org/darktable/blob/darktable-3.0.x/src/views/view.c#L1747-L1791

Oh, my bad, forgot that. I'll have a look



> The gradient wasn't drawn on top of the stars but ontop of the image.

That was done on purpose, and that was already the case before my rewrite. On 3.0x (without my changes) : 
![overlay_before](https://user-images.githubusercontent.com/1818223/79068702-23da4800-7cc9-11ea-87a4-c65c62a98229.png)

On current master (before your commit) : 
![overlay_after](https://user-images.githubusercontent.com/1818223/79068698-1cb33a00-7cc9-11ea-82b0-742114c3a22f.png)



> overlays are not supposed to overlay each other

Those gtk guys are funny... they force us to write non-sens sentences...
Anyway I have really some concerns here, as I have carefully chosen the widget type and it's explicitly mentioned in the official gtk docs that childs can overlap and they even precise in which order they are drawn.
See https://developer.gnome.org/gtk3/stable/GtkOverlay.html esp. part about reordering
So if we really face random order drawing, it's clearly a bug that should be fixed upstream !

**Comment by houz** [comment] 2020-04-12 12:49
All I can say is what I was told on IRC yesterday. That being said, I tried a minimal example and there it works, however, I tried adding a new GtkLabel to the thumbnail for the extra text, and no matter where I added it, it was always behind the image. So maybe we are doing something else that we shouldn't do? If you add a label that spans (almost) the entire space, does it get drawn on top of the image for you?

**Comment by TurboGit** [comment] 2020-04-12 13:16
> So if we really face random order drawing, it's clearly a bug that should be fixed upstream !

Looking at the doc I agree. Don't make best be enemy of good anyway :)

**Comment by TurboGit** [comment] 2020-04-12 13:18
For the extended overlay we probably want to rework this part. The fact that the gradient is behind the image is better to me. But then we need to rework the extended overlay and have a way to see them clearly.

**Comment by houz** [comment] 2020-04-12 14:07
If we can find any way at all I would love to remove the gradient altogether. I consider it ugly, and at least for me it makes stars less visible when not overlapping the image.

**Comment by TurboGit** [comment] 2020-04-12 14:19
I'm sure @AlicVB will find a solution for the extended overlay, it is a champion for GUI stuff at this stage! BTW, if the solution requires too much work because the gradient I'm also ok to remove it.

**Comment by houz** [comment] 2020-04-12 14:38
Let's ignore the gradient for now, I don't think it has anything to do with not being able to put a label over of the image.

**Comment by Nilvus** [comment] 2020-04-12 15:58
> If we can find any way at all I would love to remove the gradient altogether. I consider it ugly, and at least for me it makes stars less visible when not overlapping the image.

I totally agree here with your sentence just above : this gradient is ugly and unuseful. I will also appreciate seeing that disappear. I would just keep the transparent overlay to display text and so keeping space for the images. If possible regarding this discussion, I don't have any skills in GTK, just CSS.

Good to see you open this issue to discuss before doing anything else. That would let the possibility to find the better way as possible.

**Comment by aurelienpierre** [comment] 2020-04-12 16:34
As the author of the ugly gradient, I would like to remind people that it is not an aesthetic choice, but it is there only to darken the background for overlay icons (stars, groups, etc.), which are not legible on top of bright thumbnails without it.

Every other software uses rectangular image frames and puts text in the safety margins. Having icons overlay the image it bad practice, since the background color can't pe predicted, perhaps it's time to ditch it.

**Comment by houz** [comment] 2020-04-12 16:42
Thing is, putting the gradient OVER the image is a no go. So the only times it affects visibility of icons is when they are over the regular background. And then the gradient makes the contrast (at least in parts) worse.

**Comment by aurelienpierre** [comment] 2020-04-12 16:48
Originally, the gradient went between image and icons.

**Comment by AlicVB** [comment] 2020-04-12 16:51
I've a good news for all of you : with the "magic" of css, removing the gradient is just a matter of updating 2 lines of code in darktable.css : 
here https://github.com/darktable-org/darktable/blob/1231dd160401d72a993cdf1e91ce45f3efb4f644/data/themes/darktable.css#L1554 and the line under.

**Comment by aurelienpierre** [comment] 2020-04-12 17:04
Just to show the problem:
![Capture d’écran du 2020-04-12 19-00-23](https://user-images.githubusercontent.com/2779157/79074968-e806a900-7cef-11ea-8830-6384eedfbc34.png)

Whatever software you pick, they have an area for images, and an area for properties :
![](https://learn.captureone.com/wp-content/uploads/sites/5/2013-11-22_15-06-281.png)

![](https://www.photograpix.fr/photograpix/wp-content/uploads/2016/04/RawTherapee-navigateur-de-fichiers.jpg)

**Comment by AlicVB** [comment] 2020-04-12 17:19
> Let's ignore the gradient for now, I don't think it has anything to do with not being able to put a label over of the image.

@houz and others : can you test this branch : https://github.com/AlicVB/darktable/tree/overlay_test ? and report if you see the label ? That should answer the question...

for the gradient part, as said, What we have to decide is "just" what should be the default look. (what should be in the css) This as nothing to do with underlining code. That's at least how I see the separation between code and css

**Comment by TurboGit** [comment] 2020-04-12 17:27
I tried the branch, there is no highlight of the thumbs under the mouse so it is hard to say.

**Comment by AlicVB** [comment] 2020-04-12 17:29
no, sorry, I didn't explain well. The question is : do you see the "yes" in red in the middle ?
If yes, that means That I've solve @houz concern about adding a label ontop of the image

**Comment by aurelienpierre** [comment] 2020-04-12 17:31
What about simply resizing thumbs to free the bottom part for the icons ? That should fix the *core* issue instead.

**Comment by AlicVB** [comment] 2020-04-12 17:34
@aurelienpierre : this can -almost- already be done in... css (again) margins can be set independently for each side of the image. You can try something like : 
```
#thumb_image
{
  border: none;
  margin : 1px 4px 10px 4px; /* not real pixels, but percentage of the thumb size */
}
```
(adjust the margin values to your needs)

**Comment by Nilvus** [comment] 2020-04-12 17:43
Seen the comparative screenshots posted by @aurelienpierre, I finally would be to reduce image to have all icons and stars below the image and not overlay it. That's would also remove the gradient and probably simplify things here.

**Comment by TurboGit** [comment] 2020-04-12 17:46
No, I don't see the yes in the middle of the thumbs. In fact I see them while dt is still loading and see a big red yes on the thumbs, but as soon as the thumbs is finished to be displayed the YES does not show anymore.

**Comment by TurboGit** [comment] 2020-04-12 17:57
@Nilvus, yes something like that could work. Also note that we can remove the extended overlay altogether as we now have tooltip with image information (and even better since this is configurable by users). So under the image we only need to fit the stars and reject icon. Right?

**Comment by AlicVB** [comment] 2020-04-12 17:59
@TurboGit : thanks. I have done a too quick testing with too small test images. I'll investigate as there's no reason extend overlay appear ontop of the images and not this test label...

**Comment by AlicVB** [comment] 2020-04-12 18:32
ok, I've understand what happens. In fact gtklabel is not a widget like the others in terms of internal drawing. So in this case, we need to put it inside a gtkeventbox, and everything should be back to normal (meaning here : you see a big "yes" in red ontop of the image)
That what I've done on the updated branch : https://github.com/AlicVB/darktable/tree/overlay_test

@TurboGit : can I annoy you with another test ? (sorry for that)

**Comment by TurboGit** [comment] 2020-04-12 18:38
Perfect ! I have big ugly red YES on all thumbs :)

**Comment by Nilvus** [comment] 2020-04-12 20:12
> @Nilvus, yes something like that could work. Also note that we can remove the extended overlay altogether as we now have tooltip with image information (and even better since this is configurable by users). So under the image we only need to fit the stars and reject icon. Right?

That way, yes stars, reject icons and, don't forgot them, color labels stay under the image as it already the case. So just need to let image infos as a tooltip this case. Why not, I don't use image infos on thumbnails so for that, I personally don't care. @houz, @AlicVB and @aurelienpierre: what do you think of that?

**Comment by AlicVB** [comment] 2020-04-13 09:52
Well, the real question is : do we need to remove them ? (note that I don't use them either) : 
- it's about 3 lines of code in C (and don't add real complexity) it's just something like "`if (extend_overlay) { put the corresponding text in the label + add "dt_extented_overlay" class to the label }`
- it's themable via css, separately from the rest.
- note that what @houz is speaking about is another thing : you can have a .txt sidecar file for your image with some infos inside. this information used to be shown for zoom == 1, culling, preview. I've just touch the zoom==1 and forgot to add it back. I'll do it soon ! 

So imho, we can let extented overlay like that even if it's drawn ontop of the image (only on mouse hover). if user don't like it, they can disable it with 1 click.

This doesn't prevent us to discuss and change the look, placement, etc... of "classic" information (reject, stars, colorlabels)
Personally, I vote for removing the css gradient and don't touch the rest letting maximum space for the image.
@aurelienpierre is right to say that stars aren't readable anymore on bright image, but in this case, there's still the tooltip (maybe that need to add another configurable field, with some nice stars chars)
and if someone work with almost only bright images, gradient of background color can be added with 1 line in css (the line can even be present but deactivated with a comment)

**Comment by TurboGit** [comment] 2020-04-13 10:19
I don't think having the stars in tooltip is good. The stars must be shown and visible on all images in the lt just because that's the way we compare, select, organize the images.

**Comment by GrahamByrnes** [comment] 2020-04-13 10:19
Just a "having cake and eating it thought", possibly impractical... is it possible to switch the stars to the left column when the photo is portrait mode? 
Then you wouldn't need the gradient and the visibility would be determined by the frame.

**Comment by TurboGit** [comment] 2020-04-13 10:20
What I fear with letting more space below is that we will probably have very little image thumbs and probably loose one zoom level to work comfortably. To be tested...

**Comment by TurboGit** [comment] 2020-04-13 10:20
> Just a "having cake and eating it thought", possibly impractical... is it possible to switch the stars to the left column when the photo is portrait mode?

That's not a general option... What to do with square pictures ?

**Comment by johnny-bit** [comment] 2020-04-13 10:21
I'm all in favour of not putting anything on the image in thumbnails. This would alleviate some issues for me like stars hiding some details in bottom of image etc and would probably simplify thumbnail control.

As I suggested, tooltips are more better for details (and it shows even here) that leaves handfull of information to show:
- image extension (is it even usable? could be just raw/not raw)
- rating stars and rejection
- color flags (thb it's cool that we can use up to 5 on single image and it takes similar amount of space as single star), some apps have just 1 color flag max
- is image BW
- is image "HDR" (that's a recent request :) )
- is image a "local copy"
- is image altered in any way
- audio note (& play)
- txt note

Now the way to display those - in case there's no overlay - just display image thumbnail without anything :laughing: If the image overlay is presen (so show info)... Do you guys had those plastic film positive/negative/slide holders? that could be used as an inspiration

**Comment by GrahamByrnes** [comment] 2020-04-13 10:31
> That's not a general option... What to do with square pictures ?

Indeed. But they still leave more space at the bottom than portrait mode.

**Comment by AlicVB** [comment] 2020-04-13 10:54
> I don't think having the stars in tooltip is good. The stars must be shown and visible on all images in the lt just because that's the way we compare, select, organize the images.

agree. As said, this may just be an help for the (rare) images where they aren't readable



> What I fear with letting more space below is that we will probably have very little image thumbs and probably loose one zoom level to work comfortably. To be tested...

Here's a test with the minimal space needed under the images : 
![Capture d’écran_2020-04-13_12-47-39](https://user-images.githubusercontent.com/1818223/79115285-bcce9900-7d85-11ea-85db-5bbb3c1051dc.png)
We used to have 4% margins around the image. So **the image used to take 92%** of the thumbnail. Here, I've set (with css) margin top to 1% and margin bottom to  12% **So the image only take 87%** of the thumbnail :(
Good news for some of us : that doesn't affect landscape images (no change in left/right margins)

**Comment by johnny-bit** [comment] 2020-04-13 11:01
OK, so... This might turn into "design thumbnail control from scratch". I'll try to give some of pointers that are important (IMHO):

1. Nothing can obstruct image. No gradient, no stars, no nothing.
2. There's level of importance of specific info vs thumbnail size vs zoom level.
3. Control must be constant size regardless of image orientation/aspect ratio.

> What I fear with letting more space below is that we will probably have very little image thumbs and probably loose one zoom level to work comfortably. To be tested...

Currently filemanager can handle up to 21 images in a row and that's honestly unreadable to discern images let alone starts comfortably. at 13 images in a row it just starts to be visible, but any extended info is too small to read (unless one has 4k monitor?)

With sample from @AlicVB - I honestly think it's positive change. I'd rather take up some vertical space from image to make sure all info is shown than show info on top of image... I wonder if that can be changed in a way that leaves top and bottom margin constant regardless of image orientation (that would impact vertical images the most), bacause that would visually be consistent. try having images side by side that are vertical and horizontal - you'll see what I'm talikng about.

**Comment by GrahamByrnes** [comment] 2020-04-13 11:12
>  I wonder if that can be changed in a way that leaves top and bottom margin constant regardless of image orientation (that would impact vertical images the most),

![image](https://user-images.githubusercontent.com/58031430/79116246-41221b80-7d88-11ea-9920-ad4546ee1c82.png)

Not convinced. But if I want to look at a thubnail... I usually make it bigger than a thumbnail. Eyes getting old and all that.

**Comment by AlicVB** [comment] 2020-04-13 11:16
> I wonder if that can be changed in a way that leaves top and bottom margin constant regardless of image orientation
![Capture d’écran_2020-04-13_13-06-07](https://user-images.githubusercontent.com/1818223/79116012-a295ba80-7d87-11ea-8277-5d4cfd1532cf.png)

And just to be clear, can all of you precise if he has in mind "always shown" info bar (stars, ...) or just on mouse over. I think the effect is quite different.
Here, I just show them on mouse over. This may explain why I don't care too much about overlapping. If stars obstruct the image I move the mouse outside !

**Comment by johnny-bit** [comment] 2020-04-13 11:48
@AlicVB - i meant for horizontal and vertical images to have same amount of space top&bottom, so topline of vertical image is on the same line as topline of hotizontal image. same for bottom line.

I need to draw what I have in mind i think ;)

**Comment by johnny-bit** [comment] 2020-04-13 13:09
I know this looks bad but hear me out.

![test1](https://user-images.githubusercontent.com/10687765/79121657-13dc6a00-7d96-11ea-8634-a0802f1c8739.png)

(the screenshot was almost unmodified 3.1.0+1042)

So generally - on top you have constant-height line for things like Ext, group, modified etc
on bottom - constant height line for star/color ratings

(I know margins are too big, sorry about that)

Now for usage cases:
1. Overlay disabled (so on mouse over)
Use as much space as possible for image, no ext, no info, nothing.
On mouse over either:
- shrink down image to show overlay in a way that won't overlap image
- draw opaque (no gradient, fck it) background for overlay info and overlay that on top of image

I'd be for 1st - shrink image to show overlay info.

2. Overlay enabled
reserve constant amount of space (top and bottom) to show star ratings, colors, status(group, modified etc) & extension. Rest of the space - fill with image

3. Extended overlay enabled
on top of space reserved in point 2, reserve additional space for extended overlay (probably configureable, should default to number of lines of extended overlay). Draw it all constantly (no on mouseover please)

I know this might be different for everybody, but everybody's workflow is different. For example, I'd have point 2 (overlay enabled) constantly on. My wife would opt for point 3, @AlicVB already said that he'd use no-overlay with mouseover :)

Doing it the way I described minimizes impact for overlay on top of images, while helps (especially those who like extended overlay). In many workflows extended overlay is simply file name :) so that's a single line of text.

**Comment by AlicVB** [comment] 2020-04-13 13:40
We have in fact 4 cases to handle ;)
1. show always + only stars/...
2. show always + extended overlays
3. show on mouse hover + only stars/...
4. show on mouse hover + extended overlays

What I can propose to please everyone (I hope) : 
- drop the gradient (in css)
- add a new "never overlay" pref.
- if TRUE, always reserve the amount of space needed on top/bottom of the thumbnail and just ignore the css margin value if it's smaller.
- if FALSE, the contrary :) but it will need the addition in css of a semi transparent background/gradient/... especially for extended overlay (all this can be done in css)

In the context of the 4 situations described previously, that should work quite well and please everyone. What do you think ?

@johnny-bit : for the rest, there's 2 points which won't work imo : 
- your mockup screenshot with same height render vertical images very very small, doesn't work anymore in case of panoramic images, and anyway, we can't crawl through all images to get their ratio and fix the size accordingly, it would be too slow !
- shrinking image on mouse hover is a really bad idea as it would end in an impression of "jump" as soon as your mouse will traverse the center widget... not to speak about perfs !

**Comment by johnny-bit** [comment] 2020-04-13 14:12
@AlicVB regarding shrinking - I also think it's sorta bad idea :)

Regarding ratio/fix size etc - I thought you could have constant width/height for image area on thumbnail frame and just "fill the area" with image (eg height 100%). And I do know that it negatively affects display real estate of image.

The use cases you've mentioned:
1. show always + only stars/... - that would be "reserve amount needed on top/bottom" IMHO
2. show always + extended overlays (so show everything) - that too should be "reserve amount needed on top/bottom, only more on bottom :D " IMHO
3. show on mouse hover - that could be for opaque/semitransparent background for overlay
4. show on mouse hover + extended overlays - opaque/semitransparent background needed.

All that could be also helped (imho) with 4state "show/hide image overlays" button, that would cycle between "overlays on hover -> extended overlays on hover -> overlays always -> extended overlays always"
Hmm..

Or maybe 5th state where "overlays always + extended on hover" where space for icons is reserved, but extended overlay is drawn with background obstructing image?

This I think would cover all usecases :) That could also forgo "never overlay" pref since if yo enable overlay you want it to be shown :)

**Comment by bschwehn** [comment] 2020-04-13 16:31
Apologies for jumping in uninvited. The only reason I am reading this is because I wanted to check the code how it hard it would be to entirely remove the rating overlay in filmstrip mode :)

The reason is that I never use the rating star icons when in darkroom/filmstrip mode, but often misclick on the stars when I try to select an image from the strip. Which is quite annoying, especially when this causes an image to disappear due to a filter and also because undo does not seem to work when applying rating in the filmstrip (works in lightroom mode only)

Making the stars more visible may already help with that, but I think having an option to either hide the rating in darktable/filmstrip mode or make them readonly would be really nice. Making the action undoable would also help.

**Comment by houz** [comment] 2020-04-13 16:40
For what it's worth, I never enable the option to show all the ratings (so only mouse over for me) and I wasn't even aware that there is some extended overlay, so I don't care about that either.

**Comment by johnny-bit** [comment] 2020-04-13 16:55
@bschwehn - look at #4549 :)

**Comment by bschwehn** [comment] 2020-04-13 17:00
@johnny-bit brilliant, thanks. 

FWIW, fixing the undo in darktable might be as simple as changing line 38 in undo.h from 

`  DT_UNDO_DEVELOP     = DT_UNDO_HISTORY | DT_UNDO_MASK | DT_UNDO_TAGS,`


to 

  `DT_UNDO_DEVELOP     = DT_UNDO_RATINGS | DT_UNDO_HISTORY | DT_UNDO_MASK | DT_UNDO_TAGS,`

Works as far as I can tell, but I don't know the code well enough to understand if that may cause some unintended side effects.

**Closed** 2020-04-16 21:05 UTC

**Comment by houz** [comment] 2020-04-17 17:50
@AlicVB I added the custom metadata as a label in an eventbox, thanks for figuring that out. The only thing that I wasn't sure how to best do it is only showing it when zoomed in to a single image. Could you please have a look?

**Comment by AlicVB** [comment] 2020-04-17 18:39
@houz : yes I'll have a look

**Comment by houz** [comment] 2020-04-19 12:39
While at it, please make also sure it's not shown when in film strip. The same widget gets used both on lighttable and in the film strip which is not intended of course.
