### ISSUE TITLE
Inconsistent RAW processing with exposure errors after opening a jpeg in darkroom

### ISSUE THREAD

**Issue by vostmarhk** [darktable-org/darktable#6202] opened 2020-09-04 13:35 UTC
When I open .ARW files from Sony a6000, sometimes they are way too dark, even after the application of the base curve. With the fixed camera settings and lighting, a picture of a light object may appear in darktable normally (see screenshot 1), whereas a picture of a similar dark object will open as a very dark raw file (see screenshot 2). Meanwhile, the jpegs are unaffected. 

**To Reproduce**

1. Take a photo with a reasonably high contrast with Sony a6000, save both RAW and JPEG
2. Import files into Darktable
3. Open the raw file 
4. See that the exposure is off.

Edit: more precise algorithm from some troubleshooting in the comments below

1. Import a new directory which contains .arw and jpeg images
2. Open one of the .arw files in the darkroom, check that the exposure is normal
3. Open a jpeg using the bottom panel in the darkroom
4. Open a new .arw file using the same panel. The exposure will be off compared to the first raw file.
5. (optional) You can import the directory again and start from the second raw file, just to make sure that both raw files I provide should in fact have the same exposure.

**Expected behavior**

The exposure on the second photo (screenshot 2) should be the same as on the first photo (screenshot 1).

**Screenshots**

![Screenshot 1](https://user-images.githubusercontent.com/23016690/92245025-685ebe00-eecc-11ea-89ef-b6718950ed2b.png)
![Screenshot 2](https://user-images.githubusercontent.com/23016690/92245073-7a406100-eecc-11ea-95f0-477281ce3b67.png)

**Platform (please complete the following information):**
 - Darktable Version:  3.2.1
 - OS:  Manjaro Linux
 -  OpenCL activated
 -  Nvidia 1650 GTX Max-Q with 440.100 driver and Intel UHD 630

**Additional context**

I didn't observe such errors with darktable 3.0.x. There is also a chance that something might be wrong with my camera, but I don't see how that can be the case if jpegs are normal and only raws are affected. 

Edit with findings from troubleshooting below: 

What seems to be happening is the following: when I open a jpeg, the input profile module switches to sRGB, and does not reset back to standard afterwards. All consequtive raws are opened with sRGB input profile, which breaks all subsequently applied modules in the chain (they have 0 effect), resulting in the darkness. Switching the input profile back to standard in the module settings fixes the "darkened" raw file.

**Comment by parafin** [comment] 2020-09-04 13:45
I think it's some camera setting like highlight tone priority, which underexposes an image to save highlights but corrects it when producing the JPEGs. It's not detected by darktable and not auto-corrected. Please check your camera settings.

**Comment by vostmarhk** [comment] 2020-09-04 14:01
Well the closest thing to that in the camera is DRO, which is turned off. The example pictures on the screenshots have the exact same exposure settings, with every parameter fixed manually - so even if the camera wanted to mess with the exposure, it would have no control over it. Surely this has to produce the same exposure between raws?

**Comment by parafin** [comment] 2020-09-04 14:13
Is ISO the same also? I see that exposure and aperture are the same, but ISO is not visible. And lighting didn't change between these images?

**Comment by vostmarhk** [comment] 2020-09-04 14:17
ISO is 100 on both images, as shown below the image. The lighting is exactly the same. I literally only switched one car with the other and that is all the difference between the pictures.

**Comment by parafin** [comment] 2020-09-04 14:24
sorry, didn't notice the bottom panel. Could you attach .xmp files for both images (add .txt extension to attach them here)?

**Comment by vostmarhk** [comment] 2020-09-04 14:41
Sure, here they are:
[DSC02596.ARW.xmp.txt](https://github.com/darktable-org/darktable/files/5175450/DSC02596.ARW.xmp.txt)
[DSC02597.ARW.xmp.txt](https://github.com/darktable-org/darktable/files/5175451/DSC02597.ARW.xmp.txt)

So I've just discovered the weird thing. If I copy all the images to another folder _without_ the XMP files (so that they are indexed from zero), these same raws open normally without any issues!
However, deleting the XMP files for these specific files in the original folder does not help: upon reindexing, they are still broken. It seems that getting rid of all the XMPs or making a brand new folder fixes the issue. 

I do have XMPs generated by previos versions in the same folder, but I did have the same issue with brand new folders too before.

**Comment by ptilopteri** [comment] 2020-09-04 14:44
deleting the xmp files is not enough, you must delete the images from the library.db and then reimport them.  The library.db contains the same data as the xmp files unless you have edited them again using a different library.db.

**Comment by parafin** [comment] 2020-09-04 19:26
If importing the images as fresh files fix the issue, then it means you have something in the history making them dark. Discarding the history should also have the same effect. So the question is how it came to be, which is hard to answer if you can't reliably reproduce the issue. Probably this image got history stack from some other previously imported image. E.g. named the same way, but then removed. Or you have some database corruption. As for darkenning effect, I see only one enabled iop that can have such effect - raw black/white point, so please compare its setting between the buggy image and its freshly imported counterpart.

All-in-all it's not obvious if there is any bug here.

**Comment by vostmarhk** [comment] 2020-09-04 19:42
The raw black-white point is the same for all images. 

I've tried to open more images, and actually fresh import does not fix the issue for all images. It appears that some files open normally, while others get darkened. I can't see any pattern in regards to which images get darkened: the set is random for every re-import. Again, all of the images have the same settings and lighting. I am at a loss, to be honest.

**Comment by parafin** [comment] 2020-09-04 19:48
Please try with fresh darktable config dir (move away ~/.config/darktable) and no XMP files.

**Comment by vostmarhk** [comment] 2020-09-04 19:51
There is actually a pattern I've found just now. If I open a jpeg after opening some raws, then all raws which I open after that jpeg will get darkened, unless I've opened them before opening the jpeg. 

(by opening I mean entering the darkroom mode)

Sounds like some setting might be misbehaving somewhere.

**Comment by parafin** [comment] 2020-09-04 19:57
OK, that's more interesting. How do you switch between JPEG and raw? In darkroom or going back to lighttable?

**Comment by vostmarhk** [comment] 2020-09-04 19:58
I have tried wiping the config directory - no difference, still dark raws under the same conditions. 

The histogram looks different though for some reason on the fresh config compared to the old one.

**Comment by vostmarhk** [comment] 2020-09-04 19:58
I am switching using the darkroom bottom panel.

**Comment by parafin** [comment] 2020-09-04 20:04
Can't reproduce though. Could you share a jpeg and raw files and exact steps to reproduce starting with fresh import of a directory with those 2 files?

**Comment by vostmarhk** [comment] 2020-09-04 20:19
Here is the archive with 2 .arw files and 1 jpeg: https://www.amazon.com/clouddrive/share/apaZI8JqnaVzyu4PC1ryo3tRvKX2AtJsbY7W5keegCf

To reproduce, 
1) Import the directory with all files
2) Open one of the .arw files in the darkroom, check that the exposure is normal
3) Open the jpeg using the bottom panel in the darkroom
4) Open the second .arw file using the same panel. The exposure will be off compared to the first raw file. 

P. S.: I've checked that opening from light table does not generate this issue, unless the raw file was opened and darkened in the darkroom before, in which case it stays dark. Fresh files open normally in light table though.

**Comment by vostmarhk** [comment] 2020-09-04 21:05
I think I managed to narrow it down to the input profile module. What seems to be happening is the following: when I open a jpeg, the input profile module switches to sRGB, and does not reset back to standard afterwards. All consequtive raws are opened with sRGB input profile, which breaks all subsequentl applied modules in the chain (they have 0 effect), resulting in the darkness. Switching the input profile back to standard in the module settings fixes the "darkened" raw file. 

If there is any setting to prevent the input profile from changing, the issue will be fixed completely.

**Comment by ddbzombie** [comment] 2020-09-05 07:22
I just want to say that i have a similar if not the same problem.  it doesn't matter what sony camera I use.  so it must be ARW and database related.   I use ubuntu 20.4.1 and darktable 3.2.1.  
![Screenshot from 2020-09-05 00-20-56](https://user-images.githubusercontent.com/70794975/92300193-d4154b00-ef0d-11ea-89d1-bb7470c98963.png)

**Comment by parafin** [comment] 2020-09-05 08:43
OK, I can confirm this issue. It happens when "don't use embedded preview JPEG but half-size raw" option is disabled in preferences, raw image has an embedded preview (basically any raw file out there, but I happened to test it originally with dng file without preview JPEG) and you switch in darkroom from JPEG file to raw that wasn't opened before. First 2 points make sure that history stack wasn't created before you open the raw file in darkroom.

This is a bug in input color profile iop. Something that definitely must be fixed.

**Comment by jenshannoschwalm** [comment] 2020-09-05 12:40
Could #5291 be related?

**Comment by junkyardsparkle** [comment] 2020-09-06 08:09
See also #5954

**Comment by jenshannoschwalm** [comment] 2020-09-06 18:30
Some weird i observe; it seems the modules reload_defaults code is never executed when changing the image via filmstrip. Any ideas @parafin or @TurboGit ?

**Comment by TurboGit** [comment] 2020-09-08 06:25
Yes, looks like we have some big issue here. I just hit this this morning. Copy exposure (Ctrl+Shift+C) from one image, select another image and paste (Ctrl+v) and at some point the preview is almost full red !!!!

**Comment by junkyardsparkle** [comment] 2020-09-08 07:35
Yes, the bad part is that it can be really difficult to figure out what's going on... the input color profile module isn't usually the first thing I check when things go wrong like that. :/

**Comment by TurboGit** [comment] 2020-09-08 07:40
@junkyardsparkle @jenshannoschwalm : see #6236.

**Comment by TurboGit** [comment] 2020-09-08 15:48
Fixed, closing.

**Closed by TurboGit** 2020-09-08 15:48 UTC
Labels: bug: pending, priority: medium, reproduce: confirmed, understood: clear
