### ISSUE TITLE
Wrong "capture time" ordering

### ISSUE THREAD

**Issue by lucaddy** [darktable-org/darktable#16469] opened 2024-03-15 19:53 UTC
### Describe the bug

Hi, it's from several version that I notice that Darktable (now 4.4.2) have problems in ordering pics by capture time. In fact, it mixes photos taken in different periods. "Capture time" should sort them based on the shooting date in the Exifs, but sometimes this doesn't happen, and photos are displayed randomly. In fact:

1.  Darktable in the photos information show a timestamp similar to the correct ordered photos (sometime the same). BUT the Exif information in the file are correct, and also the sidecar created by Darktable. For example the pics below, for both Darktable show a timestamp: "11/11/23 16:34:03". I know that it's corect only for the lefct photo. The right photo, in the Exif have the correct information  "date_time_original" = "2023:03:26 09:55:34.750" and it's the same in the sidecar created by Darktable. But evidently for houndred of pics Darkteble doesn't take into accout this timestamp and "invent" one, causing an improper mixing.
2. The other strange thing is that of these mixed photos, a preview is sometimes shown with staggered colors (green or purple hues), or sometimes even opening them in lightable changes the photo by displaying another one!
3. I have already tried changing the version of Darktable and deleting the DB and also the entire AppData\Local\darktable

This seems like an important thing to point out to me. I have not found other reports.

### Steps to reproduce

Import photos, order by capture time.

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.4.2

### What OS are you using?

Windows

### What is the version of your OS?

Windows 11 Pro 23H2

### Describe your system?

Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz, RAM 16,0 GB

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

NVIDIA GeFroce MX250

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Reflex Nikon D5600

LInk to image and xmp https://drive.google.com/drive/folders/14reAPZlFWLNBZ6JUmRoZlpg_mOWto5WS?usp=sharing

**Comment by ptilopteri** [comment] 2024-03-15 21:29
would probably be helpful and pertinent to provide your camera information and a link to few of the images and accompanying xmp files that exhibit this condition.

**Comment by lucaddy** [comment] 2024-03-18 19:58
> would probably be helpful and pertinent to provide your camera information and a link to few of the images and accompanying xmp files that exhibit this condition.

Thank you, Ive uploaded the Issue, also witha  link to file.

**Comment by lucaddy** [comment] 2024-04-22 19:27
No one can reply to this issue? It's still present also in the 4.6.1 version.

**Comment by ptilopteri** [comment] 2024-04-22 19:45
perhaps this will help you.

images from my D7200,D500,D850,Z9 are not timestamped to the capture time

I routinely do the following:
  re-date images to capture time
  exiv2 -T ./*.{nef,jpg}

then change image filename to reflect same:
  exiv2 \-k \-r %y%m%d_%H%M%S_:basename: \.\/*.{nef,jpg}

and I do this every time I transfer images from my cameras.

**Comment by wpferguson** [comment] 2024-04-22 20:07
You created a duplicate of DSC_0900.NEF, which created an XMP file DSC_0900_01.NEF.xmp.  Then you added an image, 
DSC_0900_01.NEF so when darktable starts it applied the DSC_0900_01.NEF.xmp file to the duplicate and to DSC_0900_01.NEF which is why they wont sort correctly.  If I import without the xmp files the 2 images have the correct date time.  

If you do a remove, not a delete on those files so that they still exist, then rename DSC_0900_01.NEF to DSC_0901.NEF then reimport, they work fine.

**Comment by victoryforce** [comment] 2024-05-06 10:58
As @wpferguson explained, this is not a bug in the program, but an incorrect usage (image file naming that competes with the duplicate naming mechanism). So I'm closing the issue.

**Closed by victoryforce** 2024-05-06 10:58 UTC
Labels: bug: invalid, scope: DAM
