### ISSUE TITLE
Reusing Mask from other module crashes DT

### ISSUE THREAD

**Issue by muenznej** [darktable-org/darktable#6292] opened 2020-09-14 06:57 UTC
Hello, 

**Describe the bug & To Reproduce**
Since i use 3.2.1 on my windows machine DT crashes regularly when i use paths from other modules. E.g.: I used the sharpen tool on a object and wanted to use that path for exposure correction as well. Upon selection it crashes with a serious of cryptical popup messages, that i cannot screenshot since the program closes immediately.

**Expected behavior**
Dont  crash :)

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Darktable Version: 3.2.1
 - OS: Windows 8.1
 - OpenCL: yes
 - Geforce 940m and IntelHD

Update 1:
- It does not happen on all images
- the image that caused this bug, had all paths removed after the restart of DT
- the crash will happen with this image as soon as i try reproducing

Update 2: 
- after resetting the history, it works without problems again

Update 3:
- ok, crashed again after a series of modules i tried highpass filtering/sharpening with a mask and it crashed as:
"Unexpected ... the rest i couldnt read quickly enough"

**Comment by matt-maguire** [comment] 2020-09-14 08:46
Not sure what you mean by "paths"?

Maybe try disabling opencl and see if it still crashes?

If you start the program from a terminal, you'll get some useful output when the program crashes, which may provide some clues as to what is going on...

**Comment by muenznej** [comment] 2020-09-14 08:48
Hi, i ll try to run the terminal and deactivating CL. I mean masks. sorry for the confusion

**Comment by muenznej** [comment] 2020-09-14 09:34
Couldn't reproduce this problem in DT from terminal and CL on :<

**Comment by matt-maguire** [comment] 2020-09-14 11:02
Ok, now I understand :-)  We'll need a way to reproduce the issue in order to investigate it.

**Comment by johnny-bit** [comment] 2021-06-13 11:46
Closing since we need a reproducible steps in order to investigate. THere were quite a lot of changes between 3.2.1 and 3.4.1.. and then between 3.4.1 and current master in regards to masks so if you can use current master and reproduce the issue and then post reproduction steps here I'll reopen so the investigation can continue :)

**Closed by johnny-bit** 2021-06-13 11:46 UTC
Labels: no-issue-activity
