### ISSUE TITLE
iop order diferent when migrate from 2.6 - again

### ISSUE THREAD

**Issue by vsz1lu** [darktable-org/darktable#3437] opened 2019-11-14 23:03 UTC
Similar problem what is closed in #3401 

When You open an image in dt 3.0.0rc1 what have sidecar from dt 2.6 the iop order not match the default.

Why problem?
a, The output is not same in most of case in real work.
b, Working with pictures is different, when You reopen an old work and than pick up a new image.

------------------------------------------------------------
What I do?

1, delete config dir of darktable
2, start darktable 2.6.2+13
3, change language to english - restart
4, open an virgin raw image, sidecar xmp not present
5, close darktable
6, delete config dir of darktable
7, rename the newborn xmp
8, start darktable 3.0.0rc1
9, change language to english - restart
10, open the raw
11, set 'subset: all modules'
12, turn on sharpen, what is not default in 3.0.0
13, make duplicate by pressing CTRL+D
14, load the sidecar from dt 2.6.2+13 for the clone in lighttable
15, compare the iop order side by side

the result:
![01 basic](https://user-images.githubusercontent.com/57588193/68902032-88ec3a80-0737-11ea-994f-f879f88a6a08.png)
![02 tone](https://user-images.githubusercontent.com/57588193/68902040-90abdf00-0737-11ea-9400-7fb63df63e83.png)
![03 color](https://user-images.githubusercontent.com/57588193/68902053-973a5680-0737-11ea-8c60-5633d0911759.png)
![04 correction](https://user-images.githubusercontent.com/57588193/68902058-9b667400-0737-11ea-96f5-86642abe0292.png)
![05 effects](https://user-images.githubusercontent.com/57588193/68902073-a4574580-0737-11ea-9863-1f78b15439f9.png)

When load a sidecar from dt 2.6.2+13 where all iops on (xmp attached):

***** On-the-fly history V[1]->V[2], imageid: 1 ****************
   0                 flip multi  0 :: iop 20,00100000000 -> 20,00000000000
   1              sharpen multi  0 :: iop 53,00100000000 -> 53,00000000000
   2            basecurve multi  0 :: iop 23,00100000000 -> 23,00000000000
   3               colisa multi  0 :: iop 47,00100000000 -> 47,00000000000
   4               shadhi multi  0 :: iop 40,00100000000 -> 40,00000000000
   5     colorreconstruct multi  0 :: iop 28,00100000000 -> 28,00000000000
   6             clipping multi  0 :: iop 21,00100000000 -> 21,00000000000
   7             exposure multi  0 :: iop 12,00100000000 -> 12,00000000000
   8               invert multi  0 :: iop  2,00100000000 ->  2,00000000000
   9              relight multi  0 :: iop 51,00100000000 -> 51,00000000000
  10               levels multi  0 :: iop 50,00100000000 -> 50,00000000000
  11            tonecurve multi  0 :: iop 49,00100000000 -> 49,00000000000
  12           zonesystem multi  0 :: iop 48,00100000000 -> 48,00000000000
  13               filmic multi  0 :: iop 46,00100000000 -> 46,00000000000
  14                bilat multi  0 :: iop 42,00100000000 -> 42,00000000000
  15        globaltonemap multi  0 :: iop 39,00100000000 -> 39,00000000000
  16              tonemap multi  0 :: iop 11,00100000000 -> 11,00000000000
  17               velvia multi  0 :: iop 63,00100000000 -> 63,00000000000
  18         channelmixer multi  0 :: iop 59,00100000000 -> 59,00000000000
  19        colorcontrast multi  0 :: iop 57,00100000000 -> 57,00000000000
  20      colorcorrection multi  0 :: iop 52,00100000000 -> 52,00000000000
  21           monochrome multi  0 :: iop 45,00100000000 -> 45,00000000000
  22           colorzones multi  0 :: iop 43,00100000000 -> 43,00000000000
  23         colorbalance multi  0 :: iop 33,00100000000 -> 33,00000000000
  24             vibrance multi  0 :: iop 32,00100000000 -> 32,00000000000
  25         colorchecker multi  0 :: iop 29,00100000000 -> 29,00000000000
  26        profile_gamma multi  0 :: iop 25,00100000000 -> 25,00000000000
  27               dither multi  0 :: iop 70,00100000000 -> 67,50000000000
  28               atrous multi  0 :: iop 41,00100000000 -> 41,00000000000
  29              nlmeans multi  0 :: iop 38,00100000000 -> 38,00000000000
  30             defringe multi  0 :: iop 30,00100000000 -> 30,00000000000
  31          hazeremoval multi  0 :: iop 26,00100000000 -> 26,00000000000
  32            bilateral multi  0 :: iop 24,00100000000 -> 24,00000000000
  33              liquify multi  0 :: iop 17,00100000000 -> 17,00000000000
  34               ashift multi  0 :: iop 16,00100000000 -> 16,00000000000
  35                 lens multi  0 :: iop 15,00100000000 -> 15,00000000000
  36              retouch multi  0 :: iop 14,00100000000 -> 14,00000000000
  37                spots multi  0 :: iop 13,00100000000 -> 13,00000000000
  38       denoiseprofile multi  0 :: iop 10,00100000000 -> 10,00000000000
  39           rawdenoise multi  0 :: iop  7,00100000000 ->  7,00000000000
  40            hotpixels multi  0 :: iop  6,00100000000 ->  6,00000000000
  41            cacorrect multi  0 :: iop  5,00100000000 ->  5,00000000000
  42            watermark multi  0 :: iop 69,00100000000 -> 69,00000000000
  43              borders multi  0 :: iop 68,00100000000 -> 68,00000000000
  44          splittoning multi  0 :: iop 62,00100000000 -> 62,00000000000
  45             vignette multi  0 :: iop 61,00100000000 -> 61,00000000000
  46               soften multi  0 :: iop 60,00100000000 -> 60,00000000000
  47                grain multi  0 :: iop 56,00100000000 -> 56,00000000000
  48             highpass multi  0 :: iop 55,00100000000 -> 55,00000000000
  49              lowpass multi  0 :: iop 54,00100000000 -> 54,00000000000
  50             lowlight multi  0 :: iop 44,00100000000 -> 44,00000000000
  51                bloom multi  0 :: iop 37,00100000000 -> 37,00000000000
  52         colormapping multi  0 :: iop 36,00100000000 -> 36,00000000000
  53             colorize multi  0 :: iop 34,00100000000 -> 34,00000000000
  54          graduatednd multi  0 :: iop 22,00100000000 -> 22,00000000000

[dt2.6.2 all iops ON.zip](https://github.com/darktable-org/darktable/files/3849029/dt2.6.2.all.iops.ON.zip)

**Comment by junkyardsparkle** [comment] 2019-11-15 00:38
Is this possibly related to #3270?

**Comment by TurboGit** [comment] 2019-11-15 06:58
Can you elaborate a bit? I don't have time to read/tests all issues to find what is wrong.

So at least point to the issue, this will help a lot!

IIUC the only module activated is sharpen?

- What is the order of the modules in 2.6.2?
- What is the order of the modules in 3.0.0rc1?

**Comment by TurboGit** [comment] 2019-11-15 06:59
> `***** On-the-fly history V[1]->V[2], imageid: 1 **************** 0 flip multi 0 :: iop 20,00100000000 -> 20,00000000000 1 sharpen multi 0 :: iop 53,00100000000 -> 53,00000000000 2 basecurve multi 0 :: iop 23,00100000000 -> 23,00000000000 3 colisa multi 0 :: iop 47,00100000000 -> 47,00000000000 4 shadhi multi 0 :: iop 40,00100000000 -> 40,00000000000 5 colorreconstruct multi 0 :: iop 28,00100000000 -> 28,00000000000 6 clipping multi 0 :: iop 21,00100000000 -> 21,00000000000 7 exposure multi 0 :: iop 12,00100000000 -> 12,00000000000 8 invert multi 0 :: iop 2,00100000000 -> 2,00000000000 9 relight multi 0 :: iop 51,00100000000 -> 51,00000000000 10 levels multi 0 :: iop 50,00100000000 -> 50,00000000000 11 tonecurve multi 0 :: iop 49,00100000000 -> 49,00000000000 12 zonesystem multi 0 :: iop 48,00100000000 -> 48,00000000000 13 filmic multi 0 :: iop 46,00100000000 -> 46,00000000000 14 bilat multi 0 :: iop 42,00100000000 -> 42,00000000000 15 globaltonemap multi 0 :: iop 39,00100000000 -> 39,00000000000 16 tonemap multi 0 :: iop 11,00100000000 -> 11,00000000000 17 velvia multi 0 :: iop 63,00100000000 -> 63,00000000000 18 channelmixer multi 0 :: iop 59,00100000000 -> 59,00000000000 19 colorcontrast multi 0 :: iop 57,00100000000 -> 57,00000000000 20 colorcorrection multi 0 :: iop 52,00100000000 -> 52,00000000000 21 monochrome multi 0 :: iop 45,00100000000 -> 45,00000000000 22 colorzones multi 0 :: iop 43,00100000000 -> 43,00000000000 23 colorbalance multi 0 :: iop 33,00100000000 -> 33,00000000000 24 vibrance multi 0 :: iop 32,00100000000 -> 32,00000000000 25 colorchecker multi 0 :: iop 29,00100000000 -> 29,00000000000 26 profile_gamma multi 0 :: iop 25,00100000000 -> 25,00000000000 27 dither multi 0 :: iop 70,00100000000 -> 67,50000000000 28 atrous multi 0 :: iop 41,00100000000 -> 41,00000000000 29 nlmeans multi 0 :: iop 38,00100000000 -> 38,00000000000 30 defringe multi 0 :: iop 30,00100000000 -> 30,00000000000 31 hazeremoval multi 0 :: iop 26,00100000000 -> 26,00000000000 32 bilateral multi 0 :: iop 24,00100000000 -> 24,00000000000 33 liquify multi 0 :: iop 17,00100000000 -> 17,00000000000 34 ashift multi 0 :: iop 16,00100000000 -> 16,00000000000 35 lens multi 0 :: iop 15,00100000000 -> 15,00000000000 36 retouch multi 0 :: iop 14,00100000000 -> 14,00000000000 37 spots multi 0 :: iop 13,00100000000 -> 13,00000000000 38 denoiseprofile multi 0 :: iop 10,00100000000 -> 10,00000000000 39 rawdenoise multi 0 :: iop 7,00100000000 -> 7,00000000000 40 hotpixels multi 0 :: iop 6,00100000000 -> 6,00000000000 41 cacorrect multi 0 :: iop 5,00100000000 -> 5,00000000000 42 watermark multi 0 :: iop 69,00100000000 -> 69,00000000000 43 borders multi 0 :: iop 68,00100000000 -> 68,00000000000 44 splittoning multi 0 :: iop 62,00100000000 -> 62,00000000000 45 vignette multi 0 :: iop 61,00100000000 -> 61,00000000000 46 soften multi 0 :: iop 60,00100000000 -> 60,00000000000 47 grain multi 0 :: iop 56,00100000000 -> 56,00000000000 48 highpass multi 0 :: iop 55,00100000000 -> 55,00000000000 49 lowpass multi 0 :: iop 54,00100000000 -> 54,00000000000 50 lowlight multi 0 :: iop 44,00100000000 -> 44,00000000000 51 bloom multi 0 :: iop 37,00100000000 -> 37,00000000000 52 colormapping multi 0 :: iop 36,00100000000 -> 36,00000000000 53 colorize multi 0 :: iop 34,00100000000 -> 34,00000000000 54 graduatednd multi 0 :: iop 22,00100000000 -> 22,00000000000 `

Cannot read!

**Comment by chhil** [comment] 2019-11-15 07:08
Does this help?

***** On-the-fly history V[1]->V[2]
 imageid: 1 **************** 0 flip multi 0 :: iop 20
00100000000 -> 20
00000000000 1 sharpen multi 0 :: iop 53
00100000000 -> 53
00000000000 2 basecurve multi 0 :: iop 23
00100000000 -> 23
00000000000 3 colisa multi 0 :: iop 47
00100000000 -> 47
00000000000 4 shadhi multi 0 :: iop 40
00100000000 -> 40
00000000000 5 colorreconstruct multi 0 :: iop 28
00100000000 -> 28
00000000000 6 clipping multi 0 :: iop 21
00100000000 -> 21
00000000000 7 exposure multi 0 :: iop 12
00100000000 -> 12
00000000000 8 invert multi 0 :: iop 2
00100000000 -> 2
00000000000 9 relight multi 0 :: iop 51
00100000000 -> 51
00000000000 10 levels multi 0 :: iop 50
00100000000 -> 50
00000000000 11 tonecurve multi 0 :: iop 49
00100000000 -> 49
00000000000 12 zonesystem multi 0 :: iop 48
00100000000 -> 48
00000000000 13 filmic multi 0 :: iop 46
00100000000 -> 46
00000000000 14 bilat multi 0 :: iop 42
00100000000 -> 42
00000000000 15 globaltonemap multi 0 :: iop 39
00100000000 -> 39
00000000000 16 tonemap multi 0 :: iop 11
00100000000 -> 11
00000000000 17 velvia multi 0 :: iop 63
00100000000 -> 63
00000000000 18 channelmixer multi 0 :: iop 59
00100000000 -> 59
00000000000 19 colorcontrast multi 0 :: iop 57
00100000000 -> 57
00000000000 20 colorcorrection multi 0 :: iop 52
00100000000 -> 52
00000000000 21 monochrome multi 0 :: iop 45
00100000000 -> 45
00000000000 22 colorzones multi 0 :: iop 43
00100000000 -> 43
00000000000 23 colorbalance multi 0 :: iop 33
00100000000 -> 33
00000000000 24 vibrance multi 0 :: iop 32
00100000000 -> 32
00000000000 25 colorchecker multi 0 :: iop 29
00100000000 -> 29
00000000000 26 profile_gamma multi 0 :: iop 25
00100000000 -> 25
00000000000 27 dither multi 0 :: iop 70
00100000000 -> 67
50000000000 28 atrous multi 0 :: iop 41
00100000000 -> 41
00000000000 29 nlmeans multi 0 :: iop 38
00100000000 -> 38
00000000000 30 defringe multi 0 :: iop 30
00100000000 -> 30
00000000000 31 hazeremoval multi 0 :: iop 26
00100000000 -> 26
00000000000 32 bilateral multi 0 :: iop 24
00100000000 -> 24
00000000000 33 liquify multi 0 :: iop 17
00100000000 -> 17
00000000000 34 ashift multi 0 :: iop 16
00100000000 -> 16
00000000000 35 lens multi 0 :: iop 15
00100000000 -> 15
00000000000 36 retouch multi 0 :: iop 14
00100000000 -> 14
00000000000 37 spots multi 0 :: iop 13
00100000000 -> 13
00000000000 38 denoiseprofile multi 0 :: iop 10
00100000000 -> 10
00000000000 39 rawdenoise multi 0 :: iop 7
00100000000 -> 7
00000000000 40 hotpixels multi 0 :: iop 6
00100000000 -> 6
00000000000 41 cacorrect multi 0 :: iop 5
00100000000 -> 5
00000000000 42 watermark multi 0 :: iop 69
00100000000 -> 69
00000000000 43 borders multi 0 :: iop 68
00100000000 -> 68
00000000000 44 splittoning multi 0 :: iop 62
00100000000 -> 62
00000000000 45 vignette multi 0 :: iop 61
00100000000 -> 61
00000000000 46 soften multi 0 :: iop 60
00100000000 -> 60
00000000000 47 grain multi 0 :: iop 56
00100000000 -> 56
00000000000 48 highpass multi 0 :: iop 55
00100000000 -> 55
00000000000 49 lowpass multi 0 :: iop 54
00100000000 -> 54
00000000000 50 lowlight multi 0 :: iop 44
00100000000 -> 44
00000000000 51 bloom multi 0 :: iop 37
00100000000 -> 37
00000000000 52 colormapping multi 0 :: iop 36
00100000000 -> 36
00000000000 53 colorize multi 0 :: iop 34
00100000000 -> 34
00000000000 54 graduatednd multi 0 :: iop 22
00100000000 -> 22
00000000000

**Comment by TurboGit** [comment] 2019-11-15 07:16
No it does not. You said you activate only sharpen and then you list 54 iop entries.

And you didn't say what is the wrong order compared to 2.6.2.

**Comment by chhil** [comment] 2019-11-15 07:30
I will leave it to the OP person to sort it out. I was merely trying to help with the formatting :)

**Comment by vsz1lu** [comment] 2019-11-15 07:42
@TurboGit 

> IIUC the only module activated is sharpen?
Yes!

> What is the order of the modules in 2.6.2?
I can't check it's now.

> What is the order of the modules in 3.0.0rc1?
As You see on the screenshots.

**Comment by vsz1lu** [comment] 2019-11-15 07:44
@junkyardsparkle 

> Is this possibly related to #3270?

Yes!!!

**Comment by TurboGit** [comment] 2019-11-15 07:52
> As You see on the screenshots.

I don't see the order for sharpen in the screen shot or missed it in the 10 screenshots !

**Comment by vsz1lu** [comment] 2019-11-15 09:19
@TurboGit 
in first look it's not a bug but maybe a bigger problem in the using after upgrade from 2.6. i'll makeing complex real world tests in this weekend, today i'm working in a real darkroom :)

**Comment by parafin** [comment] 2019-11-15 10:14
@vsz1lu, are comparing the order of modules on the left? That's not the iop order, read the manual.

**Comment by leclercj** [comment] 2019-11-15 16:07
@vsz1lu, I had a look at http://www.vargaszilard.hu
I'm unsure about this specific issue, but what I'm sure is that your pictures are beautiful. Very great job! Good to see that you're using darktable in your workflow. I'm sure that your feedback & suggestions will be valuable to improve darktable further.

**Comment by vsz1lu** [comment] 2019-11-15 19:30
@parafin 
ok, i'll don't miss! but something is not working properly. there are visible differences between 2.6.2 and 3.0.0rc1 uncompressed tiff export with same machine, source, sidecar, icc profiles - not just the preview. i'll come back with full test in this Saturday.

@leclercj 
thank you very much! darktable is a very creative and intuitive application with great freedom so perfect for artistic work and maybe acceptable in a real professional workflow too. this is my the only one image processor for me in the last ~6 years (i make just minor polishing in gimp) - so great honor for me if i can help with anything. i have same smaller/bigger idea for the future, but i don't want frustrating the dev team before the 3.0.0 :)

**Comment by hpmickey** [comment] 2019-11-17 08:51
Hi, I believe that I have something related to OP, after upgrade from 2.6.3 to 3.0.0rc1:
Any re-exported image shows shift in hue - greens are more yellowish, sky seems to be more bluish (touch of purple is missing). Camera was Sony A7.
I uploaded an example to dropbox: [DT-2.6.3-to-3.0.0rc1-different-color-response.7z](https://www.dropbox.com/s/p8yb1b8s7fo9k4d/DT-2.6.3-to-3.0.0rc1-different-color-response.7z?dl=0)
- _DSC04496.ARW_ - source raw file
- _DSC04496.ARW.xmp_ - edited in 2.6.3
- _DSC04496dt.jpg_ - exported in 2.6.3
- _DSC04496_01.ARW.xmp_ - Ctrl+D in 3.0.0rc1
- _DSC04496dt_01.jpg_ - exported in 3.0.0rc1

It would work the same way without creating a duplicate. I created it just for comparison's sake. If there were no iop ordering problem, it would look more like the enhanced color matrix was affected by the upgrade. I will try to go back to 2.6.3 and make an edit with enhanced color matrix and base curve, and then repeat the upgrade.

**Comment by vsz1lu** [comment] 2019-11-17 21:25
@hpmickey 

Yes, your sample have more visible differences than mine new tests.

Layerd in GIMP with 'difference' option, the lower adjust by "levels" with Auto Input Levels: 
![DSC04496dt_dif](https://user-images.githubusercontent.com/57588193/69014275-d6abb180-0988-11ea-815c-08fbc3b9d06b.jpg)

**Comment by junkyardsparkle** [comment] 2019-11-17 22:37
It's not quite clear exactly what's being reported here. The following things are known/expected:
 1. the default appearance of an image *newly* imported (no history in XMP) into 3.0 will be different from the default appearance of an image imported into 2.6. The most obvious reason is that in 2.6, a basecurve was always applied, and was positioned (wrongly) before the input color profile module. In 3.0 there's an option to *not* apply the basecurve on import, and even if it *is* applied, it will be in a different position in the processing order. It's possible that there could be other more subtle color differences due to the new working color spaces etc, so even moving basecurve back to its original position might not give identical color (I haven't tried, I no longer have any images in my database using that configuration, because, for the 16MP Micro Four Thirds sensors at least, it sucks).
1. Creating in 3.0 a "duplicate" of an image with a legacy history stack uses the new default ordering for the modules involved. This means it is not a literal duplicate, and IMHO conflicts with what a user might reasonably expect, but that's how it works right now. This is discussed in #3270.
 1. The case of importing a 2.6 image with its history into 3.0... this should give essentially the same processing. I doubt if it's expected to always give 1:1 identical output to exporting the same image/history in 2.6, due to the color space changes mentioned above, but somebody with a deeper knowledge of that would have to comment (I haven't tested myself, because there's nothing about 2.6 color that I want to replicate :roll_eyes:)

So, with that, hopefully it can be clarified as to which of those points this issue is related to, and whether it's a report of an unexpected behavior, or a request for a known behavior to be changed...

**Comment by leclercj** [comment] 2019-11-17 22:48
My analysis of @hpmickey data:
In dt2.6.3, "input color profile" was done after "local contrast". After migration in dt3.0, they appear swapped:  "input color profile" is now before "local contrast"
If I manually change the order back to the original, the color bias gone away.

**Comment by junkyardsparkle** [comment] 2019-11-17 22:59
> In dt2.6.3, "input color profile" was done after "local contrast". 

I don't think the current ("bilat") local contrast module was ever on the other side of input profile... are we talking about the old deprecated one with confusingly same name?

**Comment by leclercj** [comment] 2019-11-17 23:18
@junkyardsparkle, you're right. I made a confusion between "bilat" (used here) and "bilateral"
Then this is not an iop order issue. The order are the same with dt2.6.3 and dt3.0 in this example.

**Comment by vsz1lu** [comment] 2019-11-17 23:20
Hi all, I'm coming back with the complex upgrading test in real use - samples above.

Firstly the output test looks like passed in the common non-professional using. In professional area just so-so. There are many difference between the outputs after upgrading  - however it's undetectable or hardly visible with naked eye (expected the crossed leg girl). 

I think the engine not need polishing for making same output as earlier version. Darktable is not made for very precise scientific image processing. But! You must warning the user any way (On/Off in the settings) when opening an early edited image. It's a simple elegant solution - when this issue is real problem of course. 

Here is the test
--------------------------

Testing environment:

Intel® Core™ i5-3330 CPU @ 3.00GHz × 4
GeForce GTX 1050/PCIe/SSE2
DELL U2413 (calibrated)
Wacom Bamboo tablet
Samsung SSD drive in good condition

Ubuntu 19.10
GNOME 3.34.1
darktable 2.6.2+13 (without OpenCL)
darktable 3.0.0rc1 (without OpenCL)
AdobeRGB compatible color profil
Camera specific color profils (picture control iccs by Nikon) 

GIMP 2.10.14 (for comparing)

Inputs:
10 sample picture with different sources: Nikon D7000 and Nikon D800 raw images + linear raw tiff from 2400DPI 16bit scanned medium format b/w negatives. The samples shooted for several subjects in several lightning conditions with.

Outputs:
Uncompressed 16bit tiff in AdobeRGB compatible color space

Preparing:
Taking up some picture and developing some ways, whats I'm recently using in my workflow. I used custom input color profiles (once time enhanced color matrix), my own base dt styles. I made fine adjustments, retouch works, etc - as every day. Some shot need more polishing, but I think it's real representative work. 

Running the test:
1, exported the developed images from dt 2.6.2+13
2, make backup from /home/user/.config/darktable
3, new install of dt 3.0.0rc1 - build from source and make
4, start dt 3.0.0rc1 from terminal, ok-ok for the upgrading database
5, export the samples (no opening in darkroom, just export)
6, remove the actual config and restore 2.6.2+13 form the backup
8, start dt 2.6.2+13 and export the samples again for control

Measuring:
1, open the samples in GIMP and compare by eye
2, layering the outputs from same source: first layer is the first export second is the second in "difference" layer mode
3, flatten the images and apply 'levels' by clicking the Auto Input Levels button.
4, make 1-3 step with the first and the third export for control

The result:

All control test 100% passed: the first and third export from dt 2.6.2+13 totally same.

dt 2.6.2 vs. dt 3.0.0rc1:

1/10:
It's a scanned b/w modern negative for professional use (ILFORD Delta 100). No difference, the outputs is equal pixel-by pixel. I used just the 'base curve'.
![190000-B18511_dif__](https://user-images.githubusercontent.com/57588193/69015298-e62ff800-0992-11ea-9983-a41a025dd2f2.jpg)

2/10
It's a cheap b/w negative (Fomapan 100) from a broken magazine. I used the 'shadow and highlights' module too. The difference is really undetectable by eye, and I made very hard adjustment on the dif image for visualising.
![190000-B17506_dif__](https://user-images.githubusercontent.com/57588193/69015408-d49b2000-0993-11ea-8194-344bcb7dc96c.jpg)


3/10
Nikon D7000. This sample have the most difference: easily visible by eye. I think it's unacceptable result for printed artworks. I used an additional 'level' with mask to burning the model's lower area.
![124026-D34683_dif__](https://user-images.githubusercontent.com/57588193/69015555-5c355e80-0995-11ea-8b53-08d32dcb6713.jpg)

4/10
Nikon D800. This once have got the built-in enhanced color profile. I', very-very rear using it, only for b/w. The difference is very slightly visible by naked eye, but acceptable for me.
![191273-D41043_dif__](https://user-images.githubusercontent.com/57588193/69015653-4a07f000-0996-11ea-9165-830b0b720cfd.jpg)

5/10
Nikon D800. I think it's ok in real common use, as the all others listed above.
![190642-D45581_dif__](https://user-images.githubusercontent.com/57588193/69015683-acf98700-0996-11ea-8912-d8a4752539ed.jpg)

6/10
Nikon D800
![190627-D45011_dif__](https://user-images.githubusercontent.com/57588193/69015694-d0bccd00-0996-11ea-9aa6-238c72b9d9af.jpg)

7/10
Nikon D800
![192778-D40066_dif__](https://user-images.githubusercontent.com/57588193/69015706-0366c580-0997-11ea-9be6-5bd41a1a1209.jpg)

8/10
Nikon D800
![193042-D40026_dif__](https://user-images.githubusercontent.com/57588193/69015710-15e0ff00-0997-11ea-8159-c15d35406de2.jpg)

9/10
Nikon D800
![194313-D47046_dif__](https://user-images.githubusercontent.com/57588193/69015715-285b3880-0997-11ea-81d3-1ab2fc0ad07a.jpg)

10/10
Nikon 800
![194661-D47335_dif__](https://user-images.githubusercontent.com/57588193/69015723-3a3cdb80-0997-11ea-985f-cb104827dfc0.jpg)

**Comment by vsz1lu** [comment] 2019-11-17 23:30
As I see the difference comes from the iops whats use the Gaussian blur - not for the processing order.

Otherwise the changed order of the modules in the gui when open an old pic is very frustrating. Learning the the new dt is very hard, if I see once time "a" listed, other time "b" listed order. This is the bigger problem, the differences minor of the output is smaller.

**Comment by junkyardsparkle** [comment] 2019-11-18 00:28
Nice. It's good to see that even the more colorful shots were within reason... just to clarify, was 'base curve' used on all of these? The place I would expect the most difference is for camera/profile combinations that bad gamut issues using the basecurve in its original place (in my case mostly with dark saturated blue tones). In those cases, to the extent that the color is changed by the new basecurve location, it *should* be *better*... but if somebody has additional processing to correct those issues in an old history, and then creates a "duplicate" with the same processing but different order, I suppose that would be a pathological case.

> As I see the difference comes from the iops whats use the Gaussian blur (edit: + whats use local laplacian filter too) - not for the processing order.

IIRC there was a consolidation during the last dev cycle of some different Gaussian algorithms to a single one amongst modules, so not too surprised there.

**Comment by junkyardsparkle** [comment] 2019-11-18 01:38
>Yes, your sample have more visible differences than mine new tests.
> Layerd in GIMP with 'difference' option, the lower adjust by "levels" with Auto Input Levels:

That looks suspiciously as though you used the JPEGs for diffing... :-)

**Comment by vsz1lu** [comment] 2019-11-18 11:29
@junkyardsparkle 
I not used base curve at all, maybe 50% (I can't check at now).
When I'm working with iccs from Nikon PC I never use. - it's contains the base curve, but need unbreak. In my recent work I only and only use self adjusted camera specific basecurve when I'm working with bulit-in matrixs (rear used) and AdobeRGB compatible as input color profil unbreaked linear: 0.01 / gamma: 0.45. AdobeRGB as input is far better for portraits and bodys than the factory picture control icc and lightyears far better than bulit-in matrixes. For example the 10/10 have got Nikon Standard (D800) as input and there are some unwanted yellow shift on the shine part of the face what's need more fine pimping to correct. The 8/10 made with AdobeRGB + D800 base curve and I got better result in less working time, however I used a plastic foil as diffusor in the master light what's make complex shift in the colors originali.

Yes, your right! The fine differences comes from the jpeg quantzion but the shift in the green grass visible by eye too.

**Comment by aurelienpierre** [comment] 2019-11-18 14:49
> As I see the difference comes from the iops whats use the Gaussian blur (edit: + whats use local laplacian filter too) - not for the processing order.

Looking at the adjusted diffs, the halos going along edges indicate issues with bilateral and possibly gaussian things. Local laplacian filter uses a gaussian reduction too. All that is possibly linked to #3421

**Comment by junkyardsparkle** [comment] 2019-11-18 20:14
> All that is possibly linked to #3421

Even though OpenCL wasn't used?

> darktable 2.6.2+13 (without OpenCL)
> darktable 3.0.0rc1 (without OpenCL)

**Comment by aurelienpierre** [comment] 2019-11-18 20:22
Yeah, the code affected was the CPU version of bilateral filters. d4156db4a3ebc8df7f872eb04bcef6530a2f4f70 (merged this evening) should at least fix part of the problems described here.

**Comment by hpmickey** [comment] 2019-11-18 23:05
> @hpmickey My wild guess is that using the 'color zones' module for hue shifting in two different working color spaces could easily produce the actual color difference.
> 
> UPDATE: Specifically, it looks like 'color zones' is applying that hue shift more strongly in 3.0. (@edgardoh Is this expected?)

@junkyardsparkle , you are right. I tried to bisect the problem before reading your answer. Started with the input color profile (enhanced matrix) only, both 2.6.3 and 3.0.0rc1 exported identical jpegs. Then input color profile + base curve, again identical output. Then added color zones with my preset, and green grass turned yellowish. Your theory confirmed :)

I can easily adapt to this (however can't speak for other users).

**Comment by junkyardsparkle** [comment] 2019-11-19 02:17
> Your theory confirmed 

Oh, that part wasn't theory, it was empirically tested. ;-) As to *why* there's a difference, *that* I can only speculate about; hopefully @edgardoh, who authored the changes to the module, can take a look at it. I did one more quick test of CPU vs. GPU, and it doesn't change anything, same difference between versions with both.

**Comment by leclercj** [comment] 2019-11-19 08:23
dt2.6 was using 'color zone' version 3 and dt3.0 is now upgraded to 'color zone' version 4
Looking at the 'color zone' code, I do not see the old 'strength' parameter used during the migration process. Isn't it a problem here ?

```
  if(old_version == 3 && new_version == 4)
  {
    typedef struct dt_iop_colorzones_params3_t
    {
      int32_t channel;
      float equalizer_x[3][DT_IOP_COLORZONES_BANDS], equalizer_y[3][DT_IOP_COLORZONES_BANDS];
      float strength;
    } dt_iop_colorzones_params3_t;

    const dt_iop_colorzones_params3_t *old = old_params;
    dt_iop_colorzones_params_t *new = new_params;
    new->channel = old->channel;

    for(int b = 0; b < DT_IOP_COLORZONES_BANDS; b++)
    {
      for(int c = 0; c < 3; c++)
      {
        new->curve[c][b].x = old->equalizer_x[c][b];
        new->curve[c][b].y = old->equalizer_y[c][b];
      }
    }
    for(int c = 0; c < 3; c++)
    {
      new->curve_num_nodes[c] = DT_IOP_COLORZONES_BANDS;
      new->curve_type[c] = CATMULL_ROM;
    }
    new->strength = 0.0;
    new->mode = DT_IOP_COLORZONES_MODE_OLD;
    return 0;
  }
```

**Comment by junkyardsparkle** [comment] 2019-11-19 08:46
Well, if I raise that slider to zero in 2.6, I get essentially the same result as 3.0, so... I would say you found the issue... and I feel stupid for not noticing that before, so I'll go to sleep now. :-)

**Comment by leclercj** [comment] 2019-11-19 10:50
@junkyardsparkle , its a team work. I'd never have noticed that without your detailed analysis and tests

**Comment by johnny-bit** [comment] 2020-12-30 20:36
Well, with d4156db in tree as well as #3487 fixing color zones issue it might mean that problems are "gone"... Closing since we've had couple of releases and hopefully not as many problems with edits leaking.

**Closed by johnny-bit** 2020-12-30 20:36 UTC
Labels: no-issue-activity
