### ISSUE TITLE
Darktable crashes when starting

### ISSUE THREAD

**Issue by Penguin1950** [darktable-org/darktable#12302] opened 2022-08-11 19:50 UTC
darktable.exe caused an Access Violation at location 00007FFFAD7D458E in module igdrcl64.dll Reading from location 0000000000000464.
The PC is MS Surface.  I see this reported in many places but no answer that I can find.  I have uninstalled my older version and installed v4.0.  Same problem.

**Introduction**
_This section is provided for information only. Please delete if no longer required._

Before raising a bug/issue please check that it has not already been reported
by searching https://github.com/darktable-org/darktable/issues.

Please be aware that most developers work on this project in their free time.
The more information you can provide in the initial report the quicker we can help.
Therefore please help by being as accurate and concise as possible!

For further information, please see https://github.com/darktable-org/darktable/wiki#reporting-bugs.
---------------------------------------------------------------

**Did you buy darktable from an application store ?**

_darktable is free but selling it is technically allowed by the license, at the condition that 
the seller provides extra services and assistance to users. 
If you bought darktable on a store, it was not from the darktable team but from a third party.
Support is therefore the sole responsibility of the third-party seller, 
and the darktable team will not offer free support for licenses paid to a third-party.
Please contact your seller, assistance is part of your after-sale rights._

**Describe the bug/issue**

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**
_(if applicable)_

**Screencast**
_(if applicable)_

**Which commit introduced the error**
_If possible, please try using `git bisect` to determine which commit introduced the issue and place the result here._

_A bisect is much appreciated and can significantly simplify the developer's job._
_HowTo: https://github.com/darktable-org/darktable/wiki#finding-bug-causes and https://www.youtube.com/watch?v=D7JJnLFOn4A_

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : e.g. 3.5.0+250~gee17c5dcc
* OS                : e.g. Linux - kernel 5.10.2 / Win10 (Patchlevel) / OSx
* Linux - Distro    : e.g. Ubuntu 18.4
* Memory            : 
* Graphics card     : 
* Graphics driver   : 
* OpenCL installed  : 
* OpenCL activated  : 
* Xorg              : 
* Desktop           : 
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  : 

**Additional context**
_Please provide any additional information you think may be useful, for example:_

 - Can you reproduce with another darktable version(s)? **yes with version x-y-z / no**
 - Can you reproduce with a RAW or Jpeg or both? **RAW-file-format/Jpeg/both**
 - Are the steps above reproducible with a fresh edit (i.e. after discarding history)? **yes/no**
 - If the issue is with the output image, attach an XMP file if (you'll have to change the extension to `.txt`)
 - Is the issue still present using an empty/new config-dir (e.g. start darktable with --configdir "/tmp")? **yes/no**
 - Do you use lua scripts?
   - What lua scripts start automatically?
   - What lua scripts were running when the bug occurred?

**Comment by MStraeten** [comment] 2022-08-12 05:36
did you check on of the couple of similar issue reports on that?probably duplicate of #12033 and several more issues …

**Closed** 2022-08-12 07:16 UTC
Labels: duplicate

**Comment by Penguin1950** [comment] 2022-08-12 12:11
On my MS surface laptop, I updated all my out of date drivers, including graphics.  DT started working Ok.However on my Desktop, updating the drivers did not work.  I will try the disable opencl command.Sent from my Galaxy
-------- Original message --------From: Martin Straeten ***@***.***> Date: 2022-08-11  23:36  (GMT-06:00) To: darktable-org/darktable ***@***.***> Cc: Penguin1950 ***@***.***>, Author ***@***.***> Subject: Re: [darktable-org/darktable] Darktable crashes when starting (Issue #12302) 

did you check on of the couple of similar issue reports on that?probably duplicate of #12033 and several more issues …

**Comment by Penguin1950** [comment] 2022-08-12 13:45
Where do I find the darktable launcher??Brad CargillSent from my Galaxy
-------- Original message --------From: Nicolas Auffray ***@***.***> Date: 2022-08-12  01:16  (GMT-06:00) To: darktable-org/darktable ***@***.***> Cc: Penguin1950 ***@***.***>, Author ***@***.***> Subject: Re: [darktable-org/darktable] Darktable crashes when starting (Issue #12302) 
Closed #12302 as not planned.

**Comment by Nilvus** [comment] 2022-08-13 10:28
@Penguin1950: this place is not a help support. It's only about darktable issues (those than can be fixed in darktable code). This is not the case here. Better use if needed pixls.us forum.

**Comment by Penguin1950** [comment] 2022-08-15 12:33
Thanks.Disabling opencl did fix my issue.This problem with opencl and windows 10 is clearly a problem with darktable code.  I hope you are working on a coded solution within DT.Maybe it's not your problem, but you certainly have a better chance of influencing the DT coders than I do.Sent from my Galaxy
-------- Original message --------From: Nicolas Auffray ***@***.***> Date: 2022-08-13  04:29  (GMT-06:00) To: darktable-org/darktable ***@***.***> Cc: Penguin1950 ***@***.***>, Mention ***@***.***> Subject: Re: [darktable-org/darktable] Darktable crashes when starting (Issue #12302) 
@Penguin1950: this place is not a help support. It's only about darktable issues (those than can be fixed in darktable code). This is not the case here. Better use if needed pixls.us forum.

**Comment by ptilopteri** [comment] 2022-08-15 14:47
no, not dt code.  it's problem with windows opencl, but you are welcome to 
submit pr's to correct the failure.

**Comment by Penguin1950** [comment] 2022-08-15 21:02
start cmd
start darktable.exe --disable-opencl

I created a .bat file with the content above.  I run it in a shortcut on the desktop.   DT starts with no errors when I start it this way.

Regarding your previous comment, stating that it is a Windows problem not a DT problem.    Maybe so,  but unless this is causing problems in many other programs, it is doubtful that MS will change their code to please DT.   It's the elephant vs the mouse.  (it's a myth that elephants are afraid of mice).

**Comment by ptilopteri** [comment] 2022-08-15 21:12
dt is a free and open source application.  solving the windows
problem with opencl will *only* happen if someone desires that 
avenue and has the skills, time and devotion to make it happen.

if you can provide that, I am sure that you will make some people
happy.  if not, how is this to be solved?  remember that there are
very few (I know of one) developers who use windows and then
only to provide packaging for installation.
