### ISSUE TITLE
Filmrolls display the bottom, not top of the list

### ISSUE THREAD

**Issue by johans3** [darktable-org/darktable#2501] opened 2019-05-02 06:06 UTC
**Describe the bug**
if I double-click a filmroll in lighttable, just the bottom line of all my pictures is being displayed

**To Reproduce**
1. Double click a filmroll in lighttable 
2. You'll see just the bottom line of all pictures
3. Scroll up to see all pictures of the filmroll

**Expected behavior**
Often my filmrolls contain at least 50+ pictures so I need to scroll up all times just to display all pictures. I want to retouch my pictures from beginning not bottom. 
It's a returning issue -day by day-,  the big itself small so hopefully easy to remove. 

**Platform (please complete the following information):**
 - OS: Mac 10.11
 - Version Dt 2.6.2

**Comment by TurboGit** [comment] 2019-05-02 11:31
Cannot reproduce so probably fixed in 2.7.

**Closed by TurboGit** 2019-05-02 11:31 UTC

**Comment by johans3** [comment] 2019-05-02 18:41
If you have many pictures in your film roll. 
By a dozen or 50 Dt displays the list correctly: from the beginning. 

Add soon as you've more items in your list 100 - 500, Dt shows the very bottom line of the list at the top of the lighttable list.

**Comment by AlicVB** [comment] 2019-05-02 19:12
yep, I confirm I've fixed it some time ago (only for master)
