### ISSUE TITLE
git master 7233d8bdb build fails, libavif

### ISSUE THREAD

**Issue by ptilopteri** [darktable-org/darktable#6590] opened 2020-10-20 19:26 UTC
openSUSE Tumbleweed 20201019
NVIDIA GF106 [GeForce GTS 450], 390.138
OpenCL loaded but not available
i7 12-core 36GB
kernel 5.8.14-1-default

git build fails in directory /data/dt-build/:

/data/dt-build/darktable/src/common/imageio_avif.c: In function ‘dt_imageio_open_avif’:
/data/dt-build/darktable/src/common/imageio_avif.c:141:12: error: too many arguments to function ‘avifDecoderParse’
141 |   result = avifDecoderParse(decoder, &raw);
|            ^~~~~~~~~~~~~~~~
In file included from /data/dt-build/darktable/src/common/imageio_avif.c:22:
/usr/include/avif/avif.h:707:12: note: declared here
707 | avifResult avifDecoderParse(avifDecoder * decoder);
|            ^~~~~~~~~~~~~~~~
/data/dt-build/darktable/src/common/imageio_avif.c: In function ‘dt_imageio_avif_read_color_profile’:
/data/dt-build/darktable/src/common/imageio_avif.c:309:12: error: too many arguments to function ‘avifDecoderParse’
309 |   result = avifDecoderParse(decoder, &raw);
|            ^~~~~~~~~~~~~~~~
In file included from /data/dt-build/darktable/src/common/imageio_avif.c:22:
/usr/include/avif/avif.h:707:12: note: declared here
707 | avifResult avifDecoderParse(avifDecoder * decoder);
|            ^~~~~~~~~~~~~~~~
gmake[2]: *** [bin/CMakeFiles/lib_darktable.dir/build.make:1700: bin/CMakeFiles/lib_darktable.dir/common/imageio_avif.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:2379: bin/CMakeFiles/lib_darktable.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2

**Comment by Nilvus** [comment] 2020-10-20 19:45
duplicate of  #6530

**Comment by ptilopteri** [comment] 2020-10-20 21:00
I have been building dt 3-4 times a day until 7233d8bdb
w/o a failure and have not updated *avif*
libavif-devel-0.8.2-1.1.x86_64                Tue 20 Oct 2020 10:41:29 AM EDT
libavif7-0.8.2-1.1.x86_64                     Tue 20 Oct 2020 10:41:18 AM EDT
libavif6-0.8.1-1.2.x86_64                     Fri 28 Aug 2020 11:49:24 PM EDT

what changed today?

**Comment by ptilopteri** [comment] 2020-10-21 01:47
removing libavif-devel provides successful build, but does
not explain the ability to successfully build yesterday with
libavif-devel installed.  the avif api and abi would not have
changed.  ??? 

remember I am quite unknowledgeable, and somewhat aged.

**Closed** 2020-10-21 12:10 UTC
