### ISSUE TITLE
RC1: Lens correction adds blue lines

### ISSUE THREAD

**Issue by pphotography** [darktable-org/darktable#3503] opened 2019-11-21 00:46 UTC
**Describe the bug**
Using DT 3.0.0rc1~git11.dc641cdc9 on Ubuntu 18.04 I detected a blue line at the bottom and right border in the image after applying lens correction for the lens
Maker: Pentax
Model: Super-Takumar 55mm f/1.8

- Tested with other images from other cameras and PNGs
- Tested with selecting other APS-C cameras (Nikon D3100 and others) than my Pentax K-50

![lens01](https://user-images.githubusercontent.com/49001045/69290223-8db16280-0bff-11ea-88d7-b3db9c7638cd.png)

This blue line seems to be a part of the image and is not only in the user interface. This is a screenshot with a blur using the lowpass filter:
![lens02](https://user-images.githubusercontent.com/49001045/69290298-c9e4c300-0bff-11ea-98f7-4bc0ebcae16e.png)

Lens correction off:
![lens03](https://user-images.githubusercontent.com/49001045/69290324-e97beb80-0bff-11ea-8ae1-b242722f3ba8.png)

This did not happen with 2.6.2, lensfun version should be the same. Tried lensfun-update-data after detecting this without any new data.
Last commit on lensfun on the slr-pentax.xml was in october.

**Comment by pphotography** [comment] 2019-11-21 00:52
Update: Happened again with the lensed:

- Pentacon, Pentacon 50mm f/1.8 auto multi coating
- Tamron, Tamron 18-200mm f3.5-6.3 Di III VC

Shape and position of the blue areas change when selecting different focal lengths

**Comment by junkyardsparkle** [comment] 2019-11-21 08:30
There's nothing in the Lensfun profiles themselves that could cause this, so it won't be fixed there. Does this happen the same with OpenCL enabled and not enabled?

**Comment by pphotography** [comment] 2019-11-21 09:45
You're right, happens only with OpenCL enabled.
[clinfo.txt](https://github.com/darktable-org/darktable/files/3873984/clinfo.txt)
Got a Geforce GTX 1060 6GB
NVIDIA-SMI 440.31       Driver Version: 440.31       CUDA Version: 10.2

**Comment by junkyardsparkle** [comment] 2019-11-21 20:56
Hmm. I don't get this issue using the 430.40 release of the Nvidia drivers and GTX 1050. This looks different from the other cases where the "scale" value was being slightly miscalculated using OpenCL with certain version of Mac drivers. Do any of the following changes in the lens correction module affect it?

* set corrections to "only distortion" or "only TCA"
* increase the value of the "scale" slider

**Comment by pphotography** [comment] 2019-11-21 23:46
These options only changed the geometry of the black corners, see:

[2019-11-22 00-37-41.zip](https://github.com/darktable-org/darktable/files/3877259/2019-11-22.00-37-41.zip)
(at 01:35 I disable OpenCL, my screen recorder didn't record that)

**Comment by junkyardsparkle** [comment] 2019-11-22 00:14
I can't really see if/when/where the blue line appears in that video, might need a transcript. :-)

Basically, when adjusting the scale so that the black borders are visible, is the blue appearing between the curved image edge and the black border, or between the black border and the edge of the preview window? If the second case, then I have no guesses... just another weird OpenCL implementation bug, probably.

**Comment by jenshannoschwalm** [comment] 2019-11-22 16:53
Can't reproduce here and also can't see on the video ...

**Closed** 2021-01-20 01:07 UTC
Labels: no-issue-activity
