### ISSUE TITLE
<Panasonic DC-S5M2>

### ISSUE THREAD

**Issue by JaviMat** [darktable-org/darktable#13611] opened 2023-02-11 12:57 UTC
Whole raw sample set (all crops 1:1, 4:3, 3:2, 16:9 65:24, 2:1 and high resolution mode)  uploaded under CC0 license to
https://raw.pixls.us/

**Comment by Nilvus** [comment] 2023-02-11 15:46
No need to have 2 issues. As a duplicate of #13511, I close that one. Thanks for the samples.

**Closed by Nilvus** 2023-02-11 15:46 UTC
Labels: duplicate, scope: camera support
