### ISSUE TITLE
Thumbnail overlays → Hidden after dt restart

### ISSUE THREAD

**Issue by timur-davletshin** [darktable-org/darktable#5435] opened 2020-06-12 16:18 UTC
1. Linux, 64 bit, latest git
2. Click "click to change type of overlays shown on thumbnails" (star icon in right-top corner) and choose, let's say, "permanent overlays" — overlays shown as expected.
3. Restart dt, notice that overlays are no longer visible. Selected menu option remains active.

**Comment by AlicVB** [comment] 2020-06-12 17:03
I can't reproduce of course, otherwise this feature would be useless...
Can you share more things to reproduce the issue ? In which mode are you in lighttable (filemanager, zoomable lighttable, culling, full preview) ? Exact version of dt, ...
Thanks

**Comment by timur-davletshin** [comment] 2020-06-12 17:17
file manager mode

**Comment by timur-davletshin** [comment] 2020-06-12 17:29
AlicVB, I tried with new config and I find that having header like mine (see below) is crucial (click that triangle till you get header with hidden buttons)
![header](https://user-images.githubusercontent.com/65483426/84530118-44377a80-aceb-11ea-95b8-9cd36b20324d.png)

**Comment by AlicVB** [comment] 2020-06-12 17:44
ah ah indeed, that was a crucial info.
I can reproduce now. I'll have a look

**Comment by AlicVB** [comment] 2020-06-12 18:44
@Mark-64 : I've found the culprit, it's from a part of your code... and I have no idea how to solve it : 
in fact, if we don't show the top toolbar (with the buttons), `darktable.gui->icon_size = 0` and as we rely on this to get the font and icon size for thumbnails...

That's due to the fact that the icon_size is computed once toolbar buttons are realized, which is never the case if the toolbar is hidden...

As potentially, we can start dt with every panels closed, I don't see how we can get this value...

Can you have a look ? Thanks

**Comment by Nilvus** [comment] 2020-06-15 10:59
@timur-davletshin: could you try on last master from this day to see if you can reproduce?

**Comment by Nilvus** [comment] 2020-06-15 11:08
@Mark-64: could you check that (maybe you miss @AlicVB question)? Your help would be appreciated here. Thanks.

**Comment by timur-davletshin** [comment] 2020-06-15 11:11
@Nilvus still reproducible in darktable 3.1.0~git2164.a64940338

**Comment by Nilvus** [comment] 2020-06-15 11:18
> @Nilvus still reproducible in darktable 3.1.0~git2164.a64940338

Yes, I delete my comment finally (I have not understand your PR at first as I don't reproduce it because understood that needed header bar and collapse border arrows). In fact, that's not that, it's reproducible with only header shown but header toolbar (with prefs, help, group icons...) is hidden. And then I have reproduce it.

@timur-davletshin: you should reopen your issue, you close it.

**Comment by timur-davletshin** [comment] 2020-06-15 11:49
@Nilvus my bad, haven't noticed how I closed it )))

**Comment by Nilvus** [comment] 2020-06-15 11:52
> @Nilvus my bad, haven't noticed how I closed it )))

Simply, when you click on close and comment instead of comment

**Comment by Mark-64** [comment] 2020-06-15 13:08
I will have a look later today

**Comment by AlicVB** [comment] 2020-06-15 16:13
@Mark-64 : if that can help you, I have think to 3 solutions here : 
1. Falling back to some other basing method if the first one fail (based on bauhaus sizes, for example) but that may be strange if we show the toolbar at some point and scroll : we'll end with different sizes in different thumbnails...
2. Always use other basing method. In this case, we may want to size top/bottom icons the same way. But not sure that this will fit with label/combobox heights)
3. Use a dirty trick by forcing show/hide a label if we fail...

After some reading, it seems that the icon size of the top icons is based on the height took by a label with default font-size. After that you remove css margins, etc...
But I've not found a gtk way to get height of a widget given the font-size...

**Comment by Mark-64** [comment] 2020-06-15 16:47
@AlicVB 
After some investigations, I think a change of approach is necessary. 
It was nice to have an auto synch based on the real allocated size of the panel icons, but unfortunately there might not be any panel icons drawn.
I am thinking to link a callback to the size-allocate event of the main #thumbtable_filemanager (or filmstrip / culling / zoom). There I can interrogate a css property (min-height) set in em units on purpose to match the panel icon size.
It would no longer be an auto synch, meaning it would be responsibility of the css theme to set the size in synch. But it should work in all cases.

**Comment by AlicVB** [comment] 2020-06-15 18:13
and after that, you will size the toolbar button with same size or not ? (just to ask, no strong opinion here)

About your proposal, I think it can be simpler and more uniform to base our icon size on the bauhaus font-size which is themable, invariant and always here afaik.
After all if user want bigger size, it's quite logical that we enlarge somehow icons and thumb labels too...

**Comment by Mark-64** [comment] 2020-06-15 19:16
@AlicVB 
Let me try first my idea, I made a draft PR #5481, but I need your help for culling mode

**Closed** 2020-06-17 08:23 UTC
Labels: bug: wip, priority: high, scope: UI
