### ISSUE TITLE
Duplicate management : Naming and Export

### ISSUE THREAD

**Issue by Praveen-Rai** [darktable-org/darktable#4115] opened 2020-01-14 20:03 UTC
When exporting duplicates, Darktable does not consider the duplicate name. It just keeps appending numbers to the original file name. For instance if i have image XYZ.jpg, and i create a duplicate named "ColorGraded" and another duplicated named "BW" and export, the new images will be XYZ_01, XYZ_02.jpg. It's difficult to figure out from the name of the exported images, which of the duplicate was used. 

The proposal is to append duplicate name as well to the exported image, from previous e.g. the exported images must be XYZ.jpg, XYX_ColorGraded.jpg & XYZ_BW.jpg.

Also, there always have to be default names for the duplicates. Right now it comes up blank, simple numbering/Lettering might work. The user can always modify to suite it.

Note : We might have to limit the size of duplicate title, to avoid too long names.

**Comment by aurelienpierre** [comment] 2020-01-14 20:49
Good idea.

**Comment by parafin** [comment] 2020-01-15 10:06
Duplicate name should be made available as a variable IMHO, not automatically appended in all cases.

**Comment by Praveen-Rai** [comment] 2020-01-15 19:01
> Duplicate name should be made available as a variable IMHO, not automatically appended in all cases.

Yes, but as soon as you create a duplicate it must be assigned with some name. That's what i meant with a default sequence name. One can always change it.

**Comment by Egocentrix** [comment] 2020-01-16 21:32
Duplicate names seem to be written to an xmp 'Title tag'. It can already be appended to a file name from there as an export parameter, not sure if I would like to have it in the file name by default.

**Comment by elstoc** [comment] 2020-02-16 09:04
I agree with this request. I've also mentioned this in a request of my own (https://github.com/darktable-org/darktable/issues/3816). The problem is that darktable cannot distinguish between exporting a duplicate image and exporting another copy of an image that it's exported previously - it handles both circumstances in the same way. 

So if you export two duplicated images and choose to overwrite on conflict you'll only ever get an export of the last file. A workaround would be to manually populate one of the metadata fields and use that in the exported filename. Longer term this should be its own metadata field, or at least easily viewable and amendable in the lighttable.

@Egocentrix please could you post some instructions as to how you would add this field to an export? Is this tag only populated if a duplicate exists or always?

**Comment by Egocentrix** [comment] 2020-02-18 15:26
The xmp 'Title' field is (afaik) empty by default. It can be set in different ways:
- On import
- The metadata editor module in lighttable
- The duplicate manager. The duplicate name field is the same as the Title tag.

On export, you can use this title by adding '$(TITLE)' in the target path, in the same way that $(FILE_NAME) and other darktable fields can be used.

**Comment by elstoc** [comment] 2020-02-20 20:09
@Egocentrix you seemed to imply in your previous response that there was a default name given to duplicates that was written to a tag automatically. But what you're suggesting is that we manually write something to the existing title field to identify duplicates and then use that to generate the exported filename. Unfortunately I'm already using the title (and description) fields (for the title and description!) and I don't want those included in the filenames.

So I think my suggestion remains: that we have a separate metadata field that can be uniquely assigned to duplicates (it could default to A/B/C so that it doesn't conflict with the existing method that export uses to identify files that have already been exported) but which may be manually amended, for use in file naming, such that it doesn't conflict with the title field.

**Comment by elstoc** [comment] 2020-02-28 16:37
From my investigation of #4385 I note that there is a variable that can be included in the export filename "$(VERSION)". This is an integer that uniquely identifies a duplicate and matches the number at the end of sidecar files. That solves my issue of making sure I have unique filenames.

**Comment by todd-prior** [comment] 2020-03-13 11:18
@elstoc I think this would be useful to have a variable created that reflected the text name given to the duplicate and having it available to append to file exports. Not sure how hard this is but the current usage of having a number while working to keep copies provides no visual clue in the filenames...what will 01 02 03 mean to anyone a year later and also why would there be the possibility to name duplicates if the only place you can see that and make use of it is in the duplicate pane....just my thoughts...I would find this an extremely useful feature if it could be introduced.....

**Comment by elstoc** [comment] 2020-03-13 11:32
I agree. Version number is used for xmp renaming and in the database, and should probably remain for this purpose but an additional "duplicate_desc" field would be better than reusing the existing 'title' field for duplicate names.

**Comment by elstoc** [comment] 2020-03-15 08:48
I'm happy to work on a PR for this if nobody is looking at it already.

**Comment by phweyland** [comment] 2020-03-15 19:13
> Duplicate names seem to be written to an xmp 'Title' tag.

This is not correct for my standpoint. This is a wrong mix of features.

**Comment by elstoc** [comment] 2020-03-16 14:11
To assist in resolving the original request I have created a new metadata field in the above PR, which replaces the use of 'title' in the duplicate manager module. In order to guarantee unique filenames on export this new metadata field can be used in combination with the existing $(VERSION) variable within the export module, as follows

$(FILE_NAME)_$(SHORT_DESCRIPTION-$(VERSION))

This will append the short description to the filename if one exists. If a short description has not been added, the filename will instead be appended with the (integer) version number.

**Closed** 2020-04-18 10:23 UTC
Labels: difficulty: average, feature: enhancement, no-issue-activity, priority: low

**Comment by elstoc** [comment] 2020-04-18 11:29
The merged version of the above PR is slightly different from the solution described above, which becomes...

```$(FILE_NAME)_$(VERSION_NAME-$(VERSION))```

A new variable $(VERSION_IF_MULTI) is also now available, which will be populated with the version number **only if more than one version exists**, else it will be null. This allows the following syntax to append the version number to the filename with a leading underscore only if multiple versions exist:

```$FILENAME$(VERSION_IF_MULTI+_$(VERSION_IF_MULTI))```

i.e. if $(VERSION_IF_MULTI) is empty the leading underscore will also be excluded from the export name.
