### ISSUE TITLE
Unable to import images & folders

### ISSUE THREAD

**Issue by airflow2010** [darktable-org/darktable#16046] opened 2024-01-06 17:00 UTC
### Describe the bug

Since the christmas-version of darktable, I've been unable to import new pictures/folders.

I do this on my existing installation/database, where I can edit/modify the existing pictures without problems.

### Steps to reproduce

1. click "add to library"
2. select a folder which contains new images
3. new images are displayed and are selected in list within the dialogue
4. click "add to library"
5. dialogue disappears, no progress bars, no error-messages
6. instead popup is shown which indicates success "imported 18 images"
7. no images are imported

### Expected behavior

imported images should be found in collection

### Where did you obtain darktable from?

OBS

### darktable version

4.6.0

### What OS are you using?

Linux

### What is the version of your OS?

Ubuntu 23.10

### Are you using OpenCL GPU in darktable?

I dont know

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

things I already tried/checked:

* permissions of the folder containing the images: are correct (read/write for user)
* permissions of the folder containing the config (~/.config/darktable) - here, there were some files with read-only. I set everything to read/write
* I started darktable via the command-line to observe if any error-message was displayed there while the problem is seen. no output could be observed
* Checked if I can modify previously imported files: this works and is persistent

**Comment by ptilopteri** [comment] 2024-01-06 17:12
you might try moving your dt config to see if you have a problem there
  mv ~/.config/darktable ~/.config/Xdarktable

try import on new instance of dt

if it still does not work, reverse the move
  mv ~/.config/Xcarktable ~/.config/darktable

and you are back to before this jumping thru hoops

you can get some idea if where the problem is starting dt from cl as:

   darktable -d all

there are lesser invocations but I do not know which is appropriate, '-d all' will show everyting

**Comment by airflow2010** [comment] 2024-01-06 17:28
Thanks for your ideas.

I tried importing on a new instance of dt by removing the original config-folder like you suggested.

It happens just the same in the new instance - images are not imported. A new darktable config folder is created like it is expected.

I captured the command-line-output resulting from "-d all" like you suggested. I couldn't find any obvious error-messages. Can you have a look please? [darktable-import-fail.log](https://github.com/darktable-org/darktable/files/13850578/darktable-import-fail.log)

**Comment by gi-man** [comment] 2024-01-06 17:29
Are you using the recursive selection? If yes, then this is a known bug already fixed on master.

**Comment by airflow2010** [comment] 2024-01-06 17:33
Yes I am using recursive selection. I could just verify your idea by selecting directly the folder where the images are located - it works now! Thanks.

**Comment by gi-man** [comment] 2024-01-06 18:00
Ok.

Duplicate and fixed on master last week.

#15894

**Closed** 2024-01-08 15:39 UTC
Labels: duplicate, Fixed in master
