### ISSUE TITLE
Seg fault  on Arch linux just after start

### ISSUE THREAD

**Issue by zygmund2000** [darktable-org/darktable#6008] opened 2020-08-17 19:40 UTC
Seg fault  every time after start darktable command after update to 3.2.1
I also removed all old filele from .config/darktable.

To Reproduce

Start Darktable after update to 3.2.1

Platform:

    Darktable Version: 3.2.1
    OS: Arch linux
    OpenCL No
    Intel HD Graphics 4000

Heres's a backtrace it left in my tmp folder
[darktable_bt_RUIIP0.txt](https://github.com/darktable-org/darktable/files/5086437/darktable_bt_RUIIP0.txt)

**Comment by parafin** [comment] 2020-08-17 19:47
This is probably a duplicate of #5761

**Closed by parafin** 2020-08-17 19:47 UTC
