### ISSUE TITLE
Raster masks segfault if ROI size is changed

### ISSUE THREAD

**Issue by aurelienpierre** [darktable-org/darktable#8941] opened 2021-05-12 18:18 UTC
1. Define a crop in crop or crop and rotate or perspective modules,
2. Define a parametric mask in some module,
3. Re-use that mask as a raster mask later in pipe,
4. Disable the cropping module,
5. Witness : 
```
Thread 14 "worker res 0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb37fe640 (LWP 120649)]
dt_iop_image_scaled_copy (buf=buf@entry=0x7ffee1b3e040, src=src@entry=0x7fff6585a040, scale=scale@entry=0.5, width=width@entry=1365, height=height@entry=1982, ch=ch@entry=1)
    at src/common/imagebuf.c:220
220         buf[k] = scale * src[k];
```
`dt_iop_image_scaled_copy` is only called from `src/develop/blend.c` to copy raster masks. My guess is when the ROI size is changed, the raster mask buffer is not flushed and resized accordingly.

**Comment by jenshannoschwalm** [comment] 2021-06-01 18:27
@aurelienpierre i tried for some time to reproduce this issue but couldn't trigger it on todays master neither with OpenCl activated or not. Could you give more instructions for a reproducer, from what you describe it sounds nasty and should be fixed for 3.6

**Comment by johnny-bit** [comment] 2021-06-19 11:35
I tried to reproduce it and honestly I couldn't.

Here's xmp i tried with: notice that module generating raster mask is before and the module using the mask is after crop & rotate - this gives no problem

also there's situation where both modules are after crop and rotate - no probroblem

even with both kinds on, i couldn't reproduce whle enabling and disabling crop&rotate. (and made sure that c&r does change roi)
[DSC01932_03.ARW.xmp.txt](https://github.com/darktable-org/darktable/files/6680588/DSC01932_03.ARW.xmp.txt)

**Comment by johnny-bit** [comment] 2021-07-20 06:57
Cannot reproduce... Plz giv sample reproducers to nail the problem...

**Closed** 2023-03-25 00:19 UTC
Labels: understood: unclear, scope: image processing, no-issue-activity
