### ISSUE TITLE
Panasonic DC-S5

### ISSUE THREAD

**Issue by Azanoid** [darktable-org/darktable#11474] opened 2022-04-07 14:57 UTC
Hi, i uploaded raw images of Panasonic DS-S5, they wasn`t modified in any way. If you need something specific - please let me know.

**Comment by kmilos** [comment] 2022-04-07 15:35
AFAICT, the S5 samples are already present on RPU (you can use the search box to check), and support for the regular raws is already there.

High-res raws are still not supported: https://github.com/darktable-org/rawspeed/issues/246

**Comment by Nilvus** [comment] 2022-04-08 14:25
And it's a duplicate of #9768, so I close this one.

**Closed by Nilvus** 2022-04-08 14:25 UTC
Labels: duplicate, scope: camera support
