### ISSUE TITLE
limited possibilities to change selection in film strip in map view

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/darktable#6198] opened 2020-09-04 11:12 UTC
3.2.1, but I think it's not a regression.

While in lighttable view I'm able to change the selection with click, ctl-click, shift-click, in map view only the ctl-click is working. For non-trivial selection I'm obliged to go to lighttable view, perform the selection, and then revert back to map view.

**Comment by Nilvus** [comment] 2020-09-04 15:37
I suggest you to read release articles on www.darktable.org/blog to learn new features and changes (this is describe in 3.2 one). That will help you save time and understand some features.

For map view, selection allow to drag-and-drop photos in map. And quite often, selection start from lighttable. So, we need to help user keep selection. So, to change selection, you just have to make Alt+click on a new photo then use classic shortcuts in map view. This is to avoid a not wanted selection that could lost current selection.

Think about closing this issue after reading this. Thanks.

**Comment by Nilvus** [comment] 2020-09-04 15:38
And it's a duplicate of #5495 that I have posted before 3.2.1 release (and so before writing that on 3.2 article).

**Closed** 2020-10-05 11:17 UTC
Labels: no-issue-activity
