### ISSUE TITLE
Canvas grey while loading new image in darktable mode

### ISSUE THREAD

**Issue by mkunzBGC** [darktable-org/darktable#6550] opened 2020-10-16 18:33 UTC
**Description**
When switching from one image to the next in darktable mode, the old image disappears, leaving only the grey canvas (background) visible until the loading of the new image is finished. Although the grey canvas is typically visible for less than a second, this gap makes comparing images that are part of a sequence in darktable mode much harder than it was before. With darktable 3.0.0 and earlier, the old image is being displayed until loading of the new image is finished.

**To Reproduce**
1. Go to open a collection with more than one image
2. Open the first image in darktable mode
3. Press <space> or click on any other image in the film strip
4. The central part of the window shows only grey while "working... loading image ###" is displayed

**Expected behavior**
To my mind it would be much more helpful to display the old image until the new one appears, i.e. provide a seamless transition.

**Screenshot**
![darktableLoading](https://user-images.githubusercontent.com/21644074/96295353-0d9da380-0fee-11eb-8c9e-7039a0355275.png)

**Platform (please complete the following information):**
 - darktable Version: 3.2.1
 - OS: Windows 10
 - Behaviour is the same with OpenCL activated and deactivated

**Comment by elstoc** [comment] 2020-10-16 20:27
Duplicate of #4085

**Comment by mkunzBGC** [comment] 2020-10-17 10:49
My bad, searched for the bug but apparently not thoroughly enough. Thanks for the reference, and apologies!

**Closed** 2020-10-17 10:52 UTC
