### ISSUE TITLE
Styles quick access button causes crash

### ISSUE THREAD

**Issue by abnormally-distributed** [darktable-org/darktable#7822] opened 2021-01-12 23:02 UTC
**Description**
Clicking the quick access styles button at the bottom left side of the screen in darkroom mode results in the program crashing.
The bug crash report states the following: 

`darktable.exe caused an Access Violation at location 00007FFA1863D4E0 in module msvcrt.dll Reading from location FFFFFFFFFFFFFFFF.`

**Platform info**
 - Darktable Version: 3.4
 - OS: Windows 10
 - OpenCL activated, but bug occurs still with it de-activated.

**Additional context**
This has occurred even after deleting the styles and making new ones. Specifically, I started noticing this bug after I made styles using darktable-chart.exe to calibrate my camera.

**Comment by johnny-bit** [comment] 2021-01-13 07:40
Please attach full crash log, that line alone says absolutely nothing.
Please attach sample style file which might generate a problem.

**Comment by abnormally-distributed** [comment] 2021-01-13 07:49
> Please attach full crash log, that line alone says absolutely nothing.
> Please attach sample style file which might generate a problem.

Sure, I attached a profile here generated with darktable chart, and the log. 

[darktable_bt_U1KRW0.txt](https://github.com/darktable-org/darktable/files/5807124/darktable_bt_U1KRW0.txt)

[ELPH 180 CHDK Calibration.zip](https://github.com/darktable-org/darktable/files/5807142/ELPH.180.CHDK.Calibration.zip)

**Comment by Mark-64** [comment] 2021-01-14 19:50
Dt 3.4 on windows 10, unable to reproduce with the provided style.
Does it happen with any style you try to create ?

**Comment by abnormally-distributed** [comment] 2021-01-16 07:04
No, just the one(s) made with darktable chart. I discovered something else
going on related to this as well. When I am able to click the button
without a crash, there is a "phantom style". It looks to be a corrupted
copy of the profile  made with darktable-chart. It doesn't display any text
and I only discovered it when my cursor happened to drag to the bottom of
the menu, and the sub-dialog box describing the modules popped up. In any
case, I deleted the style file and cleared it from the list in the
lightroom view. The problem still occurs, but I managed to get a screenshot
of what happens when I can click the button without a crash. I suspect that
there's a file somewhere in appdata\local\darktable that can be deleted to
solve this, but it's not obvious to me which that might be.

[image: image.png]

**Comment by abnormally-distributed** [comment] 2021-01-18 01:10
Looks like my reply direct via email didn't attach the PNG file, here is the image intended to be attached before 

![image](https://user-images.githubusercontent.com/24922749/104862022-03968400-5900-11eb-9377-c1b363a49cbb.png)

**Comment by Mark-64** [comment] 2021-01-20 12:40
Sorry, but I have no issues in the menu with your style
![immagine](https://user-images.githubusercontent.com/43290988/105175929-d840ae80-5b24-11eb-885a-31457ff3b99f.png)

You have few styles there, maybe you can try remove all of them and then reimport the calibration style, just to be sure the issue is not related to something else

**Comment by abnormally-distributed** [comment] 2021-01-20 12:55
Yeah, I had tried that before posting here. I think I'll just reinstall
darktable. it freezes a lot when starting up too, so something may be off
with the installation.

**Comment by johnny-bit** [comment] 2021-01-20 21:35
@abnormally-distributed - reinstall might not help, you have to clear darktable config dir.

**Comment by johnny-bit** [comment] 2021-02-20 17:55
I'm gonna close this - the style is well formulated and there's nothing wrong with it. We tried but could not reproduce the problem and TBH it looks more like a db issue.

**Closed by johnny-bit** 2021-02-20 17:55 UTC
Labels: no-issue-activity
