### ISSUE TITLE
darktable crashes on macOS Big Sur

### ISSUE THREAD

**Issue by timo-christ** [darktable-org/darktable#5878] opened 2020-08-06 20:36 UTC
**Describe the bug**
I tried to run darktable on macOS 11 Big Sur Beta 4 and it crashes. The Icon in the Dock started to bounce and disappeared. 

**To Reproduce**
1. Install darktable on macOS 11 Big Sur (Beta 4 20A5323l)
2. Launch it
2.1. The icon bounces
2.2 The icon disappears
3. launch it on command line:
```
/Applications/darktable.app/Contents/MacOS/darktable

(process:23593): GLib-GObject-CRITICAL **: 22:22:40.256: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(process:23593): Gtk-WARNING **: 22:22:40.459: Locale not supported by C library.
	Using the fallback 'C' locale.
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152
[dt_pthread_create] info: bumping pthread's stacksize from 524288 to 2097152

(darktable:23593): GLib-GObject-WARNING **: 22:22:41.623: invalid cast from 'GtkMenuBar' to 'GtkWindow'

(darktable:23593): Gtk-CRITICAL **: 22:22:41.623: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
Assertion failed: (!surface->finished), function _cairo_surface_release_source_image, file cairo-surface.c, line 2092.
[1]    23593 abort      /Applications/darktable.app/Contents/MacOS/darktable
```

**Expected behavior**
- The Application should be able to run.

**Crash Report**
[darktable_2020-08-06-223316_tchrist-home.crash.zip](https://github.com/darktable-org/darktable/files/5037844/darktable_2020-08-06-223316_tchrist-home.crash.zip)

**Platform (please complete the following information):**
 - Darktable Version: 3.0.2.0
 - OS: macOS 11 Big Sur Beta 4 (20A5323l)
 - OpenCL activated: ?
 - Hardware: [MacBookPro14,2](https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i5-3.1-13-mid-2017-retina-display-touch-bar-specs.html)

**Additional Information**
I will retest the issue with the latest version of macOS.

**Comment by MStraeten** [comment] 2020-08-06 22:40
You need to build darktable yourself on Big Sur beta to check if there's really an issue originated in darktables code ...    
just follow the description in https://github.com/darktable-org/darktable/blob/master/packaging/macosx/BUILD.txt
Or wait until Big Sur is released and developers have upgraded their system.

**Comment by parafin** [comment] 2020-08-07 10:03
There is only one active macOS developer and it’s me. I have tested darktable on Big Sur beta and indeed it crashes. It seems something was changed in macOS GUI frameworks which made cairo/gtk incompatible. It’s not something to fix in darktable, so I suggest to raise a bug in cairo/gtk bug tracker. I don’t have access to that Big Sur system anymore and I won’t be upgrading my macbook, so I won’t be able to help with this.

Let’s keep this bug open for people to find.

**Comment by apfelkraut** [comment] 2020-11-13 19:21
I cannot reproduce the crash with the final/official release of Big Sur (macOS 11.0.1 20B29). Darktable 3.2.1 (retrieved via Homebrew) is working as under Catalina (macOS 10.15). Tried it with my migrated preferences ($HOME/.config/darktable) as well as with the default settings (deleted $HOME/.config/darktable before starting again).

**Comment by parafin** [comment] 2020-11-13 19:25
That's good news. Let's wait for @timo-christ or someone else to confirm this and I'll close this issue then.

**Comment by jo-sm** [comment] 2020-11-14 07:28
I just upgraded to Big Sur, and can also confirm that Darktable 3.2.1 doesn't crash. It was an upgrade, and I had to close and reopen the application before it would work correctly (it didn't respond to inputs on the first open), but it doesn't crash.

**Comment by parafin** [comment] 2020-11-14 08:29
OK, let's mark it as resolved then.

**Closed by parafin** 2020-11-14 08:29 UTC
Labels: no-issue-activity
