### ISSUE TITLE
Panasonic GH6

### ISSUE THREAD

**Issue by skypilotdroneimages** [darktable-org/darktable#14767] opened 2023-06-23 23:21 UTC
I really like this program as I just downloaded it and have been exploring.   I am wondering if you will be supporting the Panasonic GH6 in the near future so I can use the software to it's fullest extent?   Thank you.

Before filing any support requests, please do make sure that you have already
contributed the whole raw sample set for your camera under CC0 license to
https://raw.pixls.us/ !

#### Important note: to make sure that darktable can keep on supporting the raw
file format for your camera, *please* read
[this post](https://discuss.pixls.us/t/raw-samples-wanted/5420?u=lebedevri) on
how/what raw samples you can contribute to ensure that we have the *full* raw
sample set for your camera under CC0 license!

**Comment by LebedevRI** [comment] 2023-06-23 23:23
See https://github.com/darktable-org/rawspeed/issues/367

(duplicate of closed https://github.com/darktable-org/darktable/issues/12426)

**Closed** 2023-09-18 12:51 UTC
Labels: duplicate, scope: camera support
