### ISSUE TITLE
Export generates different sizes even though aspect was set to fixed value

### ISSUE THREAD

**Issue by mrusme** [darktable-org/darktable#16671] opened 2024-04-22 14:42 UTC
### Describe the bug

I have a set of landscape photos that I cropped to 16:9. When exporting I set the long edge to 3840px. The exported files however randomly differ in width and height by several pixels. This doesn't seem reasonable, given that the source images are well over 6000px in width and the aspect was set to 3840, which should result in a consisten 3840x2160 size.

### Steps to reproduce

1. Edit a handful of images, cropping them to 16:9
2. Select them all and export them with the size set to 3840px
3. Inspect the resulting files

### Expected behavior

darktable should export files resulting in 3840x2160px

### Where did you obtain darktable from?

distro packaging

### darktable version

4.6.1

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Describe your system?

Starlabs StarBook Mk VI AMD

### Are you using OpenCL GPU in darktable?

Yes

### If yes, what is the GPU card and driver?

AMD / ROCm

**Comment by mrusme** [comment] 2024-04-22 14:55
This is related to https://github.com/darktable-org/darktable/issues/3757

**Comment by zisoft** [comment] 2024-04-22 16:11
Duplicate of #16638

**Closed** 2024-04-22 16:12 UTC
Labels: duplicate
