### ISSUE TITLE
UI CSS : font size not being applied (at least on Mac)

### ISSUE THREAD

**Issue by homer3018** [darktable-org/darktable#2615] opened 2019-05-22 20:40 UTC
**Describe the bug**
While I love the new UI and the fact that everything will now be tweak able, I've been suspicious about how it looks on my 5k display. I find the font size to be quite large, especially when compared with other things like my font size in terminal.
I have started DT with `GTK_DEBUG=interactive` and went straight to the tab `Visual`.
This is how it looks like upon starting it up. (I had to scale down the image for size reason, but the following screenshot has been scale down equally)

<img width="2400" alt="Screenshot 2019-05-22 at 22 05 00" src="https://user-images.githubusercontent.com/36423314/58206162-7b9e4800-7ce0-11e9-97e1-27dfbd386be5.png">

I have just opened the settings page so you can see the discrepancy between the settings title and its content for instance, or with the time unit in the histogram below the lighttable, and the image information displayed on the left hand side panel down the bottom.
If I were to go in the darktable with the theme `icons` you would notice the misalignment that was discussed at some point on pixls.us.

All I did was click once on the left hand side of the `Font Scale` parameter in the `GTK` debug tool. Immediately the value jumps from 1 to 0.99 and this is what I see now :

<img width="2400" alt="Screenshot 2019-05-22 at 22 05 27" src="https://user-images.githubusercontent.com/36423314/58206459-fd8e7100-7ce0-11e9-8c63-cd79121bd85d.png">

This is a lot more pleasant to the eye, and this font size (0.99em of OS font size ?) is very comparable to what the system is using (see the "darktable" at the top, or the settings window title and its content...)
The icons now are a lot more centered though there are still not (vertically). It looks like their position is bind to the font size instead of their GTK box dimensions. Regardless of the font size, hence of their own size, their center position should remain the same. I'm ok with leaving it as it is now (as the modification would arguably be noticeable) especially if this is too much work for a small achievement. 

<img width="350" alt="Screenshot 2019-05-22 at 22 06 57" src="https://user-images.githubusercontent.com/36423314/58206607-4e9e6500-7ce1-11e9-8683-fb11f54b3942.png">

**To Reproduce**
1. Start DT with `GTK_DEBUG=interactive`
2. Click on the left hand side of the parameter `Font Scale` and it should set it from 1 to 0.99
3. Examine the difference

**Expected behavior**
I understood that the font size was set to 1em i.e. same as OS font size should be used from the CSS, but somehow this is not the case. Switching from 1 to 0.99 should not lead to any perceivable difference.

**Screenshots**
See above.

**Platform (please complete the following information):**
 - OS: MacOS 10.14.4, 5k display (using 3200x1800)
 - Version 2.7.0 1231

**Additional context**
It might be just me, or there are more problems with fonts than expected: look at the `date time` field in the image information pane. I have no idea why this looks like Japanese symbols. I have only installed on this machine all the Roboto fonts.

**Comment by Nilvus** [comment] 2019-05-22 21:20
It seems to be a MacOS issue (or Macports one as I see on pixl.us you compile with Macports). What I see here is font on Gtk debug inspector is set to "none". None of issues you have have been seen on Linux (on mine of course not as I don't have any of them ; and @aurelienpierre who made the main part of the new UI and I have add some adds had that and even about quite few users who made feedback ; but too less on Mac or Windows).

I don't know if it's could be related but maybe if there is no default font, some bugs like that could happen, or it's a macports bug that cause this behavior ? So maybe try to see if you select a default font on Gtk Inspector. (of course, darktable normally use Roboto if installed and elegant theme used as the theme you select).
For the datetime with Japanese symbols, I really don't understand from where it came. Never see that.

I can't help more here for that as I can't reproduce this.

**Comment by homer3018** [comment] 2019-05-23 06:42
Hi @Nilvus 

I have no doubt that these things have tested again and again, and I thank you for that. I am willing to contribute any way I can and maybe testing things on macos is a good start.

It might very well be a specific issue to macos and/or macports, but I am not sure, so if someone else comes across this, please test and report as time allows.
I'll test to select a font tonight. I remember that before installing Roboto, I had in the terminal messages to let me know that Roboto was no found. These had gone away ever since I installed it on my system. I'm now assuming that it is using it, but in that case why GTK is reporting no font ? Again I have no idea but I'll try what you say and we'll take it from here.

Let aside for the moment the symbols (I have no idea either on that, very strange) but as I see it there is a font issue and if we manage to get through this, the symbol issue might go away at the same time.

Thanks for your feedback.

**Comment by Nilvus** [comment] 2019-05-23 18:02
Hi @homer3018,
Thanks for your help on trying to improve the UI. Of course, I know you want to improve that for MacOS and that's a great thing as I can't test it and most users who made feedback are not on this OS (most are on Linux of course). I precise that here especially for all users who have not read our conversation on pixl.us.

About font, maybe I was not clear. It's not about Roboto has, normally, elegant themes use Roboto. That's just about font set in Gtk debug inspector. The font set (where it's at "none" on your computer) is the default OS font. On my system for example, I use (of course) my grey theme (so Roboto font) and on Gtk Inspector the font is "Ubuntu" (a specific font made by the Linux distribution Ubuntu). Ubuntu is my default OS font. So, it's just to check if the default OS font at none change something or not here (and if it could explain the difference you see).

About that and japanese symbol, could you please see which font-family and font-size you have when pointing on datetime (with pointer on Objects tab of Gtk inspector.and see CSS node properties). On my Linux system, I have this :

![Capture-20190523195533-1102x649](https://user-images.githubusercontent.com/45535283/58275598-b7471980-7d95-11e9-81a8-69f61444b1ab.png)

**Comment by homer3018** [comment] 2019-05-23 20:47
Setting the font set does not change anything. However changing its size, as everything depends on it has an influence. I just set it from 12 to 5 just to test. Everything went very small, except all the sliders in the modules. My recollection is that these are widgets, and it seems they do not scale well, even if the font family and size look ok.

This is a screenshot right after start up (when it's all big : 
<img width="1020" alt="Screenshot 2019-05-23 at 22 34 46" src="https://user-images.githubusercontent.com/36423314/58284954-1e6fc880-7dac-11e9-8919-1a3a67bf40a2.png">

And this is after adjusting the size to .99 to make everything 'normal' : 
<img width="1020" alt="Screenshot 2019-05-23 at 22 32 32" src="https://user-images.githubusercontent.com/36423314/58284983-2fb8d500-7dac-11e9-8c8d-262bbaba88b7.png">

And this is the Lowpass module with font set size set to 5 : 
<img width="353" alt="Screenshot 2019-05-23 at 22 44 35" src="https://user-images.githubusercontent.com/36423314/58285128-70185300-7dac-11e9-830c-32a287e429ed.png">

Regardless of the font set size, or the font scale, the module sliders are always remaining at the same size.

**Comment by Nilvus** [comment] 2019-05-24 15:51
1) Ok, so no issue here in font size nor in font used. There's no "normal" view as the font is related to OS font size (emphasis) and it's a normal behavior as the view doesn't have to be too different between apps and a compromise to have an UI dedicated to image on darktable. Emphasis is also great to easy change of size with OS font for those who find the text too small or too big, depending on their view and/or what they like.

If instead of setting scale factor to 0.99 instead of 1, you reduce font size (scale factor), you will see same behaviour (text font size on the UI will change)

For example, as you certainly see, font-size on my UI is 13.33333px with scale factor to 1 and for text at 1em. I use a OS font size of 10pt and my UI is like that (what you call normal) :

![Capture-20190524173423-1920x1052](https://user-images.githubusercontent.com/45535283/58339743-8ffe5400-7e4a-11e9-8b13-07e19cc82f70.png)

And with only change my OS font size to 10pt from just 11pt. That set the font-size to 14,66667px (normal, as 1pt=1.33px) :

![Capture-20190524173451-1920x1052](https://user-images.githubusercontent.com/45535283/58339935-f08d9100-7e4a-11e9-86db-b3e6141e2e06.png)

2) About sliders and some comboboxes, you have to restart darktable to see changes. There's some parts of the UI who are special adapted widgets from Gtk and can't be refresh without restart like most of the UI

3) So the only thing I don't understand and I could not help is why datetime have some "japanese" symbols.

**To conclude and be more concise :**

You just describe the normal behaviour about fonts in reality, as the UI is adaptative. So, if you want to reduce font size to have what you called "normal behaviour", just reduce your OS font size (or macports, I don't know how macports really works and how it's use default font parameters of Mac OS) or you scale factor. Reduce font size is better than scale factor at first.

For some parts of the UI that doesn't change after changing theme or font size, that means that darktable need to be restart. On what I read from @aurelienpierre it's not possible without a too big rework (with some risk to create other issues) of that Gtk parts. So this will not be resolve by now. And as we didn't change often the Ui, a restart sometimes is not an hard thing.

_I propose to you to close this issue and create a new one with just the "japanese datetime problem". Please precise in the title of the new UI something like that : "On Mac : "japanese" symbols on datetime field in module image infos"_

Is it ok for you ?

**Comment by homer3018** [comment] 2019-05-26 20:35
Below is the screenshot of darktable just started without any modifications in the GTK debug tool.
<img width="1600" alt="Screenshot 2019-05-26 at 22 08 27" src="https://user-images.githubusercontent.com/36423314/58386656-1fe6fe00-8003-11e9-9172-f956e30ebe9a.png">
The GTK debug tool says that it is using my OS default font size which is 12, and uses a scale of 1. I understand this as "everything displayed in darktable should be of size 1em based on system font size, in this case with the scale at 1, everything will be 12pt". Is my understanding correct ?
My terminal is `SF Mono Regular 11pt` under my current settings and I simply don't think what I see in darktable is 12pt.
I don't think MacPorts has anything to do with this.

The whole thing with the scale to 0.99 was just to force GTK to update that setting. In fact, if I click on the scale factor, type 1 and enter (so not making any changes), everything will scale down as I have showed in my previous post, and I do not think this is the expected behaviour. I like what I see once I have done that, size wise, and I think this is what it should be.

**Do you see any change if you type 1 in the scale factor and hit enter ?** If not then this issue might just regards Mac users but this would need to be confirmed. And if you do see a change then please enlighten me with an explanation of why this is happening.

**Comment by Nilvus** [comment] 2019-05-27 16:46
Please read carefully what I explain to you and capture screen I have posted. You always repeat same things regardless of what I have explained to you. And I can think that I don't answer with too short explanations. And why you compare to terminal font as all Unix terminal don't use the OS system font but a special one. You just have to compare visually how text is rendering on terminal and another application (for example, your navigator or finder...).

So stop seeing an issue where there's not. As I said after your last tests : **what you see is THE NORMAL BEHAVIOR regardless your OS font and its size**. **_Just reduce your OS font from 12 to 11 or even 10pt and you will see what you called "normal"._**

The only issue you have and probably related is the only who you don't talk here !

I'm ok to help but not to lost my time on issues who doesn't exist and are just related on how your OS is configured.

@TurboGit : could you please close this "not" issue.
@TurboGit

**Comment by parafin** [comment] 2019-05-27 16:57
The issue is probably DPI. On Mac DPI is fixed to 72 I think for all applications. DT on the other hand detects actual monitor DPI and uses it. This means that same font size in DT looks different compared to other Mac applications (but it's the same physical size as it is on Linux). Probably that GTK debug tool resets DPI setting when you modify font scale. Or maybe font scale is DPI/72 and it just doesn't show correct initial value.

**Comment by TurboGit** [comment] 2019-05-27 16:58
Ok, closing.

**Closed by TurboGit** 2019-05-27 16:58 UTC

**Comment by Nilvus** [comment] 2019-05-27 17:03
> The issue is probably DPI. On Mac DPI is fixed to 72 I think for all applications. DT on the other hand detects actual monitor DPI and uses it. This means that same font size in DT looks different compared to other Mac applications (but it's the same physical size as it is on Linux). Probably that GTK debug tool resets DPI setting when you modify font scale. Or maybe font scale is DPI/72 and it just doesn't show correct initial value.

Thanks for this precision @parafin who complete I think my replies and confirm that reducing a little font size could help @homer3018 to have the UI he want to have. And if it's not sufficient for him, creating a personal CSS on his config folder with a font size of 0.9em (I'm not sure 0.99em will be ok for Gtk here) could also be a possibility.

**Comment by Nilvus** [comment] 2019-05-27 17:26
@homer3018 : That DPI thing make me think of one thing (and reread your last posts). I am on to confirm that's not a darktable issue but probably how GTK port on Mac render text regardless of how Mac works about font rendering. If you compare my screen capture about label CSS settings on GTK inspector and your same one, you will see that I have a --gtk-dpi css properties which is set to 96. If I see your GTK inspector, you don't any have this property. So, it seems that GTK doesn't set a default dpi on macports.

So that's a really special set and I really think that my last suggestions you could made on your OS is the better and easy one. Or search if it's a possibility to force DPI settings on Mac for GTK apps maybe. That's here I think the limit about porting apps from an OS to another, especially for some libraries needed like GTK. I don't know here how Gimp works about that...

**Comment by parafin** [comment] 2019-05-27 17:27
I don't know what Font Scale from GTK tool means, maybe it's one of GDK_SCALE or GDK_DPI_SCALE. In any case it doesn't matter. There are 3 related settings:

- Pixels Per Dot (screen_ppd_overwrite) - has to do with HighDPI (Retina), it's 1 on normal display and 2 on HighDPI. PPD is set in system preferences (scaled or not scaled resolution) and setting in DT exists only to render everything with sub-dot precision so it looks good, it won't scale anything.

- Dots Per Inch (screen_dpi_overwrite) - screen DPI. If you set DPI in DT lower than it actually is, then everything will become smaller because on displays with lower DPI fewer pixels are needed to get the same physical size. On Mac historically DPI is hard-coded, so font sizes don't correspond to physical size. DT doesn't follow this concept and uses real monitor DPI, like it's done on Linux. Because of that you can't compare font sizes in DT to other Mac applications.

- Font size in DT theme CSS - larger size makes letters larger;) Changing it won't scale other GUI elements, unlike DPI setting.

So one can edit either of last 2 settings to change how big are the letters in DT UI.

**Comment by parafin** [comment] 2019-05-27 17:28
Macports has nothing to do with it. GTK on Mac by default follows the policy I described about fixed DPI and uses 72 (or whatever). I wrote special code in DT that overwrites that setting with actual screen DPI.

**Comment by Nilvus** [comment] 2019-05-27 17:31
> Macports have nothing to do with it. GTK on Mac by default follows the policy I described about fixed DPI and uses 72 (or whatever). I wrote special code in DT that overwrites that setting with actual screen DPI.

Ok, I don't know how macports works and that was just an assumption.

**Comment by Nilvus** [comment] 2019-05-27 18:46
@homer3018 : After reflection, and parafin adds, I realize that I was quite rude on my first answer of this day. Apologies for that !
With parafin adds, I think the easier setting to adjust on your system is to edit your darktablerc file and change screen_dpi_overwrite.

About japanese symbol on datetime, be free to post a specific issue. I will not help here as it's beyond my skills and probably needs help of a Mac developer.

**Comment by homer3018** [comment] 2019-05-27 19:50
I knew from the beginning and the other discussion on pixl.us that I would solve this with a custom css or even in darktablerc file. What I didn't know is how hard it would be to be part of this community and try to help. 

I was not looking for a quick fix but for a real solution. Now what's next ? darktable font size (and icons) without modifications from my part is at least 2x time bigger than anything on my system (yes terminal but everything else as well). 

You keep saying this is normal and closed the issue. That's fine and no need to apologise, but It won't make me finding it normal.

Thanks again for the help so far.

**Comment by parafin** [comment] 2019-05-27 20:02
To be fair, this is indeed not a bug, so it was closed correctly. At most it's a feature request for darktable not to change DPI from system hard-coded default. You may like it better, but it's not obvious it will be better for everyone. I personally think it makes sense to scale fonts according to monitor real DPI, like it's done on Linux. Maybe darktable should have font size chooser in preferences (or even font family too), so that people wouldn't have to mess with config files manually.

**Comment by homer3018** [comment] 2019-05-27 20:08
Is there a way I can see the DPI currently used by the system and the one that darktable seem to enforce ?
I don't know how to do that.

**Comment by Nilvus** [comment] 2019-05-27 20:16
What I'm trying to explain is it's not a darktable bug and it's the normal behaviour as it's related on font size. So yes I keep saying it's normal but that doesn't means that there's not another thing to improve. Here, as parafin said better than me as I don't even think about that before, it's related to how dpi works on MacOS (not the same way than on Linux). So yes, it's not a darktable bug, nor a UI CSS issue but a feature request maybe to adapt Linux dpi working on MacOS one.

darktable doesn't enforce one, it's just use the real monitor dpi (so as parafin says the same physical size on MacOS than on Linux). But the way you see it seems different as other applications are not displayed the same. It's MacOS who set a "default" dpi setting, as I remember when I'm on Mac, for main Apple screens it's the same but about other displays of other brands...

I remember that on monitor preferences, you could use some scaled resolutions. I don't know if it change the dpi setting but maybe (see links posted on a previous post I made). And maybe searching on the web could help for you to find that. Or even post on Github a feature request to ask about adding a way to adjust that, as @parafin suggest.

**Comment by parafin** [comment] 2019-05-27 20:43
To see auto-detected DPI start darktable like that: `/Applications/darktable.app/Contents/MacOS/darktable -d control`

Look for `[HiDPI] setting ppd to` and `[screen resolution] setting the screen resolution to`

**Comment by homer3018** [comment] 2019-05-27 21:04
```
0.230621 [HiDPI] setting ppd to 2.000000
0.230748 [screen resolution] setting the screen resolution to 135.257611 dpi
```

while from what I could find my screen is 218 ppi. I'm assuming we are all talking about ppi here.

**Comment by marcsitkin** [comment] 2019-12-25 11:30
Not sure if I can contribute much to this as I'm just a user, but I loaded Darktable 3.0 on my MacBook Pro 15" retina today and got an interface with very large fonts and items running off screen. Mac OS Catalina 10.15.2, display set at default res. A screen capture is attached. Changing the display resolution to scaled (looks like 1680x1050 seems to be a better fit for darktable GUI, but leaves me with tiny type in all other system views.
<img width="1440" alt="Screen Shot 2019-12-24 at 7 38 16 PM" src="https://user-images.githubusercontent.com/58574122/71444542-0d8b8a80-26e0-11ea-823f-fbb6b96ef32d.png">

**Comment by homer3018** [comment] 2019-12-26 07:12
Had the exact same behavior a while back, which got fixed by overriding a setting in the darktablerc file. It might be specific to mac, but still, any regular user won't be ok with messing up with config files manually just to have a similar looking font size across all apps. 

Just out of curiosity, @marcsitkin , do you have the robot font family installed on your mac ? Do you have San Francisco as well ?
