### ISSUE TITLE
Banding artifacts in Waveform after resizing

### ISSUE THREAD

**Issue by groutr** [darktable-org/darktable#4065] opened 2020-01-08 17:06 UTC
**Describe the bug**
After #4041 (thanks @dtorop) was merged, I tested it and found some vertical banding artifacts after resizing the waveform.  I don't know if this caused by this PR, or merely uncovered by this PR.  I haven't noticed these pattern before.

**To Reproduce**
1. Open an image in darkroom
2. Resize the right panel to a wide width
3. Observe the vertical banding artifacts in the screenshot below.

**Expected behavior**
I would expect to see a waveform with no banding.  The pattern of the artifacts appear to depend on the width of the waveform with some widths giving a very noticeable pattern.

**Screenshots**
[![waveform-aliasing.png](https://i.postimg.cc/DznZJDPG/waveform-aliasing.png)](https://postimg.cc/K1pFC0Vc)

**Platform (please complete the following information):**
 - Darktable Version: 3.1.0.r321.ge3db8d52f
 - OS: archinux
 - OpenCL: yes (intel NEO)

**Comment by dtorop** [comment] 2020-01-09 03:30
I'm seeing this in older versions of darktable as well. I've gone back as far as release-3.0.0rc2 and still see it. Resizing the panel might make this more obvious.

Here is an example from release-3.0.0rc2 with a 350 width panel on a hidpi display:

![image](https://user-images.githubusercontent.com/2311860/72035492-0af36e00-3266-11ea-8c17-a8bd48e16ea1.png)

I'll still look and see if there's an obvious reason for this.

@groutr If you're able to replicate this in older versions, I'd be curious.

**Comment by dtorop** [comment] 2020-01-09 04:01
I think the problem is how the source image data gets processed into the waveform. In `_pixelpipe_final_histogram_waveform()`, the preview image gets downsampled horizontally to the width of the waveform histogram. The binning is simple:

https://github.com/darktable-org/darktable/blob/aae21bfd58d15c5231c0271693c3655df6133c22/src/develop/pixelpipe_hb.c#L1019

The preview image is 1338 pixels wide. With a 350 pixel wide panel, generally five preview pixels map to one waveform column, but every sixth waveform column has only three pixels mapped to it, and hence is 3/4 the brightness. The histogram gamma correction code may further exaggerate the banding.

A quick fix might be to weight each bin by the # of pixels in it. I'll check that out. A proper downsampling may be too slow.

**Comment by dtorop** [comment] 2020-01-09 04:10
Also, it may be that

https://github.com/darktable-org/darktable/blob/aae21bfd58d15c5231c0271693c3655df6133c22/src/develop/pixelpipe_hb.c#L1041-L1042

is hardcoded to only do the right thing for a 350px wide panel. This came in back in 4fe5079325a6f6e9f9ec29fcda68a58c33153293.

**Comment by dtorop** [comment] 2020-01-09 04:21
> hardcoded to only do the right thing for a 350px wide panel

I'm actually entirely uncertain about why the above math works, but take that back about hardcoded to 350px.

**Comment by dtorop** [comment] 2020-01-09 04:55
Here is a naive fix: https://github.com/darktable-org/darktable/compare/master...dtorop:waveform-banding-fix

I'll think about this more before making a PR. There's certainly a better way to write this code, and almost certainly a better method as well.

**Comment by dtorop** [comment] 2020-01-09 19:18
I'm curious what it would be like for `_pixelpipe_final_histogram_waveform()` to generate a waveform histogram which is the same width as the preview image, then rely on `_lib_histogram_draw_callback()` to appropriately scale it horizontally.

Advantages:

- the pixelpipe won't have to know about GUI things (the width of the right panel)
- we won't need to re-run the preview pipe and allocated/deallocate the waveform buffer every time the right panel width changes
- easier to render the waveform at high-dpi
- code will be simpler

But the disadvantage is that we'll output data to a bigger buffer when pixelpipe makes the waveform histogram. That happens every time an iop changes settings, which is far more frequent than when the right panel changes size. The hope is that a better quality histogram on high DPI and faster current CPUs will make this worthwhile.

It'll become clearer if this is a good idea once I try it out.

I did push a commit to `waveform-banding-fix` which makes the waveform histogram high-dpi.

Before:

![image](https://user-images.githubusercontent.com/2311860/72097316-1f794a00-32ea-11ea-8af3-f267918c97da.png)

After:

![image](https://user-images.githubusercontent.com/2311860/72097321-23a56780-32ea-11ea-9fa2-33b722a33039.png)

On my computer, making the output hidpi is about 1.6x slower for a right panel width of 350 (average 0.18 sec. vs. 0.11 sec. elapsed time).

**Comment by groutr** [comment] 2020-01-09 21:44
I like the hidpi approach better than what I was trying to do.  I was thinking about how to get nice integer width bins, but it made the waveform kind of weirdly sized for some widths.

I'll run it on my machine and see it the performance delta is similar to yours.

**Comment by groutr** [comment] 2020-01-09 22:07
@dtorop interesting.  The performance on my machine is something like this.  For narrow panel widths, master was about 0.022s, but for wide panel widths it was 0.028-0.030s.
However, with the hidpi waveforms, it is ~0.029s for any width.

Processor: i5-6300U @ 2.9Ghz.

**Comment by groutr** [comment] 2020-01-09 22:51
@dtorop perhaps this might be helpful.  I played with the loop a bit and was able to drop the hidpi waveform creation time to about 0.022s on my machine (down from 0.029s).  I'm curious to see if it has the same effect on your machine.
Basically, I did two things
1. Replaced the (8.0/9.0) with .9 (does it really have to be "exactly" 8/9ths)
2. Removed the rgb float array and the loop that fills it.  Access the input directly in the loop over k.

```c
for(int y = 0; y < roi_in->height; y++)
  {
    for(int x = 0; x < roi_in->width; x++)
    {
      // removed this
      // float rgb[3];
      // for(int k = 0; k < 3; k++) rgb[k] = pixel[4 * y * roi_in->width + 4 * x + 2 - k];

      const int px = 4 * y * roi_in->width + 4 * x + 2;   // added this
      const int out_x = MIN(x / bin_width, dev->histogram_waveform_width - 1);
      for(int k = 0; k < 3; k++)
      {
        const float fk = pixel[px - k];  // added this
        const float v = isnan(fk) ? 0.0f
                                      : fk; // catch NaNs as they don't convert well to integers
        const int out_y = CLAMP(1.0 - .9 * v, 0.0, 1.0) * _height;  // changed (8.0/9.0) to .9
        uint32_t *const out = buf + (out_y * dev->histogram_waveform_width * 3 + out_x * 3 + k);
        (*out)++;
        //               mincol[k] = MIN(mincol[k], *out);
        //               maxcol[k] = MAX(maxcol[k], *out);
      }
    }
```

**Comment by dtorop** [comment] 2020-01-09 23:04
@groutr All good to hear. I should have noted, but I put out another commit to https://github.com/darktable-org/darktable/compare/master...dtorop:waveform-banding-fix, e326c79ad80f2580b0798950dd3b2bde525e4392 which doesn't do any binning horizontally, and uses Cairo to do the downscaling. Visually results are pretty similar to the hidpi version.

Pre-hdpi binning with banding fixed:

![waveform histogram pre hidpi detail](https://user-images.githubusercontent.com/2311860/72111922-1f894200-330a-11ea-9c62-c25652b9139b.png)

Hi-dpi with horizontal binning and banding fixed:

![waveform hidpi change detail](https://user-images.githubusercontent.com/2311860/72111757-b30e4300-3309-11ea-9bf2-f15cf07f47ba.png)

No horizontal binning, using Cairo to scale:

![waveform at preview pipe width detail](https://user-images.githubusercontent.com/2311860/72111769-ba355100-3309-11ea-85e1-88330b94ea74.png)

It's slower, though. I came across eliminating the rgb[] array as well, but I'll look more closely at what else you did.

My thinking is to try integer-sized bins (probably 2 or 3 columns to each bin) and use Cairo to do the final scaling. And perhaps caching the results of powf() would be a speedup. But I won't suggest it for a PR unless the performance is reasonable and the code is straightforward.

**Comment by groutr** [comment] 2020-01-09 23:57
@dtorop I pulled your new commit.  I noticed that there seems to a small bug.  The banding is gone, but the waveform seems to be cut off.
waveform-resize-fix:
[![wf-noclip.png](https://i.postimg.cc/gkhF31sc/wf-noclip.png)](https://postimg.cc/PPdRj300)

Master:
[![wf-master.png](https://i.postimg.cc/252PzYkG/wf-master.png)](https://postimg.cc/B8Phgd1P)

**Comment by dtorop** [comment] 2020-01-10 02:09
@groutr Thanks for testing. I don't see a difference here between master (I tested aae21bfd58d15c5231c0271693c3655df6133c22):

![waveform-master](https://user-images.githubusercontent.com/2311860/72119470-89154a80-3322-11ea-9ab9-ea3d07fd047c.png)

and `waveform-banding-fix` (e326c79ad80f2580b0798950dd3b2bde525e4392):

![waverform e326c79ad8](https://user-images.githubusercontent.com/2311860/72119511-aa763680-3322-11ea-90ad-56bed7c0c424.png)

Is it possible that you are using something else for comparison?

I looked over your optimizations. For:

`const int out_y = CLAMP(1.0 - .9 * v, 0.0, 1.0) * _height;  // changed (8.0/9.0) to .9`

That should produce a slightly different value, yes? 0.88888 vs. 0.9? The compiler should be able to optimize the division of constants, regardless. For everything else I think we're on the same page.

**Comment by dtorop** [comment] 2020-01-10 02:28
@groutr I take that back -- I do see the histogram being clipped at the bottom. I can observe this by setting up an RGB curve and pulling down the top of the curve from 255 to about 60. The image is still visible, but the waveform histogram is blank. I'm not sure why I'm seeing no difference between my branch and master. I'll look into this. Thank you for letting me know.

**Comment by groutr** [comment] 2020-01-10 02:33
@dtorop, did you test with an image with extreme contrast?  I didn't notice it until I was working with an image that had very deep shadows.
Hopefully these screenshot more clearly illustrate the issue:
master (3.1.0.r321.ge3db8d52f)
[![wf-master-deep-shadow.png](https://i.postimg.cc/9QqPgG0C/wf-master-deep-shadow.png)](https://postimg.cc/k2qtBRWp)

waveform-resize-fix (3.1.0-326-ge326c79ad)
[![wf-fixed-deep-shadow.png](https://i.postimg.cc/tTgYwjkW/wf-fixed-deep-shadow.png)](https://postimg.cc/DWtv4Rtw)

Thanks for the feedback on the value change.  I wasn't sure if C compilers would optimize that out since I don't often use C.  I changed it primarily because I thought a value was easier to read than a division, and it's being cast to an int anyway. I have no attachment to the change.

**Comment by dtorop** [comment] 2020-01-10 02:47
@groutr Thanks for the further examples. Something is fishy, but the problem I just saw was actually an error in vertical scaling in some code I'm working on but didn't check in.

I did notice another interesting bug. When dragging a point on the RGB curve, if you rapidly move the mouse out of the module, the histogram doesn't update to the final position of the point. This is irrespective of whether the histogram of waveform or "regular".

The 8/9 scaling of the Y axis in waveform is so that the we can see values of greater than 100% white in the gap between the space between the top of the histogram and the topmost horizontal line. It might be nice if the topmost line was rendered slightly differently to signify this.

**Comment by dtorop** [comment] 2020-01-10 04:40
More updates to this branch. I still can't replicate the clipping at the bottom of the waveform. Possibly a hidpi issue? I rebased and may make a PR. Current code should be approximately as fast as what is in master, with slightly better visually quality and no banding. I opted to make the waveform buffer relatively small (360x128) as this gives adequate visual information, still looks pretty good, and doesn't slow things down.

**Comment by groutr** [comment] 2020-01-10 12:33
@dtorop not sure if this is pertinent information, but I'm running darktable on a 1920x1080 screen.

**Comment by dtorop** [comment] 2020-01-10 14:12
@groutr It may well matter. I will test this on a lodpi small screen laptop.

**Comment by dtorop** [comment] 2020-01-13 19:19
@aurelienpierre This should be fixed via #4075 now in master. Let me know if you're still seeing banding or other problems.

I still haven't been able to confirm what @groutr reports in the comments: that the waveform histogram crops at the bottom. I've tested this on a hidpi screen (4K, Xorg) and lodpi (1366x768, Wayland).

**Comment by aurelienpierre** [comment] 2020-01-13 22:09
Ok, closing. Feel free to reopen if needed.

**Closed by aurelienpierre** 2020-01-13 22:09 UTC
Labels: bug: wip, reproduce: confirmed, scope: UI, understood: clear

**Comment by groutr** [comment] 2020-01-15 22:51
@dtorop I built these commits from master and I'm not seeing the cropping at the bottom anymore.  Not sure what was going on before, but it seems to be ok now.

**Comment by dtorop** [comment] 2020-01-16 02:43
@groutr Thank you for checking on it and writing. Let me know if anything else looks off.
