### ISSUE TITLE
Remove Folder from Collection

### ISSUE THREAD

**Issue by maclaw13** [darktable-org/darktable#4635] opened 2020-04-07 12:40 UTC
When a user organizes collection and intend to remove the whole folder from the collection, he/she is expected to set collection filter to "Show All" prior to removal. Setting filter to something (like "= 3 stars") causes DT to remove only photos selected by filter while the rest of the collection remains intact. 
I expect "Remove Folder" to remove all photos from collection that are in this folder irrespect of filters set on collection.
If the currenct behavior is expected because of some constrains or assumptions, let's rename current option to "Remove Selected Items" and then add new option "Remove whole folder".

**Describe the bug**

**To Reproduce**

1. Import Folder
2. Process photos
3. Set "stars" filter on photos (like "= 3stars")
4. Lighttable - Collections - Folder - Remove folder
5. Only selected photos are removed

**Expected behavior**
Whole Folder removed from Collection.

**Screenshots**

**Platform (please complete the following information):**
 - Darktable Version: 3.0.1
 - OS: Ubuntu, "Studio" flavor
 - OpenCL: not available due to OS/hardware
 
Photos are selected (the selection does not matter, so empty one does the trick too).
![Screenshot1 - selected photos](https://user-images.githubusercontent.com/63295508/78669887-3de8e480-78dd-11ea-843c-653d48180740.png)

Folder is removed
![Screenshot2 - removing with filter](https://user-images.githubusercontent.com/63295508/78669890-3e817b00-78dd-11ea-80b0-b6ea3b861c34.png)
After removing folder, the screen looks exactly like in Screenshot1, so no new picture here.

Removed filter and trying to remove folder again.
![Screenshot3 - removing whitout filter](https://user-images.githubusercontent.com/63295508/78669891-3f1a1180-78dd-11ea-93e5-24604a3d0f68.png)

This time success
![Screenshot4 - success](https://user-images.githubusercontent.com/63295508/78669892-3fb2a800-78dd-11ea-8b25-1fdd20b7790e.png)

**Additional context**
 - Can you reproduce with another Darktable version? 
Don't know
 - Can you reproduce with a RAW or Jpeg or both?
Both
 - Are the steps above reproduce with a fresh edit (removing history)?
Yes
 - Attach an XMP if this is necessary
Not necessary
 - Did you compile Darktable yourself? If so which compiler was used, with what options?
Compile provided by darktable.org for Ubuntu 19.10
 - Is the issue still present using an empty/new config-dir
Yes

**Comment by elstoc** [comment] 2020-04-07 13:31
This is because ``view_popup_menu_onRemove`` (``collect.c``) populates main.selected_images with all of the images in the folder but then calls ``dt_control_remove_images`` (``control.c``) which ignores this and instead calls ``dt_view_get_image_to_act_on``.

**Comment by elstoc** [comment] 2020-04-07 14:05
@AlicVB?

**Comment by pfheatwole** [comment] 2021-03-07 19:38
I'm seeing a similar problem, but it doesn't seem to matter if I've changed "view: all".

I'm a new user, so my expectations may be wrong, but when I right-click a folder and click "remove" my expectation is that it will to remove all photos in that folder (and any of its subfolders). Most of the time the folder is removed from the folder list but the photos remain in the library. Restarting darktable causes the folder to reappear.

For now I'm avoiding the "remove" on folders entirely since it's so unpredictable when it will work. Instead I double-click the folder I wish to remove, use `Ctrl-a` to select all, then `Remove` in the "selected images[s]" pane. Once all the photos are gone the folder is (automatically) removed from the folder list correctly.

**Comment by ptilopteri** [comment] 2021-03-07 20:34
"remove" pertains to the COLLECTION, not file-system.  "delete" pertains to a permanent alteration
of the file/file-system.

if this satisfactorily explains your question, please close this issue.

**Comment by AlicVB** [comment] 2021-03-07 20:57
I can't reproduce the issue as described by @maclaw13. considering the date of the report and the amount of changes in this area. I think that it has been fixed, so I'm closing. Don't hesitate to reopen or ask for it if you are still able to reproduce.

@pfheatwole : your issue seems completely different. Can you open a new issue with all the required field so we can have a look and try to find what happen ? thanks !

**Closed by AlicVB** 2021-03-07 20:57 UTC
Labels: no-issue-activity

**Comment by pfheatwole** [comment] 2021-03-07 22:04
@ptilopteri Yes, that part works as expected, but thanks all the same. I'm not trying to delete files from the filesystem, I'm removing them from the darktable library.

@AlicVB Done: https://github.com/darktable-org/darktable/issues/8433  Thanks!
