### ISSUE TITLE
Significant slowdown when filtering for tags in the collection module

### ISSUE THREAD

**Issue by fgtham** [darktable-org/darktable#15288] opened 2023-09-21 10:51 UTC
### Describe the bug

I have some generic tags applied to a large number of images. Using the collection module to filter for these tags obviously leads to result sets with a large number of elements. Until now, I had no problems working with these collection filters. However, a recent change introduced a significant performance degradation: with my setup, any filter search for tags that result in about 150 images or more will make darktable go completely unresponsive for the next 10 seconds or more.

### Steps to reproduce

1. In lighttable view, filter the collection for a single tag. The tag should be assigned to a largeish number of images (with my hardware, approx. 150 matching images will be sufficient).
2. Darktable will become completely unresponsive for the next couple of seconds.

### Expected behavior

Darktable should display the filtered collection without noticeable delay.

### Logfile | Screenshot | Screencast

```
darktable -d sql
...
     0,2704 [sql] /home/flo/src/darktable/src/common/collection.c:189, function dt_collection_memory_update(): prepare "INSERT INTO memory.collected_images (imgid) SELECT DISTINCT mi.id FROM (SELECT mi.id, group_id, film_id, filename, datetime_taken,               flags, version,  position, aspect_ratio,              cm.maker || ' ' || cm.model AS camera,              mk.name AS maker, md.name AS model, ln.name AS lens,              aperture, exposure, focal_length,              iso, import_timestamp, change_timestamp,              export_timestamp, print_timestamp       FROM main.images AS mi, main.makers AS mk, main.cameras AS cm,            main.models AS md, main.lens AS ln               WHERE mi.maker_id = mk.id         AND mi.model_id = md.id         AND mi.lens_id = ln.id         AND mi.camera_id = cm.id      ) AS mi WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'urlaub')))) AND ( 1=1 AND (1=1) AND 1=1)) AND (group_id = 0 OR mi.id IN (SELECT id FROM (SELECT id,        MIN(ABS(id-group_id)*2 + CASE WHEN (id-group_id) < 0 THEN 1 ELSE 0 END) FROM main.images WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'urlaub')))) AND ( 1=1 AND (1=1) AND 1=1)) GROUP BY group_id))) OR (id = 0) ORDER BY filename, version LIMIT ?1, ?2"
     4,5273 [sql] /home/flo/src/darktable/src/develop/imageop.c:1390, function _init_presets(): prepare "SELECT name, op_version, op_params, blendop_version, blendop_params FROM data.presets WHERE operation = ?1" 
...
     5,1417 [sql] /home/flo/src/darktable/src/common/collection.c:1012, function _dt_collection_compute_count(): prepare "SELECT COUNT(DISTINCT mi.id) FROM (SELECT mi.id, group_id, film_id, filename, datetime_taken,               flags, version,  position, aspect_ratio,              cm.maker || ' ' || cm.model AS camera,              mk.name AS maker, md.name AS model, ln.name AS lens,              aperture, exposure, focal_length,              iso, import_timestamp, change_timestamp,              export_timestamp, print_timestamp       FROM main.images AS mi, main.makers AS mk, main.cameras AS cm,            main.models AS md, main.lens AS ln               WHERE mi.maker_id = mk.id         AND mi.model_id = md.id         AND mi.lens_id = ln.id         AND mi.camera_id = cm.id      ) AS mi WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'ereignis|urlaub|odenwald 2023')))) AND ( 1=1 AND (1=1) AND 1=1)) AND (group_id = 0 OR mi.id IN (SELECT id FROM (SELECT id,        MIN(ABS(id-group_id)*2 + CASE WHEN (id-group_id) < 0 THEN 1 ELSE 0 END) FROM main.images WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'urlaub')))) AND ( 1=1 AND (1=1) AND 1=1)) GROUP BY group_id))) OR (id = 0) ORDER BY filename, version LIMIT ?1, ?2"
     9,4099 [sql] /home/flo/src/darktable/src/dtgtk/thumbtable.c:2198, function dt_thumbtable_full_redraw(): prepare "SELECT rowid, imgid FROM memory.collected_images WHERE rowid>=1 LIMIT 25"
...
```
### Commit

e8a171f032

### Where did you install darktable from?

github

### darktable version

current master

### What OS are you using?

Linux

### What is the version of your OS?

Gentoo

### Are you using OpenCL GPU in darktable?

Yes

### Please provide additional context if applicable. You can attach files too, but might need to rename to .txt or .zip

Reverting the change from `id` to `mi.id` in e8a171f032 in just this single line below works around the issue for me:

```
diff --git a/src/common/collection.c b/src/common/collection.c
index f721b830ef..9b5221d43e 100644
--- a/src/common/collection.c
+++ b/src/common/collection.c
@@ -1701,7 +1701,7 @@ static gchar *get_query_string(const dt_collection_properties_t property, const
           // default
           // clang-format off
           query = g_strdup_printf
-            ("(mi.id IN (SELECT imgid FROM main.tagged_images"
+            ("(id IN (SELECT imgid FROM main.tagged_images"
              "           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE '%s')))",
              escaped_text);
           // clang-format on
```

Obviously, this is not a fix, but it may help digging into the issue.

**Comment by TurboGit** [comment] 2023-09-21 12:06
This looks like a fix to me. But @AlicVB is working on a clean-up of this part as there is at least two issues (wrong SQL queries) we have identified. This will get fixed as part of this work. @AlicVB : if you prefer I can revert just this part now, let me know.

**Comment by fgtham** [comment] 2023-09-21 12:21
Not sure if it's a fix: calling darktable from the shell gives me the following:

```
sqlite3 error: /home/flo/src/darktable/src/libs/filters/rating_range.c:49, function _rating_range_update(), query "SELECT CASE WHEN (flags & 8) == 8 THEN -1 ELSE (flags & 7) END AS rating, COUNT(*) AS count, mk.name AS maker, md.name AS model, ln.name AS lens, cm.maker || ' ' || cm.model AS camera FROM main.images AS mi, main.makers AS mk, main.models AS md, main.lens AS ln, main.cameras AS cm WHERE mi.maker_id = mk.id   AND mi.model_id = md.id   AND mi.lens_id = ln.id   AND mi.camera_id = cm.id   AND ( (id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'ereignis|urlaub|odenwald 2023')))) GROUP BY rating ORDER BY rating": ambiguous column name: id
```

I run the query in sqlite:

```
$ sqlite3 path/to/library.db
@sqlite> SELECT CASE WHEN (flags & 8) == 8 THEN -1 ELSE (flags & 7) END AS rating, COUNT(*) AS count, mk.name AS maker, md.name AS model, ln.name AS lens, cm.maker || ' ' || cm.model AS camera FROM main.images AS mi, main.makers AS mk, main.models AS md, main.lens AS ln, main.cameras AS cm WHERE mi.maker_id = mk.id   AND mi.model_id = md.id   AND mi.lens_id = ln.id   AND mi.camera_id = cm.id   AND ( (id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'urlaub')))) GROUP BY rating ORDER BY rating;
Parse error: no such table: data.tags

// need to replace `SELECT id FROM data.tags WHERE name LIKE 'urlaub'` with the corresponding ID from data.db:

@sqlite> SELECT CASE WHEN (flags & 8) == 8 THEN -1 ELSE (flags & 7) END AS rating, COUNT(*) AS count, mk.name AS maker, md.name AS model, ln.name AS lens, cm.maker || ' ' || cm.model AS camera FROM main.images AS mi, main.makers AS mk, main.models AS md, main.lens AS ln, main.cameras AS cm WHERE mi.maker_id = mk.id   AND mi.model_id = md.id   AND mi.lens_id = ln.id   AND mi.camera_id = cm.id   AND ( (id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (411)))) GROUP BY rating ORDER BY rating;
Parse error: ambiguous column name: id
  ns_id = ln.id   AND mi.camera_id = cm.id   AND ( (id IN (SELECT imgid FROM mai
                                      error here ---^
```

As I understand it, my partial revert leads to a broken SQL query that does not get executed at all. Hence, great performance.  e8a171f032 actually fixes the query:

```
@sqlite> SELECT CASE WHEN (flags & 8) == 8 THEN -1 ELSE (flags & 7) END AS rating, COUNT(*) AS count, mk.name AS maker, md.name AS model, ln.name AS lens, cm.maker || ' ' || cm.model AS camera FROM main.images AS mi, main.makers AS mk, main.models AS md, main.lens AS ln, main.cameras AS cm WHERE mi.maker_id = mk.id   AND mi.model_id = md.id   AND mi.lens_id = ln.id   AND mi.camera_id = cm.id   AND ( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (411)))) GROUP BY rating ORDER BY rating;
0|177|Canon|Canon EOS 200D|Sigma 17-50mm f/2.8 EX DC OS HSM|Canon EOS 200D
1|6|Canon|Canon EOS 200D|Sigma 17-50mm f/2.8 EX DC OS HSM|Canon EOS 200D
2|1|||| 
```

That's why I think it's not a fix to (partially) revert e8a171f032. Instead there might be a problem with the query.

**Comment by TurboGit** [comment] 2023-09-21 12:47
I see, not that simple... Let's wait to @AlicVB proper clean-up then. Thanks for investigating.

**Comment by fgtham** [comment] 2023-09-21 12:51
No problem, let me know if I can help testing etc.

**Comment by AlicVB** [comment] 2023-09-21 18:21
yep, I'm on it. I will propose a fix and clean-up soon (hopefully today or in week-end)

**Comment by AlicVB** [comment] 2023-09-21 20:22
PR #15293 should fix it

**Comment by fgtham** [comment] 2023-09-22 05:55
Timing seems to have improved, but there's still a noticeable delay:

```
     0,2632 [sql] /home/flo/src/darktable/src/common/collection.c:189, function dt_collection_memory_update(): prepare "INSERT INTO memory.collected_images (imgid) SELECT DISTINCT mi.id  FROM (SELECT mi.id, group_id, film_id, filename, datetime_taken,                flags, version,  position, aspect_ratio,               aperture, exposure, focal_length,               iso, import_timestamp, change_timestamp,               export_timestamp, print_timestamp        FROM main.images AS mi                WHERE 1=1) AS mi WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'ereignis|urlaub|odenwald 2023')))) AND ( 1=1 AND (1=1) AND 1=1)) AND (group_id = 0 OR mi.id IN (SELECT id FROM (SELECT id,        MIN(ABS(id-group_id)*2 + CASE WHEN (id-group_id) < 0 THEN 1 ELSE 0 END) FROM main.images WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'urlaub')))) AND ( 1=1 AND (1=1) AND 1=1)) GROUP BY group_id))) OR (id = 0) ORDER BY filename, version LIMIT ?1, ?2"
     2,3837 [sql] /home/flo/src/darktable/src/develop/imageop.c:1390, function _init_presets(): prepare "SELECT name, op_version, op_params, blendop_version, blendop_params FROM data.presets WHERE operation = ?1"
...
    14,5420 [sql] /home/flo/src/darktable/src/common/collection.c:854, function _dt_collection_compute_count(): prepare "SELECT COUNT(DISTINCT mi.id) FROM (SELECT mi.id, group_id, film_id, filename, datetime_taken,                flags, version, CASE WHEN ti.position IS NULL THEN 0 ELSE ti.position END AS position, aspect_ratio,               aperture, exposure, focal_length,               iso, import_timestamp, change_timestamp,               export_timestamp, print_timestamp        FROM main.images AS mi         LEFT JOIN main.tagged_images AS ti                ON ti.imgid = mi.id AND ti.tagid = 435        WHERE 1=1) AS mi WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'ereignis|urlaub|odenwald 2023')))) AND ( 1=1 AND (1=1) AND 1=1)) AND (group_id = 0 OR mi.id IN (SELECT id FROM (SELECT id,        MIN(ABS(id-group_id)*2 + CASE WHEN (id-group_id) < 0 THEN 1 ELSE 0 END) FROM main.images WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'urlaub')))) AND ( 1=1 AND (1=1) AND 1=1)) GROUP BY group_id))) OR (id = 0) ORDER BY filename, version LIMIT ?1, ?2"
    18,7256 [sql] /home/flo/src/darktable/src/common/collection.c:898, function dt_collection_get_collected_count(): prepare "SELECT COUNT(*) FROM memory.collected_images"
```

The more images match the current filter, the longer it takes for darktable to become responsive again. A result set with approx. 800 images would stall the UI for 10 to 15 seconds on my system.

**Comment by fgtham** [comment] 2023-09-22 06:19
Why did you close the bug? The PR improved things a bit, but the UI is still unresponsive?

**Comment by TurboGit** [comment] 2023-09-22 06:51
> Why did you close the bug? The PR improved things a bit, but the UI is still unresponsive?

It was closed automatically when I merged the PR referencing this issue.

**Comment by TurboGit** [comment] 2023-09-22 06:55
What is the setting for collection and filter?

I have just selected a collection based on a tag which has 3484 pictures in it and the result was instantaneous on my side.

**Comment by fgtham** [comment] 2023-09-22 07:19
Just tested this again with 5b8dc54291. In the lighttable view I habe reset the filter. Then I use the collection module on the left side, select "tag" from the "metadata" subsection, then select e.g. the "darktable|exported" tag, which is applied to 659 images. The moment I double-click the tag name, the UI freezes. Here's the corresponding SQL log from the moment I click the tag name until the UI is available again:

```
    28.6677 [sql] /home/flo/src/darktable/src/common/collection.c:176, function dt_collection_memory_update(): exec "DELETE FROM memory.collected_images"
    28.6677 [sql] /home/flo/src/darktable/src/common/collection.c:180, function dt_collection_memory_update(): exec "DELETE FROM memory.sqlite_sequence WHERE name='collected_images'"
    28.6678 [sql] /home/flo/src/darktable/src/common/collection.c:189, function dt_collection_memory_update(): prepare "INSERT INTO memory.collected_images (imgid) SELECT DISTINCT mi.id  FROM (SELECT mi.id, group_id, film_id, filename, datetime_taken,                flags, version, CASE WHEN ti.position IS NULL THEN 0 ELSE ti.position END AS position, aspect_ratio,               aperture, exposure, focal_length,               iso, import_timestamp, change_timestamp,               export_timestamp, print_timestamp        FROM main.images AS mi         LEFT JOIN main.tagged_images AS ti                ON ti.imgid = mi.id AND ti.tagid = 4        WHERE 1=1) AS mi WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'darktable|exported')))) AND ( 1=1 AND 1=1 AND 1=1)) AND (group_id = 0 OR mi.id IN (SELECT id FROM (SELECT id,        MIN(ABS(id-group_id)*2 + CASE WHEN (id-group_id) < 0 THEN 1 ELSE 0 END) FROM main.images WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'darktable|exported')))) AND ( 1=1 AND 1=1 AND 1=1)) GROUP BY group_id))) OR (id = 0) ORDER BY filename, version LIMIT ?1, ?2"
    34.0524 [sql] /home/flo/src/darktable/src/common/collection.c:854, function _dt_collection_compute_count(): prepare "SELECT COUNT(DISTINCT mi.id) FROM (SELECT mi.id, group_id, film_id, filename, datetime_taken,                flags, version, CASE WHEN ti.position IS NULL THEN 0 ELSE ti.position END AS position, aspect_ratio,               aperture, exposure, focal_length,               iso, import_timestamp, change_timestamp,               export_timestamp, print_timestamp        FROM main.images AS mi         LEFT JOIN main.tagged_images AS ti                ON ti.imgid = mi.id AND ti.tagid = 4        WHERE 1=1) AS mi WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'darktable|exported')))) AND ( 1=1 AND 1=1 AND 1=1)) ORDER BY filename, version"    
    34.0535 [sql] /home/flo/src/darktable/src/common/collection.c:885, function dt_collection_get_selected_count(): prepare "SELECT COUNT(*) FROM main.selected_images"
    34.0536 [sql] /home/flo/src/darktable/src/dtgtk/thumbtable.c:232, function _thumb_get_imgid(): prepare "SELECT imgid FROM memory.collected_images WHERE rowid=1"
...
    34.0887 [sql] /home/flo/src/darktable/src/libs/filters/rating_range.c:49, function _rating_range_update(): prepare "SELECT CASE WHEN (flags & 8) == 8 THEN -1 ELSE (flags & 7) END AS rating, COUNT(*) AS count, mk.name AS maker, md.name AS model, ln.name AS lens, cm.maker || ' ' || cm.model AS camera FROM main.images AS mi, main.makers AS mk, main.models AS md, main.lens AS ln, main.cameras AS cm WHERE mi.maker_id = mk.id   AND mi.model_id = md.id   AND mi.lens_id = ln.id   AND mi.camera_id = cm.id   AND ( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'darktable|exported')))) GROUP BY rating ORDER BY rating"
    34.0918 [sql] /home/flo/src/darktable/src/libs/duplicate.c:271, function _lib_duplicate_init_callback(): prepare "SELECT i.version, i.id, m.value FROM images AS i LEFT JOIN meta_data AS m ON m.id = i.id AND m.key = ?3 WHERE film_id = ?1 AND filename = ?2 ORDER BY i.version"
    34.1886 [sql] /home/flo/src/darktable/src/common/collection.c:854, function _dt_collection_compute_count(): prepare "SELECT COUNT(DISTINCT mi.id) FROM (SELECT mi.id, group_id, film_id, filename, datetime_taken,                flags, version, CASE WHEN ti.position IS NULL THEN 0 ELSE ti.position END AS position, aspect_ratio,               aperture, exposure, focal_length,               iso, import_timestamp, change_timestamp,               export_timestamp, print_timestamp        FROM main.images AS mi         LEFT JOIN main.tagged_images AS ti                ON ti.imgid = mi.id AND ti.tagid = 4        WHERE 1=1) AS mi WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'darktable|exported')))) AND ( 1=1 AND 1=1 AND 1=1)) AND (group_id = 0 OR mi.id IN (SELECT id FROM (SELECT id,        MIN(ABS(id-group_id)*2 + CASE WHEN (id-group_id) < 0 THEN 1 ELSE 0 END) FROM main.images WHERE   (flags & 256) != 256  AND  (( (mi.id IN (SELECT imgid FROM main.tagged_images           WHERE tagid IN (SELECT id FROM data.tags WHERE name LIKE 'darktable|exported')))) AND ( 1=1 AND 1=1 AND 1=1)) GROUP BY group_id))) OR (id = 0) ORDER BY filename, version LIMIT ?1, ?2"
    41.5541 [sql] /home/flo/src/darktable/src/common/film.c:544, function dt_film_set_folder_status(): prepare "DELETE FROM memory.film_folder"
    41.5541 [sql] /home/flo/src/darktable/src/common/film.c:550, function dt_film_set_folder_status(): prepare "SELECT id, folder FROM main.film_rolls"
    41.5542 [sql] /home/flo/src/darktable/src/common/film.c:555, function dt_film_set_folder_status(): prepare "INSERT INTO memory.film_folder (id, status) VALUES (?1, ?2)"
```

All in all it took the UI 13 seconds to become responsive again.

I have an AMD Ryzen 5 5600G CPU, 32 GB of RAM, and an NVIDIA GeForce RTX 3060 GPU with 12 GB RAM, so I assume that the hardware is not the problem.

**Comment by TurboGit** [comment] 2023-09-22 07:42
Reproduced and fixed, see #15298. Can you test and report if it is ok on your side? TIA.

**Comment by fgtham** [comment] 2023-09-22 08:09
Looks good, I cannot reproduce the problem any longer. Thank you!

**Comment by TurboGit** [comment] 2023-09-22 10:57
Fix merged then, thanks for testing.

**Closed** 2023-09-22 10:57 UTC
Labels: priority: high, scope: UI, scope: DAM, bug: pending
