### ISSUE TITLE
Darktable hang on exporting extremely large image as JPEG

### ISSUE THREAD

**Issue by JosephPatenaude** [darktable-org/darktable#17643] opened 2024-10-12 01:41 UTC
### Describe the bug

I am attempting to export an edited 16 bit TIFF (~1GB) as an 85% JPEG.  The export gets stuck on "exporting 1/1 to file on disk".  I attempted restarting my Mac, reinstalling Darktable (I was already running the most recent version).  I was able to export an unedited TIFF on Photomator as an 85% JPEG with no issues.  I have used Darktable to export countless other images without issue, granted this is the largest export I've attempted.  I am running a 2021 MB Pro with 16GB RAM.

### Steps to reproduce

1. Open TIFF
2. Export as 85% JPEG (or any quality, I attempted a 5% quality and it still didn't work)
3. Darktable gets hung up on "exporting 1/1 to file disk"

### Expected behavior

Export TIFF as JPEG

### Where did you obtain darktable from?

downloaded from www.darktable.org

### darktable version

4.8.1

### What OS are you using?

Mac

### What is the version of your OS?

14.4.1 (23E224)

### Are you using OpenCL GPU in darktable?

No

**Comment by pehar1** [comment] 2024-10-12 15:51
Did not download the image because of it's size. Maybe you have a memory problem with this image size ? To verify this you should start darktable in debug mode to get a logging : see https://www.darktable.org/about/faq/#faq-windows-logs

**Comment by zisoft** [comment] 2024-10-12 16:34
The export of the image takes 6min on my Intel MacBook Pro 16 (2019).
Exported image is 27648 × 7009 pixels, 35,1 MB (jpeg 85%).

**Comment by jenshannoschwalm** [comment] 2024-10-13 04:56
On a 16GB machine there is **very** heavy tiling plus the memory load for "stitching" the tiles.

A short reminder @zisoft we have `darktable --conf resourcelevel="notebook"` as an option to test such cases. See https://darktable-org.github.io/dtdocs/en/special-topics/mem-performance/ 

@JosephPatenaude I am very interested in a log - if possible running latest master. `-d pipe -d opencl` would be sufficient to see if processing modules happen without OpenCL fallbacks.

**Comment by JosephPatenaude** [comment] 2024-10-15 20:41
[darktable_debug_log.txt](https://github.com/user-attachments/files/17384808/darktable_debug_log.txt)
@jenshannoschwalm I have attached a debug log.  Is this what you're looking for?  I'm not very technically knowledgeable in this area so let me know if you need something different.

Attempting to reproduce the issue, the export did actually complete this time.  Perhaps I underestimated how demanding the export would be.

**Comment by jenshannoschwalm** [comment] 2024-10-15 21:01
I think it was an underestimation :-) If it completes at all that would be good enough for me. The most demanding stuff are the diffuse modules .,.

**Comment by jenshannoschwalm** [comment] 2024-10-16 04:02
Closing this issue for now as "not a bug"

**Closed by jenshannoschwalm** 2024-10-16 04:02 UTC
Labels: scope: image processing
