### ISSUE TITLE
Orientation Wrong After DT 3.4.0 Upgrade

### ISSUE THREAD

**Issue by Spectre5** [darktable-org/darktable#7746] opened 2021-01-08 06:58 UTC
**Describe the bug**
I have a set of JPG images that I did some minor edits to with DT a few years ago, one of which was changing the orientation of many of the images by 90 degrees using the "orientation" module.  Now when I import this JPG+XMP into DT 3.4.0, the image is rotated 90 degrees the *other* direction from the DT 2.6.0 edit, so the result is that the image is 180 degrees different (flipped upside down).

**To Reproduce (images at the end)**
1. The original file from the camera is `DSCF1230.JPG`
2. The original xmp is `DSCF1230.xmp` which output with DT 2.6.0 the file `DSCF1230_Output_DT2.6.0.jpg`.  The JPG metadata shows that it was edited with DT 2.6.0, but it is possible (likely?) that the xmp was saved again with a later version using the "write sidecar files" from lighttable.  The image was certainly never opened again in darkroom, so no edit was made after the output jpg was produced.
3. Now when I import the original image and xmp in DT 3.4.0, I get the `DSCF1230_Output_DT3.4.0.jpg` result and the xmp text gets changed/updated to the text in the `DSCF1230_DT3.4.0.xmp` file).  As you can see, the image is flipped.  This change happens immediately, even without opening the file in Darkroom.

**Expected behavior**
I should get the same orientation that I got when I first edited it with DT 2.6.0.

**Screenshots**
See attached files.

**Platform (please complete the following information):**
 - Darktable Version: 2.6.0 (original edit), 3.4.0 shows the issue
 - OS: Ubuntu 20.04
 - OpenCL *not* activated
 - GeForce GTX 650 Ti BOOST/PCIe/SSE2 with "nvidia-driver-450 (proprietary)"

**Additional context**
Due to my issue in #6702, I skipped DT 3.2.0 and I started DT 3.4.0 with a brand new library.  I removed the entire ~/.config/darktable directory to  be sure I started completely clean with DT 3.4.0 and then imported my entire library from the XMP files.  After quickly scanning the library, it appears that this is the only set of images where I have this problem.  This is, however, the only set of images that I have from this camera and I only have 1 other set of JPG images from a different camera, which does not have this issue.  So this may be something related to camera detection or reading the camera metadata different now...

**Original (from camera)**
![DSCF1230](https://user-images.githubusercontent.com/31610422/103983886-f4af1500-513a-11eb-8925-b50c57fc2754.JPG)

**DT 2.6.0 output**
[DSCF1230.xmp.txt](https://github.com/darktable-org/darktable/files/5785651/DSCF1230.xmp.txt)
![DSCF1230_Output_DT2 6 0](https://user-images.githubusercontent.com/31610422/103983922-0a243f00-513b-11eb-8463-41753bbf913a.jpg)

**DT 3.4.0 output**
This XMP is the result of importing the *original* image with the XMP above used to create the DT 2.6.0 output.
[DSCF1230_DT3.4.0.xmp.txt](https://github.com/darktable-org/darktable/files/5785652/DSCF1230_DT3.4.0.xmp.txt)
![DSCF1230_Output_DT3 4 0](https://user-images.githubusercontent.com/31610422/103983939-114b4d00-513b-11eb-8049-221322af2b5e.jpg)

**Comment by parafin** [comment] 2021-01-08 09:36
I believe this is a duplicate of #3545, which unfortunately isn't recoverable (you have to correct rotation manually).

**Comment by johnny-bit** [comment] 2021-01-08 09:48
This is indeed unfortunate but it's most likely not a "won't fix" but "can't fix". All connected issues are closed as duplicates... Indeed the only fix is manual and current way the orientation is handled is more stable.

**Closed by johnny-bit** 2021-01-08 09:48 UTC

**Comment by Spectre5** [comment] 2021-01-08 09:53
Ok, thanks for the heads up.  I tried searching for the bug to see if it was already reported, but I missed that previous issue!

**Comment by Spectre5** [comment] 2021-01-09 08:25
I'm fairly certain that I'd used the orientation module in the past (~DT 2.6.0) on other images too, but this set of images is the only on I see this issue with (so far since I haven't looked at my entire library).  Is it know what specific factors would cause this issue, e.g. specific camera model or manufacturer, etc?  >90% of my images are canon CR2 raw files.

**Comment by TurboGit** [comment] 2021-01-09 09:34
I don't remember all the details. The issue was that for some orientations (depending on how the camera was handled) the information was wrongly used by dt. This has been fixed with a set of image with all possible orientations so we are fairly confident that the current behavior is correct. You may want to look for an issue or PR here.

**Comment by TurboGit** [comment] 2021-01-09 09:36
Found see #2296.
