### ISSUE TITLE
[Contrast Equalizer] settings apply differently when crop size is changed

### ISSUE THREAD

**Issue by Clind99** [darktable-org/darktable#4552] opened 2020-03-25 19:06 UTC
SUMMARY
When using the contrast equalizer and changing the image size via the crop module, specified frequencies settings get "shifted" from the content of the image point of view ...

THE PROBLEM
The current version behaviour produce the following effect : changing the crop size setting when using the contrast equalizer will change the way the part of the image still present after the new crop look when compared to the same areas of the image before the new crop.

STEPS TO REPRODUCE 
1 : Use the contrast equalizer (tone and/or luma)
2 : crop or change crop settings applied to the image
3 : Contrast equalizer affect differently the content of the image.

EXPECTED BEHAVIOUR & THOUGHTS 
I've been bothered by this behaviour several time and have a tendancy to think that the equalizer frequency should keep to the original image size as reference, but I realise that people processing high megapixel count images may work on heavily cropped images and the effect of keeping the original image size as a base reference would make the frequency scale of the module interface less relevant and less convenient for them in that case. Maybe whether to base the "Contrast Equalizer" frequency scale on the original or crop size of the image should be a checkable option ?

I hope This explanation is not too confusing, thanks for your excellent work !

**Comment by johnny-bit** [comment] 2020-12-31 19:32
I tried to reproduce on multiple images with just crop&rot and contrast equalizer and i REALLY can't find that much of a difference to consider it "negligible".

At first I thought you meant controlls of contrast equalizer shift depending on crop, but that's not the case.
I also tried overbaking the settings and then try enabling/disabling crop to see changes but really - the changes are (at least in current master) absolutelly miniscule (if even present).

Overall I doubt this something to be bothered about ;)

I'm closing this since I "can't replicate" but if you can - please provide screenshots and sample files + xmps on which problem is visible and I'll re-open the issue ASAP!

**Closed by johnny-bit** 2020-12-31 19:32 UTC
Labels: no-issue-activity
