### ISSUE TITLE
DNG: File unavailable / allocation failed???

### ISSUE THREAD

**Issue by bvb-sc** [darktable-org/darktable#5920] opened 2020-08-11 13:17 UTC
**Describe the bug**
Opening certain .dng files in Darktable, or converting certain .dng files with Darktable-cli, results in errors.

Error Message UI:
![image](https://user-images.githubusercontent.com/67702686/89892486-049bea80-dbd7-11ea-9f30-ed7b19da27c3.png)

Error Message CLI:

```
darktable-cli "<file>.dng" "<file>.png" --verbose

(darktable-cli:44888): Gtk-WARNING **: 13:33:29.311: gtk_disable_setlocale() must be called before gtk_init()
[empty history stack]
allocation failed???
[imageio_storage_disk] could not export to file: `<file>.png'!
```

**To Reproduce**
Sample file: https://bvbpublicstorage.blob.core.windows.net/public/DR6A0013.dng?sp=r&st=2020-08-11T12:21:04Z&se=2021-01-01T21:21:04Z&spr=https&sv=2019-12-12&sr=b&sig=XZ2HuO3q6baaAmGojiPIV7uKZzyd9HgUgddnAp7GVOE%3D

UI:
- Open the sample file in Darktable
- Notice error message

CLI:
- Run command `darktable-cli "<file>.dng" "<file>.png" --verbose`
- Notice error message

**Expected behavior**
UI: I expect the file to open, similarly to other .dng files
CLU: I expect the file to convert from .dng to .png, similarly to other .dng files

**Platform**
 - Darktable Version: 3.0.2
 - OS: Windows 10
 - No OpenCL
 - Intel UHD Graphics 6.30 (Driver: 25.20.100.6472)

**Platform**
 - Darktable Version: 3.0.1-0ubuntu1
 - OS: Linux Ubuntu 20.04
 - No OpenCL
 - /

**Comment by jenshannoschwalm** [comment] 2020-08-12 11:09
The referenced file is a dual-pixel image, dt unfortunately does not support such files yet because of rawspeed.
There have been some attempts to solve this but ...

**Comment by johnny-bit** [comment] 2021-06-08 11:43
Duplicate of #4006

(i wonder though how dual pixel stuff should look/work)

**Closed by johnny-bit** 2021-06-08 11:43 UTC
Labels: no-issue-activity
