### ISSUE TITLE
Recursive Folder Regression - 3.6.1+6~g4bc866924

### ISSUE THREAD

**Issue by naisanzaa** [darktable-org/darktable#10666] opened 2021-12-22 10:36 UTC
**Describe the bug/issue**
Recursive import is bad when importing from the cloud. 

The previous behavior does not try to list out every file recursively; and that worked exactly how I needed it.

E.g. 

* Enabling recursive import on a folder with 40k images, nested, nested, nested, nested folder structure (`path/to/folder/sorted/year/month/day`)
* takes several minutes to list, before you can begin importing 

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Open
2. Import 
3. Select recursive 

**Expected behavior**
Don't enumerate the list of files recursively (it's too slow)  

**Platform**

* darktable version : 3.6.1+6~g4bc866924
* OS                : OSx (installed via brew cask, https://github.com/TheShellLand/antsable/tree/master/playbooks/roles/darktable)
* Memory            :  16GB

**Comment by elstoc** [comment] 2021-12-22 13:15
It's not clear what darktable version you are using - the title says "v3.6.1+6" (I'm not sure what that means) and the Platform section says "e.g. 3.5.0+250~gee17c5dcc" which I presume is a leftover from the issue template.

**Comment by Nilvus** [comment] 2021-12-22 16:42
And another thing, on my side (actual master and so 3.8 which will be release in 2-3 days, I have a recursive option to select or not at the top of the import window. Just uncheck it. I often find it better to see files recursively but of course, with 40k images, it's better to not check that option!

**Comment by naisanzaa** [comment] 2021-12-22 18:18
> It's not clear what darktable version you are using - the title says "v3.6.1+6" (I'm not sure what that means) and the Platform section says "e.g. 3.5.0+250~gee17c5dcc" which I presume is a leftover from the issue template.

updated

**Comment by naisanzaa** [comment] 2021-12-22 18:22
> And another thing, on my side (actual master and so 3.8 which will be released in 2-3 days), I have a recursive option to select or not at the top of the import window. Just uncheck it. I can't remember if this option was here in 3.6.1 or implemented since. I often find it better to see files recursively but of course, with 40k images, it's better to not check that option!

I'm running the brew cask version of darktable. Let me upgrade it actually.

But I do want it to import recursively. 

(also a new issue with this version, I can't uncheck the recursive until it finishes its recursion. So I'm just looking at a spinning beachball for 20 minutes)

**Comment by naisanzaa** [comment] 2021-12-22 18:27
Looks like 3.6.1.6 is the latest version from brew

**Comment by Nilvus** [comment] 2021-12-22 18:32
@phweyland: as you work on that, some ideas here?

**Comment by naisanzaa** [comment] 2021-12-22 18:32
> with 40k images, it's better to not check that option!

With the previous version, it worked perfectly. 

* select a folder
* select recursive
* import 

Now. 

* select a folder
* select recursive
* wait an hour until it recurses through every file (because it wants to list out all the files)
* import 

That's the major difference. Before, it worked better. Now, it's IO bound. And it completely locks up the application until it's finished listing every file.

AND. the best part is. You can't uncheck `recursive mode` until it finishes resursing  

![image](https://user-images.githubusercontent.com/58240560/147139033-9b8a5285-c086-4d06-b2d1-b0fabd9ded05.png)

**Comment by Nilvus** [comment] 2021-12-22 18:36
> Before, it worked better. Now, it's IO bound. And it completely locks up the application until it's finished listing every file.

Keep cool. There's no so much people to try to import (or even list so much images at same time). So this probably had never been tested before you. New import UI is much better than previous one.

I personally never had issue like that with this new import dialog window for example. I never just never list/import more than 2k images at the same time. And it's probably something near 99% people using darktable.

**Comment by naisanzaa** [comment] 2021-12-22 18:49
> I personally never had issue like that with this new import dialog window for example. I never just never list/import more than 2k images at the same time. And it's probably something near 99% people using darktable.

True. 

I'm trying to have Darktable be the main way I organize my library with tagging and importing GPX.

I'm trying out a cloud-first workflow. Google Drive's handling of caching makes it possible to just import everything.

For example, if I restructure my pictures. I would:
* delete `~/.config/darktable` 
* and just reimport the entire library. 

Instead of searching and removing individual pictures from Darktable. It's easier to just reimport the entire library.

**Comment by phweyland** [comment] 2021-12-22 20:18
The new import process is not the best to import blindly a large set of images. Agreed.

> Instead of searching and removing individual pictures from Darktable. It's easier to just reimport the entire library.

I don't understand what you mean. Could you describe a bit more the workflow ?
How do you actually remove images ?

**Comment by naisanzaa** [comment] 2021-12-22 22:06
quoting from https://github.com/darktable-org/darktable/issues/10668

> That's what is expected when `recursive` is set, anyway... even with the previous version.

Not in one of the previous versions. Before this new function was added. 

You could browse to the folder, and it would just list the folder like a normal file browser.

When you select `recursive`, it's just a toggle. 

With the new import browser, it wants to check if a picture has already been imported. Which I guess is nice. 

But if that's to improve the import process by reducing the number of files to import. All of that speed gained is neglected by the amount of time it's taking just to enumerate the files to import.

**Comment by naisanzaa** [comment] 2021-12-22 22:08
> The new import process is not the best to import blindly a large set of images. Agreed.

Actually, it worked perfectly before. That's how I was importing my entire library. And it worked perfectly.

**Comment by naisanzaa** [comment] 2021-12-22 22:18
> I don't understand what you mean. Could you describe a bit more the workflow ? How do you actually remove images ?

So this issue https://github.com/darktable-org/darktable/issues/10115 is still open, which breaks my workflow of being able to use Darktable to move files (all files that's moved by Darktable loses the file timestamps, and this breaks a lot of cloud platforms that uses the file timestamp, instead of the EXIF data)

Besides that. 

My workflow is:

* organize and structure files on the filesystem 
* import all files into darktable
* use darktable to tag and apply gpx
* use darktable to bulk export images

This is made possible because of the sidecar file Darktable uses, so the original file isn't modified (although it would be nice if Darktable could modify the files directly while preserving all timestamps)

If I've reorganized the files a lot, I would just delete the Darktable database and reimport the entire Library.

If I've only made a few changes, and I'm able to quickly find which pictures to delete out of Darktable, I'll do that; and reimport the folder. 

E.g. 

If I'm reorganizing images tagged with `2021`, I know in Darktable, I can just filter for tag `2021` and delete all of those.

**Comment by phweyland** [comment] 2021-12-23 15:29
Thanks. Understood. 
This said, it's a unusual use case and doesn't justify the name of "regression".
To treat this use case, the option "recursively blind" should be added. Then the interface would not show the files list. The files enumeration would happen anyway but in the background.

**Comment by elstoc** [comment] 2021-12-23 17:23
A more generic option of "show files" might be better. If not selected this would just import the entire selected directory including folder recursion if required (i.e. act just like the previous "import folder" option).

**Comment by naisanzaa** [comment] 2021-12-24 00:36
> the interface would not show the files list. The files enumeration would happen anyway but in the background.

I like this better.

Adding a dedicated `recursively blind` option is excessive to the UI.

If I can:

* enable recursive
* files enumeration always happens in the background
* can still navigate to other folders
* stop, and re-enumerate on the new selected folder

This would satisfy my use case, as well as keeping the interface responsive.

**Comment by elstoc** [comment] 2021-12-24 11:09
The problem is that afaik the list of files to be imported is taken from the selection on the right hand pane, so you wouldn't be able to import until the pane finished populating.

**Comment by AlicVB** [comment] 2021-12-24 12:11
My 2 cents...

imho, the real issue is more that the file listing block completely the UI, which will cause issues sooner or later, whatever the number of files (we can also have the same problem, with a "big" folder and a very slow IO rate)

What I would propose is more : 
1. ensure that we don't block the UI during the file listing (a little bit like for lighttable during the next import step)
2. give the user some feedback that something happen (by filling the file list on the fly for example)
3. during the listing, show a button " stop the file listing"
4. if that button has been clicked, change the whole last line (select all, ...) by some warning like "all the files will be imported"
5. then if the user click on the import button : first finish the listing and then import... but all that in the background "real" import process

we can also imagine that 2 and 3 is done in a "waiting popup window" (even if I'm not a great fan of that)

of course, I perfectly know that it's easy to come with such design but lot more complex to implement... I know that non-blocking UI is quite complex with gtk...

**Comment by phweyland** [comment] 2021-12-24 12:12
There are in fact two different topics.
The @naisanzaa suggestion solves the issue of not being able to abort an unwanted long recursive enumeration. This is a general issue as this can happen to anybody by mistake. This is clearly possible but I haven't found any easy solution so far.
@elstoc is right. The fact to have to wait to start actual importation is another subject. That's the `recursively blind` or `show files` option. The treatment is also completely different.

**Comment by phweyland** [comment] 2021-12-24 12:15
> then if the user click on the import button : first finish the listing and then import... but all that in the background "real" import process

yaahhh... a bit more complexity ! :smile:

**Comment by naisanzaa** [comment] 2021-12-24 18:09
> imho, the real issue is more that the file listing block completely the UI, which will cause issues sooner or later, whatever the number of files (we can also have the same problem, with a "big" folder and a very slow IO rate)

Exactly.

**Comment by naisanzaa** [comment] 2021-12-24 19:17
> That's the `recursively blind` or `show files` option. 

How about a combination of how it worked before, with the new one?

When `recursive` is enabled:
* show the files in the selected folder
* show a notice it is "grabbing all files"
* enumerate the files in the background

If the file enumeration is not complete, and the user clicks `import`
* treat as a `recursive blind`

**Comment by phweyland** [comment] 2021-12-24 19:31
That's what @AlicVB was suggesting if I'm not mistaken.

**Comment by naisanzaa** [comment] 2021-12-24 21:22
> That's what @AlicVB was suggesting if I'm not mistaken.

More of less yea. But with less user-required inputs 

E.g. 

* without having to click a button `stop the file listing`
* before clicking `import`

My idea just says you can click `import` anytime you want

* with `recursive` enabled, you already expect everything to be recursed 
* you won't think it's only going to import shown files

**Comment by elstoc** [comment] 2021-12-24 21:35
> with recursive enabled, you already expect everything to be recursed

The dialog allows you to manually deselect images, even when recursing, so I'm not sure this expectation is true for everyone

**Comment by naisanzaa** [comment] 2021-12-24 22:25
> The dialog allows you to manually deselect images, even when recursing

I suppose for blind recursive imports it does

**Comment by audiofish** [comment] 2022-11-08 22:03
Issue affects me too--35K images stored on a NAS and darktable becomes unresponsive for ~1hr when clicking import.

**Comment by ralfbrown** [comment] 2024-01-12 06:05
This should have been fixed by #15894 and #16074.  if not, feel free to re-open this issue or open a new one.

**Closed by ralfbrown** 2024-01-12 06:05 UTC
Labels: feature: enhancement, scope: UI, scope: performance, no-issue-activity
