### ISSUE TITLE
Ratings tools not visible on top-bottom of the lighttable

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/darktable#4850] opened 2020-04-28 17:39 UTC
**Describe the bug**

Ratings tools not visible on top-bottom of the lighttable.

**To Reproduce**

1. Go to lighttable

**Expected behavior**
Stars should be visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/467069/80519081-b7796d00-8987-11ea-9112-dfa70e80ca64.png)

It seems that there are present as I see a white point, but all compressed! A CSS issue ?

**Platform (please complete the following information):**
 - Darktable Version: master
 - OS: Debian

**Comment by AlicVB** [comment] 2020-04-28 19:31
confirmed.
@Nilvus : I think the problem is commit bef0263b521a1c1512bbf3e73e63841e222f8227 especially the part about #lib-rating-stars was the culprit. It seems that it wasn't the stars inside thumbs...
if you don't have time, I can propose a PR

**Comment by Nilvus** [comment] 2020-04-28 19:58
@AlicVB: my mistake so I will done that. I'm actually on CSS things.

Is one of you could assign this issue and also #4836 to me please? Will propose a PR soon to fix those and probably add an update to preferences window CSS part if PR #4851 is merged

**Closed** 2020-04-29 10:41 UTC
